### ISSUE TITLE
Out of space in /data ... is there a cleanup script?

### ISSUE THREAD

**Issue by golimer** [getsentry/self-hosted#1140]
### Version

20.12.1

### Steps to Reproduce

/data# du -hs *
19G	clickhouse
4.0K	code
20K	exim
101M	fluentd
11G	kafka
14M	nginx
29G	postgres
3.3M	redis
220G	sentry    <<<<<<<<   
4.0K	sentry-secrets
24K	symbolicator
1.1M	zookeeper

### Expected Result

any solution how to cleanup?

### Actual Result

cleanup script?

**Comment by chadwhitacre** [comment]
There's gotta be some cleanup advice floating around in the [old forum](https://forum.sentry.io/c/on-premise/7) and possibly otherplaces. What have you googled so far @golimer?
