### ISSUE TITLE
"unknown error (http status: 413)" when uploading sourcemaps

### ISSUE THREAD

**Issue by tommynordli** [getsentry/self-hosted#1142]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 2.1.0

**`react-native` version:** 0.63.4

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [ ]  sentry.io (SaaS)
- [x]  on-premise

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.company.com/...'
});
```

---
**I have following issue:**

After moving our Sentry installation over to self-hosted I haven't been able to upload bundle and sourcemaps. I have completely reinstalled `@sentry/react-native`, gone through the installation steps, run `sentry-wizard`, and made sure my `sentry.properties` looks correct. Also made sure we have no `client_max_body_size` on our server. It's happening on both iOS and Android. 

**Steps to reproduce:**
- Host sentry on-premise
- Follow sentry installation steps
- Build for release

**Actual result:**

```
> Bundled 2 files for upload
error: API request failed
  caused by: sentry reported an error: unknown error (http status: 413)
API request failed

  DEBUG   2020-12-23 11:13:13.573074 +01:00 client close; no transport to shut down  (from sentry)
  DEBUG   2020-12-23 11:13:13.573089 +01:00 skipping update nagger because session is not attended

> Task :app:bundleReleaseJsAndAssets_SentryUpload_310 FAILED
  caused by: sentry reported an error: unknown error (http status: 413)

Execution failed for task ':app:bundleReleaseJsAndAssets_SentryUpload_310'.
> Process 'command '/Users/tommy/Git/noisolation/FamilyFrame/node_modules/@sentry/cli/bin/sentry-cli'' finished with non-zero exit value 1
```

**Expected result:**

Successfully build and uploading bundle and sourcemaps to Sentry

**Comment by chadwhitacre** [comment]
> The source maps are 3.6mb

Can you upload a minimal sourcemap? Something of size 0 or maybe a few bytes? It feels like the 413 is a red herring but this would confirm.

```
error: API request failed
  caused by: sentry reported an error: unknown error (http status: 413)
API request failed
```

Anything in the API server logs that correlates with this?

**Comment by uson1x** [comment]
Seeing the same issue in our on-premise setup. Can't upload our dSYM file, which is 35.6 Mb zipped.

I tried uploading empty zero-bytes file instead, but `sentry-cli` is too smart about that, detecting that it's an empty file 🙂
```
Found 0 debug information files
No debug information files found
No new debug symbols to associate.
```

What else can I do to help fixing this?

@tommynordli have you been able to find a way to upload?

The App Store Connect Custom Repository is also missing for us in the web dashboard menu list, but I don't know if it should be there for on-premise (docs don't mention anything about that).

**Comment by uson1x** [comment]
Yes it was nginx at fault.

Apparently we had two nginx instances: one was external and the other one was inside the Docker image.
Setting `client_max_body_size` to 100m on external nginx resolved this issue.

**Comment by aminvakil** [comment]
> Yes it was nginx at fault.
> 
> Apparently we had two nginx instances: one was external and the other one was inside the Docker image. Setting `client_max_body_size` to 100m on external nginx resolved this issue.

Nice, sentry launches a nginx container by default and its `client_max_body_size`is `100m` as well.

@tommynordli Can you test uploading files to a location other than sentry to verify your nginx on host is configured properly?
