### ISSUE TITLE
Deprecate forum in favor of GitHub Issues

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/self-hosted#1151]
I would like to have a single async channel rather than splitting attention between two. As it stands it's unclear to users where to post what, so we end up with duplicates.

**Comment by chadwhitacre** [comment]
I'm going to let [this forum meta post](https://forum.sentry.io/t/anyone-out-there-self-hosted-community-meta/15559) sit for a few days, if no-one responds I intend to move forward with this ticket, if not then we'll talk first. :)

**Comment by chadwhitacre** [comment]
I'm planning to put a notice at the top of the On-Premise forum tomorrow, and to follow through with the deprecation next week.

**Comment by chadwhitacre** [comment]
Also, I'm really proud of this GIF that I made. 🐭

![embers-of-sentry](https://user-images.githubusercontent.com/134455/142283826-a31a7962-b57b-441d-8e21-08541730c0b0.gif)

**Comment by chadwhitacre** [comment]
> I'm planning to put a notice at the top of the On-Premise forum tomorrow

Done.

https://forum.sentry.io/t/deprecating-the-on-premise-forum-moving-to-github-issues/15587

pinned on

https://forum.sentry.io/c/on-premise/7

**Comment by chadwhitacre** [comment]
Done. Let's see how long we can last before enabling GitHub Discussions. 😅

**Comment by chadwhitacre** [comment]
Reopening for @renchap (https://github.com/getsentry/self-hosted/issues/796#issuecomment-981854733 … and sure @byk, too 😉 https://github.com/getsentry/self-hosted/issues/1175#issuecomment-981935992):

> I suggest moving to Github Discussions, not Issues, as they provide a much better platform for this kind of… discussions, with useful tools like marking topics as solved, accepted answers, threading and such.
> 
> It is easy to convert an issue to a discussion (or the other way around), and it does not clutter the issue tracker with non-issue things, and (if i remember correctly) you can redirect people to open a discussion instead of an issue in the configurable "new issue" page.
> 
> As for the Github are really improving issues and discussions a lot and the OSS community is switching to it quickly, so I assume many people will be familiar with GH Discussions in the coming months and it wont really be an issue.

**Comment by chadwhitacre** [comment]
Thanks for weighing in @renchap.

> I suggest moving to Github Discussions, not Issues

Enabling Discussions is a valid suggestion, and choosing not to rightly requires defending, or at least explaining. :)

Building on [my answer here](https://forum.sentry.io/t/anyone-out-there-self-hosted-community-meta/15559/8), my problem with a forum—whether Discourse or Discussions—is that, at our scale, it is not differentiated enough from Issues to justify the cognitive overhead of maintaining and navigating between two systems.

> useful tools like marking topics as solved, accepted answers

This is easily approximated in Issues with closing an issue, and emoji reactions on comments.

> threading

I see nested vs. flat message boards as largely stylistic, I don't see one as offering a lot of value over another. If Issues were nested I'd be fine with it, but the fact that it's flat and Discussions is nested doesn't sway me.

> and such

?

> It is easy to convert an issue to a discussion (or the other way around)

To me, GitHub providing a workflow for transferring threads between Issues and Discussions reinforces that they're basically the same product.

> it does not clutter the issue tracker with non-issue things

In this repo we have `Type: *` labels that make it easy to filter on different kinds of conversation threads. Asserting that some of these kinds are "non-issue things" begs the question. If something can be expressed as a "to do" item then it fits within my mental model of closable Issues—"[fix a bug](https://github.com/getsentry/self-hosted/issues/941)," "[add a feature](https://github.com/getsentry/self-hosted/issues/914)," "[help a user](https://github.com/getsentry/self-hosted/issues/1173)," and "[adopt a course of action](https://github.com/getsentry/self-hosted/issues/1151)," all qualify in my book. If a discussion has a clear decision point then it fits within Issues, if not, then what's the point of having the discussion?

> and (if i remember correctly) you can redirect people to open a discussion instead of an issue in the configurable "new issue" page.

Yeah, and we see how good people are at deciding which conversation to have where. ;-) Better when possible not to offer the choice then to depend on people to choose correctly.

> the OSS community is switching to it quickly, so I assume many people will be familiar with GH Discussions in the coming months and it wont really be an issue.

I realize that my opinion goes against the grain, and I am theoretically [open to being proven wrong](https://github.com/getsentry/self-hosted/issues/1151#issuecomment-975992480), but to reconsider I would need to see such a high volume of traffic in Issues, and such a vibrant user community for self-hosted, that we need to a user-to-user forum as a release valve, with Issues limited to collaborators.

Until then, I would like to try managing the project without a forum, using Issues alone. So far I think it has been sufficient for this conversation, at least. ;)

**Comment by BYK** [comment]
>Building on my answer here, my problem with a forum—whether Discourse or Discussions—is that, at our scale, it is not differentiated enough from Issues to justify the cognitive overhead of maintaining and navigating between two systems.

An issue is something you need to deal with, and hopefully as soon as possible with preferably little discussion as the discussions go long, it becomes very hard to manage and track. A _discussion_ however is aimed towards staying open as long as it may be, allowing people to keep talking forever and ever and ever.

Now, I know that you want a list of things to get done, hence setting auto-close on the former forum. But it still had ongoing conversations on other topics.

**Comment by chadwhitacre** [comment]
> the discussions go long, it becomes very hard to manage and track

This is not my experience. 🐭

> allowing people to keep talking forever and ever and ever

That's what Twitter is for? 😅

> But it still had ongoing conversations on other topics.

Hmmm ... there may have been a few, but we had waaaaaay more one-off support requests than real live community conversation. If the forums were nice and lively then that'd be one thing, to talk about moving that vibrant community to Discussions, but the forums have been on life support for a while, and now they're pretty much [a ghost town](https://forum.sentry.io/c/on-premise/7). 😞

Also—and maybe this is the bottom line, for better or for worse—it's just way easier for me personally to operate in GitHub Issues than in a forum (whether Discourse or Discussions). 🐭 Since I'm on the hook to support and manage the self-hosted Sentry community (among other things), I need to optimize for my own ability to do so, and for me that means Issues. Other Sentry sub-communities may very well opt for Discussions, and once the self-hosted community has grown and/or we [bring in someone](https://sentry.io/careers/3648639/) to whom I can hand off self-hosted community management, I'm open to reopening this can of worms.

For now, I'm going to go ahead and call this question decided. Feel free to leave some parting comments, and I will see you [on other issues](https://github.com/getsentry/self-hosted/issues)! :)
