### ISSUE TITLE
sentry 21.11.0 - web interface does not work

### ISSUE THREAD

**Issue by Trepliev** [getsentry/self-hosted#1154]
### Version

21.11.0

### Steps to Reproduce

Upgraded 21.10.0 to 21.11.0. The port 9000 is not available anymore on the host. I can access it directly on the ip address of the container but not on the ip of the host.

container ip access:
telnet 172.18.0.22 9000
Trying 172.18.0.22...
Connected to 172.18.0.22.
Escape character is '^]'.
GET / HTTP/1.0

HTTP/1.0 302 Found
Content-Type: text/html; charset=utf-8
Location: /auth/login/
X-Robots-Tag: noindex, nofollow
Vary: Accept-Language, Cookie
Content-Language: en
Content-Length: 0
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Set-Cookie:  sentrysid=gAJ9cQBYBQAAAF9uZXh0cQFYAQAAAC9xAnMu:1mnZxl:yymZiaVpmuQTxJ5uOfCVZPVZIfI; expires=Thu, 02 Dec 2021 05:27:57 GMT; HttpOnly; Max-Age=1209600; Path=/

host ip access:
telnet: Unable to connect to remote host: Connection refused

### Expected Result

Working web interface

### Actual Result

[sentry_onpremise_web_1.log](https://github.com/getsentry/onpremise/files/7560143/sentry_onpremise_web_1.log)
[sentry_install_log-2021-11-18_04-37-42.txt](https://github.com/getsentry/onpremise/files/7560144/sentry_install_log-2021-11-18_04-37-42.txt)

**Comment by chadwhitacre** [comment]
Possibly something with the move from Docker Compose v1 to v2? Not sure what else we changed that might be relevant ...

Something in your config implicated, since you're upgrading?

Can you repro with a clean 21.11.0?

**Comment by Trepliev** [comment]
Now it seems to be related with kafka error - it repeats again and again in the docker-compose logs

`KafkaError{code=OFFSET_OUT_OF_RANGE,val=1,str="Broker: Offset out of range"}`

**Comment by Trepliev** [comment]
Update:
I tried everything on the page - https://develop.sentry.dev/self-hosted/troubleshooting/#recovery
and everything on the source page - https://github.com/getsentry/self-hosted/issues/478#issuecomment-666254392
But nothing helped.
After these changes the relay and nginx stopped working.
I decided to re-run the install.sh again. And now the Sentry is back and the web interface as well :-)

**Comment by chadwhitacre** [comment]
Going to close this out since reinstall got you unblocked. If you have recurring issues can you review #1131 to see if that covers what you're seeing?
