### ISSUE TITLE
onpremise postgres failed to start

### ISSUE THREAD

**Issue by sajjadG** [getsentry/self-hosted#1157]
### Version

21.11.0

### Steps to Reproduce

1. Download `21.11.0` release from github
2. Extract the archive
3. Change the `.env` if you want
4. Run `docker compose up -d`

### Expected Result

Everything container to be up and running with no error.

### Actual Result

```
/onpremise-21.11.0# docker logs -f sentry_onpremise-postgres-1
Setting up Change Data Capture
DB not initialized. Postgres will take care of pg_hba
cp: cannot stat '/opt/sentry/wal2json/wal2json.so': No such file or directory
```
There's no `wal2json` file in `postgres` directory (not in this release and not in the master branch)
```
/onpremise-21.11.0# ls postgres/
init_hba.sh             postgres-entrypoint.sh  
```
### Research
Looks like this error existed in previous versions too: `(21.6.0 (21.6.3 too) to 21.8.0)`
https://forum.sentry.io/t/could-not-translate-host-name-postgres-to-address-name-or-service-not-known/14292/5

**Comment by aminvakil** [comment]
Please follow the guidelines closely: https://develop.sentry.dev/self-hosted/#getting-started

> Our recommendation is to download the latest release of the onpremise repository, and then run `./install.sh` inside this directory. This script will take care of all the things you need to get started, including a base-line configuration, and then will tell you to run `docker-compose up -d` to start Sentry. Sentry binds to port `9000` by default. You should be able to reach the login page at http://127.0.0.1:9000

It seems that you missed running `./install.sh` prior to running `docker-compose up -d`.

And the url you have pasted is a different issue.

**Comment by chadwhitacre** [comment]
Please let us know if we're missing something @sajjadG. Closing for now.
