### ISSUE TITLE
Python Deprecated Warning (sentry clean up)

### ISSUE THREAD

**Issue by AyoubHabra** [getsentry/self-hosted#1162]
### Version

21.11.0

### Steps to Reproduce

docker-compose exec -T worker sentry cleanup --days 30

### Expected Result

Clean up with few warnings on stdout.

### Actual Result

Now this msg is sent to stderr.
`Removing Group for days=30 project=*
Cleaning up unused FileBlob references
/usr/local/lib/python3.8/site-packages/sentry/utils/email/list_resolver.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import Mapping
`

**Comment by chadwhitacre** [comment]
Undoubtedly introduced with the [upgrade to Python 3.8](https://github.com/getsentry/sentry/pull/29064) in [21.11.0](https://github.com/getsentry/sentry/releases/tag/21.11.0).

@joshuarli Are we committed to resolving these deprecation warnings? Do you already have a ticket for this or would you like this one? :)

**Comment by joshuarli** [comment]
This is fixed in sentry @ f05891b6c13d86399dcb1ec1b7fc211e5501650a.

We should fix DeprecationWarnings if they're in sentry, but I haven't figured out a way to make CI error if we specifically encounter DeprecationWarnings from only sentry.

**Comment by chadwhitacre** [comment]
Thanks @joshuarli. :)

https://github.com/getsentry/sentry/commit/f05891b6c13d86399dcb1ec1b7fc211e5501650a ftr
