### ISSUE TITLE
Server Requirements 

### ISSUE THREAD

**Issue by ikay42** [getsentry/self-hosted#1164]
### Problem Statement

What are the minimum requirements for setting up a Sentry Server?
RAM requirement and Disk Requirement.

**Comment by chadwhitacre** [comment]
Documented [on the README](https://github.com/getsentry/self-hosted#requirements):

> - Docker 19.03.6+
> - Compose 1.28.0+
> - 4 CPU Cores
> - 8 GB RAM
> - 20 GB Free Disk Space

:)
