### ISSUE TITLE
Sentry error

### ISSUE THREAD

**Issue by duyuyouci** [getsentry/self-hosted#1165]
### Environment

self-hosted (`onpremise` deployment)

### Version

21.11.0.dev0

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/39803418/142809884-770fdc30-c8d4-4c00-a1ac-8c8b9ce0da19.png)

### Expected Result

Why is this error reported

### Actual Result

How should I solve this error

**Comment by aminvakil** [comment]
Have you checked your host metrics (cpu/memory/disk)? I've seen this on spikes where my disk cannot handle very high load, but of course this does not happen 13k times.
