### ISSUE TITLE
Unlabel `Hacktoberfest` and `help wanted` issues

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/self-hosted#1168]
I'm taking the `Hacktoberfest` and `help wanted` labels off of issues in this repo. In a year I've never seen anybody randomly show up and pick up one of those, rather outside contributors tend to be motivated by solving immediate problems with their own particular self-hosted experience. I'm leaving the Hacktoberfest label around for use again next year but I'll probably just remove the help wanted label entirely. Will leave this open for a few days before I do that in case anybody wants to object. :)

**Comment by aminvakil** [comment]
I don't see the benefit of removing `help wanted` tags honestly...
Even if it only helps contribution from one user. Does it do any harm which I missing?

**Comment by chadwhitacre** [comment]
@aminvakil Do you want to take on management of the `help wanted` issues? It would mean going through the backlog of open issues, identifying some that are good candidates, grooming them and making sure they have clear instructions for new contributors, and then periodically regrooming them to make sure they stay current.

**Comment by aminvakil** [comment]
> @aminvakil Do you want to take on management of the `help wanted` issues? It would mean going through the backlog of open issues, identifying some that are good candidates, grooming them and making sure they have clear instructions for new contributors, and then periodically regrooming them to make sure they stay current.

Let's nuke them! :smiley:  (kidding)

I will try to go through them in the next week.

**Comment by aminvakil** [comment]
OK, I have tried going through older issues and now I see that there aren't many issues will stay open and stale and can be easily fixed anyway.

Let's nuke `help wanted`!

**Comment by chadwhitacre** [comment]
Done! 😁
