### ISSUE TITLE
CI flakes under "Ensure cleanup crons are working"

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/self-hosted#1171]
Seeing integration tests fail quite frequently, rerun sometimes works. Noticing a few failure modes, here is one (cf. #1170):

https://github.com/getsentry/self-hosted/runs/4317568879?check_suite_focus=true

```
Ensure cleanup crons are working ...
  + grep -q -E -e '\-cleanup\s+running\s+' -e '\-cleanup[_-].+\s+Up\s+'
  + docker compose --ansi never --env-file /home/runner/work/self-hosted/self-hosted/.env ps
  ++ teardown ERR 121
  ++ '[' 0 -eq 1 ']'
  ++ DID_TEAR_DOWN=1
  ++ '[' ERR '!=' EXIT ']'
  ++ echo 'An error occurred, caught SIGERR on line 121'
  An error occurred, caught SIGERR on line 121
  ++ echo 'Tearing down ...'
  Tearing down ...
  ++ rm /tmp/tmp.9Qws9UthXM
  ++ echo Done.
  Done.
  + teardown EXIT 1
  + '[' 1 -eq 1 ']'
  + return 0
  Error: Process completed with exit code 255.
  ##[debug]Finishing: Integration Test
```

Not consistent between 1.28 and 2.0.1.

Line:

https://github.com/getsentry/self-hosted/blob/da8f4903e4cfe47ca4fa5bf68265b62f795c60a0/_integration-test/run.sh#L123

**Comment by chadwhitacre** [comment]
https://github.com/getsentry/self-hosted/runs/4372607126?check_suite_focus=true#step:4:3336

**Comment by aminvakil** [comment]
I was trying to understand what has happened in times prior to regression starting to happen yesterday and could it be because of https://github.com/getsentry/self-hosted/pull/1119?

I couldn't understand why this should fail sometimes, maybe others have some idea?

**Comment by chadwhitacre** [comment]
Another on #1289:

https://github.com/getsentry/self-hosted/runs/5058157966?check_suite_focus=true#step:4:3617

My hunch is that cleanup runs but the test hits either before or after.

**Comment by chadwhitacre** [comment]
https://github.com/getsentry/self-hosted/runs/5116818258?check_suite_focus=true#step:4:3641

**Comment by aminvakil** [comment]
https://github.com/getsentry/self-hosted/runs/5163491240?check_suite_focus=true

On https://github.com/getsentry/self-hosted/commit/e0a8ae commit.

**Comment by chadwhitacre** [comment]
https://github.com/getsentry/self-hosted/runs/5517601056?check_suite_focus=true#step:4:1513

**Comment by aminvakil** [comment]
https://github.com/getsentry/self-hosted/runs/5541434168?check_suite_focus=true#step:4:3034

**Comment by chadwhitacre** [comment]
https://github.com/getsentry/self-hosted/runs/5561229447?check_suite_focus=true#step:4:3562

**Comment by aminvakil** [comment]
https://github.com/getsentry/self-hosted/runs/5669181355?check_suite_focus=true
