### ISSUE TITLE
Snuba cleanup transactions dropped 0 partitions

### ISSUE THREAD

**Issue by e-jjj** [getsentry/self-hosted#1172]
### Version

Sentry v21.6.1

### Steps to Reproduce

There are 3 jobs set up to cleanup transactions on a daily basis, however the job logs always show the message as below,

Dropped 0 partitions on sentry-clickhouse:9000

The cleanup command in use is,

snuba cleanup --storage transactions --dry-run "False" --clickhouse-host sentry-clickhouse --clickhouse-port "9000"

### Expected Result

Clean up the snuba transactions and reduce the clickhouse volumes

### Actual Result

The clickhouse volumes seem to be populating the clickhouse-0, clickhouse-1 and clickhouse-3 volumes

21G	/var/lib/clickhouse/store/
13G	/var/lib/clickhouse/data/default/

And the snuba transactions and consumers logs show the following,

snuba.clickhouse.errors.ClickhouseWriterError: [243] Received from sentry-clickhouse-2.sentry-clickhouse-headless.sentry.svc.cluster.local:9000. DB::Exception: Cannot reserve 1.00 MiB, not enough space. (version 20.8.9.6 (official build))

**Comment by chadwhitacre** [comment]
> Cannot reserve 1.00 MiB, not enough space.

You're saying you are running out of disk space? Is that the pain point here?

> Clean up the snuba transactions and reduce the clickhouse volumes

Why do you believe that snuba is failing to clean up properly, rather than that you don't have enough disk space allocated for snuba/clickhouse's needs?

**Comment by aminvakil** [comment]
Sentry volumes do not have restriction on how much disk space they can get, what you see from host is what you get in docker volumes, I'd suggest checking disk space available on host and see if the problem arises then.

**Comment by e-jjj** [comment]
@chadwhitacre 

The out of disk space issue is what causes the snuba pods to crash, I have increased the volume size twice, started at 20GB and currently is set to 60GB within few months.

I managed to fix the snuba pods crashing issue by increasing the volume allocated to the clickhouse deployments, three volumes altogehter. I see this as a workaround as I would prefer to keep the volumes under certain size by cleaning up the clickhouse data store. I tried removing the volumes and allocating new volumes before and I lost performance data.

The pain point is that the snuba cleanup jobs dont seem to be cleaning up. The logs show  `Dropped 0 partitions on sentry-clickhouse:9000` every time. Is this expected? What would be the best way to clean up the clickhouse data store?

Thanks

**Comment by chadwhitacre** [comment]
Here is the [implementation of `snuba cleanup`](https://github.com/getsentry/snuba/blob/b88d8194cb409fd1e013d6ca8d24ad8491dd6652/snuba/cleanup.py). Is your retention window set to something other than the default (90 days, pretty sure)? Do you have events older than 90 days in your system?

**Comment by e-jjj** [comment]
@chadwhitacre The retention window is set to default 90 days. We currently don't have events older than 90 days in our sentry system.

**Comment by chadwhitacre** [comment]
Okay, then to me it sounds so far like your system is behaving as expected.

**Comment by e-jjj** [comment]
@chadwhitacre would you know the expected size of the clickhouse volume with the default 90 day retention period? Mainly using for about 8 web apps with tracing rate set to 80%.

Thanks

**Comment by chadwhitacre** [comment]
We [state](https://github.com/getsentry/self-hosted#requirements) 20 GB as a minimum requirement. I guess 20 GB × 8 apps = 160 GB?
