### ISSUE TITLE
ChunkLoadError while loading sentry

### ISSUE THREAD

**Issue by gforcada** [getsentry/self-hosted#1174]
### Version

21.11.0

### Steps to Reproduce

After an OS upgrade done by our server provider sentry fails to load some JS.
I upgraded from 21.9.0 (where the problem was already happening) to 21.11.0 and run `./install.sh` which run fine as well.
Seems that somehow some JS needs some recompile?

### Expected Result

That JS is loaded as usual, and the website is loaded.

### Actual Result

Running `docker-compose ps` says that all is running fine, but on the browser one sees:

```
Some cookies are misusing the recommended “SameSite“ attribute 4
Loading failed for the <script> with source “https://sentry.dfstats.fcio.net/_static/dist/sentry/chunks/app_utils_discover_eventView_tsx-app_views_performance_transactionSummary_filter_tsx.46973a43258aa1d59b0a.js”. issues:1:1
Loading failed for the <script> with source “https://sentry.dfstats.fcio.net/_static/dist/sentry/chunks/vendors-node_modules_emotion_css_dist_emotion-css_esm_js-node_modules_emotion_react_dist_emot-ea6130.dba7ad29b85b1fd3dd0d.js”. issues:1:1
Loading failed for the <script> with source “https://sentry.dfstats.fcio.net/_static/dist/sentry/chunks/app_components_asyncComponent_tsx.150c1d6e1c4c0211201a.js”. issues:1:1
Loading failed for the <script> with source “https://sentry.dfstats.fcio.net/_static/dist/sentry/chunks/vendors-node_modules_copy-text-to-clipboard_index_js-node_modules_echarts-for-react_lib_core_-292084.0b23c3e50f26f38a0cf1.js”. issues:1:1
Uncaught (in promise) ChunkLoadError: Loading chunk app_utils_discover_eventView_tsx-app_views_performance_transactionSummary_filter_tsx failed.
(error: https://sentry.dfstats.fcio.net/_static/dist/sentry/chunks/a…rmance_transactionSummary_filter_tsx.46973a43258aa1d59b0a.js)
    j jsonp chunk loading:27
    e ensure chunk:6
    e ensure chunk:5
    c initializeMain.tsx:14
jsonp chunk loading:27:17
```

**Comment by chadwhitacre** [comment]
Weird. Do you have some caching going on? Is this a stock `self-hosted` setup?

**Comment by gforcada** [comment]
Yes, it is a self-hosted setup that was going smooth until this server OS upgrade, but it's weird that now some JS fails, as that seems quite unrelated... as for caching, it should not be, our frontend pipeline is only nginx+haproxy.

**Comment by chadwhitacre** [comment]
Somehow you're in a weird state. You can try to debug to understand exactly why and how, but probably easier to start over. Can you run `install.sh` again? 🤔

**Comment by gforcada** [comment]
@chadwhitacre thanks for the tips and getting the time to answer! 👍🏾 unfortunately seems that it still keeps failing 😕 is there any debug guide on how to get logs from the docker containers? 🤔 I'm rather newbie on that field 😅

**Comment by chadwhitacre** [comment]
> is there any debug guide on how to get logs from the docker containers?

https://docs.docker.com/engine/reference/commandline/logs/ is one place to start. Good luck! :)

**Comment by aminvakil** [comment]
Given from error you have pasted, I'd suspect something has been changed in your proxy (whether it's nginx or something else) that's causing problems.

**Comment by gforcada** [comment]
@aminvakil the proxy? 🤔 that's interesting, I did not try to bypass it and connect directly to sentry, I will give it a try! thanks!!

@chadwhitacre I will have a look at the docs, thanks for the pointer!!

**Comment by gforcada** [comment]
@aminvakil wow! awesome 🎉 💯 indeed, it is the proxy! Connecting right away to the port 9000 gives actually no warning at all, all is fine and works as expected 🤩 

Now, try to figure out what's wrong with the proxy server 😅 👍🏾

**Comment by gforcada** [comment]
Small update here: I could get it to work if I remove the `http2` directive on the `listen` configuration line of the external nginx server 🤷🏾‍♂️

**Comment by guemidiborhane** [comment]
@gforcada can you please share your nginx config files related to sentry, i'm having the same issue and can't seem to figure it out.

**Comment by aminvakil** [comment]
@guemidiborhane 

Try this:

https://github.com/getsentry/self-hosted/issues/1161#issuecomment-974799008

**Comment by guemidiborhane** [comment]
@gforcada Thanks i'll try it out.
