### ISSUE TITLE
'ERROR: for snuba-api Container "ee666f7f2cdd" is unhealthy.' during install.sh

### ISSUE THREAD

**Issue by ynotna87** [getsentry/self-hosted#1178]
### Version

21.11.0

### Steps to Reproduce

1. Run ./install.sh

### Expected Result

Installation succeed

### Actual Result

▶ Bootstrapping and migrating Snuba ...
Creating sentry_onpremise_clickhouse_1 ... 
Creating sentry_onpremise_zookeeper_1  ... 
Creating sentry_onpremise_redis_1      ... 
Creating sentry_onpremise_redis_1      ... done
Creating sentry_onpremise_zookeeper_1  ... done
Creating sentry_onpremise_clickhouse_1 ... done
Creating sentry_onpremise_kafka_1      ... 
Creating sentry_onpremise_kafka_1      ... done

ERROR: for snuba-api  Container "ee666f7f2cdd" is unhealthy.
Encountered errors while bringing up the project.
An error occurred, caught SIGERR on line 3
Cleaning up...

Can anyone help me with this ?

**Comment by chadwhitacre** [comment]
Is this a clean install @ynotna87? If not, can you try a clean install?

**Comment by ynotna87** [comment]
> Is this a clean install @ynotna87? If not, can you try a clean install?

Hi Chad, yes it is a clean install from scratch on a new VM.

OS: Centos 7
Docker Version: 20.10.11
docker-compose Version: 1.29.2
Python Version: 3.6.8
vCPU: 8
RAM: 16G

**Comment by aminvakil** [comment]
Try running `docker-compose down -v --remove-orphans && docker volume prune -f && docker-compose up -d` again.

**Beware this will effectively removes all your data.**

**Comment by ynotna87** [comment]
> Try running `docker-compose down -v --remove-orphans && docker volume prune -f && docker-compose up -d` again.
> 
> **Beware this will effectively removes all your data.**

Hi Amin,

i tried to run the command, but unfortunately the same error still the same. What could possibly wrong ?
Currently i try to request additional VM to try installing on that, but it's yet to be provisioned.

**Comment by ynotna87** [comment]
> > Try running `docker-compose down -v --remove-orphans && docker volume prune -f && docker-compose up -d` again.
> > **Beware this will effectively removes all your data.**
> 
> Hi Amin,
> 
> i tried to run the command, but unfortunately the same error still the same. What could possibly wrong ? Currently i try to request additional VM to try installing on that, but it's yet to be provisioned.

Update : After i tried on another VM, it still giving the same error:

▶ Bootstrapping and migrating Snuba ...
Creating sentry_onpremise_clickhouse_1 ... 
Creating sentry_onpremise_zookeeper_1  ... 
Creating sentry_onpremise_redis_1      ... 
Creating sentry_onpremise_redis_1      ... done
Creating sentry_onpremise_clickhouse_1 ... done
Creating sentry_onpremise_zookeeper_1  ... done
Creating sentry_onpremise_kafka_1      ... 
Creating sentry_onpremise_kafka_1      ... done

ERROR: for snuba-api  Container "05c4e3a60327" is unhealthy.
Encountered errors while bringing up the project.
An error occurred, caught SIGERR on line 3
Cleaning up...

**Comment by chadwhitacre** [comment]
Can you run with debugging and paste your full install log in [a gist](https://gist.github.com/)?

```
DEBUG=1 ./install.sh --no-user-prompt
```

**Comment by sajphon** [comment]
@chadwhitacre not OP, but the same issue.

https://gist.github.com/sajphon/ef85f11488f8fe0a9b7699e971ecc642

**Comment by AxTheB** [comment]
Had the same issue, rebooting the machine helped.

**Comment by chadwhitacre** [comment]
What is the `snuba-api` [healthcheck](https://docs.docker.com/engine/reference/builder/#healthcheck)? How is it failing? Why?

https://github.com/getsentry/self-hosted/blob/c258a1e9394cf68ed970ae6d60347795000c95c2/docker-compose.yml#L31-L32

Curious to me that `snuba-api` doesn't seem on the surface to _have_ a healthcheck. 🤔

**Comment by aminvakil** [comment]
> Curious to me that `snuba-api` doesn't seem on the surface to _have_ a healthcheck. thinking

It does not.

```
docker ps | grep snuba-api
bab3ff609285   getsentry/snuba:21.9.0                 "./docker_entrypoint…"   2 hours ago   Up 2 hours             1218/tcp                                    sentry_onpremise_snuba-api_1
```
(It does not a `(healthy)` after Up 2 hours).
I'm more confused now, why on the first run it has? :thinking:

**Comment by markdensen403** [comment]
I'm also having the same error where snuba-api is failing. In fact, my entire dockers are down, and production is offline because I was trying to update our sentry server. Does anyone have any idea what is happening here?

**Comment by AxTheB** [comment]
At that point it will fail for example when any of the started containers does not go up, try starting the zookeeper, clickhouse, redis and kafka containers manually and check their state.

**Comment by ynotna87** [comment]
I am still having the same issue, snuba-api container are not healthy. Anyone here with the same issue, having some luck on resolving this ?

**Comment by ynotna87** [comment]
> Can you run with debugging and paste your full install log in [a gist](https://gist.github.com/)?
> 
> ```
> DEBUG=1 ./install.sh --no-user-prompt
> ```

https://gist.github.com/ynotna87/96fc2d37aed51ead2f6a915c8cf7f5cb @chadwhitacre

**Comment by AxTheB** [comment]
@ynotna87 Yes I had. Can you start other containers mentioned in this phase into healthy/running state? In my case it was kafka one stuck in Starting up state because of network issues

**Comment by ynotna87** [comment]
> @ynotna87 Yes I had. Can you start other containers mentioned in this phase into healthy/running state? In my case it was kafka one stuck in Starting up state because of network issues

Any guidance on how to do it ? honestly i am not too proficient on docker.

**Comment by chadwhitacre** [comment]
@ynotna87 Not to be a jerk but have you [considered SaaS](https://sentry.io/signup/) if maintaining self-hosted is beyond your comfort level?

**Comment by ynotna87** [comment]
> @ynotna87 Not to be a jerk but have you [considered SaaS](https://sentry.io/signup/) if maintaining self-hosted is beyond your comfort level?

Yes, but in my country, there's a regulation, that the data should be on premise, specifically for our company's nature of business. Unfortunately, we have to comply as it have serious sanctions. As for me, i am more than happy to use the SaaS as it will brings more ease of mind for me and the team.

**Comment by chadwhitacre** [comment]
Ah, gotcha. :) Well in that case it sounds like you have a learning journey ahead of you! Good luck! ☺️

**Comment by rwky** [comment]
I had the same issue the error is actually with clickhouse just to add confusion and it's this error https://github.com/getsentry/self-hosted/issues/1205

This comment solved it for me https://github.com/getsentry/self-hosted/issues/1205#issuecomment-995877578

**Comment by aamarques** [comment]
I had the same issue with snuba. I did a `docker-compose up -d` and got many unhealthy  errors. 
So, I did a `docker-compose down` and `docker-compose up -d`  again and snuba is healthy but.. now I have a lot of problems: 
```
ERROR: for post-process-forwarder  Container "a5a3823b64ee" is unhealthy.

ERROR: for worker  Container "a5a3823b64ee" is unhealthy.

ERROR: for cron  Container "a5a3823b64ee" is unhealthy.

ERROR: for subscription-consumer-events  Container "a5a3823b64ee" is unhealthy.

ERROR: for sentry-cleanup  Container "a5a3823b64ee" is unhealthy.

ERROR: for web  Container "a5a3823b64ee" is unhealthy.

ERROR: for ingest-consumer  Container "a5a3823b64ee" is unhealthy.

ERROR: for subscription-consumer-transactions  Container "a5a3823b64ee" is unhealthy.
```

```
postgres_1                                  |
postgres_1                                  | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1                                  |
postgres_1                                  | LOG:  database system was interrupted while in recovery at 2021-12-20 11:25:50 UTC
postgres_1                                  | HINT:  This probably means that some data is corrupted and you will have to use the last backup for recovery.
postgres_1                                  | LOG:  database system was not properly shut down; automatic recovery in progress
postgres_1                                  | LOG:  redo starts at A08/5AD57638
postgres_1                                  | WARNING:  specified item offset is too large
postgres_1                                  | CONTEXT:  xlog redo at A08/5B7A5700 for Btree/INSERT_LEAF: off 169
postgres_1                                  | PANIC:  btree_insert_redo: failed to add item
postgres_1                                  | CONTEXT:  xlog redo at A08/5B7A5700 for Btree/INSERT_LEAF: off 169
postgres_1                                  | LOG:  startup process (PID 33) was terminated by signal 6: Aborted
postgres_1                                  | LOG:  aborting startup due to startup pro
```

**Comment by aamarques** [comment]
following https://github.com/getsentry/self-hosted/issues/1211

**Comment by shaomingyangallan** [comment]
Do you forgot run ./install.sh before you run docker-compose up -d Hm...

**Comment by aamarques** [comment]
> Do you forgot run ./install.sh before you run docker-compose up -d Hm... i met seem wrong because i forgot run it

No.. Idid, but did `deocker-compose up -d` after this:

```
ERROR: for snuba-api Container "xxx" is unhealthy.
Encountered errors while bringing up the project.
An error occurred, caught SIGERR on line 3
Cleaning up...
```

**Comment by shaomingyangallan** [comment]
can you run docker logs "xxx", my problem is miss wal2json

**Comment by AxTheB** [comment]
> Any guidance on how to do it ? honestly i am not too proficient on docker.

I use portainer.io for this, its clikety and easy.

**Comment by frame** [comment]
At almost every new release I run into these `x Container "x" is unhealthy` issues. Sometimes it's **snuba-api**, but mostly it was **kafka**. I noticed that the containers were indeed healthy and happily running when I checked them manually.

On my system (EC2 t3.xlarge with gp2 disks) the containers wouldn't start quickly enough and were causing timeouts. Hence reported unhealthy. A few seconds later they were up and running, which made the debugging so hard.

I've edited the docker-compose.yml to be a lot more patient and everything works fine for me now:

`diff --git a/docker-compose.yml b/docker-compose.yml`
```
index 8197e3a..3c028d2 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -11,7 +11,7 @@ x-healthcheck-defaults: &healthcheck_defaults
   # https://github.com/moby/moby/issues/39388
   # https://github.com/getsentry/self-hosted/issues/1000
   interval: 30s
-  timeout: 5s
+  timeout: 60s
   retries: 5
   start_period: 10s
 x-sentry-defaults: &sentry_defaults
```

Note: If the upgrade got interrupted you need to stop all docker containers before trying again:

`docker stop $(docker ps -q)` (as root)

This assumes no other services than sentry is on this machine.

**Comment by aminvakil** [comment]
> I've edited the docker-compose.yml to be a lot more patient and everything works fine for me now:
> 
> ```
> diff --git a/docker-compose.yml b/docker-compose.yml
> index 8197e3a..3c028d2 100644
> --- a/docker-compose.yml
> +++ b/docker-compose.yml
> @@ -11,7 +11,7 @@ x-healthcheck-defaults: &healthcheck_defaults
>    # https://github.com/moby/moby/issues/39388
>    # https://github.com/getsentry/self-hosted/issues/1000
>    interval: 30s
> -  timeout: 5s
> +  timeout: 60s
>    retries: 5
>    start_period: 10s
>  x-sentry-defaults: &sentry_defaults
> ```
> 

Do you think this should be an environment variable so you don't have to manually edit `docker-compose.yml` and just set it in `.env.custom`?

**Comment by maximal** [comment]
So, folks, are our data unrecoverably corrupted? Nice upgrade it was.

**Comment by MazzMazz** [comment]
I get the same Problem when upgrading from 21.11.0 to 21.12.0. After i upgraded from 21.6.3 to 21.12.0 and completely corrupted sentry i used a backup and upgraded month by month.

I was able to checkout the version before (21.11.0) and it works again after upgrading from 21.11.0 to 21.12.0 - didn't need a backup. No guarantee that this works for you.

```
git checkout tags/21.11.0
./install.sh
docker-compose up -d
```

**Comment by maximal** [comment]
@MazzMazz, thanks!

**Comment by chadwhitacre** [comment]
> I've edited the docker-compose.yml to be a lot more patient

Should we up the timeout, then? Should dig up the original conversation where we added that to see if there's a reason ...

**Comment by chadwhitacre** [comment]
>  the error is actually with clickhouse

@rwky Ah, okay. That makes sense, as the `snuba-api` service depends (via `snuba-defaults`) on `clickhouse`, and we invoke the `snuba-api` service in `bootstrap-snuba.sh` underneath `install.sh`. @sajphon's [log lines up here](https://gist.github.com/sajphon/ef85f11488f8fe0a9b7699e971ecc642#file-sentry-full-install-log-L446-L459).

> and it's this error #1205

It seems @rwky that you hit a different root cause than @ynotna87 (OP) as they were using 21.11.0.

I'm a little surprised that folks are running `install.sh` against live instances without a) stopping services, or at least b) taking a backup. I mean, YOLO, I guess.

But don't we ... ? Yeah, we [turn things off](https://github.com/getsentry/self-hosted/blob/6c26bce20d64001159b3d1ecd9afc66fcac4bc4b/install.sh#L21) as part of `install.sh`. 🤔 Do we need to do that earlier in the process?

Here are the potential actions items I'm seeing:

1. Up the health check timeout from 5s to 60s (any reason not to?).
2. Turn things off way earlier (would that actually have prevented [#1205](https://github.com/getsentry/self-hosted/issues/1205) and/or [#1211](https://github.com/getsentry/self-hosted/issues/1211), though?).

Any other action items I'm missing?

**Comment by jthomaschewski** [comment]
> ERROR: for snuba-api Container "ee666f7f2cdd" is unhealthy.
> Encountered errors while bringing up the project.

I also got this error message while upgrading an existing instance because I didn't stop containers before running the `install.sh` script/checking out the new git tag.

Solution: manually stopping the existing instance before switching the tag:
```
$ docker-compose down
$ git checkout 21.12.0
$ ./install.sh
```

Previous upgrades worked fine without stopping containers as the install.sh script was doing so anways before upgrading. Thats why I didn't bother.
Due to the name change this time this didn't worked out: The containers where not detected&stopped and new containers where started anyways.

The new clickhouse container failed to start with:
```
2022.01.05 15:14:27.133432 [ 1 ] {} <Error> Application: DB::Exception: Cannot lock file /var/lib/clickhouse/status. Another server instance in same directory is already running.
```
This was causing the health checks to fail for the new container - not a timeout issue in this case.

Maybe it would help to add a simple generic upgrade guide to the `README` as the log output is not making the cause of these kinds of errors obvious.

**Comment by chadwhitacre** [comment]
> Here are the potential actions items I'm seeing:

Addressed in https://github.com/getsentry/self-hosted/pull/1241.

**Comment by chadwhitacre** [comment]
I merged the changes in #1241, hopefully this helps. Should ship in 22.1.0 next week.

Thanks everyone!

**Comment by nttdocomo** [comment]
> 

I have the same error, and follow your step, this time error disapear but the postgres is not start

**Comment by aminvakil** [comment]
For future reference: https://develop.sentry.dev/self-hosted/troubleshooting/#docker-containers-healthcheck

**Comment by tomasnorre** [comment]
I also had this issue upgrading from 21.6.3 -> 22.1.0, the suggestion from https://github.com/getsentry/self-hosted/issues/1178#issuecomment-996659153 helped me move on.

**Comment by chadwhitacre** [comment]
And actually I'm surprised you hit this with 22.1.0, @tomasnorre, because we made #1241 to avoid this. Were you going straight to 22.1.0, or through 21.12.0 first?

**Comment by tomasnorre** [comment]
I'm on 21.1.0 went to 21.6.3 and from there to 22.1.0 as the upgrade guide suggests.
https://develop.sentry.dev/self-hosted/releases/#hard-stops

I got this in the step from 21.6.3 -> 22.1.0.

**Comment by chadwhitacre** [comment]
Bummer. I guess we start getting more reports about this, then, and we'll have to keep digging. :-/

**Comment by kai11** [comment]
I had this error during upgrade and fixed it. My findings:
- this is not for snuba-api container error - it says "_for_ snuba-api"
- this is clickhouse error and clickhouse container DOES have healhcheck
- error essentially means clickhouse already running on this server somewhere
- for my 21.10.0 install I had COMPOSE_PROJECT_NAME=sentry_onpremise
- 22.1.0 defaults to COMPOSE_PROJECT_NAME=sentry-self-hosted in .env file
- with incorrect setting above docker-compose may not work with running containers - even docker-compose down may not be enough to stop everything.
- my own fix was to revert to correct project name; install.sh \ docker-compose up both successful after it.

**Comment by chadwhitacre** [comment]
> even docker-compose down may not be enough to stop everything.

That could explain why @frame took [a more drastic route](https://github.com/getsentry/self-hosted/issues/1178#issuecomment-999421948):

> Note: If the upgrade got interrupted you need to stop all docker containers before trying again:
>
> `docker stop $(docker ps -q)` (as root)
>
> This assumes no other services than sentry is on this machine.

Maybe we should do something similar in [`turn-things-off.sh`](https://github.com/getsentry/self-hosted/blob/22.1.0/install/turn-things-off.sh)? 🤔

**Comment by jthomaschewski** [comment]
I worked around this by calling `docker-compose down` before upgrading, see 
https://github.com/getsentry/self-hosted/issues/1178#issuecomment-1005844731
All tries to stop containers in the install script fail because of the changed `COMPOSE_PROJECT_NAME`

I cam 2 possible solutions, something around:
- document that its required to manually stop containers before doing major upgrades
- add something like ` COMPOSE_PROJECT_NAME=sentry_onpremise docker-compose down` into the `install.sh` script to make sure the old containers are stopped and removed if existent

**Comment by chadwhitacre** [comment]
> document that its required to manually stop containers before doing major upgrades

The intention of `turn-things-off.sh` is to avoid having to document this as a manual step.

> add something like `COMPOSE_PROJECT_NAME=sentry_onpremise docker-compose down` into the `install.sh`

I like this better than the over-broad `docker stop $(docker ps -q)`. Are there other reasons that `docker compose down` might be insufficient, though?

**Comment by kai11** [comment]
What about simply fail to proceed with install if old containers are found and need to be stopped by user? Of course, with clear message.

**Comment by chadwhitacre** [comment]
I think since we're already attempting to stop services automatically during install then we should preserve that behavior for old containers as well.

**Comment by shaqaruden** [comment]
I had this same issue. After a failed install I ran `docker-compose down` which brought down all the new containers but I needed to run `docker-compose down` again which brought all the older containers. I ran the same command again to ensure everything was down and then ran `./install.sh` which succeeded

```terminal
...
ERROR: for snuba-api  Container "faf1ca068692" is unhealthy.
Encountered errors while bringing up the project.
An error occurred, caught SIGERR on line 3
Cleaning up...

[redacted] in sentry at [redacted] on  tags/22.1.0 [!?] on 🐳 v20.10.12 took 57s 
➜ dcd
Removing sentry-onpremise_kafka_1      ... done
Removing sentry-onpremise_clickhouse_1 ... done
Removing sentry-onpremise_zookeeper_1  ... done
Removing sentry-onpremise_redis_1      ... done
Removing network sentry-onpremise_default

[redacted] in sentry at [redacted] on  tags/22.1.0 [!?] on 🐳 v20.10.12 
➜ vim .env

[redacted] in sentry at [redacted] on  tags/22.1.0 [!?] on 🐳 v20.10.12 took 8s 
➜ dcd
Stopping sentry_onpremise_nginx_1                                    ... done
Stopping sentry_onpremise_relay_1                                    ... done
Stopping sentry_onpremise_worker_1                                   ... done
Stopping sentry_onpremise_cron_1                                     ... done
Stopping sentry_onpremise_subscription-consumer-events_1             ... done
Stopping sentry_onpremise_post-process-forwarder_1                   ... done
Stopping sentry_onpremise_sentry-cleanup_1                           ... done
Stopping sentry_onpremise_subscription-consumer-transactions_1       ... done
Stopping sentry_onpremise_ingest-consumer_1                          ... done
Stopping sentry_onpremise_web_1                                      ... done
Stopping sentry_onpremise_snuba-cleanup_1                            ... done
Stopping sentry_onpremise_snuba-transactions-cleanup_1               ... done
Stopping sentry_onpremise_symbolicator-cleanup_1                     ... done
Stopping sentry_onpremise_snuba-replacer_1                           ... done
Stopping sentry_onpremise_snuba-subscription-consumer-transactions_1 ... done
Stopping sentry_onpremise_snuba-sessions-consumer_1                  ... done
Stopping sentry_onpremise_snuba-outcomes-consumer_1                  ... done
Stopping sentry_onpremise_snuba-subscription-consumer-events_1       ... done
Stopping sentry_onpremise_snuba-consumer_1                           ... done
Stopping sentry_onpremise_snuba-api_1                                ... done
Stopping sentry_onpremise_snuba-transactions-consumer_1              ... done
Stopping sentry_onpremise_postgres_1                                 ... done
Stopping sentry_onpremise_smtp_1                                     ... done
Stopping sentry_onpremise_memcached_1                                ... done
Stopping sentry_onpremise_symbolicator_1                             ... done
Stopping sentry_onpremise_kafka_1                                    ... done
Stopping sentry_onpremise_clickhouse_1                               ... done
Stopping sentry_onpremise_zookeeper_1                                ... done
Stopping sentry_onpremise_redis_1                                    ... done
Removing sentry_onpremise_nginx_1                                    ... done
Removing sentry_onpremise_relay_1                                    ... done
Removing sentry_onpremise_worker_1                                   ... done
Removing sentry_onpremise_cron_1                                     ... done
Removing sentry_onpremise_subscription-consumer-events_1             ... done
Removing sentry_onpremise_post-process-forwarder_1                   ... done
Removing sentry_onpremise_sentry-cleanup_1                           ... done
Removing sentry_onpremise_subscription-consumer-transactions_1       ... done
Removing sentry_onpremise_ingest-consumer_1                          ... done
Removing sentry_onpremise_web_1                                      ... done
Removing sentry_onpremise_snuba-cleanup_1                            ... done
Removing sentry_onpremise_snuba-transactions-cleanup_1               ... done
Removing sentry_onpremise_symbolicator-cleanup_1                     ... done
Removing sentry_onpremise_geoipupdate_1                              ... done
Removing sentry_onpremise_snuba-replacer_1                           ... done
Removing sentry_onpremise_snuba-subscription-consumer-transactions_1 ... done
Removing sentry_onpremise_snuba-sessions-consumer_1                  ... done
Removing sentry_onpremise_snuba-outcomes-consumer_1                  ... done
Removing sentry_onpremise_snuba-subscription-consumer-events_1       ... done
Removing sentry_onpremise_snuba-consumer_1                           ... done
Removing sentry_onpremise_snuba-api_1                                ... done
Removing sentry_onpremise_snuba-transactions-consumer_1              ... done
Removing sentry_onpremise_postgres_1                                 ... done
Removing sentry_onpremise_smtp_1                                     ... done
Removing sentry_onpremise_memcached_1                                ... done
Removing sentry_onpremise_symbolicator_1                             ... done
Removing sentry_onpremise_kafka_1                                    ... done
Removing sentry_onpremise_clickhouse_1                               ... done
Removing sentry_onpremise_zookeeper_1                                ... done
Removing sentry_onpremise_redis_1                                    ... done
Removing network sentry_onpremise_default

[redacted] in sentry at [redacted] on  tags/22.1.0 [?] on 🐳 v20.10.12 took 26s 
➜ dcd
Removing network sentry-self-hosted_default
WARNING: Network sentry-self-hosted_default not found.

[redacted] in sentry at [redacted] on  tags/22.1.0 [?] on 🐳 v20.10.12 
➜ ./install.sh 
▶ Parsing command line ...

▶ Initializing Docker Compose ...

▶ Setting up error handling ...

...

-----------------------------------------------------------------

You're all done! Run the following command to get Sentry running:

  docker-compose up -d

-----------------------------------------------------------------
```

**Comment by ragesoss** [comment]
I ran into this when upgrading today, and had to use `docker stop $(docker ps -q)` to get the upgrade to work properly. (`docker compose down` was not sufficient.)

**Comment by aminvakil** [comment]
> I ran into this when upgrading today, and had to use `docker stop $(docker ps -q)` to get the upgrade to work properly. (`docker compose down` was not sufficient.)

@ragesoss If this has happened from a version < 21.12.0 to a version >= 21.12.0, `docker-compose down -v --remove-orphans` should have worked. Or executing `docker-compose down -v` before checking out new version.

**Comment by iburrows** [comment]
I recently upgraded from 20.12.1 -> 21.6.3 -> 22.2.0 and running `docker-compose down -v --remove-orphans` did not help going from 21.6.3 -> 22.2.0. The only way I could get it running was to set the clickhouse healthcheck to `test: "exit 0"` and then it started up. I looked at #1081 as this was the same error I was seeing but there is nothing different in master to the latest release (currently 22.2.0). I probably broke something with setting `test: "exit 0"` but it started up here are the logs from clickhouse.
```
$ docker logs 2047e3808568
Processing configuration file '/etc/clickhouse-server/config.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/docker_related_config.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/sentry.xml'.
Include not found: clickhouse_remote_servers
Include not found: clickhouse_compression
Logging information to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
Logging information to console
2022.03.15 14:32:13.546698 [ 1 ] {} <Information> : Starting ClickHouse 20.3.9.70 with revision 54433
2022.03.15 14:32:13.549431 [ 1 ] {} <Information> Application: starting up
Include not found: networks
2022.03.15 14:32:13.565627 [ 1 ] {} <Information> Application: Uncompressed cache size was lowered to 1.90 GiB because the system has low amount of memory
2022.03.15 14:32:13.565955 [ 1 ] {} <Information> Application: Mark cache size was lowered to 1.90 GiB because the system has low amount of memory
2022.03.15 14:32:13.565998 [ 1 ] {} <Information> Application: Loading metadata from /var/lib/clickhouse/
2022.03.15 14:32:13.567895 [ 1 ] {} <Information> DatabaseOrdinary (system): Total 2 tables and 0 dictionaries.
2022.03.15 14:32:13.571923 [ 44 ] {} <Information> BackgroundProcessingPool: Create BackgroundProcessingPool with 16 threads
2022.03.15 14:32:13.832585 [ 1 ] {} <Information> DatabaseOrdinary (system): Starting up tables.
2022.03.15 14:32:13.843690 [ 1 ] {} <Information> DatabaseOrdinary (default): Total 13 tables and 0 dictionaries.
2022.03.15 14:32:13.944329 [ 1 ] {} <Information> DatabaseOrdinary (default): Starting up tables.
2022.03.15 14:32:13.947507 [ 1 ] {} <Information> BackgroundSchedulePool: Create BackgroundSchedulePool with 16 threads
2022.03.15 14:32:13.948176 [ 1 ] {} <Information> Application: It looks like the process has no CAP_NET_ADMIN capability, 'taskstats' performance statistics will be disabled. It could happen due to incorrect ClickHouse package installation. You could resolve the problem manually with 'sudo setcap cap_net_admin=+ep /usr/bin/clickhouse'. Note that it will not work on 'nosuid' mounted filesystems. It also doesn't work if you run clickhouse-server inside network namespace as it happens in some containers.
2022.03.15 14:32:13.948212 [ 1 ] {} <Information> Application: It looks like the process has no CAP_SYS_NICE capability, the setting 'os_thread_nice' will have no effect. It could happen due to incorrect ClickHouse package installation. You could resolve the problem manually with 'sudo setcap cap_sys_nice=+ep /usr/bin/clickhouse'. Note that it will not work on 'nosuid' mounted filesystems.
2022.03.15 14:32:13.950341 [ 1 ] {} <Error> Application: Listen [::]:8123 failed: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = DNS error: EAI: -9 (version 20.3.9.70 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
2022.03.15 14:32:13.950672 [ 1 ] {} <Error> Application: Listen [::]:9000 failed: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = DNS error: EAI: -9 (version 20.3.9.70 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
2022.03.15 14:32:13.950951 [ 1 ] {} <Error> Application: Listen [::]:9009 failed: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = DNS error: EAI: -9 (version 20.3.9.70 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
2022.03.15 14:32:13.951219 [ 1 ] {} <Error> Application: Listen [::]:9004 failed: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = DNS error: EAI: -9 (version 20.3.9.70 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
2022.03.15 14:32:13.951330 [ 1 ] {} <Information> Application: Listening for http://0.0.0.0:8123
2022.03.15 14:32:13.951442 [ 1 ] {} <Information> Application: Listening for connections with native protocol (tcp): 0.0.0.0:9000
2022.03.15 14:32:13.951534 [ 1 ] {} <Information> Application: Listening for replica communication (interserver): http://0.0.0.0:9009
2022.03.15 14:32:14.126773 [ 1 ] {} <Information> Application: Listening for MySQL compatibility protocol: 0.0.0.0:9004
2022.03.15 14:32:14.127392 [ 1 ] {} <Information> Application: Available RAM: 3.80 GiB; physical cores: 2; logical cores: 2.
2022.03.15 14:32:14.127416 [ 1 ] {} <Information> Application: Ready for connections.
Include not found: clickhouse_remote_servers
Include not found: clickhouse_compression
```

**Comment by jthomaschewski** [comment]
> I recently upgraded from 20.12.1 -> 21.6.3 -> 22.2.0 and running `docker-compose down -v --remove-orphans` did not help

I think this needs to be run before checking out the new repository.
The issue is, that `--remove-orphans` only removes orphan containers of the same docker-compose project. But as the project name changed, it won't discover/cleanup running containers of the old project.

So running `docker-compose down` while stilling having the old version checked out should stop and remove all containers. Then checking out the new version and upping/running `install.sh` should work

**Comment by chadwhitacre** [comment]
In that case would something like https://github.com/getsentry/self-hosted/pull/1384 address this?

**Comment by chadwhitacre** [comment]
Here goes nothin'. ¯\\\_(ツ)\_/¯

**Comment by jthomaschewski** [comment]
> In that case would something like #1384 address this?

lgtm, I believe this should fix this issue, thanks!
I haven't tested it though as I've upgraded my instances a while ago.
