### ISSUE TITLE
Install process freeze

### ISSUE THREAD

**Issue by x2x4com** [getsentry/self-hosted#1181]
### Version

21.11.0

### Steps to Reproduce

step: Setting up / migrating database ...

terminal freeze and looks install process paused

### Expected Result

▶ Setting up / migrating database ...
Container sentry_onpremise-symbolicator-1  Creating
Container sentry_onpremise-memcached-1  Creating
Container sentry_onpremise-smtp-1  Creating
Container sentry_onpremise-postgres-1  Creating
Container sentry_onpremise-zookeeper-1  Running
Container sentry_onpremise-redis-1  Running
Container sentry_onpremise-clickhouse-1  Running
Container sentry_onpremise-kafka-1  Running
Container sentry_onpremise-snuba-replacer-1  Creating
Container sentry_onpremise-snuba-sessions-consumer-1  Creating
Container sentry_onpremise-snuba-outcomes-consumer-1  Creating
Container sentry_onpremise-snuba-subscription-consumer-events-1  Creating
Container sentry_onpremise-snuba-consumer-1  Creating
Container sentry_onpremise-snuba-subscription-consumer-transactions-1  Creating
Container sentry_onpremise-snuba-transactions-consumer-1  Creating
Container sentry_onpremise-snuba-api-1  Creating
Container sentry_onpremise-symbolicator-1  Created
Container sentry_onpremise-postgres-1  Created
Container sentry_onpremise-snuba-sessions-consumer-1  Created
Container sentry_onpremise-snuba-outcomes-consumer-1  Created
Container sentry_onpremise-snuba-subscription-consumer-events-1  Created
Container sentry_onpremise-snuba-replacer-1  Created
Container sentry_onpremise-snuba-consumer-1  Created
Container sentry_onpremise-snuba-subscription-consumer-transactions-1  Created
Container sentry_onpremise-snuba-api-1  Created
Container sentry_onpremise-memcached-1  Created
Container sentry_onpremise-smtp-1  Created
Container sentry_onpremise-snuba-transactions-consumer-1  Created
Container sentry_onpremise-smtp-1  Starting
Container sentry_onpremise-symbolicator-1  Starting
Container sentry_onpremise-memcached-1  Starting
Container sentry_onpremise-postgres-1  Starting
Container sentry_onpremise-memcached-1  Started
Container sentry_onpremise-postgres-1  Started
Container sentry_onpremise-smtp-1  Started
Container sentry_onpremise-symbolicator-1  Started
Container sentry_onpremise-snuba-transactions-consumer-1  Starting
Container sentry_onpremise-snuba-subscription-consumer-transactions-1  Starting
Container sentry_onpremise-snuba-sessions-consumer-1  Starting
Container sentry_onpremise-snuba-replacer-1  Starting
Container sentry_onpremise-snuba-consumer-1  Starting
Container sentry_onpremise-snuba-outcomes-consumer-1  Starting
Container sentry_onpremise-snuba-subscription-consumer-events-1  Starting
Container sentry_onpremise-snuba-api-1  Starting
Container sentry_onpremise-snuba-transactions-consumer-1  Started
Container sentry_onpremise-snuba-api-1  Started
Container sentry_onpremise-snuba-outcomes-consumer-1  Started
Container sentry_onpremise-snuba-replacer-1  Started
Container sentry_onpremise-snuba-sessions-consumer-1  Started
Container sentry_onpremise-snuba-consumer-1  Started
Container sentry_onpremise-snuba-subscription-consumer-transactions-1  Started
Container sentry_onpremise-snuba-subscription-consumer-events-1  Started
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
Installing additional dependencies...
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

06:48:32 [WARNING] sentry.utils.geo: Error opening GeoIP database: /geoip/GeoLite2-City.mmdb
06:48:32 [WARNING] sentry.utils.geo: Error opening GeoIP database in Rust: /geoip/GeoLite2-City.mmdb
06:48:34 [INFO] sentry.plugins.github: apps-not-configured
Running migrations for default
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, nodestore, sentry, sessions, sites, social_auth
Running migrations:
  Applying sentry.0001_squashed_0200_release_indices... OK
  Applying contenttypes.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying nodestore.0001_initial... OK
  Applying nodestore.0002_nodestore_no_dictfield... OK
  Applying sentry.0201_semver_package... OK
  Applying sentry.0202_org_slug_upper_idx... OK
  Applying sentry.0203_groupedmessage_status_index... OK
  Applying sentry.0204_use_project_team_for_team_key_transactions... OK
  Applying sentry.0205_semver_backfill... OK
  Applying sentry.0206_organization_require_email_verification_flag... OK
  Applying sentry.0207_release_adoption... OK
  Applying sentry.0208_add_team_scope... OK
  Applying sentry.0209_avatar_remove_file_fk... OK
  Applying sentry.0210_backfill_project_transaction_thresholds... OK
  Applying sentry.0211_add_artifact_count... OK
  Applying sentry.0212_appconnectbuilds... OK
  Applying sentry.0213_rule_project_status_owner_index... OK
  Applying sentry.0214_activity_project_type_datetime_idx... OK
  Applying sentry.0215_fix_state... OK
  Applying sentry.0216_cdc_setup_replication_index... OK
  Applying sentry.0217_debugfile_remove_project_fk... OK
  Applying sentry.0218_releasefile_remove_fks... OK
  Applying sentry.0219_exporteddatablob_remove_blob_fk... OK
  Applying sentry.0220_add_current_release_version_group_resolution... OK
  Applying sentry.0221_add_appconnect_upload_dates... OK
  Applying sentry.0222_add_datetime_index_to_auditlogentry... OK
  Applying sentry.0223_semver_backfill_2... OK
  Applying sentry.0224_has_sessions_flag... OK
  Applying sentry.0225_latest_appconnect_builds_check... OK
  Applying sentry.0226_add_visits... OK
  Applying sentry.0227_backfill_visits... OK
  Applying sentry.0228_update_auditlog_index_with_entry... OK
  Applying sentry.0229_drop_jiratenant... OK
  Applying sentry.0230_sentry_app_config_jsonfield... OK
  Applying sentry.0231_alert_rule_comparison_delta... OK
  Applying sentry.0232_backfill_missed_semver_releases... OK
  Applying sentry.0233_recreate_subscriptions_in_snuba... OK
  Applying sentry.0234_grouphistory... OK
  Applying sentry.0235_add_metricskeyindexer_table... OK
  Applying sentry.0236_remove_legacy_key_transactions... OK
  Applying sentry.0237_recreate_subscriptions_in_snuba... OK
  Applying sentry.0238_remove_scheduleddeletion_aborted... OK
  Applying sentry.0239_drop_scheduleddeletion_aborted... OK
  Applying sentry.0240_grouphistory_index... OK
  Applying sentry.0241_grouphistory_null_actor... OK
  Applying sentry.0242_delete_removed_plugin_data... OK
  Applying sentry.0243_delete_visualstudio_repo_data... OK
  Applying sentry.0244_organization_and_integration_foreign_keys... OK
  Applying sentry.0245_delete_itunes_credentials... OK
  Applying sentry.0246_incident_snapshots_remove_fks... OK
  Applying sentry.0247_add_color_column... OK
  Applying sentry.0248_add_popularity_column... OK
  Applying sessions.0001_initial... OK
  Applying sites.0001_initial... OK
  Applying sites.0002_alter_domain_unique... OK
  Applying social_auth.0001_initial... OK
06:49:02 [WARNING] sentry: Cannot initiate onboarding for organization (1) due to missing owners
Created internal Sentry project (slug=internal, id=1)

Would you like to create a user account now? [Y/n]: /usr/local/lib/python3.8/site-packages/sentry/utils/email/list_resolver.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import Mapping
/usr/local/lib/python3.8/site-packages/memcache.py:1303: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key is '':
/usr/local/lib/python3.8/site-packages/memcache.py:1304: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key_extra_len is 0:

### Actual Result

06:49:02 [WARNING] sentry: Cannot initiate onboarding for organization (1) due to missing owners
Created internal Sentry project (slug=internal, id=1)

Would you like to create a user account now? [Y/n]: /usr/local/lib/python3.8/site-packages/sentry/utils/email/list_resolver.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import Mapping
/usr/local/lib/python3.8/site-packages/memcache.py:1303: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key is '':
/usr/local/lib/python3.8/site-packages/memcache.py:1304: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key_extra_len is 0:

then terminal freeze

**Comment by x2x4com** [comment]
OS: aws ami2
Kernel: Linux ip-10-205-100-209.cn-north-1.compute.internal 5.10.75-79.358.amzn2.x86_64 #1 SMP Thu Nov 4 21:08:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Docker: 
Client:
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.15.14
 Git commit:        f0df350
 Built:             Wed Nov 17 03:05:36 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.15.14
  Git commit:       b0f5bc3
  Built:            Wed Nov 17 03:06:14 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0
  GitCommit:        84113eef6fc27af1b01b3181f31bbaf708715301
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
docker-compose:
Docker Compose version v2.1.1

**Comment by x2x4com** [comment]
using option --no-user-prompt when install.sh looks ok

**Comment by chadwhitacre** [comment]
Thanks for the report @x2x4com. I'm folding this into https://github.com/getsentry/self-hosted/issues/1133.
