### ISSUE TITLE
Get all issues for the last 24 hours for instance - endpoint

### ISSUE THREAD

**Issue by Fhjorth** [getsentry/self-hosted#1185]
### Problem Statement

I want to get all the issues from a given periode with an endpoint. so I have tried to use the end point where I get a list of all issues, but it seems to get me all events that have that issue. so I just want to get a list of issues aggregating the events, is that possible?

**Comment by chadwhitacre** [comment]
Have you [read the docs](https://docs.sentry.io/api/events/list-a-projects-issues/), @Fhjorth? :)

**Comment by aminvakil** [comment]
> Have you [read the docs](https://docs.sentry.io/api/events/list-a-projects-issues/), @Fhjorth? :)

And unrelated to this repository :)
