### ISSUE TITLE
Flutter web CORS issues

### ISSUE THREAD

**Issue by jaumard** [getsentry/self-hosted#1188]
_Platform:_
- [ ]  Dart
- [ ]  Flutter Android or iOS
- [*]  Flutter Web

Output of the command `flutter doctor -v` below:

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale fr-FR)
    • Flutter version 2.5.3 at /Users/jaumard/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (7 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4
```

The version of the SDK (See pubspec.lock):
**6.0.1**

---
I have the following issue:

Once an error occurs on flutter web, I'm getting:
```
Access to XMLHttpRequest at 'https://sentry.ah2020.org/api/2/envelope/' from origin 'http://localhost:49673' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.
```

Not sure how/where to fix this...

**Comment by aminvakil** [comment]
Probably related to your reverse proxy which sentry is behind it, try connecting directly to sentry nginx (port 9000) and if it worked correctly, try fixing your proxy.

**Comment by chadwhitacre** [comment]
@jaumard You might also find some tips under https://github.com/getsentry/self-hosted/search?q=cors&type=issues.
