### ISSUE TITLE
Maintenance Guide

### ISSUE THREAD

**Issue by Leopere** [getsentry/self-hosted#1189]
### Problem Statement

I'm not entirely sure how after using the `install.sh` script to prep the server how do I deploy this to a Docker Swarm or how do I maintain this behemoth with no maintenance documentation.

### Solution Brainstorm

Potentially if there is documentation on how to manage this link it in the README.md it's really impressively complex to fathom how to maintain 20 different microservices without breakage.

**Comment by Leopere** [comment]
I discovered the phrase "visit our documentation for everything else" which doesn't really allude to there being any plans for Upgrades and regular Maintenance in the docs.

**Comment by chadwhitacre** [comment]
Thanks for weighing in, @Leopere.

> how do I deploy this to a Docker Swarm

That's out of scope for this repo. If you need help deploying to Docker Swarm then our recommendation is that you [use our SaaS offering](https://sentry.io/signup/) as we take care of the hosting for you. :)

This repo is for simple single-node deployments.

**Comment by chadwhitacre** [comment]
Sorry for the surprise. We try to be up-front about our intentions on the repo:

<img width="335" alt="Screen Shot 2021-12-06 at 1 15 23 PM" src="https://user-images.githubusercontent.com/134455/144900023-ecfa5a93-97fc-43a2-adca-a31dae02c5cb.png">

and in our dev docs:

<img width="554" alt="Screen Shot 2021-12-06 at 1 16 08 PM" src="https://user-images.githubusercontent.com/134455/144900098-e26dfb9f-db4c-43dc-8b93-1cbf95e6a3ae.png">

---------------

If there is some additional way we can make this clearer up front please let us know. :)
