### ISSUE TITLE
owner role does not see /manage/ content

### ISSUE THREAD

**Issue by shimon-elbaz** [getsentry/self-hosted#1190]
### Version

21.11.0

### Steps to Reproduce

1. install a selfhosted sentry
2. setup SSO with a google account
3. connect a user and give it "Owner" permissions
4. access any of the subpages in /manage/

### Expected Result

owner will be able to access settings.

### Actual Result

the following error is shown:

"Your role does not have the necessary permissions to access this resource, please read more about organizational roles"

**Comment by aminvakil** [comment]
Try https://YOUR_INSTANCE/manage/users/ and give the user `admin` privileges.

**Comment by shimon-elbaz** [comment]
i get an empty list and the following text: "Something bad happened :("

**Comment by aminvakil** [comment]
Try with an already admin user, not the one you want to give permissions.

**Comment by shimon-elbaz** [comment]
same

**Comment by aminvakil** [comment]
What about the user you created during creation of sentry? (superuser)

**Comment by shimon-elbaz** [comment]
It was a local one and not an sso one, so i cannot connect with it.
Also, it was removed from the syatem (since there was no way to connect).

Can i make my user a superuser via the cli?
Btw, the auperuser was shown as owner as well - i would expect any ither
owner to be a superuser.

**Comment by aminvakil** [comment]
Owner / Admin / Superuser, there are three different roles and have different privileges.

> Owner
Unrestricted access to the organization, its data, and its settings. Can add, modify, and delete projects and members, as well as make billing and plan changes.

> Admin
Admin privileges on any teams of which they're a member. They can create new teams and projects, as well as remove teams and projects on which they already hold membership (or all teams, if open membership is enabled). Additionally, they can manage memberships of teams that they are members of. They cannot invite members to the organization.

> Superuser
Designates whether this user has all permissions without explicitly assigning them.

And as for forgetting superuser password, you may try changing django username / passwords directly, creating superuser, etc. But I don't have any idea how to do it properly so something else does not break.

**Comment by shimon-elbaz** [comment]
can i enable my user via the database?

**Comment by aminvakil** [comment]
> can i enable my user via the database?

Yes.

**Comment by shimon-elbaz** [comment]
can you please direct me to the correct table?

**Comment by chadwhitacre** [comment]
Good find @shimon-elbaz, thanks for posting back for others to find in the future. :)
