### ISSUE TITLE
How to cleanup the volume of sentry-data 

### ISSUE THREAD

**Issue by duyuyouci** [getsentry/self-hosted#1192]
### Version

21.11.0.dev0

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/39803418/144960879-3fd0261b-1cdd-4da4-a130-fa34a8bd8c49.png)

### Expected Result

console start the replay, the volume of sentry-data keep getting bigger

### Actual Result

How to cleanup the volume of sentry-data

**Comment by aminvakil** [comment]
There is `SENTRY_EVENT_RETENTION_DAYS=90` in `.env` by default, you can change it, so it keeps less days.
