### ISSUE TITLE
Relay server connection closing to web

### ISSUE THREAD

**Issue by jpyams** [getsentry/self-hosted#1201]
### Version

21.11.0

### Steps to Reproduce

1. git clone the self-hosted repo
2. Basic SMTP configuration in sentry/config.yml
3. Run `./install.sh`
4. Run `docker-compose up -d`

### Expected Result

Sentry launches and issues are reported.

### Actual Result

No errors ever reach Sentry.  The relay server spits out continuous messages identical to the following:

```
relay_1                                     | 2021-12-14T23:15:45Z [relay_server::actors::upstream] WARN: Network outage, scheduling another check in 17.0859375s
relay_1                                     | 2021-12-14T23:15:48Z [relay_server::actors::upstream] INFO: registering with upstream (http://web:9000/)
relay_1                                     | 2021-12-14T23:15:48Z [relay_server::actors::upstream] ERROR: authentication encountered error: could not send request to upstream
relay_1                                     |   caused by: error sending request for url (http://web:9000/api/0/relays/register/challenge/): connection closed before message completed
relay_1                                     | 2021-12-14T23:15:48Z [relay_server::actors::upstream] DEBUG: scheduling authentication retry in 25 seconds
```

**Comment by chadwhitacre** [comment]
> Basic SMTP configuration in sentry/config.yml

Why is this relevant?

> No errors ever reach Sentry.

🤔

> The relay server spits out continuous messages identical to the following:

Could be the culprit ... seems like a problem reaching http://web:9000/ from the relay container. Can you get a shell in the relay container and try reaching http://web:9000/? Any clues there?

**Comment by aminvakil** [comment]
Maybe some firewall dropping/rejecting between containers?

I know default `firewalld` rules in CentOS 8 (RIP) did this, but I'm not sure if that was applicable to containers in the same network created by `docker-compose`, but worth checking.

**Comment by jpyams** [comment]
> > Basic SMTP configuration in sentry/config.yml
> 
> Why is this relevant?

I don't think it is, I just wanted to be comprehensive.  You never know.

> Could be the culprit ... seems like a problem reaching http://web:9000/ from the relay container. Can you get a shell in the relay container and try reaching http://web:9000/? Any clues there?

I can ping `web` from within the container, and it found it fine.  I'll try running a curl on `web:9000`.

> Maybe some firewall dropping/rejecting between containers?

Will check.  This is an Ubuntu 20.04 install.

**Comment by jpyams** [comment]
Discovered the issue.  I have the $http_proxy and $HTTPS_PROXY variables set in docker, which interfered with HTTP requests between containers.  I added 'web' to the $no_proxy in `~/.docker/config.json`, and that has resolved the issue.

**Comment by chadwhitacre** [comment]
Thanks for closing the loop @jpyams, glad you got it sorted! 👍
