### ISSUE TITLE
force internal project DSN to be the same

### ISSUE THREAD

**Issue by matti** [getsentry/self-hosted#1210]
### Problem Statement

_integration_test/run.sh has complex fetching of DSN name of the internal project. For testing scenarios it would be better to have an option to set always set this to a predefined value

**Comment by chadwhitacre** [comment]
I guess 4e62380084c6a4e790a1696932e787ade9e6331c is how you're doing this @matti?

**Comment by matti** [comment]
actually I went further and skipped the whole internal project. Now I have a set of projects that always get created with same DSNs and IDs so that I can reinstall sentry from scratch and just keep sending data. I do loose all the existing data, but I dont really care avout that, see:

https://github.com/matti/sentry-self-hosted-tools/blob/main/project-create-static.py

and ec2 userdata at:

https://github.com/matti/sentry-self-hosted-tools/blob/main/userdata.sh

**Comment by chadwhitacre** [comment]
Nice, glad you found a workaround. Do we still need this ticket, then?

**Comment by matti** [comment]
no
