### ISSUE TITLE
Revert stick migration for sentry

### ISSUE THREAD

**Issue by ingtarius** [getsentry/self-hosted#1212]
### Environment

How do you use Sentry?
self-hosted/on-premise (21.11.0) updated fron 21.6.0

1) Run migration from snuba container:  snuba migrations migrate --force
2) Abort migration (too long, connection was broked)
3) See list of migrations:

> transactions
[X]  0001_transactions
[X]  0002_transactions_onpremise_fix_orderby_and_partitionby
[X]  0003_transactions_onpremise_fix_columns
[X]  0004_transactions_add_tags_hash_map
[X]  0005_transactions_add_measurements
[X]  0006_transactions_add_http_fields
[X]  0007_transactions_add_discover_cols
[X]  0008_transactions_add_timestamp_index
[X]  0009_transactions_fix_title_and_message
[X]  0010_transactions_nullable_trace_id
[X]  0011_transactions_add_span_op_breakdowns
[-]  0012_transactions_add_spans (IN PROGRESS)

But no changes in clickhouse. I reboot clickhouse, try to re-run migrations - no changes.
`snuba.migrations.errors.MigrationInProgress: transactions: 0012_transactions_add_spans`
How to re-run this stick migration?
I cant revert it with error
>2021-11-25 14:13:02,195 Reversing migration: 0012_transactions_add_spans
/usr/local/lib/python3.8/site-packages/clickhouse_driver/columns/datetimecolumn.py:207: PytzUsageWarning: The zone attribute is specific to pytz's interface; please migrate to a new time zone provider. For more details on how to do so, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  local_timezone = get_localzone().zone
Traceback (most recent call last):
  File "/usr/src/snuba/snuba/clickhouse/native.py", line 87, in execute
    result: Sequence[Any] = conn.execute(
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 220, in execute
    rv = self.process_ordinary_query(
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 346, in process_ordinary_query
    return self.receive_result(with_column_types=with_column_types,
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 89, in receive_result
    return result.get_result()
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/result.py", line 50, in get_result
    for packet in self.packet_generator:
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 101, in packet_generator
    packet = self.receive_packet()
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 118, in receive_packet
    raise packet.exception
clickhouse_driver.errors.ServerException: Code: 341.
DB::Exception: Exception happened during execution of mutation 'mutation_10740798.txt' with part '90-20210830_6701240_7697362_186_10739730' reason: 'Code: 47, e.displayText() = DB::Exception: Missing columns: 'spans.group' 'spans.op' 'spans.exclusive_time' while processing query: 'user_name, `spans.exclusive_time`, `span_op_breakdowns.value`, _contexts_flattened, user_hash, timestamp, ip_address_v4, offset, retention_days, `spans.op`, message_timestamp, user, release, start_ms, dist, `span_op_breakdowns.key`, trace_id, `spans.group`, http_referer, `contexts.key`, transaction_status, transaction_hash, sdk_name, user_id, platform, project_id, finish_ts, ip_address_v6, transaction_op, duration, `contexts.value`, title, start_ts, `tags.key`, user_email, span_id, environment, `measurements.value`, `tags.value`, http_method, partition, sdk_version, _tags_flattened, type, `measurements.key`, transaction_name, deleted, finish_ms, message', required columns: 'span_op_breakdowns.value' 'spans.exclusive_time' 'user_hash' '_contexts_flattened' 'user_name' 'ip_address_v4' 'timestamp' 'offset' 'retention_days' 'message_timestamp' 'spans.op' 'start_ms' 'user' 'release' 'span_op_breakdowns.key' 'dist' 'spans.group' 'trace_id' 'http_referer' 'transaction_status' 'contexts.key' 'sdk_name' 'transaction_hash' 'ip_address_v6' 'user_id' 'platform' 'project_id' 'finish_ts' 'transaction_op' 'duration' 'contexts.value' 'title' 'start_ts' 'tags.key' 'user_email' 'span_id' 'environment' 'partition' 'http_method' 'tags.value' 'measurements.value' '_tags_flattened' 'type' 'sdk_version' 'measurements.key' 'message' 'finish_ms' 'deleted' 'transaction_name', maybe you meant:  '['span_op_breakdowns.value']' '['user_hash']' '['_contexts_flattened']' '['user_name']' '['ip_address_v4']' '['timestamp']' '['offset']' '['retention_days']' '['message_timestamp']' '['start_ms']' '['user']' '['release']' '['span_op_breakdowns.key']' '['dist']' '['trace_id']' '['http_referer']' '['transaction_status']' '['contexts.key']' '['sdk_name']' '['transaction_hash']' '['ip_address_v6']' '['user_id']' '['platform']' '['project_id']' '['finish_ts']' '['transaction_op']' '['duration']' '['contexts.value']' '['title']' '['start_ts']' '['tags.key']' '['user_email']' '['span_id']' '['environment']' '['partition']' '['http_method']' '['tags.value']' '['measurements.value']' '['_tags_flattened']' '['type']' '['sdk_version']' '['measurements.key']' '['message']' '['finish_ms']' '['deleted']' '['transaction_name']' (version 21.2.5.5 (official build))'. This error maybe retryable or not. In case of unretryable error, mutation can be killed with KILL MUTATION query. Stack trace:

0. DB::Exception::Exception<char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&>(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) @ 0xf405961 in /usr/bin/clickhouse
1. DB::checkMutationStatus(std::__1::optional<DB::MergeTreeMutationStatus>&, std::__1::set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xf4057e8 in /usr/bin/clickhouse
2. DB::StorageMergeTree::waitForMutation(long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xf0ee7c1 in /usr/bin/clickhouse
3. DB::StorageMergeTree::alter(DB::AlterCommands const&, DB::Context const&, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>&) @ 0xf0eda4e in /usr/bin/clickhouse
4. DB::InterpreterAlterQuery::execute() @ 0xe9c9a46 in /usr/bin/clickhouse
5. ? @ 0xeeb8e62 in /usr/bin/clickhouse
6. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0xeeb77bc in /usr/bin/clickhouse
7. DB::TCPHandler::runImpl() @ 0xf5b2785 in /usr/bin/clickhouse
8. DB::TCPHandler::run() @ 0xf5c2409 in /usr/bin/clickhouse
9. Poco::Net::TCPServerConnection::start() @ 0x11b5fe2f in /usr/bin/clickhouse
10. Poco::Net::TCPServerDispatcher::run() @ 0x11b61841 in /usr/bin/clickhouse
11. Poco::PooledThread::run() @ 0x11c988e9 in /usr/bin/clickhouse
12. Poco::ThreadImpl::runnableEntry(void*) @ 0x11c9474a in /usr/bin/clickhouse
13. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
14. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/migrations.py", line 160, in reverse
    runner.reverse_migration(migration_key, force=force, fake=fake)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 260, in reverse_migration
    self._reverse_migration_impl(migration_key)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 272, in _reverse_migration_impl
    migration.backwards(context, dry_run)
  File "/usr/src/snuba/snuba/migrations/migration.py", line 162, in backwards
    op.execute(local=True)
  File "/usr/src/snuba/snuba/migrations/operations.py", line 29, in execute
    connection.execute(self.format_sql())
  File "/usr/src/snuba/snuba/clickhouse/native.py", line 112, in execute
    raise ClickhouseError(e.message, code=e.code) from e
snuba.clickhouse.errors.ClickhouseError: DB::Exception: Exception happened during execution of mutation 'mutation_10740798.txt' with part '90-20210830_6701240_7697362_186_10739730' reason: 'Code: 47, e.displayText() = DB::Exception: Missing columns: 'spans.group' 'spans.op' 'spans.exclusive_time' while processing query: 'user_name, `spans.exclusive_time`, `span_op_breakdowns.value`, _contexts_flattened, user_hash, timestamp, ip_address_v4, offset, retention_days, `spans.op`, message_timestamp, user, release, start_ms, dist, `span_op_breakdowns.key`, trace_id, `spans.group`, http_referer, `contexts.key`, transaction_status, transaction_hash, sdk_name, user_id, platform, project_id, finish_ts, ip_address_v6, transaction_op, duration, `contexts.value`, title, start_ts, `tags.key`, user_email, span_id, environment, `measurements.value`, `tags.value`, http_method, partition, sdk_version, _tags_flattened, type, `measurements.key`, transaction_name, deleted, finish_ms, message', required columns: 'span_op_breakdowns.value' 'spans.exclusive_time' 'user_hash' '_contexts_flattened' 'user_name' 'ip_address_v4' 'timestamp' 'offset' 'retention_days' 'message_timestamp' 'spans.op' 'start_ms' 'user' 'release' 'span_op_breakdowns.key' 'dist' 'spans.group' 'trace_id' 'http_referer' 'transaction_status' 'contexts.key' 'sdk_name' 'transaction_hash' 'ip_address_v6' 'user_id' 'platform' 'project_id' 'finish_ts' 'transaction_op' 'duration' 'contexts.value' 'title' 'start_ts' 'tags.key' 'user_email' 'span_id' 'environment' 'partition' 'http_method' 'tags.value' 'measurements.value' '_tags_flattened' 'type' 'sdk_version' 'measurements.key' 'message' 'finish_ms' 'deleted' 'transaction_name', maybe you meant:  '['span_op_breakdowns.value']' '['user_hash']' '['_contexts_flattened']' '['user_name']' '['ip_address_v4']' '['timestamp']' '['offset']' '['retention_days']' '['message_timestamp']' '['start_ms']' '['user']' '['release']' '['span_op_breakdowns.key']' '['dist']' '['trace_id']' '['http_referer']' '['transaction_status']' '['contexts.key']' '['sdk_name']' '['transaction_hash']' '['ip_address_v6']' '['user_id']' '['platform']' '['project_id']' '['finish_ts']' '['transaction_op']' '['duration']' '['contexts.value']' '['title']' '['start_ts']' '['tags.key']' '['user_email']' '['span_id']' '['environment']' '['partition']' '['http_method']' '['tags.value']' '['measurements.value']' '['_tags_flattened']' '['type']' '['sdk_version']' '['measurements.key']' '['message']' '['finish_ms']' '['deleted']' '['transaction_name']' (version 21.2.5.5 (official build))'. This error maybe retryable or not. In case of unretryable error, mutation can be killed with KILL MUTATION query. Stack trace:

0. DB::Exception::Exception<char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&>(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) @ 0xf405961 in /usr/bin/clickhouse
1. DB::checkMutationStatus(std::__1::optional<DB::MergeTreeMutationStatus>&, std::__1::set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xf4057e8 in /usr/bin/clickhouse
2. DB::StorageMergeTree::waitForMutation(long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xf0ee7c1 in /usr/bin/clickhouse
3. DB::StorageMergeTree::alter(DB::AlterCommands const&, DB::Context const&, std::__1::shared_ptr<DB::RWLockImpl::LockHolderImpl>&) @ 0xf0eda4e in /usr/bin/clickhouse
4. DB::InterpreterAlterQuery::execute() @ 0xe9c9a46 in /usr/bin/clickhouse
5. ? @ 0xeeb8e62 in /usr/bin/clickhouse
6. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool) @ 0xeeb77bc in /usr/bin/clickhouse
7. DB::TCPHandler::runImpl() @ 0xf5b2785 in /usr/bin/clickhouse
8. DB::TCPHandler::run() @ 0xf5c2409 in /usr/bin/clickhouse
9. Poco::Net::TCPServerConnection::start() @ 0x11b5fe2f in /usr/bin/clickhouse
10. Poco::Net::TCPServerDispatcher::run() @ 0x11b61841 in /usr/bin/clickhouse
11. Poco::PooledThread::run() @ 0x11c988e9 in /usr/bin/clickhouse
12. Poco::ThreadImpl::runnableEntry(void*) @ 0x11c9474a in /usr/bin/clickhouse
13. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
14. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so

**Comment by chadwhitacre** [comment]
Did you ever sort this out @ingtarius? Sorry this slipped through the cracks. :-/
