### ISSUE TITLE
我想在树莓派4b上部署这个，但是我没有找到可行的方案

### ISSUE THREAD

**Issue by w934423231** [getsentry/self-hosted#1220]
### Problem Statement

我想在树莓派4b上部署这个，但是我没有找到可行的方案

**Comment by aminvakil** [comment]
In English Please.

**Comment by w934423231** [comment]
I want to buy raspberry pie to deploy this, but I don't know how to implement it.

**Comment by aminvakil** [comment]
I've found this **non-official** fork for ARM based systems (https://github.com/Sentry-ARM/onpremise)

Of course it's unsupported here, and I don't know if it works, it gets updated, if an update breaks it ...

**Comment by w934423231** [comment]
OK, I'll try it tomorrow. I wonder if there will be any operation supporting raspberry pie in the later official period?

**Comment by aminvakil** [comment]
I don't work for @getsentry, but I doubt if there will be.

**Comment by w934423231** [comment]
Thank you for your answer

**Comment by chadwhitacre** [comment]
@w934423231 You can follow along on #914, though as @aminvakil suggests it's not a priority for us.

**Comment by w934423231** [comment]
OK, I'll pay attention to this. Thank you for helping me answer these questions
