### ISSUE TITLE
Uploading and Sourcemaps not working

### ISSUE THREAD

**Issue by teebu** [getsentry/self-hosted#1232]
### Version

21.8

### Steps to Reproduce

Using the helm chart provided by https://github.com/sentry-kubernetes/charts/tree/develop/sentry 
I have enabled S3 as the storage.

I can upload files through the sentry page, and can verify the avatar upload is working. However, the source maps are still not loading. I'm submitting them through the CLI sentry-cli releases -p myproj files

sentry-cli releases new $RELEASE_NAME
sentry-cli releases set-commits --auto $RELEASE_NAME
sentry-cli releases files $RELEASE_NAME upload-sourcemaps --validate /work/dist/my-project-name
sentry-cli releases finalize $RELEASE_NAME

### Expected Result

I should be able to download artifacts uploaded by the cli. 

![image](https://user-images.githubusercontent.com/5531844/147797321-316c1e4b-888e-4e60-b90b-bd83d2a2d404.png)

![image](https://user-images.githubusercontent.com/5531844/147797331-92406317-8b9c-442e-b663-719709d1c32b.png)

### Actual Result

I see some files in the s3 bucket, however sentry is throwing s3 GetObject error when I try to download the artifacts from the frontend.

![image](https://user-images.githubusercontent.com/5531844/147797287-104090de-2224-48c5-aa86-8e5be43a1bb2.png)
![image](https://user-images.githubusercontent.com/5531844/147797292-98f0e944-d214-4876-9442-b68a6a2b04bb.png)

I brought this issue up here https://github.com/sentry-kubernetes/charts/issues/538

**Comment by chadwhitacre** [comment]
> I brought this issue up here sentry-kubernetes/charts#538

That's the right place to ask. If you can repro with stock `self-hosted`, let us know. Closing for now. Good luck! :-)

**Comment by teebu** [comment]
Thanks @chadwhitacre. While im waiting on a response there, can you point me to a log i can look at to help me further investigate this? Nothing seems to be screaming out at me.
