### ISSUE TITLE
Set[Allow JavaScript Source Fetching] is false, How can I sourcemap support?

### ISSUE THREAD

**Issue by yigeyi** [getsentry/self-hosted#1237]
### Version

21.0.0

### Steps to Reproduce

If I set [Allow JavaScript Source Fetching] is false，does that mean I can't use source mapping 。Because I read Blog that enabling sourceMap causes SSRF attacks，So I saw that I could turn it off 。But I also want the source map, is it two can only choose one ？ thanks

### Expected Result

I want to have source maps that block SSRF

### Actual Result

Right now it looks like one of two

**Comment by chadwhitacre** [comment]
Hmm ... maybe someone from @getsentry/team-webplatform can comment? 🤔

**Comment by yigeyi** [comment]
你好，蔡奕俊已经收到你的邮件，我会尽快查看并回复。

**Comment by chadwhitacre** [comment]
lol ... I googled "ssrf sourcemaps" and got this issue. 😂

<img width="828" alt="Screen Shot 2022-01-04 at 11 11 24 AM" src="https://user-images.githubusercontent.com/134455/148088956-8ff9017c-fff6-4b4b-9089-52dadd6aba53.png">

**Comment by chadwhitacre** [comment]
Can you link the blog post you found, @yigeyi?

**Comment by AbhiPrasad** [comment]
If you turn off JavaScript source fetching, we recommend you upload your source maps to Sentry directly. See our [documentation around source maps for more details](https://docs.sentry.io/platforms/javascript/sourcemaps/#2-provide-source-maps-to-sentry). You can upload source maps with [Sentry's Webpack Plugin](https://docs.sentry.io/platforms/javascript/sourcemaps/uploading/webpack/) or with our [`sentry-cli`](https://docs.sentry.io/platforms/javascript/sourcemaps/uploading/cli/) tool.
