### ISSUE TITLE
Upgrade error from 21.3.0 to 21.6.3

### ISSUE THREAD

**Issue by maxp1256** [getsentry/self-hosted#1238]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

21.3.0 1a6acd6

### Steps to Reproduce

I want to upgrade from current 21.3.0 with (or without) the intermediate step 21.6.3 as suggested:
```
SENTRY_IMAGE=getsentry/sentry:7345c40
./install.sh
```

But I'm getting the following error ...

### Expected Result

Successful upgrade to 21.6.0 or 21.12

### Actual Result

/usr/local/lib/python3.8/site-packages/sentry/utils/strings.py:44: DeprecationWarning: invalid escape sequence '\['
return value.encode("ascii", "backslashreplace").decode( 

/usr/local/lib/python3.8/site-packages/memcache.py:1303: SyntaxWarning: "is" with a literal. Did you mean "=="?
if key is '':
/usr/local/lib/python3.8/site-packages/memcache .py:1304: SyntaxWarning: "is" with a literal. Did you mean "=="?
h a literal. Did you mean 
if key extra_len is 0: 
09:11:47 [INFO] sentry.pluginl.github: apps-not-configured
Error: It looks like you've skipped a hard stop in our upgrade process. Please follow the upgrade process here: https://develop.sentry.dev/self-hosted/releases/#hard-stops 
An error occurred, caught SIGERR on line 332 
Cleaning up.

**Comment by chadwhitacre** [comment]
@maxp1256 The warnings should be spurious (and fixed under https://github.com/getsentry/self-hosted/issues/1162). Can you try going through 21.5.0 before going to 21.6.3? Yes this is not what [the docs](https://develop.sentry.dev/self-hosted/releases/#hard-stops) indicate, but https://github.com/getsentry/self-hosted/issues/1149#issuecomment-970530585 suggests this should work (and I remember having some conversation about the docs before and it's fairly subtle and I'd have to revisit to be confident).

**Comment by chadwhitacre** [comment]
Hrm, in #1149 they were starting from 10.x, though, not 21.3.0. 🤔

Oh! The error message you're hitting wasn't introduced until after 21.6.3, in getsentry/sentry#26714 (cf. `upgrade.py` in [21.6.3](https://github.com/getsentry/sentry/blob/21.6.3/src/sentry/runner/commands/upgrade.py#L9) and [21.7.0](https://github.com/getsentry/sentry/blob/21.7.0/src/sentry/runner/commands/upgrade.py#L43)). Therefore, I hypothesize that your working copy is at a later revision than the version you're intending to install. Are you doing a `git checkout` in addition to setting `SENTRY_IMAGE`?

```
git checkout 21.6.3
SENTRY_IMAGE=getsentry/sentry:21.6.3
./install.sh
```

**Comment by chadwhitacre** [comment]
In fact, explicitly setting `SENTRY_IMAGE` should be unnecessary, since on release tags the value is set in `.env` to the current version for the release, e.g.:

https://github.com/getsentry/self-hosted/blob/21.3.0/.env#L6
https://github.com/getsentry/self-hosted/blob/21.6.3/.env#L6

**Comment by maxp1256** [comment]
I'm sorry for the late response. Meanwhile I've successfully upgraded in two steps to 21.6.3 and 22.1. My fault was, that I didn't checked out the onpremise setup before running install.sh (thought that it will be done automatically).

It was necessary to stop&kill the docker instances before with `docker-compose down` and `docker stop $(docker ps -q)` because otherwise there were some unhealthy docker instances which prevented the upgrade.

**Comment by chadwhitacre** [comment]
Thanks for reporting back @maxp1256.

>  I didn't checked out the onpremise setup before running install.sh (thought that it will be done automatically).

The automation is actually the other way, if you `git checkout X.Y.Z` then there is no need to explicitly set `SENTRY_IMAGE`, so the way to upgrade is:

```
$ git checkout X.Y.Z
$ ./install.sh
```

As to the unhealthy docker instances, we are discussing on https://github.com/getsentry/self-hosted/issues/1178 if you'd like to weigh in.
