### ISSUE TITLE
install.sh error

### ISSUE THREAD

**Issue by pumpkindev** [getsentry/self-hosted#1242]
### Version

21.12.0

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/21173134/148322033-011ec586-253c-4d8b-8086-603bb1dbefe8.png)
![image](https://user-images.githubusercontent.com/21173134/148322427-73d3e6e7-eba6-4dfd-b7be-609d3e00d484.png)

### Expected Result

install success

### Actual Result

./install/_lib.sh: line 6: syntax error near unexpected token `>'

**Comment by aminvakil** [comment]
Maybe try `brew install coreutils` to be able to use `realpath`?

It should be ran with `bash` nonetheless.

**Comment by chadwhitacre** [comment]
We do have https://github.com/getsentry/self-hosted/issues/941 to track the `realpath` issue, `coreutils` is the workaround, yes.

Not sure what's up with the syntax error, here's the line:

https://github.com/getsentry/self-hosted/blob/8cdae78e40283dc1d0e351311e871f1698df3ee4/install/_lib.sh

What does `which -a sh` show?
