### ISSUE TITLE
Can not install Azure DevOps Integration

### ISSUE THREAD

**Issue by furlongmatt** [getsentry/self-hosted#1243]
### Version

21.12.0

### Steps to Reproduce

Click through the following link tree:
⚙ Settings ➡ Integrations ➡ Azure DevOps ➡ Add Installation

### Expected Result

Azure DevOps integration would be enabled

### Actual Result

_This was recorded on 21.10 (we upgraded this morning to 21.12.0)_
![sentry-devops-integration-issue](https://user-images.githubusercontent.com/79411748/148408172-f49d7b01-5936-4268-8387-4a283f2baa4f.gif)

**Comment by chadwhitacre** [comment]
https://docs.sentry.io/product/integrations/source-code-mgmt/azure-devops/

Hmmm ... seems like a misconfiguration somewhere. 🤔

Do you have any overrides in your `sentry/config.yml` that might be relevant?

If you can't find anything from that direction then one idea would be to grep the [codebase](https://github.com/getsentry/sentry) for `Add Installation` and see if you can figure out what setting is gummed up.

**Comment by chadwhitacre** [comment]
Like, it seems like it's opening the wrong URL in the popup window. Why?

**Comment by furlongmatt** [comment]
> https://docs.sentry.io/product/integrations/source-code-mgmt/azure-devops/
> 
> Hmmm ... seems like a misconfiguration somewhere. 🤔
> 
> Do you have any overrides in your `sentry/config.yml` that might be relevant?
> 
> If you can't find anything from that direction then one idea would be to grep the [codebase](https://github.com/getsentry/sentry) for `Add Installation` and see if you can figure out what setting is gummed up.

The only thing I have added to my `sentry/config.yml` is:
`# Azure DevOps #
vsts.client-id: REDACTED
vsts.client-secret: REDACTED`

**Comment by wickettc** [comment]
I am actually having the exact same issue and cannot seem to find any more info in the docs about what could be causing this. My sentry/config.yml is the exact same. The only thing else I could add is that sentry is up and running as intended and receiving info from the connected apps, azure integration is the only thing not working.
 Would love to know if you found the solution? @chadwhitacre or @furlongmatt

**Comment by chadwhitacre** [comment]
I don't have a solution, but I'm happy to be a rubber duck. :)

Maybe it's something in the networking? Have you inspected with browser dev tools to see what is getting loaded in that popup? Is there a redirect happening that gives a clue?

**Comment by furlongmatt** [comment]
> I don't have a solution, but I'm happy to be a rubber duck. :)
> 
> Maybe it's something in the networking? Have you inspected with browser dev tools to see what is getting loaded in that popup? Is there a redirect happening that gives a clue?

@chadwhitacre - here are the results of the inspection from immediately after I click `Add Installation`. Let me know if you need/want more.

![Add Installation Inspection](https://i.imgur.com/ebc0u8L.png)

**setup/**
https://devlogging.[REDACTED].com/organizations/sentry/integrations/vsts/setup/?

**authorize?client_id=**
https://devlogging.[REDACTED].com/oauth2/authorize?client_id=3E67BF2E-A362-4215-85DF-2663AE9BF53A&response_type=code&scope=vso.code+vso.graph+vso.serviceendpoint_manage+vso.work_write&state=70d97e05ffb54fb6a5253ec92d340418&redirect_uri=https://devlogging.[REDACTED].com/extensions/vsts/setup/

**?client_id=**
https://devlogging.[REDACTED].com/oauth2/authorize/?client_id=3E67BF2E-A362-4215-85DF-2663AE9BF53A&response_type=code&scope=vso.code+vso.graph+vso.serviceendpoint_manage+vso.work_write&state=70d97e05ffb54fb6a5253ec92d340418&redirect_uri=https://devlogging.[REDACTED].com/extensions/vsts/setup/

**login/**
https://devlogging.[REDACTED].com/auth/login/

**issues/**
https://devlogging.[REDACTED].com/organizations/sentry/issues/

Hopefully, this is helpful. Also @wickettc welcome to the party! :partying_face:

**Comment by chadwhitacre** [comment]
Yeah those redirects into an auth flow suggest a permissions problem. I find this [in the docs](https://docs.sentry.io/product/integrations/source-code-mgmt/azure-devops/):

> To install this integration, Sentry organization owner, manager, or admin permissions and Azure organization owner permissions or being a user in the Project Collections Administrators group are required.

Are those conditions satisfied?
