### ISSUE TITLE
How do I modify the Sentry Management Background Web UI

### ISSUE THREAD

**Issue by yigeyi** [getsentry/self-hosted#1245]
### Version

21.11.0

### Steps to Reproduce

**English description：**
Hello, everyone. I am deployed on my own server through Docker in my company using Self-hosted.  Now I want to make some changes to the HTML interface of the admin background, such as changing some button colors or adding functions to the front interface.  But I see all docker images after deployment.  How can I modify the front-end interface?  

**中文描述：**
大家好。 我通过Docker部署在我自己的服务器上，使用Self-hosted。 现在，我想对管理后台的HTML界面做一些更改，例如更改一些按钮的颜色或向前端界面添加功能。 但我看到所有的docker 镜像。 如何修改前端界面？

### Expected Result

**English description：**
I want to be able to modify the UI interface of the admin background, because I need to customize some functions in it.  

**中文描述：**
我希望能够对管理后台的UI界面进行修改，因为我要定制一些功能在里边。

### Actual Result

![image](https://user-images.githubusercontent.com/28527224/148540488-f632ecd2-ed44-427a-82cd-e831b20de245.png)

I'm talking about the admin background interface

我说的就是这个管理后台的界面

**Comment by chadwhitacre** [comment]
If you want to modify Sentry, your best bet is to fork the [`sentry`](https://github.com/getsentry/sentry) repo and implement your changes in your fork. Here are the docs for setting up [a local development environment](https://develop.sentry.dev/). You can probably still use `self-hosted` for deployment by setting [`SENTRY_IMAGE`](https://develop.sentry.dev/continuous-integration/#docker-images) (in [`.env.custom`](https://develop.sentry.dev/self-hosted/#configuration)) to a Docker image of your fork that you build and host yourself.

If you think your changes would be valuable to others you can [suggest them to our product team(s)](https://github.com/getsentry/sentry/issues/new?assignees=&labels=&template=feature.yml) in the `sentry` repo.

Good luck! :)

**Comment by yigeyi** [comment]
> 如果你想修改 Sentry，最好的办法是分叉[`sentry`](https://github.com/getsentry/sentry)repo 并在你的分叉中实现你的更改。以下是设置[本地开发环境](https://develop.sentry.dev/)的文档。您可能仍然可以`self-hosted`通过将[`SENTRY_IMAGE`](https://develop.sentry.dev/continuous-integration/#docker-images)(in [`.env.custom`](https://develop.sentry.dev/self-hosted/#configuration))设置为您自己构建和托管的 fork 的 Docker 映像来用于部署。
> 
> 如果您认为您的更改对其他人有价值，您可以在repo中将[它们推荐给我们的产品团队](https://github.com/getsentry/sentry/issues/new?assignees=&labels=&template=feature.yml)`sentry`。
> 
> 祝你好运！:)

Thank you, chadwhitacre. I will try. If I still don't understand, I still need to ask you.
