### ISSUE TITLE
 Oops! Something went wrong ，500 Internal Server Error

### ISSUE THREAD

**Issue by zhuangdl** [getsentry/self-hosted#1250]
### Environment

self-hosted (`onpremise` deployment)

### Version

21.10.0

### Steps to Reproduce

hello!
python 3.6
pip3 install sentry
postgresql 10
redis-cli 3.2.8

### Expected Result

i don't know how to resolve this problem，thank you!

### Actual Result

![飞书20211112-165247](https://user-images.githubusercontent.com/42343587/141441409-01d28493-cfa2-4c9f-a38b-07a58ff76c21.png)
![飞书20211112-165243](https://user-images.githubusercontent.com/42343587/141441379-281d25e4-c3a0-4cec-8020-942753e30158.png)
![飞书20211112-165251](https://user-images.githubusercontent.com/42343587/141442066-dcb5454b-3190-4de6-9bce-19200d6c4790.png)
![飞书20211112-165254](https://user-images.githubusercontent.com/42343587/141442108-e9984ff5-5572-461b-ade1-12e7337ca38f.png)
![飞书20211112-173730](https://user-images.githubusercontent.com/42343587/141445320-4f4e9db5-2670-4ea6-8e79-bb16b1aef910.png)

**Comment by chadwhitacre** [comment]
Sorry this fell through the cracks @zhuangdl. :(

Were you able to resolve this or is this still an issue?

Note that Sentry requires Python 3.8 (not 3.6).
