### ISSUE TITLE
Lost Issues/Events After upgrade from version 9.0 to 21.5

### ISSUE THREAD

**Issue by bergpb** [getsentry/self-hosted#1252]
### Version

9.0

### Steps to Reproduce

1. Have a Sentry in version 9.0 with projects and a good amount of issues,
2. Start the upgrade from version 9.0 to 21.5 (9.0 > 9.1.2 > 20.12.1 > 21.5) using hard steps,
    1. I'm using version 20.12.1 because I have some problems with migrations: https://forum.sentry.io/t/migration-errors-9-1-2-to-21-6-1-project-object-has-no-attribute-get-option/14279
3. After finishing the upgrade check issues for every project

### Expected Result

After the upgrade is expected that all issues from version 9.0 are migrated correctly to version 21.5

### Actual Result

Some issues were lost after the upgrade.

1. The cleanup service is removed in the docker-compose file,
2. The variable SENTRY_EVENT_RETENTION_DAYS is increased to a value more than necessary to test if another service can remove issues too. Ex: SENTRY_EVENT_RETENTION_DAYS=3560

Previous discussion in General Thread:
https://github.com/getsentry/self-hosted/issues/1175#issuecomment-1000450678
https://github.com/getsentry/self-hosted/issues/1239#issuecomment-1009071691

**Comment by brunis** [comment]
When you write 9.1, do you mean 9.1.2?  ..hard stop is supposed to go:
`<your.sentry.version> -> 9.1.2 -> 21.5.0 -> 21.6.3 -> latest`

**Comment by bergpb** [comment]
Yes @brunis, I'm 9.1.2 like described in hard stops.

**Comment by chadwhitacre** [comment]
Hrm, should we fold this into https://github.com/getsentry/self-hosted/issues/1240? 👀

**Comment by brunis** [comment]
> Hrm, should we fold this into #1240? 👀

You should fix it, and not worry so much about folding..

**Comment by brunis** [comment]
> Hrm, should we fold this into #1240? 👀

But yes, if @bergpb documents that his events disappear in the 9.1.2 -> 10.0.0 upgrade, then i guess we have a good reason to.
And an even better reason to look into it and fix it :)

**Comment by chadwhitacre** [comment]
Sounds good. @bergpb Let's move over to #1240 ...

**Comment by chadwhitacre** [comment]
Sorry for the flail! Reopening because I now see a different actual result here than on #1240:

> After finishing the upgrade check issues for every project
> Some issues were lost after the upgrade.

Can you remind me how you are checking issues? I think this might be in one of the previous threads ... 🐭

**Comment by bergpb** [comment]
Hey @chadwhitacre I'm created a simple python script and made requests to Sentry API to compare the issues between versions 9 and 21.5!
I'm algo got some of these values and checked manually to verify if script work's like expected.
