### ISSUE TITLE
Unable to setup bitbucket integration

### ISSUE THREAD

**Issue by m1keru** [getsentry/self-hosted#1254]
### Version

21.12.0

### Steps to Reproduce

1. Enable Develper Mode in Bitbucket
2. Navigate to https://{{sentry.domain.com}}/settings/{{project}}/integrations/bitbucket/
3. Press "add integration"

### Expected Result

Integration between self-hosted Sentry configured.

### Actual Result

I receive such an error:
```
An error has occurred during installation

descriptor_uri: The add-on server wasn't able to authorize your request. Try again, or contact the add-on vendor for help.

redirect_uri: Could not resolve descriptor so cannot check redirect_uri against baseUrl
```

**Comment by chadwhitacre** [comment]
[From the docs](https://docs.sentry.io/product/integrations/source-code-mgmt/bitbucket/):

> Sentry owner, manager, or admin permissions, and Bitbucket admin permissions are required to install this integration.

Are these conditions satisfied in your case, @m1keru?

**Comment by m1keru** [comment]
Yes, 
Sentry:
![Снимок экрана от 2022-01-14 18-07-48](https://user-images.githubusercontent.com/48204749/149547573-9fc2ed6b-2a61-4273-acdd-5af3dc728044.png)

Bitbucket:
![Снимок экрана от 2022-01-14 18-10-39](https://user-images.githubusercontent.com/48204749/149547670-f625ee7b-9429-4ff0-a722-85ec60558383.png)

**Comment by chadwhitacre** [comment]
Okay, looks like you'll have to do more debugging. Any clues in your Sentry logs?

**Comment by m1keru** [comment]
Give me a way to increase log level.
I've tried all of these: https://develop.sentry.dev/config/#logging

In the log I see only:
```
nginx_1    | 172.18.0.1 - - [15/Jan/2022:00:24:15 +0000] "GET /organizations/xxx/integrations/bitbucket/setup/? HTTP/1.1" 302 0 "https://xxx/settings/xxx/integrations/bitbucket/" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36" "xxx.xxx"

```

**Comment by m1keru** [comment]
issue resolved, Cloudflare was banning incoming requests from bitbucket.

**Comment by chadwhitacre** [comment]
Interesting. Good find @m1keru, thanks for posting back. :)
