### ISSUE TITLE
nginx worker_processes auto

### ISSUE THREAD

**Issue by shadowlmd** [getsentry/self-hosted#1257]
### Version

22.1.0

### Steps to Reproduce

I noticed that in https://github.com/getsentry/self-hosted/pull/1207 you changed worker_processes to auto in nginx.conf. According to https://nginx.org/en/docs/ngx_core_module.html#worker_processes, the auto parameter is supported starting from versions 1.3.8 and 1.2.5. I can see version 1.21.5 in https://github.com/getsentry/self-hosted/blob/25381dab2e56115a17798850b139862cc3c09ea6/docker-compose.yml#L331. It could be a problem.

### Expected Result

N/A

### Actual Result

N/A

**Comment by shadowlmd** [comment]
I need new eyes. Sorry about this bug report.

**Comment by chadwhitacre** [comment]
Heh, no worries! :D
