### ISSUE TITLE
Hangs after doing migrations

### ISSUE THREAD

**Issue by fabiopedrosa** [getsentry/self-hosted#1258]
### Version

22.1.0

### Steps to Reproduce

Setup just gets stuck after finishing the migrations, and can't really figure out what is happening.

```
   ...
  Applying sites.0002_alter_domain_unique... OK
  Applying social_auth.0001_initial... OK
```

### Expected Result

Setup finish successfully.

### Actual Result

[migrations.log](https://github.com/getsentry/self-hosted/files/7888518/migrations.log)

**Comment by fabiopedrosa** [comment]
Running `./install.sh` again, still gets stuck, while there's no migrations to run:

```
Running migrations for default
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, nodestore, sentry, sessions, sites, social_auth
Running migrations:
  No migrations to apply.
```

**Comment by aminvakil** [comment]
We have not upgraded to 22.1.0 yet, but during previous upgrades I had to wait about 15 minutes after everything seems stuck for script to continue, I'm not sure which state sentry is during that period, but it certainly can be improved to be more verbose.

May I ask how long have you waited after it seems stuck?

**Comment by fabiopedrosa** [comment]
> We have not upgraded to 22.1.0 yet, but during previous upgrades I had to wait about 15 minutes after everything seems stuck for script to continue, I'm not sure which state sentry is during that period, but it certainly can be improved to be more verbose.
> 
> May I ask how long have you waited after it seems stuck?

@aminvakil I've actually waited hours, two times.

**Comment by fabiopedrosa** [comment]
@chadwhitacre No, did not. Ended up reverting back to an older version of sentry, which worked fine. Don't think I'll try to upgrade anytime soon, so I won't be able to help troubleshoot this situation.

**Comment by chadwhitacre** [comment]
Fair enough, better luck next time I guess? 😅
