### ISSUE TITLE
Fresh install of any version reports success but none of them work.

### ISSUE THREAD

**Issue by brunis** [getsentry/self-hosted#1260]
### Version

any

### Steps to Reproduce

1. install any version of Sentry. 10.0, 21.5, 21.6.3
2. configure a project and set up your integration, .NET, Javascript, whatever.
3. send data (cause exception or .captureMessage)

### Expected Result

Events should show up in Sentry after an exception or captureMessage.

### Actual Result

Nothing shows up in Sentry despite successful sentry post.
`Sentry.captureMessage("test",Sentry.Severity.Fatal);`
succesfully sends a message and gets a HTTP/200:
![sentry-post](https://user-images.githubusercontent.com/2270134/150123024-de742444-d3fd-4c15-a889-321fe6c01628.png)
but still doesn't show up in Sentry.

**Comment by brunis** [comment]
My bad, didn't enable the SSL/TLS settings in Sentry.conf.py, now events are coming in.

**Comment by chadwhitacre** [comment]
Glad _something_ is working right. 👍 😉
