### ISSUE TITLE
external volume "" not found

### ISSUE THREAD

**Issue by CodeSpent** [getsentry/self-hosted#1262]
### Version

22.1.0

On Silicon M1, same result on both arm and rosetta environments.

### Steps to Reproduce

1. Download release 22.1.0 & unzip files
2. cd into self-hosted directory & execute `install.sh`
3. Run `docker compose up`
4. Observe the following output

```
➜  self-hosted-22.1.0 docker compose up
[+] Running 2/0
 ⠿ Volume "sentry-self-hosted_sentry-secrets"   Created                    0.0s
 ⠿ Volume "sentry-self-hosted_sentry-smtp-log"  Created                    0.0s
external volume "" not found
```

### Expected Result

Volumes to be created & containers to spin up

### Actual Result

```
➜  self-hosted-22.1.0 docker compose up
[+] Running 2/0
 ⠿ Volume "sentry-self-hosted_sentry-secrets"   Created                    0.0s
 ⠿ Volume "sentry-self-hosted_sentry-smtp-log"  Created                    0.0s
external volume "" not found
```

**Comment by CodeSpent** [comment]
For the sake of having it documented for anyone else, the issue was using `docker compose up` as opposed to `docker-compose up`. These should, in theory, be 1:1, so I'm not certain if its something specific to the silicon nightly of Docker Desktop or what.

When using `docker-compose up --build`, however, all volumes must be created manually.

My issue is resolved, but wanted to share this information in case its telling of a bigger issue.

**Comment by chadwhitacre** [comment]
Interesting, thanks for posting back @CodeSpent (also hi! 👋 😁 ).

We've [learned](https://github.com/getsentry/self-hosted/milestone/5?closed=1) that `docker compose` and `docker-compose` are highly variable across environments. What versions does each point to for you? Here are mine at the moment:

```
$ docker-compose version
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
$
$
$ docker compose version
Docker Compose version v2.2.1
$
```

**Comment by CodeSpent** [comment]
Looks like my versions are identical. Not sure on the under-the-hood specifics, but `docker-compose build` does work fine, other than volumes needing to be created manually. Nonetheless I don't feel this is a Sentry specific issue, but I did want the context here since I wasn't able to find any results in my own searches.

Feel free to close if you feel it should be closed, and thanks for your response!

**Comment by chadwhitacre** [comment]
Sounds good. One for future archaeologists. ;)
