### ISSUE TITLE
growth of postgres nodestore_node table in aws rds

### ISSUE THREAD

**Issue by praseeb** [getsentry/self-hosted#1263]
### Version

21.6.3

### Steps to Reproduce

Our sentry database size has been increasing drastically in last 2-3 months, now nodestore_node table itself having ~280GB.
We were looking on this issue,but how we can do it for AWS RDS?
We are using AWS RDS Postgress for sentry.
https://github.com/getsentry/self-hosted/issues/783

### Expected Result

nodestore_node table storage need to be reduced.

@BYK @chendo @dlouzan

### Actual Result

Currently the size of the table keeps on increasing.

**Comment by chadwhitacre** [comment]
AWS RDS isn't officially supported, but maybe somebody from the community has some ideas here?

**Comment by praseeb** [comment]
@chadwhitacre @BYK @dlouzan I have a few questions

1. What data is stored in the nodestore_node table?

2. The cleanup script provided below will clean up what type of data?

```
DELETE FROM public.nodestore_node WHERE "timestamp" < NOW() - INTERVAL ‘30 day’;

pg_repack -h testrdshostaddress.eu-central-1.rds.amazonaws.com  -U adminuser -t nodestore_node -k sentrydatabase
```

Will this impact anything?

3. Is there any better solution that we can implement for the cleanup of the nodestore_node table?

4. How can we automate this task to run it frequently?

It would be helpful if you could provide any information.

**Comment by chadwhitacre** [comment]
It seems to me (1) through (3) are answered on #783, and that (4) is sorta up to you to figure out.

If there's some limitation of AWS RDS that means the techniques on #783 won't work, then please let us know if you figure out any workarounds. Closing for now as this is already covered in #783 and RDS is out of scope.
