### ISSUE TITLE
How do I modify the getSentry/Sentry code when I deploy Sentry privately with self-Hosted  

### ISSUE THREAD

**Issue by yigeyi** [getsentry/self-hosted#1264]
### Version

21.11.0

### Steps to Reproduce

Hello, I deployed Sentry on my server using self-Hosted.  Now I want to modify the getSentry/Sentry code to fit some of the functionality in it to our own needs.  But I found that the getSentry/Sentry source code has a SRC /Sentry directory and a template folder with some HTML files and Python files that are very similar to what we're using in the background management system.  
There's also a folder called static/app that contains some code for the React framework.  
When I want to change the background code, do I change the code, do I just change the code in static/app?  What if I use docker build to build a SENTRY_IMAGE image and go to the server to replace my old Web service? 
thank you

hello， 我在我的服务器使用self-Hosted  部署了Sentry。我现在想要修改getSentry/Sentry的代码让里边一些功能符合我们自己的需求。但是我发现getSentry/Sentry的源代码里边有一个 src/sentry的目录中有一个template文件夹中有一些html文件以及python文件很像我们正在使用的后台管理系统的功能。 
另外还有一个文件夹是static/app  里边有一些React框架的代码。 
当我想要修改这个后台代码时，我是不是修改代码时，我是不是修改static/app中的代码就可以呢？修改好之后我通过docker build构建一个SENTRY_IMAGE镜像 就可以去服务器替换我旧的web服务呢？

### Expected Result

How do I correctly modify the getSentry/Sentry code to fit my needs, such as button colors  

### Actual Result

How do I correctly modify the getSentry/Sentry code to fit my needs, such as button colors

**Comment by chadwhitacre** [comment]
Sorry @yigeyi, the best answer I can give you is https://github.com/getsentry/self-hosted/issues/1245#issuecomment-1007439514. 🐭

**Comment by chadwhitacre** [comment]
I mean, I guess we can leave this open for a while though to see if anyone else from the community wants to chime in. :)

**Comment by yigeyi** [comment]
@chadwhitacre thx chadwhitacre. I am working on it, and I will try to update the image of SENTRY_IMAGE to see if it works

**Comment by islom-d** [comment]
I have the same question, how can we build our custom Sentry image after some changes in code? I've tried to build an image from Dockerfile inside the repo, but it did not help. I saw the cloudbuild.yaml file, but I did not figure out how it suppose to work. It would be nice of you if you provide some tips on how to build our custom image. Thank you!

**Comment by yigeyi** [comment]
你好，蔡奕俊已经收到你的邮件，我会尽快查看并回复。

**Comment by yigeyi** [comment]
> I have the same question, how can we build our custom Sentry image after some changes in code? I've tried to build an image from Dockerfile inside the repo, but it did not help. I saw the cloudbuild.yaml file, but I did not figure out how it suppose to work. It would be nice of you if you provide some tips on how to build our custom image. Thank you!

🤣I didn't quite understand it after reading the official document.  The reason is that I'm not very familiar with Docker either.  So I asked our server colleague to handle it for me, if he had time.  I'm sorry I can't help you right now.

**Comment by chadwhitacre** [comment]
>  I've tried to build an image from Dockerfile inside the repo, but it did not help. I saw the cloudbuild.yaml file, but I did not figure out how it suppose to work.

If you provide more specific information about what exactly you tried, what you expected to happen, and what happened instead, then it will be easier for others to help you.
