### ISSUE TITLE
slack notification actions not working

### ISSUE THREAD

**Issue by michabbb** [getsentry/self-hosted#1265]
### Version

22.1.0

### Steps to Reproduce

get a Slack notification about an issue, press one of the buttons:

![image](https://user-images.githubusercontent.com/3524595/150569761-0f7ba332-edb1-4c0c-9b68-72514926cf4a.png)

### Expected Result

they do what they should do

### Actual Result

nothings happens

---

maybe my slack app is missing some permissions?
how can I debug this?

if I press any button (at the slack notification) I cannot see any output while watching the Nginx container,
so it looks like, slack isn´t doing any HTTP calls to my sentry ;(

thanks for any help!

**Comment by chadwhitacre** [comment]
> so it looks like, slack isn´t doing any HTTP calls to my sentry

Looks like a reasonable starting point. Why is Slack not making any HTTP requests? Do you have any firewalls or other network config that would prevent it from getting through? 🤔

**Comment by michabbb** [comment]
nope, maybe it has something to do with the fact that I am using traefik to handle my https traffic. maybe slack is not hitting the external url (with https), maybe the internal (without https) - could that be a problem? how do I know what URL is slack trying to reach?

**Comment by chadwhitacre** [comment]
Could be. Here are [the docs](https://docs.sentry.io/product/integrations/notification-incidents/slack/), it's not jumping out at me what URL Slack will try to reach. Here's [the code](https://github.com/getsentry/sentry/tree/22.1.0/src/sentry/integrations/slack), I guess we could look under there ... or inspect traffic in Chrome Dev Tools.

**Comment by michabbb** [comment]
thanks for the info, but i have no idea how to debug this. i enabled the access-log at my traefik container and I don´t see any request here. but in general, I do see HTTP requests, when I try HTTP instead of HTTPS. so my assumption is that slack is trying to contact a totally different URL, but I have no idea how to find out, which URL slack is trying to reach because the browser only shows `https://xxxxxxxxx.slack.com/api/chat.attachmentAction?........` - I am not a python coder, so reading all the code is not that easy. 

thanks for any hint, help, notice!

**Comment by michabbb** [comment]
okay, i totally missed a very important part of the docs 😖 

https://develop.sentry.dev/integrations/slack/

> Now that you’ve created your app and updated your Sentry config, you can navigate to Interactivity & Shortcuts under Features.

> Toggle on Interactivity.

> Now you’ll be able to enter your Request URL (this is the location of your self-hosted Sentry) and Options Load URL:
> Request URL: {YOUR_DOMAIN}/extensions/slack/action/
> Options Load URL: {YOUR_DOMAIN}/extensions/slack/options-load/

but these settings are on a different page, that´s why I have missed that: 

https://api.slack.com --> right top ---> "Your Apps" --> "Sentry" ---> left side: "Interactivity & Shortcuts"

**Comment by chadwhitacre** [comment]
Hey! A breakthrough! Huzzah! 🥳

Thanks for posting back for others to find @michabbb, glad you figured it out! 😁
