### ISSUE TITLE
[Errno 111] Connection refused when sending mail

### ISSUE THREAD

**Issue by Fumaz** [getsentry/self-hosted#1266]
### Version

22.1.0

### Steps to Reproduce

1. configure sentry self hosted dockerized (run ./install.sh)
2. configure the config.yml file to include your smtp details
3. try and send a test email from the admin page

### Expected Result

the mail gets sent

### Actual Result

an error is shown
![image](https://user-images.githubusercontent.com/45318608/150651489-ecfec426-61f6-446d-947e-c10ec36b5c98.png)

P.S. I tried with smtper and it works so it's a sentry issue.

**Comment by aminvakil** [comment]
Can you please test it with something like this:

`docker run --rm curlimages/curl:7.77.0 curl mail.fumaz.dev:587 -v`

To see if a curl docker container aside unrelated to sentry also returns `connection refused` or not.

**Comment by chadwhitacre** [comment]
I came here to update the label and didn't need to. 😁 💃

**Comment by aminvakil** [comment]
> I came here to update the label and didn't need to. grin woman_dancing

Yeah, I'm trying to learn updating labels recently :)
