### ISSUE TITLE
Integration of self-hosted Sentry with self-holsted Azure devops

### ISSUE THREAD

**Issue by beigirad** [getsentry/self-hosted#1274]
### Version

-

### Steps to Reproduce

Its not a bug. 

I want to ask how we can integrate our self-hosted Sentry with our self-hosted Azure devops server for tracking commits and releases purpose.

The current integration with Azure devops is working by Cloud based Azure. Not self-hosts.

### Expected Result

-

### Actual Result

-

**Comment by chadwhitacre** [comment]
Does [this doc](https://develop.sentry.dev/integrations/azuredevops/) get you pointed in the right direction?
