### ISSUE TITLE
Trouble receiving events when changing Port from 9000 to 80

### ISSUE THREAD

**Issue by c5racing** [getsentry/self-hosted#1275]
### Version

Sentry 22.2.0.dev0

### Steps to Reproduce

1.  set system.url-prefix in config.yml to http://sentry.example.internal
2. Modified docker-compose to change port as indicated here:      https://github.com/getsentry/self-hosted/blob/1ee602110aa4ecf48014240a46c7e68b662fafa8/docker-compose.yml#L140

```
ports:
      - '80:9000/tcp'
```

3. Configured Angular application to report events to correct url, port.

### Expected Result

I can view web and send events on port 80

### Actual Result

I can browse the site on port 80; however, events are not accepted.  I get a 403 error in return

POST http://sentry.example.internal/api/8/envelope/?sentry_key=e1a299c478714a4ca695922fd89bd56e&sentry_version=7 net::ERR_FAILED 403

**Comment by chadwhitacre** [comment]
Something with nginx? 🤔

https://github.com/getsentry/self-hosted/search?q=nginx+403&type=issues

**Comment by c5racing** [comment]
> Something with nginx? 🤔
> 
> https://github.com/getsentry/self-hosted/search?q=nginx+403&type=issues

From what I've read, Sentry uses nginx for some internal functions; however, I read somewhere it isn't used to front events or the web.

**Comment by aminvakil** [comment]
>     2. Modified docker-compose to change port as indicated here:      https://github.com/getsentry/self-hosted/blob/1ee602110aa4ecf48014240a46c7e68b662fafa8/docker-compose.yml#L140
> 
> 
> ```
> ports:
>       - '80:9000/tcp'
> ```
> 

This is a very old (Feb 2020) commit, can you please say again where have you changed 9000 port?
