### ISSUE TITLE
sentry_onpremise_geoipupdate_1 can not work

### ISSUE THREAD

**Issue by duyuyouci** [getsentry/self-hosted#1276]
### Version

22.1.0.dev0

### Steps to Reproduce

root@i-i3utdt8g:/pitrix/lib/onpremise# docker logs sentry_onpremise_geoipupdate_1
error loading configuration file /sentry/GeoIP.conf: error opening file: open /sentry/GeoIP.conf: no such file or directory
error loading configuration file /sentry/GeoIP.conf: error opening file: open /sentry/GeoIP.conf: no such file or directory

### Expected Result

how to fix it

### Actual Result

tx

**Comment by aminvakil** [comment]
This gets generated while executing `install.sh` (in `install/geoip.sh`), have you ran `install.sh` prior to `docker-compose up -d`?

**Comment by chadwhitacre** [comment]
Actually, this config file needs to be manually created. Here are [the docs for geolocation](https://develop.sentry.dev/self-hosted/geolocation/), @duyuyouci. Good luck! :)

**Comment by chadwhitacre** [comment]
P.S. Key line from the docs (if I'm understanding this correctly):

> It's normal to see the `sentry_self_hosted_geoipupdate_1` container exit soon after startup, since updating the geolocation database is a one-off batch process and not a long-running job.
