### ISSUE TITLE
Upgrade to 22.1.0

### ISSUE THREAD

**Issue by tomasnorre** [getsentry/self-hosted#1277]
### Version

21.6.3

### Steps to Reproduce

1. Setup Sentry 21.6.3
2. Download the 22.1.0.zip and unzip it
3. Run the `./install.sh`

I'm installing over Ansible so don't know if my execution part is different, and therefore the `source "$(dirname $0)/install/_min-requirements.sh"` resolves defferently.  

### Expected Result

Should find the `_min-requirements.sh`

### Actual Result

▶ Checking minimum requirements ...
    check-minimum-requirements.sh: line 3: /opt/sentry/_min-requirements.sh: No such file or directory
    
This looks related to: 
https://github.com/getsentry/self-hosted/issues/1079

If I adjust the `install/check-minimum-requirements.sh` to include `install/_min-requirements.sh` before sourcing the `_min-requirements.sh` file, it works for me.

**Comment by tomasnorre** [comment]
This is cause by my ansible script as I call it with. 

`./opt/sentry/install.sh --no-user-prompt` and not 

```shell
$ cd /opt/sentry
$ ./install.sh --no-user-prompt
```

**Comment by aminvakil** [comment]
Try https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html#parameter-chdir
