### ISSUE TITLE
Sentry Stopped Receiving Events

### ISSUE THREAD

**Issue by lanandra** [getsentry/self-hosted#1278]
### Version

21.9.0

### Steps to Reproduce

1. Go to menu Stats > Change Date Range to Last 24 hours
2. Approximately last 24 hours, accepted events dropped. Previously accepted events can reach 15k-20k per hour. But since last 24 hour only 200 events in average.
3. But starting last hour, no events received. 0 accepted, 0 dropped
4. Experienced this issue. Steps to troubleshoot is docker-compose restart. But nothing changed. Tried to reboot EC2 instance still no events 

### Expected Result

Events received

### Actual Result

No accepted events, 0 in last min

**Comment by aminvakil** [comment]
Can you please share some logs? If you have a load-balancer which sentry nginx is behind it, please share its logs. And if you're directly hitting sentry nginx, please share its logs using `docker-compose logs nginx`.

**Comment by lanandra** [comment]
Hi @aminvakil , case solved. 
This issue is impacted because relay cannot reach redis. We have changed some reconfiguration of our managed redis, but forgot to change in relay/config.yml
After we changed, sentry working back normally
