### ISSUE TITLE
Receiving HTTP 400 in response to POST events

### ISSUE THREAD

**Issue by jmtysonjr** [getsentry/self-hosted#1279]
### Version

21.11.0

### Steps to Reproduce

Greetings,

I have stood up an on-prem, self-hosted Sentry v**21.11.0** instance upgraded from a DB dump from a v8.22.0 instance. Other than an external PostgreSQL DB, the install is utilizing the shipping defaults. In the UI everything appears to be functioning correctly -- all the Users and Projects are there as well as previous events.

While testing the instance to ensure it can receive telemetry events, I used the dockerized _sentry-cli_ to perform a "send-event" to the instance as well as a test python routine to send an event via "_sentry_sdk.init("...")_".

In both cases, the "_sentry_onpremise_nginx_1_" docker container shows a response of "**400**" to the POST events received from the tests. As a consequence, these telemetry events do not show up under Issues.

I also performed the REST call -- "_/api/0/projects/_" -- to return the list of all the Projects. In the case of the REST (GET) call, the "sentry_onpremise_nginx_1" docker container shows a response of "200" and successfully returned the list of Projects.

Any insights into what could be happening would be greatly appreciated. I have migrated two other Sentry instances in the same manor and they did not experience this issue.

### Expected Result

HTTP 200 in response to my POST events to "_send-events_" from _sentry-cli_ and "_sentry_sdk.init("...")_".

### Actual Result

```
# docker logs -f sentry_onpremise_nginx_1 | grep -e "YYY\.YYY\.YYY\.YYY" -e "ZZZ\.ZZZ\.ZZZ\.ZZZ"
WWW.WWW.WWW.WWW - - [26/Jan/2022:22:26:02 +0000] "POST /api/1/envelope/ HTTP/1.1" 400 38 "-" "-" "YYY.YYY.YYY.YYY"
WWW.WWW.WWW.WWW - - [26/Jan/2022:22:39:11 +0000] "POST /api/1/store/ HTTP/1.1" 400 38 "-" "sentry.python/0.19.5" "ZZZ.ZZZ.ZZZ.ZZZ"
XXX.XXX.XXX.XXX - - [26/Jan/2022:22:52:23 +0000] "GET /api/0/projects/ HTTP/1.1" 200 30817 "-" "curl/7.81.0" "ZZZ.ZZZ.ZZZ.ZZZ"
WWW.WWW.WWW.WWW - - [27/Jan/2022:14:45:05 +0000] "POST /api/1/store/ HTTP/1.1" 400 38 "-" "sentry.python/0.19.5" "ZZZ.ZZZ.ZZZ.ZZZ"
XXX.XXX.XXX.XXX - - [27/Jan/2022:14:49:02 +0000] "GET /api/0/projects/ HTTP/1.1" 200 30816 "-" "curl/7.81.0" "ZZZ.ZZZ.ZZZ.ZZZ"
WWW.WWW.WWW.WWW - - [27/Jan/2022:14:53:01 +0000] "GET /api/0/projects/ HTTP/1.1" 200 30816 "-" "curl/7.81.0" "ZZZ.ZZZ.ZZZ.ZZZ"
XXX.XXX.XXX.XXX - - [27/Jan/2022:14:55:01 +0000] "POST /api/1/store/ HTTP/1.1" 400 38 "-" "sentry.python/0.19.5" "ZZZ.ZZZ.ZZZ.ZZZ"
WWW.WWW.WWW.WWW - - [27/Jan/2022:15:00:01 +0000] "POST /api/1/envelope/ HTTP/1.1" 400 38 "-" "-" "YYY.YYY.YYY.YYY"
```

**Comment by chadwhitacre** [comment]
Hrm, 400 suggests there's something wrong with the requests you're sending from `sentry-cli` and your test script. Want to provide some more detail on one or both of those methods? Maybe something will jump out, I suspect there's a missing header or auth or something of that nature.

**Comment by jmtysonjr** [comment]
This is my Python3 test code:
`
#!/usr/bin/env python3
import sentry_sdk

sentry_sdk.init("https://3141735d66cf4bc4b75c855c38ae7d8bedf65f0fe89e4de7b44ee0e05ef41993@sentry-host.com/1",
                # Set traces_sample_rate to 1.0 to capture 100%
                # of transactions for performance monitoring.
                # We recommend adjusting this value in production.
                traces_sample_rate=1.0)

if __name__ == '__main__':
    division_by_zero = 1 / 0 # Trigger an exception event
`

This is the _sentry-cli_ docker invocation I used:
`$ export SENTRY_DSN="https://3141735d66cf4bc4b75c855c38ae7d8bedf65f0fe89e4de7b44ee0e05ef41993@sentry-host.com/1"
$ docker run --rm -e SENTRY_DSN="$SENTRY_DSN" -v $(pwd):/work getsentry/sentry-cli send-event -m "Something happened coming from $(curl -s https://api.ipify.org) (${USER}@$(date -u +%Y%m%dT%H%M%SZ))" --log-level debug`

(I changed the _Auth Token_ and Sentry host name to protect the innocent)

**Comment by chadwhitacre** [comment]
(Formatting nit: can you use triple ticks instead of single to get linebreaks to show up right? I edited the original description to make it easier to read.)

`$ export SENTRY_DSN="https://3141735d66cf4bc4b75c855c38ae7d8bedf65f0fe89e4de7b44ee0e05ef41993@sentry-host.com/1"
$ docker run --rm -e SENTRY_DSN="$SENTRY_DSN" -v $(pwd):/work getsentry/sentry-cli send-event -m "Something happened coming from $(curl -s https://api.ipify.org) (${USER}@$(date -u +%Y%m%dT%H%M%SZ))" --log-level debug`

vs.

```
$ export SENTRY_DSN="https://3141735d66cf4bc4b75c855c38ae7d8bedf65f0fe89e4de7b44ee0e05ef41993@sentry-host.com/1"
$ docker run --rm -e SENTRY_DSN="$SENTRY_DSN" -v $(pwd):/work getsentry/sentry-cli send-event -m "Something happened coming from $(curl -s https://api.ipify.org) (${USER}@$(date -u +%Y%m%dT%H%M%SZ))" --log-level debug
```

**Comment by jmtysonjr** [comment]
My apologies, false alarm.  I was using a generated _API KEY_ inside of the _Client Keys (DSN)_ instead of the DSN provided under _Client Keys_ section. I guess when I was testing the REST call, I just plugged in the _API KEY_ when I went to test that piece.

**Comment by chadwhitacre** [comment]
Glad it was that easy! Thanks for closing the loop @jmtysonjr. 👍
