### ISSUE TITLE
Can't access Sentry via domain. 

### ISSUE THREAD

**Issue by Space-Turtle0** [getsentry/self-hosted#1281]
### Version

22.1.0

### Steps to Reproduce

```py
SENTRY_WEB_HOST = "0.0.0.0"
SENTRY_WEB_PORT = 9000
SENTRY_WEB_OPTIONS = {
    "http": "%s:%s" % (SENTRY_WEB_HOST, SENTRY_WEB_PORT),
    ...
```

### Expected Result

I placed an A record on my sub-domain and when I access the sub-domain, I get a 502 Bad Gateway error. Also is there a way to make it so I don't need a port in order to access the webpage? So like I can just access it at sentry.XXX.com instead of sentry.XXX.com:9000? I can't access it through localhost because I'm hosting this on my server so I can't open up a browser through that IP. 

### Actual Result

<img width="312" alt="image" src="https://user-images.githubusercontent.com/56415283/151646375-46b94296-75ae-4215-97cd-bce78fa07870.png">

**Comment by chadwhitacre** [comment]
Seems like you figured it out @Space-Turtle0? Let us know if there are any tips to help the next person who might hit this issue. :)
