### ISSUE TITLE
Reset script doesn't work to unbound variable _group

### ISSUE THREAD

**Issue by lovetodream** [getsentry/self-hosted#1283]
### Version

22.1.0

### Steps to Reproduce

1. Download the latest version
2. Execute the install script (not really necessary)
3. Execute the reset script

### Expected Result

The reset script should execute successfully.

### Actual Result

install/dc-detect-version.sh: line 1: _group: unbound variable

**Comment by chadwhitacre** [comment]
Good catch @lovetodream, thanks. Should be fixed in https://github.com/getsentry/self-hosted/pull/1285.

**Comment by chadwhitacre** [comment]
lol oops seeing #1284 now :P

**Comment by lovetodream** [comment]
I am glad to help. 
Next time I'll highlight that I already made a PR.

**Comment by lovetodream** [comment]
Fixed in #1284
