### ISSUE TITLE
Alerts not being sent to Pagerduty

### ISSUE THREAD

**Issue by ginokhumz2020** [getsentry/self-hosted#1286]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

21.12.0

### Steps to Reproduce

Integrate Pagerduty with Sentry. 
Set up alerts and have the alerts sent via Pagerduty.

### Expected Result

Alert is sent to PagerDuty

### Actual Result

Alerts are sent to Pagerduty for a few days and then they stop being sent.
After restarting the server the alerts get sent out again but that will also last a week or two.

Is there any container that I should be looking at to try and diagnose this problem?

**Comment by chadwhitacre** [comment]
@ginokhumz2020 Still seeing this behavior?

**Comment by ginokhumz2020** [comment]
@chadwhitacre Yes it is still happening

**Comment by chadwhitacre** [comment]
Here's [the code for the PagerDuty integration](https://github.com/getsentry/sentry/blob/22.1.0/src/sentry/integrations/pagerduty/integration.py). Maybe that will get you pointed in the right direction for debugging?

**Comment by ginokhumz2020** [comment]
Hi @chadwhitacre 
Thanks, I've checked out the code and all looks good. 
Do you perhaps know which container runs these alerts?
I want to check why some alerts are not being sent or sent hours later

**Comment by chadwhitacre** [comment]
> Do you perhaps know which container runs these alerts?

I don't know for sure off the top of my head, my hunch would be either the `worker` or `cron` containers?

**Comment by aminvakil** [comment]
@ginokhumz2020 
Can you share output of `docker-compose ps -a`?

**Comment by hubertdeng123** [comment]
Issue looks stale here, so I'm going to close this
