### ISSUE TITLE
Hosting Sentry within a Docker container

### ISSUE THREAD

**Issue by drmrbrewer** [getsentry/self-hosted#1287]
### Problem Statement

I'd like to host Sentry within a Docker container but cannot figure out how.  I've tried with a basic Dockerfile that replicates the installation steps in the README, starting with an Ubuntu image, installing docker and docker-compose, then running `install.sh`, but it bombs out with `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`.  I'm guessing that it's tricky to run docker within docker, and there's some stuff out there about this being not recommended.  Is there any way to get Sentry to work inside a Docker container?  I note that there used to be a [Docker image for Sentry](https://hub.docker.com/_/sentry), so things have moved on, but it would really suit my use-case far better to be able to run Sentry in a docker container (amongst other containers on the same server running in a swarm).

**Comment by completerevolution** [comment]
@drmrbrewer The `self-hosted` project contains a `docker-compose.yml` file which spins up the necessary environment.  `install.sh` is designed to be executed on the host server, which is running `docker` service and contains a `docker-compose` binary.

**Comment by chadwhitacre** [comment]
What @completerevolution said. 😁

**Comment by drmrbrewer** [comment]
Thanks, both.

> If you're determined, perhaps look at dind

Well, I'm determined, but also somewhat clueless, so getting Sentry up and running even with the help of `dind` may be an uphill struggle.  I'll see what I can do, but any clues to make me less clueless would be appreciated :-)
