### ISSUE TITLE
Snuba migration fails during upgrade from 21.6.3 to 22.1.0

### ISSUE THREAD

**Issue by bretteville** [getsentry/self-hosted#1291]
### Version

22.1.0

### Steps to Reproduce

We are trying to get from 21.3.0 to 22.1.0. Upgraded from 21.3.0 to 21.6.3 as pr instructions without incident. The upgrade from 21.6.3 to 22.1.0 errors out with the following message

DB::Exception: Wrong column name. Cannot find column span_op_breakdowns.value to insert after.

Resetting the migration and trying again resulted in the same exception. Traces are attached.

Is there an intermediary release that should be added to the mix?

### Expected Result

install.sh completes as pr the online documentation https://develop.sentry.dev/self-hosted/releases/

### Actual Result

[sentry-upgrade-error.txt](https://github.com/getsentry/self-hosted/files/7993137/sentry-upgrade-error.txt)

**Comment by aminvakil** [comment]
Just to be sure, you have ran `docker-compose down -v --remove-orphans` before checking out 22.1.0.
Let's say you are on 21.6.3 now, something like this should be done in these steps:
```
docker-compose down -v --remove-orphans
git checkout 22.1.0
./install.sh
docker-compose up -d
```

**Comment by bretteville** [comment]
I did not use that command, but in essence I did the same thing by manually removing (sudo docker volume rm ...) the volumes not used to persist data as described in the doc on backing up sentry hosted locally. This is provided that is all the docker-compose command above does.

**Comment by bretteville** [comment]
I know this is not supposed to be easy, but I could not leave this alone, so I started poking around and eventually got past the issue.  **The TL;DR is that a migration was recorded as completed when it wasn't as was the case for `0011_transactions_add_span_op_breakdowns`.** I have added a detailed description below as it may be of help to others running into similar issues in the future.

-------

Here is what I did

To see which migrations had run and were thought OK I executed 
`sudo docker-compose run --rm snuba-api migrations list`

It showed that all migrations under 'events' had run and that under 'transactions' '0011' had run and '0012' had not which made sense as it had exited during that migration.

To clean up after the crash, I reversed '0012' by executing
`sudo docker-compose run --rm snuba-api migrations reverse --group transactions --migration-id 0012-transaction_add_spans`

Then I located the code for '0011' on github and saw that the only thing it does was to add the column that '0012' couldn't find.

Next I exec'ed into the clickhouse container and checked the 'transactions' table in the default db. It showed me that the column was indeed missing. Comparing this to the same table in my test environment, which is at 22.1.0, confirmed that I was looking in the right place as the column was present there.

I then shut what was up of the stack down and took a volume backup of the volumes holding sentry data and then forced a reversal of migration '0011'. 

`sudo docker-compose run --rm snuba-api migrations reverse --force --group transactions --migrations-id 0011_transactions_add_span_op_breakdowns`

Next was another go at running `./install.sh` which succeeded this time.

Bringing the stack up I had two of the snuba worker containers restarting every few seconds. I recognized this from earlier issues I have had and it was resolved by 

`sudo docker volume rm sentry-kafka`
`sudo docker volume rm sentry-zookeeper`

followed by yet another

`./ìnstall.sh`

Now when I brought the stack up it stays up and accepts events.

**Comment by chadwhitacre** [comment]
Awesome work @bretteville! Thanks for posting back!

> a migration was recorded as completed when it wasn't

Why was the migration not completed? Because of the "Wrong column name." error reference in your original report?

**Comment by bretteville** [comment]
I can't say why 0011 failed. The 'wrong column name' error is part of the exception thrown by '0012' as the code can't find the column '0011' was supposed to have created. Fair enough. The problem is that the code instrumenting the migrations had marked '0011' as complete had not caught that it was in fact not. I can't explain why or how, that is for your developers to investigate and remedy.

**Comment by chadwhitacre** [comment]
Looks like we have [a custom migration system in Snuba](https://github.com/getsentry/snuba/blob/22.1.0/MIGRATIONS.md). I've let the Snuba devs know about this ticket. At the very least, there may be some improvements we can make in aborting and error reporting when a migration fails.

Thanks @bretteville! Glad you got your environment back on track! :)

**Comment by chadwhitacre** [comment]
Leaving open for a now in case @getsentry/sns wants to debug further here ...

**Comment by chadwhitacre** [comment]
Stumped over here @bretteville:

> Hmm, i ran this back and forwards a few times and couldn't reproduce anything like this
> The code that marks the migration complete runs after successful migration so hard to imagine how it got called without the migration actually completing

Gonna chalk this up to who-knows-what as a one-off.

To anyone else who hits this: can you try to capture additional repro info?
