### ISSUE TITLE
CI flakes with "Cannot restart container"

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/self-hosted#1293]
Reticketing from https://github.com/getsentry/self-hosted/pull/1289#issuecomment-1028149691. [Log link](https://github.com/getsentry/self-hosted/runs/5040239745?check_suite_focus=true#step:4:2101)

Happens at:

https://github.com/getsentry/self-hosted/blob/da8f4903e4cfe47ca4fa5bf68265b62f795c60a0/install/wrap-up.sh#L6

[Old SO](https://stackoverflow.com/questions/31365827/cannot-stop-or-restart-a-docker-container)

Considering adding a `|| true`?

**Comment by chadwhitacre** [comment]
https://github.com/getsentry/self-hosted/runs/5116648918?check_suite_focus=true#step:4:2096

**Comment by aminvakil** [comment]
https://github.com/getsentry/self-hosted/runs/7267174574?check_suite_focus=true#step:4:3809
