### ISSUE TITLE
CI flakes with "Renaming a container with the same name as its current name"

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/self-hosted#1294]
Reticketing from https://github.com/getsentry/self-hosted/pull/1290#issuecomment-1028902426. [Log link](https://github.com/getsentry/self-hosted/runs/5040186466?check_suite_focus=true#step:4:2459)

Happens at:

https://github.com/getsentry/self-hosted/blob/da8f4903e4cfe47ca4fa5bf68265b62f795c60a0/_integration-test/run.sh#L45

Possibly https://github.com/docker/compose/issues/6704? But why? And how to avoid? 🤔

**Comment by chadwhitacre** [comment]
https://github.com/getsentry/self-hosted/runs/5100619223?check_suite_focus=true#step:4:2609

**Comment by chadwhitacre** [comment]
https://github.com/getsentry/self-hosted/runs/5517601020?check_suite_focus=true#step:4:2698

**Comment by aminvakil** [comment]
https://github.com/getsentry/self-hosted/runs/5522537135?check_suite_focus=true#step:4:2360

**Comment by chadwhitacre** [comment]
From https://github.com/getsentry/self-hosted/pull/1365#issuecomment-1067074853 ...

> multiple versions in same docker instance

@glensc Do you understand what's going on here and how to fix it?

**Comment by chadwhitacre** [comment]
@BYK Confirming ... did you intend to fix this ticket by setting `COMPOSE_PROJECT_NAME` in CI?

**Comment by BYK** [comment]
>@BYK Confirming ... did you intend to fix this ticket by setting COMPOSE_PROJECT_NAME in CI?

No I did not. I intended to fix another one with "container has the same name" or something like that and that one seems to be fixed.

**Comment by BYK** [comment]
>Possibly https://github.com/docker/compose/issues/6704? But why? And how to avoid? 🤔

Adding `--no-recreate` to that command should fix it. Also adding `--wait` may make the `waiting for Sentry to be up` step redundant.

**Comment by aminvakil** [comment]
https://github.com/getsentry/self-hosted/runs/5620519447?check_suite_focus=true#step:4:2170

**Comment by aminvakil** [comment]
https://github.com/getsentry/self-hosted/runs/6953387418?check_suite_focus=true#step:4:3973

**Comment by aminvakil** [comment]
https://github.com/getsentry/self-hosted/runs/7158445726?check_suite_focus=true#step:4:3806

**Comment by aminvakil** [comment]
This has been fixed since docker-compose 2.2.4, what do you think about changing docker-compose versions in our CI to something greater than 2.2.4 and using `--no-recreate` ?

As this does not only affect CI, it will break users using docker-compose < 2.2.4 .

I don't think we can set docker-compose minimum version to 2.2.4 for users, but we can check for docker-compose version less than 2.2.4 and do not use `--no-recreate` though, and use `no-recreate` for docker-compose >= 2.2.4 .

Otherwise we keep getting hit this issue from time to time and won't be fixed.

**Comment by aminvakil** [comment]
2 days ago: https://github.com/getsentry/self-hosted/runs/7260082046?check_suite_focus=true#step:4:4126

**Comment by ethanhs** [comment]
> what do you think about changing docker-compose versions in our CI to something greater than 2.2.4 and using --no-recreate

That would be great! Flaky CI is always rather annoying :/

> I don't think we can set docker-compose minimum version to 2.2.4 for users, but we can check for docker-compose version less than 2.2.4 and do not use --no-recreate though, and use no-recreate for docker-compose >= 2.2.4 .

I think this seems reasonable, we might even want to give a warning about the potential issue?

**Comment by SubsterNL** [comment]
Getting this error a lot when trying to adjust an existing (portainer added) image and then trying to deploy it again while automaticaly replacing the existing one... it just fails with that message. No .env file used.. just deploy from template.

**Comment by SubsterNL** [comment]
using docker compose 2.6 which is the latest that is installed following the official latest install procedure

**Comment by aminvakil** [comment]
https://github.com/getsentry/self-hosted/runs/7869502187?check_suite_focus=true#step:4:1205

**Comment by chadwhitacre** [comment]
Seems we're not seeing this anymore closing, we can reopen if it occurs again.

**Comment by chadwhitacre** [comment]
lolsob

https://github.com/getsentry/self-hosted/actions/runs/4458020103/jobs/7829470226#step:4:11754
