### ISSUE TITLE
Slack Event-Subscription fails with Sentry registered error

### ISSUE THREAD

**Issue by wilfriedwolf** [getsentry/self-hosted#1303]
### Version

22.1.0

### Steps to Reproduce

1. I follow the guide for slack integration.
2. I enter the URL on "Event Subscription" 

### Expected Result

Get a green Verified note

### Actual Result

- getting a "Your URL didn't respond with the value of the challenge parameter. " respones
- also getting a Sentry Issue
``` 
slack.action.auth New Issue
```

**Comment by wilfriedwolf** [comment]
Hi @chadwhitacre 

Thank you for the hints. Describing the topology i had a look on the apache (reverse proxy) access log, where I found a 401 header, which led me straight to the misconfiguration in the sentry/config.yml (pasted twice the same secret, silly me)...

Works now. Thanks a lot..

Best regards,

Willi

**Comment by chadwhitacre** [comment]
Wish it were always that easy. :)

Cheers!
