### ISSUE TITLE
Missing release session statistics

### ISSUE THREAD

**Issue by pustelnik** [getsentry/self-hosted#1307]
### Version

21.12.0

### Steps to Reproduce

1. Sentry 21.12.0 on-prem installation on kubernetes with 3 node kafka clusters and 3 partitions per topic. Deployment is based on docker-compose
2. Create 2 organizations
3. Create multiple js/java etc projects for given organizations
4. After few days we've discovered that release statistics are missing (described as session count at https://docs.sentry.io/product/releases/) There are no lags on kafka topics, messages are consumed as expected, although we had to limit topics size to 80 GB because of heavy load. It happened after solving identical issue as https://github.com/getsentry/snuba/issues/1527. Issue mentioned in given report doesn't occur anymore but stats are also missing.  In sentry web issues are displayed correctly and what is interesting release session stats are missing for only one organization. 

### Expected Result

Release stats should be present. Currently we have no idea what could be the cause of missing statistics. Any hints how session statistics are created would be appreciated for debugging. 

### Actual Result

There are no actual errors in the logs. I can provide some if needed.

**Comment by chadwhitacre** [comment]
> on kubernetes

This is out of scope for Team Sentry, happy to leave it open for a while in case anyone else has any insight. Good luck! :)

**Comment by pustelnik** [comment]
Any ideas how to troubleshoot missing session information will be appreciated :)

**Comment by pustelnik** [comment]
I have noticed that required data is inside sessions_raw table in ClickHouse, but missing from sessions_hourly. Any ideas?
