### ISSUE TITLE
The SENTRY_URL_PREFIX setting is deprecated

### ISSUE THREAD

**Issue by drmrbrewer** [getsentry/self-hosted#1309]
### Version

22.2.0.dev0

### Steps to Reproduce

Install self-hosted sentry as per the guidance without changing anything.

### Expected Result

No warning saying `SENTRY_URL_PREFIX setting is deprecated`

### Actual Result

In the Sentry console I get the following banner at the top:

![image](https://user-images.githubusercontent.com/9009792/152880903-5e883604-5499-417f-b43c-0efb1ef2a307.png)

And clicking on that I see:

![image](https://user-images.githubusercontent.com/9009792/152880956-a131436c-64c5-4d9b-be44-6048c598336a.png)

Warning text: `The SENTRY_URL_PREFIX setting is deprecated. Please use SENTRY_OPTIONS['system.url-prefix'] instead.`

But I don't (knowingly) use `SENTRY_URL_PREFIX` anywhere.  I do enter details in the initial configuration screen you get when first loading up Sentry after installation, and that field was in fact pre-populated.  But I don't manually set it up anywhere else or refer to it in the config.  I can't even find any reference to this env var anywhere in the repo, so I'm not sure how to proceed or what other info to provide.

**Comment by chadwhitacre** [comment]
Did you look for the envvar in [the `sentry` codebase](https://github.com/getsentry/sentry)? Any clues there? 🤔

**Comment by drmrbrewer** [comment]
Ah yes.  But I can't see it as having been logged as an issue, unless it's hidden under something else.  Shall I just ignore this warning and not make myself feel like I'm somehow doing something wrong?

**Comment by chadwhitacre** [comment]
You mean logged into your Sentry instance as an issue? I wouldn't expect a deprecation warning to be filed as an error.

**Comment by drmrbrewer** [comment]
> wouldn't expect a deprecation warning to be filed as an error

I just thought you might want to be aware of it, seeing as though this warning must by triggered by something on your side, given that so far I've done nothing except install and run the default installation.  Sorry to trouble you.

**Comment by chadwhitacre** [comment]
Yeah, I did do some poking in `sentry` for `SENTRY_URL_PREFIX`. Here's [where the `DeprecationWarning` is coming from](https://github.com/getsentry/sentry/blob/master/src/sentry/runner/initializer.py#L538-L552). However, I don't find anywhere in `self-hosted` that we _set_ `SENTRY_URL_PREFIX`. You've done a grep of your filesystem to see where this might be set in your environment?

**Comment by drmrbrewer** [comment]
> You've done a grep of your filesystem to see where this might be set in your environment?

Yep... zilch.

I know nothing about python, but isn't [this bit](https://github.com/getsentry/sentry/blob/master/src/sentry/runner/initializer.py#L576-L581) setting `SENTRY_URL_PREFIX`?

I know it comes after the legacy check you referenced, but maybe this `apply_legacy_settings()` function is called again later, on `settings` that now include the legacy `SENTRY_URL_PREFIX`?

**Comment by chadwhitacre** [comment]
Interesting hypothesis, cursory `ag` suggests not, but maybe?

```
tests/sentry/runner/test_initializer.py
4:from sentry.runner.initializer import apply_legacy_settings, bootstrap_options
168:def test_apply_legacy_settings(settings):
182:    apply_legacy_settings(settings)
206:    apply_legacy_settings(settings)
212:        apply_legacy_settings(settings)

src/sentry/runner/initializer.py
357:    apply_legacy_settings(settings)
524:def apply_legacy_settings(settings):
```

**Comment by marianhlavac** [comment]
I can confirm we have the same issue on clean installation of Sentry 22.1.0. The same warning message appears in the UI sporadically.

I haven't set the variable anywhere in the configs. Grepping the folder on fs where our sentry lives doesn't give any clues indicating the variable would be set anywhere.

```
❯ ssh s.sentry.xxx
Welcome to Ubuntu 20.04.3 LTS (GNU/Linux 5.11.0-1022-aws x86_64)
Last login: Sun Feb 13 13:35:47 2022 from xxx
ubuntu@ip-172-xxx:~$ cd sentry
ubuntu@ip-172-xxx:~/sentry$ grep SENTRY_URL_PREFIX -R .
./sentry_install_log-2022-02-08_18-35-53.txt:/usr/local/lib/python3.8/site-packages/sentry/runner/initializer.py:551: DeprecatedSettingWarning: The SENTRY_URL_PREFIX setting is deprecated. Please use SENTRY_OPTIONS['system.url-prefix'] instead.
ubuntu@ip-172-xxx:~/sentry$
```

**Comment by webmozart** [comment]
Same here with 22.2.0. I get the error but I don't find any occurrence of `SENTRY_URL_PREFIX` except for the source code of the warning.

**Comment by chadwhitacre** [comment]
No recent commits or issues:

https://github.com/getsentry/sentry/search?o=desc&q=sentry_url_prefix&s=committer-date&type=commits
https://github.com/getsentry/sentry/search?o=desc&q=sentry_url_prefix&s=updated&type=issues

This is gonna take some debugging. 🤔

**Comment by nycterent** [comment]
i was not able to understand the reason, but setting system.url-prefix in config.yml got rid of this warning (which broke some monitoring scripts due to the unexpected output after sentry update :))

**Comment by soroosh-chabi** [comment]
> Thanks for the workaround @nycterent!
> 
> Leaving this open as it seems we have a (small?) bug here. Does anyone know what version this might have been introduced in? Anyone see this on 21.12.0?

As I recall, I first saw this on 22.1.0.

**Comment by idonda** [comment]
Same here with 22.3.0.dev0 just installed

**Comment by fliespl** [comment]
Or maybe it's one of these? That weren't deleted once deprecation was introduced?

https://github.com/getsentry/sentry/blob/2f31b4ef7bffdcbc80f19739fbd1a1dadaec34b1/src/sentry/options/manager.py#L149

https://github.com/getsentry/sentry/blob/2f31b4ef7bffdcbc80f19739fbd1a1dadaec34b1/src/sentry/runner/initializer.py#L576-L581

**Comment by chadwhitacre** [comment]
Those are where we backport the new config to the old. Current best hypothesis is that this inadvertently triggers the warning. Need to validate.

**Comment by haydenwalker980** [comment]
same here. After modding config,yml for the first time and restarting Sentry (docker-compose restart), we got that error consistently

We still get it. I've tried grepping / for the legacy setting. No luck.

**Comment by ascendify-engineering** [comment]
I just got the error, on updating to Sentry 22.3.0.dev0. We did not get the error on our previous version, 21.11.0.dev0.

**Comment by chadwhitacre** [comment]
I dropped a line internally to see if we can get some movement on this.

**Comment by srozdzynski** [comment]
> Thanks for the workaround @nycterent!
> 
> Leaving this open as it seems we have a (small?) bug here. Does anyone know what version this might have been introduced in? Anyone see this on 21.12.0?

According to install_log, first warning showed between upgrade 21.12.0 -> 22.1.0 and later.

**Comment by chadwhitacre** [comment]
Got one taker internally and nothing jumped out. Hard to prioritize as it is mostly a minor annoyance (yes)? 🐭

**Comment by webmozart** [comment]
I'm getting a cron email every day, so it's pretty annoying :smile: But if it's not going to be fixed quickly (as I expected), I'll apply a work around.

**Comment by chadwhitacre** [comment]
> I'm getting a cron email every day

Ouch! 😖

> I'll apply a work around

Probably the right move, I'd love to dig into this myself but I don't see that happening soon. If anyone wants to be a hero and get to the bottom of this you will get mad internet points. :P

**Comment by bsjaga** [comment]
->  Go to `self-hosted/sentry/config.yml` 
->  Replace `system.internal-url-prefix: 'http://web:9000'` with `system.url-prefix: 'https://sentry.your-domain' `

**Comment by AndreKR** [comment]
I'm quite sure that `SENTRY_URL_PREFIX` corresponds to Admin > Settings > Root URL and that must be coming from the database because during the upgrade procedure we replace the complete file set, including `config.yml`, but after the upgrade it still contains the old value.

The GUI tells us that

![image](https://user-images.githubusercontent.com/1188538/160209458-04f9f375-c3ce-4898-ad57-cf2ebbdf51e0.png)

but I think that is simply wrong.

**Comment by BYK** [comment]
@chadwhitacre quite sure this is related to getsentry/sentry#31615 which changed the option store model. @markstory pointed out that these options are very different from the options being refactored this line still made it in: https://github.com/getsentry/sentry/pull/31615/files#diff-ccd3dc0900218de662c8e661fd9b2e6ade119ede4ae946043d427271e19ad420

I think reverting that line would fix the issue. This probably broke reading options from the DB which made `SENTRY_OPTIONS['system.url-prefix']` which would cause issues with many existing setups. We make an API request to set this value in https://github.com/getsentry/self-hosted/blob/9bd7766dffd841166c2363b67a8e87df4c3437b2/_integration-test/run.sh#L87 so we can probably add a `grep` based test in this repo to catch this regression once it is fixed.

**Comment by chadwhitacre** [comment]
Good find, @BYK! I guess that mention in the newsletter worked after all. 😉 😁

**Comment by chadwhitacre** [comment]
Hey @getsentry/app-backend, could I get someone to take a look at this ticket? Seems that some changes to our configuration system in https://github.com/getsentry/sentry/pull/31615 are at the very least causing spam in self-hosted, and at worst may be breaking configuration.

**Comment by chadwhitacre** [comment]
I did some digging on this with @mgaeta, didn't get to the bottom of it but yes @bsjaga's workaround works, if you set `sentry.url-prefix` explicitly then you shouldn't get the warning.

**Comment by uhlhosting** [comment]
We also deployed latest version and got same deprrecation warning.

Sentry 22.8.0.dev0
3dcc8fb

**Comment by ethanhs** [comment]
I will be tackling this issue in the coming weeks :)

**Comment by NaveenGovindraj** [comment]
We also have this same warning.
The SENTRY_URL_PREFIX setting is deprecated. Please use SENTRY_OPTIONS['system.url-prefix'] instead.
But in the config.yml file, I have used `system.url-prefix: 'https://sentry.my-domain'`

As a result, we are not able to add any SAML Auth integrations.

Sentry version: Sentry 22.8.0.dev0
07effca

**Comment by ethanhs** [comment]
Ok, I traced the stack trace of the cause of the error, and it seems that the U2F auth code calls `.get` on the options manager twice due to multiple uwsgi workers. I'm not sure why this suddenly broken when it did, and I am not sure why it doesn't happen with SaaS however.

**Comment by johnsturgeon** [comment]
Can confirm that I'm getting the deprecation warning as well, since I do the GitHub integration 'auth' dance, I'm hesitant to change config.yml so I'll live with it, but it would be nice to get it cleaned up.

**Comment by hubertdeng123** [comment]
Hey there, also investigating this issue. I'm having trouble replicating this in my setup. Are people encountering this issue after doing a clean install of self-hosted?

**Comment by Vanav** [comment]
I have it on fresh install v22.9.0. Also after some time I got "Root URL" setting disabled, but I have not added it to config file. Maybe it is somehow related.

![image](https://user-images.githubusercontent.com/761333/194175485-18fee5fa-8bd8-4e3f-8449-ea90faa65146.png)
![image](https://user-images.githubusercontent.com/761333/194175669-3a807a90-125e-40d7-923f-e88bed6ed8b0.png)

**Comment by johnsturgeon** [comment]
> Hey there, also investigating this issue. I'm having trouble replicating this in my setup. Are people encountering this issue after doing a clean install of self-hosted? I'm wondering if there is a more reliable way to get this warning, since I definitely have seen it before in the past.

Yes, clean install

**Comment by hubertdeng123** [comment]
thanks for the datapoints everyone

**Comment by idonda** [comment]
self-hosted on ubuntu 20 22.3.0.dev0 updated to 22.9.0.dev0 same problem before and after.

**Comment by hubertdeng123** [comment]
ok, I think this happens as a result of `docker compose run --rm web upgrade` being run more than once. 
https://github.com/getsentry/sentry/blob/master/src/sentry/runner/initializer.py#L588

This line sets the `SENTRY_URL_PREFIX` if it doesn't exist, even if `system.url-prefix` is not being used

**Comment by hubertdeng123** [comment]
Note, I'm not seeing it on a clean install (first run of ./install.sh), but I'm seeing it when ./install.sh is run again because of the `docker compose run --rm web upgrade`

**Comment by hubertdeng123** [comment]
still need to verify this, so reopening for now

**Comment by hubertdeng123** [comment]
I decided that the PR did not properly tackle the issue. It seems like the deprecation warning appears and then sets the `system.url-prefix` to be`http://sentry.example.com`.

**Comment by ssjunior** [comment]
Same situation here, fresh install using docker.

**Comment by hubertdeng123** [comment]
I have a PR up here to address, just trying to figure out why e2e tests aren't passing:
https://github.com/getsentry/sentry/pull/39932

**Comment by hubertdeng123** [comment]
I just tested with the latest sentry image, this url deprecation warning should now no longer appear on self-hosted setups as a false positive.

**Comment by dashed** [comment]
@hubertdeng123 Thanks! This also no longer show up when doing `make develop` on `sentry`.

**Comment by hubertdeng123** [comment]
@dashed glad it's working for you!
