### ISSUE TITLE
How do I change the identifier type of an issue?

### ISSUE THREAD

**Issue by BaxAndrei** [getsentry/self-hosted#1310]
### Version

22.1.0

### Steps to Reproduce

For some time now, issues have been appearing with the letter identifier instead of the number, and I don't know what to do to make them look the same as before.

### Expected Result

PHPAPI-1, PHPAPI-2, PHPAPI-45

### Actual Result

PHPAPI-B, PHPAPI-C, PHPAPI-J

**Comment by chadwhitacre** [comment]
Did you do any searching on Google for this? I feel like there may have been some product change around this that others have talked about but I'm not 100% sure. I would say I'm not even 60% sure. :)

If you can't come up with anything let's see what we can help you discover. :)

**Comment by BaxAndrei** [comment]
I tried searching on google but found nothing relevant. I'm thinking of reinstalling it from scratch and so I solve this problem and the other problem. I think this happened after processor # 4 crashed on the server, it's been like that ever since.

**Comment by BaxAndrei** [comment]
The issue has been resolved with a reinstall. Thanks!

For anyone who needs: `cd /srv/sentry <- the location where you have the sentry files`
```
$ docker-compose stop
$ docker-compose rm
$ docker-compose down
$ docker volume rm $(docker volume ls -qf dangling=true)
```

**Comment by aminvakil** [comment]
@BaxAndrei Thanks for posting your solution.
````
cd /srv/sentry
bash reset.sh
```
is sufficient for destroying and installing sentry again.

**Comment by chadwhitacre** [comment]
> I think this happened after processor # 4 crashed on the server

Seems plausible. Good luck with the new install! :)

**Comment by BaxAndrei** [comment]
![image](https://user-images.githubusercontent.com/12484505/153638250-7ad8f310-6618-448e-905e-e8b682194036.png)
The problem occurred again, instead of project_name-INT_id it is now project_name-LETTER or INT + LETTER. Is there a setting or something I miss?
