### ISSUE TITLE
 Unable to send email after configuring aws ses as smtp host

### ISSUE THREAD

**Issue by sdarshil** [getsentry/self-hosted#1312]
### Version

21.7.0

### Steps to Reproduce

i have done my sentry setup as described
i have used this in my config.yml :

mail.backend: ‘smtp’
mail.host: ‘[email-smtp.us-east-1.amazonaws.com](http://email-smtp.us-east-1.amazonaws.com/)’
mail.port: 587
mail.username: 'AKIAUEXXXXXXX ’
mail.password: 'BFW2TafXXXXX ’
mail.use-tls: True
mail.from: ‘darsXXXXXX’

but i am unable to send test mail , it says check server logs 
in server logs i am unable to find any logs regarding email queue !

nginx logs :    
2022/02/08 06:30:45 [error] 23#23: *1 upstream prematurely closed connection while reading response header from upstream, client: 43.251.223.179, server: , request: "POST /api/0/internal/mail/ HTTP/1.1", upstream: "http://192.168.144.25:9000/api/0/internal/mail/", host: "45.79.216.101:9000", referrer: "http://45.79.216.101:9000/manage/status/mail/"

### Expected Result

Test Email Sent

### Actual Result

Check server logs , email not sent !

**Comment by misschak** [comment]
Have you modified SENTRY_MAIL_HOST in .env ?

**Comment by chadwhitacre** [comment]
What @misschak said. 😁

**Comment by sdarshil** [comment]
@misschak no i have not added but now i have added that in .env file , and i got diffrent error this time .

it says connection refused !
![image](https://user-images.githubusercontent.com/31997374/153123796-d65fb377-c914-4303-b717-d444fad796b9.png)

**Comment by aminvakil** [comment]
@sdarshil Make sure you have followed https://develop.sentry.dev/self-hosted/email/ completely.

Have you restarted your sentry instance after adding using `docker-compose up -d`?

P.S. It's worth taking a look at https://github.com/getsentry/self-hosted#customize-dotenv-env-file instead of changing `.env` itself.

**Comment by sdarshil** [comment]
yes i have done the setup from scratch again by delete all containers with volume and i have added the sentry_mail_ host in .env and this is my config file : 
# mail.backend: 'smtp'  # Use dummy if you want to disable email entirely
mail.host: 'email-smtp.us-east-1.amazonaws.com'
mail.port: 587
mail.username: 'AKIAUE3JIZBXXXXXXXXXX'
mail.password: 'BBer9qyYW2txgHPVSqEPSAVXXXXXXXXXXXX'
mail.use-tls: True
# mail.use-ssl: false

# NOTE: The following 2 configs (mail.from and mail.list-namespace) are set
#       through SENTRY_MAIL_HOST in sentry.conf.py so remove those first if
#       you want your values in this file to be effective!


# The email address to send on behalf of
mail.from: 'darshil.shah@XXXXXX.co'

**Comment by sdarshil** [comment]
@aminvakil 
![image](https://user-images.githubusercontent.com/31997374/153543252-e660892b-63cb-49a3-a416-647d3f745e6f.png)
THIS NETWORK CALL FAILED!

**Comment by chadwhitacre** [comment]
What do the logs in the `sentry` container show for the 500?

**Comment by aminvakil** [comment]
> @aminvakil ![image](https://user-images.githubusercontent.com/31997374/153543252-e660892b-63cb-49a3-a416-647d3f745e6f.png) THIS NETWORK CALL FAILED!

Also I see you have stated you're using 21.7.0 at first, but I see 22.2.0.dev0 in this image, how have you upgraded? There may be a issue there.

**Comment by sdarshil** [comment]
hi @aminvakil actually i was using that version but now i have delete all the volumes with containers and now i am using the latest one

**Comment by chadwhitacre** [comment]
Did you ever have any luck with this @sdarshil? Sorry I was unable to see anything useful in the screenshot you posted, too much noise. :(

**Comment by sdarshil** [comment]
@chadwhitacre no i still didnt have luck with this issue !
\

**Comment by bnxdev** [comment]
Also seeing this issue on a fresh install.

Tried SES as well as a self-hosted mail server, but Sentry always reports:
```
{"error":"[Errno 111] Connection refused"}
```

Have confirmed it's not a network issue, as telnet from the same EC2 instance to any of the mail servers I tried does work. In the case of the self-hosted mail server, the logs show Sentry does not even try to connect.

I don't know what is blocking Sentry, but it seems to be somewhere inside docker.

I have my `.env` and `sentry/config.yml` set correctly (as per comments and documentation mentioned above) and have tried both re-running `install.sh` and `docker-composer up -d` each time I try different settings.

```
#mail.backend: 'smtp'  # Use dummy if you want to disable email entirely
mail.host: 'email-smtp.eu-west-1.amazonaws.com'
mail.port: 587
mail.username: '...'
mail.password: '...'
mail.use-tls: true
mail.use-ssl: false
```

I don't know where to dig deeper for better logs.

The web container just shows it's forwarding the server error:
```
15:07:24 [INFO] sentry.access.api: api.access (method='POST' view='sentry.api.endpoints.internal.mail.InternalMailEndpoint' response=500 user_id='1' is_app='None' token_type='None' is_frontend_request='True' organization_id='None' auth_id='None' path='/api/0/internal/mail/' caller_ip='172.20.0.1' user_agent='Mozilla/5.0 Firefox/98.0' rate_limited='False' rate_limit_category='user' request_duration_seconds=0.029939889907836914 rate_limit_type='RateLimitType.NOT_LIMITED' concurrent_limit='300' concurrent_requests='1')
15:07:24 [ERROR] django.request: Internal Server Error: /api/0/internal/mail/ (status_code=500 request=<WSGIRequest: POST '/api/0/internal/mail/'>)
```

Can any of the other container provide some logs that might help?

**Comment by sdarshil** [comment]
Same issue like mine waiting for response

**Comment by chadwhitacre** [comment]
Thanks for posting back @bnxdev, glad you figured it out!

Is there something we could change in [the docs](https://develop.sentry.dev/self-hosted/email/#outbound-email) to make this clearer?

Also @sdarshil does this help you out?
