### ISSUE TITLE
MS Teams Integration cannot be done

### ISSUE THREAD

**Issue by carlosen14** [getsentry/self-hosted#1318]
### Problem Statement

Sentry self-hosted has the option to integrate with MS Teams, but when you add the application on MS Teams, the "Complete setup" button just open up a default sentry site, cannot open the on-premise site.

This is the default message to configure it.
<img width="672" alt="image" src="https://user-images.githubusercontent.com/9368632/153639261-ae5e8f9c-fca8-4c20-b11f-90c59e86a6d7.png">

### Solution Brainstorm

The "Complete setup" button could ask for the SENTRY_URL, or ask if is an on-premise instance.

![image](https://user-images.githubusercontent.com/9368632/153639707-eff5fbbf-5d96-4ba4-9395-06b084c292a2.png)

**Comment by aminvakil** [comment]
AFAICS this could be done now too:

https://develop.sentry.dev/integrations/msteams/

I don't have a teams account to test this myself, can you please follow this documentation?
