### ISSUE TITLE
 Kafka: Failed to elect leader for partition

### ISSUE THREAD

**Issue by githubmann** [getsentry/self-hosted#1321]
### Version

 21.5.1

### 2. change config below.
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/13065289/153738883-e82f73e8-ee38-46c7-938b-af3cda26584a.png">

### 5. found haven't issue data in 9000
<img width="1829" alt="image" src="https://user-images.githubusercontent.com/13065289/153738918-f0221fcd-4644-4ed3-aa4a-3c0bdf8a72a4.png">

### 6.docker-compose logs kafka, logs below.

[2022-02-13 04:12:42,920] ERROR [Controller id=1002 epoch=520] Controller 1002 epoch 520 failed to change state for partition ingest-metrics-0 from OfflinePartition to OnlinePartition (state.change.logger)
kafka_1                                     | kafka.common.StateChangeFailedException: Failed to elect leader for partition ingest-metrics-0 under strategy OfflinePartitionLeaderElectionStrategy(false)
kafka_1                                     |   at kafka.controller.ZkPartitionStateMachine.$anonfun$doElectLeaderForPartitions$7(PartitionStateMachine.scala:427)
kafka_1                                     |   at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
kafka_1                                     |   at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
kafka_1                                     |   at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
kafka_1                                     |   at kafka.controller.ZkPartitionStateMachine.doElectLeaderForPartitions(PartitionStateMachine.scala:424)
kafka_1                                     |   at kafka.controller.ZkPartitionStateMachine.electLeaderForPartitions(PartitionStateMachine.scala:335)
kafka_1                                     |   at kafka.controller.ZkPartitionStateMachine.doHandleStateChanges(PartitionStateMachine.scala:236)
kafka_1                                     |   at kafka.controller.ZkPartitionStateMachine.handleStateChanges(PartitionStateMachine.scala:157)
kafka_1                                     |   at kafka.controller.PartitionStateMachine.triggerOnlineStateChangeForPartitions(PartitionStateMachine.scala:73)
kafka_1                                     |   at kafka.controller.PartitionStateMachine.triggerOnlinePartitionStateChange(PartitionStateMachine.scala:58)
kafka_1                                     |   at kafka.controller.PartitionStateMachine.startup(PartitionStateMachine.scala:41)
kafka_1                                     |   at kafka.controller.KafkaController.onControllerFailover(KafkaController.scala:306)
kafka_1                                     |   at kafka.controller.KafkaController.elect(KafkaController.scala:1404)
kafka_1                                     |   at kafka.controller.KafkaController.processStartup(KafkaController.scala:1291)
kafka_1                                     |   at kafka.controller.KafkaController.process(KafkaController.scala:1924)
kafka_1                                     |   at kafka.controller.QueuedEvent.process(ControllerEventManager.scala:53)
kafka_1                                     |   at kafka.controller.ControllerEventManager$ControllerEventThread.process$1(ControllerEventManager.scala:136)
kafka_1                                     |   at kafka.controller.ControllerEventManager$ControllerEventThread.$anonfun$doWork$1(ControllerEventManager.scala:139)
kafka_1                                     |   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
kafka_1                                     |   at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:31)
kafka_1                                     |   at kafka.controller.ControllerEventManager$ControllerEventThread.doWork(ControllerEventManager.scala:139)
kafka_1                                     |   at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
kafka_1                                     | [2022-02-13 04:12:42,921] ERROR [Controller id=1002 epoch=520] Controller 1002 epoch 520 failed to change state for partition event-replacements-0 from OfflinePartition to OnlinePartition (state.change.logger)
kafka_1                                     | kafka.common.StateChangeFailedException: Failed to elect leader for partition event-replacements-0 under strategy OfflinePartitionLeaderElectionStrategy(false)
kafka_1                                     |   at kafka.controller.ZkPartitionStateMachine.$anonfun$doElectLeaderForPartitions$7(PartitionStateMachine.scala:427)
kafka_1                                     |   at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
kafka_1                                     |   at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
kafka_1                                     |   at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
kafka_1                                     |   at kafka.controller.ZkPartitionStateMachine.doElectLeaderForPartitions(PartitionStateMachine.scala:424)
kafka_1                                     |   at kafka.controller.ZkPartitionStateMachine.electLeaderForPartitions(PartitionStateMachine.scala:335)
kafka_1                                     |   at kafka.controller.ZkPartitionStateMachine.doHandleStateChanges(PartitionStateMachine.scala:236)
kafka_1                                     |   at kafka.controller.ZkPartitionStateMachine.handleStateChanges(PartitionStateMachine.scala:157)
kafka_1                                     |   at kafka.controller.PartitionStateMachine.triggerOnlineStateChangeForPartitions(PartitionStateMachine.scala:73)
kafka_1                                     |   at kafka.controller.PartitionStateMachine.triggerOnlinePartitionStateChange(PartitionStateMachine.scala:58)
kafka_1                                     |   at kafka.controller.PartitionStateMachine.startup(PartitionStateMachine.scala:41)
kafka_1                                     |   at kafka.controller.KafkaController.onControllerFailover(KafkaController.scala:306)
kafka_1                                     |   at kafka.controller.KafkaController.elect(KafkaController.scala:1404)
kafka_1                                     |   at kafka.controller.KafkaController.processStartup(KafkaController.scala:1291)
kafka_1                                     |   at kafka.controller.KafkaController.process(KafkaController.scala:1924)
kafka_1                                     |   at kafka.controller.QueuedEvent.process(ControllerEventManager.scala:53)
kafka_1                                     |   at kafka.controller.ControllerEventManager$ControllerEventThread.process$1(ControllerEventManager.scala:136)
kafka_1                                     |   at kafka.controller.ControllerEventManager$ControllerEventThread.$anonfun$doWork$1(ControllerEventManager.scala:139)
kafka_1                                     |   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
kafka_1                                     |   at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:31)
kafka_1                                     |   at kafka.controller.ControllerEventManager$ControllerEventThread.doWork(ControllerEventManager.scala:139)
kafka_1                                     |   at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
kafka_1                                     | [2022-02-13 04:12:42,921] ERROR [Controller id=1002 epoch=520] Controller 1002 epoch 520 failed to change state for partition snuba-commit-log-0 from OfflinePartition to OnlinePartition (state.change.logger)
kafka_1                                     | kafka.common.StateChangeFailedException: Failed to elect leader for partition snuba-commit-log-0 under strategy OfflinePartitionLeaderElectionStrategy(false)
kafka_1                                     |   at kafka.controller.ZkPartitionStateMachine.$anonfun$doElectLeaderForPartitions$7(PartitionStateMachine.scala:427)
kafka_1                                     |   at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
kafka_1                                     |   at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
kafka_1                                     |   at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
kafka_1                                     |   at kafka.controller.ZkPartitionStateMachine.doElectLeaderForPartitions(PartitionStateMachine.scala:424)
kafka_1                                     |   at kafka.controller.ZkPartitionStateMachine.electLeaderForPartitions(PartitionStateMachine.scala:335)
kafka_1                                     |   at kafka.controller.ZkPartitionStateMachine.doHandleStateChanges(PartitionStateMachine.scala:236)
kafka_1                                     |   at kafka.controller.ZkPartitionStateMachine.handleStateChanges(PartitionStateMachine.scala:157)
kafka_1                                     |   at kafka.controller.PartitionStateMachine.triggerOnlineStateChangeForPartitions(PartitionStateMachine.scala:73)
kafka_1                                     |   at kafka.controller.PartitionStateMachine.triggerOnlinePartitionStateChange(PartitionStateMachine.scala:58)
kafka_1                                     |   at kafka.controller.PartitionStateMachine.startup(PartitionStateMachine.scala:41)
kafka_1                                     |   at kafka.controller.KafkaController.onControllerFailover(KafkaController.scala:306)
kafka_1                                     |   at kafka.controller.KafkaController.elect(KafkaController.scala:1404)
kafka_1                                     |   at kafka.controller.KafkaController.processStartup(KafkaController.scala:1291)
kafka_1                                     |   at kafka.controller.KafkaController.process(KafkaController.scala:1924)
kafka_1                                     |   at kafka.controller.QueuedEvent.process(ControllerEventManager.scala:53)
kafka_1                                     |   at kafka.controller.ControllerEventManager$ControllerEventThread.process$1(ControllerEventManager.scala:136)
kafka_1                                     |   at kafka.controller.ControllerEventManager$ControllerEventThread.$anonfun$doWork$1(ControllerEventManager.scala:139)
kafka_1                                     |   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
kafka_1                                     |   at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:31)
kafka_1                                     |   at kafka.controller.ControllerEventManager$ControllerEventThread.doWork(ControllerEventManager.scala:139)
kafka_1                                     |   at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
kafka_1                                     | [2022-02-13 04:12:42,922] ERROR [Controller id=1002 epoch=520] Controller 1002 epoch 520 failed to change state for partition __consumer_offsets-0 from OfflinePartition to OnlinePartition (state.change.logger)
kafka_1                                     | kafka.common.StateChangeFailedException: Failed to elect leader for partition __consumer_offsets-0 under strategy OfflinePartitionLeaderElectionStrategy(false)
kafka_1                                     |   at kafka.controller.ZkPartitionStateMachine.$anonfun$doElectLeaderForPartitions$7(PartitionStateMachine.scala:427)
kafka_1                                     |   at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
kafka_1                                     |   at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
kafka_1                                     |   at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
kafka_1                                     |   at kafka.controller.ZkPartitionStateMachine.doElectLeaderForPartitions(PartitionStateMachine.scala:424)
kafka_1                                     |   at kafka.controller.ZkPartitionStateMachine.electLeaderForPartitions(PartitionStateMachine.scala:335)
kafka_1                                     |   at kafka.controller.ZkPartitionStateMachine.doHandleStateChanges(PartitionStateMachine.scala:236)
kafka_1                                     |   at kafka.controller.ZkPartitionStateMachine.handleStateChanges(PartitionStateMachine.scala:157)
kafka_1                                     |   at kafka.controller.PartitionStateMachine.triggerOnlineStateChangeForPartitions(PartitionStateMachine.scala:73)
kafka_1                                     |   at kafka.controller.PartitionStateMachine.triggerOnlinePartitionStateChange(PartitionStateMachine.scala:58)
kafka_1                                     |   at kafka.controller.PartitionStateMachine.startup(PartitionStateMachine.scala:41)
kafka_1                                     |   at kafka.controller.KafkaController.onControllerFailover(KafkaController.scala:306)
kafka_1                                     |   at kafka.controller.KafkaController.elect(KafkaController.scala:1404)
kafka_1                                     |   at kafka.controller.KafkaController.processStartup(KafkaController.scala:1291)
kafka_1                                     |   at kafka.controller.KafkaController.process(KafkaController.scala:1924)
kafka_1                                     |   at kafka.controller.QueuedEvent.process(ControllerEventManager.scala:53)
kafka_1                                     |   at kafka.controller.ControllerEventManager$ControllerEventThread.process$1(ControllerEventManager.scala:136)
kafka_1                                     |   at kafka.controller.ControllerEventManager$ControllerEventThread.$anonfun$doWork$1(ControllerEventManager.scala:139)
kafka_1                                     |   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
kafka_1                                     |   at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:31)
kafka_1                                     |   at kafka.controller.ControllerEventManager$ControllerEventThread.doWork(ControllerEventManager.scala:139)
kafka_1                                     |   at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)

### Expected Result

everything is ok 

### Actual Result

[2022-02-13 04:12:42,920] ERROR [Controller id=1002 epoch=520] Controller 1002 epoch 520 failed to change state for partition ingest-metrics-0 from OfflinePartition to OnlinePartition (state.change.logger)
kafka_1                                     | kafka.common.StateChangeFailedException: Failed to elect leader for partition ingest-metrics-0 under strategy OfflinePartitionLeaderElectionStrategy(false)
kafka_1                                     |   at kafka.controller.ZkPartitionStateMachine.$anonfun$doElectLeaderForPartitions$7(PartitionStateMachine.scala:427)
kafka_1                                     |   at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
kafka_1                                     |   at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
kafka_1                                     |   at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
kafka_1                                     |   at kafka.controller.ZkPartitionStateMachine.doElectLeaderForPartitions(PartitionStateMachine.scala:424)
kafka_1                                     |   at kafka.controller.ZkPartitionStateMachine.electLeaderForPartitions(PartitionStateMachine.scala:335)
kafka_1                                     |   at kafka.controller.ZkPartitionStateMachine.doHandleStateChanges(PartitionStateMachine.scala:236)
kafka_1                                     |   at kafka.controller.ZkPartitionStateMachine.handleStateChanges(PartitionStateMachine.scala:157)
kafka_1                                     |   at kafka.controller.PartitionStateMachine.triggerOnlineStateChangeForPartitions(PartitionStateMachine.scala:73)
kafka_1                                     |   at kafka.controller.PartitionStateMachine.triggerOnlinePartitionStateChange(PartitionStateMachine.scala:58)
kafka_1                                     |   at kafka.controller.PartitionStateMachine.startup(PartitionStateMachine.scala:41)
kafka_1                                     |   at kafka.controller.KafkaController.onControllerFailover(KafkaController.scala:306)
kafka_1                                     |   at kafka.controller.KafkaController.elect(KafkaController.scala:1404)
kafka_1                                     |   at kafka.controller.KafkaController.processStartup(KafkaController.scala:1291)
kafka_1                                     |   at kafka.controller.KafkaController.process(KafkaController.scala:1924)
kafka_1                                     |   at kafka.controller.QueuedEvent.process(ControllerEventManager.scala:53)
kafka_1                                     |   at kafka.controller.ControllerEventManager$ControllerEventThread.process$1(ControllerEventManager.scala:136)
kafka_1                                     |   at kafka.controller.ControllerEventManager$ControllerEventThread.$anonfun$doWork$1(ControllerEventManager.scala:139)
kafka_1                                     |   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
kafka_1                                     |   at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:31)
kafka_1                                     |   at kafka.controller.ControllerEventManager$ControllerEventThread.doWork(ControllerEventManager.scala:139)
kafka_1                                     |   at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
kafka_1                                     | [2022-02-13 04:12:42,921] ERROR [Controller id=1002 epoch=520] Controller 1002 epoch 520 failed to change state for partition event-replacements-0 from OfflinePartition to OnlinePartition (state.change.logger)
kafka_1                                     | kafka.common.StateChangeFailedException: Failed to elect leader for partition event-replacements-0 under strategy OfflinePartitionLeaderElectionStrategy(false)
kafka_1                                     |   at kafka.controller.ZkPartitionStateMachine.$anonfun$doElectLeaderForPartitions$7(PartitionStateMachine.scala:427)
kafka_1                                     |   at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
kafka_1                                     |   at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
kafka_1                                     |   at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
kafka_1                                     |   at kafka.controller.ZkPartitionStateMachine.doElectLeaderForPartitions(PartitionStateMachine.scala:424)
kafka_1                                     |   at kafka.controller.ZkPartitionStateMachine.electLeaderForPartitions(PartitionStateMachine.scala:335)
kafka_1                                     |   at kafka.controller.ZkPartitionStateMachine.doHandleStateChanges(PartitionStateMachine.scala:236)
kafka_1                                     |   at kafka.controller.ZkPartitionStateMachine.handleStateChanges(PartitionStateMachine.scala:157)
kafka_1                                     |   at kafka.controller.PartitionStateMachine.triggerOnlineStateChangeForPartitions(PartitionStateMachine.scala:73)
kafka_1                                     |   at kafka.controller.PartitionStateMachine.triggerOnlinePartitionStateChange(PartitionStateMachine.scala:58)
kafka_1                                     |   at kafka.controller.PartitionStateMachine.startup(PartitionStateMachine.scala:41)
kafka_1                                     |   at kafka.controller.KafkaController.onControllerFailover(KafkaController.scala:306)
kafka_1                                     |   at kafka.controller.KafkaController.elect(KafkaController.scala:1404)
kafka_1                                     |   at kafka.controller.KafkaController.processStartup(KafkaController.scala:1291)
kafka_1                                     |   at kafka.controller.KafkaController.process(KafkaController.scala:1924)
kafka_1                                     |   at kafka.controller.QueuedEvent.process(ControllerEventManager.scala:53)
kafka_1                                     |   at kafka.controller.ControllerEventManager$ControllerEventThread.process$1(ControllerEventManager.scala:136)
kafka_1                                     |   at kafka.controller.ControllerEventManager$ControllerEventThread.$anonfun$doWork$1(ControllerEventManager.scala:139)
kafka_1                                     |   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
kafka_1                                     |   at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:31)
kafka_1                                     |   at kafka.controller.ControllerEventManager$ControllerEventThread.doWork(ControllerEventManager.scala:139)
kafka_1                                     |   at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
kafka_1                                     | [2022-02-13 04:12:42,921] ERROR [Controller id=1002 epoch=520] Controller 1002 epoch 520 failed to change state for partition snuba-commit-log-0 from OfflinePartition to OnlinePartition (state.change.logger)
kafka_1                                     | kafka.common.StateChangeFailedException: Failed to elect leader for partition snuba-commit-log-0 under strategy OfflinePartitionLeaderElectionStrategy(false)
kafka_1                                     |   at kafka.controller.ZkPartitionStateMachine.$anonfun$doElectLeaderForPartitions$7(PartitionStateMachine.scala:427)
kafka_1                                     |   at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
kafka_1                                     |   at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
kafka_1                                     |   at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
kafka_1                                     |   at kafka.controller.ZkPartitionStateMachine.doElectLeaderForPartitions(PartitionStateMachine.scala:424)
kafka_1                                     |   at kafka.controller.ZkPartitionStateMachine.electLeaderForPartitions(PartitionStateMachine.scala:335)
kafka_1                                     |   at kafka.controller.ZkPartitionStateMachine.doHandleStateChanges(PartitionStateMachine.scala:236)
kafka_1                                     |   at kafka.controller.ZkPartitionStateMachine.handleStateChanges(PartitionStateMachine.scala:157)
kafka_1                                     |   at kafka.controller.PartitionStateMachine.triggerOnlineStateChangeForPartitions(PartitionStateMachine.scala:73)
kafka_1                                     |   at kafka.controller.PartitionStateMachine.triggerOnlinePartitionStateChange(PartitionStateMachine.scala:58)
kafka_1                                     |   at kafka.controller.PartitionStateMachine.startup(PartitionStateMachine.scala:41)
kafka_1                                     |   at kafka.controller.KafkaController.onControllerFailover(KafkaController.scala:306)
kafka_1                                     |   at kafka.controller.KafkaController.elect(KafkaController.scala:1404)
kafka_1                                     |   at kafka.controller.KafkaController.processStartup(KafkaController.scala:1291)
kafka_1                                     |   at kafka.controller.KafkaController.process(KafkaController.scala:1924)
kafka_1                                     |   at kafka.controller.QueuedEvent.process(ControllerEventManager.scala:53)
kafka_1                                     |   at kafka.controller.ControllerEventManager$ControllerEventThread.process$1(ControllerEventManager.scala:136)
kafka_1                                     |   at kafka.controller.ControllerEventManager$ControllerEventThread.$anonfun$doWork$1(ControllerEventManager.scala:139)
kafka_1                                     |   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
kafka_1                                     |   at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:31)
kafka_1                                     |   at kafka.controller.ControllerEventManager$ControllerEventThread.doWork(ControllerEventManager.scala:139)
kafka_1                                     |   at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
kafka_1                                     | [2022-02-13 04:12:42,922] ERROR [Controller id=1002 epoch=520] Controller 1002 epoch 520 failed to change state for partition __consumer_offsets-0 from OfflinePartition to OnlinePartition (state.change.logger)
kafka_1                                     | kafka.common.StateChangeFailedException: Failed to elect leader for partition __consumer_offsets-0 under strategy OfflinePartitionLeaderElectionStrategy(false)
kafka_1                                     |   at kafka.controller.ZkPartitionStateMachine.$anonfun$doElectLeaderForPartitions$7(PartitionStateMachine.scala:427)
kafka_1                                     |   at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
kafka_1                                     |   at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
kafka_1                                     |   at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
kafka_1                                     |   at kafka.controller.ZkPartitionStateMachine.doElectLeaderForPartitions(PartitionStateMachine.scala:424)
kafka_1                                     |   at kafka.controller.ZkPartitionStateMachine.electLeaderForPartitions(PartitionStateMachine.scala:335)
kafka_1                                     |   at kafka.controller.ZkPartitionStateMachine.doHandleStateChanges(PartitionStateMachine.scala:236)
kafka_1                                     |   at kafka.controller.ZkPartitionStateMachine.handleStateChanges(PartitionStateMachine.scala:157)
kafka_1                                     |   at kafka.controller.PartitionStateMachine.triggerOnlineStateChangeForPartitions(PartitionStateMachine.scala:73)
kafka_1                                     |   at kafka.controller.PartitionStateMachine.triggerOnlinePartitionStateChange(PartitionStateMachine.scala:58)
kafka_1                                     |   at kafka.controller.PartitionStateMachine.startup(PartitionStateMachine.scala:41)
kafka_1                                     |   at kafka.controller.KafkaController.onControllerFailover(KafkaController.scala:306)
kafka_1                                     |   at kafka.controller.KafkaController.elect(KafkaController.scala:1404)
kafka_1                                     |   at kafka.controller.KafkaController.processStartup(KafkaController.scala:1291)
kafka_1                                     |   at kafka.controller.KafkaController.process(KafkaController.scala:1924)
kafka_1                                     |   at kafka.controller.QueuedEvent.process(ControllerEventManager.scala:53)
kafka_1                                     |   at kafka.controller.ControllerEventManager$ControllerEventThread.process$1(ControllerEventManager.scala:136)
kafka_1                                     |   at kafka.controller.ControllerEventManager$ControllerEventThread.$anonfun$doWork$1(ControllerEventManager.scala:139)
kafka_1                                     |   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
kafka_1                                     |   at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:31)
kafka_1                                     |   at kafka.controller.ControllerEventManager$ControllerEventThread.doWork(ControllerEventManager.scala:139)
kafka_1                                     |   at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)

**Comment by aminvakil** [comment]
Can you please tell us why have you made these changes? What is the objection?

I'm almost sure something will break removing cron installation from `cron/Dockerfile` file.
