### ISSUE TITLE
Cannot get backup and restore to work

### ISSUE THREAD

**Issue by drmrbrewer** [getsentry/self-hosted#1322]
The [restore section](https://develop.sentry.dev/self-hosted/backup/#restore) of the page relating to backups has the following statement:

> This directory automatically gets mounted to /etc/sentry so you can run the following to restore your backup

But in my installation, this directory is *not* mounted to `/etc/sentry`... there is nothing at all mounted to `/etc/sentry`.  So either there's a bug in the docs, or a bug in the installation.

**Comment by drmrbrewer** [comment]
Thanks, @AbhiPrasad.  

@chadwhitacre I may be doing something wrong, but I'd expect that (as a test) I should be able to do a backup followed immediately by a restore of that backup, based on the steps as described on the [Self-Hosted Backup & Restore](https://develop.sentry.dev/self-hosted/backup/) page (using `docker compose` rather than `docker-compose`):

Backup:

    docker compose run --rm -T -e SENTRY_LOG_LEVEL=CRITICAL web export > sentry/backup.json

Restore:

    docker compose run --rm -T web import /etc/sentry/backup.json

But I just get the error messages as shown previously when I run the restore command.

**Comment by chadwhitacre** [comment]
> I should be able to do a backup followed immediately by a restore

The export/import functionality is somewhat undermaintained, so it wouldn't surprise me if it's broken. I'm not sure what testing we have for it over in `sentry`, a high-level integration test for the basic functionality would be good to have if we don't already.

**Comment by drmrbrewer** [comment]
> this is unexpected, afaict we mount `/etc/sentry` for all containers that use the `x-sentry-defaults` config:

    # ls /etc/sentry
    ls: cannot access '/etc/sentry': No such file or directory

The sentry installation is otherwise working fine.

> The export/import functionality is somewhat undermaintained, so it wouldn't surprise me if it's broken.

Would be great to get this working properly because in IMHO backup and restore is a key feature.

**Comment by chadwhitacre** [comment]
> backup and restore is a key feature

Since it's only metadata and not actual event data, it's less critical than it would be if it were a full backup solution. For that we [bump to Docker](https://develop.sentry.dev/self-hosted/backup/#full-backup).

**Comment by drmrbrewer** [comment]
> Since it's only metadata and not actual event data

For me, metadata is more important than actual event data, because event data will just repopulate over time but metadata won't.

**Comment by drmrbrewer** [comment]
@chadwhitacre did you confirm this as a bug, or is it just something I'm misunderstanding about the backup and restore process?

**Comment by drmrbrewer** [comment]
> You made it past the original `/etc/sentry` mount issue, yes?

No, still nothing is mounted there:

    # ls /etc/sentry
    ls: cannot access '/etc/sentry': No such file or directory

But everything else is working fine without that.

**Comment by drmrbrewer** [comment]
@chadwhitacre still not figured how to get this working :-(

Referring to [your comment](https://github.com/getsentry/self-hosted/issues/1322#issuecomment-1039402365), which containers actually use the `x-sentry-defaults` config?

**Comment by chadwhitacre** [comment]
> still not figured how to get this working :-(

D'oh! :-/ I need to wrap my head around this subsystem ... won't be able to fit that in this week but maybe next week? 🤞

> which containers actually use the `x-sentry-defaults` config?

Grep for `sentry_defaults` in `docker-compose.yml`.

https://github.com/getsentry/self-hosted/blob/8c5c1adf956ed589d53967447d567cd65dbadf84/docker-compose.yml#L17

**Comment by chadwhitacre** [comment]
Still interested in this @drmrbrewer?

**Comment by drmrbrewer** [comment]
@chadwhitacre yes, still very interested!

**Comment by chadwhitacre** [comment]
Okay, in that case I'll try to convince the bot to leave this ticket alone. :)

**Comment by chadwhitacre** [comment]
From @miraslav @onmomo in https://github.com/getsentry/self-hosted/issues/1428:

-------------------

> Ok, how I can resolve that error?
> ```
> File "/usr/local/lib/python3.8/site-packages/django/core/serializers/json.py", line 73, in Deserializer
>     raise DeserializationError() from exc
> django.core.serializers.base.DeserializationError
> ```

-----------

> The sentry export command generated an invalid json for me
> ```
> root@sentry-web-55cd99ffd9-628vf:/# sentry export -> export.json
> ```
> resulted in the following
> ```
> 06:15:02 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
> 06:15:10 [INFO] sentry.plugins.github: apps-not-configured
> [
> {
>   "model": "sites.site",
>   "pk": 1,
>   "fields": {
>     "domain": "example.com",
>     "name": "example.com"
>   }
> },
> ....
> ```
> Removing the log messages in the beginning of the file, fixed the `json.decoder.JSONDecodeError: Extra data: line 1 column 2 (char 1)` error.
> Which corresponds to what is documented here. 
> * https://develop.sentry.dev/self-hosted/backup/#backup

**Comment by andreasschmitz** [comment]
The messages at the beginning of the file are not part of the actual export command, but something that is printed when the docker container is started. To be honest, I haven't figured out that part yet. 

However, that allows us to work around the problem by mounting a folder into the docker container and exporting the backup file directly into it.

For example, the following mounts the current folder into the docker container at path `/backup` and then exports into the mounted folder.

`docker-compose run --rm -T -e SENTRY_LOG_LEVEL=CRITICAL -v $(pwd):/backup web bash -c "sentry export -q /backup/backup.json"`

In this case the `SENTRY_LOG_LEVEL=CRITICAL` part isn't even needed anymore, at least in my tests.

Hope that helps mitigate the problem :). The import should work as documented.

In my view this is a  less error-prone way to achieve the same thing.
Maybe worth updating the documentation for?

**Comment by chadwhitacre** [comment]
Closing in favor of https://github.com/getsentry/sentry/issues/36868 since this functionality lives in that repo.
