### ISSUE TITLE
Don't export data

### ISSUE THREAD

**Issue by see** [getsentry/self-hosted#1329]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

21.8.0

### Steps to Reproduce

Unable to download data after opening this link

### Expected Result

Data can be exported normally

### Actual Result

![screenshot-20220217-162547](https://user-images.githubusercontent.com/19725091/154435611-0da30e38-c72c-4e1a-a6a3-4686d1568123.png)

**Comment by chadwhitacre** [comment]
What have you done to debug so far @realkimmy? Your report doesn't provide much information.

**Comment by realkimmy** [comment]
@chadwhitacre Click this button, an email will be sent, click the link in the email, the address will be opened, and the data cannot be downloaded now.

![screenshot-20220228-133414](https://user-images.githubusercontent.com/19725091/155929632-6724d1c5-7d3f-4f82-b0a9-e74b6b311f74.png)

**Comment by realkimmy** [comment]
There is another question: My sentry service is self-hosted, and the api for batch calling the sentry service will report a 400 error. Does the sentry service have an anti-crawler protection mechanism?

**Comment by aminvakil** [comment]
@realkimmy I've just tested this on 22.1.0 and it emailed me a link, and I could download it successfully, there is an expiration time to download it though, have you checked it was not expired yet?

Also you should provide more information than "the data cannot be downloaded now.". What happens exactly?

> There is another question: My sentry service is self-hosted, and the api for batch calling the sentry service will report a 400 error. Does the sentry service have an anti-crawler protection mechanism?

Do you get the same result calling sentry service once? I've tested our sentry instance and it could handle approximately 5000 requests per second without an issue, and I load-tested it with a single IP. I was sampling an error issue.
