### ISSUE TITLE
Alerts aren't sending on every event

### ISSUE THREAD

**Issue by Grigoriy-Simonov** [getsentry/self-hosted#1330]
### Version

21.4.0

### Steps to Reproduce

1. Configure alert without `when` conditions
2. Send new event for existing issue.

### Expected Result

New alert is sent

### Actual Result

Alert is sent for new issues but not for new events in existing issue.

**Comment by chadwhitacre** [comment]
Can you repro with latest? 21.4.0 is almost a year old.

**Comment by Grigoriy-Simonov** [comment]
We have updated Sentry to 21.8.0. Newer versions aren't available in helm chart. Problem is still reproducible.

**Comment by chadwhitacre** [comment]
Thanks @Grigoriy-Simonov. Please pursue this with the helm chart authors. If you can repro with stock self-hosted we can revisit here. Good luck!
