### ISSUE TITLE
Installation Error - Error response from daemon: no build stage in current context - Service 'snuba-cleanup' failed to build : Build failed

### ISSUE THREAD

**Issue by sunny-repo88** [getsentry/self-hosted#1331]
### Version

latest version

### Steps to Reproduce

git clone https://github.com/getsentry/self-hosted.git
cd self-hosted
./install.sh

### Expected Result

should install successfully

### Actual Result

▶ Parsing command line ...

▶ Initializing Docker Compose ...

▶ Setting up error handling ...

▶ Checking for latest commit ...

▶ Checking minimum requirements ...
Found Docker version 20.10.12
Found Docker Compose version 1.29.2

▶ Turning things off ...
Removing network sentry-self-hosted_default
Network sentry-self-hosted_default not found.

▶ Creating volumes for persistent storage ...
Created sentry-clickhouse.
Created sentry-data.
Created sentry-kafka.
Created sentry-postgres.
Created sentry-redis.
Created sentry-symbolicator.
Created sentry-zookeeper.

▶ Ensuring files from examples ...
../sentry/sentry.conf.py already exists, skipped creation.
../sentry/config.yml already exists, skipped creation.
../symbolicator/config.yml already exists, skipped creation.
../sentry/requirements.txt already exists, skipped creation.

▶ Ensuring Relay credentials ...
../relay/config.yml already exists, skipped creation.
../relay/credentials.json already exists, skipped creation.

▶ Generating secret key ...

▶ Replacing TSDB ...

▶ Fetching and updating Docker images ...
Some service image(s) must be built from source by running:
    docker-compose build symbolicator-cleanup snuba-transactions-cleanup sentry-cleanup snuba-cleanup
nightly: Pulling from getsentry/sentry
Digest: sha256:e8c58370c81ade1133ecd3631e0126b0dfdca49d1b95840572bb9d17227102cf
Status: Image is up to date for getsentry/sentry:nightly
docker.io/getsentry/sentry:nightly

▶ Building and tagging Docker images ...

smtp uses an image, skipping
memcached uses an image, skipping
redis uses an image, skipping
postgres uses an image, skipping
zookeeper uses an image, skipping
kafka uses an image, skipping
clickhouse uses an image, skipping
geoipupdate uses an image, skipping
snuba-api uses an image, skipping
snuba-consumer uses an image, skipping
snuba-outcomes-consumer uses an image, skipping
snuba-sessions-consumer uses an image, skipping
snuba-transactions-consumer uses an image, skipping
snuba-replacer uses an image, skipping
snuba-subscription-consumer-events uses an image, skipping
snuba-subscription-consumer-transactions uses an image, skipping
symbolicator uses an image, skipping
web uses an image, skipping
cron uses an image, skipping
worker uses an image, skipping
ingest-consumer uses an image, skipping
post-process-forwarder uses an image, skipping
subscription-consumer-events uses an image, skipping
subscription-consumer-transactions uses an image, skipping
relay uses an image, skipping
nginx uses an image, skipping
Building snuba-cleanup
Sending build context to Docker daemon  3.584kB
Error response from daemon: no build stage in current context
Service 'snuba-cleanup' failed to build : Build failed
An error occurred, caught SIGERR on line 4
Cleaning up...

**Comment by chadwhitacre** [comment]
I'm unable to reproduce this @sunny-repo88. You've tried more than once? Is it something ephemeral or weird in your local Docker environment?

**Comment by jykhor** [comment]
@chadwhitacre , my mistake. placing proxy configuration before 'FROM'.
https://stackoverflow.com/questions/50452860/error-response-from-daemon-no-build-stage-in-current-context.

Closing this.

**Comment by sunny-repo88** [comment]
@chadwhitacre , my bad
Placing environment variable before 'FROM' in dockerfile

https://stackoverflow.com/questions/50452860/error-response-from-daemon-no-build-stage-in-current-context.

Closing this ticket.

**Comment by aminvakil** [comment]
@sunny-repo88 Thanks for reporting back!

You may also want to take a look at https://develop.sentry.dev/self-hosted/#configuration (Environment variables section) :wink:
