### ISSUE TITLE
Sentry upgrade with relay - downtime on the application side ?

### ISSUE THREAD

**Issue by JeSappelleRoot** [getsentry/self-hosted#1332]
### Problem Statement

Hi there, 

I tried to check on Sentry forum but the on-premise section is now read-only and refer to the main github repo.
We need to perform upgrade of our Sentry installation step-by-step  21.11.0 > 21.12.0 > 22.1.0 > 22.2.0.
In our configuration, we are using a relay to do not publicly expose our Sentry installation.

The relay is mainly use by our Android and IOS applications, that could reach the relay (publicly exposed) to report issues.

Could the upgrade process of Sentry impact the Android and IOS applications if relay is online but Sentry is not ? 
_I'm aware that it's more an application design concern_ but **I would like to make sure that we shouldn't expect weird behavior between relay and Sentry interactions during the downtime**.

Best, 

Joseph

**Comment by chadwhitacre** [comment]
I'm like 98% positive that maintaining an ingest queue while web nodes reboot is part of the raison d'etre of relay. I can do some asking around internally to reach closer to 100% :) in the meantime you could also do some testing on your side to convince yourself ... why depend on an argument from authority? :)

**Comment by JeSappelleRoot** [comment]
Hi @chadwhitacre 

Thanks for your support.
Is there some metrics from the relay that we could retrieve to confirm and monitor the ingest queue ? 

Best, 
Joseph

**Comment by chadwhitacre** [comment]
The [architecture diagram](https://develop.sentry.dev/architecture/) shows Relay writing to Kafka, so I guess that would be a place to start.
