### ISSUE TITLE
New installation getting  SyntaxWarning: "is" with a literal. Did you mean "=="

### ISSUE THREAD

**Issue by zllovesuki** [getsentry/self-hosted#1333]
### Version

22.2.0

### Steps to Reproduce

1. Download the 22.2.0 release tar and unpack
2. `./install.sh`
3. error message

### Expected Result

Sentry up and running

### Actual Result

```
/usr/local/lib/python3.8/site-packages/memcache.py:1303: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key is '':
/usr/local/lib/python3.8/site-packages/memcache.py:1304: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key_extra_len is 0:
02:31:05 [INFO] sentry.plugins.github: apps-not-configured
```

**Comment by zllovesuki** [comment]
And it seems that the queue isn't exactly working. I queued deletion on repo integration deletion and it's been "queued deletion" for a long while

**Comment by aminvakil** [comment]
Is this a clean installation or an upgrade from previous versions?

**Comment by zllovesuki** [comment]
Clean install, I saw related issues here but those were upgrades.

**Comment by aminvakil** [comment]
@zllovesuki And does this prevent self-hosted from running or is this just a warning? As this is a warning which have been added since python 3.8 (https://docs.python.org/3.8/whatsnew/3.8.html#changes-in-python-behavior) and AFAICS you're using python 3.8 too.

**Comment by zllovesuki** [comment]
It's probably harmless, but right now i'm trying to debug an issue with kafka consumer crashing with `arroyo.errors.OffsetOutOfRange: KafkaError{code=OFFSET_OUT_OF_RANGE,val=1,str="Broker: Offset out of range"}`. Hopefully they are not related.

**Comment by aminvakil** [comment]
> @zllovesuki And does this prevent self-hosted from running or is this just a warning? As this is a warning which have been added since python 3.8 (https://docs.python.org/3.8/whatsnew/3.8.html#changes-in-python-behavior) and AFAICS you're using python 3.8 too.

Yes, sentry image is using python 3.8 (https://github.com/getsentry/sentry/blob/master/docker/Dockerfile) as base image and I've just checked and all my containers have this error too and it's fine.

So no, it's not related and harmless.

You may want to open a new issue regarding your kafka error though.

**Comment by zllovesuki** [comment]
OK, the kafka consumer thing was a known issue. I think we are good!
