### ISSUE TITLE
Sentry 21.12.0 crash rate alerts

### ISSUE THREAD

**Issue by VladVolchkov** [getsentry/self-hosted#1336]
### Version

21.12.0

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/35953713/154936991-011b9844-5dcc-4874-a207-a0d5d2151e3b.png)

Hello, I updated on-premise sentry to 21.12.0 version, but looks like Crash Rate alerts are still unavailable? Should it be available in on-premise sentry?

Attaching part of Sentry config:
```
############
    # Features #
    ############


    SENTRY_FEATURES = {
      "auth:register": True
    }
    SENTRY_FEATURES["projects:sample-events"] = False
    SENTRY_FEATURES.update(
        {
            feature: True
            for feature in ("organizations:advanced-search",
                "organizations:android-mappings",
                "organizations:api-keys",
                "organizations:boolean-search",
                "organizations:related-events",
                "organizations:alert-filters",
                "organizations:custom-symbol-sources",
                "organizations:dashboards-basic",
                "organizations:dashboards-edit",
                "organizations:data-forwarding",
                "organizations:discover",
                "organizations:discover-basic",
                "organizations:discover-query",
                "organizations:enterprise-perf",
                "organizations:event-attachments",
                "organizations:events",
                "organizations:global-views",
                "organizations:incidents",
                "organizations:metric-alert-builder-aggregate",
                "organizations:metric-alert-gui-filters",
                "organizations:integrations-event-hooks",
                "organizations:integrations-issue-basic",
                "organizations:integrations-issue-sync",
                "organizations:integrations-alert-rule",
                "organizations:integrations-chat-unfurl",
                "organizations:integrations-incident-management",
                "organizations:integrations-ticket-rules",
                "organizations:integrations-vsts-limited-scopes",
                "organizations:integrations-stacktrace-link",
                "organizations:internal-catchall",
                "organizations:invite-members",
                "organizations:large-debug-files",
                "organizations:monitors",
                "organizations:onboarding",
                "organizations:org-saved-searches",
                "organizations:performance-view",
                "organizations:project-detail",
                "organizations:relay",
                "organizations:release-performance-views",
                "organizations:rule-page",
                "organizations:set-grouping-config",
                "organizations:custom-event-title",
                "organizations:slack-migration",
                "organizations:sso-basic",
                "organizations:sso-rippling",
                "organizations:sso-saml2",
                "organizations:sso-migration",
                "organizations:stacktrace-hover-preview",
                "organizations:symbol-sources",
                "organizations:transaction-comparison",
                "organizations:usage-stats-graph",
                "organizations:inbox",
                "organizations:unhandled-issue-flag",
                "organizations:invite-members-rate-limits",
                "organizations:dashboards-v2",

                "projects:alert-filters",
                "projects:custom-inbound-filters",
                "projects:data-forwarding",
                "projects:discard-groups",
                "projects:issue-alerts-targeting",
                "projects:minidump",
                "projects:rate-limits",
                "projects:sample-events",
                "projects:servicehooks",
                "projects:similarity-view",
                "projects:similarity-indexing",
                "projects:similarity-view-v2",
                "projects:similarity-indexing-v2",
                "projects:reprocessing-v2",

                "projects:plugins",
            )
        }
    )
```

### Expected Result

Crash Rate alerts available in on-premise sentry

### Actual Result

Alerts unavailable

**Comment by aminvakil** [comment]
What do you see when you open
https://<YOUR_SENTRY_INSTANCE>/organizations/sentry/alerts/rules/
And click on "Create Alert Rule" button?

I'm on 21.12.0 and I can see both "Crash Free Session Rate" and "Crash Free User Rate" in "Sessions" section.

Here is a screenshot:
![image](https://user-images.githubusercontent.com/12948692/155105103-86b1fcce-2127-4748-ace4-f10128ee8564.png)

**Comment by VladVolchkov** [comment]
Hi @aminvakil ,
I tried to crate alert, but there is no "Sessions" section:
![Screenshot at Feb 23 16-13-57](https://user-images.githubusercontent.com/35953713/155326503-bda320a8-0c9b-4399-bcd3-2a71ec1dbc0e.png)

**Comment by aminvakil** [comment]
@VladVolchkov Maybe it has got something to do with your user's privileges? Are you trying it with superuser account?

**Comment by VladVolchkov** [comment]
@aminvakil , I'm trying to crate alert using **owner** permissions, also my account has superuser privileges

**Comment by chadwhitacre** [comment]
Sorry ... reading further ... where did you get the list of features in your `SENTRY_FEATURES.update`? Are you sure you have all the ones you need?

**Comment by VladVolchkov** [comment]
@chadwhitacre , there are features declared in helm chart, also I added features from this [pull request](https://github.com/getsentry/self-hosted/pull/735/files). 
Full list of enabled features attached above, maybe I'm missing some required features, but I didn't find anything in Sentry documentation regarding crash rate alerts enabling.

**Comment by chadwhitacre** [comment]
If you're using the helm chart you ought to take this up with the maintainers over there. Can you repro with stock self-hosted?

**Comment by VladVolchkov** [comment]
@chadwhitacre I'm not sure that current issue should be submitted to chart maintainers, as part of config attached in issue was taken from sentry pods, not from values.yaml file. I'm trying to say that as far as I see there is no issue with helm chart, as config rendered correctly from templates. Just trying to found out did I missed something in configuration or there can another issue
