### ISSUE TITLE
LDAP as officially supported authentication method

### ISSUE THREAD

**Issue by codegain** [getsentry/self-hosted#1337]
### Problem Statement

Hi,

I really love sentry and I have been using it for a few years now. My biggest wish for the future of sentry is that LDAP will become an officially supported authentication method on self-hosted instances. Currently I'm using https://github.com/Banno/getsentry-ldap-auth but it gave me more headaches then anything else (and I did run sentry in docker behind a proxy :D).

Every update of sentry is currently a gamble that everything works and everybody can log in. Debugging is a nightmare.

Due to company policy we had to migrate from sentry.io to the self-hosted solution and this is a feature we really missed both on sentry.io and on sentry self-hosted.

(Sorry if this idea has been propsed already, I didn't find any issue)

### Solution Brainstorm

I would propose something like https://github.com/Banno/getsentry-ldap-auth but with a few more features and an easier setup:

- Sync user from AD on login (name, email, role, permission, user state, etc.) and automatically assign to teams, projects etc.
- Debugging in the admin area for LDAP (connectivity, latest errors, audit)
- Configuration in admin area (instead of having to edit the config file and restart for changes in the mapping)
- Restrict login method to LDAP

**Comment by aminvakil** [comment]
Hi!

This repository just installs and configures different parts sentry needs to be up and running, we cannot add features here.
I guess this is more appropriate for https://github.com/getsentry/sentry repository.

Please wait for someone from sentry to migrate this issue there (or somewhere else which is more appropriate).

**Comment by chadwhitacre** [comment]
(#1337 – Nice get, @codegain. 😁)

As @aminvakil says we won't be adding features here in this repo, as the purpose of the `self-hosted` repo is to package up Sentry for proofs of concept and low-volume deployments. I can also say that if we move this ticket to `sentry` it is unlikely to go anywhere. What we "officially" support is driven by the needs of Sentry SaaS, so, for example, we [dropped support for all databases except Postgres a few years ago](https://github.com/getsentry/self-hosted/issues/1305), we [don't (yet?) officially support Postgres > 9.6](https://github.com/getsentry/self-hosted/issues/1097), we [won't be swapping out Kafka for Redpanda in core Sentry anytime soon](https://github.com/getsentry/self-hosted/pull/1335), and I don't see that we will provide first-class support for LDAP as you propose.

> I would propose something like https://github.com/Banno/getsentry-ldap-auth but with a few more features and an easier setup:

Have you tried working with the folks over there to improve that project? I know we have _some_ kind of plugin/integration architecture, and at the end of the day it's just Python so you can always monkey-patch. 😬

How do our existing [SSO](https://docs.sentry.io/product/accounts/sso/) and [custom SAML](https://docs.sentry.io/product/accounts/sso/saml2/) features relate here? You can't use those to achieve what you want?

**Comment by codegain** [comment]
Hi @chadwhitacre,

> What we "officially" support is driven by the needs of Sentry SaaS

I fully understand that. In the end, self-hosted sentry is a blessing for everyone to use freely which I really appreciate.

> Have you tried working with the folks over there to improve that project? I know we have some kind of plugin/integration architecture, and at the end of the day it's just Python so you can always monkey-patch. 😬

It seems to me that the ldap-sentry auth plugin is pretty much dead at this point (f.e. many open issues that never get closed). It sometimes works with newer versions of sentry, but oftentimes something in the sentry images changes (f.e. build-essential not being included) which leads to strange errors and a lot of headaches on my side 😅

Unfortunately I'm not that familiar with python or django. I could maybe write a "Hello World" in python, but thats it 😅

> How do our existing [SSO](https://docs.sentry.io/product/accounts/sso/) and [custom SAML](https://docs.sentry.io/product/accounts/sso/saml2/) features relate here? You can't use those to achieve what you want?

I didn't know these existed, but I don't see that any of them do support on-premise AD. And without clear instructions I won't be able to build a custom SAML-based authentication based on the information available on sentry.io.

I guess if there would be a product like "enterprise self-hosted sentry" with LDAP authentication support in a higher tier (like GitLab self-managed), I won't hesitate to purchase a license. sentry.io is (unfortunately) not an option anymore.


If there is no hope that LDAP authentication will ever become a sentry-supported feature then I guess this issue can be closed.

**Comment by chadwhitacre** [comment]
Okay, I'm going to go ahead and close this out. If anyone ever comes along and forks [`getsentry-ldap-auth`](https://github.com/Banno/getsentry-ldap-auth) hopefully they will leave a note here for others to find. :)
