### ISSUE TITLE
CI flakes with "The operation was canceled."

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/self-hosted#1341]
Integration test is timing out after 360 minutes:

https://github.com/getsentry/self-hosted/runs/5266047420?check_suite_focus=true#step:4:775

**Comment by aminvakil** [comment]
I'm not sure after two runs , but it seems to happen with 1.28.0, 1.29.2 and 2.2.3 (2.0.1 is fine)
https://github.com/getsentry/self-hosted/runs/5300821867?check_suite_focus=true

**Comment by chadwhitacre** [comment]
Is that because it's the first one to kick off? Is there some resource constraint, like the 2.0.1 job is grabbing a lock and not releasing it?

**Comment by aminvakil** [comment]
https://github.com/getsentry/self-hosted/runs/5307522338?check_suite_focus=true
Again only 2.0.1 was fine.

**Comment by aminvakil** [comment]
https://github.com/getsentry/self-hosted/runs/5311060854?check_suite_focus=true
from https://github.com/getsentry/self-hosted/pull/1347

**Comment by aminvakil** [comment]
https://github.com/getsentry/self-hosted/runs/5343799600?check_suite_focus=true
OK, I was hoping if this was a temporary issue somehow with GHA, unfortunately it's not :(

**Comment by aminvakil** [comment]
https://github.com/getsentry/self-hosted/runs/5461913213?check_suite_focus=true
Again, 2.0.1 is only working.

**Comment by BYK** [comment]
[>https://github.com/getsentry/self-hosted/runs/5339631065?check_suite_focus=true#step:4:1207](https://github.com/getsentry/self-hosted/runs/5339631065?check_suite_focus=true#step:4:1207) shows the issue

**Comment by BYK** [comment]
This is because https://github.com/getsentry/sentry/commit/53e38f42bcb01078a78169f4223894920e29276c - you should not have an interactive prompt when `CI=1` or [`--no-input`](https://github.com/getsentry/sentry/blob/b5bf8da514bef723e7e11940c869a9e203a1f86e/src/sentry/runner/commands/createuser.py#L56) is passed. 🤦🏻

**Comment by chadwhitacre** [comment]
Reopening as fix was deemed "temporary."

**Comment by chadwhitacre** [comment]
> This is because https://github.com/getsentry/sentry/commit/53e38f42bcb01078a78169f4223894920e29276c

Good find @BYK. 👍
