### ISSUE TITLE
Run install.sh error on Macos

### ISSUE THREAD

**Issue by reuwi** [getsentry/self-hosted#1343]
### Version

22.2.0

### Steps to Reproduce

1.git clone git@github.com:getsentry/self-hosted.git
2.cd self-hosted && ./install.sh

### Expected Result

install sentry successfully

### Actual Result

▶ Parsing command line ...

▶ Initializing Docker Compose ...

▶ Setting up error handling ...

▶ Checking for latest commit ... 

▶ Checking minimum requirements ...
Found Docker version 20.10.7
Found Docker Compose version 2.0.0

▶ Turning things off ...
time="2022-02-23T20:05:15+08:00" level=warning msg="The SENTRY_MAIL_HOST variable is not set. Defaulting to a blank string."
time="2022-02-23T20:05:15+08:00" level=warning msg="The POSTGRES_USER variable is not set. Defaulting to a blank string."
services.web.healthcheck.retries must be a number
An error occurred, caught SIGERR on line 9
Cleaning up...

**Comment by chadwhitacre** [comment]
I'm not able to repro with Docker Compose 2.1.3. Can you upgrade Docker Compose?

**Comment by reuwi** [comment]
After I upgrade Docker Compose to 2.2.3, everything gose ok, thanks. BTW, previous version was 2.0.0.

**Comment by chadwhitacre** [comment]
Glad to hear it, thanks for posting back @reuwi! Seems like there should be a workaround we can find for 2.0.0. If anyone else hits this and wants to suggest something, let us know! :)
