### ISSUE TITLE
Sentry takes up too much CPU resources

### ISSUE THREAD

**Issue by ljwlaji** [getsentry/self-hosted#1345]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

21.10.0

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/16899528/155262567-26c64292-5190-4b4d-a4b5-fc27c177d4bb.png)
Sentry keeps calling swap memory even if the memory is not completely exhausted.
swapfile is currently disabled
![image](https://user-images.githubusercontent.com/16899528/155262712-6f56deb6-025a-4cde-be87-36d7dbf3e92b.png)
![image](https://user-images.githubusercontent.com/16899528/155262733-b8893d5d-8b74-426d-b5e6-03c8ef6a3989.png)

### Expected Result

call swap when the memory is completely exhausted.

### Actual Result

Sentry keeps calling swap memory even if the memory is not completely exhausted.

**Comment by chadwhitacre** [comment]
What's your event volume?

**Comment by aminvakil** [comment]
> > I have try to kill this process manually(this process won't restart), after that the cpu usage will cutting down, and nothing happens on sentry, it looks work fine, and no error log outputs, Curious when this process is called and why is it called when the memory is not fully occupied 

This is odd. I remember there were some memory issues which I asked in https://github.com/getsentry/self-hosted/issues/1328#issuecomment-1046288836 as well. Can you tell us more about this server? Is this is a VM and if yes, has hypervisor been overcomitted? Can you check your memory health with something like `memtester` or whatever you prefer?

> will the install.sh create a linux user named 'sentry'?

No. It does not make any changes outside of its docker volumes and on host (well docker volumes exist on host:), but you get the idea ).

**Comment by ljwlaji** [comment]
@aminvakil  Yes, this machine is a vm, it's on the cloud server, This process starts every time when i call the docker-compose up -d command to bring sentry up, 
issue starts on feb 8 (the day that kafka gets the error when alloc memory), then i upgrade memory size from 8GB to 16GB. not sure the kswapd0 process will or not called in the early time,

**Comment by ljwlaji** [comment]
@chadwhitacre  don't understand that is 'event volume'
there are my docker volumes
![image](https://user-images.githubusercontent.com/16899528/155466951-c9b0e8c0-46b1-44f9-aea7-28dd66cd7000.png)

**Comment by aminvakil** [comment]
Can you please verify if you can fill the memory without a problem?

I've seen this issue on over-committed hypervisors many times, you have available memory on your VM, but hypervisor does not allocate you the memory as it's getting used by another VM.

This command fills 90% of your available memory.
```
stress --vm-bytes $(awk '/MemAvailable/{printf "%d\n", $2 * 0.95;}' < /proc/meminfo)k --vm-keep -m 1
```

**Comment by chadwhitacre** [comment]
> not sure which 'event volume' is

I mean how many events are you sending to your Sentry instance, are you overloading the system?

**Comment by ljwlaji** [comment]
@chadwhitacre  @aminvakil 
I may get the point,
this machine has been hacked in feb 8 that's why the memory issue of kafka happend, and the kswapd0 file is in the /tmp folder, i clean the /tmp folder and disable the user who runs it, and this issue was gone for good...

**Comment by aminvakil** [comment]
@ljwlaji Great! Thanks for reporting back on what the problem was.

On a side-note :) you may better reinstall operating system as you may never know what other parts of it has been tampered with.
