### ISSUE TITLE
Unable to update user permissions

### ISSUE THREAD

**Issue by georgimorozov** [getsentry/self-hosted#1346]
### Version

22.3.0.dev0

### Steps to Reproduce

1. Go to a User
2. Toggle Admin or Super Admin
3. Click Save
4. Get Success Message
4. Reload Page
5. Settings Unchanged

### Expected Result

Settings to be saved

### Actual Result

Settings are not saved

**Comment by chadwhitacre** [comment]
This seems like it should be a dupe of https://github.com/getsentry/self-hosted/issues/1288, but we supposedly fixed that by now. Can you review that and see whether its relevant @georgimorozov?

**Comment by georgimorozov** [comment]
@chadwhitacre Thank for the quick response, the solution worked! However it was noted that the fixed was merged into 22.2, however I am on 22.3 and the issue persists...I am assuming the fix would not be retroactive for existing users?

**Comment by chadwhitacre** [comment]
> I am assuming the fix would not be retroactive for existing users?

Hmm, yeah I guess that is the case. :-/

So any user created between what version and 22.2.0 will be affected by this? @SavchenkoAlexander on #1288 has "21.11-22.1" as the version ... 🤔
