### ISSUE TITLE
How run the copy of self-hosted in A machine docker

### ISSUE THREAD

**Issue by ningmengwork** [getsentry/self-hosted#1349]
### Problem Statement

I want to run two set of self-hosted in a machine docker，but the step of `./install.sh --no-user-promt` allways failed, when one self-hosted already is running.

I changed the port of Nginx  from the copy of self-hosted,  but some problem still happened,  'Status file /var/lib/clickhouse/status already exists - unclean restart.'. 

What to run two set of self-hosted meanwhile  must be more than the modification of Nginx port , what should I do to make it.

Looking forward to your reply.

**Comment by aminvakil** [comment]
Debugging such two instances it would be like hell :) but if you want to try it anyway, other thing that I can recall are docker volumes which should be renamed too in second instances (not only in `docker-compose.yml`, but also in `install/create-docker-volumes.sh`).

**Comment by aminvakil** [comment]
@ningmengwork Maybe use something like this in `self-hosted` folder to make sure you're not missing anything

grep -rl clickhouse . | grep -vE "^./.git|CHANGELOG.md" | xargs sed -i 's/clickhouse/clickhouse-2/g'

Not that this would change some places you don't want like docker image or `/var/lib/clickhouse` in container:
![image](https://user-images.githubusercontent.com/12948692/155729343-467b1cc7-d529-4960-9da3-bc2b5fa1c9b6.png)

Repeat this for all containers and volumes.

But seriously this is too much hassle and effort.

May I ask what's the reason you want to sentry instances in a same host and why don't you use different organizations in a same sentry host?

**Comment by ningmengwork** [comment]
Thank you  very  very much for your nice patient reply and guidance! The second  instance  is running！

The reason is that there is one instance of version 9.1.2 running, and I want to upgrade to the version 21.12.0 without mass steps and take this opportunity to master more about `self-hosted`.

Another question is how to deploy self-hosted by cluster?

**Comment by aminvakil** [comment]
> Thank you very very much for your nice patient reply and guidance! The second instance is running！
> 

You're welcome!
> The reason is that there is one instance of version 9.1.2 running, and I want to upgrade to the version 21.12.0 without mass steps and take this opportunity to master more about `self-hosted`.
> 

You're running a hacked version of 21.12.0 now, which **may** differ from the 21.12.0 you will get running at last. You **may** make some changes in configurations which you don't need to do in production. Also those changes **may** break sentry without these hacks.

All I'm trying to say is if you want to test 21.12.0 before migrating to it, clone your 9.1.2 instance on another server by migrating docker volumes and configurations, upgrade it to 21.12.0 (beware of [hard-stops](https://develop.sentry.dev/self-hosted/releases/#hard-stops) though), and if it was working fine, upgrade your main sentry instance.

> Another question is how to deploy self-hosted by cluster?

Running it on a cluster is not supported in this repository, but I've found this searching https://github.com/sentry-kubernetes/charts/ which is not official.

**Comment by ningmengwork** [comment]
Solved. Amin Vakil, Thanks again for your kindly help!
