### ISSUE TITLE
Cannot use a custom config for sentry installation

### ISSUE THREAD

**Issue by Glyphack** [getsentry/self-hosted#1350]
### Version

22.2.0

### Steps to Reproduce

1. Clone the sentry repository
2. Edit sentry/conf.py
3. Install sentry with install script

I tried both cases:
1. Editing the sentry/conf.example.py
2. Renaming conf.example.py to conf.example

### Expected Result

from here https://develop.sentry.dev/self-hosted/#configuration
I expected to see my custom configuration after installation. I think the way I'm expecting it to work is wrong but did not find more information in docs.

### Actual Result

sentry.conf.py is generated and does not have my code with it.

**Comment by chadwhitacre** [comment]
This sounds similar to another report we had recently, let me find that ...

**Comment by chadwhitacre** [comment]
[Here it is, in the general thread for the quarter](https://github.com/getsentry/self-hosted/issues/1239#issuecomment-1041939940).

**Comment by chadwhitacre** [comment]
Is this related to that?

**Comment by Glyphack** [comment]
Yes, it's related.

**Comment by chadwhitacre** [comment]
Okay, in that case let's keep this open to track and fold that conversation into here. cc: @anthonyvelazquez

-----------

>> Hello, I'm encountering a problem setting up the most recent version of Sentry with an external Postgres DB. We are currently using Vagrant and Puppet to provision everything and with Sentry's default settings, it works perfectly. To use the external DB, I replaced `sentry.conf.example.py` with a copy of the same file and the `DATABASES` field updated with the appropriate settings and then it runs the `./install.sh` script as normal.
After Puppet finishes provisioning the system, I SSH into the box and see that the conf settings are there but I don't see any changes that occurred to the external DB and I never receive any error messages.
>>
>> Are there any additional steps required to used an external DB rather than the internal container?

-------------

>> see that the conf settings are there
>
> You're depending on install.sh to copy sentry.conf.example.py to sentry.conf.py, yes? The config values shows up in the latter?

**Comment by chadwhitacre** [comment]
Thanks for posting back @anthonyvelazquez, glad you got it sorted. :)

Is that relevant for you @Glyphack?

**Comment by Glyphack** [comment]
Yes In my case was also there was a typo. Thanks for your follow-ups.
