### ISSUE TITLE
Sentry On-premise with on-hosted Postgres Db

### ISSUE THREAD

**Issue by ozankyncu** [getsentry/self-hosted#1353]
### Problem Statement

Hello Sentry Team,

We're using Sentry On-premise version with on-hosted Postgres db. 
I wonder when a new version of Sentry comes out, do you publish a script for the changes made in the database section for column additions etc.?

In Addition could you please share any information or documentation about seperated postgre db installation or upgrading sentry version?

Best regards.

**Comment by chadwhitacre** [comment]
> do you publish a script for the changes made in the database section for column additions etc.?

We [use Django migrations](https://develop.sentry.dev/database-migrations/), here's the call chain:

- https://github.com/getsentry/self-hosted/blob/22.2.0/install.sh
- https://github.com/getsentry/self-hosted/blob/22.2.0/install/set-up-and-migrate-database.sh
- https://github.com/getsentry/sentry/blob/22.2.0/src/sentry/runner/commands/upgrade.py#L40-L67

> could you please share any information or documentation about seperated postgre db installation

I guess we don't have docs on this apart from [the generic config docs](https://develop.sentry.dev/self-hosted/#configuration). Here are some database settings you could mess with:

https://github.com/getsentry/self-hosted/blob/8c5c1adf956ed589d53967447d567cd65dbadf84/sentry/sentry.conf.example.py#L36-L45

>  or upgrading sentry version?

https://develop.sentry.dev/self-hosted/releases/#upgrading

**Comment by ozankyncu** [comment]
Thanks for the answer
