### ISSUE TITLE
Problems upgrading versions

### ISSUE THREAD

**Issue by Duckelekuuk** [getsentry/self-hosted#1354]
### Version

21.6.3

### Steps to Reproduce

Sentry version installed 21.2.0.dev07b4f609
docker-compose version 1.29.2, build 5becea4c
Docker version 20.10.12, build e91ed57

Followed steps from: [guide](https://develop.sentry.dev/self-hosted/releases/#upgrading)
Downloaded version 21.6.3 from Github

executed `./install.sh` as sudo

### Expected Result

Migration of database

Error:
`ERROR: for sentry_onpremise_postgres_1  Cannot start service postgres: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/opt/sentry/postgres-entrypoint.sh": permission denied: unknown`

### Actual Result

Full log:
[sentry_install_log-2022-03-02_01-31-18.txt](https://github.com/getsentry/self-hosted/files/8165619/sentry_install_log-2022-03-02_01-31-18.txt)
g

**Comment by aminvakil** [comment]
Can you please paste output of these commands? (Feel free to obfuscate your username/uid/gid if you feel more safe that way)
```
id
ls -l
ls -l postgres
```
To retrieve what's the owner/permissions of `postgres` folder and files in it.

**Comment by Duckelekuuk** [comment]
![image](https://user-images.githubusercontent.com/13730138/156347881-46a34040-3bb5-4f36-becb-9396753581ae.png)

**Comment by aminvakil** [comment]
I guess this has something to do with this getting run as root, can you please try again from a non-root user which has access to `docker` group?

**Comment by aminvakil** [comment]
@Duckelekuuk Sorry, I should've mentioned this earlier, you ought to upgrade to 21.5.0 before 21.6.3 when upgrading from versions < 21.5.0: https://develop.sentry.dev/self-hosted/releases/#hard-stops

Can you try upgrading to 21.5.0 first?

**Comment by Duckelekuuk** [comment]
I actually tried this! I ran it again to get the log for you
The error: `Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/etc/sentry/entrypoint.sh": permission denied: unknown
1
An error occurred, caught SIGERR on line 12`

Here is the full log
[sentry_install_log-2022-03-02_16-00-45.txt](https://github.com/getsentry/self-hosted/files/8170487/sentry_install_log-2022-03-02_16-00-45.txt)

**Comment by aminvakil** [comment]
@Duckelekuuk I don't have any other ideas, what's the status of SELinux, AppArmor or any other security which may prevent this?

But line 12 of `sentry/entrypoint.sh` is:
```
if [[ -s "$req_file" ]] && ! cat "$req_file" | grep '^[^#[:space:]]' | shasum -s -c "$checksum_file" 2>/dev/null; then
```
and `"$req_file"` is:
`req_file="/etc/sentry/requirements.txt"`
which should be created in previous steps next to `sentry/entrypoint.sh`.

From the log you have pasted it seems it has been created already and exists:
```
▶ Ensuring files from examples ...
../sentry/sentry.conf.py already exists, skipped creation.
../sentry/config.yml already exists, skipped creation.
../symbolicator/config.yml already exists, skipped creation.
../sentry/requirements.txt already exists, skipped creation.
```
Also from my understanding `-f` and `-s` checks if it's readable
Verified it like this:
`if [[ -f "/path/to/readable/file" ]]; then echo "file exists and it's readable!"; fi`
So why it cannot be read from inside the container, I don't know.
