### ISSUE TITLE
how to configure corporate proxy when installing github app

### ISSUE THREAD

**Issue by sunny-repo88** [getsentry/self-hosted#1355]
### Version

latest

### Steps to Reproduce

Install Github App  (sentry io github integration)

1. Create github apps - https://github.com/getsentry/sentry/issues/30865#issuecomment-1004196446
2. settings -> integration -> github -> add installation
3. install github apps from (1)
4.  installation failed with timeout

![image](https://user-images.githubusercontent.com/30856837/156299905-a7fe5592-8723-4448-bfb6-1e7bcd2f10ca.png)

### Expected Result

able to install github apps

### Actual Result

nginx_1                                     | 172.31.0.1 - - [02/Mar/2022:04:50:41 +0000] "GET /extensions/github/setup/?installation_id=xxxxxx&setup_action=install HTTP/1.0" 502 552 "https://github.com/" 

web_1                                       | 04:50:41 [INFO] sentry.integrations.client: integration.http_response (status_string='connection_error' error=**"SafeHTTPSConnectionPool(host='api.github.com', port=443):** Max retries exceeded with url: /app/installations/xxxxxx (Caused by ConnectTimeoutError(<sentry.net.http.SafeHTTPSConnection object at 0x7f8cae9daf70>, 'Connection to api.github.com timed out. (co" integration='github')
![image](https://user-images.githubusercontent.com/30856837/156300264-16184ee4-b04b-4e9d-856c-eb130330a28d.png)

**Comment by sunny-repo88** [comment]
possible duplicate -  https://github.com/getsentry/sentry/issues/31735

**Comment by aminvakil** [comment]
@sunny-repo88 Are you using a proxy to connect to outside of your network?

And if not, can you please paste the output of this command:
docker run --rm curlimages/curl:7.77.0 curl api.github.com -vL

**Comment by sunny-repo88** [comment]
configure proxy inside ~/.docker/config.json and restart the instances - solve the issue. thanks!
Closing this.
