### ISSUE TITLE
I would like to ask how to clear all data of sentry

### ISSUE THREAD

**Issue by WuChenDi** [getsentry/self-hosted#1356]
### Version

Sentry 21.12.0.dev0

### Steps to Reproduce

Problems caused when a lot of data is reported

### Expected Result

result

### Actual Result

![image](https://user-images.githubusercontent.com/31385662/156522508-86d4c74d-5e54-4c2b-98d8-7e7162295a87.png)

Server configuration as described above。
![2ac26294b3672cb0e8ec501726a837d](https://user-images.githubusercontent.com/31385662/156522602-0d6f63bf-0257-4129-bbab-41681e085ed4.png)
These services have been restarting and the web side online has been closed for reporting。

**Comment by aminvakil** [comment]
Comment last line of `reset.sh` which is `./install.sh`, then run `./reset.sh`.

It will effectively remove all docker volumes and containers.

**Make sure you want this, it is destructive, and it will remove all sentry data.**

**Comment by WuChenDi** [comment]
> Comment last line of `reset.sh` which is `./install.sh`, then run `./reset.sh`.
> 
> It will effectively remove all docker volumes and containers.
> 
> **Make sure you want this, it is destructive, and it will remove all sentry data.**

With this operation, can I ask if the previously configured user and team items in sentry still exist?

**Comment by aminvakil** [comment]
> > Comment last line of `reset.sh` which is `./install.sh`, then run `./reset.sh`.
> > It will effectively remove all docker volumes and containers.
> > **Make sure you want this, it is destructive, and it will remove all sentry data.**
> 
> With this operation, can I ask if the previously configured user and team items in sentry still exist?

No, everything will be lost.

If you want to keep your configurations without any event data, you can use commands as specified in https://develop.sentry.dev/self-hosted/backup/#quick-backup.

**Comment by WuChenDi** [comment]
> > > Comment last line of `reset.sh` which is `./install.sh`, then run `./reset.sh`.
> > > It will effectively remove all docker volumes and containers.
> > > **Make sure you want this, it is destructive, and it will remove all sentry data.**
> > 
> > 
> > With this operation, can I ask if the previously configured user and team items in sentry still exist?
> 
> No, everything will be lost.
> 
> If you want to keep your configurations without any event data, you can use commands as specified in https://develop.sentry.dev/self-hosted/backup/#quick-backup.

Thank you for your reply, if I only want to keep the team members and project configuration information in sentry and not the rest, how does this work?

**Comment by aminvakil** [comment]
Take a backup, start a new sentry instance somewhere else, restore the backup, make sure everything you need is present, nuke the first sentry instance with data on it.

**Comment by WuChenDi** [comment]
docker-compose run --rm -T -e SENTRY_LOG_LEVEL=CRITICAL web export > sentry/backup.json
docker-compose run --rm -T web import /etc/sentry/backup.json

Okay, thanks. Do you operate these two commands?

**Comment by WuChenDi** [comment]
> > > Comment last line of `reset.sh` which is `./install.sh`, then run `./reset.sh`.
> > > It will effectively remove all docker volumes and containers.
> > > **Make sure you want this, it is destructive, and it will remove all sentry data.**
> > 
> > 
> > With this operation, can I ask if the previously configured user and team items in sentry still exist?
> 
> No, everything will be lost.
> 
> If you want to keep your configurations without any event data, you can use commands as specified in https://develop.sentry.dev/self-hosted/backup/#quick-backup.

Hi, I tested the backup restore operation on a test machine and the actual result does not serve the purpose, that is, the restore is a failure, the following error message is reported

root@iZxjv9e22z6q0aZ:/home/onpremise# docker-compose run --rm -T web import /etc/sentry/backup.json
Creating sentry-self-hosted_web_run ... done
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
10:40:32 [INFO] sentry.plugins.github: apps-not-configured
/usr/local/lib/python3.8/site-packages/sentry/runner/initializer.py:551: DeprecatedSettingWarning: The SENTRY_URL_PREFIX setting is deprecated. Please use SENTRY_OPTIONS['system.url-prefix'] instead.
  warnings.warn(DeprecatedSettingWarning(old, "SENTRY_OPTIONS['%s']" % new))
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/serializers/json.py", line 68, in Deserializer
    objects = json.loads(stream_or_string)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 188, in main
    func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/backup.py", line 19, in import_
    for obj in serializers.deserialize("json", src, stream=True, use_natural_keys=True):
  File "/usr/local/lib/python3.8/site-packages/django/core/serializers/json.py", line 73, in Deserializer
    raise DeserializationError() from exc
django.core.serializers.base.DeserializationError
ERROR: 1

**Comment by aminvakil** [comment]
Are you using the same version between the sentry instance you have backed up from and the server you're trying to restore to?
You have stated 21.12.dev0 (make sure to be on the same commit), but I'm seeing this line in your log:
```
/usr/local/lib/python3.8/site-packages/sentry/runner/initializer.py:551: DeprecatedSettingWarning: The SENTRY_URL_PREFIX setting is deprecated. Please use SENTRY_OPTIONS['system.url-prefix'] instead.
```
which is something that started to happen since 22.1.0.

**Comment by aminvakil** [comment]
Ah, and 21.12.dev0 which has been built and pulled before is different from the 21.12.dev0 which gets built now, as it will pull nightly tag of docker images, and so on.

Make sure to stick to the same version, I guess you have to upgrade to 22.1.0 first, make sure it upgraded correctly, do a backup again, and start a new sentry instance sticking to 22.1.0, restore the backup.

**Comment by WuChenDi** [comment]
> 

Sorry, because the server configuration is not enough to run two sentry services, so the backup operation was tested on another machine, using the latest version, and the backup operation was reported as unsuccessful.

**Comment by aminvakil** [comment]
It's ok. You cannot run two sentry instances on one machine without lots of hacks anyway.

**Comment by WuChenDi** [comment]
Okay. Then I am testing with the latest version, how can I restore the backup please, this is my error message.

```
root@iZxjv9e22z6q0aZ:/home/onpremise# docker-compose run --rm -T web import /etc/sentry/backup.json
Creating sentry-self-hosted_web_run ... done
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
10:40:32 [INFO] sentry.plugins.github: apps-not-configured
/usr/local/lib/python3.8/site-packages/sentry/runner/initializer.py:551: DeprecatedSettingWarning: The SENTRY_URL_PREFIX setting is deprecated. Please use SENTRY_OPTIONS['system.url-prefix'] instead.
warnings.warn(DeprecatedSettingWarning(old, "SENTRY_OPTIONS['%s']" % new))
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/django/core/serializers/json.py", line 68, in Deserializer
objects = json.loads(stream_or_string)
File "/usr/local/lib/python3.8/json/init.py", line 357, in loads
return _default_decoder.decode(s)
File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/local/bin/sentry", line 8, in
sys.exit(main())
File "/usr/local/lib/python3.8/site-packages/sentry/runner/init.py", line 188, in main
func(**kwargs)
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in call
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
return process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
return callback(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
return f(get_current_context(), *args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 29, in inner
return ctx.invoke(f, *args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
return callback(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/backup.py", line 19, in import
for obj in serializers.deserialize("json", src, stream=True, use_natural_keys=True):
File "/usr/local/lib/python3.8/site-packages/django/core/serializers/json.py", line 73, in Deserializer
raise DeserializationError() from exc
django.core.serializers.base.DeserializationError
ERROR: 1
```

**Comment by aminvakil** [comment]
You cannot perform a backup on an old version and restore it on latest version.

https://develop.sentry.dev/self-hosted/backup/#quick-backup

> Are you using the same version between the sentry instance you have backed up from and the server you're trying to restore to?

**Comment by WuChenDi** [comment]
> Collaborator

Yes, I'm using the latest version on my test machine

**Comment by aminvakil** [comment]
> > Collaborator
> 
> Yes, I'm using the latest version on my test machine

I didn't mention latest version. Use **the same version** on both. Please read my comments and wiki carefully again.
