### ISSUE TITLE
The ARCHIVE number of Source Maps exists, but ARTIFACTS is 0

### ISSUE THREAD

**Issue by looooool11111** [getsentry/self-hosted#1359]
### Version

22.3.0.dev0

### Steps to Reproduce

1.foo

### Expected Result

The sentiry deployed in my server successfully uploaded the soucemap file

### Actual Result

![1646307117781](https://user-images.githubusercontent.com/89401805/156556584-c3c8a1ea-dcfb-4047-9519-d9066f34ab21.jpg)
error logs:warning: could not determine a source map reference (Could not auto-detect referenced sourcemap for ~/dist/2820.fa84bf8fb9d045eaeac3.js.)
![AFAEE627-EFB0-4801-9FAE-83F52F813976](https://user-images.githubusercontent.com/89401805/156556155-9846d8fb-9d0d-4d19-ba24-656e9c0ed015.png)
![EFB0B129-6FD7-491A-9C53-CE4D88B9F544](https://user-images.githubusercontent.com/89401805/156556333-dcf747d8-810c-4dff-b918-442f303f7acf.png)
I can upload successfully under SaaS, but I can't upload on the server I deploy. I wonder if the server has restrictions on the upload permission of sentry?

**Comment by aminvakil** [comment]
If you're using a reverse proxy in front of your sentry instance, can you try uploading directly to it, bypassing reverse proxy?

**Comment by looooool11111** [comment]
> 如果您在哨兵实例前使用反向代理，您可以尝试直接上传到它，绕过反向代理吗？

My server is connected to port 80 through proxy. Do I need to reconfigure my server？

**Comment by aminvakil** [comment]
@looooool11111 Not necessarily, for this case I'm suspecting something is not configured correctly on the reverse proxy, it's worth trying to upload directly to sentry itself (on ngnix container on port 9000).

**Comment by looooool11111** [comment]
> @looooool11111 Not necessarily, for this case I'm suspecting something is not configured correctly on the reverse proxy, it's worth trying to upload directly to sentry itself (on ngnix container on port 9000).

Thank you for your reply. I solved this problem by redeploying sentry and modifying all ports at the same time. But there are new problems.

All “Minified Scripts” files report this error and keep the original on the sentry platform.
Are some key files missing from the file I uploaded.
![WechatIMG36](https://user-images.githubusercontent.com/89401805/156872317-d73753a6-c61d-4aa0-ad89-cd0210576eaf.png)
![WechatIMG38](https://user-images.githubusercontent.com/89401805/156872321-5338aa4c-8809-4ece-9e06-aadb4a784893.png)
![WechatIMG37](https://user-images.githubusercontent.com/89401805/156872323-a1379ce8-9557-4e55-91b9-2367c4d2f3a9.png)
![WechatIMG38](https://user-images.githubusercontent.com/89401805/156872324-60095b12-795f-4a3e-ae75-a0f351f3ac5a.png)

**Comment by looooool11111** [comment]
hi dude, i need some help

**Comment by chadwhitacre** [comment]
I would need way more detailed steps to reproduce your problem in order to provide any help.

**Comment by looooool11111** [comment]
> I would need way more detailed steps to reproduce your problem in order to provide any help.

I uploaded the sourcemap file, but some of them showed upload failure, as shown in the following picture.

I deployed the sentry service on my server and changed all 9000 ports occupied by sentry to 9100.
The problem now is that the sourcemap does not take effect
![a](https://user-images.githubusercontent.com/89401805/158370320-33792cb5-9144-4865-8634-000fad9a6495.png)
![b](https://user-images.githubusercontent.com/89401805/158370333-16fe1e5b-1247-4f67-90a2-c7ad537fd1c4.png)
![cc](https://user-images.githubusercontent.com/89401805/158370337-e7926bcd-9d97-4e16-8714-136d3c606524.png)

**Comment by chadwhitacre** [comment]
> The problem now is that the sourcemap does not take effect

For your initial upload problem you said "I can upload successfully under SaaS" ... is the same true for the second problem? Do sourcemaps take effect in Saas?

**Comment by looooool11111** [comment]
> > The problem now is that the sourcemap does not take effect
> 
> For your initial upload problem you said "I can upload successfully under SaaS" ... is the same true for the second problem? Do sourcemaps take effect in Saas?



> I can upload successfully under SaaS,But the sourcemap file doesn't work. This is my webpack configuration

![WechatIMG48](https://user-images.githubusercontent.com/89401805/158502430-d17acad3-a307-41ab-99b3-1dc41585985e.png)
![WechatIMG49](https://user-images.githubusercontent.com/89401805/158502433-31425538-2dcc-45f3-84af-f28c597dfcc5.png)

**Comment by chadwhitacre** [comment]
Okay, if you can't get your sourcemaps to work even in SaaS then I am going to go ahead and close out this issue as we're off-topic for self-hosted. You can try asking for help [in the `sentry-javascript` repo](https://github.com/getsentry/sentry-javascript/discussions/new).

**Comment by looooool11111** [comment]
> Okay, if you can't get your sourcemaps to work even in SaaS then I am going to go ahead and close out this issue as we're off-topic for self-hosted. You can try asking for help [in the `sentry-javascript` repo](https://github.com/getsentry/sentry-javascript/discussions/new).

Thank you for your reply！
