### ISSUE TITLE
`install.sh` is hang at `Would you like to create a user account now? [Y/n]`

### ISSUE THREAD

**Issue by anhtumai-spacehub** [getsentry/self-hosted#1360]
### Version

22.1.0 & 22.2.0

### Steps to Reproduce

Run the command: `bash install.sh`

### Expected Result

The script should have ended gracefully

### Actual Result

It hangs on  `Would you like to create a user account now? [Y/n]`

<img width="763" alt="image" src="https://user-images.githubusercontent.com/94450786/156574168-1eb9ae2f-bd0c-4a10-b410-f55277cdf251.png">

**Comment by anhtumai-spacehub** [comment]
my docker-compose is pre-ship with Docker Desktop, since I use MacOs. The version is:

<img width="392" alt="image" src="https://user-images.githubusercontent.com/94450786/156785534-80b8489c-8855-48d6-955e-b74371729c5b.png">

**Comment by aminvakil** [comment]
@anhtumai-spacehub  Please use `./install.sh --skip-user-prompt` then.
