### ISSUE TITLE
After Install.sh relay does not start 'could not load the Geoip Db'

### ISSUE THREAD

**Issue by oko-x** [getsentry/self-hosted#1363]
### Version

22.2.0

### Steps to Reproduce

1. git checkout tags/22.2.0 -b remotes/origin/master
2. ./install.sh
3. docker-compose up -d

Relay does not start with logs:
` 2022-03-07T16:25:18Z [relay_log::utils] ERROR: could not load the Geoip Db caused by: IoError: entity not found`

During installation following warning occured, which may be related:
`16:21:09 [WARNING] sentry.utils.geo: Error opening GeoIP database: /geoip/GeoLite2-City.mmdb`
`16:21:09 [WARNING] sentry.utils.geo: Error opening GeoIP database in Rust: /geoip/GeoLite2-City.mmdb`

### Expected Result

Sentry available.

### Actual Result

Sentry not available, due to nginx not starting due to relay not found, due to GeoIP DB not found in relay.

**Comment by aminvakil** [comment]
Have you filled in `geoip/GeoIP.conf` as told in https://develop.sentry.dev/self-hosted/geolocation/ ?

**Comment by oko-x** [comment]
I did not, as it states that it 'can' be used so I thought not configuring it won't break anything. In my scenario GeoIP resolving is not needed.

**Comment by chadwhitacre** [comment]
Yeah you have something weird going on in your environment. `install.sh` is supposed to install an empty `GeoLite2-City.mmdb` file:

https://github.com/getsentry/self-hosted/blob/1201e5d97118735afaa6b4ee56828924677788c5/install/geoip.sh#L11-L13

You could probably manually create the file (based on the above). If want to understand why that file is missing for you in the first place, you can use `DEBUG=1 ./install.sh` for more detailed logs.

**Comment by oko-x** [comment]
Thank you for the help @chadwhitacre empty file did the trick indeed. Strange that command didn't create it, maybe some permission issue in the folder although it was inside home directory of the current user.

Anyway it works now perfectly, thanks for the help, much appreciated.
