### ISSUE TITLE
How to access Audit logs to get user actions traceback?

### ISSUE THREAD

**Issue by LinTechSo** [getsentry/self-hosted#1366]
### Version

2

### Steps to Reproduce

I’m running a on-premise setup with docker containers (and nginx as proxy).

### Expected Result

Hi,
I’m trying to get user actions that (supposedly) renamed an Organization and removed it after few hours.

I found some Audit logs on (Django) Admin area but isn’t enough to confirm what really happened.

### Actual Result

Docker logs are too verbose to get specific actions occurred over a Project or an Organization.

I’m searching for a practical way/tool to reach it, like over interface and/or SQL queries.

**Comment by LinTechSo** [comment]
any updates?
is there ant way to store sentry audit logs into specific log file ?

**Comment by aminvakil** [comment]
See `web` container logs, it has something like this when a change happens:

I changed default role from `Member` to `Admin` and changed back here:
```
12:10:26 [INFO] sentry.audit.api: org.edit (ip_address='1.1.1.1' organization_id=1 object_id=1 entry_id=80 actor_label='info@example.com' actor_id=1)
12:10:26 [INFO] sentry.access.api: api.access (method='PUT' view='sentry.api.endpoints.organization_details.OrganizationDetailsEndpoint' response=200 user_id='1' is_app='None' token_type='NoneType' organization_id='1' auth_id='None' path='/api/0/organizations/sentry/' caller_ip='1.1.1.1' user_agent='Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0' rate_limited='False' rate_limit_category='user' request_duration_seconds=0.21752047538757324)
12:10:28 [INFO] sentry.audit.api: org.edit (ip_address='1.1.1.1' organization_id=1 object_id=1 entry_id=81 actor_label='info@example.com' actor_id=1)
12:10:28 [INFO] sentry.access.api: api.access (method='PUT' view='sentry.api.endpoints.organization_details.OrganizationDetailsEndpoint' response=200 user_id='1' is_app='None' token_type='NoneType' organization_id='1' auth_id='None' path='/api/0/organizations/sentry/' caller_ip='1.1.1.1' user_agent='Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0' rate_limited='False' rate_limit_category='user' request_duration_seconds=0.15916156768798828)
```

**Comment by chadwhitacre** [comment]
Is this sufficient for your needs @LinTechSo? Can we close this out?

**Comment by The-Seyed** [comment]
@chadwhitacre Yeah it totally worked. Thank You!

**Comment by aminvakil** [comment]
@The-Seyed Thanks for reporting back!
