### ISSUE TITLE
QueryExecutionError corrupted data

### ISSUE THREAD

**Issue by hhoechtl** [getsentry/self-hosted#1380]
### Version

22.2.0

### Steps to Reproduce

I don't know, we're just trying to explore our issues like usually.
But the list shows an internal error and you can't open any issue (except the internal ones).

### Expected Result

Issues should be listed and can be opened

### Actual Result

We're seeing the internal error:

DB::Exception: Checksum doesn't match: corrupted data. Reference: 5e07dd30f886cf12471b92d39ac098bf. Actual: 169ed458a7a81ec613e0f45b1d43de81. Size of compressed block: 85464. The mismatch is caused by single bit flip in data block at byte 64014, bit 5. This is most likely due to hardware failure. If you receive broken data over network and the error does not repeat every time, this can be caused by bad RAM on network interface controller or bad controller itself or bad RAM on network switches or bad CPU

**Comment by chadwhitacre** [comment]
Ouch! Seems bad @hhoechtl. :(

Is there a reason to disbelieve the error message?

> This is most likely due to hardware failure. If you receive broken data over network and the error does not repeat every time, this can be caused by bad RAM on network interface controller or bad controller itself or bad RAM on network switches or bad CPU
