### ISSUE TITLE
Enable performance feature in local

### ISSUE THREAD

**Issue by YaYaPao** [getsentry/self-hosted#1386]
### Version

21.6.3

### Steps to Reproduce

1. `make bootstrap`
2. `sentry devserver --workers`

### Expected Result

**Performace** in the sidebar and transaction is active!

### Actual Result

Cannot find entry of performance module.
<img width="200" alt="image" src="https://user-images.githubusercontent.com/46279229/158812029-4330bae1-fa73-404d-9628-db7d06bfd31b.png">

Debugger something:
<img width="925" alt="image" src="https://user-images.githubusercontent.com/46279229/158812215-c39c0be0-5e01-4d6a-b23c-01c064979029.png">

```js
organization.access = [
    "team:read",
    "team:write",
    "team:admin",
    "event:read",
    "project:releases",
    "project:read",
    "alerts:read",
    "member:read",
    "project:admin",
    "member:write",
    "org:integrations",
    "member:admin",
    "alerts:write",
    "project:write",
    "event:write",
    "org:write",
    "event:admin",
    "org:admin",
    "org:read"
]
```

**Comment by Y-lonelY** [comment]
Can i use `sentry permissions add` by adding something to enable it ?

**Comment by chadwhitacre** [comment]
> 1. `make bootstrap`
> 1. `sentry devserver --workers`

These are [dev instructions](https://develop.sentry.dev/environment/#bootstrap-services), not [self-hosted instructions](https://develop.sentry.dev/self-hosted/). So either you're in the wrong repo or you're doing it wrong. Which one is it? :)

**Comment by Y-lonelY** [comment]
> 

Dev instructions is what i need, myabe i'm in the wrong repo, but can you give me some help about this issue? 

Have a great day!

**Comment by chadwhitacre** [comment]
Why are you on an old version 21.6.3 if you are doing dev work? Why not on latest master?
