### ISSUE TITLE
No AWS Lambda Integration

### ISSUE THREAD

**Issue by xXLXx** [getsentry/self-hosted#1389]
### Version

21.1.0

### Steps to Reproduce

I was trying to follow this blog: https://blog.sentry.io/2021/05/24/no-code-aws-lambda-monitoring

### Expected Result

I should be able to see AWS Lambda under integrations
![image (70)](https://user-images.githubusercontent.com/4793838/158932143-07f7eed9-aca5-4b1c-a58f-4a4489828f3b.png)

### Actual Result

There is no AWS when searching for it
![Screenshot 2022-03-16 at 08 44 20](https://user-images.githubusercontent.com/4793838/158932122-39d5410c-a781-41a3-9ef8-62d4fc1c55be.png)

**Comment by chadwhitacre** [comment]
Hrm, not sure if serverless integration works with self-hosted or not, I dropped a line internally @xXLXx.

**Comment by xXLXx** [comment]
> Hrm, not sure if serverless integration works with self-hosted or not, I dropped a line internally @xXLXx.

thanks @chadwhitacre !

**Comment by scefali** [comment]
@xXLXx Hey there, so theoretically it is possible to get the AWS Lambda integration to work for self-hosted users but we haven't written up the instructions as it's rather complicated. In any case, the integration doesn't add any features/abilities that aren't supported by the SDK or layer (the integration just makes it less work to setup and update).  I would suggest just manually setting up the layer with the instructions here: https://docs.sentry.io/platforms/node/guides/aws-lambda/layer/

**Comment by xXLXx** [comment]
@scefali Ahh I see. Actually this link you shared I've already tried and found out that it adds a 2 second duration to all lambda innvocations, which is not too good.

So that's why we thought if there's a way Sentry can just hook up directly to our lambdas and log whatever lambda spits out. And that AWS Lambda integration seems it's doing just that instead of the node code doing the logging

**Comment by xXLXx** [comment]
> @scefali Ahh I see. Actually this link you shared I've already tried and found out that it adds a 2 second duration to all lambda innvocations, which is not too good.
> 
> So that's why we thought if there's a way Sentry can just hook up directly to our lambdas and log whatever lambda spits out. And that AWS Lambda integration seems it's doing just that instead of the node code doing the logging

@scefali @chadwhitacre by any chance is this what this [lambda monitoring setup](https://blog.sentry.io/2021/05/24/no-code-aws-lambda-monitoring) is doing ? Specifically a direct listener to our lambdas instead of the node code logging to Sentry ?

**Comment by chadwhitacre** [comment]
Insight on this one @scefali?

**Comment by scefali** [comment]
@xXLXx @chadwhitacre We are working on improving the experience and performance of Sentry with AWS Lambda. But for now, it's pretty much doing what you see here: https://blog.sentry.io/2021/05/24/no-code-aws-lambda-monitoring
