### ISSUE TITLE
prune old source maps

### ISSUE THREAD

**Issue by tsmt09** [getsentry/self-hosted#1395]
### Version

22.1.0

### Steps to Reproduce

1. uploads lots of source maps

### Expected Result

Method to delete old source maps

### Actual Result

File system is full.

Hello everbody

I got into this new project where we uploaded source maps for every single push CI run (new release created which has the name of a git hash). I would like to delete all of them which are older than X days, but I cannot find a button to "prune old source maps" or something like this.

Actually, I don't really need a button implemented or anything, I would also be happy if you can just provide me where the source map files are located, so I can run a CLI script myself on the containers storage, because I cannot find any ".js.map" files on my sentry onpremise root.

Also, I know sentry source map upload is not supposed to be used like that, so I already changed it. But still I would like to clean up after myself =)

**Comment by chadwhitacre** [comment]
> my sentry onpremise root

It's probably in one of the docker containers, no? Have you looked in the web container? That's where I'd start.

**Comment by chadwhitacre** [comment]
(Also P.S. sorry for the late reply I was [OOO](https://github.com/getsentry/self-hosted/issues/1390) last week.)
