### ISSUE TITLE
Missing support for URL sub paths like `https://example.com/sentry-subpath`

### ISSUE THREAD

**Issue by PhilippMatthes** [getsentry/self-hosted#1396]
### Version

22.4.0.dev0

### Steps to Reproduce

Let's say we have a frontline NGINX proxy which points `localhost/sentry` to the sentry upstream under port 9000. For example:

<details>

```nginx
# An upstream to the sentry environment
upstream sentry {
    server localhost:9000;
}

server {
    listen      80 default_server;
    server_name localhost;

    # Forward the according urls to the respective service
    location /sentry/ {
        proxy_pass http://sentry/;

        include    /etc/nginx/proxy_params;
    }
}
```

Where `/etc/nginx/proxy_params` is as follows.

```nginx
proxy_set_header Host $http_host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
```

</details>

Then set `system.url-prefix: 'http://localhost/sentry'` in `sentry/config.yml`. 

### Expected Result

When the login page is accessed under `http://localhost/sentry`, it should redirect to `http://localhost/sentry/auth/login`.

### Actual Result

Instead, it redirects to `http://localhost/auth/login` which is unavailable (see example NGINX config).

**Comment by chadwhitacre** [comment]
Have you searched the web and/or [the old forums](https://forum.sentry.io/c/on-premise/7) for other folks trying to do this?

**Comment by chadwhitacre** [comment]
I don't know whether Sentry is designed to support mounting on non-root paths or not. Searching the web would be a next step, then grepping/reading [code](https://github.com/getsentry/sentry).

**Comment by chadwhitacre** [comment]
I dropped a line internally to see if anyone has an answer off the top of their head.

**Comment by PhilippMatthes** [comment]
Thanks @chadwhitacre, I already researched a bit, also in the code of Sentry. Since I exhausted all of the above sources, I came to open this issue.

**Comment by HorseLuke** [comment]
Two years ago (2020) someone posted same question, the answer was no: https://forum.sentry.io/t/how-to-change-the-default-root-url-in-sentry/9889 

And neither one year ago: https://forum.sentry.io/t/add-url-prefix-in-reverse-proxy/14018/3

In fact we have a very restricted deployment scenario that need such feature. In this restricted deployment scenario, only one port is allowed to be exposed to Internet by firewall. The solution is to set up nginx with this port, and use proxy_pass with location to proxy other internal app. But sentry does not support sub path, we can not do such method.

**Comment by PhilippMatthes** [comment]
Correct me if I am wrong, but neither of above resources show a sufficient solution to the problem. Setting `system.url-prefix` does not work, as explained in the initial problem description:

> Steps to reproduce
> [...]
> Then set system.url-prefix: 'http://localhost/sentry' in sentry/config.yml.

The other resource simply ends with a reply, that this feature is not supported. However, I think that a lot of people who want to reuse this framework depend on it being able to bind behind a sub url. If this feature is not supported, as proclaimed in the title of this issue, it should be from my pov.

**Comment by HorseLuke** [comment]
@PhilippMatthes seems that this feature was removed from 2019  :(

https://github.com/getsentry/sentry/commit/cab678a6e263df574cfc45d9b9280e16c074f670#diff-34247419429b1cc8f6951fcbbdb3dfe6953b8e3442f984f6005f3886f3acef98

**Comment by chadwhitacre** [comment]
Good find @HorseLuke! I don't see `FORCE_SCRIPT_NAME` mentioned anywhere else on https://github.com/getsentry/sentry/pull/12613 (nor in the current codebase). How was it actually used? How hard would it be to bring back? I can discuss internally if there is appetite for bringing this back if someone wants to make the PR.

**Comment by PhilippMatthes** [comment]
@github-actions This is not resolved, and we still have the demand for this to be solved ASAP.

**Comment by chadwhitacre** [comment]
Putting this on the backlog so the bot won't close. Best I can do for now.

**Comment by chadwhitacre** [comment]
Ftr this ended up at https://github.com/getsentry/sentry/issues/34760.
