### ISSUE TITLE
first time install failed

### ISSUE THREAD

**Issue by mowangjuanzi** [getsentry/self-hosted#1400]
### Version

22.3.0

### Steps to Reproduce

1. download repo.
```bash
git clone git@github.com:getsentry/self-hosted.git sentry
cd sentry
git checkout tags/22.3.0
```

2. change .env: `SENTRY_BIND` from `9000` to `9999`

3. run `install.sh` command.

### Expected Result

install success.

### Actual Result

$ sudo ./install.sh 
▶ Parsing command line ...

▶ Initializing Docker Compose ...

▶ Setting up error handling ...

▶ Checking for latest commit ... 

▶ Checking minimum requirements ...
Found Docker version 20.10.13
Found Docker Compose version 2.3.4
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
554879bb3004: Pulling fs layer
554879bb3004: Download complete
554879bb3004: Pull complete
Digest: sha256:caa382c432891547782ce7140fb3b7304613d3b0438834dce1cad68896ab110a
Status: Downloaded newer image for busybox:latest

▶ Turning things off ...
Network sentry-self-hosted_default  Removing
Network sentry-self-hosted_default  Error
failed to remove network sentry-self-hosted_default: Error: No such network: sentry-self-hosted_default
An error occurred, caught SIGERR on line 8
Cleaning up...

**Comment by dpvdberg** [comment]
I had the same problem, it seems the install script does not support the latest docker-comopse version.
Downgrading (I used [v2.2.3](https://github.com/docker/compose/releases/tag/v2.2.3)) worked for me.

**Comment by aminvakil** [comment]
@dpvdberg Thanks!

Yes, I'm not sure if this behaviour is going to be persistent in the next `docker-compose` releases too, we should definitely do something about it if that's the case.

Please tell us if downgrading to [v2.2.3](https://github.com/docker/compose/releases/tag/v2.2.3) didn't work out.

**Comment by chadwhitacre** [comment]
> it seems the install script does not support the latest docker-compose version

What broke? Does anyone know?

**Comment by aminvakil** [comment]
Maybe https://github.com/docker/compose/pull/9281? I can't see anything else in [v2.3.4](https://github.com/docker/compose/releases/tag/v2.3.4) regarding removing non-created volumes/networks.

**Comment by aminvakil** [comment]
@mowangjuanzi This has been fixed in https://github.com/docker/compose/releases/tag/v2.4.0.

Right now latest release is v2.4.1 .
