### ISSUE TITLE
install.sh get stuck in 'Bootstrapping and migrating Snuba'

### ISSUE THREAD

**Issue by azerpas** [getsentry/self-hosted#1404]
### Version

22.3.0

## Setup
- WSL 
- Ubuntu 20.4

## Steps
1. Clone the 22.3.0
2. Set the .env with STMP host and Postgres user
3. Run `./install.sh`

### Expected Result

Containers get created and bootstrap starts to connect to kafka

### Actual Result

```
...
Docker images built.

▶ Setting up Zookeeper ...
Network sentry-self-hosted_default  Creating
Network sentry-self-hosted_default  Created

▶ Downloading and installing wal2json ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5417  100  5417    0     0  12459      0 --:--:-- --:--:-- --:--:-- 12481

▶ Bootstrapping and migrating Snuba ...
Container sentry-self-hosted-zookeeper-1  Creating
Container sentry-self-hosted-redis-1  Creating
Container sentry-self-hosted-clickhouse-1  Creating
Container sentry-self-hosted-clickhouse-1  Created
Container sentry-self-hosted-redis-1  Created
Container sentry-self-hosted-zookeeper-1  Created
Container sentry-self-hosted-kafka-1  Creating
Container sentry-self-hosted-kafka-1  Created
Container sentry-self-hosted-clickhouse-1  Starting
Container sentry-self-hosted-redis-1  Starting
Container sentry-self-hosted-zookeeper-1  Starting
Container sentry-self-hosted-redis-1  Started
Container sentry-self-hosted-zookeeper-1  Started
Container sentry-self-hosted-clickhouse-1  Started
Container sentry-self-hosted-kafka-1  Starting
Container sentry-self-hosted-kafka-1  Started
```

And then it get stuck here forever

Full logs with DEBUG=1 [here](https://gist.github.com/azerpas/558c2a2e72b45423a1a70a8abccbfd3a)

**Comment by chadwhitacre** [comment]
Hrm, you've updated in the past successfully, yes? What version are you upgrading from?

Your log shows it failing under `snuba-api bootstrap` (not `migrations migrate`).

https://github.com/getsentry/self-hosted/blob/5911acb9dd48fc2b95df062f994c290dabec556b/install/bootstrap-snuba.sh#L3

Can you try running that command directly at that point? Maybe there is some additional logging under `snuba-api` that you can enable? Does `snuba-api --help` and/or `snuba-api bootstrap --help` suggest anything?

> And then it get stuck here forever

How long is forever? :)

It looks like a couple of the containers are in "starting" state. Can you monitor with `docker ps` or `docker stats` or whatever and observe behavior over time vs. static snapshot?

**Comment by chadwhitacre** [comment]
Okay, same questions as above then. :)

**Comment by aminvakil** [comment]
Not sure if this is the same issue or not, but it's a couple of days I'm seeing this regression on docker-compose 1.28.0 and 1.29.2 too.

https://github.com/aminvakil/self-hosted/actions/runs/2068250465
https://github.com/aminvakil/self-hosted/actions/runs/2074457629
https://github.com/aminvakil/self-hosted/actions/runs/2080468698
https://github.com/aminvakil/self-hosted/actions/runs/2083753352

This is a clean installation of course :)

And the error is different:
```
Bootstrapping and migrating Snuba ...
  Container self-hosted-0-clickhouse-1  Creating
  Container self-hosted-0-redis-1  Creating
  Container self-hosted-0-zookeeper-1  Creating
  Container self-hosted-0-clickhouse-1  Created
  Container self-hosted-0-zookeeper-1  Created
  Container self-hosted-0-kafka-1  Creating
  Container self-hosted-0-redis-1  Created
  Container self-hosted-0-kafka-1  Created
  Container self-hosted-0-redis-1  Starting
  Container self-hosted-0-zookeeper-1  Starting
  Container self-hosted-0-clickhouse-1  Starting
  Container self-hosted-0-redis-1  Started
  Container self-hosted-0-zookeeper-1  Started
  Container self-hosted-0-zookeeper-1  Waiting
  Container self-hosted-0-clickhouse-1  Started
  Container self-hosted-0-zookeeper-1  Healthy
  Container self-hosted-0-kafka-1  Starting
  Container self-hosted-0-kafka-1  Started
  Container self-hosted-0-kafka-1  Waiting
  Container self-hosted-0-redis-1  Waiting
  no such service: web
  An error occurred, caught SIGERR on line 3
  *NOT* cleaning up, to clean your environment run "docker compose stop".
  Error: Process completed with exit code 1.
```

And oddly this is not happening on https://github.com/getsentry/self-hosted CI :thinking: 

@azerpas @rodolphewachter What docker-compose version are you using? Are your errors the same as this?

**Comment by azerpas** [comment]
@chadwhitacre 

> Hrm, you've updated in the past successfully, yes? What version are you upgrading from?

No, first install actually. 

> Can you try running that command directly at that point? Maybe there is some additional logging under snuba-api that you can enable? Does snuba-api --help and/or snuba-api bootstrap --help suggest anything?

I'm unable to run `snuba-api` commands through Docker and I can't seem to find documentation to install a CLI.

> How long is forever? :)

I'll say an hour. :/


@aminvakil

> @azerpas @rodolphewachter What docker-compose version are you using? Are your errors the same as this?

Using Docker Compose version v2.2.3 and sadly not the same error.

**Comment by azerpas** [comment]
`docker ps` result: 

``` 
6b237ff16ad7   confluentinc/cp-kafka:5.5.0          "/etc/confluent/dock…"   7 minutes ago   Up 6 minutes (healthy)            9092/tcp                                        sentry-self-hosted-kafka-1
7b8fa13b6132   confluentinc/cp-zookeeper:5.5.0      "/etc/confluent/dock…"   7 minutes ago   Up 7 minutes (healthy)            2181/tcp, 2888/tcp, 3888/tcp                    sentry-self-hosted-zookeeper-1
b2da48aab1e5   yandex/clickhouse-server:20.3.9.70   "/entrypoint.sh"         7 minutes ago   Up 7 minutes (health: starting)   8123/tcp, 9000/tcp, 9009/tcp                    sentry-self-hosted-clickhouse-1
58d5cfdceeb4   redis:6.2.4-alpine                   "docker-entrypoint.s…"   7 minutes ago   Up 7 minutes (healthy)            6379/tcp                                        sentry-self-hosted-redis-1
```

It looks like the clickhouse server is not starting and when checking the logs I get multiple errors:

```
2022.04.04 07:51:52.043415 [ 1 ] {} <Error> Application: Listen [::]:8123 failed: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = DNS error: EAI: -9 (version 20.3.9.70 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>

2022.04.04 07:51:52.043756 [ 1 ] {} <Error> Application: Listen [::]:9000 failed: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = DNS error: EAI: -9 (version 20.3.9.70 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>

2022.04.04 07:51:52.044102 [ 1 ] {} <Error> Application: Listen [::]:9009 failed: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = DNS error: EAI: -9 (version 20.3.9.70 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>

2022.04.04 07:51:52.044430 [ 1 ] {} <Error> Application: Listen [::]:9004 failed: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = DNS error: EAI: -9 (version 20.3.9.70 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
```

Which seems related to #1402

**Comment by azerpas** [comment]
Update: I've managed to get past this error by opening the required ports in my firewall. 🎉

Quick note on what I did:
## Setup for Windows WSL2 (Ubuntu 20.4) w/ corporate proxy

### Build with a proxy
I've modified the ./install/build-docker-images.sh file by adding a `--build-arg` for my proxy:
```
$dc build --force-rm --build-arg http_proxy=http://host.docker.internal:3128
```

### Solving this issue
Opened the required ports inside Windows Firewall (Inbound, TCP)
```
9092, 2181, 2888, 3888, 8123, 9000, 9009, 6379
```

**Comment by chadwhitacre** [comment]
Glad you figured it out @azerpas, thanks for posting back! :)

**Comment by aminvakil** [comment]
> Not sure if this is the same issue or not, but it's a couple of days I'm seeing this regression on docker-compose 1.28.0 and 1.29.2 too.
> 
> https://github.com/aminvakil/self-hosted/actions/runs/2068250465 https://github.com/aminvakil/self-hosted/actions/runs/2074457629 https://github.com/aminvakil/self-hosted/actions/runs/2080468698 https://github.com/aminvakil/self-hosted/actions/runs/2083753352
> 
> This is a clean installation of course :)
> 
> And the error is different:
> 
> ```
> Bootstrapping and migrating Snuba ...
>   Container self-hosted-0-clickhouse-1  Creating
>   Container self-hosted-0-redis-1  Creating
>   Container self-hosted-0-zookeeper-1  Creating
>   Container self-hosted-0-clickhouse-1  Created
>   Container self-hosted-0-zookeeper-1  Created
>   Container self-hosted-0-kafka-1  Creating
>   Container self-hosted-0-redis-1  Created
>   Container self-hosted-0-kafka-1  Created
>   Container self-hosted-0-redis-1  Starting
>   Container self-hosted-0-zookeeper-1  Starting
>   Container self-hosted-0-clickhouse-1  Starting
>   Container self-hosted-0-redis-1  Started
>   Container self-hosted-0-zookeeper-1  Started
>   Container self-hosted-0-zookeeper-1  Waiting
>   Container self-hosted-0-clickhouse-1  Started
>   Container self-hosted-0-zookeeper-1  Healthy
>   Container self-hosted-0-kafka-1  Starting
>   Container self-hosted-0-kafka-1  Started
>   Container self-hosted-0-kafka-1  Waiting
>   Container self-hosted-0-redis-1  Waiting
>   no such service: web
>   An error occurred, caught SIGERR on line 3
>   *NOT* cleaning up, to clean your environment run "docker compose stop".
>   Error: Process completed with exit code 1.
> ```
> 
> And oddly this is not happening on https://github.com/getsentry/self-hosted CI thinking
> 
> @azerpas @rodolphewachter What docker-compose version are you using? Are your errors the same as this?

@chadwhitacre Do you think we need a new issue to follow this?

**Comment by chadwhitacre** [comment]
> Do you think we need a new issue to follow this?

Yes, if you think it is worth investigating further.
