### ISSUE TITLE
Typo on releases page

### ISSUE THREAD

**Issue by raytio** [getsentry/self-hosted#1409]
### Version

22.3.0

### Steps to Reproduce

https://github.com/getsentry/self-hosted/releases/tag/22.3.0

`COMPOSE_PROJECT_NAME=sentry_onpremise docker compose down --rmi local --remove-orphans`

should read

`COMPOSE_PROJECT_NAME=sentry_onpremise docker-compose down --rmi local --remove-orphans`

### Expected Result

N/A

### Actual Result

N/A

**Comment by aminvakil** [comment]
It's not a typo, `docker compose` has been changed to be a docker plugin (by default) since v2, hence you should use `docker compose` instead of `docker-compose` to use it.

(This can be changed by creating a symlink though.)
