### ISSUE TITLE
Self-Hosted Sentry cannot get Issues When use the domain name to access the web application

### ISSUE THREAD

**Issue by Ayildiz89** [getsentry/self-hosted#1411]
### Problem Statement

Self-Hosted Sentry cannot get Issues When use the domain name to access the web application

Sentry are working on my own server as docker-container , it gets the issues from local url (localhost:xxxx) but are not  getting from domain nmae !!!!

**Comment by chadwhitacre** [comment]
Gonna need some more info to help you debug @Ayildiz89. What does your browser show you when you try to access your Sentry installation via your domain name? How about dev tools? What logging do you see in your Sentry containers?

**Comment by Ayildiz89** [comment]
Hi  @chadwhitacre ,
Sory i replied  late , We are able to connect with domain name , the problem is when we create a new project , Sentry gives dsn number  with ip addres without domain name  like this dsn:  http://7d376946a132ybb2842txfa583c85vec@13.26.47.154:9000/9 ..

**Comment by chadwhitacre** [comment]
Hrm, this is probably some missing config on your side, maybe `system.url-prefix`? Did you read about this [in the docs](https://develop.sentry.dev/config/)?

**Comment by Ayildiz89** [comment]
system.internal-url-prefix: 'http://sentry.mydomainaddress'
symbolicator.enabled: true
symbolicator.options:
  url: "http://symbolicator:3021"

this is my configuration in config.yaml file of Sentry

**Comment by chadwhitacre** [comment]
Are you still stuck with this @Ayildiz89? Did you figure anything out?
