### ISSUE TITLE
Sentry on premise cannot change DSN key 

### ISSUE THREAD

**Issue by iulian0512** [getsentry/self-hosted#1413]
### Version

22.3.0

### Steps to Reproduce

I have a flutter app that has a few hundred installs and has a hardcoded sentry url, i had a problem and had to reinstall sentry on premise on a new machine. 
I found no way to change the dsn key part:
https://**9ffc87ba7dc54bb9af7408663c2fa03c**@myhostname:9000/2
Reinstalling the app on a few hundred devices is a big no-no.

### Expected Result

I expect to be able to change the dsn key part to match the old install.

### Actual Result

unable to change the dsn key field is readonly in 
ProjectSettings->Client Keys->Details

**Comment by chadwhitacre** [comment]
Hrm, if you don't see a way to change it through the UI then I guess a couple workarounds would be to rewrite it manually in your database, or rewrite it dynamically in nginx. Would one of these get you unstuck?

**Comment by iulian0512** [comment]
> Hrm, if you don't see a way to change it through the UI then I guess a couple workarounds would be to rewrite it manually in your database, or rewrite it dynamically in nginx. Would one of these get you unstuck?

i manually modified the key in the database, this would be really useful to be presented in the user manual.

**Comment by chadwhitacre** [comment]
@iulian0512 Nice, glad you figured it out. Want to post some notes here describing the process you followed? That will at least give people something to find in the future, and we can consider folding into the dev docs.

**Comment by iulian0512** [comment]
i stopped all docker services then modified the pgconfig to allow connection via its default port then edited the row with the current generated dsn key, i do not remember the table name but it was named intuitively.

**Comment by chadwhitacre** [comment]
Gonna go ahead and close this out as we have a workaround documented here.
