### ISSUE TITLE
ERROR: Encountered errors while bringing up the project.

### ISSUE THREAD

**Issue by lanzhu1993** [getsentry/self-hosted#1418]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

21.10.0

### Steps to Reproduce

 I execute on CentOS 7.0 docker-compose up -d

Creating sentry-self-hosted_postgres_1             ... done
Creating sentry-self-hosted_geoipupdate_1          ... done
Creating sentry-self-hosted_clickhouse_1           ... done
Creating sentry-self-hosted_smtp_1                 ... done
Creating sentry-self-hosted_zookeeper_1            ... done
Creating sentry-self-hosted_symbolicator_1         ... done
Creating sentry-self-hosted_symbolicator-cleanup_1 ... done
Creating sentry-self-hosted_redis_1                ... done
Creating sentry-self-hosted_memcached_1            ... done
Creating sentry-self-hosted_kafka_1                ... done
Creating sentry-self-hosted_snuba-transactions-consumer_1              ... done
Creating sentry-self-hosted_snuba-replacer_1                           ... done
Creating sentry-self-hosted_snuba-subscription-consumer-transactions_1 ... done
Creating sentry-self-hosted_snuba-subscription-consumer-events_1       ... done
Creating sentry-self-hosted_snuba-sessions-consumer_1                  ... done
Creating sentry-self-hosted_snuba-cleanup_1                            ... done
Creating sentry-self-hosted_snuba-outcomes-consumer_1                  ... done
Creating sentry-self-hosted_snuba-consumer_1                           ... done
Creating sentry-self-hosted_snuba-transactions-cleanup_1               ... done
Creating sentry-self-hosted_snuba-api_1                                ... done

ERROR: for cron  Container "39eca2065a27" is unhealthy.

ERROR: for worker  Container "39eca2065a27" is unhealthy.

ERROR: for subscription-consumer-transactions  Container "39eca2065a27" is unhealthy.

ERROR: for web  Container "39eca2065a27" is unhealthy.

ERROR: for sentry-cleanup  Container "39eca2065a27" is unhealthy.

ERROR: for ingest-consumer  Container "39eca2065a27" is unhealthy.

ERROR: for post-process-forwarder  Container "39eca2065a27" is unhealthy.

ERROR: for subscription-consumer-events  Container "39eca2065a27" is unhealthy.

### Expected Result

Expect no errors when executing **docker-compose up -d** commands

### Actual Result

Can you help me see what the problem is? Thanks

**Comment by chadwhitacre** [comment]
What do the logs show for the unhealthy containers?

**Comment by aminvakil** [comment]
CentOS 7.0 is so ancient, full of bugs, please upgrade your system to CentOS 7.9.

Also could you please paste output of these commands:
```
docker --version
docker-compose --version
```

**Comment by lanzhu1993** [comment]
> CentOS 7.0 is so ancient, full of bugs, please upgrade your system to CentOS 7.9.
> 
> Also could you please paste output of these commands:
> 
> ```
> docker --version
> docker-compose --version
> ```

[root@localhost /]# docker --version
Docker version 20.10.14, build a224086
[root@localhost /]# docker-compose --version
docker-compose version 1.29.2, build 5becea4c

**Comment by lanzhu1993** [comment]
> What do the logs show for the unhealthy containers?

What commands can be executed to output logs? I checked the relevant issue and didn't solve it。[#1211](https://github.com/getsentry/self-hosted/issues/1211)

**Comment by chadwhitacre** [comment]
@lanzhu1993 Did you figure something out here? Anything you can share for the next person?

**Comment by lanzhu1993** [comment]
> Did you figure something out here? Anything you can share for the next person

The main reason is because of the network restrictions and the change of my CentOS to version 7.9. I used the network agent to re execute install.sh, after docker compose up - d is executed, the service can be created. If the overall execution is successful, I will close the issue. Thanks

**Comment by chadwhitacre** [comment]
Thanks for posting back! :)
