### ISSUE TITLE
Owner cannot remove users。

### ISSUE THREAD

**Issue by yangmei123** [getsentry/self-hosted#1427]
### Version

22.2.0

### Steps to Reproduce

I'm owner want to remove user。

### Expected Result

user can be successfully deleted。

### Actual Result

 delete user failer。

response：Missing required permission to hard delete account.
![image](https://user-images.githubusercontent.com/15100752/163916607-57e1eddb-f066-4d73-b371-2c1379a955f5.png)
![Uploading image.png…]()

![image](https://user-images.githubusercontent.com/15100752/163916535-7bf5d4ce-3fdd-45a0-9535-77691d71e508.png)

![image](https://user-images.githubusercontent.com/15100752/163916700-0f9840ea-46d5-4ad4-b3eb-4add6dcf7b7f.png)

Can anyone tell me. Am I missing some configuration? I got this error on both local and production environments. Let me know if you have any suggestions. Thank you very much. Looking forward to reply.

**Comment by yangmei123** [comment]
The problem has been solved. Permission loss due to upgrade. And the following questions are the same.
https://github.com/getsentry/self-hosted/issues/1288

Execute the command to add permission:
`docker exec -ti sentry-self-hosted_web_1 sentry permissions add -u xxx@xxx.com -p "users.admin"`

**Comment by chadwhitacre** [comment]
Thanks for following up @yangmei123, glad you were able to figure it out.
