### ISSUE TITLE
Alert Notifications sent to Internal Integration after removal from Alert Rules

### ISSUE THREAD

**Issue by JMcConahie** [getsentry/self-hosted#1429]
### Version

22.2.0

### Steps to Reproduce

1. Add a "Send a notification via an Integration" Action to an alert
2. Select an Internal Integration
3. Trigger the alert
4. Remove the Internal Integration from the alert rule actions
5. Trigger the alert again

### Expected Result

Notification shouldn't be sent after the internal integration is removed from the actions list in the alert rules.

### Actual Result

Notifications are still being sent to the internal integration, even though it's been removed from the alert rules actions.

**Comment by JMcConahie** [comment]
I think I may have figured out what was going on. We have the action "Send a notification (for all legacy integrations)" on the alert as well. It appears that may send to internal integrations that are set up also, not just the legacy integrations. This is my working theory at the moment.

**Comment by JMcConahie** [comment]
The problem seemed to be that the webhooks boxes were checked for the integration, which would send to the integration whether it was an action on the alert or not any time an issue was created. Unchecking the webhook boxes fixed that problem, but now I can't send to the integration at all, even when adding to alert actions.

**Comment by JMcConahie** [comment]
I think I fixed the issue by modifying the action interval of the alert to something smaller. It was previously set at 12 hours, but I think because I was triggering the same alert via a test case, it was getting ignored. So I guess just user error all around.

**Comment by aminvakil** [comment]
Thanks for reporting back!
