### ISSUE TITLE
Install.sh error: Error response from daemon: start failed: : fork/exec /usr/bin/containerd-shim-runc-v2: resource temporarily unavailable: unknown

### ISSUE THREAD

**Issue by lthamm** [getsentry/self-hosted#1438]
### Version

22.4.0

### Steps to Reproduce

1. Download latest release 
2. ./install.sh
3. Fail

### Expected Result

Installation of sentry

### Actual Result

Installation fails with response:
`Error response from daemon: start failed: : fork/exec /usr/bin/containerd-shim-runc-v2: resource temporarily unavailable: unknown`

I've found a related issue here:
https://forum.sentry.io/t/install-sh-file-error/13632
which suggested checking the requirements:
```zsh
set -x
export dc="docker-compose --no-ansi"
source ./install/check-minimum-requirements.sh
```

which gives me this output:
```zsh
+ source ./install/check-minimum-requirements.sh
++ echo 'Checking minimum requirements ...'
Checking minimum requirements ...
+++ dirname -bash
dirname: Ungültige Option -- b
„dirname --help“ liefert weitere Informationen.
++ source /_min-requirements.sh
-bash: /_min-requirements.sh: Datei oder Verzeichnis nicht gefunden
+++ docker version --format '{{.Server.Version}}'
++ DOCKER_VERSION=20.10.14
+++ ver 20.10.14
+++ awk -F. '{ printf("%d%03d%03d", $1,$2,$3); }'
+++ echo 20.10.14
+++ ver
+++ echo
+++ awk -F. '{ printf("%d%03d%03d", $1,$2,$3); }'
++ [[ 20010014 -lt 0000000 ]]
++ echo 'Found Docker version 20.10.14'
Found Docker version 20.10.14
+++ version
-bash: version: Befehl nicht gefunden
+++ head -n1
+++ sed -E 's/^.* version:? v?([0-9.]+),?.*$/\1/'
++ COMPOSE_VERSION=
+++ ver
+++ awk -F. '{ printf("%d%03d%03d", $1,$2,$3); }'
+++ echo
+++ ver
+++ echo
+++ awk -F. '{ printf("%d%03d%03d", $1,$2,$3); }'
++ [[ 0000000 -lt 0000000 ]]
++ echo 'Found Docker Compose version '
Found Docker Compose version 
+++ docker run --rm busybox nproc --all
++ CPU_AVAILABLE_IN_DOCKER=6
++ [[ 6 -lt '' ]]
++ [[ 6 -lt '' ]]
+++ awk '/Mem/ {print $2}'
+++ docker run --rm busybox free -m
++ RAM_AVAILABLE_IN_DOCKER=16384
++ [[ 16384 -lt '' ]]
++ [[ 16384 -lt '' ]]
+++ docker run --rm busybox grep -c 'Common KVM processor' /proc/cpuinfo
+++ :
++ IS_KVM=0
++ [[ 0 -eq 0 ]]
+++ docker run --rm busybox grep -c sse4_2 /proc/cpuinfo
++ SUPPORTS_SSE42=6
++ [[ 6 -eq 0 ]]
++ echo ''
```

**Comment by chadwhitacre** [comment]
> Error response from daemon: start failed: : fork/exec /usr/bin/containerd-shim-runc-v2: resource temporarily unavailable: unknown

Initial response is some resource constraint in your environment. Do you have enough RAM/disk? What operating system are you on? What version?

**Comment by lthamm** [comment]
Thanks for the fast response! I suspected that but could not figure where that would come from.
I have 497 GB of free ssd space and  15 GB free RAM during idle. This is on Ubuntu 20.04 LTS.

**Comment by chadwhitacre** [comment]
What version of Docker?

```
$ docker version
```

**Comment by lthamm** [comment]
The version is 20.10.14

**Comment by aminvakil** [comment]
Can you try `docker run hello-world`?

**Comment by lthamm** [comment]
`Hello from Docker!
This message shows that your installation appears to be working correctly.`

**Comment by aminvakil** [comment]
> `Hello from Docker! This message shows that your installation appears to be working correctly.`

Hmm, I'm suspecting you've hit a kernel limit now...

Try adding this to `/etc/security/limits.conf` to remove all kernel limits and reboot and see if it helps.

```
* soft core unlimited
* hard core unlimited
* soft data unlimited
* hard data unlimited
* soft fsize unlimited
* hard fsize unlimited
* soft memlock unlimited
* hard memlock unlimited
* soft nofile 1048576
* hard nofile 1048576
* soft rss unlimited
* hard rss unlimited
* soft stack unlimited
* hard stack unlimited
* soft cpu unlimited
* hard cpu unlimited
* soft nproc unlimited
* hard nproc unlimited
* soft as unlimited
* hard as unlimited
* soft maxlogins unlimited
* hard maxlogins unlimited
* soft maxsyslogins unlimited
* hard maxsyslogins unlimited
* soft locks unlimited
* hard locks unlimited
* soft sigpending unlimited
* hard sigpending unlimited
* soft msgqueue unlimited
* hard msgqueue unlimited
```

Just keep in mind that this is a temporary resolution to see if this is your problem or not, you should not ever do this on a production system.

**Comment by aminvakil** [comment]
Just saw:
```
+++ version
-bash: version: Befehl nicht gefunden
```
and google translate tells me that means `command not found` :)

It shouldn't try executing `version`, of course `version` is not a command.

That may be because of this line:
`COMPOSE_VERSION=$($dc_base version | head -n1 | sed -E 's/^.* version:? v?([0-9.]+),?.*$/\1/')`
and because `$dc_base` is an empty variable, and so I'm thinking what is wrong with docker-compose?

What is the output of `docker-compose --version`?

**Comment by lthamm** [comment]
I came across that as well but was not able to figure out what is going on. Docker compose works: `Docker Compose version v2.5.0`.
Should docker-compose export $dc_base? I've manually exported `dc` (see initial post) and I have now exported `export dc_base="docer-compose"`after your message, which changes the output too what I would expect:
```zsh
+++ docker-compose version
+++ sed -E 's/^.* version:? v?([0-9.]+),?.*$/\1/'
+++ head -n1
++ COMPOSE_VERSION=2.5.0
+++ ver 2.5.0
+++ awk -F. '{ printf("%d%03d%03d", $1,$2,$3); }'
+++ echo 2.5.0
+++ ver
+++ awk -F. '{ printf("%d%03d%03d", $1,$2,$3); }'
+++ echo
++ [[ 2005000 -lt 0000000 ]]
++ echo 'Found Docker Compose version 2.5.0'
Found Docker Compose version 2.5.0
```

**Comment by aminvakil** [comment]
If executing `./install.sh` cannot set `$dc_base` correctly, there is something wrong.

There shouldn't be a need to export it manually.

I'd suggest running this section manually and catch errors here first rather than trying to manually setting variables.
https://github.com/getsentry/self-hosted/blob/a1288b082b5db1598806e8c486f665c3c99ac8ee/install.sh#L12-L17

**Comment by lthamm** [comment]
```zsh
/onpremise/install#  source parse-cli.sh 
▶ Parsing command line ...
```

dc-dectect-version fails (translated): 
```
source dc-detect-version.sh
▶ Initializing Docker Compose ...
basename: Invaild operation -- b
„basename --help“ gives more information
```

error-handling.sh and check-latest-commit.sh run without error and without output. And then min requirements fail:

```zsh
source check-minimum-requirements.sh
▶ Checking minimum requirements ...
dirname: Ungültige Option -- b
„dirname --help“ liefert weitere Informationen.
-bash: /_min-requirements.sh: Datei oder Verzeichnis nicht gefunden
An error occurred, caught SIGERR on line 3
Cleaning up...
Found Docker version 20.10.14
Found Docker Compose version 2.5.0
```

**Comment by chadwhitacre** [comment]
From the Discussions version of this thread:

@aminvakil:

> I can't find it now, but I saw something before about zsh in your logs. Are you using zsh, and if so, can you try using bash?

@lthamm:

> I wrote the code formatting as zsh (out of habit), but it actually is bash.

@aminvakil:

>> ```
>> source dc-detect-version.sh
>> ▶ Initializing Docker Compose ...
>> basename: Invaild operation -- b
>> „basename --help“ gives more information
>> ```
>
> I don't know what is not working with your environment, but this script be should definitely working, and I'd suggest try figuring out what's wrong here first instead of the whole `install.sh`.

**Comment by aminvakil** [comment]
@lthamm Has your problem been fixed?

**Comment by aminvakil** [comment]
> Thanks for getting back to me! I tried running after a fresh install of Ubuntu
> 
> ```
> set -x
> export dc="docker-compose --no-ansi"
> source ./install/check-minimum-requirements.sh
> ```
> 
> again and it is still failing with the same output.

Specifying only `check-minimum-requirements.sh` without previous scripts fails for me too:
```
$ bash ./install/check-minimum-requirements.sh 
Checking minimum requirements ...
Found Docker version 20.10.17
./install/check-minimum-requirements.sh: line 16: version: command not found
FAIL: Expected minimum  version to be 1.28.0 but found
```

Try `./install.sh` again and if it failed, specify commands written in `install.sh` one by one from top.
