### ISSUE TITLE
Changelog for v22.0.0

### ISSUE THREAD

**Issue by mrleblanc101** [getsentry/self-hosted#1444]
### Version

22.0.0

### Steps to Reproduce

There is no changelog for this version.
Does the changelog in 22.1.0 include the change in 22.0.0 ?
If not, what are the change in 22.0.0

### Expected Result

Provide a changelog for v22.0.0

### Actual Result

There is no changelog for this version.

**Comment by aminvakil** [comment]
There isn't a v22.0.0 version at all.

https://github.com/getsentry/self-hosted/releases

Sentry is released on 15th of every month and v22.1.0 is release on 2022/01/15 for example. So there cannot be a v22.0.0 version.
