### ISSUE TITLE
snuba-subscription-consumer-events: KeyError: 'query'

### ISSUE THREAD

**Issue by failoman23** [getsentry/self-hosted#1472]
### Version

22.4.0

### Steps to Reproduce

Upgrade path: 20.12.1 -> 21.6.3 -> 22.4.0

I had tu run install.sh twice because of forgotten proxy settings.

Problem: after upgrading to 22.4.0 is that **snuba-subscription-consumer-events** container keeps restarting with following error:

> today at 09:42:342022-05-17 07:42:34,727 Processor terminated
> today at 09:42:34Traceback (most recent call last):
> today at 09:42:34  File "/usr/local/bin/snuba", line 33, in <module>
> today at 09:42:34    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
> today at 09:42:34  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
> today at 09:42:34    return self.main(*args, **kwargs)
> today at 09:42:34  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
> today at 09:42:34    rv = self.invoke(ctx)
> today at 09:42:34  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
> today at 09:42:34    return _process_result(sub_ctx.command.invoke(sub_ctx))
> today at 09:42:34  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
> today at 09:42:34    return ctx.invoke(self.callback, **ctx.params)
> today at 09:42:34  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
> today at 09:42:34    return callback(*args, **kwargs)
> today at 09:42:34  File "/usr/src/snuba/snuba/cli/subscriptions.py", line 283, in subscriptions
> today at 09:42:34    batching_consumer.run()
> today at 09:42:34  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 118, in run
> today at 09:42:34    self._run_once()
> today at 09:42:34  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 156, in _run_once
> today at 09:42:34    self.__processing_strategy.submit(self.__message)
> today at 09:42:34  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/batching.py", line 158, in submit
> today at 09:42:34    result = self.__worker.process_message(message)
> today at 09:42:34  File "/usr/src/snuba/snuba/subscriptions/worker.py", line 224, in process_message
> today at 09:42:34    return [
> today at 09:42:34  File "/usr/src/snuba/snuba/subscriptions/worker.py", line 224, in <listcomp>
> today at 09:42:34    return [
> today at 09:42:34  File "/usr/src/snuba/snuba/subscriptions/scheduler.py", line 354, in find
> today at 09:42:34    subscriptions = self.__get_subscriptions()
> today at 09:42:34  File "/usr/src/snuba/snuba/subscriptions/scheduler.py", line 333, in __get_subscriptions
> today at 09:42:34    for uuid, data in self.__store.all()
> today at 09:42:34  File "/usr/src/snuba/snuba/subscriptions/store.py", line 70, in all
> today at 09:42:34    return [
> today at 09:42:34  File "/usr/src/snuba/snuba/subscriptions/store.py", line 71, in <listcomp>
> today at 09:42:34    (UUID(key.decode("utf-8")), self.codec.decode(val))
> today at 09:42:34  File "/usr/src/snuba/snuba/subscriptions/codecs.py", line 34, in decode
> today at 09:42:34    return SubscriptionData.from_dict(data, self.entity_key)
> today at 09:42:34  File "/usr/src/snuba/snuba/subscriptions/data.py", line 184, in from_dict
> today at 09:42:34    query=data["query"],
> today at 09:42:34KeyError: 'query'

I looked at install.sh upgrade log and found this:

> Query Subscriptions: N/A% |                                     | ETA:  --:--:--  Applying sentry.0233_recreate_subscriptions_in_snuba...Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/sentry/migrations/0233_recreate_subscriptions_in_snuba.py", line 35, in migrate_subscriptions
>     _delete_from_snuba(
> TypeError: _delete_from_snuba() missing 1 required positional argument: 'entity_key'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/sentry/migrations/0233_recreate_subscriptions_in_snuba.py", line 42, in migrate_subscriptions
>     _delete_from_snuba(
> TypeError: _delete_from_snuba() missing 1 required positional argument: 'entity_key'
> 19:45:53 [ERROR] root: failed to delete orphan 0/cc0a79dcd55011eca7a80242ac12000c: _delete_from_snuba() missing 1 required positional argument: 'entity_key'
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/sentry/migrations/0233_recreate_subscriptions_in_snuba.py", line 35, in migrate_subscriptions
>     _delete_from_snuba(
> TypeError: _delete_from_snuba() missing 1 required positional argument: 'entity_key'
> 19:45:54 [ERROR] root: failed to delete 0/451e6bfc50fb11eba7e00242ac16000b: _delete_from_snuba() missing 1 required positional argument: 'entity_key'

### Expected Result

No error

### Actual Result

Parsing command line ...

▶ Initializing Docker Compose ...

▶ Setting up error handling ...

▶ Checking for latest commit ... 

▶ Checking minimum requirements ...
Found Docker version 19.03.7
Found Docker Compose version 1.29.2

▶ Turning things off ...
Removing orphan container "sentry-self-hosted_nginx_web_proxy_1"
Removing sentry-self-hosted_relay_1                                    ... 
Removing sentry-self-hosted_sentry-cleanup_1                           ... 
Removing sentry-self-hosted_post-process-forwarder_1                   ... 
Removing sentry-self-hosted_worker_1                                   ... 
Removing sentry-self-hosted_subscription-consumer-transactions_1       ... 
Removing sentry-self-hosted_subscription-consumer-events_1             ... 
Removing sentry-self-hosted_ingest-consumer_1                          ... 
Removing sentry-self-hosted_cron_1                                     ... 
Removing sentry-self-hosted_web_1                                      ... 
Removing sentry-self-hosted_snuba-outcomes-consumer_1                  ... 
Removing sentry-self-hosted_snuba-replacer_1                           ... 
Removing sentry-self-hosted_snuba-sessions-consumer_1                  ... 
Removing sentry-self-hosted_snuba-transactions-cleanup_1               ... 
Removing sentry-self-hosted_snuba-api_1                                ... 
Removing sentry-self-hosted_snuba-consumer_1                           ... 
Removing sentry-self-hosted_snuba-cleanup_1                            ... 
Removing sentry-self-hosted_snuba-subscription-consumer-transactions_1 ... 
Removing sentry-self-hosted_snuba-subscription-consumer-events_1       ... 
Removing sentry-self-hosted_snuba-transactions-consumer_1              ... 
Removing sentry-self-hosted_kafka_1                                    ... 
Removing sentry-self-hosted_symbolicator-cleanup_1                     ... 
Removing sentry-self-hosted_smtp_1                                     ... 
Removing sentry-self-hosted_clickhouse_1                               ... 
Removing sentry-self-hosted_geoipupdate_1                              ... 
Removing sentry-self-hosted_postgres_1                                 ... 
Removing sentry-self-hosted_symbolicator_1                             ... 
Removing sentry-self-hosted_redis_1                                    ... 
Removing sentry-self-hosted_memcached_1                                ... 
Removing sentry-self-hosted_zookeeper_1                                ... 
Removing sentry-self-hosted_snuba-api_1                                ... done
Removing sentry-self-hosted_snuba-subscription-consumer-events_1       ... done
Removing sentry-self-hosted_snuba-subscription-consumer-transactions_1 ... done
Removing sentry-self-hosted_zookeeper_1                                ... done
Removing sentry-self-hosted_postgres_1                                 ... done
Removing sentry-self-hosted_clickhouse_1                               ... done
Removing sentry-self-hosted_snuba-transactions-cleanup_1               ... done
Removing sentry-self-hosted_kafka_1                                    ... done
Removing sentry-self-hosted_subscription-consumer-events_1             ... done
Removing sentry-self-hosted_symbolicator_1                             ... done
Removing sentry-self-hosted_sentry-cleanup_1                           ... done
Removing sentry-self-hosted_smtp_1                                     ... done
Removing sentry-self-hosted_relay_1                                    ... done
Removing sentry-self-hosted_ingest-consumer_1                          ... done
Removing sentry-self-hosted_post-process-forwarder_1                   ... done
Removing sentry-self-hosted_snuba-transactions-consumer_1              ... done
Removing sentry-self-hosted_worker_1                                   ... done
Removing sentry-self-hosted_snuba-outcomes-consumer_1                  ... done
Removing sentry-self-hosted_snuba-cleanup_1                            ... done
Removing sentry-self-hosted_redis_1                                    ... done
Removing sentry-self-hosted_snuba-replacer_1                           ... done
Removing sentry-self-hosted_snuba-consumer_1                           ... done
Removing sentry-self-hosted_cron_1                                     ... done
Removing sentry-self-hosted_symbolicator-cleanup_1                     ... done
Removing sentry-self-hosted_snuba-sessions-consumer_1                  ... done
Removing sentry-self-hosted_subscription-consumer-transactions_1       ... done
Removing sentry-self-hosted_memcached_1                                ... done
Removing sentry-self-hosted_geoipupdate_1                              ... done
Removing sentry-self-hosted_web_1                                      ... done
Removing network sentry-self-hosted_default
Removing network sentry_onpremise_default
Network sentry_onpremise_default not found.

▶ Creating volumes for persistent storage ...
Created sentry-clickhouse.
Created sentry-data.
Created sentry-kafka.
Created sentry-postgres.
Created sentry-redis.
Created sentry-symbolicator.
Created sentry-zookeeper.

▶ Ensuring files from examples ...
../sentry/sentry.conf.py already exists, skipped creation.
../sentry/config.yml already exists, skipped creation.
../symbolicator/config.yml already exists, skipped creation.
../sentry/requirements.txt already exists, skipped creation.

▶ Ensuring Relay credentials ...
../relay/config.yml already exists, skipped creation.
Pulling relay ... 
Pulling relay ... pulling from getsentry/relay
Pulling relay ... digest: sha256:216fcc731cf8451ec9...
Pulling relay ... status: image is up to date for g...
Pulling relay ... done
Creating network "sentry-self-hosted_default" with the default driver
Creating sentry-self-hosted_relay_run ... 
Creating sentry-self-hosted_relay_run ... done
2022-05-16T20:07:20Z [relay_config::config] INFO: generating new relay credentials
Creating sentry-self-hosted_relay_run ... 
Creating sentry-self-hosted_relay_run ... done
Relay credentials written to ../relay/credentials.json.

▶ Generating secret key ...

▶ Replacing TSDB ...

▶ Fetching and updating Docker images ...
Some service image(s) must be built from source by running:
    docker-compose build snuba-transactions-cleanup snuba-cleanup sentry-cleanup symbolicator-cleanup
22.4.0: Pulling from getsentry/sentry
Digest: sha256:1815a9eafde66a89c967f896f2c18c33a1fc7718c33c35c187203237007155e3
Status: Image is up to date for getsentry/sentry:22.4.0
docker.io/getsentry/sentry:22.4.0

▶ Building and tagging Docker images ...

smtp uses an image, skipping
memcached uses an image, skipping
redis uses an image, skipping
postgres uses an image, skipping
zookeeper uses an image, skipping
kafka uses an image, skipping
clickhouse uses an image, skipping
geoipupdate uses an image, skipping
snuba-api uses an image, skipping
snuba-consumer uses an image, skipping
snuba-outcomes-consumer uses an image, skipping
snuba-sessions-consumer uses an image, skipping
snuba-transactions-consumer uses an image, skipping
snuba-replacer uses an image, skipping
snuba-subscription-consumer-events uses an image, skipping
snuba-subscription-consumer-transactions uses an image, skipping
symbolicator uses an image, skipping
web uses an image, skipping
cron uses an image, skipping
worker uses an image, skipping
ingest-consumer uses an image, skipping
post-process-forwarder uses an image, skipping
subscription-consumer-events uses an image, skipping
subscription-consumer-transactions uses an image, skipping
relay uses an image, skipping
nginx uses an image, skipping
Building snuba-cleanup
Sending build context to Docker daemon  3.584kB
Step 1/5 : ARG BASE_IMAGE
Step 2/5 : FROM ${BASE_IMAGE}
 ---> 33bb88dc4157
Step 3/5 : RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
 ---> Using cache
 ---> b2cca3c85c7f
Step 4/5 : COPY entrypoint.sh /entrypoint.sh
 ---> Using cache
 ---> d74a2cfadc10
Step 5/5 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> 5ed1acb41a6a
Successfully built 5ed1acb41a6a
Successfully tagged snuba-cleanup-self-hosted-local:latest
Building snuba-transactions-cleanup
Sending build context to Docker daemon  3.584kB
Step 1/5 : ARG BASE_IMAGE
Step 2/5 : FROM ${BASE_IMAGE}
 ---> 33bb88dc4157
Step 3/5 : RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
 ---> Using cache
 ---> b2cca3c85c7f
Step 4/5 : COPY entrypoint.sh /entrypoint.sh
 ---> Using cache
 ---> d74a2cfadc10
Step 5/5 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> 5ed1acb41a6a
Successfully built 5ed1acb41a6a
Successfully tagged snuba-cleanup-self-hosted-local:latest
Building symbolicator-cleanup
Sending build context to Docker daemon  3.584kB
Step 1/5 : ARG BASE_IMAGE
Step 2/5 : FROM ${BASE_IMAGE}
 ---> 6c4923ab81d2
Step 3/5 : RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
 ---> Using cache
 ---> e74d99f66d2a
Step 4/5 : COPY entrypoint.sh /entrypoint.sh
 ---> Using cache
 ---> f9fdf3239063
Step 5/5 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> d60ac5e5dcfe
Successfully built d60ac5e5dcfe
Successfully tagged symbolicator-cleanup-self-hosted-local:latest
Building sentry-cleanup
Sending build context to Docker daemon  3.584kB
Step 1/5 : ARG BASE_IMAGE
Step 2/5 : FROM ${BASE_IMAGE}
 ---> aa66ab141473
Step 3/5 : RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
 ---> Using cache
 ---> b0c24a625233
Step 4/5 : COPY entrypoint.sh /entrypoint.sh
 ---> Using cache
 ---> fe3cbc17830c
Step 5/5 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> 41d2e6108935
Successfully built 41d2e6108935
Successfully tagged sentry-cleanup-self-hosted-local:latest

Docker images built.

▶ Setting up Zookeeper ...
Creating sentry-self-hosted_zookeeper_run ... 
Creating sentry-self-hosted_zookeeper_run ... done
Creating sentry-self-hosted_zookeeper_run ... 
Creating sentry-self-hosted_zookeeper_run ... done
Creating sentry-self-hosted_zookeeper_run ... 
Creating sentry-self-hosted_zookeeper_run ... done

▶ Downloading and installing wal2json ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5417  100  5417    0     0  24862      0 --:--:-- --:--:-- --:--:-- 24963

▶ Bootstrapping and migrating Snuba ...
Creating sentry-self-hosted_redis_1 ... 
Creating sentry-self-hosted_clickhouse_1 ... 
Creating sentry-self-hosted_zookeeper_1  ... 
Creating sentry-self-hosted_redis_1      ... done
Creating sentry-self-hosted_clickhouse_1 ... done
Creating sentry-self-hosted_zookeeper_1  ... done
Creating sentry-self-hosted_kafka_1      ... 
Creating sentry-self-hosted_kafka_1      ... done
Creating sentry-self-hosted_snuba-api_run ... 
Creating sentry-self-hosted_snuba-api_run ... done
2022-05-16 20:08:43,552 Attempting to connect to Kafka (attempt 0)...
2022-05-16 20:08:43,575 Connected to Kafka on attempt 0
2022-05-16 20:08:43,575 Creating Kafka topics...
Creating sentry-self-hosted_snuba-api_run ... 
Creating sentry-self-hosted_snuba-api_run ... done
Finished running migrations

▶ Creating additional Kafka topics ...

▶ Ensuring proper PostgreSQL version ...

▶ Setting up / migrating database ...
Creating sentry-self-hosted_postgres_1 ... 
Creating sentry-self-hosted_symbolicator_1 ... 
Creating sentry-self-hosted_smtp_1         ... 
Creating sentry-self-hosted_memcached_1    ... 
Creating sentry-self-hosted_snuba-replacer_1 ... 
Creating sentry-self-hosted_snuba-api_1      ... 
Creating sentry-self-hosted_snuba-sessions-consumer_1 ... 
Creating sentry-self-hosted_snuba-outcomes-consumer_1 ... 
Creating sentry-self-hosted_snuba-subscription-consumer-transactions_1 ... 
Creating sentry-self-hosted_snuba-consumer_1                           ... 
Creating sentry-self-hosted_snuba-subscription-consumer-events_1       ... 
Creating sentry-self-hosted_snuba-transactions-consumer_1              ... 
Creating sentry-self-hosted_postgres_1                                 ... done
Creating sentry-self-hosted_symbolicator_1                             ... done
Creating sentry-self-hosted_smtp_1                                     ... done
Creating sentry-self-hosted_memcached_1                                ... done
Creating sentry-self-hosted_snuba-replacer_1                           ... done
Creating sentry-self-hosted_snuba-subscription-consumer-transactions_1 ... done
Creating sentry-self-hosted_snuba-api_1                                ... done
Creating sentry-self-hosted_snuba-consumer_1                           ... done
Creating sentry-self-hosted_snuba-sessions-consumer_1                  ... done
Creating sentry-self-hosted_snuba-subscription-consumer-events_1       ... done
Creating sentry-self-hosted_snuba-transactions-consumer_1              ... done
Creating sentry-self-hosted_snuba-outcomes-consumer_1                  ... done
Creating sentry-self-hosted_web_run                                    ... 
Creating sentry-self-hosted_web_run                                    ... done
ls: cannot access '/usr/local/share/ca-certificates/': Operation not permitted
stat: cannot statx '/data': Operation not permitted
20:09:26 [INFO] sentry.plugins.github: apps-not-configured
Running migrations for default
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, nodestore, sentry, sessions, sites, social_auth
Running migrations:
  No migrations to apply.
Creating missing DSNs
Correcting Group.num_comments counter

▶ Migrating file storage ...

▶ Setting up GeoIP integration ...
Setting up IP address geolocation ...
IP address geolocation database already exists.
IP address geolocation is not configured for updates.
See https://develop.sentry.dev/self-hosted/geolocation/ for instructions.
Error setting up IP address geolocation.

-----------------------------------------------------------------

You're all done! Run the following command to get Sentry running:

  docker-compose up -d

-----------------------------------------------------------------

**Comment by aminvakil** [comment]
It looks like migration has not been done correctly, I'd suggest running `./install.sh` again.

**Comment by aminvakil** [comment]
I saw 
```
ls: cannot access '/usr/local/share/ca-certificates/': Operation not permitted
stat: cannot statx '/data': Operation not permitted
```
in `Setting up / migrating database ...` section, you may want to get to the root of this.

**Comment by chadwhitacre** [comment]
From the Discussions version of this thread:

@aminvakil:

> Searching the error: `invoke-rc.d: could not determine current runlevel` brought up some issues and workarounds in WSL, are you running ubuntu on WSL?
>
> What operating system are you using?

@failoman23:

> Thank you for taking your time! I'm running CentOS 7 on a vm with 4 cores and 24GB ram. Cron seems to trigger fine in those two containers reporting errors with invoke-rc.d, both did some work around 2am today.
>
> I had a look at kafka stream (events) and there are entries with 'query' value:
>
>> [
  2,
  "query",
  {
    "group_id": 15199,
    "event_id": "af4835fe86294754b6ac44fd283a3aac",
    "organization_id": 1,
    "project_id": 38,
    ...
]
>
> Was there maybe a braking change in sentry-dotnet-sdk so that the value 'query' is not where it supposed to be now?

**Comment by aminvakil** [comment]
> > Was there maybe a braking change in sentry-dotnet-sdk so that the value 'query' is not where it supposed to be now?

I don't know about `sentry-dotnet-sdk`, but I guess the issue with `cron` not running has been solved, right?

Can we close this then?

**Comment by chadwhitacre** [comment]
Sounds good to me. :)
