### ISSUE TITLE
It may build local cleanup image before the local sentry image is built

### ISSUE THREAD

**Issue by PMExtra** [getsentry/self-hosted#1490]
### Version

nightly (master)

### Steps to Reproduce

Since the local image design is brought back via #1479 , also a problem is back.

The docker compose build order is not always established. It means that it may build the cron image before the `sentry-self-hosted-local` is built. You can refer to https://github.com/docker/compose/issues/5228 and https://github.com/docker/compose/issues/6332 to get details.

### Expected Result

Build cleanup image base on the latest sentry-self-hosted-local.

### Actual Result

When a clean build, it may cause an error about image 'sentry-self-hosted-local' is not found.

When an upgrade build, it may incorrectly use the older `sentry-self-hosted-local` as the base image.

**Comment by aminvakil** [comment]
@PMExtra How did you fix this issue?

**Comment by PMExtra** [comment]
@aminvakil https://github.com/getsentry/self-hosted/pull/1479/files#diff-745af3a66b22b55b6659689cfbb79f835ad5dcbe5d7818744131fff088f2d9ebR4-R6
