### ISSUE TITLE
Turn off Discussions (again)

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/self-hosted#1499]
In https://github.com/getsentry/self-hosted/issues/1151 we deprecated the Discourse forum in favor of GitHub Issues. In https://github.com/getsentry/self-hosted/discussions/1468 we turned on Discussions after all to match what the rest of the org seems to prefer. I now regret that decision, as our support flow is more or less [wrecked](https://github.com/getsentry/self-hosted/discussions/1496) at this point. I want to go back to Issues-only.

**Comment by chadwhitacre** [comment]
Okay how are we going to do this?

**Comment by chadwhitacre** [comment]
It looks like there's no way to unconvert an issue ... i.e., reopen an issue that has been converted to a discussion. I'm not seeing UI on e.g. https://github.com/getsentry/self-hosted/issues/1483. 🤔

**Comment by chadwhitacre** [comment]
Discussions have UI to open a new issue based on the discussion, so I guess that's our option? Reopen issues (they'll be under my name, boo) for all support requests currently in discussions, then delete/turn off the discussions.

**Comment by aminvakil** [comment]
I tried "Create issue from discussion button" in https://github.com/getsentry/self-hosted/issues/1502 and it didn't do anything.

I thought they will do something, but AFAICS it doesn't. (I mean what's the difference between this and opening an issue manually then?)

**Comment by chadwhitacre** [comment]
Really? Could be a permissions issue but if so that seems like a bug (why show you the button if clicking it doesn't do anything?). When I click "Create issue from discussion" on (e.g.) #1483 I get a prepopulated issue form like this:

<img width="1457" alt="Screen Shot 2022-06-03 at 1 19 44 PM" src="https://user-images.githubusercontent.com/134455/171914417-54aee59a-04bc-4179-bb25-f62c69ce1cc8.png">

No comments are brought over, that's probably worth doing manually.

**Comment by chadwhitacre** [comment]
What do you get when you go directly here?

https://github.com/getsentry/self-hosted/issues/new?created_from_discussion_number=1496

**Comment by aminvakil** [comment]
> What do you get when you go directly here?
> 
> https://github.com/getsentry/self-hosted/issues/new?created_from_discussion_number=1496

![image](https://user-images.githubusercontent.com/12948692/172118261-4088f6c7-542a-4f7f-9ba6-cecad317f1ac.png)

**Comment by chadwhitacre** [comment]
Interesting. Yet another reason to not use Discussions, if triage role can't convert discussions to issues. :-/

**Comment by chadwhitacre** [comment]
Aiming to power through this today. My plan is to work through old discussions and hard-delete them all and then turn off Discussions. For each discussion before deleting I'll convert to an issue. For the old support requests that I converted to discussions I'll link to the old support request issue.

**Comment by chadwhitacre** [comment]
Okay! Learning more: the ability to unlock an issue to bring it back is only available if Discussions is disabled for the repo. Makes sense. 👍

**Comment by chadwhitacre** [comment]
Here they are, the issues I've reopened from Discussions:

https://github.com/getsentry/self-hosted/issues/1286
https://github.com/getsentry/self-hosted/issues/1322
https://github.com/getsentry/self-hosted/issues/1326
https://github.com/getsentry/self-hosted/issues/1394
https://github.com/getsentry/self-hosted/issues/1396
https://github.com/getsentry/self-hosted/issues/1401
https://github.com/getsentry/self-hosted/issues/1406
https://github.com/getsentry/self-hosted/issues/1414
https://github.com/getsentry/self-hosted/issues/1419
https://github.com/getsentry/self-hosted/issues/1420
https://github.com/getsentry/self-hosted/issues/1433
https://github.com/getsentry/self-hosted/issues/1434
https://github.com/getsentry/self-hosted/issues/1435
https://github.com/getsentry/self-hosted/issues/1438
https://github.com/getsentry/self-hosted/issues/1440
https://github.com/getsentry/self-hosted/issues/1441
https://github.com/getsentry/self-hosted/issues/1442
https://github.com/getsentry/self-hosted/issues/1445
https://github.com/getsentry/self-hosted/issues/1472
https://github.com/getsentry/self-hosted/issues/1483
https://github.com/getsentry/self-hosted/issues/1491
https://github.com/getsentry/self-hosted/issues/1493

**Comment by chadwhitacre** [comment]
Done! I manually copied over comments from Discussions to the issues (required toggling Discussions on and off as I could only edit one version at a time 🙄) and I created new issues for some new discussions:

- [ ] https://github.com/getsentry/self-hosted/issues/1523
- [ ] https://github.com/getsentry/self-hosted/issues/1525
- [ ] https://github.com/getsentry/self-hosted/issues/1526
- [ ] https://github.com/getsentry/self-hosted/issues/1527

**Comment by chadwhitacre** [comment]
I also took a pass through the issues in https://github.com/getsentry/self-hosted/issues/1499#issuecomment-1159038913 and reopened just the ones that seemed to be still viable. Calling this good there. 👍
