### ISSUE TITLE
Why does sentry keep prompting unknown in native mode

### ISSUE THREAD

**Issue by donallin823** [getsentry/self-hosted#1504]
### Problem Statement

![image](https://user-images.githubusercontent.com/62011907/172291821-be0bf118-3ddf-4bad-8781-f8d4b4ae8052.png)
![image](https://user-images.githubusercontent.com/62011907/172291846-844223ab-e159-4d7d-9f9c-969de4d9494e.png)
![image](https://user-images.githubusercontent.com/62011907/172291881-2f8e9d16-e23a-4665-b478-05f517288b07.png)

**Comment by chadwhitacre** [comment]
We're going to need some better steps to repro the problem here, @donallin823.

**Comment by Swatinem** [comment]
I think its rather about symbolication (fn names) not working.
