### ISSUE TITLE
@sentry/browser POST 400 ping request

### ISSUE THREAD

**Issue by kopax-polyconseil** [getsentry/self-hosted#1508]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Self-hosted/on-premise

### Which package are you using?

@sentry/react

### SDK Version

6.19.7

### Framework Version

6.19.7

### Steps to Reproduce

Note : We are using SDK6 as it is the latest for a crossplatform app. We are not using (yet) SDK7 because we are awaiting for Sentry React Native to upgrade to this SDK, our app is iOS/Android and Web, code is hosted here : https://github.com/pass-culture/pass-culture-app-native, but the bug remain even in latest version, see here : https://github.com/getsentry/sentry-javascript/blob/master/packages/browser/src/transports/utils.ts#L94

https://github.com/getsentry/sentry-javascript/blob/838dcfb8808b9b2a851b08dd4e942e48cbb40e50/packages/browser/src/transports/utils.ts#L94

1. open https://passculture.app
2. open developer tab with <kbd>F12</kbd>
3. go to network tab
4. <kbd>CTRL</kbd> + <kbd>SHIFT</kbd> + <kbd>F5</kbd> to hard reload the page
5. observe the ping `400` send to sentry

### Expected Result

I expect no 400 at all

> I do not know the consequences of this error but it seems without impact for the Sentry error report and our users.

### Actual Result

I get a 400

![image](https://user-images.githubusercontent.com/77674046/172572194-9a0afe83-c142-4a83-bd41-6d87c8ea1444.png)
![image](https://user-images.githubusercontent.com/77674046/172572226-b8c73613-db9c-4812-bc7a-2834b8444333.png)

**Comment by chadwhitacre** [comment]
@kopax-polyconseil Is there anything in your server logs say about the 400?

**Comment by kopax-polyconseil** [comment]
@chadwhitacre on my end, I don't have access to those logs.

I am not promessing but I asked the busy ops to check if they can share some logs.Things is I deployed a fix where we do not use `sendBeacon`, instead we use the `fetch` fallback, and this will be deployed soon to production and we'll have no log for this anymore. Can you tell if it's a good temporary fix ? https://github.com/pass-culture/pass-culture-app-native/pull/3097

**Comment by chadwhitacre** [comment]
I just went down a rabbit hole looking for a `/ping` route somewhere in Sentry ... then I looked more closely at the screenshot and I'm seeing now that "ping" is in the type column on the Chrome network tab. As near as I can tell, that indicates that we're [dealing with a WebSocket frame](https://developer.chrome.com/docs/devtools/network/reference/#frames) here. Sound right?

Without others piling on this ticket my assumption is that this is something weird in your environment, maybe something about your network topology? Something firewall-y interfering with WebSockets here?

**Comment by kopax-polyconseil** [comment]
Could you tell about the consequence of this error?

Also, there is a fetch fallback that I decided to use as a fix, may I have
your opinion on this?

I asked for the server logs but our ops are quite busy and I am not sure we
will have logs on time before our fix with fetch goes to production.

**Comment by lforst** [comment]
Hi, the consequences of this error are negligible.

I'll quickly explain what this ping request is: Essentially, the SDK keeps track of the number of unreported error events. They might not be reported for a number of reasons, for example, because of a network error, because of an event processor, or because a rate limit has been hit.
In the Sentry browser SDK, when the user tabs away from a page, we attempt to send the number of unsent events to Sentry, so we can have statistics of them. We call this statistic "client reports". Client reports are useful for us to determine whether a version of the SDK has a bug, and also users sometimes just want to see how many events they drop.

The ping request you see, is the request we use to send this statistic to sentry. It uses [`Navigator.sendBeacon()`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon) which is why it shows up as `type: ping`. Replacing it with fetch is fine - we use fetch as a fallback in the SDK itself when `sendBeacon` is not available.

One thing to definitely try out is to upgrade the self-hosted version of Sentry to the newest version. The version you have might not be compatible with client reports we're sending in SDK version 6.19.7.

**Comment by chadwhitacre** [comment]
Super-helpful, thanks @lforst. :)

https://develop.sentry.dev/sdk/client-reports/ - the minimum server version to support client reports is 21.9.0 and you say you're on 21.8.0, yes @kopax-polyconseil? Can you upgrade and see if this goes away? :)

**Comment by kopax-polyconseil** [comment]
Hi @chadwhitacre and thanks for the detailled explanation @lforst 

I finally got some time to work on this and got lucky because our Ops meanwhile did a Sentry server upgrade to `22.5.0`. I am still not able to check the server logs despite my requests.

For the records, these are our sentry `dependencies` and `devDependencies` on our clients, I recently upgrade for Sentry SDK7 both native and Web : 

```json
{
  "dependencies": {
    "@sentry/react": "^7.6.0",
    "@sentry/react-native": "^4.1.2",
    "@sentry/tracing": "^7.6.0"
  },
  "devDependencies": {
    "@sentry/types": "^7.6.0",
    "@sentry/webpack-plugin": "^1.18.9"
  }
}
```

I also removed the `fetch` workaround, our self hosted sentry is on version Sentry 22.5.0. I just need my PR to be merged and I will let you know the results :)

**Comment by kopax-polyconseil** [comment]
After publishing the new version in our testing environnment and restoring the workaround to it's original state (which use sendBeacon), we do not see anymore the request (at all) in our developer tab, see by your self [here](https://app.testing.passculture.team), is it normal ?

**Comment by lforst** [comment]
@kopax-polyconseil It's only when switching tabs or leaving the page that the ping request is sent. I just tried it out and it seems to work!

**Comment by chadwhitacre** [comment]
We good to close here, then?

**Comment by kopax-polyconseil** [comment]
I presume. I'll check it later to confirm and reopen if necessary. Thanks a lot to you all :)
