### ISSUE TITLE
whyt nightly build image version display 'Sentry 22.1.0.dev0 69b813d'?

### ISSUE THREAD

**Issue by jinceon** [getsentry/self-hosted#1509]
### Version

nightly

### Steps to Reproduce

1. git clone https://github.com/getsentry/self-hosted.git
2. cd self-hosted
3. ./install.sh
4. docker-compose up -d

### Expected Result

I think the version is at least "Sentry 22.5.0 xxxxxxx", 

### Actual Result

why it display "Sentry 22.1.0.dev0 69b813d"?

**Comment by chadwhitacre** [comment]
You're talking about the string in the footer? I forget where exactly that pulls from. I know I've traced it from the template over in `sentry` before. If others can repro maybe it's systemic. I'm starting with an assumption that it's local to your environment.

**Comment by aminvakil** [comment]
I just tried running latest nightly on a testing virtual machine and result is fine.

![image](https://user-images.githubusercontent.com/12948692/173186948-08909110-be17-4740-93c5-d5d92f559602.png)

@jinceon Please test again.
