### ISSUE TITLE
[sso]google account for sso just last one day, how can I extend the time

### ISSUE THREAD

**Issue by Chris0121** [getsentry/self-hosted#1513]
### Problem Statement

google account for sso just last one day, how can I extend the time.
refer to 
https://develop.sentry.dev/self-hosted/sso/

Actual Reuslt : We need authenticate by google account everyday.
Expected Result : We can stay authentication more than one day.

**Comment by aminvakil** [comment]
What do you mean "last one day"?

Please fill the placeholders for issue, "Actual Result", "Expected Result".

**Comment by Chris0121** [comment]
> 

@aminvakil 
thank you for repsonse.
"last one day" means that we expire organization access after one day. After one day, we need retry to SSO using Google account.
<img width="820" alt="image" src="https://user-images.githubusercontent.com/71202262/173328203-0ed37512-143c-416b-b3dc-abfdd020a4a5.png">
Actual reuslt : We need authenticate by google account everyday.
Expected Result : We can stay authentication more than one day.

**Comment by aminvakil** [comment]
This is the PR which has implemented expiring token after 20 hours: https://github.com/getsentry/sentry/pull/29422

**Comment by Chris0121** [comment]
> This is the PR which has implemented expiring token after 20 hours: [getsentry/sentry#29422](https://github.com/getsentry/sentry/pull/29422)

Thank you for quickly response.
So if I need set expiring time more than 20 hours. How can I do it?
Thank you.

**Comment by chadwhitacre** [comment]
We good to close here?

**Comment by Chris0121** [comment]
@chadwhitacre 
I test several days. It work now. Please close the task.
Thank you.
And thanks to @aminvakil
