### ISSUE TITLE
symbolicator get "unknown_image"

### ISSUE THREAD

**Issue by ljwlaji** [getsentry/self-hosted#1518]
### Version

21.10.0

### Steps to Reproduce

I have create a signal receiver function before sentry init, some code like :
![image](https://user-images.githubusercontent.com/16899528/173743418-a2a7c59a-b2b8-4831-aa6c-835dae2f1f99.png)
![image](https://user-images.githubusercontent.com/16899528/173742651-b0152ad9-0757-49ba-8cf2-9dc7048a062e.png)
...
![image](https://user-images.githubusercontent.com/16899528/173742923-f48701c2-e087-4b83-b0d8-f0b12af20f64.png)
This issue was happened on android device, but step of application starts up was same
crash report randomly receive "unknown image" exception (about 80% of crash event)
![image](https://user-images.githubusercontent.com/16899528/173741932-36155678-fea8-4397-b19c-882f72603281.png)
but it can still recive normal report(within stack trace info) about 20%
![image](https://user-images.githubusercontent.com/16899528/173744130-79094311-8556-4b1d-b314-6a343acbe17f.png)
this project has no debug file uploaded,

i'm not sure is the custom signal receiver cause this issue.
in an another project, i use abort() instead of exit(0) to terminal application, and it work fine. but it will get stuck when crash happens sometime;
i'm a green hand to deal with signals, is there some solution can dissolve both these issue?
1. need to call to a custom signal reciver function before sentry recives signal
2. exit the application smoothly, no stucking

### Expected Result

crash report get stack trace info

### Actual Result

no stack info

**Comment by ljwlaji** [comment]
here is the link of one of the issue http://vv2.azerothcn.com:19000/share/issue/41510426e4af47a5b1ddc9eb379900fa/

**Comment by chadwhitacre** [comment]
This seems like a general symbolication configuration question and not something specific to self-hosted, correct?

**Comment by ljwlaji** [comment]
gsdg54sdg5s4d5gからドムをプレゼンりやかなベルガモットオジビタからロピカなフ
