### ISSUE TITLE
Upgrade from 9.1.2 to latest failed

### ISSUE THREAD

**Issue by royzhao7** [getsentry/self-hosted#1519]
### Version

9.1.2

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/35291563/174000878-6f67ed39-4c29-45b3-a643-e825827838c6.png)

### Expected Result

Is this my network problem?

### Actual Result

  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Reading package lists...
E: The repository 'http://deb.debian.org/debian bullseye InRelease' is not signed.
E: Failed to fetch http://deb.debian.org/debian/dists/bullseye/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: Failed to fetch http://deb.debian.org/debian/dists/bullseye-updates/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'http://deb.debian.org/debian bullseye-updates InRelease' is not signed.
E: Failed to fetch http://security.debian.org/debian-security/dists/bullseye-security/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'http://security.debian.org/debian-security bullseye-security InRelease' is not signed.

**Comment by chadwhitacre** [comment]
@royzhao7 Yes, this seems like a network problem on your end. If you determine otherwise, let us know. Good luck!

**Comment by royzhao7** [comment]
> 

![image](https://user-images.githubusercontent.com/35291563/174620980-0fb8a861-985d-4a2b-bf5d-2f159d011de9.png)
can you give me some advise

**Comment by royzhao7** [comment]
> @royzhao7 Yes, this seems like a network problem on your end. If you determine otherwise, let us know. Good luck!

hi can you give  me some advise for add repo bulleye

**Comment by aminvakil** [comment]
You definitely don't want to add Debian bullseye repo on your ubuntu machine.

The docker image which is getting built is from a debian bullseye image and it couldn't reach debian bullseye sources and what @chadwhitacre meant by network issue, was building of this docker image.

Self-hosted do not mess with repositories and sources on your host.
