### ISSUE TITLE
can’t search jira user 

### ISSUE THREAD

**Issue by Easy-Ez** [getsentry/self-hosted#1522]
### Version

Sentry 21.1.0 486d790

### Steps to Reproduce

1.  integration with jira server
2. click "Link Jira Server Issue" at the issue page
3. search jira user "Assignee" and "Reporter" filed
4. then reponse  {"detail":"Unable to fetch users from Jira"}

request url: `Request URL: https://sentry.automizely.org/extensions/jira-server/search/sentry/3/?field=assignee&issuetype=10002&project=10800&query=yao`

<img width="1657" alt="image" src="https://user-images.githubusercontent.com/7855225/174242568-02f9811f-bbb1-410c-ada1-3d1eb85ce2c9.png"> 

### Expected Result

can search jira user list 

### Actual Result

response code ： 400
response body： {"detail":"Unable to fetch users from Jira"}

**Comment by chadwhitacre** [comment]
@Easy-Ez Likely a network topology issue between your Sentry and Jira instances. Have you investigated along these lines?

**Comment by Easy-Ez** [comment]
SRE checked and no progress 🤦🏻‍♀️。
but we can search   ”Jira Project" and "Components“

**Comment by chadwhitacre** [comment]
Maybe a permissions issue on the Jira side if you can search some things (project, component) but not others (users)?

**Comment by Easy-Ez** [comment]
finally found out。
due to [Atlassian's GDPR Commitment](https://www.atlassian.com/trust/privacy/country/europe-and-gdpr) ,
when searching the user list, we maybe should use  `https://xxxx.atlassian.net/rest/api/3/user/search?project=ADMP&query=ben`  replace
`xxxx.atlassian.net/rest/api/2/user/assignable/search?project=ADMP&username=ben`

**Comment by Easy-Ez** [comment]
Thanks for your reply
