### ISSUE TITLE
error for getsentry/snuba:nightly and maxmindinc/geoipupdate:v4.7.1 image

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/self-hosted#1523]
_Reposting from @autumnyyds520 in Discussions (see #1499)._

-----------

> docker-compose --version is 1.29.2
> dokcer version is：20.10.17
> 
> docker logs -f sentry-self-hosted_snuba-subscription-consumer-events_1
> docker logs -f sentry-self-hosted_snuba-subscription-consumer-transactions_1
> the error is ./docker_entrypoint.sh: line 15: exec: subscriptions-scheduler-executor: not found
> ./docker_entrypoint.sh: line 15: exec: subscriptions-scheduler-executor: not found
> ./docker_entrypoint.sh: line 15: exec: subscriptions-scheduler-executor: not found
> ./docker_entrypoint.sh: line 15: exec: subscriptions-scheduler-executor: not found
> 
> what‘s that?
> i can't find some doc about subscriptions-scheduler-executor

**Comment by chadwhitacre** [comment]
This is related to #1507.

@autumnyyss520 Can you describe steps to repro? Did you follow the normal upgrade procedure? What version were you coming from?

**Comment by lynnagara** [comment]
The command was added in https://github.com/getsentry/snuba/commit/534bf3e6829ed315ab15436c05925ffc96464a2f and is included in the 22.6 self hosted release. What version of Sentry are you currently running?

**Comment by autumnyyds520** [comment]
> 这与#1507有关。抄送：@lynnagara
> 
> @autumnyyds520你能描述一下repro的步骤吗？您是否遵循正常的升级程序？你是从哪个版本来的？


The version I use is 22.5.0，I followed the upgrade process, and then still generated this error message for me. These two containers could not be started normally，I added a geo.IP configuration file does not report an error, it still cannot use the location container normally. Should I ignore the role of these two containers?

**Comment by chadwhitacre** [comment]
@autumnyyds520 Okay you've got something weird going on. If `subscription-consumer-events` came in with 22.6.0 then why are you seeing it at all in 22.5.0? If you can't figure it out we can reopen here, let us know.
