### ISSUE TITLE
admin form login with SSO enabled

### ISSUE THREAD

**Issue by christopher-wong** [getsentry/self-hosted#1528]
### Version

22.5.0

### Steps to Reproduce

I have a installation of Sentry with SSO (G-Suite) enabled. Unfortunately, SSO users have the "owner" role, so I can't edit many settings or escalate the roles of other users. My admin account would let me change these settings, however with SSO enabled, the form login option is gone and there is only a "login with Google" option.

Is there a way to enable form-login or temporarily disable SSO so that I can elevate one of my users to SSO using my admin credentials?

### Expected Result

I should be able to login with my admin user even with SSO enabled

### Actual Result

<img width="806" alt="Screen Shot 2022-06-18 at 1 55 13 AM" src="https://user-images.githubusercontent.com/10580086/174424997-24b44907-a21d-431c-9994-a7c56339b133.png">

**Comment by chadwhitacre** [comment]
This is reminiscent of recent changes we made ... https://github.com/getsentry/self-hosted/pull/1397 is one of the threads to pull on. It'll take me a minute to get back into this context and I'm churning through an inbox backlog right now, will get back to this when I can ...

**Comment by chadwhitacre** [comment]
Reopening, I feel like we didn't give this its due.
