### ISSUE TITLE
List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)

### ISSUE THREAD

**Issue by duyuyouci** [getsentry/self-hosted#1531]
### Version

21.9.0

### Steps to Reproduce

./install.sh

### Expected Result

E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)

### Actual Result

subscription-consumer-transactions uses an image, skipping
relay uses an image, skipping
nginx uses an image, skipping
Building snuba-cleanup
Sending build context to Docker daemon  3.584kB
Step 1/5 : ARG BASE_IMAGE
Step 2/5 : FROM ${BASE_IMAGE}
 ---> a77f8946858f
Step 3/5 : RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
 ---> Running in c0c31cde30a4
Reading package lists...
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)
Removing intermediate container c0c31cde30a4
The command '/bin/sh -c apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*' returned a non-zero code: 100
Service 'snuba-cleanup' failed to build : Build failed
An error occurred, caught SIGERR on line 4
Cleaning up...

**Comment by aminvakil** [comment]
Is this is a clean install or are you upgrading from an older version to 21.9.0? or from 21.9.0 to a newer version?

Can you check free disk space on your system?

**Comment by duyuyouci** [comment]
> 

from 21.9.0 to a newer version
<img width="674" alt="image" src="https://user-images.githubusercontent.com/39803418/174543894-2072d471-f78f-4488-875c-65b8bcfca5f7.png">

**Comment by aminvakil** [comment]
Judging from snap stuff, this is an Ubuntu, right? Do you have apparmor enabled or some other MAC? Can you temporary disable it to make sure if it's not preventing from write?

This may seems odd, but can you check output of `df -i` for free inodes? :)

**Comment by aminvakil** [comment]
You can also try building the image manually, it may help debugging to be faster and easier, it's in `cron` folder.

Or try this simpler Dockerfile here.
To be sure change 22.6.0 to whatever version you are upgrading to:
```
FROM getsentry/snuba:22.6.0
USER 0
RUN apt-get update && apt-get install -y --no-install-recommends cron && \
    rm -r /var/lib/apt/lists/*
CMD ["test 0"]
```
Just paste this into a file named `Dockerfile` in a clean folder and execute this command:
`docker build -t snubatest:1 .`

**Comment by duyuyouci** [comment]
> You can also try building the image manually, it may help debugging to be faster and easier, it's in `cron` folder.
> 
> Or try this simpler Dockerfile here. To be sure change 22.6.0 to whatever version you are upgrading to:
> 
> ```
> FROM getsentry/snuba:22.6.0
> USER 0
> RUN apt-get update && apt-get install -y --no-install-recommends cron && \
>     rm -r /var/lib/apt/lists/*
> CMD ["test 0"]
> ```
> 
> Just paste this into a file named `Dockerfile` in a clean folder and execute this command: `docker build -t snubatest:1 .`

This method works，thanks。

**Comment by aminvakil** [comment]
> > You can also try building the image manually, it may help debugging to be faster and easier, it's in `cron` folder.
> > Or try this simpler Dockerfile here. To be sure change 22.6.0 to whatever version you are upgrading to:
> > ```
> > FROM getsentry/snuba:22.6.0
> > USER 0
> > RUN apt-get update && apt-get install -y --no-install-recommends cron && \
> >     rm -r /var/lib/apt/lists/*
> > CMD ["test 0"]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Just paste this into a file named `Dockerfile` in a clean folder and execute this command: `docker build -t snubatest:1 .`
> 
> This method works，thanks。

So the issue only happens when you try with `./install.sh`?

**Comment by duyuyouci** [comment]
> > > You can also try building the image manually, it may help debugging to be faster and easier, it's in `cron` folder.
> > > Or try this simpler Dockerfile here. To be sure change 22.6.0 to whatever version you are upgrading to:
> > > ```
> > > FROM getsentry/snuba:22.6.0
> > > USER 0
> > > RUN apt-get update && apt-get install -y --no-install-recommends cron && \
> > >     rm -r /var/lib/apt/lists/*
> > > CMD ["test 0"]
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Just paste this into a file named `Dockerfile` in a clean folder and execute this command: `docker build -t snubatest:1 .`
> > 
> > 
> > This method works，thanks。
> 
> So the issue only happens when you try with `./install.sh`?

yes

**Comment by aminvakil** [comment]
This is odd, please execute it with debug mode like this and paste it in a [gist](https://gist.github.com/).

`DEBUG=1 ./install.sh`

**Comment by joaodlf** [comment]
I also got this when upgrading from 22.1.0 to 22.7.0.

Gist:
https://gist.github.com/joaodlf/ed9c3eb911cc08c8b44599c124e441ca

**Comment by joaodlf** [comment]
> You can also try building the image manually, it may help debugging to be faster and easier, it's in `cron` folder.
> 
> Or try this simpler Dockerfile here. To be sure change 22.6.0 to whatever version you are upgrading to:
> 
> ```
> FROM getsentry/snuba:22.6.0
> USER 0
> RUN apt-get update && apt-get install -y --no-install-recommends cron && \
>     rm -r /var/lib/apt/lists/*
> CMD ["test 0"]
> ```
> 
> Just paste this into a file named `Dockerfile` in a clean folder and execute this command: `docker build -t snubatest:1 .`

Can also confirm this has worked. But now I'm getting the following when starting the containers via `docker-compose up -d`:

> Starting sentry_onpremise_sentry-cleanup_1 ... error
ERROR: for sentry_onpremise_sentry-cleanup_1  Cannot start service sentry-cleanup: OCI runtime create failed: > container_linux.go:380: starting container process caused: exec: "/entrypoint.sh": stat /entrypoint.sh: no such file or directory: unknown

I can see an "entrypoint.sh" file at `sentry/entrypoint.sh`, but not at root.

**Comment by chadwhitacre** [comment]
You still stuck on this @joaodlf?

**Comment by SyCode7** [comment]
I still had the issue, I manually commented out the line in the Dockerfile before it worked. Will there be any implications @chadwhitacre  @aminvakil ?

**Comment by aminvakil** [comment]
@joaodlf that's different from cron entrypoint.sh, it should be present and executable in `cron` directory.

Will you please check that?

@SyCode7 What line?

**Comment by SyCode7** [comment]
> @joaodlf that's different from cron entrypoint.sh, it should be present and executable in `cron` directory.
> 
> Will you please check that?
> 
> @SyCode7 What line?

@aminvakil  - I believe lines 3 & 4. These are the commands on the lines
```
RUN apt-get update && apt-get install -y --no-install-recommends cron && \
    rm -r /var/lib/apt/lists/*
```

**Comment by aminvakil** [comment]
Ah, you're effectively removing the `cron` installation, rest of the container does nothing.

@duyuyouci @joaodlf @SyCode7 I'm not sure if should affect anything or not, just a wild guess, do you have a custom umask? Something different from 0022?

It can be retrieved using `umask` command.

**Comment by SyCode7** [comment]
> 

@aminvakil , I just checked, `umask ` is default - `022`

**Comment by joaodlf** [comment]
> @joaodlf that's different from cron entrypoint.sh, it should be present and executable in `cron` directory.
> 
> Will you please check that?
> 
> @SyCode7 What line?

I've got an entrypoint.sh file within my cron dir:
```
#!/usr/bin/env bash

if [ "$(ls -A /usr/local/share/ca-certificates/)" ]; then
  update-ca-certificates
fi

# Prior art:
# - https://git.io/fjNOg
# - https://blog.knoldus.com/running-a-cron-job-in-docker-container/

declare -p | grep -Ev 'BASHOPTS|BASH_VERSINFO|EUID|PPID|SHELLOPTS|UID' > /container.env

{ for cron_job in "$@"; do echo -e "SHELL=/bin/bash
BASH_ENV=/container.env
${cron_job} > /proc/1/fd/1 2>/proc/1/fd/2"; done } \
  | sed --regexp-extended 's/\\(.)/\1/g' \
  | crontab -
crontab -l
exec cron -f -l -L 15
```

umask is showing `0022`.

**Comment by Olegt0rr** [comment]
still actual :(
