### ISSUE TITLE
Installation failed: Configuration file does not exist

### ISSUE THREAD

**Issue by gander** [getsentry/self-hosted#1532]
### Version

22.6.0

### Steps to Reproduce

1. Download https://github.com/getsentry/self-hosted/archive/refs/tags/22.6.0.zip
2. Unpack
3. Run `./install.sh`. Error `Failed to create relay credentials in ../relay/credentials.json.` occurs
4. Run `./install.sh` again
5. Processing (fetching images, starting containers)

### Expected Result

To make it work

### Actual Result

```
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
Error: Configuration file does not exist. Use 'sentry init' to initialize the file.
An error occurred, caught SIGERR on line 12
Cleaning up...
```

**Comment by gander** [comment]
It's crashing when running:

```bash
$dcr web upgrade
# docker compose --ansi never --env-file ${PWD}/.env run --rm web upgrade
```

```bash
docker compose --ansi never --env-file ${PWD}/.env run --rm web bash
# and then
sentry upgrade
```
It looks like the process is going on. But only this fragment.

**Comment by gander** [comment]
Some errors:
```
/usr/local/lib/python3.8/site-packages/memcache.py:1303: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key is '':
/usr/local/lib/python3.8/site-packages/memcache.py:1304: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key_extra_len is 0:
```

**Comment by gander** [comment]
I used this workaround:
```bash
$dcr web bash -c 'sentry upgrade --noinput'
```
The process seems to be completed, but the web does not get up:
```
container for service "web" is unhealthy
```

**Comment by gander** [comment]
Infinite restart loop:
```
Error: Configuration file does not exist. Use 'sentry init' to initialize the file.
```

**Comment by aminvakil** [comment]
There is no need to perform any command manually, please remove and clean anything and execute `./install.sh` again, this time with debug mode. Something like this:

```
docker-compose down -v --remove-orphans
git clean -fdx
docker volume prune -a **### This will erase all volumes which no container is using now, notice if you have other volumes on this machine. ###**
```
You can also use this command to make sure you're only removing volumes related to sentry:
```
for volume in $(docker volume list --format '{{ .Name }}' | grep '^sentry-'); do
  docker volume remove $volume > /dev/null \
    && echo "Removed volume: $volume" \
    || echo "Skipped volume: $volume"
done
```
Then run `./install.sh` like this and paste the output in a [gist](https://gist.github.com).
`DEBUG=1 ./install.sh`

**Comment by aminvakil** [comment]
I couldn't reproduce this, can you clean again as https://github.com/getsentry/self-hosted/issues/1532#issuecomment-1161748716 and run these exact commands and paste the output:
```
bash install/create-docker-volumes.sh
cp relay/config.example.yml relay/config.yml
docker compose run --rm --no-deps -T relay credentials generate --stdout > relay/credentials.json.tmp
cat relay/credentials.json.tmp 
mv relay/credentials.json.tmp relay/credentials.json
docker compose run --rm --no-deps -T relay credentials generate --stdout
docker compose run --rm --no-deps -T relay credentials show
```

**Comment by gander** [comment]
https://gist.githubusercontent.com/gander/eed1a4598c20d907688611e55a1aa05b/raw/4d542381da16e8adf62332caa3d258e53c8d5104/custom.txt

**Comment by aminvakil** [comment]
Seems like `mv relay/credentials.json.tmp relay/credentials.json` is not getting executed.

**Comment by gander** [comment]
No, it is here.
`relay/credentials.json`:
https://gist.githubusercontent.com/gander/eed1a4598c20d907688611e55a1aa05b/raw/c0319db201880206a67e6e10ab00f922d8b78185/relay%255Ccredentials.json

**Comment by gander** [comment]
Ah finally:

```bash
docker compose run --rm --no-deps -T relay credentials show
```
Displays:
```
Credentials:
  relay id: 78670c52-e22e-476d-ac8d-68d9d220727e
  public key: ok0fVb4Ak7n6ZkAqkcOz3MDQxnSOo1hB_4DXp-tlZH0
```
How?

Changing ownership all files:
```bash
chown -R relay:relay /work/.relay
```

**Comment by gander** [comment]
```
  File: relay/credentials.json
  Size: 164       	Blocks: 24         IO Block: 4096   regular file
Device: 3ah/58d	Inode: 11674413    Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1000/  gander)   Gid: ( 1000/  gander)
Access: 2022-06-22 00:38:23.523293377 +0200
Modify: 2022-06-22 00:38:22.687299016 +0200
Change: 2022-06-22 00:38:22.891297640 +0200
 Birth: -
```

**Comment by gander** [comment]
So?

**Comment by aminvakil** [comment]
@gander I ran out of ideas and I cannot reproduce, I kept this open to see if anyone else had any ideas.

**Comment by gander** [comment]
Where `sentry` looking for config file?

**Comment by gander** [comment]
bump

**Comment by chadwhitacre** [comment]
Any ideas @ethanhs? 🤔

**Comment by ethanhs** [comment]
The only thing I can think of that could cause this would be some kind of permissions issue on either the self-hosted folder or the parent of that.

Could you tell us more about your docker setup @gander? e.g. what OS you are on, what version docker and compose are, and if you are using docker compose from docker desktop or the binary.

**Comment by gander** [comment]
It happened again. It broke again. I was wondering what did I do wrong? I have some suspicion and am checking it out right now.

**Comment by gander** [comment]
The code downloaded by GIT works. Code from ZIP archive doesn't work. I haven't checked the TAR.GZ archive, so I don't know if there is a problem with this archive as well.

**Comment by ethanhs** [comment]
> Code from ZIP archive doesn't work.

The only thing that would fail from using the zip as far as I know is the check of git versioning. https://github.com/getsentry/self-hosted/blob/master/install/check-latest-commit.sh

Do you run into the issue with the config file from using the zip?

Perhaps we can detect if we aren't in a git checkout and tell people to clone instead.

**Comment by gander** [comment]
Yes, all the time it didn't work, I was using code from a ZIP archive. The code works fine when I run it from the GIT repository.

**Comment by ethanhs** [comment]
Ok, my guess then it is some permissions information kept in git but not the zip? I've opened https://github.com/getsentry/self-hosted/pull/1589 to resolve this.

**Comment by chadwhitacre** [comment]
Has anyone been able to repro @gander's result with the ZIP? Downloading tarballs from GitHub is not not normal, would be a shame to have to avoid that if we don't have to.

**Comment by gander** [comment]
I could try to record it on asciinema.

**Comment by chadwhitacre** [comment]
[Unable to repro](https://github.com/getsentry/self-hosted/pull/1589#issuecomment-1191301711), ftr.

**Comment by gander** [comment]
Linux Mint or some Standard Unix Server with root?

**Comment by chadwhitacre** [comment]
@gander Can you try on a different linux and see if you can repro?

**Comment by gander** [comment]
@chadwhitacre 

You're kidding? I reported a problem and it might be Linux Mint pointing to the Ubuntu family. No, I don't have the conditions to experiment on other systems, I have one computer and I have Linux Mint on it, and I'm not going to change it or risk losing data to see if it works on another system. Not all of your potential users will run it on a clean server machine. The ability to run it on your own PC can also be seen as verifying the software's capabilities before recommending it to your supervisor. 

"Everything works for me and we have nothing to worry about the fact that for one user who uses a popular system, the application does not work."

**Comment by gander** [comment]
I have already found a solution to the problem that works and is sufficient for me. You should be concerned not to have any doubts that the standard solution will work for other users.

**Comment by gander** [comment]
I did everything according to my conscience: Report a problem and share a discovery when it works well.

You want to hide your head in the sand, your will.

**Comment by aminvakil** [comment]
@gander
We're using it on Debian 10 in our corporation, I have tested on Fedora 33, and CI is running on ubuntu 20.04 and I'm trying to add macOS to our CI in https://github.com/getsentry/self-hosted/pull/1587.

Latest `tar.gz` archive from master is also getting tested as you can see here (https://github.com/getsentry/sentry/blob/88892a6c8a29f12f6c678901cca8f8455ca7ef78/docker/cloudbuild.yaml#L44).

We're doing our best to reproduce your problem and could not, what's your suggestion?

**Comment by gander** [comment]
Try on desktop with Linux Mint?

**Comment by chadwhitacre** [comment]
@gander I believe you that it's not working on Linux Mint. We don't have the resources to support every platform and so far you're the only one asking reporting a problem, so we would need yourself or someone else to help us out with a solution unless we get a lot more demand to justify us spending time on it rather than other priorities.

> I have already found a solution to the problem that works and is sufficient for me.

👍
