### ISSUE TITLE
installation failed: Couldn't find env file: /home/self-hosted/.env

### ISSUE THREAD

**Issue by zxf1111** [getsentry/self-hosted#1535]
### Version

22.6.0

### Steps to Reproduce

1. git clone https://github.com/getsentry/self-hosted.git
2. cd self-hosted
3. Run ./install.sh
Error Couldn't find env file: /home/self-hosted/.env
An error occurred, caught SIGERR on line 8

### Expected Result

To make it work

### Actual Result

▶ Parsing command line ...

▶ Initializing Docker Compose ...

▶ Setting up error handling ...

▶ Checking for latest commit ...

▶ Checking minimum requirements ...
Found Docker version 20.10.14
Found Docker Compose version 1.29.2

▶ Turning things off ...
Couldn't find env file: /home/self-hosted/.env
An error occurred, caught SIGERR on line 8
Cleaning up...

logs :
+ source turn-things-off.sh
++ echo '▶ Turning things off ...'
▶ Turning things off ...
++ [[ -n '' ]]
++ docker-compose --ansi never --env-file /home/self-hosted/.env down -t 60 --rmi local --remove-orphans
Couldn't find env file: /home/self-hosted/.env
+++ cleanup ERR 8
+++ [[ 0 -eq 1 ]]
+++ DID_CLEAN_UP=1
+++ [[ ERR != \E\X\I\T ]]
+++ echo 'An error occurred, caught SIGERR on line 8'
An error occurred, caught SIGERR on line 8
+++ [[ -n '' ]]
+++ echo 'Cleaning up...'
Cleaning up...
+++ [[ -z '' ]]
+++ docker-compose --ansi never --env-file /home/self-hosted/.env stop -t 60
+ cleanup EXIT 1
+ [[ 1 -eq 1 ]]
+ return 0

**Comment by aminvakil** [comment]
What's the output of `git status` & `ls -la`?

**Comment by zxf1111** [comment]
> What's the output of `git status` & `ls -la`?

Thx for you replay, that is the result of  "git status" and "ls -la".

```
➜  self-hosted git:(master) git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
➜  self-hosted git:(master) ls -al
total 120
drwxr-xr-x  17 root root  4096 Jun 21 16:08 .
drwxr-xr-x. 15 root root  4096 Jun 21 16:15 ..
drwxr-xr-x   2 root root    24 Jun 21 10:57 certificates
-rw-r--r--   1 root root  7327 Jun 21 10:57 CHANGELOG.md
drwxr-xr-x   2 root root    24 Jun 21 10:57 clickhouse
-rw-r--r--   1 root root  1480 Jun 21 10:57 cloudbuild.yaml
-rw-r--r--   1 root root   111 Jun 21 10:57 CONTRIBUTING.md
-rw-r--r--   1 root root   100 Jun 21 10:57 .craft.yml
drwxr-xr-x   2 root root    45 Jun 21 10:57 cron
-rw-r--r--   1 root root 13128 Jun 21 10:57 docker-compose.yml
-rw-r--r--   1 root root   183 Jun 21 10:57 .editorconfig
-rw-r--r--   1 root root   597 Jun 21 10:57 .env
drwxr-xr-x   2 root root    38 Jun 21 10:57 geoip
drwxr-xr-x   8 root root   163 Jun 22 07:47 .git
-rw-r--r--   1 root root   134 Jun 21 10:57 .gitattributes
drwxr-xr-x   4 root root    77 Jun 21 10:57 .github
-rw-r--r--   1 root root  1407 Jun 21 10:57 .gitignore
drwxr-xr-x   2 root root  4096 Jun 21 13:12 install
-rwxr-xr-x   1 root root   995 Jun 21 10:57 install.sh
drwxr-xr-x   3 root root   124 Jun 21 10:57 _integration-test
-rwxr-xr-x   1 root root   686 Jun 21 10:57 integration-test.sh
-rw-r--r--   1 root root  4733 Jun 21 10:57 LICENSE
drwxr-xr-x   2 root root    24 Jun 21 10:57 nginx
drwxr-xr-x   2 root root    55 Jun 21 10:57 postgres
-rw-r--r--   1 root root  3718 Jun 21 10:57 README.md
drwxr-xr-x   2 root root    32 Jun 21 10:57 relay
-rwxr-xr-x   1 root root  1665 Jun 21 10:57 reset.sh
drwxr-xr-x   2 root root    52 Jun 21 10:57 scripts
drwxr-xr-x   2 root root   165 Jun 21 10:57 sentry
-rw-rw-r--   1 root root   376 Jun 21 10:57 sentry_install_log-2022-06-21_10-57-28.txt
-rw-rw-r--   1 root root  7136 Jun 21 10:58 sentry_install_log-2022-06-21_10-57-57.txt
-rw-rw-r--   1 root root   376 Jun 21 10:59 sentry_install_log-2022-06-21_10-59-32.txt
-rw-rw-r--   1 root root  7159 Jun 21 12:57 sentry_install_log-2022-06-21_12-57-01.txt
-rw-rw-r--   1 root root   376 Jun 21 13:00 sentry_install_log-2022-06-21_13-00-27.txt
drwxr-xr-x   2 root root    32 Jun 21 10:57 symbolicator
-rwxr-xr-x   1 root root   185 Jun 21 10:57 test.sh
drwxr-xr-x   2 root root    24 Jun 21 10:57 zookeeper

```

**Comment by zxf1111** [comment]
Fixed

update docker- to latest version
from 
 Docker version 20.10.14
Docker Compose version 1.29.2
to
Docker version 22.06.0-beta.0
 Docker Compose version 2.6.0
