### ISSUE TITLE
Problems with installing self-hosted sentry over http proxy

### ISSUE THREAD

**Issue by goganchic** [getsentry/self-hosted#1537]
### Version

22.7.0

### Steps to Reproduce

I have a server, which can access the Internet only through http proxy. To make Docker access the Internet I perform 2 steps.

**Step 1**

Create file `/etc/systemd/system/docker.service.d/http-proxy.conf` with such contents:

```
[Service]
Environment="HTTP_PROXY=http://proxy:3128"
Environment="HTTPS_PROXY=http://proxy:3128"
Environment="NO_PROXY=127.0.0.0/8"
```

Where `proxy` is my proxy host. Then I reload systemd with a command `systemctl daemon-reload` and restart docker: `systemctl restart docker.service`.

These actions allow docker to perform `docker pull` command using http proxy.

**Step2**

Create file `~/.docker/config.json` with such contents:

```json
{
 "proxies":
 {
   "default":
   {
     "httpProxy": "http://proxy:3128",
     "httpsProxy": "http://proxy:3128",
     "noProxy": "127.0.0.0/8"
   }
 }
}
```

Where `proxy` is my proxy host. It sets `http_proxy`, `https_proxy` and `no_proxy` env variables in the docker containers, so it makes it possible to execute `curl` and other commands that require Internet access.

After it I try to execute `install.sh`.

### Expected Result

Everything works as described in the README and the documentation.

### Actual Result

Installation fails.

`apt-get` fails for [cron](https://github.com/getsentry/self-hosted/blob/master/cron/Dockerfile) container. It does not use proxy env variables and requires to configure proxies in the `/etc/apt/apt.conf`. So it can be fixed with such apt.conf:

```
Acquire::http::proxy "http://proxy:3128/";
Acquire::https::proxy "http://proxy:3128/";
```

And [cron/Dockerfile](https://github.com/getsentry/self-hosted/blob/master/cron/Dockerfile) should be modified like this:

```
ARG BASE_IMAGE
FROM ${BASE_IMAGE}
USER 0
COPY apt.conf /etc/apt/apt.conf # <-- this line added
RUN apt-get update && apt-get install -y --no-install-recommends cron && \
    rm -r /var/lib/apt/lists/*
COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
```

Even if I fix cron container problem - the installation fails again with such an error:

```
container for service "clickhouse" is unhealthy
An error occurred, caught SIGERR on line 3
```

In the [docker-compose.yml](https://github.com/getsentry/self-hosted/blob/master/docker-compose.yml) there are such lines:

```yaml
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -nv -t1 --spider 'http://localhost:8123/' || exit 1",
        ]
```

`yandex/clickhouse-server:20.3.9.70` container has a `wget` from busybox, which ignores `no_proxy` env variable (take a look at [this ticket](https://github.com/gliderlabs/docker-alpine/issues/259) for more details). So healthcheck command tries to make a request to the localhost though http proxy and fails.

It can be fixed with such command: `HTTP_PROXY='' wget -nv -t1 --spider 'http://localhost:8123/' || exit 1`.

**Comment by goganchic** [comment]
I can make a PR if the solutions from the message about looks OK.

**Comment by aminvakil** [comment]
Can you try the solution which has been provided in https://github.com/getsentry/self-hosted/issues/1404#issuecomment-1087663377 ?

**Comment by goganchic** [comment]
@aminvakil, it's just an alternative to `~/.docker/config.json`. It does not solve all problems that I'd described

**Comment by aminvakil** [comment]
Honestly I don't agree having an `apt.conf` which we should keep an eye on its changes when there is an update to `apt` or distro we're using or ...

Also for the change you have mentioned for `wget`.

But I'm not maintainer of this repository after all :) You can wait and see maintainers' opinion about this if you want to.

**Comment by goganchic** [comment]
@aminvakil it's impossible to use some distro and do not pay attention to its package management system. `apt-get` does not respect `http_proxy` variable and it's required to set proxy with `apt.conf` file. E.g. `apk` from `alpine` uses `http_proxy` env variable and it's possible install packages through proxy.

if you know better solution for this problem, I'll be happy to discuss it.

If I'm not mistaken this repo is mentioned as an official way to setup self-hosted Sentry. I think that my setup is quite common for a lot of enterprises, so the possibility to install sentry without direct connection to the Internet is important, imho.

**Comment by chadwhitacre** [comment]
Just skimming so far ... is it possible that you could achieve what you want using the [new `enhance-image.sh` hook](https://develop.sentry.dev/self-hosted/#configuration)?

**Comment by goganchic** [comment]
@chadwhitacre don't get me wrong, I can implement all required features with `enhance-image.sh` or just modifying the source code. I just want to make this feature work out of the box.  As I can see there are [some sort of proxy support](https://github.com/getsentry/self-hosted/blob/f2fb758c48e969f5ee513889226cd47033caf7de/install/install-wal2json.sh#L10) in the source code, that is why I think that current behavior is a bug.

**Comment by aminvakil** [comment]
> @chadwhitacre don't get me wrong, I can implement all required features with `enhance-image.sh` or just modifying the source code. I just want to make this feature work out of the box. As I can see there are [some sort of proxy support](https://github.com/getsentry/self-hosted/blob/f2fb758c48e969f5ee513889226cd47033caf7de/install/install-wal2json.sh#L10) in the source code, that is why I think that current behavior is a bug.

With your current solution, you should change `apt.conf` too and I disagree with adding an `apt.conf` to repository. But don't get me wrong, I don't disagree with making it easier rather than current solution.

Right now `enhance-image.sh` is what we think is good and easy way to do stuff in many environments, I'll be happy and open to hear if you have better ideas.

**Comment by goganchic** [comment]
I'd created PR https://github.com/getsentry/self-hosted/pull/1543 without `apt.conf` in the repository. Please take a look.

**Comment by chadwhitacre** [comment]
FYI I gave you a shout-out in our newsletter, @goganchic. Thanks again! :)

<img width="683" alt="" src="https://user-images.githubusercontent.com/134455/182199854-287ee321-ff94-4705-a2f5-d9200a08dd39.png">

------------------------------

> Shout-out this month to [goganchic](https://go.sentry.io/Nzc2LU1KTi01MDEAAAGF30H4bVMAh__EBR2CogwP7pywmIStVoISXzSEDbWONEA4d4R6Z_rcmTJlF5bEIeuSmSqvL0k=), a self-hoster who, probably like many of you, is running Sentry behind a firewall. They gave us a great report about the [problems this causes](https://go.sentry.io/Nzc2LU1KTi01MDEAAAGF30H4bChswgTXbWmQF_eepXpcAzk4FBg6wru2TAx9DbdpuwJM-kZ4l4bZk4lkmjjq0rjmnJg=), and after hashing out the details with us, they contributed [a fix](https://go.sentry.io/Nzc2LU1KTi01MDEAAAGF30H4bFRsK7btQZQyPpOJ72taT9-SIvpNh8cHW5MaNuNEGiJOcbi8X-iVh1pDdbjcTC9JAUA=) and a [doc update](https://go.sentry.io/Nzc2LU1KTi01MDEAAAGF30H4bAcAHJpFAzUQJRiBUDn8sJRlGqro8vnmLK0pZXCA637WvLUg0akyVqL485k9VSqMAHE=). Bonus points for [squishing a regression](https://go.sentry.io/Nzc2LU1KTi01MDEAAAGF30H4bUfh2iw7mlA5Npw-NMptGlutr5fRQ9syaeV81FQJpVmyC-EK454M6gJQzziozjqrsQY=) from when we dropped gosu. Thanks for the solid contributions, goganchic.
