### ISSUE TITLE
ERROR: Invalid interpolation format

### ISSUE THREAD

**Issue by KlemenDanfoss** [getsentry/self-hosted#1542]
### Version

22.6.0

### Steps to Reproduce

1. download 22.6.0
2. run ./install.sh
3. docker-compose up -d

### Expected Result

Containers are up.

docker compose version
Docker Compose version v2.6.0

### Actual Result

ERROR: Invalid interpolation format for "smtp" option in service "services": "${SENTRY_MAIL_HOST:-}"
ERROR: Invalid interpolation format for "postgres" option in service "services": "pg_isready -U ${POSTGRES_USER:-postgres}"

sentry@sentry-prod:~/current$ docker-compose up -d
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for x-depends_on-default: 'condition'
Unsupported config option for x-depends_on-healthy: 'condition'
Unsupported config option for x-sentry-defaults: 'depends_on'
Unsupported config option for x-snuba-defaults: 'depends_on'
Unsupported config option for volumes: 'sentry-smtp'
Unsupported config option for x-healthcheck-defaults: 'timeout'
Unsupported config option for services: 'web'
x-sentry-defaults.build contains an invalid type, it should be a string

**Comment by masoudmghd** [comment]
Also I've the same problem restarting all services with docker-compose restart.

**Comment by aminvakil** [comment]
@KlemenDanfoss @masoudmghd Are you using bash? What operating system are you using?

Also please paste output of `DEBUG=1 ./install.sh` in a [gist](https://gist.github.com) and put the link here.

**Comment by KlemenDanfoss** [comment]
@aminvakil , yes, bash and Ubuntu 22.04LTS.

I can't reproduce this with Ubuntu 20.04LTS.

**Comment by KlemenDanfoss** [comment]
I guess this is related with package docker-compose-plugin and/or using package docker-compose

Package docker-compose-plugin : usage 'docker compose'
Package docker-compose : usage 'docker-compose'

And it behaves differently.

Ubuntu 20.04 LTS:

ii  docker-compose                           1.25.0-1                          all          Punctual, lightweight development environments using Docker
ii  docker-compose-plugin                    2.6.0~ubuntu-focal                amd64        Docker Compose (V2) plugin for the Docker CLI.

**Comment by aminvakil** [comment]
I'm sure more stuff will break if you have both versions of `docker-compose` v1 and v2.

Please remove `docker-compose 1.25.0` and try again.

Currently we only support `docker-compose` v1 versions greater than 1.28.0 and all v2 versions. It's suggested to install latest `docker-compose` (currently [2.6.1](https://github.com/docker/compose/releases/tag/v2.6.1)).

**Comment by KlemenDanfoss** [comment]
Yes, removing docker-compose 1.25.0 works.
