### ISSUE TITLE
CI flakes with "The container name [...] is already in use by container"

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/self-hosted#1547]
https://github.com/getsentry/self-hosted/runs/7097939715?check_suite_focus=true#step:4:690

**Comment by ethanhs** [comment]
https://github.com/getsentry/self-hosted/runs/8257636445

**Comment by chadwhitacre** [comment]
https://github.com/getsentry/self-hosted/actions/runs/4421444502/jobs/7752248239#step:4:5629

**Comment by aminvakil** [comment]
https://github.com/getsentry/self-hosted/actions/runs/7506913309/job/20439372082?pr=2681#step:4:7972

**Comment by chadwhitacre** [comment]
still

https://github.com/getsentry/self-hosted/actions/runs/7869631081/job/21469116797?pr=2788#step:4:3686
