### ISSUE TITLE
Configuration error: ConfigurationError('SyntaxError: invalid syntax (<string>, line 41)')

### ISSUE THREAD

**Issue by martinwrightgithub** [getsentry/self-hosted#1549]
### Version

latest

### Steps to Reproduce

clone repository  git clone https://github.com/getsentry/self-hosted.git run ./install.sh

### Expected Result

Install to complete. 

### Actual Result

root@netbox:/opt/sentry# ./install.sh
▶ Parsing command line ...

▶ Initializing Docker Compose ...

▶ Setting up error handling ...

▶ Checking for latest commit ... 

▶ Checking minimum requirements ...
Found Docker version 20.10.17
Found Docker Compose version 2.4.1
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
19d511225f94: Pulling fs layer
19d511225f94: Verifying Checksum
19d511225f94: Download complete
19d511225f94: Pull complete
Digest: sha256:3614ca5eacf0a3a1bcc361c939202a974b4902b9334ff36eb29ffe9011aaad83
Status: Downloaded newer image for busybox:latest
WARN: Recommended minimum CPU cores available to Docker is 4, found 2
WARN: Recommended minimum RAM available to Docker is 7800 MB, found 6784 MB

▶ Turning things off ...
sentry-self-hosted  Warning: No resource found to remove
sentry_onpremise  Warning: No resource found to remove

▶ Creating volumes for persistent storage ...
Created sentry-clickhouse.
Created sentry-data.
Created sentry-kafka.
Created sentry-postgres.
Created sentry-redis.
Created sentry-symbolicator.
Created sentry-zookeeper.

▶ Ensuring files from examples ...
../sentry/sentry.conf.py already exists, skipped creation.
../sentry/config.yml already exists, skipped creation.
../symbolicator/config.yml already exists, skipped creation.

▶ Ensuring Relay credentials ...
../relay/config.yml already exists, skipped creation.
../relay/credentials.json already exists, skipped creation.

▶ Generating secret key ...

▶ Replacing TSDB ...

▶ Fetching and updating Docker images ...
nightly: Pulling from getsentry/sentry
f7a1c6dad281: Pulling fs layer
92c59ec44e08: Pulling fs layer
08935196cb79: Pulling fs layer
7aa958b41dfb: Pulling fs layer
86c7a279e304: Pulling fs layer
7f6dda53dda9: Pulling fs layer
b0ff3e436380: Pulling fs layer
bc522c386863: Pulling fs layer
46f70dfa761a: Pulling fs layer
24820c2cf49c: Pulling fs layer
56b8e0110fdc: Pulling fs layer
0d1de16a82c4: Pulling fs layer
633d455fc55b: Pulling fs layer
f3830833292a: Pulling fs layer
274c8e7f59b0: Pulling fs layer
0d1de16a82c4: Waiting
633d455fc55b: Waiting
f3830833292a: Waiting
274c8e7f59b0: Waiting
7f6dda53dda9: Waiting
b0ff3e436380: Waiting
bc522c386863: Waiting
46f70dfa761a: Waiting
24820c2cf49c: Waiting
56b8e0110fdc: Waiting
7aa958b41dfb: Waiting
86c7a279e304: Waiting
92c59ec44e08: Verifying Checksum
92c59ec44e08: Download complete
7aa958b41dfb: Verifying Checksum
7aa958b41dfb: Download complete
08935196cb79: Verifying Checksum
08935196cb79: Download complete
7f6dda53dda9: Verifying Checksum
7f6dda53dda9: Download complete
86c7a279e304: Download complete
f7a1c6dad281: Verifying Checksum
f7a1c6dad281: Download complete
b0ff3e436380: Verifying Checksum
b0ff3e436380: Download complete
bc522c386863: Verifying Checksum
bc522c386863: Download complete
f7a1c6dad281: Pull complete
92c59ec44e08: Pull complete
08935196cb79: Pull complete
7aa958b41dfb: Pull complete
56b8e0110fdc: Verifying Checksum
56b8e0110fdc: Download complete
86c7a279e304: Pull complete
7f6dda53dda9: Pull complete
b0ff3e436380: Pull complete
0d1de16a82c4: Download complete
bc522c386863: Pull complete
633d455fc55b: Verifying Checksum
633d455fc55b: Download complete
f3830833292a: Verifying Checksum
f3830833292a: Download complete
274c8e7f59b0: Verifying Checksum
274c8e7f59b0: Download complete
24820c2cf49c: Verifying Checksum
24820c2cf49c: Download complete
46f70dfa761a: Verifying Checksum
46f70dfa761a: Download complete
46f70dfa761a: Pull complete
24820c2cf49c: Pull complete
56b8e0110fdc: Pull complete
0d1de16a82c4: Pull complete
633d455fc55b: Pull complete
f3830833292a: Pull complete
274c8e7f59b0: Pull complete
Digest: sha256:02f57fed6187a9234c6e7b84975c13ff5459c090beb535fa2b3aa5873f0d3b2a
Status: Downloaded newer image for getsentry/sentry:nightly
docker.io/getsentry/sentry:nightly

▶ Building and tagging Docker images ...

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 463B done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 transferring context: 2B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/getsentry/sentry:nightly
#3 DONE 0.0s

#4 [internal] load build context
#4 transferring context: 25.09kB done
#4 DONE 0.0s

#5 [1/4] FROM docker.io/getsentry/sentry:nightly
#5 DONE 0.5s

#6 [2/4] COPY . /usr/src/sentry
#6 DONE 0.1s

#7 [3/4] RUN if [ -s /usr/src/sentry/enhance-image.sh ]; then     /usr/src/sentry/enhance-image.sh; fi
#7 DONE 0.3s

#8 [4/4] RUN if [ -s /usr/src/sentry/requirements.txt ]; then     echo "sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image";     pip install -r /usr/src/sentry/requirements.txt; fi
#8 DONE 0.4s

#9 exporting to image
#9 exporting layers 0.1s done
#9 writing image sha256:4aa355474598a8e82249832757386622b2993e1f6fe86a992c6ae71bff37963e
#9 writing image sha256:4aa355474598a8e82249832757386622b2993e1f6fe86a992c6ae71bff37963e done
#9 naming to docker.io/library/sentry-self-hosted-local done
#9 DONE 0.1s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
#1 [snuba-cleanup-self-hosted-local internal] load build definition from Dockerfile
#1 transferring dockerfile: 469B done
#1 DONE 0.0s

#2 [sentry-cleanup-self-hosted-local internal] load build definition from Dockerfile
#2 transferring dockerfile: 469B done
#2 DONE 0.0s

#3 [symbolicator-cleanup-self-hosted-local internal] load build definition from Dockerfile
#3 transferring dockerfile: 469B done
#3 DONE 0.0s

#4 [sentry-self-hosted-local internal] load build definition from Dockerfile
#4 transferring dockerfile: 32B done
#4 DONE 0.0s

#5 [symbolicator-cleanup-self-hosted-local internal] load .dockerignore
#5 transferring context: 2B done
#5 DONE 0.0s

#6 [sentry-cleanup-self-hosted-local internal] load .dockerignore
#6 transferring context: 2B done
#6 DONE 0.0s

#7 [snuba-cleanup-self-hosted-local internal] load .dockerignore
#7 transferring context: 2B done
#7 DONE 0.0s

#8 [sentry-self-hosted-local internal] load .dockerignore
#8 transferring context: 2B done
#8 DONE 0.0s

#9 [sentry-self-hosted-local internal] load metadata for docker.io/getsentry/sentry:nightly
#9 DONE 0.0s

#10 [snuba-cleanup-self-hosted-local internal] load metadata for docker.io/getsentry/snuba:nightly
#10 DONE 0.0s

#11 [sentry-cleanup-self-hosted-local internal] load metadata for docker.io/library/sentry-self-hosted-local:latest
#11 DONE 0.0s

#12 [symbolicator-cleanup-self-hosted-local internal] load metadata for docker.io/getsentry/symbolicator:nightly
#12 DONE 0.0s

#13 [symbolicator-cleanup-self-hosted-local internal] load build context
#13 transferring context: 662B done
#13 DONE 0.0s

#14 [snuba-cleanup-self-hosted-local 1/5] FROM docker.io/getsentry/snuba:nightly
#14 ...

#15 [sentry-self-hosted-local 1/4] FROM docker.io/getsentry/sentry:nightly
#15 DONE 0.0s

#16 [snuba-cleanup-self-hosted-local internal] load build context
#16 transferring context: 662B done
#16 DONE 0.1s

#17 [sentry-cleanup-self-hosted-local internal] load build context
#17 transferring context: 662B done
#17 DONE 0.1s

#18 [symbolicator-cleanup-self-hosted-local 1/5] FROM docker.io/getsentry/symbolicator:nightly
#18 DONE 0.2s

#19 [sentry-self-hosted-local internal] load build context
#19 transferring context: 297B done
#19 DONE 0.1s

#20 [sentry-self-hosted-local 3/4] RUN if [ -s /usr/src/sentry/enhance-image.sh ]; then     /usr/src/sentry/enhance-image.sh; fi
#20 CACHED

#21 [sentry-self-hosted-local 2/4] COPY . /usr/src/sentry
#21 CACHED

#22 [sentry-self-hosted-local 4/4] RUN if [ -s /usr/src/sentry/requirements.txt ]; then     echo "sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image";     pip install -r /usr/src/sentry/requirements.txt; fi
#22 CACHED

#23 [symbolicator-cleanup-self-hosted-local 2/5] RUN if [ -z "${http_proxy}" ]; then echo "Acquire::http::proxy "${http_proxy}";" >> /etc/apt/apt.conf; fi
#23 ...

#14 [snuba-cleanup-self-hosted-local 1/5] FROM docker.io/getsentry/snuba:nightly
#14 DONE 0.4s

#24 [sentry-self-hosted-local] exporting to image
#24 exporting layers done
#24 writing image sha256:4aa355474598a8e82249832757386622b2993e1f6fe86a992c6ae71bff37963e done
#24 naming to docker.io/library/sentry-self-hosted-local done
#24 DONE 0.3s

#25 [snuba-cleanup-self-hosted-local 2/5] RUN if [ -z "${http_proxy}" ]; then echo "Acquire::http::proxy "${http_proxy}";" >> /etc/apt/apt.conf; fi
#25 ...

#23 [symbolicator-cleanup-self-hosted-local 2/5] RUN if [ -z "${http_proxy}" ]; then echo "Acquire::http::proxy "${http_proxy}";" >> /etc/apt/apt.conf; fi
#23 DONE 0.6s

#26 [sentry-cleanup-self-hosted-local 1/5] FROM docker.io/library/sentry-self-hosted-local
#26 DONE 0.9s

#27 [sentry-cleanup-self-hosted-local 2/5] RUN if [ -z "${http_proxy}" ]; then echo "Acquire::http::proxy "${http_proxy}";" >> /etc/apt/apt.conf; fi
#27 ...

#25 [snuba-cleanup-self-hosted-local 2/5] RUN if [ -z "${http_proxy}" ]; then echo "Acquire::http::proxy "${http_proxy}";" >> /etc/apt/apt.conf; fi
#25 DONE 0.7s

#28 [snuba-cleanup-self-hosted-local 3/5] RUN if [ -z "${https_proxy}" ]; then echo "Acquire::https::proxy "${https_proxy}";" >> /etc/apt/apt.conf; fi
#28 ...

#27 [sentry-cleanup-self-hosted-local 2/5] RUN if [ -z "${http_proxy}" ]; then echo "Acquire::http::proxy "${http_proxy}";" >> /etc/apt/apt.conf; fi
#27 DONE 0.6s

#29 [symbolicator-cleanup-self-hosted-local 3/5] RUN if [ -z "${https_proxy}" ]; then echo "Acquire::https::proxy "${https_proxy}";" >> /etc/apt/apt.conf; fi
#29 DONE 0.8s

#30 [symbolicator-cleanup-self-hosted-local 4/5] RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
#30 ...

#28 [snuba-cleanup-self-hosted-local 3/5] RUN if [ -z "${https_proxy}" ]; then echo "Acquire::https::proxy "${https_proxy}";" >> /etc/apt/apt.conf; fi
#28 DONE 0.7s

#31 [snuba-cleanup-self-hosted-local 4/5] RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
#31 0.520 Get:1 http://security.debian.org/debian-security bullseye-security InRelease [44.1 kB]
#31 0.520 Get:2 http://deb.debian.org/debian bullseye InRelease [116 kB]
#31 0.558 Get:3 http://deb.debian.org/debian bullseye-updates InRelease [39.4 kB]
#31 ...

#32 [sentry-cleanup-self-hosted-local 3/5] RUN if [ -z "${https_proxy}" ]; then echo "Acquire::https::proxy "${https_proxy}";" >> /etc/apt/apt.conf; fi
#32 DONE 1.0s

#30 [symbolicator-cleanup-self-hosted-local 4/5] RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
#30 0.803 Ign:1 http://deb.debian.org/debian stretch InRelease
#30 0.809 Get:2 http://security.debian.org/debian-security stretch/updates InRelease [53.0 kB]
#30 0.830 Get:3 http://deb.debian.org/debian stretch-updates InRelease [93.6 kB]
#30 0.834 Get:4 http://deb.debian.org/debian stretch Release [118 kB]
#30 0.842 Get:5 http://deb.debian.org/debian stretch Release.gpg [3177 B]
#30 1.051 Get:6 http://security.debian.org/debian-security stretch/updates/main amd64 Packages [780 kB]
#30 1.723 Get:7 http://deb.debian.org/debian stretch/main amd64 Packages [7080 kB]
#30 3.974 Fetched 8127 kB in 3s (2560 kB/s)
#30 3.974 Reading package lists...
#30 5.208 Reading package lists...
#30 6.332 Building dependency tree...
#30 6.523 Reading state information...
#30 6.645 Suggested packages:
#30 6.645   anacron logrotate checksecurity
#30 6.645 Recommended packages:
#30 6.645   exim4 | postfix | mail-transport-agent
#30 6.662 The following NEW packages will be installed:
#30 6.666   cron
#30 6.697 0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
#30 6.697 Need to get 96.6 kB of archives.
#30 6.697 After this operation, 257 kB of additional disk space will be used.
#30 6.697 Get:1 http://security.debian.org/debian-security stretch/updates/main amd64 cron amd64 3.0pl1-128+deb9u2 [96.6 kB]
#30 6.926 debconf: delaying package configuration, since apt-utils is not installed

#30 ...

#31 [snuba-cleanup-self-hosted-local 4/5] RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
#31 0.888 Get:4 http://deb.debian.org/debian bullseye/main amd64 Packages [8182 kB]
#31 1.262 Get:5 http://security.debian.org/debian-security bullseye-security/main amd64 Packages [161 kB]
#31 1.621 Get:6 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [2592 B]
#31 3.217 Fetched 8545 kB in 3s (3154 kB/s)
#31 3.217 Reading package lists...
#31 4.098 Reading package lists...
#31 5.042 Building dependency tree...
#31 5.223 Reading state information...
#31 5.457 The following additional packages will be installed:
#31 5.457   sensible-utils
#31 5.459 Suggested packages:
#31 5.459   anacron logrotate checksecurity
#31 5.459 Recommended packages:
#31 5.459   default-mta | mail-transport-agent
#31 5.505 The following NEW packages will be installed:
#31 5.506   cron sensible-utils
#31 5.537 0 upgraded, 2 newly installed, 0 to remove and 3 not upgraded.
#31 5.537 Need to get 114 kB of archives.
#31 5.537 After this operation, 314 kB of additional disk space will be used.
#31 5.537 Get:1 http://deb.debian.org/debian bullseye/main amd64 sensible-utils all 0.0.14 [14.8 kB]
#31 5.539 Get:2 http://deb.debian.org/debian bullseye/main amd64 cron amd64 3.0pl1-137 [99.6 kB]
#31 5.836 debconf: delaying package configuration, since apt-utils is not installed
#31 5.933 Fetched 114 kB in 0s (4128 kB/s)
#31 5.971 Selecting previously unselected package sensible-utils.
(Reading database ... 7032 files and directories currently installed.)
#31 5.998 Preparing to unpack .../sensible-utils_0.0.14_all.deb ...
#31 6.000 Unpacking sensible-utils (0.0.14) ...
#31 6.035 Selecting previously unselected package cron.
#31 6.036 Preparing to unpack .../cron_3.0pl1-137_amd64.deb ...
#31 6.038 Unpacking cron (3.0pl1-137) ...
#31 6.095 Setting up sensible-utils (0.0.14) ...
#31 6.103 Setting up cron (3.0pl1-137) ...
#31 6.195 Adding group `crontab' (GID 101) ...
#31 6.212 Done.
#31 6.262 invoke-rc.d: could not determine current runlevel
#31 6.270 invoke-rc.d: policy-rc.d denied execution of start.
#31 DONE 6.6s

#30 [symbolicator-cleanup-self-hosted-local 4/5] RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
#30 7.014 Fetched 96.6 kB in 0s (5696 kB/s)
#30 7.088 Selecting previously unselected package cron.
(Reading database ... 6906 files and directories currently installed.)
#30 7.092 Preparing to unpack .../cron_3.0pl1-128+deb9u2_amd64.deb ...
#30 ...

#33 [snuba-cleanup-self-hosted-local 5/5] COPY entrypoint.sh /entrypoint.sh
#33 DONE 0.2s

#30 [symbolicator-cleanup-self-hosted-local 4/5] RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
#30 7.092 Preparing to unpack .../cron_3.0pl1-128+deb9u2_amd64.deb ...
#30 7.223 Unpacking cron (3.0pl1-128+deb9u2) ...
#30 7.290 Setting up cron (3.0pl1-128+deb9u2) ...
#30 ...

#24 [snuba-cleanup-self-hosted-local] exporting to image
#24 exporting layers 0.1s done
#24 writing image sha256:9d1fb2151f32f2a07a3b693aed5d0a5e0b3be3778a8656911bb8255962ae59bf done
#24 naming to docker.io/library/snuba-cleanup-self-hosted-local done
#24 DONE 0.4s

#30 [symbolicator-cleanup-self-hosted-local 4/5] RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
#30 7.420 Adding group `crontab' (GID 101) ...
#30 7.432 Done.
#30 7.585 update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
#30 7.589 invoke-rc.d: could not determine current runlevel
#30 7.591 invoke-rc.d: policy-rc.d denied execution of start.
#30 DONE 7.7s

#34 [symbolicator-cleanup-self-hosted-local 5/5] COPY entrypoint.sh /entrypoint.sh
#34 DONE 0.1s

#24 [symbolicator-cleanup-self-hosted-local] exporting to image
#24 ...

#35 [sentry-cleanup-self-hosted-local 4/5] RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
#0 0.570 Get:1 http://security.debian.org/debian-security bullseye-security InRelease [44.1 kB]
#0 0.581 Get:2 http://deb.debian.org/debian bullseye InRelease [116 kB]
#0 0.582 Get:3 http://deb.debian.org/debian bullseye-updates InRelease [39.4 kB]
#0 0.808 Get:4 http://security.debian.org/debian-security bullseye-security/main amd64 Packages [161 kB]
#0 1.013 Get:5 http://deb.debian.org/debian bullseye/main amd64 Packages [8182 kB]
#0 1.750 Get:6 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [2592 B]
#0 3.307 Fetched 8545 kB in 3s (3079 kB/s)
#0 3.307 Reading package lists...
#0 4.518 Reading package lists...
#0 5.511 Building dependency tree...
#0 5.748 Reading state information...
#0 5.941 The following additional packages will be installed:
#0 5.942   sensible-utils
#0 5.943 Suggested packages:
#0 5.943   anacron logrotate checksecurity
#0 5.944 Recommended packages:
#0 5.944   default-mta | mail-transport-agent
#0 6.045 The following NEW packages will be installed:
#0 6.059   cron sensible-utils
#0 6.091 0 upgraded, 2 newly installed, 0 to remove and 13 not upgraded.
#0 6.091 Need to get 114 kB of archives.
#0 6.091 After this operation, 314 kB of additional disk space will be used.
#0 6.091 Get:1 http://deb.debian.org/debian bullseye/main amd64 sensible-utils all 0.0.14 [14.8 kB]
#0 6.095 Get:2 http://deb.debian.org/debian bullseye/main amd64 cron amd64 3.0pl1-137 [99.6 kB]
#0 6.316 debconf: delaying package configuration, since apt-utils is not installed
#0 6.359 Fetched 114 kB in 0s (3005 kB/s)
#0 6.388 Selecting previously unselected package sensible-utils.
(Reading database ... 12313 files and directories currently installed.)
#0 6.404 Preparing to unpack .../sensible-utils_0.0.14_all.deb ...
#0 6.412 Unpacking sensible-utils (0.0.14) ...
#0 6.453 Selecting previously unselected package cron.
#0 6.453 Preparing to unpack .../cron_3.0pl1-137_amd64.deb ...
#0 6.455 Unpacking cron (3.0pl1-137) ...
#0 6.495 Setting up sensible-utils (0.0.14) ...
#0 6.500 Setting up cron (3.0pl1-137) ...
#0 6.549 Adding group `crontab' (GID 101) ...
#0 6.562 Done.
#0 6.581 invoke-rc.d: could not determine current runlevel
#0 6.585 invoke-rc.d: policy-rc.d denied execution of start.
#35 DONE 7.0s

#36 [sentry-cleanup-self-hosted-local 5/5] COPY entrypoint.sh /entrypoint.sh
#36 DONE 0.1s

#24 [symbolicator-cleanup-self-hosted-local] exporting to image
#24 exporting layers 0.1s done
#24 writing image sha256:b1d3e167c15209e467abbc5e137f4ee5f50b78b9e9dd8165c663385d8cfd3f11 done
#24 naming to docker.io/library/symbolicator-cleanup-self-hosted-local done
#24 writing image sha256:9de0593617e65605987a2e8f5acb9d4c2bee49a995fb825d3c0377560eac94fe done
#24 naming to docker.io/library/sentry-cleanup-self-hosted-local done
#24 DONE 0.8s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them

Docker images built.

▶ Setting up Zookeeper ...
Network sentry-self-hosted_default  Creating
Network sentry-self-hosted_default  Created

▶ Downloading and installing wal2json ...
Unable to find image 'curlimages/curl:7.77.0' locally
7.77.0: Pulling from curlimages/curl
339de151aab4: Pulling fs layer
9576f9a419e9: Pulling fs layer
5b67e0e9bce9: Pulling fs layer
7c0640a6c519: Pulling fs layer
1d8f7d50664a: Pulling fs layer
3ce74da83aeb: Pulling fs layer
7094fabf5e16: Pulling fs layer
2f4d0b649c1f: Pulling fs layer
110e7f874674: Pulling fs layer
3ce74da83aeb: Waiting
7094fabf5e16: Waiting
2f4d0b649c1f: Waiting
110e7f874674: Waiting
7c0640a6c519: Waiting
1d8f7d50664a: Waiting
5b67e0e9bce9: Verifying Checksum
5b67e0e9bce9: Download complete
9576f9a419e9: Verifying Checksum
9576f9a419e9: Download complete
339de151aab4: Verifying Checksum
339de151aab4: Pull complete
7c0640a6c519: Verifying Checksum
7c0640a6c519: Download complete
9576f9a419e9: Pull complete
1d8f7d50664a: Verifying Checksum
1d8f7d50664a: Download complete
5b67e0e9bce9: Pull complete
3ce74da83aeb: Verifying Checksum
3ce74da83aeb: Download complete
7c0640a6c519: Pull complete
1d8f7d50664a: Pull complete
3ce74da83aeb: Pull complete
7094fabf5e16: Verifying Checksum
7094fabf5e16: Download complete
7094fabf5e16: Pull complete
2f4d0b649c1f: Download complete
110e7f874674: Verifying Checksum
110e7f874674: Download complete
2f4d0b649c1f: Pull complete
110e7f874674: Pull complete
Digest: sha256:6e0a786e3e5181df00eaf3a0a1749c18a6bb20b01c9bd192ea72176ce8a1c94b
Status: Downloaded newer image for curlimages/curl:7.77.0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5417  100  5417    0     0  23140      0 --:--:-- --:--:-- --:--:-- 23149

▶ Bootstrapping and migrating Snuba ...
Container sentry-self-hosted-clickhouse-1  Creating
Container sentry-self-hosted-zookeeper-1  Creating
Container sentry-self-hosted-redis-1  Creating
Container sentry-self-hosted-clickhouse-1  Created
Container sentry-self-hosted-zookeeper-1  Created
Container sentry-self-hosted-kafka-1  Creating
Container sentry-self-hosted-redis-1  Created
Container sentry-self-hosted-kafka-1  Created
Container sentry-self-hosted-redis-1  Starting
Container sentry-self-hosted-clickhouse-1  Starting
Container sentry-self-hosted-zookeeper-1  Starting
Container sentry-self-hosted-clickhouse-1  Started
Container sentry-self-hosted-zookeeper-1  Started
Container sentry-self-hosted-zookeeper-1  Waiting
Container sentry-self-hosted-redis-1  Started
Container sentry-self-hosted-zookeeper-1  Healthy
Container sentry-self-hosted-kafka-1  Starting
Container sentry-self-hosted-kafka-1  Started
2022-06-29 14:04:38,195 Attempting to connect to Kafka (attempt 0)...
2022-06-29 14:04:38,225 Connected to Kafka on attempt 0
2022-06-29 14:04:38,226 Creating Kafka topics...
Container sentry-self-hosted-clickhouse-1  Running
Container sentry-self-hosted-zookeeper-1  Running
Container sentry-self-hosted-redis-1  Running
Container sentry-self-hosted-kafka-1  Running
Container sentry-self-hosted-zookeeper-1  Waiting
Container sentry-self-hosted-zookeeper-1  Healthy
Finished running migrations

▶ Creating additional Kafka topics ...

▶ Ensuring proper PostgreSQL version ...

▶ Setting up / migrating database ...
Container sentry-self-hosted-smtp-1  Creating
Container sentry-self-hosted-symbolicator-1  Creating
Container sentry-self-hosted-postgres-1  Creating
Container sentry-self-hosted-memcached-1  Creating
Container sentry-self-hosted-clickhouse-1  Running
Container sentry-self-hosted-redis-1  Running
Container sentry-self-hosted-zookeeper-1  Running
Container sentry-self-hosted-kafka-1  Running
Container sentry-self-hosted-snuba-consumer-1  Creating
Container sentry-self-hosted-snuba-subscription-consumer-transactions-1  Creating
Container sentry-self-hosted-snuba-subscription-consumer-events-1  Creating
Container sentry-self-hosted-snuba-transactions-consumer-1  Creating
Container sentry-self-hosted-snuba-sessions-consumer-1  Creating
Container sentry-self-hosted-snuba-outcomes-consumer-1  Creating
Container sentry-self-hosted-snuba-replacer-1  Creating
Container sentry-self-hosted-snuba-api-1  Creating
Container sentry-self-hosted-snuba-subscription-consumer-transactions-1  Created
Container sentry-self-hosted-snuba-subscription-consumer-events-1  Created
Container sentry-self-hosted-snuba-sessions-consumer-1  Created
Container sentry-self-hosted-smtp-1  Created
Container sentry-self-hosted-snuba-transactions-consumer-1  Created
Container sentry-self-hosted-snuba-consumer-1  Created
Container sentry-self-hosted-snuba-api-1  Created
Container sentry-self-hosted-snuba-outcomes-consumer-1  Created
Container sentry-self-hosted-snuba-replacer-1  Created
Container sentry-self-hosted-symbolicator-1  Created
Container sentry-self-hosted-postgres-1  Created
Container sentry-self-hosted-memcached-1  Created
Container sentry-self-hosted-postgres-1  Starting
Container sentry-self-hosted-memcached-1  Starting
Container sentry-self-hosted-symbolicator-1  Starting
Container sentry-self-hosted-zookeeper-1  Waiting
Container sentry-self-hosted-smtp-1  Starting
Container sentry-self-hosted-zookeeper-1  Healthy
Container sentry-self-hosted-kafka-1  Waiting
Container sentry-self-hosted-clickhouse-1  Waiting
Container sentry-self-hosted-clickhouse-1  Waiting
Container sentry-self-hosted-redis-1  Waiting
Container sentry-self-hosted-redis-1  Waiting
Container sentry-self-hosted-clickhouse-1  Waiting
Container sentry-self-hosted-clickhouse-1  Waiting
Container sentry-self-hosted-redis-1  Waiting
Container sentry-self-hosted-kafka-1  Waiting
Container sentry-self-hosted-clickhouse-1  Waiting
Container sentry-self-hosted-kafka-1  Waiting
Container sentry-self-hosted-redis-1  Waiting
Container sentry-self-hosted-clickhouse-1  Waiting
Container sentry-self-hosted-clickhouse-1  Waiting
Container sentry-self-hosted-kafka-1  Waiting
Container sentry-self-hosted-kafka-1  Waiting
Container sentry-self-hosted-kafka-1  Waiting
Container sentry-self-hosted-redis-1  Waiting
Container sentry-self-hosted-redis-1  Waiting
Container sentry-self-hosted-kafka-1  Waiting
Container sentry-self-hosted-kafka-1  Waiting
Container sentry-self-hosted-redis-1  Waiting
Container sentry-self-hosted-clickhouse-1  Waiting
Container sentry-self-hosted-redis-1  Waiting
Container sentry-self-hosted-postgres-1  Started
Container sentry-self-hosted-clickhouse-1  Healthy
Container sentry-self-hosted-kafka-1  Healthy
Container sentry-self-hosted-redis-1  Healthy
Container sentry-self-hosted-clickhouse-1  Healthy
Container sentry-self-hosted-clickhouse-1  Healthy
Container sentry-self-hosted-clickhouse-1  Healthy
Container sentry-self-hosted-clickhouse-1  Healthy
Container sentry-self-hosted-redis-1  Healthy
Container sentry-self-hosted-clickhouse-1  Healthy
Container sentry-self-hosted-kafka-1  Healthy
Container sentry-self-hosted-kafka-1  Healthy
Container sentry-self-hosted-clickhouse-1  Healthy
Container sentry-self-hosted-redis-1  Healthy
Container sentry-self-hosted-kafka-1  Healthy
Container sentry-self-hosted-kafka-1  Healthy
Container sentry-self-hosted-snuba-replacer-1  Starting
Container sentry-self-hosted-kafka-1  Healthy
Container sentry-self-hosted-redis-1  Healthy
Container sentry-self-hosted-snuba-subscription-consumer-transactions-1  Starting
Container sentry-self-hosted-redis-1  Healthy
Container sentry-self-hosted-snuba-sessions-consumer-1  Starting
Container sentry-self-hosted-redis-1  Healthy
Container sentry-self-hosted-redis-1  Healthy
Container sentry-self-hosted-kafka-1  Healthy
Container sentry-self-hosted-kafka-1  Healthy
Container sentry-self-hosted-clickhouse-1  Healthy
Container sentry-self-hosted-snuba-outcomes-consumer-1  Starting
Container sentry-self-hosted-snuba-consumer-1  Starting
Container sentry-self-hosted-snuba-transactions-consumer-1  Starting
Container sentry-self-hosted-snuba-subscription-consumer-events-1  Starting
Container sentry-self-hosted-redis-1  Healthy
Container sentry-self-hosted-snuba-api-1  Starting
Container sentry-self-hosted-memcached-1  Started
Container sentry-self-hosted-smtp-1  Started
Container sentry-self-hosted-symbolicator-1  Started
Container sentry-self-hosted-snuba-replacer-1  Started
Container sentry-self-hosted-snuba-subscription-consumer-transactions-1  Started
Container sentry-self-hosted-snuba-consumer-1  Started
Container sentry-self-hosted-snuba-sessions-consumer-1  Started
Container sentry-self-hosted-snuba-outcomes-consumer-1  Started
Container sentry-self-hosted-snuba-subscription-consumer-events-1  Started
Container sentry-self-hosted-snuba-transactions-consumer-1  Started
Container sentry-self-hosted-snuba-api-1  Started
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
!! Configuration error: ConfigurationError('SyntaxError: invalid syntax (<string>, line 41)')
An error occurred, caught SIGERR on line 12
Cleaning up...

**Comment by ethanhs** [comment]
The clone URL you gave is incorrect, perhaps that was a copy paste error?

Are there any changes to your operating certificates made prior to install?

**Comment by aminvakil** [comment]
I'm seeing this from the logs you have pasted:
```
Ensuring files from examples ...
../sentry/sentry.conf.py already exists, skipped creation.
../sentry/config.yml already exists, skipped creation.
../symbolicator/config.yml already exists, skipped creation.

Ensuring Relay credentials ...
../relay/config.yml already exists, skipped creation.
../relay/credentials.json already exists, skipped creation.
```
which means it has been run more than once and **maybe** something has been put wrong there. This is a clean install so I guess it's OK to nuke everything and try again.

Something like this:
```
docker-compose down -v --remove-orphans
git clean -fdx
for volume in $(docker volume list --format '{{ .Name }}' | grep '^sentry-'); do
  docker volume remove $volume > /dev/null \
    && echo "Removed volume: $volume" \
    || echo "Skipped volume: $volume"
done
```

Then please paste output of `./install.sh` in a [gist](https://gist.github.com).

**Comment by martinwrightgithub** [comment]
This issue has now been resolved. 

The problem was when we were installing via sentry via Ansible and the database password contained a closing quotation mark (") and this caused a syntax error that broke `sentry.conf.py`
