### ISSUE TITLE
Options to control ClickhouseDB disk usage spikes during event bursts

### ISSUE THREAD

**Issue by prasus** [getsentry/self-hosted#1552]
### Problem Statement

We are running self hosted sentry `v21.6.1` deployed using the sentry/sentry helm chart version `11.4.1` it works great in general but we are having issues with the ClickhouseDB disk usage. The sentry's ClickhouseDB storage gets filled quickly when there is a burst of events/errors in the projects. We have rate limits in place for all our busy projects and most of the events are discarded during event bursts, so sentry continues to work fine during burst events. 

I have already updated the snuba cleanup hourly cronjobs (sentry-snuba-cleanup-errors, sentry-snuba-cleanup-transactions) to run every 15 minutes and this helped a bit, but still there are disk usage spikes when there is a burst of events from the apps, Is there something we can do to alleviate/fix this problem?

**Comment by ethanhs** [comment]
We do not support using Sentry via the Helm chart, that is an unofficial third-party offering. I would recommend seeking support from them. I'll leave this open though in case someone in the community has a suggestion or solution.

**Comment by aminvakil** [comment]
I'd suggest opening an issue in https://github.com/sentry-kubernetes/charts .
