### ISSUE TITLE
Exim configuration file /var/lib/exim4/config.autogenerated has the wrong owner, group, or mode

### ISSUE THREAD

**Issue by gaozhibo** [getsentry/self-hosted#1554]
### Version

21.9.0

### Steps to Reproduce

执行 docker-compose up -d  command，I find that my docker image not work , name is sentry_onpremise_smtp_1 。
![image](https://user-images.githubusercontent.com/7436608/176898249-b125bcb3-9f38-4f04-9abd-caacba244e97.png)

### Expected Result

sentry_onpremise_smtp_1  work

### Actual Result

docker image logs  Exim configuration file /var/lib/exim4/config.autogenerated has the wrong owner, group, or mode

**Comment by chadwhitacre** [comment]
Blocking user because image URL shows red here:

https://www.virustotal.com/gui/url/7fd3099cc41165046daf4dcebb49b3a95b9d8341ed79efa647f3fd208a7b9af9?nocache=1
