### ISSUE TITLE
/bin/bash: line 1: gosu: command not found

### ISSUE THREAD

**Issue by goganchic** [getsentry/self-hosted#1556]
### Version

22.6.0

### Steps to Reproduce

1. Start Sentry with docker-compose
2. Wait for a bit
3. Check `docker-compose logs`

### Expected Result

No errors

### Actual Result

```
sentry-self-hosted-snuba-transactions-cleanup-1                | /bin/bash: line 1: gosu: command not found
sentry-self-hosted-snuba-cleanup-1                             | /bin/bash: line 1: gosu: command not found
```

**Comment by aminvakil** [comment]
```
$ docker exec -ti sentry-self-hosted-snuba-cleanup-1 whereis gosu
gosu: /usr/local/bin/gosu
$ docker exec -ti sentry-self-hosted-snuba-cleanup-1 gosu --help
Usage: gosu user-spec command [args]
   eg: gosu tianon bash
       gosu nobody:root bash -c 'whoami && id'
       gosu 1000:1 id

gosu version: 1.12 (go1.13.10 on linux/amd64; gc)
gosu license: GPL-3 (full text at https://github.com/tianon/gosu)
```
It's working fine for me, are you sure your docker has been built correctly?

**Comment by goganchic** [comment]
You run this command using shell directly, but docker-compose run this command using cron, so the command will be something like `cron "0 0 * * * /usr/local/bin/gosu sentry sentry cleanup --days $SENTRY_EVENT_RETENTION_DAYS"`. I don't think that in this case `$PATH` variable will be the same as for shell.

**Comment by goganchic** [comment]
The problem is not with paths: sentry-cleanup and symbolicator-cleanup have gosu, but snuba-transactions-cleanup and snuba-cleanup. I think, it's because snuba-transactions-cleanup and snuba-cleanup use another base image. Does it really contains gosu?

I use such versions:

```
SENTRY_IMAGE=getsentry/sentry:22.6.0
SNUBA_IMAGE=getsentry/snuba:22.6.0
RELAY_IMAGE=getsentry/relay:22.6.0
SYMBOLICATOR_IMAGE=getsentry/symbolicator:0.5.1
```

**Comment by goganchic** [comment]
I'd checked the problem with nightly images - nothing changed: sentry-cleanup and symbolicator-cleanup have gosu, but snuba-transactions-cleanup and snuba-cleanup do not have.

If I add `gosu` into `cron/Dockerfile` - everything works as expected.

**Comment by dlouzan** [comment]
Just experiencing the same issue after updating to 22.6.0. Adding `gosu` to the base image as https://github.com/getsentry/self-hosted/pull/1564 does seem to fix the problem.

/cc @max-wittig

**Comment by ethanhs** [comment]
I can reproduce this issue locally.

**Comment by ethanhs** [comment]
It looks like there was an attempt to remove gosu which may be the root cause of this: https://github.com/getsentry/snuba/pull/2696, that PR has been reverted, but the revert was reverted https://github.com/getsentry/snuba/pull/2777.
