### ISSUE TITLE
I'm having the same issue.    

### ISSUE THREAD

**Issue by RevRebel** [getsentry/self-hosted#1557]
Ubuntu 20 Service
Docker version 20.10.17, build 100c701
docker-compose version 1.27.0, build 980ec85b

Sure would expect that to work. Can you repro on your laptop or some other environment? Is it something unique about your environment? If it's a bug on the `onpremise`/`sentry` side then I'd expect to hear about it from more folks.

_Originally posted by @chadwhitacre in https://github.com/getsentry/self-hosted/issues/1082#issuecomment-910490959_

**Comment by RevRebel** [comment]
.0-121-generic
sentry-kafka-1                              | [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:user.name=root
sentry-kafka-1                              | [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:user.home=/root
sentry-kafka-1                              | [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:user.dir=/
sentry-kafka-1                              | [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:os.memory.free=56MB
sentry-kafka-1                              | [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:os.memory.max=875MB
sentry-kafka-1                              | [main] INFO org.apache.zookeeper.ZooKeeper - Client environment:os.memory.total=59MB
sentry-kafka-1                              | [main] INFO org.apache.zookeeper.ZooKeeper - Initiating client connection, connectString=zookeeper:2181 sessionTimeout=40000 watcher=io.confluent.admin.utils.ZookeeperConnectionWatcher@cc34f4d
sentry-kafka-1                              | [main] INFO org.apache.zookeeper.common.X509Util - Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation
sentry-kafka-1                              | [main] INFO org.apache.zookeeper.ClientCnxnSocket - jute.maxbuffer value is 4194304 Bytes
sentry-kafka-1                              | [main] INFO org.apache.zookeeper.ClientCnxn - zookeeper.request.timeout value is 0. feature enabled=
sentry-kafka-1                              | [main-SendThread(zookeeper:2181)] INFO org.apache.zookeeper.ClientCnxn - Opening socket connection to server zookeeper/172.29.0.4:2181. Will not attempt to authenticate using SASL (unknown error)
sentry-kafka-1                              | [main-SendThread(zookeeper:2181)] INFO org.apache.zookeeper.ClientCnxn - Socket connection established, initiating session, client: /172.29.0.2:50996, server: zookeeper/172.29.0.4:2181
sentry-kafka-1                              | [main-SendThread(zookeeper:2181)] INFO org.apache.zookeeper.ClientCnxn - Session establishment complete on server zookeeper/172.29.0.4:2181, sessionid = 0x100051740dd003e, negotiated timeout = 40000
sentry-kafka-1                              | [main] INFO org.apache.zookeeper.ZooKeeper - Session: 0x100051740dd003e closed
sentry-kafka-1                              | [main-EventThread] INFO org.apache.zookeeper.ClientCnxn - EventThread shut down for session: 0x100051740dd003e
sentry-kafka-1                              | ===> Launching ... 
sentry-kafka-1                              | ===> Launching kafka ... 
sentry-kafka-1                              | [2022-07-03 09:36:17,026] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
sentry-kafka-1                              | [2022-07-03 09:36:17,591] WARN The package io.confluent.support.metrics.collectors.FullCollector for collecting the full set of support metrics could not be loaded, so we are reverting to anonymous, basic metric collection. If you are a Confluent customer, please refer to the Confluent Platform documentation, section Proactive Support, on how to activate full metrics collection. (io.confluent.support.metrics.KafkaSupportConfig)
sentry-kafka-1                              | [2022-07-03 09:36:17,591] WARN The support metrics collection feature ("Metrics") of Proactive Support is disabled. (io.confluent.support.metrics.SupportedServerStartable)
sentry-kafka-1                              | [2022-07-03 09:36:17,924] ERROR Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
sentry-kafka-1                              | kafka.common.InconsistentClusterIdException: The Cluster ID 5ms3zsmFQlGiVgC_dAbIyQ doesn't match stored clusterId Some(qWPWOLQUTaywtgOK-Pr_uA) in meta.properties. The broker is trying to join the wrong cluster. Configured zookeeper.connect may be wrong.
sentry-kafka-1                              |   at kafka.server.KafkaServer.startup(KafkaServer.scala:244)
sentry-kafka-1                              |   at io.confluent.support.metrics.SupportedServerStartable.startup(SupportedServerStartable.java:114)
sentry-kafka-1                              |   at io.confluent.support.metrics.SupportedKafka.main(SupportedKafka.java:66)

**Comment by aminvakil** [comment]
`docker-compose 1.28.0` is the minimum requirement.

Also please open a new issue filling all required fields.
