### ISSUE TITLE
Relay network error

### ISSUE THREAD

**Issue by goganchic** [getsentry/self-hosted#1558]
### Version

22.6.0

### Steps to Reproduce

1. Start sentry self-hosted behind http proxy
2. Wait for a bit
3. Check `docker-compose logs`

### Expected Result

No errors

### Actual Result

```
sentry-self-hosted-relay-1                                     | 2022-07-03T09:27:48Z [relay_server::actors::upstream] WARN: Network outage, scheduling another check in 38.443359375s
sentry-self-hosted-relay-1                                     | 2022-07-03T09:28:13Z [relay_server::actors::upstream] ERROR: authentication encountered error: upstream request returned error 503 Service Unavailable
sentry-self-hosted-relay-1                                     |   caused by: no error details
sentry-self-hosted-relay-1                                     | 2022-07-03T09:28:27Z [relay_server::actors::upstream] WARN: Network outage, scheduling another check in 57.665039062s
```

**Comment by goganchic** [comment]
I should add something into `no_proxy`, but I don't know what is the name of the host.

**Comment by goganchic** [comment]
The name of the host is `web`.

**Comment by aminvakil** [comment]
I thought we have a default `no_proxy`, then I realized there isn't any. I think it's good to also add these to docs.

From `nginx.conf` these should be in `no_proxy`:
`relay`, `web`, `sentry`

**Comment by goganchic** [comment]
https://github.com/getsentry/develop/pull/628

**Comment by goganchic** [comment]
Yep

**Comment by chadwhitacre** [comment]
Thanks again for the contributions, @goganchic! :)
