### ISSUE TITLE
zookeeper unhealthy

### ISSUE THREAD

**Issue by fengerzh** [getsentry/self-hosted#1562]
### Version

22.6.0

### Steps to Reproduce

After upgrade to 22.6.0, `docker ps` report zookeeper container as unhealthy.

BTW, after `docker-compose pull`, it says have to build something like `docker-compose build snuba-cleanup` and else, my build failed with error of `Permission denied`. I can't solve it, so just ignore it, and run `docker-compose up -d` to start, don't know if this related to that or not.

### Expected Result

Hope it works.

### Actual Result

```
c2a1bc683325   confluentinc/cp-zookeeper:6.2.0                   "/etc/confluent/dock…"   16 minutes ago   Up 16 minutes (unhealthy)   2181/tcp, 2888/tcp, 3888/tcp                                                                                    sentry_onpremise_zookeeper_1
```

run docker logs show as below:

```
root@iz2zecpcbch9u78uni2hzsz /k/sentry# docker logs sentry_onpremise_zookeeper_1
===> User
uid=1000(appuser) gid=1000(appuser) groups=1000(appuser)
===> Configuring ...
===> Running preflight checks ...
===> Check if /var/lib/zookeeper/data is writable ...
===> Check if /var/lib/zookeeper/log is writable ...
===> Launching ...
===> Launching zookeeper ...
[2022-07-04 07:28:36,126] WARN Either no config or no quorum defined in config, running  in standalone mode (org.apache.zookeeper.server.quorum.QuorumPeerMain)
[2022-07-04 07:28:41,104] WARN o.e.j.s.ServletContextHandler@433defed{/,null,STOPPED} contextPath ends with /* (org.eclipse.jetty.server.handler.ContextHandler)
[2022-07-04 07:28:41,104] WARN Empty contextPath (org.eclipse.jetty.server.handler.ContextHandler)
[2022-07-04 07:28:42,464] WARN ServletContext@o.e.j.s.ServletContextHandler@433defed{/,null,STARTING} has uncovered http methods for path: /* (org.eclipse.jetty.security.SecurityHandler)
```

Also the integration with Gitlab failed, cannot login from webpage.

**Comment by ethanhs** [comment]
> BTW, after docker-compose pull, it says have to build something like docker-compose build snuba-cleanup and else, my build failed with error of Permission denied

Hm, could you share the logs related to that and the exact steps you did to get that error?

It sounds like you ran `./install.sh` at some point, then `docker-compose pull` then `docker-compose up -d`, is that correct?

**Comment by fengerzh** [comment]
After `docker-compose pull`, the message is like this:

```
WARNING: Some service image(s) must be built from source by running:
    docker-compose build symbolicator-cleanup snuba-cleanup sentry-cleanup snuba-transactions-cleanup
```

Then I ran `docker-compose build symbolicator-cleanup snuba-cleanup sentry-cleanup snuba-transactions-cleanup` as indicated, it says:

```
Building snuba-cleanup
Sending build context to Docker daemon  3.072kB
Step 1/5 : ARG BASE_IMAGE
Step 2/5 : FROM ${BASE_IMAGE}
 ---> 5321b198370b
Step 3/5 : RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
 ---> Running in fd209fdf7424
Reading package lists...
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)
The command '/bin/sh -c apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*' returned a non-zero code: 100
ERROR: Service 'snuba-cleanup' failed to build : Build failed
```

**Comment by fengerzh** [comment]
About half an year ago, I `git pull` the master branch, and I did not notice the version, after all, I ran `install.sh` and it works, so I didn't care.

But recently, Sentry began to create http `400` errors, so I think I need to upgrade it, so I ran `docker-compose pull` to try to upgrade, but not work, I checked the `.env` file, found that:

```
SENTRY_IMAGE=getsentry/sentry:nightly
SNUBA_IMAGE=getsentry/snuba:nightly
RELAY_IMAGE=getsentry/relay:nightly
```

So I changed the version in `.env` file as below:

```
SENTRY_IMAGE=getsentry/sentry:22.6.0
SNUBA_IMAGE=getsentry/snuba:22.6.0
RELAY_IMAGE=getsentry/relay:22.6.0
```

And got zookeeper not start errors.

**Comment by aminvakil** [comment]
> But recently, Sentry began to create http `400` errors, so I think I need to upgrade it, so I ran `docker-compose pull` to try to upgrade, but not work, I checked the `.env` file, found that:
> 
> ```
> SENTRY_IMAGE=getsentry/sentry:nightly
> SNUBA_IMAGE=getsentry/snuba:nightly
> RELAY_IMAGE=getsentry/relay:nightly
> ```
> 
`docker-compose pull` is supposed to fail for the exact reason it's saying.

Please use `./install.sh` and let it pull and build your docker images for you.
> So I changed the version in `.env` file as below:
> 
> ```
> SENTRY_IMAGE=getsentry/sentry:22.6.0
> SNUBA_IMAGE=getsentry/snuba:22.6.0
> RELAY_IMAGE=getsentry/relay:22.6.0
> ```
> 
> And got zookeeper not start errors.

You ought to git checkout to the tag you want to use, just changing the `.env` is not enough.

And please read https://develop.sentry.dev/self-hosted/ prior to making modifications to your system.

**Comment by fengerzh** [comment]
Yes, thank you! I run `install.sh` and it works now.
