### ISSUE TITLE
Error 500 when uploading new organization avatar

### ISSUE THREAD

**Issue by NK74** [getsentry/self-hosted#1565]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

22.6.0

### Steps to Reproduce

Hello

I am unable to change default avatar. My file fit the requirement (255px x 255px)
![image](https://user-images.githubusercontent.com/17825769/176711946-b813b395-0fb4-42f3-976f-06710556e239.png)

### Expected Result

Upload the avatar and change organization avatar ;) 

### Actual Result

![image](https://user-images.githubusercontent.com/17825769/176711451-2347eea3-0659-4a26-b084-964106b0acc5.png)

![image](https://user-images.githubusercontent.com/17825769/176713170-fb003fef-bf80-4d3c-b52f-00adf58df9bb.png)

**Comment by NK74** [comment]
```
sentry-data# ls -l
total 20
drwx------ 3 libstoragemgmt root  4096 May 26  2020 data

data# ls -l
total 4
drwxr-xr-x 11 libstoragemgmt root 4096 Jul 26  2021 files

files# ls -l
total 36
drwxr-xr-x 3 libstoragemgmt input 4096 Jul 26  2021 11
drwxr-xr-x 3 libstoragemgmt input 4096 Jul 26  2021 18
drwxr-xr-x 3 libstoragemgmt input 4096 Apr 12  2021 19
drwxr-xr-x 3 libstoragemgmt input 4096 Apr 13  2021 5d
drwxr-xr-x 3 libstoragemgmt input 4096 Jun  2  2021 9e
drwxr-xr-x 3 libstoragemgmt input 4096 Jul 16  2021 b2
drwxr-xr-x 3 libstoragemgmt input 4096 Jul 26  2021 b4
drwxr-xr-x 3 libstoragemgmt input 4096 Jun  2  2021 bc
drwxr-xr-x 3 libstoragemgmt input 4096 Apr 13  2021 ef
```

**Comment by aminvakil** [comment]
Can you also check for other clues which restrict docker from writing, specific SELinux permissions, `df -h` to check free space, `df -i` to check free inodes, etc.

**Comment by chadwhitacre** [comment]
Were you able to figure something out here, @NK74, or did you end up giving up? :(

**Comment by NK74** [comment]
Strange, we recently upgraded our sentry version. I tried to upload again, it worked...

**Comment by chadwhitacre** [comment]
Ah, glad we fixed it! 😅
