### ISSUE TITLE
When i upload a large pdb file , File exceeds maximum size

### ISSUE THREAD

**Issue by 9989836** [getsentry/self-hosted#1569]
### Version

docker-compose 22.4.0

### Steps to Reproduce

1、I have run my own instance of Sentry , and override this setting “system.maximum-file-size” to 4G
2、Use sentry-cli upload a pdb file , size more then 2G
3、The pdb file upload success , And an error occurred when assemble file 。

### Expected Result

  DEBUG   2022-07-07 16:42:36.915150 +08:00 > POST /api/0/projects/sentry/windows-test-debug/files/difs/assemble/ HTTP/1.1
  DEBUG   2022-07-07 16:42:37.086702600 +08:00 < Set-Cookie: sentrysid=gAJ9cQBYCQAAAF9sYW5ndWFnZXEBWAIAAABlbnECcy4:1o9N5p:Jlz34BwQGEcib6heY2nePRwD5SQ; expires=Thu, 21 Jul 2022 08:42:37 GMT; HttpOnly; Max-Age=1209600; Path=/
  DEBUG   2022-07-07 16:42:37.093624500 +08:00 response status: 200
  DEBUG   2022-07-07 16:42:37.094642800 +08:00 body: {"0740c40a153a1bae6061a9227ae9aff19fce2d6f":{"state":"error","detail":"File exceeds maximum size","missingChunks":[]}}
> File processing complete:
    ERROR xxxx.dll.pdb
        File exceeds maximum size
  DEBUG   2022-07-07 16:42:37.233862300 +08:00 request POST http://senty-test.com/api/0/projects/sentry/windows-test-debug/reprocessing/
  DEBUG   2022-07-07 16:42:37.234689300 +08:00 using token authentication
  DEBUG   2022-07-07 16:42:37.235654400 +08:00 retry number 0, max retries: 0
  DEBUG   2022-07-07 16:42:37.256406400 +08:00 > POST /api/0/projects/sentry/windows-test-debug/reprocessing/ HTTP/1.1

### Actual Result

In the sentry source code, "files.py"

def get_max_file_size(organization):
"""Returns the maximum allowed debug file size for this organization."""
if features.has("organizations:large-debug-files", organization):
return MAX_FILE_SIZE
else:
return options.get("system.maximum-file-size")

How do I override the “"organizations:large-debug-files" configuration？

thank your very much !!!

**Comment by 9989836** [comment]
HI @aminvakil   2GB is the maximum offset supported by fileblob , How to break through this limitation ？

My pdb file size 2.1GB.

**Comment by chadwhitacre** [comment]
Answer from https://github.com/getsentry/sentry/issues/36538:

> the way to go for these large files would be to use a custom symbol source, and host your own symbol server that symbolicator can then use/query.

**Comment by bruno-garcia** [comment]
New max is 4 GB:

* https://github.com/getsentry/sentry/issues/86896
