### ISSUE TITLE
no image is specified for the address of the frame in self-hosted sentry

### ISSUE THREAD

**Issue by XiaoyuDong** [getsentry/self-hosted#1570]
### Version

Self-hosted Sentry 22.5.0 ffc60a7

### Steps to Reproduce

1、create a c++ project to build a libtest.so at ubuntu 20.04，this library produce a crash，like：
      int *p = nullptr;
      p[2] = 1;
2、create a c++ project  to build a application program link with libtest.so，this program use breakpad to generate minidump.
3、use dump_syms to generate symbol file of library and program.
4、use sentry-cli create release and upload symbol file.
5、run program above， generate a minidump file.
6、use curl upload minidump file

### Expected Result

sentry can location crash about line number of source file at libtest.so module in stack trace of self-hosted sentry。

### Actual Result

sentry can location crash about line number of source file at program module, but at lbitest.so module, show:
no image is specified for the address of the frame.

I use sentry.io, can location crash about line number of source file at libtest.so module in stack trace.

**Comment by XiaoyuDong** [comment]
> Sorry, I am not sure I understand. Are you saying that this works with sentry.io but not self-hosted Sentry?

yes
i  use clang toolchain， not gcc

**Comment by ethanhs** [comment]
Could this be an issue with the upload limit perhaps? You can edit your sentry.conf.py, see https://develop.sentry.dev/feature-flags/

Settings to look at:
 - `system.maximum-file-size`
 - `organizations:large-debug-files`

**Comment by aminvakil** [comment]
Also if you have a proxy (nginx, haproxy, etc.) in front of your sentry instance, it may limit maximum body size you can send.

https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size
