### ISSUE TITLE
Service 'snuba-cleanup' failed to start

### ISSUE THREAD

**Issue by billni** [getsentry/self-hosted#1574]
### Version

22.1.0

### Steps to Reproduce

docker-compose start snuba-cleanup

### Expected Result

This service is running.

### Actual Result

[+] Running 4/5
 ⠿ Container sentry-self-hosted-zookeeper-1      Healthy                                                                                                           0.5s
 ⠿ Container sentry-self-hosted-clickhouse-1     Healthy                                                                                                           0.5s
 ⠿ Container sentry-self-hosted-kafka-1          Healthy                                                                                                           0.5s
 ⠿ Container sentry-self-hosted-redis-1          Healthy                                                                                                           0.5s
 ⠇ Container sentry-self-hosted-snuba-cleanup-1  Starting                                                                                                          0.8s
Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"*/5 * * * * gosu snuba snuba cleanup --storage errors --dry-run False\": stat */5 * * * * gosu snuba snuba cleanup --storage errors --dry-run False: no such file or directory": unknown

**Comment by aminvakil** [comment]
Same as #1575 , let's continue discussion there.
