### ISSUE TITLE
Service 'symbolicator-cleanup' failed to start

### ISSUE THREAD

**Issue by billni** [getsentry/self-hosted#1575]
### Version

22.1.0

### Steps to Reproduce

 docker-compose start  symbolicator-cleanup

### Expected Result

Running

### Actual Result

[+] Running 0/1
 ⠇ Container sentry-self-hosted-symbolicator-cleanup-1  Starting                                                                                                   0.8s
Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"55 23 * * * gosu symbolicator symbolicator cleanup\": executable file not found in $PATH": unknown
[root@TX-k8s-worker1-test self-hosted-master]#

**Comment by aminvakil** [comment]
This is a known issue which has been fixed in https://github.com/getsentry/self-hosted/pull/1564
It will be included in 22.7.0 which will be released on 15th this month (4 days remaining), you can either wait for

**Comment by billni** [comment]
I compared the parameters of the sentry-cleanup container in docker-compose.yml , then found that the startup parameters of the snuba-clean container lacked the statement "entrypoint:"/entrypoint.sh"
This is also the reason why the symbolicator-cleanup container cannot be up properly.

**Comment by aminvakil** [comment]
This has not been changed since 17 months ago: https://github.com/getsentry/self-hosted/blame/master/docker-compose.yml#L339

Can you check `git diff`?

**Comment by billni** [comment]
Then I don't know why. I downloaded version 22.6.0 and  added this statement: entrypoint: "/entrypoint.sh", snuba-cleanup and symbolicator-cleanup can run normally.

**Comment by aminvakil** [comment]
You shouldn't need to manually add this to `docker-compose.yml`, but you may check `git diff` or if you have committed something by mistake or ... .

Let us know if there was something wrong in repository.
