### ISSUE TITLE
How we can push the sentry application logs to Cloud Watch & change the default volume location to EFS

### ISSUE THREAD

**Issue by praseeb** [getsentry/self-hosted#1576]
### Self-Hosted Version

22.5.0

### CPU Architecture

x86_64

### Docker Version

20.10.7

### Docker Compose Version

1.29.0

### Steps to Reproduce

We are using Sentry self-host with docker-compose approach, we would like push our logs to cloud watch instead of storing in the ec2 standalone machine.

Also, currently all the containers are storing their volumes in EC2 root volume, we would like to change that to EFS location.

How we can achieve this, Any suggestion on this approach ?
Currently we are using sentry 22.5.0 version.

### Expected Result

Sentry application Logs need to be pushed to CloudWatch & need to change the default Volume location to EFS

### Actual Result

Currently Sentry application logs are stored in the ec2 instance itself
Also about Volumes, its using the default location of docker to store the sentry volumes.

**Comment by praseeb** [comment]
@chadwhitacre

**Comment by ethanhs** [comment]
Hi,

I believe the best option to configure the docker daemon to put logs in CloudWatch https://docs.docker.com/config/containers/logging/awslogs/

You can also set the root point of storage for volumes using this method which should enable you to store the volumes on EFS.

**Comment by praseeb** [comment]
@ethanhs  Thanks for the suggestions.

If we changing the root volume to EFS, which all volumes we need to migrate carefully and important?

@chadwhitacre

**Comment by ethanhs** [comment]
The volumes that persist are here: https://github.com/getsentry/self-hosted/blob/eb4d70995bbbfaee4524b8f43cdbfd00e44d008d/docker-compose.yml#L375

**Comment by praseeb** [comment]
@ethanhs  okay thanks for the quick update, will check and update if there are any issue while performing these changes.
