### ISSUE TITLE
Lightweight version without Russian technologies

### ISSUE THREAD

**Issue by mmospanenko** [getsentry/self-hosted#1578]
### Problem Statement

Hi everyone! Sentry is a great product, especially self-hosted solution when we have security restrictions inside the company.  But after one from last major updates it became in something heavy, unmaintainable and uses a lot of resources (hdd, ram). I think it is because you added some real-time monitoring functionality and analytics - I don't think that a lot of people are using it (we don't). And this part is using dangerous Russian tool from Yandex - Clickhouse. 

I'd like to see some versions for different usecases. One - lightweight - for error logging only, second for performance analysis, etc. 

In most cases we use inly traceback collecting functionality, will be great to have this simple onpremise version (or docker-compose) to install on small servers.

Thank you for a great product, I hope these request will find support from other users. 

### Solution Brainstorm

Add light-weight docker-compose for self-hosted variant of installation (without analytics and others time series db requirements).

**Comment by ethanhs** [comment]
Clickhouse is not a "dangerous Russian tool". While it started there a decade ago, Clickhouse is now an open source project backed by a company incorporated in the San Francisco Bay Area, with offices in Amsterdam.

Wikipedia (https://en.wikipedia.org/wiki/ClickHouse) says this about it:

> ClickHouse Inc. is headquartered in the Bay Area of California, United States with the subsidiary, ClickHouse B.V., based in [Amsterdam](https://en.wikipedia.org/wiki/Amsterdam), Netherlands

I am going to go ahead and close this.

**Comment by mmospanenko** [comment]
My point was that Sentry now is to heavy and not all use it. Will be great to have only code modules distribution, without heavy performance analysis. Only bug monitoring, how it was before major update recently.

**Comment by ethanhs** [comment]
I see. Splitting up the release into components is something we can consider, but it isn't easy. There are a lot of moving parts but I will ask internally about it.

Clickhouse is a dependency of Snuba, which is used *both* in errors and performance. Making a version of Sentry self-hosted that just had the error reporting features would still depend on Clickhouse.
