### ISSUE TITLE
Sentry Postgres Container always in "Restarting" status

### ISSUE THREAD

**Issue by NaveenGovindraj** [getsentry/self-hosted#1593]
### Self-Hosted Version

10.0.1

### CPU Architecture

x86_64 GNU/Linux

### Docker Version

17.05.0-ce

### Docker Compose Version

1.25.4

### Steps to Reproduce

Hi Team,

I am using Sentry onpremise Version: 10.0.1.
I was trying to run "./install.sh" and all the containers except "Postgres" seem to be up and running.

Postgres container alone seems to be in "Restarting" status.

As a result, I ma not able access the Sentry web portal as well.

### Expected Result

All Containers are up and running.

### Actual Result

e8abda0dd849  postgres:9.6  "docker-entrypoint..."   18 seconds ago      Restarting (1) 1 second ago                                                        sentry_onpremise_postgres_1

**Comment by NaveenGovindraj** [comment]
Hi @aminvakil,
Thanks for the response.

Yes I understand its an ancient installation, but we are still using this installation and I was just running "./install.sh" command and now I receive this error message:

`Reading package lists...
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)
Removing intermediate container 1e6c1be40c80

ERROR: for snuba-cleanup  (<Service: snuba-cleanup>, "The command '/bin/sh -c apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*' returned a non-zero code: 100")
Service 'snuba-cleanup' failed to build: The command '/bin/sh -c apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*' returned a non-zero code: 100
Cleaning up...
`
Any suggestions on how to resolve this error message?

**Comment by aminvakil** [comment]
Aha, so do you think it's appropriate this issue and continue discussion in https://github.com/getsentry/self-hosted/issues/1531?

**Comment by NaveenGovindraj** [comment]
Sure, I already tried the steps mentioned in https://github.com/getsentry/self-hosted/issues/1531 but it did not resolve the issue for me.
Secondly, do you think the postgress issue is due to this issue?

**Comment by aminvakil** [comment]
What does `docker-compose logs postgres` say? Any other log? I assume it started to happen after you executed `./install.sh`, right?

**Comment by aminvakil** [comment]
Seems like your database has been corrupted, not sure why though.

**Comment by NaveenGovindraj** [comment]
anyway to recover them? what is the best way to proceed on such situations?
I don't mind the data loss, but I would like to keep/retain my projects and DSNs. Is that possible?

**Comment by aminvakil** [comment]
@NaveenGovindraj There is https://develop.sentry.dev/self-hosted/backup/#quick-backup but I'm not sure if it works for a corrupted database.

Searching for your error, I also reached this, https://dba.stackexchange.com/a/261761 , you may want to try it.
