### ISSUE TITLE
nginx container-json.log is consuming a lot of disk space

### ISSUE THREAD

**Issue by lanandra** [getsentry/self-hosted#1594]
### Self-Hosted Version

21.9.0

### CPU Architecture

x86_64

### Docker Version

20.10.7

### Docker Compose Version

1.29.2

### Steps to Reproduce

Self hosted on Amazon EC2. Our EBS disk space usage most likely increased periodically every 1-2 months

- We have set event retention days with default configuration which is 90 days.
- Then we check top disk usage on /var/ directory that consumed most disk, found out /var/lib/docker/containers/ is using most of the space and specifically directory which nginx container resided
- File that consumed most of the disk usage is randomstring-json.log. For Example
```
sudo ls -lah
total 387G
drwx-----x  4 root root  237 Jul 26 05:25 .
drwx-----x 40 root root 4.0K Jan 27 16:05 ..
-rw-r-----  1 root root 387G Jul 26 13:18 0c5320ed9e5f8bb6bd65d724f06f831aba500ced9118f1dc021006171a87b82f-json.log
drwx------  2 root root    6 Jan 27 15:59 checkpoints
-rw-------  1 root root 3.7K Jan 27 16:09 config.v2.json
-rw-r--r--  1 root root 1.7K Jan 27 16:09 hostconfig.json
-rw-r--r--  1 root root   13 Jan 27 16:09 hostname
-rw-r--r--  1 root root  174 Jan 27 16:09 hosts
drwx-----x  2 root root    6 Jan 27 15:59 mounts
-rw-r--r--  1 root root   98 Jan 27 16:09 resolv.conf
-rw-r--r--  1 root root   71 Jan 27 16:09 resolv.conf.hash
```

### Expected Result

- My assumption this usage because access log of nginx is enabled. If we disable the nginx access log, can the disk usage consumption will not increased significantly every 1-2 months ?
- Is it safe to delete this json.log. ?

### Actual Result

The result still not visible as we haven't done any actions

**Comment by aminvakil** [comment]
`nginx` log is not persistent and can be removed once you remove `nginx` container and create it again.

We have also disabled `nginx` log in our self-hosted setup as we don't need and use `access.log` inside `nginx` container as well.

Just change `access_log` line in `nginx/nginx.conf` to `access_log off;` and recreate `nginx` container.

Also if uptime of service is important to you you can remove and recreate `nginx` container with this command:

`docker-compose rm -s -v nginx`

Then run `docker-compose up -d` to recreate `nginx` container.

**Comment by lanandra** [comment]
Nice, thanks for your feedback @aminvakil. This solve our issue

**Comment by aminvakil** [comment]
> Nice, thanks for your feedback @aminvakil. This solve our issue
> 

Great!
> About the error log in nginx.conf, is it safe if we also disable it ?

AFAIK disabling error log does not affect `nginx` core functionality in proxying and serving files, but to be honest I don't see a point in disabling error log anyway.

You can try disabling error log and see for yourself though ;)

**Comment by vzhgit** [comment]
Or if you what to have logs you can modify docker-compose.yaml file by adding into a common section for each container following `logging` settings:
```
x-restart-policy: &restart_policy
  restart: unless-stopped
  logging:
    driver: "json-file"
    options:
      max-size: "20m"
      max-file: "10"
```
And docker daemon will automatically control size of log files: 20Mb * 10 = 200Mb for each container, I think it's really useful.

**Comment by aminvakil** [comment]
@vzhgit Thank you very much! I think it's appropriate to document this. Do you want to open a PR in https://github.com/getsentry/develop/tree/master/src/docs/self-hosted ?

**Comment by aminvakil** [comment]
> @vzhgit Thank you very much! I think it's appropriate to document this. Do you want to open a PR in https://github.com/getsentry/develop/tree/master/src/docs/self-hosted ?

@vzhgit And could you please mention me on the PR then? I don't keep an eye on all the PRs of docs.

Thanks!

**Comment by lanandra** [comment]
@aminvakil @vzhgit Sorry to bump this issue, since @aminvakil mentioned to document this issue and create a new PR on docs.

Tried to check it on docs repo but haven't seen commit about it yet.
May I continue on that ? I can try to document this issue.

About the docs, is it appropriate if i write it on [troubleshooting](https://develop.sentry.dev/self-hosted/troubleshooting/) section of self hosted @aminvakil ?

**Comment by aminvakil** [comment]
@lanandra Thanks, @vzhgit has created a PR regarding this, please mention any comment you have on it.

https://github.com/getsentry/develop/pull/675
