### ISSUE TITLE
Transactions delayed: Ingest Consumer worker flush

### ISSUE THREAD

**Issue by wormhole-wayne** [getsentry/self-hosted#1595]
### Self-Hosted Version

22.6.0

### CPU Architecture

x86_64

### Docker Version

Kubernetes 1.20

### Docker Compose Version

0

### Steps to Reproduce

Send a bunch of transactions

### Expected Result

Transactions processed in a timely manner

### Actual Result

Transactions show up hours later

**Comment by wormhole-wayne** [comment]
Running on Kubernetes, wondering if there is a way to scale the ingest-consumers to process more transactions, faster: https://github.com/sentry-kubernetes/charts/issues/690

**Comment by aminvakil** [comment]
Do not cross post please.

If you could reproduce it on self-hosted open a new issue.
