### ISSUE TITLE
table growth in the postgres database

### ISSUE THREAD

**Issue by fadeinflames** [getsentry/self-hosted#1599]
### Self-Hosted Version

21.9.0

### CPU Architecture

x86_64

### Docker Version

19.03

### Docker Compose Version

2.04

### Steps to Reproduce

just use sentry

### Expected Result

idk

### Actual Result

the nodestore table grows extremely fast and eats up disk space. what to do? is it possible to truncate it?

**Comment by aminvakil** [comment]
How many events do you have in your sentry installation and how much disk space postgres volume has been taken?

You can reduce `SENTRY_EVENT_RETENTION_DAYS` in `.env` from 90 days by default to something lower if you don't need all the 90 days.

**Comment by fadeinflames** [comment]
@aminvakil 
i need retention more than 90 days, coz its prod server
postgres volume - 100gb
events - more than 2.5 mil

**Comment by aminvakil** [comment]
@fadeinflames From my experience that's totally normal. Although your events may vary.

**Comment by fadeinflames** [comment]
@aminvakil and the only solution is to constantly increase the space for the base?

**Comment by fadeinflames** [comment]
@aminvakil if I clear this table, what will be the consequences?

**Comment by aminvakil** [comment]
> @aminvakil and the only solution is to constantly increase the space for the base?

After retention days (by default 90 days) older events will be removed and disk space will be constant (if your load is constant though).

> @aminvakil if I clear this table, what will be the consequences?

Something will break, not sure where though.

**Comment by ethanhs** [comment]
One other thing you can try @fadeinflames is running pg_repack: 
https://develop.sentry.dev/self-hosted/troubleshooting/#postgres
