### ISSUE TITLE
When you use external SSL reverse proxy, you would be to know real ip address in logs 

### ISSUE THREAD

**Issue by IgorAlov** [getsentry/self-hosted#1604]
### Problem Statement

Some times, when you using external nginx as SSL reverse proxy, you would be want to know real ip addresses in docker nginx's logs instad of docker0's ip address.

### Solution Brainstorm

So you could add options to set_real_ip_from 172.18.0.1; option to the nginx/nginx.conf:
```
--- /nginx/nginx.conf  2022-07-28 22:14:34.630461441 +0300
+++ /nginx/nginx.conf.new      2022-07-28 22:14:20.002233263 +0300
@@ -26,6 +26,8 @@
 
        keepalive_timeout 75s;
 
+       set_real_ip_from 172.18.0.1;
+
        gzip off;
        server_tokens off;
```

**Comment by ethanhs** [comment]
Unfortunately I don't think that works for two reasons:

1. The IP of the web container might vary, so we'd have to regenerate the config file every time someone `docker compose up`'d
2. (I might be wrong on this) I don't think this works with how podman does container networking, which we'd like to support https://github.com/getsentry/self-hosted/issues/369)

Thanks for the suggestion all the same!
