### ISSUE TITLE
Installation Error: Service 'snuba-cleanup' failed to build

### ISSUE THREAD

**Issue by ckrgithub** [getsentry/self-hosted#1605]
### Self-Hosted Version

latest version

### CPU Architecture

linux/amd64

### Docker Version

20.10.7

### Docker Compose Version

1.29.2

### Steps to Reproduce

1. git clone https://github.com/Sentry-ARM/onpremise.git
2. cd onpremise
3. ./install.sh

### Expected Result

should install successfully

### Actual Result

Building snuba-cleanup
Sending build context to Docker daemon  3.584kB
Step 1/5 : ARG BASE_IMAGE
Step 2/5 : FROM ${BASE_IMAGE}
 ---> 5ef1ff96c8d8
Step 3/5 : RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
 ---> [Warning] The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
 ---> Running in 455c33c2091f
standard_init_linux.go:228: exec user process caused: exec format error
The command '/bin/sh -c apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*' returned a non-zero code: 1
_**ERROR: Service 'snuba-cleanup' failed to build : Build failed**_

**Comment by aminvakil** [comment]
Other repositories are not supported.

**Comment by aminvakil** [comment]
Other repositories are not supported, try this

**Comment by ckrgithub** [comment]
The problem is “The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64)”

**Comment by aminvakil** [comment]
Why are you using https://github.com/Sentry-ARM/onpremise ?

Please clone this repository which you have opened issue on and try again.
