### ISSUE TITLE
issue alert has not been triggered

### ISSUE THREAD

**Issue by chenzizui** [getsentry/self-hosted#1606]
### Self-Hosted Version

22.5.0

### CPU Architecture

intel core i7

### Docker Version

20.10.16

### Docker Compose Version

2.6.0

### Steps to Reproduce

use 22.5.0 version

### Expected Result

triggered error,issue alert has been triggered

### Actual Result

triggered error,but issue alert has not been triggered

**Comment by ethanhs** [comment]
Hi, could you give some more details about the configuration of the alert? Can you check the logs for the worker container to see if there are any errors there?

**Comment by chenzizui** [comment]
![image](https://user-images.githubusercontent.com/27997366/182090334-0a28fbdc-5999-434c-add7-8f992348d1fc.png)

**Comment by chenzizui** [comment]
issue list exist,but issue alert not receive

**Comment by ethanhs** [comment]
Could you please send the output of `docker compose logs` please? I want to see if there is an error in the server when the event should be firing.

**Comment by NB13** [comment]
Seems like a duplicate of https://github.com/getsentry/sentry/issues/37200

**Comment by ethanhs** [comment]
@chenzizui can you try upgrading to 22.8.0 (or 22.9.0, which is releasing tomorrow!) and see if this issue persists?

**Comment by afaianswq** [comment]
We had a similar issue: Alerts were not triggered after conditions were clearly met. Checking logs revealed we had an issue with Kafka documented here: https://develop.sentry.dev/self-hosted/troubleshooting/#kafka
