### ISSUE TITLE
docker-compose build clickhouse error

### ISSUE THREAD

**Issue by feeops** [getsentry/self-hosted#1608]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

22.7.0

### Steps to Reproduce

docker-compose version: 2.7.0
docker version: 20.10.17
OS: centos 7

docker-compose build clickhouse

### Expected Result

success

### Actual Result

[+] Building 0.0s (2/2) FINISHED                                                                                                    
 => [internal] load build definition from Dockerfile                                                                           0.0s
 => => transferring dockerfile: 31B                                                                                            0.0s
 => [internal] load .dockerignore                                                                                              0.0s
 => => transferring context: 2B                                                                                                0.0s
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: base name (${BASE_IMAGE}) should not be blank

**Comment by ethanhs** [comment]
Hi! Did you run the installer script `./install.sh` in this repo? It seems that the compose file is missing a required environment variable. If you did run the official installer, could you send the full install log please?

**Comment by feeops** [comment]
> Hi! Did you run the installer script `./install.sh` in this repo? It seems that the compose file is missing a required environment variable. If you did run the official installer, could you send the full install log please?

Yes.I run the official installer

[sentry_install_log-2022-07-29_15-11-24.txt](https://github.com/getsentry/self-hosted/files/9247912/sentry_install_log-2022-07-29_15-11-24.txt)

The install is success.But when I rebuild,it is failed

**Comment by aminvakil** [comment]
I don't know about this pip plugin, but it's worth fixing this too.
```
Failed to load plugin 'dingtalk':
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/initializer.py", line 33, in register_plugins
    plugin = ep.load()
  File "/usr/local/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/sentry_dingtalk/plugin.py", line 28, in <module>
    from django.core.urlresolvers import reverse
ModuleNotFoundError: No module named 'django.core.urlresolvers'
```

Also by rebuilding you mean, running `./install.sh` again? Because I don't see the error you've pasted in your original post in log you've pasted.

**Comment by feeops** [comment]
> I don't know about this pip plugin, but it's worth fixing this too.
> 
> ```
> Failed to load plugin 'dingtalk':
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/sentry/runner/initializer.py", line 33, in register_plugins
>     plugin = ep.load()
>   File "/usr/local/lib/python3.8/importlib/metadata.py", line 77, in load
>     module = import_module(match.group('module'))
>   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/usr/local/lib/python3.8/site-packages/sentry_dingtalk/plugin.py", line 28, in <module>
>     from django.core.urlresolvers import reverse
> ModuleNotFoundError: No module named 'django.core.urlresolvers'
> ```
> 
> Also by rebuilding you mean, running `./install.sh` again? Because I don't see the error you've pasted in your original post in log you've pasted.

docker-compose down
docker-compose rebuild

**Comment by aminvakil** [comment]
> docker-compose down docker-compose rebuild

We don't have a `docker-compose rebuild` command.

**Comment by feeops** [comment]
> docker-compose rebuild

I am sorry.It is 

```bash
docker-compose down
docker-compose build
```

**Comment by aminvakil** [comment]
You shouldn't run `docker-compose build` as `./install.sh` takes care of couple stuff before executing `docker-compose build` in of many steps and stuff it gets done.

You only need `./install.sh` and `docker-compose up -d` afterwards.

**Comment by feeops** [comment]
ok,thanks

**Comment by JosonJiang** [comment]
`docker-compose build


[+] Building 0.8s (19/25)
 => [sentry-cleanup-self-hosted-local internal] load build definition from Dockerfile                                                                                                   0.0s
 => => transferring dockerfile: 32B                                                                                                                                                     0.0s
 => [symbolicator-cleanup-self-hosted-local internal] load build definition from Dockerfile                                                                                             0.0s
 => => transferring dockerfile: 32B                                                                                                                                                     0.0s
 => [snuba-cleanup-self-hosted-local internal] load build definition from Dockerfile                                                                                                    0.0s
 => => transferring dockerfile: 32B                                                                                                                                                     0.0s
 => [clickhouse-self-hosted-local internal] load build definition from Dockerfile                                                                                                       0.0s
 => => transferring dockerfile: 31B                                                                                                                                                     0.0s
 => [sentry-self-hosted-local internal] load build definition from Dockerfile                                                                                                           0.0s
 => => transferring dockerfile: 32B                                                                                                                                                     0.0s
 => [sentry-cleanup-self-hosted-local internal] load .dockerignore                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                                                         0.0s
 => [symbolicator-cleanup-self-hosted-local internal] load .dockerignore                                                                                                                0.0s
 => => transferring context: 2B                                                                                                                                                         0.0s
 => [snuba-cleanup-self-hosted-local internal] load .dockerignore                                                                                                                       0.0s
 => => transferring context: 2B                                                                                                                                                         0.0s
 => [clickhouse-self-hosted-local internal] load .dockerignore                                                                                                                          0.0s
 => => transferring context: 2B                                                                                                                                                         0.0s
 => [sentry-self-hosted-local internal] load .dockerignore                                                                                                                              0.0s
 => => transferring context: 2B                                                                                                                                                         0.0s
 => CANCELED [sentry-cleanup-self-hosted-local internal] load metadata for docker.io/library/sentry-self-hosted-local:latest                                                            0.1s
 => [symbolicator-cleanup-self-hosted-local internal] load metadata for docker.io/getsentry/symbolicator:nightly                                                                        0.0s
 => [symbolicator-cleanup-self-hosted-local 1/5] FROM docker.io/getsentry/symbolicator:nightly                                                                                          0.0s
 => [symbolicator-cleanup-self-hosted-local internal] load build context                                                                                                                0.0s
 => => transferring context: 35B                                                                                                                                                        0.0s
 => CACHED [symbolicator-cleanup-self-hosted-local 2/5] RUN if [ -z "${http_proxy}" ]; then echo "Acquire::http::proxy "${http_proxy}";" >> /etc/apt/apt.conf; fi                       0.0s
 => CANCELED [symbolicator-cleanup-self-hosted-local 3/5] RUN if [ -z "${https_proxy}" ]; then echo "Acquire::https::proxy "${https_proxy}";" >> /etc/apt/apt.conf; fi                  0.5s
 => [snuba-cleanup-self-hosted-local internal] load metadata for docker.io/getsentry/snuba:nightly                                                                                      0.0s
 => CACHED [snuba-cleanup-self-hosted-local 1/5] FROM docker.io/getsentry/snuba:nightly                                                                                                 0.0s
 => CANCELED [snuba-cleanup-self-hosted-local internal] load build context                                                                                                              0.0s
 => => transferring context:                                                                                                                                                            0.5s
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: base name (${BASE_IMAGE}) should not be blank`

**Comment by aminvakil** [comment]
@JosonJiang https://github.com/getsentry/self-hosted/issues/1608#issuecomment-1203841490
