### ISSUE TITLE
Bump default Postgres from 9.6 to 14

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/self-hosted#1610]
I learned last week that we've completed the Postgres upgrade for SaaS from 9.6 the whole way to 14. Time to bump the default version in self-hosted to match. What docs do we need? What are the upgrade steps besides what we already have? What other considerations exist?

To be clear, people are successfully running Self-hosted Sentry on Postgres 14 (see https://github.com/getsentry/self-hosted/issues/1097 for details). This ticket is about changing the default in the repo, and I guess documenting the upgrade steps. Even when we switch the default we'll almost certainly leave it to you to manually upgrade older installations. I believe in the past we've tried to automate Postgres upgrades, that feels risky to me and I'm inclined to not take that on again.

**Comment by aminvakil** [comment]
Let's have this here https://github.com/tianon/docker-postgres-upgrade/tree/master/9.6-to-14, we may need it.

**Comment by chadwhitacre** [comment]
Back to gosu after all. :P

**Comment by chadwhitacre** [comment]
FYI we'll be doing something similar in the [local dev env](https://develop.sentry.dev/environment/), cc: @beezz to coordinate as it makes sense.

**Comment by beezz** [comment]
fyi: Just opened a PR with an upgrade script https://github.com/getsentry/sentry/pull/38733

**Comment by chadwhitacre** [comment]
Thanks @beezz. Will this script live in the `sentry` repo forever, or will it be removed at some predictable point down the line, or ... ?

@ethanhs @hubertdeng123 Can we look over the script and see if it will work for self-hosted as well?

My thinking is that if it will be suitable for self-hosted and at a stable URL then we can link to it from our self-hosted docs, etc. as the recommended path for upgrading.

I'm inclined to say that the db upgrade should be manual rather than trying to make it automatic in the install.sh script. What does everyone think?

**Comment by ethanhs** [comment]
> I'm inclined to say that the db upgrade should be manual rather than trying to make it automatic in the install.sh script. What does everyone think?

Yeah I think we may want to ask people to do the upgrade manually.

**Comment by beezz** [comment]
> Will this script live in the `sentry` repo forever, or will it be removed at some predictable point down the line, or ... ?

I would like to remove it a few weeks after pg 14 becomes the default dev environment version.

**Comment by chadwhitacre** [comment]
> I would like to remove it a few weeks after pg 14 becomes the default dev environment version.

Okay, in that case @ethanhs @hubertdeng123 let's plan to maintain our own version of it as we will want to keep that around longer (a year or two? forever? move it to a gist after a while?)

**Comment by hubertdeng123** [comment]
Yep, that's what I was thinking. We should provide users the script to upgrade for a bit longer

**Comment by roock** [comment]
FWIW Upgrading to PostgreSQL 14 requires updated wal2json PostgreSQL extension in https://github.com/getsentry/wal2json

**Comment by patsevanton** [comment]
The final release for PostgreSQL 9.6 is slated for November 11th, 2021. https://www.postgresql.org/support/versioning/
How i can

PR https://github.com/getsentry/sentry/pull/38733 is closed.
Any news about migration to new Postgresql ?

**Comment by chadwhitacre** [comment]
I've added this to https://github.com/getsentry/team-ospo/issues/64, maybe we can prioritize this next quarter.

**Comment by patsevanton** [comment]
I can test you alfa version Sentry with new PostgreSQL.

**Comment by meotimdihia** [comment]
Please do it soon. The server storage was full.

**Comment by chadwhitacre** [comment]
I've updated the ticket description to reflect that you should go upgrade. Anyone have a good write-up on steps for this? Let's collect some collective wisdom and put it in the docs.

**Comment by BYK** [comment]
>I believe in the past we've tried to automate Postgres upgrades, that feels risky to me and I'm inclined to not take that on again.

It was not risky and it worked out quite well. I'd say it is the responsibility of this repo to provide smooth upgrades once the default becomes 14. [This section in self-hosted docs](https://develop.sentry.dev/self-hosted/releases/#hard-stops) implicitly says that upgrades should be care-free unless you are skipping over a "hard-stop".

**Comment by chadwhitacre** [comment]
Just posted internally by @beezz re: dev sentry:

> The time has finally come. Next week we are upgrading the PostgreSQL version in the development environment and CI from 9.6 to 14.
> 
> If you want to start using PostgreSQL version 14 right now and don't need to keep any data, do the following:
> 
> ```
> $ docker stop sentry_postgres; docker rm sentry_postgres && docker volume rm sentry_postgres
> $ export PG_VERSION=14
> $ sentry devservices up postgres
> $ make reset-db
> ```
> 
> If you want to keep data, use the migration script from sentry repo:
> 
> ```
> ./scripts/upgrade-postgres.sh
> ```
> 
> In both cases, save the `export PG_VERSION=14` in your shell configuration file so that the next time you run `sentry devservices`, the correct PostgreSQL is used.
> 
> Why are we doing it?
> 
> There are multiple reasons.
> 
> - PostgreSQL version 9.6 support ended on 11 Nov 2021, meaning we are currently developing against an unmaintained version.
> - In SaaS production, we have been running all our clusters on version 14 for some time now.
> - The upgrade allows us to use new shiny features like native logical replication, table partitioning, and more.

**Comment by hubertdeng123** [comment]
We should be able to copy the upgrade script to our scripts in self-hosted and it should just work. I attempted to do that successfully a while back. I'd imagine we'd want to bump the default Postgres version here soon since starting next week PG 14 will be used everywhere.

**Comment by hubertdeng123** [comment]
It would be super similar to the script here:
https://github.com/getsentry/self-hosted/blob/1920b23d7d0beb552bdfaa8eb17f53af2ab6971b/install/upgrade-postgres.sh

But with 9.6 -> 14
```
if [[ -n "$(docker volume ls -q --filter name=sentry-postgres)" && "$(docker run --rm -v sentry-postgres:/db busybox cat /db/PG_VERSION 2>/dev/null)" == "9.6" ]]; then
  docker volume rm sentry-postgres-new || true
  # If this is Postgres 9.6 data, start upgrading it to 14 in a new volume
  docker run --rm \
  -v sentry-postgres:/var/lib/postgresql/9.6/data \
  -v sentry-postgres-new:/var/lib/postgresql/14/data \
  tianon/postgres-upgrade:9.6-to-14
```

We can delete this upgrade script after, since the script will always run for the version we declare as the hard-stop. @BYK does that sound similar to the way it was handled in the past?

**Comment by hubertdeng123** [comment]
Although it looks like we deleted those scripts a while after declaring certain versions as hard stops in the past 😅https://github.com/getsentry/self-hosted/issues/1705

**Comment by BYK** [comment]
@hubertdeng123 yup, you'll just revive [this script](https://github.com/getsentry/self-hosted/pull/1710/files#diff-d5dbeb45062bd0425b95bf710ab4128bf099a566b2624fd58e13e8bd593a5bdf) but for 9.6->14.

It even has the version check built-in so it shoult "just work™" 😅

**Comment by chadwhitacre** [comment]
[Last I heard](https://github.com/getsentry/self-hosted/issues/1097#issuecomment-999160152), Sentry should function fine without `wal2json`. I'm checking internally to see if this is still true.

**Comment by hubertdeng123** [comment]
FWIW I tested the upgrade on a branch in self-hosted yesterday, seemed to work fine

**Comment by beezz** [comment]
> To everyone running Postgresql 14: How are you integrating the wal2json extension? The current version uses seems not compatible with postgres 14 afaik. Is the wal2json functionality even already used inside Sentry?

The wal2json extension works with pg14 just fine. Are you running into some problems?

**Comment by roock** [comment]
@beezz I haven't tried running Sentry with Postgres 14 (or any newer version than the default version yet).

When I investigated in this issue a few months ago, I found some commits in the wal2json upstream repository (which are not present in the sentry fork) that would suggest that the Sentry fork is not ready yet for newer Postgresql versions. I wasn't able to find those commits again today.

**Comment by hubertdeng123** [comment]
put up a PR for this! 

@BYK if you could take a look at it 🙏

**Comment by chadwhitacre** [comment]
Woo-hoo! Let's make sure we put something in the release notes ... seeing we already have it on the todo for https://github.com/getsentry/self-hosted/issues/2033. 😁

**Comment by BYK** [comment]
>Let's make sure we put something in the release notes

Great excuse to use milestones so it shows up nicely? 😉

**Comment by hubertdeng123** [comment]
The milestones [here](https://github.com/getsentry/self-hosted/milestones?state=open)? Tried to find examples of previous milestones showing up nicely in our release notes but not seeing it

**Comment by chadwhitacre** [comment]
https://github.com/getsentry/craft#changelog-policies :)

**Comment by BYK** [comment]
@hubertdeng123 try this one: https://github.com/getsentry/sentry/milestones?state=open

Or this: https://github.com/getsentry/craft/milestones?state=closed

It will look like this once you use them: https://github.com/getsentry/craft/releases/tag/0.25.0 (but even better as we added "authors" after that release)

**Comment by hubertdeng123** [comment]
Created the milestone, will look out for that when running the release Monday :)

**Comment by hubertdeng123** [comment]
Milestone here: https://github.com/getsentry/self-hosted/milestone/11

**Comment by webmozart** [comment]
My upgrade just failed with a "loadable libraries" error. Anyone had this?

```
Digest: sha256:8edb60c8322d1eea0f59f2a33292dba0d00c8b1e6b448ee655c3712720e4a722
Status: Downloaded newer image for tianon/postgres-upgrade:9.6-to-14
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/14/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok


Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/14/data -l logfile start

initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.
Performing Consistency Checks
-----------------------------
Checking cluster versions                                   ok
Checking database user is the install user                  ok
Checking database connection settings                       ok
Checking for prepared transactions                          ok
Checking for system-defined composite types in user tables  ok
Checking for reg* data types in user tables                 ok
Checking for contrib/isn with bigint-passing mismatch       ok
Checking for user-defined encoding conversions              ok
Checking for user-defined postfix operators                 ok
Checking for incompatible polymorphic functions             ok
Checking for tables WITH OIDS                               ok
Checking for invalid "sql_identifier" user columns          ok
Checking for invalid "unknown" user columns                 ok
Creating dump of global objects                             ok
Creating dump of database schemas
  postgres
  template1
                                                            ok
Checking for presence of required libraries                 fatal

Your installation references loadable libraries that are missing from the
new installation.  You can add these libraries to the new installation,
or remove the functions using them from the old installation.  A list of
problem libraries is in the file:
    loadable_libraries.txt

Failure, exiting
Error in install/upgrade-postgres.sh:6.
'docker run --rm -v sentry-postgres:/var/lib/postgresql/9.6/data -v sentry-postgres-new:/var/lib/postgresql/14/data tianon/postgres-upgrade:9.6-to-14' exited with status 1
-> ./install.sh:main:33
--> install/upgrade-postgres.sh:source:6

Envelope from file sentry-envelope-28240e265a53ec23ee16275c9656b850 dispatched
Cleaning up...
```

**Comment by chadwhitacre** [comment]
@webmozart Thanks for reporting. What's the contents of `loadable_libraries.txt`?

**Comment by hubertdeng123** [comment]
Also found [this](https://www.percona.com/blog/missing-library-a-pg_upgrade-history/), perhaps helpful here?

**Comment by webmozart** [comment]
> @webmozart Thanks for reporting. What's the contents of `loadable_libraries.txt`?

Couldn't figure out yet where to find that file. Still searching for it.

**Comment by webmozart** [comment]
Found a solution, but it's probably specific to my problem. Maybe it still helps anyone.

1. Change the version of your `postgres` container back from `14.5` to `9.6` in `docker-compose.yml`
2. Boot the container: `docker-compose up -d postgres`
3. Log into the container: `docker-compose exec --user=0 postgres bash`
4. Start psql: `su postgres` and `psql`
5. Check that the extension is found: `\dx`
6. Drop it: `drop extension pg_repack cascade;`
7. Exit psql and the container and revert the changes from step 1
8. Re-run `install.sh`

One thing I noted in the output was the following:

```
Your installation contains extensions that should be updated
with the ALTER EXTENSION command.  The file
    update_extensions.sql
when executed by psql by the database superuser will update
these extensions.
```

The file contained the following SQL statements, which I executed in my instance just in case (see steps 3 and 4):

```
ALTER EXTENSION "citext" UPDATE;
```

To clean up, revert the changes in `install/upgrade-postgres.sh` and remove `/home/ubuntu/onpremise/tmp-var-lib-postgresql` again (for both see my previous comment).

**Comment by chadwhitacre** [comment]
Thanks for sharing! Hopefully it's helpful to others who are using `pg_repack`. If there's enough folks in this boat we can consider improving the update script, even if only to give a better error message.

**Comment by hubertdeng123** [comment]
Going to close this as this is now released in [23.4.0](https://github.com/getsentry/self-hosted/releases/tag/23.4.0)

**Comment by dcd-arnold** [comment]
This was an issue with our instance, as well. Thanks to @webmozart we were able to fix it following: https://github.com/getsentry/self-hosted/issues/1610#issuecomment-1511716317

**Comment by Omeryl** [comment]
This resulted in a failure here, as well.

**Comment by hubertdeng123** [comment]
@dcd-arnold @Omeryl Would you be able to elaborate more on the issues you are experiencing?

**Comment by Omeryl** [comment]
@hubertdeng123 hit the exact same one as @webmozart above, however after following his instructions I ended up just getting a Postgres that refused to boot. I ended up just starting from scratch, and will keep a backup.json around going forward.

**Comment by hubertdeng123** [comment]
ah gotcha, thanks for the data point

**Comment by dcd-arnold** [comment]
@hubertdeng123 We got the same issue, as @webmozart [here](https://github.com/getsentry/self-hosted/issues/1610#issuecomment-1511716317). This is due because we hat to follow the [troubleshooting guide for prostgres](https://develop.sentry.dev/self-hosted/troubleshooting/#postgres) at some point. Hence, `pg_repack` was still installed in our instance.

**Comment by BYK** [comment]
@dcd-arnold are you sure you used the exact script there? Because it uses `docker-compose run` which creates a new, ephemeral container. `pg_repack` would only linger around if you used `docker-exec instead`.

**Comment by elpito** [comment]
Hi,
I had exactly the same problem like @webmozart, after removing the extension in 9.6 PG version, I was able to do the upgrade to version 14 of PG. I'm quite sure, we never installed this extension by our selves.
