### ISSUE TITLE
How to re-execute entrypoint.sh

### ISSUE THREAD

**Issue by chengandpeng** [getsentry/self-hosted#1639]
### Self-Hosted Version

22.3.0

### CPU Architecture

x86_64

### Docker Version

19.03.8

### Docker Compose Version

1.28.4

### Steps to Reproduce

add following line in sentry/entrypoint.sh and xxx folder.
```
pip install --user /etc/sentry/xxx/ --no-cache-dir
```
I have installed xxx package succeed. Then I wanted to upgrade this local package by following step.

1. docker-compose down
2. docker-compose build --no-cache
3. docker-compose up -d

### Expected Result

I modified sentry/entrypoint.sh (to upgrade a local package by pip install),  and down,  build docker without cache .

### Actual Result

When I up the docker，the package wasn't upgraded by expected. And it seems entrypoint.sh wasn't executed too.
How can I re-execute entrypoint.sh without clear all data?

**Comment by aminvakil** [comment]
This may be a bug with docker-compose `1.28.4`, I've just tested v2.9.0 and it worked fine.

**Comment by aminvakil** [comment]
Also, although it has been changed since `22.6.0`, you can add packages you want to install in https://github.com/getsentry/self-hosted/blob/22.3.0/sentry/requirements.example.txt .

**Comment by ethanhs** [comment]
Also, you should re-run `install.sh` instead of manually running `docker-compose build`. The install script also handles upgrading, so it should handle this as well.

**Comment by chengandpeng** [comment]
> Also, you should re-run `install.sh` instead of manually running `docker-compose build`. The install script also handles upgrading, so it should handle this as well.

@ethanhs @aminvakil thanks for your advices.
```install.sh```  looks use docker cache, so I run ```docker-compose build --no-cache``` manually.

Why I use ```entrypoints.sh``` instead of  ```requirements.txt```  is I need install a local package.
And now I can confirm that  ``` pip install --user /etc/sentry/my_local_package/ --no-cache-dir``` command which I added in  ```entrypoints.sh``` was been executed. 

Which I confused is when I change my local package's source code. The new version wasn't installed after rebuild the docker.

**Comment by aminvakil** [comment]
> But which I confused is when I change my local package's source code. The new version wasn't installed after rebuild the docker. So how can I upgrade my local package ?

`./install.sh` :)

You can change `install/build-docker-images.sh` and add `--no-cache` to it, therefore you can run `./install.sh` and have `docker-compose build --no-cache` too.

Also since 22.6.0, self-hosted has a `enhance-image.sh` which you can add your scripts to it instead of changing `entrypoint.sh`.

**Comment by chengandpeng** [comment]
> > But which I confused is when I change my local package's source code. The new version wasn't installed after rebuild the docker. So how can I upgrade my local package ?
> 
> `./install.sh` :)
> 
> You can change `install/build-docker-images.sh` and add `--no-cache` to it, therefore you can run `./install.sh` and have `docker-compose build --no-cache` too.
> 
> Also since 22.6.0, self-hosted has a `enhance-image.sh` which you can add your scripts to it instead of changing `entrypoint.sh`.

I have given up installing plugin by local package.  :( 
Instead, I uploaded it to pypi and installed by ```requirements.txt```  since I'm using 22.3.0 and not going to upgrade now.
Any way thanks for help.
