### ISSUE TITLE
No arm support for relay image

### ISSUE THREAD

**Issue by jellevanhees** [getsentry/self-hosted#1642]
### Self-Hosted Version

22.7.0

### CPU Architecture

arm64

### Docker Version

20.10.17

### Docker Compose Version

2.6.0

### Steps to Reproduce

running install.sh erros out with the following error.
```
▶ Ensuring Relay credentials ...
../relay/config.yml already exists, skipped creation.
relay Pulling 
relay Pulled 
Network sentry-self-hosted_default  Creating
Network sentry-self-hosted_default  Created
exec /bin/bash: exec format error
An error occurred, caught SIGERR on line 29
Cleaning up...
```

running` docker compose run --rm --no-deps -T relay credentials`  results in 
```
exec /bin/bash: exec format error 
```

running `docker run -it --rm getsentry/relay bash` results in
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
exec /bin/bash: exec format error
```

### Expected Result

getsentry/replay and other sentry images are built with arm support.

### Actual Result

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
exec /bin/bash: exec format error
```

**Comment by ethanhs** [comment]
I think we'd rather have a single issue for self-hosted tracking this: https://github.com/getsentry/self-hosted/issues/1585
