### ISSUE TITLE
How to change the volume in docker-compose file

### ISSUE THREAD

**Issue by darkfallen777** [getsentry/self-hosted#1643]
### Self-Hosted Version

22.8.0.dev0

### CPU Architecture

x86_64

### Docker Version

20.10.17

### Docker Compose Version

1.29.2

### Steps to Reproduce

How do I change the volume

### Expected Result

ERROR: for snuba-sessions-consumer  Container "058f0a819e65" is unhealthy.

ERROR: for snuba-replacer  Container "058f0a819e65" is unhealthy.

ERROR: for snuba-subscription-consumer-events  Container "058f0a819e65" is unhealthy.

ERROR: for snuba-transactions-consumer  Container "058f0a819e65" is unhealthy.

ERROR: for snuba-consumer  Container "058f0a819e65" is unhealthy.

ERROR: for snuba-transactions-cleanup  Container "058f0a819e65" is unhealthy.

ERROR: for snuba-cleanup  Container "058f0a819e65" is unhealthy.

ERROR: for snuba-outcomes-consumer  Container "058f0a819e65" is unhealthy.

ERROR: for snuba-api  Container "058f0a819e65" is unhealthy.

ERROR: for snuba-subscription-consumer-transactions  Container "058f0a819e65" is unhealthy.
ERROR: Encountered errors while bringing up the project.

### Actual Result

can i change volume

**Comment by ethanhs** [comment]
Hi, what did you try that lead to these errors?

**Comment by darkfallen777** [comment]
I want to mask data from services, specify volume, when I specify folders for them, services in the docker compose does not come up

**Comment by ethanhs** [comment]
I can't help you solve your problem if you don't tell me what you tried. Could you please send a diff of your docker compose file?
