### ISSUE TITLE
Can not install Github Integration

### ISSUE THREAD

**Issue by meotimdihia** [getsentry/self-hosted#1648]
### Self-Hosted Version

22.8.0

### CPU Architecture

x86_64

### Docker Version

Docker version 20.10.14, build a224086

### Docker Compose Version

Docker version 20.10.14, build a224086

### Steps to Reproduce

I have the same error as this issue: 
https://github.com/getsentry/self-hosted/issues/1243

But with Github.

it always redirects 302 from:

`https://[custom-domain]/github/setup/?installation_id=28293064&setup_action=install`  ( or `https://[custom-domain]/github/setup/?installation_id=28291213&setup_action=update`)

redirect to 302

`https://[custom-domain]/auth/login/`

redirect 302 to 

`https://[custom-domain]/organizations/sentry/issues/`

I tried everything, it take more than 10 hours but I can't install it. 
There is no error or anything to see.

### Expected Result

It should be working.

### Actual Result

<img width="1325" alt="image" src="https://user-images.githubusercontent.com/300961/184830622-6a7dd6bf-369f-4e9f-b2d6-806ebce9d07b.png">

![image](https://user-images.githubusercontent.com/300961/184831167-071291d7-ea5d-449d-8a96-2de096e12b5f.png)

**Comment by ethanhs** [comment]
As Chad mentioned in the issue you linked to, this sounds like a permissions issue. Can you confirm the account you are doing this from is a Sentry org admin, manager, or owner? And your account is an org owner on the github side?

**Comment by ethanhs** [comment]
No, #1309 is a bug in our setup. I doubt it is related to this.

>  There is no error or anything to see.

Did you check the logs from compose? (`docker compose logs`) Or is this just talking about in the web UI?

**Comment by meotimdihia** [comment]
I don't see any warning or error logs: 

`sudo docker-compose logs -f web | grep 'github'` 
```
_1                                       | 01:43:24 [INFO] sentry.web.frontend.base: Active organization [github] not found
web_1                                       | 01:43:24 [INFO] sentry.web.frontend.base: Active organization [github] not found in scope
web_1                                       | 01:43:24 [INFO] sentry.web.frontend.base: Active organization [github] not found
web_1                                       | 01:43:24 [INFO] sentry.web.frontend.base: Active organization [github] not found in scope
web_1                                       | 01:43:24 [INFO] sentry.access.api: api.access (method='GET' view='sentry.web.frontend.react_page.ReactPageView' response=302 user_id='1' is_app='None' token_type='None' is_frontend_request='True' organization_id='None' auth_id='None' path='/github/setup/' caller_ip='xxxx:4803:eada:2170:8961:ad54:d90d:96a6' user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.01786971092224121 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
```

![image](https://user-images.githubusercontent.com/300961/185276729-240f8561-3638-4fe0-8abc-18e58c76fce9.png)

**Comment by meotimdihia** [comment]
Status: Backlog

**Comment by ethanhs** [comment]
Random thought: it looks like your domain is behind cloudflare? If it is proxied try turning that off? I have successfully set up the github integration before so I'm not sure why yours isn't working...

**Comment by rajivmucheli** [comment]
It’s not behind cloudflare, the same GitHub integrates with sentry v9.1.2,
are there any changes in v22.8.0 or above ?

**Comment by meotimdihia** [comment]
@ethanhs mine is behind Cloudflare.
But the problem is no error is reported in this case.

**Comment by meotimdihia** [comment]
I just have tried to turn off the Cloudflare proxy but it doesn't work too.

**Comment by ethanhs** [comment]
> It’s not behind cloudflare, the same GitHub integrates with sentry v9.1.2,
are there any changes in v22.8.0 or above ?

@rajivmucheli yeah the way we do Github integrations has changed IIRC, I would check these docs and make sure you've followed them https://develop.sentry.dev/integrations/github/

@meotimdihia hmm ok I'll keep thinking of what could be causing this.

**Comment by sentaur-athena** [comment]
I'm going to close this issue since it's stale on an old version of sentry. Setup docs have been updated since. Please feel free to open a new ticket if you're still experiencing an issue after upgrade.
