### ISSUE TITLE
No mails are sent, except the test mail

### ISSUE THREAD

**Issue by lukashoffmannhb** [getsentry/self-hosted#1649]
### Self-Hosted Version

22.8.0

### CPU Architecture

x86-64

### Docker Version

docker-ce=5:20.10.5

### Docker Compose Version

Kubernetes

### Steps to Reproduce

Whenever a mail is sent (e.g. to invite new users), no mail is sent to the corresponding mail address. I've checked the mail log of the mail server but no mails are sent to the mail server.
But the Sentry worker gives me the following log: 
`08:28:37 [INFO] sentry.mail: mail.sent (message_id='<20220816082836.9.55828@xxx.xx>' size=4923)`

The only mails that are working fine are the mails sent via the test mail function. 

Unfortunately I don't get more logs, I even set the SENTRY_LOG_LEVEL to DEBUG.

### Expected Result

Mails should be sent regardless of the function that triggers the mail.

### Actual Result

Only mails via test mail function are sent.

**Comment by ethanhs** [comment]
> no mail is sent to the corresponding mail address. I've checked the mail log of the mail server but no mails are sent to the mail server.

So the server doesn't even see any mail to block or drop? Could you set up another simple mail server and make sure it isn't a configuration issue with the receiving server or some network issue?

**Comment by lukashoffmannhb** [comment]
> > no mail is sent to the corresponding mail address. I've checked the mail log of the mail server but no mails are sent to the mail server.
> 
> So the server doesn't even see any mail to block or drop? Could you set up another simple mail server and make sure it isn't a configuration issue with the receiving server or some network issue?

Thanks for your answer.
I've tried another mail account by a different mail provider. It's still the same that only the test mail is sent. Every other mail isn't sent.

**Comment by lukashoffmannhb** [comment]
I just found out that I can send testmails also via "sentry django sendtestemail". When I use this function I get the following error:
`Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/redis.py", line 123, in setup_once
    _patch_rediscluster()
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/redis.py", line 88, in _patch_rediscluster
    pipeline_cls = rediscluster.ClusterPipeline
AttributeError: module 'rediscluster' has no attribute 'ClusterPipeline'
09:49:32 [ERROR] sentry_sdk.errors: Error occurred while patching `rediscluster` library`

Any idea on that?

**Comment by ethanhs** [comment]
Hm, can you check for errors in redis?

`docker compose logs redis`

**Comment by lukashoffmannhb** [comment]
Since I'm using Kubernetes, docker compose commands are not available to me. 
But I've checked the Kubernetes pod logs for Redis and there were no logs.

**Comment by ethanhs** [comment]
Sorry, we cannot officially support Kubernetes deployments, as there are too many variables. If you change to using the docker compose setup and run into this issue please open a new issue. Otherwise, I'd recommend seeking assistance from the community.
