### ISSUE TITLE
Using an external PostgreSQL database with SEntry....

### ISSUE THREAD

**Issue by ZXRobotum** [getsentry/self-hosted#1651]
### Self-Hosted Version

22.8.0

### CPU Architecture

x86_64

### Docker Version

20.10.17

### Docker Compose Version

2.7.0

### Steps to Reproduce

I would very much like to address my external database server instead of the internal database server under DOCKER, but unfortunately I cannot find the appropriate places to do this. 

How can I do this / set it up?

### Expected Result

It would be nice if the settings under "sentry/config....." were used in the install process and not ignored.

### Actual Result

I don't have any results to post here at the moment. Because I haven't yet figured out how to do it directly.

**Comment by aminvakil** [comment]
Changing `DATABASES` in `sentry/sentry.conf.py` should probably suffice if you use the same version as sentry does (9.6).
```
    "default": {
        "ENGINE": "sentry.db.postgres",
        "NAME": "sentry",
        "USER": "username",
        "PASSWORD": "password",
        "HOST": "postgres_hostname",
        "PORT": "port_number",
    }
}
```
Also take a look at https://github.com/getsentry/self-hosted/issues/957 .

**Comment by ZXRobotum** [comment]
Thank you very much and NO, I am not USING PostgreSQL 9.6 - I am using PostgreSQL 14 or above....
So, what is the best way for using it with PG_Version 14?

**Comment by ethanhs** [comment]
We do not support using postgres 14 yet we plan on upgrading things however https://github.com/getsentry/self-hosted/issues/1610

**Comment by ZXRobotum** [comment]
Thank you so much for your answer. I've create a new Server with several "OLD" Versions of PostgreSQL to manage S.Entry or other software - tools. And thank you for all your help; my instance is now running with external DB - Service.

Best regards


Z. Matthias
