### ISSUE TITLE
Postgresql - Version 14 instead 9.x

### ISSUE THREAD

**Issue by ZXRobotum** [getsentry/self-hosted#1652]
### Self-Hosted Version

22.8.0

### CPU Architecture

x86_64

### Docker Version

20.17.0

### Docker Compose Version

2.7.0

### Steps to Reproduce

Is it possible that in the file "compose.yml" I have these lines:

postgres:
    <<: *restart_policy
    image: "postgres:9.6"

to the following:

postgres:
    <<: *restart_policy
    image: "postgres:latest"

### Expected Result

I had tried that, but unfortunately it was not so easy...

### Actual Result

I have no ideas....

**Comment by aminvakil** [comment]
Some other tweaks should get done too, this issue has been reported before and you can follow it in https://github.com/getsentry/self-hosted/issues/1610 .
