### ISSUE TITLE
Sentry sends out "Bad Gateway" when using tunnel

### ISSUE THREAD

**Issue by lodybo** [getsentry/self-hosted#1659]
### Self-Hosted Version

Sentry 22.8.0.dev0

### CPU Architecture

x86_64

### Docker Version

20.10.17

### Docker Compose Version

1.25.0

### Steps to Reproduce

We have Sentry running without problems, but when I clone the example repo and run the [Next.js example](https://github.com/getsentry/examples/tree/master/tunneling/nextjs) against our locally hosted Sentry instance, we see that we're getting a 502 Bad Gateway error from our instance:
```html
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

I've tried the Next.js example with the DSN of a project that I have on Sentry.io and the tunnel connects with no problem, even sending errors correctly to Sentry.io. So I'm confident that the Next.js tunnel works, but the locally hosted Sentry instance doesn't seem to accept a tunnel.

### Expected Result

I'd expect the self-hosted Sentry instance to accept a tunnel connection to https://<our sentry host>/api/<project id>/envelope.

### Actual Result

This is the code from `/api/tunnel.js`. Some tweaks to the example code was needed to fix errors, but the code below works against Sentry.io:

```javascript
const sentryHost = "sentry.mycompany.nl";

// Set knownProjectIds to an array with your Sentry project IDs which you
// want to accept through this proxy.
const knownProjectIds = [
  '/3', // taken from 'https://<public key>@sentry.mycompany.nl/3'
];

async function handler(req, res) {
  try {
    const envelope = req.body;
    const pieces = envelope.split("\n");

    const header = JSON.parse(pieces[0]);

    const { host, path } = url.parse(header.dsn);
    if (host !== sentryHost) {
      throw new Error(`invalid host: ${host}`);
    }

    const projectId = path.endsWith("/") ? path.slice(0, -1) : path;
    if (!knownProjectIds.includes(projectId)) {
      throw new Error(`invalid project id: ${projectId}`);
    }

    const apiUrl = `https://${sentryHost}/api${projectId}/envelope/`;
    const response = await fetch(apiUrl, {
      method: "POST",
      body: envelope,
    });

    if (response.headers.get('content-type') !== 'application/json') {
      // This is for when we receive the "502 Bad Gateway" response, which is a web page.
      const txt = await response.text();
      console.log(txt);
      return res.status(response.status).json(JSON.stringify(txt));
    }

    const json = await response.json();
    return res.status(200).json(json);
  } catch (e) {
    captureException(e);
    console.error(e);
    return res.status(400).json({ status: "invalid request" });
  }
}
```

Our Next.js server logs this:
```sh
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

I logged the NGINX Sentry container and it doesn't show anything. It seems the 502 error appears before Sentry is reached?

**Comment by ethanhs** [comment]
Does the host you are running Sentry on have nginx running? If it isn't showing up in sentry's nginx container I am guessing it has to come from outside of the docker stack.

**Comment by lodybo** [comment]
Hi @ethanhs, thanks for responding. When I run `docker ps` on our server, I can see the NGINX container for Sentry running (`sentry-self-hosted-1`, version 1.22.0-alpine).

**Comment by aminvakil** [comment]
> Hi @ethanhs, thanks for responding. When I run `docker ps` on our server, I can see the NGINX container for Sentry running (`sentry-self-hosted-1`, version 1.22.0-alpine).

I guess what @ethanhs means is see if there is any log in `nginx` container which indicates if it's getting used or not.

**Comment by lodybo** [comment]
@aminvakil Ah I get it! If I open the logs, I can see it getting used when I hit the UI in my browser. However, the calls from the tunnel do not reach the log, so it looks like the `https://${sentryHost}/api${projectId}/envelope/` is not being hit.

**Comment by lodybo** [comment]
The problem seems to be solved at my end. It seems that the Sentry server had another NGINX proxy running that was missing an entry in its configuration. It passed almost every request to Sentry, _except_ ones starting with `/api/`, so debugging it was pretty difficult.

But our first logged error is visible in Sentry. Thanks for helping out.

**Comment by ethanhs** [comment]
Glad you figured it out!
