### ISSUE TITLE
[Errno 111] Connection refused when sending mail

### ISSUE THREAD

**Issue by csrlsm** [getsentry/self-hosted#1661]
### Self-Hosted Version

22.1.0

### CPU Architecture

x86_64

### Docker Version

20.10.17

### Docker Compose Version

1.29.2

### Steps to Reproduce

1. set up .env file with : SENTRY_MAIL_HOST=smtp.partner.outlook.cn
2. config sentry/config.yml as : 
![image](https://user-images.githubusercontent.com/18453523/185878822-0fe362fb-1d99-4c9a-80e9-00b2a553479c.png)

3. recreate container with "docker-compose down && docker-compose up -d"
4. using curl and can return normal result 
5. 
![image](https://user-images.githubusercontent.com/18453523/185879890-84632aee-0d40-4379-95d4-faab979f482a.png)

### Expected Result

can get mail result

### Actual Result

return Error 111 connection refused，and the nginx_log return 500 error "POST /api/0/internal/mail/ HTTP/1.1" 500"
![image](https://user-images.githubusercontent.com/18453523/185879138-d98685a6-16e8-4226-9228-ec7d110a7a3f.png)

**Comment by ethanhs** [comment]
Hi, could you please check the output of the web and worker containers for errors? e.g. `docker compose logs web`
