### ISSUE TITLE
Unable to fetch commits (sentry self-hosted + gitlab.com)

### ISSUE THREAD

**Issue by e-jjj** [getsentry/self-hosted#1662]
### Self-Hosted Version

21.6.1

### CPU Architecture

x86_64

### Docker Version

kubernetes 1.21

### Docker Compose Version

kubernetes 1.21

### Steps to Reproduce

1. Create a gitlab integration in sentry (within settings, select integrations and new installation) 
2. Enter the client key and secret from the gitlab user (with apin
3. Add a repository
4. Deploy an application in gitlab and ensure commit data and release information is shown within the corresponding sentry release or issue
5. Commits data does not show

Followed the steps in this document to set up release automation  and commits

https://docs.sentry.io/product/releases/setup/release-automation/ 

### Expected Result

Expect to see the commit data upon commit/ merge request from gitlab in sentry 

### Actual Result

Commits is not showing any data

<img width="591" alt="Screen Shot 2022-08-22 at 11 13 19 pm" src="https://user-images.githubusercontent.com/22207113/185929780-82c96ab3-c19f-4467-a7f9-636d37a43898.png">

**Comment by ethanhs** [comment]
Hi, could you check the logs e.g. `docker compose logs` and see if you notice any errors?

**Comment by e-jjj** [comment]
@ethanhs I'm running sentry in kubernetes, the sentry worker logs show the following when the requests are sent from gitlab. 

```
00:32:15 [INFO] sentry.integrations.client: integration.http_response (integration='slack' status_string='200')
```

The requests in gitlab get a 204 response, which tells me the commit data is being sent from gitlab but for some reason not displayed in sentry.

**Comment by ethanhs** [comment]
Oh hah, I missed that. Unfortunately we don't support Sentry running in Kubernetes, there are too many variables and we want to keep the setup simple so we use docker compose for the official installer. If you are able to reproduce the issue with the docker compose setup please let me know.
