### ISSUE TITLE
Skip ahead in the issue processing

### ISSUE THREAD

**Issue by bjonord** [getsentry/self-hosted#1663]
### Self-Hosted Version

22.7.0

### CPU Architecture

x86_64

### Docker Version

19.03.14

### Docker Compose Version

v2.7.0

### Steps to Reproduce

One of our services went down and started reporting 100,000s of errors and sentry is unable to process the errors fast enough, seeing as they are all the same, we would like to skip ahead to the latest errors or to a certain timestamp(if possible).

What would be the best approach to achieve this?

### Expected Result

Not having to process all of the queued up errors.

### Actual Result

We have to wait for sentry to catch up.

**Comment by hubertdeng123** [comment]
Unfortunately, this is something that we don't support 😕. Is the issue here entirely latency related due to the large amount of errors coming in?

**Comment by hubertdeng123** [comment]
Going to close this out as this is not something we are looking to support

**Comment by aminvakil** [comment]
Not sure if you could use this method or not, but in our environment we won't miss much if we lose 30 minutes of our sentry data.

So in some circumstances, I just put a `return 200;` at our loadbalancer, so it will not reach our sentry as upstream of loadbalancer and sentry sdks won't try again :) (If they hit a 502, 503 or something like that, they will try again multiple times)
