### ISSUE TITLE
Jira Server integration

### ISSUE THREAD

**Issue by horseBatteryStapler** [getsentry/self-hosted#1665]
### Self-Hosted Version

22.6.0

### CPU Architecture

x86_64

### Docker Version

-

### Docker Compose Version

-

### Steps to Reproduce

1. Install Sentry
2. Run Jira Server 8.22
3. Try to create an incoming/outgoing link on Jira Server and enable the "Jira Server" integration on Sentry

### Expected Result

Jira Server integration accepts client id+secret for oauth

### Actual Result

The existing Sentry Jira Server integration looks to be out of sync with Atlassian docs (we're on Jira Server 8.22, clustered)

Atlassian docs: 
- Incoming: https://confluence.atlassian.com/adminjiraserver0822/configure-an-incoming-link-1142237085.html
- Outgoing: https://confluence.atlassian.com/adminjiraserver0822/configure-an-outgoing-link-1142237084.html

Creating an incoming link on Jira only gives us a Client ID and Secret for OAuth:
![image](https://user-images.githubusercontent.com/110652384/186570878-a1468e61-5aae-4cec-bd5d-21bfa4a78600.png)

Whereas Sentry's Jira Server integration requires a consumer key + private key:
![image](https://user-images.githubusercontent.com/110652384/186570987-6f1c2d74-4ec8-41f2-b1c6-d4096eaf5193.png)

On the other hand, creating an outgoing link requires the following:
- Client ID
- Client Secret
- Scopes
- Authorization endpoint
- Token endpoint
- Redirect URL

For which I don't see any documentation on https://docs.sentry.io/product/integrations/issue-tracking/jira/#jira-server - is this something I need to create a separate Internal Integration (https://docs.sentry.io/product/integrations/integration-platform/internal-integration/) for?

So with regards to the Jira Server integration...

1. Should I be creating both incoming and outgoing links?
2. Is the SSH key approach documented on the Sentry website for a different version of Jira Server?
3. Am I doing the integration wrong?

**Comment by hubertdeng123** [comment]
Hey there! This looks like the Jira Server integration for OAuth 2.0. Is it possible to try the Jira Server integration for OAuth 1.0 located here?
https://confluence.atlassian.com/adminjiraserver0822/link-to-other-applications-1142237081.html

Seems like that method more aligns with the information in the sentry docs you linked.
