### ISSUE TITLE
Github Enterprise Auth needs a token instead of client-id/secret ?

### ISSUE THREAD

**Issue by rajivmucheli** [getsentry/self-hosted#1666]
### Self-Hosted Version

nightly

### CPU Architecture

x86_64

### Docker Version

20.10.17

### Docker Compose Version

k8s

### Steps to Reproduce

Hi,

Considering several steps required to migrate from v9.1.2 to the latest stable version i.e. nightly. I decided to uninstall v91.2 and install a fresh nightly version.

I had some success installing all new services apart Relay, i need some assistance enabling Github Auth (which was enabled by default in v9.1.2), i followed the steps mentioned [here](https://docs.sentry.io/product/integrations/source-code-mgmt/github/) but after clicking submit i get redirected to Sentry integration tab and see the installation is Not installed. Am i missing any steps or would i need to introduces these [config steps](https://github.com/sentry-kubernetes/charts/blob/develop/sentry/templates/configmap-sentry.yaml#L32-L53).

Also, do we need to install new services ? (its been 2 years since i upgraded my sentry version).

### Expected Result

Github Auth to show as enabled or integrated.

### Actual Result

Integration tab doesnt show Github Enterprise is activated after manually configuring these [steps](https://docs.sentry.io/product/integrations/source-code-mgmt/github/).

**Comment by rajivmucheli** [comment]
after updating the values of these 2 Sentry options :

SENTRY_OPTIONS['github-login.api-domain']
SENTRY_OPTIONS['github-login.base-domain']

i am redirected to my Github enterprise but i get this error now ;( 


`{
  "message": "Must authenticate to access this API.",
  "documentation_url": "https://docs.github.com/enterprise/3.3/rest"
}`

How do we authenticate via [token](https://docs.github.com/en/enterprise-server@3.3/rest/guides/getting-started-with-the-rest-api) to enable github auth in sentry ?

**Comment by ethanhs** [comment]
Hi, sorry but we don't support Kubernetes as a way of deploying self-hosted Sentry. I would recommend either raising an issue in the sentry-kubernetes repo or trying to set up a fresh nightly instance using docker-compose. If you do run into the same problem on self-hosted's docker-compose setup please open a new issue.
