### ISSUE TITLE
Temporary failure resolving 'deb.debian.org' when installing with ./install.sh

### ISSUE THREAD

**Issue by drmrbrewer** [getsentry/self-hosted#1667]
### Self-Hosted Version

22.8.0

### CPU Architecture

x86_64

### Docker Version

20.10.17

### Docker Compose Version

2.6.0

### Steps to Reproduce

    mkdir -p /root/sentry
    cd /root/sentry
    rm -fr self-hosted
    git clone https://github.com/getsentry/self-hosted.git
    cd self-hosted

    MY_NETWORK="my-overlay-network"
    cat << EOF >> docker-compose.yml
    networks:
      default:
        external: true
        name: ${MY_NETWORK}
    EOF

    sed -i "s/\${COMPOSE_PROJECT_NAME}_default/${MY_NETWORK}/g" ./install/wrap-up.sh 

    ./install.sh --skip-user-prompt

In the above, I'm specifying a network as per https://github.com/getsentry/self-hosted/issues/1302.

EDIT this issue seems to be unrelated to the use of a custom network as per above steps.  I get the same `failure resolving 'deb.debian.org'` errors with a very basic install:

    mkdir -p /root/sentry
    cd /root/sentry
    rm -fr self-hosted
    git clone https://github.com/getsentry/self-hosted.git
    cd self-hosted
    ./install.sh

### Expected Result

No errors.  It has worked up till now, though admittedly I haven't tried for a couple of months so various dependencies may have been updated since then.

### Actual Result

	▶ Parsing command line ...

	▶ Detecting Docker platform
	Detected Docker platform is linux/amd64

	▶ Initializing Docker Compose ...

	▶ Setting up error handling ...

	▶ Checking for latest commit ... 

	▶ Checking minimum requirements ...
	Found Docker version 20.10.17
	Found Docker Compose version 2.6.0

	▶ Turning things off ...
	Warning: No resource found to remove for project "sentry-self-hosted".
	Warning: No resource found to remove for project "sentry_onpremise".

	▶ Creating volumes for persistent storage ...
	Created sentry-clickhouse.
	Created sentry-data.
	Created sentry-kafka.
	Created sentry-postgres.
	Created sentry-redis.
	Created sentry-symbolicator.
	Created sentry-zookeeper.

	▶ Ensuring files from examples ...
	../sentry/sentry.conf.py already exists, skipped creation.
	../sentry/config.yml already exists, skipped creation.
	../symbolicator/config.yml already exists, skipped creation.

	▶ Ensuring Relay credentials ...
	../relay/config.yml already exists, skipped creation.
	../relay/credentials.json already exists, skipped creation.

	▶ Generating secret key ...

	▶ Replacing TSDB ...

	▶ Fetching and updating Docker images ...
	nightly: Pulling from getsentry/sentry
	Digest: sha256:0ea35f9157c0dfd69b737d2d1de75a544bb17c605b7f6dd1107680c7e3e163af
	Status: Image is up to date for getsentry/sentry:nightly
	docker.io/getsentry/sentry:nightly

	▶ Building and tagging Docker images ...

	#1 [internal] load build definition from Dockerfile
	#1 transferring dockerfile: 32B done
	#1 DONE 0.0s

	#2 [internal] load .dockerignore
	#2 transferring context: 2B done
	#2 DONE 0.0s

	#3 [internal] load metadata for docker.io/getsentry/sentry:nightly
	#3 DONE 0.0s

	#4 [1/4] FROM docker.io/getsentry/sentry:nightly
	#4 DONE 0.0s

	#5 [internal] load build context
	#5 transferring context: 297B done
	#5 DONE 0.0s

	#6 [3/4] RUN if [ -s /usr/src/sentry/enhance-image.sh ]; then     /usr/src/sentry/enhance-image.sh; fi
	#6 CACHED

	#7 [2/4] COPY . /usr/src/sentry
	#7 CACHED

	#8 [4/4] RUN if [ -s /usr/src/sentry/requirements.txt ]; then     echo "sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image";     pip install -r /usr/src/sentry/requirements.txt; fi
	#8 CACHED

	#9 exporting to image
	#9 exporting layers done
	#9 writing image sha256:2c9148498c31b184fb6fe48ca088dd595677daaa0369072b81205f0b223cd616 done
	#9 naming to docker.io/library/sentry-self-hosted-local done
	#9 DONE 0.0s
	#1 [sentry-cleanup-self-hosted-local internal] load build definition from Dockerfile
	#1 transferring dockerfile: 32B done
	#1 DONE 0.0s

	#2 [sentry-self-hosted-local internal] load build definition from Dockerfile
	#2 transferring dockerfile: 32B done
	#2 DONE 0.0s

	#3 [symbolicator-cleanup-self-hosted-local internal] load build definition from Dockerfile
	#3 transferring dockerfile: 32B done
	#3 DONE 0.0s

	#4 [clickhouse-self-hosted-local internal] load build definition from Dockerfile
	#4 transferring dockerfile: 31B done
	#4 DONE 0.0s

	#5 [snuba-cleanup-self-hosted-local internal] load build definition from Dockerfile
	#5 transferring dockerfile: 32B done
	#5 DONE 0.0s

	#6 [snuba-cleanup-self-hosted-local internal] load .dockerignore
	#6 transferring context: 2B done
	#6 DONE 0.0s

	#7 [sentry-cleanup-self-hosted-local internal] load .dockerignore
	#7 transferring context: 2B done
	#7 DONE 0.0s

	#8 [symbolicator-cleanup-self-hosted-local internal] load .dockerignore
	#8 transferring context: 2B done
	#8 DONE 0.0s

	#9 [clickhouse-self-hosted-local internal] load .dockerignore
	#9 transferring context: 2B done
	#9 DONE 0.0s

	#10 [sentry-self-hosted-local internal] load .dockerignore
	#10 transferring context: 2B done
	#10 DONE 0.0s

	#11 [sentry-cleanup-self-hosted-local internal] load metadata for docker.io/library/sentry-self-hosted-local:latest
	#11 DONE 0.0s

	#12 [sentry-cleanup-self-hosted-local 1/5] FROM docker.io/library/sentry-self-hosted-local
	#12 DONE 0.0s

	#13 [sentry-cleanup-self-hosted-local 2/5] RUN if [ -z "${http_proxy}" ]; then echo "Acquire::http::proxy "${http_proxy}";" >> /etc/apt/apt.conf; fi
	#13 CACHED

	#14 [sentry-cleanup-self-hosted-local internal] load build context
	#14 transferring context: 35B done
	#14 DONE 0.0s

	#15 [sentry-cleanup-self-hosted-local 3/5] RUN if [ -z "${https_proxy}" ]; then echo "Acquire::https::proxy "${https_proxy}";" >> /etc/apt/apt.conf; fi
	#15 ...

	#16 [symbolicator-cleanup-self-hosted-local internal] load metadata for docker.io/getsentry/symbolicator:nightly
	#16 DONE 0.0s

	#17 [symbolicator-cleanup-self-hosted-local 1/5] FROM docker.io/getsentry/symbolicator:nightly
	#17 DONE 0.0s

	#18 [sentry-self-hosted-local internal] load metadata for docker.io/getsentry/sentry:nightly
	#18 DONE 0.0s

	#19 [sentry-self-hosted-local 1/4] FROM docker.io/getsentry/sentry:nightly
	#19 DONE 0.0s

	#20 [snuba-cleanup-self-hosted-local internal] load metadata for docker.io/getsentry/snuba:nightly
	#20 DONE 0.0s

	#21 [sentry-self-hosted-local internal] load build context
	#21 transferring context: 297B done
	#21 DONE 0.0s

	#22 [sentry-self-hosted-local 2/4] COPY . /usr/src/sentry
	#22 CACHED

	#23 [sentry-self-hosted-local 3/4] RUN if [ -s /usr/src/sentry/enhance-image.sh ]; then     /usr/src/sentry/enhance-image.sh; fi
	#23 CACHED

	#24 [sentry-self-hosted-local 4/4] RUN if [ -s /usr/src/sentry/requirements.txt ]; then     echo "sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image";     pip install -r /usr/src/sentry/requirements.txt; fi
	#24 CACHED

	#25 [snuba-cleanup-self-hosted-local 1/5] FROM docker.io/getsentry/snuba:nightly
	#25 DONE 0.0s

	#26 [snuba-cleanup-self-hosted-local 2/5] RUN if [ -z "${http_proxy}" ]; then echo "Acquire::http::proxy "${http_proxy}";" >> /etc/apt/apt.conf; fi
	#26 CACHED

	#27 [snuba-cleanup-self-hosted-local 3/5] RUN if [ -z "${https_proxy}" ]; then echo "Acquire::https::proxy "${https_proxy}";" >> /etc/apt/apt.conf; fi
	#27 CACHED

	#28 [snuba-cleanup-self-hosted-local internal] load build context
	#28 transferring context: 35B done
	#28 DONE 0.0s

	#29 [symbolicator-cleanup-self-hosted-local 2/5] RUN if [ -z "${http_proxy}" ]; then echo "Acquire::http::proxy "${http_proxy}";" >> /etc/apt/apt.conf; fi
	#29 CACHED

	#30 [symbolicator-cleanup-self-hosted-local 3/5] RUN if [ -z "${https_proxy}" ]; then echo "Acquire::https::proxy "${https_proxy}";" >> /etc/apt/apt.conf; fi
	#30 CACHED

	#31 [symbolicator-cleanup-self-hosted-local internal] load build context
	#31 transferring context: 35B done
	#31 DONE 0.0s

	#32 [sentry-self-hosted-local] exporting to image
	#32 exporting layers done
	#32 writing image sha256:2c9148498c31b184fb6fe48ca088dd595677daaa0369072b81205f0b223cd616 done
	#32 naming to docker.io/library/sentry-self-hosted-local done
	#32 DONE 0.1s

	#33 [clickhouse-self-hosted-local internal] load metadata for docker.io/yandex/clickhouse-server:20.3.9.70
	#33 DONE 1.0s

	#34 [clickhouse-self-hosted-local 1/1] FROM docker.io/yandex/clickhouse-server:20.3.9.70@sha256:932ef73994dd4b6507a55a288c5ee065aae8e77e61ee569512a76a65eddbe2c3
	#34 DONE 0.0s

	#35 [symbolicator-cleanup-self-hosted-local 4/5] RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
	#35 ...

	#15 [sentry-cleanup-self-hosted-local 3/5] RUN if [ -z "${https_proxy}" ]; then echo "Acquire::https::proxy "${https_proxy}";" >> /etc/apt/apt.conf; fi
	#15 DONE 1.2s

	#34 [clickhouse-self-hosted-local 1/1] FROM docker.io/yandex/clickhouse-server:20.3.9.70@sha256:932ef73994dd4b6507a55a288c5ee065aae8e77e61ee569512a76a65eddbe2c3
	#34 resolve docker.io/yandex/clickhouse-server:20.3.9.70@sha256:932ef73994dd4b6507a55a288c5ee065aae8e77e61ee569512a76a65eddbe2c3 done
	#34 sha256:2910811b6c4227c2f42aaea9a3dd5f53b1d469f67e2cf7e601f631b119b61ff7 0B / 847B 0.1s
	#34 sha256:abe55fc6544d42937af1eccad0a639a039bded091b0972124d3069eba82089b8 7.93kB / 7.93kB done
	#34 sha256:23884877105a7ff84a910895cd044061a4561385ff6c36480ee080b76ec0e771 0B / 26.69MB 0.1s
	#34 sha256:932ef73994dd4b6507a55a288c5ee065aae8e77e61ee569512a76a65eddbe2c3 2.62kB / 2.62kB done
	#34 sha256:bc38caa0f5b94141276220daaf428892096e4afd24b05668cd188311e00a635f 0B / 35.37kB 0.1s
	#34 sha256:bc38caa0f5b94141276220daaf428892096e4afd24b05668cd188311e00a635f 35.37kB / 35.37kB 0.4s done
	#34 CANCELED

	#36 [snuba-cleanup-self-hosted-local 4/5] RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
	#0 1.169 Err:1 http://deb.debian.org/debian bullseye InRelease
	#0 1.169   Temporary failure resolving 'deb.debian.org'
	#0 1.171 Err:2 http://deb.debian.org/debian-security bullseye-security InRelease
	#0 1.171   Temporary failure resolving 'deb.debian.org'
	#0 1.171 Err:3 http://deb.debian.org/debian bullseye-updates InRelease
	#0 1.171   Temporary failure resolving 'deb.debian.org'
	#0 1.181 Reading package lists...
	#0 1.210 W: Failed to fetch http://deb.debian.org/debian/dists/bullseye/InRelease  Temporary failure resolving 'deb.debian.org'
	#0 1.210 W: Failed to fetch http://deb.debian.org/debian-security/dists/bullseye-security/InRelease  Temporary failure resolving 'deb.debian.org'
	#0 1.210 W: Failed to fetch http://deb.debian.org/debian/dists/bullseye-updates/InRelease  Temporary failure resolving 'deb.debian.org'
	#0 1.210 W: Some index files failed to download. They have been ignored, or old ones used instead.
	#0 1.223 Reading package lists...
	#0 1.238 Building dependency tree...
	#0 1.238 Reading state information...
	#0 1.250 E: Unable to locate package cron
	#36 ERROR: executor failed running [/bin/sh -c apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*]: exit code: 100

... and so on... lots of `Temporary failure resolving 'deb.debian.org'` etc.

Restarting Docker doesn't help (as suggested e.g. [here](https://stackoverflow.com/a/64053785/4070848)).

**Comment by ethanhs** [comment]
It seems that your setup has a network issue. Can you ping deb.debian.org from the host? Can you curl/wget http://deb.debian.org/debian/dists/bullseye/InRelease ? If not, your machine has a network issue you will need to resolve. Otherwise it is likely a network issue with your docker setup.

**Comment by drmrbrewer** [comment]
> Can you ping deb.debian.org from the host?
> Can you curl/wget http://deb.debian.org/debian/dists/bullseye/InRelease

Yes to both.

> Otherwise it is likely a network issue with your docker setup

Possibly, but I have many many other docker containers and services running without any problem, and they all access the network.  This wasn't this problem with the Sentry install a couple of months ago.

**Comment by ethanhs** [comment]
Are you using a network proxy?

**Comment by drmrbrewer** [comment]
Not knowingly.  I don't tinker with any network stuff... it's just a standard Ubuntu 18.04 installation with the latest Docker, and everything else seems to work just fine.

**Comment by aminvakil** [comment]
Can you run `docker run --rm debian:bullseye apt-get update` and paste output?

**Comment by drmrbrewer** [comment]
@aminvakil here you go:

	# docker run --rm debian:bullseye apt-get update
	Unable to find image 'debian:bullseye' locally
	bullseye: Pulling from library/debian
	1671565cc8df: Pull complete 
	Digest: sha256:d52921d97310d0bd48dab928548ef539d5c88c743165754c57cfad003031386c
	Status: Downloaded newer image for debian:bullseye
	Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
	Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
	Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
	Get:4 http://deb.debian.org/debian bullseye/main amd64 Packages [8182 kB]
	Get:5 http://deb.debian.org/debian-security bullseye-security/main amd64 Packages [180 kB]
	Get:6 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [2596 B]
	Fetched 8573 kB in 2s (4407 kB/s)
	Reading package lists...

**Comment by mschadev** [comment]
Turn off the firewall and try again. In my case, its worked

**Comment by drmrbrewer** [comment]
> Turn off the firewall and try again. In my case, its worked

    # ufw status
    Status: inactive

I have many docker services/containers running on this host, all of which require and use network without any issue.

**Comment by drmrbrewer** [comment]
I mentioned that I'm using a standard Ubuntu 18.04 installation.  I've now moved to using Ubuntu 22.04 and the self-hosted Sentry installation runs just fine... perhaps some conflict with the setup on Ubuntu 18.04?

**Comment by ethanhs** [comment]
I would be surprised but perhaps? Glad things are working, it could also be re-installing was what fixed it 🤷‍♂️

**Comment by drmrbrewer** [comment]
It wouldn't just be re installing that did it, because I spin up a new (cloud) server frequently, re installing everything including Sentry by script, and it remained broken until I moved up to Ubuntu 20.04.
