### ISSUE TITLE
Fresh install 22.8.0 with imported configs from same version missing "Next" and "Previous" buttons

### ISSUE THREAD

**Issue by connorwang** [getsentry/self-hosted#1668]
### Self-Hosted Version

22.8.0

### CPU Architecture

x86_64

### Docker Version

20.10.16

### Docker Compose Version

2.6

### Steps to Reproduce

Fresh install 22.8.0 with imported configs from same version (22.8.0). The "Next" and "Previous" buttons (bottom right) are missing - we can only see the first page issues (we have over 1,000 issues if you wonder).

Indeed a very weird bug.

### Expected Result

Buttons display correctly.

### Actual Result

Missing "Next" and "Previous" buttons

**Comment by ethanhs** [comment]
Hm, that is rather odd. Can you confirm that all of your issues are correctly copied over?

**Comment by connorwang** [comment]
> Hm, that is rather odd. Can you confirm that all of your issues are correctly copied over?

We didn't copy any events over - just configurations included in the backup json file. After some debugging here and there, I think the issues might be related to total issue count? Since it's supposed to show ## out of ### issues, so my guess would be one of those number is not present (the latter is more likely to be the case).

**Comment by ethanhs** [comment]
Sorry I'm not sure I understand, you didn't copy over events, but you did copy issues? If you didn't restore redis than I think that would break things.

**Comment by connorwang** [comment]
Sorry for the confusion - we followed this guide https://develop.sentry.dev/self-hosted/backup/ and did the following

1. Set up a new instance of Sentry
2. Backup the old instance (backup.json) 
3. Import the backup.json to the new instance

We didn't copy any issues over since we just wanted to migrate the configuration and let the events flow in.  After we ran the new instance briefly and received a few hundred events then we noticed it was missing the previous and next buttons.

We didn't restore redis :( Is there any way to fix that?

**Comment by hubertdeng123** [comment]
Ah, so just to confirm, a quick backup was made that didn't import over the issues. The configuration is pretty much all that you cared about, and new events started coming in again. After receiving a good number of events, you discovered that you were unable to view all of them since the `<` and `>` buttons at the bottom of the page weren't there. 

Am I understanding this correctly? Would you be able to take a quick screenshot?

**Comment by connorwang** [comment]
> Ah, so just to confirm, a quick backup was made that didn't import over the issues. The configuration is pretty much all that you cared about, and new events started coming in again. After receiving a good number of events, you discovered that you were unable to view all of them since the `<` and `>` buttons at the bottom of the page weren't there.
> 
> Am I understanding this correctly? Would you be able to take a quick screenshot?

That's correct. As you can see - we have more than 1k issues, and the <> buttons are missing.

<img width="850" alt="Screenshot 2022-09-26 141429" src="https://user-images.githubusercontent.com/7822862/192205750-c352e1fd-0031-4ca6-9d42-890d1ebe5690.png">



<img width="538" alt="Screenshot 2022-09-26 141718" src="https://user-images.githubusercontent.com/7822862/192206127-b8f542f6-2ebe-4c9c-a7b8-4bb3f1fd644a.png">
