### ISSUE TITLE
Artifacts do not appear after loading source map

### ISSUE THREAD

**Issue by Sarga** [getsentry/self-hosted#1681]
### Self-Hosted Version

10.0.0

### CPU Architecture

x86_64

### Docker Version

18.06.3-ce

### Docker Compose Version

2.6

### Steps to Reproduce

1) I'm trying to upload source maps to sentry

./sentry-cli  --url https://sentry.example.com releases --auth-token secret_token --org sentry --project front-react-dev files "ece7161915a7846ec8ae91d57a8aff5b1f9f008e" upload-sourcemaps /tmp/sources/
 Found 2 release files
 Analyzing 2 sources
 Analyzing completed in 0.023s
 Rewriting sources
 Rewriting completed in 0s
 Adding source map references
 Bundling files for upload...
 Bundling completed in 0s
 Optimizing completed in 0s
 Uploading completed in 0.811s
 Uploaded release files to Sentry
 Processing completed in 0.13s
 File upload complete (processing pending on server)
 Organization: sentry
 Project: front-react-dev
 Release: ece7161915a7846ec8ae91d57a8aff5b1f9f008e
 Dist: None

Source Map Upload Report
  Minified Scripts
    ~/100.js (sourcemap at bundle.js.map)
  Source Maps
    ~/bundle.js.map

2) I've got 200 code from sentry web    
`
Sep  3 18:53:55 sentry-01 supervisord: sentry-web 127.0.0.1 - - [03/Sep/2022:18:53:55 +0000] "POST /api/0/projects/sentry/front-react-dev/releases/ HTTP/1.1" 208 1050 "-" "sentry-cli/2.5.2"
Sep  3 18:53:55 sentry-01 supervisord: sentry-web 127.0.0.1 - - [03/Sep/2022:18:53:55 +0000] "GET /api/0/projects/sentry/front-react-dev/releases/ece7161915a7846ec8ae91d57a8aff5b1f9f008e/files/?cursor= HTTP/1.1" 200 907 "-" "sentry-cli/2.5.2"
Sep  3 18:53:56 sentry-01 supervisord: sentry-web 127.0.0.1 - - [03/Sep/2022:18:53:55 +0000] "GET /api/0/organizations/sentry/chunk-upload/ HTTP/1.1" 200 809 "-" "sentry-cli/2.5.2"
Sep  3 18:53:56 sentry-01 supervisord: sentry-web 127.0.0.1 - - [03/Sep/2022:18:53:56 +0000] "POST /api/0/organizations/sentry/chunk-upload/ HTTP/1.1" 200 485 "-" "sentry-cli/2.5.2"
Sep  3 18:53:56 sentry-01 supervisord: sentry-web 127.0.0.1 - - [03/Sep/2022:18:53:56 +0000] "POST /api/0/organizations/sentry/releases/ece7161915a7846ec8ae91d57a8aff5b1f9f008e/assemble/ HTTP/1.1" 200 534 "-" "sentry-cli/2.5.2"
`

3) I've open https://sentry.example.com/organizations/sentry/releases/ece7161915a7846ec8ae91d57a8aff5b1f9f008e/artifacts/?project=98 but there is message "There are no artifacts uploaded for this release."

4) Please tell me which components are responsible for loading and displaying artifacts (maybe some kind of worker)? What component logs should I check?

### Expected Result

Should be a list of artifacts

### Actual Result

There are no artifacts uploaded for this release.

**Comment by ethanhs** [comment]
Hm, your version of self-hosted is quite old. I'd recommend trying to upgrade first. Otherwise, I would try to look at the docker compose logs to see if there is any more information there about what could have caused the issue.
