### ISSUE TITLE
Another fix for KAFKA offset out of range

### ISSUE THREAD

**Issue by gabn88** [getsentry/self-hosted#1690]
### Self-Hosted Version

22.8.0

### CPU Architecture

x86_64

### Docker Version

20.10.17docker-

### Docker Compose Version

1.29.2

### Steps to Reproduce

The proper solution in https://develop.sentry.dev/self-hosted/troubleshooting/#proper-solution is quite cumbersome.

I have seen myself do:

```
docker-compose run --rm kafka kafka-consumer-groups --bootstrap-server kafka:9092 --all-groups --all-topics --reset-offsets --to-latest --execute
```
instead. It might be something in between of the proper and nuclear option though as I'm not sure about any (data) consequences. It fixes all groups and all topics.

### Expected Result

Fix the error

### Actual Result

It fixes it.

**Comment by hubertdeng123** [comment]
thanks for bringing this up to us! I will take a look and see if we can update documentation for this

**Comment by Dherlou** [comment]
AFAIK this results in a data loss of the events between the current index and the index-to-be by skipping their processing, so a notice would be nice in the documentary for users that may have a problem with this behaviour. :)

**Comment by beaupletga** [comment]
You made a small typo, it's `--bootstrap-server`  instead of `--bootsrap-server`.

**Comment by gabn88** [comment]
@beaupletga Thanks, edited the original post.

**Comment by aminvakil** [comment]
@hubertdeng123 Just mentioning you to see if this has been checked for data consequences as @gabn88 mentioned in original post and if it's ok, this could be added to documentation .

**Comment by hubertdeng123** [comment]
Bit late here on the response, but the potential for data loss is definitely there. Merged in documentation changes!
