### ISSUE TITLE
Turn things off script erroring out

### ISSUE THREAD

**Issue by hubertdeng123** [getsentry/self-hosted#1706]
### Problem Statement

Seeing an exception being thrown during the `./turn-things-off.sh` script with this error:

`$dc down -t $STOP_TIMEOUT --rmi local --remove-orphans`

**Comment by aminvakil** [comment]
Can the error be shared too?

**Comment by hubertdeng123** [comment]
```
▶ Turning things off ...

Container sentry-self-hosted-snuba-subscription-consumer-events-1  Stopping
Container sentry-self-hosted-snuba-replacer-1  Stopping
Container sentry-self-hosted-snuba-api-1  Stopping
...
Container sentry-self-hosted-zookeeper-1  Removing
Container sentry-self-hosted-zookeeper-1  Removed


Error response from daemon: removal of container 21136ea8655aba78b4a259809b256fafd22dbd8cb3c9f94694605a9add7af70a is already in progress
Error in turn-things-off.sh:8.
'$dc down -t $STOP_TIMEOUT --rmi local --remove-orphans' exited with status 1

-> ./install.sh:main:23
--> turn-things-off.sh:source:8

'$dc down -t $STOP_TIMEOUT --rmi local --remove-orphans' exited with status 1
```

**Comment by hubertdeng123** [comment]
Seeing this one a good amount!

**Comment by ethanhs** [comment]
We do run docker compose down twice: https://github.com/getsentry/self-hosted/blob/bacecf4fedde3635d27433d00c833890af086fc7/install/turn-things-off.sh#L8-L12 so my guess is one of the containers is in the removal state when we run the down command again.

**Comment by aminvakil** [comment]
I don't think `docker-compose down` gets executed twice, as if the `COMPOSE_PROJECT_NAME` you want to do stuff with does not exist, it won't do anything,

A simple reproducer with any `docker-compose.yml` you want:
```
$ docker-compose up -d
[+] Running 1/0
 ⠿ Container httpd  Running                                                                                                                                                                                                            0.0s
$ COMPOSE_PROJECT_NAME=nonexistent docker-compose down -v --remove-orphans
$
$ docker-compose down -v --remove-orphans
[+] Running 2/2
 ⠿ Container httpd      Removed                                                                                                                                                                                                        1.3s
 ⠿ Network nfs_default  Removed                                                                                                                                                                                                        0.1s
$ COMPOSE_PROJECT_NAME=nonexistent docker-compose down -v --remove-orphans
$
```
It seems that second `docker-compose down` with specifying `COMPOSE_PROJECT_NAME` does not do anything.

Maybe this issue is with a specific version of `docker-compose`, can you check `docker-compose` version of users facing this issue?

**Comment by ethanhs** [comment]
I have experienced this issue before (on v.2.6.0)

**Comment by ethanhs** [comment]
In getsentry/sentry#39281 @alexandernst found that we did not catch his compose was too old... which is odd because we do check for this. Perhaps our check is not working 100% of the time?

**Comment by hubertdeng123** [comment]
Yeah Ethan you're right on this one. The minimum requirements for the version of docker and compose weren't working properly
