### ISSUE TITLE
GitLab Integration fails - redirects to 504 Gateway Time-out

### ISSUE THREAD

**Issue by jemx** [getsentry/self-hosted#1707]
### Self-Hosted Version

22.9.0

### CPU Architecture

x86_64

### Docker Version

20.10.18

### Docker Compose Version

1.25.0

### Steps to Reproduce

1. Add GitLab integration
2. Follow the setup steps
3. Sign in to GitLab and allow Sentry access

### Expected Result

GitLab Integration should be added to Sentry, the setup wizard should continue.

### Actual Result

After authorizing in GitLab it redirects to `172.16.16.202:9000/extensions/gitlab/setup/?code=XXX&state=XXX`

**This results sometimes into a 504 Gateway Timeout and other times into a 502 Bad Gateway**. I found the following in `docker compose logs`:
`sentry-self-hosted-nginx-1| 2022/09/17 14:51:00 [error] 25#25: *3446 upstream prematurely closed connection while reading response header from upstream, client: 192.168.1.5, server: , request: "GET /extensions/gitlab/setup/?code=XXX&state=XXX HTTP/1.1", upstream: "http://172.18.0.23:9000/extensions/gitlab/setup/?code=XXX&state=XXX", host: "172.16.16.202:9000"`

If i try to add a new GitLab Integration again, I have to log out and into Sentry again before I can try again.

**Comment by hubertdeng123** [comment]
Got it, thanks for that. I was wondering if you could try tweaking the numbers a bit for your proxy timeout.
https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_connect_timeout

**Comment by jemx** [comment]
I played around a bit and increased the proxy timeouts. I still get a 502 but now an exception is triggered (and thankfully Sentry monitors it self \o/).

```
SafeHTTPSConnectionPool(host='xxx.xxx.xxx', port=443): Max retries exceeded with url: /oauth/token (Caused by ConnectTimeoutError(<sentry.net.http.SafeHTTPSConnection object at 0x7f64a95d1e50>, 'Connection to xxx.xxx.xxx timed out. (connect timeout=30)'))
```

I've checked that the machine running Sentry can reach GitLab (ping and curl) and it works fine...

**Comment by hubertdeng123** [comment]
Hmmm, this still sounds like some sort of networking issue of some sort. Have you attempted to ping and curl GitLab from inside the docker containers?

**Comment by victorelec14** [comment]
related with getsentry/self-hosted#1672 ??
