### ISSUE TITLE
sentry-cli upload ios dSYM get 413 Request Entity Too Large error

### ISSUE THREAD

**Issue by feeops** [getsentry/self-hosted#1708]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

22.7.0

### Steps to Reproduce

sentry-cli --url https://{server}/ --auth-token {token} upload-dif --org sentry --project {project} xxx.dSYM

### Expected Result

sucess

### Actual Result

<img width="1355" alt="iShot_2022-09-13_15 39 27" src="https://user-images.githubusercontent.com/92842117/189840532-6c8f982e-0328-48f9-b1ad-f2e6216e3673.png">

And I changed nginx.conf client_max_body_size from 100m to 1000m.
But It did not work.

**Comment by kamilogorek** [comment]
Transfering this issue to `self-hosted`, as this CLI is not in control o this behavior. It only outputs what server is returning for the request.

**Comment by aminvakil** [comment]
@feeops Have you restarted nginx container after making the changes?

Also https://github.com/getsentry/self-hosted/issues/937#issuecomment-828371053 ? :smile:

**Comment by feeops** [comment]
> @feeops Have you restarted nginx container after making the changes?
> 
> Also [#937 (comment)](https://github.com/getsentry/self-hosted/issues/937#issuecomment-828371053) ? 😄

Yes.I had restart nginx and web

```
docker  restart sentry-self-hosted-web-1
docker  restart sentry-self-hosted-nginx-1
```

**Comment by ethanhs** [comment]
Relay and sentry both have upload limits as well, you might want to check your settings for that: https://docs.sentry.io/product/relay/options/#size-limits

**Comment by feeops** [comment]
> Relay and sentry both have upload limits as well, you might want to check your settings for that: https://docs.sentry.io/product/relay/options/#size-limits

It do not work.

**Comment by ethanhs** [comment]
Sorry, and just to make sure, you restarted the relevant containers after editing the relay config file?

**Comment by feeops** [comment]
> Sorry, and just to make sure, you restarted the relevant containers after editing the relay config file?

yes
