### ISSUE TITLE
 Required minimum RAM available to Docker is 3800 MB, found 3789 MB

### ISSUE THREAD

**Issue by chuanjing** [getsentry/self-hosted#1711]
### Self-Hosted Version

22.10.0

### CPU Architecture

x86_64

### Docker Version

Docker version 1.13.1

### Docker Compose Version

Compose version 1.29.2

### Steps to Reproduce

./install.sh

### Expected Result

success

### Actual Result

Required minimum RAM available to Docker is 3800 MB, found 3789 MB

**Comment by aminvakil** [comment]
Can you paste the output of `free -m` command ?
