### ISSUE TITLE
How to change the language of the front-end page

### ISSUE THREAD

**Issue by takeern** [getsentry/self-hosted#1713]
### Self-Hosted Version

22.9.0

### CPU Architecture

x86_64

### Docker Version

20.10.12

### Docker Compose Version

1.28.0

### Steps to Reproduce

**Environment** 
<img width="334" alt="image" src="https://user-images.githubusercontent.com/12117721/191468633-8cf99a0d-6b17-431e-bae0-3c8c4a0b7792.png">

**User config**
![image](https://user-images.githubusercontent.com/12117721/191469499-24ba78da-fdcd-42b3-86fa-d125085175ad.png)

### Expected Result

language code is “en”

### Actual Result

**Login interface config**
![image](https://user-images.githubusercontent.com/12117721/191469093-04c95f67-efc8-4a42-ba60-c05104369da5.png)

<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  
  <meta name="robots" content="none, noarchive">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="icon" type="image/png" href="http://47.243.231.246:9000/_static/1663749857/sentry/images/favicon.png">

  <link rel="apple-touch-icon" href="http://47.243.231.246:9000/_static/1663749857/sentry/images/logos/apple-touch-icon.png">
  <link rel="apple-touch-icon" sizes="76x76" href="http://47.243.231.246:9000/_static/1663749857/sentry/images/logos/apple-touch-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="120x120" href="http://47.243.231.246:9000/_static/1663749857/sentry/images/logos/apple-touch-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="152x152" href="http://47.243.231.246:9000/_static/1663749857/sentry/images/logos/apple-touch-icon-152x152.png">
  

  <link rel="mask-icon" sizes="any" href="http://47.243.231.246:9000/_static/1663749857/sentry/images/logos/logo-sentry.svg" color="#FB4226">

  <link href="/_static/dist/sentry/entrypoints/sentry.css" rel="stylesheet"/>

  

  <title>Sign In | Sentry</title>

  
    <script>window.__initialData = {"singleOrganization":true,"supportEmail":"louellayenglineia37@gmail.com","urlPrefix":"http://47.243.231.246:9000","version":{"current":"22.9.0","latest":"22.9.0","build":"e40adedb52066474034a8fe27d8818aa0f071a30","upgradeAvailable":false},"features":[],"distPrefix":"/_static/dist/sentry/","needsUpgrade":false,"dsn":"http://18b73ef98bca4a148d6db0d1bc66925e@47.243.231.246:9000/1","statuspage":null,"messages":[],"apmSampling":0.0,"isOnPremise":true,"isSelfHosted":true,"invitesEnabled":true,"gravatarBaseUrl":"https://secure.gravatar.com","termsUrl":null,"privacyUrl":null,"lastOrganization":null,"languageCode":"zh-cn","userIdentity":{"ip_address":"203.198.11.197"},"csrfCookieName":"sc","sentryConfig":{"dsn":"http://18b73ef98bca4a148d6db0d1bc66925e@47.243.231.246:9000/1","release":"frontend@22.9.0+e40adedb52066474034a8fe27d8818aa0f071a30","environment":"production","whitelistUrls":[]},"demoMode":false,"enableAnalytics":false,"validateSUForm":true,"disableU2FForSUForm":false,"links":{"organizationUrl":null,"regionUrl":null,"sentryUrl":"http://47.243.231.246:9000"},"isAuthenticated":false,"user":null};</script>
  

  <script>// if the ads.js file loads below it will mark this variable as false
    window.adblockSuspected = true;
    // Initialize this so that we can queue up tasks when Sentry SPA is initialized
    window.__onSentryInit = window.__onSentryInit || [];</script>

  <script>try {
    var reg = new RegExp(/\/organizations\/(.+?(?=(\/|$)))(\/|$)/, 'i');
    var organization = window.location.pathname;
    var slug = organization.match(reg)[1];

    function promiseRequest(url) {
      return new Promise(function (resolve, reject) {
        var xhr = new XMLHttpRequest();
        xhr.open('GET', url);
        xhr.onload = function () {
          try {
            this.status >= 200 && this.status < 300
              ? resolve([JSON.parse(xhr.response), this.statusText, xhr])
              : reject([this.status, this.statusText]);
          } catch (e) {
            reject();
          }
        };
        xhr.onerror = function () {
          reject([this.status, this.statusText]);
        };
        xhr.send();
      });
    }

    function makeUrl(suffix) {
      return '/api/0/organizations/' + slug + suffix;
    }

    // There are probably more, but this is at least one case where
    // this should not be treated as a slug
    if (slug !== 'new') {
      var preloadPromises = {orgSlug: slug};
      window.__sentry_preload = preloadPromises;

      preloadPromises.organization = promiseRequest(makeUrl('/?detailed=0'));
      preloadPromises.projects = promiseRequest(
        makeUrl('/projects/?all_projects=1&collapse=latestDeploys')
      );
      preloadPromises.teams = promiseRequest(makeUrl('/teams/'));
    }
  } catch (_) {}</script>

  

  
    
    <script src="/_static/dist/sentry/entrypoints/app.js"></script>
  

  
  

  
  <script src="/_static/1663749857/sentry/js/ads.js"></script>
  

<script>window.__onSentryInit = window.__onSentryInit || [];
  window.__onSentryInit.push({
    name: 'passwordStrength',
    input: '#id_registration_password',
    element: '.password-strength',
  });
  // HACK(jferge): inline getCookie function from our utils,
  // update the csrf token value in a rudimentary way (timer based)
  // on the SSO login form
  // to help out when users have multiple sentry tabs and are logged out
  function getCookie(name) {
    if (document.cookie && document.cookie !== '') {
      var cookies = document.cookie.split(';');
      for (let i = 0; i < cookies.length; i++) {
        var cookie = cookies[i].trim();
        // Does this cookie string begin with the name we want?
        if (cookie.substring(0, name.length + 1) === name + '=') {
          return decodeURIComponent(cookie.substring(name.length + 1));
        }
      }
    }
    return null;
  }
  setInterval(function() {
    var csrfCookieVal = getCookie('sc');
    // combine strings for csrf name as some tests grep on the token name :(
    var csrfName = 'csrf'+'middleware'+'token';
    var csrfEls = document.getElementsByName(csrfName);
    if (csrfEls.length == 1 && csrfCookieVal) {
      csrfEls[0].value = csrfCookieVal;
    }
  },200);</script>

</head>

<body class="narrow auth org-login">
  
  <div class="app">
    

    
    

<div id="blk_alerts" class="messages-container"></div>
<div id="blk_indicators"></div>

<script>window.__onSentryInit = window.__onSentryInit || [];
  window.__onSentryInit.push({
    name: 'renderReact',
    component: 'SystemAlerts',
    container: '#blk_alerts',
    props: {
      className: 'alert-list',
    },
  });
  window.__onSentryInit.push({
    name: 'renderReact ',
    component: 'Indicators',
    container: '#blk_indicators',
    props: {
      className: 'indicators-container',
    },
  });</script>

    

    <div class="container">
      <div class="content">
        
<div class="pattern-bg"></div>

<div class="box">
  <div class="auth-sidebar">
    <a href="/">
      <span class="icon-sentry-logo"></span>
    </a>
  </div>
  <section class="org-login">
    
<div>
  <div class="align-center p-t-2">
    <img src="/_static/1663749857/sentry/images/logos/default-organization-logo.png" class="org-avatar">
    <h3>Sentry</h3>
  </div>

  
    <div class="auth-container p-t-0 border-bottom">
      <ul class="nav nav-tabs auth-toggle m-b-0">
        <li class="active">
          <a href="#login" data-toggle="tab">Sign In</a>
        </li>
        
        
          <li class="join-request">
            <a href="/join-request/sentry/">
              <svg width="37" height="31" viewBox="0 0 37 31" fill="none" xmlns="http://www.w3.org/2000/svg">
<g clip-path="url(#clip0)" fill-rule="evenodd" clip-rule="evenodd" fill="currentColor">
<rect width="36" height="31" transform="translate(0.262695)" fill="white"/>
<path d="M25.0029 9.9302C24.5547 8.25773 22.8356 7.26521 21.1631 7.71335L20.6455 5.78149C23.3849 5.04747 26.2007 6.67316 26.9347 9.41256C27.6687 12.152 26.043 14.9677 23.3036 15.7018L22.786 13.7699C24.4585 13.3218 25.451 11.6027 25.0029 9.9302Z"/>
<path d="M2.52864 15.9521C2.67312 16.4913 3.22735 16.8113 3.76654 16.6668L4.28418 18.5986C2.67805 19.029 1.02715 18.0758 0.596792 16.4697C0.166431 14.8636 1.11958 13.2127 2.72571 12.7823L3.24334 14.7142C2.70415 14.8587 2.38417 15.4129 2.52864 15.9521Z"/>
<path d="M9.31756 29.0904L6.875 19.9746L8.80685 19.457L11.1469 28.1903L12.9937 27.6955L12.2281 24.838C12.1606 24.586 12.1555 24.3215 12.2133 24.0672L12.8689 21.1837L12.1651 18.5571L14.097 18.0395L14.8261 20.7607C14.8936 21.0126 14.8987 21.2772 14.8409 21.5315L14.1853 24.415L15.0281 27.5602C15.2574 28.416 14.7495 29.2956 13.8938 29.5248L11.2822 30.2246C10.4264 30.4539 9.54685 29.9461 9.31756 29.0904Z"/>
<path d="M17.5998 4.07355L13.8132 8.53283C13.6228 8.75713 13.3773 8.92808 13.1009 9.02892L4.48516 12.1717L6.11329 18.2479L15.1461 16.6618C15.4359 16.6109 15.734 16.6362 16.0111 16.7352L21.52 18.7038L23.8831 18.0706L19.9629 3.44036L17.5998 4.07355ZM16.1363 2.70714C16.3596 2.44413 16.6578 2.2554 16.9911 2.1661L19.7371 1.43031C20.6428 1.18762 21.5738 1.72513 21.8165 2.63089L25.8931 17.8448C26.1358 18.7506 25.5983 19.6816 24.6925 19.9243L21.9465 20.6601C21.6133 20.7494 21.2607 20.735 20.9358 20.6189L15.4133 18.6455L6.1867 20.2657C5.32007 20.4178 4.48077 19.8827 4.25304 19.0328L2.4817 12.4221C2.25397 11.5722 2.71327 10.6891 3.53988 10.3876L12.3404 7.1774L16.1363 2.70714Z"/>
<path d="M28.3174 12.5909C28.5935 12.1126 29.2051 11.9487 29.6834 12.2249L33.3668 14.3515C33.8451 14.6276 34.009 15.2392 33.7328 15.7175C33.4567 16.1958 32.8451 16.3597 32.3668 16.0835L28.6834 13.9569C28.2051 13.6808 28.0412 13.0692 28.3174 12.5909Z"/>
<path d="M28.8018 8.91246C28.6588 8.37899 28.9754 7.83066 29.5089 7.68771L34.4512 6.36341C34.9847 6.22047 35.533 6.53706 35.676 7.07052C35.8189 7.60399 35.5024 8.15232 34.9689 8.29527L30.0265 9.61957C29.4931 9.76251 28.9447 9.44593 28.8018 8.91246Z"/>
<path d="M26.5438 5.96826C26.0655 5.69212 25.9016 5.08053 26.1777 4.60224L28.3043 0.91885C28.5805 0.440558 29.1921 0.276683 29.6704 0.552825C30.1487 0.828967 30.3125 1.44056 30.0364 1.91885L27.9098 5.60224C27.6336 6.08053 27.0221 6.2444 26.5438 5.96826Z"/>
</g>
<defs>
<clipPath id="clip0">
<rect width="36" height="31" fill="white" transform="translate(0.262695)"/>
</clipPath>
</defs>
</svg>

              请求加入
            </a>
          </li>
        
      </ul>
    </div>

    <div class="tab-content basic-login">
      <div class="tab-pane active" id="login">
        <div class="auth-container">
          <div class="auth-form-column">
            <form class="form-stacked" action="" method="post" autocomplete="off">
              <input type="hidden" name="csrfmiddlewaretoken" value="vctoKnmJq5H28cxemq1T9I2cl1SYByq6mvaCgaeXe9oYfQduJLnHUSE2xVJS9Mcp">

              <input type="hidden" name="op" value="login" />

              

              
                

    
    <div id="div_id_username" class="form-group">
        
            <label for="id_username" class="control-label  requiredField">
                账户<span class="asteriskField">*</span>
            </label>
        

        

        

        
            
                <div class="controls ">
                        
                        <input type="text" name="username" placeholder="用户名或邮箱" tabindex="1" maxlength="128" class="textinput textInput form-control" required id="id_username">
                        
                    

    

    

                </div>
            
        
    </div>
    

              
                

    
    <div id="div_id_password" class="form-group">
        
            <label for="id_password" class="control-label  requiredField">
                密码<span class="asteriskField">*</span>
            </label>
        

        

        

        
            
                <div class="controls ">
                        
                        <input type="password" name="password" placeholder="密码" tabindex="2" class="textinput textInput form-control" required id="id_password">
                        
                    

    

    

                </div>
            
        
    </div>
    

              

              <div class="auth-footer m-t-1">
                <button type="submit" class="btn btn-primary">Sign In</button>
                <a class="secondary" href="/account/recover/">密码丢失？</a>
              </div>
            </form>
          </div>
          
        </div>
      </div>
      <div class="tab-pane" id="register">
        <div class="auth-container">
          <div class="auth-form-column">
            <form class="form-stacked" action="" method="post" autocomplete="off">
              <input type="hidden" name="csrfmiddlewaretoken" value="vctoKnmJq5H28cxemq1T9I2cl1SYByq6mvaCgaeXe9oYfQduJLnHUSE2xVJS9Mcp">

              <input type="hidden" name="op" value="register" />

              

              

              <div class="password-strength"></div>
              <div class="auth-footer m-t-1">
                <button type="submit" class="btn btn-primary">注册</button>
                <a class="secondary" href="https://sentry.io/privacy/" target="_blank">
                  隐私政策
                </a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  
</div>

  </section>
</div>

      </div>
    </div>
  </div>
  

  
  
  <script>document.addEventListener('DOMContentLoaded', function() {
      const el = document.querySelector('#sign-out');
      if (el) {
        el.addEventListener('click', function() {
          document.modalLogoutForm.submit();
        });
      }
    });</script>

</body>
</html>

**Comment by hubertdeng123** [comment]
Would you be able to give us more details on how to reproduce here? Are you changing from the Chinese language to English and finding that it does not work? A refresh on the page is needed to update the language

**Comment by takeern** [comment]
Thanks Reply

I tried to reset all configurations with reset.sh, but the languageCode is still 'zh-cn', but I directly use wget to get index.html, and the languageCode is 'en', so I want to know where can I configure languageCode globally

**Comment by takeern** [comment]
I seem to have found the reason. When I initiate this request in the browser, accept-language will be specified by default. Is there a way to make the system not refer to this parameter?

**Comment by hubertdeng123** [comment]
So if I'm understanding this correctly, the accept-language of your browser is `zh-cn`, and that is influencing the `languageCode`?

**Comment by hubertdeng123** [comment]
While your browser is still displaying Sentry in `zh-cn` when you're expecting `en`?

**Comment by hubertdeng123** [comment]
What browser are you using? I'd like to see if I can reproduce this
