### ISSUE TITLE
Can't build on macOS with colima

### ISSUE THREAD

**Issue by DmitriiMukhin** [getsentry/self-hosted#1717]
### Self-Hosted Version

22.9.0

### CPU Architecture

x86_64

### Docker Version

20.10.11

### Docker Compose Version

2.11.0

### Steps to Reproduce

Just run ./install.sh. Build fails.

### Expected Result

Succesfull build of sentry

### Actual Result

`▶ Parsing command line ...

▶ Detecting Docker platform
Detected Docker platform is linux/amd64

▶ Initializing Docker Compose ...

▶ Setting up error handling ...

▶ Checking for latest commit ... 

▶ Checking minimum requirements ...
Found Docker version 20.10.11
Found Docker Compose version 2.11.0
WARN: Recommended minimum CPU cores available to Docker is 4, found 2

▶ Turning things off ...
Image sentry-self-hosted-local:latest  Removing
Image sentry-self-hosted-local:latest  Removed

▶ Creating volumes for persistent storage ...
Created sentry-clickhouse.
Created sentry-data.
Created sentry-kafka.
Created sentry-postgres.
Created sentry-redis.
Created sentry-symbolicator.
Created sentry-zookeeper.

▶ Ensuring files from examples ...
../sentry/sentry.conf.py already exists, skipped creation.
../sentry/config.yml already exists, skipped creation.
../symbolicator/config.yml already exists, skipped creation.

▶ Ensuring Relay credentials ...
../relay/config.yml already exists, skipped creation.
../relay/credentials.json already exists, skipped creation.

▶ Generating secret key ...

▶ Replacing TSDB ...

▶ Fetching and updating Docker images ...
nightly: Pulling from getsentry/sentry
Digest: sha256:1b8c8097c8b7aa23218ff4083625820501312f0585c11477513f11b4f38dd7dd
Status: Image is up to date for getsentry/sentry:nightly
docker.io/getsentry/sentry:nightly

▶ Building and tagging Docker images ...

service.platform should be part of the service.build.platforms: "linux/amd64"
Error in ./build-docker-images.sh:6.
'$dc build --build-arg "http_proxy=${http_proxy:-}" --build-arg "https_proxy=${https_proxy:-}" --build-arg "no_proxy=${no_proxy:-}" --force-rm web' exited with status 1
-> ./install.sh:main:30
--> ./build-docker-images.sh:source:6

Cleaning up...`

**Comment by hubertdeng123** [comment]
Hi there, can you try exporting this env variable?
`export DOCKER_DEFAULT_PLATFORM=linux/amd64 `

**Comment by DmitriiMukhin** [comment]
> export DOCKER_DEFAULT_PLATFORM=linux/amd64

I tried to do that. Didn't help.

![Screenshot 2022-09-23 at 10 21 52](https://user-images.githubusercontent.com/88187872/191910398-96bceebe-a6cb-4dc0-85f6-74825883738a.png)

**Comment by hubertdeng123** [comment]
I'm not familiar with how colima works, maybe that has something to do with this? Otherwise, I've seen other issues pop up with arm support that can be resolved by playing around with the `DOCKER_PLATFORM` in docker-compose.yml

```
x-sentry-defaults: &sentry_defaults
  <<: *restart_policy
  image: sentry-self-hosted-local
  # Set the platform to build for linux/arm64 when needed on Apple silicon Macs.
  platform: ${DOCKER_PLATFORM:-}
  ```

**Comment by DmitriiMukhin** [comment]
> I'm not familiar with how colima works, maybe that has something to do with this? Otherwise, I've seen other issues pop up with arm support that can be resolved by playing around with the `DOCKER_PLATFORM` in docker-compose.yml
> 
> ```
> x-sentry-defaults: &sentry_defaults
>   <<: *restart_policy
>   image: sentry-self-hosted-local
>   # Set the platform to build for linux/arm64 when needed on Apple silicon Macs.
>   platform: ${DOCKER_PLATFORM:-}
> ```

Even hardcoded linux/amd64 doesn't make sense.

**Comment by hubertdeng123** [comment]
Could you try this then?
https://github.com/getsentry/self-hosted/issues/1720#issuecomment-1258806526

Seems to be a duplicate issue

**Comment by DmitriiMukhin** [comment]
Everything works as expected on last version
