### ISSUE TITLE
Error at install.sh

### ISSUE THREAD

**Issue by sbellver** [getsentry/self-hosted#1720]
### Self-Hosted Version

22.9.0

### CPU Architecture

x86_64 

### Docker Version

20.10.18

### Docker Compose Version

2.11.0

### Steps to Reproduce

Clone the actual repo at tag 22.9.0
Change .env to modify BIND PORT variable
Run install.sh

### Expected Result

Do the install fine

### Actual Result

▶ Fetching and updating Docker images ...
22.9.0: Pulling from getsentry/sentry
Digest: sha256:a6eb413caa953c172f1a44d355879ba30a4ecdb40553d4d11f20c3e12063ba18
Status: Image is up to date for getsentry/sentry:22.9.0
docker.io/getsentry/sentry:22.9.0

▶ Building and tagging Docker images ...

service.platform should be part of the service.build.platforms: "linux/amd64"
Error in build-docker-images.sh:6.
'$dc build --build-arg "http_proxy=${http_proxy:-}" --build-arg "https_proxy=${https_proxy:-}" --build-arg "no_proxy=${no_proxy:-}" --force-rm web' exited with status 1
yes: salida estándar: Tubería rota
yes: salida estándar: Tubería rota
-> ./install.sh:main:30
--> build-docker-images.sh:source:6

**Comment by ethanhs** [comment]
Hi! Can you try to change this line: https://github.com/getsentry/self-hosted/blob/196b40feb1c8f527e994b726711127bc556ca4ff/docker-compose.yml#L21 to be under `build`? Which seems to be what docker is complaining about?
