### ISSUE TITLE
Run ./install.sh without user prompt and without --skip-user-creation

### ISSUE THREAD

**Issue by drmrbrewer** [getsentry/self-hosted#1721]
### Problem Statement

At the moment I am installing sentry as part of a script, avoiding any user prompt by running:

    ./install.sh --skip-user-creation

Then afterwards I have to run the following command to add a user:

    docker compose run --rm web createuser

This stops to ask three questions (plus one confirmation):

    Email: 
    Password: 
    Repeat for confirmation: 
    Should this user be a superuser?

The problem is that this is a two-stage process... install as part of an automated process.  Then another step of adding a user.

### Solution Brainstorm

Would be good to be able to create a user as part of `./install.sh` for example by passing the required info as arguments, or via environment variables.  That way, the entire installation process could be automated from start to finish.

**Comment by ethanhs** [comment]
Is this an environment where you already were running Sentry beforehand? If not could you describe what your use case is?

**Comment by drmrbrewer** [comment]
When I spin up a new server, I run a script which installs all the necessary tools and services, including docker and multiple docker containers/services etc.  One of the things I do in this script is to install self-hosted sentry.  But I can't complete the installation because creating a user results in a prompt which stalls the setup script.  So I would like to be able to create the user at the time of installation, not after, by passing the required information via arguments or environment variables instead of via a prompt... this is a secure environment so there's no issue with having user credentials passed in this way.

**Comment by hubertdeng123** [comment]
You can create a user by using a script with this in it
`docker-compose --ansi never run --rm web createuser --force-update --superuser --email user@example.com --password secret`

**Comment by drmrbrewer** [comment]
@hubertdeng123 ah OK that's useful to know.  So it would still be a two-step process (install without user creation to avoid any prompt), then create user (without any prompt)?

Like:

    ./install.sh --skip-user-creation --no-report-self-hosted-issues
    docker-compose --ansi never run --rm web createuser --force-update --superuser --email user@example.com --password secret

i.e. user creation can't be wrapped up into the install step?  Not that it matters much when this is scripted, just checking which gives the most streamlined installation overall... thanks.

And I assume this should also work with `docker compose` as opposed to `docker-compose`, with the same args?

**Comment by ethanhs** [comment]
> i.e. user creation can't be wrapped up into the install step

We could add an option but we would essentially be just running that exact same `docker compose` command with what you pass.

Also yes, re `docker-compose` vs `docker compose` they are two different namings of the same thing basically, `docker compose` is a newer way to write `docker-compose` (which was a dedicated program but now is just a docker plugin)

**Comment by drmrbrewer** [comment]
Thanks, having to script two steps rather than one is of course no problem... thanks for letting me know the flags to use for the second (user creation) step to avoid the prompts.  Works fine.

**Comment by hubertdeng123** [comment]
Yep, it would be a two step process @drmrbrewer, glad this could solve your issue!
