### ISSUE TITLE
Mass import users

### ISSUE THREAD

**Issue by marbon87** [getsentry/self-hosted#1725]
### Problem Statement

I want to assign issues to users, that are currently not registired in our sentry environment. Therefore i want to import all relevant users and autoassign them dedicated teams.
Note: We use saml for authentication.

### Solution Brainstorm

A rest api to create teams, create users and assign groups.
At the possibility to connect external users providesr, like ldap to request users and team membership.

**Comment by hubertdeng123** [comment]
Sounds like this is more of a feature request that doesn't specifically relate to self-hosted.

**Comment by hubertdeng123** [comment]
Actually I may have misspoken here 😅.  Are you searching for a way to modify our postgres database to perform organizational functions through an API? Is the end goal to write a script that can utilize this API?

**Comment by marbon87** [comment]
Sorry for the inaccurate description of the solution.
The end goal is to have a scheduled task, that syncs an amount of existing users from our IAM to sentry and assign them appropiate rules. Another solutoin would be that sentry can actively query external system, like ldap to query for existing users.
I found the API reference docs at https://docs.sentry.io/api but i did not find an endpoint to create /modify users.
But i agree that this does not specifically relate to self-hosted and i will create a new issue at the main sentry repo.
