### ISSUE TITLE
Is it possible to split the UI and DSN ports - Would like to restrict IP access to the web interface only

### ISSUE THREAD

**Issue by Reyalsorik** [getsentry/self-hosted#1735]
### Self-Hosted Version

22.9.0

### CPU Architecture

x86_64

### Docker Version

20.10.18

### Docker Compose Version

2.10.2

### Steps to Reproduce

1. Install sentry with the `install.sh` file.
2. docker compose up -d

`sentry.mydomain.com:9000` is accessible now.

### Expected Result

We would like to separate the web UI and the exposed DSN for sending data. (e.g., web 9000, DSN 9001)

Goals:
* restrict the web UI to our internal VPN due to potential PHI and PII (i.e., port 9000 is closed to the general internet)
* leave the DSN open for new data to flow in (i.e., port 9001 is open to the general internet)

### Actual Result

At this point, the web UI is accessible over port 9000.
New DSN entries are also over port 9000.

By utilizing the same port, we can't simply turn off the port to the rest of the internet since that would deny sending data too.

**Comment by hubertdeng123** [comment]
Thanks for bringing this up to us, unfortunately this is something that we do not support. However, we do have a site that offers suggestions for scrubbing data
https://docs.sentry.io/platforms/node/data-management/sensitive-data/

**Comment by ethanhs** [comment]
You could probably configure nginx to only accept connections to the web UI via splitting the requests paths in nginx and setting `allowed_ips` (i.e. two `location` blocks, one for web ui, one for the DSN).

**Comment by beaupletga** [comment]
Hello,

I actually managed to do that.

In the  `docker-compose.yaml`, you can change the ports of nginx. 
Here I'm using 443 for the UI and 9000 for the events.

```
nginx:
    <<: *restart_policy
    ports:
      - "443:443/tcp"
      - "9000:9000/tcp"
```

Then in the `nginx.conf` file, just split the server into 2 parts:

```
server {
    listen 9000 ssl;

    location /api/store/ {
      	proxy_pass http://relay;
    }
    location ~ ^/api/[1-9]\d*/ {
	proxy_pass http://relay;
    }
}

server {
    listen 443 ssl;

    location / {
	proxy_pass http://sentry;
    }
}
```

Then restart sentry with docker compose and you should be good.

**Comment by hubertdeng123** [comment]
Oh wow looks like I was completely wrong here, thanks for the solution here!

**Comment by ethanhs** [comment]
Glad to hear it! I am going to go ahead and close this since it seems like this has been resolved.

**Comment by aminvakil** [comment]
> In the `docker-compose.yaml`, you can change the ports of nginx. Here I'm using 443 for the UI and 9000 for the events.
> 

We have also restricted access to UI expect from specific IPs, but we are using another `nginx` in front of sentry, this way we have much more control over what to change and what not to.

Also I'm not sure how are you handling real IP of users who connect to container as they're getting `NAT`ed in docker network, but overall if you use an external `nginx` you don't have to worry about this too.
