### ISSUE TITLE
SSL certificate problem when executing install-wal2json.sh

### ISSUE THREAD

**Issue by zhiyong-lv** [getsentry/self-hosted#1743]
### Self-Hosted Version

22.9.0

### CPU Architecture

x86_64

### Docker Version

20.10.11

### Docker Compose Version

1.29.2

### Steps to Reproduce

1. execute "./install.sh"

### Expected Result

1. it could be done without any issues.

## The following error will show:
```
Downloading and installing wal2json ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

## Work Around
1. change all "https" to "http" in install/install-wal2json.sh

**Comment by ethanhs** [comment]
Hmm I wonder if we need to add `ca-certificates` to our images...

**Comment by aminvakil** [comment]
@ethanhs I don't think so, this problem should have happened for all users then, right?

@zhiyong-lv Can you execute this command from host?

`curl https://api.github.com/repos/getsentry/wal2json/releases/latest`
