### ISSUE TITLE
How to set a people as Sentry superuser while open SSO?

### ISSUE THREAD

**Issue by liukch** [getsentry/self-hosted#1744]
### Problem Statement

In self-hosted Sentry, I open SAML2 authentication, I can not login Sentry with primary superuser.

So I need to Specify a member as the superuser in order to access the manage API to control the whole Sentry.

**Comment by ethanhs** [comment]
I'm going to close this in favor of your other issue here: https://github.com/getsentry/self-hosted/issues/1745 (I'll answer there)
