### ISSUE TITLE
Unable to give user admin or superuser role in manage UI.

### ISSUE THREAD

**Issue by liukch** [getsentry/self-hosted#1745]
### Self-Hosted Version

22.9.0

### CPU Architecture

x86_64

### Docker Version

20.10.11

### Docker Compose Version

1.29.2

### Steps to Reproduce

1. Login with Sentry primary superuser A
2. Enable SAML2 SSO auth, at the same time create SSO user B
3. Sign out superuser A and create another SSO user C as a member
4. Disable SAML2 SSO 
5. Login with primary superuser A 
6. Jump to https://sentry.mydomain/manage/users/3/
7. Enable `Admin` and `Superuser`, save changes
8. Refresh the web page, nothing happend, the user not be set to Admin or Superuser

### Expected Result

SSO user C is set to Admin and Superuser

### Actual Result

Nothing happend

**Comment by liukch** [comment]
After read from https://github.com/getsentry/self-hosted/issues/1288 

I use `docker exec -ti sentry-self-hosted_web_1 sentry permissions add -u A -p "user.superuser"`
The result is `Permission already exists for A`

But I use `docker exec -ti sentry-self-hosted_web_1 sentry permissions add -u C -p "user.superuser"`
The result is `Error: User C does not have superuser status`

**Comment by ethanhs** [comment]
Hi, sorry this isn't working for you. Can you check the logs of the web/worker containers to see if there are any clues as to what is going wrong there?
