### ISSUE TITLE
Sentry not sending email when a new issue happens or a new event of an existing issue happens

### ISSUE THREAD

**Issue by ntimo** [getsentry/self-hosted#1746]
### Self-Hosted Version

22.8.0

### CPU Architecture

x86_64

### Docker Version

20.10.17, build 100c701

### Docker Compose Version

docker-compose version 1.29.2, build unknown

### Steps to Reproduce

1. Create a new project in sentry
2. Create a script in python that devices zero by zero
3. Check that the exeption is catched by sentry
4. Check your mails since no mail about the issue is going to be send
5. Repeat step 3 and rerun the script
6. Check your mails again no new mails is send again

### Expected Result

A email should be send to the user immediately to notify him of the problem and the email should be send asap.

### Actual Result

No emails are send

## Additional context
Our email server in configured like this in the sentry/config.yml
```
mail.backend: 'smtp'
mail.host: 'mailserver.example.com'
mail.port: 25
mail.username: 'sentry@example.com'
mail.password: ''
mail.use-tls: false
mail.use-ssl: false
```

Testing the email configuration using the admin panel works however and this email together with the weekly / daily summary are send correctly.

**Comment by ethanhs** [comment]
Hm, can you confirm that the email did not get rejected by your email server? Also have you changed your .env file?

**Comment by afaianswq** [comment]
Email should only be sent if you have created an alert.
