### ISSUE TITLE
TLS/SSL and Kerberos Support

### ISSUE THREAD

**Issue by ozankyncu** [getsentry/self-hosted#1747]
### Problem Statement

Hello,

Is there support for Sentry self-hosted TLS/SSL and Kerberos?

If not, what are the alternatives? Can you share your documents?

Best regard.

**Comment by ozankyncu** [comment]
Thank you for your quick reply.

We are using Cloudera Kafka in our self-hosted use instead of default Kafka. So Kerberos authentication must for Cloudera Kafka. 

Is there any solution you can point me to use Kerberos?

**Comment by ethanhs** [comment]
You might be able to use kdcproxy, but unfortunately I don't think we support this configuration, nor plan to. We use confluence kafka and I can't promise using a different kafka implementation will work.
