### ISSUE TITLE
SMTP configuration working unexpectedly

### ISSUE THREAD

**Issue by maciejpankanin** [getsentry/self-hosted#1748]
### Self-Hosted Version

22.9.0

### CPU Architecture

x86_64

### Docker Version

20.10.8

### Docker Compose Version

1.29.2

### Steps to Reproduce

1. Comment out `mail.host: 'smtp'` line in `sentry/config.yml`
2. Start Sentry.

### Expected Result

When I log in as admin I get SMTP config prompt and can configure it.

<img width="613" alt="image" src="https://user-images.githubusercontent.com/33896387/195531753-bbb52a04-88fb-45ce-a0ef-d4001dd41ea0.png">

### Actual Result

I cannot save SMTP Host setting.

I looked into Developer Tools - getting 403 status for request which sets host, it happens no matter host I try.

**Comment by ethanhs** [comment]
Hm, if you fill in your SMTP server's config in the config.yml file does it work?

**Comment by maciejpankanin** [comment]
It does but that is not my point. Point is that if I configure it as explained I cannot do anything, clicking _Continue_ button and nothing happens, cannot also dismiss this configuration in any way.
