### ISSUE TITLE
Post process forwarder restarts every 5 seconds

### ISSUE THREAD

**Issue by izica** [getsentry/self-hosted#1751]
### Self-Hosted Version

22.9.0

### CPU Architecture

x86_64

### Docker Version

Docker version 20.10.12, build 20.10.12-0ubuntu4

### Docker Compose Version

docker-compose version 1.29.2, build unknown

### Steps to Reproduce

0. vps: 4 cpu, 12gb
1. ./install
2. docker-compose up -d

### Expected Result

success

### Actual Result

post-process-forwarder_1                    | 07:03:59 [INFO] sentry.plugins.github: apps-not-configured
post-process-forwarder_1                    | 07:03:59 [INFO] sentry.eventstream.kafka.backend: Starting post process forwarder to consume all messages
post-process-forwarder_1                    | Traceback (most recent call last):
post-process-forwarder_1                    |   File "/usr/local/bin/sentry", line 8, in <module>
post-process-forwarder_1                    |     sys.exit(main())
post-process-forwarder_1                    |   File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 188, in main
post-process-forwarder_1                    |     func(**kwargs)
post-process-forwarder_1                    |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
post-process-forwarder_1                    |     return self.main(*args, **kwargs)
post-process-forwarder_1                    |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
post-process-forwarder_1                    |     rv = self.invoke(ctx)
post-process-forwarder_1                    |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
post-process-forwarder_1                    |     return _process_result(sub_ctx.command.invoke(sub_ctx))
post-process-forwarder_1                    |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
post-process-forwarder_1                    |     return _process_result(sub_ctx.command.invoke(sub_ctx))
post-process-forwarder_1                    |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
post-process-forwarder_1                    |     return ctx.invoke(self.callback, **ctx.params)
post-process-forwarder_1                    |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
post-process-forwarder_1                    |     return __callback(*args, **kwargs)
post-process-forwarder_1                    |   File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
post-process-forwarder_1                    |     return f(get_current_context(), *args, **kwargs)
post-process-forwarder_1                    |   File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 69, in inner
post-process-forwarder_1                    |     return ctx.invoke(f, *args, **kwargs)
post-process-forwarder_1                    |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
post-process-forwarder_1                    |     return __callback(*args, **kwargs)
post-process-forwarder_1                    |   File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
post-process-forwarder_1                    |     return f(get_current_context(), *args, **kwargs)
post-process-forwarder_1                    |   File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 29, in inner
post-process-forwarder_1                    |     return ctx.invoke(f, *args, **kwargs)
post-process-forwarder_1                    |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
post-process-forwarder_1                    |     return __callback(*args, **kwargs)
post-process-forwarder_1                    |   File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/run.py", line 363, in post_process_forwarder
post-process-forwarder_1                    |     eventstream.run_post_process_forwarder(
post-process-forwarder_1                    |   File "/usr/local/lib/python3.8/site-packages/sentry/utils/services.py", line 127, in <lambda>
post-process-forwarder_1                    |     context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
post-process-forwarder_1                    |   File "/usr/local/lib/python3.8/site-packages/sentry/eventstream/kafka/backend.py", line 288, in run_post_process_forwarder
post-process-forwarder_1                    |     self.run_batched_consumer(
post-process-forwarder_1                    |   File "/usr/local/lib/python3.8/site-packages/sentry/eventstream/kafka/backend.py", line 254, in run_batched_consumer
post-process-forwarder_1                    |     consumer = self._build_consumer(
post-process-forwarder_1                    |   File "/usr/local/lib/python3.8/site-packages/sentry/eventstream/kafka/backend.py", line 218, in _build_consumer
post-process-forwarder_1                    |     assert self.topic == self.transactions_topic
post-process-forwarder_1                    | AssertionError

**Comment by lbogdan** [comment]
Getting this too, with latest `master`.
