### ISSUE TITLE
Ask for user account information at the beginning

### ISSUE THREAD

**Issue by lbogdan** [getsentry/self-hosted#1752]
### Problem Statement

Right now, the initial user account information (email, password) is asked towards the end of the installation, before shutting down the whole stack, which takes a little while.

### Solution Brainstorm

It would be nice to ask for it at the beginning of the installation, so the rest of the installation is non-interactive.

Later edit: it would be even nicer to be able to set it from the command line / environment variables.

**Comment by hubertdeng123** [comment]
Hi there, you're actually able to set the user account information after installing through the command line. It would look something like this

```
./install.sh --skip-user-creation --report-self-hosted-issues
docker-compose --ansi never run --rm web createuser --force-update --superuser --email user@example.com --password secret
```
