### ISSUE TITLE
Release 22.11.0

### ISSUE THREAD

**Issue by ethanhs** [getsentry/self-hosted#1754]
[22.10.0](https://github.com/getsentry/self-hosted/issues/1701) | **22.11.0** | [22.12.0](https://github.com/getsentry/self-hosted/issues/1813)

- [x] https://github.com/getsentry/publish/issues/1566
- [x] https://github.com/getsentry/publish/issues/1568
- [x] https://github.com/getsentry/publish/issues/1567
- [x] https://github.com/getsentry/publish/issues/1571
- [x] https://github.com/getsentry/publish/issues/1569
- [x] https://github.com/getsentry/publish/issues/1570
- [x] [22.12.0 issue](https://github.com/getsentry/self-hosted/issues/new)
- [x] Say something in the release notes about the window global export of the deprecated `Form` object being unused—see verbiage in comment below.
- [x] Say something about [consolidating self-hosted snuba/cron containers](https://github.com/getsentry/self-hosted/issues/1763) in the future

**Comment by chadwhitacre** [comment]
> The deprecated `Form` interface exposed on the `window.SentryApp` global has been removed. 3rd party old-style plugins may have used this to to display complex Forms. [[PR 40830](https://github.com/getsentry/sentry/pull/40830)]

**Comment by chadwhitacre** [comment]
@hubertdeng123 Done here, ya?

**Comment by hubertdeng123** [comment]
yep done
