### ISSUE TITLE
Standardize e2e testing

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/self-hosted#1756]
We have a messy mess of integration testing:

1. [`test.sh`](https://github.com/getsentry/self-hosted/blob/65fa3d4b8aadc6c1aa1879edb4f67025b8912e69/test.sh)
1. [`integration-test.sh`](https://github.com/getsentry/self-hosted/blob/65fa3d4b8aadc6c1aa1879edb4f67025b8912e69/integration-test.sh)
1. [`self-hosted` cloudbuild](https://github.com/getsentry/self-hosted/blob/65fa3d4b8aadc6c1aa1879edb4f67025b8912e69/cloudbuild.yaml#L12-L50)
1. [`sentry` cloudbuild](https://github.com/getsentry/sentry/blob/d198d75981d88851dffd5e76970f01bbd89a5e54/docker/cloudbuild.yaml#L35-L69)
1. [`snuba` cloudbuild](https://github.com/getsentry/snuba/blob/4879b84c2ad63205f237406f06dbef655b7ba05e/cloudbuild.yaml#L42-L80)
1. [`relay` cloudbuild](https://github.com/getsentry/relay/blob/dd82727766e8a9c65168f21f5f972307d7c1209d/cloudbuild.yaml#L64-L82)

We should standardize this in a way that ensures that e2e is kept in sync across all consumer repos (`sentry`, `snuba`, `relay`) in addition to local environments and `self-hosted` cloudbuild.

Task list:

1. [x] Review cloudbuild configs and write new Github Action based on them (needs to handle custom sentry/snuba/relay containers etc)
1. [x] Add new Github Action to CI pipelines in repos we care about as allow-fail
    1. [x] https://github.com/getsentry/self-hosted/pull/1806
    1. [x] https://github.com/getsentry/relay/pull/1592
    1. [x] https://github.com/getsentry/snuba/pull/3401
    2. [x] https://github.com/getsentry/sentry/pull/42124
1. [x] https://github.com/getsentry/self-hosted/issues/1867
1. [x] Add Docker container deployment (set up Dockerhub access token)
    1. [x] relay
    1. [x] snuba
    1. [x] sentry
1. [x] After two days, make the Action required
1. [x] Remove old Google Cloud build check
    1. [x] https://github.com/getsentry/relay/pull/1721
    1. [x] https://github.com/getsentry/snuba/pull/3557
    1. [x] https://github.com/getsentry/sentry/pull/42641
    1. [x] https://github.com/getsentry/self-hosted/pull/1880

**Comment by BYK** [comment]
Historical context:

The reason for using Cloudbuild is two fold:
1. Performance: in the bad old days we did not have GitHub Actions and anything else was too slow or limited in terms of memory (no our build is not demanding :P). Since e2e has been working quite well for some time in self-hosted through GHA, I think that can be revisited. Even more, using hosted-runners for GHA might be a good option too.
2. The idea was to build the Sentry image and use the same image for single-tenant which lives in GCP. It was a hassle to manage secrets etc, again in the bad old days. Now in the bright future, we have OIDC which should also fix that problem: https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-google-cloud-platform

Also, while we are at that, considering switching to GitHub packages instead of Docker Hub may be beneficial both in terms of performance _and_ budget.

**Comment by ethanhs** [comment]
Thanks for the background @BYK! I agree a custom action seems like the best way to standardize here.

**Comment by ethanhs** [comment]
Plan for switching over to the new action:

1. [ ] Review cloudbuild configs and write new Github Action based on them (needs to handle custom sentry/snuba/relay containers etc)
1. [ ] Add new Github Action to CI pipelines in repos we care about as allow-fail
1. [ ] After a while, make the Action required
1. [ ] Remove old Google Cloud build check

**Comment by ethanhs** [comment]
Repo is live at https://github.com/getsentry/action-self-hosted-e2e-tests. Planning on adding it to self-hosted today, the rest of the repos next week.

**Comment by ethanhs** [comment]
All of the actions are now deployed! Need to figure out the docker image deployment situation but once that is done we can start the clock on replacing GCB.

**Comment by chadwhitacre** [comment]
> All of the actions are now deployed! Need to figure out the docker image deployment situation but once that is done we can start the clock on replacing GCB.

FTR we decided to keep Docker build and push in GCB rather than moving to GHA, mostly for security concerns. Now we're trying to kick off the e2e tests in GHA from GCB via a webhook. When we moved GitHub behind Okta I lost access to our bot accounts, so I'm trying [to recover that](https://getsentry.atlassian.net/servicedesk/customer/portal/4/ISD-3990) so I can [set up a PAT](https://getsentry.atlassian.net/servicedesk/customer/portal/4/ISD-3978).

**Comment by chadwhitacre** [comment]
Bot accounts recovered! I created a (new-style) PAT and am looking at setting it up in GCB.

**Comment by chadwhitacre** [comment]
New-style PATs must expire, going with classic.

**Comment by chadwhitacre** [comment]
GCB secrets process is complicated ...

**Comment by chadwhitacre** [comment]
[🐰🕳️](https://github.com/getsentry/self-hosted/issues/1867)

**Comment by chadwhitacre** [comment]
Hit a wall, [escalated to Ops](https://getsentry.atlassian.net/browse/OPS-2744).

**Comment by chadwhitacre** [comment]
Decided to go with publishing from GHA to Docker after all.

> **Any concerns about keeping the dockerhub secret secure in Github Actions?**
> 
> I don't have any concern, no -- I think we should do all the pushing in GHA instead of having to do complicated back and forth between GCB and GHA
> 
> **I assume only Sentry employees will be able to kick off a release and publish to DockerHub?**
> 
> **The main concern with pushing from Github is people aren't going to check PRs for exposing secrets before hitting the approve button to run CI for PRs from external contributors, so if there is a PR from an outside contributor they might be able to expose the secret**
> 
> they won't have access to secrets unless they are sentry employees
> 
> **Even with a PR to getsentry/sentry?**
> 
> yep. only pull_request_target will have secrets available and we're very particular about what we put into that

I created a token in Docker Hub and set it as a repo secret in `sentry`, `relay`, and `snuba`.

**Comment by ethanhs** [comment]
This is now done!

**Comment by chadwhitacre** [comment]
Had to do some cleanup in https://github.com/getsentry/action-self-hosted-e2e-tests/pull/3 ftr.
