### ISSUE TITLE
Make e2e tests more thorough

### ISSUE THREAD

**Issue by ethanhs** [getsentry/self-hosted#1761]
This tests code deeper in the pipeline that might have caught https://github.com/getsentry/self-hosted/issues/1668

Task list:
1. [x] https://github.com/getsentry/self-hosted/issues/1888
1. [x] https://github.com/getsentry/self-hosted/issues/1887

**Comment by BYK** [comment]
@ethanhs the backup/restore dance is woefully undertested. I did some fixes and improvements there while writing the docs (it did not even work before that 😅). In the upgrade scenario, you may wanna add a backup/restore scenario too. That said it should only matter when there's a model/migration change.

**Comment by ethanhs** [comment]
Good idea! I think we've seen a couple of tickets about backup/restore, so it would be good to test that.

**Comment by ethanhs** [comment]
Arpad suggested for testing symbolicator workflows:

> That seems like a good idea, yes. To cover this particular usecase, you would need a test that uses all the builtin symbol servers. A Windows minidump perhaps. We should have one already in the main Sentry tests, though those tests are always testing the very latest symbolicator master.

**Comment by chadwhitacre** [comment]
> backup/restore

Punting to https://github.com/getsentry/sentry/issues/36868, need to address more comprehensively.

**Comment by chadwhitacre** [comment]
What else could/should we test?

SSO & integrations ... would involve many more moving parts, more difficult to test.

**Comment by chadwhitacre** [comment]
Profiling should come in with #1838.

Replays (#1873)? Dynamic Sampling?

**Comment by chadwhitacre** [comment]
FE? Not really worth doing here, leave that in `sentry`.

We want to exercise the containers, that's really the scope.

Do we have tests for updating settings?

**Comment by chadwhitacre** [comment]
Closing with 1 of 2 completed.
