### ISSUE TITLE
Check health of containers in e2e tests

### ISSUE THREAD

**Issue by ethanhs** [getsentry/self-hosted#1762]
We want to check that all the containers are healthy after we run the event through the test instance - this catches any containers that crash due to an issue at runtime. 

Currently we only check container health in the installer.

**Comment by BYK** [comment]
Did this actually happen causing a bug getting through? If so I'm willing to submit a PR :)

**Comment by ethanhs** [comment]
Yes, just before the 22.10.0 release, the error and transaction pipelines were split, causing https://github.com/getsentry/sentry/issues/40120

If you would like to submit a PR to add this that would be great, but I think if we are going to centralize our e2e tests (#1756 for anyone reading along) we should probably hold off until that is done first.
