### ISSUE TITLE
sentry-self-hosted-nginx-1：Bind for 0.0.0.0:9000 failed: port is already allocated

### ISSUE THREAD

**Issue by wangyingsi** [getsentry/self-hosted#1764]
### Self-Hosted Version

22.10.0

### CPU Architecture

x86-64

### Docker Version

20.10.7

### Docker Compose Version

v2.7.0

### Steps to Reproduce

1.  ./install.sh 
2.  docker-compose up -d

### Expected Result

all containers are running 

### Actual Result

 ⠿ Container sentry-self-hosted-snuba-transactions-consumer-1               Running                                                     0.0s
 ⠿ Container sentry-self-hosted-snuba-subscription-consumer-events-1        Running                                                     0.0s
 ⠿ Container sentry-self-hosted-cron-1                                      Running                                                     0.0s
 ⠿ Container sentry-self-hosted-subscription-consumer-transactions-1        Running                                                     0.0s
 ⠿ Container sentry-self-hosted-worker-1                                    Running                                                     0.0s
 ⠿ Container sentry-self-hosted-ingest-consumer-1                           Running                                                     0.0s
 ⠿ Container sentry-self-hosted-sentry-cleanup-1                            Running                                                     0.0s
 ⠿ Container sentry-self-hosted-post-process-forwarder-transactions-1       Running                                                     0.0s
 ⠿ Container sentry-self-hosted-post-process-forwarder-errors-1             Running                                                     0.0s
 ⠿ Container sentry-self-hosted-subscription-consumer-events-1              Running                                                     0.0s
 ⠿ Container sentry-self-hosted-web-1                                       Healthy                                                     2.5s
 ⠿ Container sentry-self-hosted-relay-1                                     Running                                                     0.0s
 ⠿ Container sentry-self-hosted-nginx-1                                     Starting                                                    3.1s
Error response from daemon: driver failed programming external connectivity on endpoint sentry-self-hosted-nginx-1 (26e0aa0495906735d30b1506bd546de1c787d9c6b03e42a466722447198ed118): Bind for 0.0.0.0:9000 failed: port is already allocated

**Comment by linpan** [comment]
Creating sentry-self-hosted_nginx_1                                      ... error
ERROR: for sentry-self-hosted_nginx_1  Cannot start service nginx: driver failed programming external connectivity on endpoint sentry-self-hosted_nginx_1 (dd8602536f566c624fb96c74d9aa8877322605638508452f5fca8b670ca7e909): Bind for 0.0.0.0:9000 failed: port is already allocated

**Comment by hubertdeng123** [comment]
@linpan sounds like maybe some other process is using the port 9000
