### ISSUE TITLE
How save all events during db migration and increase insert rate of events into clickhouse?

### ISSUE THREAD

**Issue by RedShiba** [getsentry/self-hosted#1767]
### Self-Hosted Version

21.5.0 

### CPU Architecture

x86_64

### Docker Version

20.10.16

### Docker Compose Version

1.28.5

### Steps to Reproduce

Hey, maybe someone could help me here. I'm trying to update sentry 9.1.2 to 21.5.0.  
Events are getting deleted during db migration. I'm assuming, the reason of default_retention variable
https://github.com/getsentry/sentry/blob/21.5.0/src/sentry/migrations/0024_auto_20191230_2052.py#L33 
I don't use SENTRY_EVENT_RETENTION_DAYS or system.event-retention-days, , so its not set and by default system.event-retention-days = 0. Also I deleted all cleanup jobs from docker-compose.yaml.
Is there any way to keep all my events(14kk) during migration to avoid setting variable SENTRY_EVENT_RETENTION_DAYS=700000 ? (This value help to save all my events and not get error like "out of range" during the exec of https://github.com/getsentry/sentry/blob/21.6.0/src/sentry/migrations/0024_auto_20191230_2052.py#L37.)

and second question:
How could I increase insert rate of events into clickhouse during migration? As far as I can see speed is 100 events per sec. Could I somehow change it, e.g. 10k events per sec? I have 14kk events, migration takes more than a day.

Thanks.

### Expected Result

all events was moved during db migrations.

### Actual Result

events are getting deleted if not use SENTRY_EVENT_RETENTION_DAYS.

**Comment by hubertdeng123** [comment]
The `SENTRY_EVENT_RETENTION_DAYS` is a variable that must be used now with the sentry cleanup cron job. However, if the cleanup jobs are deleted I would assume that we wouldn't be deleting those events during the upgrade. Are events still being deleted after setting the `SENTRY_EVENT_RETENTION_DAYS` and deletion of cron cleanup jobs?

**Comment by hubertdeng123** [comment]
For your answer about clickhouse's rate of insert, I'm not too sure but after a quick glance on their site they said to expect a throughput of 100 queries per second.

https://clickhouse.com/docs/en/about-us/performance/

**Comment by RedShiba** [comment]
> The `SENTRY_EVENT_RETENTION_DAYS` is a variable that must be used now with the sentry cleanup cron job. However, if the cleanup jobs are deleted I would assume that we wouldn't be deleting those events during the upgrade. Are events still being deleted after setting the `SENTRY_EVENT_RETENTION_DAYS` and deletion of cron cleanup jobs?

Yes.
SENTRY_EVENT_RETENTION_DAYS override default value of system.event-retention-days
https://github.com/getsentry/self-hosted/blob/21.5.0/sentry/sentry.conf.example.py#L62
If I'm not set SENTRY_EVENT_RETENTION_DAYS, system.event-retention-days would be equal 90(cuz default). It comes to this variable
https://github.com/getsentry/sentry/blob/21.5.0/src/sentry/migrations/0024_auto_20191230_2052.py#L33 (sentry execute this script during migration)
When we call get_events function during db migration
https://github.com/getsentry/sentry/blob/21.5.0/src/sentry/migrations/0024_auto_20191230_2052.py#L35
 sentry get events for the last 90days and migrate it. All other older  events being deleted.

pgsql logs during db migration. Sentry make select of events for the past 90days.
`"SELECT",2022-10-10 19:36:24 UTC,2/318479,0,LOG,00000,"duration: 7324.884 ms  statement: SELECT ""sentry_message"".""id"", ""sentry_message"".""group_id"", ""sentry_message"".""message_id"", ""sentry_message"".""project_id"", ""sentry_message"".""message"", ""sentry_message"".""platform"", ""sentry_message"".""datetime"", ""sentry_message"".""time_spent"", ""sentry_message"".""data"" FROM ""sentry_message"" WHERE (""sentry_message"".""datetime"" >= '2022-07-12T19:36:51.339901+00:00'::timestamptz AND ""sentry_message"".""group_id"" IS NOT NULL AND ""sentry_message"".""datetime"" <= '2022-10-10T19:36:51.339901+00:00'::timestamptz) ORDER BY ""sentry_message"".""id"" ASC LIMIT 100",,,,,,,,,""`

and process 808922(but actually I have 14kk events)

   Applying sentry.0022_merge... OK
  Applying sentry.0023_hide_environment_none_20191126... OK
  Applying sentry.0024_auto_20191230_2052...Events to process: 808922

I'm not sure cleanup jobs play role during db migration. But SENTRY_EVENT_RETENTION_DAYS influence on migration even if cleanup jobs are absent.
Even if I delete from sentry.conf this row
https://github.com/getsentry/self-hosted/blob/21.5.0/sentry/sentry.conf.example.py#L62
It will look like system.event-retention-days is unset and in this case SENTRY_EVENT_RETENTION_DAYS doesn't play any role during upgrade(db migration). BUT script that I mentioned above has their own default retention 
https://github.com/getsentry/sentry/blob/21.5.0/src/sentry/migrations/0024_auto_20191230_2052.py#L32

So, the only one solution I found is set SENTRY_EVENT_RETENTION_DAYS equal 700k and as a result the sentry make select for the last 700k days and migrate all my events.

pgsql log when I set SENTRY_EVENT_RETENTION_DAYS = 700000:
`SELECT ""sentry_message"".""id"", ""sentry_message"".""group_id"", ""sentry_message"".""message_id"", ""sentry_message"".""project_id"", ""sentry_message"".""message"", ""sentry_message"".""platform"", ""sentry_message"".""datetime"", ""sentry_message"".""time_spent"", ""sentry_message"".""data"" FROM ""sentry_message"" WHERE (""sentry_message"".""datetime"" >= '0106-03-31T22:19:51.431039+00:00'::timestamptz AND ""sentry_message"".""datetime"" <= '2022-10-12T22:19:51.431039+00:00'::timestamptz AND ""sentry_message"".""group_id"" IS NOT NULL AND ""sentry_message"".""id"" >= 12494813) ORDER BY ""sentry_message"".""id"" ASC LIMIT 100",,,,,,,,,""`

My question was maybe I got it wrong and there is another way to migrate all my events and not getting deleted. I just thought the sentry migrate all events during upgrade by default, but actually isn't.

**Comment by hubertdeng123** [comment]
> My question was maybe I got it wrong and there is another way to migrate all my events and not getting deleted. I just thought the sentry migrate all events during upgrade by default, but actually isn't.

Got it, yeah unfortunately this variable will need to be set. Glad you were able to resolve this yourself though 😁 Is there anything else I can do to help you here or can I close this ticket out?

**Comment by RedShiba** [comment]
> > My question was maybe I got it wrong and there is another way to migrate all my events and not getting deleted. I just thought the sentry migrate all events during upgrade by default, but actually isn't.
> 
> Got it, yeah unfortunately this variable will need to be set. Glad you were able to resolve this yourself though 😁 Is there anything else I can do to help you here or can I close this ticket out?

would be great to mention it somewhere like "sentry doesn't migrate all events by default and this variable obligatory if you want save all events during migration" or re-write get_event function. But it's up to you (:

Back to clickhouse. I didn't get could I somehow increase rate of insert? e.g. read and insert more rows 
I see in clickhouse logs it inserting ~150-300 rows per sec, if I got it right
`[ 12967 ] {67ea69b0-1451-4b2b-af0b-223661bddb6e} <Information> executeQuery: Read 264 rows, 421.58 KiB in 0.024 sec., 11157 rows/sec., 17.40 MiB/sec.
[ 12967 ] {efeafe8d-c1a1-4127-87b7-bb678e090acd} <Debug> executeQuery: (from [::ffff:]:44356, user: sentry_clickhouse) INSERT INTO sentry.sentry_local   FORMAT JSONEachRow
[ 12967 ] {e8c918b4-7c50-4d8e-bc4f-6f77a83d4317} <Information> executeQuery: Read 207 rows, 362.63 KiB in 0.023 sec., 9157 rows/sec., 15.67 MiB/sec.
[ 12967 ] {67ea69b0-1451-4b2b-af0b-223661bddb6e} <Debug> executeQuery: (from [::ffff:]:44356, user: sentry_clickhouse) INSERT INTO sentry.sentry_local   FORMAT JSONEachRow`

maybe it somehow depends on step [variable](https://github.com/getsentry/sentry/blob/21.5.0/src/sentry/migrations/0024_auto_20191230_2052.py#L74) ? and we can change it or doesn't override [default](https://github.com/getsentry/sentry/blob/930550c5bceb7a2bb698bdb4b67ae3d7f7f5fbfe/src/sentry/utils/query.py#L72) step value ? I'm just digging into this cause my 14kk events gonna being migrated more than a day :(

**Comment by RedShiba** [comment]
hmmm...as I mentioned above rate of insert ~150-300 rows per sec during upgrade to 21.5.0. 
But when I upgrade sentry to 20.12.1 rate of insert ~50-100 rows per sec.  I'll try to upgrade to 21.5.0 again to be sure it was not a coincidence, cuz 250 rows per sec(on average) much better and my migration should takes ~14h. If someone knows why is there such difference in amount of  inserting rows between 20.12.1 and 21.5.0 share knowledge please (:
