### ISSUE TITLE
Can not select custom metrics as aggregate args

### ISSUE THREAD

**Issue by TonyGui7** [getsentry/self-hosted#1769]
### Self-Hosted Version

22.10.0

### CPU Architecture

x86_64

### Docker Version

20.10.13

### Docker Compose Version

2.3.3

### Steps to Reproduce

1. add "organizations:dashboards-mep" flag to sentry.conf.py file
2. execute install.sh and start service
3. enter localhost:9000 in browser 
4. select "Errors and Transactions" within "Choose your dataset " option while creating custom widget
5. can not find custom metrics had been reported in "Choose your columns" options

### Expected Result

show custom metrics(measurements.xxx &) that had been reported

### Actual Result

not show custom metrics

**Comment by TonyGui7** [comment]
![7FFB3E8E-D691-429E-BB5C-21C3FC4D3CE2](https://user-images.githubusercontent.com/19777415/196624788-1b04742e-5e1a-4167-bc61-97dd70215a9d.png)

**Comment by hubertdeng123** [comment]
Hey there @TonyGui7 , are you using SaaS or self-hosted? It looks like the screenshot you've linked is from SaaS since it has profiling and replays enabled

**Comment by TonyGui7** [comment]
> Hey there @TonyGui7 , are you using SaaS or self-hosted? It looks like the screenshot you've linked is from SaaS since it has profiling and replays enabled

I am using self-hosted.  Because I add "organizations:profiling" and other flags to sentry.conf.py file. 
![7667EFDE-51E0-4C8F-A045-9E3257B44B0E](https://user-images.githubusercontent.com/19777415/197092139-27cd18af-10d6-49c8-8230-c3f38059f019.png)

Since "video_prepare" metric can not be selected with default configuration int sentry.conf.py file,   I decided to read the source code of [getSentry/Sentry](https://github.com/getsentry/sentry) and found a lot of feature flags that control corresponding function, but I don't know the flag that enables custom metric display in custom dashboard, so I add all of flags I found.

**Comment by TonyGui7** [comment]
I add "organizations:dashboards-mep" and "organizations:mep-rollout-flag" as well, but it still can't work. 
![6B3C9B15-6C33-49C1-8B7D-F375C9E0534E](https://user-images.githubusercontent.com/19777415/197095424-97c4ff32-bdc0-4a8f-8584-178a0d32367b.png)

The request  will return response that has "video_prepare" measurement if I use the service that Sentry Team deploy(host: sentry.io)
![AFE7BD36-A083-48B4-BF78-FF6289C6FD8C](https://user-images.githubusercontent.com/19777415/197096403-ed08d3f7-8d7f-4b1e-9d71-dfe2dbe7b9b6.png)

but the response is empty(http code 200) if I use service I deployed on my mac(host: localhost:9000), I guess it has something to do with configuration in \relay\config.yml

**Comment by hubertdeng123** [comment]
I'm not quite familiar with what `video_prepare` does but I'm wondering if it has something to do with our session replay feature.

Can I ask what your use case is here? We disable certain features for self-hosted because either the features are in beta/alpha and we know that these features will require significant maintenance burden.

**Comment by TonyGui7** [comment]
> I'm not quite familiar with what `video_prepare` does but I'm wondering if it has something to do with our session replay feature.
> 
> Can I ask what your use case is here? We disable certain features for self-hosted because either the features are in beta/alpha or we know that these features will require significant maintenance burden.

oh, "video_prepare" is the metric that I reported through SDK, to record video loading time, the key code is below
```
ISpan span = Sentry.getSpan();
span.setMeasurement("video_prepare", preparingTime, MeasurementUnit.Duration.MILLISECOND)
```

My use case is that I want to report several custom performance metrics of our project to Sentry, like heap memory,  video loading time &etc.   So I can make a judgement on performance optimization by visualization that Sentry provide below.
![F59ED326-728F-4BAB-8221-8C3CB59F4A4C](https://user-images.githubusercontent.com/19777415/197666604-a3abd252-892e-43f9-83dc-5998675e3dcb.png)

However, the judgement can not be done if custom metrics that I have reported can't be selected as aggregate args
