### ISSUE TITLE
Error during download docker image

### ISSUE THREAD

**Issue by teo666** [getsentry/self-hosted#1770]
### Self-Hosted Version

22.10.0

### CPU Architecture

x86_64

### Docker Version

20.10.18

### Docker Compose Version

2.11.1

### Steps to Reproduce

1. download **tar** from https://github.com/getsentry/self-hosted/archive/refs/tags/22.10.0.tar.gz
2. extract
3. enter extracted dir
4. ./install.sh (any file change)

### Expected Result

installation ends

### Actual Result

`ERROR: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed`

[sentry_install_log-2022-10-19_16-28-32.txt](https://github.com/getsentry/self-hosted/files/9821373/sentry_install_log-2022-10-19_16-28-32.txt)

**Comment by hubertdeng123** [comment]
Just to confirm, are you receiving this error after a clean install? Or after changing some file?

**Comment by teo666** [comment]
Clean install, even after removing all sentry related docker images.

**Comment by hubertdeng123** [comment]
Hmmm, have you checked to make sure there aren't any network errors involved while pulling docker images?

**Comment by teo666** [comment]
Sure. I tried three time at least, and also reinstalled 22.8 sentry version to check if the problem was caused by something corrupted in docker. I will try reinstall tomorrow anyway

**Comment by teo666** [comment]
UPDATE: I tried on another PC and installation complete successfully.
I also noticed that installation completes much more faster than yesterday.

Can my error caused by momentary problem with docker container registry?

**Comment by hubertdeng123** [comment]
Awesome, great to hear! Yeah, I assumed the error was with connectivity to the docker container registry

**Comment by aminvakil** [comment]
@sharokh1 Does `docker pull hello-world` work?

**Comment by sharokh1** [comment]
> @sharokh1 Does `docker pull hello-world` work?

Yep, that seems to work.

**Comment by sharokh1** [comment]
created new issue as this one is closed #1781
