### ISSUE TITLE
What runs first: config.yml or sentry.conf.py?

### ISSUE THREAD

**Issue by hach-que** [getsentry/self-hosted#1779]
### Self-Hosted Version

22.9.0

### CPU Architecture

x86_64

### Docker Version

N/A - Kubernetes

### Docker Compose Version

N/A - Kubernetes

### Steps to Reproduce

1. Set up a `config.yml` file with this setting:

```
filestore.backend: "not-set"
```

2. Set up a `sentry.conf.py` file with this content:

```
print("Configuring SENTRY_OPTIONS filestore.backend")
SENTRY_OPTIONS['filestore.backend'] = "s3"
SENTRY_OPTIONS['filestore.options'] = {
  "access_key": "...",
  "secret_key": os.getenv("FILESTORE_SECRET_KEY", ""),
  "bucket_name": "sentry",
  "endpoint_url": "...",
  "signature_version": "s3v4"
}
print("Configuring SENTRY_OPTIONS filestore.backend: " + SENTRY_OPTIONS['filestore.backend'])
```

3. Watch the application emit the correct print statements on startup:

```
Configuring SENTRY_OPTIONS filestore.backend
Configuring SENTRY_OPTIONS filestore.backend: s3
```

4. Watch file access not work because Sentry tries to use "not-set" as the file provider:

```
ImportError: not-set doesn't look like a module path
```

### Expected Result

It should be trying to use the `s3` file storage system, because that is what is set in `sentry.conf.py`.

I can't figure out *why* this doesn't work, since mail configuration is done in `sentry.conf.py` in much the same way and works fine:

```
SENTRY_OPTIONS['mail.backend'] = os.getenv("SENTRY_EMAIL_BACKEND", "smtp")
```

For additional context, I've run into this issue while trying to move secrets from the the `config.yml` file (which in Kubernetes is stored as a configmap and easily visible) to secret-based environment variables. By doing this, it prevents the secrets from having to be stored in the Git repository for `values.yaml` and prevents them from appearing when Helm runs (since they would otherwise appear in the build output as they are just part of the configmap).

### Actual Result

Refer to steps to reproduce.

**Comment by hubertdeng123** [comment]
The reason why this is happening is because the `config.yml` takes priority over `sentry.conf.py`. It's overriding the settings in `sentry.conf.py`. You can take a look at this code here:
https://github.com/getsentry/sentry/blob/master/src/sentry/runner/initializer.py#L153

**Comment by ethanhs** [comment]
I should also mention that we don't support Kubernetes as an official way to deploy Sentry self-hosted, since there can be so many different environments. We generally recommend using SaaS if you need scale greater than the docker-compose setup can handle.
