### ISSUE TITLE
failed to solve: sentry-self-hosted-local: pull access denied while trying to install

### ISSUE THREAD

**Issue by sharokh1** [getsentry/self-hosted#1781]
### Self-Hosted Version

22.10.0

### CPU Architecture

aarch64

### Docker Version

20.10.20

### Docker Compose Version

2.12.0

### Steps to Reproduce

1. downloaded latest version or git clone latest commit.
2. ./install.sh

### Expected Result

install succesful

### Actual Result

```
failed to solve: sentry-self-hosted-local: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
Error in build-docker-images.sh:7.
'$dc build --build-arg "http_proxy=${http_proxy:-}" --build-arg "https_proxy=${https_proxy:-}" --build-arg "no_proxy=${no_proxy:-}" --force-rm' exited with status 17
error-handling.sh: line 191: jq: command not found

```

**Comment by multinerd** [comment]
I am having the same issue. 
Logs: https://gist.github.com/multinerd/6515d83b1bcbed968c78f23be64df7ea

**Comment by ethanhs** [comment]
@sharokh1 ARM is not currently supported outside of macOS, see https://github.com/getsentry/self-hosted/issues/1585.

@multinerd It looks like you may have an old version of `docker-compose` installed as well as `docker compose`? If that is not the issue please open a new issue.

**Comment by sharokh1** [comment]
@ethanhs so where does it say I am not using macOS ? please do not make assumptions and close the issue...

**Comment by multinerd** [comment]
> @multinerd It looks like you may have an old version of `docker-compose` installed as well as `docker compose`? If that is not the issue please open a new issue.

Yes, i had switched docker-compose back to v1 to try to upgrade an existing instance to 21.6.3. Must have forgot to switch it back. My issue is resolved.

**Comment by ethanhs** [comment]
@sharokh1 fair point, apologies if I closed too quickly. The error seemed to have the same root cause though, since trying to pull an image we build locally so far as I had seen only happened due to trying to run on ARM. Glad things are working for you now.
