### ISSUE TITLE
Deployment in kvm prompts me with an error:The CPU your machine is running on does not support the SSE 4.2 instruction set

### ISSUE THREAD

**Issue by Winspain** [getsentry/self-hosted#1782]
### Self-Hosted Version

22.10.0

### CPU Architecture

x86_64

### Docker Version

19.03.9, build 9d988398e7

### Docker Compose Version

1.29.2

### Steps to Reproduce

1  ./install.sh
2  report an error

### Expected Result

correctly deploy

### Actual Result

The CPU your machine is running on does not support the SSE 4.2 instruction set

**Comment by ethanhs** [comment]
Yeah, I suppose if you pass through your CPU that it won't show up as a KVM processor? Does the machine you are running on actually support SSE 4.2?

**Comment by Winspain** [comment]
@ethanhs my host machine supports SSE 4.2,and i deployed successfully by skipping the IS_KVM codes
the machine can be correctly identified whether the kvm by the following command

```bash
[root@localhost ~]# dmesg |grep -i hypervisor
[    0.000000] Hypervisor detected: KVM

**Comment by ethanhs** [comment]
This should remain open until we merge https://github.com/getsentry/self-hosted/pull/1790 or a similar PR.
