### ISSUE TITLE
Problem setting password on Redis

### ISSUE THREAD

**Issue by zemestanzibaeman** [getsentry/self-hosted#1786]
### Self-Hosted Version

22.10.0

### CPU Architecture

x86_64

### Docker Version

20.10.20

### Docker Compose Version

v2.12.0

### Steps to Reproduce

Hello friends
I when in the file
sentry.conf.example.py
I set a password for redis when running install.sh I get the following error:

sentry.exceptions.InvalidConfiguration: AUTH <password> called without any password configured for the default user

How to set a password for Redis ؟

### Expected Result

set password

### Actual Result

sentry.exceptions.InvalidConfiguration: AUTH <password> called without any password configured for the default user

**Comment by hubertdeng123** [comment]
How are you setting the password for redis? This can be done with the env variable `SENTRY_REDIS_PASSWORD`
https://github.com/getsentry/sentry/blob/master/docker/sentry.conf.py#L85
