### ISSUE TITLE
install.sh:ERROR: for postgres  Cannot start service postgres: OCI runtime create failed: runc create failed: unable to start container process: exec: "/opt/sentry/postgres-entrypoint.sh"

### ISSUE THREAD

**Issue by damengzhang** [getsentry/self-hosted#1794]
### Self-Hosted Version

22.10.0

### CPU Architecture

x86_64

### Docker Version

20.10.7

### Docker Compose Version

1.29.2

### Steps to Reproduce

1、Download releaze zip
2、Unzip archive
3、run  install.sh

### Expected Result

install success

### Actual Result

 sudo bash install.sh
▶ Parsing command line ...

▶ Detecting Docker platform
Detected Docker platform is linux/amd64

▶ Initializing Docker Compose ...

▶ Setting up error handling ...

Hey, so ... we would love to automatically find out about issues with your
Sentry instance so that we can improve the product. Turns out there is an app
for that, called Sentry. Would you be willing to let us automatically send data
about your instance upstream to Sentry for development and debugging purposes?

  y / yes / 1
  n / no / 0

(Btw, we send this to our own self-hosted Sentry instance, not to Sentry SaaS,
so that we can be in this together.)

Here's the info we may collect:

  - OS username
  - IP address
  - install log
  - runtime errors
  - performance data

Thirty (30) day retention. No marketing. Privacy policy at sentry.io/privacy.

y or n? y

Thank you. To avoid this prompt in the future, use one of these flags:

  --report-self-hosted-issues
  --no-report-self-hosted-issues

or set the REPORT_SELF_HOSTED_ISSUES environment variable:

  REPORT_SELF_HOSTED_ISSUES=1 to send data
  REPORT_SELF_HOSTED_ISSUES=0 to not send data

latest: Pulling from getsentry/sentry-cli
Digest: sha256:7b961ed50cffe9b40e110e7b87a8bf718a2dbfa55c413b0915af3d08c57d0101
Status: Image is up to date for getsentry/sentry-cli:latest
docker.io/getsentry/sentry-cli:latest

▶ Checking for latest commit ...
skipped

▶ Checking minimum requirements ...
Found Docker version 20.10.7
Found Docker Compose version 1.29.2
WARN: Recommended minimum RAM available to Docker is 7800 MB, found 7500 MB

▶ Turning things off ...
Removing sentry-self-hosted_snuba-outcomes-consumer_1                  ...
Removing sentry-self-hosted_snuba-subscription-consumer-transactions_1 ...
Removing sentry-self-hosted_snuba-replacer_1                           ...
Removing sentry-self-hosted_snuba-sessions-consumer_1                  ...
Removing sentry-self-hosted_snuba-consumer_1                           ...
Removing sentry-self-hosted_snuba-subscription-consumer-events_1       ...
Removing sentry-self-hosted_snuba-transactions-consumer_1              ...
Removing sentry-self-hosted_snuba-api_1                                ...
Removing sentry-self-hosted_postgres_1                                 ...
Removing sentry-self-hosted_memcached_1                                ...
Removing sentry-self-hosted_smtp_1                                     ...
Removing sentry-self-hosted_symbolicator_1                             ...
Removing sentry-self-hosted_kafka_1                                    ...
Removing sentry-self-hosted_clickhouse_1                               ...
Removing sentry-self-hosted_zookeeper_1                                ...
Removing sentry-self-hosted_redis_1                                    ...
Removing sentry-self-hosted_snuba-subscription-consumer-transactions_1 ... done
Removing sentry-self-hosted_postgres_1                                 ... done
Removing sentry-self-hosted_snuba-transactions-consumer_1              ... done
Removing sentry-self-hosted_snuba-sessions-consumer_1                  ... done
Removing sentry-self-hosted_smtp_1                                     ... done
Removing sentry-self-hosted_snuba-outcomes-consumer_1                  ... done
Removing sentry-self-hosted_snuba-subscription-consumer-events_1       ... done
Removing sentry-self-hosted_snuba-consumer_1                           ... done
Removing sentry-self-hosted_clickhouse_1                               ... done
Removing sentry-self-hosted_snuba-replacer_1                           ... done
Removing sentry-self-hosted_zookeeper_1                                ... done
Removing sentry-self-hosted_snuba-api_1                                ... done
Removing sentry-self-hosted_symbolicator_1                             ... done
Removing sentry-self-hosted_redis_1                                    ... done
Removing sentry-self-hosted_kafka_1                                    ... done
Removing sentry-self-hosted_memcached_1                                ... done
Removing network sentry-self-hosted_default

▶ Creating volumes for persistent storage ...
Created sentry-clickhouse.
Created sentry-data.
Created sentry-kafka.
Created sentry-postgres.
Created sentry-redis.
Created sentry-symbolicator.
Created sentry-zookeeper.

▶ Ensuring files from examples ...
../sentry/sentry.conf.py already exists, skipped creation.
../sentry/config.yml already exists, skipped creation.
../symbolicator/config.yml already exists, skipped creation.

▶ Ensuring Relay credentials ...
../relay/config.yml already exists, skipped creation.
../relay/credentials.json already exists, skipped creation.

▶ Generating secret key ...

▶ Fetching and updating Docker images ...
Some service image(s) must be built from source by running:
    docker-compose build cron sentry-cleanup symbolicator-cleanup snuba-transactions-cleanup subscription-consumer-transactions subscription-consumer-events post-process-forwarder-errors worker web post-process-forwarder-transactions ingest-consumer snuba-cleanup clickhouse
22.10.0: Pulling from getsentry/sentry
Digest: sha256:e67c076242873f57bfa69072047c378a2c3c3faf0ad5c6d4aa42158f4ffd8319
Status: Image is up to date for getsentry/sentry:22.10.0
docker.io/getsentry/sentry:22.10.0

▶ Building and tagging Docker images ...

Building web
Sending build context to Docker daemon  31.74kB
Step 1/5 : ARG SENTRY_IMAGE
Step 2/5 : FROM ${SENTRY_IMAGE}
 ---> 18564d21d9aa
Step 3/5 : COPY . /usr/src/sentry
 ---> Using cache
 ---> 9f1e45efb492
Step 4/5 : RUN if [ -s /usr/src/sentry/enhance-image.sh ]; then     /usr/src/sentry/enhance-image.sh; fi
 ---> Using cache
 ---> 92bc8dc83f39
Step 5/5 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then     echo "sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image";     pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> da8f92342e5e
Successfully built da8f92342e5e
Successfully tagged sentry-self-hosted-local:latest
smtp uses an image, skipping
memcached uses an image, skipping
redis uses an image, skipping
postgres uses an image, skipping
zookeeper uses an image, skipping
kafka uses an image, skipping
geoipupdate uses an image, skipping
snuba-api uses an image, skipping
snuba-consumer uses an image, skipping
snuba-outcomes-consumer uses an image, skipping
snuba-sessions-consumer uses an image, skipping
snuba-transactions-consumer uses an image, skipping
snuba-replacer uses an image, skipping
snuba-subscription-consumer-events uses an image, skipping
snuba-subscription-consumer-transactions uses an image, skipping
symbolicator uses an image, skipping
relay uses an image, skipping
nginx uses an image, skipping
Building clickhouse
Sending build context to Docker daemon  3.584kB
Step 1/2 : ARG BASE_IMAGE
Step 2/2 : FROM ${BASE_IMAGE}
 ---> abe55fc6544d
Successfully built abe55fc6544d
Successfully tagged clickhouse-self-hosted-local:latest
Building snuba-cleanup
Sending build context to Docker daemon  3.584kB
Step 1/8 : ARG BASE_IMAGE
Step 2/8 : FROM ${BASE_IMAGE}
 ---> 6f6e872bef6e
Step 3/8 : USER 0
 ---> Using cache
 ---> f98b9f054dfd
Step 4/8 : RUN if [ -z "${http_proxy}" ]; then echo "Acquire::http::proxy \"${http_proxy}\";" >> /etc/apt/apt.conf; fi
 ---> Using cache
 ---> f716b04138f7
Step 5/8 : RUN if [ -z "${https_proxy}" ]; then echo "Acquire::https::proxy \"${https_proxy}\";" >> /etc/apt/apt.conf; fi
 ---> Using cache
 ---> f52be8569b3d
Step 6/8 : RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
 ---> Using cache
 ---> 4b251260f20a
Step 7/8 : COPY entrypoint.sh /entrypoint.sh
 ---> Using cache
 ---> 380f1895e1ea
Step 8/8 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> bbdd4186d3b7
Successfully built bbdd4186d3b7
Successfully tagged snuba-cleanup-self-hosted-local:latest
Building snuba-transactions-cleanup
Sending build context to Docker daemon  3.584kB
Step 1/8 : ARG BASE_IMAGE
Step 2/8 : FROM ${BASE_IMAGE}
 ---> 6f6e872bef6e
Step 3/8 : USER 0
 ---> Using cache
 ---> f98b9f054dfd
Step 4/8 : RUN if [ -z "${http_proxy}" ]; then echo "Acquire::http::proxy \"${http_proxy}\";" >> /etc/apt/apt.conf; fi
 ---> Using cache
 ---> f716b04138f7
Step 5/8 : RUN if [ -z "${https_proxy}" ]; then echo "Acquire::https::proxy \"${https_proxy}\";" >> /etc/apt/apt.conf; fi
 ---> Using cache
 ---> f52be8569b3d
Step 6/8 : RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
 ---> Using cache
 ---> 4b251260f20a
Step 7/8 : COPY entrypoint.sh /entrypoint.sh
 ---> Using cache
 ---> 380f1895e1ea
Step 8/8 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> bbdd4186d3b7
Successfully built bbdd4186d3b7
Successfully tagged snuba-cleanup-self-hosted-local:latest
Building symbolicator-cleanup
Sending build context to Docker daemon  3.584kB
Step 1/8 : ARG BASE_IMAGE
Step 2/8 : FROM ${BASE_IMAGE}
 ---> 543d5fd4f165
Step 3/8 : USER 0
 ---> Using cache
 ---> cc8efeef29e7
Step 4/8 : RUN if [ -z "${http_proxy}" ]; then echo "Acquire::http::proxy \"${http_proxy}\";" >> /etc/apt/apt.conf; fi
 ---> Using cache
 ---> 3da897a62a24
Step 5/8 : RUN if [ -z "${https_proxy}" ]; then echo "Acquire::https::proxy \"${https_proxy}\";" >> /etc/apt/apt.conf; fi
 ---> Using cache
 ---> 16a1f775b24d
Step 6/8 : RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
 ---> Using cache
 ---> 4b2d576628f4
Step 7/8 : COPY entrypoint.sh /entrypoint.sh
 ---> Using cache
 ---> f01ca596f802
Step 8/8 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> 946af9e21fa8
Successfully built 946af9e21fa8
Successfully tagged symbolicator-cleanup-self-hosted-local:latest
Building web
Sending build context to Docker daemon  31.74kB
Step 1/5 : ARG SENTRY_IMAGE
Step 2/5 : FROM ${SENTRY_IMAGE}
 ---> 18564d21d9aa
Step 3/5 : COPY . /usr/src/sentry
 ---> Using cache
 ---> 9f1e45efb492
Step 4/5 : RUN if [ -s /usr/src/sentry/enhance-image.sh ]; then     /usr/src/sentry/enhance-image.sh; fi
 ---> Using cache
 ---> 92bc8dc83f39
Step 5/5 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then     echo "sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image";     pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> da8f92342e5e
Successfully built da8f92342e5e
Successfully tagged sentry-self-hosted-local:latest
Building cron
Sending build context to Docker daemon  31.74kB
Step 1/5 : ARG SENTRY_IMAGE
Step 2/5 : FROM ${SENTRY_IMAGE}
 ---> 18564d21d9aa
Step 3/5 : COPY . /usr/src/sentry
 ---> Using cache
 ---> 9f1e45efb492
Step 4/5 : RUN if [ -s /usr/src/sentry/enhance-image.sh ]; then     /usr/src/sentry/enhance-image.sh; fi
 ---> Using cache
 ---> 92bc8dc83f39
Step 5/5 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then     echo "sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image";     pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> da8f92342e5e
Successfully built da8f92342e5e
Successfully tagged sentry-self-hosted-local:latest
Building worker
Sending build context to Docker daemon  31.74kB
Step 1/5 : ARG SENTRY_IMAGE
Step 2/5 : FROM ${SENTRY_IMAGE}
 ---> 18564d21d9aa
Step 3/5 : COPY . /usr/src/sentry
 ---> Using cache
 ---> 9f1e45efb492
Step 4/5 : RUN if [ -s /usr/src/sentry/enhance-image.sh ]; then     /usr/src/sentry/enhance-image.sh; fi
 ---> Using cache
 ---> 92bc8dc83f39
Step 5/5 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then     echo "sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image";     pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> da8f92342e5e
Successfully built da8f92342e5e
Successfully tagged sentry-self-hosted-local:latest
Building ingest-consumer
Sending build context to Docker daemon  31.74kB
Step 1/5 : ARG SENTRY_IMAGE
Step 2/5 : FROM ${SENTRY_IMAGE}
 ---> 18564d21d9aa
Step 3/5 : COPY . /usr/src/sentry
 ---> Using cache
 ---> 9f1e45efb492
Step 4/5 : RUN if [ -s /usr/src/sentry/enhance-image.sh ]; then     /usr/src/sentry/enhance-image.sh; fi
 ---> Using cache
 ---> 92bc8dc83f39
Step 5/5 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then     echo "sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image";     pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> da8f92342e5e
Successfully built da8f92342e5e
Successfully tagged sentry-self-hosted-local:latest
Building post-process-forwarder-errors
Sending build context to Docker daemon  31.74kB
Step 1/5 : ARG SENTRY_IMAGE
Step 2/5 : FROM ${SENTRY_IMAGE}
 ---> 18564d21d9aa
Step 3/5 : COPY . /usr/src/sentry
 ---> Using cache
 ---> 9f1e45efb492
Step 4/5 : RUN if [ -s /usr/src/sentry/enhance-image.sh ]; then     /usr/src/sentry/enhance-image.sh; fi
 ---> Using cache
 ---> 92bc8dc83f39
Step 5/5 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then     echo "sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image";     pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> da8f92342e5e
Successfully built da8f92342e5e
Successfully tagged sentry-self-hosted-local:latest
Building post-process-forwarder-transactions
Sending build context to Docker daemon  31.74kB
Step 1/5 : ARG SENTRY_IMAGE
Step 2/5 : FROM ${SENTRY_IMAGE}
 ---> 18564d21d9aa
Step 3/5 : COPY . /usr/src/sentry
 ---> Using cache
 ---> 9f1e45efb492
Step 4/5 : RUN if [ -s /usr/src/sentry/enhance-image.sh ]; then     /usr/src/sentry/enhance-image.sh; fi
 ---> Using cache
 ---> 92bc8dc83f39
Step 5/5 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then     echo "sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image";     pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> da8f92342e5e
Successfully built da8f92342e5e
Successfully tagged sentry-self-hosted-local:latest
Building subscription-consumer-events
Sending build context to Docker daemon  31.74kB
Step 1/5 : ARG SENTRY_IMAGE
Step 2/5 : FROM ${SENTRY_IMAGE}
 ---> 18564d21d9aa
Step 3/5 : COPY . /usr/src/sentry
 ---> Using cache
 ---> 9f1e45efb492
Step 4/5 : RUN if [ -s /usr/src/sentry/enhance-image.sh ]; then     /usr/src/sentry/enhance-image.sh; fi
 ---> Using cache
 ---> 92bc8dc83f39
Step 5/5 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then     echo "sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image";     pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> da8f92342e5e
Successfully built da8f92342e5e
Successfully tagged sentry-self-hosted-local:latest
Building subscription-consumer-transactions
Sending build context to Docker daemon  31.74kB
Step 1/5 : ARG SENTRY_IMAGE
Step 2/5 : FROM ${SENTRY_IMAGE}
 ---> 18564d21d9aa
Step 3/5 : COPY . /usr/src/sentry
 ---> Using cache
 ---> 9f1e45efb492
Step 4/5 : RUN if [ -s /usr/src/sentry/enhance-image.sh ]; then     /usr/src/sentry/enhance-image.sh; fi
 ---> Using cache
 ---> 92bc8dc83f39
Step 5/5 : RUN if [ -s /usr/src/sentry/requirements.txt ]; then     echo "sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image";     pip install -r /usr/src/sentry/requirements.txt; fi
 ---> Using cache
 ---> da8f92342e5e
Successfully built da8f92342e5e
Successfully tagged sentry-self-hosted-local:latest
Building sentry-cleanup
Sending build context to Docker daemon  3.584kB
Step 1/8 : ARG BASE_IMAGE
Step 2/8 : FROM ${BASE_IMAGE}
 ---> da8f92342e5e
Step 3/8 : USER 0
 ---> Using cache
 ---> aa0f363e9b5c
Step 4/8 : RUN if [ -z "${http_proxy}" ]; then echo "Acquire::http::proxy \"${http_proxy}\";" >> /etc/apt/apt.conf; fi
 ---> Using cache
 ---> 353719901167
Step 5/8 : RUN if [ -z "${https_proxy}" ]; then echo "Acquire::https::proxy \"${https_proxy}\";" >> /etc/apt/apt.conf; fi
 ---> Using cache
 ---> b1dd8c792d60
Step 6/8 : RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
 ---> Using cache
 ---> 24bf20183def
Step 7/8 : COPY entrypoint.sh /entrypoint.sh
 ---> Using cache
 ---> e180eec016af
Step 8/8 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> a57053cf4253
Successfully built a57053cf4253
Successfully tagged sentry-cleanup-self-hosted-local:latest

Docker images built.

▶ Downloading and installing wal2json ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5418  100  5418    0     0   8236      0 --:--:-- --:--:-- --:--:--  8234

▶ Bootstrapping and migrating Snuba ...
Creating network "sentry-self-hosted_default" with the default driver
Creating sentry-self-hosted_zookeeper_1 ...
Creating sentry-self-hosted_redis_1     ...
Creating sentry-self-hosted_clickhouse_1 ...
Creating sentry-self-hosted_redis_1      ... done
Creating sentry-self-hosted_zookeeper_1  ... done
Creating sentry-self-hosted_clickhouse_1 ... done
Creating sentry-self-hosted_kafka_1      ...
Creating sentry-self-hosted_kafka_1      ... done
Creating sentry-self-hosted_snuba-api_run ...
Creating sentry-self-hosted_snuba-api_run ... done
2022-11-02 09:03:35,749 Attempting to connect to Kafka (attempt 0)...
2022-11-02 09:03:35,780 Connected to Kafka on attempt 0
2022-11-02 09:03:35,781 Creating Kafka topics...
Creating sentry-self-hosted_snuba-api_run ...
Creating sentry-self-hosted_snuba-api_run ... done
Finished running migrations

▶ Creating additional Kafka topics ...

▶ Setting up / migrating database ...
Creating sentry-self-hosted_symbolicator_1 ...
Creating sentry-self-hosted_smtp_1         ...
Creating sentry-self-hosted_memcached_1    ...
Creating sentry-self-hosted_postgres_1     ...
Creating sentry-self-hosted_snuba-transactions-consumer_1 ...
Creating sentry-self-hosted_snuba-subscription-consumer-transactions_1 ...
Creating sentry-self-hosted_snuba-outcomes-consumer_1                  ...
Creating sentry-self-hosted_snuba-replacer_1                           ...
Creating sentry-self-hosted_snuba-sessions-consumer_1                  ...
Creating sentry-self-hosted_snuba-api_1                                ...
Creating sentry-self-hosted_snuba-consumer_1                           ...
Creating sentry-self-hosted_snuba-subscription-consumer-events_1       ...
Creating sentry-self-hosted_smtp_1                                     ... done
Creating sentry-self-hosted_memcached_1                                ... done
Creating sentry-self-hosted_symbolicator_1                             ... done
Creating sentry-self-hosted_snuba-transactions-consumer_1              ... done
Creating sentry-self-hosted_postgres_1                                 ... error

ERROR: for sentry-self-hosted_postgres_1  Cannot start service postgres: OCI runtime create failed: runc create failed: unable to start container process: exec: "/opt/sentry/postgres-entrypoint.sh": permission denied: unknown
Creating sentry-self-hosted_snuba-subscription-consumer-transactions_1 ... done
Creating sentry-self-hosted_snuba-sessions-consumer_1                  ... done
Creating sentry-self-hosted_snuba-replacer_1                           ... done
Creating sentry-self-hosted_snuba-outcomes-consumer_1                  ... done
Creating sentry-self-hosted_snuba-api_1                                ... done
Creating sentry-self-hosted_snuba-subscription-consumer-events_1       ... done
Creating sentry-self-hosted_snuba-consumer_1                           ... done

ERROR: for postgres  Cannot start service postgres: OCI runtime create failed: runc create failed: unable to start container process: exec: "/opt/sentry/postgres-entrypoint.sh": permission denied: unknown
Encountered errors while bringing up the project.
Error in set-up-and-migrate-database.sh:12.
'$dcr web upgrade' exited with status 1
-> install.sh:main:33
--> set-up-and-migrate-database.sh:source:12

**Comment by aminvakil** [comment]
Related: https://github.com/getsentry/self-hosted/issues/1658 and a couple of others in https://github.com/getsentry/self-hosted/issues?q=%2Fopt%2Fsentry%2Fpostgres-entrypoint.sh .

**Comment by damengzhang** [comment]
> 

I don't see the /opt/sentry folder

**Comment by damengzhang** [comment]
>They are executable, but I don't see the /opt/sentry folder

>ll /opt/sentry
ls: cannot access '/opt/sentry': No such file or directory

>ll
drwxr-xr-x  3 root root   58 Nov  2 16:48 self-hosted-22.10.0
drwxr-xr-x  3 root root   57 Nov  2 17:08 self-hosted-22.9.0
drwxr-xr-x 17 root root 4096 Nov  2 16:19 self-hosted-master

**Comment by damengzhang** [comment]
When I moved all files under self-hosted-22.10.0 folder to /opt/sentry, and chmod 777 /opt/sentry/, the previous error disappeared, but new error appeared

Error response from daemon: OCI runtime create failed: runc create failed: unable to start container process: exec: "/etc/sentry/entrypoint.sh": permission denied: unknown
1
Error in set-up-and-migrate-database.sh:12.
'$dcr web upgrade' exited with status 1
-> ./install.sh:main:33
--> set-up-and-migrate-database.sh:source:12

**Comment by aminvakil** [comment]
@damengzhang `/opt/sentry` is in the container, that's ok, you don't need it in your host.

**Comment by damengzhang** [comment]
When I moved all files under self-hosted-22.10.0 folder to /opt/sentry, and execute the following command before execute install.sh, the problem is solved

>chmod 777 /opt/sentry
>chmod 777 /opt/sentry/sentry/postgres/init_hba.sh 
>chmod 777 /opt/sentry/sentry/postgres/postgres-entrypoint.sh
>chmod 777 /opt/sentry/sentry/sentry/entrypoint.sh

**Comment by hubertdeng123** [comment]
glad you were able to figure that out!
