### ISSUE TITLE
Nginx is using the wrong IP address

### ISSUE THREAD

**Issue by edhgoose** [getsentry/self-hosted#1795]
### Self-Hosted Version

22.10.0

### CPU Architecture

x86_64

### Docker Version

20.10.17, build 100c701

### Docker Compose Version

1.29.2, build 5becea4c

### Steps to Reproduce

I'm not sure how we would reproduce this, but we found an issue where Sentry started up and nginx was using the wrong IP address.

@jamesob reported the same problem here but it was closed: https://github.com/getsentry/self-hosted/issues/1780

### Expected Result

We would expect that the `web` domain resolves to the correct IP address.

### Actual Result

Our self hosted Sentry is sitting behind an AWS load balancer. We found that requests to the load balancer were failing with logs like the following:

```
nginx_1                                     | 10.0.0.222 - - [02/Nov/2022:12:42:48 +0000] "GET / HTTP/1.1" 502 150 "-" "ELB-HealthChecker/2.0" "-"
nginx_1                                     | 10.0.0.222 - - [02/Nov/2022:12:42:51 +0000] "GET /api/0/relays/live/ HTTP/1.1" 502 150 "-" "-" "12.34.56.78"
nginx_1                                     | 2022/11/02 12:42:51 [error] 22#22: *3188 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.0.222, server: , request: "GET /api/0/relays/live/ HTTP/1.1", upstream: "http://172.20.0.6:9000/api/0/relays/live/", host: "sentry.our.domain"
nginx_1                                     | 2022/11/02 12:42:52 [error] 24#24: *3291 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.0.222, server: , request: "GET /api/0/relays/live/ HTTP/1.1", upstream: "http://172.20.0.6:9000/api/0/relays/live/", host: "sentry.our.domain"
nginx_1                                     | 10.0.0.222 - - [02/Nov/2022:12:42:52 +0000] "GET /api/0/relays/live/ HTTP/1.1" 502 150 "-" "-" "12.34.56.78"
nginx_1                                     | 2022/11/02 12:42:55 [error] 24#24: *3293 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.1.148, server: , request: "GET /api/0/relays/live/ HTTP/1.1", upstream: "http://172.20.0.6:9000/api/0/relays/live/", host: "sentry.our.domain"
```

The odd thing is that 172.20.0.6 was not what `web` and relay were pointed at.

Using ping for web:
```
/ # ping web
PING web (172.20.0.17): 56 data bytes
64 bytes from 172.20.0.17: seq=0 ttl=64 time=0.252 ms
```
And for relay:
```
/ # ping relay
PING relay (172.20.0.10): 56 data bytes
64 bytes from 172.20.0.10: seq=0 ttl=64 time=0.093 ms
```

It looks like the resolver can incorrectly lose the IP address. It seems to have happened as a result of a reboot if that's useful information.

We wonder if the nginx configuration should be changed to include something like:

`resolver 127.0.0.11 valid=10s;`, as [per this StackOverflow result](https://serverfault.com/questions/722438/nginx-refresh-upstream-server-ip)?

**Comment by hubertdeng123** [comment]
Interesting, not sure if this is something that people are experiencing recently. Thanks for bringing this up I'll take a look at this and see what I can find

**Comment by hubertdeng123** [comment]
I don't think I've seen this happen before on my side though

**Comment by jamesob** [comment]
My best guess (from https://github.com/getsentry/self-hosted/issues/1780) is that upon `docker-compose restart`, the resolver in nginx goes stale somehow and a full removal of the container is required to bring it up to date.
