### ISSUE TITLE
sentry.eventstream.kafka.backend in run_consumer

### ISSUE THREAD

**Issue by YutaoChow** [getsentry/self-hosted#1802]
### Self-Hosted Version

sentry.eventstream.kafka.backend in run_consumer

### CPU Architecture

X86_64

### Docker Version

20.10.9

### Docker Compose Version

1.28.6

### Steps to Reproduce

1. install new version
2. docker-compose up -d
3. catch the issue
![image](https://user-images.githubusercontent.com/20595456/200789682-fdbf42b8-fc98-4226-89fc-f11d1b917b47.png)
![image](https://user-images.githubusercontent.com/20595456/200789768-09e6ff55-882b-4166-b885-615443259a4d.png)
![image](https://user-images.githubusercontent.com/20595456/200789832-5aec9871-2aea-4513-8813-e7b3dc089788.png)
4. The post-process-forwarder container keep restarting
![image](https://user-images.githubusercontent.com/20595456/200790009-6aa2ea9d-3330-4155-8f1c-812807b35a04.png)
![image](https://user-images.githubusercontent.com/20595456/200793025-afd6d9f3-44c6-4727-aa60-1799e7127447.png)
ps: I find the error because the `None` topic
![image](https://user-images.githubusercontent.com/20595456/200979085-0a3c05f5-8682-4fe2-a360-14caae3326b9.png)

5. Issue Alerts not trigger
![image](https://user-images.githubusercontent.com/20595456/200790450-693544fe-e24e-4eaf-a5fb-afc8dedef545.png)

### Expected Result

1. The container status healthy
2. The issue alerts working normal

### Actual Result

1. The container keep restarting
2. The issue alerts not trigger

**Comment by ethanhs** [comment]
I'm guessing this is the same root cause as https://github.com/getsentry/self-hosted/issues/1799. I would suggest going through https://develop.sentry.dev/self-hosted/troubleshooting/#kafka

**Comment by YutaoChow** [comment]
> I'm guessing this is the same root cause as #1799. I would suggest going through https://develop.sentry.dev/self-hosted/troubleshooting/#kafka

I doubt that because it catch the different error message,and I try the `Proper solution` and `Nuclear option` but didn't work

**Comment by ethanhs** [comment]
Hm, yeah I suppose that it is different. I thought it might have the same root cause.

**Comment by YutaoChow** [comment]
> Hm, yeah I suppose that it is different. I thought it might have the same root cause.
Thanks,I have find the problem,it's because the old version `self-hosted` code.
<img width="1384" alt="image" src="https://user-images.githubusercontent.com/20595456/201675730-1e4202f0-8f0b-4130-8954-5e7fc5b39cf9.png">
