### ISSUE TITLE
Self hosted Sentry: Custom Performance metrics UI

### ISSUE THREAD

**Issue by HemantSinghRao** [getsentry/self-hosted#1805]
### Problem Statement

I was researching about a sentry feature i.e  [Custom Performance metrics](https://docs.sentry.io/product/performance/metrics/#custom-performance-metrics). The [sdks](https://docs.sentry.io/platforms/python/performance/instrumentation/performance-metrics/) to send the performance metrics to the sentry were configured. Still, I am not able to see the [Custom Performance metrics UI](https://docs.sentry.io/static/42e04349c6cc71eb4eb64d04c976b154/869d7/custom-metrics-performance.png) on my self hosted sentry as mentioned in the document.
<img width="1476" alt="image" src="https://user-images.githubusercontent.com/14067565/201408808-132f11e4-4f37-427e-aabd-a5ce23ed92a0.png">

Can you please enable this feature for self-hosted?

**Comment by ethanhs** [comment]
Hi sorry this isn't working for you. Just to confirm, have you followed the steps listed on the page you link?

> Custom metrics are accessible to you in [sentry.io](https://sentry.io/)
when you:
    Create visualizations in Dashboards
    Query and add columns for them in Discover
    View a transaction event detail (see image below)

We don't block features on self-hosted. I'll see if I can repro this issue.

**Comment by HemantSinghRao** [comment]
Hi @ethanhs 

I have followed the steps.

> Custom metrics are accessible to you in [sentry.io](https://sentry.io/)
> Create visualizations in Dashboards
> Query and add columns for them in Discover
> View a transaction event detail (see image below)

I have self-hosted and on its endpoint, I am unable to see the Custom metrics. 
Can you please replicate the same for self-hosted and validate?

**Comment by hubertdeng123** [comment]
Just wanted to clarify here, Custom metrics is a part of dynamic sampling which is not ready for self-hosted yet. Closing this ticket because we cannot enable this feature yet

https://github.com/getsentry/sentry/issues/40240#issuecomment-1287083636
