### ISSUE TITLE
Sentry don't use X-Forwarded-For header

### ISSUE THREAD

**Issue by LocalHeroPro** [getsentry/self-hosted#1807]
### Self-Hosted Version

22.11.0.dev0

### CPU Architecture

64

### Docker Version

20.10.21

### Docker Compose Version

1.29.2

### Steps to Reproduce

1. Send request via browser
2. Request go via proxy which add X-Forwarded-For header with client IP address
3. Request go to edge router
4. Request go to web server
5. Exception occurred
6. Sentry store User IP Address and REMOTE_ADDR of edge router

### Expected Result

Sentry store IP address from X-Forwarded-For header.

### Actual Result

6. Sentry store User IP Address and REMOTE_ADDR of edge router

### Event ID

585f0caecdfd4e0d909953641e540293

**Comment by hubertdeng123** [comment]
I don't think your event ID sent properly to us. Can you give us some more details here? What exception occurred? I do believe there's a setting like `SENTRY_USE_X_FORWARDED_FOR` for sentry.conf.py for this but I'm not entirely sure

**Comment by LocalHeroPro** [comment]
It's looks like to be on my config side, because of: https://youtu.be/1I5FywY6opQ.
When I disable that option, everything works as expected.
