### ISSUE TITLE
Error install sentry

### ISSUE THREAD

**Issue by MiguelTortosa** [getsentry/self-hosted#1810]
### Self-Hosted Version

latest

### CPU Architecture

x86_64

### Docker Version

20.10.21

### Docker Compose Version

1.28.6

### Steps to Reproduce

bash install.sh

### Expected Result

error-handling.sh: line 19: jq: command not found
error-handling.sh: line 19: jq: command not found

### Actual Result

error-handling.sh: line 19: jq: command not found
error-handling.sh: line 19: jq: command not found

**Comment by hubertdeng123** [comment]
Hi there, could you post some more logs? It's likely here that the jq container isn't being built properly

**Comment by MiguelTortosa** [comment]
Hi @hubertdeng123 ,  thanks for your support.
More logs ---->
Bootstrapping and migrating Snuba ...
Creating network "sentry-self-hosted_default" with the default driver
Creating sentry-self-hosted_zookeeper_1 ... 
Creating sentry-self-hosted_clickhouse_1 ... 
Creating sentry-self-hosted_redis_1      ... 
Creating sentry-self-hosted_zookeeper_1  ... done
Creating sentry-self-hosted_clickhouse_1 ... done
Creating sentry-self-hosted_redis_1      ... done
Creating sentry-self-hosted_kafka_1      ... 
Creating sentry-self-hosted_kafka_1      ... done

ERROR: for snuba-api  Container "8aedcce2dc12" is unhealthy.
Encountered errors while bringing up the project.
error-handling.sh: line 176: jq: command not found

**Comment by algethamy** [comment]
i have the same issue

**Comment by hubertdeng123** [comment]
Thanks for reporting, I'm able to repro and we plan on releasing a fix today
