### ISSUE TITLE
Errors in multiple containers after trying to upgrade to 22.10.0

### ISSUE THREAD

**Issue by cjesper** [getsentry/self-hosted#1811]
### Self-Hosted Version

22.10.0

### CPU Architecture

x86_64

### Docker Version

20.10.21

### Docker Compose Version

2.12.2

### Steps to Reproduce

Hi, sorry in advance if this should be split up into multiple issues but as there are errors across 3 services i suspect that some part of the installation has become corrupted on my machine.

I am trying to install Sentry 22.10.0 on a machine running Ubuntu 20. 
The installation script runs through without any errors but when i run docker-compose up -d i get errors in

- sentry_onpremise_smtp_1
- sentry_onpremise_snuba-subscription-consumer-events_1
- sentry_onpremise_snuba-subscription-consumer-transactions_1

See "Actual Result" for the exact errors. I have tried cleaning the containers, volumes, configuration (ie. redownloading the artifact) multiple times, to no effect. 

**Note:** If it matters, i am running with an external postgres database and an external Redis Server.

### Expected Result

No errors in any of the containers.

### Actual Result

**docker logs sentry_onpremise_snuba-subscription-consumer-transactions_1**
```
FileNotFoundError: [Errno 2] No such file or directory: '/usr/src/snuba/snuba/cli/subscriptions.py'
2022-11-15 12:01:37,921 Initializing Snuba CLI...
2022-11-15 12:01:37,922 Initializing Snuba
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1651, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1698, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/usr/src/snuba/snuba/cli/__init__.py", line 61, in get_command
    with open(fn) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/src/snuba/snuba/cli/subscriptions.py'
```
**docker logs sentry_onpremise_snuba-subscription-consumer-events_1**
```
FileNotFoundError: [Errno 2] No such file or directory: '/usr/src/snuba/snuba/cli/subscriptions.py'
2022-11-15 12:03:42,776 Initializing Snuba CLI...
2022-11-15 12:03:42,777 Initializing Snuba
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1651, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1698, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/usr/src/snuba/snuba/cli/__init__.py", line 61, in get_command
    with open(fn) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/src/snuba/snuba/cli/subscriptions.py'
```
**docker logs sentry_onpremise_smtp_1**
```
LOG: MAIN PANIC DIE
  Exim configuration file /var/lib/exim4/config.autogenerated has the wrong owner, group, or mode
LOG: MAIN PANIC DIE
  Exim configuration file /var/lib/exim4/config.autogenerated has the wrong owner, group, or mode
```

Sentry Install Logs
`▶ Parsing command line ...

▶ Detecting Docker platform
Detected Docker platform is linux/amd64

▶ Initializing Docker Compose ...

▶ Setting up error handling ...

Hey, so ... we would love to automatically find out about issues with your
Sentry instance so that we can improve the product. Turns out there is an app
for that, called Sentry. Would you be willing to let us automatically send data
about your instance upstream to Sentry for development and debugging purposes?

  y / yes / 1
  n / no / 0

(Btw, we send this to our own self-hosted Sentry instance, not to Sentry SaaS,
so that we can be in this together.)

Here's the info we may collect:

  - OS username
  - IP address
  - install log
  - runtime errors
  - performance data

Thirty (30) day retention. No marketing. Privacy policy at sentry.io/privacy.

y or n?
Understood. To avoid this prompt in the future, use one of these flags:

  --report-self-hosted-issues
  --no-report-self-hosted-issues

or set the REPORT_SELF_HOSTED_ISSUES environment variable:

  REPORT_SELF_HOSTED_ISSUES=1 to send data
  REPORT_SELF_HOSTED_ISSUES=0 to not send data

▶ Checking for latest commit ...
skipped

▶ Checking minimum requirements ...
Found Docker version 20.10.21
Found Docker Compose version 2.12.2

▶ Turning things off ...
Container sentry_onpremise_worker_1  Stopping
Container sentry_onpremise_worker_1  Stopping
Container sentry_onpremise_symbolicator-cleanup_1  Stopping
Container sentry_onpremise_symbolicator-cleanup_1  Stopping
Container sentry_onpremise_cron_1  Stopping
Container sentry_onpremise_snuba-transactions-cleanup_1  Stopping
Container sentry_onpremise_ingest-consumer_1  Stopping
Container sentry_onpremise_snuba-transactions-cleanup_1  Stopping
Container sentry_onpremise_ingest-consumer_1  Stopping
Container sentry_onpremise_relay_1  Stopping
Container sentry_onpremise_subscription-consumer-events_1  Stopping
Container sentry_onpremise_subscription-consumer-events_1  Stopping
Container sentry_onpremise_relay_1  Stopping
Container sentry_onpremise_subscription-consumer-transactions_1  Stopping
Container sentry_onpremise_subscription-consumer-transactions_1  Stopping
Container sentry_onpremise_snuba-cleanup_1  Stopping
Container sentry_onpremise_snuba-cleanup_1  Stopping
Container sentry_onpremise_cron_1  Stopping
Container sentry_onpremise_sentry-cleanup_1  Stopping
Container sentry_onpremise_sentry-cleanup_1  Stopping
Container sentry_onpremise_worker_1  Stopped
Container sentry_onpremise_worker_1  Removing
Container sentry_onpremise_symbolicator-cleanup_1  Stopped
Container sentry_onpremise_relay_1  Stopped
Container sentry_onpremise_symbolicator-cleanup_1  Removing
Container sentry_onpremise_relay_1  Removing
Container sentry_onpremise_cron_1  Stopped
Container sentry_onpremise_cron_1  Removing
Container sentry_onpremise_snuba-transactions-cleanup_1  Stopped
Container sentry_onpremise_snuba-transactions-cleanup_1  Removing
Container sentry_onpremise_snuba-cleanup_1  Stopped
Container sentry_onpremise_sentry-cleanup_1  Stopped
Container sentry_onpremise_sentry-cleanup_1  Removing
Container sentry_onpremise_subscription-consumer-transactions_1  Stopped
Container sentry_onpremise_subscription-consumer-transactions_1  Removing
Container sentry_onpremise_snuba-cleanup_1  Removing
Container sentry_onpremise_subscription-consumer-events_1  Stopped
Container sentry_onpremise_subscription-consumer-events_1  Removing
Container sentry_onpremise_ingest-consumer_1  Stopped
Container sentry_onpremise_ingest-consumer_1  Removing
Container sentry_onpremise_symbolicator-cleanup_1  Removed
Container sentry_onpremise_snuba-transactions-cleanup_1  Removed
Container sentry_onpremise_cron_1  Removed
Container sentry_onpremise_subscription-consumer-transactions_1  Removed
Container sentry_onpremise_worker_1  Removed
Container sentry_onpremise_subscription-consumer-events_1  Removed
Container sentry_onpremise_snuba-cleanup_1  Removed
Container sentry_onpremise_ingest-consumer_1  Removed
Container sentry_onpremise_relay_1  Removed
Container sentry_onpremise_web_1  Stopping
Container sentry_onpremise_web_1  Stopping
Container sentry_onpremise_sentry-cleanup_1  Removed
Container sentry_onpremise_web_1  Stopped
Container sentry_onpremise_web_1  Removing
Container sentry_onpremise_web_1  Removed
Container sentry_onpremise_symbolicator_1  Stopping
Container sentry_onpremise_smtp_1  Stopping
Container sentry_onpremise_symbolicator_1  Stopping
Container sentry_onpremise_smtp_1  Stopping
Container sentry_onpremise_snuba-outcomes-consumer_1  Stopping
Container sentry_onpremise_snuba-transactions-consumer_1  Stopping
Container sentry_onpremise_snuba-subscription-consumer-events_1  Stopping
Container sentry_onpremise_snuba-subscription-consumer-transactions_1  Stopping
Container sentry_onpremise_snuba-transactions-consumer_1  Stopping
Container sentry_onpremise_snuba-api_1  Stopping
Container sentry_onpremise_snuba-subscription-consumer-transactions_1  Stopping
Container sentry_onpremise_snuba-outcomes-consumer_1  Stopping
Container sentry_onpremise_memcached_1  Stopping
Container sentry_onpremise_snuba-api_1  Stopping
Container sentry_onpremise_snuba-sessions-consumer_1  Stopping
Container sentry_onpremise_memcached_1  Stopping
Container sentry_onpremise_snuba-subscription-consumer-events_1  Stopping
Container sentry_onpremise_snuba-consumer_1  Stopping
Container sentry_onpremise_snuba-consumer_1  Stopping
Container sentry_onpremise_snuba-replacer_1  Stopping
Container sentry_onpremise_snuba-sessions-consumer_1  Stopping
Container sentry_onpremise_snuba-replacer_1  Stopping
Container sentry_onpremise_smtp_1  Stopped
Container sentry_onpremise_smtp_1  Removing
Container sentry_onpremise_snuba-subscription-consumer-events_1  Stopped
Container sentry_onpremise_snuba-subscription-consumer-events_1  Removing
Container sentry_onpremise_snuba-subscription-consumer-transactions_1  Stopped
Container sentry_onpremise_snuba-subscription-consumer-transactions_1  Removing
Container sentry_onpremise_snuba-subscription-consumer-events_1  Removed
Container sentry_onpremise_smtp_1  Removed
Container sentry_onpremise_snuba-subscription-consumer-transactions_1  Removed
Container sentry_onpremise_snuba-sessions-consumer_1  Stopped
Container sentry_onpremise_snuba-sessions-consumer_1  Removing
Container sentry_onpremise_snuba-sessions-consumer_1  Removed
Container sentry_onpremise_memcached_1  Stopped
Container sentry_onpremise_memcached_1  Removing
Container sentry_onpremise_memcached_1  Removed
Container sentry_onpremise_snuba-replacer_1  Stopped
Container sentry_onpremise_snuba-replacer_1  Removing
Container sentry_onpremise_snuba-replacer_1  Removed
Container sentry_onpremise_snuba-outcomes-consumer_1  Stopped
Container sentry_onpremise_snuba-outcomes-consumer_1  Removing
Container sentry_onpremise_snuba-outcomes-consumer_1  Removed
Container sentry_onpremise_snuba-transactions-consumer_1  Stopped
Container sentry_onpremise_snuba-transactions-consumer_1  Removing
Container sentry_onpremise_snuba-transactions-consumer_1  Removed
Container sentry_onpremise_snuba-consumer_1  Stopped
Container sentry_onpremise_snuba-consumer_1  Removing
Container sentry_onpremise_snuba-consumer_1  Removed
Container sentry_onpremise_snuba-api_1  Stopped
Container sentry_onpremise_snuba-api_1  Removing
Container sentry_onpremise_snuba-api_1  Removed
Container sentry_onpremise_kafka_1  Stopping
Container sentry_onpremise_kafka_1  Stopping
Container sentry_onpremise_clickhouse_1  Stopping
Container sentry_onpremise_clickhouse_1  Stopping
Container sentry_onpremise_clickhouse_1  Stopped
Container sentry_onpremise_clickhouse_1  Removing
Container sentry_onpremise_clickhouse_1  Removed
Container sentry_onpremise_kafka_1  Stopped
Container sentry_onpremise_kafka_1  Removing
Container sentry_onpremise_kafka_1  Removed
Container sentry_onpremise_zookeeper_1  Stopping
Container sentry_onpremise_zookeeper_1  Stopping
Container sentry_onpremise_zookeeper_1  Stopped
Container sentry_onpremise_zookeeper_1  Removing
Container sentry_onpremise_zookeeper_1  Removed
Container sentry_onpremise_symbolicator_1  Stopped
Container sentry_onpremise_symbolicator_1  Removing
Container sentry_onpremise_symbolicator_1  Removed
Image symbolicator-cleanup-onpremise-local:latest  Removing
Image sentry-cleanup-onpremise-local:latest  Removing
Image snuba-cleanup-onpremise-local:latest  Removing
Network sentry_onpremise_default  Removing
Image sentry-cleanup-onpremise-local:latest  Removed
Image symbolicator-cleanup-onpremise-local:latest  Removed
Image snuba-cleanup-onpremise-local:latest  Removed
Network sentry_onpremise_default  Removed

▶ Creating volumes for persistent storage ...
Created sentry-clickhouse.
Created sentry-data.
Created sentry-kafka.
Created sentry-postgres.
Created sentry-redis.
Created sentry-symbolicator.
Created sentry-zookeeper.

▶ Ensuring files from examples ...
../sentry/sentry.conf.py already exists, skipped creation.
../sentry/config.yml already exists, skipped creation.
../symbolicator/config.yml already exists, skipped creation.

▶ Ensuring Relay credentials ...
../relay/config.yml already exists, skipped creation.
../relay/credentials.json already exists, skipped creation.

▶ Generating secret key ...

▶ Fetching and updating Docker images ...
nightly: Pulling from getsentry/sentry
Digest: sha256:876e3e63357afb77f11cf99803cbb59bc15be1e22f646ab7e14e14a3fe1d4478
Status: Image is up to date for getsentry/sentry:nightly
docker.io/getsentry/sentry:nightly

▶ Building and tagging Docker images ...

#1 [symbolicator-cleanup-onpremise-local internal] load build definition from Dockerfile
#1 transferring dockerfile: 32B done
#1 DONE 0.0s

#2 [snuba-cleanup-onpremise-local internal] load build definition from Dockerfile
#2 transferring dockerfile: 32B done
#2 DONE 0.0s

#3 [sentry-cleanup-onpremise-local internal] load build definition from Dockerfile
#3 transferring dockerfile: 32B done
#3 DONE 0.0s

#4 [sentry-cleanup-onpremise-local internal] load .dockerignore
#4 transferring context: 2B done
#4 DONE 0.0s

#5 [symbolicator-cleanup-onpremise-local internal] load .dockerignore
#5 transferring context: 2B done
#5 DONE 0.0s

#6 [snuba-cleanup-onpremise-local internal] load .dockerignore
#6 transferring context: 2B done
#6 DONE 0.0s

#7 [sentry-cleanup-onpremise-local internal] load metadata for docker.io/getsentry/sentry:nightly
#7 DONE 0.0s

#8 [sentry-cleanup-onpremise-local 1/5] FROM docker.io/getsentry/sentry:nightly
#8 DONE 0.0s

#9 [symbolicator-cleanup-onpremise-local internal] load metadata for docker.io/getsentry/symbolicator:nightly
#9 DONE 0.0s

#10 [sentry-cleanup-onpremise-local internal] load build context
#10 transferring context: 35B done
#10 DONE 0.0s

#11 [symbolicator-cleanup-onpremise-local 1/5] FROM docker.io/getsentry/symbolicator:nightly
#11 DONE 0.0s

#12 [snuba-cleanup-onpremise-local internal] load metadata for docker.io/getsentry/snuba:nightly
#12 DONE 0.0s

#13 [sentry-cleanup-onpremise-local 4/5] RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
#13 CACHED

#14 [sentry-cleanup-onpremise-local 3/5] RUN if [ -z "${https_proxy}" ]; then echo "Acquire::https::proxy "${https_proxy}";" >> /etc/apt/apt.conf; fi
#14 CACHED

#15 [sentry-cleanup-onpremise-local 2/5] RUN if [ -z "${http_proxy}" ]; then echo "Acquire::http::proxy "${http_proxy}";" >> /etc/apt/apt.conf; fi
#15 CACHED

#16 [sentry-cleanup-onpremise-local 5/5] COPY entrypoint.sh /entrypoint.sh
#16 CACHED

#17 [symbolicator-cleanup-onpremise-local internal] load build context
#17 transferring context: 35B done
#17 DONE 0.0s

#18 [symbolicator-cleanup-onpremise-local 4/5] RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
#18 CACHED

#19 [symbolicator-cleanup-onpremise-local 2/5] RUN if [ -z "${http_proxy}" ]; then echo "Acquire::http::proxy "${http_proxy}";" >> /etc/apt/apt.conf; fi
#19 CACHED

#20 [symbolicator-cleanup-onpremise-local 3/5] RUN if [ -z "${https_proxy}" ]; then echo "Acquire::https::proxy "${https_proxy}";" >> /etc/apt/apt.conf; fi
#20 CACHED

#21 [symbolicator-cleanup-onpremise-local 5/5] COPY entrypoint.sh /entrypoint.sh
#21 CACHED

#22 [snuba-cleanup-onpremise-local 1/5] FROM docker.io/getsentry/snuba:nightly
#22 DONE 0.0s

#23 [snuba-cleanup-onpremise-local internal] load build context
#23 transferring context: 35B done
#23 DONE 0.0s

#24 [symbolicator-cleanup-onpremise-local] exporting to image
#24 exporting layers done
#24 writing image sha256:a3990cb0cbedc772cc018004be96392e140ca8f8a2837901a00f5684187b96ce done
#24 naming to docker.io/library/symbolicator-cleanup-onpremise-local done
#24 exporting layers done
#24 writing image sha256:59b5ba3f869ec363e3983597ebef5dcc8ac42f6c20f3a1615ec81b5e471f7dcc done
#24 naming to docker.io/library/snuba-cleanup-onpremise-local done
#24 writing image sha256:aa6c81dbb872cd794ae789b5133a0ae23b11b234b7d7398c10b78c9be6318d5b done
#24 naming to docker.io/library/sentry-cleanup-onpremise-local done
#24 DONE 0.1s

#25 [snuba-cleanup-onpremise-local 4/5] RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
#25 CACHED

#26 [snuba-cleanup-onpremise-local 2/5] RUN if [ -z "${http_proxy}" ]; then echo "Acquire::http::proxy "${http_proxy}";" >> /etc/apt/apt.conf; fi
#26 CACHED

#27 [snuba-cleanup-onpremise-local 3/5] RUN if [ -z "${https_proxy}" ]; then echo "Acquire::https::proxy "${https_proxy}";" >> /etc/apt/apt.conf; fi
#27 CACHED

#28 [snuba-cleanup-onpremise-local 5/5] COPY entrypoint.sh /entrypoint.sh
#28 CACHED

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them

Docker images built.

▶ Downloading and installing wal2json ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5418  100  5418    0     0  43789      0 --:--:-- --:--:-- --:--:-- 44048

▶ Bootstrapping and migrating Snuba ...
Network sentry_onpremise_default  Creating
Network sentry_onpremise_default  Created
Container sentry_onpremise-zookeeper-1  Creating
Container sentry_onpremise-clickhouse-1  Creating
Container sentry_onpremise-zookeeper-1  Created
Container sentry_onpremise-kafka-1  Creating
Container sentry_onpremise-clickhouse-1  Created
Container sentry_onpremise-kafka-1  Created
Container sentry_onpremise-clickhouse-1  Starting
Container sentry_onpremise-zookeeper-1  Starting
Container sentry_onpremise-zookeeper-1  Started
Container sentry_onpremise-kafka-1  Starting
Container sentry_onpremise-clickhouse-1  Started
Container sentry_onpremise-kafka-1  Started
2022-11-15 12:08:28,744 Initializing Snuba CLI...
2022-11-15 12:08:28,745 Initializing Snuba
2022-11-15 12:08:30,335 Snuba initialization took 1.5916846729960525s
2022-11-15 12:08:30,722 Initializing Snuba CLI...
2022-11-15 12:08:30,724 Initializing Snuba
2022-11-15 12:08:32,352 Snuba initialization took 1.6302817760006292s
2022-11-15 12:08:32,353 Attempting to connect to Kafka (attempt 0)...
2022-11-15 12:08:34,355 Attempting to connect to Kafka (attempt 1)...
2022-11-15 12:08:34,510 Connected to Kafka on attempt 1
2022-11-15 12:08:34,511 Creating Kafka topics...
Container sentry_onpremise-zookeeper-1  Running
Container sentry_onpremise-kafka-1  Running
Container sentry_onpremise-clickhouse-1  Running
2022-11-15 12:08:35,625 Initializing Snuba CLI...
2022-11-15 12:08:35,626 Initializing Snuba
2022-11-15 12:08:37,149 Snuba initialization took 1.5246262159926118s
2022-11-15 12:08:37,502 Initializing Snuba CLI...
2022-11-15 12:08:37,503 Initializing Snuba
2022-11-15 12:08:39,028 Snuba initialization took 1.5256706890068017s
Finished running migrations

▶ Creating additional Kafka topics ...

▶ Setting up / migrating database ...
Container sentry_onpremise-memcached-1  Creating
Container sentry_onpremise-symbolicator-1  Creating
Container sentry_onpremise-smtp-1  Creating
Container sentry_onpremise-clickhouse-1  Running
Container sentry_onpremise-zookeeper-1  Running
Container sentry_onpremise-kafka-1  Running
Container sentry_onpremise-snuba-api-1  Creating
Container sentry_onpremise-snuba-sessions-consumer-1  Creating
Container sentry_onpremise-snuba-transactions-consumer-1  Creating
Container sentry_onpremise-snuba-subscription-consumer-events-1  Creating
Container sentry_onpremise-snuba-consumer-1  Creating
Container sentry_onpremise-snuba-outcomes-consumer-1  Creating
Container sentry_onpremise-snuba-replacer-1  Creating
Container sentry_onpremise-snuba-subscription-consumer-transactions-1  Creating
Container sentry_onpremise-symbolicator-1  Created
Container sentry_onpremise-smtp-1  Created
Container sentry_onpremise-snuba-outcomes-consumer-1  Created
Container sentry_onpremise-snuba-replacer-1  Created
Container sentry_onpremise-memcached-1  Created
Container sentry_onpremise-snuba-subscription-consumer-transactions-1  Created
Container sentry_onpremise-snuba-subscription-consumer-events-1  Created
Container sentry_onpremise-snuba-consumer-1  Created
Container sentry_onpremise-snuba-api-1  Created
Container sentry_onpremise-snuba-sessions-consumer-1  Created
Container sentry_onpremise-snuba-transactions-consumer-1  Created
Container sentry_onpremise-smtp-1  Starting
Container sentry_onpremise-memcached-1  Starting
Container sentry_onpremise-symbolicator-1  Starting
Container sentry_onpremise-snuba-transactions-consumer-1  Starting
Container sentry_onpremise-snuba-api-1  Starting
Container sentry_onpremise-snuba-sessions-consumer-1  Starting
Container sentry_onpremise-snuba-consumer-1  Starting
Container sentry_onpremise-snuba-subscription-consumer-transactions-1  Starting
Container sentry_onpremise-snuba-outcomes-consumer-1  Starting
Container sentry_onpremise-snuba-subscription-consumer-events-1  Starting
Container sentry_onpremise-snuba-replacer-1  Starting
Container sentry_onpremise-smtp-1  Started
Container sentry_onpremise-memcached-1  Started
Container sentry_onpremise-symbolicator-1  Started
Container sentry_onpremise-snuba-subscription-consumer-transactions-1  Started
Container sentry_onpremise-snuba-sessions-consumer-1  Started
Container sentry_onpremise-snuba-subscription-consumer-events-1  Started
Container sentry_onpremise-snuba-transactions-consumer-1  Started
Container sentry_onpremise-snuba-consumer-1  Started
Container sentry_onpremise-snuba-replacer-1  Started
Container sentry_onpremise-snuba-outcomes-consumer-1  Started
Container sentry_onpremise-snuba-api-1  Started
12:08:50 [INFO] sentry.plugins.github: apps-not-configured
Running migrations for default
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, nodestore, replays, sentry, sessions, sites, social_auth
Running migrations:
  No migrations to apply.
Creating missing DSNs
Correcting Group.num_comments counter
/usr/local/lib/python3.8/site-packages/memcache.py:1303: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key is '':
/usr/local/lib/python3.8/site-packages/memcache.py:1304: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key_extra_len is 0:

▶ Setting up GeoIP integration ...
Setting up IP address geolocation ...
IP address geolocation database already exists.
IP address geolocation is not configured for updates.
See https://develop.sentry.dev/self-hosted/geolocation/ for instructions.
Error setting up IP address geolocation.

-----------------------------------------------------------------

You're all done! Run the following command to get Sentry running:

  docker compose up -d

-----------------------------------------------------------------`

**Comment by hubertdeng123** [comment]
Is this a clean install? We should no longer be using the `sentry_onpremise` naming convention, it should actually be `sentry-self-hosted`

**Comment by hubertdeng123** [comment]
Definitely seems like something might be corrupted here. Have you tried something like
`docker system prune -a`?

**Comment by cjesper** [comment]
Hi, 
Yes - i have tried system prune multiple times. As well as explicitly deleting the volumes. This did not solve the issue

**Comment by ethanhs** [comment]
Are you running from a fresh checkout/release zip? Perhaps there is a docker-compose.override.yml that is interferring? Or one of the files tracked by git is stale?
