### ISSUE TITLE
Install explanation no longer seems valid

### ISSUE THREAD

**Issue by JadenSWang** [getsentry/self-hosted#1815]
### Self-Hosted Version

22.10.0

### CPU Architecture

x86_64

### Docker Version

20.10.18

### Docker Compose Version

1.29.2

### Steps to Reproduce

Under getting started here: https://develop.sentry.dev/self-hosted/
- download the latest build here: https://github.com/getsentry/self-hosted/archive/refs/tags/22.10.0.zip
- unzip
- ./install.sh

the docker-compose.yml no longer has a port number as specified here:
https://forum.sentry.io/t/changing-port-after-running-install-sh/8988/2

### Expected Result

Change the port from 9000 to something else
./install.sh should "then ... tell [me] to run docker-compose up -d to start Sentry"

### Actual Result

Running ./install.sh runs sentry
killing ./instal.sh and running docker-compose up -d launches an obnoxious amount of containers (15+)

**Comment by hubertdeng123** [comment]
Are you attempting to change the port from 9000 to something else? That is an outdated forum post so yes, our `docker-compose.yml` file is no longer the same. `SENTRY_BIND` in the .env file includes the port that you can change

**Comment by JadenSWang** [comment]
Yeah, that was the general idea but I realized just how much of the setup was out of date :), I'll give the SENTRY_BIND a shot in the env file, kinda embarrassed I didn't even check for an environment file.

**Comment by JadenSWang** [comment]
./install.sh runs the docker container in command line mode, any idea how to run it in detached mode? docker-compose up -d creates way too many containers

**Comment by JadenSWang** [comment]
nevermind, ./install.sh creates docker containers for the installation process for some reason...

**Comment by hubertdeng123** [comment]
awesome keep me updated!
