### ISSUE TITLE
After upgrading from 22.9.0 to 22.11.0: There is 1 issue blocking event processing

### ISSUE THREAD

**Issue by djmartin67** [getsentry/self-hosted#1818]
### Self-Hosted Version

22.11.0

### CPU Architecture

x86_64

### Docker Version

Docker version 20.10.5+dfsg1, build 55c4c88

### Docker Compose Version

docker-compose version 1.28.6, build 5db8d86f

### Steps to Reproduce

Since upgrading from  22.9.0 to 22.11.0 we have a problem processing issues, on the issues main screen a red banner displays the message There is 1 issue blocking event processing.
When you click show details the following page shows Unknown Error in the Pending issues section.

The error below refers to offset out of range - is it related to this? https://github.com/getsentry/self-hosted/issues/478 
 
I tried the commands in the Kafka section here: https://develop.sentry.dev/self-hosted/troubleshooting/

<img width="1111" alt="Screenshot 2022-11-16 at 14 35 34" src="https://user-images.githubusercontent.com/44056161/202214876-317fe8cb-cf1c-4e9f-a921-b1596bb124f0.png">

I no longer get the AUTO_OFFSET_RESET error but the processing issue continues. I can now see ConnectionRefusedError: [Errno 111] Connection refused error message -see attached log

[log.txt](https://github.com/getsentry/self-hosted/files/10023237/log.txt)

<img width="1138" alt="Screenshot 2022-11-16 at 15 24 11" src="https://user-images.githubusercontent.com/44056161/202221623-8447c4fc-beae-4fb0-a056-5dcdd11102fb.png">
<img width="1154" alt="Screenshot 2022-11-16 at 15 24 26" src="https://user-images.githubusercontent.com/44056161/202221629-ce360708-7792-4253-87a8-72990d014ce7.png">

### Expected Result

Issues to be processed

### Actual Result

post-process-forwarder-errors_1             | 2022-11-16T12:33:35.172505798Z     raise Exception(msg.error())
post-process-forwarder-errors_1             | 2022-11-16T12:33:35.172507986Z Exception: KafkaError{code=_AUTO_OFFSET_RESET,val=-140,str="fetch failed due to requested offset not available on the broker: Broker: Offset out of range (broker 1001)"}

**Comment by hubertdeng123** [comment]
Ah darn, so the troubleshooting steps didn't work in your case? In your logs it seems like the worker is having trouble connecting

**Comment by hubertdeng123** [comment]
Seems to be happening for `/api/1/store`. That apparently is the endpoint to send [json payloads](https://develop.sentry.dev/sdk/store/)

**Comment by m-keller** [comment]
Running into the same issue after upgrading to 22.11.0. 22.10.0 does not expose this.

I ran tcpdump inside the symbolicator container and this is what happens:

Request

`{"sources": [{"type": "sentry", "id": "sentry:project", "url": "http://web:9000/api/0/projects/xxx/xxx/files/dsyms/", "token": "79750613c68e4b3e8aafafd8d87c32b2"}, {"type": "http", "id": "sentry:microsoft", "name": "Microsoft", "layout": {"type": "symstore"}, "filters": {"filetypes": ["pe", "pdb", "portablepdb"]}, "url": "https://msdl.microsoft.com/download/symbols/", "is_public": true}], "options": {"dif_candidates": true}, "stacktraces": [{"registers": {}, "frames": [{"function": "<redacted>", "package": "/private/var/containers/Bundle/Application/527FAF08-5068-4477-93E8-03AB5407BE38/kphone.app/kphone", "in_app": true, "image_addr": "0x1000d8000", `

Response

```
HTTP/1.1 422 Unprocessable Entity
Failed to deserialize the JSON body into the target type: unknown variant `portablepdb`, expected one of `pe`, `pdb`, `mach_debug`, `mach_code`, `elf_debug`, `elf_code`, `wasm_debug`, `wasm_code`, `breakpad`, `sourcebundle`, `uuidmap`, `bcsymbolmap`, `usym` at line 1 column 401
```

Gives me the impression that there is some disconnect between the outside container making the request and the symbolicator that does not understand a new file type, something got removed, changed etc.?

**Comment by m-keller** [comment]
For my problem removing Microsoft on this screen helped (while processing iOS symbols):

<img width="1200" alt="Screenshot 2022-11-17 at 9 56 36 PM" src="https://user-images.githubusercontent.com/2228415/202607506-a9274dab-e8f1-436e-8c91-8053ff404e15.png">

**Comment by djmartin67** [comment]
Hi Both thanks for the comments. As I upgraded from .9 to .11 and skipped version .10 I decided to roll back to .9 and upgrade to .10 from .9. This upgrade was successful and I can report I have had no issues running .10. So the issue is .11 related.

@m-keller I'll need to create a sandboxed environment to test but once I have it would be useful to have some more detail on how to debug - I'm new to Sentry in Docker containers so when you say you ran a tcpdump inside the symbolicator container I would be grateful if you could send me some links on how to do that and the reasoning behind it.

Thanks

Donald

**Comment by hubertdeng123** [comment]
Nice find! Perhaps this is some sort of regression that our e2e tests didn't catch...

**Comment by ethanhs** [comment]
My guess is this is related to the changes in snuba but I'm not certain.

**Comment by wampiedriessen** [comment]
I believe I have found the culprit. I have been able to fix this error by tweaking a local installation of sentry.
[I explained how and why in the other issue](https://github.com/getsentry/self-hosted/issues/1860#issuecomment-1351318749)

**Comment by ethanhs** [comment]
I'm going to close this in favor of that issue since it has more context on the solution (tl;dr, bump to 22.12 tomorrow)
