### ISSUE TITLE
Internal error FileNotFoundError sentry.tasks.store.process_event since 22.07

### ISSUE THREAD

**Issue by sbarrypoppulo** [getsentry/self-hosted#1825]
### Self-Hosted Version

22.10.0

### CPU Architecture

x86_64

### Docker Version

20.10.18

### Docker Compose Version

1.29.2

### Steps to Reproduce

We are observing a huge volume of an internal Sentry error since upgrading to 22.07. This errors accounts for 7.4 million out of total 15.1 million errors within our instance. As such, it's putting us under disk space issues for the instance. 

What is the reason for this error? How can we resolve this?

<img width="1598" alt="Screenshot 2022-11-18 at 10 46 46" src="https://user-images.githubusercontent.com/101636916/202690523-5ba55f99-61fe-48d6-9167-5298b4cc9429.png">

<img width="1560" alt="Screenshot 2022-11-18 at 10 47 24" src="https://user-images.githubusercontent.com/101636916/202690576-557504ca-630e-479f-b35c-9642eeff9fd9.png">

### Expected Result

Sentry should not fill itself up with internal errors

### Actual Result

Logs for specific services can be obtained on request

### Event ID

Opted out of self-hosted monitoring

**Comment by hubertdeng123** [comment]
So, this internal error has been happening for a while then? At any point in time, did you change the `filestore` config options?

**Comment by sbarrypoppulo** [comment]
Hi Hubert,

Yes, it appears to be happening with quite a while. No, no `filestore` config changes have been made in the last few months. However, we may have the command [here](https://github.com/getsentry/self-hosted/issues/1682#issuecomment-1241155153) to reclaim some disk space at some point. Would this be the reason for this error?

Please let me know if you require any further information to aid troubleshooting.

**Comment by ethanhs** [comment]
Yes, that probably is the cause of your error. Deleting random folders is a bit of a dangerous thing to do! Do you have any way to restore from a backup?
