### ISSUE TITLE
Unable to subscribe to Slack Events. Sentry URL does not response with the value of challenge parameter

### ISSUE THREAD

**Issue by alicjabarbarakalisz** [getsentry/self-hosted#1827]
### Self-Hosted Version

22.11.0.dev0

### CPU Architecture

x86_64

### Docker Version

20.10.17

### Docker Compose Version

2.6.0

### Steps to Reproduce

I am trying to integrate slack app with Sentry. I have followed the integration instructions as per the docs: 
https://develop.sentry.dev/integrations/slack/

The sentry is running in AWS EC2 . I have access to the UI. The config.yml file has been updated with slack's client_id, client_secret, signing_secret, verification_token.  

However when I want to enable slack events the Url I input does not respond with the value of challenge parameter.I have tried changing http to https but did not help. 

### Expected Result

<img width="866" alt="image" src="https://user-images.githubusercontent.com/95652820/202898795-c4fa23ec-0c66-4808-b366-b433e4c28a71.png">

### Actual Result

<img width="774" alt="image" src="https://user-images.githubusercontent.com/95652820/202898729-1f706ea4-77eb-42a8-8f53-6cb6cc66ddef.png">

**Comment by ethanhs** [comment]
Could you check the output of the logs from the `worker` container? There might be clues there.
