### ISSUE TITLE
GitLab Integration and releases/ API

### ISSUE THREAD

**Issue by failoman23** [getsentry/self-hosted#1831]
### Self-Hosted Version

22.4.0

### CPU Architecture

x86_64

### Docker Version

20.10.16

### Docker Compose Version

1.29.2

### Steps to Reproduce

I am trying to get GitLab integration to work: suspected commits, links to files where the error happend. We develop in C#

1. Install Gitlab Integration under Settings > Integrations (We are using GitlLab on-premise and I configured only one group, lets call it: **apis**)
2. I configured/activated few repositories. They show up in the UI as apis/MyApp

I am using API to create release first and when deployment happens also. This is done with two powershell scripts: release.ps1 and deploy.ps1. From the documentation I gathered one can use it even if integration is enabled. 
In my release.ps1 script I notify Sentry of the last commit with: id, author_name, author_email, repository, message and of course projects, dateReleased, version and url (here I put commit url).
I omitted the **patch_set** as I would like the GitLab-Integration to take care of changed files. I had a look at your code (https://github.com/getsentry/sentry/tree/master/src/sentry/integrations/gitlab/repository.py) where the function compare_commits does all I want to achive.

My release information is showing in Sentry's UI: the last commit, author of said commit but I get no suspected commits or changed files.
My assumption is that my repository name isn't correct and the GitLab integration doesnt know where to look. I have tried setting it to: 1. MyApp, 2. MyApp/feature (feature branch)

In logs there are no errors mentioning GitLab. The only error which might be related is this one: 

from docker-compose-service: _sentry_self_hosted_worker: sentry.tasks.release_registry:_
_Release registry URL is not specified, skipping the task._ I suspect this is due to not set SENTRY_RELEASE_REGISTRY_BASEURL environment variable.

I have also experimented with VSCode HttpClient to send my request to Sentry releases-Endpoint and received following response:

> "repository": {
>       "id": "51",
>       "name": "feature/SomeFeature",
>       "url": null,
>       "provider": {
>         "id": "unknown",
>         "name": "Unknown Provider"
>       },
>       "status": "active",
>       "dateCreated": "2022-11-24T19:30:55.734180Z",
>       "integrationId": null,
>       "externalSlug": null 

What stands out is that provider is unknown. I expected to find GitLab here.

### Expected Result

Working GitLab integration with suspected commits and links to files in repository where errors happen. 

### Actual Result

Missing suspected commits

**Comment by ethanhs** [comment]
Just to make sure, you followed https://docs.sentry.io/product/integrations/source-code-mgmt/gitlab/ and configured your integration after it was installed?

And also you set up code mapping and such?

**Comment by failoman23** [comment]
There is no option for code mapping. I replayed the whole proccess again: 
In Settings>Integrations>GitLab>Add Installation. I link our GitLab (On-permise) with application id and secret. After creating it I am redirected to repository view. I am able to add repositories. When I navigate back to Settings>Integrations>GitLab>Configurations and click on Configure I am redirected to repositories view

**Comment by failoman23** [comment]
Found it. It was just in front of me in "repository view"

![image](https://user-images.githubusercontent.com/15184821/206442283-3e4d85f2-1b81-49dc-add3-b5ffa76b03fd.png)
