### ISSUE TITLE
rrweb memory problem

### ISSUE THREAD

**Issue by Js-Man-H5** [getsentry/self-hosted#1832]
### Problem Statement

Added rrweb replay, causing memory to increase rapidly. What method or command should be used to clear it

### Solution Brainstorm

Now it is clear /var/lib/docker/volumes/sentry-data， whether there is a better way to restart the container but upload the map file again

**Comment by Js-Man-H5** [comment]
目前是清楚 /var/lib/docker/volumes/sentry-data 重新启动容器 但需要重新上传map文件，是否有更好的方法

**Comment by ethanhs** [comment]
Hi, sorry but did you mean "memory" as in RAM or "memory" as in disk/storage?

If it is memory, perhaps you are hitting https://github.com/getsentry/self-hosted/issues/1828 ?

If it is storage perhaps you need to check out our documentation: https://develop.sentry.dev/self-hosted/troubleshooting/#reducing-disk-usage
