### ISSUE TITLE
Cannot find error in logs when server crashes

### ISSUE THREAD

**Issue by ddkurguzikova** [getsentry/self-hosted#1833]
### Self-Hosted Version

22.11.0.dev0

### CPU Architecture

x86_64

### Docker Version

20.10.2

### Docker Compose Version

1.29.2

### Steps to Reproduce

Send many debug info files to my sentry self-hosted one by one
It's run to run error

### Expected Result

All files are located at server, server is stable

### Actual Result

**Server crashed**
Unable to see web-page

**Logs from command line:** 
DEBUG   2022-11-07 14:55:46.483800 +03:00 retry number 0, max retries: 0
error: API request failed
caused by: [35] SSL connect error (Server aborted the SSL handshake)

**Logs from  /var/log/nginx/error.log**
2022/11/28 02:01:24 [crit] # : *20763 SSL_do_handshake() failed (SSL: error:0A00006C:SSL routines::bad key share) while SSL handshaking, client: 

**And there are no errors in log from:**
1) docker-compose logs
2) docker logs id_containers

where else can I see log files?

**Comment by ddkurguzikova** [comment]
Additional info: server doesn't respond only for several minutes, after this time it starts to work itself. Server crashed only when I start uploading debug info from Windows machine

**Comment by ethanhs** [comment]
This error seems unrelated to self-hosted Sentry:

>  2022/11/28 02:01:24 [crit] # : *20763 SSL_do_handshake() failed (SSL: error:0A00006C:SSL routines::bad key share) while SSL handshaking, client:

And seems to be the root of your issues, SSL is not terminating correctly so the client can't actually reach Sentry. Maybe check how your TLS setup works and check for issues around that?

**Comment by ddkurguzikova** [comment]
Thank you for your replay!
It's seems that everything is okay with certificates
I have feeling that I just look at the wrong places for errors, and it is one of containers which crashes

**Comment by ddkurguzikova** [comment]
because ngnix works fine, while server crashes
<img width="810" alt="image" src="https://user-images.githubusercontent.com/110471348/204513981-ee987e88-9b29-4c56-af2e-969cfb0ebbc4.png">

**Comment by ethanhs** [comment]
Ah, I wonder if the nginx we include in our docker compose setup is having issues? Everything looks ok if you run `docker compose ps`?

**Comment by ddkurguzikova** [comment]
every container is up except of hosted_geoipupdate_1, but I do not think that it is unusual. May be server cannot handle many loads?

**Comment by ethanhs** [comment]
The sentry container doesn't handle SSL termination by default, so that likely is coming from elsewhere I expect.

**Comment by ddkurguzikova** [comment]
@ethanhs thanks for your reply, sorry, I was on vacation 

Could you please tell me where I should look for errors? ngnix config?
