### ISSUE TITLE
Is there any way to delete transactions for the single project in on-prem version or will project re-creating remove the transactions from nodestore?

### ISSUE THREAD

**Issue by akovalev-lrd** [getsentry/self-hosted#1834]
### Problem Statement

The issue relates to 'nodestore_node' table size.

We've found the project, which generates the same amount of data as the whole instance without it. We don't want delete anything else except transactions for that project for the dates issue took place.

- I was able to found [the post](https://github.com/getsentry/sentry/issues/40953#issuecomment-1302414231) which describes an ability to request transactions deleting for the cloud instance.. Is any functionality for the on-prem instance for the same?
- Will project re-creation delete transactions from database?

I understand, i'll need run VACUUM after it. The question is just about correct transactions removing without affecting other instance's data.

**Comment by ethanhs** [comment]
Hi, you may want to read the section on our docs: https://develop.sentry.dev/self-hosted/troubleshooting/#postgres which discusses reducing the size of the nodestore_node table.

**Comment by akovalev-lrd** [comment]
Yup, thank you very much. But as i can see it's about maintaining the base
and table after the deletion or after data reached retention period.

Do you have any solution for cleaning up unwanted data which is already in
the sentry, which takes more than half of the space and which will reach
retention date only after the database will fully fill the disk space? I
want to delete only the data which belongs to one single project, but not
cut the whole instance's retention period - other projects inside the
instance are fine and should keep data.

пн, 28 нояб. 2022 г., 21:58 Ethan Smith ***@***.***>:

**Comment by akovalev-lrd** [comment]
Looks like i found reply on my question. Do i understand it correct:

1. on worker run: sentry cleanup --project PROJECT-ID --days 1
2. on psql run vacuum job

And i will have my problems solved?

And off course, run pg-repack/vacuum full/dump-drop-create-load dump to make space visible for the system

**Comment by ethanhs** [comment]
That does sound correct for what you want to do.

**Comment by akovalev-lrd** [comment]
Hello! Sorry to disturb you again.

sentry worker says "Bulk NodeStore deletion not available for project selection"

Do we have any other way to proceed the deletion?
