### ISSUE TITLE
Can't configure alert for unhandled errors (was a Docs issue, moved)

### ISSUE THREAD

**Issue by jzaefferer** [getsentry/self-hosted#1837]
### Core or SDK?

Core Sentry product

### Which part? Which one?

Alerts

### Description

I'm looking for documentation to configure an Alert about "unhandled" issues (for a React Native app = crashes). While I can search for `error.unhandled = true` in the issues view, I can't figure out how to use this for alerts.

It seems pretty useful for alerts to focus on crashes, so I'm hoping this is possible already and "just" need documentation.

### Suggested Solution

see above - I don't know

**Comment by ethanhs** [comment]
I'll take a deeper look at this tomorrow but my initial theory is that these tags changed between 22.7 and 22.12? Could that be?

**Comment by jzaefferer** [comment]
@ethanhs is there additional information I could provide? If so, I'd need some pointers

**Comment by jzaefferer** [comment]
@chadwhitacre @ethanhs anything new on this? Can we contribute something?

**Comment by chadwhitacre** [comment]
> I guess the next step would be to find and read the code for the template where this appears and work backwards from there to get to a root cause for why this isn't showing up in your environment.

Someone needs to do this. I'm personally unable to prioritize this since it seems to only be affecting your instance @jzaefferer.

**Comment by jzaefferer** [comment]
It looks like this was resolved by upgrading our Sentry instance, we're now on 23.1.0 and I see the `error.unhandled` option now.

That alert is still not working, since we're currently not getting any alerts for specific issues (new issues, Number of events in an issue is more than), but that's a  separate issue, so I'm closing this.

**Comment by chadwhitacre** [comment]
Glad that did it, thanks for posting back. :)
