### ISSUE TITLE
Add Profiling

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/self-hosted#1838]
Arriving here from a hallway chat with @jernejstrasner @indragiek @phacops @hubertdeng123. We should aim to ship Profiling in self-hosted as close to GA as possible, ideally part of the same announcement but it's understood this is not a GA blocker.

## To Do

- [x] https://github.com/getsentry/team-ospo/issues/51
- [x] https://github.com/getsentry/team-profiling/issues/188
- [x] Add something to e2e test.
- [x] Add to `docker-compose.yml`.
- [x] Add to CalVer release pipeline.

**Comment by jernejstrasner** [comment]
@indragiek what's the plan on this one?

**Comment by chadwhitacre** [comment]
Putting this to backlog for now, let's revisit in Jan/Feb when closer to GA.

**Comment by irudoy** [comment]
Any ETA on this?

**Comment by phacops** [comment]
@irudoy a bit late to the party but we're targetting end of March for all this to be completed.

**Comment by chadwhitacre** [comment]
See #1873 and #1993 for examples to follow.

**Comment by jamesob** [comment]
Would love to see this feature in self-hosted.

**Comment by aldy505** [comment]
Just a heads up: when this is up and running, and people are submitting way too much profiling data from their applications, they can offload the profiling data into Azure Blob Storage, AWS S3 bucket, or GCP's GCS by providing (or maybe overriding) the value on the `SENTRY_BUCKET_PROFILES` environment variable. The default value is that it will write to a local filesystem (that will probably mounted to a Docker volume. See [here](https://github.com/getsentry/vroom/blob/6cc05b2e2652015f75f6b9b12c88f46fa486d2b8/Dockerfile#L17)).

A few examples:
- AWS S3: `s3://my-bucket?region=us-west-1&awssdk=2&endpoint=minio.selfhosted.com&s3ForcePathStyle=false&disableSSL=true`

    Do provide additional environment variables (if needed):
    - AWS_ACCESS_KEY=foobar
    - AWS_SECRET_KEY=foobar
    - AWS_SESSION_TOKEN=foobar (not required)

   Or, if you have machine running on AWS already, see https://docs.aws.amazon.com/sdk-for-go/api/aws/session/#pkg-overview for other methods on authenticating to S3.
- Azure Blob: `azblob://my-container?protocol=http&domain=localhost:10001&protocol=string&localemu=false&cdn=false`

    Do provide additional environment variables (if needed):
    -  AZURE_STORAGE_ACCOUNT=foobar
        Additional information per the documentations:
        > The service account name. Required if used along with AZURE_STORAGE KEY, because it defines authentication mechanism to be azblob.NewSharedKeyCredential, which creates immutable shared key credentials. Otherwise, "storage_account" in the URL query string parameter can be used.
     - AZURE_STORAGE_KEY=foobar
     - AZURE_STORAGE_SAS_TOKEN=foobar

  See https://pkg.go.dev/gocloud.dev/blob/azureblob#hdr-URLs for more information on authenticating.
- GCS: `gs://my-bucket`
    See https://cloud.google.com/docs/authentication#service-accounts for additional information on authentication. I don't know much about this one.

**Comment by chadwhitacre** [comment]
Woo-hoo! 😍 

🥔 💃 🎉 @phacops
