### ISSUE TITLE
A large number of errors are sent to the sentry, resulting in error messages that are not up to date

### ISSUE THREAD

**Issue by Julian-zly** [getsentry/self-hosted#1839]
### Self-Hosted Version

21.5.0

### CPU Architecture

x86_64

### Docker Version

20.10.21

### Docker Compose Version

1.29.2

### Steps to Reproduce

160,000 exceptions collected on sentry

### Expected Result

Get the latest error message

### Actual Result

The error message was two hours ago

**Comment by ethanhs** [comment]
With what time frame did you collect the 160,000 errors? We don't have concrete numbers for how much compute you need to run self-hosted, but it does greatly depend on your transaction rate of course.
