### ISSUE TITLE
sentry alert not triggered but thresholds have been met 

### ISSUE THREAD

**Issue by mahmoodkohansal** [getsentry/self-hosted#1845]
### Self-Hosted Version

22.6.0

### CPU Architecture

x86_64

### Docker Version

20.10.21

### Docker Compose Version

2.12.2

### Steps to Reproduce

1. Go to Alert's menu
2. Create a new alert (Alerts > Create Alert)
3. Setup a metric alert, Number of Errors then set conditions
4. Set the critical, warning, and resolved thresholds and Actions
5. Save the alert and go to the alert details page (dashboard)

### Expected Result

show triggered alerts that happened.

### Actual Result

there are no triggered events in the list, but the diagram shows that thresholds have been met.
<img width="903" alt="Screen Shot 1401-09-11 at 12 53 38" src="https://user-images.githubusercontent.com/4072975/205264225-af0617a1-81eb-449f-befd-209c692f5260.png">

**Comment by hubertdeng123** [comment]
Has this worked for you in the past? Can you post the logs? `docker compose logs`

**Comment by mahmoodkohansal** [comment]
No, it doesn't work in the past.
which part of the docker logs can help to find the problem?

**Comment by hubertdeng123** [comment]
I'm wondering if you're getting an error related to Kafka offset out of range. Is it possible for you to post the output of 
`docker compose logs` here?

**Comment by mahmoodkohansal** [comment]
I uploaded 1000 lines of docker compose logs [here](https://bimito.com/file/public/sentry.log).

**Comment by hubertdeng123** [comment]
Hmmm, not really able to tell anything from those logs. Can you limit the logs to those from the `sentry-self-hosted-web-1` container?

**Comment by mahmoodkohansal** [comment]
Yes, [this](https://bimito.com/file/public/logs_web1.log) file is part of sentry-self-hosted-web-1 container.

**Comment by hubertdeng123** [comment]
Unfortunately, I'm not really able to tell anything from those logs either. Are you filtering any issues?
