### ISSUE TITLE
Wrong Nginx upstream config ?

### ISSUE THREAD

**Issue by franck-grenier** [getsentry/self-hosted#1846]
### Self-Hosted Version

22.11.0

### CPU Architecture

x86_64

### Docker Version

Docker version 20.10.12, build e91ed57

### Docker Compose Version

docker-compose version 1.28.0, build d02a7b1a

### Steps to Reproduce

After fresh installation of 22.11.0 release,
`sentry-self-hosted_nginx_1` container is responding "502 Bad Gateaway" to API requests.

Checking `./nginx/nginx.conf`, I can see: 

```
upstream relay {
    server relay:3000;
}

upstream sentry {
    server web:9000;
}
```

`relay` and `web` are Docker-Compose services names. But the containers are: 
- `sentry-self-hosted_relay_1`
- `sentry-self-hosted_web_1`

Changing `./nginx/nginx.conf` as below fixed my Sentry: 

```
upstream relay {
    server sentry-self-hosted_relay_1:3000;
}

upstream sentry {
    server sentry-self-hosted_web_1:9000;
}
```

### Expected Result

working Sentry installation receiving issues through API

### Actual Result

Sentry installation unable to receive issues through API => "502 Bad Gateway"

**Comment by hubertdeng123** [comment]
Interesting, using the docker compose service names seem to be working for me. I wonder if there's something different about your setup. Can you do a `docker compose ps`? Is `relay` and `sentry` there as service names?

**Comment by franck-grenier** [comment]
Services are up. But containers names are not `relay` nor `web`.

```
docker ps | grep relay
48a1994c49c1      getsentry/relay:22.11.0      3000/tcp      sentry-self-hosted_relay_1
```

```
docker ps | grep web
69dcd2584794      sentry-self-hosted-local      9000/tcp      sentry-self-hosted_web_1
```
I don't know if one service is supposed to do the matching. But this matching does not occur on my setup.

**Comment by hubertdeng123** [comment]
Ok, I'm out of ideas 😕 This does appear to work generally for us and there may be something different about your setup that is causing this. I'm glad it's working for you after changing the nginx config though

**Comment by franck-grenier** [comment]
Ok,
thanks for your help.

Hope it could be useful for someone else.
