### ISSUE TITLE
SSO sign out with SAML is not working

### ISSUE THREAD

**Issue by timetofaceit** [getsentry/self-hosted#1850]
### Self-Hosted Version

22.10.0

### CPU Architecture

x86_64

### Docker Version

latest

### Docker Compose Version

latest

### Steps to Reproduce

Hi!

I'm trying to configure my ADFS SSO as auth method using SAML2. The problem I have is that when SSO is enabled I can't sign out from local admin user... When I hit sign out button it takes me to my login screen and when I hit login with SAML2 button, it logs me back in with local admin user again...

If I do a sign out manually from ADFS portal and hit login with SAML2 button in Sentry login page, it takes me to my ADFS SSO login page where I authenticate and then logins me again as local admin user again and not the AD user...

### Expected Result

Configure SAML with local admin, log out from local admin user and authenticate using SAML2 method with my SSO using my AD user to Sentry.

### Actual Result

-

**Comment by timetofaceit** [comment]
I think I managed to figure it out... SAML assigns local admin user to first SSO authenticated user to avoid losing local admin user access... So I need to create an AD user for this local admin user then to add SSO access for it.

What is left to solve is why I can't logout of ADFS when I hit sign out in sentry...

**Comment by hubertdeng123** [comment]
Glad you were able to figure out a part of your problem. What happens when you try to logout of ADFS?

**Comment by timetofaceit** [comment]
Sorry for late response. It logouts from Sentry, but not ADFS :/
