### ISSUE TITLE
Unable to create a team - A team with this slug already exists

### ISSUE THREAD

**Issue by Corepany** [getsentry/self-hosted#1851]
### Self-Hosted Version

22.11.0

### CPU Architecture

x86_64

### Docker Version

20.10.21

### Docker Compose Version

1.29.2

### Steps to Reproduce

1. Go to settings
2. Navigate to teams
3. click Create teams 
4. Add random name eg: 'Idonthavethisprojectrandomnumber123'

### Expected Result

Team created

### Actual Result

Toaster message
A team with this slug already exists

**Comment by hubertdeng123** [comment]
Is this a clean install? I seem unable to reproduce so I'll need some more information. Are docker compose logs returning anything useful?

**Comment by Corepany** [comment]
It was a clean installation. I need to prune all containers and install Sentry again. It is working now, but I can't provide further information since I have deleted it.

**Comment by hubertdeng123** [comment]
gotcha, well glad you were able to get it working!
