### ISSUE TITLE
[WARNING] sentry.tasks.release_registry

### ISSUE THREAD

**Issue by failoman23** [getsentry/self-hosted#1853]
### Self-Hosted Version

22.4.0

### CPU Architecture

x86_64

### Docker Version

20.10.16

### Docker Compose Version

1.29.2

### Steps to Reproduce

sentry-self-hosted_worker_1 reports following warning:
[WARNING] sentry.tasks.release_registry: Release registry URL is not specified, skipping the task

Questions: what is the cause of this warning?

### Expected Result

No warnings

### Actual Result

...
today at 11:21:0210:21:02 [WARNING] sentry.tasks.release_registry: Release registry URL is not specified, skipping the task.
today at 11:26:0210:26:02 [INFO] sentry.tasks.update_user_reports: update_user_reports.records_updated (reports_to_update=0 reports_with_event=0 updated_reports=0)
today at 11:26:0210:26:02 [WARNING] sentry.tasks.release_registry: Release registry URL is not specified, skipping the task.
today at 11:31:0210:31:02 [WARNING] sentry.tasks.release_registry: Release registry URL is not specified, skipping the task.
...

**Comment by hubertdeng123** [comment]
Looks like it's thrown on this [line](https://github.com/getsentry/sentry/blob/master/src/sentry/tasks/release_registry.py#L51). It should be a harmless warning but I'm not sure exactly why it's thrown either. Hopefully that's a start for you!

**Comment by failoman23** [comment]
Thank you. I found that line also and had a read on https://github.com/getsentry/sentry-release-registry/. My undersranding is that sentry-release-registry exists only for sentry.io to track all existing SDKs and its versions. I was hoping this error had something to do with my not working GitLab integration
