### ISSUE TITLE
Vercel integration is listening for legacy webhooks that aren't send anymore

### ISSUE THREAD

**Issue by hcentelles** [getsentry/self-hosted#1857]
### Self-Hosted Version

22.11.0

### CPU Architecture

x86_64

### Docker Version

20.10.21

### Docker Compose Version

2.12.0

### Steps to Reproduce

1. Configure a vercel integration following this steps https://develop.sentry.dev/integrations/vercel/
2. Create a vercel deployment

### Expected Result

Successful webhook reponse

### Actual Result

Webhook failed because is expecting a payload object different than what Vercel is actually sending.

The code is using vercel legacy webhooks. 

https://vercel.com/docs/integrations/webhooks-overview/webhooks-api#legacy-event-types

https://vercel.com/docs/integrations/webhooks-overview/webhooks-api#legacy-payload

Affected code: https://github.com/getsentry/sentry/blob/master/src/sentry/integrations/vercel/webhook.py#L153

**Comment by ethanhs** [comment]
@hcentelles did you find out a solution for this?

**Comment by hcentelles** [comment]
> @hcentelles did you find out a solution for this?

I opened a new issue because of wrong repo. https://github.com/getsentry/sentry/issues/42163
