### ISSUE TITLE
How to restart sentry when i modaify './sentry/config.yaml'?

### ISSUE THREAD

**Issue by yang200258** [getsentry/self-hosted#1859]
### Self-Hosted Version

22.11.0

### CPU Architecture

x86_64

### Docker Version

20.10.3

### Docker Compose Version

2.10.0

### Steps to Reproduce

1.edit the sentry config.yaml
2.want to refresh it

### Expected Result

take effect

### Actual Result

take effect

**Comment by yang200258** [comment]
Only run install.sh one way?

**Comment by hubertdeng123** [comment]
Changing the config.yml and running ./install.sh should work. Are you having issues there?

**Comment by yang200258** [comment]
> Changing the config.yml and running ./install.sh should work. Are you having issues there?

Thanks, I did have a few issues when I installed it, but it all worked out

**Comment by ethanhs** [comment]
@yang200258, in general the minimum changes required are `docker compose down`, `docker compose build`, then `docker compose up -d` as usual. It does depend a bit on what changes you make however.

Sounds like we're good to close this, glad you got things working.
