### ISSUE TITLE
Member invite link shows IP address

### ISSUE THREAD

**Issue by MohsenSepandar** [getsentry/self-hosted#1861]
### Self-Hosted Version

22.11.0

### CPU Architecture

x86_64

### Docker Version

20.10.12

### Docker Compose Version

1.29.2

### Steps to Reproduce

I have a problem with the unique invite link that sentry service generates. It shows the IP address and the port of the server.

### Expected Result

Hi.
I have installed self-hosted sentry on my server and want to invite a new member to the organization that I have created. I set domain name for my sentry server using nginx so that anybody can access it using domain name. My problem is when I want to create a new invitation link, it shows the exact IP address and its port in the invitation link, instead of the domain name that I have set for it. Is there any solution to solve this problem?
It is so important for me.
Thank you in advance.

### Actual Result

Hi.
I have installed self-hosted sentry on my server and want to invite a new member to the organization that I have created. I set domain name for my sentry server using nginx so that anybody can access it using domain name. My problem is when I want to create a new invitation link, it shows the exact IP address and its port in the invitation link, instead of the domain name that I have set for it. Is there any solution to solve this problem?
It is so important for me.
Thank you in advance.

**Comment by ethanhs** [comment]
Hi, did you set `system.url-prefix` in `sentry/config.yml`? Setting the url in nginx will not tell Sentry what URL it is being served as so it will default to the IP it is using I believe.
