### ISSUE TITLE
The 'Access-Control-Allow-Origin' header contains multiple values ‘xxx.com, *’ when i run Sentry.init in react

### ISSUE THREAD

**Issue by yang200258** [getsentry/self-hosted#1864]
### Self-Hosted Version

22.11.0

### CPU Architecture

x86_64

### Docker Version

20.10.3

### Docker Compose Version

2.10.0

### Steps to Reproduce

<img width="646" alt="image" src="https://user-images.githubusercontent.com/38518538/207210642-ccf2f1fc-949e-4301-8f57-2527ac246fdf.png">

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/38518538/207210487-928c0ec3-ecd0-4945-ad28-0e3518e92b9b.png">

### Expected Result

Normal use

### Actual Result

no

**Comment by yang200258** [comment]
The request is https://sentry.xxx.io/api/2/envelope/?sentry_key=xxxxx&sentry_version=7&sentry_client=sentry.javascript.react%2F7.24.2

**Comment by ethanhs** [comment]
Are the domains listed under your control or unknown to you? Is it the same entry listed multiple times?

**Comment by yang200258** [comment]
> Are the domains listed under your control or unknown to you? Is it the same entry listed multiple times?

yes，the domains under my control,every list happpened,but sentry can take those errors.
