### ISSUE TITLE
Include Session Replay in Self Hosted

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/self-hosted#1873]
### Problem Statement

Sentry has a Beta feature available: https://sentry.io/for/session-replay
We'd like our Self-Hosted customers to have access to it. As well as the Sandbox.

### Solution Brainstorm

Possibly once the product goes GA, make Session Replay available on self hosted Sentry

- [ ] List all configuration files that need to be changed

Relates to: https://github.com/getsentry/team-ospo/issues/64

**Comment by chadwhitacre** [comment]
Let's get a simple test added to [self-hosted e2e](https://github.com/getsentry/self-hosted/blob/a48d3795949ddf38d50aa846625c6e6591a1b824/_integration-test/run.sh).

**Comment by jas-kas** [comment]
Goal for upcoming sprint: Develop a plan for self-hosted support for Session Replay.

**Comment by chadwhitacre** [comment]
Thanks @jas-kas! Lmk if it would be helpful for me or @hubertdeng123 to join a team meeting. I talked to @bruno-garcia a bit, the main ask from us would be to add a happy-path end-to-end integration test in our [self-hosted test suite](https://github.com/getsentry/self-hosted/blob/master/_integration-test/run.sh). This gives us a simple seatbelt to make sure that Replay works for self-hosted users and does not regress. Hopefully it works already, but if not writing the test should surface that as well. The test suite is implemented in with bash/curl/jq and is a bit messy so we are happy to help answer questions about it.

Thanks for owning this! Looking forward to announcing to the world when Replay is verified in self-hosted!

**Comment by joshacheson** [comment]
Folks at risk of adding spam/notifications to your plate (and please, let me know if that's most of what I'm doing) I wanted to swoop in with some appreciation.

These conversations playing out in public are _so helpful_ as a user so that I can keep the pulse on how you guys are managing things I'm especially interested in (and Session Replay on self hosted is something I'm _extremely_ eager for). Stuff like this is much of what makes me a rabid fan of Sentry.

So anyways, thank you! <3 <3 <3

**Comment by chadwhitacre** [comment]
Thanks @joshacheson, that means a lot to hear! Hope we can get this in your hands asap. :D

**Comment by davidflypei** [comment]
I can't wait! I've been using sentry-rrweb with some hacky work arounds to get it working on browser and its been great when it works. Having official support in self hosted and the abilities its going have looks awesome!

**Comment by JoshFerge** [comment]
PR open here: https://github.com/getsentry/self-hosted/pull/1990

Question: do any docs need to be updated?

**Comment by JoshFerge** [comment]
Closed by https://github.com/getsentry/self-hosted/pull/1990

**Comment by chadwhitacre** [comment]
Reopening for https://github.com/getsentry/self-hosted/pull/2000 ...

**Comment by hubertdeng123** [comment]
Closing as we've decided to kick the integration test for replays to the future. Issue has been created to track that here:
https://github.com/getsentry/self-hosted/issues/2015

**Comment by joshacheson** [comment]
Hi folks, sorry for noise - was this included in release `23.3.0`, or expected in the next release?

**Comment by hubertdeng123** [comment]
@joshacheson FYI we've decided to cut a [23.3.1 release](https://github.com/getsentry/self-hosted/issues/2038) to fix replays for our users which will go out in the next few days
