### ISSUE TITLE
DSN is public, Web UI is private

### ISSUE THREAD

**Issue by mspolitaev** [getsentry/self-hosted#1877]
### Self-Hosted Version

22.10

### CPU Architecture

x86_64

### Docker Version

20.10.18

### Docker Compose Version

2.10.2

### Steps to Reproduce

We have a Sentry DSN which are publicly available, thus Sentry Web UI also available through the public internet. How we can restrict access to Web UI on sentry.company.com for example, by allow access only from internal network 10.0.0.0/8 and keep generated project's DSN publicly available like https://sdfsdfregr8824gf@sentry.company.com/14 ?

Is it possible in Sentry self-hosted? Thanks.

### Expected Result

Sentry Web UI available only from internal network, while DSN are publicly available.

### Actual Result

Sentry DSN are publicly available and Web UI too.

**Comment by hubertdeng123** [comment]
Did you by chance also post in discord? This should have a solution

https://github.com/getsentry/self-hosted/issues/1735

**Comment by mspolitaev** [comment]
Oh, looks like it was a solution. Thanks. 

But they made a split based on the path /api/store. Does the DSN fall into this path? I'll check tomorrow.

**Comment by hubertdeng123** [comment]
That's our relay service, which should handle all events that come in

**Comment by mspolitaev** [comment]
I see, let me check this approach, seems it's but i want check it on practice and do not ask here additional questions. I'll ask something tomorrow if need or we will close the issue. Thanks.

**Comment by hubertdeng123** [comment]
Sorry for the late response in discord, keep me updated here :)

**Comment by mspolitaev** [comment]
Yeah, i have checked 👌
Solution works like a charm, thank you guys. Please close.
