### ISSUE TITLE
pull access denied for snuba-api

### ISSUE THREAD

**Issue by mansplace** [getsentry/self-hosted#1878]
### Self-Hosted Version

master

### CPU Architecture

x86_64

### Docker Version

20.10.22

### Docker Compose Version

1.29.2

### Steps to Reproduce

clone repo;
run ./install.sh and wait

### Expected Result

sentry installed

### Actual Result

sentry install fails bcoz docker cant pull image
docker pull snuba-api 
Using default tag: latest
Error response from daemon: pull access denied for snuba-api, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by hubertdeng123** [comment]
The image for snuba definitely exists, https://hub.docker.com/r/getsentry/snuba. Are you able to pull other images from sentry?
