### ISSUE TITLE
New projects won't show in projects list

### ISSUE THREAD

**Issue by alekitto** [getsentry/self-hosted#1879]
### Self-Hosted Version

22.12.0

### CPU Architecture

x86_64

### Docker Version

20.10.7

### Docker Compose Version

2.2.2

### Steps to Reproduce

I created two projects in the Sentry organization (which already had other projects), but these ones do not show up in the "Projects" tab.
I can see those projects in the Settings tab, under Organization -> Projects, but when I click on one of those, it does not show anything, just the loading spinner that keeps spinning forever.

### Expected Result

Projects are created correctly and I can see them in the projects list

### Actual Result

Can't see any error reported in logs

**Comment by hubertdeng123** [comment]
Unfortunately this is not enough information for me to reproduce. Is there any other information you can provide for me?

**Comment by alekitto** [comment]
I manually created a deployment in one of the new projects and flushed redis db. Now the projects are visible in the dashboard, but when I click on it to see the issues, an error appears with this message "This project could not be found."
