### ISSUE TITLE
smtplib.SMTPServerDisconnected: Connection unexpectedly closed: timed out

### ISSUE THREAD

**Issue by LiuxzDrew** [getsentry/self-hosted#1883]
### Self-Hosted Version

22.11.0

### CPU Architecture

x86_64

### Docker Version

20.10.7

### Docker Compose Version

v2.0.1

### Steps to Reproduce

Failed to send mail

### Expected Result

Failed to send mail

### Actual Result

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/smtplib.py", line 396, in getreply
    line = self.file.readline(_MAXLINE + 1)
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 207, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 57, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 202, in _inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/base.py", line 64, in _wrapped
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/email.py", line 73, in send_email
    send_messages([message])
  File "/usr/local/lib/python3.8/site-packages/sentry/utils/email/send.py", line 18, in send_messages
    sent: int = connection.send_messages(messages)
  File "/usr/local/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 103, in send_messages
    new_conn_created = self.open()
  File "/usr/local/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 63, in open
    self.connection = self.connection_class(self.host, self.port, **connection_params)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 341, in connect
    (code, msg) = self.getreply()
  File "/usr/local/lib/python3.8/smtplib.py", line 399, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed: "
smtplib.SMTPServerDisconnected: Connection unexpectedly closed: timed out
11:10:46 [ERROR] celery.app.trace: Task sentry.tasks.email.send_email[216878a7-2920-4a10-8c9f-565f965d36ea] raised unexpected: SMTPServerDisconnected('Connection unexpectedly closed: timed out') (data={'hostname': '2317f5dfa70c', 'id': '216878a7-2920-4a10-8c9f-565f965d36ea', 'name': 'sentry.tasks.email.send_email', 'exc': "SMTPServerDisconnected('Connection unexpectedly closed: timed out')", 'traceback': 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.8/smtplib.py", line 396, in getreply\n    line = self.file.readline(_MAXLINE + 1)\n  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto\n    return self._sock.recv_into(b)\nsocket.timeout: timed out\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task\n    R = retval = fun(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 207, in _inner\n    reraise(*exc_info)\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 57, in reraise\n    raise value\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 202, in _inner\n    return f(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__\n    return self.run(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/base.py", line 64, in _wrapped\n    result = func(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/email.py", line 73, in send_email\n    send_messages([message])\n  File "/usr/local/lib/python3.8/site-packages/sentry/utils/email/send.py", line 18, in send_messages\n    sent: int = connection.send_messages(messages)\n  File "/usr/local/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 103, in send_messages\n    new_conn_created = self.open()\n  File "/usr/local/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 63, in open\n    self.connection = self.connection_class(self.host, self.port, **connection_params)\n  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__\n    (code, msg) = self.connect(host, port)\n  File "/usr/local/lib/python3.8/smtplib.py", line 341, in connect\n    (code, msg) = self.getreply()\n  File "/usr/local/lib/python3.8/smtplib.py", line 399, in getreply\n    raise SMTPServerDisconnected("Connection unexpectedly closed: "\nsmtplib.SMTPServerDisconnected: Connection unexpectedly closed: timed out\n', 'args': '()', 'kwargs': "{'message': <django.core.mail.message.EmailMultiAlternatives object at 0x7f0ebe2fb9a0>}", 'description': 'raised unexpected', 'internal': False})
11:10:46 [ERROR] sentry_sdk.errors: Unexpected status code: 400 (body: b'<html>\r\n<head>\r\n<title>400 Required SSL Certificate Not Sent</title>\r\n</head>\r\n<body bgcolor="white">\r\n<center>\r\n<div id="error"><h1>400 Required SSL Certificate Not Sent</h1></div>\r\n<hr><center>akamai/nginx</center><br><br>\r\n<table border="1">\r\n<col width="100">\r\n<col width="350">\r\n<td><p>Info</p></td>\r\n<td><div id="xinfo"><p>Client Certificate required</p></div></td>\r\n</tr>\r\n<tr>\r\n<td><p>Id</p></td>\r\n<td><div id="xid"><p>7414929730503495139</p></div></td>\r\n</tr>\r\n</table>\r\n</center>\r\n</body>\r\n</html>\r\n')
11:10:46 [ERROR] sentry_sdk.errors: Unexpected status code: 400 (body: b'<html>\r\n<head>\r\n<title>400 Required SSL Certificate Not Sent</title>\r\n</head>\r\n<body bgcolor="white">\r\n<center>\r\n<div id="error"><h1>400 Required SSL Certificate Not Sent</h1></div>\r\n<hr><center>akamai/nginx</center><br><br>\r\n<table border="1">\r\n<col width="100">\r\n<col width="350">\r\n<td><p>Info</p></td>\r\n<td><div id="xinfo"><p>Client Certificate required</p></div></td>\r\n</tr>\r\n<tr>\r\n<td><p>Id</p></td>\r\n<td><div id="xid"><p>5030662336732266904</p></div></td>\r\n</tr>\r\n</table>\r\n</center>\r\n</body>\r\n</html>\r\n')

**Comment by hubertdeng123** [comment]
What is the port are you using? Someone had a similar issue here:
https://stackoverflow.com/questions/47328056/smtpserverdisconnected-connection-unexpectedly-closed-timed-out

**Comment by ethanhs** [comment]
Hi, could you send a redacted version of how you configured email?
