### ISSUE TITLE
Unable to find image 'sentry-self-hosted-jq-local:latest' pull access denied for sentry-self-hosted-jq-local, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

### ISSUE THREAD

**Issue by justin48** [getsentry/self-hosted#1884]
### Self-Hosted Version

22.12.0

### CPU Architecture

x86_64

### Docker Version

20.10.22

### Docker Compose Version

1.29.0

### Steps to Reproduce

When I run the install script (install.sh) I get the following error.
#

> 
> Unable to find image 'sentry-self-hosted-jq-local:latest' locally
> docker: Error response from daemon: pull access denied for sentry-self-hosted-jq-local, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

I can't find this image on docker hub either 

> sentry-self-hosted-jq-local:latest 

Do I need someway to authenticate or permission to access it?

### Expected Result

Install Latest version of self hosted sentry

### Actual Result

> 
> Unable to find image 'sentry-self-hosted-jq-local:latest' locally
> docker: Error response from daemon: pull access denied for sentry-self-hosted-jq-local, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

**Comment by billni** [comment]
I'm seem to same issue, my solution is :
1. docker system info,
the result ：
----------------
 Labels:
 Experimental: true   # this value must be true, if it's false, you need to modify config.
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  http://hub-mirror.c.163.com/
 Live Restore Enabled: false
---------------------
2.  If Experimental is false,  you need to modify the /etc/docker/daemon.json, add new line :
experimental": true

3. save it , and redo ./install.sh, It can be ok .
4.

**Comment by gareth-johnstone** [comment]
I'm having the same issues

installed sentry just fine on a local almalinux 8.5 but having issues installing sentry on a cloud provider almalinux 8.5

**Comment by justin48** [comment]
> I've same issue, my solution is :
> 
> 1. docker system info,
>    output as follow:
>    ........................
>    Labels:
>    Experimental: true   # this value must be true, if it's false, you need to modify config.
>    Insecure Registries:
>    127.0.0.0/8
>    Registry Mirrors:
>    http://hub-mirror.c.163.com/
>    Live Restore Enabled: false
> 2. If Experimental is false,  you need to modify the /etc/docker/daemon.json, add new line :
>    "experimental": true
> 3. save it , and redo ./install.sh, It can be ok .

I tried adding "experimental": true to the daemon.json file but that didn't work.
I reloaded docker and restarted it. It still has the value false on the experimental attribute in docker system info tho. Not sure how to get that to update properly.
I added that line on a few different places on daemon.json

**Comment by loveangle66** [comment]
me too, add "experimental" it doesn't work! ,anyone can help to fix it !!!

**Comment by ziyu-93** [comment]
me too, the same promble 

docker version 20.10.8
compose version 1.29.2
error ：
   Unable to find image 'sentry-self-hosted-jq-local:latest' locally
   docker: Error response from daemon: pull access denied for sentry-self-hosted-jq-local, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

the result is still the same https://github.com/getsentry/self-hosted/issues/1819
who can fix it ..

**Comment by niziak** [comment]
On clean system when error reporting is enabled, and error occurs during execution of `install.sh` script tries to report error using ` [jq](https://github.com/getsentry/self-hosted/blob/ee9aea9f449ab7e41ad628771b338ca0e6b35fb8/install/error-handling.sh#L7) but image doesn't exists on clean system.

In my case there was existing external volume problem:
```bash
+ source create-docker-volumes.sh
++ echo '▶ Creating volumes for persistent storage ...'
▶ Creating volumes for persistent storage ...
+++ docker volume create --name=sentry-clickhouse
Error response from daemon: create sentry-clickhouse: driver 'anybox/buttervolume:latest' already has volume 'sentry-clickhouse': volume name must be unique
++++ cleanup ERR
++++ local retcode=1
++++ local 'cmd=docker volume create --name=sentry-clickhouse'
++++ [[ 0 -eq 1 ]]
++++ DID_CLEAN_UP=1
++++ [[ ERR != \E\X\I\T ]]
++++ set +o xtrace
Unable to find image 'sentry-self-hosted-jq-local:latest' locally
Unable to find image 'sentry-self-hosted-jq-local:latest' locally
docker: Error response from daemon: pull access denied for sentry-self-hosted-jq-local, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
docker: Error response from daemon: pull access denied for sentry-self-hosted-jq-local, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
Unable to find image 'sentry-self-hosted-jq-local:latest' locally
docker: Error response from daemon: pull access denied for sentry-self-hosted-jq-local, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
Unable to find image 'sentry-self-hosted-jq-local:latest' locally
docker: Error response from daemon: pull access denied for sentry-self-hosted-jq-local, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
Unable to find image 'sentry-self-hosted-jq-local:latest' locally
docker: Error response from daemon: pull access denied for sentry-self-hosted-jq-local, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
^C
```

**Comment by ethanhs** [comment]
This image is [built locally](https://github.com/getsentry/self-hosted/blob/ee9aea9f449ab7e41ad628771b338ca0e6b35fb8/install/build-docker-images.sh#L11). It looks like it should be built earlier, since the errors you are experiencing is before that image is built.

**Comment by WarriorXK** [comment]
I've got the same issue. Navigating to the repo and executing the following command seems to fix it:
`docker build -t sentry-self-hosted-jq-local --platform=linux/amd64 ./jq`
