### ISSUE TITLE
Error response from daemon: No command specified, Error in bootstrap-snuba.sh:3.,  '$dcr snuba-api bootstrap --no-migrate --force' exited with status 1

### ISSUE THREAD

**Issue by billni** [getsentry/self-hosted#1885]
### Self-Hosted Version

22.12.0

### CPU Architecture

Architecture: x86_64

### Docker Version

19.03.8

### Docker Compose Version

v2.6.1

### Steps to Reproduce

Install 22.12.0

### Expected Result

Script ./install.sh works successfully

### Actual Result

Error response from daemon: No command specified
Error in bootstrap-snuba.sh:3.
'$dcr snuba-api bootstrap --no-migrate --force' exited with status 1
-> ./install.sh:main:31
--> bootstrap-snuba.sh:source:3

Docker container logs :
..........................................
▶ Bootstrapping and migrating Snuba ...
Network sentry-self-hosted_default  Creating
Network sentry-self-hosted_default  Created
Container sentry-self-hosted-redis-1  Creating
Container sentry-self-hosted-clickhouse-1  Creating
Container sentry-self-hosted-zookeeper-1  Creating
Container sentry-self-hosted-redis-1  Created
Container sentry-self-hosted-zookeeper-1  Created
Container sentry-self-hosted-kafka-1  Creating
Container sentry-self-hosted-kafka-1  Created
Error response from daemon: No command specified
Error in bootstrap-snuba.sh:3.
'$dcr snuba-api bootstrap --no-migrate --force' exited with status 1
-> ./install.sh:main:31
--> bootstrap-snuba.sh:source:3

Looks like you've already sent this error to us, we're on it :)
Cleaning up...

**Comment by ethanhs** [comment]
Hm, could you please add `echo $dcr` in `bootstrap-snuba.sh` please? I'm not really sure how that error is happening...

**Comment by kiawizard** [comment]
The error is https://github.com/docker/cli/issues/2229
Fixed by apt-get install pass

**Comment by SunYong76** [comment]
same problem, solved it

before:
Docker Version : 20.10.16 

change:
Docker Version : 20.10.23 

for CentOS 7 x86_64
