### ISSUE TITLE
sentry 22.12.0 not support ldap？

### ISSUE THREAD

**Issue by LiuxzDrew** [getsentry/self-hosted#1886]
### Problem Statement

sentry 22.12.0 not support ldap？
I want Unified authentication using ldap。

**Comment by ethanhs** [comment]
LDAP is not supported by Sentry. There is a community plugin that adds LDAP support, but it seems like last we heard, [there was some work that needed to be done](https://github.com/getsentry/self-hosted/issues/1337#issuecomment-1048028154).
