### ISSUE TITLE
'$dcr snuba-api bootstrap --no-migrate --force' exited with status 1

### ISSUE THREAD

**Issue by steffjenl** [getsentry/self-hosted#1889]
### Self-Hosted Version

22.12.0

### CPU Architecture

x85_64

### Docker Version

20.10.22

### Docker Compose Version

1.29.2

### Steps to Reproduce

Run ./install.sh after upgrading from 22.11.x

### Expected Result

Installing version 22.12.0 and starting Sentry back online

### Actual Result

▶ Bootstrapping and migrating Snuba ...
Creating network "sentry-self-hosted_default" with the default driver
Creating sentry-self-hosted_clickhouse_1 ...
Creating sentry-self-hosted_zookeeper_1  ...
Creating sentry-self-hosted_redis_1      ...
Creating sentry-self-hosted_clickhouse_1 ... done
Creating sentry-self-hosted_zookeeper_1  ... done
Creating sentry-self-hosted_redis_1      ... done

ERROR: for kafka  Container "329a0cf3b387" is unhealthy.
Encountered errors while bringing up the project.
Error in bootstrap-snuba.sh:3.
'$dcr snuba-api bootstrap --no-migrate --force' exited with status 1
-> ./install.sh:main:31
--> bootstrap-snuba.sh:source:3

Cleaning up...

**Comment by ethanhs** [comment]
Hi, we've seen this fail sporadically, could you try to run the installer again?

**Comment by steffjenl** [comment]
I have removed the docker containers zookeeper and kafka and delete the kafka, zookeeper and zookeeper-log and run install.sh again and everything works great again!

`docker rm kafka`
`docker rm zookeeper`
`docker volume rm kafka`
`docker volume rm zookeeper`
`docker volume rm zookeeper-log`
