### ISSUE TITLE
No possibility to create organisations.

### ISSUE THREAD

**Issue by vaclav-kasal** [getsentry/self-hosted#1891]
### Self-Hosted Version

22.12.0

### CPU Architecture

x86_64

### Docker Version

20.10.22

### Docker Compose Version

v2.14.1

### Steps to Reproduce

1. clone repo and go inside `https://github.com/getsentry/self-hosted.git && cd self-hosted`
2. checkout 20.10.22 (same problem reproduced in master branch) `git checkout 20.10.22`
3. install sentry `./install.sh --no-report-self-hosted-issues`
4. login in and go to admin -> manage -> organizations

### Expected Result

There should be button to add organisation.

### Actual Result

There is not button to add organisation.
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/15031392/210151203-c0bee9cb-bf12-4619-a482-597037d66a7e.png">

**Comment by aminvakil** [comment]
AFAIK this is a self-hosted restriction.

**Comment by ethanhs** [comment]
This is not a self-hosted restriction, per-se, I believe that you might be able to change the setting here: https://github.com/getsentry/self-hosted/blob/19d6edfae05ab5386fe13529465d711ae1f2ed2e/sentry/sentry.conf.example.py#L58

No guarantee it will work though.
