### ISSUE TITLE
Cannot Access Web Instance from Desktop

### ISSUE THREAD

**Issue by steviegt6** [getsentry/self-hosted#1892]
### Self-Hosted Version

22.12.0

### CPU Architecture

x86_64

### Docker Version

20.10.21

### Docker Compose Version

2.12.2

### Steps to Reproduce

I would love to present steps to reproduce this issue but I'm not sure what's causing it or how it even happened.

Attempting to access my instance on desktop fails on all browsers I've tried. Accessing from my phone works fine.

#### Firefox 108.0.1 (64-bit)

![image](https://user-images.githubusercontent.com/27323911/210161810-3491e9d9-7727-4d27-b3f0-f91ce063d23c.png)

#### Edge 108.0.1462.54 (Official build) (64-bit)

![image](https://user-images.githubusercontent.com/27323911/210161827-40fdd9cd-c1ac-4fca-a266-82b63e930eb6.png)

#### Google Chrome 108.0.5359.125 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/27323911/210161848-5b9d67e0-ebf2-4e8c-8f75-a8c710e47c41.png)

### Linux arch 6.1.1-arch1-1

I had a friend try on his Arch installation as well, to confirm this isn't an issue with my machine or network.

#### Firefox 108.0.1

![image](https://user-images.githubusercontent.com/27323911/210161870-6f45ce1b-5db7-4e50-8c85-bd3130f13954.png)

### Other

I have tried this on a school-provided Chromebook (ChromeOS & Google Chrome 102.0.5005.193) as well, but district restrictions prevent me from sharing console logs. May or may not be negligible.

Loads without issue on my iPhone X (15.6.1) running Firefox 108.1 (24234).

### Expected Result

Web instance loads on desktop and I can continue as normal.

### Actual Result

Web instance does not load on desktop, instead failing due to issues with chunk loading.

[sentry_install_log-2023-01-01_02-42-31.txt](https://github.com/getsentry/self-hosted/files/10328328/sentry_install_log-2023-01-01_02-42-31.txt)
[docker-logs.txt](https://github.com/getsentry/self-hosted/files/10328347/docker-logs.txt)

**Comment by steviegt6** [comment]
I can also provide my nginx configuration later if it's needed or otherwise useful.

**Comment by hubertdeng123** [comment]
Interesting, were you able to access the web instance in browser before? Is this after upgrading to 22.12.0 or is this a clean install?

**Comment by steviegt6** [comment]
> Interesting, were you able to access the web instance in browser before? Is this after upgrading to 22.12.0 or is this a clean install?

I was able to access the web instance before, though it seemingly just stopped functioning one day. Decided to upgrade to the 22.12.0 (I believe I was only a month or two behind, but I'll try to confirm later) to see if this would resolve it. When that failed, attempted to reinstall a couple times through `reset.sh` to no avail as well.

**Comment by steviegt6** [comment]
I believe I've noticed this same problem with some other services I'm hosting, so I'll be closing this issue. Sorry for the trouble. I'll reopen if I can reproduce this on a new VPS without other issues.
