### ISSUE TITLE
Add option to disable "Request to Join" functionality

### ISSUE THREAD

**Issue by LordSimal** [getsentry/self-hosted#1893]
### Problem Statement

Currently we get random people triggering the `/api/0/organizations/{organization_slug}/join-request/` endpoint which for us is not really necessary/usefull because all our sentry users are manually created/invited.

### Solution Brainstorm

Therefore it would be awesome if this feature could be disabled in general so that no random users can trigger that API and request to join the organisation via e.g. `testing@example.com`

This should also hide the "Request to Join" button on the login form as well as disable the form `/join-request/<org-name>/`.

With that option present it would prevent any spam "Request to Join" entries from getting into sentry at all.

**Comment by hubertdeng123** [comment]
Have you tried to disable the `Request to Join` button? This should be in `Security and Privacy` settings
<img width="1160" alt="Screen Shot 2023-01-03 at 9 40 18 AM" src="https://user-images.githubusercontent.com/25517925/210411497-68ed81ea-78e8-4011-8352-1fd7d7b3f03a.png">

**Comment by LordSimal** [comment]
🙈 I am so stupid. Thanks for the help. Yes, this solves my problem.
