### ISSUE TITLE
Self-hosted Cloud Native Buildpack

### ISSUE THREAD

**Issue by akindo** [getsentry/self-hosted#1898]
### Problem Statement

We'd like to self-host Sentry in Scalingo (a cloud provider which [supports](https://doc.scalingo.com/platform/deployment/buildpacks/custom) [Cloud Native Buildpacks](https://buildpacks.io)). Any plans to create such a buildpack? I'm aware there's many dependencies, so not sure it's even technically possible? Thanks. :)

### Solution Brainstorm

If it's possible, create a Cloud Native Buildpack for running self-hosted Sentry.

**Comment by hubertdeng123** [comment]
That is something that we haven't planned to do at the moment sadly. Can I ask what the use case here is?
