### ISSUE TITLE
Wal2JSON version download is flaking

### ISSUE THREAD

**Issue by ethanhs** [getsentry/self-hosted#1899]
Wal2JSON keeps failing in CI. I initially thought this was due to Github's API being flaky, but it seems that it is something to do with the reading end of the pipes hanging up early. We should replace the pipes into grep and sed with a call to `jq` now that we use that in error handling.

Note I've only seen this in Github Actions... if someone sees this outside of that, please do comment below with your OS!

**Comment by chadwhitacre** [comment]
Boom.

```
{"message":"API rate limit exceeded for 13.64.10.224. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```

https://github.com/getsentry/self-hosted/actions/runs/3877670089/jobs/6612957076#step:4:957

**Comment by chadwhitacre** [comment]
We haven't cut a new wal2json release in almost two years. Let's hard-code it.
