### ISSUE TITLE
New Issues does't marked as NEW (22.10.0+ versions)

### ISSUE THREAD

**Issue by AndrewK0009** [getsentry/self-hosted#1902]
### Self-Hosted Version

22.12.0

### CPU Architecture

x86_64

### Docker Version

20.10.18

### Docker Compose Version

1.29.2

### Steps to Reproduce

![Screenshot](https://user-images.githubusercontent.com/122153761/211275269-e8beb514-5fcc-4fb6-9ee5-d0147256783a.png)

### Expected Result

It should be "New Issiue"  label 

![Screen](https://user-images.githubusercontent.com/122153761/211275901-1880d273-aad2-43fa-b903-edbaad31b77d.png)

### Actual Result

It doesn't work ( 22.10.0+ versions)
New issues haven't been marked as a New Issiue

**Comment by ethanhs** [comment]
When you say it doesn't work in 22.10.0+ versions, did you upgrade from a previous version where it was working?

**Comment by AndrewK0009** [comment]
> When you say it doesn't work in 22.10.0+ versions, did you upgrade from a previous version where it was working?

Yes. I updated Sentry from 22.9.0 to 22.10.0 (later 22.12.0)  and noticed that new issues haden't been marked as a New Issiue. Sentry has been rollouted back to 22.9.0

**Comment by John-jk** [comment]
Hello. 
I have the same problem, but on version 23.1.0 (fresh install). 
Any first event is created without the label “New Issue”, after the arrival of the second same event, the label appears. 

Ps: Everything worked on version 22.12.0.

**Comment by AndrewK0009** [comment]
> This issue has gone three weeks without activity. In another week, I will close it.
> 
> But! If you comment or otherwise update it, I will reset the clock, and if you label it `Status: Backlog` or `Status: In Progress`, I will leave it alone ... forever!
> 
> "A weed is but an unloved flower." ― _Ella Wheeler Wilcox_ wilted_flower


I still haven't received any response

**Comment by hubertdeng123** [comment]
This is now resolved, so closing 
https://github.com/getsentry/self-hosted/issues/1982
