### ISSUE TITLE
it is not clear from the documentation how the redis is connected from  relay and sentry.py

### ISSUE THREAD

**Issue by alexey-gavrilov-flant** [getsentry/self-hosted#1903]
### Problem Statement

redis is specified in the config https://github.com/getsentry/self-hosted/blob/master/relay/config.example.yml 

and there is sentry config https://github.com/getsentry/self-hosted/blob/master/sentry/sentry.conf.example.py#L73-L77
SENTRY_BUFFER or SENTRY_TSDB or else

can i specify different redis host values?

### Solution Brainstorm

instructions for using Redis by each sentry component  https://develop.sentry.dev/architecture/#high-level-overview

**Comment by ethanhs** [comment]
Hi! I'm sorry, I'm not certain what you are asking. If you just want to know if you can specify a custom redis host, yes you can. If you edit both the files you point out to replace "redis" with your hostname, that should work.
