### ISSUE TITLE
 Logging into Sentry gives error. Could possibly be related to Snuba..?

### ISSUE THREAD

**Issue by DeviNoles** [getsentry/self-hosted#1904]
### Self-Hosted Version

22.12.0

### CPU Architecture

 x86_64

### Docker Version

19.03.4

### Docker Compose Version

1.25.3

### Steps to Reproduce

1. Running ./install.sh
2. Get snuba build error.
3. I then run 'docker-compose up -d'
4. It Docker composes Sentry even though I received Snuba error in install.sh
![4](https://user-images.githubusercontent.com/24501975/211353687-6f91825f-3bec-4a22-b242-eec0ab7cb9be.PNG)

Here are images of the errors:
![1](https://user-images.githubusercontent.com/24501975/211354187-89959eac-9c46-440e-bea8-8195eb99ae6d.PNG)

![2](https://user-images.githubusercontent.com/24501975/211354157-13fefb22-22c1-4ad4-b9e2-450ab29f1360.PNG)

![3](https://user-images.githubusercontent.com/24501975/211354207-676ab580-b9b7-40b8-b45a-83b419438d52.PNG)

### Expected Result

Should be able to fully build and log into Sentry..

### Actual Result

![5](https://user-images.githubusercontent.com/24501975/211353849-26be88b8-7e0c-42fc-af21-c9ada458e5a9.PNG)

**Comment by ethanhs** [comment]
Hi, we only support docker-compose 1.28 and above. Can you try a newer version?

**Comment by DeviNoles** [comment]
![image](https://user-images.githubusercontent.com/24501975/211644034-a7f4d3d4-fc00-4eaa-8cdd-9eae579202b0.png)
My server is showing Docker Compose version v2.15.1. I was able to set up a brand new box

![image](https://user-images.githubusercontent.com/24501975/211649640-1831907d-f080-4184-bd5d-a7c9f5e69778.png)
Thank you.

**Comment by DeviNoles** [comment]
I was able to make a new Sentry box and change our endpoint to this original (broken) box's endpoint as seen here: #1413. Marking as closed. If anyone else has this issue in the future, make a brand new box and install everything from scratch. Then go into the postgres and find the keys table. Good luck 😃

**Comment by DeviNoles** [comment]
Changing the endpoint to the original endpoint as stated in #1413 did not fix my issue. We are not receiving issues on the new box even though the endpoint is the same as our old one. (DSN key + secret + Host Path).
