### ISSUE TITLE
Sentry broken after update [21.12 -> 22.01]

### ISSUE THREAD

**Issue by futureweb** [getsentry/self-hosted#1911]
### Self-Hosted Version

21.12

### CPU Architecture

x86_64

### Docker Version

20.10.22

### Docker Compose Version

1.28.6

### Steps to Reproduce

installed on: AlmaLinux release 8.7 (Stone Smilodon) running as Virtuozzo Container.
Trying to install small update (21.12.0 --> 22.01.0) but always breaks installation.

git checkout d6d11240f4a4faa9176329b1aaf3d7f609fec693 (= 22.1.0)
./install.sh

Error on snuba-api:
```
▶ Bootstrapping and migrating Snuba ...
Creating sentry-self-hosted_redis_1 ... 
Creating sentry-self-hosted_zookeeper_1 ... 
Creating sentry-self-hosted_clickhouse_1 ... 
Creating sentry-self-hosted_redis_1      ... done
Creating sentry-self-hosted_clickhouse_1 ... done
Creating sentry-self-hosted_zookeeper_1  ... done
Creating sentry-self-hosted_kafka_1      ... 
Creating sentry-self-hosted_kafka_1      ... done

ERROR: for snuba-api  Container "ae02ab867ba5" is unhealthy.
Encountered errors while bringing up the project.
An error occurred, caught SIGERR on line 3
Cleaning up...
```

### Expected Result

Update should work :-)

### Actual Result

See docker logs: http://in7.futureweb.at/temp/docker_logs.txt

**Comment by futureweb** [comment]
updated docker compose to: v2.14.1
Tried to update to 2022.12.0

Also Error:

```
container for service "clickhouse" is unhealthy
+++ cleanup ERR
+++ local retcode=1
+++ local 'cmd=$dcr snuba-api bootstrap --no-migrate --force'
+++ [[ 0 -eq 1 ]]
+++ DID_CLEAN_UP=1
+++ [[ ERR != \E\X\I\T ]]
+++ set +o xtrace
Error in ./bootstrap-snuba.sh:3.
'$dcr snuba-api bootstrap --no-migrate --force' exited with status 1
-> ./install.sh:main:31
--> ./bootstrap-snuba.sh:source:3

Looks like you've already sent this error to us, we're on it :)
```

**Comment by hubertdeng123** [comment]
Seems like this might be the root cause. 
`relation "sentry_userrole" does not exist`

Are you getting the same errors after upgrading docker compose?

**Comment by futureweb** [comment]
Tried a whole day to get it running - even with latest docker compose (v2.14.1) everytime something failed.
What I did in the end - no update, clean install with config files copied to new instance + using persistent Data Storage of old instance - worked pretty good this way ...
