### ISSUE TITLE
I WANT TO DEPLOY SENTRY SELF HOSTED ON CUSTOM PATH

### ISSUE THREAD

**Issue by sdarshil** [getsentry/self-hosted#1914]
### Self-Hosted Version

22.12.0

### CPU Architecture

x86_64

### Docker Version

20.10.14

### Docker Compose Version

1.29.2

### Steps to Reproduce

deploy sentry self-hosted

### Expected Result

want to deploy sentry on self-hosted machine on custom path look like :
http://0.0.0.0:9000/darshil 

### Actual Result

it is getting deployed on :
http://0.0.0.0:9000

**Comment by hubertdeng123** [comment]
Can I ask what the use case scenario is? I'm pretty sure we don't support this

**Comment by sdarshil** [comment]
The usecase is , we are deploying sentry o k8s and we have created one ingress to expose sentry frontend but on the / path of our root domain there is some other app already running so i want that i can run sentry on some custom path like /darshil so that we can use sentry on that custom path rather than directly /

**Comment by hubertdeng123** [comment]
Ah got it. Unfortunately, deploying on self-hosted through k8s is not officially supported. There are unofficial versions out there that you may be able to look at

**Comment by hubertdeng123** [comment]
Otherwise it seems like you might want to play around with nginx config or a reverse proxy of some sort

**Comment by sdarshil** [comment]
Yes but when i am using unofficial versions it looks like it is kinda same as afterall there is containers running as a pod , can you guide how tp tweak nginx config for this
