### ISSUE TITLE
ldap with freeipa

### ISSUE THREAD

**Issue by gusikina** [getsentry/self-hosted#1917]
### Self-Hosted Version

22.9.0

### CPU Architecture

x86_64

### Docker Version

20.10.7

### Docker Compose Version

1.29.2

### Steps to Reproduce

in sentry/enhance-image.sh i added

```#!/bin/bash

requirements=(sentry-auth-ldap)
# You can add other packages here, just like requirements.txt


# Install the dependencies of ldap
apt-get update
apt-get install -y --no-install-recommends build-essential libldap2-dev libsasl2-dev

pip install ${requirements[@]}

# Clean up to shrink the image size
apt-get purge -y --auto-remove build-essential
rm -rf /var/lib/apt/lists/*

# Support ldap over tls (ldaps://) protocol
mkdir -p /etc/ldap && echo "TLS_CACERT /etc/ssl/certs/ca-certificates.crt" > /etc/ldap/ldap.conf```

in sentry/sentry-conf.py
#############
# LDAP auth #
#############
import ldap
from django_auth_ldap.config import LDAPSearch, GroupOfUniqueNamesType

AUTH_LDAP_SERVER_URI = 'ldap://freeipa.EXAMPLE.COM'

AUTH_LDAP_BIND_DN = 'cn=LOGIN,cn=accounts,dc=EXAMPLE,dc=COM'
AUTH_LDAP_BIND_PASSWORD = 'PASS'

AUTH_LDAP_USER_SEARCH = LDAPSearch(
    'cn=users,cn=accounts,dc=EXAMPLE,dc=COM',
    ldap.SCOPE_SUBTREE, '(uid=%(user)s)',
)

AUTH_LDAP_GROUP_SEARCH = LDAPSearch(
    'cn=users,cn=accounts,dc=EXAMPLE,dc=COM', ldap.SCOPE_SUBTREE, '(objectClass=groupOfUniqueNames)'
)

AUTH_LDAP_GROUP_TYPE = GroupOfUniqueNamesType()
AUTH_LDAP_REQUIRE_GROUP = 'cn=admins,cn=groups,cn=accounts,dc=EXAMPLE,dc=COM'
AUTH_LDAP_DENY_GROUP = None

AUTH_LDAP_USER_ATTR_MAP = {
    'username': 'uid',
    'first_name': 'givenName',
    'last_name': 'sn',
    'email': 'mail'
}

SENTRY_SINGLE_ORGANIZATION=True
AUTH_LDAP_FIND_GROUP_PERMS = True
AUTH_LDAP_CACHE_GROUPS = True
AUTH_LDAP_GROUP_CACHE_TIMEOUT = 3600

AUTH_LDAP_SENTRY_ORGANIZATION_GLOBAL_ACCESS = True
AUTH_LDAP_SENTRY_SUBSCRIBE_BY_DEFAULT = False

AUTHENTICATION_BACKENDS = AUTHENTICATION_BACKENDS + (
    'sentry_ldap_auth.backend.SentryLdapBackend',
)

import logging
logger = logging.getLogger('django_auth_ldap')
logger.setLevel(logging.DEBUG)


### Expected Result

Integration with freeipa

### Actual Result

![photo_2023-01-17_12-11-48 (2)](https://user-images.githubusercontent.com/122877995/212887114-c8541c1a-c844-48f1-bd31-4a0f71339c3a.jpg)


### Event ID

_No response_

**Comment by hubertdeng123** [comment]
Are there logs in your `web` container that we can use to debug this issue?

**Comment by gusikina** [comment]
> Are there logs in your `web` container that we can use to debug this issue?

16:06:42 [WARNING] django_auth_ldap: Caught LDAPError while authenticating m.gusev: INVALID_CREDENTIALS({'msgtype': 97, 'msgid': 1, 'result': 49, 'desc': 'Invalid credentials', 'ctrls': []})
16:06:42 [WARNING] django.request: Not Found: /_static/dist/sentry/chunks/app_bootstrap_initializeMain_tsx.7a05f479d8837be3f637.js (status_code=404 request=<WSGIRequest: GET '/_static/dist/sentry/chunks/app_bootstrap_initializeMain_tsx.7a05f479d8837be3f637.js'>)
16:06:42 [WARNING] django.request: Not Found: /_static/dist/sentry/chunks/vendors-node_modules_emotion_react_jsx-runtime_dist_emotion-react-jsx-runtime_browser_esm_js--8cd9ca.a18b5077e8c9a20e017c.js (status_code=404 request=<WSGIRequest: GET '/_static/dist/sentry/chunks/vendors-node_modules_emotion_react_jsx-runtime_dist_emotion-react-jsx-runtime_browser_esm_js--8cd9ca.a18b5077e8c9a20e017c.js'>)

but my credentials are correct

**Comment by hubertdeng123** [comment]
How are you checking to ensure your credentials are correct?

**Comment by gusikina** [comment]
> How are you checking to ensure your credentials are correct?

with the same data, I can log in to freeipa. I have other services where there is integration with freeipa, similar to sentry. The work goes on without problems
