### ISSUE TITLE
How Connect Sentry to External Postgres Database

### ISSUE THREAD

**Issue by farhad8463** [getsentry/self-hosted#1920]
### Problem Statement

Dear All
I want connect self-hosted Sentry to my postgres database (external database).
how i can do this change?
Thanks

**Comment by hubertdeng123** [comment]
This should be possible. You'd need to tweak the configs in `sentry.conf.py` and `docker-compose.yml`. See this:
https://forum.sentry.io/t/how-can-i-connect-on-premise-to-database-running-in-rds/11047
