### ISSUE TITLE
service.platform should be part of the service.build.platforms: "linux/amd64"

### ISSUE THREAD

**Issue by nicky132** [getsentry/self-hosted#1924]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

22.9.0

### Steps to Reproduce

1.download self-hosted-22.9.0.zip
2./install.sh
3.
service.platform should be part of the service.build.platforms: "linux/amd64"
Error in build-docker-images.sh:6.
'$dc build --build-arg "http_proxy=${http_proxy:-}" --build-arg "https_proxy=${https_proxy:-}" --build-arg "no_proxy=${no_proxy:-}" --force-rm web' exited with status 1
-> ./install.sh:main:30
--> build-docker-images.sh:source:6

Event dispatched: ccce1c91-396c-49cf-a1bd-0423282cd097

### Expected Result

success

### Actual Result

service.platform should be part of the service.build.platforms: "linux/amd64"
Error in build-docker-images.sh:6.
'$dc build --build-arg "http_proxy=${http_proxy:-}" --build-arg "https_proxy=${https_proxy:-}" --build-arg "no_proxy=${no_proxy:-}" --force-rm web' exited with status 1
-> ./install.sh:main:30
--> build-docker-images.sh:source:6

**Comment by MegaThorx** [comment]
Same issue with docker version `20.10.14` and docker compose version `2.11.0` with the sentry `23.1.0` release.

**Comment by ethanhs** [comment]
@MegaThorx Odd request, but if you downgrade to compose 2.7.0 do you get the same error before patching the compose file? I wonder if Docker changed the schema (we should probably pin to a version at the top of the compose file...)

**Comment by MegaThorx** [comment]
```
root@sentry [ /docker/sentry ]# docker-compose --version
Docker Compose version v2.7.0
root@sentry [ /docker/sentry ]# docker-compose up -d
services.post-process-forwarder-errors.build Additional property platforms is not allowed
```

And after reverting the change it works again with the _older_ version.

**Comment by MegaThorx** [comment]
This issue is still relevant
