### ISSUE TITLE
Error in ensure-relay-credentials.sh:29.

### ISSUE THREAD

**Issue by thedtvn** [getsentry/self-hosted#1926]
### Self-Hosted Version

* get from github (Latest)

### CPU Architecture

arm64

### Docker Version

20.10.22

### Docker Compose Version

2.14.1

### Steps to Reproduce

run  sudo ./install.sh

### Expected Result

install ok and run

### Actual Result

![image](https://user-images.githubusercontent.com/80153297/213631799-d15eba39-e5ba-4f15-907c-3215b57722dd.png)

**Comment by hubertdeng123** [comment]
Can you do a `docker inspect` of the relay image?

**Comment by thedtvn** [comment]
> Can

I delete it
