### ISSUE TITLE
Azure AD SSO doesn't work for new users

### ISSUE THREAD

**Issue by Zaratusa** [getsentry/self-hosted#1928]
### Self-Hosted Version

23.1.0

### CPU Architecture

x86_64

### Docker Version

20.10.22

### Docker Compose Version

1.29.2

### Steps to Reproduce

1. Have existing accounts in sentry
2. Add Azure AD SSO as required login option
3. Try to login with a new Azure AD managed account

### Expected Result

Login is successful everything works

### Actual Result

Existsing users can link their account with Azure AD, but new users can't login in Sentry and get this error: 
```
Authentication error: Failed to map SAML attributes. Assertion returned the following attribute keys: 'http://schemas.microsoft.com/claims/authnmethodsreferences', 'http://schemas.microsoft.com/identity/claims/displayname', 'http://schemas.microsoft.com/identity/claims/identityprovider', 'http://schemas.microsoft.com/identity/claims/objectidentifier', 'http://schemas.microsoft.com/identity/claims/tenantid', 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname', 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name', 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname'
```
The login is shown as successful in Azure AD, but it fails in Sentry.

**Comment by hubertdeng123** [comment]
This is something that's a known issue actually, it's on our backlog so we'll track there. Please comment there so that we have more context.
https://github.com/getsentry/self-hosted/issues/1536
