### ISSUE TITLE
Can't install sentry

### ISSUE THREAD

**Issue by gareth-johnstone** [getsentry/self-hosted#1942]
### Self-Hosted Version

23.1.1

### CPU Architecture

x86_64

### Docker Version

20.10.23

### Docker Compose Version

2.15.1

### Steps to Reproduce

git clone https://github.com/getsentry/self-hosted.git . --branch 23.1.1
./install.sh

### Expected Result

I have a functional install of sentry

### Actual Result

▶ Bootstrapping and migrating Snuba ...
Container sentry-self-hosted-zookeeper-1  Creating
Container sentry-self-hosted-clickhouse-1  Creating
Container sentry-self-hosted-redis-1  Creating
Container sentry-self-hosted-redis-1  Created
Container sentry-self-hosted-clickhouse-1  Created
Container sentry-self-hosted-zookeeper-1  Created
Container sentry-self-hosted-kafka-1  Creating
Container sentry-self-hosted-kafka-1  Created
Container sentry-self-hosted-redis-1  Starting
Container sentry-self-hosted-clickhouse-1  Starting
Container sentry-self-hosted-zookeeper-1  Starting
Container sentry-self-hosted-clickhouse-1  Started
Container sentry-self-hosted-redis-1  Started
Container sentry-self-hosted-zookeeper-1  Started
Container sentry-self-hosted-zookeeper-1  Waiting
Container sentry-self-hosted-zookeeper-1  Error
dependency failed to start: container for service "zookeeper" is unhealthy
Error in bootstrap-snuba.sh:3.
'$dcr snuba-api bootstrap --no-migrate --force' exited with status 1
-> ./install.sh:main:31
--> bootstrap-snuba.sh:source:3

Envelope from file sentry-envelope-65fc8aab59c4268b073de65205449c12 dispatched
Cleaning up...

**Comment by hubertdeng123** [comment]
Is this a clean install? That's a flaky error that we're aware of. It will likely be resolved if you run the installer again.

**Comment by gareth-johnstone** [comment]
> Is this a clean install? That's a flaky error that we're aware of. It will likely be resolved if you run the installer again.

Yes clean install, its probably the 8th time ive tried and i seem to get this error every time.

I have also tried to run the installer twice, thrice in a row with the same error being produced.

**Comment by hubertdeng123** [comment]
Ah, this may be related then:
https://github.com/getsentry/self-hosted/issues/1445#issuecomment-1122415883

Could you try that and report back?

**Comment by gareth-johnstone** [comment]
> 

Tried setting the limits on the zookeeper docker and it hangs a little longer but still ultimately fails with the same error.

**Comment by gareth-johnstone** [comment]
@hubertdeng123 interestingly i changed from using Almalinux 9 as the host OS to Debian 10 and the install seems to go without a hitch!
