### ISSUE TITLE
How to deploy Sentry to Amazon ECS

### ISSUE THREAD

**Issue by berry2012** [getsentry/self-hosted#1943]
### Problem Statement

I want to deploy Sentry to Amazon ECS
How can I do this?

**Comment by hubertdeng123** [comment]
Have you attempted to do this yet? There are some steps here to do so from someone in the community:
https://technoapple.com/blog/post/How-to-Self-Hosted-Sentry.io-at-AWS-EC2

Just replace `onpremise` with `self-hosted`

**Comment by berry2012** [comment]
@hubertdeng123 thanks but that link is for Amazon EC2 and not Amazon ECS
