### ISSUE TITLE
About Transaction Counting

### ISSUE THREAD

**Issue by Seol827** [getsentry/self-hosted#1944]
### Self-Hosted Version

23.2.0

### CPU Architecture

x86_64

### Docker Version

20.10.16

### Docker Compose Version

2.6.0

### Steps to Reproduce

I'm using Sentry on the client side.
I Found that my project's transaction is too high I expected. Cause my project is not a production yet, so I'm the only one who accesses my project webpage. But I checked the transaction is almost 2.4k per hour. I can't understand that. Transaction counting is only for api or some Communications with back-end, isn't it?
Even I didn't enter my web, the transaction is still increasing.
I wonder this counting number is normal thing.

### Expected Result

low transaction counting

### Actual Result

almost 2.4k transactions per hour

**Comment by hubertdeng123** [comment]
Perhaps your project is having issues communicating with the back-end? What kind of transactions are they?

**Comment by hubertdeng123** [comment]
Are these transactions coming in through the `internal` project?

**Comment by Seol827** [comment]
> Are these transactions coming in through the `internal` project?

not internal project. Anyhow, in my opinion, my team applied 'google analytics', 'google reCaptcha', this can be problem. Is there any case with that?
