### ISSUE TITLE
docker-compose logs not giving the logs for any container

### ISSUE THREAD

**Issue by PrakashSuthar** [getsentry/self-hosted#1945]
### Self-Hosted Version

22.10.0

### CPU Architecture

x86_64

### Docker Version

20.10.21

### Docker Compose Version

1.29.2

### Steps to Reproduce

1. Install the self hosted sentry using `./install.sh`
2. Run `docker-compose logs`  command after successful installation (In my case as I am not getting any new errors logged on sentry UI, I wanted to debug the issue by analysing container logs)

Also, tried checking docker logs using `docker logs sentry-self-hosted_web_1`.

### Expected Result

logs related to all docker containers should be shown.

### Actual Result

docker-compose logs gives:
```
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.12) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Attaching to sentry-self-hosted_nginx_1, sentry-self-hosted_relay_1, sentry-self-hosted_sentry-cleanup_1, sentry-self-hosted_web_1, sentry-self-hosted_post-process-forwarder-errors_1, sentry-self-hosted_ingest-consumer_1, sentry-self-hosted_subscription-consumer-events_1, sentry-self-hosted_subscription-consumer-transactions_1, sentry-self-hosted_post-process-forwarder-transactions_1, sentry-self-hosted_cron_1, sentry-self-hosted_worker_1, sentry-self-hosted_snuba-consumer_1, sentry-self-hosted_snuba-replacer_1, sentry-self-hosted_snuba-outcomes-consumer_1, sentry-self-hosted_snuba-subscription-consumer-transactions_1, sentry-self-hosted_snuba-subscription-consumer-events_1, sentry-self-hosted_snuba-transactions-cleanup_1, sentry-self-hosted_snuba-transactions-consumer_1, sentry-self-hosted_snuba-cleanup_1, sentry-self-hosted_snuba-api_1, sentry-self-hosted_snuba-sessions-consumer_1, sentry-self-hosted_clickhouse_1, sentry-self-hosted_symbolicator-cleanup_1, sentry-self-hosted_geoipupdate_1, sentry-self-hosted_postgres_1, sentry-self-hosted_memcached_1, sentry-self-hosted_smtp_1, sentry-self-hosted_symbolicator_1, sentry-self-hosted_kafka_1, sentry-self-hosted_redis_1, sentry-self-hosted_zookeeper_1
```

docker logs <containerid/name> gives:
```Error response from daemon: configure logging driver does not support reading```

**Comment by hubertdeng123** [comment]
What logging driver are you using? These docs mention the ones that are supported:
https://docs.docker.com/config/containers/logging/configure/#limitations-of-logging-drivers

**Comment by PrakashSuthar** [comment]
@hubertdeng123 In my case it looks like by default log-driver value was configured to `none` due to which docker logs did not work for any container. I had to update the `/etc/docker/daemon.json` to use `json-file` log-driver explicitly. After that restarting docker service followed by `docker-compose up -d --force-recreate` was required to make new containers which can use json-file log driver.
