### ISSUE TITLE
Cannot install specific version

### ISSUE THREAD

**Issue by EdgarSedov** [getsentry/self-hosted#1947]
### Self-Hosted Version

Sentry 23.2.0.dev0 921eff5

### CPU Architecture

x86_64

### Docker Version

20.10.16

### Docker Compose Version

1.28.2

### Steps to Reproduce

1. clone sentry repo into new folder
2. git checkout 23.1.1
3. find last commit hash at https://github.com/getsentry/sentry/commits/23.1.1
4. run SENTRY_IMAGE=getsentry/sentry:921eff5 ./install.sh --skip-user-creation

### Expected Result

Installed expected version of sentry, 23.1.1

### Actual Result

Getting installed version Sentry 23.2.0.dev0 921eff5 (shows in footer)

**Comment by EdgarSedov** [comment]
No error, just dev version being installed instead of expected 23.1.1Sent from my Galaxy
-------- Original message --------From: Hubert Deng ***@***.***> Date: 1/31/23  21:03  (GMT+03:00) To: getsentry/self-hosted ***@***.***> Cc: EdgarSedov ***@***.***>, Author ***@***.***> Subject: Re: [getsentry/self-hosted] Cannot install specific version (Issue #1947) 
Can you post logs for the installation error?

**Comment by EdgarSedov** [comment]
Is there any way to install specific version? I need to automate sentry installation, but until i can find a proven way to install specific version it's pointless

**Comment by EdgarSedov** [comment]
Also, this dev version cannot start snuba-replacer (container keeps restarting):

> snuba-replacer_1                            | 2023-02-01 13:16:32,035 Initializing Snuba...
> snuba-replacer_1                            | 2023-02-01 13:16:33,672 Snuba initialization took 1.6369958340001176s
> snuba-replacer_1                            | 2023-02-01 13:16:34,081 Initializing Snuba...
> snuba-replacer_1                            | 2023-02-01 13:16:36,057 Snuba initialization took 1.9775049119998585s
> snuba-replacer_1                            | Usage: snuba replacer [OPTIONS]
> snuba-replacer_1                            | Try 'snuba replacer --help' for help.
> snuba-replacer_1                            | 
> snuba-replacer_1                            | Error: No such option: --max-batch-size
> snuba-replacer_1                            | 2023-02-01 13:16:37,135 Initializing Snuba...
> snuba-replacer_1                            | 2023-02-01 13:16:38,625 Snuba initialization took 1.490969482001674s
> snuba-replacer_1                            | 2023-02-01 13:16:38,931 Initializing Snuba...
> snuba-replacer_1                            | 2023-02-01 13:16:40,396 Snuba initialization took 1.4663110960027552s
> snuba-replacer_1                            | Usage: snuba replacer [OPTIONS]
> snuba-replacer_1                            | Try 'snuba replacer --help' for help.

**Comment by hubertdeng123** [comment]
You shouldn't need to pass in the `SENTRY_IMAGE` parameter, that will be set automatically in your `.env` file after checking out 23.1.1. The installed version of Sentry then should be correct

**Comment by EdgarSedov** [comment]
> You shouldn't need to pass in the `SENTRY_IMAGE` parameter, that will be set automatically in your `.env` file after checking out 23.1.1. The installed version of Sentry then should be correct

Thank you! That worked
