### ISSUE TITLE
Is it possible to use Slack integration while restrict IP access behind a VPN

### ISSUE THREAD

**Issue by Reyalsorik** [getsentry/self-hosted#1948]
### Self-Hosted Version

22.9.0

### CPU Architecture

x86_64

### Docker Version

20.10.18

### Docker Compose Version

2.10.2

### Steps to Reproduce

We've split the DSN and UI between 2 separate ports per: https://github.com/getsentry/self-hosted/issues/1735
This is working correctly. The DSN is open to the world and our UI is behind our corporate VPN.

We'd now like to enable Slack integration, but it looks like Slack requires some sort of POST authentication with each event.

Is there a recommended way to get around this?

### Expected Result

The self-hosted sentry application is running behind a VPN and Slack integration is able to communicate successfully.

### Actual Result

The self-hosted sentry application is running behind a VPN and Slack integration is unable to communicate.

**Comment by hubertdeng123** [comment]
I am unsure if this is possible, is there an error that is thrown when you try enabling the slack integration?
