### ISSUE TITLE
Recent changes to Events API payloads from slack,Can not get the alert in slack channel

### ISSUE THREAD

**Issue by yang200258** [getsentry/self-hosted#1949]
### Self-Hosted Version

23.2.0

### CPU Architecture

x86_64

### Docker Version

20.10.3

### Docker Compose Version

2.10.0

### Steps to Reproduce

1.I set the alert rule in sentry
2.when set custom Metric,the channel can get the alert
3.But when set the issue alert rule,can not get the alert
4.So when i configure the slack app,it is remommend me "Recent changes to Events API payloads"
<img width="1332" alt="image" src="https://user-images.githubusercontent.com/38518538/215939252-d8d1cc58-c2c5-48eb-b621-9cee1ad6c61c.png">

### Expected Result

It can send alert to slack channel.

### Actual Result

Can not send success.

**Comment by hubertdeng123** [comment]
Can you be more specific? So setting an alert rule in Sentry does work when sending slack notifications? However, when it's an issue related alert rule, it fails?

**Comment by yang200258** [comment]
> Can you be more specific? So setting an alert rule in Sentry does work when sending slack notifications? However, when it's an issue related alert rule, it fails?

Yes，my slack app bot can get the alerts,but not in my slack channel.
<img width="670" alt="image" src="https://user-images.githubusercontent.com/38518538/216484114-be8d0d90-7b7c-42b2-a41f-5adc23ed28d7.png">
