### ISSUE TITLE
nextjs how to disable performance tracing

### ISSUE THREAD

**Issue by Capricair** [getsentry/self-hosted#1951]
### Self-Hosted Version

Sentry 23.2.0.dev0

### CPU Architecture

x64

### Docker Version

20.10.23

### Docker Compose Version

2.15.1

### Steps to Reproduce

no

### Expected Result

some ways to disable performance tracking, looks like this
```
Sentry.init({
    ...
    performance: false
})
```

### Actual Result

no

**Comment by hubertdeng123** [comment]
You should be able to set the sample rate to 0 to not send anything for performance

https://docs.sentry.io/platforms/javascript/guides/nextjs/performance/
