### ISSUE TITLE
Event delayed for hours and delay is increasing

### ISSUE THREAD

**Issue by zjzwjcbj** [getsentry/self-hosted#1953]
### Self-Hosted Version

22.8.0.dev0

### CPU Architecture

x86_64

### Docker Version

20.10.17

### Docker Compose Version

1.29.2

### Steps to Reproduce

1. 8C64G
2. Three worker
3.A lot of requests
4.Discover search all events

### Expected Result

The event is near real-time to search.

### Actual Result

The latest event delayed for hours and delay is increasing.

**Comment by zjzwjcbj** [comment]
How can I improve it ?

**Comment by hubertdeng123** [comment]
Can you check your CPU/RAM usage and report back?

**Comment by zjzwjcbj** [comment]
I have increased some relevant parameters of the batch size, it is now normal. Thanks
