### ISSUE TITLE
HTTPClientError -> SoftTimeLimitExceeded() in s3 filestore (sourcemaps.read_archive_failed)

### ISSUE THREAD

**Issue by onmomo** [getsentry/self-hosted#1959]
### Self-Hosted Version

22.10.0

### CPU Architecture

x86_64

### Docker Version

20.10.16

### Docker Compose Version

2.6.0

### Steps to Reproduce

We are uploading source maps to sentry and have s3 filestore configured with a private aws s3 bucket. This source map upload to s3 works without issues. Also uploading profile images and such.

### Expected Result

During operation, we don't receive HTTPClientError sentry.tasks.store.process_event -> SoftTimeLimitExceeded() when reading source maps from s3.

### Actual Result

We randomly receive this exception during operation.

message
`sourcemaps.read_archive_failed`

HTTPClientError
An HTTP Client raised an unhandled exception: SoftTimeLimitExceeded()

```
 if self._file is None:
            with metrics.timer("filestore.read", instance="s3"):
                self._file = BytesIO()
                if "r" in self._mode:
                    self._is_dirty = False
                    self._file.write(self.obj.get()["Body"].read())
                    self._file.seek(0)
                if self._storage.gzip and self.obj.content_encoding == "gzip":
                    self._file = GzipFile(mode=self._mode, fileobj=self._file, mtime=0.0)
        return self._file
```

<img width="961" alt="Screenshot 2023-02-09 at 09 11 51" src="https://user-images.githubusercontent.com/1713109/217754605-a996e4f1-2916-4619-8d2f-753c4b59eab5.png">

The s3 bucket in question is currently at ~3gb. I think the SoftTimeout is set around 60s, is there a way to tweak this? I'm wondering why downloading a source map could require that much time but it seems to happen regularly.

**Comment by hubertdeng123** [comment]
Can you check your cpu/ram usage? Otherwise, this issue might be useful for you to check out
https://github.com/getsentry/self-hosted/issues/1131
