### ISSUE TITLE
Host cpu raised to 100% suddenly and crashed

### ISSUE THREAD

**Issue by doubaozia** [getsentry/self-hosted#1962]
### Self-Hosted Version

22.10.0

### CPU Architecture

x86_64

### Docker Version

20.10.21

### Docker Compose Version

2.12.2

### Steps to Reproduce

1. Download and install self-hosted sentry.
2. Follow the steps as sentry web document.
3. Whating for several days the host cpu raized to 100% and the services crashed.
I guess the reason for this issue is as the follows:
![image](https://user-images.githubusercontent.com/12318032/218625172-d4f5a62a-b9e3-48ed-9683-cb9fd1abbe9a.png)
The crash started from about 2023-02-12 01:04

### Expected Result

The sentry services is going as expected and without any crash.

### Actual Result

Sentry services crashed serveral days later, and the cpu usage raised up to 100% suddenly. This happened several times, and every time I restart the docker it still happens several days later.

**Comment by hubertdeng123** [comment]
How much RAM/CPU is on your host?

**Comment by doubaozia** [comment]
It's 8G RAM and 4 core CPU

**Comment by SliverYuki** [comment]
> How much RAM/CPU is on your host?

I had the same question on similar RAM/CPU configuration with @doubaozia (just 8G RAM and 4 cores CPU)

**Comment by cyrilcolinet** [comment]
Hi guys, same here with the same configuration on EC2 instance.
But the logs aren't really verbose for me, just crash and nothing else

**Comment by hubertdeng123** [comment]
I'm wondering if we need to increase the minimum RAM/CPU requirements for self-hosted. Would any of you be able to report back if the issue still happens after increasing RAM/CPU with your configurations?

**Comment by hubertdeng123** [comment]
I'm suspecting that the services might be crashing because of resource usage

**Comment by SliverYuki** [comment]
> I'm wondering if we need to increase the minimum RAM/CPU requirements for self-hosted. Would any of you be able to report back if the issue still happens after increasing RAM/CPU with your configurations?

I'm considering add this params `maxmemory-policy volatile-ttl maxmemeory 4G` to startup script，see https://github.com/getsentry/self-hosted/issues/1719#issuecomment-1284878683，it seems to help solve the problem

**Comment by doubaozia** [comment]
I have checked the host monitor and it's CPU and RAM data displays as the following image:
**The nomal (no crash) situation:**
![image](https://user-images.githubusercontent.com/12318032/219252821-1451ea92-b898-4ef0-a699-a7957f90289b.png)
**The crash situation:**
![image](https://user-images.githubusercontent.com/12318032/219253636-68153557-7ecb-4271-bb2d-841c61caa40c.png)
When the sentry services crashed, it's CPU raised suddenly(from 40% to 100%, normal is below 10%), and it's RAM did't raised. So I guess there must be some events trigger this issue.

**Comment by hubertdeng123** [comment]
That's what I'd assume too, the frequency is every once in a couple of days?

**Comment by doubaozia** [comment]
The frequency is about every three weeks or a month.

**Comment by cyrilcolinet** [comment]
> I'm wondering if we need to increase the minimum RAM/CPU requirements for self-hosted. Would any of you be able to report back if the issue still happens after increasing RAM/CPU with your configurations?

hi, I increased and for now it works well (from 4GB to 6GB)

**Comment by SliverYuki** [comment]
> > I'm wondering if we need to increase the minimum RAM/CPU requirements for self-hosted. Would any of you be able to report back if the issue still happens after increasing RAM/CPU with your configurations?
> 
> hi, I increased and for now it works well (from 4GB to 6GB)

Emmm, I've been using 8G since the beginning, but still have the problem

**Comment by cyrilcolinet** [comment]
> > > I'm wondering if we need to increase the minimum RAM/CPU requirements for self-hosted. Would any of you be able to report back if the issue still happens after increasing RAM/CPU with your configurations?
> > 
> > 
> > hi, I increased and for now it works well (from 4GB to 6GB)
> 
> Emmm, I've been using 8G since the beginning, but still have the problem

hum :/ how much storage?

**Comment by SliverYuki** [comment]
> > > > I'm wondering if we need to increase the minimum RAM/CPU requirements for self-hosted. Would any of you be able to report back if the issue still happens after increasing RAM/CPU with your configurations?
> > > 
> > > 
> > > hi, I increased and for now it works well (from 4GB to 6GB)
> > 
> > 
> > Emmm, I've been using 8G since the beginning, but still have the problem
> 
> hum :/ how much storage?

![image](https://user-images.githubusercontent.com/19161689/219618043-b75326f9-144e-4809-9c2f-c4e926b55ac8.png)
there is more than enough space left

**Comment by hubertdeng123** [comment]
Darn, we're running a self-hosted version of Sentry ourselves and we haven't noticed this issue. We're using 16 GB of RAM so that might be the bottleneck here

**Comment by crinjes** [comment]
I noticed that along with the slowly increasing CPU spikes over the past month, the disk read rate went up to GB/s for the duration of those spikes, while writes remained relatively low. This was 23.1.0

**Comment by doubaozia** [comment]
From the last time, this occured today again, and below is the CPU usage rate. It  raised to 30% for a hour and then reached 100% suddenly.
![image](https://user-images.githubusercontent.com/12318032/220816993-46d35479-d355-4c68-bc8b-430833aa13b0.png)
