### ISSUE TITLE
Add Log size restriction

### ISSUE THREAD

**Issue by pranaysharma** [getsentry/self-hosted#1964]
### Problem Statement

Hi ,
We are using self-hosted sentry and after a couple of months the server's space gets occupied fully.
I wanted to know if docker-compose based logging restrictions could be added?

### Solution Brainstorm

e.g.
`logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "10"
`

Reference: [Link](https://docs.docker.com/config/containers/logging/local/)

**Comment by hubertdeng123** [comment]
How much disk space are logs taking up? Have you tried adding the logging restrictions to your docker compose file?
