### ISSUE TITLE
Have a new issue，but alerts not triggered yet

### ISSUE THREAD

**Issue by shell0215** [getsentry/self-hosted#1967]
### Self-Hosted Version

22.6.0 

### CPU Architecture

x86_64

### Docker Version

 20.10.21

### Docker Compose Version

1.28.6

### Steps to Reproduce

Have a new issue,but alerts not triggered yet
![image](https://user-images.githubusercontent.com/125450324/218993399-5c329c06-050b-49cf-814e-f84243f3963a.png)
![image](https://user-images.githubusercontent.com/125450324/218993861-c9d33fab-8934-446c-bbef-af5e00d60dbc.png)
![image](https://user-images.githubusercontent.com/125450324/218993914-848cea54-30c3-4386-b5ac-7f4e212f5add.png)

### Expected Result

alerts also can be see all issue

### Actual Result

__        sentry - self - hosted - post - process - forwarder - 1 | 0
        9: 10:05[ERROR]
        sentry_sdk.errors: Internal
        error in sentry_sdk

**Comment by hubertdeng123** [comment]
There seems to be one issue with your configuration, could you tell me what that is?

**Comment by bobvandevijver** [comment]
@shell0215  I was having the same issue, in my case Kafka was misbehaving on one of our installations. Following the nuclear option described at  https://develop.sentry.dev/self-hosted/troubleshooting/#kafka fixed it for us.

**Comment by saschanos** [comment]
Experiencing the same issue; Sentry 23.1.1 – all other mails (e.g. weekly summary) are sent out correctly.
