### ISSUE TITLE
Symbolicator 401 Unauthorized Error

### ISSUE THREAD

**Issue by slvdr34m** [getsentry/self-hosted#1970]
### Self-Hosted Version

22.6.0

### CPU Architecture

x86_64

### Docker Version

20.10.9

### Docker Compose Version

1.29.2

### Steps to Reproduce

We deployed this project inside a restrict network environment directly by running "docker compose up". No extra steps performed.

### Expected Result

We expect the container `symbolicator` running without any error occurs in its logs.

### Actual Result

We got error logs from container: `symbolicator`.

```shell
2023-02-16T08:04:43Z [symbolicator::services::download::sentry] WARN: Sentry returned status code 401 Unauthorized
2023-02-16T08:04:43Z [symbolicator::services::download::sentry] WARN: Sentry returned status code 401 Unauthorized
2023-02-16T08:04:43Z [symbolicator::services::download::sentry] WARN: Sentry returned status code 401 Unauthorized
2023-02-16T08:04:43Z [symbolicator::services::objects] ERROR: Failed to fetch file list from sentry: failed to fetch data from Sentry
  caused by: bad status code from Sentry: 401 Unauthorized
```

To solve this problem, we googled it and found this link: https://forum.sentry.io/t/symbolicator-401-unauthorized-error/13878.

However, we cannot solve it by editing part of code inside `sentry/sentry.conf.py` like below:

```python
INTERNAL_SYSTEM_IPS = (get_internal_network(),"0.0.0.0/8",....."<our intranet ip address>",)
```

Any suggestions would be appreciated. We are looking forward for any timely reply for this issue.

**Comment by hubertdeng123** [comment]
Are you running `docker compose up -d`? We recommend using the `-d` flag

Are you certain the ip address you added is the ip address that symbolicator requests are coming from?

**Comment by slvdr34m** [comment]
> Are you running `docker compose up -d`? We recommend using the `-d` flag
> 
> Are you certain the ip address you added is the ip address that symbolicator requests are coming from?


------------------

> Are you running `docker compose up -d`? We recommend using the `-d` flag

Yes, we've tried to create/destroy containers many times via `docker compose up -d` and `docker compose down`. But it still does not work.

> Are you certain the ip address you added is the ip address that symbolicator requests are coming from?

Yes, since symbolicator sends requests from a docker container, we have added docker container's ip address which is like `172.19.0.0/16`. Also, we appended local ip address (E.G. `10.xx.xx.0/24`) from network interface of system to allowlist. But none of them worked.
