### ISSUE TITLE
Is data is secure?

### ISSUE THREAD

**Issue by rahulsingh806080** [getsentry/self-hosted#1971]
### Problem Statement

I want to know about data privacy in case of self hosted scenario. As per my company policy data can not be sent outside country. 

Where are data servers for self hosted versions.

**Comment by hubertdeng123** [comment]
Your self-hosted instance will never send any sort of data to us besides some usage metrics as outlined [here](https://develop.sentry.dev/self-hosted/) in the `Self-hosted Beacon` section. Otherwise, the server is wherever you'd like to host our self-hosted Sentry

**Comment by rahulsingh806080** [comment]
@hubertdeng123 thanks for quick response. Just for my knowledge , where r u storing free 90 days storage?
is that data is secure?
Where are server for these data?

**Comment by hubertdeng123** [comment]
The 90 days storage is stored on wherever you are hosting self-hosted Sentry (wherever you are running the install script). You can choose to add more security to our default setup if you'd like. Whether the data being secure or not is mostly dependent on whether or not the data on your server is secure.

**Comment by rahulsingh806080** [comment]
@hubertdeng123 Thanks. I am frontend guy. I just installed the as instructed. And Project is also running on localhost 9000.
I integrated that with dummy nextjs project which is working foine and logs are getting created. Just for curiosity where these data on localhost is store. how can i view them

**Comment by hubertdeng123** [comment]
@rahulsingh806080 Our self-hosted setup comes shipped with a backend that uses Postgres to store a lot of your data. You will be able to access that wherever you've installed Sentry.

**Comment by hubertdeng123** [comment]
You can docker exec into the postgres container which should be named something like
`sentry-self-hosted-postgres-1` and use psql or whatever you'd like to view entries

**Comment by rahulsingh806080** [comment]
@hubertdeng123 can we replace your postgres with our db?

**Comment by aldy505** [comment]
You could replace postgres with your own database, but that means you have to change every datastore implementation that already implemented on all of the other sentry's services (it's all open source though).

If you're worried about your data being sent out of your own server that runs the self-hosted sentry, you can just turn off the telemetry (or analytics) that is prompted early on the installation phase. That way, you can be 100% sure that your data is not going anywhere.

**Comment by hubertdeng123** [comment]
Closing this as it looks like the main question has been answered.
