### ISSUE TITLE
IntegrityError('null value in column "name" violates not-null constraint

### ISSUE THREAD

**Issue by integrator-sev** [getsentry/self-hosted#1978]
### Problem Statement

Sentry 9.1.2(self-hosted, dockerized). I want upgrade to 21.5.0. When run container web with command  'upgrade --noinput'  I see in log : "django.db.utils.IntegrityError: IntegrityError('null value in column "name" violates not-null constraint\nDETAIL:  Failing row contains (169, null, sentry, alertrule).\n',)
SQL: INSERT INTO "django_content_type" ("app_label", "model") VALUES (%s, %s) RETURNING "django_content_type"."id""
And upgrade fails. 
How I can resolve this problem ???

**Comment by hubertdeng123** [comment]
Does one your alertrules currently not have a name? You may need to manually edit that in your postgres db if that's the case
