### ISSUE TITLE
sentry-worker sentry-kafka-2.sentry-kafka-headless.sentry.svc.cluster.local:9092: Timed out 1 in-flight

### ISSUE THREAD

**Issue by source-xm** [getsentry/self-hosted#1979]
### Self-Hosted Version

22.3

### CPU Architecture

x86_64

### Docker Version

20.10.16

### Docker Compose Version

>3.0.0

### Steps to Reproduce

tying them to specific queues using the -Q queue_name argument. 

### Expected Result

normal connection kafka，normal operation save_event

### Actual Result

error message comes from:sentry-worker -Q events.save_event
![image](https://user-images.githubusercontent.com/15379012/220499678-078ee467-cfd3-43c5-b368-44dab15d233e.png)
It can be determined that the kafka logs of the connection related to snuba are normal

should I adjust the relevant parameters of kafka, perhaps because the maximum connection is limited?

**Comment by hubertdeng123** [comment]
Can you give me more details on how to reproduce? are you changing kafka args?
