### ISSUE TITLE
Sentry ignores system.url-prefix behind nginx proxy

### ISSUE THREAD

**Issue by akarabach** [getsentry/self-hosted#1980]
### Self-Hosted Version

23.3.0

### CPU Architecture

x86_64

### Docker Version

20.10.16

### Docker Compose Version

2.6.0

### Steps to Reproduce

1. We have nginx server which proxy all requests to sentry for specific path

```
  location /sentry {
      proxy_pass http://192.168.1.22:9000;
  }
```

2. Our sentry config

`system.url-prefix: 'https://example.duckdns.org:8443/sentry'`

### Expected Result

Sentry is working on `https://example.duckdns.org:8443/sentry/**`

### Actual Result

Sentry is redirecting all request to root 'https://example.duckdns.org:8443' and ignores '/sentry' path which is specified in config

**Comment by hubertdeng123** [comment]
This doesn't look like it's supported anymore from our [docs](https://develop.sentry.dev/config/), so I'm going to go ahead and close this
```
The URL prefix in which Sentry is accessible. This will be used both for referencing URLs in the UI, as well as in outbound notifications. This only works for scheme, hostname and port. In particular, it does not work for path (we supported this years ago, but it became too difficult to maintain). Sentry needs to be at the root of its own (sub)domain or IP address.
```
