### ISSUE TITLE
Install fails: container sentry-self-hosted-postgres-1 is unhealthy

### ISSUE THREAD

**Issue by knycket** [getsentry/self-hosted#1981]
### Self-Hosted Version

23.2.0

### CPU Architecture

x86_64

### Docker Version

20.10.23

### Docker Compose Version

v2.16.0

### Steps to Reproduce

sudo ./install.sh

### Expected Result

Successfully

### Actual Result

dependency failed to start: container sentry-self-hosted-postgres-1 is unhealthy
Error in install/set-up-and-migrate-database.sh:12.
'$dcr web upgrade' exited with status 1
-> ./install.sh:main:33
--> install/set-up-and-migrate-database.sh:source:12

Envelope from file sentry-envelope-b0bddf588294d0507c07dee0d22d913f dispatched
Cleaning up...

Install log:
[Sentel-install.log](https://github.com/getsentry/self-hosted/files/10814606/Sentel-install.log)

**Comment by hubertdeng123** [comment]
Are there any logs from the `sentry-self-hosted-postgres-1` container that might be useful here? That's not a lot of information for me to go off of

**Comment by knycket** [comment]
$ docker logs sentry-self-hosted-postgres-1
exec /opt/sentry/postgres-entrypoint.sh: no such file or directory
exec /opt/sentry/postgres-entrypoint.sh: no such file or directory
exec /opt/sentry/postgres-entrypoint.sh: no such file or directory
exec /opt/sentry/postgres-entrypoint.sh: no such file or directory
exec /opt/sentry/postgres-entrypoint.sh: no such file or directory
exec /opt/sentry/postgres-entrypoint.sh: no such file or directory
exec /opt/sentry/postgres-entrypoint.sh: no such file or directory
exec /opt/sentry/postgres-entrypoint.sh: no such file or directory

**Comment by hubertdeng123** [comment]
Can you check if that file exists? or if you have permissions to access the file?

**Comment by knycket** [comment]
I'm not able to access the container and list files

$ docker-compose up -d
[+] Running 19/20
 ⠿ Container sentry-self-hosted-zookeeper-1                                Healthy                  0.5s
 ⠿ Container sentry-self-hosted-kafka-1                                Healthy                   1.5s
 ⠿ Container sentry-self-hosted-smtp-1                                Running                    0.0s
 ⠿ Container sentry-self-hosted-clickhouse-1                                Healthy                  1.0s
 ⠿ Container sentry-self-hosted-redis-1                                     Healthy                  1.5s
 ⠿ Container sentry-self-hosted-memcached-1                                 Running                  0.0s
 ⠿ Container sentry-self-hosted-snuba-api-1                                 Running                  0.0s
 ⠿ Container sentry-self-hosted-symbolicator-1                              Running                  0.0s
 ⠿ Container sentry-self-hosted-geoipupdate-1                               Started                  0.3s
 ⠿ Container sentry-self-hosted-snuba-consumer-1                            Running                  0.0s
 ⠿ Container sentry-self-hosted-snuba-transactions-consumer-1               Running                  0.0s
 ⠿ Container sentry-self-hosted-snuba-replacer-1                            Running                  0.0s
 ⠿ Container sentry-self-hosted-snuba-outcomes-consumer-1                   Running                   0.0s
 ⠿ Container sentry-self-hosted-snuba-subscription-consumer-events-1        Running                  0.0s
 ⠿ Container sentry-self-hosted-snuba-subscription-consumer-transactions-1  Running                  0.0s
 ⠿ Container sentry-self-hosted-snuba-sessions-consumer-1                   Running                  0.0s
 ⠿ Container sentry-self-hosted-symbolicator-cleanup-1                      Started                  0.0s
 ⠿ Container sentry-self-hosted-postgres-1                                  Error                  1.5s
 ⠿ Container sentry-self-hosted-snuba-transactions-cleanup-1                Started                   0.0s
 ⠿ Container sentry-self-hosted-snuba-cleanup-1                             Started                   0.0s
dependency failed to start: container sentry-self-hosted-postgres-1 is unhealthy

$ docker exec -t -i  sentry-self-hosted-postgres-1 /bin/bash
Error response from daemon: Container 240437c944c1729959d58a60545f1cbbfa135982e6543b7bb768deb6e19911b6 is restarting, wait until the container is running

**Comment by knycket** [comment]
I removed all containers and images and reinstalled from scratch and then it was successful.
