### ISSUE TITLE
How to remove breadcrumbs

### ISSUE THREAD

**Issue by JoyJeck** [getsentry/self-hosted#1983]
### Problem Statement

Sentry's breadcrumbs occupy too many bytes

**Comment by hubertdeng123** [comment]
What SDK are you using? You can turn it off as seen here if you're using javascript SDK:
https://github.com/getsentry/sentry-javascript/issues/1706

**Comment by JoyJeck** [comment]
> What SDK are you using? You can turn it off as seen here if you're using javascript SDK: [getsentry/sentry-javascript#1706](https://github.com/getsentry/sentry-javascript/issues/1706)
Deployed in docker mode, the version is self-hosted-23.2.0
