### ISSUE TITLE
Component Stack doesn't appear in Sentry dashboard. [NextJS]

### ISSUE THREAD

**Issue by meotimdihia** [getsentry/self-hosted#1987]
### Problem Statement

Next.js recently added Component Stack for the errors:
- "Hydration failed because the initial UI does not match what was rendered on the server."
- "There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering"

This is an error that I can't produce on the client. It just reports once and disappears

Related to these issues:
- https://github.com/facebook/react/issues/24519#issuecomment-1439915463
- https://github.com/facebook/react/issues/24519#issuecomment-1439915463
![image](https://user-images.githubusercontent.com/300961/221465311-366cbb27-14bb-4795-b945-b560a7000d7e.png)

**Comment by hubertdeng123** [comment]
Hi there, thanks for reporting. Are you saying this exception is being thrown but not displayed in your Sentry instance?

**Comment by meotimdihia** [comment]
Sorry, I posted it on the wrong repo. I want to post this in the https://github.com/getsentry/sentry-javascript
