### ISSUE TITLE
CSRF Verification Failed

### ISSUE THREAD

**Issue by kmanika** [getsentry/self-hosted#1988]
### Self-Hosted Version

22.11.0

### CPU Architecture

NA

### Docker Version

NA

### Docker Compose Version

NA

### Steps to Reproduce

I've configured the sentry-relay (22.11.0) in EKS cluster
After login into the Sentry getting error like "Unable to fetch all project stats"
Project events not capturing getting 403 error in pod logs (CSRF Verification Failed)
 
<img width="484" alt="Screenshot 2023-02-27 at 8 08 05 PM" src="https://user-images.githubusercontent.com/61220490/221592972-c5bfa1a8-f468-49ae-bfbb-c67a9260b798.png">

I've commented the below block in sentry.conf.py
# if env('SENTRY_USE_SSL', False):
    #     SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    #     SESSION_COOKIE_SECURE = True
    #     CSRF_COOKIE_SECURE = True
    #     SOCIAL_AUTH_REDIRECT_IS_HTTPS = True

And nginx.conf is below :

server {
    listen   80;

    root /usr/share/nginx/html;
    index index.html;
    server_tokens on;

    location /api/store/ {
        proxy_pass      http://relay
    }
    
    location ~ ^/api/[1-9]\d*/ {
        proxy_pass      http://relay
	}
    
    location / {
        proxy_pass      http://sentry.
        proxy_pass_header      X-CSRF-TOKEN;
        proxy_set_header Host $http_host;
	}
}

### Expected Result

In Sentry should show all events

### Actual Result

\n        </a>\n      \n    </div>\n    <div class="box-content with-padding">\n      \n    <section class="body">\n        <div class="page-header">\n            <h2>CSRF Verification Failed</h2>\n        </div>\n\n        <p>A required security token was not found or was invalid.</p>\n\n        <p>If you\'re continually seeing this issue, try the following:</p>\n\n        <ol>\n          <li>Clear cookies (at least for Sentry\'s domain).</li>\n          <li>Reload the page you\'re trying to submit (don\'t re-submit data).</li>\n          <li>Re-enter the information, and submit the form again.</li>\n        </ol>\n\n        \n          <p>You are seeing this message because Sentry requires a \'Referer\n           header\' to be sent by your Web browser, but none was sent. This header is\n           required for security reasons, to ensure that your browser is not being\n           hijacked by third parties.</p>\n\n          <p>If you have configured your browser to disable \'Referer\' headers, please\n           re-enable them, at least for this site, or for HTTPS connections, or for\n           \'same-origin\' requests.</p>\n        \n\n        <p>Read more about <a href="http://en.wikipedia.org/wiki/Cross-site_request_forgery">CSRF on Wikipedia</a>.</p>\n    </section>\n\n    </div>\n  </div>\n</section>\n\n      </div>\n    </div>\n  </div>\n  \n\n  \n  \n  <script>document.addEventListener(\'DOMContentLoaded\', function() {\n      const el = document.querySelector(\'#sign-out\');\n      if (el) {\n        el.addEventListener(\'click\', function() {\n          document.modalLogoutForm.submit();\n        });\n      }\n    });</script>\n\n</body>\n</html>\n')

**Comment by hubertdeng123** [comment]
Is this a clean install? This looks to be the base setup

**Comment by kmanika** [comment]
I've upgraded it from 22.1.o to 22.11.0 and have used the old DB only

**Comment by hubertdeng123** [comment]
Gotcha, do you have any specific relay logs that may be helpful? You mentioned using an EKS cluster setup, so I'm assuming that you're not using our docker compose setup so there might be a lot of parts in your environment I'm not aware of
