### ISSUE TITLE
Issues still exist after executing sentry cleanup.

### ISSUE THREAD

**Issue by acrazing** [getsentry/self-hosted#1992]
### Self-Hosted Version

 23.3.0.dev0 7daa270

### CPU Architecture

x86_64

### Docker Version

19.03.13-ce

### Docker Compose Version

1.29.2

### Steps to Reproduce

1. Execute the following commands:

    ```bash
    docker exec -it sentry-self-hosted_sentry-cleanup_1 bash
    gosu sentry sentry cleanup --days 60
    ```

2. Open the `Discovery`. Issues from 60 days ago still exist: 
![image](https://user-images.githubusercontent.com/10029810/221813162-8f736c4f-7e9b-410a-ab8a-107f75bb3b1c.png)

### Expected Result

Only issues less than 60 days old.

### Actual Result

Issues from 60 days ago still exist.

**Comment by hubertdeng123** [comment]
I believe the graph there is from our `nodestore_node` table but I'm not quite sure. Could you try the steps outlined here for postgres?
https://develop.sentry.dev/self-hosted/troubleshooting/
