### ISSUE TITLE
Add Crons

### ISSUE THREAD

**Issue by hubertdeng123** [getsentry/self-hosted#1993]
### Problem Statement

Sentry has a Cron Monitoring feature in beta. We'd like to make this available to everyone. 

### Solution Brainstorm

Once Crons goes to GA, we'll make Crons generally available for self-hosted

See Replays in #1990 for a template.

**Comment by hubertdeng123** [comment]
For now, users can enable it by editing their `sentry.conf.py` file. In `SENTRY_FEATURES`, add the `"organizations:monitors"` flag. This will look something like this:

```
SENTRY_FEATURES.update(
    {
        feature: True
        for feature in (
            "organizations:discover",
            ...
            "organizations:monitors",
        )
    }
)
```

**Comment by chadwhitacre** [comment]
@hubertdeng123 Can you post this back in that slack thread wherever it was if you haven't?

**Comment by hubertdeng123** [comment]
already posted there 😃

**Comment by viktor2097** [comment]
> For now, users can enable it by editing their `sentry.conf.py` file. In `SENTRY_FEATURES`, add the `"organizations:monitors"` flag. This will look something like this:
> 
> ```
> SENTRY_FEATURES.update(
>     {
>         feature: True
>         for feature in (
>             "organizations:discover",
>             ...
>             "organizations:monitors",
>         )
>     }
> )
> ```

Do we have an equivalent to turn on the new profiling feature?

**Comment by chadwhitacre** [comment]
> Do we have an equivalent to turn on the new profiling feature?

If so let's post it on https://github.com/getsentry/self-hosted/issues/1838.

**Comment by aldy505** [comment]
> Do we have an equivalent to turn on the new profiling feature?

@viktor2097 Not yet. At least from my understanding, profiling feature requires [additional backend](https://github.com/getsentry/vroom) to be added to the docker compose file and set the profiling backend address on the `sentry` container. Right now, the `vroom` is not published on the Docker Hub yet, so we're all waiting on that.

**Comment by aldy505** [comment]
@hubertdeng123 any idea when this will be on GA?

**Comment by aldy505** [comment]
For those brave souls who wants to activate Cron feature:

On `sentry/sentry.conf.py`:
```python
# Add this line
SENTRY_FEATURES["organizations:monitors"] = True
```

On `docker-compose.yml`: (yes you have to deal with changing this everytime you upgrade Sentry)
```yaml
services:
  # Add new container for Cron
  ingest-monitors:
    <<: *sentry_defaults
    command: run consumer --no-strict-offset-reset ingest-monitors --consumer-group ingest-monitors
```

It's safer if you do `./install.sh` all over again, but I think a simple `docker compose up -d` will work.

**Comment by hubertdeng123** [comment]
Thanks for the guide here!

**Comment by kohenkatz** [comment]
I enabled this around 6 weeks ago, and since then kafka has been consuming much more system resources than it used to - enough to sometimes make the whole server (6 vCPU, 16GB RAM) stop responding. I think I'm going to have to turn it off again.

**Comment by hubertdeng123** [comment]
With the Crons GA, we should enable this for all self-hosted users.
