### ISSUE TITLE
Error in install/ensure-relay-credentials.sh:29.

### ISSUE THREAD

**Issue by rainbowMehBerdaya** [getsentry/self-hosted#2001]
### Self-Hosted Version

Get from github (Latest master)

### CPU Architecture

aarch64

### Docker Version

23.0.1

### Docker Compose Version

2.16.0

### Steps to Reproduce

sudo ./install.sh

### Expected Result

Install success

### Actual Result

exec /bin/bash: exec format error
Error in install/ensure-relay-credentials.sh:29.
'$creds generate --stdout > "$RELAY_CREDENTIALS_JSON".tmp' exited with status 1
-> ./install.sh:main:26
--> install/ensure-relay-credentials.sh:source:29

**Comment by rainbowMehBerdaya** [comment]
Is this error due to arm64 issue?

**Comment by hubertdeng123** [comment]
Yes it is, seems to be a duplicate of [this](https://github.com/getsentry/self-hosted/issues/1585)?

**Comment by rainbowMehBerdaya** [comment]
I think this error ['exec /bin/bash: exec format error'] seems to be arm64 issue
but I cant find error about the install/ensure-relay-credentials
so Im wondering is thin another issue or just arm64 issue

**Comment by Karsei** [comment]
When qemu is installed, some of the above errors are resolved and progressed. However, it took an unusually long time, and later when running with the `docker compose up -d` command, the `web` container ended up with an uwsgi error, such as https://github.com/getsentry/self-hosted/issues/1785.

I checked this on the oracle cloud A1.Flex arm64 instance, and I think we need to wait a little longer.
