### ISSUE TITLE
Problem with CSFR

### ISSUE THREAD

**Issue by asapbg** [getsentry/self-hosted#2013]
### Self-Hosted Version

23.02

### CPU Architecture

x86_64

### Docker Version

n/a

### Docker Compose Version

n/a

### Steps to Reproduce

Follow the step from this tutorial:

https://www.linkedin.com/pulse/sentry-self-hosted-installation-ubuntu-2004-lts-nginx-mahendra-rathod/

I have configured url prefix correctly, I tried with and without Nginx. WIth and without SSL. 

The only "wrong" thing  I do is to try to install it without docker.

Installation works, but one single page(and maybe whole /api/ not sure) gives CSRF error.

I even see the projects listed, but then they disappear from the page and are replaces with "OOPS something went worng".

Any idea how to make it work ? I really would love to skip Docker if possible...

### Expected Result

Have working sentry

### Actual Result

Page: 

Settings -> Projects (/settings/sentry/projects/) gives

Oops! Something went wrong

In the log file we have:

Mar  4 05:42:58 sentryv3 /supervisord: sentry-web 05:42:58 [ERROR] root: CSRF failure for staff or superuser
Mar  4 05:42:59 sentryv3 /supervisord: sentry-web 05:42:59 [WARNING] django.security.csrf: Forbidden (CSRF cookie not set.): /api/1/store/ (status_code=403 request=<WSGIRequest: POST '/api/1/store/'>)
Mar  4 05:42:59 sentryv3 /supervisord: sentry-web 05:42:59 [INFO] sentry.access.api: api.access (method='POST' view='django.views.generic.base.RedirectView' response=403 user_id='None' is_app='None' token_type='None' is_frontend_request='False' organization_id='None' auth_id='None' path='/api/1/store/' caller_ip='10.17.10.85' user_agent='sentry.python/1.14.0' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.0785207748413086 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
Mar  4 05:42:59 sentryv3 /supervisord: sentry-web 127.0.0.1 - - [04/Mar/2023:05:42:58 +0000] "POST /api/1/store/ HTTP/1.0" 403 6578 "-" "sentry.python/1.14.0"
Mar  4 05:42:59 sentryv3 /supervisord: sentry-web 05:42:59 [ERROR] sentry_sdk.errors: Unexpected status code: 403

**Comment by hubertdeng123** [comment]
Interesting, have you made sure to clear cookies each time in between switching out configurations? There's a lot of moving parts in your environment that I'm not familiar with especially since we don't officially support sentry self-hosted without docker

**Comment by asapbg** [comment]
Hi,

I cleared cookies a few times. It works much better without docker - much less CPU,Disk and RAM.
I tried all possible browsers.

You can easily reproduce it on your machine.
If we work it out I can write nice on howto make work without docker in exchange :-)

**Comment by hubertdeng123** [comment]
I'm afraid you'll need to do the bulk of the debugging on your own. The `api/store` endpoint is how event payloads are sent to Sentry. Perhaps checking your relay service might yield more answers?

**Comment by asapbg** [comment]
I did not install relay as it is missing from the tutorial. Tried myself, manage to compile ir, but was misisng sample config file.

Can you please give me a sample config file for relay ? I will modify it and hopefully it will work. :-)

**Comment by hubertdeng123** [comment]
Would this be helpful for you?
https://docs.sentry.io/product/relay/options/

**Comment by asapbg** [comment]
Hi,

I read it at the time, but could not figure how to make working sample file....

**Comment by hubertdeng123** [comment]
There's also a sample relay config in the self-hosted repo, is that not working?
```
relay:
  upstream: "http://web:9000/"
  host: 0.0.0.0
  port: 3000
logging:
  level: WARN
processing:
  enabled: true
  kafka_config:
    - {name: "bootstrap.servers", value: "kafka:9092"}
    - {name: "message.max.bytes", value: 50000000} # 50MB
  redis: redis://redis:6379
  geoip_path: "/geoip/GeoLite2-City.mmdb"

```
