### ISSUE TITLE
Bitbucket integration (the add-on server could not be reached)

### ISSUE THREAD

**Issue by jssoriao** [getsentry/self-hosted#2014]
### Self-Hosted Version

23.2.0

### CPU Architecture

x86_64

### Docker Version

23.0.1

### Docker Compose Version

2.16.0

### Steps to Reproduce

We use EC2 in private subnet and an AWS ALB in front that terminates SSL. We also have a NAT Gateway which allows the EC2 instance to communicate to the internet (outbound)
1. Download self-hosted sentry.
2. Modify `system.url-prefix` to custom domain (https://subdomain.domain.com)
3. Install the self-hosted sentry
4. Open the webapp in the browser and do some setups like orgs, projects, etc.
5. Go to Integrations > Bitbucket > Add Installation

<img width="981" alt="Screenshot 2023-03-05 at 6 11 05 PM" src="https://user-images.githubusercontent.com/26679479/222955761-8f6a6dd9-fd0b-4692-a186-bc34b3911a15.png">

### Expected Result

I can connect to our Bitbucket Workspace successfully

### Actual Result

<img width="722" alt="Screenshot 2023-03-05 at 6 01 46 PM" src="https://user-images.githubusercontent.com/26679479/222955770-b84869de-ce04-408c-8056-3782fb3f7beb.png">

**Comment by jssoriao** [comment]
I have enabled development mode for bitbucket, and when I attempt to `Install app from URL`, I encounter that error again when I use our sentry on-prem domain. But for sentry.io, it is successful.

<img width="923" alt="Screenshot 2023-03-05 at 10 21 25 PM" src="https://user-images.githubusercontent.com/26679479/222966265-6b6cebb0-ea20-4665-883d-75bfe1b6c247.png">

<img width="923" alt="Screenshot 2023-03-05 at 10 23 25 PM" src="https://user-images.githubusercontent.com/26679479/222966340-cb075caa-c035-4e35-af2f-7c3bc83ccf54.png">

**Comment by hubertdeng123** [comment]
Can you check your network logs when trying to hit the on-prem domain? I'm wondering if there are network rules that might be causing this
