### ISSUE TITLE
Request for cookie information

### ISSUE THREAD

**Issue by ichniowski** [getsentry/self-hosted#2017]
### Problem Statement

I apologize that this is a feature request but I couldn't find a suitable type to raise a general question. 
I'm attempting to solve a "Missing Secure Flag From SSL" vulnerability on my self-hosted sentry instance, and would like to understand more about what cookies sentry's web interface uses.

I have added a "add_header Set-Cookie "Path=/; HttpOnly; Secure";" flag to my nginx.conf, but two of the cookies do not seem to respond to it. Their names are "sentrysid" and "sc". Is there any information about these cookies or how to resolve this issue? 

sentry version: 21.3.0
docker version: 20.10.5
docker-compose version: 1.28.6
arch: x86_64

**Comment by hubertdeng123** [comment]
Are you using a reverse SSL proxy? You will need to enable a few flags in `sentry.conf.py`

```
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SOCIAL_AUTH_REDIRECT_IS_HTTPS = True
```

**Comment by ichniowski** [comment]
> Are you using a reverse SSL proxy? You will need to enable a few flags in `sentry.conf.py`
> 
> ```
> SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
> SESSION_COOKIE_SECURE = True
> CSRF_COOKIE_SECURE = True
> SOCIAL_AUTH_REDIRECT_IS_HTTPS = True
> ```

Yes, we're using a reverse SSL proxy. I'll give this a shot. Does this require anything more than a restart afterwards? (I don't need to do a rebuild, right?)

**Comment by ichniowski** [comment]
my mistake, didn't mean to close. new at this

**Comment by ichniowski** [comment]
This worked, thank you very much!
