### ISSUE TITLE
I try to use external postgres db, but it can not create table automatically. 

### ISSUE THREAD

**Issue by tanoya** [getsentry/self-hosted#2018]
### Self-Hosted Version

23.1.1

### CPU Architecture

x86_64

### Docker Version

20.10.23

### Docker Compose Version

2.16.0

### Steps to Reproduce

modify the /sentry/sentry.conf.py about postgres to our external postgres link.
such like 
DATABASES = {
    "default": {
        "ENGINE": "sentry.db.postgres",
        "NAME": "postgres",
        "USER": "postgres",
        "PASSWORD":"",
       "HOST": "127.0.0.1",
        "PORT": "5432",
    }
}

### Expected Result

after excute command `docker compose up -d`,   It can running sentry container that use our external postgres db and create table automatically. 

### Actual Result

 SQL: SELECT "sentry_option"."id", "sentry_option"."key", "sentry_option"."value", "sentry_option"."last_updated" FROM "sentry_option" WHERE "sentry_option"."last_updated" >= %s
sentry-worker-1                               |
sentry-worker-1                               | The above exception was the direct cause of the following exception:
sentry-worker-1                               |
sentry-worker-1                               | Traceback (most recent call last):
sentry-worker-1                               |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task
sentry-worker-1                               |     R = retval = fun(*args, **kwargs)
sentry-worker-1                               |   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 207, in _inner
sentry-worker-1                               |     reraise(*exc_info)
sentry-worker-1                               |   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 60, in reraise
sentry-worker-1                               |     raise value
sentry-worker-1                               |   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 202, in _inner
sentry-worker-1                               |     return f(*args, **kwargs)
sentry-worker-1                               |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__
sentry-worker-1                               |     return self.run(*args, **kwargs)
sentry-worker-1                               |   File "/usr/local/lib/python3.8/site-packages/sentry/tasks/base.py", line 64, in _wrapped
sentry-worker-1                               |     result = func(*args, **kwargs)
sentry-worker-1                               |   File "/usr/local/lib/python3.8/site-packages/sentry/tasks/options.py", line 26, in sync_options
sentry-worker-1                               |     for option in Option.objects.filter(last_updated__gte=cutoff_dt).iterator():
sentry-worker-1                               |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 341, in _iterator
sentry-worker-1                               |     yield from self._iterable_class(self, chunked_fetch=use_chunked_fetch, chunk_size=chunk_size)
sentry-worker-1                               |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 55, in __iter__
sentry-worker-1                               |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
sentry-worker-1                               |   File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql
sentry-worker-1                               |     cursor.execute(sql, params)
sentry-worker-1                               |   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/django/__init__.py", line 577, in execute
sentry-worker-1                               |     return real_execute(self, sql, params)
sentry-worker-1                               |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
sentry-worker-1                               |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
sentry-worker-1                               |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
sentry-worker-1                               |     return executor(sql, params, many, context)
sentry-worker-1                               |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
sentry-worker-1                               |     return self.cursor.execute(sql, params)
sentry-worker-1                               |   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
sentry-worker-1                               |     raise dj_exc_value.with_traceback(traceback) from exc_value
sentry-worker-1                               |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
sentry-worker-1                               |     return self.cursor.execute(sql, params)
sentry-worker-1                               |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 77, in inner
sentry-worker-1                               |     raise_the_exception(self.db, e)
sentry-worker-1                               |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 75, in inner
sentry-worker-1                               |     return func(self, *args, **kwargs)
sentry-worker-1                               |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 18, in inner
sentry-worker-1                               |     return func(self, *args, **kwargs)
sentry-worker-1                               |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
sentry-worker-1                               |     raise exc_info[0](msg).with_traceback(exc_info[2])
sentry-worker-1                               |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
sentry-worker-1                               |     return func(self, sql, *args, **kwargs)
sentry-worker-1                               |   File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py", line 86, in execute
sentry-worker-1                               |     return self.cursor.execute(sql, clean_bad_params(params))
sentry-worker-1                               | django.db.utils.ProgrammingError: UndefinedTable('relation "sentry_option" does not exist\nLINE 1: ...ion"."value", "sentry_option"."last_updated" FROM "sentry_op...\n                                                             ^\n')
sentry-worker-1                               | SQL: SELECT "sentry_option"."id", "sentry_option"."key", "sentry_option"."value", "sentry_option"."last_updated" FROM "sentry_option" WHERE "sentry_option"."last_updated" >= %s
sentry-worker-1                               | 09:59:47 [ERROR] celery.app.trace: Task sentry.tasks.options.sync_options[95838546-3c71-4d36-9eb6-a898e4a34fac] raised unexpected: ProgrammingError('UndefinedTable(\'relation "sentry_option" does not exist\\nLINE 1: ...ion"."value", "sentry_option"."last_updated" FROM "sentry_op...\\n                                                             ^\\n\')\nSQL: SELECT "sentry_option"."id", "sentry_option"."key", "sentry_option"."value", "sentry_option"."last_updated" FROM "sentry_option" WHERE "sentry_option"."last_updated" >= %s') (data={'hostname': '23f063b4def6', 'id': '95838546-3c71-4d36-9eb6-a898e4a34fac', 'name': 'sentry.tasks.options.sync_options', 'exc': 'ProgrammingError(\'UndefinedTable(\\\'relation "sentry_option" does not exist\\\\nLINE 1: ...ion"."value", "sentry_option"."last_updated" FROM "sentry_op...\\\\n                                                             ^\\\\n\\\')\\nSQL: SELECT "sentry_option"."id", "sentry_option"."key", "sentry_option"."value", "sentry_option"."last_updated" FROM "sentry_option" WHERE "sentry_option"."last_updated" >= %s\')', 'traceback': 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 91, in inner\n    return func(self, sql, *args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py", line 86, in execute\n    return self.cursor.execute(sql, clean_bad_params(params))\npsycopg2.errors.UndefinedTable: relation "sentry_option" does not exist\nLINE 1: ...ion"."value", "sentry_option"."last_updated" FROM "sentry_op...\n                                                             ^\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute\n    return self.cursor.execute(sql, params)\n  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 77, in inner\n    raise_the_exception(self.db, e)\n  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 75, in inner\n    return func(self, *args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 18, in inner\n    return func(self, *args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 95, in inner\n    raise exc_info[0](msg).with_traceback(exc_info[2])\n  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 91, in inner\n    return func(self, sql, *args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py", line 86, in execute\n    return self.cursor.execute(sql, clean_bad_params(params))\npsycopg2.errors.UndefinedTable: UndefinedTable(\'relation "sentry_option" does not exist\\nLINE 1: ...ion"."value", "sentry_option"."last_updated" FROM "sentry_op...\\n                                                             ^\\n\')\nSQL: SELECT "sentry_option"."id", "sentry_option"."key", "sentry_option"."value", "sentry_option"."last_updated" FROM "sentry_option" WHERE "sentry_option"."last_updated" >= %s\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task\n    R = retval = fun(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 207, in _inner\n    reraise(*exc_info)\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 60, in reraise\n    raise value\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 202, in _inner\n    return f(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__\n    return self.run(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/base.py", line 64, in _wrapped\n    result = func(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/options.py", line 26, in sync_options\n    for option in Option.objects.filter(last_updated__gte=cutoff_dt).iterator():\n  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 341, in _iterator\n    yield from self._iterable_class(self, chunked_fetch=use_chunked_fetch, chunk_size=chunk_size)\n  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 55, in __iter__\n    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)\n  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql\n    cursor.execute(sql, params)\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/django/__init__.py", line 577, in execute\n    return real_execute(self, sql, params)\n  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute\n    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)\n  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers\n    return executor(sql, params, many, context)\n  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute\n    return self.cursor.execute(sql, params)\n  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__\n    raise dj_exc_value.with_traceback(traceback) from exc_value\n  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute\n    return self.cursor.execute(sql, params)\n  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 77, in inner\n    raise_the_exception(self.db, e)\n  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 75, in inner\n    return func(self, *args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 18, in inner\n    return func(self, *args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 95, in inner\n    raise exc_info[0](msg).with_traceback(exc_info[2])\n  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/decorators.py", line 91, in inner\n    return func(self, sql, *args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/db/postgres/base.py", line 86, in execute\n    return self.cursor.execute(sql, clean_bad_params(params))\ndjango.db.utils.ProgrammingError: UndefinedTable(\'relation "sentry_option" does not exist\\nLINE 1: ...ion"."value", "sentry_option"."last_updated" FROM "sentry_op...\\n                                                             ^\\n\')\nSQL: SELECT "sentry_option"."id", "sentry_option"."key", "sentry_option"."value", "sentry_option"."last_updated" FROM "sentry_option" WHERE "sentry_option"."last_updated" >= %s\n', 'args': '()', 'kwargs': '{}', 'description': 'raised unexpected', 'internal': False})

**Comment by hubertdeng123** [comment]
If you're using an external postgres db, you will need to perform the db migrations yourself. These migrations are performed automatically in our install script. You can find the migrations here:
https://github.com/getsentry/sentry/tree/master/src/sentry/migrations

**Comment by tanoya** [comment]
thanks a lot. It seems like I created a test table in the database witch my sentry link. After I delete the test table. it goes well.

**Comment by hubertdeng123** [comment]
awesome, closing this issue then
