### ISSUE TITLE
When the amount of issues exceeds a certain value, the service won't work。

### ISSUE THREAD

**Issue by jaluik** [getsentry/self-hosted#2023]
### Problem Statement

In my case，when the amount of issues exceeds  17k, the self-hosted sentry server responds slowly, sometimes it even won't work.

I notice an intro in the [homepage](https://develop.sentry.dev/self-hosted/):

> In addition to making its source code available publicly, Sentry offers and maintains a minimal setup that works out-of-the-box for simple use cases. 

I want to known what the  **simple use cases** refer to. For exaple, how much data can be supported by self-hosted sentry.

ps： I use `22.7.0` version of self-hosted sentry.

**Comment by hubertdeng123** [comment]
There's not a clear amount of data that can be supported by self-hosted Sentry, but it is not built for scale. For large amount of issues, latency is unfortunately expected. Simple use cases refer to the basic integrations and services that Sentry provides (Error Monitoring, Performance Monitoring, Replays) in a relatively lower scale.

**Comment by jaluik** [comment]
thanks
