### ISSUE TITLE
External kafka, zookeeper and clickhouse

### ISSUE THREAD

**Issue by xRTRx** [getsentry/self-hosted#2024]
### Problem Statement

Is it possible to use external kafka, zookeeper and clickhouse without default parameters?
I tried to use external postgres and it has parameters like NAME, USER, PASSWORD, HOST in sentry.conf.py file.
And it works. 
Kafka, Zookeper and Clickhouse has no such parameters, but works with default ones.
Now I want to use external kafka, zookeeper and clickhouse with custom parameters.

**Comment by dereckson** [comment]
_Solution brainstorm_

For snuba containers: some variables are extracted from the environment according https://github.com/getsentry/snuba/blob/master/snuba/settings files

For example:
  * Kafka and ClickHouse can be configured through environment too according snuba/settings/__init__.py
  * Redis is also defined in in https://github.com/getsentry/snuba/blob/master/snuba/settings/settings_docker.py
