### ISSUE TITLE
23.2.0 new install: dependency failed to start: container sentry-self-hosted-clickhouse-1 is unhealthy

### ISSUE THREAD

**Issue by francisATgwn** [getsentry/self-hosted#2027]
### Self-Hosted Version

23.2.0

### CPU Architecture

x86_64

### Docker Version

Docker version 23.0.1, build a5ee5b1

### Docker Compose Version

Docker Compose version v2.16.0

### Steps to Reproduce

1. Create new AWS EC2 running Ubuntu 22.04.2 jammy.
2. clone this repo
3. `git checkout 23.2.0`
4. ./install.sh

### Expected Result

sentry installs and runs

### Actual Result

In the first run through the installer, it fails on credentials.json same as #1532. However, subsequent runs of the installer don't suffer this issue so I guess it self corrects.

In every subsequent run it fails with this error:

```
dependency failed to start: container sentry-self-hosted-clickhouse-1 is unhealthy
```

**Comment by francisATgwn** [comment]
Initial failure a la #1532: https://gist.github.com/francisATgwn/7e2f2484e8de11124b916b3c4bcd1c14

Subsequent failures that this issue is about: https://gist.github.com/francisATgwn/7e4712698579add0cf54cdf2029b3a75

**Comment by hubertdeng123** [comment]
Could you look at clickhouse logs? Sometimes that is a flaky error that happens when installing but I'm guessing it's happening for you quite often

**Comment by francisATgwn** [comment]
I'll see if I can dig those up somehow. After the failure, `docker ps` shows nothing is running.

It is unavoidable. I mean, I give up after 3 reruns of install.sh, so maybe it'll flake in and out if I keep going, but 3 in a row is what I'm looking at right now. I've destroyed and recreated the EC2 instance and the new one does exactly the same thing: 1 occurence of #1532 and then 3 occurrences of this issue.

**Comment by francisATgwn** [comment]
@hubertdeng123 https://gist.github.com/francisATgwn/5a2a0a297c46c166de1e5c3b9c7ec0d1

**Comment by hubertdeng123** [comment]
seeing `Access to file denied: /etc/clickhouse-server/config.d/sentry.xml`, perhaps this is a permissioning issue?

**Comment by francisATgwn** [comment]
Indeed. I'm not taking any action to mount that directory/file into the container on my end. I have to assume it's the config file that ships inside that clickhouse docker image, or it's a config file your docker compose is mounting.

If it's the latter, where can I check on the host side to verify permissions? If you know, what user within the clickhouse container needs access and is it read/write?

**Comment by francisATgwn** [comment]
The issue was resolved by setting `umask` to something more permissive (002) prior to cloning the repo. I'm not happy with this solution as I look at a world readable credentials.json file that the install script generated, which is the exact reason we set a less permissive umask (027). But the application does successfully start up now.

**Comment by hubertdeng123** [comment]
Glad you were able to figure this out, although not the ideal solution for you. Closing this issue
