### ISSUE TITLE
use external clickhouse, can not create event

### ISSUE THREAD

**Issue by tanoya** [getsentry/self-hosted#2028]
### Self-Hosted Version

23.1.1

### CPU Architecture

x86_64

### Docker Version

20.10.23

### Docker Compose Version

2.16.0

### Steps to Reproduce

1. Install clickhouse on a machine.
2.  change docker-compose.yaml file. the clickhouse part of the config file. like this:
3. 
![image](https://user-images.githubusercontent.com/11534005/224998008-fb604c3f-c0f7-4c3b-b600-15e1680f4886.png)

4. docker compose up -d all the service.
5. click the web site 'Create a sample event' button.
![image](https://user-images.githubusercontent.com/11534005/224996235-db625a73-dde2-4a29-9aba-08b0d012aea3.png)
6. we can see that clickhouse and postgres can create table and accept data from web site of the test page.

### Expected Result

after we create a test event. the website can see the event on the web page.

### Actual Result

we can only see the error in the chrome cosole like this:
![image](https://user-images.githubusercontent.com/11534005/224997436-3dee27a6-2b10-40a3-b27c-47e1230d06bc.png)

and we can see this error in the docker log file like this:
![image](https://user-images.githubusercontent.com/11534005/224998452-a8fbcfc8-9ec3-4cb9-b11f-b747ac53bb59.png)

**Comment by hubertdeng123** [comment]
I believe you'll have to run clickhouse migrations yourself. Have you done that?

**Comment by hubertdeng123** [comment]
Here's a link that might help if you haven't run those:
https://github.com/getsentry/snuba/blob/master/MIGRATIONS.md#running-migrations

**Comment by tanoya** [comment]
sorry to response late, But still have not figure it out. becase i am trying do something else. If I have any progress, I will comment it.
