### ISSUE TITLE
Self-hosted e2e tests not working for forks in relay

### ISSUE THREAD

**Issue by hubertdeng123** [getsentry/self-hosted#2032]
Self-hosted e2e tests in the relay repo are failing for contributor forks due to the lack of credentials when uploading the image to gchr.

**Comment by mattgauntseo-sentry** [comment]
Change to the PR is here: https://github.com/getsentry/relay/pull/1918

I managed to get around this for some tests by using the local docker image (which can be exported / imported with docker), but the e2e tests (and the accompanying action) use `docker pull` and I'm not sure how best to handle that in the test.sh case (i.e. I imagine `docker pull` would be needed to update tagged images i.e. `:nightly`).

Action change that fixes the action for this was here: https://github.com/getsentry/action-self-hosted-e2e-tests/pull/9
