### ISSUE TITLE
Bump default clickhouse version

### ISSUE THREAD

**Issue by hubertdeng123** [getsentry/self-hosted#2036]
It seems that Replays are breaking because SaaS is running Clickhouse 21 and Sentry devs are running Clickhouse 21 as well on M1 macs. For other configurations, self-hosted sentry is running Clickhouse 20 which broke replays for many people.

https://github.com/getsentry/self-hosted/issues/2002

**Comment by JoshFerge** [comment]
will note that snuba / sentry CI runs on clickhouse 20, and we just simply did not have adequate test coverage for replays that looked at clickhouse insertion. however, for many reasons it is a good idea to get to clickhouse 21.

**Comment by hubertdeng123** [comment]
ah yes it is, closing in favor of that then
