### ISSUE TITLE
Issues -> All Events Does Not Work With 50+ Events

### ISSUE THREAD

**Issue by mencarellic** [getsentry/self-hosted#2041]
### Self-Hosted Version

23.3.1

### CPU Architecture

x86_64

### Docker Version

23.0.1

### Docker Compose Version

1.29.2

### Steps to Reproduce

This is a follow-up of: https://github.com/getsentry/self-hosted/issues/1927

We have upgraded our self-hosted Sentry stack to 23.3.1 and still see the same behavior. We have some issues with 100k events in them for reference of scale.

1. Have an issue with more than ~50 individual events
2. Open the "All events" tab

### Expected Result

The all events page shows the list of all events paginated

### Actual Result

I'm unable to find the very same logs as the original issue, nor can I find the 502 returned in the logs.

**Comment by hubertdeng123** [comment]
Hi there! Are there any logs that are useful for nginx? It's hard to debug this without additional information

**Comment by stefangr** [comment]
Is there perhaps another nginx (or http proxy) before the nginx that is part of the self-hosted sentry?

Because in my situation there was and I had to change the buffer configuration in both nginx instances.

**Comment by mencarellic** [comment]
> Is there perhaps another nginx (or http proxy) before the nginx that is part of the self-hosted sentry?
> 
> Because in my situation there was and I had to change the buffer configuration in both nginx instances.

There was a hidden nginx for me as well. Thanks for the nudge @stefangr.
