### ISSUE TITLE
The subcommand 'send-envelope' wasn't recognized 	Did you mean 'send-event'?

### ISSUE THREAD

**Issue by qingfengmy** [getsentry/self-hosted#2046]
### Self-Hosted Version

23.3.1

### CPU Architecture

x64arm

### Docker Version

20.10.23

### Docker Compose Version

2.15.1

### Steps to Reproduce

./install.sh

### Expected Result

successed

### Actual Result

#8 [4/5] RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
#8 0.973 Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
#8 31.25 Err:1 http://deb.debian.org/debian bullseye InRelease
#8 31.25   Connection timed out [IP: 151.101.78.132 80]
#8 32.89 Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
#8 33.11 Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
#8 34.28 Get:4 http://deb.debian.org/debian-security bullseye-security/main amd64 Packages [236 kB]
#8 41.38 Get:5 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [14.6 kB]
#8 42.07 Fetched 343 kB in 42s (8244 B/s)
#8 42.07 Reading package lists...
#8 42.22 W: Failed to fetch http://deb.debian.org/debian/dists/bullseye/InRelease  Connection timed out [IP: 151.101.78.132 80]
#8 42.22 W: Some index files failed to download. They have been ignored, or old ones used instead.
#8 42.32 Reading package lists...
#8 42.48 Building dependency tree...
#8 42.50 Reading state information...
#8 42.51 Package cron is not available, but is referred to by another package.
#8 42.51 This may mean that the package is missing, has been obsoleted, or
#8 42.51 is only available from another source
#8 42.51
#8 42.52 E: Package 'cron' has no installation candidate
#8 ERROR: executor failed running [/bin/sh -c apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*]: exit code: 100
------
 > [4/5] RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*:
#8 41.38 Get:5 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [14.6 kB]

#8 42.48 Building dependency tree...
#8 42.50 Reading state information...
#8 42.51 Package cron is not available, but is referred to by another package.
#8 42.51 This may mean that the package is missing, has been obsoleted, or
#8 42.51 is only available from another source
#8 42.51
#8 42.52 E: Package 'cron' has no installation candidate
------
failed to solve: executor failed running [/bin/sh -c apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*]: exit code: 100
Error in install/build-docker-images.sh:8.
'$dcb --force-rm "$service"' exited with status 17
-> ./install.sh:main:29
--> install/build-docker-images.sh:source:8

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
error: The subcommand 'send-envelope' wasn't recognized
	Did you mean 'send-event'?

If you believe you received this message in error, try re-running with 'sentry-cli -- send-envelope'

USAGE:
    sentry-cli <SUBCOMMAND>

For more information try --help

**Comment by hubertdeng123** [comment]
This is super weird, and this is using the latest version of sentry-cli? `send-envelope` has been a part of the sentry-cli for some time now
