### ISSUE TITLE
Run apt-get install jq in Docker will cause network connection problems.

### ISSUE THREAD

**Issue by liukch** [getsentry/self-hosted#2049]
### Self-Hosted Version

23.3.1

### CPU Architecture

x86_64

### Docker Version

20.10.11

### Docker Compose Version

20.10.11

### Steps to Reproduce

1. Upgrade version 22.9.0 => 23.3.1
2. run install.sh

You can get Pull Request [here](https://github.com/getsentry/self-hosted/pull/1775)
The cmd jq was installed in Docker by `apt-get install`, it is not a good solution for all users.
Because not all regions network are unobstructed when using `apt-get`. If I run cmd in my own server, I can set mirrors rather than use default `deb.debian.org`, but run these cmd in  Docker, I will receive errors like `Connection timeout`

### Expected Result

Not network problems.

### Actual Result

I received errors like `Failed to fetch http://deb.debian.org/debian/pool/main/j/jq/libjq1_1.6-2.1_amd64.deb  Connection timed out`

This is all of my outputs in run `install.sh`:
```
▶ Parsing command line ...

▶ Detecting Docker platform
Detected Docker platform is linux/amd64

▶ Initializing Docker Compose ...

▶ Setting up error handling ...
Sending build context to Docker daemon  2.048kB
Step 1/4 : FROM debian:bullseye-slim
 ---> cec0d876642b
Step 2/4 : LABEL MAINTAINER="oss@sentry.io"
 ---> Using cache
 ---> 6ef3971efd5b
Step 3/4 : RUN set -x   && apt-get update   && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends jq   && apt-get clean   && rm -rf /var/lib/apt/lists/*
 ---> Running in eb1a1a695360
+ apt-get update
Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
Get:4 http://deb.debian.org/debian bullseye/main amd64 Packages [8183 kB]
Get:5 http://deb.debian.org/debian-security bullseye-security/main amd64 Packages [236 kB]
Get:6 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [14.6 kB]
Fetched 8642 kB in 11min 54s (12.1 kB/s)
Reading package lists...
+ DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends jq
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libjq1 libonig5
The following NEW packages will be installed:
  jq libjq1 libonig5
0 upgraded, 3 newly installed, 0 to remove and 1 not upgraded.
Need to get 384 kB of archives.
After this operation, 1148 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bullseye/main amd64 libonig5 amd64 6.9.6-1.1 [185 kB]
Get:2 http://deb.debian.org/debian bullseye/main amd64 libjq1 amd64 1.6-2.1 [135 kB]
Err:2 http://deb.debian.org/debian bullseye/main amd64 libjq1 amd64 1.6-2.1
  Connection timed out [IP: 151.101.110.132 80]
Get:3 http://deb.debian.org/debian bullseye/main amd64 jq amd64 1.6-2.1 [64.9 kB]
Fetched 249 kB in 1min 21s (3073 B/s)
E: Failed to fetch http://deb.debian.org/debian/pool/main/j/jq/libjq1_1.6-2.1_amd64.deb  Connection timed out [IP: 151.101.110.132 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command '/bin/sh -c set -x   && apt-get update   && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends jq   && apt-get clean   && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```

**Comment by hubertdeng123** [comment]
I wasn't aware of this, thanks for bringing this up. Can you try to paste this in the `DockerFile` and see if it works for you?
```
&& wget -O jq https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 \ 
&& chmod +x ./jq \
&& cp jq /usr/bin \
```
instead of 
```
&& apt-get update \
&& DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends jq \
&& apt-get clean \
```

**Comment by liukch** [comment]
@hubertdeng123 
Yes, my network connection is fine for accessing GitHub. However, I have been experiencing connection timeouts when attempting to access Dockerfiles containing ·apt-get· commands. 
As a solution, I suggest that these Dockerfiles should not be built on the server and instead should be pushed to Docker Hub. Then, when we use them, we can simply pull them from Docker Hub.

**Comment by liukch** [comment]
Could you help me solve this problem? 
Due to this issue, I am unable to upgrade my Sentry. If I attempt an upgrade, the Sentry service will stop. 
However, due to a network problem, the upgrade shell script will never succeed. I am uncertain whether I can revert to a previous version if the upgrade fails.

**Comment by liukch** [comment]
I have come up with an idea to help me solve this problem. 
I am using AWS cloud services and I plan to mount the EBS of the old server to a new EC2 instance. I will then complete the upgrade on the new EC2 instance by continuously retrying until it is successful. After that, I will move the service to the new EC2 instance and stop the old Sentry service. 
However, this approach may result in data loss during the upgrade process and is not the optimal solution.

**Comment by hubertdeng123** [comment]
If you truly don't want to encounter this issue with installing jq, you can just comment out all the `source install/error-handling.sh` in `./install.sh` script.

**Comment by hubertdeng123** [comment]
This isn't necessary for the install script to run, it is there to help send errors to our self-hosted Sentry instance so we can be on top of things

**Comment by liukch** [comment]
Anyone can help me solve this problem, thanks very much.

**Comment by neet11** [comment]
you can modify the /etc/docker/daemon.json file. Here are the steps:
1.Log in to the operating system as the root user
2.Open the /etc/docker/daemon.json file, and if the file does not exist, create it and open it
```bash
sudo nano /etc/docker/daemon.json
```
3.Add the following JSON configuration to the opened file, which sets the MTU value of the docker0 bridge to 1400:
```json
{
     "bip": "172.17.0.1/16",
     "mtu": 1400
 }
```
Here, bip specifies the IP address range of the docker0 bridge, and mtu specifies the MTU value of the docker0 bridge.
    1.Save and close the /etc/docker/daemon.json file.
    2.Restart the Docker service to apply the changes.
```bash
sudo systemctl restart docker
```

**Comment by liukch** [comment]
@neet11 
The issue is likely not caused by MTU. It is due to network problems in the region where my server is located. It is unable to access the apt repository address `deb.debian.org` smoothly, resulting in the inability to complete the Docker build process.

I believe it is incorrect to build the Docker image directly on the server in this case. Instead, it would be more appropriate to pre-upload the image to Docker Hub and then pull it directly from there.

**Comment by karatekaneen** [comment]
I ran into a similar issue where I got timeout when trying to install jq. The solution by @neet11 above fixed it for me.

This was my original error output provided to give better googlings:

```
sudo ./install.sh
▶ Parsing command line ...

▶ Detecting Docker platform
Detected Docker platform is linux/amd64

▶ Initializing Docker Compose ...

▶ Setting up error handling ...
Sending build context to Docker daemon  2.048kB
Step 1/4 : FROM debian:bullseye-slim
 ---> f8e203ddac5b
Step 2/4 : LABEL MAINTAINER="oss@sentry.io"
 ---> Using cache
 ---> 3139c94f8bde
Step 3/4 : RUN set -x   && apt-get update   && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends jq   && apt-get clean   && rm -rf /var/lib/apt/lists/*
 ---> Running in ecfddd27cc8b
+ apt-get update
Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
Err:1 http://deb.debian.org/debian bullseye InRelease
  Connection timed out [IP: 151.101.86.132 80]
Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
Err:2 http://deb.debian.org/debian-security bullseye-security InRelease
  Connection timed out [IP: 151.101.86.132 80]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
Err:3 http://deb.debian.org/debian bullseye-updates InRelease
```
