### ISSUE TITLE
Incompatible with Docker Compse 2.17.0 and up due to go-yaml/v3

### ISSUE THREAD

**Issue by sparknsh** [getsentry/self-hosted#2054]
### Self-Hosted Version

Any

### CPU Architecture

Any

### Docker Version

Any

### Docker Compose Version

2.17

### Steps to Reproduce

Run docker compose 

### Expected Result

Run as normal

### Actual Result

yaml: unmarshal errors:
  line 81: mapping key "<<" already defined at line 21

**Comment by hubertdeng123** [comment]
Thanks for bringing this up. I will look into this

**Comment by dlouzan** [comment]
Related upstream change and solutions: https://github.com/docker/compose/issues/10411

**Comment by bikingfreak** [comment]
I seem to have the same problem with version 2.17.3.
docker compose up -d
parsing /opt/docker-compose.yaml: yaml: unmarshal errors:
  line 16: mapping key "container_name" already defined at line 5
  line 17: mapping key "image" already defined at line 6
  line 21: mapping key "restart" already defined at line 7
  line 18: mapping key "volumes" already defined at line 12
root@mieow:/opt# vi docker-compose.yaml

**Comment by shadowlmd** [comment]
Looks like this is already fixed. I don't have any issues with Compose v2.18.1.
