### ISSUE TITLE
Events are not logging on self hosted sentry( 403 - csrf failed)

### ISSUE THREAD

**Issue by rahulsingh806080** [getsentry/self-hosted#2056]
### Problem Statement

Hi Team, 
@hubertdeng123 

When self hosted sentry is locally deployed , events are getting logged. 
But when i am deploying on any domain its throwing 403. Tried many solutions but with no success.

I have also replaced http with https and  localhost with domain in DSN key. Even after that also facing issues. 

**Request**

Request URL: https://dev-sentry.piramal.com/api/4/envelope/?sentry_key=271118557784468f57f682dc8e4881&sentry_version=7&sentry_client=sentry.javascript.nextjs%2F7.45.0
Request Method: POST
Status Code: 403 
Remote Address: 10.31.15.120:443
Referrer Policy: origin

**Response**

  <section class="body">
        <div class="page-header">
            <h2>CSRF Verification Failed</h2>
        </div>

        <p>A required security token was not found or was invalid.</p>

        <p>If you're continually seeing this issue, try the following:</p>

        <ol>
          <li>Clear cookies (at least for Sentry's domain).</li>
          <li>Reload the page you're trying to submit (don't re-submit data).</li>
          <li>Re-enter the information, and submit the form again.</li>
        </ol>

        

        <p>Read more about <a href="http://en.wikipedia.org/wiki/Cross-site_request_forgery">CSRF on Wikipedia</a>.</p>
    </section>

**Comment by hubertdeng123** [comment]
Are you using the default setup in self-hosted?

Which SDK and what version of the SDK are you using?

**Comment by rahulsingh806080** [comment]
Yes. Default setup in self hosted.(latest version)
Next js with latest version.
@hubertdeng123

**Comment by rahulsingh806080** [comment]
@hubertdeng123 Any update on this?

**Comment by rahulsingh806080** [comment]
@hubertdeng123  Do we need to setup any auth token for same.

**Comment by rowan-wang** [comment]
How was it solved? I had the same problem
