### ISSUE TITLE
Some transactions getting dropped

### ISSUE THREAD

**Issue by gaurijoshi9** [getsentry/self-hosted#2060]
### Self-Hosted Version

22.6.0

### CPU Architecture

x86_64

### Docker Version

20.10.21

### Docker Compose Version

2.12.2

### Steps to Reproduce

Code for sentry init:
```
  Sentry.init({
    Vue,
    dsn: config?.server?.sentryDsn,
    environment: process.env.VS_ENV,
    integrations: [
      new BrowserTracing({
        routingInstrumentation: Sentry.vueRouterInstrumentation(router),
        tracingOrigins: ['*']
      })
    ],
    maxValueLength: 5000,
    tracesSampleRate: process.env.NODE_CONFIG_ENV === 'production' ? 1.0 : 0.2
  });
  Sentry.configureScope(scope => {
    let transaction_id = uuidv4()
    scope.setTag('store', 'us');
    scope.setTag('transaction_id', transaction_id);
    scope.setUser({
      'transaction_id': transaction_id
    })
  });
}
```

### Expected Result

We do not want to drop any transactions on prod environment

### Actual Result

Some transactions of a vuejs project are getting dropped
![dropped_transactions](https://user-images.githubusercontent.com/35684163/229036204-4475389b-adf5-4f20-a6f5-54b4be6afe06.png)

**Comment by gaurijoshi9** [comment]
@hubertdeng123 
1. Is your project sending in a lot of events in a short time interval? - **yes**
2. Do you have inbound filters set up? - **no, we are not filtering out any events**
3. Do you have rate limit set up in your Sentry project settings? - **yes, we increased from 10k to 10,00,000 now in global settings (https://url/manage/settings/). Could not find the option in specific project settings**

**Comment by hubertdeng123** [comment]
What does your disk/memory usage look like?
