### ISSUE TITLE
Warning during upgrade 22.6 -> 23.3.1

### ISSUE THREAD

**Issue by Apollon77** [getsentry/self-hosted#2061]
### Self-Hosted Version

22.6

### CPU Architecture

x86_64

### Docker Version

23.0.1

### Docker Compose Version

1.29.2

### Steps to Reproduce

checkout branch 23.3.1 and run install.sh

### Expected Result

no warning on code errors

### Actual Result

```
Running migrations for default
/usr/local/lib/python3.8/site-packages/memcache.py:1303: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key is '':
/usr/local/lib/python3.8/site-packages/memcache.py:1304: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key_extra_len is 0:
```

Full log see

[Gesicherte Terminal-Ausgabe.txt](https://github.com/getsentry/self-hosted/files/11120095/Gesicherte.Terminal-Ausgabe.txt)

**Comment by hubertdeng123** [comment]
This is actually a duplicate issue and belongs in the sentry repo so I'm going to close. Thanks for reporting though!
https://github.com/getsentry/sentry/issues/42137
