### ISSUE TITLE
Workers and docker-compose.overrides.yml

### ISSUE THREAD

**Issue by LorenDorez** [getsentry/self-hosted#2072]
### Problem Statement

Hello, I am new to sentry. We setup a self-hosted box and been having some performance issues with the rate of ingestions. We see a backlog on the events.symbolicate_event queue.

I read on the docs that adding some workers might help with this issue. However, i cant seem to fina any examples of the docker-compose.overrides.yml file. 

### Solution Brainstorm

It would be nice if the documentation discussed not only setting this up but the pros and cons as im sure too many workers is a bad thing. Also maybe a suggestion best practices and sample of the overrides file

**Comment by hubertdeng123** [comment]
Are you referring to this documentation?
https://develop.sentry.dev/self-hosted/troubleshooting/#workers

What could be done better here to make this more clear?

**Comment by LorenDorez** [comment]
> Are you referring to this documentation?
> 
> https://develop.sentry.dev/self-hosted/troubleshooting/#workers
> 
> 
> 
> What could be done better here to make this more clear?

Yes I posted also on the documentation repo as well. Appears you can use YAML anchors inside another file. 

So you can't do <<: * sentry_defaults in the docker-compose.override.unless file. You will get an error.

So some proper documentation on how to add those to an override file without having to copy over all the anchors etc from the original docker-compose.

**Comment by hubertdeng123** [comment]
Hmmmm, if you don't want to copy over all the anchors, perhaps you can do that instead in the `docker-compose.yml` file then? You're right though, the documentation there could be better since the tip errors out. However, I don't believe there is an easy way to have an override file without copying all the anchors after looking at this [here](https://github.com/docker/compose/issues/5621)

**Comment by hubertdeng123** [comment]
The file will get overwritten during updates/upgrades since since it will introduce a merge conflict if the `docker-compose.yml` file is changed during the update/upgrade
