### ISSUE TITLE
Can't scale ingest-consumer

### ISSUE THREAD

**Issue by bra-fsn** [getsentry/self-hosted#2086]
### Self-Hosted Version

22.11.0

### CPU Architecture

x86_64

### Docker Version

20.10.17

### Docker Compose Version

1.29.2

### Steps to Reproduce

1. produce a lot of transactions to clog Sentry's `ingest-consumer` (the `ingest-sessions` topic in Kafka shows a significant lag and the `ingest-consumer` container eats 100% CPU
2. try to scale that consumer, should be easy with a message queue. Add more partitions to the `ingest-sessions` topic and spawn more containers(*)
3. even though the new partitions have messages in them, only one consumer actually consumes from them.

That one writes:
```
19:50:38 [INFO] batching-kafka-consumer: New partitions assigned: [TopicPartition{topic=ingest-attachments,partition=0,offset=-1001,error=None}, TopicPartition{topic=ingest-events,partition=0,offset=-1001,error=None}, TopicPartition{topic=ingest-transactions,partition=0,offset=-1001,error=None}]
```

while all other consumers have this in their logs:
```
[INFO] batching-kafka-consumer: New partitions assigned: []
```

*: use this in the `docker-compose.yaml`:
```yaml
  ingest-consumer:
    <<: *sentry_defaults
    deploy:
      replicas: 8
    command: run ingest-consumer --all-consumer-types
```

### Expected Result

I would except that adding new consumers with more Kafka partitions should help to spread the load, so all consumers (if their number matches the Kafka partitions or is more than that) should receive traffic.

### Actual Result

According to the outputs, only one consumer gets traffic.

**Comment by hubertdeng123** [comment]
Is this link helpful?
https://forum.sentry.io/t/how-many-containers-with-consumers-i-should-run-for-sentry/15149/7

It outlines what you may need to do to scale your containers up

**Comment by bra-fsn** [comment]
> Is this link helpful? https://forum.sentry.io/t/how-many-containers-with-consumers-i-should-run-for-sentry/15149/7
> 
> It outlines what you may need to do to scale your containers up

No, sorry.
I'm already running more containers (see the example above) and that I've already created more partitions for the topic in question.
The problem here is even if I have multiple partitions and multiple consumers, only one will get messages, the others log:
```
[INFO] batching-kafka-consumer: New partitions assigned: []
```
and therefore receive nothing.

I'm not yet sure if this is a Kafka or a client (Confluent Kafka or the Sentry consumer) issue.

**Comment by hubertdeng123** [comment]
Ah got it. Snuba and Sentry partition events such that a single project writes to a single partition. Are these events all coming in from one project? If so, scaling out by adding containers won't work. You'll have to do that with these parameters on the consumer that handles events coming in from the one project:
```
--processes
--input-block-size
--output-block-size
```

If your events are spread out between projects, you'll need to perform these two steps. 
1. Add partitions manually: `bin/kafka-topics.sh --zookeeper YOUR_ZOOKEEPER --alter --topic events --partitions XXX`
2. Update `TOPIC_PARTITION_COUNTS` in snuba config

**Comment by bra-fsn** [comment]
> Ah got it. Snuba and Sentry partition events such that a single project writes to a single partition. Are these events all coming in from one project? If so, scaling out by adding containers won't work. You'll have to do that with these parameters on the consumer that handles events coming in from the one project:
> 
> ```
> --processes
> --input-block-size
> --output-block-size
> ```
> 
> If your events are spread out between projects, you'll need to perform these two steps.
> 
>     1. Add partitions manually: `bin/kafka-topics.sh --zookeeper YOUR_ZOOKEEPER --alter --topic events --partitions XXX`
> 
>     2. Update `TOPIC_PARTITION_COUNTS` in snuba config

Are you sure the above stands for the `ingest-consumer`? As far as I can remember, it doesn't support these options.
Yes, the majority belongs to one project, but does it count Kafka-wise?

**Comment by hubertdeng123** [comment]
> Are you sure the above stands for the ingest-consumer? As far as I can remember, it doesn't support these options.
Yes, the majority belongs to one project, but does it count Kafka-wise?

You're right, `ingest-consumer` doesn't seem to have those [options](https://github.com/getsentry/sentry/blob/master/src/sentry/runner/commands/run.py#L498). 

It looks like the `ingest-consumer` only has these types that are listed [here](https://github.com/getsentry/sentry/blob/master/src/sentry/ingest/types.py)(events, attachments, transactions). If you'd like your replicas to consume from those types, you'll need to partition those topics accordingly. I was able to get replicas of `ingest-consumer` to consume messages and get assigned to the appropriate partitions. I am unsure if doing this will reduce the lag on `ingest-sessions` though
