### ISSUE TITLE
Using COMPOSE_PROJECT_NAME breaks postgres migration

### ISSUE THREAD

**Issue by bobvandevijver** [getsentry/self-hosted#2092]
### Self-Hosted Version

23.4.0

### CPU Architecture

x86_64

### Docker Version

23.0.3

### Docker Compose Version

2.17.2

### Steps to Reproduce

Have an existing installation with `COMPOSE_PROJECT_NAME` defined as something else than the default, and run `./install.sh` to migrate to 23.4.0.

The migrations script will try to reference the wrong container, after which the upgrade fails. I have fixed it for now by updating [the script](https://github.com/getsentry/self-hosted/blob/master/install/upgrade-postgres.sh) by hand, to remove the `self-hosted` parts.

### Expected Result

Successful update.

### Actual Result

```
Starting up new PostgreSQL version
 Container sentry-postgres-1  Creating
 Container sentry-postgres-1  Created
 Container sentry-postgres-1  Starting
 Container sentry-postgres-1  Started
Waiting for postgres server, 5 remaining attempts...
Waiting for postgres server, 4 remaining attempts...
Waiting for postgres server, 3 remaining attempts...
Waiting for postgres server, 2 remaining attempts...
Waiting for postgres server, 1 remaining attempts...
Error response from daemon: No such container: sentry-self-hosted-postgres-1
Error in install/upgrade-postgres.sh:34.
'DBS=$(docker exec sentry-self-hosted-postgres-1 psql -qAt -U postgres -c "SELECT datname FROM pg_database WHERE datistemplate = false;")' exited with status 1
-> ./install.sh:main:33
--> install/upgrade-postgres.sh:source:34
```

**Comment by hdhoang** [comment]
i agree with this issue, upgrading from 23.3.1 to 23.4.0. our fix was patching `install/upgrade-postgres.sh` such as:

```bash
sed -e "s,sentry-self-hosted,${COMPOSE_PROJECT_NAME},g"
```

hth

**Comment by hubertdeng123** [comment]
Thanks for bringing this up, I'll put up a PR to address this
