### ISSUE TITLE
OffsetOutOfRange

### ISSUE THREAD

**Issue by ycachencheng** [getsentry/self-hosted#2093]
### Self-Hosted Version

Sentry 23.5.0.dev0

### CPU Architecture

x86_64

### Docker Version

Docker version 23.0.3, build 3e7cbfd

### Docker Compose Version

docker-compose version 1.26.2, build eefe0d31

### Steps to Reproduce

OffsetOutOfRange
KafkaError{code=_AUTO_OFFSET_RESET,val=-140,str="fetch failed due to requested offset not available on the broker: Broker: Offset out of range (broker 1001)"}

### Expected Result

help! thanks

### Actual Result

![image](https://user-images.githubusercontent.com/8850928/232666771-7a95f719-43bf-4ee0-83e2-6cccdb9090a4.png)

**Comment by aldy505** [comment]
See https://github.com/getsentry/self-hosted/issues/1894, try some of the solutions there

**Comment by AlexanderRydberg** [comment]
> See #1894, try some of the solutions there

Tried this one [https://github.com/getsentry/self-hosted/issues/1894#issuecomment-1426538497](https://github.com/getsentry/self-hosted/issues/1894#issuecomment-1426538497) today on our Sentry (23.4.0) instance in our test env.

Couple of minutes now without any events (Occured every 15s before)

**Comment by hubertdeng123** [comment]
Thanks for linking that @aldy505. I'm going to close this as a duplicate issue
