### ISSUE TITLE
upgrade-postgres.sh upgrade issues

### ISSUE THREAD

**Issue by mmospanenko** [getsentry/self-hosted#2098]
### Self-Hosted Version

23.4.0

### CPU Architecture

x86_64

### Docker Version

20.10.21

### Docker Compose Version

v2.12.2

### Steps to Reproduce

1. run ./install.sh
2. wait for Error :)

### Expected Result

Script finishes correctly, without errors and app works as expected. 

Also, there is hard-coded container name `sentry-self-hosted-postgres-1` and if we're using different COMPOSE_PROJECT_NAME - it fails.

### Actual Result

...
``` 
  /var/lib/postgresql/9.6/data/base/12407/308592
  /var/lib/postgresql/9.6/data/base/12407/308594
  /var/lib/postgresql/9.6/data/base/12407/308603
  /var/lib/postgresql/9.6/data/base/12407/308605
  /var/lib/postgresql/9.6/data/base/1/2613
  /var/lib/postgresql/9.6/data/base/1/2683
                                                            ok
Setting next OID for new cluster                            ok
Sync data directory to disk                                 ok
Creating script to delete old cluster                       ok
Checking for hash indexes                                   ok
Checking for extension updates                              notice

Your installation contains extensions that should be updated
with the ALTER EXTENSION command.  The file
    update_extensions.sql
when executed by psql by the database superuser will update
these extensions.


Upgrade Complete
----------------
Optimizer statistics are not transferred by pg_upgrade.
Once you start the new server, consider running:
    /usr/lib/postgresql/14/bin/vacuumdb --all --analyze-in-stages

Running this script will delete the old cluster's data files:
    ./delete_old_cluster.sh
Error response from daemon: remove sentry-postgres: volume is in use - [0d2a24ed76696c22771610b02551f49c3aa05dbfb9ab3d787be3b1a4dba1c529]
Error in install/upgrade-postgres.sh:12.
'docker volume rm sentry-postgres' exited with status 1
-> ./install.sh:main:33
--> install/upgrade-postgres.sh:source:12

Cleaning up...
```

**Comment by hubertdeng123** [comment]
Is this helpful for you?
https://github.com/getsentry/self-hosted/issues/1610#issuecomment-1511716317

**Comment by mmospanenko** [comment]
@hubertdeng123 thank you, yes, I see that I should do it manually, but issue about .sh script that have to care about migrations. People shouldn't care about own cases - it should be integrated in the product. For example I use Ansible for configuration and want to just change number of version for update.

This is not a support request, it is a bug in code
1. update script should work on particular version of environment (avoid using imperative code like this `docker volume rm sentry-postgres` - we can't predict state, as my case with 'volume is in use'). So it should be rewritten in more declarative way, more abstract over implementation.
2. avoid hardcode. `sentry-self-hosted-postgres-1` is not a good idea, use variables for example (if it is convention on the project)

**Comment by hubertdeng123** [comment]
Hi there, sorry to hear that you're experiencing trouble. In an ideal world the script would take care of all cases but it's hard to account for everything. We are providing an upgrade script to help users upgrade that use the out of the box version of self-hosted Sentry. 

For 1, what set of commands would work for you? As for 2, I've merged a [fix](https://github.com/getsentry/self-hosted/pull/2096) to account for this.

**Comment by hrebenarMartin** [comment]
Hi, i also encountered an issue with `upgrade-postgres.sh` script. It was the hardcoded value `sentry-self-hosted-postgres-1`, in my case the correct container name is `sentry_onpremise_posgres_1` ... `sentry_onpremise` is defined in the `.env` rest is automatically created.

Had to manually change the values in the script to move on. Otherwise that was the only issue with upgrade from 21.10 to 23.4. So great job guys. 👏🏻 It could not be easier to move up major versions.

**Comment by aamarques** [comment]
Hi @hubertdeng123, I have a simillar issue but I think at the end of migration.

```
sentry-postgres-new
Re-indexing due to glibc change, this may take a while...
Starting up new PostgreSQL version
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
Creating sentry-self-hosted_postgres_1 ...
Creating sentry-self-hosted_postgres_1 ... done
Waiting for postgres server, 5 remaining attempts...
Waiting for postgres server, 4 remaining attempts...
Waiting for postgres server, 3 remaining attempts...
Waiting for postgres server, 2 remaining attempts...
Waiting for postgres server, 1 remaining attempts...
Error: No such container: sentry-self-hosted-postgres-1
Error in install/upgrade-postgres.sh:34.
'DBS=$(docker exec sentry-self-hosted-postgres-1 psql -qAt -U postgres -c "SELECT datname FROM pg_database WHERE datistemplate = false;")' exited with status 1
-> ./install.sh:main:33
--> install/upgrade-postgres.sh:source:34

Cleaning up...
```

I have tried the [workarround]( https://github.com/getsentry/self-hosted/issues/1610#issuecomment-1511716317) without success (Step 2)
```
PostgreSQL Database directory appears to contain a database; Skipping initialization

FATAL:  "/var/lib/postgresql/data" is not a valid data directory
DETAIL:  File "/var/lib/postgresql/data/PG_VERSION" does not contain valid data.
HINT:  You might need to initdb.
Setting up Change Data Capture
Replication config already present in pg_hba. Not changing anything.
```

Should I need to wait for a new release?

**Comment by hubertdeng123** [comment]
Hi there @aamarques, looks like for you the workaround that you linked shouldn't apply for you. The reason is your postgres upgrade succeeded to the new version. The issue here is the container name. If you apply the changes I made to the script [here](https://github.com/getsentry/self-hosted/pull/2096/files) you should be able to manually run the rest of the script.

**Comment by aamarques** [comment]
Hey @hubertdeng123 wish you are well. :)

I have a VM validating updates using a snapshot before going to production. I changed the ` install/upgrade-postgres.sh ` and run ` install.sh ` from the beginning and I got the following error.
```
Creating sentry-self-hosted_postgres_1 ...
Creating sentry-self-hosted_postgres_1 ... done
Re-indexing database: postgres
" does not existnection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  database "postgres
2
Error in install/upgrade-postgres.sh:37.
'$dc exec postgres psql -qAt -U postgres -d ${db} -c "reindex system ${db}"' exited with status 2
-> ./install.sh:main:33
--> install/upgrade-postgres.sh:source:37

```

Is this fix should run in a fresh update or only when Postgres upgrade succeeded to the new version but run into the previous error (that I have related [before](https://github.com/getsentry/self-hosted/issues/2098#issuecomment-1525441216))?

**Comment by aamarques** [comment]
@hubertdeng123 could you check my question, please? :)

**Comment by hubertdeng123** [comment]
This fix should run in a fresh upgrade when your database is on 9.6. Otherwise, you'll have to manually run the reindex

**Comment by aamarques** [comment]
> This fix should run in a fresh upgrade when your database is on 9.6. Otherwise, you'll have to manually run the reindex

So, This is the error I get in a fresh install.
I'll open a new issue.

**Comment by aamarques** [comment]
@hubertdeng123 
[Issue #2128 ](https://github.com/getsentry/self-hosted/issues/2128)

**Comment by mmospanenko** [comment]
solved with backup/restore using pg_dump. Current script is broken, add some notes in docs please (similar to Kafka offset fixes). Thanks for removing hardcode (project name) :)

**Comment by mmospanenko** [comment]
how to solve this? Seems Clickhouse migration... or Postgres?

```
May 18 01:27:44 srv-inner docker[2316937]: sentry-web                                       | sentry.utils.snuba.QueryMissingColumn: DB::Exception: Missing columns: 'click_title' 'click_role' 'click_class' 'click_aria_label' 'click_testid' 'click_text' '
click_alt' 'click_tag' 'click_id' while processing query: 'SELECT project_id AS _snuba_project_id, replay_id AS _snuba_replay_id, _snuba_replay_id, _snuba_project_id, arrayMap(trace_id -> (replaceAll(toString(trace_id), '-', '') AS _snuba_trace_id), grou
pUniqArrayArray(trace_ids AS _snuba_trace_ids)) AS _snuba_traceIds, arrayMap(error_id -> (replaceAll(toString(error_id), '-', '') AS _snuba_error_id), groupUniqArrayArray(error_ids AS _snuba_error_ids)) AS _snuba_errorIds, min(replay_start_timestamp AS _
snuba_replay_start_timestamp) AS _snuba_started_at, max(timestamp AS _snuba_timestamp) AS _snuba_finished_at, dateDiff('second', _snuba_started_at, _snuba_finished_at) AS _snuba_duration, arrayFlatten(arraySort((urls, sequence_id) -> identity(sequence_id
), arrayMap(url_tuple -> (url_tuple.2), groupArray((segment_id AS _snuba_segment_id, urls AS _snuba_urls)) AS _snuba_agg_urls), arrayMap(url_tuple -> (url_tuple.1), _snuba_agg_urls))) AS _snuba_urls_sorted, _snuba_agg_urls, count(_snuba_segment_id) AS _s
nuba_count_segments, sum(length(_snuba_error_ids)) AS _snuba_count_errors, sum(length(_snuba_urls)) AS _snuba_count_urls, ifNull(max(is_archived AS _snuba_is_archived), 0) AS _snuba_isArchived, floor(greatest(1, least(10, intDivOrZero((_snuba_count_error
s * 25) + (_snuba_count_urls * 5), 10)))) AS _snuba_activity, groupUniqArray(release AS _snuba_release) AS _snuba_releases, any(replay_type) AS _snuba_replay_type, any(platform) AS _snuba_platform, any(environment AS _snuba_environment) AS _snuba_agg_env
ironment, any(dist) AS _snuba_dist, any(user_id) AS _snuba_user_id, any(user_email) AS _snuba_user_email, any(user_name AS _snuba_user_name) AS _snuba_user_username, IPv4NumToString(any(ip_address_v4 AS _snuba_ip_address_v4)) AS _snuba_user_ip, any(os_na
me) AS _snuba_os_name, any(os_version) AS _snuba_os_version, any(browser_name) AS _snuba_browser_name, any(browser_version) AS _snuba_browser_version, any(device_name) AS _snuba_device_name, any(device_brand) AS _snuba_device_brand, any(device_family) AS
 _snuba_device_family, any(device_model) AS _snuba_device_model, any(sdk_name) AS _snuba_sdk_name, any(sdk_version) AS _snuba_sdk_version, groupArrayArray(tags.key AS `_snuba_tags.key`) AS _snuba_tk, groupArrayArray(tags.value AS `_snuba_tags.value`) AS 
_snuba_tv, groupArray(click_alt) AS _snuba_click_alt, groupArray(click_aria_label) AS _snuba_click_aria_label, groupArrayArray(click_class AS _snuba_click_class) AS _snuba_clickClass, groupArray(_snuba_click_class) AS _snuba_click_classes, groupArray(cli
ck_id) AS _snuba_click_id, groupArray(click_role) AS _snuba_click_role, groupArray(click_tag) AS _snuba_click_tag, groupArray(click_testid) AS _snuba_click_testid, groupArray(click_text) AS _snuba_click_text, groupArray(click_title) AS _snuba_click_title
 FROM replays_local WHERE (_snuba_project_id IN [5, 6, 2, 1, 3]) AND (_snuba_timestamp < toDateTime('2023-05-17T22:27:43', 'Universal')) AND (_snuba_timestamp >= toDateTime('2023-02-16T22:27:43', 'Universal')) AND (_snuba_replay_id = 'b3f73c90-5868-4614-
91dc-7f08a15d09f0') GROUP BY _snuba_project_id, _snuba_replay_id HAVING ((_snuba_isArchived = 0) AND (min(_snuba_segment_id) = 0)) AND (_snuba_finished_at < toDateTime('2023-05-17T22:27:43', 'Universal')) ORDER BY _snuba_started_at DESC LIMIT 0, 1000', r
equired columns: 'is_archived' 'error_ids' 'replay_id' 'segment_id' 'tags.value' 'click_id' 'platform' 'project_id' 'device_model' 'trace_ids' 'replay_start_timestamp' 'user_email' 'tags.key' 'urls' 'replay_type' 'release' 'user_id' 'click_tag' 'user_nam
e' 'click_alt' 'ip_address_v4' 'device_name' 'timestamp' 'browser_name' 'os_name' 'dist' 'device_family' 'device_brand' 'os_version' 'sdk_name' 'click_text' 'sdk_version' 'click_testid' 'browser_version' 'click_aria_label' 'environment' 'click_class' 'cl
ick_role' 'click_title', source columns: 'offset' 'sdk_version' 'sdk_name' 'device_family' 'browser_version' 'browser_name' 'device_brand' 'os_version' 'user_name' 'device_name' 'timestamp' 'ip_address_v4' 'os_name' 'dist' 'tags.key' 'user_email' 'replay
_start_timestamp' 'replay_id' 'error_ids' 'url' 'is_archived' 'environment' 'retention_days' 'urls' '_trace_ids_hashed' 'device_model' 'platform' 'project_id' 'partition' 'tags.value' 'segment_id' 'error_sample_rate' 'event_hash' 'title' 'session_sample_
rate' 'user_id' 'ip_address_v6' '_error_ids_hashed' 'user' 'release' 'replay_type' 'trace_ids'. Stack trace:

```

**Comment by LeonB** [comment]
I had the same issue. `docker system prune -f` fixed the issue for me.

**Comment by flottes** [comment]
I had the same issue.

```
Upgrade Complete
----------------
Optimizer statistics are not transferred by pg_upgrade.
Once you start the new server, consider running:
    /usr/lib/postgresql/14/bin/vacuumdb --all --analyze-in-stages

Running this script will delete the old cluster's data files:
    ./delete_old_cluster.sh
Error response from daemon: remove sentry-postgres: volume is in use - [fde005d8fa517c3217a8850ded46cf4ed6ba65494fe1573fb372e44aac8c8d57]
Error in install/upgrade-postgres.sh:12.
'docker volume rm sentry-postgres' exited with status 1
-> ./install.sh:main:33
--> install/upgrade-postgres.sh:source:12

```

Docker says the volume is linked to `sentry_onpremise_postgres_1` (`onpremise` is my folder name)
```
docker ps -a --filter volume="sentry-postgres"  --format '{{.Names}}'
sentry_onpremise_postgres_1
```

`docker container ls -a |grep postgres` showes:
`fde005d8fa51   postgres:9.6                           "/opt/sentry/postgre…"   3 months ago    Exited (0) 3 months ago                                                                                                   sentry_onpremise_postgres_1`

so i removed the `sentry_onpremise_postgres_1` container.

As i noticed my foldername is `onpremise` but in the `.env` file the `COMPOSE_PROJECT_NAME` is `sentry-self-hosted` so i renamed my folder to `self-hosted`.

After running `./install.sh` it works now.

**Comment by pvarry** [comment]
I had the same issue as : https://github.com/getsentry/self-hosted/issues/2098#issuecomment-1531354782

```
Re-indexing database: postgres
" does not existnection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  database "postgres
Error in install/upgrade-postgres.sh:37.
'$dc exec postgres psql -qAt -U postgres -d ${db} -c "reindex system ${db}"' exited with status 2
-> ./install.sh:main:33
--> install/upgrade-postgres.sh:source:37
```

By just re-run install.sh, it finished installation, and it works well now.

**Comment by mmospanenko** [comment]
still waiting for solution...

**Comment by mmospanenko** [comment]
> @mmospanenko What kind of solution are you waiting for? Our postgres upgrade script is meant to serve as a pain free way to upgrade your self-hosted instance, but it's difficult to accommodate for every user's use case. It looks like you've managed to solve your issue from the responses in the thread above. We're happy to work with you to come to a solution during the upgrade process, but not sure what else can be done here.

Sorry, I added comment to wrong thread, thought this is about ARM64.
About Postgres, yes, I managed issue with cleanup, thank you for immediately responses and assistance. 

I think we can close this one, hope everyone migrated successfully :)
