### ISSUE TITLE
Sentry replay is not working

### ISSUE THREAD

**Issue by Tush1999** [getsentry/self-hosted#2100]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

Sentry replay has not been set up after follow all the steps

### Expected Result

The replay should be working fine.

### Actual Result

Nothing is visible under replays section

**Comment by chadwhitacre** [comment]
We're gonna need a lot more info in order to help. What do the logs show? What steps are you taking exactly?

**Comment by Tush1999** [comment]
I am initializing Sentry and session replay by using this code.
  
  Sentry.init({
      dsn: process.env.REACT_APP_SENTRY_DSN,
      environment: process.env.REACT_APP_ENVIRONMENT,
      tracesSampleRate: 1,
      replaysSessionSampleRate: 1,
      replaysOnErrorSampleRate: 1,
      integrations: [new BrowserTracing(), new Sentry.Replay()]
    });
    
    Error is successfully reported on sentry but nothing is visible under Replays Section

**Comment by Tush1999** [comment]
<img width="1437" alt="Screen Shot 2023-04-21 at 10 22 11 PM" src="https://user-images.githubusercontent.com/87068206/233691901-6efa0d71-593a-4308-aa5a-be477d7b469a.png">

**Comment by Tush1999** [comment]
<img width="1440" alt="Screen Shot 2023-04-21 at 10 23 21 PM" src="https://user-images.githubusercontent.com/87068206/233692122-e1ea4670-3ce4-425d-8631-3f4ee24c1b90.png">
The above image is showing the detail of the error and the replay id has also been set for this error

**Comment by Tush1999** [comment]
<img width="1138" alt="Screen Shot 2023-04-21 at 11 15 35 PM" src="https://user-images.githubusercontent.com/87068206/233701426-29f6a78b-bb1f-4a74-a7aa-b8288455834a.png">
<img width="1132" alt="Screen Shot 2023-04-21 at 11 15 52 PM" src="https://user-images.githubusercontent.com/87068206/233701484-c88b4a4b-4c34-4359-b8c4-25e8b8091d88.png">
The above images are related to session replay request and its payload

**Comment by Mordreak** [comment]
Do we have any idea of when this issue could be solved ?

**Comment by thelazyoxymoron** [comment]
+1. Getting the same issue in my self-hosted instance.

**Comment by qwshixiang** [comment]
me too

**Comment by chadwhitacre** [comment]
Thanks for the details @Tush1999 and for chiming in, other folks. :)

@hubertdeng123 Looks like we should look into this one.

**Comment by wardpieters** [comment]
Experiencing the same issue on self-hosted Sentry.
If you've upgraded your Sentry instance, this might be a duplicate of #2057.

**Comment by hubertdeng123** [comment]
@Tush1999 is this an upgraded instance of Sentry? If so this would be a duplicate issue as mentioned above. I haven't been able to take another look at this but may have some time later this week

**Comment by Tush1999** [comment]
Yes, @hubertdeng123 It is an upgraded instance

**Comment by mmospanenko** [comment]
After update to 23.5 having this issue (500). Also, it shows an error with loading files (2-4mb is too large, but I set 20M for memcached). I think some volumes are corrupted but how to debug? Postgres migration is completely broken so I had to export/import dump. Any ideas how to check? 
![image](https://github.com/getsentry/self-hosted/assets/2766211/8254d16f-72fd-40cd-8f06-18fab0d22ae2)

![image](https://github.com/getsentry/self-hosted/assets/2766211/f5599b6c-4853-45d9-bf7a-2835f08eecf8)

**Comment by hubertdeng123** [comment]
Hi there, could you try the steps suggested [here](https://github.com/getsentry/self-hosted/issues/2057#issuecomment-1554052504) to see if this fixes replays for you?

**Comment by chadwhitacre** [comment]
Should we close this as a dupe of #2057? Are there some docs we can update or other fixes we can apply to mitigate this?

**Comment by chadwhitacre** [comment]
Closing as https://github.com/getsentry/self-hosted/issues/2057#issuecomment-1559528234 is resolved.
