### ISSUE TITLE
zookeeper faults after installation

### ISSUE THREAD

**Issue by Lorttexwolf** [getsentry/self-hosted#2101]
### Self-Hosted Version

23.4.0

### CPU Architecture

x86_64

### Docker Version

23.0.3

### Docker Compose Version

2.17.2

### Steps to Reproduce

1. git clone git@github.com:getsentry/self-hosted.git
2. cd self-hosted
3. git checkout 23.4.0
4. ./install.sh
5. docker compose up
6. encounter zookeeper issue

### Expected Result

Sentry should start up correctly and all health checks should pass.

### Actual Result

`installation logs` [sentry_install_log-2023-04-21_10-18-53.txt](https://github.com/getsentry/self-hosted/files/11297142/sentry_install_log-2023-04-21_10-18-53.txt) 
`docker compose up` [logs.txt](https://github.com/getsentry/self-hosted/files/11297137/logs.txt)

**Comment by hubertdeng123** [comment]
Can you try this solution [here](https://github.com/getsentry/self-hosted/issues/1445#issuecomment-1122415883)?

**Comment by Lorttexwolf** [comment]
Thank you, this has solved my problem!
