### ISSUE TITLE
Access to issues metadata

### ISSUE THREAD

**Issue by antonpodolsky** [getsentry/self-hosted#2107]
### Problem Statement

Hi, I'm trying to collect some stats from our self-hosted Sentry and need access to the issues table.
What I need is the number of daily seen/resolved/ignored issues.

I went over the PostgreSQL tables and didn't find the table that stores issues metadata and the resolved/ignored state.

Please advise how this data can be obtained (without using the REST APIs).

**Comment by antonpodolsky** [comment]
Thanks @hubertdeng123.

We need to have this data for all projects across multiple organizations (around 30 and growing, each org has ~5 projects) and display the data in our own dashboards, so we can see usage/adoption trends.

**Comment by antonpodolsky** [comment]
Our Stats => Issues page shows zeroes unfortunately. I suppose that could be another way to get the data.

![image](https://user-images.githubusercontent.com/7899596/234832248-14556209-73d6-4a1f-93cc-a584c2999c8d.png)

**Comment by hubertdeng123** [comment]
Hmmm, I don't think it's working for me either. Doesn't seem normal 🤔

**Comment by hubertdeng123** [comment]
filed an issue after replicating on SaaS:
https://github.com/getsentry/sentry/issues/48113

**Comment by hubertdeng123** [comment]
Ok, seems like that page requires your issues to be assigned to a certain team. So for your use case, it might not be super helpful. You won't find much data in regards to issue data in Postgres, that will live in Clickhouse. Particularly the `errors_local` table

**Comment by antonpodolsky** [comment]
@hubertdeng123 Thanks for looking into it. 
So an issue needs to be assigned to a team manually/using ownership rules in order for the stats to show some numbers?

Also, looks like the Postgres `sentry_activity` has the data I need.
