### ISSUE TITLE
invalid platform architecture "amd64"

### ISSUE THREAD

**Issue by wushiwein119** [getsentry/self-hosted#2108]
### Self-Hosted Version

23.4.0

### CPU Architecture

x86_64

### Docker Version

18.03.1-ce

### Docker Compose Version

1.18.0

### Steps to Reproduce

./install.sh

### Expected Result

success

### Actual Result

▶ Parsing command line ...

▶ Detecting Docker platform
Detected Docker platform is linux/amd64

▶ Initializing Docker Compose ...

▶ Setting up error handling ...
Sending build context to Docker daemon  2.048kB
Error response from daemon: invalid platform: invalid platform architecture "amd64"

**Comment by hubertdeng123** [comment]
Our minimum requirements are Docker 19.03.6+ as listed in our README. Could you try upgrading your version of Docker and try again?

**Comment by wushiwein119** [comment]
▶ Creating volumes for persistent storage ...
Created sentry-clickhouse.
Created sentry-data.
Created sentry-kafka.
Created sentry-postgres.
Created sentry-redis.
Created sentry-symbolicator.
Created sentry-zookeeper.

▶ Ensuring files from examples ...
sentry/sentry.conf.py already exists, skipped creation.
sentry/config.yml already exists, skipped creation.
symbolicator/config.yml already exists, skipped creation.

▶ Ensuring Relay credentials ...
relay/config.yml already exists, skipped creation.
relay/credentials.json already exists, skipped creation.

▶ Generating secret key ...

▶ Fetching and updating Docker images 

wait longtime，what‘s happen？

**Comment by wushiwein119** [comment]
it is too hard to install sentry,

**Comment by wushiwein119** [comment]
> Our minimum requirements are Docker 19.03.6+ as listed in our README. Could you try upgrading your version of Docker and try again?

▶ Bootstrapping and migrating Snuba ...
 Network sentry-self-hosted_default  Creating
 Network sentry-self-hosted_default  Created
 Container sentry-self-hosted-clickhouse-1  Creating
 Container sentry-self-hosted-zookeeper-1  Creating
 Container sentry-self-hosted-redis-1  Creating
 Container sentry-self-hosted-zookeeper-1  Created
 Container sentry-self-hosted-kafka-1  Creating
 Container sentry-self-hosted-redis-1  Created
 Container sentry-self-hosted-clickhouse-1  Created
 Container sentry-self-hosted-kafka-1  Created
 Container sentry-self-hosted-clickhouse-1  Starting
 Container sentry-self-hosted-redis-1  Starting
 Container sentry-self-hosted-zookeeper-1  Starting
 Container sentry-self-hosted-clickhouse-1  Started
 Container sentry-self-hosted-zookeeper-1  Started
 Container sentry-self-hosted-zookeeper-1  Waiting
 Container sentry-self-hosted-redis-1  Started
 Container sentry-self-hosted-zookeeper-1  Healthy
 Container sentry-self-hosted-kafka-1  Starting
 Container sentry-self-hosted-kafka-1  Started
./docker_entrypoint.sh: line 15: exec: bootstrap: not found

After multiple retries，I'm going to collapse

**Comment by hubertdeng123** [comment]
Hmmmm, Are you still using docker compose version 1.18.0? These are our minimum requirements:
Docker 19.03.6+
Compose 1.28.0+
4 CPU Cores
8 GB RAM
20 GB Free Disk Space
