### ISSUE TITLE
After the issue is successfully reported by the browser, it is not seen in the issue list of sentry background

### ISSUE THREAD

**Issue by yang200258** [getsentry/self-hosted#2116]
### Self-Hosted Version

23.1.1

### CPU Architecture

x86_64

### Docker Version

22

### Docker Compose Version

2.6

### Steps to Reproduce

1.when i look the issue has reported in the browser:
<img width="780" alt="image" src="https://user-images.githubusercontent.com/38518538/235388815-d699dddc-cc8c-4978-856e-8f582d9e013f.png">
2.There is no result in issue list:
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/38518538/235388989-ac854db6-8f2b-4f38-ab6c-be37b566810b.png">
3.So i see the stats page:
<img width="1181" alt="image" src="https://user-images.githubusercontent.com/38518538/235389039-e08799c9-8819-4e5b-ba43-2774fcc77ce2.png">
4.how to controll the dropped errors?

### Expected Result

Just make the issues reported sucessful.

### Actual Result

I can not see the reported issues in sentry background.

### Event ID

378d66fcd4ac41198317aec5b73c05a2

**Comment by hubertdeng123** [comment]
Do you happen to have a sample rate/rate limit configured? There's some documentation on why these errors might be dropped. 

https://develop.sentry.dev/sdk/client-reports/

**Comment by yang200258** [comment]
> 

Yeah,i configure tracesSampleRate is 0.1,Finally, I found the reason. It was because there were too many error reports, which caused the queue to be blocked. After I added a cache and expanded the woker, I could report normally.

**Comment by hubertdeng123** [comment]
got it, will close this issue then. Glad you were able to find a solution
