### ISSUE TITLE
Unusual Event Grouping Behavior

### ISSUE THREAD

**Issue by prasadkris** [getsentry/self-hosted#2124]
### Problem Statement

We are using Sentry v22.7.0 on our self-hosted Kubernetes cluster (v1.25.7) and have encountered an odd behavior with event grouping. 

The issue is that we frequently observe completely unrelated events being grouped together within a single issue 🙁 

Upon examining the event grouping information, I found that all these events have the same hash value, which is why they are grouped together. Is there a reason why entirely different events would have identical hash values? 

I'm not sure if this issue can be resolved by creating custom grouping rules. We are currently using the default [event grouping](https://docs.sentry.io/product/data-management-settings/event-grouping/) settings. I attempted to modify the fingerprint, stack trace rules, but it didn't help. It's possible that the approach I took was incorrect. I would appreciate it if someone could provide pointers on fixing this behavior. Thanks!

**Comment by hubertdeng123** [comment]
Different events shouldn't have the same hash value. Could you provide more details on this? Are the events happening at different lines of code? Different error messages? Different stacktraces? We are working on improving the grouping algorithm but could use some more context
