### ISSUE TITLE
Sentry stops processing new events after high volume

### ISSUE THREAD

**Issue by sekroots** [getsentry/self-hosted#2130]
### Self-Hosted Version

20.9.0

### CPU Architecture

x86_64

### Docker Version

23.0.5

### Docker Compose Version

1.27.4

### Steps to Reproduce

Setup sentry self-hosted version 20.9.0, configure some applications and reproduce a high volume events sending to sentry;
We noticed a high volume events at table nodestore_node on postgres.

Related issues:
https://github.com/getsentry/self-hosted/issues/859
https://forum.sentry.io/t/no-new-events-log-event-exceeded-its-configured-lifetime/12845/3
https://github.com/getsentry/self-hosted/issues/1853
https://github.com/getsentry/self-hosted/issues/1562
https://forum.sentry.io/t/relay-errors-in-fresh-new-on-premise-install/9804

### Expected Result

It should work fine and be able to process this volume.

### Actual Result

There was an error creating your Issue: body is too long (maximum is 65536 characters), so I uploaded logs here: https://pasteio.com/xU77pQbkUMpe[ https://pasteio.com/xU77pQbkUMpe ](url)

**Comment by hubertdeng123** [comment]
Hi there, how much volume are we talking? Self-hosted Sentry is not built for scale, so this may be expected

**Comment by sekroots** [comment]
Hello @hubertdeng123, our Sentry  had average 22k daily events but  Sentry stops processing new events after it reached 249k at 24/04/2023.

This is the evidence: [https://pasteboard.co/g2jjPJuJWdUe.jpg](url)


thanks.

**Comment by sekroots** [comment]
Any help to solve this issue?

I am trying to perform backup to import on a brand new sentry instance v 21.6.3 as suggested https://develop.sentry.dev/self-hosted/releases/
