### ISSUE TITLE
Is it possible to deploy self hosted sentry in one container?

### ISSUE THREAD

**Issue by WalkerWalker** [getsentry/self-hosted#2131]
### Problem Statement

Is it possible to deploy self hosted sentry in container?

### Solution Brainstorm

I would say the answer is almost certainly yes.  but maybe someone has already build an image for it.  I can image to provision the image with docker, compose and python and run the installation script in the container.   Hopefully I am not the first one to ask this.  Thank you in advance.

**Comment by hubertdeng123** [comment]
We don't officially support this. What is the reason you would want to deploy self-hosted Sentry in 1 container? It's generally recommended to have different Sentry services in different docker containers.

**Comment by WalkerWalker** [comment]
> We don't officially support this. What is the reason you would want to deploy self-hosted Sentry in 1 container? It's generally recommended to have different Sentry services in different docker containers.

Cuz then I can manage it in my own docker compose and deploy at multiple on-premise servers easier.
