### ISSUE TITLE
How to configure ClickHouse to run on another machine?

### ISSUE THREAD

**Issue by yakiler** [getsentry/self-hosted#2136]
### Problem Statement

"I have successfully started the Sentry service according to the documentation, but I noticed that ClickHouse consumes a significant amount of memory. I would like to deploy ClickHouse separately and allocate additional memory resources to it. Due to limited hardware on a single machine, I need to deploy ClickHouse and Sentry on different machines. How can I configure them to communicate properly? The Sentry service is still started using .init.sh && docker compose up -d, while ClickHouse will be deployed on another machine using docker run -d --name clickhouse-svr -p 8123 -p 9000 -p 9009 -e CLICKHOUSE_DB=sentry -e CLICKHOUSE_USER=sentry -e CLICKHOUSE_PASSWORD=sentry yandex/clickhouse-server."

**Comment by hubertdeng123** [comment]
If you'd like to do this, you would need to modify the `CLICKHOUSE_HOST` to point to your external clickhouse server. Then, you can delete the clickhouse service in the [docker-compose.yml file ](https://github.com/getsentry/self-hosted/blob/25f10ea8974cb0b42cb3c8d495c2e8d3be73a54e/docker-compose.yml#L208). You would also need to include snuba clickhouse [migrations](https://github.com/getsentry/snuba/blob/master/MIGRATIONS.md) for your instance.
