### ISSUE TITLE
where is docker image soure code ?

### ISSUE THREAD

**Issue by cuijiudai** [getsentry/self-hosted#2137]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

I cloned https://github.com/getsentry/sentry,  switch to the tag 23.2.0,  run `yarn`,  `yarn run  dev-ui` to start the Front-end project ,but it's not the same as the self-host docker image 23.2.0, so what wrong with my operation ?

### Expected Result

source code runs as the docker image does .

### Actual Result

source code runs not  the docker image does .

### Product Area

Discover

**Comment by hubertdeng123** [comment]
Which image are you seeing then? Self-hosted version 23.2.0 uses the `getsentry/sentry` 23.2.0 docker image as specified in the [.env file](https://github.com/getsentry/self-hosted/blob/23.2.0/.env#L8). There may be something going wrong with your dev setup perhaps?

**Comment by aminvakil** [comment]
I think what you're looking for is https://github.com/getsentry/sentry/blob/master/docker/Dockerfile .
