### ISSUE TITLE
Performance monitoring in self-hosted?

### ISSUE THREAD

**Issue by adamyaziji** [getsentry/self-hosted#2139]
### Problem Statement

Hi, just wondering if there is an ETA on when performance monitoring will be available for self-hosted instances? I notice that this was previously marked in beta but its not anymore: https://docs.sentry.io/product/performance/#explore-performance-metrics. Is it likely to be in a near-future release for self-hosted?
Thanks!

**Comment by aldy505** [comment]
It's already supported in self-hosted instance, and it's enabled by default.

**Comment by adamyaziji** [comment]
Ah man I'm sorry, I meant profiling haha. Any ideas profiling will be available?

**Comment by aldy505** [comment]
See https://github.com/getsentry/self-hosted/issues/1993#issuecomment-1533431892. We're all still waiting for the public Docker image for vroom.

**Comment by hubertdeng123** [comment]
It should be in the near future now. Looks like they're working on a release process here:
https://github.com/getsentry/vroom/pull/252

You can refer to this ticket as a main source of truth for releasing profiling for self-hosted:
https://github.com/getsentry/self-hosted/issues/1838
