### ISSUE TITLE
ProGuard Mappings automatic cleanup

### ISSUE THREAD

**Issue by adamherman** [getsentry/self-hosted#2140]
### Environment
self-hosted

### Version
23.4.0

### Problem
We are facing currently, a problem with the decreasing amount of free disk space on our Sentry server, primarily caused by the growing number of ProGuard Mapping files.

On a daily basis, we build approximately 50 versions of our application, and with each version, we upload ProGuard Mapping files to the Sentry server, which have an average size of around 80MB. As you can imagine, this results in a significant amount of disk space being occupied every day, approximately 4GB.

Unfortunately, we haven't been able to find a suitable solution so far that would enable us to automatically clean up these files, for example, after a certain period of time. Additionally, the administrative panel does not provide an option to delete multiple files at once, but only allows deleting each file individually, which becomes cumbersome when dealing with a larger number of files.

Therefore, I would like to inquire if there is any way to automate the cleaning process for ProGuard Mapping files. It would be greatly appreciated if you could provide guidance or suggest a solution that would allow us to free up disk space more efficiently.

**Comment by hubertdeng123** [comment]
Currently, we don't have an official solution that enables automatic cleanup of these files. However, there's a user that posted their solution for dealing with growing disk space usage [here](https://github.com/getsentry/self-hosted/issues/2121#issuecomment-1534181631) which might be helpful
