### ISSUE TITLE
projects:discard-groups is being ignored

### ISSUE THREAD

**Issue by thenitai** [getsentry/self-hosted#2141]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

1. Add feature to sentry config:
```
# Enables the Discard and Delete feature
SENTRY_FEATURES['projects:discard-groups'] = True
```

2. Run ./install.sh

3. Sentry still reports that the feature is not enabled:

![image](https://github.com/getsentry/sentry/assets/372121/bd3caa6b-4727-481a-a46a-fa14914ddab3)

### Expected Result

Feature to be enabled :)

### Actual Result

Done

### Product Area

Issues

### Version

23.5.0.dev0

**Comment by hubertdeng123** [comment]
This looks like it is a super old feature flag 🤔

**Comment by thenitai** [comment]
Agreed, but as you see it's in the latest release and I keep on getting it...

**Comment by hubertdeng123** [comment]
Are you putting this in your `sentry.conf.py` file? I am not able to reproduce, I'm able to discard an event.
