### ISSUE TITLE
Server-side scrubber does not remove objects with secret key

### ISSUE THREAD

**Issue by HansAarneLiblik** [getsentry/self-hosted#2148]
### Self-Hosted Version

22.12.0

### CPU Architecture

x86_64

### Docker Version

20.10.22

### Docker Compose Version

1.29.2

### Steps to Reproduce

Send data to Sentry via Python integration with code variables

```py
    my_data = {
        "secret": "t0ast",
        "secret_row": "t0ast",
        "password": "t0ast",
        "token": "t0ast",
        "key": "t0ast",
        "secret_dct": {"f1": "t0ast", "secret_f1": "t0ast"},
        "dct": {"f1": "t0ast", "secret_f1": "t0ast"},
        "secret_lst": ["f1", "secret_f1", "password"],
        "lst": ["f1", "secret_f1", "password"],
    }
    secret = {"default": "t0ast", "secret": "t0ast"}

    secret_dct = {"key": "t0ast", "random": "t0ast", "aruba": "jamaica"}
    secret_lst = ["f1", "secret_f1", "password"]
    secret_variable = "t0ast"
```

### Expected Result

Every variable, that contains `secret` is scrubbed

### Actual Result

Dicts with name `secret` or `secret_dct` are not scrubbed. Lists and primitives are

![image](https://github.com/getsentry/self-hosted/assets/5418540/340366fd-7223-497e-be85-331bce953d5c)

![image](https://github.com/getsentry/self-hosted/assets/5418540/0d655da6-1022-4c21-92c6-49f95d75e2e6)

**Comment by hubertdeng123** [comment]
Looks like this was added in release [23.2.0](https://github.com/getsentry/relay/releases/tag/23.2.0), so you'll need to upgrade to pick this up

https://github.com/getsentry/relay/pull/1789

**Comment by HansAarneLiblik** [comment]
Thanks for the link! My searches proved no results :( Will look into upgrading our sentry!
