### ISSUE TITLE
/etc/sentry/entrypoint.sh does not exist

### ISSUE THREAD

**Issue by cascadetile** [getsentry/self-hosted#2149]
### Self-Hosted Version

23.3.1

### CPU Architecture

x86_64

### Docker Version

23.0.3

### Docker Compose Version

2.17.0

### Steps to Reproduce

self-hosted folder is inside /home/username/
docker_data is inside /opt
I also skipped curl wal2json certificate check, because of self-signed certs on my server (`-k` flag in install-wal2json.sh)
After executing `sudo bash install.sh` everything is fine until set-up-and-migrate-database.sh begin processing line 12. Then it gives me this error:

```
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec /etc/sentry/entrypoint.sh: permission denied: unknown
Error in install/set-up-and-migrate-database.sh:12.
'$dcr web upgrade' exited with status 1
-> install.sh:main:33
--> install/set-up-and-migrate-database.sh:source:12

Cleaning up...
```

I tried to check /etc/ during the process of Dockerfile and it does not create an entrypoint.sh or sentry folder. I tried to create that folder myself and give it 777 permissions, but it did not help. Maybe I could create that .sh myself, but I don't know its content

### Expected Result

Fresh install of Sentry

### Actual Result

```
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec /etc/sentry/entrypoint.sh: permission denied: unknown
Error in install/set-up-and-migrate-database.sh:12.
'$dcr web upgrade' exited with status 1
-> install.sh:main:33
--> install/set-up-and-migrate-database.sh:source:12

Cleaning up...
```

![image](https://github.com/getsentry/self-hosted/assets/112803211/cef892d1-9dd3-45f8-b01c-4d995e8dcbd3)

**Comment by cascadetile** [comment]
> What are the permissions of the script in `sentry/entrypoint.sh`? Are there executable permissions there?

Sorry, couldn't get access to check it
senty/entrypoint.sh has these permissions
![image](https://github.com/getsentry/self-hosted/assets/112803211/e32c598e-6dae-442b-861d-dc3bd206d42c)

**Comment by cascadetile** [comment]
@hubertdeng123 does this installation create folders inside /etc?

**Comment by hubertdeng123** [comment]
The installation will mount the `sentry` folder to `/etc/sentry`
