### ISSUE TITLE
support for traefik deploy

### ISSUE THREAD

**Issue by sandroden** [getsentry/self-hosted#2152]
### Problem Statement

This is not properly a feature request, maybe there's already something I overlooked.
I just deployed sentry under Traefik. Everything is up ad seems to work pretty well.

To obtain the setup I had to add some labels and a network to my `docker-compose.yaml`, namely for web and relay.
Is there a suggested approach to preserve these added conf when upgrading sentry (git pull?)

**Comment by mmospanenko** [comment]
just add some lines to nginx service

`
    networks:
      - proxy
      - default
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.sentry.rule=Host(`{{ server_name }}`)'
      - 'traefik.http.routers.sentry.entrypoints=websecure'
      - 'traefik.http.routers.sentry.tls.certresolver=letsEncrypt'
`
where proxy - traefik's network and tsl/entrypoint configs from your setup

**Comment by hubertdeng123** [comment]
Thanks for the suggestions everyone. Does that help you out @sandroden?
