### ISSUE TITLE
Events list doesn't work if there are more than 50 events

### ISSUE THREAD

**Issue by keithlammers** [getsentry/self-hosted#2156]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

1. Generate an issue with more than 50 events so that the list has to page.
2. Navigate to the issue, then click "All Events." The list hangs at the loading circle.

### Expected Result

The list should fully load.

### Actual Result

The list hangs at the loading circle. See screenshot below.

![image](https://github.com/getsentry/sentry/assets/7863361/0c29f17f-e56f-4683-b560-3db167dae93d)

There is somewhat of a workaround. If you enter a search query on that page, then clear the query, the list of events will load. If you navigate to the next page of events, it hangs again, but the search query/clear trick will work again on that page.

### Product Area

Issues

### Version

23.5.0

**Comment by chadwhitacre** [comment]
> The list hangs at the loading circle.

What do you see in your docker logs, @keithlammers?

**Comment by keithlammers** [comment]
@chadwhitacre Good question! I'm not well versed in docker, but I assume you mean the container logs? If so, are you wanting me to check the logs for the `sentry-self-hosted_web_1` container?

**Comment by keithlammers** [comment]
The dev console output actually helped me track this down and it is not a Sentry issue. Our reverse proxy had a limit on the query string size and the query string used on this page was longer than that limit. Increasing the limit on the reverse proxy fixed this up. My only thought here is that maybe that query string could be optimized, but if that's not necessary or possible, please just close this issue.

Thanks!

**Comment by chadwhitacre** [comment]
Glad you were able to figure this out! :)

> My only thought here is that maybe that query string could be optimized, but if that's not necessary or possible, please just close this issue.

I expect the juice ain't gonna be worth the squeeze. If enough others run into similar issues we can revisit.

Cheers! 😁 🍻

**Comment by keithlammers** [comment]
Haha, all good! 🍻
