### ISSUE TITLE
"Profiling" features available on self-hosted ?

### ISSUE THREAD

**Issue by franck-grenier** [getsentry/self-hosted#2159]
### Problem Statement

Hello Sentry,
does "self-hosted" Sentry provide "Profiling" features as shown in the recent webinar https://www.youtube.com/watch?v=9n_qbENm2Lw&t=880s ?

I run self-hosted Sentry 23.2.0.

**Comment by AlexanderRydberg** [comment]
Does this answer your question https://github.com/getsentry/self-hosted/issues/2139#issuecomment-1548228592 :-) ?

**Comment by hubertdeng123** [comment]
It will be available in the near future. You can follow the process for enabling it here:
https://github.com/getsentry/self-hosted/issues/1838
