### ISSUE TITLE
Ability to run containerless under NixOS

### ISSUE THREAD

**Issue by TheArcaneBrony** [getsentry/self-hosted#2160]
### Problem Statement

I'd love to run Sentry under NixOS. This allows me to compact my services down to a single machine without dealing with the overhead of containers and additional VMs.
It's *possible* to run Docker under NixOS, but takes a lot of tinkering to get running.
I'm willing to bring my own Postgres instance, etc. if I have to.

### Solution Brainstorm

When implementing, assert that the database(s) are enabled.

**Comment by hubertdeng123** [comment]
Hi there, don't think we can prioritize this right now, but will put this on the backlog

**Comment by anpin** [comment]
@bc-sentry can you point out where it was implemented?

**Comment by bc-sentry** [comment]
@anpin I closed this because we do not plan to support NixOS.
