### ISSUE TITLE
generate backup.json json without running  ... web export > sentry/backup.json

### ISSUE THREAD

**Issue by buchidiai** [getsentry/self-hosted#2162]
### Self-Hosted Version

22.11.0

### CPU Architecture

x86_64

### Docker Version

Docker version 24.0.1, build 6802122

### Docker Compose Version

N/A

### Steps to Reproduce

N/A

### Expected Result

N/A

### Actual Result

When I execute the command "docker compose run --rm -T -e SENTRY_LOG_LEVEL=CRITICAL web export > sentry/backup.json" on my current instance, it encounters an unknown error that leads to a 502 bad gateway error in the application. Despite attempting various troubleshooting methods and consulting past issues, I have been unable to resolve the problem.

However, I have now set up a new instance where I no longer encounter the 502 error, and I have access to the PostgreSQL database. I can successfully execute queries on the existing data. My main concern is whether the command "docker compose run --rm -T -e SENTRY_LOG_LEVEL=CRITICAL web export > sentry/backup.json" utilizes a script that I can directly call to export the necessary information. By doing so, I aim to safeguard the project configurations. Additionally, I have access to the following tables:

1. auth_authenticator
2.  auth_group
3.  auth_group_permissions
4.  auth_permission
5.  auth_user
6.  django_admin_log
7.  django_content_type
8.  django_migrations
9.  django_session
10.  django_site
11.  nodestore_node
12.  pg_buffercache
13.  pg_stat_statements
14.  replays_replayrecordingsegment
15.  sentry_activity
16.  sentry_actor
17.  sentry_alertrule
18.  sentry_alertruleactivity
19.  sentry_alertruleexcludedprojects
20.  sentry_alertruletrigger
21.  sentry_alertruletriggeraction
22.  sentry_alertruletriggerexclusion
23.  sentry_apiapplication
24.  sentry_apiauthorization
25.  sentry_apigrant
26.  sentry_apikey
27.  sentry_apitoken
28.  sentry_appconnectbuild
29.  sentry_assistant_activity
30.  sentry_auditlogentry
31.  sentry_authidentity
32.  sentry_authprovider
33.  sentry_authprovider_default_teams
34.  sentry_broadcast
35.  sentry_broadcastseen
36.  sentry_commit
37.  sentry_commitauthor
38.  sentry_commitfilechange
39.  sentry_dashboard
40.  sentry_dashboardproject
41.  sentry_dashboardtombstone
42.  sentry_dashboardwidget
43.  sentry_dashboardwidgetquery
44.  sentry_deletedorganization
45.  sentry_deletedproject
46.  sentry_deletedteam
47.  sentry_deploy
48.  sentry_discoversavedquery
49.  sentry_discoversavedqueryproject
50.  sentry_distribution
51.  sentry_docintegration
52.  sentry_docintegrationavatar
53.  sentry_email
54.  sentry_environment
55.  sentry_environmentproject
56.  sentry_environmentrelease
57.  sentry_eventattachment
58.  sentry_eventprocessingissue
59.  sentry_eventuser
60.  sentry_exporteddata
61.  sentry_exporteddatablob
62.  sentry_externalactor
63.  sentry_externalissue
64.  sentry_featureadoption
65.  sentry_file
66.  sentry_fileblob
67.  sentry_fileblobindex
68.  sentry_fileblobowner
69.  sentry_groupasignee
70.  sentry_groupbookmark
71.  sentry_groupcommitresolution
72.  sentry_groupedmessage
73.  sentry_groupemailthread
74.  sentry_groupenvironment
75.  sentry_grouphash
76.  sentry_grouphistory
77.  sentry_groupinbox
78.  sentry_grouplink
79.  sentry_groupmeta
80.  sentry_groupowner
81.  sentry_groupredirect
82.  sentry_grouprelease
83.  sentry_groupresolution
84.  sentry_grouprulestatus
85.  sentry_groupseen
86.  sentry_groupshare
87.  sentry_groupsnooze
88.  sentry_groupsubscription
89.  sentry_grouptombstone
90.  sentry_identity
91.  sentry_identityprovider
92.  sentry_incident
93.  sentry_incidentactivity
94.  sentry_incidentproject
95.  sentry_incidentseen
96.  sentry_incidentsnapshot
97.  sentry_incidentsubscription
98.  sentry_incidenttrigger
99.  sentry_integration
100.  sentry_integrationexternalproject
101.  sentry_integrationfeature
102.  sentry_latestappconnectbuildscheck
103.  sentry_latestrelease
104.  sentry_lostpasswordhash
105.  sentry_metricskeyindexer
106.  sentry_monitor
107.  sentry_monitorcheckin
108.  sentry_monitorlocation
109.  sentry_notificationsetting
110.  sentry_option
111.  sentry_organization
112.  sentry_organizationaccessrequest
113.  sentry_organizationavatar
114.  sentry_organizationintegration
115.  sentry_organizationmember
116.  sentry_organizationmember_teams
117.  sentry_organizationonboardingtask
118.  sentry_organizationoptions
119.  sentry_pagerdutyservice
120.  sentry_pendingincidentsnapshot
121.  sentry_performanceteamkeytransaction
122.  sentry_perfstringindexer
123.  sentry_platformexternalissue
124.  sentry_processingissue
125.  sentry_project
126.  sentry_projectavatar
127.  sentry_projectbookmark
128.  sentry_projectcodeowners
129.  sentry_projectcounter
130.  sentry_projectdsymfile
131.  sentry_projectintegration
132.  sentry_projectkey
133.  sentry_projectoptions
134.  sentry_projectownership
135.  sentry_projectplatform
136.  sentry_projectredirect
137.  sentry_projectteam
138.  sentry_projecttransactionthreshold
139.  sentry_projecttransactionthresholdoverride
140.  sentry_promptsactivity
141.  sentry_pull_request
142.  sentry_pullrequest_commit
143.  sentry_querysubscription
144.  sentry_rawevent
145.  sentry_recentsearch
146.  sentry_relay
147.  sentry_relayusage
148.  sentry_release
149.  sentry_release_project
150.  sentry_releaseactivity
151.  sentry_releasecommit
152.  sentry_releasefile
153.  sentry_releaseheadcommit
154.  sentry_releaseprojectenvironment
155.  sentry_repository
156.  sentry_repositoryprojectpathconfig
157.  sentry_reprocessingreport
158.  sentry_rule
159.  sentry_ruleactivity
160.  sentry_rulefirehistory
161.  sentry_savedsearch
162.  sentry_savedsearch_userdefault
163.  sentry_scheduleddeletion
164.  sentry_scheduledjob
165.  sentry_sentryapp
166.  sentry_sentryappavatar
167.  sentry_sentryappcomponent
168.  sentry_sentryappinstallation
169.  sentry_sentryappinstallationforprovider
170.  sentry_sentryappinstallationtoken
171.  sentry_sentryfunction
172.  sentry_servicehook
173.  sentry_servicehookproject
174.  sentry_snubaquery
175.  sentry_snubaqueryeventtype
176.  sentry_stringindexer
177.  sentry_team
178.  sentry_teamavatar
179.  sentry_timeseriessnapshot
180.  sentry_useravatar
181.  sentry_useremail
182.  sentry_userip
183.  sentry_useroption
184.  sentry_userpermission
185.  sentry_userreport
186.  sentry_userrole
187.  sentry_userrole_users
188.  social_auth_usersocialauth

**Comment by hubertdeng123** [comment]
You can take a look at the source code that is used for the import/export command if that is helpful to you:
https://github.com/getsentry/sentry/blob/5b2337016e17111b975bf776e70bf92655e6e3a3/src/sentry/runner/commands/backup.py

**Comment by buchidiai** [comment]
Thanks for your response. How can I manually call with function without using the docker command? I just need the exported data in this format ? 
```
[
{
  "model": "sites.site",
  "pk": 1,
  "fields": {
    "domain": "example.com",
    "name": "example.com"
  }
},
{
  "model": "sentry.actor",
  "pk": 1,
  "fields": {
    "type": 0
  }
},
{
  "model": "sentry.actor",
  "pk": 2,
  "fields": {
    "type": 1
  }
},
{
  "model": "sentry.option",
  "pk": 1,
  "fields": {
    "key": "sentry:install-id",
    "value": "gAJYKAAAAGVjM2NiZDA5Y2EzNmU5MjFmODI5MDBlOGYzNmIzMWU1OTNhNjE5NjFxAC4=",
    "last_updated": "2023-05-24T15:21:33.259Z"
  }
},
{
  "model": "sentry.option",
  "pk": 2,
  "fields": {
    "key": "sentry:last_worker_ping",
    "value": 1684946426.8165853,
    "last_updated": "2023-05-24T16:40:26.816Z"
  }
},
{
  "model": "sentry.option",
  "pk": 3,
  "fields": {
    "key": "sentry:last_worker_version",
    "value": "gAJYBwAAADIyLjExLjBxAC4=",
    "last_updated": "2023-05-24T16:40:26.894Z"
  }
},
{
  "model": "sentry.option",
  "pk": 4,
  "fields": {
    "key": "sentry:latest_version",
    "value": "gAJYBgAAADIzLjUuMXEALg==",
    "last_updated": "2023-05-24T16:21:36.397Z"
  }
},
]
```

**Comment by hubertdeng123** [comment]
I don't think there's a way to call that function without using the docker command, since the code lives in the web container. If you create your own script you may be able to do it outside docker though.
