### ISSUE TITLE
ModuleNotFoundError: No module named 'csp'

### ISSUE THREAD

**Issue by defp** [getsentry/self-hosted#2163]
### Self-Hosted Version

Self-Hosted Sentry 23.5.1

### CPU Architecture

x86_64

### Docker Version

24.0.1

### Docker Compose Version

Docker Compose version v2.18.1

### Steps to Reproduce

install.sh
docker compose --env-file .env.custom up

### Expected Result

web is ok

### Actual Result

sentry-self-hosted-web-1  | gateway "uWSGI http 1" has been buried (pid: 691)
sentry-self-hosted-web-1  | Exception ignored in: <module 'threading' from '/usr/local/lib/python3.8/threading.py'>
sentry-self-hosted-web-1  | Traceback (most recent call last):
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/threading.py", line 1355, in _shutdown
sentry-self-hosted-web-1  |     def _shutdown():
sentry-self-hosted-web-1  | KeyboardInterrupt:
sentry-self-hosted-web-1  | Traceback (most recent call last):
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/integrations/excepthook.py", line 61, in sentry_sdk_excepthook
sentry-self-hosted-web-1  |     hub.capture_event(event, hint=hint)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/hub.py", line 338, in capture_event
sentry-self-hosted-web-1  |     rv = client.capture_event(event, hint, scope)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/client.py", line 474, in capture_event
sentry-self-hosted-web-1  |     self.transport.capture_event(event_opt)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/utils/sdk.py", line 361, in capture_event
sentry-self-hosted-web-1  |     self._capture_anything("capture_event", event)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/utils/sdk.py", line 393, in _capture_anything
sentry-self-hosted-web-1  |     if is_current_event_safe():
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/utils/sdk.py", line 148, in is_current_event_safe
sentry-self-hosted-web-1  |     for _, filename, _, _, _, _ in inspect.stack():
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/inspect.py", line 1526, in stack
sentry-self-hosted-web-1  |     return getouterframes(sys._getframe(1), context)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/inspect.py", line 1503, in getouterframes
sentry-self-hosted-web-1  |     frameinfo = (frame,) + getframeinfo(frame, context)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/inspect.py", line 1477, in getframeinfo
sentry-self-hosted-web-1  |     lines, lnum = findsource(frame)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/inspect.py", line 792, in findsource
sentry-self-hosted-web-1  |     module = getmodule(object, file)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/inspect.py", line 754, in getmodule
sentry-self-hosted-web-1  |     os.path.realpath(f)] = module.__name__
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/posixpath.py", line 391, in realpath
sentry-self-hosted-web-1  |     path, ok = _joinrealpath(filename[:0], filename, {})
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/posixpath.py", line 425, in _joinrealpath
sentry-self-hosted-web-1  |     if not islink(newpath):
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/posixpath.py", line 166, in islink
sentry-self-hosted-web-1  |     try:
sentry-self-hosted-web-1  | KeyboardInterrupt
sentry-self-hosted-web-1  | Traceback (most recent call last):
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/integrations/excepthook.py", line 61, in sentry_sdk_excepthook
sentry-self-hosted-web-1  |     hub.capture_event(event, hint=hint)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/hub.py", line 338, in capture_event
sentry-self-hosted-web-1  |     rv = client.capture_event(event, hint, scope)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/client.py", line 474, in capture_event
sentry-self-hosted-web-1  |     self.transport.capture_event(event_opt)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/utils/sdk.py", line 361, in capture_event
sentry-self-hosted-web-1  |     self._capture_anything("capture_event", event)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/utils/sdk.py", line 393, in _capture_anything
sentry-self-hosted-web-1  |     if is_current_event_safe():
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/utils/sdk.py", line 148, in is_current_event_safe
sentry-self-hosted-web-1  |     for _, filename, _, _, _, _ in inspect.stack():
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/inspect.py", line 1526, in stack
sentry-self-hosted-web-1  |     return getouterframes(sys._getframe(1), context)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/inspect.py", line 1503, in getouterframes
sentry-self-hosted-web-1  |     frameinfo = (frame,) + getframeinfo(frame, context)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/inspect.py", line 1477, in getframeinfo
sentry-self-hosted-web-1  |     lines, lnum = findsource(frame)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/inspect.py", line 792, in findsource
sentry-self-hosted-web-1  |     module = getmodule(object, file)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/inspect.py", line 754, in getmodule
sentry-self-hosted-web-1  |     os.path.realpath(f)] = module.__name__
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/posixpath.py", line 391, in realpath
sentry-self-hosted-web-1  |     path, ok = _joinrealpath(filename[:0], filename, {})
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/posixpath.py", line 425, in _joinrealpath
sentry-self-hosted-web-1  |     if not islink(newpath):
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/posixpath.py", line 167, in islink
sentry-self-hosted-web-1  |     st = os.lstat(path)

**Comment by defp** [comment]
pip install django-csp
 
<img width="965" alt="image" src="https://github.com/getsentry/self-hosted/assets/612381/ffbf69c9-6596-43ff-bae6-90e7c1886679">

**Comment by hubertdeng123** [comment]
Interesting, is this something that you needed to add before 23.5.1 was installed correctly? If so, I don't see any harm in adding that, but I'm not able to repro
