### ISSUE TITLE
If you select personnel in the dev member field in jira iusse, an error will be reported: could not find usernames

### ISSUE THREAD

**Issue by runtu666** [getsentry/self-hosted#2164]
### Self-Hosted Version

22.11.0

### CPU Architecture

x86_64

### Docker Version

20.10.21

### Docker Compose Version

v2.12.1

### Steps to Reproduce

1.click << jira server issue >>
2.select all required field
3.select personnel in the dev member field 
4.click  <<create issue>>

<img width="749" alt="image" src="https://github.com/getsentry/self-hosted/assets/32669202/98732539-bc6a-4fa4-9474-dc0abe5a7945">

### Expected Result

Created successfully

### Actual Result

<img width="657" alt="image" src="https://github.com/getsentry/self-hosted/assets/32669202/547d0ac3-b1d1-46d2-81d2-51de16c7ce9b">

**Comment by runtu666** [comment]
We found that the dev memeber field should be multi-choice, but the page can only be single-choice. We changed the curl request and changed this field to a json array and it worked. Please take a look at this bug

**Comment by hubertdeng123** [comment]
Seems like in the photo, it's trying to find a username for each character? Can you elaborate a little more? This may be a bug on the sentry repo if it isn't working as expected

**Comment by runtu666** [comment]
https://github.com/getsentry/self-hosted/assets/32669202/3e0ab162-d100-4cee-b3b3-cf3b6799db16

watch this screen recording

**Comment by runtu666** [comment]
@hubertdeng123

**Comment by runtu666** [comment]
@hubertdeng123
