### ISSUE TITLE
Project events are not showing after using external redis

### ISSUE THREAD

**Issue by riskirinando** [getsentry/self-hosted#2165]
### Self-Hosted Version

23.3.1

### CPU Architecture

x86_64

### Docker Version

23.0.2

### Docker Compose Version

2.18.1

### Steps to Reproduce

Hello,

I just split the Redis service from the default container to our external Redis instance. I saw it looks fine without any error logs, but the data and event in our project seems not working (empty). I just followed the instruction in this link:

https://forum.sentry.io/t/i-want-to-use-external-redis-on-sentry-on-premise-20-x/12062

when i try to edit the snuba config file, the folder does not exist from the sentry repo that I have cloned from this link below:

https://github.com/getsentry/self-hosted

### Expected Result

The data and events from project is showing correctly.

### Actual Result

<img width="1277" alt="image" src="https://github.com/getsentry/self-hosted/assets/79828572/5ec86609-9026-4eb6-b7b8-414c56a678da">
no error logs and the data is not showing.

**Comment by hubertdeng123** [comment]
The snuba config file should be in the snuba container. This is the file that is relevant for you:
https://github.com/getsentry/snuba/blob/a882046c0b72f8f6b6748588498236e018a57b5b/snuba/settings/settings_self_hosted.py

You can change the env variables as you see fit in the `docker-compose.yml` file for your snuba containers

**Comment by riskirinando** [comment]
hi @hubertdeng123 

I have known about the file but I am just a bit confused about where I can edit that file. So I should change the Redis host inside the Snuba container or from the outside file? because i can't edit the file inside the Snuba container because of this error
<img width="187" alt="image" src="https://github.com/getsentry/self-hosted/assets/79828572/617e3b3b-cf71-4ef1-ad0b-148b3d6f0a2d">

**Comment by riskirinando** [comment]
hi @hubertdeng123 

i just edited the `settings_self_hosted.py` and `settings_docker.py` directly inside to the all Snuba containers and adjust them with my EC2 Redis IP. However, the events and graphics are still not showing. 

any advise with this?
