### ISSUE TITLE
source-maps only works with sentry-cli (I'm trying to use esbuild)

### ISSUE THREAD

**Issue by caioricciuti** [getsentry/self-hosted#2166]
### Self-Hosted Version

Sentry 23.5.1

### CPU Architecture

x86_64

### Docker Version

24.0.1

### Docker Compose Version

1.29.1

### Steps to Reproduce

Use `esbuild` to upload source-maps (react-app) 
https://docs.sentry.io/platforms/node/guides/serverless-cloud/sourcemaps/uploading/esbuild/
<img width="1069" alt="image" src="https://github.com/getsentry/self-hosted/assets/63287675/c1aad13e-f4c4-409c-800b-df2a4af971d9">

### Expected Result

After running the build of my app, I would like to get the source-maps of my release. It works when I use sentry-cli but I need to use `esbuild` in this project. 

### Actual Result

After the build the expected result is to see my source maps on sentry. (under artifacts) but I always see -1 when using esbuild plugin. The weird thing is that when I use `sentry-cli` it all works and all source-maps are uploaded correctly. 

`https://sentry.example.com/settings/test-project-react/projects/app-test-react/source-maps/` 

<img width="1076" alt="Screenshot 2023-05-26 at 15 28 41" src="https://github.com/getsentry/self-hosted/assets/63287675/46b6f09b-bff1-4486-b1ed-90775b542eab">

**Comment by hubertdeng123** [comment]
That's super interesting, is there anything in your docker logs that may indicate that the sourcemaps uploaded using `esbuild` is failing? Also, are you able to reproduce this in SaaS?

**Comment by caioricciuti** [comment]
Hey @hubertdeng123 thank you for your interest! 

1. I didn't saw any off logs, so don't think there is anything wrong. 
2. In SaaS it works, that's what is driving me crazy. 

One side note that's also very interesting is that when I use `vite` to build it works on my `self-hosted` .

![Screenshot 2023-05-31 at 08 39 42](https://github.com/getsentry/self-hosted/assets/63287675/8a6d075a-bd94-4578-a17e-11871b6e6593)

any insights? Thanks have a good one!

**Comment by caioricciuti** [comment]
Ahhh! I got it, not sure why! But the `/**` at:
```
uploadLegacySourcemaps: './public/**',
```
didn't got the files (`vite` does). So from `uploadLegacySourcemaps: './public/**` to `uploadLegacySourcemaps: './public/**/*.*'` all works!
