### ISSUE TITLE
nginx config overwrite

### ISSUE THREAD

**Issue by liscuate** [getsentry/self-hosted#2167]
### Problem Statement

It seems like Sentry overwrites my own nginx configuration. Would it be possible to either:

1) Use our own configuration so our programs can still be behind reverse proxies.
2) Put our own configuration inside Sentry's one so it can run that way.

**Comment by liscuate** [comment]
It seems that if you disable the Apache2. You can run your own NGINX together with the one Sentry uses. Haven't tested the connections from outside the network though!

**Comment by hubertdeng123** [comment]
We currently are running a version of self-hosted Sentry that runs our own nginx config along with the one that comes in self-hosted so I don't think this should be an issue. Keep me updated on whether that works for you after disabling Apache2

**Comment by liscuate** [comment]
It seems as if Apache2 is a dependency of the install.sh, can not 100% confirm this but after running that script, it install apache2 and apache2 got bound to port 80, causing NGINX to be unable to bind.
