### ISSUE TITLE
Interupted index update

### ISSUE THREAD

**Issue by Fouzyyyy** [getsentry/self-hosted#2178]
### Self-Hosted Version

23.5.0

### CPU Architecture

x86_64

### Docker Version

20.10.13

### Docker Compose Version

2.6.0

### Steps to Reproduce

To update the Sentry installation, we run the below commands:

1. sudo su
2. cd /sentry/self-hosted
3. git pull origin master
4. ./install.sh --skip-commit-check

While updating, we accidentally interrupted the index update of the Postgres db. We run `./install.sh --skip-commit-check` to continue the whole Sentry update.

### Expected Result

How can we see/find symptoms of a corrupt index?

### Actual Result

Currently our Sentry installation runs properly under 23.6.0. We only want to know if our index is corrupt.

**Comment by hubertdeng123** [comment]
Oof, you can run some queries on your db to look for invalid indexes but hopefully everything is fine. This article has more details on that here:
https://medium.com/carwow-product-engineering/problems-with-concurrent-postgres-indexes-and-how-to-solve-them-c57f7656c852#:~:text=How%20can%20I%20detect%20invalid,indisvalid%20%3D%20false%20AND%20pg_index.

**Comment by Fouzyyyy** [comment]
@hubertdeng123 thanks a lot, the article above definitely help. For those who in the future have a similar question, you need to run the following query inside the postgres container: 

`SELECT * FROM pg_class, pg_index WHERE pg_index.indisvalid = false AND pg_index.indexrelid = pg_class.oid;`

If the output of the above query is empty then there are no invalid indexes.

Source: https://medium.com/carwow-product-engineering/problems-with-concurrent-postgres-indexes-and-how-to-solve-them-c57f7656c852#:~:text=How%20can%20I%20detect%20invalid,indisvalid%20%3D%20false%20AND%20pg_index

**Comment by hubertdeng123** [comment]
thanks for following up here!
