### ISSUE TITLE
The trace you are looking for was not found.

### ISSUE THREAD

**Issue by hariprasadiit** [getsentry/self-hosted#2183]
### Self-Hosted Version

23.5.2

### CPU Architecture

x86_64

### Docker Version

20.10.23

### Docker Compose Version

2.15.1

### Steps to Reproduce

Help needed in debugging this issue.

### Expected Result

Trace of any event to be shown.

### Actual Result

Actual error from chrome network tab

`detail:  "Internal error. Your query failed to run."`

Logs at the time of this error

```
sentry-self-hosted-web-1                                       | /usr/local/lib/python3.8/site-packages/sentry/models/avatars/base.py:74: DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
sentry-self-hosted-web-1                                       |   image = image.resize((size, size), Image.LANCZOS)
sentry-self-hosted-web-1                                       | /usr/local/lib/python3.8/site-packages/sentry/web/frontend/base.py:662: ResourceWarning: unclosed file <_io.BufferedReader name='/data/files/7d/797e/8c890a4b66b6d2a25510ba2501'>
sentry-self-hosted-web-1                                       |   photo_file = avatar.get_cached_photo(size)
sentry-self-hosted-web-1                                       | ResourceWarning: Enable tracemalloc to get the object allocation traceback
sentry-self-hosted-web-1                                       | Traceback (most recent call last):
sentry-self-hosted-web-1                                       |   File "/usr/local/lib/python3.8/site-packages/sentry/snuba/referrer.py", line 630, in validate_referrer
sentry-self-hosted-web-1                                       |     raise Exception(error_message)
sentry-self-hosted-web-1                                       | Exception: referrer api.trace-view.count-performance-issues is not part of Referrer Enum
sentry-self-hosted-web-1                                       | 12:00:26 [WARNING] sentry.snuba.referrer: referrer api.trace-view.count-performance-issues is not part of Referrer Enum
sentry-self-hosted-web-1                                       | 12:00:26 [INFO] sentry.access.api: api.access (method='GET' view='sentry.api.endpoints.organization_events_trace.OrganizationEventsTraceEndpoint' response=200 user_id='1' is_app='None' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/organizations/vizmo/events-trace/296452efc9894d7ea176cfbb54554eab/' caller_ip='172.23.0.36' user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 13_3_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/113.0.0.0' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.20128297805786133 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
sentry-self-hosted-web-1                                       | 12:00:26 [INFO] sentry.access.api: api.access (method='GET' view='sentry.api.endpoints.organization_events_trace.OrganizationEventsTraceMetaEndpoint' response=500 user_id='1' is_app='None' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/organizations/vizmo/events-trace-meta/296452efc9894d7ea176cfbb54554eab/' caller_ip='172.23.0.36' user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 13_3_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/113.0.0.0' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.23880314826965332 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
sentry-self-hosted-web-1                                       | 12:00:26 [ERROR] django.request: Internal Server Error: /api/0/organizations/vizmo/events-trace-meta/296452efc9894d7ea176cfbb54554eab/ (status_code=500 request=<WSGIRequest: GET '/api/0/organizations/vizmo/events-trace-meta/296452efc9894d7ea176cfbb54554eab/?end=2023-06-02T23%3A55%3A21.508&project=-1&query=&start=2023-06-01T23%3A55%3A21.508'>)
```

Recently I've fixed issues with Kafka out of range errors

One more thing we've noticed is that, at the same time notifications stopped working. We're no longer receiving error event related email notifications

This issue started occurring after upgrading to 23.5.1 from 23.3.1

**Comment by hariprasadiit** [comment]
`https://sentry.vizmo.dev/api/0/organizations/vizmo/events-trace/a39313f97a164153a59c94c070a49b1a/?detailed=1&end=2023-06-03T00:34:20.449&project=-1&query=&start=2023-06-02T00:34:20.449`

this request is successful while

`https://sentry.vizmo.dev/api/0/organizations/vizmo/events-trace-meta/a39313f97a164153a59c94c070a49b1a/?end=2023-06-03T00:34:20.449&project=-1&query=&start=2023-06-02T00:34:20.449` request is failing

**Comment by hubertdeng123** [comment]
Just to confirm, you're getting a 500 error upon clicking into any issue? Can you check snuba logs to see if there's anything useful there?

**Comment by hariprasadiit** [comment]
I can see all the issue details, however when I click on `View full trace` to view trace of the relevant request, it shows not found error message.

When sentry tries to load `events-trace-meta` it fails but `events-trace` loads successfully as mentioned in the above comment

<img width="1040" alt="Screenshot 2023-06-03 at 12 35 16 PM" src="https://github.com/getsentry/self-hosted/assets/1260204/bae72407-b73f-4c3d-b8ea-298ec69645aa">
<img width="1204" alt="Screenshot 2023-06-03 at 12 35 23 PM" src="https://github.com/getsentry/self-hosted/assets/1260204/323fc5f2-5f7f-46ca-9fe6-9513cec3e652">

**Comment by hubertdeng123** [comment]
Can you check your clickhouse db manually to see if the table `search_issues_local_v2` exists? Looks like it was part of a snuba migration that was added a few months ago.

**Comment by hariprasadiit** [comment]
> Can you check your clickhouse db manually to see if the table `search_issues_local_v2` exists? Looks like it was part of a snuba migration that was added a few months ago.

Yes, the table was missing.

> I had the same issue, you need to force migration in the snuba because for some reason it's not executed by default even if the storage set `"search_issues"` is specified in the config. You can force this migration group using:
> 
> ```
> snuba migrations migrate -g search_issues --force
> ```

This fixed the issue.

Thanks for the help!!
