### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by yudong5740** [getsentry/self-hosted#2184]
### Environment

self-hosted

### Steps to Reproduce

My version is 21.10.0

http://****:9000/api/3/envelope/?sentry_key=ac3e2aa6d71041058386b58ef1fab76b&sentry_version=7&sentry_client=sentry.javascript.vue%2F7.45.0

### Expected Result

{id:******}

### Actual Result

Return Results ：Request URL: http://*****:9000/api/3/envelope/?sentry_key=ac3e2aa6d71041058386b58ef1fab76b&sentry_version=7&sentry_client=sentry.javascript.vue%2F7.45.0
Request Method: POST
Status Code: 403 Forbidden
Referrer Policy: origin

Return Results：
CSRF verification failed
The security token does not exist or is invalid
If you constantly see this issue, you can try the following steps:
Clear cookies (at least cookies under the Sentry domain name).

Reload the page you are attempting to submit (do not resubmit data).

Reenter the information and resubmit the form.

Read more about CSRF on Wikipedia.

### Product Area

Unknown

**Comment by chadwhitacre** [comment]
Interesting that multiple people are hitting this. We're gonna need a lot more info to help you all debug. As @hubertdeng123 asked, are you using the stock Docker Compose version of self-hosted or something derivative? What's your network topology?

**Comment by LeanderD** [comment]
Same issue here. Also using the Docker compose version of self-hosted.
It was working before I switched to https.

**Comment by hubertdeng123** [comment]
It's difficult to tell what might be going wrong without additional info. Are there any logs that are useful?

**Comment by djoeycl** [comment]
We got an similar problem.

We got it on the url:
/api/0/internal/options/
response is 403 forbidden

Tried to change ratelimit from 1000 to 2000, but it cant be saved.

Version:
Sentry 23.7.0.dev 02f14632

Nginx 9200 proxied to https

Which logs would be useful for you?

**Comment by hubertdeng123** [comment]
I suspect this may be a proxying issue since it seems that multiple people are only hitting this when using https. Is there any logs in your nginx or web containers that you can share?

**Comment by djoeycl** [comment]
> 

I tried with an VPN that is running on this server, so i can access it on port 9000.
Still /api/0/internal/options/ returns an 403 forbidden without any info.

How can i enable the logs for nginx on the docker image?

**Comment by LeanderD** [comment]
Sorry for my late reply.

The error I'm seeing in the logs is:
2023-07-08T05:28:45.630030Z ERROR relay_server::actors::upstream: authentication encountered error error=could not send request to upstream error.sources=[error sending request for url (http://web:9000/api/0/relays/register/challenge/): error trying to connect: tcp connect error: Connection refused (os error 111), error trying to connect: tcp connect error: Connection refused (os error 111), tcp connect error: Connection refused (os error 111), Connection refused (os error 111)]

I did change all the settings to switch to https, but somehow it's still using http internally.

**Comment by hubertdeng123** [comment]
> How can i enable the logs for nginx on the docker image?
You can just use `docker compose logs web` to find the logs

> I did change all the settings to switch to https, but somehow it's still using http internally.
Did you try to set a `system.url-prefix`?

**Comment by devops-tavus** [comment]
I am also facing same issue but still didn't get any solution 
I installed sentry on Ubuntu not in docker directly on ec2

**Comment by LeanderD** [comment]
> Did you try to set a `system.url-prefix`?

I think that's what I did, but I'm not sure.

I did manage to get everything working on https now.
No idea what I did differently this time, but somehow it just worked and now everything is running on https like it should.
No issues at all.

I did remove "everything" and started over from scratch. I thought I deleted everything using the nuclear option from the docs (https://develop.sentry.dev/self-hosted/troubleshooting/#nuclear-option), but after cloning the repo and installing Sentry the data from previous installs was still there.
This time Sentry is running on https though.

I wish I could tell you what I did wrong the previous times, but unfortunately I have no idea.
It's possible I tried setting `the system.url-prefix`. I'm sure I tried that at some point, but I'm also sure I didn't do that this time.

I just uncommented the lines for `SSL/TLS`  in `sentry.conf.py`, changed my nginx config and that's about it.

**Comment by hubertdeng123** [comment]
> I just uncommented the lines for SSL/TLS in sentry.conf.py, changed my nginx config and that's about it.

Well, thanks for the data point here. Glad to hear you got it working somehow

**Comment by kaustavb79** [comment]
> ### Environment
> self-hosted
> 
> ### Steps to Reproduce
> My version is 21.10.0
> 
> http://****:9000/api/3/envelope/?sentry_key=ac3e2aa6d71041058386b58ef1fab76b&sentry_version=7&sentry_client=sentry.javascript.vue%2F7.45.0
> 
> ### Expected Result
> {id:******}
> 
> ### Actual Result
> Return Results ：Request URL: http://*****:9000/api/3/envelope/?sentry_key=ac3e2aa6d71041058386b58ef1fab76b&sentry_version=7&sentry_client=sentry.javascript.vue%2F7.45.0 Request Method: POST Status Code: 403 Forbidden Referrer Policy: origin
> 
> Return Results： CSRF verification failed The security token does not exist or is invalid If you constantly see this issue, you can try the following steps: Clear cookies (at least cookies under the Sentry domain name).
> 
> Reload the page you are attempting to submit (do not resubmit data).
> 
> Reenter the information and resubmit the form.
> 
> Read more about CSRF on Wikipedia.
> 
> ### Product Area
> Unknown
> 
> ### Link
> _No response_
> 
> ### DSN
> _No response_
> 
> ### Version
> _No response_

If you are serving it from http:// schema then comment the SSL/TLS config mentioned below in **sentry.conf.py**

```code
###########
# SSL/TLS #
###########
# If you're using a reverse SSL proxy, you should enable the X-Forwarded-Proto
# header and enable the settings below
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SOCIAL_AUTH_REDIRECT_IS_HTTPS = True
# End of SSL/TLS settings
```

Save the file and restart docker: **systemctl restart docker**

**Comment by csvan** [comment]
In my case, the logs indicated this is a cookie issue:

```
 | 11:24:27 [WARNING] django.security.csrf: Forbidden (CSRF cookie not set.): /api/2/envelope (status_code=403 request=<WSGIRequest: POST '/api/2/envelope?
```

So this may give deeper insights to what is going wrong: https://forum.djangoproject.com/t/getting-forbidden-csrf-cookie-not-set-while-trying-to-login-to-django-admin-page/20645/11

**Comment by WilenChen** [comment]
same issue.

sentry-self-hosted-web-1  | 03:20:35 [WARNING] django.request: Forbidden: /api/0/internal/options/ (status_code=403 request=<WSGIRequest: PUT '/api/0/internal/options/'>)

**Comment by hubertdeng123** [comment]
@WilenChen That is an entirely different issue. That endpoint is internal and is used by admins. You are likely trying to access a page that only superusers can access.

**Comment by Erokos** [comment]
> > Did you try to set a `system.url-prefix`?
> 
> I think that's what I did, but I'm not sure.
> 
> I did manage to get everything working on https now. No idea what I did differently this time, but somehow it just worked and now everything is running on https like it should. No issues at all.
> 
> I did remove "everything" and started over from scratch. I thought I deleted everything using the nuclear option from the docs (https://develop.sentry.dev/self-hosted/troubleshooting/#nuclear-option), but after cloning the repo and installing Sentry the data from previous installs was still there. This time Sentry is running on https though.
> 
> I wish I could tell you what I did wrong the previous times, but unfortunately I have no idea. It's possible I tried setting `the system.url-prefix`. I'm sure I tried that at some point, but I'm also sure I didn't do that this time.
> 
> I just uncommented the lines for `SSL/TLS` in `sentry.conf.py`, changed my nginx config and that's about it.

Hi we're experiencing a similar issue with self-hosted sentry versions 24.1.0 and 24.1.1 deployed via the install script and docker-compose:
`[WARNING] django.security.csrf: Forbidden (CSRF token missing.): /api/1/envelope/ (status_code=403 request=<WSGIRequest: POST '/api/1/envelope/?sentry_key=<REDACTED>&sentry_version=7&sentry_client=sentry.javascript.react%2F7.98.0'>)`

how did you change your nginx.conf? This info would be much appreciated.

**Comment by azaslavsky** [comment]
Does adding [this](https://github.com/getsentry/self-hosted/pull/2762/files) (uncommented, and with your domain names) to your sentry.conf.py help? You'll need to restart the server.

**Comment by Erokos** [comment]
Thanks, in the end it was due to something else and we managed to solve the issue. Nevertheless this is good to know and thank you for the info.

**Comment by axelgenus** [comment]
I've been struggling with this for two hours. The CSRF_TRUSTED_ORIGINS array MUST INCLUDE the schema!

```
CSRF_TRUSTED_ORIGINS = ["example.com", "127.0.0.1:9000"]
```

should be

```
CSRF_TRUSTED_ORIGINS = ["https://www.example.com", "http://127.0.0.1:9000"]
```

**Comment by chadwhitacre** [comment]
Thanks for pushing through and posting back @axelgenus. 🙌 

@Sweet-KK @theremoon-j Does [the above](https://github.com/getsentry/self-hosted/issues/2184#issuecomment-1952296188) help with your comments at https://github.com/getsentry/self-hosted/issues/2751#issuecomment-1952183896?

**Comment by caseyduquettesc** [comment]
If you're willing to accept the security risks, either because you have other infrastructure in front of sentry or because you just don't care, I found this to be the easiest way forward.

```
CSRF_TRUSTED_ORIGINS = [
    "http://*",
    "https://*",
]
```

**Comment by erlangparasu** [comment]
> I've been struggling with this for two hours. The CSRF_TRUSTED_ORIGINS array MUST INCLUDE the schema!
> 
> ```
> CSRF_TRUSTED_ORIGINS = ["example.com", "127.0.0.1:9000"]
> ```
> 
> should be
> 
> ```
> CSRF_TRUSTED_ORIGINS = ["https://www.example.com", "http://127.0.0.1:9000"]
> ```

Thanks!

**Comment by bukovjanmic** [comment]
In our experience, this started around Sentry 24.1 with the introduction of Django 4.

We are struggling with this as well and so far we are only partially succcessful to work around it.

There seems to be multiple issues how Sentry/Relay/Nginx handle the request for Sentry.

First, we are running Sentry on Openshift, adopting docker-compose approach. So the chain is (Web browser (Sentry application) -> Openshift default ingress (HA Proxy based, HTTPS with edge termination) -> Nginx (based on Docker compose, HTTP, port 80) -> Relay (HTTP, port 3000) -> Sentry (HTTP, port 9000).

1. Relay in proxy mode changes Origin header

When Relay is in proxy mode or in managed mode but with processing disabled, Relay passes the request to Sentry (aka web container). By doing this it changes the Origin header by adding a slash. So Origin:

https://sentry-test.example.com

becomes

https://sentry-test.example.com/

Since in case of non-wildcard domains in CSRF_TRUSTED_ORIGINS middleware Django does an exact match, you need to put both, the slash variant because of Relay and non-slash variant because of everything else (e.g. Sentry frontend).

So you need this, although it is not according to specification:

    CSRF_TRUSTED_ORIGINS = ["https://sentry-test.example.com", "https://sentry-test.example.com/"]

Another workaround is to use wildcards in CSRF_TRUSTED_ORIGINS, e.g. https://*.example.com, as in this case, Django parses the URL and throws away the slash for you.

2. Cookie must be set to what Sentry actually listens on

If Sentry is edge terminated (this is the case of docker-compose here), set CSRF_COOKIE_SECURE = False, as Sentry itself is non-HTTPS. If set to secure, the cookie is set but not visible to Django and you get "403 - Cookie not set" error.

3. Sentry SDK does not send X-Csrftoken

While normal requests from Sentry frontend do send this header (for example when posting a form with some configuration), Sentry SDK does not (the /api/1/envelope calls). Django tries to compare the CSRF cookie with the value of this token (https://github.com/django/django/blob/86b548a59bce88a274daa17f22b59ce63282d7ba/django/middleware/csrf.py#L386), and this is why you see:

07:51:19 [WARNING] django.security.csrf: Forbidden (CSRF cookie not set.): /api/1/envelope/ (status_code=403 request=<WSGIRequest: POST '/api/1/envelope/'>)
07:51:19 [INFO] sentry.access.api: api.access (method='POST' view='django.views.generic.base.RedirectView' response=403 user_id='None' is_app='None' token_type='None' is_frontend_request='False' organization_id='None' ...

e.g. Sentry itself cannot report its performance metrics via SDK in case Relay is not processing the requests.

The only workaround that we came up with so far is to use Relay to do the API processing (as is the case with docker-compose), i.e. run it in default managed mode. Beware, there is another gotcha, the code for automatic determining INTERNAL_SYSTEM_IPS is not bulletproof and it is better to explicitly state the network and mask of your environment (in our case, the automatic code determined lesser netmask than reality and we had a situation where 2 of 3 relay instances were working and 1 was rejected depending on IP address each instance got assigned).

With the above setup the Relay seems to process the transactions/events, however, it seems to be throwing away the envelopes for Sentry "internal" project, therefore we do not see any transactions for Sentry itself. 

Relevant Relay logs:

2024-07-15T07:54:00.873182Z TRACE relay_server::services::cogs: recording measurement: CogsMeasurement { resource: Relay, feature: Sessions, value: Time(124.692µs) }
2024-07-15T07:54:02.559286Z DEBUG request{method=POST uri=/api/1/envelope/?sentry_key=289ed3abb4e940cbb126316b016b9674&sentry_version=7&sentry_client=sentry.javascript.react%2F8.9.2 version=HTTP/1.1}: tower_http::trace::on_request: started processing request
2024-07-15T07:54:02.559458Z DEBUG request{method=POST uri=/api/1/envelope/?sentry_key=289ed3abb4e940cbb126316b016b9674&sentry_version=7&sentry_client=sentry.javascript.react%2F8.9.2 version=HTTP/1.1}: tower_http::trace::on_response: finished processing request latency=0 ms status=200
2024-07-15T07:54:02.559569Z TRACE relay_server::services::processor: Processing client_report group
2024-07-15T07:54:02.559604Z DEBUG relay_server::utils::managed_envelope: dropped envelope: rate limited

However, in our case, transactions for "internal" project were not there in older version of Sentry as well (version 23.4.0), so it is either another bug or a feature, we will investigate this further.

**Comment by amoghthefword** [comment]
> In our experience, this started around Sentry 24.1 with the introduction of Django 4.
> 
> We are struggling with this as well and so far we are only partially succcessful to work around it.
> 
> There seems to be multiple issues how Sentry/Relay/Nginx handle the request for Sentry.
> 
> First, we are running Sentry on Openshift, adopting docker-compose approach. So the chain is (Web browser (Sentry application) -> Openshift default ingress (HA Proxy based, HTTPS with edge termination) -> Nginx (based on Docker compose, HTTP, port 80) -> Relay (HTTP, port 3000) -> Sentry (HTTP, port 9000).
> 
> 1. Relay in proxy mode changes Origin header
> 
> When Relay is in proxy mode or in managed mode but with processing disabled, Relay passes the request to Sentry (aka web container). By doing this it changes the Origin header by adding a slash. So Origin:
> 
> https://sentry-test.example.com
> 
> becomes
> 
> https://sentry-test.example.com/
> 
> Since in case of non-wildcard domains in CSRF_TRUSTED_ORIGINS middleware Django does an exact match, you need to put both, the slash variant because of Relay and non-slash variant because of everything else (e.g. Sentry frontend).
> 
> So you need this, although it is not according to specification:
> 
> ```
> CSRF_TRUSTED_ORIGINS = ["https://sentry-test.example.com", "https://sentry-test.example.com/"]
> ```
> 
> Another workaround is to use wildcards in CSRF_TRUSTED_ORIGINS, e.g. https://*.example.com, as in this case, Django parses the URL and throws away the slash for you.
> 
> 2. Cookie must be set to what Sentry actually listens on
> 
> If Sentry is edge terminated (this is the case of docker-compose here), set CSRF_COOKIE_SECURE = False, as Sentry itself is non-HTTPS. If set to secure, the cookie is set but not visible to Django and you get "403 - Cookie not set" error.
> 
> 3. Sentry SDK does not send X-Csrftoken
> 
> While normal requests from Sentry frontend do send this header (for example when posting a form with some configuration), Sentry SDK does not (the /api/1/envelope calls). Django tries to compare the CSRF cookie with the value of this token (https://github.com/django/django/blob/86b548a59bce88a274daa17f22b59ce63282d7ba/django/middleware/csrf.py#L386), and this is why you see:
> 
> 07:51:19 [WARNING] django.security.csrf: Forbidden (CSRF cookie not set.): /api/1/envelope/ (status_code=403 request=<WSGIRequest: POST '/api/1/envelope/'>) 07:51:19 [INFO] sentry.access.api: api.access (method='POST' view='django.views.generic.base.RedirectView' response=403 user_id='None' is_app='None' token_type='None' is_frontend_request='False' organization_id='None' ...
> 
> e.g. Sentry itself cannot report its performance metrics via SDK in case Relay is not processing the requests.
> 
> The only workaround that we came up with so far is to use Relay to do the API processing (as is the case with docker-compose), i.e. run it in default managed mode. Beware, there is another gotcha, the code for automatic determining INTERNAL_SYSTEM_IPS is not bulletproof and it is better to explicitly state the network and mask of your environment (in our case, the automatic code determined lesser netmask than reality and we had a situation where 2 of 3 relay instances were working and 1 was rejected depending on IP address each instance got assigned).
> 
> With the above setup the Relay seems to process the transactions/events, however, it seems to be throwing away the envelopes for Sentry "internal" project, therefore we do not see any transactions for Sentry itself.
> 
> Relevant Relay logs:
> 
> 2024-07-15T07:54:00.873182Z TRACE relay_server::services::cogs: recording measurement: CogsMeasurement { resource: Relay, feature: Sessions, value: Time(124.692µs) } 2024-07-15T07:54:02.559286Z DEBUG request{method=POST uri=/api/1/envelope/?sentry_key=289ed3abb4e940cbb126316b016b9674&sentry_version=7&sentry_client=sentry.javascript.react%2F8.9.2 version=HTTP/1.1}: tower_http::trace::on_request: started processing request 2024-07-15T07:54:02.559458Z DEBUG request{method=POST uri=/api/1/envelope/?sentry_key=289ed3abb4e940cbb126316b016b9674&sentry_version=7&sentry_client=sentry.javascript.react%2F8.9.2 version=HTTP/1.1}: tower_http::trace::on_response: finished processing request latency=0 ms status=200 2024-07-15T07:54:02.559569Z TRACE relay_server::services::processor: Processing client_report group 2024-07-15T07:54:02.559604Z DEBUG relay_server::utils::managed_envelope: dropped envelope: rate limited
> 
> However, in our case, transactions for "internal" project were not there in older version of Sentry as well (version 23.4.0), so it is either another bug or a feature, we will investigate this further.

We are facing similar issue except we have nginx.
updated the nginx conf file with the location and server directives 
               location /api/store/ {
                        proxy_pass http://relay;
                }

added 

            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type' always;
            
but nothing seems to resolve the issue.

**Comment by amoghthefword** [comment]
@bukovjanmic 

We are facing similar issue except we have nginx.
updated the nginx conf file with the location and server directives
location /api/store/ {
proxy_pass http://relay/;
}

added

        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type' always;
        
but nothing seems to resolve the issue.

**Comment by bukovjanmic** [comment]
Yes. In this case this actually does not matter much. The X-Csrftoken must be sent by the browser application.

We experimted with several architecture, for example, from default to effectively reduced to minimum:

Browser (Sentry) -> Openshift Ingress (default router, HA Proxy, HTTPS) -> Nginx (HTTP, port 80) -> Relay (HTTP, port 3000) -> Sentry web (HTTP, port 9000)
Browser (Sentry) -> Openshift Ingress (default router, HA Proxy, HTTPS) -> Nginx (HTTP, port 80) -> Sentry web (HTTP, port 9000)
Browser (Sentry) -> Openshift Ingress (default router, HA Proxy, HTTPS) -> Sentry web (HTTP, port 9000)

but the result is the same, which is expected - Nginx and Relay are not related to this issue, as they just forward the X-Csrftoken if present (and it is not).

I wonder how it is meant to work, as I suspect that the Sentry SDK just produces POST requests to the API endpoint, therefore it will not have and cookie and also may not know the value to send in X-Csrftoken. But it is just my guess.

**Comment by bukovjanmic** [comment]
Small about about point 2: This is not entirely true. The real issue is that Relay does not forward CSRF cookie to Sentry at all, so unless API endpoint is exempt from CSRF in Djanog, Relay in proxy mode will not work.

**Comment by gm-thawani** [comment]
Did anyone manage to solve it? Self hosted version 24.7.0 and CSRF persists.
![image](https://github.com/user-attachments/assets/f8d3dda0-b31b-4bcd-826f-a5d68b4ab1f6)

**Comment by bukovjanmic** [comment]
You need either set up system.url-prefix to the URL where the browser sees the application (without slash at the end), or set it in Sentry itself (in the Admin area of configuration), or set CSRF_TRUSTED_ORIGINS in sentry.conf.py, again to full Sentry URL with protocol but without slash at the end, e.g. 

CSRF_TRUSTED_ORIGINS = ["https://sentry.mydomain.com"]

Sentry will work, but Relay in proxy mode will not.

**Comment by wonderGames** [comment]
I also encountered this problem, have you solved it?

I downloaded the self hosted-24.7.0 project and modified the system.url prefix of sentry/config.yml= http://192.168.100.1:9001 If the web. ports of docker-compose.yml is 9001:9000, then using Vue's initialization script will result in a 403 issue.

I also used the above solution and tried to modify the CSRF_TYSTED-ORIGINS of sentry/center. conf. py=[“http://192.168.100.1:9001 ", " http://192.168.100.1:9001/"] The problem still exists.

I have tried using "@ entry/vue": "7.118.0" and "@ entry/vue": "^ 8.18.0" on the client side, but to no avail.

**Comment by wonderGames** [comment]
> I also encountered this problem, have you solved it?
> 
> I downloaded the self hosted-24.7.0 project and modified the system.url prefix of sentry/config.yml= http://192.168.100.1:9001 If the web. ports of docker-compose.yml is 9001:9000, then using Vue's initialization script will result in a 403 issue.
> 
> I also used the above solution and tried to modify the CSRF_TYSTED-ORIGINS of sentry/center. conf. py=[“http://192.168.100.1:9001 ", " http://192.168.100.1:9001/"] The problem still exists.
> 
> I have tried using "@ entry/vue": "7.118.0" and "@ entry/vue": "^ 8.18.0" on the client side, but to no avail.

It's strange, as long as I use the default port and don't use a custom port, this problem won't occur anymore

**Comment by joshuarli** [comment]
What do your nginx configs look like? I think our example on the docs site is outdated (will fix). The repo's `nginx/nginx.conf` is what you want to use as reference.

**Comment by bukovjanmic** [comment]
Also, try to set env. variable SENTRY_LOG_LEVEL to DEBUG and restart the web container, usually you find in the logs what Django thinks is wrong with CSRF. You can also crosscheck this with the code, it is relatively straightforward: https://github.com/django/django/blob/main/django/middleware/csrf.py#L324

**Comment by wonderGames** [comment]
> 您的 nginx 配置是什么样的？我认为我们在文档站点上的示例已经过时了（将修复）。`nginx/nginx.conf`您要使用的参考资料是 repo。

I did not make any adjustments to this file：nginx/nginx.conf

```


user nginx;
worker_processes auto;

error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;


events {
	worker_connections 1024;
}


http {
	default_type application/octet-stream;

	log_format main '$remote_addr - $remote_user [$time_local] "$request" '
	'$status $body_bytes_sent "$http_referer" '
	'"$http_user_agent" "$http_x_forwarded_for"';

	access_log /var/log/nginx/access.log main;

	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	reset_timedout_connection on;

	keepalive_timeout 75s;

	gzip off;
	server_tokens off;

	server_names_hash_bucket_size 64;
	types_hash_max_size 2048;
	types_hash_bucket_size 64;
	client_body_buffer_size 64k;
	client_max_body_size 100m;

	proxy_http_version 1.1;
	proxy_redirect off;
	proxy_buffer_size          128k;
	proxy_buffers              4 256k;
	proxy_busy_buffers_size    256k;
	proxy_next_upstream error timeout invalid_header http_502 http_503 non_idempotent;
	proxy_next_upstream_tries 2;

	# Docker default address pools
	# https://github.com/moby/libnetwork/blob/3797618f9a38372e8107d8c06f6ae199e1133ae8/ipamutils/utils.go#L10-L22
	set_real_ip_from 172.17.0.0/16;
	set_real_ip_from 172.18.0.0/16;
	set_real_ip_from 172.19.0.0/16;
	set_real_ip_from 172.20.0.0/14;
	set_real_ip_from 172.24.0.0/14;
	set_real_ip_from 172.28.0.0/14;
	set_real_ip_from 192.168.0.0/16;
	set_real_ip_from 10.0.0.0/8;
	real_ip_header X-Forwarded-For;
	real_ip_recursive on;

	# Remove the Connection header if the client sends it,
	# it could be "close" to close a keepalive connection
	proxy_set_header Connection '';
	proxy_set_header Host $host;
	proxy_set_header X-Forwarded-For $remote_addr;
	proxy_set_header X-Forwarded-Proto $scheme;
	proxy_set_header X-Request-Id $request_id;
	proxy_read_timeout 30s;
	proxy_send_timeout 5s;

	upstream relay {
		server relay:3000;
		keepalive 2;
	}

	upstream sentry {
		server web:9000;
		keepalive 2;
	}

	server {
		listen 80;

		location /api/store/ {
			proxy_pass http://relay;
		}
		location ~ ^/api/[1-9]\d*/ {
			proxy_pass http://relay;
		}
		location ^~ /api/0/relays/ {
			proxy_pass http://relay;
		}
		location / {
			proxy_pass http://sentry;
		}
		location /_static/ {
			proxy_pass http://sentry;
			proxy_hide_header Content-Disposition;
		}
	}
}


```

**Comment by gm-thawani** [comment]
> You need either set up system.url-prefix to the URL where the browser sees the application (without slash at the end), or set it in Sentry itself (in the Admin area of configuration), or set CSRF_TRUSTED_ORIGINS in sentry.conf.py, again to full Sentry URL with protocol but without slash at the end, e.g.
> 
> CSRF_TRUSTED_ORIGINS = ["https://sentry.mydomain.com"]
> 
> Sentry will work, but Relay in proxy mode will not.

How can I make it work? I am using self-hosted Sentry. I want to capture events using SentrySDK in .NET Core.

I keep getting this error `HttpTransport: Sentry rejected the envelope '4ef14562e2a64e47916c778694aef855'. Status code: "Forbidden".`

I found out the API for `api/hooks` for a project. If I paste that link directly, it would return CSRF 403 but if I append a slash `/` at the end, it works.

For example:

`https://mysentry.com/api/hooks/release/builtin/1/<some_id>` [NOT WORKING]
`https://mysentry.com/api/hooks/release/builtin/1/<some_id>/` [WORKING]

**Comment by joshuarli** [comment]
Sorry, still learning about self-hosted. The nginx/nginx.conf we have in here is used for the nginx inside docker compose. @wonderGames I doubt you're using nginx externally, so ignore what I said about the config.

**Comment by sashimi-houdini** [comment]
I couldn't figure this one out and after a day of frustration in the end I just went with [Bugsink](https://www.bugsink.com/) instead 😕

**Comment by rlucha-crowdstrike** [comment]
I was able to make this work by exposing nginx and pointing the dsn to the nginx port instead of the sentry-web service.
