### ISSUE TITLE
SourceMap upload works only via legacy upload

### ISSUE THREAD

**Issue by kadet1090** [getsentry/self-hosted#2186]
### Self-Hosted Version

23.5.2

### CPU Architecture

x86_64

### Docker Version

non-important (k8s cluster)

### Docker Compose Version

non-important (k8s cluster)

### Steps to Reproduce

This is almost (or exactly) the same issue as #2166.

Using sourcemap upload via webpack plugin with config like this:
```
SentryWebpackPlugin({
    url: "https://sentry.dev.pg.edu.pl",
    org: "cui",
    project: "forms-frontend",
    authToken: process.env.SENTRY_TOKEN,
    release: {
        name: `forms@${process.env.SNAP_VERSION}+${process.env.GIT_REVISION}`
    },
})
```

The plugin states that everything was uploaded correctly:
```
> Found 6 files
> Analyzing 6 sources
> Analyzing completed in 0.016s
> Adding source map references
> Bundling completed in 0.376s
> Bundled 6 files for upload
> Bundle ID: 07c79825-0360-5ecc-a26e-78ac2c751d58
> Optimizing completed in 0.007s
> Uploading completed in 0.648s
> Uploaded files to Sentry
> Processing completed in 0.076s
> File upload complete (processing pending on server)
> Organization: cui
> Project: forms-frontend
> Release: forms@asd5
> Dist: None
> Upload type: artifact bundle

Source Map Upload Report
  Minified Scripts
    ~/61715f90-1732-4996-af33-e14238914310-0.js (sourcemap at app.bfbe1007.js.map, debug id 61715f90-1732-4996-af33-e14238914310)
    ~/b42e28ee-a132-436c-ae8f-d67c2a79649b-2.js (sourcemap at 643.01bbf493.js.map, debug id b42e28ee-a132-436c-ae8f-d67c2a79649b)
    ~/c52c6acf-e7a2-4a25-9211-15bce74de27f-1.js (sourcemap at runtime.cb4982ec.js.map, debug id c52c6acf-e7a2-4a25-9211-15bce74de27f)
  Source Maps
    ~/61715f90-1732-4996-af33-e14238914310-0.js.map (debug id 61715f90-1732-4996-af33-e14238914310)
    ~/b42e28ee-a132-436c-ae8f-d67c2a79649b-2.js.map (debug id b42e28ee-a132-436c-ae8f-d67c2a79649b)
    ~/c52c6acf-e7a2-4a25-9211-15bce74de27f-1.js.map (debug id c52c6acf-e7a2-4a25-9211-15bce74de27f)
```

The sentry however shows -1 artifacts in the sourcemaps section of project settings, and correct number of artifacts in the "release" page. 

![image](https://github.com/getsentry/self-hosted/assets/747404/906093f0-690f-4c3c-9889-1b41cd8cf09c)
![image](https://github.com/getsentry/self-hosted/assets/747404/9037ab02-cd14-4fa8-ad40-3393a62d8fac)
(artifacts were uploaded 7 times, hence the 42)

Workaround for this issue is using the `uploadLegacySourcemaps` option.
```
            uploadLegacySourcemaps: {
                paths: [
                    "public/build/**/*.js",
                    "public/build/**/*.js.map"
                ],
            },
```

Then in the build log we can see (skipped some non-important stuff, full log at: https://bin.kadet.net/L9Ew): 
```
> Analyzing 3 sources
> Analyzing completed in 0.016s
> Rewriting sources
> Bundling completed in 0.378s
> Bundled 6 files for upload
> Bundle ID: 624b1404-9ab3-50de-bc6f-6a5f7a29942c
> Optimizing completed in 0.007s
> Uploading files...
> Bundling completed in 0.057s
> Bundled 3 files for upload
> Upload type: release bundle

Source Map Upload Report
  Minified Scripts
    ~/643.1963e3d9.js (sourcemap at 643.1963e3d9.js.map)
> Bundling completed in 0.311s
> Bundled 3 files for upload
> Upload type: artifact bundle

Source Map Upload Report
  Minified Scripts
    ~/2b9a289c-9bf4-462d-9924-414c29caa9f2-2.js (sourcemap at 643.1963e3d9.js.map, debug id 2b9a289c-9bf4-462d-9924-414c29caa9f2)
    ~/83eb93a8-e5d7-4569-9a54-b710e5e8848a-0.js (sourcemap at app.62ce5b99.js.map, debug id 83eb93a8-e5d7-4569-9a54-b710e5e8848a)
    ~/8efd0d8f-d54a-436a-9613-e17ce8c1de2a-1.js (sourcemap at runtime.4dc52807.js.map, debug id 8efd0d8f-d54a-436a-9613-e17ce8c1de2a)
  Source Maps
    ~/2b9a289c-9bf4-462d-9924-414c29caa9f2-2.js.map (debug id 2b9a289c-9bf4-462d-9924-414c29caa9f2)
    ~/83eb93a8-e5d7-4569-9a54-b710e5e8848a-0.js.map (debug id 83eb93a8-e5d7-4569-9a54-b710e5e8848a)
    ~/8efd0d8f-d54a-436a-9613-e17ce8c1de2a-1.js.map (debug id 8efd0d8f-d54a-436a-9613-e17ce8c1de2a)
> Upload type: release bundle
```

So there are 2 release bundles and 1 artifact bundle instead of only 1 artifact bundle in the non-legacy case.

As far as I was able to check for the non-legacy broken case:
1. upload correctly uploads file to the server (they can be found on the data volume)
2. uploaded file is a valid zip file containing mentioned files and additionally manifest.json with file list
3. the database table `sentry_artifactbundle` gets populated with valid data (this is done in the [assemble-artifacts](https://github.com/getsentry/sentry/blob/a062941dc2eef92ad9cc32023270339c753ec3df/src/sentry/tasks/assemble.py#L413-L489) task)
4. the database table `sentry_releasefile` is left untouched
5. there are no sings indicating that anything gone wrong, no logs, nothing

As far as I can tell, the `sentry_releasefile` table is the only source for the artifact counter and so -1 can be seen as the table is empty (based on [sentry:models/release.py](https://github.com/getsentry/sentry/blob/a062941dc2eef92ad9cc32023270339c753ec3df/src/sentry/models/release.py#L1247-L1257) and [sentry:api/endpoints/debug_files.py](https://github.com/getsentry/sentry/blob/db5de93b8374388cfd6e921e82e1707e9e2b054c/src/sentry/api/endpoints/debug_files.py#L443))

If this is intended behavior for the self hosted version it should be clearly documented. For now [the documentation](https://docs.sentry.io/platforms/javascript/guides/nextjs/sourcemaps/troubleshooting_js/uploading-without-debug-ids/#uploading-using-sentry-bundler-plugins-on-version-2x) says:

>If you are using a Sentry self-hosted or single-tenant on version 23.4.0 or lower, or you are using the Sentry JavaScript SDK on version 7.46.0 you will need to configure the bundler plugins with the release.uploadLegacySourcemaps option.

Which can be interpreted as `(Sentry self-hosted or single-tenant) on version 23.4.0 or lower` or `(Sentry self-hosted) or (single-tenant on version 23.4.0 or lower)`, where the former seems more plausible. If the second one is valid then it should be stated more clearly and also, the plugin should report an error instead of success.

If however this is not the issue with documentation and there is anything more that I could provide - I'd gladly do that. 
 

### Expected Result

Artifact count should be equal to 6

### Actual Result

Artifact count is equal to -1

**Comment by hubertdeng123** [comment]
Looks like you're using a k8s setup which we don't officially support, so may be more difficult to tell what might be going wrong here.

> Which can be interpreted as (Sentry self-hosted or single-tenant) on version 23.4.0 or lower or (Sentry self-hosted) or (single-tenant on version 23.4.0 or lower), where the former seems more plausible.

The former should be the case here. What version of the javascript SDK are you using?

**Comment by tron-billy** [comment]
I met the same issue. How to modify the field organizations:source-maps-debug-ids?

**Comment by tron-billy** [comment]
Hi, can u see the stack trace and the source code in issuses panel after you solve this problem? @kadet1090

**Comment by kadet1090** [comment]
> I met the same issue. How to modify the field organizations:source-maps-debug-ids?
You do this in the `sentry.conf.py` file. Basically you have to add another line containing `organizations:source-maps-debug-ids` to this list: https://github.com/getsentry/self-hosted/blob/master/sentry/sentry.conf.example.py#L258-L278

 > Hi, can u see the stack trace and the source code in issuses panel after you solve this problem? @kadet1090
Unfortunately for now I can neither confirm or deny this as I don't have any already existing clean issues related to releases with source maps uploaded. Due to holidays I'd be able to check this no sooner than monday. But given that the source maps are visible in sentry I'd suggest to use `sentry-cli sourcemaps explain <event id>` command - that should give you some useful information.

**Comment by hubertdeng123** [comment]
Thanks for digging into this @kadet1090 

> After enabling this flag, mentioned view in my instance changed to that from the SaaS version and now I can see uploaded bundles

Good find. I'm going to drop a line internally to see why the feature flag is not enabled by default, otherwise will put up a PR to include that flag in self-hosted

**Comment by hubertdeng123** [comment]
The feature flag is now enabled by default. https://github.com/getsentry/sentry/pull/50795

Going to close this issue now
