### ISSUE TITLE
smtp_syntax_error when sending email

### ISSUE THREAD

**Issue by nemurasu** [getsentry/self-hosted#2189]
### Self-Hosted Version

23.1.0

### CPU Architecture

x86_64

### Docker Version

20.10.12

### Docker Compose Version

2.2.3

### Steps to Reproduce

1. Install Sentry using Docker
2. Configure it to use default SMTP server
3. Try to send invite email

### Expected Result

Invitation sent

### Actual Result

Sentry is installed via docker-compos. Mail settings are still default - mail.host: 'smtp'
When sending an invitation in the logs of the smtp container, the following error occurs:
sentry-self-hosted-smtp-1  |    13   SMTP syntax error in "\026\003\001\002?\001?\001\374\003\003")\330\003\r)G\217{}\361\377!\304\274\242\316\301\374\350\301\263\222\263HO\343.:\371\v\367 \201\271\3601\367\342\340!H\2751\344j\005\363\357\255$\326\215U:\224\357\306\253\213\302\344\262\003L?>\023\002\023\003\023\001\300,\3000?\237\314\251\314\250\314\252\300+\300/?\236\300$\300(?k\300#\300'?g\300" H=sentry-self-hosted-worker-1.sentry-self-hosted_default [172.18.0.29] NUL character(s) present (shown as '?')
sentry-self-hosted-smtp-1  |    13 LOG: smtp_syntax_error MAIN
sentry-self-hosted-smtp-1  |    13   SMTP syntax error in "\300\024?9\300       \300\023?3?\235?\234?=?<?5?/?\377\001?\001u???  ?\007??\004smtp?\v?\004\003?\001\002?" H=sentry-self-hosted-worker-1.sentry-self-hosted_default [172.18.0.29] NUL character(s) present (shown as '?')
sentry-self-hosted-smtp-1  |    13 LOG: smtp_syntax_error MAIN
sentry-self-hosted-smtp-1  |    13   SMTP syntax error in "?\f?" H=sentry-self-hosted-worker-1.sentry-self-hosted_default [172.18.0.29] NUL character(s) present (shown as '?')
sentry-self-hosted-smtp-1  |    13 LOG: smtp_syntax_error MAIN
sentry-self-hosted-smtp-1  |    13   SMTP syntax error in "?\035?\027?\036?\031?\030?#???\026???\027???\r?*?(\004\003\005\003\006\003\b\007\b\b\b       \b" H=sentry-self-hosted-worker-1.sentry-self-hosted_default [172.18.0.29] NUL character(s) present (shown as '?')
sentry-self-hosted-smtp-1  |    13 LOG: MAIN REJECT
sentry-self-hosted-smtp-1  |    13   SMTP call from sentry-self-hosted-worker-1.sentry-self-hosted_default [172.18.0.29] dropped: too many syntax or protocol errors (last command was "?\035?\027?\036?\031?\030?#???\026???\027???\r?*?(\004\003\005\003\006\003\b\007\b\b\b       \b")

In the logs of the worker container at the same time, there are such errors:
sentry-self-hosted-worker-1  | ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)
sentry-self-hosted-worker-1  | 10:50:04 [ERROR] celery.app.trace: Task sentry.tasks.email.send_email[254c3c78-1d66-4bf6-891c-b93cedb0851e] raised unexpected: SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)') (data={'hostname': '02d6980c1bb8', 'id': '254c3c78-1d66-4bf6-891c-b93cedb0851e', 'name': 'sentry.tasks.email.send_email', 'exc': "SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)')", 'traceback': 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task\n    R = retval = fun(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 207, in _inner\n    reraise(*exc_info)\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 57, in reraise\n    raise value\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 202, in _inner\n    return f(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in protected_call__\n    return self.run(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/base.py", line 64, in _wrapped\n    result = func(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/email.py", line 73, in send_email\n    send_messages([message])\n  File "/usr/local/lib/python3.8/site-packages/sentry/utils/email/send.py", line 18, in send_messages\n    sent: int = connection.send_messages(messages)\n  File "/usr/local/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 103, in send_messages\n    new_conn_created = self.open()\n  File "/usr/local/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 63, in open\n    self.connection = self.connection_class(self.host, self.port, **connection_params)\n  File "/usr/local/lib/python3.8/smtplib.py", line 1048, in __init__\n    SMTP.__init(self, host, port, local_hostname, timeout,\n  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__\n    (code, msg) = self.connect(host, port)\n  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect\n    self.sock = self._get_socket(host, port, self.timeout)\n  File "/usr/local/lib/python3.8/smtplib.py", line 1056, in _get_socket\n    new_socket = self.context.wrap_socket(new_socket,\n  File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket\n    return self.sslsocket_class._create(\n  File "/usr/local/lib/python3.8/ssl.py", line 1040, in _create\n    self.do_handshake()\n  File "/usr/local/lib/python3.8/ssl.py", line 1309, in do_handshake\n    self._sslobj.do_handshake()\nssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)\n', 'args': '()', 'kwargs': "{'message': <django.core.mail.message.EmailMultiAlternatives object at 0x7f23f4e98910>}", 'description': 'raised unexpected', 'internal': False})

Sentry does not have any SSL settings, only nginx on the host that proxies to Sentry.
With what it can be connected? Python version not supported or something else? How can I fix it?

**Comment by hubertdeng123** [comment]
Something weird is going on here. Can you set the `SENTRY_LOG_LEVEL` to `DEBUG` to see if there are more verbose logs to use?
https://develop.sentry.dev/config/#logging

What port are you using? Are you setting any of these values in your config file?
```
# mail.use-tls: false
# mail.use-ssl: false
```

**Comment by nemurasu** [comment]
I added SENTRY_LOG_LEVEL=DEBUG to the .env file and restarted the sentry, but I don’t see any changes in the logs:
sentry-self-hosted-smtp-1  |    11 LOG: MAIN REJECT
sentry-self-hosted-smtp-1  |    11   SMTP protocol synchronization error (input sent without waiting for greeting): rejected connection from H=sentry-self-hosted-worker-1.sentry-self-hosted_default [172.18.0.26] input="\026\003\001\002"


sentry-self-hosted-worker-1  | ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)
sentry-self-hosted-worker-1  | 09:28:03 [ERROR] celery.app.trace: Task sentry.tasks.email.send_email[eb8a122f-3869-49c5-aa64-193f2af38d41] raised unexpected: SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)') (data={'hostname': '02d6980c1bb8', 'id': 'eb8a122f-3869-49c5-aa64-193f2af38d41', 'name': 'sentry.tasks.email.send_email', 'exc': "SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)')", 'traceback': 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task\n    R = retval = fun(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 207, in _inner\n    reraise(*exc_info)\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 57, in reraise\n    raise value\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 202, in _inner\n    return f(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__\n    return self.run(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/base.py", line 64, in _wrapped\n    result = func(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/email.py", line 73, in send_email\n    send_messages([message])\n  File "/usr/local/lib/python3.8/site-packages/sentry/utils/email/send.py", line 18, in send_messages\n    sent: int = connection.send_messages(messages)\n  File "/usr/local/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 103, in send_messages\n    new_conn_created = self.open()\n  File "/usr/local/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 63, in open\n    self.connection = self.connection_class(self.host, self.port, **connection_params)\n  File "/usr/local/lib/python3.8/smtplib.py", line 1048, in __init__\n    SMTP.__init__(self, host, port, local_hostname, timeout,\n  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__\n    (code, msg) = self.connect(host, port)\n  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect\n    self.sock = self._get_socket(host, port, self.timeout)\n  File "/usr/local/lib/python3.8/smtplib.py", line 1056, in _get_socket\n    new_socket = self.context.wrap_socket(new_socket,\n  File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket\n    return self.sslsocket_class._create(\n  File "/usr/local/lib/python3.8/ssl.py", line 1040, in _create\n    self.do_handshake()\n  File "/usr/local/lib/python3.8/ssl.py", line 1309, in do_handshake\n    self._sslobj.do_handshake()\nssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)\n', 'args': '()', 'kwargs': "{'message': <django.core.mail.message.EmailMultiAlternatives object at 0x7ff6488a7850>}", 'description': 'raised unexpected', 'internal': False})

**Comment by nemurasu** [comment]
SMTP settings from /manage/status/mail/
From Address
sentry@localhost
Host
smtp:25
Username
not set
Password
not set
STARTTLS?
No
SSL?
Yes
Mailing List Namespace
localhost

**Comment by hubertdeng123** [comment]
Is your SMTP server using SSL? I believe that error is happening because of that, you may need to configure that for your self-hosted instance.

**Comment by nemurasu** [comment]
In general, the SMTP settings are default.
Now explicitly specified in config.yml:
mail.use-tls: false
mail.use-ssl: false
In other places, SSL for SMTP is also not registered, I restarted docker-compose restart smtp, but the /manage/status/mail/ page still says:
SSL?
Yes
How can I correctly disable SSL for SMTP?
