### ISSUE TITLE
Chrome DevTools tries to access all .map files for the JS files

### ISSUE THREAD

**Issue by sadeghi-aa** [getsentry/self-hosted#2190]
### Self-Hosted Version

22.7.0

### CPU Architecture

Not sure

### Docker Version

Not sure

### Docker Compose Version

Not sure

### Steps to Reproduce

I've enabled Sentry in my NuxtJS project and I've also enabled the publishRelease option with the current config:

`publishRelease: {
      authToken: process.env.SENTRY_AUTH_TOKEN,
      org: 'organization',
      project: 'some-project-name',
      url: process.env.SENTRY_INTERNAL_URL,
      setCommits: {
        ignoreMissing: true,
      },
}`

### Expected Result

I want to eliminate all those warnings in the DevTools while hiding the source map files from the public. I couldn't find any related option in the Sentry configuration for this purpose.

### Actual Result

Using this configuration, the source maps are uploaded to out self-hosted instance of Sentry at the build time and I can see readable tracebacks for all errors that we receive. The problem is that, Chrome tries to fetch all .map files for some reason an results in many warnings like this one in the console:

`DevTools failed to load source map: Could not load content for https://somewebsite.com/8199b61.modern.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

It's getting a 404 error because I have denied all requests ending with .map with a 404 status code to prevent everyone from accessing our source map files because that would expose our project source code to the public and we don't want that.

**Comment by hubertdeng123** [comment]
Reading through our docs, are you using the hidden-source-map option? It seems to function to hide the sourcemaps from browser:
https://docs.sentry.io/platforms/javascript/guides/nextjs/manual-setup/?original_referrer=https%3A%2F%2Fgithub.com%2Fgetsentry%2Fsupport%2Fdiscussions%2F42#use-hidden-source-map
