### ISSUE TITLE
real time data not visible in monitoring dashboard

### ISSUE THREAD

**Issue by ajith-nataraj** [getsentry/self-hosted#2191]
### Self-Hosted Version

 9.0.0

### CPU Architecture

x86_64

### Docker Version

1.6.12

### Docker Compose Version

1.6

### Steps to Reproduce

Unable to see real time data In sentry dashboard, data gets pushed to sentry dashboard after every hour

### Expected Result

want to see real time data in monitoring dashboard

### Actual Result

real time data in monitoring dashboard

### Event ID

NA

**Comment by hubertdeng123** [comment]
You're using a super old version of self-hosted Sentry, so I'd advise you to upgrade and see if you still have this issue.
