### ISSUE TITLE
Can I move installed Sentry from one VM to another with all contains data?

### ISSUE THREAD

**Issue by vsfomin** [getsentry/self-hosted#2192]
### Problem Statement

I need to move a previously installed version of Sentry from one virtual machine to another, along with all the data it contains. How can I do this?

**Comment by hubertdeng123** [comment]
What data do you need? We have a [backup/restore process](https://develop.sentry.dev/self-hosted/backup/) that allows you to save minimal data. Otherwise, you'd need to backup your docker volumes to move your Sentry installation

**Comment by vsfomin** [comment]
> What have you tried ?

I've tried to copy all data from old server to new and put in into /var/lib/docker/volumes/
All the information I need has been migrated, but for some reason the project information is no longer being updated. It feels like no new data is coming in, but it's not. 
> What data do you need?
All data from old server ideally.

**Comment by hubertdeng123** [comment]
Are there any errors in your docker containers (web, postgres, clickhouse) that are helpful for debugging here?

**Comment by vsfomin** [comment]
> Are there any errors in your docker containers (web, postgres, clickhouse) that are helpful for debugging here?

[web.txt](https://github.com/getsentry/self-hosted/files/11886562/web.txt)
[postgres.txt](https://github.com/getsentry/self-hosted/files/11886563/postgres.txt)
Yes, there are some errors in web and postgres.

**Comment by hubertdeng123** [comment]
Seeing this. Looks like redis is not connecting, which is a pretty big issue here.
```
web_1  |   File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 544, in connect
web_1  |     raise ConnectionError(self._error_message(e))
web_1  | ConnectionError: Error -2 connecting to redis:6379. Name or service not known.
```

**Comment by vsfomin** [comment]
> Seeing this. Looks like redis is not connecting, which is a pretty big issue here.
> 
> ```
> web_1  |   File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 544, in connect
> web_1  |     raise ConnectionError(self._error_message(e))
> web_1  | ConnectionError: Error -2 connecting to redis:6379. Name or service not known.
> ```

May it be because **redis** not started yet before **web** was started? 
If I try to connect from web container to redis container, connection is OK. **nc** output below:
```
docker exec -it de94aca57021 /bin/bash
root@de94aca57021:/# nc -v redis 6379
DNS fwd/rev mismatch: redis != sentry_onpremise_redis_1.sentry_onpremise_default
redis [172.222.6.4] 6379 (?) open
```
Is postgres logs ok? Is it normal to see something like "ERROR:  duplicate key value violates unique constraint "sentry_environmentprojec_project_id_environment_i_91da82f2_uniq"

UPD: seems to me after rebooting server all works fine :-) Now sentry receives new issues and I receive test issue in my test go project.

**Comment by hubertdeng123** [comment]
> Is postgres logs ok? Is it normal to see something like "ERROR: duplicate key value violates unique constraint "sentry_environmentprojec_project_id_environment_i_91da82f2_uniq"

Yep, this is actually normal and don't indicate errors that should be of concern.

> UPD: seems to me after rebooting server all works fine :-) Now sentry receives new issues and I receive test issue in my test go project.

Awesome.
