### ISSUE TITLE
Slack integration fails to authenticate

### ISSUE THREAD

**Issue by radicaled42** [getsentry/self-hosted#2197]
### Self-Hosted Version

23.5.0

### CPU Architecture

x86:_64

### Docker Version

20.10.21

### Docker Compose Version

2.16.0

### Steps to Reproduce

Follow the slack integration [instructions](https://develop.sentry.dev/integrations/slack/) from Sentry.
On the  Event Subscriptions step I'm unable to get my Sentry url verified.

Its worth mentioning that my Sentry is in a private network. 
I made an API gateway to forward the request.

### Expected Result

The Slack challenge gets verified

### Actual Result

The slack challenge fails with a 401 error.
Using the API gateway, I can see this on the logs:
```
20:40:40 [INFO] sentry.integrations.slack: slack.event.url_verification
20:40:40 [ERROR] sentry.integrations.slack: slack.action.auth
20:40:40 [INFO] sentry.access.api: api.access (method='POST' view='sentry.integrations.slack.webhooks.event.SlackEventEndpoint' response=401 user_id='None' is_app='None' token_type='None' is_frontend_request='False' organization_id='None' auth_id='None' path='/extensions/slack/event/' caller_ip='XXX.XXX.XXX.XXX' user_agent='Slackbot 1.0 (+https://api.slack.com/robots)' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.06956982612609863 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
20:40:40 [WARNING] django.request: Unauthorized: /extensions/slack/event/ (status_code=401 request=<WSGIRequest: POST '/extensions/slack/event/'>)
```
Also an issue gets generated on Sentry.
```
slack.action.auth
SlackEventEndpoint
```

Using postman I have created a similar request from inside my network and I'm getting the same error.

**Comment by radicaled42** [comment]
This is the postman test I'm running in curl form:
```
curl --location 'https://sentry.XXXXX.XXXXX.com/extensions/slack/event/' \
--header 'Content-Type: application/json' \
--data '{"token": "XXXXXXXXXXXXXXXXXXXX", "challenge": "XXXXXXXXXXXXXXXXXXXXXXXXX", "type": "url_verification"}'
```

**Comment by hubertdeng123** [comment]
This sounds like something entirely network related then. Perhaps you can try modifying the `INTERNAL_SYSTEM_IPS` in the sentry.conf.py file to see if that works?

**Comment by radicaled42** [comment]
I agree this is a networking related issue. I don't see how can the `INTERNAL_SYSTEM_IPS` would help.

I have attached a small diagram with the architecture
![sentry-infra](https://github.com/getsentry/self-hosted/assets/48332446/dd4e7a56-918e-4f98-9b20-f2b98f46a1e5)
Basically everything is inside the VPC and Slack is the only thing outside.

From the slack integration instructions I gather that I have to configure these urls:
```
{YOUR_DOMAIN}/extensions/slack/action/
{YOUR_DOMAIN}/extensions/slack/options-load/
{YOUR_DOMAIN}/extensions/slack/setup/
{YOUR_DOMAIN}/extensions/slack/event/
{YOUR_DOMAIN}/extensions/slack/commands/
```

So my first approach was to change all the urls from my domain to the external api domain.
For example:
```
YOUR_DOMAIN=sentry.test.com
EXTERNAL_API_DOMAIN=external.sentry.test.com
```

But I'm getting this error:
```
redirect_uri did not match any configured URIs. Passed URI: https://sentry.test.com/extensions/slack/setup/
```

I understand that this error is related with the slack redirect url configuration, I used `https://external.sentry.test.com/extensions/slack/setup/` instead of `https://sentry.test.com/extensions/slack/setup/`

Now my question is, **is it possible to use multiple URI in the Sentry configuration?**

**Comment by hubertdeng123** [comment]
Got it, yeah perhaps `INTERNAL_SYSTEM_IPS` won't be useful. 

> I understand that this error is related with the slack redirect url configuration, I used https://external.sentry.test.com/extensions/slack/setup/ instead of https://sentry.test.com/extensions/slack/setup/

Have you tried configuring the `system.url-prefix` in your `config.yml` file? You can set that to `https://external.sentry.test.com`

**Comment by radicaled42** [comment]
I have configure the system.url-prefix with my company url `https://sentry.test.com`.
Its possible to configure multiple url-prefix or if I change it for the external url (`https://external.sentry.test.com`).
Both could keep working?

**Comment by radicaled42** [comment]
I made a couple of tests.
First changed the `url-prefix` to the external url `https://external.sentry.test.com` and started getting the following error:
`20:15:11 [ERROR] sentry_sdk.errors: Unexpected status code: 403 (body: b'{"message":"Missing Authentication Token"}')
`
I wasn't able to add the workspace and the events didn't work as well. Basically nothing was working

The second test, I change back `url-prefix` to the internal url `https://sentry.test.com` and then I changed the Slack app urls to point to the external API. The API is basically a passthrough of the requests. The only change that the API is doing, is to the **host** header, from `external.sentry.test.com` to `sentry.test.com`.

I added the internal url as well as the api url to the **Redirect URLs**:
```
https://sentry.test.com/extensions/slack/setup/ --> INTERNAL

https://externalsentry.test.com/extensions/slack/setup/ --> EXTERNAL
https://external.sentry.test.com/extensions/slack/action/ --> EXTERNAL
https://external.sentry.test.com/extensions/slack/options-load/ --> EXTERNAL
https://external.sentry.test.com/extensions/slack/event/ --> EXTERNAL
https://external.sentry.test.com/extensions/slack/commands/ --> EXTERNAL
```

I was able to add the Slack workspace to Sentry. But the events, the slash commands and the alert creation are not working.

I'm getting the following error when I tried to configure the events:
```
18:16:00 [INFO] sentry.integrations.slack: slack.event.url_verification
18:16:00 [ERROR] sentry.integrations.slack: slack.action.auth
18:16:00 [INFO] sentry.access.api: api.access (method='POST' view='sentry.integrations.slack.webhooks.event.SlackEventEndpoint' response=401 user_id='None' is_app='None' token_type='None' is_frontend_request='False' organization_id='None' auth_id='None' path='/extensions/slack/event/' caller_ip='XXX.XXX.XXX.XXX' user_agent='Slackbot 1.0 (+https://api.slack.com/robots)' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.07419657707214355 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
18:16:00 [WARNING] django.request: Unauthorized: /extensions/slack/event/ (status_code=401 request=<WSGIRequest: POST '/extensions/slack/event/'>)
```

This is the error when I tried to configure an alert to a Slack channel:
```
18:19:18 [INFO] sentry.rules: rule.slack.provide_channel_id (slack_integration_id=1 channel_id='CXXXXXXXXX')
18:19:18 [INFO] sentry.integrations.client: integration.http_response (integration='slack' status_string='200')
18:19:18 [INFO] sentry.access.api: api.access (method='PUT' view='sentry.api.endpoints.project_rule_details.ProjectRuleDetailsEndpoint' response=400 user_id='1' is_app='None' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/projects/sentry/python-test/rules/6/' caller_ip='XXX.XXX.XXX.XXX' user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.2251420021057129 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
18:19:18 [WARNING] django.request: Bad Request: /api/0/projects/sentry/python-test/rules/6/ (status_code=400 request=<WSGIRequest: PUT '/api/0/projects/sentry/python-test/rules/6/?duplicateRule=false&wizardV3=true'>)
```

Any idea?

**Comment by hubertdeng123** [comment]
> Its possible to configure multiple url-prefix or if I change it for the external url (https://external.sentry.test.com), both will keep working?

Unfortunately, not possible. It sounds like the webhooks are not being authenticated correctly, perhaps because `https://external.sentry.test.com/extensions/slack/event/` is the external URL and not internal. Sounds like you may be close, so good luck with getting a solution! 😁

**Comment by sentaur-athena** [comment]
I'm going to close this issue since there are some good suggestions on the ticket already and slack integration is in a healthy state in self-hosted.
