### ISSUE TITLE
The list of replays could not be loaded

### ISSUE THREAD

**Issue by davidpanic** [getsentry/self-hosted#2199]
### Self-Hosted Version

23.5.0

### CPU Architecture

x86_64

### Docker Version

Kubernetes v1.27.1, containerd 1.6.20

### Docker Compose Version

sentry-kubernetes 18.0.0

### Steps to Reproduce

1. Try to view replays on an issue.
2. Observe error

### Expected Result

I expected to be able to view the replays.

### Actual Result

![image](https://github.com/getsentry/self-hosted/assets/13370323/89517e95-adf8-4c83-a337-bc54389db4fe)

For the logs, please ask me for the exact pod logs because `docker compose logs` is not going to work in this case and there are 50 pods.

### Event ID

I cannot find any event ID to give you.

**Comment by kadet1090** [comment]
From my experience (also using kubernetes setup based on mentioned chart) most of the time you can find useful information in the logs of the `snuba-api` and `sentry-worker` pods. Then you can target consumers related to your specific problem - in that case it'd be `sentry-ingest-replay-recordings` and `sentry-snuba-replays-consumer`. Most of the time `sentry-web` do not log anything special but it's always good to check.

Taking into account that sentry knows about replays (36 in the tab) I'd suspect that related data is available in the postgresql database, but not in the clickhouse - I am not however sure if clickhouse is used for this feature. So I'd suggest you to check:
1. `snuba-api` logs - they will be helpful if there are missing migrations and problems with clickhouse
2. If the files related to replays are correctly stored in the filestore of your choice
3. If your kafka has all the topics required in that case it'd be `ingest-replay-recordings` - you can always check [install/create-kafka-topics.sh](https://github.com/getsentry/self-hosted/blob/master/install/create-kafka-topics.sh) file for list
4. If the related consumers are running ok and do not complain about anything in logs - you can check logs of the `sentry-ingest-replay-recordings` / `sentry-snuba-replays-consumer` pods or try to exec into some other pods (I usually exec into `sentry-worker` or `snuba-api` and try to start consumers there for short time to see if everything is ok)

**Comment by hubertdeng123** [comment]
We don't officially support running Sentry on kubernetes but to follow up on the comment above, Clickhouse is also used to store replay metadata. Postgres will store the replay blobs while clickhouse will store the mapping from each replay to 1 (or more) of these blobs. Otherwise, some helpful debugging tips are also provided so hopefully those can lead you down the right path!

**Comment by davidpanic** [comment]
I will definitely be investigating this further, I just haven't gotten around to it yet. Thanks for the extra info.
