### ISSUE TITLE
GitLab integration fails to verify custom certificate

### ISSUE THREAD

**Issue by spawnia** [getsentry/self-hosted#2210]
### Self-Hosted Version

23.6.1

### CPU Architecture

x86_64

### Docker Version

24.0.2

### Docker Compose Version

2.11.1

### Steps to Reproduce

- Add a GitLab integration that connects to a self-hosted GitLab instance with a custom certificate
- Add the certificate to the `certificates` directory in the project root
- `./install.sh`
- Try to create a GitLab issue

The integration worked fine with 23.3.1, it broke with the update to 23.5.1.

### Expected Result

A pop-up should appear that allows selection of a project and issue to create or link.

When starting the containers with `docker-compose up -d`, the entrypoint that adds the custom certificate runs:

```
sentry-self-hosted-web-1  | Updating certificates in /etc/ssl/certs...
sentry-self-hosted-web-1  | 1 added, 0 removed; done.
```

The custom certificate has been added:

```
root@f36dff7e7e95:/# tail /etc/ssl/certs/ca-certificates.crt
7+EhQybcz5MS8HduUPDhid4Wp8sZTtfHWFXkIoO9GtCBSMoPMNl7ehvAK65JZwGy
CCtBvgQnRthj363yeDqWbA19r3YEu1wGqg/HK0bEnDltKdx66LC/TxxjBaV374kI
oC4PRjrB2CenT/tsTPWwvDpmv2NGBxFTZMRufADK7NidK/5X/Zl0oNT8cKeI0lqn
NBEN3DCFI+a9nRO3b31BDrUIBGJzbGEMoq4rDYyFxsn0RyfMxNJ0MVlCEmCqrRg9
bcGBVqgqeA9p8Gx3J2oLStuWdHxDQA09c59XRNkHFqFyEfjAjuk1NeDDHfeFekWu
EFO7xV2i14IdV16Sk+4iFC6qXFTDJASO59/iBfeeODOKuQL4Tw8UMfE740NKXGP+
w5AKKQjfdJ/TfaccGFPP6dHymYR5rt1JcKm+/5QFMMNkgE9g2CaCzjQk0HByK/1v
obvUf/m/lmZR/ByUfCa10TquTc8gPkL1xKLfFsgA90fBAfynmroCo7rPh9YsuoL8
RYe4xMkTHbAKcEqRL/asN1kA00C0XJ9qdL1xzJ04lI9kZKkHzd4glNgqDEOey5o=
-----END CERTIFICATE-----
root@f36dff7e7e95:/# tail /etc/sentry/mll_CA.crt 
7+EhQybcz5MS8HduUPDhid4Wp8sZTtfHWFXkIoO9GtCBSMoPMNl7ehvAK65JZwGy
CCtBvgQnRthj363yeDqWbA19r3YEu1wGqg/HK0bEnDltKdx66LC/TxxjBaV374kI
oC4PRjrB2CenT/tsTPWwvDpmv2NGBxFTZMRufADK7NidK/5X/Zl0oNT8cKeI0lqn
NBEN3DCFI+a9nRO3b31BDrUIBGJzbGEMoq4rDYyFxsn0RyfMxNJ0MVlCEmCqrRg9
bcGBVqgqeA9p8Gx3J2oLStuWdHxDQA09c59XRNkHFqFyEfjAjuk1NeDDHfeFekWu
EFO7xV2i14IdV16Sk+4iFC6qXFTDJASO59/iBfeeODOKuQL4Tw8UMfE740NKXGP+
w5AKKQjfdJ/TfaccGFPP6dHymYR5rt1JcKm+/5QFMMNkgE9g2CaCzjQk0HByK/1v
obvUf/m/lmZR/ByUfCa10TquTc8gPkL1xKLfFsgA90fBAfynmroCo7rPh9YsuoL8
RYe4xMkTHbAKcEqRL/asN1kA00C0XJ9qdL1xzJ04lI9kZKkHzd4glNgqDEOey5o=
-----END CERTIFICATE-----
```

### Actual Result

This appears in the UI:

![Screenshot 2023-06-16 103614](https://github.com/getsentry/self-hosted/assets/12158000/cc79bbab-ae92-4584-b387-9cb9ecf14df6)

The logs show the cause to be failing SSL verification:

```
sentry-self-hosted-web-1  | 08:29:04 [INFO] sentry.integrations.client: integration.http_response (status_string='connection_error' error="SafeHTTPSConnectionPool(host='gitlab.mll', port=443): Max retries exc
eeded with url: /api/v4/projects?simple=True&order_by=last_activity_at&page=1&per_page=100&membership=True (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED" integration='gitlab
')
```

**Comment by spawnia** [comment]
Upon further investigation, I found that the `requests` module (or perhaps the use of that module in the integration) does not respect the environment variable `REQUESTS_CA_BUNDLE`. The following steps fixed the issue temporarily:

```
root@f36dff7e7e95:/# echo $REQUESTS_CA_BUNDLE
/etc/ssl/certs/ca-certificates.crt
root@f36dff7e7e95:/# python -mrequests.certs
/usr/local/lib/python3.8/runpy.py:127: RuntimeWarning: 'requests.certs' found in sys.modules after import of package 'requests', but prior to execution of 'requests.certs'; this may result in unpredictable be
haviour
  warn(RuntimeWarning(msg))
/usr/local/lib/python3.8/site-packages/certifi/cacert.pem
root@f36dff7e7e95:/# cp /etc/ssl/certs/ca-certificates.crt /usr/local/lib/python3.8/site-packages/certifi/cacert.pem
```

A more permanent solution to this problem would be much appreciated still.

**Comment by spawnia** [comment]
Thanks for your feedback @hubertdeng123 . Yes, it broke when upgrading from 23.3.1 to 23.5.1. I did not try any version inbetween.

Once I found the error, I figured I would try an update to 23.6.1 before investigating further. Since that did not help, I then dug into the problem deeper and wrote this report and found the fix I mentioned in https://github.com/getsentry/self-hosted/issues/2210#issuecomment-1594355572.

**Comment by crinjes** [comment]
My current workaround, as `sentry/enhance-image.sh`:
```bash
#!/bin/bash
CERTIFI_LOCATION="$(python -m requests.certs 2>/dev/null)"
if [[ -f "$CERTIFI_LOCATION" ]]; then
  rm "$CERTIFI_LOCATION"
  ln -s /etc/ssl/certs/ca-certificates.crt "$CERTIFI_LOCATION"
fi
```

There's also a `python -m certifi` that outputs yet another CA bundle, but the above _works on my machine™_.

**Comment by hubertdeng123** [comment]
Thanks for chiming in!

**Comment by spawnia** [comment]
Thank you @crinjes, I can confirm that your fix also works for me. Perhaps that symlink can be included in the package by default?

**Comment by hubertdeng123** [comment]
This PR should actually fix this:
https://github.com/getsentry/sentry/pull/53836

I'm wondering if this is still an issue for you all.
