### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by godt21** [getsentry/self-hosted#2212]
### Self-Hosted Version

21.7.0

### CPU Architecture

x86_64

### Docker Version

24.0.2

### Docker Compose Version

1.29.2

### Steps to Reproduce

when excute ./install.sh

### Expected Result

the error is in 4/5 

#8 [symbolicator-cleanup 4/5] RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
#8 0.423 Ign:1 http://deb.debian.org/debian stretch InRelease
#8 0.497 Ign:2 http://deb.debian.org/debian stretch-updates InRelease
#8 0.525 Ign:3 http://security.debian.org/debian-security stretch/updates InRelease
#8 0.574 Ign:4 http://deb.debian.org/debian stretch Release
#8 0.594 Ign:5 http://security.debian.org/debian-security stretch/updates Release
#8 0.649 Ign:6 http://deb.debian.org/debian stretch-updates Release
#8 0.663 Ign:7 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
#8 0.730 Ign:8 http://security.debian.org/debian-security stretch/updates/main all Packages
#8 0.731 Ign:9 http://deb.debian.org/debian stretch/main all Packages
#8 0.795 Ign:7 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
#8 0.796 Ign:10 http://deb.debian.org/debian stretch/main amd64 Packages
#8 0.861 Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
#8 0.863 Ign:8 http://security.debian.org/debian-security stretch/updates/main all Packages
#8 0.933 Ign:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
#8 0.946 Ign:7 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
#8 0.998 Ign:9 http://deb.debian.org/debian stretch/main all Packages
#8 1.011 Ign:8 http://security.debian.org/debian-security stretch/updates/main all Packages
#8 1.063 Ign:10 http://deb.debian.org/debian stretch/main amd64 Packages
#8 1.078 Ign:7 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
#8 1.129 Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
#8 1.146 Ign:8 http://security.debian.org/debian-security stretch/updates/main all Packages
#8 1.205 Ign:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
#8 1.214 Ign:7 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
#8 1.284 Ign:8 http://security.debian.org/debian-security stretch/updates/main all Packages
#8 1.358 Err:7 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
#8 1.358   404  Not Found [IP: 151.101.194.132 80]
#8 1.428 Ign:8 http://security.debian.org/debian-security stretch/updates/main all Packages
#8 1.429 Ign:9 http://deb.debian.org/debian stretch/main all Packages
#8 1.505 Ign:10 http://deb.debian.org/debian stretch/main amd64 Packages
#8 1.586 Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
#8 1.654 Ign:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
#8 1.724 Ign:9 http://deb.debian.org/debian stretch/main all Packages
#8 1.792 Ign:10 http://deb.debian.org/debian stretch/main amd64 Packages
#8 1.860 Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
#8 1.930 Ign:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
#8 2.001 Ign:9 http://deb.debian.org/debian stretch/main all Packages
#8 2.076 Ign:10 http://deb.debian.org/debian stretch/main amd64 Packages
#8 2.159 Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
#8 2.237 Ign:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
#8 2.313 Ign:9 http://deb.debian.org/debian stretch/main all Packages
#8 2.470 Err:10 http://deb.debian.org/debian stretch/main amd64 Packages
#8 2.470   404  Not Found
#8 2.550 Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
#8 2.620 Err:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
#8 2.620   404  Not Found
#8 2.623 Reading package lists...
#8 2.631 W: The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file.
#8 2.631 W: The repository 'http://security.debian.org/debian-security stretch/updates Release' does not have a Release file.
#8 2.631 W: The repository 'http://deb.debian.org/debian stretch-updates Release' does not have a Release file.
#8 2.631 E: Failed to fetch http://deb.debian.org/debian/dists/stretch/main/binary-amd64/Packages  404  Not Found
#8 2.631 E: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/main/binary-amd64/Packages  404  Not Found [IP: 151.101.194.132 80]
#8 2.631 E: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/main/binary-amd64/Packages  404  Not Found
#8 2.631 E: Some index files failed to download. They have been ignored, or old ones used instead.
#8 ERROR: process "/bin/sh -c apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*" did not complete successfully: exit code: 100
------
 > [symbolicator-cleanup 4/5] RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*:
#8 2.620 Err:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
#8 2.620   404  Not Found
#8 2.623 Reading package lists...
#8 2.631 W: The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file.
#8 2.631 W: The repository 'http://security.debian.org/debian-security stretch/updates Release' does not have a Release file.
#8 2.631 W: The repository 'http://deb.debian.org/debian stretch-updates Release' does not have a Release file.
#8 2.631 E: Failed to fetch http://deb.debian.org/debian/dists/stretch/main/binary-amd64/Packages  404  Not Found
#8 2.631 E: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/main/binary-amd64/Packages  404  Not Found [IP: 151.101.194.132 80]
#8 2.631 E: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/main/binary-amd64/Packages  404  Not Found
#8 2.631 E: Some index files failed to download. They have been ignored, or old ones used instead.
------
failed to solve: process "/bin/sh -c apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*" did not complete successfully: exit code: 100
Error in install/build-docker-images.sh:9.
'$dcb --force-rm "$service"' exited with status 17
-> ./install.sh:main:29
--> install/build-docker-images.sh:source:9

### Actual Result

maybe I think it is relay on network for download some image. could list all ? or and I could change the mirror?

**Comment by kiskoza** [comment]
Seems to be a duplication of #2214  (this one was created earlier, but I found that first and wrote a workaround in the comments)

**Comment by hubertdeng123** [comment]
Closing this as a duplicate, thanks for posting a solution @kiskoza
