### ISSUE TITLE
Error when deploying Sentry with Docker

### ISSUE THREAD

**Issue by weiwendi** [getsentry/self-hosted#2214]
### Self-Hosted Version

23.70

### CPU Architecture

x86_64

### Docker Version

24.0.2

### Docker Compose Version

v2.18.1

### Steps to Reproduce

Error when deploying Sentry with Docker.

### Expected Result

#8 2.914 Err:8 http://deb.debian.org/debian stretch/main amd64 Packages
#8 2.914   404  Not Found
#8 2.999 Ign:9 http://deb.debian.org/debian stretch-updates/main all Packages
#8 3.085 Err:11 http://deb.debian.org/debian stretch-updates/main amd64 Packages
#8 3.085   404  Not Found
#8 3.213 Ign:12 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
#8 3.375 Ign:10 http://security.debian.org/debian-security stretch/updates/main all Packages
#8 3.531 Ign:12 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
#8 3.699 Ign:10 http://security.debian.org/debian-security stretch/updates/main all Packages
#8 3.869 Err:12 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
#8 3.869   404  Not Found [IP: 151.101.130.132 80]
#8 3.872 Reading package lists...
#8 3.879 W: The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file.
#8 3.879 W: The repository 'http://deb.debian.org/debian stretch-updates Release' does not have a Release file.
#8 3.879 W: The repository 'http://security.debian.org/debian-security stretch/updates Release' does not have a Release file.
#8 3.879 E: Failed to fetch http://deb.debian.org/debian/dists/stretch/main/binary-amd64/Packages  404  Not Found
#8 3.879 E: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/main/binary-amd64/Packages  404  Not Found
#8 3.879 E: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/main/binary-amd64/Packages  404  Not Found [IP: 151.101.130.132 80]
#8 3.879 E: Some index files failed to download. They have been ignored, or old ones used instead.
#8 ERROR: process "/bin/sh -c apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*" did not complete successfully: exit code: 100
------
 > [symbolicator-cleanup 4/5] RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*:
#8 3.869 Err:12 http://securit

### Actual Result

/var/lib/apt/lists/*" did not complete successfully: exit code: 100
------
 > [symbolicator-cleanup 4/5] RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*:
#8 3.869 Err:12 http://securit

**Comment by weiwendi** [comment]
replay

**Comment by kiskoza** [comment]
I ran into the same issue while I was upgrading from an earlier version. I wrote this workaround for 23.6.1

```diff
diff --git a/cron/Dockerfile b/cron/Dockerfile
index edb6407..70939bd 100644
--- a/cron/Dockerfile
+++ b/cron/Dockerfile
@@ -3,6 +3,9 @@ FROM ${BASE_IMAGE}
 USER 0
 RUN if [ -z "${http_proxy}" ]; then echo "Acquire::http::proxy \"${http_proxy}\";" >> /etc/apt/apt.conf; fi
 RUN if [ -z "${https_proxy}" ]; then echo "Acquire::https::proxy \"${https_proxy}\";" >> /etc/apt/apt.conf; fi
+RUN sed -i s/deb.debian.org\\/debian\ stretch-updates/archive.debian.org\\/debian\ stretch/g /etc/apt/sources.list
+RUN sed -i s/deb.debian.org\\/debian\ stretch/archive.debian.org\\/debian\ stretch/g /etc/apt/sources.list
+RUN sed -i s/security.debian.org\\/debian-security\ stretch/archive.debian.org\\/debian-security\ stretch/g /etc/apt/sources.list
 RUN apt-get update && apt-get install -y --no-install-recommends cron && \
     rm -r /var/lib/apt/lists/*
 COPY entrypoint.sh /entrypoint.sh
```

The issue relates to the fact that Debian Stretch (9) is no longer supported and the moved the apt repository from `deb.debian.org` to `archive.debian.org`.

**Comment by hubertdeng123** [comment]
Thanks for sharing this, could you try the solution @weiwendi ?
