### ISSUE TITLE
How to clean all SAML setting  in database ?

### ISSUE THREAD

**Issue by Schoomee** [getsentry/self-hosted#2225]
### Self-Hosted Version

Sentry 22.10.0 ad40640

### CPU Architecture

x86_64

### Docker Version

20.10.16

### Docker Compose Version

2.6.0

### Steps to Reproduce

Do you know how to clean all Saml configuration in PostgreSQL db?

We migrated our Sentry hosted under Kubernetes to a new cluster, we also changed dns domain. The PostgreSQL database is restored with all the data, when we try to reactivate SSO on the new server, once the configuration is complete, it responds with the old URL.

I tried this: https://forum.sentry.io/t/incorrect-saml2-configuration-disable-saml2-login-page/12862

But it does not clean the URL saved in the database

### Expected Result

-

### Actual Result

-

**Comment by hubertdeng123** [comment]
What SSO option are you using? It's possible you may need to change the url-prefix on whatever app you're using. I took a skim into how SAML is set up in `getsentry/sentry` I couldn't find much

**Comment by failoman23** [comment]
I run into this issue while on 20.12.1, My workaround was to use IdP Data for configuration instead of Metadata URL
