### ISSUE TITLE
Cannot autolaunch D-Bus without X11 $DISPLAY

### ISSUE THREAD

**Issue by aamarques** [getsentry/self-hosted#2226]
### Self-Hosted Version

23.5.2

### CPU Architecture

x86_64

### Docker Version

24.0.2

### Docker Compose Version

2.18.1

### Steps to Reproduce

SENTRY_IMAGE=getsentry/sentry:23.6.1 ./install.sh

Why do we need X11 now? 

### Expected Result

Update to 23.6.1

### Actual Result

```
#3 [symbolicator-cleanup internal] load metadata for docker.io/getsentry/symbolicator:23.6.1
#3 ERROR: error getting credentials - err: exit status 1, out: `Cannot autolaunch D-Bus without X11 $DISPLAY`
------
 > [symbolicator-cleanup internal] load metadata for docker.io/getsentry/symbolicator:23.6.1:
------
failed to solve: getsentry/symbolicator:23.6.1: error getting credentials - err: exit status 1, out: `Cannot autolaunch D-Bus without X11 $DISPLAY`
Error in install/build-docker-images.sh:9.
'$dcb --force-rm "$service"' exited with status 17
-> ./install.sh:main:29
--> install/build-docker-images.sh:source:9
```

**Comment by aamarques** [comment]
This is related to a update of docker that call X11 and set some vars.
So, logoff/logon solve this.

It's working.

**Comment by nyrygyk** [comment]
If anybody else stumbles across this, your system maz also be missing `pass` (see https://stackoverflow.com/a/52251706/11599848). After following the steps provided in the mentioned answer the script was able to fetch the credentials.
