### ISSUE TITLE
Sentry 9.1.2 incompatibility with postgress version 12 or above

### ISSUE THREAD

**Issue by rajivmucheli** [getsentry/self-hosted#2233]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Hi,

Due to cost issues i am unable to upgrade my onpremise sentry version 9.1.2 to the latest version. Could i know which is the latest postgres version which is compatible with version 9.1.2 ? i am currently running on postgres version 9.6

### Expected Result

Sentry v9.1.2 needs to be compatible with postgres 12 and above

### Actual Result

pg_upgrade fails

### Product Area

Performance

### Version

9.1.2

**Comment by hubertdeng123** [comment]
This is a very old version, but it looks like the default is postgres 9.5. If you'd like to upgrade your own postgres instance you'll need to experiment on your own if you don't want to upgrade your Sentry instance.

**Comment by rajivmucheli** [comment]
i see, whats the best to upgrade sentry to the latest version ?

the static relay mode is chargeable ? i tried upgrading to v10 and v22 but couldnt find any events post ugprading :

v22 : https://github.com/sapcc/helm-charts/commit/77d6a815293e7e4f0ef13b67f3e72a0c7150f797
v10 : https://github.com/sapcc/helm-charts/tree/sentry-10

**Comment by hubertdeng123** [comment]
I am not sure how to upgrade if you're using helm charts. There are hard stops that you must honor though:
https://develop.sentry.dev/self-hosted/releases/

**Comment by rajivmucheli** [comment]
thanks for the docu, how can i find which version of postgres is supported by which sentry version ?

Online shows 23x supports postgres 14, how about 21.5.0, 21.6.3 ?

**Comment by hubertdeng123** [comment]
Those will be on postgres 9. You can look at the source code in the `docker-compose.yml` file to confirm the image version
