### ISSUE TITLE
502 gateway

### ISSUE THREAD

**Issue by KobeZhou** [getsentry/self-hosted#2247]
### Self-Hosted Version

23.6.1

### CPU Architecture

x86_64

### Docker Version

20.10.16

### Docker Compose Version

2.6.0

### Steps to Reproduce

1. click on the self-host sentry platform
2. POST xx/api/1/envelope/?sentry_key=xx&sentry_version=7&sentry_client=sentry.javascript.react%2F7.53.1 
3. 502 (Bad Gateway) problem

### Expected Result

xx/api/1/envelope/?sentry_key=xx&sentry_version=7&sentry_client=sentry.javascript.react%2F7.53.1    is   status 200.

### Actual Result

 http://xx.com/api/1/envelope/?sentry_key=xx&sentry_version=7&sentry_client=sentry.javascript.react%2F7.53.1 502 (Bad Gateway)

**Comment by hubertdeng123** [comment]
Are there any logs in your `web` container that indicate any issues?
