### ISSUE TITLE
Container sentry-self-hosted-web error when run docker compose up

### ISSUE THREAD

**Issue by jokomanza** [getsentry/self-hosted#2249]
### Self-Hosted Version

23.6.1

### CPU Architecture

aarch64

### Docker Version

24.0.2

### Docker Compose Version

2.18.1

### Steps to Reproduce

1. Download sentry release v23.6.1
2. Run ./install.sh
3. Run docker compose up -d

### Expected Result

Run successfully

### Actual Result

[+] Building 0.0s (0/0)                                                                                                                                                                                   
[+] Running 44/44
 ✔ Container sentry-self-hosted-symbolicator-cleanup-1                                                                                                                                 Started       1.4s 
 ✔ Container sentry-self-hosted-geoipupdate-1                                                                                                                                          Started       1.3s 
 ✔ Container sentry-self-hosted-clickhouse-1                                                                                                                                           Healthy      32.9s 
 ✔ Container sentry-self-hosted-zookeeper-1                                                                                                                                            Healthy      32.1s 
 ✔ Container sentry-self-hosted-symbolicator-1                                                                                                                                         Started       1.7s 
 ✔ Container sentry-self-hosted-redis-1                                                                                                                                                Healthy      67.6s 
 ✔ Container sentry-self-hosted-kafka-1                                                                                                                                                Healthy      67.6s 
 ✔ Container sentry-self-hosted-postgres-1                                                                                                                                             Healthy      65.3s 
 ✔ Container sentry-self-hosted-smtp-1                                                                                                                                                 Started       1.1s 
 ✔ Container sentry-self-hosted-memcached-1                                                                                                                                            Started       1.1s 
 ✔ Container sentry-self-hosted-snuba-subscription-consumer-transactions-1                                                                                                             Started      64.6s 
 ✔ Container sentry-self-hosted-vroom-1                                                                                                                                                Started      64.5s 
 ✔ Container sentry-self-hosted-snuba-sessions-consumer-1                                                                                                                              Started      64.6s 
 ✔ Container sentry-self-hosted-snuba-replays-consumer-1                                                                                                                               Started      64.8s 
 ✔ Container sentry-self-hosted-snuba-subscription-consumer-events-1                                                                                                                   Started      64.0s 
 ✔ Container sentry-self-hosted-snuba-api-1                                                                                                                                            Started      64.1s 
 ✔ Container sentry-self-hosted-snuba-subscription-consumer-sessions-1                                                                                                                 Started      64.7s 
 ✔ Container sentry-self-hosted-snuba-outcomes-consumer-1                                                                                                                              Started      63.7s 
 ✔ Container sentry-self-hosted-snuba-replacer-1                                                                                                                                       Started      64.8s 
 ✔ Container sentry-self-hosted-snuba-profiling-profiles-consumer-1                                                                                                                    Started      63.7s 
 ✔ Container sentry-self-hosted-snuba-consumer-1                                                                                                                                       Started      64.4s 
 ✔ Container sentry-self-hosted-snuba-transactions-consumer-1                                                                                                                          Started      64.1s 
 ✔ Container sentry-self-hosted-snuba-profiling-functions-consumer-1                                                                                                                   Started      64.8s 
 ✔ Container sentry-self-hosted-post-process-forwarder-transactions-1                                                                                                                  Started      67.9s 
 ✔ Container sentry-self-hosted-subscription-consumer-events-1                                                                                                                         Started      67.9s 
 ✔ Container sentry-self-hosted-cron-1                                                                                                                                                 Started      67.9s 
 ✔ Container sentry-self-hosted-post-process-forwarder-errors-1                                                                                                                        Started      67.9s 
 ✘ Container sentry-self-hosted-web-1                                                                                                                                                  Error       441.6s 
 ✔ Container sentry-self-hosted-transactions-consumer-1                                                                                                                                Started      66.5s 
 ✔ Container sentry-self-hosted-subscription-consumer-transactions-1                                                                                                                   Started      67.9s 
 ✔ Container sentry-self-hosted-worker-1                                                                                                                                               Started      67.1s 
 ✔ Container sentry-self-hosted-attachments-consumer-1                                                                                                                                 Started      67.3s 
 ✔ Container sentry-self-hosted-ingest-profiles-1                                                                                                                                      Started      68.0s 
 ✔ Container sentry-self-hosted-ingest-replay-recordings-1                                                                                                                             Started      67.9s 
 ✔ Container sentry-self-hosted-sentry-cleanup-1                                                                                                                                       Started      67.8s 
 ✔ Container sentry-self-hosted-events-consumer-1                                                                                                                                      Started      67.1s 
 ! snuba-profiling-functions-consumer The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                 0.0s 
 ! snuba-profiling-profiles-consumer The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                  0.0s 
 ! snuba-subscription-consumer-sessions The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested               0.0s 
 ! symbolicator-cleanup The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                               0.0s 
 ! snuba-replays-consumer The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                             0.0s 
 ✔ Container sentry-self-hosted-relay-1                                                                                                                                                Created       0.1s 
 ! relay The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                                              0.0s 
 ✔ Container sentry-self-hosted-nginx-1                                                                                                                                                Created       0.0s

**Comment by wyr1227** [comment]
It happened to me, too

**Comment by hubertdeng123** [comment]
Unfortunately, we offer limited support for ARM64. We have an issue open for this but it is unlikely that we'll get to this in the near future. Please follow up in the linked issue if you have any other concerns.

https://github.com/getsentry/self-hosted/issues/1585
