### ISSUE TITLE
service.platform should be part of the service.build.platforms: "linux/amd64" 

### ISSUE THREAD

**Issue by MegaThorx** [getsentry/self-hosted#2257]
### Self-Hosted Version

23.6.2

### CPU Architecture

x86_64

### Docker Version

20.10.14

### Docker Compose Version

2.11.0

### Steps to Reproduce

1. Try to run ./install.sh with the specified docker compose version.

### Expected Result

It should work without a modification to the docker-compose.yml OR downgrade of the docker compose.

### Actual Result

```
▶ Building and tagging Docker images ...

service.platform should be part of the service.build.platforms: "linux/amd64"
Error in install/build-docker-images.sh:6.
'$dcb --force-rm web' exited with status 1
-> ./install.sh:main:29
--> install/build-docker-images.sh:source:6
```

https://github.com/getsentry/self-hosted/issues/1924

**Comment by hubertdeng123** [comment]
I'm using docker compose v2.18.1 and this doesn't seem to be an issue for me. I'm looking at the code for when this error happens and it seems like it displays when a user defines a service platform and a build platform. Is that the case for you?

https://github.com/docker/compose/blob/e28b223650807aa24a5c7637b6ad17189fb9276c/pkg/compose/build.go#L528

**Comment by MegaThorx** [comment]
I've upgraded docker-compose to `2.19.0` and it works perfectly. 



The platform was defined in the provided docker-compose.yml file.
https://github.com/getsentry/self-hosted/blob/master/docker-compose.yml#L21

**Comment by hubertdeng123** [comment]
> I've upgraded docker-compose to 2.19.0 and it works perfectly.

May be an issue with docker compose then for an older version. Going to go ahead and close this then
