### ISSUE TITLE
Jira on-premises integration after Update

### ISSUE THREAD

**Issue by DrDth** [getsentry/self-hosted#2258]
### Self-Hosted Version

23.6.1

### CPU Architecture

x86_64

### Docker Version

23.0.4

### Docker Compose Version

2.4.1

### Steps to Reproduce

1. Install latest sentry-onpremise
2. Use older jira version then the current one

### Expected Result

Jira Integration for self-hosted jira should work correctly 

### Actual Result

Since https://github.com/getsentry/sentry/issues/37534 was completed we have a problem with our jira integration in sentry.

Our jira´s licence is expired long time ago and since atlassian does not wan´t to support self-hosting anymore we are not able to purchase a new one anymore.

So our jira version is way older than the version the api-path-change from the referenced issue has happend in.

Since the latest sentry update the integration does not work anymore.

Is there any way to extract the jira-server plugin again easily (which I don´t see) so we can just install an earlier version without the jira api route change via pip and the enhance-image.sh file?

**Comment by hubertdeng123** [comment]
I don't think there's an easy way to extract the jira-server plugin if you're on a more recent version of Sentry. Your best bet is just to try downgrading your Sentry instance if you're using an old jira setup.

**Comment by DrDth** [comment]
Okay I thought so. Thank you for the answer. I did not wan´t to close our internal issue without asking.
