### ISSUE TITLE
migration 0460 crashing

### ISSUE THREAD

**Issue by bb4L** [getsentry/self-hosted#2261]
### Self-Hosted Version

23.4.0 -> 23.6.2

### CPU Architecture

x86_64

### Docker Version

20.10.22

### Docker Compose Version

1.29.2

### Steps to Reproduce

1. i had v 23.4.0 running without issues
2. updated to 23.6.2 and when running the `install.sh` script

### Expected Result

I would expect the migration to work out of the box

### Actual Result

 the migration 0460 failed with
 ```
    Running migrations for default
    /usr/local/lib/python3.8/site-packages/memcache.py:1303: SyntaxWarning: "is" with a literal. Did you mean "=="?
    if key is '':
    /usr/local/lib/python3.8/site-packages/memcache.py:1304: SyntaxWarning: "is" with a literal. Did you mean "=="?
      if key_extra_len is 0:
    Audit Log Entrys: N/A% |                                       | ETA:  --:--:--Operations to perform:
     Apply all migrations: admin, auth, contenttypes, nodestore, replays, sentry, sessions, sites, social_auth
    Running migrations:
      Applying sentry.0460_pickle_to_json_sentry_auditlogentry...Traceback (most recent call last):
      File "/usr/local/lib/python3.8/site-packages/sentry/db/models/fields/gzippeddict.py", line 35, in to_python
    return json.loads(value)
      File "/usr/local/lib/python3.8/site-packages/sentry/utils/json.py", line 138, in loads
    return _default_decoder.decode(value)
      File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
     obj, end = self.raw_decode(s)
      File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
    simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
 ```

**Comment by bb4L** [comment]
when attaching to the container (after rebuilding for version 23.4.0) and looking at the data with `sentry django shell`

i don't see a team with `id=1` 

```
from sentry.models.team import Team
Team.objects.all().order_by("id").first()
```

gives me a team with `id=2`

**Comment by hubertdeng123** [comment]
Interesting, if I were you I'd query postgres and look for any rows in the `sentry_auditlogentry` table and delete anything that has the team `id=1`. Just a quick look in the table indicates to me you should be able to find that in the `data` column

**Comment by hubertdeng123** [comment]
I would also expect the migration to work out of box so this is indeed a bit strange

**Comment by bb4L** [comment]
i could resolve it by adjusting those entries to follow the newer pattern and removing all the `id=1` entries

but i still wonder how i could end up in this state 🤔

**Comment by hubertdeng123** [comment]
Glad you got this resolved, going to close this then.
