### ISSUE TITLE
How to automatically create projects?

### ISSUE THREAD

**Issue by gabriel-v** [getsentry/self-hosted#2263]
### Problem Statement

For data security reasons we are required to run a separate Sentry instance for each website we want to monitor.

All these instances share the same 5 Sentry projects (Djangos, Flasks, Javascripts).

Manually creating projects and manually copying back DSN into app configuration is such a drag.

This may be related: https://github.com/getsentry/sentry-cli/issues/424 - I understand Sentry-CLI will not have this capability in the near future.

But how does one automate this?

### Solution Brainstorm

I looked at the `web` container commands - I expected some `createproject` command to exist alongside the `createuser`. I looked in `sentry --help` and `sentry django --help` -- I see nothing relevant.

### Proposed solution

Add a subcommand called `createproject` that takes a name and preset (Django/Node.JS) as CLI arguments, creates project if it doesn't exist, then prints the DSN and exits.

Or some of your internal shell/python scripts that automate creation of projects - is there something like this in your CI?

**Comment by gabriel-v** [comment]
I just found the API documentation here: https://docs.sentry.io/api/projects/create-a-new-project/

So a possible solution would be:
1. `createuser --email a@b.c --password XXX --superuser --staff --no-input` 
2. Authenticate to web service using username/password and somehow fetch the auth token for the superuser??
3. Use above API endpoint with bearer token

Any suggestion for the second step above? Is there some management command to print the auth token for the user, so one doesn't have to visit the home page to obtain it?

**Comment by hubertdeng123** [comment]
Thanks for writing in, yes we definitely recommend using our api to create projects like you have discovered above. We don't plan on supporting a `createproject` subcommand for project creation. Your use case does seem extremely specific. Most people I would assume would be running one Sentry instance and would only need to retrieve the API token once.

> Any suggestion for the second step above? Is there some management command to print the auth token for the user, so one doesn't have to visit the home page to obtain it?

No, I'm afraid there isn't one that I know of. 

Looks like you're deep in the rabbit hole 😅. Good luck finding a solution for this!
