### ISSUE TITLE
Enable Issue Platform for self-hosted

### ISSUE THREAD

**Issue by hubertdeng123** [getsentry/self-hosted#2269]
Looks like issue platform is rolled out elsewhere. It would be awesome to have performance issues in self-hosted!

Things to get this to work:
- [x] enable migrations for `search_issues` here: https://github.com/getsentry/snuba/blob/d7c781ee0368cc4895e92edba1d48f72e6f0d8ec/snuba/settings/settings_self_hosted.py#L22
- [x] https://github.com/getsentry/self-hosted/pull/2309

**Comment by aldy505** [comment]
3 new snuba containers?

**Comment by hubertdeng123** [comment]
> 3 new snuba containers?
😬

https://github.com/getsentry/self-hosted/issues/1763 becoming more important

**Comment by aldy505** [comment]
Also https://github.com/getsentry/snuba/issues/1670
