### ISSUE TITLE
Checking migration state failed (1146)

### ISSUE THREAD

**Issue by Jerry805** [getsentry/self-hosted#2270]
### Self-Hosted Version

23.6.2

### CPU Architecture

x86_64

### Docker Version

not use docker

### Docker Compose Version

not use docker compose

### Steps to Reproduce

1. pip install sentry
2. sentry init
3. change database to mysql
4. sentry upgrade
Checking migration state failed with: (1146, "Table 'sentry.django_migrations' doesn't exist")
Error: Could not determine migration state. Aborting

### Expected Result

init database success

### Actual Result

Checking migration state failed with: (1146, "Table 'sentry.django_migrations' doesn't exist")
Error: Could not determine migration state. Aborting

**Comment by azaslavsky** [comment]
You are not downloading the self-hosted repository - `pip install sentry` downloads mainline Sentry (ie, the code that is used to run the SaaS offering) instead.

More broadly - what are you trying to do here? Do you have an already working install of Sentry, or are you trying to start from scratch? If it's the former, this is way outside of our supported workflow (we only support using Docker + Postgres, not ??? + MySQL). If it's the latter, you should use the supported workflow described [here](https://github.com/getsentry/self-hosted#installation).

Have you tried to use the Postgres + Docker setup?

**Comment by Jerry805** [comment]
I use Postgres + Python, not with Docker. I will uninstall and reinstall sentry in docker with postgres. thanks for the response.
