### ISSUE TITLE
Github App integration - Release not created

### ISSUE THREAD

**Issue by acuD1** [getsentry/self-hosted#2273]
### Self-Hosted Version

23.6.2

### CPU Architecture

x86_64

### Docker Version

24.0.4

### Docker Compose Version

2.19.1

### Steps to Reproduce

1. Create a Github App
2. Install Github App
3. Push commit
4. Check releases

### Expected Result

Release should be displaying

### Actual Result

No releases are created. If I understand correctly the Github App should send the events to sentry with the actuals tags for releases right  ?

Thank you

**Comment by azaslavsky** [comment]
The GitHub integration doesn't support this feature. It is mainly used for automatic issue creation from Sentry errors -> GitHub Issues, and for importing the source repository for features like Suspect Commits. The recommended way to match a range of commits to the concept of a release is to [associate commits](https://docs.sentry.io/product/releases/associate-commits) using the `sentry-cli`.
