### ISSUE TITLE
unknown error with hitting of api

### ISSUE THREAD

**Issue by namrathapandey** [getsentry/self-hosted#2286]
### Self-Hosted Version

23.3.0

### CPU Architecture

x86_64

### Docker Version

23.0.1

### Docker Compose Version

1.25.0

### Steps to Reproduce

login to sentry with email and password

### Expected Result

it should allow me to login to sentry

### Actual Result

error with below response

It looks like you've hit an issue in our server API. Don't worry though! We use Sentry to monitor Sentry and it's likely we're already looking into this 

<img width="829" alt="image" src="https://github.com/getsentry/self-hosted/assets/140143005/72f2f0a3-2519-4788-9e77-8d0d52e546f9">

**Comment by azaslavsky** [comment]
This is a bit misleading, since we don't use Sentry to monitor your self-hosted instance - we'll do what we can to help on this issue though! :)

Can you look at your server logs when this happens? Usually, a message like this produces a loggable server error in your docker logs.
