### ISSUE TITLE
"Your session has expired." appear frequently.

### ISSUE THREAD

**Issue by 1vicente** [getsentry/self-hosted#2292]
### Self-Hosted Version

23.1.0.dev0

### CPU Architecture

x86-64

### Docker Version

20.10.21

### Docker Compose Version

1.29.2

### Steps to Reproduce

After navigating through the system, we received the message "Your session has expired." opening multiple tabs in parallel or in a single tab. We identified that the Cookie "session_expire = 1" is injected, forcing the logout and soon after it is removed when redirected to the login route.

We tried to update to the latest version but the problem persists.

Are there any settings or limitations to mitigate this behavior?

### Expected Result

Using sentry without being disconnected frequently.

### Actual Result

![image](https://github.com/getsentry/self-hosted/assets/13755048/d7cffb9d-23a1-43f3-aed2-d03b85ed0a8f)

**Comment by hubertdeng123** [comment]
How often are you getting the `Your session has expired.`? We run our own instance and it rarely occurs after logging in.

**Comment by 1vicente** [comment]
Hello @hubertdeng123!

This happens several times during the day. A few minutes after logging in and using sentry, we are logged out.

**Comment by hubertdeng123** [comment]
That is pretty unexpected. Is this an out of the box setup of self-hosted? You mention 23.1.0.dev0

**Comment by 1vicente** [comment]
This release was received via checkout on the master branch at the time to update the self-hosted environment. After updating, the messages "Your session has expired." started.

We performed tests with an updated and clean installation and there is no logout.

Which service should we check the logs to understand the reason for this behavior?

**Comment by hubertdeng123** [comment]
I would check your `web` container logs here. Perhaps there's some information there that might be useful.
