### ISSUE TITLE
./install.sh

### ISSUE THREAD

**Issue by yysfwls** [getsentry/self-hosted#2295]
### Self-Hosted Version

git clone https://github.com/getsentry/onpremise.git

### CPU Architecture

x86_64

### Docker Version

24.0.4

### Docker Compose Version

v2.19.1

### Steps to Reproduce

run ./install.sh

### Expected Result

success

### Actual Result

.env: line 8: syntax error near unexpected token `)'
.env: line 8: `SENTRY_SECRET_KEY=tre*%#j8n48o9_)xz5ja1nf@pxxdym%y6#y!ns21v37qvdzx+3'
▶ Parsing command line ...

▶ Detecting Docker platform
Detected Docker platform is linux/amd64

▶ Initializing Docker Compose ...

▶ Setting up error handling ...
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 292B done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 transferring context: 2B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/debian:bullseye-slim
#3 DONE 4.4s

#4 [1/2] FROM docker.io/library/debian:bullseye-slim@sha256:3460d74bec6b88496cd183d7731930be55234c094f581f7dbdd96f56c1fc34d8
#4 CACHED

#5 [2/2] RUN set -x   && apt-get update   && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends jq   && apt-get clean   && rm -rf /var/lib/apt/lists/*
#5 0.150 + apt-get update
#5 0.710 Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
#5 1.758 Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
#5 7.787 Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
#5 19.54 Get:4 http://deb.debian.org/debian bullseye/main amd64 Packages [8183 kB]
#5 209.8 Ign:4 http://deb.debian.org/debian bullseye/main amd64 Packages
#5 211.1 Get:5 http://deb.debian.org/debian-security bullseye-security/main amd64 Packages [252 kB]
#5 224.9 Get:6 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [14.8 kB]
#5 226.4 Get:4 http://deb.debian.org/debian bullseye/main amd64 Packages [8183 kB]
#5 281.2 Ign:4 http://deb.debian.org/debian bullseye/main amd64 Packages
#5 281.4 Get:4 http://deb.debian.org/debian bullseye/main amd64 Packages [11.1 MB]

#5 446.3 Ign:4 http://deb.debian.org/debian bullseye/main amd64 Packages
#5 446.7 Get:4 http://deb.debian.org/debian bullseye/main amd64 Packages [11.1 MB]
#5 552.6 Ign:4 http://deb.debian.org/debian bullseye/main amd64 Packages
#5 553.1 Ign:4 http://deb.debian.org/debian bullseye/main amd64 Packages
#5 553.5 Err:4 http://deb.debian.org/debian bullseye/main amd64 Packages
#5 553.5   Connection timed out [IP: 151.101.110.132 80]
#5 553.5 Fetched 476 kB in 9min 13s (859 B/s)
#5 553.5 Reading package lists...
#5 553.5 E: Failed to fetch http://deb.debian.org/debian/dists/bullseye/main/binary-amd64/Packages  Connection timed out [IP: 151.101.110.132 80]
#5 553.5 E: Some index files failed to download. They have been ignored, or old ones used instead.
#5 ERROR: process "/bin/sh -c set -x   && apt-get update   && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends jq   && apt-get clean   && rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100
------
 > [2/2] RUN set -x   && apt-get update   && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends jq   && apt-get clean   && rm -rf /var/lib/apt/lists/*:
446.3 Ign:4 http://deb.debian.org/debian bullseye/main amd64 Packages
446.7 Get:4 http://deb.debian.org/debian bullseye/main amd64 Packages [11.1 MB]
552.6 Ign:4 http://deb.debian.org/debian bullseye/main amd64 Packages
553.1 Ign:4 http://deb.debian.org/debian bullseye/main amd64 Packages
553.5 Err:4 http://deb.debian.org/debian bullseye/main amd64 Packages
553.5   Connection timed out [IP: 151.101.110.132 80]
553.5 Fetched 476 kB in 9min 13s (859 B/s)
553.5 Reading package lists...
553.5 E: Failed to fetch http://deb.debian.org/debian/dists/bullseye/main/binary-amd64/Packages  Connection timed out [IP: 151.101.110.132 80]
553.5 E: Some index files failed to download. They have been ignored, or old ones used instead.
------
Dockerfile:5
--------------------
   4 |     
   5 | >>> RUN set -x \
   6 | >>>   && apt-get update \
   7 | >>>   && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends jq \
   8 | >>>   && apt-get clean \
   9 | >>>   && rm -rf /var/lib/apt/lists/*
  10 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c set -x   && apt-get update   && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends jq   && apt-get clean   && rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100

**Comment by hubertdeng123** [comment]
Not sure if you noticed, but there's a potential secret you may have leaked in your issue.
```
.env: line 8: syntax error near unexpected token )' .env: line 8: 
SENTRY_SECRET_KEY=*****
```

Otherwise, this error seems to be coming from your instance not being able to access deb.debian.org and I'd try something similar to what is described here:
https://unix.stackexchange.com/questions/710615/apt-update-unable-to-connect-to-deb-debian-org

**Comment by williamszz** [comment]
@yysfwls 
If you set "registry-mirrors" in /etc/docker/daemon.json.
Delete "registry-mirrors" and try again.

**Comment by yysfwls** [comment]
但是我遇到了另外一个问题，在执行docker-compose up -d的时候，
 ✘ Container sentry-self-hosted-web-1                                       Error                     80.6s 
 ✔ Container sentry-self-hosted-worker-1                                    Started                   49.2s 
 ✔ Container sentry-self-hosted-attachments-consumer-1                      Started                   49.1s 
 ✔ Container sentry-self-hosted-post-process-forwarder-transactions-1       Started                   49.4s 
 ✔ Container sentry-self-hosted-events-consumer-1                           Started                   48.2s 
 ✔ Container sentry-self-hosted-post-process-forwarder-errors-1             Started                   49.8s 
 ✔ Container sentry-self-hosted-sentry-cleanup-1                            Started                   48.7s 
 ✔ Container sentry-self-hosted-ingest-profiles-1                           Started                   49.9s 
 ✔ Container sentry-self-hosted-relay-1                                     Created                    0.2s 
 ✔ Container sentry-self-hosted-nginx-1                                     Created                    0.0s 
dependency failed to start: container sentry-self-hosted-web-1 is unhealthy

**Comment by yysfwls** [comment]
> @yysfwls 如果您在 /etc/docker/daemon.json 中设置“registry-mirrors”。 删除“注册表镜像”并重试。
抱歉etc/docker 下面没有找到daemon.json

**Comment by yysfwls** [comment]
还有一个疑问，我找到的教程提示我要把SENTRY_SECRET_KEY添加到.env中

**Comment by williamszz** [comment]
> 

可以尝试新建daemon.json这个文件，设置一下docker的dns：
```
{
"dns": ["114.114.114.114","8.8.8.8"]
}
```
然后重启一下docker再看看是否能解决这个问题。

**Comment by yysfwls** [comment]
还是没有解决问题，我有重新clone了一遍项目，按步骤走下来：
在执行./install.sh的时候
970.5 Ign:4 http://deb.debian.org/debian bullseye/main amd64 Packages

971.2 W: Failed to fetch http://deb.debian.org/debian/dists/bullseye-updates/InRelease  Connection timed out [IP: 151.101.110.132 80]
971.2 E: Failed to fetch http://deb.debian.org/debian/dists/bullseye/main/binary-amd64/Packages  Connection timed out [IP: 151.101.78.132 80]
971.2 W: Some index files failed to download. They have been ignored, or old ones used instead.
------
Dockerfile:5
--------------------
   4 |     
   5 | >>> RUN set -x \
   6 | >>>   && apt-get update \
   7 | >>>   && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends jq \
   8 | >>>   && apt-get clean \
   9 | >>>   && rm -rf /var/lib/apt/lists/*
  10 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c set -x   && apt-get update   && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends jq   && apt-get clean   && rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100

yum换了源下载依然很慢很慢
centOS又不是用apt

**Comment by yysfwls** [comment]
./install.sh该命令是不是只在安装的时候启动一次就好了？

**Comment by hubertdeng123** [comment]
@yysfwls were you able to get `./install.sh` to complete without errors? It only needs to be run once. If your containers are unhealthy I'd check the logs to see why. Otherwise, it might be helpful to fiddle with the healthcheck variabes in .env file if that doesn't help
