### ISSUE TITLE
sentry-self-hosted-local: pull access denied

### ISSUE THREAD

**Issue by nikserg** [getsentry/self-hosted#2302]
### Self-Hosted Version

23.7.1

### CPU Architecture

x86_64

### Docker Version

20.10.21

### Docker Compose Version

2.13.0

### Steps to Reproduce

Run `./install.sh`

### Expected Result

Sentry is installed

### Actual Result

See an error after some time of installation:

```
failed to solve: sentry-self-hosted-local: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
Error in install/build-docker-images.sh:9.
'$dcb --force-rm "$service"' exited with status 17
-> ./install.sh:main:29
--> install/build-docker-images.sh:source:9
```

**Comment by hubertdeng123** [comment]
Is this a fresh install of Sentry? Did you happen to change any variables in your `.env` file? Wondering if you're referencing the wrong docker images
