### ISSUE TITLE
Problem with install.sh - upgrade from 22.10 to 23.6.2

### ISSUE THREAD

**Issue by pbakadm** [getsentry/self-hosted#2303]
### Self-Hosted Version

22.10

### CPU Architecture

x86_64

### Docker Version

24.0.5

### Docker Compose Version

1.28.0 (tired 2.20) 

### Steps to Reproduce

Pull newest release, change env file form nightly to 23.6.2, run /.install.sh

### Expected Result

No errors :)

### Actual Result
------
> #5 [vroom-cleanup internal] load build context
> #5 transferring context: 35B done
> #5 DONE 0.0s

> #6 [vroom-cleanup 2/5] RUN if [ -z "${http_proxy}" ]; then echo "Acquire::http::proxy "${http_proxy}";" >> /etc/apt/apt.conf; fi #6 0.254 /bin/sh: can't create /etc/apt/apt.conf: nonexistent directory
> #6 ERROR: process "/bin/sh -c if [ -z \"${http_proxy}\" ]; then echo \"Acquire::http::proxy \\\"${http_proxy}\\\";\" >> /etc/apt/apt.conf; fi" did not complete successfully: exit code: 1
 > [vroom-cleanup 2/5] RUN if [ -z "${http_proxy}" ]; then echo "Acquire::http::proxy "${http_proxy}";" >> /etc/apt/apt.conf; fi:
0.254 /bin/sh: can't create /etc/apt/apt.conf: nonexistent directory
> failed to solve: process "/bin/sh -c if [ -z \"${http_proxy}\" ]; then echo \"Acquire::http::proxy \\\"${http_proxy}\\\";\" >> /etc/apt/apt.conf; fi" did not complete successfully: exit code: 1
> Error in install/build-docker-images.sh:9.
'$dcb --force-rm "$service"' exited with status 17
-> ./install.sh:main:29
--> install/build-docker-images.sh:source:9
------

### Event ID

no id

**Comment by aldy505** [comment]
Don't pull latest release and change the version to 23.6.2 manually. Instead please do this:

```bash
git fetch
git checkout 23.6.2

sudo ./install.sh
```

The latest release (right now it's 23.7.1) contains a new container that has to be configured with Vroom (Sentry's profiling backend service).

**Comment by pbakadm** [comment]
Thank you! This helped and im on 23.6.2 without errors.

Regards,
Przemek

**Comment by hubertdeng123** [comment]
Thanks @aldy505 for chiming in, was going to say the same thing. Going to close this now.
