### ISSUE TITLE
Outdated images for Zookeeper and Kafka

### ISSUE THREAD

**Issue by paulbruedgam** [getsentry/self-hosted#2304]
### Problem Statement

In the docker-compose.yaml you use two images that are very old.
- confluentinc/cp-zookeeper:5.5.7
- confluentinc/cp-kafka:5.5.7

Both are based on Debian 8, which has been EOL for three years.

### Solution Brainstorm

Please update to a newer Version such as the tags 6.0.14 or 7.4.1.

**Comment by hubertdeng123** [comment]
Definitely something we should look into doing. Thanks for filing, looks like we don't have a ticket for this yet

**Comment by malsssh** [comment]
bump

**Comment by aldy505** [comment]
Done in https://github.com/getsentry/self-hosted/pull/2988
