### ISSUE TITLE
Integrations reject self-signed certificates despite REQUESTS_CA_CERTS set correctly.

### ISSUE THREAD

**Issue by raww** [getsentry/self-hosted#2305]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce
Attempt to add an integration to Slack, Opsgenie, or similar integrations that use the shared ApiClient for integrations when running sentry in an environment with self-signed certificates inserted into external requests.
Ensure all certificate routes are correctly placed in `./certificates` as per the guidelines provided in [Sentry Self-Hosted Documentation](https://develop.sentry.dev/self-hosted/custom-ca-roots/).

### Expected Result

The integration should work seamlessly with the self-signed certificate in the certificate chain.

### Actual Result

The integration encounters errors when using prepared requests, as it does not take into account the environment settings. This can lead to SSL certificate verification failures (SSL: CERTIFICATE_VERIFY_FAILED). The use of environment variables, such as REQUESTS_CA_BUNDLE, to modify request behavior is not considered in the prepared request flow.

### Product Area

Settings - Integrations

### Version

23.6.2

**Comment by hubertdeng123** [comment]
Thanks for bringing this up. I'll keep an eye out for your PR, feel free to ping me for a review

**Comment by raww** [comment]
Thanks @hubertdeng123. PR created, let me know if you need me to do anything

**Comment by hubertdeng123** [comment]
awesome, will take a look
