### ISSUE TITLE
Enable Escalating Issues

### ISSUE THREAD

**Issue by hubertdeng123** [getsentry/self-hosted#2308]
Relies on metrics infrastructure from work done to [deprecate sessions](https://github.com/getsentry/self-hosted/issues/2200). This requires no additional infrastructure to be set up for self-hosted. 

```[tasklist]
### Tasks
- [ ] notify issues team when metrics infra is in place in self-hosted
- [ ] delete feature flag for escalating issues to enable for self-hosted
```

**Comment by aldy505** [comment]
@hubertdeng123 Been a year. Is this still relevant?

**Comment by hubertdeng123** [comment]
no longer relevant
