### ISSUE TITLE
webhooks donot work with dingding, no errors returned,sentry 钉钉机器人告警失败

### ISSUE THREAD

**Issue by nicky132** [getsentry/self-hosted#2310]
### Self-Hosted Version

21.7.0

### CPU Architecture

x86_64

### Docker Version

20.10.16

### Docker Compose Version

2.6.0

### Steps to Reproduce

1、点击test-plugin,点击测试插件
2、no errors returned
<img width="909" alt="image" src="https://github.com/getsentry/self-hosted/assets/34881461/0d98e543-78c6-45bf-8aa9-706e4a6da279">

### Expected Result

webhooks work

### Actual Result

webhook donot  work

**Comment by azaslavsky** [comment]
I think we need a bit more information about this. How are you testing the webhooks? Can you share the code that is pinging "Test Results" during the test?

Also, would it be possible to upgrade to 23.7.1, just in case this is an old issue?

**Comment by azaslavsky** [comment]
Looking at the screen grab, I also notice it mentions the version as 22.9.0?
