### ISSUE TITLE
ERROR: failed to solve: base name (${BASE_IMAGE}) should not be blank

### ISSUE THREAD

**Issue by LocalHeroPro** [getsentry/self-hosted#2311]
### Self-Hosted Version

newest

### CPU Architecture

x86_64

### Docker Version

24.0.5

### Docker Compose Version

1.29.2

### Steps to Reproduce

```shell
git pull
./install.sh
docker-compose --env-file .env.custom up -d
WARNING: The VROOM_IMAGE variable is not set. Defaulting to a blank string.
Creating network "sentry-self-hosted_default" with the default driver
Building clickhouse
[+] Building 0.1s (2/2) FINISHED                                                                                                              docker:default
 => [internal] load build definition from Dockerfile                                                                                                    0.0s
 => => transferring dockerfile: 71B                                                                                                                     0.0s
 => [internal] load .dockerignore                                                                                                                       0.0s
 => => transferring context: 2B                                                                                                                         0.0s
Dockerfile:2
--------------------
   1 |     ARG BASE_IMAGE
   2 | >>> FROM ${BASE_IMAGE}
   3 |     
--------------------
ERROR: failed to solve: base name (${BASE_IMAGE}) should not be blank
ERROR: Service 'clickhouse' failed to build : Build failed
```

### Expected Result

Can start containers.

### Actual Result

```shell
exit 1
```

**Comment by aldy505** [comment]
This is a similar issue with https://github.com/getsentry/self-hosted/issues/2303#issuecomment-1652814356

Additional two things:
1. Make sure you have the environment at `.env.custom` to be equal or similar than what's on `.env`.
2. You're running v1 of `docker-compose`. On v2, it's `docker compose` (with no dash). See [this link](https://docs.docker.com/compose/migrate/) for migration guide, and see [this link](https://docs.docker.com/compose/install/linux/#install-using-the-repository) for installation guide through Docker repository.

**Comment by LocalHeroPro** [comment]
I thing all is fixed by adding missing `VROOM_IMAGE=getsentry/vroom:nightly` in my `.env.custom` file,
Many thanks.
I'm closing as resolved.
