### ISSUE TITLE
Help upgrading from 9.1.2

### ISSUE THREAD

**Issue by danvaneijck** [getsentry/self-hosted#2319]
### Self-Hosted Version

9.1.2

### CPU Architecture

x86_64

### Docker Version

24.0.4

### Docker Compose Version

v2.19.1

### Steps to Reproduce

fresh install of 9.1.2
run command given in docs for manual backup

### Expected Result

it back up

### Actual Result

Error: Could not open file /sentry-data/backup/backup.json: Permission denied

**Comment by danvaneijck** [comment]
Hello, I am trying to make a backup of our companys sentry instance currently running on 9.1.2. 
I get a permission error. 

I have tried going to 21.5.0 as stated in the upgrade suggested path. but this image is broken and does not build 

DO I just give up and do a fresh install and re set up all the projects ?

**Comment by hubertdeng123** [comment]
What command are you running? Is it
`docker-compose run -v $(pwd)/sentry:/sentry-data/backup  --rm -T -e SENTRY_LOG_LEVEL=CRITICAL web export /sentry-data/backup/backup.json`

**Comment by danvaneijck** [comment]
yeah running that command gives me `Error: Could not open file /sentry-data/backup/backup.json: Permission denied`

**Comment by hubertdeng123** [comment]
You may have to do a workaround similar to what we do for our integration test then:
https://github.com/getsentry/self-hosted/blob/master/_integration-test/ensure-backup-restore-works.sh

On another note, backup/restore is pretty poorly written right now. It's on our plate to make it a better process, but for now we don't support backup/restore on different versions of Sentry. This will change in the future though.
