### ISSUE TITLE
application couldn't upload sourcemaps, and also errors on the web console for release information

### ISSUE THREAD

**Issue by howan36** [getsentry/self-hosted#2328]
### Self-Hosted Version

22.10.0

### CPU Architecture

x86_64

### Docker Version

19.03.15

### Docker Compose Version

3.8

### Steps to Reproduce

1.login sentry 
2.click on issues and spot on release 

### Expected Result

normal function

### Actual Result

Oops! Something went wrong
It looks like you've hit an issue in our client application. Don't worry though! We use Sentry to monitor Sentry and it's likely we're already looking into this!

### Event ID

{"detail":"Internal Error","errorId":"edc72b8e705f4e17ae0aad9ea386b522"}

**Comment by hubertdeng123** [comment]
Are there any logs in your `web` container that can indicate what might be going wrong?

**Comment by howan36** [comment]
errors like this:
01:38:03 [ERROR] django.request: Internal Server Error: /api/0/projects/china-digital-hub/event-booking-fe-c/ (status_code=500 request=<WSGIRequest: GET '/api/0/projects/china-digital-hub/event-booking-fe-c/'>)

**Comment by howan36** [comment]
02:00:24 [INFO] sentry.access.api: api.access (method='POST' view='sentry.api.endpoints.project_releases.ProjectReleasesEndpoint' response=500 user_id='16' is_app='True' token_type='ApiToken' is_frontend_request='False' organization_id='1' auth_id='9' path='/api/0/projects/china-digital-hub/checkout-service/releases/' caller_ip='47.110.176.49' user_agent='sentry-cli/1.67.2 github-action-release/1.4.1' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.14333534240722656 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')

**Comment by howan36** [comment]
there are also some info like the above, and likes interface with /api/0/*** couldn't be reached

**Comment by howan36** [comment]
this is the error from worker pod 03:06:17 [ERROR] sentry.lang.javascript.processor: sourcemaps.index_read_failed

**Comment by howan36** [comment]
and this is the error from relay pod:ERROR: unit mismatch on measurements.ttfb.requesttime: second

**Comment by howan36** [comment]
request POST https://sentry.ingka-system.cn/api/0/projects/china-digital-hub/ikeacn-pc-mall/releases/

**Comment by hubertdeng123** [comment]
How are you uploading sourcemaps? Is it through the CLI? It might be helpful to follow the steps here:
https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/#use-the-cli

**Comment by howan36** [comment]
we can successfully upload before, only because i upgraded new version failed, after i roll back to previous version, it happened

**Comment by howan36** [comment]
by the error id , what useful information we can get? where to find the details?

**Comment by hubertdeng123** [comment]
> we can successfully upload before, only because i upgraded new version failed, after i roll back to previous version, it happened

Which version were you using previously? What version of SDK are you using?

**Comment by howan36** [comment]
you can close it, it's because the clickhouse version, after i upgrade it ,it's solved.
