### ISSUE TITLE
"All Events" not working

### ISSUE THREAD

**Issue by futureweb** [getsentry/self-hosted#2329]
### Self-Hosted Version

23.7.2

### CPU Architecture

x86_64

### Docker Version

24.0.5

### Docker Compose Version

2.20.2

### Steps to Reproduce

1) open an issue with lot's of multiple (hundreds to thousands) events
2) click on "All Events"
3) not further Events are shown, loading indicator stays forever, lot's of 502 Errors are shown in Firefox Console

### Expected Result

All Events should be shown

### Actual Result

Docker Logs: http://futureweb.at.dev.futurecms.at/tools/sentry.log.txt

### Event ID

e8109759dfc64666be665fb45f093231
1f89a46f73e84477808ba821d61b238e

**Comment by hubertdeng123** [comment]
Can you try the solution here? It might fix things for you:
https://github.com/getsentry/self-hosted/issues/2256

**Comment by futureweb** [comment]
@hubertdeng123 - the problems sounds to be the same. But unfortunately enabling nginx proxy_buffering didn't solve the problem. 
"All Events" works if there are only a handfull (2- maybe 15) Events ... but if there are a few dozen to hundreds - it always fails to load :-/

Sentry Error logged while this happens: https://sentry.futureweb.at/share/issue/42187b51240a4c28a7fc3b883e7a6cb1/

**Comment by futureweb** [comment]
update: I've just added this config to nginx running on the root node - not the docker nginx - and now it's working?!?

# vi /etc/nginx/nginx.conf
        proxy_buffering on;
        proxy_buffer_size          128k;
        proxy_buffers              4 256k;
# service nginx restart

I thought the Docker nginx is in front of Sentry?!? Am I missing something here?

**Comment by hubertdeng123** [comment]
> update: I've just added this config to nginx running on the root node - not the docker nginx - and now it's working?!?

That sounds about right, that's what we had to do for our instance as well. 

> I thought the Docker nginx is in front of Sentry?!? Am I missing something here?

It is, but you had another nginx config active on your machine

**Comment by hubertdeng123** [comment]
Glad this fixed your issue, going to close this.
