### ISSUE TITLE
CORS and CSRF token issues

### ISSUE THREAD

**Issue by abriginets** [getsentry/self-hosted#2332]
### Self-Hosted Version

23.7.2

### CPU Architecture

x86_64

### Docker Version

Docker version 24.0.5, build ced0996

### Docker Compose Version

Docker Compose version v2.20.2

### Steps to Reproduce

1. Install self-hosted by running `./install.sh`
2. Expose web ports to the outside world
```yml
ports:
      - 80:9000/tcp
```
3. Uncomment the following lines in `sentry.conf.py`
```python
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SOCIAL_AUTH_REDIRECT_IS_HTTPS = True
```
4. Add `system.url-prefix` before `system.url-prefix-internal` in config.yml
```yml
system.url-prefix: "https://sentry.flaut.travel"
system.internal-url-prefix: "http://web:9000"
```
5. Put domain behind CloudFlare and active SSL mode "Flexible" (HTTPS between client and CloudFlare, HTTP between CloudFlare and Sentry deployment)
6. In CloudFlare admin simulate the following response headers from Sentry (Optional, but without those headers CORS error will occur)
```
Access-Control-Allow-Headers: *
Access-Control-Allow-Methods: GET,HEAD,PUT,PATCH,POST,DELETE,OPTIONS
Access-Control-Allow-Origin: https://flaut.travel
```

### Expected Result

Envelope request should succeed

I don't see any logs in Relay, web logs shows reqular INFO logs

### Actual Result

CSRF Verification Failed

**Comment by hubertdeng123** [comment]
If you don't see any logs in Relay, it's probably because your web service cannot communicate to the relay container. Perhaps there is a firewall setting preventing this? Did you modify the nginx config by any chance?

**Comment by hubertdeng123** [comment]
bad bot!

**Comment by abriginets** [comment]
@hubertdeng123 no, I didn't modify anything related to nginx.

**Comment by hubertdeng123** [comment]
I would check to make sure your web service is able to communicate with relay.

**Comment by juslintek** [comment]
Having same problem:
I had problem on ⁠self-hosted with sentry script being noop functions. But fixed this by adding:
```
JS_SDK_LOADER_DEFAULT_SDK_URL = "https://browser.sentry-cdn.com/%s/bundle.tracing.replay.debug.min.js"
```
to 
```
sentry/sentry.conf.py
```
using docker setup and then rerunning ./install.sh, I am on main branch.

But now I am having another issue, which is causing envelope to show 403, read on some github issues, that it is deprecated endpoint or something like that, though using latest bundle.

Any ideas anyone how to fix this? Response on sentry itself is 403 from web server. And when I using script provided by my self-hosted instance. It points to:
```
{{self-hosted.domain}}/api/1/envelope/?sentry_key={{project_token}}&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.64.0
```
which responds also with 403 HTTP code. But also provides this payload:
```
{"detail":"event submission rejected with_reason: Cors"}
```

**Comment by abriginets** [comment]
So I've tried to redeploy self-hosted Sentry instance and it succeded. This time I was specifying the actual domain during installation process instead of leaving it with `http://<ip-address>:9000` and setting `system.url-prefix` afterwards. Also I didn't change docker-compose config to reveal port 80 along with port 9000 for web service. I installed nginx on local machine outside of Docker and redirected all traffic to port 9000 instead. Now it's working fine. So either documentation is incomplete and changing `system.url-prefix` after the installation process is not enough for productionalizing, or opening port 80 for the outside world for web service breaks something.

**Comment by hubertdeng123** [comment]
Glad you were able to figure it out. We can add some documentation on this, since I believe the postgres db settings for `url-prefix` will overwrite the `system.url-prefix` in your config. Is that what you were experiencing?

**Comment by juslintek** [comment]
I fixed this by disabling "Verify TLS/SSL" at project settings. Do not know how, but probably I need to setup sentry self-hosted instance internals to have ssl as well as proxy nginx instance. Or it expects some other ssl certificate.

**Comment by csampaio26** [comment]
I'm also having that problem when I began using https. I have changed nginx config but not sure if that's the problem.

```
user nginx;
worker_processes auto;

error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;


events {
	worker_connections 1024;
}


http {
	default_type application/octet-stream;

	log_format main '$remote_addr - $remote_user [$time_local] "$request" '
	'$status $body_bytes_sent "$http_referer" '
	'"$http_user_agent" "$http_x_forwarded_for"';

	access_log /var/log/nginx/access.log main;

	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	reset_timedout_connection on;

	keepalive_timeout 75s;

	gzip off;
	server_tokens off;

	server_names_hash_bucket_size 64;
	types_hash_max_size 2048;
	types_hash_bucket_size 64;
	client_max_body_size 100m;

	proxy_http_version 1.1;
	proxy_redirect off;
	proxy_buffering off;
	proxy_buffer_size          128k;
	proxy_buffers              4 256k;
	proxy_busy_buffers_size    256k;
	proxy_next_upstream error timeout invalid_header http_502 http_503 non_idempotent;
	proxy_next_upstream_tries 2;

	# Must be removed to play nice with Safari, see the discussion in: getsentry/self-hosted#2285.
	proxy_hide_header Content-Disposition;

	# Remove the Connection header if the client sends it,
	# it could be "close" to close a keepalive connection
	proxy_set_header Connection '';
	proxy_set_header Host $host;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Proto $scheme;
	proxy_set_header X-Request-Id $request_id;
	proxy_read_timeout 30s;
	proxy_send_timeout 5s;

	upstream relay {
		server relay:3000;
		keepalive 2;
	}

	upstream sentry {
		server web:8000;
		keepalive 2;
	}

	server {
			listen 80;
			server_name <domain>;
			return 301 https://$host$request_uri;
	}

	server {
        listen                    443 ssl;
        server_name               <domain>;
        ssl_certificate           "/cert/live/<domain>/fullchain.pem";
        ssl_certificate_key       "/cert/live/<domain>/privkey.pem";
        ssl_protocols             TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers on;
        ssl_ciphers               "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
        ssl_ecdh_curve            secp384r1;
        ssl_session_cache         shared:SSL:10m;
        ssl_session_tickets       off;

        ssl_dhparam /certs/ssl-dhparams.pem;

        add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";
        add_header X-Content-Type-Options nosniff;
        add_header X-Frame-Options "SAMEORIGIN";

        # Load configuration files for the default server block.
        location / {
          proxy_set_header Host $http_host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-proto $scheme;
          proxy_pass http://sentry;
          proxy_http_version 1.1;
          proxy_cache_bypass $http_upgrade;
          proxy_set_header   Upgrade $http_upgrade;
          proxy_set_header   Connection keep-alive;
          # https://www.nginx.com/blog/rate-limiting-nginx/#bursts
          limit_req  zone=one <request_limit>;
        }

				location ~ ^/api/[1-9]\d*/ {
          proxy_set_header Host $http_host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-proto $scheme;
          proxy_pass http://relay;
          proxy_http_version 1.1;
          proxy_cache_bypass $http_upgrade;
          proxy_set_header   Upgrade $http_upgrade;
          proxy_set_header   Connection keep-alive;
          # https://www.nginx.com/blog/rate-limiting-nginx/#bursts
          limit_req  zone=one <request_limit>;
        }

				location /api/store/  {
          proxy_set_header Host $http_host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-proto $scheme;
          proxy_pass http://relay;
          proxy_http_version 1.1;
          proxy_cache_bypass $http_upgrade;
          proxy_set_header   Upgrade $http_upgrade;
          proxy_set_header   Connection keep-alive;
          # https://www.nginx.com/blog/rate-limiting-nginx/#bursts
          limit_req  zone=one <request_limit>;
        }
    }
}

```

**Comment by azaslavsky** [comment]
@csampaio26 saw you marked this as closed, as the other issue you opened addresses your case more directly.
