### ISSUE TITLE
in centos7 install fail

### ISSUE THREAD

**Issue by akbloom** [getsentry/self-hosted#2337]
### Self-Hosted Version

23.7.2

### CPU Architecture

x86_64

### Docker Version

24.0.5

### Docker Compose Version

2.20.2

### Steps to Reproduce

1、clone to disk
2、chmod -R 777 ...path/install.sh
3、sudo ...path/install.sh
4、waiting...........

### Expected Result

install success

### Actual Result

error info :
read tcp 10.1.101.149:57572->104.18.125.25:443: read: connection reset by peer
Error in install/ensure-relay-credentials.sh:27.
'$dc pull relay' exited with status 18
-> ./install.sh:main:26
--> install/ensure-relay-credentials.sh:source:27
Cleaning up...

**Comment by hubertdeng123** [comment]
This sounds like a networking issue to me. I'd look into your firewall settings or network rules that you've set up.

**Comment by akbloom** [comment]
> This sounds like a networking issue to me. I'd look into your firewall settings or network rules that you've set up.
fire-wall is closed and proxy is ok
and 
when install again , new error is 
`read tcp 10.1.101.149:48840->104.18.122.25:443: read: connection reset by peer
Error in install/ensure-relay-credentials.sh:27.
'$dc pull relay' exited with status 18
-> ./install.sh:main:26
--> install/ensure-relay-credentials.sh:source:27

error: The subcommand 'send-envelope' wasn't recognized
	Did you mean 'send-event'?

If you believe you received this message in error, try re-running with 'sentry-cli -- send-envelope'

USAGE:
    sentry-cli <SUBCOMMAND>

For more information try --help`

**Comment by azaslavsky** [comment]
Can you run `sentry-cli --version` from a terminal and post the result? Its possible you have a very old `sentry-cli` installed.
