### ISSUE TITLE
API create trusted relay permissions denied

### ISSUE THREAD

**Issue by weestack** [getsentry/self-hosted#2338]
### Self-Hosted Version

23.7.2

### CPU Architecture

X86_64

### Docker Version

24.0.5

### Docker Compose Version

2.20.2

### Steps to Reproduce

Trying to auto create trusted_relay servers with api call.

We have 100+ servers, where puppet setup relay with docker compose on all production webservers, so far the auto config and auto generated config/credentials.json works fine, however when I try to use an auth token with full permissions to create a trusted relay I get permissions denied.

REQUEST:
`curl -X PUT -H 'Authorization: Bearer <auth_token>'  https://<selfhosted_FQDN>/api/0/organizations/<org_name>/ \
-d '{ "trustedRelays": [ { "name": "srv132", "publicKey": "<public_relay_key>", "description": "srv132" } ] }'`

RESPONSE:
`{"detail":"You do not have permission to perform this action."}%`

All other api calls works as expected, for example the below will give me a list of all trusted relays:
`curl -H 'Authorization: Bearer <auth_token>' https://<selfhosted_FQDN>/api/0/projects/`

Permissions of auth token:
![image](https://github.com/getsentry/self-hosted/assets/25548462/1bbabb58-9ad2-4c63-b80a-f78951a1da6f)

### Expected Result

Expect the trusted_relay to be created for my organization

### Actual Result

`{"detail":"You do not have permission to perform this action."}%`

**Comment by hubertdeng123** [comment]
Wondering if this is a self-hosted specific issue or if this exists on SaaS as well.

**Comment by hubertdeng123** [comment]
Just checked SaaS, don't think it is an issue there. Unless I'm doing something different. Are there any logs in your `web` or `relay` containers that could be useful to debug?

**Comment by weestack** [comment]
@hubertdeng123 no there are no helpfull logs in this matter, the logs just return 403.
However what I posted is a user token with all permissions, it turns out that if you make a custom integration that have org:admin then that token is allowed to update the allowed relays.

**Comment by hubertdeng123** [comment]
> Actually if you cant reproduce it, can the problem be that I am only admin of the organization and not owner?
I will test that out and update this post, its not really an issue on my end any more as a custom integration did the job, but it would still be good to disclose it if someone else comes by with the same issue.

Interesting, please keep me posted since this may be the case.
