### ISSUE TITLE
Sentry Upgrade Failure from 22.11.0 to 23.6.2

### ISSUE THREAD

**Issue by anedd1** [getsentry/self-hosted#2339]
### Self-Hosted Version

22.11.0

### CPU Architecture

x86_64

### Docker Version

20.10.17

### Docker Compose Version

2.5.0

### Steps to Reproduce

```
cd /data/sentry
cat .env
```

Navigate into your terminal and the directory storing sentry then read the contents of the .env file to locate the VROOM_IMAGE variable 

### Expected Result

You should see a variable VROOM_IMAGE in the .env file:
`VROOM_IMAGE=getsentry/vroom:23.6.2`\

### Actual Result

The variable VROOM_IMAGE does not exist in our .env file. See attachment for more details. 

![env](https://github.com/getsentry/self-hosted/assets/142046457/a65e5658-a27f-4a4c-b69b-5dde4c7b780a)

**Comment by hubertdeng123** [comment]
How are you upgrading to 23.6.2? is it by checking out the tag? Or downloading the binary?
