### ISSUE TITLE
Debugging remote sourcemap issues

### ISSUE THREAD

**Issue by ingria** [getsentry/self-hosted#2342]
### Self-Hosted Version

23.8.0.dev0

### CPU Architecture

x86_x64

### Docker Version

24.0.4

### Docker Compose Version

24.0.4

### Steps to Reproduce

I'm using [webpack source maps plugin](https://webpack.js.org/plugins/source-map-dev-tool-plugin/), the `noSources` option is turned off.

The script location is `https://cdn.host/js/my-script.js`. 

In the end of the script there's a line:

```
//# sourceMappingURL=https://some-other.host/js/my-script.js.map
```

If I change the source map location to relative path, everything works fine.

In my web server logs I don't see any requests to *.map files from my Sentry instance. I assume that the Sentry instance cannot extract the sourceMappingURL from my .js script.

How can I debug that? Where are the source map parser logs located? `sentry-self-hosted-symbolicator` doesn't show any logs at all.

### Expected Result

Everything works fine

### Actual Result

Sentry doesn't see source maps

**Comment by hubertdeng123** [comment]
I'd check to see if the appropriate network requests are going out from your Sentry instance to make sure your Sentry instance is fetching your source maps. Are there any requests logged in your nginx container?

**Comment by ingria** [comment]
I've rechecked all my infrastructure for the possible errors, but the problem still persists. Interestingly, sourcemaps.io doesn't show any errors:

![sentry](https://github.com/getsentry/self-hosted/assets/2178368/da5780ef-f736-4d93-9bbf-94eed1c77112)
 
I can see the requests from sourcemaps.io backend in my logs, but I still cannot see any request logs from my sentry instance. Is there any way I can view the debug log for source map fetcher script in Sentry container, to see why exactly it stumbles?

**Comment by hubertdeng123** [comment]
Sorry for the late response. Have you by chance tried using https://www.npmjs.com/package/@sentry/webpack-plugin?

**Comment by ingria** [comment]
Yes, I’ve ended up using the webpack plugin

**Comment by hubertdeng123** [comment]
Is it working for you?

**Comment by ingria** [comment]
Not as good as the automatic source map fetching. Some files are still displayed obfuscated

**Comment by hubertdeng123** [comment]
Got it, I'm not sure if this helps but you can set the log level through `SENTRY_LOG_LEVEL` to be more verbose by using `INFO` or `DEBUG`. Perhaps more information may be found in your logs that way that can help?

**Comment by ingria** [comment]
The problem is that I don't know what container should I look at. There are 33 containers and they constantly produce a lot of logs even on INFO level.

**Comment by hubertdeng123** [comment]
It should be in your web or symbolicator containers, so you're looking at the right spots.
