### ISSUE TITLE
Fail to reload nginx in install.sh

### ISSUE THREAD

**Issue by marin-h** [getsentry/self-hosted#2343]
### Self-Hosted Version

23.6.2

### CPU Architecture

x86_64

### Docker Version

20.10.23

### Docker Compose Version

2.20.2

### Steps to Reproduce

Run install.sh and tail the install log file.

### Expected Result

Docker compose up command should start nginx container, and then nginx service in the container should reload without errors.

### Actual Result

I am getting this error:
```
 Container sentry-self-hosted-sentry-cleanup-1  Started
 Container sentry-self-hosted-ingest-profiles-1  Started
service "nginx" is not running
Error in install/wrap-up.sh:7.
'$dc exec -T nginx nginx -s reload' exited with status 1
```

I think it's because of this:
```
  # Start the whole setup, except nginx and relay.
  $dc up -d --remove-orphans $($dc config --services | grep -v -E '^(nginx|relay)$')
  $dc exec -T nginx service nginx reload # --> this line fails, because we skip starting nginx in the prev line
```

**Comment by hubertdeng123** [comment]
I'm not able to reproduce this, nginx should've been started in the first place so I'm wondering why it wasn't in the first place. If you remove nginx here:
`  $dc up -d --remove-orphans $($dc config --services | grep -v -E '^(nginx)$')`

Do you still get this issue?
