### ISSUE TITLE
Sentry Upgrade from v9.1.2

### ISSUE THREAD

**Issue by rajivmucheli** [getsentry/self-hosted#2350]
### Self-Hosted Version

Self hosted 9.1.4

### CPU Architecture

x86_64

### Docker Version

20.10.17

### Docker Compose Version

k8s

### Steps to Reproduce

Hi,

Its been a long time since i upgraded my self-hosted version from v9.1.2. i looked into online docu but wasnt able to validate which version of dependent versions are compatible, for example, compatible version of postgres, relay is required to upgrade to v21.5.0 based on the below doc :

https://develop.sentry.dev/self-hosted/releases/#hard-stops

I had issues processing events based on the relay service mode :

https://github.com/sapcc/helm-charts/commit/94bde5d70423c5804e44296c58a68301b0eab959
https://github.com/sapcc/helm-charts/commit/77d6a815293e7e4f0ef13b67f3e72a0c7150f797

Looking for all possible help to upgrade my current self-hosted env to the latest release.

### Expected Result

easy upgrade to the latest sentry version.

### Actual Result

Relay mode is not compatible

**Comment by hubertdeng123** [comment]
Are you using the docker compose version of Sentry? Or a third party helm charts?

**Comment by rajivmucheli** [comment]
It’s
https://github.com/sapcc/helm-charts/tree/master/system/sentry

**Comment by rajivmucheli** [comment]
We use the sentry provided containers.

 pull it from docker hub > add some customisations and certs > manage them
using this in-house helm chart :

https://github.com/sapcc/helm-charts/tree/master/system/sentry

**Comment by hubertdeng123** [comment]
That is not officially support by us. I'm not quite sure what the upgrade process is there. You can take a look at the versions of relay and postgres here:
https://github.com/getsentry/self-hosted/tree/864e184e3b0712a735b898d9e9853fd17a44a474
