### ISSUE TITLE
Not able to delete and discard future issues on my installation

### ISSUE THREAD

**Issue by bellini666** [getsentry/self-hosted#2352]
### Self-Hosted Version

23.8.0

### CPU Architecture

x86_64

### Docker Version

24.0.5,

### Docker Compose Version

1.29.2

### Steps to Reproduce

This is my `SENTRY_FEATURES` from my `sentry.conf.py` file:

```python
SENTRY_FEATURES["projects:sample-events"] = False
SENTRY_FEATURES.update(
    {
        feature: True
        for feature in (
            "organizations:discover",
            "organizations:events",
            "organizations:global-views",
            "organizations:incidents",
            "organizations:integrations-issue-basic",
            "organizations:integrations-issue-sync",
            "organizations:invite-members",
            "organizations:metric-alert-builder-aggregate",
            "organizations:sso-basic",
            "organizations:sso-rippling",
            "organizations:sso-saml2",
            "organizations:performance-view",
            "organizations:advanced-search",
            "organizations:session-replay",
            "organizations:issue-platform",

            "organizations:monitors",
            "organizations:artifact-bundles",
            "organizations:derive-code-mappings",
            "organizations:commit-context",
            "organizations:profiling",
            "organizations:profiling-flamegraphs",
            "organizations:profiling-ui-frames",
            "organizations:profiling-aggregate-flamegraph",
            "organizations:profiling-previews",
            "organizations:profiling-span-previews",
            "organizations:profiling-using-transactions",
            "organizations:grouping-tree-ui",
            "organizations:grouping-stacktrace-ui",
            "organizations:metrics",
            "organizations:dashboards-mep",
            "organizations:enterprise-perf",
            "organizations:integrations-codeowners",
            "organizations:scaleable-codeowners-search",
            "organizations:performance-anomaly-detection-ui",
            "organizations:performance-span-histogram-view",
            "organizations:related-events",

            "projects:suspect-resolutions",
            "projects:custom-inbound-filters",
            "projects:data-forwarding",
            "projects:discard-groups",
            "projects:plugins",
            "projects:rate-limits",
            "projects:servicehooks",
        )
    }
)
```

Also, I'm reporting this now but have seen this issue for a while (it is not related to the current version only)

### Expected Result

Clicking to delete and discard future events to work

### Actual Result

It tells me that the feature is not enabled on my installation:

![Screenshot from 2023-08-17 12-46-36](https://github.com/getsentry/self-hosted/assets/134025/3bf8f97b-5b93-4270-b860-b0147cb0840e)

**Comment by hubertdeng123** [comment]
Will need to take a look into this. Thanks for bringing it up

**Comment by gee-forr** [comment]
Hey there - chiming in to mention that I've got the same problem. Unable to delete and discard future events as well. Sentry shows the same config advice in the dialog just like the screenshot 👆🏻 .

I've double-checked that the feature is indeed enabled inside the running sentry container's `sentry.conf.py`.

I'm running the latest sentry self-hosted release as of January 12th (`Sentry 24.1.0.dev0`).

Please let me know if there's anything I can do to help with info or debugging this.

Thank you so much for this amazing software.

**Comment by hubertdeng123** [comment]
I am going to close this out as a duplicate for https://github.com/getsentry/sentry/issues/57162

That seems to be the more active ticket here.
