### ISSUE TITLE
issue.category:error  is ineficient

### ISSUE THREAD

**Issue by ecxod** [getsentry/self-hosted#2356]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

selecting "issue.category:error"  still shows warnings

### Expected Result

not see warning

### Actual Result

shows warnings

### Product Area

Issues

### Version

23.7.2

**Comment by hubertdeng123** [comment]
I'm going to need more details from you to attempt to reproduce this. Is this the filter on the issues page? If so, then it is working for me :/
