### ISSUE TITLE
"23.5.2" to "23.6.0" events-consumer container restarting loop (Broker: Offset out of range (broker 1001))

### ISSUE THREAD

**Issue by hatam-abolghasemi** [getsentry/self-hosted#2358]
### Self-Hosted Version

23.6.0

### CPU Architecture

x86_64

### Docker Version

24.0.5

### Docker Compose Version

2.20.2

### Steps to Reproduce

So i had sentry 23.4.0 working all fine and ok and i wanted to upgrade to the latest (23.8.0) and i had read hard stops (23.6.2) and skips (23.7.0) and for more careful process i decided to update like this: 23.4.0 -> 23.4.2 -> 23.5.2 -> 23.6.2 -> 23.7.2 -> 23.8.0
Everything was going well until 23.6.2 i noticed one container "events-consumer" status is restarting. docker logs output was as follows:
```
arroyo.errors.OffsetOutOfRange: KafkaError{code=_AUTO_OFFSET_RESET,val=-140,str="fetch failed due to requested offset not available on the broker: Broker: Offset out of range (broker 1001)"}
06:31:47 [ERROR] arroyo.processing.processor: Caught exception, shutting down...
06:31:47 [INFO] arroyo.processing.processor: Closing <arroyo.backends.kafka.consumer.KafkaConsumer object at 0x7fd2d98bf670>...
06:31:47 [INFO] arroyo.processing.processor: Partitions to revoke: [Partition(topic=Topic(name='ingest-events'), index=0)]
06:31:47 [INFO] arroyo.processing.processor: Partition revocation complete.
```
So i thought may be it was fixed in the future updates and kept on going up to 23.8.0 but the container was still in restart loop. after a little research i noticed that after 23.6.0 the old "ingest-consumer" container was split into three containers which 2 of them work correctly but the "events-consumer" couldn't stay up & running. 
I tried "https://develop.sentry.dev/self-hosted/troubleshooting/#kafka" solutions and compared the LAG value of "ingest-consumer ingest-events" time to time and it was changing between 5000 and 15000. the vm has 10 core cpu and 32GB memory. i monitored the resource usage with zabbix and docker stats and made sure that it's not resource limit issue. the docker-compose also didn't define any limit for it.

Thanks in advance for your help.

### Expected Result

events-consumer container not failing.

### Actual Result

```
arroyo.errors.OffsetOutOfRange: KafkaError{code=_AUTO_OFFSET_RESET,val=-140,str="fetch failed due to requested offset not available on the broker: Broker: Offset out of range (broker 1001)"}
06:31:47 [ERROR] arroyo.processing.processor: Caught exception, shutting down...
06:31:47 [INFO] arroyo.processing.processor: Closing <arroyo.backends.kafka.consumer.KafkaConsumer object at 0x7fd2d98bf670>...
06:31:47 [INFO] arroyo.processing.processor: Partitions to revoke: [Partition(topic=Topic(name='ingest-events'), index=0)]
06:31:47 [INFO] arroyo.processing.processor: Partition revocation complete.
```

**Comment by hubertdeng123** [comment]
Seems like an issue that was happening here that was similar:
https://github.com/getsentry/self-hosted/issues/1894

I added `--no-strict-offset-reset` option to avoid this for a lot of containers, but looks like I didn't do it for `events-consumer`. Can you try that for events-consumer?

**Comment by Aulig** [comment]
> Seems like an issue that was happening here that was similar: #1894
> 
> I added `--no-strict-offset-reset` option to avoid this for a lot of containers, but looks like I didn't do it for `events-consumer`. Can you try that for events-consumer?

I had this issue too and this worked for me :) I tried all the workarounds mentioned in that other issue but they didn't help. This finally did the trick, thanks Hubert!

**Comment by hatam-abolghasemi** [comment]
Thanks everyone. it was fixed by a new fresh update process from scratch (23.4.0) and a volume cleanup "docker volume rm sentry-kafka sentry-zookeeper sentry-symbolicator sentry-clickhouse sentry-self-hosted_sentry-vroom".
