### ISSUE TITLE
snuba-subscription-consumer-events & snuba-subscription-consumer-transactions - KeyError: 1

### ISSUE THREAD

**Issue by akpay** [getsentry/self-hosted#2359]
### Self-Hosted Version

22.8.0

### CPU Architecture

x86_64

### Docker Version

20.10.17

### Docker Compose Version

2.10.1

### Issue:

> There is no new sentry version install triggered or updates but suddenly below problem **KeyError: 1** started. I could see only external update was Certificate upgrade from Kafka (PAAS integrated AWS MSK)

> **Here is my sentry_install_log not updated for long time,**
> -rw-rw-r-- 1 root root  1407 Aug 30  2022 sentry_install_log-2022-08-30_04-33-44.txt
> -rw-rw-r-- 1 root root 70975 Aug 30  2022 sentry_install_log-2022-08-30_04-35-57.txt

### Problem:

> Container **sentry-self-hosted_snuba-subscription-consumer-events_1** & **sentry-self-hosted-snuba-subscription-consumer-transactions-1** keeps restarting with following error message

### Error:

> **sentry-self-hosted-snuba-subscription-consumer-events-1
> getsentry/snuba:22.8.0**
> 
> 2023-08-21 00:57:41,691 New partitions assigned: {Partition(topic=Topic(name='snuba-commit-log'), index=0): 151888, Partition(topic=Topic(name='snuba-commit-log'), index=1): 3961372}
> 2023-08-21 00:58:48,422 Caught KeyError(1), shutting down...
> 2023-08-21 00:58:48,422 Closing <snuba.subscriptions.scheduler_consumer.CommitLogTickConsumer object at 0x7f8ef1aa9700>...
> 2023-08-21 00:58:48,423 Partitions revoked: [Partition(topic=Topic(name='snuba-commit-log'), index=0), Partition(topic=Topic(name='snuba-commit-log'), index=1)]
> 2023-08-21 00:58:48,425 Processor terminated
> Traceback (most recent call last):
>   File "/usr/local/bin/snuba", line 33, in <module>
>     sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
>   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
>     return __callback(*args, **kwargs)
>   File "/usr/src/snuba/snuba/cli/subscriptions_scheduler_executor.py", line 163, in subscriptions_scheduler_executor
>     processor.run()
>   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 131, in run
>     self._run_once()
>   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 169, in _run_once
>     self.__processing_strategy.submit(self.__message)
>   File "/usr/src/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 252, in submit
>     self.__next_step.submit(message)
>   File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 258, in submit
>     tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
> KeyError: 1
> 
> ---------------------------------------------------------------------------------------------------------------
> 
> **sentry-self-hosted-snuba-subscription-consumer-transactions-1
> getsentry/snuba:22.8.0**
> 
> 2023-08-21 01:03:09,652 New partitions assigned: {Partition(topic=Topic(name='snuba-commit-log'), index=0): 151896, Partition(topic=Topic(name='snuba-commit-log'), index=1): 3961444}
> 2023-08-21 01:04:15,071 Caught KeyError(1), shutting down...
> 2023-08-21 01:04:15,072 Closing <snuba.subscriptions.scheduler_consumer.CommitLogTickConsumer object at 0x7f6327cd73d0>...
> 2023-08-21 01:04:15,072 Partitions revoked: [Partition(topic=Topic(name='snuba-commit-log'), index=0), Partition(topic=Topic(name='snuba-commit-log'), index=1)]
> 2023-08-21 01:04:15,077 Processor terminated
> Traceback (most recent call last):
>   File "/usr/local/bin/snuba", line 33, in <module>
>     sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
>   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
>     return __callback(*args, **kwargs)
>   File "/usr/src/snuba/snuba/cli/subscriptions_scheduler_executor.py", line 163, in subscriptions_scheduler_executor
>     processor.run()
>   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 131, in run
>     self._run_once()
>   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 169, in _run_once
>     self.__processing_strategy.submit(self.__message)
>   File "/usr/src/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 252, in submit
>     self.__next_step.submit(message)
>   File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 258, in submit
>     tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
> KeyError: 1

### Expected Result

No error

### Actual Result

> **sentry-self-hosted-snuba-subscription-consumer-events-1
> getsentry/snuba:22.8.0**
> 
> 2023-08-21 00:57:41,691 New partitions assigned: {Partition(topic=Topic(name='snuba-commit-log'), index=0): 151888, Partition(topic=Topic(name='snuba-commit-log'), index=1): 3961372}
> 2023-08-21 00:58:48,422 Caught KeyError(1), shutting down...
> 2023-08-21 00:58:48,422 Closing <snuba.subscriptions.scheduler_consumer.CommitLogTickConsumer object at 0x7f8ef1aa9700>...
> 2023-08-21 00:58:48,423 Partitions revoked: [Partition(topic=Topic(name='snuba-commit-log'), index=0), Partition(topic=Topic(name='snuba-commit-log'), index=1)]
> 2023-08-21 00:58:48,425 Processor terminated
> Traceback (most recent call last):
>   File "/usr/local/bin/snuba", line 33, in <module>
>     sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
>   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
>     return __callback(*args, **kwargs)
>   File "/usr/src/snuba/snuba/cli/subscriptions_scheduler_executor.py", line 163, in subscriptions_scheduler_executor
>     processor.run()
>   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 131, in run
>     self._run_once()
>   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 169, in _run_once
>     self.__processing_strategy.submit(self.__message)
>   File "/usr/src/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 252, in submit
>     self.__next_step.submit(message)
>   File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 258, in submit
>     tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
> KeyError: 1
> 
> ---------------------------------------------------------------------------------------------------------------
> 
> **sentry-self-hosted-snuba-subscription-consumer-transactions-1
> getsentry/snuba:22.8.0**
> 
> 2023-08-21 01:03:09,652 New partitions assigned: {Partition(topic=Topic(name='snuba-commit-log'), index=0): 151896, Partition(topic=Topic(name='snuba-commit-log'), index=1): 3961444}
> 2023-08-21 01:04:15,071 Caught KeyError(1), shutting down...
> 2023-08-21 01:04:15,072 Closing <snuba.subscriptions.scheduler_consumer.CommitLogTickConsumer object at 0x7f6327cd73d0>...
> 2023-08-21 01:04:15,072 Partitions revoked: [Partition(topic=Topic(name='snuba-commit-log'), index=0), Partition(topic=Topic(name='snuba-commit-log'), index=1)]
> 2023-08-21 01:04:15,077 Processor terminated
> Traceback (most recent call last):
>   File "/usr/local/bin/snuba", line 33, in <module>
>     sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
>   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
>     return __callback(*args, **kwargs)
>   File "/usr/src/snuba/snuba/cli/subscriptions_scheduler_executor.py", line 163, in subscriptions_scheduler_executor
>     processor.run()
>   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 131, in run
>     self._run_once()
>   File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 169, in _run_once
>     self.__processing_strategy.submit(self.__message)
>   File "/usr/src/snuba/snuba/subscriptions/scheduler_processing_strategy.py", line 252, in submit
>     self.__next_step.submit(message)
>   File "/usr/src/snuba/snuba/subscriptions/combined_scheduler_executor.py", line 258, in submit
>     tasks.extend([task for task in entity_scheduler[tick.partition].find(tick)])
> KeyError: 1

### Event ID

NA

**Comment by hubertdeng123** [comment]
Did you tweak the partition counts for topics by any chance?
