### ISSUE TITLE
Not getting events, works fine after redis restart.

### ISSUE THREAD

**Issue by prasadkris** [getsentry/self-hosted#2362]
### Self-Hosted Version

23.7.1

### CPU Architecture

x86_64

### Docker Version

Kubernetes v1.25.7

### Docker Compose Version

NA

### Steps to Reproduce

Greetings, we have got a Sentry deployment running on our Kubernetes cluster, and it works great. I have noticed an issue (happens rarely) recently in which there were no events for a few hours, and upon investigation, I noticed the following messages in the logs:

```
[ERROR] sentry.errors.events: process.failed.empty (cache_key='e:29f6f00f8f334ac5bba25da30c117219:3')
[ERROR] sentry.errors.events: process.failed.empty (cache_key='e:b8a53f91cf5b400da53b2e7f8609ae49:3')
[ERROR] sentry.errors.events: process.failed.empty (cache_key='e:585c58900ee943cfb7f8655917112765:3')
[ERROR] sentry.errors.events: process.failed.empty (cache_key='e:e8c39f9b845d4102aeb8d8e53d8da637:7')
```

I was able to fix it after resetting the redis cluster, but there were no errors in the redis logs and the resource usage was within the limit. This is not much of an issue as it happens rarely and can be solved by restarting redis, but I would like to know the possible reasons for this, so that I can investigate further and fix it. Thanks. 🙏🏻 

### Expected Result

Sentry should process events always, without issues.

### Actual Result

-

**Comment by hubertdeng123** [comment]
Here, we only officially support the docker compose version of self-hosted. We'd recommend you open an issue in the repo of the k8s setup you're using.
