### ISSUE TITLE
i get Cannot read properties of undefined (reading 'coord') error

### ISSUE THREAD

**Issue by Chengshihao1018** [getsentry/self-hosted#2363]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

i have push data to sentry and the issue page does really shows it
![image](https://github.com/getsentry/sentry/assets/31720199/d9fa37ff-227e-4058-9a6c-b4ead40ea348)

but when it comes to release page i get this 
![image](https://github.com/getsentry/sentry/assets/31720199/25d99250-ebf0-4818-816c-5394e377d39b)

and i get this error in console
![image](https://github.com/getsentry/sentry/assets/31720199/e5c8563c-e951-461b-8d71-6b36c10ba8de)

and from sentry self monitor i get this issue
![image](https://github.com/getsentry/sentry/assets/31720199/13e36ee2-ac38-46f4-a992-54d36ecc85fc)

### Expected Result

should get the result as below
![image](https://github.com/getsentry/sentry/assets/31720199/6f0d2ad1-d7f3-4bb7-b59f-47157b37b1e9)

### Actual Result

can`t get any result
![image](https://github.com/getsentry/sentry/assets/31720199/691d7429-d54b-425d-9b0b-f33a27a1ca52)

### Product Area

Releases

### Version

22.10.0

**Comment by hubertdeng123** [comment]
Wondering if this may have to do with release sessions, which is now deprecated. We're migrating to release metrics backend soon, so I don't think this is an issue that can be solved right now. See this ticket to follow along on the progress:
https://github.com/getsentry/self-hosted/issues/2200

**Comment by Chengshihao1018** [comment]
ok,it seems that the result miss upper and lower limits so the echarts throw this error.After a period of time, it can be viewed normally

**Comment by hubertdeng123** [comment]
If that's the case, is this issue resolved?

**Comment by Chengshihao1018** [comment]
When constantly pushing the data for a period of time, we can look at the picture normally.It will not affect the normal use at present.later, i will try to add limit to upper and lower to see if it works on new data.thx
