### ISSUE TITLE
[ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header

### ISSUE THREAD

**Issue by wyfaq** [getsentry/self-hosted#2367]
### Self-Hosted Version

23.8.0

### CPU Architecture

x86_64

### Docker Version

20.10.9

### Docker Compose Version

2.4.1

### Steps to Reproduce

1. start with docker-compose up -d 
2. config root url : sentry.test.cn
3. use the https://sentry.test.cn , report http_code is 400.
4. check docker-compose logs ,find errors: `sentry-self-hosted-web-1  | 08:00:46 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'sentry_ext.test.cn'. The domain name provided is not valid according to RFC 1034/1035. (status_code=400 request=<WSGIRequest: GET '/'>)`

### Expected Result

I want use domain to open the sentry website,but faild.

### Actual Result

sentry-self-hosted-web-1  | 08:00:46 [ERROR] django.security.DisallowedHost: Invalid HTTP_HOST header: 'sentry_ext.test.cn'. The domain name provided is not valid according to RFC 1034/1035. (status_code=400 request=<WSGIRequest: GET '/'>)

**Comment by azaslavsky** [comment]
Do you actually own https://sentry.test.cn/? Or is that stand in for the domain you are actually using?

**Comment by wyfaq** [comment]
django not support the domain 'sentry_ext.test.cn' ,include '-'

**Comment by azaslavsky** [comment]
I'm not sure I'm understanding your comment. Are you suggesting we expand the scope of valid URLs? I'm also still not sure which URL you are using that is causing you these problems.
