### ISSUE TITLE
Sentry returning CSRF error on SDK

### ISSUE THREAD

**Issue by csampaio26** [getsentry/self-hosted#2373]
### Self-Hosted Version

23.9.0

### CPU Architecture

x86_64

### Docker Version

20.10.23

### Docker Compose Version

2.20.3

### Steps to Reproduce

I have configured HTTPs and also changed the web ports from 9000 to 8000. Our nginx server is also outside docker-compose. Everything works fine except when using the sdk. When I run `docker-compose up -d` I can see from the web logs the following error:

`

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/connection.py", line 395, in connect
    self.ssl_context = create_urllib3_context(
  File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/util/ssl_.py", line 290, in create_urllib3_context
    context = SSLContext(ssl_version)
  File "/usr/local/lib/python3.8/ssl.py", line 483, in __new__
    self = _SSLContext.__new__(cls, protocol)
ssl.SSLError: unknown error (_ssl.c:3163)

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/transport.py", line 508, in send_envelope_wrapper
    self._send_envelope(envelope)
  File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/transport.py", line 404, in _send_envelope
    self._send_request(
  File "/usr/local/lib/python3.8/site-packages/sentry/utils/sdk.py", line 305, in patched_send_request
    return _send_request(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/transport.py", line 235, in _send_request
    response = self._pool.request(
  File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/request.py", line 78, in request
    return self.request_encode_body(
  File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/sentry/../urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sentry.tooling.systems', port=443): Max retries exceeded with url: /api/1/envelope/ (Caused by SSLError(SSLError(0, 'unknown error (_ssl.c:3163)')))
`

My nginx configuration is:

```

# For more information on configuration, see:
# * Official English Documentation: http://nginx.org/en/docs/
# * Official Russian Documentation: http://nginx.org/ru/docs/

user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

# Load dynamic modules. See /usr/share/doc/nginx/README.dynamic.
include /usr/share/nginx/modules/*.conf;
events {
    worker_connections 1024;
}
http {
    log_format main '$remote_addr-$remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';
    access_log /var/log/nginx/access.log main;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 4096;
    client_max_body_size 20M;
    
    # Allow E2E tests to bypass rate limiting (Using HTTP Header "e2e-test")
    # https://www.nginx.com/blog/rate-limiting-nginx/#Advanced-Configuration-Examples
    map $http_e2e_test $limit_key {
        0 "";
        1 $binary_remote_addr;
    }

    # https://www.nginx.com/blog/rate-limiting-nginx
    limit_req_zone $limit_key zone=one:10m rate=20r/s;
    
    # https://medium.com/@mshanak/solve-nginx-error-signin-oidc-502-bad-gateway-dotnet-core-and-identity-serve-bc27920b42d5
    proxy_buffer_size   128k;
    proxy_buffers   4 256k;
    proxy_busy_buffers_size   256k;
    large_client_header_buffers 4 16k;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Load modular configuration files from the /etc/nginx/conf.d directory.
    #See http://nginx.org/en/docs/ngx_core_module.html#include
    # for more information.
    include /etc/nginx/conf.d/*.conf;

    server {
        listen 80;
        server_name <domain>;
        return 301 https://$host$request_uri;
    }

    # Setting for a TLS enabled server.
    server {
        listen                    443 ssl;
        server_name               <domain>;
        ssl_certificate           "/etc/letsencrypt/live/<domain>/fullchain.pem";
        ssl_certificate_key       "/etc/letsencrypt/live/<domain>/privkey.pem";
        ssl_protocols             TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers on;
        ssl_ciphers               "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
        ssl_ecdh_curve            secp384r1;
        ssl_session_cache         shared:SSL:10m;
        ssl_session_tickets       off;

        ssl_dhparam /etc/ecs/user/certs/ssl-dhparams.pem;

        add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";
        add_header X-Content-Type-Options nosniff;
        add_header X-Frame-Options "SAMEORIGIN";

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;
          
        location / {
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-proto $scheme;
            proxy_pass http://127.0.0.1:8000;
            proxy_http_version 1.1;
            proxy_cache_bypass $http_upgrade;
            proxy_set_header   Upgrade $http_upgrade;
            proxy_set_header   Connection keep-alive;
        }
    
        location ~ ^/api/[1-9]\d*/ {
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-proto $scheme;
            proxy_pass http://127.0.0.1:3000;
            proxy_http_version 1.1;
            proxy_cache_bypass $http_upgrade;
            proxy_set_header   Upgrade $http_upgrade;
            proxy_set_header   Connection keep-alive;
        }
    
        location /api/store/  {
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-proto $scheme;
            proxy_pass http://127.0.0.1:3000;
            proxy_http_version 1.1;
            proxy_cache_bypass $http_upgrade;
            proxy_set_header   Upgrade $http_upgrade;
            proxy_set_header   Connection keep-alive;
        }
    }
}



```

### Expected Result

The events are received.

### Actual Result

CSRF Verification Failed

**Comment by azaslavsky** [comment]
Have you attempted to do https://github.com/getsentry/self-hosted/issues/2332#issuecomment-1689071008 for the 9000 -> 8000 port switch, or is it still pointed at 9000?

**Comment by csampaio26** [comment]
I pointed to 9000. The solution I found was enabling nginx on docker compose and do an external nginx with my certificates.

**Comment by azaslavsky** [comment]
Does that mean you've found a solution in your case? If so, I'd like to close the ticket, since I don't think this is a general problem with self-hosted.
