### ISSUE TITLE
when vist"https://sentry.hwufo.com/api/0/organizations/sentry/sdks/",return“{"detail":"Error occurred while fetching SDKs"}”

### ISSUE THREAD

**Issue by Ipanel22** [getsentry/self-hosted#2385]
### Self-Hosted Version

23.8

### CPU Architecture

x86_64

### Docker Version

20.10.6

### Docker Compose Version

2.6.0

### Steps to Reproduce

1

### Expected Result

when vist"https://sentry.hwufo.com/api/0/organizations/sentry/sdks/",return“{"detail":"Error occurred while fetching SDKs"}”

### Actual Result

1

### Event ID

1

**Comment by hubertdeng123** [comment]
Can you provide more information here? I will need to have reproduction steps in order to proceed here.
