### ISSUE TITLE
Session Replay isn't available for project prod-service. Select a project using our Sentry browser SDK package, or equivalent framework SDK.

### ISSUE THREAD

**Issue by hostinqer** [getsentry/self-hosted#2386]
### Problem Statement

![image](https://github.com/getsentry/self-hosted/assets/75067422/2728d233-8d3c-475b-a6b9-78cddd0fb236)

### Solution Brainstorm

self-hosted
Sentry 23.6.0.dev0
up in docker
hoü can İ setting session replay on self-hosted?

**Comment by hubertdeng123** [comment]
It looks like you're using a Django project. Replays is only available on Javascript based SDK's.

**Comment by hostinqer** [comment]
SOLVED!
in .env file insted of 
SENTRY_IMAGE=getsentry/sentry:23.8.0
SNUBA_IMAGE=getsentry/snuba:23.8.0
RELAY_IMAGE=getsentry/relay:23.8.0

was 
SENTRY_IMAGE=getsentry/sentry:nightly
SNUBA_IMAGE=getsentry/snuba:nightly
RELAY_IMAGE=getsentry/relay:nightly
