### ISSUE TITLE
 Can not create Jira Server Issue in issue details page of Sentry

### ISSUE THREAD

**Issue by josergenreach** [getsentry/self-hosted#2387]
### Self-Hosted Version

23.8.0

### CPU Architecture

x86_64

### Docker Version

24.0.2

### Docker Compose Version

19.1-1

### Steps to Reproduce

Click "Jira Server Issue" button on the issue details page of Sentry

### Expected Result

can create jira issue

### Actual Result

error shown:

Oops! Something went wrong
It looks like you've hit an issue in our client application. Don't worry though! We use Sentry to monitor Sentry and it's likely we're already looking into this!

If you're daring, you may want to try the following:

Give it a few seconds and reload the page.
If all else fails, contact us with more details.

![image](https://github.com/getsentry/self-hosted/assets/144357658/debc2e0c-9a77-4c57-b04d-a8c7ffbdc3e9)

**Comment by josergenreach** [comment]
I see this is similar to #2153 but I don't see how to fix it. I would appreciate your help.

Thank you.

**Comment by hubertdeng123** [comment]
Looks like the bot should not have closed that issue. I'm going to reopen the other one
