### ISSUE TITLE
Snuba replays migrations error after launch install.sh

### ISSUE THREAD

**Issue by javierviera8** [getsentry/self-hosted#2389]
### Self-Hosted Version

23.7.2 -> 23.8.0

### CPU Architecture

x86_64

### Docker Version

Docker version 24.0.6, build ed223bc

### Docker Compose Version

Docker Compose version v2.21.0

### Steps to Reproduce

Running ./install.sh

### Expected Result

Successful migrations from install.sh

### Actual Result

[error_install_sentry.txt](https://github.com/getsentry/self-hosted/files/12556369/error_install_sentry.txt)
When I attempt to upgrade from 23.7.2 to 23.8.0 sentry get stucked in snuba migrations (replay section) as you can see in error log. I tried to reverse that migration with `docker-compose --ansi never run --rm snuba-api migrations reverse --group replays --migration-id 0011_add_is_dead_rage` and again launch the migration `docker-compose run --rm snuba-api migrations migrate --force` but it still get stucked in that migrations. After this I tried to run manually the rest of migrations with success:

`docker-compose run --rm snuba-api migrations migrate --group generic_metrics --force`
`docker-compose run --rm snuba-api migrations migrate --group search_issues --force `

`system (readiness_state: complete)
[X]  0001_migrations

events (readiness_state: complete)
[X]  0001_events_initial
[X]  0002_events_onpremise_compatibility
[X]  0003_errors
[X]  0004_errors_onpremise_compatibility
[X]  0005_events_tags_hash_map
[X]  0006_errors_tags_hash_map
[X]  0007_groupedmessages
[X]  0008_groupassignees
[X]  0009_errors_add_http_fields
[X]  0010_groupedmessages_onpremise_compatibility
[X]  0011_rebuild_errors
[X]  0012_errors_make_level_nullable
[X]  0013_errors_add_hierarchical_hashes
[X]  0014_backfill_errors
[X]  0015_truncate_events
[X]  0016_drop_legacy_events
[X]  0017_errors_add_indexes
[X]  0018_errors_ro_add_tags_hash_map
[X]  0019_add_replay_id_column
[X]  0020_add_main_thread_column
[X]  0021_add_replay_id_errors_ro
[X]  0022_add_main_thread_column_errors_ro
[X]  0023_add_trace_sampled_num_processing_errors_columns
[X]  0024_add_trace_sampled_num_processing_errors_columns_ro

transactions (readiness_state: complete)
[X]  0001_transactions
[X]  0002_transactions_onpremise_fix_orderby_and_partitionby
[X]  0003_transactions_onpremise_fix_columns
[X]  0004_transactions_add_tags_hash_map
[X]  0005_transactions_add_measurements
[X]  0006_transactions_add_http_fields
[X]  0007_transactions_add_discover_cols
[X]  0008_transactions_add_timestamp_index
[X]  0009_transactions_fix_title_and_message
[X]  0010_transactions_nullable_trace_id
[X]  0011_transactions_add_span_op_breakdowns
[X]  0012_transactions_add_spans
[X]  0013_transactions_reduce_spans_exclusive_time
[X]  0014_transactions_remove_flattened_columns
[X]  0015_transactions_add_source_column
[X]  0016_transactions_add_group_ids_column
[X]  0017_transactions_add_app_start_type_column
[X]  0018_transactions_add_profile_id
[X]  0019_transactions_add_indexes_and_context_hash
[X]  0020_transactions_add_codecs
[X]  0021_transactions_add_replay_id

discover (readiness_state: complete)
[X]  0001_discover_merge_table
[X]  0002_discover_add_deleted_tags_hash_map
[X]  0003_discover_fix_user_column
[X]  0004_discover_fix_title_and_message
[X]  0005_discover_fix_transaction_name
[X]  0006_discover_add_trace_id
[X]  0007_discover_add_span_id

outcomes (readiness_state: complete)
[X]  0001_outcomes
[X]  0002_outcomes_remove_size_and_bytes
[X]  0003_outcomes_add_category_and_quantity
[X]  0004_outcomes_matview_additions
[X]  0005_outcomes_ttl
[X]  0006_outcomes_add_size_col
[X]  0007_outcomes_add_event_id_ttl_codec
[X]  0008_outcomes_add_indexes

metrics (readiness_state: complete)
[X]  0001_metrics_buckets
[X]  0002_metrics_sets
[X]  0003_counters_to_buckets
[X]  0004_metrics_counters
[X]  0005_metrics_distributions_buckets
[X]  0006_metrics_distributions
[X]  0007_metrics_sets_granularity_10
[X]  0008_metrics_counters_granularity_10
[X]  0009_metrics_distributions_granularity_10
[X]  0010_metrics_sets_granularity_1h
[X]  0011_metrics_counters_granularity_1h
[X]  0012_metrics_distributions_granularity_1h
[X]  0013_metrics_sets_granularity_1d
[X]  0014_metrics_counters_granularity_1d
[X]  0015_metrics_distributions_granularity_1d
[X]  0016_metrics_sets_consolidated_granularity
[X]  0017_metrics_counters_consolidated_granularity
[X]  0018_metrics_distributions_consolidated_granularity
[X]  0019_aggregate_tables_add_ttl
[X]  0020_polymorphic_buckets_table
[X]  0021_polymorphic_bucket_materialized_views
[X]  0022_repartition_polymorphic_table
[X]  0023_polymorphic_repartitioned_bucket_matview
[X]  0024_metrics_distributions_add_histogram
[X]  0025_metrics_counters_aggregate_v2
[X]  0026_metrics_counters_v2_writing_matview
[X]  0027_fix_migration_0026
[X]  0028_metrics_sets_aggregate_v2
[X]  0029_metrics_distributions_aggregate_v2
[X]  0030_metrics_distributions_v2_writing_mv
[X]  0031_metrics_sets_v2_writing_mv
[X]  0032_redo_0030_and_0031_without_timestamps
[X]  0033_metrics_cleanup_old_views
[X]  0034_metrics_cleanup_old_tables
[X]  0035_metrics_raw_timeseries_id

sessions (readiness_state: deprecate)
[X]  0001_sessions
[X]  0002_sessions_aggregates
[X]  0003_sessions_matview
[X]  0004_sessions_ttl

profiles (readiness_state: complete)
[X]  0001_profiles
[X]  0002_disable_vertical_merge_algorithm
[X]  0003_add_device_architecture
[X]  0004_drop_profile_column

functions (readiness_state: complete)
[X]  0001_functions
[X]  0002_add_new_columns_to_raw_functions

replays (readiness_state: complete)
[X]  0001_replays
[X]  0002_add_url
[X]  0003_alter_url_allow_null
[X]  0004_add_error_ids_column
[X]  0005_add_urls_user_agent_replay_start_timestamp
[X]  0006_add_is_archived_column
[X]  0007_add_replay_type_column
[X]  0008_add_sample_rate
[X]  0009_add_dom_index_columns
[X]  0010_add_nullable_columns
[-]  0011_add_is_dead_rage (IN PROGRESS)

generic_metrics (readiness_state: complete)
[X]  0001_sets_aggregate_table
[X]  0002_sets_raw_table
[X]  0003_sets_mv
[X]  0004_sets_raw_add_granularities
[X]  0005_sets_replace_mv
[X]  0006_sets_raw_add_granularities_dist_table
[X]  0007_distributions_aggregate_table
[X]  0008_distributions_raw_table
[X]  0009_distributions_mv
[X]  0010_counters_aggregate_table
[X]  0011_counters_raw_table
[X]  0012_counters_mv
[X]  0013_distributions_dist_tags_hash
[X]  0014_distribution_add_options
[X]  0015_sets_add_options
[X]  0016_counters_add_options
[X]  0017_distributions_mv2

search_issues (readiness_state: complete)
[X]  0001_search_issues
[X]  0002_search_issues_add_tags_hash_map
[X]  0003_search_issues_modify_occurrence_type_id_size
[X]  0004_rebuild_search_issues_with_version
[X]  0005_search_issues_v2
[X]  0006_add_subtitle_culprit_level_resource_id
[X]  0007_add_transaction_duration
[X]  0008_add_profile_id_replay_id
[X]  0009_add_message`

so the only migration that is missing is **0011_add_is_dead_rage** in replays.

If I run `docker-compose up -d` after the install I can be able to access web GUI and it shows the new version (23.8.0) but I think something can break in any moment.

Another problem I can see sometimes in install.sh is this:

 snuba.clickhouse.errors.ClickhouseError: DB::Exception: Wrong column name. Cannot find column click_title to insert after. Stack trace:

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x105351b0 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x8f4172d in /usr/bin/clickhouse
2. ? @ 0xd65026a in /usr/bin/clickhouse
3. DB::AlterCommand::apply(DB::StorageInMemoryMetadata&) const @ 0xd63feeb in /usr/bin/clickhouse
4. DB::AlterCommands::apply(DB::StorageInMemoryMetadata&) const @ 0xd641080 in /usr/bin/clickhouse
5. DB::MergeTreeData::checkAlterIsPossible(DB::AlterCommands const&, DB::Settings const&) @ 0xd8f876f in /usr/bin/clickhouse
6. DB::InterpreterAlterQuery::execute() @ 0xd0a6585 in /usr/bin/clickhouse
7. ? @ 0xd550808 in /usr/bin/clickhouse
8. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool, bool) @ 0xd553441 in /usr/bin/clickhouse
9. DB::TCPHandler::runImpl() @ 0x9024489 in /usr/bin/clickhouse
10. DB::TCPHandler::run() @ 0x9025470 in /usr/bin/clickhouse
11. Poco::Net::TCPServerConnection::start() @ 0xe3ac69b in /usr/bin/clickhouse
12. Poco::Net::TCPServerDispatcher::run() @ 0xe3acb1d in /usr/bin/clickhouse
13. Poco::PooledThread::run() @ 0x105c3317 in /usr/bin/clickhouse
14. Poco::ThreadImpl::runnableEntry(void*) @ 0x105bf11c in /usr/bin/clickhouse
15. ? @ 0x105c0abd in /usr/bin/clickhouse
16. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
17. __clone @ 0x12188f in /lib/x86_64-linux-gnu/libc-2.27.so

I can fix both problems if I remove `sentry-clickhouse` volume, but I lose my data so that is not a solution. 

It also happens from 23.7.0 to 23.7.1 and 23.7.1 to 23.7.2 (downgrade to 23.6.2 it works fine)

Any suggestions guys? Thanks ;)

**Comment by hubertdeng123** [comment]
Seems like `click_title` is apart of the migration that is failing for you.

https://github.com/getsentry/snuba/blob/master/snuba/snuba_migrations/replays/0011_add_is_dead_rage.py

The error message makes it seem like the reason it's failing is that it is already in progress 🤔
