### ISSUE TITLE
release error in the latest version of sentry

### ISSUE THREAD

**Issue by manijeh325** [getsentry/self-hosted#2391]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

I have installed python 3.9.6
postgres 13
redis 3.2.12
I want to have standard manual installation (not docker, not cloud)
I installed Sentry 23.7.1
1. release give me this issue:

![image](https://github.com/getsentry/sentry/assets/55620927/d76823ba-153c-4b8f-91c3-40b37711ce6c)

2.  in all of modules it says me unable to load tags

### Expected Result

I want not to have any issue in my on-premise installed sentry

### Actual Result

![image](https://github.com/getsentry/sentry/assets/55620927/637a5f1f-1003-4091-8a3f-056cccc60946)

### Product Area

Issues

### Version

23.7.1.

**Comment by hubertdeng123** [comment]
I am not able to reproduce this issue. We only support the docker compose version of self-hosted, and it looks like you are not using that.

**Comment by hariprasadiit** [comment]
I'm also facing similar issue. everything is working except, it shows error, `Unable to load tags`.  I'm using official docker-compose.
```
[ERROR] django.request: Internal Server Error: /api/0/organizations/vizmo/tags/ (status_code=500 request=<WSGIRequest: GET '/api/0/organizations/vizmo/tags/?statsPeriod=7d&use_cache=1&utc=false'>)
```
This is the error I'm seeing in the `web` logs.
