### ISSUE TITLE
Restore doesn't properly restore everything

### ISSUE THREAD

**Issue by androidacy-user** [getsentry/self-hosted#2394]
### Self-Hosted Version

23.7.1

### CPU Architecture

x86_64

### Docker Version

24.0.6

### Docker Compose Version

2.21.0

### Steps to Reproduce

1. Create backup with ./scripts/backup.sh
2. Restore backup on same version but different host
3. Try to login
4. See "you have no organization access"

### Expected Result

Restore works fine and so does login

### Actual Result

- logs contain about 5-6 "no sequences found" messages but nothing else of interest, no errors, nada

**Comment by azaslavsky** [comment]
A fix for this is coming in 23.9, which should land in a few days, though it will probably require making a new backup. The basic issue (among many) is that the old backup JSON file was incomplete, so rehydrating from it is basically impossible.

You can track work at getsentry/team-ospo#153.

**Comment by azaslavsky** [comment]
The backup feature is currently broken. Part of the work for the linked bug will fix it for self-hosted as well, so you are not compelled to upgrade to SaaS. The work stream for fixing this feature and for supporting easier migration to SaaS is covered by the same issue - sorry about the confusion!

> Is there any way to fix it as it is now? We're certainly not afraid to get dirty with a bit of postgresql 😁

You can certainly try to `pg_dump` your database one one machine and `pg_restore` it on the other, thoug there are no guarantees that this will work as expected.

**Comment by azaslavsky** [comment]
Sorry, just to be clear: you no longer have the original db? So the only thing remaining is the JSON backup file?

In that case, you can probably edit the JSON manually: find the user you are logging in as and set their `is_staff` and `is_superuser` flags to `True`. This should give you pretty broad admin privileges (you may still need some other permissions, but those are more complicated to setup via JSON hacking alone).

**Comment by azaslavsky** [comment]
If you do want to make this user an admin with complete privileges, you can do add something like this to the end of your import:
```
    {
        "model": "sentry.userpermission",
        "pk":  [[INCREMENT_ABOVE_GREATEREST_SENTRY_USERPERMISSION_PK]],
        "fields": {
            "user": [[DESIRED_USER]],
            "permission": "users.admin"
        }
    },
    {
        "model": "sentry.userrole",
        "pk": [[INCREMENT_ABOVE_GREATEREST_SENTRY_USERROLE_PK]],
        "fields": {
            "date_updated": "2023-06-22T23:00:00.123Z",
            "date_added": "2023-06-22T22:54:27.960Z",
            "name": "Super Admin",
            "permissions": "['broadcasts.admin', 'users.admin', 'options.admin']"
        }
    },
    {
        "model": "sentry.userroleuser",
        "pk": [[INCREMENT_ABOVE_GREATEREST_SENTRY_USERROLEUSER_PK]],
        "fields": {
            "date_updated": "2023-06-22T23:00:00.123Z",
            "date_added": "2023-06-22T22:59:57.000Z",
            "user": [[DESIRED_USER]],
            "role": [[PK_OF_USERROLE_ABOVE]]
        }
    }
  ```
  
  For example, if the user you want to be a super user is `moo@cow.com`, the greatest `sentry.userpermission` pk is 2, the greatest `sentry.userrole` pk is 5, and the greatest `sentry.userroleuser` pk is 10, you would end up with:


```
    {
        "model": "sentry.userpermission",
        "pk": 3,
        "fields": {
            "user": "moo@cow.com",
            "permission": "users.admin"
        }
    },
    {
        "model": "sentry.userrole",
        "pk": 6,
        "fields": {
            "date_updated": "2023-06-22T23:00:00.123Z",
            "date_added": "2023-06-22T22:54:27.960Z",
            "name": "Super Admin",
            "permissions": "['broadcasts.admin', 'users.admin', 'options.admin']"
        }
    },
    {
        "model": "sentry.userroleuser",
        "pk": 11,
        "fields": {
            "date_updated": "2023-06-22T23:00:00.123Z",
            "date_added": "2023-06-22T22:59:57.000Z",
            "user": "moo@cow.com",
            "role": 6
        }
    }
```

Does this help?

**Comment by azaslavsky** [comment]
> See, it does recognize me as a super admin. Just not on initial login. If I go to org settings, it shows my account as the owner and won't let me change it. But when logging in, I get "no organization access" until I click "user settings" and I can go from there

This is very odd. I'm not sure I have other suggestions without seeing the backup JSON, and even then, the tool is not in a great state at the moment, so I would not be surprised if something in it was corrupted. I'm sorry - we're working hard to make this a better exeperience!

**Comment by hubertdeng123** [comment]
Sorry to hear that. We host our own version of self-hosted Sentry for internal use and for what it's worth, it's upgraded daily without issues so far so mileage definitely varies here. As mentioned above, we're trying to improve the backup/restore process so it's much more usable in the future so please be patient with us while we improve the process.
