### ISSUE TITLE
关于 geo和geoipupdate

### ISSUE THREAD

**Issue by yysfwls** [getsentry/self-hosted#2395]
### Problem Statement

我在onpremise/geoip/GeoIP.conf 目录下配置AccountID、LicenseKey、EditionIDs之后，重启了服务
但是sentry dashboards-Errors by Country 没有关于GEO的数据，所有都是no value，

其他地方，例如Performance-Transaction Summary 的USER IP 都是有值的；

### Solution Brainstorm

尝试在onpremise 安装了geoipupdate_6.0.0_darwin_amd64，修改了GeoIP.conf 并尝试执行
geoipupdate
geoipupdate -d /opt/onpremise/geoip/GeoIP.conf
都没有解决

**Comment by yysfwls** [comment]
所以我到底应不应该装geoipupdate？
系统是ubuntu x86_64
apt install geoipupdate之后自动安装了geoipupdate_5.0.0_linux_amd64.deb

**Comment by yysfwls** [comment]
还没解决 有人帮助解答吗

**Comment by hubertdeng123** [comment]
Could you please use english here so that it is easier to help out? Have you followed the instructions here?

https://develop.sentry.dev/self-hosted/geolocation/

**Comment by yysfwls** [comment]
sorry, My English is terrible；i followed the instructions, sign up for
a free MaxMind, and set AccountID LicenseKey EditionIDs GeoLite2-City.
dashboards-Errors by Country No data on GEO, all are no value，I'm sure
we have some foreign users visiting the site；
and The country code and region (such as "US (Canada) ") are not
displayed below the IP address.


Hubert Deng ***@***.***> 于2023年9月15日周五 04:15写道：

**Comment by hubertdeng123** [comment]
Responded here:
https://github.com/getsentry/self-hosted/issues/2402

It's difficult to know what is going wrong when it appears your setup is just not working properly. Are there any logs that may indicate what might be going wrong?

`docker compose logs`

**Comment by yysfwls** [comment]
> Responded here: #2402
> 
> It's difficult to know what is going wrong when it appears your setup is just not working properly. Are there any logs that may indicate what might be going wrong?
> 
> `docker compose logs`

ok , i close https://github.com/getsentry/self-hosted/issues/2402, 
Now there is only one problem with Self-Hosted Geolocation；

I created a new GeoIP.conf and configured AccountID LicenseKey EditionIDs.
Then
docker compose down
./install.sh
docker compose up -d
Check User Settings > Security > Session History. The country/region code and region are not displayed below the IP address in the table

**Comment by yysfwls** [comment]
GeoIp.conf：

![043e7d287a8f2f63d3d82073bee439b9](https://github.com/getsentry/self-hosted/assets/29426633/c3851bf7-6bb5-41b5-87ba-495ca0952754)

**Comment by hubertdeng123** [comment]
Are you sending ip addresses to Sentry? Newer SDK's don't do this by default

https://docs.sentry.io/platforms/python/data-management/sensitive-data/#personally-identifiable-information-pii

**Comment by yysfwls** [comment]
> Are you sending ip addresses to Sentry? Newer SDK's don't do this by default
> 
> https://docs.sentry.io/platforms/python/data-management/sensitive-data/#personally-identifiable-information-pii

😀感谢回复，现在我有了一些region和city的数据，但是为什么大多数显示（no value）？

**Comment by yysfwls** [comment]
> Are you sending ip addresses to Sentry? Newer SDK's don't do this by default
> 
> https://docs.sentry.io/platforms/python/data-management/sensitive-data/#personally-identifiable-information-pii

😬Thanks for the reply. Now I have some data for regions and cities, but why do most of them show no value?

**Comment by hubertdeng123** [comment]
> 😬Thanks for the reply. Now I have some data for regions and cities, but why do most of them show no value?

Most of them show no value? Can you elaborate more here?

**Comment by yysfwls** [comment]
> > 😬Thanks for the reply. Now I have some data for regions and cities, but why do most of them show no value?
> 
> Most of them show no value? Can you elaborate more here?

![dd523b1bc5465faf10da8c91f97e0d3c](https://github.com/getsentry/self-hosted/assets/29426633/11d88f92-9058-46f6-b065-c152523a5a04)

**Comment by hubertdeng123** [comment]
I'm afraid I'm not entirely sure what might be the issue here. Some people may be disabling geoip usage from their browsers so that might be it.
