### ISSUE TITLE
Weekly reports sent multiple times

### ISSUE THREAD

**Issue by pharindoko** [getsentry/self-hosted#2397]
### Self-Hosted Version

23.8.0

### CPU Architecture

x86_64

### Docker Version

20.10.23

### Docker Compose Version

2.21.0

### Steps to Reproduce

1. Activate weekly reports for your user
2. Wait for schedule interval to send weekly report

### Expected Result

I receive the weekly report scheduled on Monday only once per week.

### Actual Result

I receive the weekly reports 6 times to my mail address.
2 colleages of mine reported to me that they get the **same amount of mails** for weekly reports as well.

I run the same solution for over 2 years now. Never had this before.
I updated on 31st of August.
Received it first time Monday 04.09 and now again on 11.09.

Any idea why this happens ?

**Comment by jimmalone** [comment]
We have been having this issue as well for the past few weeks affecting multiple users.

**Comment by azaslavsky** [comment]
This was fixed a couple of weeks ago on mainline sentry: https://github.com/getsentry/sentry/issues/55141.

The fix should land in the next self-hosted release, 23.9.0. That is slated to go out next week.

**Comment by pharindoko** [comment]
> This was fixed a couple of weeks ago on mainline sentry: [getsentry/sentry#55141](https://github.com/getsentry/sentry/issues/55141).
> 
> The fix should land in the next self-hosted release, 23.9.0. That is slated to go out next week.

Sounds good :) Thanks for the reply @azaslavsky
