### ISSUE TITLE
Sentry Upgrade failed

### ISSUE THREAD

**Issue by ctgdevops** [getsentry/self-hosted#2401]
### Self-Hosted Version

22.8.0

### CPU Architecture

x86_64

### Docker Version

Docker version 24.0.6

### Docker Compose Version

Docker Compose version v2.21.0

### Steps to Reproduce

Download the 23.6.2 version from the self-hosted repository ( [23.6.2] )

Unzip the file ( unzip 23.6.2.zip ), this creates a new folder self-hosted-23.6.2

Copy the contents of the self-hosted-23.6.2 folder into self-hosted-22.8.0 folder

Update the upgrade-Postgres script file (We are using Postgres 10.5)
vi install/upgrade-postgres.sh
line 3 9.6 => 10
line 7 9.6 => 10
line 9 9.6-to-14 => 10-to-14

### Expected Result

Installation without any problem

### Actual Result

 Ensuring proper PostgreSQL version ...
sentry-postgres-new
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/14/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/14/data -l logfile start

initdb: warning: enabling "trust" authentication for local connections You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb. Performing Consistency Checks
----
Checking cluster versions                                   ok

connection to server on socket "/var/lib/postgresql/.s.PGSQL.50432" failed: fe_sendauth: no password supplied

could not connect to source postmaster started with the command:
"/usr/lib/postgresql/10/bin/pg_ctl" -w -l "pg_upgrade_server.log" -D "/var/lib/postgresql/10/data" -o "-p 50432 -b  -c listen_addresses='' -c unix_socket_permissions=0700 -c unix_socket_directories='/var/lib/postgresql'" start
Failure, exiting
Error in install/upgrade-postgres.sh:6.
'docker run --rm -v sentry-postgres:/var/lib/postgresql/10/data -v sentry-postgres-new:/var/lib/postgresql/14/data tianon/postgres-upgrade:10-to-14' exited with status 1
-> ./install.sh:main:33
--> install/upgrade-postgres.sh:source:6

**Comment by azaslavsky** [comment]
Do you have anything in `pg_upgrade_server.log`?

**Comment by ctgdevops** [comment]
Issue is fixed
Unix domain socket connection's method was set md5. Changed to trust and the DB migration successfully.
