### ISSUE TITLE
Oops! Something went wrong

### ISSUE THREAD

**Issue by yysfwls** [getsentry/self-hosted#2402]
### Self-Hosted Version

23.7.1

### CPU Architecture

x86_64

### Docker Version

Docker 24.0.5

### Docker Compose Version

Docker Compose version v2.20.2

### Actual Result

It looks like you've hit an issue in our server API. Don't worry though! We use Sentry to monitor Sentry and it's likely we're already looking into this!

If you're daring, you may want to try the following:

Give it a few seconds and reload the page.
If all else fails, [contact us](https://github.com/getsentry/sentry/issues/new/choose) with more details.

本来是在正常运行，但是我在没有docker compose down的情况下执行了./install.sh，多次失败
最近一次./install.sh启动成功但是访问web是这样
有尝试过docker compose down和docker compose up -d重启

**Comment by yysfwls** [comment]
![Uploading 577b0862327c9797ba49aeb8844573c1.png…]()

**Comment by yysfwls** [comment]
我有尝试docker logs CONTAINER ID
但是不知道是哪一个 CONTAINER ID出问题

**Comment by yysfwls** [comment]
![Uploading b4544751b6501f00a7054f1743a3409b.png…]()

**Comment by yysfwls** [comment]
![b4544751b6501f00a7054f1743a3409b](https://github.com/getsentry/self-hosted/assets/29426633/35d46558-13c8-4c6e-aafc-74afa26c105b)

**Comment by yysfwls** [comment]
![577b0862327c9797ba49aeb8844573c1](https://github.com/getsentry/self-hosted/assets/29426633/fc8d0643-7596-4af0-9caf-ca538aade729)

**Comment by yysfwls** [comment]
![b27f08cadb75a2817b7ec1ebdd02ebc0](https://github.com/getsentry/self-hosted/assets/29426633/874f7c13-e865-485c-b8e9-7e5f75bcfccc)

尝试docker compose logs <service_name>没反应

**Comment by yysfwls** [comment]
<img width="1352" alt="9d8e75781171ba9b886273323d46a6a2" src="https://github.com/getsentry/self-hosted/assets/29426633/d5acf6fd-3ef8-46b0-8acf-e6a069736975">

（acs是我的项目名称）

**Comment by azaslavsky** [comment]
Seems like you may need to update docker: https://github.com/timescale/timescaledb-docker-ha/issues/260

**Comment by yysfwls** [comment]
> Seems like you may need to update docker: [timescale/timescaledb-docker-ha#260](https://github.com/timescale/timescaledb-docker-ha/issues/260)

my Docker version 24.0.5

**Comment by hubertdeng123** [comment]
Could you consolidate your issues into one issue instead of multiple? It's difficult to tell what's going wrong when there appears to be something wrong with your setup generally. Are there any logs that might tell us any more info?
