### ISSUE TITLE
Sending emails to Team's members when an Issue is raised doesn't work

### ISSUE THREAD

**Issue by jcpascolo** [getsentry/self-hosted#2418]
### Self-Hosted Version

23.6.2

### CPU Architecture

amazon EC2 linux x86_64

### Docker Version

24.0.5

### Docker Compose Version

v2.21.0

### Steps to Reproduce

1. Create a Team (in my case, MyTeam)
2. Invite people to the Team.
3. Create a Project (in my case, MyFlaskProject)
4. Create an alert for the project. When (A new issue is created) - if (nothing) - Then (Send a notification to Team #MyTeam and if none can be found then send a notification to All Project Members)
5. Set the owner of the alert MyTeam

### Expected Result

When a new issue arrives, an email is sent to all members of the Team

### Actual Result

Nothing. No email is sent.
The best part is, if I hit the "Send Test Notification" button, the test emails is sent to all members!

Neither work if I create an alert for the project with a "When (The issue changes state from resolved to unresolved)" but in that case the Test email also works.

In addition, in the "Preview" section when you create an alert the example issues that would have match the alert are right, so I assume that filter is not the problem.

Thanks in advance!

**Comment by hubertdeng123** [comment]
Can you check your nginx logs to see if something was sent when an alert is triggered?
