### ISSUE TITLE
!! Configuration error: ConfigurationError("sentry.tsdb service failed to call validate()\nmodule 'sentry.tsdb.redis' has no attribute 'RedisSnubaTSDB'")

### ISSUE THREAD

**Issue by LionSniper** [getsentry/self-hosted#2427]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

docker run -it --rm -e SENTRY_SECRET_KEY=${SECRET_KEY} --link sentry-postgres:postgres --link sentry-redis:redis getsentry/sentry upgrade

### Expected Result

how to resolve it, thanks

### Actual Result

docker run -it --rm -e SENTRY_SECRET_KEY=${SECRET_KEY} --link sentry-postgres:postgres --link sentry-redis:redis getsentry/sentry upgrade

!! Configuration error: ConfigurationError("sentry.tsdb service failed to call validate()\nmodule 'sentry.tsdb.redis' has no attribute 'RedisSnubaTSDB'")

### Product Area

Unknown

**Comment by hubertdeng123** [comment]
That does not seem like the correct way to run sentry. You'll need to use the docker-compose setup found here in the self-hosted repo.
