### ISSUE TITLE
The repository 'http://deb.debian.org/debian bookworm InRelease' is not signed.

### ISSUE THREAD

**Issue by zechen706** [getsentry/self-hosted#2429]
### Self-Hosted Version

latest

### CPU Architecture

x86_64

### Docker Version

20.10.4

### Docker Compose Version

2.19.1

### Steps to Reproduce

Execute ./scripts/restore.sh

### Expected Result

The installation should be successful.

### Actual Result

#1 [symbolicator-cleanup internal] load build definition from Dockerfile
#1 transferring dockerfile: 32B done
#1 DONE 0.0s

#2 [symbolicator-cleanup internal] load .dockerignore
#2 transferring context: 2B done
#2 DONE 0.0s

#3 [symbolicator-cleanup internal] load metadata for docker.io/getsentry/symbolicator:nightly
#3 DONE 0.0s

#4 [symbolicator-cleanup 1/5] FROM docker.io/getsentry/symbolicator:nightly
#4 DONE 0.0s

#5 [symbolicator-cleanup 2/5] RUN if [ -z "${http_proxy}" ]; then echo "Acquire::http::proxy "${http_proxy}";" >> /etc/apt/apt.conf; fi
#5 CACHED

#6 [symbolicator-cleanup 3/5] RUN if [ -z "${https_proxy}" ]; then echo "Acquire::https::proxy "${https_proxy}";" >> /etc/apt/apt.conf; fi
#6 CACHED

#7 [symbolicator-cleanup internal] load build context
#7 transferring context: 35B done
#7 DONE 0.0s

#8 [symbolicator-cleanup 4/5] RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
#8 0.733 Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
#8 1.189 Err:1 http://deb.debian.org/debian bookworm InRelease
#8 1.189   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131 NO_PUBKEY F8D2585B8783D481
#8 1.227 Get:2 http://deb.debian.org/debian bookworm-updates InRelease [52.1 kB]
#8 1.306 Err:2 http://deb.debian.org/debian bookworm-updates InRelease
#8 1.306   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
#8 1.397 Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
#8 1.466 Err:3 http://deb.debian.org/debian-security bookworm-security InRelease
#8 1.466   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 54404762BBB6E853 NO_PUBKEY BDE6D2B9216EC7A8
#8 1.468 Reading package lists...
#8 1.477 W: GPG error: http://deb.debian.org/debian bookworm InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131 NO_PUBKEY F8D2585B8783D481
#8 1.477 E: The repository 'http://deb.debian.org/debian bookworm InRelease' is not signed.
#8 1.477 W: GPG error: http://deb.debian.org/debian bookworm-updates InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
#8 1.477 E: The repository 'http://deb.debian.org/debian bookworm-updates InRelease' is not signed.
#8 1.477 W: GPG error: http://deb.debian.org/debian-security bookworm-security InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 54404762BBB6E853 NO_PUBKEY BDE6D2B9216EC7A8
#8 1.477 E: The repository 'http://deb.debian.org/debian-security bookworm-security InRelease' is not signed.
#8 1.477 E: Problem executing scripts APT::Update::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'
#8 1.477 E: Sub-process returned an error code
#8 ERROR: executor failed running [/bin/sh -c apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*]: exit code: 100
------
 > [symbolicator-cleanup 4/5] RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*:
1.466   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 54404762BBB6E853 NO_PUBKEY BDE6D2B9216EC7A8
1.468 Reading package lists...
1.477 W: GPG error: http://deb.debian.org/debian bookworm InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131 NO_PUBKEY F8D2585B8783D481
1.477 E: The repository 'http://deb.debian.org/debian bookworm InRelease' is not signed.
1.477 W: GPG error: http://deb.debian.org/debian bookworm-updates InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
1.477 E: The repository 'http://deb.debian.org/debian bookworm-updates InRelease' is not signed.
1.477 W: GPG error: http://deb.debian.org/debian-security bookworm-security InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 54404762BBB6E853 NO_PUBKEY BDE6D2B9216EC7A8
1.477 E: The repository 'http://deb.debian.org/debian-security bookworm-security InRelease' is not signed.
1.477 E: Problem executing scripts APT::Update::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'
1.477 E: Sub-process returned an error code
------
failed to solve: executor failed running [/bin/sh -c apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*]: exit code: 100
Error in install/build-docker-images.sh:9.
'$dcb --force-rm "$service"' exited with status 17
-> ./install.sh:main:29
--> install/build-docker-images.sh:source:9

Looks like you've already sent this error to us, we're on it :)

**Comment by hubertdeng123** [comment]
Which version of self-hsoted Sentry are you on? The latest version? Do you mean nightly or 23.9.1?

**Comment by zechen706** [comment]
23.9.1-2-geda2ab6

**Comment by hubertdeng123** [comment]
That's interesting. You may need to play around with the Dockerfile. Maybe this is helpful?

https://forums.debian.net/viewtopic.php?t=155019

Otherwise, I am not able to reproduce this.

**Comment by jarro** [comment]
Ran into this, ended up having to upgrade docker to get past the 1.41 api version requirement later in the script.  And after that this issue disappeared.

**Comment by zechen706** [comment]
i upgrade docker to 24.0.6 ，sentry can be installed successfully。 thanks！ @jarro @hubertdeng123
