### ISSUE TITLE
Shared volumes on consumers

### ISSUE THREAD

**Issue by luckyraul** [getsentry/self-hosted#2433]
### Problem Statement

I have migrated this setup to nomad cluster two months ago. 

Firstly it wasn't so hard as I imagined. Recently I started a version upgrade and I've noticed that so many consumers I need to create. I have noticed that snuba consumers do not have any volume attached so they can work on any host in a cluster.  However Sentry consumers use &sentry_defaults and require it. I can understand that the core services really need data volume attached but I can't imagine that everything requires it.

Do all sentry consumers need to have access to sentry-data volume?  If not, It should be refactored. I can't keep all of containers just on one host there I bind the volume.

### Solution Brainstorm

Refactor sentry_defaults in docker-compose

**Comment by hubertdeng123** [comment]
Interesting use case you have there. It's possible that not all containers need access to the data volume, but I'm not sure exactly which ones since there are so many consumers now. Have you tried to unattach the data volumes from the Sentry consumers?

**Comment by luckyraul** [comment]
No,  I haven't. 

Actually my data folder contains only empty folder ```files```.

**Comment by azaslavsky** [comment]
Are you observing any notable performance issues from this setup? I'm not 100% that snuba never uses this data - my guess is that there are scenarios where it persists data, necessitating these volumes.

**Comment by luckyraul** [comment]
My question is about x-sentry-defaults. x-snuba-defaults  has no volume attachments. 

The biggest my concern about performance is that I need to allocate all resources on same volume=host(for my setup). Also amount of consumers is growing and I need to allocate more and more RAM and cpu.

**Comment by azaslavsky** [comment]
We're sorry about the growth in containers - we're thinking about how to consolidate these going forward, and making things a bit less resource intensive. In the meantime, I'd recommend not adjusting the default volume attachments. Even if they don't seem like they're being used, rarely used features and future updates will assume their existence, which could cause breakages down the line.
