### ISSUE TITLE
Errors When Upgrading to 23.5.2 and Newer

### ISSUE THREAD

**Issue by mencarellic** [getsentry/self-hosted#2435]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

So, when upgrading from `23.4.0`, I neglected to check the [hard stops](https://develop.sentry.dev/self-hosted/releases/#hard-stops) documentation (which TIL about) and saw some failures to upgrade. It appears that we can't get to version `23.5.2` no matter what we try, so before going to far, I'm reaching out here for assistance. 

1. Upgrade from `23.4.0` to `23.9.1`
2. Failure occurs
3. Revert the install to `23.6.2`
4. Failure occurs
5. Revert the install to `23.5.2`
6. Failure occurs
7. Revert the install to `23.5.1`
8. Sentry works at this point

---
Additionally, we restored the database to before any of the above was done and tried going to the hard stop at `23.6.2` with the same failure

### Expected Result

Migrations and upgrade to succeed.

### Actual Result

There are no errors in the installation until the migrations are being run, at which point we consistently get:

```
Running migrations:
  Applying sentry.0465_pickle_to_json_sentry_activity...Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sentry/db/models/fields/gzippeddict.py", line 35, in to_python
    return json.loads(value)
  File "/usr/local/lib/python3.8/site-packages/sentry/utils/json.py", line 138, in loads
    return _default_decoder.decode(value)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
22:26:57 [ERROR] sentry.runner.initializer: django.compat.model-unpickle-compat (model_id=('sentry', 'Release') attrs=[] factory=<function __simple_class_factory_compat at 0x7eff2c25f8b0>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sentry/db/models/fields/gzippeddict.py", line 35, in to_python
    return json.loads(value)
  File "/usr/local/lib/python3.8/site-packages/sentry/utils/json.py", line 138, in loads
    return _default_decoder.decode(value)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
22:26:57 [ERROR] sentry.runner.initializer: django.compat.model-unpickle-compat (model_id=('sentry', 'Project') attrs=[] factory=<function __simple_class_factory_compat at 0x7eff2c25f8b0>)
22:26:57 [INFO] sentry_sdk.errors: event processor (<function DedupeIntegration.setup_once.<locals>.processor at 0x7eff21cfedc0>) dropped event
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sentry/db/models/fields/gzippeddict.py", line 35, in to_python
    return json.loads(value)
  File "/usr/local/lib/python3.8/site-packages/sentry/utils/json.py", line 138, in loads
    return _default_decoder.decode(value)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### Product Area

Unknown

### Version

23.5.1

**Comment by mencarellic** [comment]
I have looked at [this issue](https://github.com/getsentry/self-hosted/issues/2180) as well and the approach didn't work.

**Comment by hubertdeng123** [comment]
Unfortunately, it looks like you did not go to 23.6.2 prior to upgrading to 23.9.1, so that may have corrupted your data. Do you keep a backup? Otherwise, you may need to start from scratch

**Comment by mencarellic** [comment]
Hi @hubertdeng123 Thanks for the reply.

As noted in the original issue:
> Additionally, we restored the database to before any of the above was done and tried going to the hard stop at 23.6.2 with the same failure

This was a restore to the database as it was on version 23.4.0. We then tried the upgrade to 23.6.2 with it failing at the same step.

---

Some additional info we've found while trying to debug this is that we had some old (really old, like 2016-old) data that may not have been converted right a long time ago.

For example, we had some old projects that, once we removed them, turned into errors relating to data in the `sentry_activity` table. 

When trying to unpickle the `data` column in the `sentry_activity` table manually, we see errors like:
```
AttributeError: Can't get attribute 'simple_class_factory' on <module 'django.db.models.base'
```

Research indicates this could be from an older version of Django that the newer version can no longer decode. It seems like these few thousand rows are all in the 2016 range. Newer data can be decoded fine.

This brings me to my next question: we have an event retention of 180 days. Does this indicate objects such as releases are kept forever? In the case of the data from 2016, it's all of the `RELEASE` object type (`type=10`)

**Comment by mencarellic** [comment]
We attempted to clean up these artifacts with the `sentry cleanup` command, but it did not clean these particular items up.

The next attempt was with the Djagno shell targeting the type and id range.: `Activity.objects.filter(type=10, id__gt=7570, id__lt=11095).delete()`. This unblocked us on the upgrade, and we were able to upgrade to `23.5.2` and then `23.6.2`
