### ISSUE TITLE
Wrong command flag "--skip-user-prompt" in readme file

### ISSUE THREAD

**Issue by rc5hack** [getsentry/self-hosted#2438]
### Self-Hosted Version

23.9.1

### CPU Architecture

x86_64

### Docker Version

24.0.6

### Docker Compose Version

2.20.0

### Steps to Reproduce

In current readme there is `./install.sh --skip-user-prompt` command in "[Installation](https://github.com/getsentry/self-hosted/blob/eda2ab6f609797994013e6e38379f3ab2ccb4a84/README.md#installation)" section.

`git clone` sources and run this command.

### Expected Result

Command is OK.

### Actual Result

You get deprecation warning:
```
./install.sh --skip-user-prompt
▶ Parsing command line ...
WARNING The --skip-user-prompt flag is deprecated. Please use --skip-user-creation instead.
```

**Comment by hubertdeng123** [comment]
Thanks for bringing this up, I'll put a PR up to change this.
