### ISSUE TITLE
ERROR: duplicate key value violates unique constraint

### ISSUE THREAD

**Issue by JustDoItSascha** [getsentry/self-hosted#2439]
Experiencing the same problem while following the https://develop.sentry.dev/self-hosted/releases/#hard-stops upgrade schema. Now on the latest version (23.8.0) and this issue occurred anyways, not immediately but just this morning (did the upgrade yesterday) ...

_Originally posted by @jsbrain in https://github.com/getsentry/self-hosted/issues/2171#issuecomment-1710005506_
          
Unfortunately the original issue is closed, but it is not solved. The same issue happened to me today. Upgraded to 23.8.0 18 days ago und just today the error happened and sentry is not working anymore for us.

What is this error and why is the original thread closed?

Edit: I'm on 23.8.0 and postgres 15.4.0.

**Comment by azaslavsky** [comment]
In what way is it "not working" for you anymore? The error you are describing is the same "duplicate unique" error described in that bug? Can you provide the rest of the information on our bug form as well (see: https://github.com/getsentry/self-hosted/issues/new?assignees=&labels=&projects=&template=problem-report.yml).

**Comment by leedongwei** [comment]
Closing this ticket because #2171 has been reopened.
