### ISSUE TITLE
Docker Volume Backup for Clickhouse Performance Issues

### ISSUE THREAD

**Issue by mencarellic** [getsentry/self-hosted#2443]
### Self-Hosted Version

23.9.1

### CPU Architecture

x86_64

### Docker Version

24.0.6

### Docker Compose Version

2.21.0

### Steps to Reproduce

Since upgrading to 23.9.1, we're seeing a significantly slow Clickhouse data volume backup.

1. Run a [full Docker volume backup]() as the [docs suggest]()
  a. `docker run --rm -v sentry-clickhouse:/data_to_backup -v /backups:/backups debian bash -c 'tar -czf /backups/sentry-clickhouse.tar.gz -C /data_to_backup .'`
2. See memory, cpu, and I/O spike.

We are running a `c5a.2xlarge` in AWS which has 8vCPU and 16GB memory on a GP3 EBS volume that's provisioned with 1000Mbps throughput and 5000IOPs

Compressed and gzipped, the volume backup is about 10GB. 

### Expected Result

Looking to see if this is an expected change or if we should be looking at alternate means to update our events data now. 

### Actual Result

Previously this would run in approximately 15 minutes; it's been taking over 30 minutes now. There are no errors or warnings in the logs during this time that relate to the backup process.

**Comment by azaslavsky** [comment]
Was memory, CPU, and I/O not spiking before when you did a backup? If anything, that's the more surprising thing - that copying the entire volume didn't affect any of these metrics.

We updated the metrics backend in 23.9.1, so for a period we have 2 running while we deprecate the old system and move onto the new one. This may have cause a jump in the number of records that need to be backed up, though I'm not entirely sure. Is 30 minutes untenable for this process on your end?

**Comment by mencarellic** [comment]
> Was memory, CPU, and I/O not spiking before when you did a backup? If anything, that's the more surprising thing - that copying the entire volume didn't affect any of these metrics.
> 
> We updated the metrics backend in 23.9.1, so for a period we have 2 running while we deprecate the old system and move onto the new one. This may have cause a jump in the number of records that need to be backed up, though I'm not entirely sure. Is 30 minutes untenable for this process on your end?

We saw some spikes, but not as persistent. 

Previously it would spike for a few minutes to the 90% resource usage range. Now it jumps to 100% and hangs out there for several minutes. This, as you can imagine, has a negative effect on Sentry.

The time it takes is not too much of an issue either. Really just the impact on usability for the several minutes of the spike and the curiosity of is this observed or expected.

**Comment by azaslavsky** [comment]
We've added more containers, and, as stated above, we are now running a couple of services in duplicate as we work to deprecate them. This may have been enough to push your resource usage to 100% for your particular instance :(

**Comment by mencarellic** [comment]
Thanks @azaslavsky 

We changed instances to one with more memory after catching a few OOM errors. Since then, everything has been stable. Previously, we were running an instance with 16GB of memory. Upon changing to an instance with more memory than that, we saw memory usage of just over 16GB which tracks with the errors we saw.

Thanks for the help.
