### ISSUE TITLE
After upgrading to 23.9.1 there is an error message in the UI: Background workers haven't checked in recently

### ISSUE THREAD

**Issue by afaianswq** [getsentry/self-hosted#2452]
### Self-Hosted Version

23.9.1

### CPU Architecture

x86_64

### Docker Version

24.0.6

### Docker Compose Version

2.21.0

### Steps to Reproduce

1. Upgrade Sentry from 23.6.2 to 23.9.1
2. Log in to UI as Admin

### Expected Result

No errors should appear at the top

### Actual Result

An error message appears at the top:

```
Background workers haven't checked in recently. It seems that you have a backlog of 371 tasks. Either your workers aren't running or you need more capacity.
```

The number of tasks keeps increasing.

There were no problems reported during the upgrade.

There are no exceptions or tracebacks in the logs except for the ones mentioned in https://github.com/getsentry/snuba/issues/4806 and https://github.com/getsentry/snuba/issues/4821 which do not seem related.

**Comment by azaslavsky** [comment]
Are you hitting any resource limits on your machine? 23.9.1 introduced some new containers, which some folks have reported to be causing higher resource usage, ex: https://github.com/getsentry/self-hosted/issues/2453

**Comment by afaianswq** [comment]
> Are you hitting any resource limits on your machine? 23.9.1 introduced some new containers, which some folks have reported to be causing higher resource usage, ex: #2453

No, I am not hitting any resource limits. Also, this happens under no load at all - no events are being submitted.

```
$ free -h
              total        used        free      shared  buff/cache   available
Mem:           15Gi       8.7Gi       244Mi       160Mi       6.5Gi       6.2Gi
Swap:            0B          0B          0B
```

**Comment by azaslavsky** [comment]
Could you try the instruction found here: https://forum.sentry.io/t/sentry-no-more-catch-errors/10500/10 (note that some of the specifics, like the name of the underlying Kafka docker container, may have changed since this was posted).

**Comment by afaianswq** [comment]
> Could you try the instruction found here: https://forum.sentry.io/t/sentry-no-more-catch-errors/10500/10 (note that some of the specifics, like the name of the underlying Kafka docker container, may have changed since this was posted).

I did that, please check my original report: https://github.com/getsentry/snuba/issues/4806

**Comment by afaianswq** [comment]
Also, it looks like the issue have self-healed over a several days. Today I don't see this error on top, and the queue overviews is displaying jobs again.

**Comment by azaslavsky** [comment]
If the issue has self-healed, and it's not causing any visible issues in your Sentry install's functionality, there doesn't seem to be much to fix here.
