### ISSUE TITLE
sentry-self-hosted-cron-1 restarting again and again and CPU load is too high

### ISSUE THREAD

**Issue by ahmedwarwani** [getsentry/self-hosted#2454]
### Self-Hosted Version

23.10.0

### CPU Architecture

x84_64

### Docker Version

20.0.5

### Docker Compose Version

2.20.3

### Steps to Reproduce

1. docker ps (up less then a second), others containers are up and running
2. docker logs sentry-self-hosted-cron-1
3. /usr/local/lib/python3.8/site-packages/memcache.py:1303: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key is '':
![image](https://github.com/getsentry/self-hosted/assets/57829549/8c917dba-7282-4200-b7ef-ed625728b23f)

### Expected Result

Sentry Up and Running with normal load

### Actual Result

Consuming very high load. 
![image](https://github.com/getsentry/self-hosted/assets/57829549/130d4eec-d9f7-4b3d-a6f1-22f1f9ef0eef)

### Event ID

.

**Comment by azaslavsky** [comment]
By 23.10.0, do you mean that you are on nightly? We have not release 23.10.0 yet.

**Comment by yorch** [comment]
@azaslavsky Same problem here, just upgraded to 23.9.1. Also seeing the extremely high CPU usage compared to 23.8.0 and before, and cron keep restarting with the same error as reported

<img width="1683" alt="image" src="https://github.com/getsentry/self-hosted/assets/60499/c17343ca-07ef-44f8-82fe-7d700071cf5e">

```
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
/usr/local/lib/python3.8/site-packages/memcache.py:1303: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key is '':
/usr/local/lib/python3.8/site-packages/memcache.py:1304: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key_extra_len is 0:
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
```

**Comment by ahmedwarwani** [comment]
> By 23.10.0, do you mean that you are on nightly? We have not release 23.10.0 yet.

Yes I'm on nightly, Is it not a recommended version? Facing too much issues on this. Can you suggest me the stable version if it's not recommended. 
Thanks

**Comment by azaslavsky** [comment]
If you turn off this job, does the CPU usage reset back to normal? Also, are you using Python 3.8?

**Comment by ahmedwarwani** [comment]
Hi @azaslavsky CPU is back to normal but some containers are keeps restarting. 

![image](https://github.com/getsentry/self-hosted/assets/57829549/d556005f-f2f0-4565-b5f6-a03564d02d38)

**Comment by ahmedwarwani** [comment]
@azaslavsky These 3 containers which I have shared above are keeps restarting and consuming the high CPU. 
sentry-self-hosted-post-process-forwarder-issue-platform-1
sentry-self-hosted-post-process-forwarder-errors-1
sentry-self-hosted-post-process-forwarder-transactions-1

**Comment by azaslavsky** [comment]
We're looking into this - I'm not 100% sure what's going on here, but it only seems to be happening on some installs, and not on our dogfood instance. Is there anything else you can tell me about these spikes? Do they occur at a certain time of day, or are otherwise associated with other odd behavior?
