### ISSUE TITLE
The query result of the interface is incorrect

### ISSUE THREAD

**Issue by yysfwls** [getsentry/self-hosted#2456]
### Self-Hosted Version

git clone https://github.com/getsentry/onpremise.git

### CPU Architecture

/

### Docker Version

/

### Docker Compose Version

/

### Steps to Reproduce

![021bec4276c9270699fede33933bc2f5](https://github.com/getsentry/self-hosted/assets/29426633/735c3bc4-084b-4a18-bc76-e715e7db0e02)
<img width="739" alt="4d94deb3840bf6305df5450feb212d26" src="https://github.com/getsentry/self-hosted/assets/29426633/7ae66641-0f7a-4186-b077-54b4f4e83d82">

### Expected Result

Consistent result

### Actual Result

The query time is 24h,
There are eight errors found by api query.
The sentry pc has four errors

**Comment by yysfwls** [comment]
![fe24123afcce6569ca09ef2360d371fa](https://github.com/getsentry/self-hosted/assets/29426633/3d96d66a-3c9c-4b20-a351-43d0a3737d06)

**Comment by yysfwls** [comment]
Has anyone seen this question? 
The query parameter is 24h, but the historical data is found

**Comment by azaslavsky** [comment]
Can you see all 8 errors if you disable the filter? Can you send a screenshot with all 8 displayed?/

**Comment by yysfwls** [comment]
> Can you see all 8 errors if you disable the filter? Can you send a screenshot with all 8 displayed?/

![c8c4dca9bb00dea89058f99b77834d76](https://github.com/getsentry/self-hosted/assets/29426633/e0873090-9b5b-4c1a-8521-926db99ae3b8)
![8d9bc785a9551c7192734f578ebb2cdb](https://github.com/getsentry/self-hosted/assets/29426633/87252639-73a7-43cb-87c3-2b7b2a87b37c)

**Comment by azaslavsky** [comment]
I'm not sure what you're showing me here - when inspecting the JSON, can you see any difference between the errors that do show up and the ones that do not? Can you paste the JSON blob you are showing in that image, with the information of the 8 errors?

**Comment by yysfwls** [comment]
> I'm not sure what you're showing me here - when inspecting the JSON, can you see any difference between the errors that do show up and the ones that do not? Can you paste the JSON blob you are showing in that image, with the information of the 8 errors?

I don't know if you noticed that the parameters in the two screenshots above are different; when querying using the interface, they both returned 8 pieces of JSON, which is the problem.
Because when directly querying on the webpage, there are only 4 entries within 24 hours

**Comment by azaslavsky** [comment]
Right, but can you show me the actual content of the JSON returned by each query?
