### ISSUE TITLE
sentry-ingest-consumer-events can't connect to external kafka in ssl

### ISSUE THREAD

**Issue by cloud-digitaltag** [getsentry/self-hosted#2459]
### Self-Hosted Version

23.6.1

### CPU Architecture

x86_64

### Docker Version

N/A

### Docker Compose Version

N/A

### Steps to Reproduce

1. Create sentry.config.py file with additional settings for Kafka
additional varaiable:
```
DEFAULT_KAFKA_OPTIONS = {
    "bootstrap.servers": "kafka-0:9094, kafka-1:9094, kafka-2:9094",
    "security.protocol": "ssl",   # <---- added ssl protocol
    "message.max.bytes": 50000000,
    "socket.timeout.ms": 1000,
}
```
2. Deploy new config
3. Check logs, still error with ssl when connecting to kafka:

### Expected Result

sentry containers(pods) connect to Kaka with TLS enabled.

### Actual Result

Logs from pod:
```
%6|1696840537.644|FAIL|rdkafka#consumer-1| [thrd:kafka-0]: kafka-0:9094/bootstrap: Disconnected while requesting ApiVersion: might be caused by incorrect security.protocol configuration (connecting to a SSL listener?) or broker version is < 0.10 (see api.version.request) (after 3ms in state APIVERSION_QUERY, 5 identical error(s) suppressed)
%6|1696840538.808|FAIL|rdkafka#consumer-1| [thrd:kafka-1]: kafka-1:9094//bootstrap: Disconnected while requesting ApiVersion: might be caused by incorrect security.protocol configuration (connecting to a SSL listener?) or broker version is < 0.10 (see api.version.request) (after 0ms in state APIVERSION_QUERY, 5 identical error(s) suppressed)
%6|1696840538.944|FAIL|rdkafka#consumer-1| [thrd:kafka-2: kafka-2:9094//bootstrap: Disconnected while requesting ApiVersion: might be caused by incorrect security.protocol configuration (connecting to a SSL listener?) or broker version is < 0.10 (see api.version.request) (after 0ms in state APIVERSION_QUERY, 5 identical error(s) suppressed)
```

When I login to pod, I see config with added variable. Maybe I do something wrong with my deploy, config ?

### Event ID

N/A

**Comment by cloud-digitaltag** [comment]
Hi, I don't use docker. Sentry is deployed on Kubernetes 1.24. 
For snuba there is no problem with enabled SSL, only pods with sentry. binary have issue to connect and relay (must be compiled with ssl)

**Comment by aldy505** [comment]
AFAIK Sentry container doesn't support Kafka's SSL + SASL. You might wanna open an issue at https://github.com/getsentry/sentry to address this (or ask the organization member to transfer this issue).

**Comment by azaslavsky** [comment]
We only offer support for using the docker-compose setup stored in this repo, not k8s - debugging every possible deployment setup would be a massive increase in scope for us, much beyond our current team size. There are other github repositories floating around that contain prototype Sentry + k8s setups - you could try asking there. Good luck!
