### ISSUE TITLE
"An unknown error occurred" in the Performance Tab after upgrading to 22.10.0 from 22.8.0

### ISSUE THREAD

**Issue by mariusmitrofan** [getsentry/self-hosted#2461]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

22.10.0

### Steps to Reproduce

1. Upgrade sentry from 22.8.0 to 22.10.0
2. Run migrations for Sentry and for Snuba

### Expected Result

The Performance Tab does not show "An unexpected error occurred" and instead show me the actual performance of my APIs.

### Actual Result

The Performance Tab shows "An unexpected error occured".

What I did notice is some 404 errors for URLs starting with this - https://${SENTRY_DOMAIN}/api/0/organizations/sentry/eventsv2 with method GET

What I also noticed:
1) https://${SENTRY_DOMAIN}/api/0/organizations/sentry/events with method GET also throws a 404
2) https://${SENTRY_DOMAIN}/api/0/organizations/sentry shows a JSON with a lot of data

**Comment by hubertdeng123** [comment]
Could you all try upgrading to a later version of self-hosted Sentry? I don't believe this is an issue anymore
