### ISSUE TITLE
Upgrade with Postgres migration failed

### ISSUE THREAD

**Issue by Apollon77** [getsentry/self-hosted#2462]
### Self-Hosted Version

23.3.1

### CPU Architecture

x86_64

### Docker Version

24.0.6

### Docker Compose Version

1.29.2

### Steps to Reproduce

I tagged 23.9.1 and fetched as usual and checkout. Then run install. 

it run until postgres migratikn and crashes there

### Expected Result

upgrade works

### Actual Result

```
▶ Ensuring proper PostgreSQL version ...
Error response from daemon: get sentry-postgres-new: no such volume
Unable to find image 'tianon/postgres-upgrade:9.6-to-14' locally
9.6-to-14: Pulling from tianon/postgres-upgrade
360eba32fa65: Pulling fs layer
6987678f9780: Pulling fs layer
42299245e905: Pulling fs layer
afcda32ad76a: Pulling fs layer
23d81c750666: Pulling fs layer
c7813914a8b7: Pulling fs layer
876fecb4c432: Pulling fs layer
0a8727713246: Pulling fs layer
e1385f7a1533: Pulling fs layer
6b859343a8ef: Pulling fs layer
0d40b7446ea8: Pulling fs layer
605145b3b805: Pulling fs layer
0395508f1a1a: Pulling fs layer
cfd235258c20: Pulling fs layer
3a6e003afaf3: Pulling fs layer
65f293f5b79c: Pulling fs layer
afcda32ad76a: Waiting
23d81c750666: Waiting
c7813914a8b7: Waiting
4f4fb700ef54: Pulling fs layer
c2d23bdffeb7: Pulling fs layer
876fecb4c432: Waiting
0a8727713246: Waiting
e1385f7a1533: Waiting
6b859343a8ef: Waiting
65f293f5b79c: Waiting
4f4fb700ef54: Waiting
3a6e003afaf3: Waiting
c2d23bdffeb7: Waiting
0d40b7446ea8: Waiting
605145b3b805: Waiting
0395508f1a1a: Waiting
cfd235258c20: Waiting
6987678f9780: Verifying Checksum
6987678f9780: Download complete
42299245e905: Verifying Checksum
42299245e905: Download complete
360eba32fa65: Verifying Checksum
360eba32fa65: Download complete
afcda32ad76a: Verifying Checksum
afcda32ad76a: Download complete
c7813914a8b7: Verifying Checksum
c7813914a8b7: Download complete
23d81c750666: Verifying Checksum
23d81c750666: Download complete
360eba32fa65: Pull complete
876fecb4c432: Verifying Checksum
876fecb4c432: Download complete
0a8727713246: Download complete
6b859343a8ef: Verifying Checksum
6b859343a8ef: Download complete
0d40b7446ea8: Verifying Checksum
0d40b7446ea8: Download complete
e1385f7a1533: Verifying Checksum
e1385f7a1533: Download complete
605145b3b805: Verifying Checksum
605145b3b805: Download complete
6987678f9780: Pull complete
cfd235258c20: Verifying Checksum
3a6e003afaf3: Verifying Checksum
3a6e003afaf3: Download complete
4f4fb700ef54: Download complete
65f293f5b79c: Verifying Checksum
65f293f5b79c: Download complete
42299245e905: Pull complete
c2d23bdffeb7: Verifying Checksum
c2d23bdffeb7: Download complete
afcda32ad76a: Pull complete
23d81c750666: Pull complete
c7813914a8b7: Pull complete
876fecb4c432: Pull complete
0a8727713246: Pull complete
e1385f7a1533: Pull complete
6b859343a8ef: Pull complete
0d40b7446ea8: Pull complete
605145b3b805: Pull complete
0395508f1a1a: Pull complete
cfd235258c20: Pull complete
3a6e003afaf3: Pull complete
65f293f5b79c: Pull complete
4f4fb700ef54: Pull complete
c2d23bdffeb7: Pull complete
Digest: sha256:2ff78f791338b3502c8b61dc148f1e7e8a4ebdd7f69f2cdd33f0f31ec16f7896
Status: Downloaded newer image for tianon/postgres-upgrade:9.6-to-14
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/14/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok


Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/14/data -l logfile start

initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.
Performing Consistency Checks
-----------------------------
Checking cluster versions                                   ok

connection to server on socket "/var/lib/postgresql/.s.PGSQL.50432" failed: FATAL:  role "postgres" does not exist

could not connect to source postmaster started with the command:
"/usr/lib/postgresql/9.6/bin/pg_ctl" -w -l "pg_upgrade_server.log" -D "/var/lib/postgresql/9.6/data" -o "-p 50432 -b  -c listen_addresses='' -c unix_socket_permissions=0700 -c unix_socket_directories='/var/lib/postgresql'" start
Failure, exiting
Error in install/upgrade-postgres.sh:6.
'docker run --rm -v sentry-postgres:/var/lib/postgresql/9.6/data -v sentry-postgres-new:/var/lib/postgresql/14/data tianon/postgres-upgrade:9.6-to-14' exited with status 1
-> ./install.sh:main:33
--> install/upgrade-postgres.sh:source:6

install/error-handling.sh: line 82: /usr/bin/docker: Argument list too long

```

**Comment by Apollon77** [comment]
I did another try to just go to 23.4.0 ... there it also do not work but you go maybe some more infos:

sentry-envelope-28240e265a53ec23ee16275c9656b850

**Comment by Apollon77** [comment]
PS: (also when unrelated most likely) ... in the changelog I saw deprecation od docker-cpmpose v1 ... but I have v1 and got not warned. Formerly there were checks and install process was cancelled on wrong version. Was that missed to increase?

**Comment by Apollon77** [comment]
Thank you. Will check. But in Facebook did nothing. ;-)) I just use the standard ways to upgrade the sentry instance since first release ... I never touched anything else.

**Comment by hubertdeng123** [comment]
Did you go to 23.6.2 before going to 23.9.1? That is a hard stop that you'd need to hit first.

**Comment by Apollon77** [comment]
@hubertdeng123 Thanks thats important to know ... but in fact second try (after restoring backup from before) was to just to up to 22.4.0 and already there I have this issue ... so seems really that somehow that role got lost in my DB ... I need to see how I get that back in there

**Comment by Apollon77** [comment]
![Bildschirmfoto 2023-10-13 um 23 12 24](https://github.com/getsentry/self-hosted/assets/11976694/95a94e8c-11a8-4f01-bb89-625ec8db145c)

I'm directly stuck here ... (i also tried to use "-U sentry postgres" then the prompt is "postgres=#" but also no response ... to nothing ... But snetry is running so DB needs to woprk and is also healty

**Comment by Apollon77** [comment]
Ok ... got it do execute the command on CLI:

![Bildschirmfoto 2023-10-13 um 23 15 12](https://github.com/getsentry/self-hosted/assets/11976694/a2d144f4-c62d-4c20-9af9-2db8423c393d)

**Comment by Apollon77** [comment]
In fact this username "sentry" is set in sentry.conf.py ... should the DB migration script not siply uise this confiog also for the migration?
To me it seems that whyever (maybe from the very beginning) the username is set there that way. I can not tell you why. On GitHub in this place the user is "postgres" (https://github.com/getsentry/self-hosted/blob/master/sentry/sentry.conf.example.py#L47)

So yes ... one option seems that I add a user called "postgres" ... but what happens then if this uses is doing all the migration? do I think also need to change config and use this user from now on?

Or is it not more clean that the migration script uses the configured username rather then a hardcoded one? :-)

In fact for me it is "too late". I need to somehow fix that now because - with knowing the "hard stop" even a fix in a newer version will not be that helpful for me :-)

So just to be sure because Ihave no clue about postgres:
In stackoverflow there are two options:

use the sentry user to create a new user postgres as superuser
> CREATE USER postgres SUPERUSER;
> CREATE DATABASE postgres WITH OWNER postgres;

( But the database "postgres" already seems to exist? So create will not really work ... ?)

Someone else wrote
>  I had to run /usr/local/opt/postgresql/bin/createuser -s postgres 

I'm thankful for any advice

**Comment by hubertdeng123** [comment]
The database postgres should already exist. If you add a user called "postgres" and give it access to the database, I believe that should work.

**Comment by Apollon77** [comment]
@hubertdeng123 so adding just the superuser should be enoiught? When I read coirrectly in some places then "Superusers" disable any permission checks, so can do anything ... ?!

**Comment by hubertdeng123** [comment]
I am not entirely sure, as your setup seems to differ from what most people are using. Report back any problems you may have and we'll see if we can help out.

**Comment by Apollon77** [comment]
Thank you. I will need to find a day next time to declare a longer maintenance with a fill backup and then I try it ....

**Comment by Apollon77** [comment]
Ok, I now added user postgres and gave him the same tole as that user sentry ...

Now next error comes

```
initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.
Performing Consistency Checks
-----------------------------
Checking cluster versions                                   ok
Checking database user is the install user                  
database user "postgres" is not the install user
Failure, exiting
Error in install/upgrade-postgres.sh:6.
'docker run --rm -v sentry-postgres:/var/lib/postgresql/9.6/data -v sentry-postgres-new:/var/lib/postgresql/14/data tianon/postgres-upgrade:9.6-to-14' exited with status 1
-> ./install.sh:main:33
--> install/upgrade-postgres.sh:source:6

Envelope from file sentry-envelope-28240e265a53ec23ee16275c9656b850 dispatched

```

**Comment by Apollon77** [comment]
Puuh ok another update. I now renamed the user sentry to postgres ... 
* create a role "temp" as superuser with an db "temp"
* use this user to rename sentry to postgres- check that postgres role exists as superuser
* Set the password for postgres because thats potentially lost
* Change sentry config to use "postgres" as user

With this it worked and also the db upgrade now went through ...
