### ISSUE TITLE
After upgrade from 23.4.0 to 23.9.1 events not coming

### ISSUE THREAD

**Issue by grulicht** [getsentry/self-hosted#2464]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

Hello,

After upgrade from 23.4.0 to 23.9.1 events not coming to our self hosted Sentry in Docker.
Events not coming when we tests from Next.js Dockerfile apps and also from terminal by [sentry-cli](https://sentry.sentry.io/issues/?project=1&query=SENTRY-cli) is result still same, but in log is all OK in [[sentry-nginx-1](https://sentry.sentry.io/issues/?project=1&query=SENTRY-nginx-1)] docker container, but in GUIi in Sentry after this tests and message in log docker container, we not see anything in GUIi in Sentry about this tests events/messages.
Where is a problem or show me solutions please.
Thanks.

### Expected Result

Hello,

After upgrade from 23.4.0 to 23.9.1 events not coming to our self hosted Sentry in Docker.
Events not coming when we tests from Next.js Dockerfile apps and also from terminal by [sentry-cli](https://sentry.sentry.io/issues/?project=1&query=SENTRY-cli) is result still same, but in log is all OK in [[sentry-nginx-1](https://sentry.sentry.io/issues/?project=1&query=SENTRY-nginx-1)] docker container, but in GUIi in Sentry after this tests and message in log docker container, we not see anything in GUIi in Sentry about this tests events/messages.
Where is a problem or show me solutions please.
Thanks.

### Actual Result

Hello,

After upgrade from 23.4.0 to 23.9.1 events not coming to our self hosted Sentry in Docker.
Events not coming when we tests from Next.js Dockerfile apps and also from terminal by [sentry-cli](https://sentry.sentry.io/issues/?project=1&query=SENTRY-cli) is result still same, but in log is all OK in [[sentry-nginx-1](https://sentry.sentry.io/issues/?project=1&query=SENTRY-nginx-1)] docker container, but in GUIi in Sentry after this tests and message in log docker container, we not see anything in GUIi in Sentry about this tests events/messages.
Where is a problem or show me solutions please.
Thanks.

### Product Area

Unknown

### Version

23.9.1

**Comment by azaslavsky** [comment]
Do your nginx logs show the requests being made on the server? Are there any other suspicious logs (errors, warnings) occurring in any of the services?

**Comment by djmaze** [comment]
I experienced a similar problem. Probably the relay container has been started after nginx, or it was restarted after the nginx container has already been started. In these cases it helps to just restart the nginx container.

The problem is that the nginx config used here is not prone to dns changes for upstream services (e.g. when the ip changes because an upstream container is restarted). The nginx config should probably be adjusted to prevent those kinds of problems in the future. (Use a [`resolver`](https://nginx.org/en/docs/http/ngx_http_core_module.html#resolver) with a ttl.)

**Comment by hubertdeng123** [comment]
Thanks for chiming in!
