### ISSUE TITLE
Cannot configure sentry Jira plugin

### ISSUE THREAD

**Issue by wkaskie** [getsentry/self-hosted#2465]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

1. Install Sentry plugin in Jira
2. click Finish installation in Sentry. This opens <domain>/extensions/jira/link/?signed_params=<hash>
3. Choose your organization
4. Click "install Jira"
5. Get error: 
![Screenshot 2023-10-11 at 1 27 03 PM](https://github.com/getsentry/sentry/assets/14349014/a0079f01-08c7-4f3b-a794-fcac827bfbda)

### Expected Result

JIra integration plugin will be installed and configured.

### Actual Result

![Screenshot 2023-10-11 at 1 27 03 PM](https://github.com/getsentry/sentry/assets/14349014/a0079f01-08c7-4f3b-a794-fcac827bfbda)

### Product Area

Settings - Integrations

### Version

22.11.0

**Comment by hubertdeng123** [comment]
Are you following the instructions for setup as specified here?
https://develop.sentry.dev/integrations/jira/

Are your sentry web container logs displaying anything useful for debugging?

**Comment by wkaskie** [comment]
Yes, I am following the instructions here: https://develop.sentry.dev/integrations/jira/ with the exception that I'm not using ngrok, but our on premises instance url `https://sentry.our-company.net/extensions/jira/descriptor/`

I'll see if I can view the logs...
