### ISSUE TITLE
./install.sh

### ISSUE THREAD

**Issue by liansky** [getsentry/self-hosted#2466]
> “[https://deb.debian.org”](https://deb.debian.org%E2%80%9D) access is too slow for me，my dockerfile like this ： ARG BASE_IMAGE FROM ${BASE_IMAGE} USER 0 RUN sed -i "s@http://deb.debian.org@http://mirrors.aliyun.com@g" /etc/apt/sources.list && apt-get clean && apt-get update && apt-get install -y --no-install-recommends cron && rm -r /var/lib/apt/lists/* RUN if [ -z "${http_proxy}" ]; then echo "Acquire::http::proxy "${http_proxy}";" >> /etc/apt/apt.conf; fi RUN if [ -z "${https_proxy}" ]; then echo "Acquire::https::proxy "${https_proxy}";" >> /etc/apt/apt.conf; fi RUN apt-get update && apt-get install -y --no-install-recommends cron && rm -r /var/lib/apt/lists/* COPY entrypoint.sh /entrypoint.sh ENTRYPOINT ["/entrypoint.sh"]
> 
> and my “/etc/apt/sources.list” like this deb http://mirrors.aliyun.com/ubuntu/ jammy main restricted universe multiverse deb-src http://mirrors.aliyun.com/ubuntu/ jammy main restricted universe multiverse
> 
> deb http://mirrors.aliyun.com/ubuntu/ jammy-security main restricted universe multiverse deb-src http://mirrors.aliyun.com/ubuntu/ jammy-security main restricted universe multiverse
> 
> deb http://mirrors.aliyun.com/ubuntu/ jammy-updates main restricted universe multiverse deb-src http://mirrors.aliyun.com/ubuntu/ jammy-updates main restricted universe multiverse
> 
> deb http://mirrors.aliyun.com/ubuntu/ jammy-proposed main restricted universe multiverse deb-src http://mirrors.aliyun.com/ubuntu/ jammy-proposed main restricted universe multiverse
> 
> deb http://mirrors.aliyun.com/ubuntu/ jammy-backports main restricted universe multiverse deb-src http://mirrors.aliyun.com/ubuntu/ jammy-backports main restricted universe multiverse
> 
> deb https://mirrors.aliyun.com/debian/ bullseye main non-free contrib deb-src https://mirrors.aliyun.com/debian/ bullseye main non-free contrib deb https://mirrors.aliyun.com/debian-security/ bullseye-security main deb-src https://mirrors.aliyun.com/debian-security/ bullseye-security main deb https://mirrors.aliyun.com/debian/ bullseye-updates main non-free contrib deb-src https://mirrors.aliyun.com/debian/ bullseye-updates main non-free contrib deb https://mirrors.aliyun.com/debian/ bullseye-backports main non-free contrib deb-src https://mirrors.aliyun.com/debian/ bullseye-backports main non-free contrib
> 
> and run sudo apt-get update，but its still bad😭😭😭

昨天成功了 使用阿里镜像
建议下载发布版本替换这个。不要直接clone仓库 -  然后install.sh 一次成功
```
ARG BASE_IMAGE
FROM ${BASE_IMAGE}
USER 0
RUN if [ -z "${http_proxy}" ]; then echo "Acquire::http::proxy \"${http_proxy}\";" >> /etc/apt/apt.conf; fi
RUN if [ -z "${https_proxy}" ]; then echo "Acquire::https::proxy \"${https_proxy}\";" >> /etc/apt/apt.conf; fi
RUN echo "\
	deb http://mirrors.aliyun.com/debian/ bullseye main non-free contrib \
	deb-src http://mirrors.aliyun.com/debian/ bullseye main non-free contrib \
	deb http://mirrors.aliyun.com/debian-security/ bullseye-security main \
	deb-src http://mirrors.aliyun.com/debian-security/ bullseye-security main \
	deb http://mirrors.aliyun.com/debian/ bullseye-updates main non-free contrib \
	deb-src http://mirrors.aliyun.com/debian/ bullseye-updates main non-free contrib \
	deb http://mirrors.aliyun.com/debian/ bullseye-backports main non-free contrib \
	deb-src http://mirrors.aliyun.com/debian/ bullseye-backports main non-free contrib \
" > /etc/apt/sources.list
RUN apt-get clean

RUN ln -s /lib/x86_64-linux-gnu/libpcre.so.3.13.3  /lib/libpcre.so.1
RUN apt-get update && apt-get install -y --no-install-recommends cron && \
    rm -r /var/lib/apt/lists/*

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
```

_Originally posted by @MR-ZiWeiter in https://github.com/getsentry/self-hosted/issues/2399#issuecomment-1718517050_

**Comment by azaslavsky** [comment]
I can't really understand your post. Could you translate the portion in a foreign language, and fill our the default form for filing bugs (Docker version, Sentry version, and other fields)?

**Comment by thuvh** [comment]
I think he would like to customize the repository's url, change from default to fastest mirror based on his location.

**Comment by hubertdeng123** [comment]
If that's the case, I think we should default to using `deb.debian.org` and if you'd like to use mirrors, you should be able to set that up yourself. @liansky are you able to get this working on a mirror?
