### ISSUE TITLE
Issue Categories

### ISSUE THREAD

**Issue by BenJChen** [getsentry/self-hosted#2469]
### Self-Hosted Version

23.8.0

### CPU Architecture

x86

### Docker Version

24.0.6

### Docker Compose Version

2.20.3

### Steps to Reproduce

1.generate an error
2.Issues-Activity- Check if a new issue 
3.Project Details-New Issues-Check for new issues

### Expected Result

1.Errors can be correctly identified as new issues
2.Project Details-New Issues-Can return new issues

### Actual Result

1.generate an error
2.Issues-Activity-Tip:Sentry first saw this issue,But there seems to be no new issue tag
3.Project Details-New Issues-The result list returned is 0
![QQ截图20231016112302](https://github.com/getsentry/self-hosted/assets/15866873/91fdf50b-f43b-4c07-a4d6-9f4bf81796ac)
![youdu图片20231016112227](https://github.com/getsentry/self-hosted/assets/15866873/1ecb212d-ff6c-4d4c-a434-66549d24552e)

**Comment by hubertdeng123** [comment]
Did you mark the issue as reviewed? If not, this does appear to be abnormal. Would you be able to check your snuba-post-processor group for lag? I'm wondering if there is any lag there. I think that'd look something like this
```
docker compose run --rm kafka kafka-topics --list --group snuba-post-processor --bootstrap-server kafka:9092
```

**Comment by BenJChen** [comment]
> Did you mark the issue as reviewed? If not, this does appear to be abnormal. Would you be able to check your snuba-post-processor group for lag? I'm wondering if there is any lag there. I think that'd look something like this
> 
> ```
> docker compose run --rm kafka kafka-topics --list --group snuba-post-processor --bootstrap-server kafka:9092
> ```

![0096d950720f1fd32c475da7f2802263-215516](https://github.com/getsentry/self-hosted/assets/15866873/c35d8eab-8534-4c3b-8b8c-ffbbf4e04479)

**Comment by hubertdeng123** [comment]
try 
`sudo docker compose run --rm kafka kafka-consumer-groups  --bootstrap-server kafka:9092 --describe --all-groups`
