### ISSUE TITLE
Restore of single organization ends up in multiple organizations and sentry is unusable

### ISSUE THREAD

**Issue by max-mycarly** [getsentry/self-hosted#2473]
### Self-Hosted Version

23.9.1

### CPU Architecture

x86_64

### Docker Version

24.0.5, build ced0996

### Docker Compose Version

2.22.0

### Steps to Reproduce

Create backup on one system with scripts ./scripts/backup
Copy ./sentry/backup.json in old system
Fresh install of Sentry ./install.sh --skip-user-creation
Paste ./sentry/backup.json in new system
Restore backup  with script ./scripts/restore
Start Sentry docker-compose --env-file .env.custom up -d

### Expected Result

Migration should work and new sentry instance should be usable

### Actual Result

Beside the issue #2437, if you modify the backup.json restore.sh finishes without an error.
But if you start sentry and access it via browser the default organization has changed.
On the original sentry instance there is only one organization named "myorga" 
But after the restore there are two organizations "sentry" and "myorga".
The "sentry" organization is created during the installation by the install.sh  but not updated / replaced through the restore.

Beside this, you cannot login to the new sentry instance. No user / password is recognized.

Organization before restore:

```
{
  "model": "sentry.organization",
  "pk": 1,
  "fields": {
    "name": "myorga",
    "slug": "myorga",
    "status": 0,
    "date_added": "2022-05-31T06:56:20.290Z",
    "default_role": "member",
    "is_test": false,
    "flags": "16"
  }
},
```

Organization after restore:
```
{
  "model": "sentry.organization",
  "pk": 1,
  "fields": {
    "name": "Sentry",
    "slug": "sentry",
    "status": 0,
    "date_added": "2023-10-16T14:04:28.741Z",
    "default_role": "member",
    "is_test": false,
    "flags": "1"
  }
},
{
  "model": "sentry.organization",
  "pk": 2,
  "fields": {
    "name": "myorga",
    "slug": "myorga",
    "status": 0,
    "date_added": "2022-05-31T06:56:20.290Z",
    "default_role": "member",
    "is_test": false,
    "flags": "16"
  }
},
```

**Comment by hubertdeng123** [comment]
Looks like there are two threads going on here. https://github.com/getsentry/self-hosted/issues/2437. I'll let @azaslavsky follow up with you

**Comment by max-mycarly** [comment]
Hi, please do not forget this issue.
The install script always creates a default organization "Sentry". 
If you then restore a backup, the organization in your backup is restored as a second organization.
Which is a contradiction to the default self hosted settings which allow only a single organization.

Similar to the --skip-user-creation flag there should a --skip-organization-creation flag

**Comment by azaslavsky** [comment]
I'm going to look at this at the same time I look at the other bug you raised, hopefully mid next week. I think your basic diagnosis is right: we need some means by which we can either install with a totally empty database, or otherwise completely scrub it post installation. I'll look at what's the best way forward and report back.

**Comment by azaslavsky** [comment]
Just wanted to update: I am currently making sure that https://github.com/getsentry/self-hosted/issues/2468, which blocks this work, lands correctly. After that, I'd like to get a fix for this up sometime this week or early next.

**Comment by azaslavsky** [comment]
This PR should have fixed this as well: https://github.com/getsentry/sentry/commit/1bbc23fcec6133008b282bda97776f62bad19b2d.

This should land in 23.12.0
