### ISSUE TITLE
Unfortunately another failed to solve: base name (${BASE_IMAGE}) should not be blank

### ISSUE THREAD

**Issue by scoobydooxp** [getsentry/self-hosted#2474]
### Self-Hosted Version

23.9.1 and Nightly

### CPU Architecture

x86_64

### Docker Version

24.0.4

### Docker Compose Version

2.19.1

### Steps to Reproduce

On Rocky8 (RHEL8 clone)
1. git clone https://github.com/getsentry/self-hosted.git
2. export REPORT_SELF_HOSTED_ISSUES=0
3. cd self-hosted
4. ./install.sh
5. docker compose up -d

### Expected Result

Sentry instance should be up and running

### Actual Result

failed to solve: base name (${BASE_IMAGE}) should not be blank

**Comment by hubertdeng123** [comment]
Can you check your .env file? I'm suspecting that the `BASE_IMAGE` is not defined there.
