### ISSUE TITLE
Patch sentry-sentry-self-hosted-local vulnerabilities

### ISSUE THREAD

**Issue by ziler-orca** [getsentry/self-hosted#2483]
### Self-Hosted Version

23.9.1

### CPU Architecture

x86_64

### Docker Version

24.0.6

### Docker Compose Version

v2.21.0

### Steps to Reproduce

The sentry-sentry-self-hosted-local image has various vulnerabilities. Please see attached for details.

[sentry-sentry-self-hosted-local_cves.xlsx](https://github.com/getsentry/self-hosted/files/12924285/sentry-sentry-self-hosted-local_cves.xlsx)

### Expected Result

Please patch vulnerabilities.

### Actual Result

Please patch vulnerabilities.

**Comment by hubertdeng123** [comment]
should be patched with docker image upgrades
