### ISSUE TITLE
Patch sentry-vroom-cleanup-self-hosted-local vulnerabilities

### ISSUE THREAD

**Issue by ziler-orca** [getsentry/self-hosted#2485]
### Self-Hosted Version

23.9.1

### CPU Architecture

x86_64

### Docker Version

24.0.6

### Docker Compose Version

v2.21.0

### Steps to Reproduce

The sentry-vroom-cleanup-self-hosted-local image need to be patched. Please see below for details.

[sentry-vroom-cleanup-self-hosted-local_cves.xlsx](https://github.com/getsentry/self-hosted/files/12924311/sentry-vroom-cleanup-self-hosted-local_cves.xlsx)

### Expected Result

Please patch vulnerabilities.

### Actual Result

Please patch vulnerabilities.

**Comment by hubertdeng123** [comment]
should be patched with https://github.com/getsentry/vroom/issues/338, since it uses the vroom image
