### ISSUE TITLE
Sentry Installation Failed

### ISSUE THREAD

**Issue by wangdaners** [getsentry/self-hosted#2496]
### Self-Hosted Version

23.10.0

### CPU Architecture

x86_64

### Docker Version

20.10.8

### Docker Compose Version

2.22.0

### Steps to Reproduce

CentOS Linux release 7.9.2009 8C32G

- git clone https://github.com/getsentry/onpremise.git
- git checkout 23.10.0
- cd onpremise
- ./install.sh

### Expected Result

In the installation process, I encountered an error related to the use of the 'apt-get' command.

### Actual Result

Because I am in China, accessing Docker image repositories from the global sources is very slow. Therefore, I have added the following registry mirrors to the /etc/docker/daemon.json file:
`"registry-mirrors": [
	"https://*******.mirror.aliyuncs.com",
	"https://mirror.ccs.tencentyun.com"
]`

But it still failed to install.
![image](https://github.com/getsentry/self-hosted/assets/40197767/21c622f9-0c1f-4437-8661-2dc089d21fa5)

**Comment by hubertdeng123** [comment]
Have you tried modifying the dockerfile like in this issue?

https://github.com/getsentry/self-hosted/issues/2399#issuecomment-1718517050

**Comment by wangdaners** [comment]
> Have you tried modifying the dockerfile like in this issue?
> 
> [#2399 (comment)](https://github.com/getsentry/self-hosted/issues/2399#issuecomment-1718517050)

According to the solution provided in this issue, I attempted to make changes to the corn/DockerFile. However, I still encountered an error during the installation. Here is the error message:

 > [symbolicator-cleanup 7/8] RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*:
239.9 W: Skipping acquire of configured file 'deb/binary-amd64/Packages' as repository 'http://mirrors.aliyun.com/debian bullseye InRelease' doesn't have the component 'deb' (component misspelt in sources.list?)
239.9 W: Skipping acquire of configured file 'http://mirrors.aliyun.com/debian-security//binary-amd64/Packages' as repository 'http://mirrors.aliyun.com/debian bullseye InRelease' doesn't have the component 'http://mirrors.aliyun.com/debian-security/' (component misspelt in sources.list?)
239.9 W: Skipping acquire of configured file 'http://mirrors.aliyun.com/debian//binary-amd64/Packages' as repository 'http://mirrors.aliyun.com/debian bullseye InRelease' doesn't have the component 'http://mirrors.aliyun.com/debian/' (component misspelt in sources.list?)
239.9 W: Skipping acquire of configured file 'bullseye-updates/binary-amd64/Packages' as repository 'http://mirrors.aliyun.com/debian bullseye InRelease' doesn't have the component 'bullseye-updates' (component misspelt in sources.list?)
239.9 W: Skipping acquire of configured file 'bullseye/binary-amd64/Packages' as repository 'http://mirrors.aliyun.com/debian bullseye InRelease' doesn't have the component 'bullseye' (component misspelt in sources.list?)
239.9 W: Skipping acquire of configured file 'bullseye-security/binary-amd64/Packages' as repository 'http://mirrors.aliyun.com/debian bullseye InRelease' doesn't have the component 'bullseye-security' (component misspelt in sources.list?)
239.9 W: Skipping acquire of configured file 'deb-src/binary-amd64/Packages' as repository 'http://mirrors.aliyun.com/debian bullseye InRelease' doesn't have the component 'deb-src' (component misspelt in sources.list?)
239.9 W: Skipping acquire of configured file 'bullseye-backports/binary-amd64/Packages' as repository 'http://mirrors.aliyun.com/debian bullseye InRelease' doesn't have the component 'bullseye-backports' (component misspelt in sources.list?)
239.9 E: Problem executing scripts APT::Update::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'
239.9 E: Sub-process returned an error code
------
failed to solve: executor failed running [/bin/sh -c apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*]: exit code: 100
Error in install/build-docker-images.sh:9.
'$dcb --force-rm "$service"' exited with status 17
-> ./install.sh:main:29
--> install/build-docker-images.sh:source:9

Cleaning up...

**Comment by azaslavsky** [comment]
You could try the suggested answers at https://stackoverflow.com/questions/38002543/apt-get-update-returned-a-non-zero-code-100.

In any case, this does not appear to be a Sentry problem - apt-get is having trouble pulling a common package `cron`, potentially due to firewalls, security software, or other local machine configuration.

**Comment by wangdaners** [comment]
> You could try the suggested answers at https://stackoverflow.com/questions/38002543/apt-get-update-returned-a-non-zero-code-100.您可以在 https://stackoverflow.com/questions/38002543/apt-get-update-returned-a-non-zero-code-100 尝试建议的答案。
> 
> In any case, this does not appear to be a Sentry problem - apt-get is having trouble pulling a common package `cron`, potentially due to firewalls, security software, or other local machine configuration.无论如何，这似乎不是哨兵的问题 - apt-get 在拉取公共软件包 `cron` 时遇到问题，可能是由于防火墙、安全软件或其他本地机器配置。

Does the Sentry installation using apt-get take into account compatibility across various operating systems? This command is for Debian and Ubuntu, not CentOS.

**Comment by wangdaners** [comment]
> You could try the suggested answers at https://stackoverflow.com/questions/38002543/apt-get-update-returned-a-non-zero-code-100.您可以在 https://stackoverflow.com/questions/38002543/apt-get-update-returned-a-non-zero-code-100 尝试建议的答案。
> 
> In any case, this does not appear to be a Sentry problem - apt-get is having trouble pulling a common package `cron`, potentially due to firewalls, security software, or other local machine configuration.无论如何，这似乎不是哨兵的问题 - apt-get 在拉取公共软件包 `cron` 时遇到问题，可能是由于防火墙、安全软件或其他本地机器配置。

Thank you. The error I encountered during Docker image pulling might be caused by network issues on the server.

**Comment by azaslavsky** [comment]
Good luck getting the network issues debugged!
