### ISSUE TITLE
backup.mdx is not up to date

### ISSUE THREAD

**Issue by LvckyAPI** [getsentry/self-hosted#2498]
https://develop.sentry.dev/self-hosted/backup/

The documentation is outdated. It does not work currently.

Running the command `./scripts/restore.sh` will give this error/info:
![image](https://github.com/getsentry/develop/assets/47639297/ad9c55b6-9e07-451a-954b-e485e1702707)

The command backup does the same but for export.

**Comment by hubertdeng123** [comment]
What version of self-hosted Sentry are you on? Did you run `./scripts/backup.sh` beforehand?

**Comment by LvckyAPI** [comment]
> What version of self-hosted Sentry are you on? Did you run `./scripts/backup.sh` beforehand?

23.9.1 but now the latest one

**Comment by azaslavsky** [comment]
Can you run the following:

```
bash -x ./scripts/backup.sh
```

and report back the resulting output, particularly the `docker compose ...` commands that get called?

**Comment by LvckyAPI** [comment]
Hello @azaslavsky. I put the Output in a File:
[log01.txt](https://github.com/getsentry/self-hosted/files/13326107/log01.txt)

Content of `senty/backup.json`:
```bash
deployer@eta:~/sentry/sentry$ cat backup.json 
deployer@eta:~/sentry/sentry$ 
```

**Comment by LvckyAPI** [comment]
> Your backup.sh and restore.sh scripts seem out of date - can you go into the folder that you have download self-hosted to on your local machine, and run `git rev-parse HEAD` please?

deployer@eta:~/sentry$ git rev-parse HEAD
b935d8bc43e11eb9728a08c1a2ed7dc4d1938911

**Comment by azaslavsky** [comment]
Hmm, that commit doesn't seem to exist: https://github.com/getsentry/self-hosted/commits/b935d8bc43e11eb9728a08c1a2ed7dc4d1938911

Can you run `git log` and post the top entry?

**Comment by LvckyAPI** [comment]
I used my own repository for deploying Sentry to my Server.
I've merged the github master branch into my master branch.

The Backup is working now, but throws some warnings about the syntax.

**Comment by azaslavsky** [comment]
Can you post those warnings? If they're what I think they are (https://github.com/getsentry/self-hosted/issues/2458), they're in a dependency and there's nothing we can really do about them. They are safe to ignore.

**Comment by azaslavsky** [comment]
Also, worth noting that if you use your own repository, it's possible that you'll need to do manual syncs to mainline master when upgrading versions in the future.
