### ISSUE TITLE
sourcemap doesn't work on self-hosted, but the same file works on SAAS，What's the solution? 

### ISSUE THREAD

**Issue by zenotsai066** [getsentry/self-hosted#2503]
### Self-Hosted Version

23.9.1

### CPU Architecture

x86_64

### Docker Version

24.0.5

### Docker Compose Version

24.0.5

### Steps to Reproduce

I've only changed the following two configurations

```
system.internal-url-prefix: 'https://xxx'
system.url-prefix: 'https://xxx'
```

### Expected Result

The sourcemap I uploaded in self-hosted Sentry is not working, how should I troubleshoot this?

The same file, confusingly, works fine on Sentry SAAS!

What are the reasons why self-hosted does not work? What should I troubleshoot? Help me!

### Actual Result

I used sentry-cli to upload it.
![image](https://github.com/getsentry/self-hosted/assets/66027308/db979f4d-f908-4b6d-9ef9-e0b9f034182c)

**Comment by Swatinem** [comment]
Sourcemap processing was moved to symbolicator quite a while ago.
There is however frequent problems with correctly setting up Symbolicator in self-hosted.
Do you have any detailed logs from your self-hosted instance of Symbolicator that might hint to that problem?

The inter-communication between Symbolicator and Sentry might be one thing to specifcally look at. You mentioned that you changed the `system.internal-url-prefix` option, which is the URL that symbolicator will try use to lookup the artifact bundles on Sentry.

**Comment by dalveytech-zeno** [comment]
> Sourcemap processing was moved to symbolicator quite a while ago. There is however frequent problems with correctly setting up Symbolicator in self-hosted. Do you have any detailed logs from your self-hosted instance of Symbolicator that might hint to that problem?
> 
> The inter-communication between Symbolicator and Sentry might be one thing to specifcally look at. You mentioned that you changed the `system.internal-url-prefix` option, which is the URL that symbolicator will try use to lookup the artifact bundles on Sentry.

Thank you for your help! But my problem is still not solved, I made the following 2 attempts
1, I checked the logs of the ``sentry-self-hosted-symbolicator`` instance and didn't find anything
2, I removed the ```system.internal-url-prefix`` configuration, and that didn't solve the problem either.

**Comment by Swatinem** [comment]
TBH, I’m not an expert in troubleshooting self-hosted problems.

You can try turning up the log level of symbolicator, so you get a detailed view of what it is trying to do. In this particular case, we would be looking for logs related to fetching the file list from sentry.
