### ISSUE TITLE
recurrent  nginx 502 bad gateway after about 5 days no access sentry

### ISSUE THREAD

**Issue by nicky132** [getsentry/self-hosted#2506]
### Self-Hosted Version

23.8.0

### CPU Architecture

x86_64

### Docker Version

22.0.5

### Docker Compose Version

2.6.0

### Steps to Reproduce

![image](https://github.com/getsentry/self-hosted/assets/34881461/4a666c82-1328-4013-ada5-68501adb2f94)
When i firstly accessed sentry to find any error logs after almost about 5 days,then i got this 502.
But if i refreshed this page  again, then i accessed sentry successfully.
Also after very long days to access my sentry, i will got 502 again, :c, super noisy.

### Expected Result

I can access my sentry successfully every single time!

### Actual Result

![image](https://github.com/getsentry/self-hosted/assets/34881461/3dc77e08-ab77-49dd-b7ad-5e3a9ef9c10b)
2 questions:
一、
When i firstly accessed sentry to find any error logs after almost about 5 days,then i got this 502.
But if i refreshed this page  again, then i accessed sentry successfully.
Also after very long days to access my sentry, i will got 502 again, :c, super noisy.

二、
<img width="870" alt="image" src="https://github.com/getsentry/self-hosted/assets/34881461/41817ebb-751f-49c2-906b-adb245640fdf">

<img width="1353" alt="image" src="https://github.com/getsentry/self-hosted/assets/34881461/3f671088-4d3e-4db3-8513-c1c5a6f6e0cb">

I am not sure, dose the nginx.conf file work with sentry.
I cannot find access.log or error.log work with sentry either.
### Event ID

c2d85058-d3b0-4d85-a509-e2ba965845d7

**Comment by azaslavsky** [comment]
You can try the instructions [here](https://github.com/getsentry/self-hosted/issues/1594#issuecomment-1195493162) to enable more nginx logs.

**Comment by nicky132** [comment]
> You can try the instructions [here](https://github.com/getsentry/self-hosted/issues/1594#issuecomment-1195493162) to enable more nginx logs.

Firstly,still no idea,about how could i enable more nginx logs.

Secondly,how to solve the 502 problem.

**Comment by hubertdeng123** [comment]
You will probably need to enable proxy buffering in your nginx configs on your machine. I'm suspecting the issue is similar to this one:
https://github.com/getsentry/self-hosted/issues/2256

**Comment by darrelajonas** [comment]
One thing that caught me out was that Sentry takes ages to start-up fully. Don't try anything until your server has been up and running for about 10 minutes.

Once the RAM usage gets upto about 6 GB it should be online.


As for Nginx his is the config I am using

```
# force https
server {
    listen 80;
    server_name sentry.mydomain.com;
    return 301 https://$host$request_uri;
}

# main site processing
server {

    # Set server name
    server_name sentry.mydomain.com;

    # Set default files to use for homepage
    index index.html index.htm;

    # route to port 9000
    location / {
        proxy_pass http://localhost:9000;
        include proxy_params;
    }

    # deny other hidden files
    location ~ /\.(?!well-known).* {
        deny all;
    }

    # communicate with the browser over HTTPS
    #listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/sentry.mydomain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/sentry.mydomain.com/privkey.pem; # managed by Certbot
    #include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    #ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
```

**Comment by darrelajonas** [comment]
Forgot something...

Contents of the `/etc/nginx/proxy_params` file in the above config

```
proxy_set_header Host $http_host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
```

**Comment by darrelajonas** [comment]
...also in `~/.sentry/sentry/sentry.conf.py`

![image](https://github.com/getsentry/self-hosted/assets/149162517/6e3ecfb5-35c0-45f2-84b4-bfacebaac83a)
