### ISSUE TITLE
Crash Free Sessions, Crash Free Users is not updated 

### ISSUE THREAD

**Issue by MinaMaher0** [getsentry/self-hosted#2508]
### Self-Hosted Version

23.8.0

### CPU Architecture

x86_64

### Docker Version

it's kubernetes

### Docker Compose Version

it's kubernetes

### Steps to Reproduce

the Crash Free Sessions, Crash Free Users is not updated, although we updating the release and add the 
`Sentry.init({
    dsn: "xxxxxxxxxxxxxxxxxxxxxx",`
    })`
 to our angular app
 
 Note: our angular app is deployed using nginx

![image](https://github.com/getsentry/self-hosted/assets/53441349/edf3a0d5-9cbb-4608-b1f3-0c2b79d3e309)

### Expected Result

the Crash Free Sessions, Crash Free Users to be updated

### Actual Result

![image](https://github.com/getsentry/self-hosted/assets/53441349/7e406cb8-4fad-46f1-8309-ebd6cc507d2a)

**Comment by azaslavsky** [comment]
Are you sure the events are hitting your server? Do you have logs saying they've been ingested?

**Comment by MinaMaher0** [comment]
@azaslavsky 
sorry i didn't get you, could you pleas elaborate more how can i see it

**Comment by hubertdeng123** [comment]
This may be an issue on your side, as you're using a kubernetes setup that we do not support. Although, we've recently moving infrastructure away from sessions -> metrics for release health but I'm not sure if that's something that is useful to you. Good luck in debugging your error, and you may have better luck filing this in the repo of the kubernetes setup you're using!
