### ISSUE TITLE
Account permissions

### ISSUE THREAD

**Issue by BenJChen** [getsentry/self-hosted#2512]
### Self-Hosted Version

23.10.1

### CPU Architecture

x86

### Docker Version

24.0.6

### Docker Compose Version

2.20.3

### Steps to Reproduce

1.Use the Owner account to access /manage/settings/

### Expected Result

Can be accessed correctly

### Actual Result

1.Your role does not have the necessary permissions to access this resource, please read more about [organizational roles]
![image](https://github.com/getsentry/self-hosted/assets/15866873/c99f2e21-5eb9-4fff-9f46-c3943e91d889)

**Comment by azaslavsky** [comment]
Is the owner account a superuser?

**Comment by BenJChen** [comment]
> Is the owner account a superuser?

My account is not a superuser. How can I set up a superuser? When I use superuser A to set up a superuser for my account, I am prompted missing required permission to add superuser.
![ee7a627ac77fa036840efd3a34d4cbac-34256](https://github.com/getsentry/self-hosted/assets/15866873/02617661-cb6a-4db8-adc6-c7c541a9d354)

**Comment by azaslavsky** [comment]
Try this:
```
docker compose exec postgres bash
psql -U postgres
select username from auth_user where is_superuser = True;
```

This will show you the usernames of all of the superusers on your instance.

**Comment by BenJChen** [comment]
> Try this:
> 
> ```
> docker compose exec postgres bash
> psql -U postgres
> select username from auth_user where is_superuser = True;
> ```
> 
> This will show you the usernames of all of the superusers on your instance.


I only see one super user account. Can I set up multiple super accounts? Is there any way to achieve this?

**Comment by azaslavsky** [comment]
Can you log into this account? You should be able to access the original page from either the owner's account or a superuser account.

**Comment by BenJChen** [comment]
> Can you log into this account? You should be able to access the original page from either the owner's account or a superuser account.

I can log in to this superuser account, but can I set up more superusers?

**Comment by hubertdeng123** [comment]
There isn't a way to do that right now, if you'd like this you will need to modify your postgres database to change the permissions of your user.
