### ISSUE TITLE
Edit page failed to load with timeout (http error 504) 

### ISSUE THREAD

**Issue by arielNayax** [getsentry/self-hosted#2517]
### Self-Hosted Version

1.9.15

### CPU Architecture

X86_64

### Docker Version

23.0.3

### Docker Compose Version

2.17.2

### Steps to Reproduce

1. Log in
2. Open edit link on any workspace. For simplicity sake I created a new workspace and got “edit”

### Expected Result

Workspace is open for edit 

### Actual Result

Linux machine running self hosted sentry app in docker.
 
Editor logs:
10.12.11.254 - - [25/Oct/2023:09:01:09 +0000] "GET /applications HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15"
10.12.11.254 - - [25/Oct/2023:09:01:09 +0000] "GET /api/v1/users/me HTTP/1.1" 200 248 "http://10.14.24.113/applications" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15"
10.12.11.254 - - [25/Oct/2023:09:01:10 +0000] "GET /api/v1/users/features HTTP/1.1" 200 275 "http://10.14.24.113/applications" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15"
10.12.11.254 - - [25/Oct/2023:09:01:10 +0000] "GET /api/v1/tenants/current HTTP/1.1" 200 166 "http://10.14.24.113/applications" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15"
10.12.11.254 - - [25/Oct/2023:09:01:10 +0000] "GET /api/v1/applications/new HTTP/1.1" [200 2683](tel:200 2683) "http://10.14.24.113/applications" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15"
10.12.11.254 - - [25/Oct/2023:09:01:10 +0000] "GET /rts/?EIO=4&transport=websocket HTTP/1.1" 101 552 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15"
127.0.0.1 - - [25/Oct/2023:09:01:22 +0000] "GET / HTTP/1.1" [200 4559](tel:200 4559) "-" "curl/7.68.0"
10.12.11.254 - - [25/Oct/2023:09:01:30 +0000] "GET /api/v1/applications/releaseItems HTTP/1.1" 499 0 "http://10.14.24.113/applications" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15"
 
 
Redis and Mongo are up and running.
 
The error.log show an error from docker start only and not new errors during entering the 'edit' page:
 
+ echo 'Removing key now that validation is done for nayaxcaital.com...'
+ rm -Rfv /etc/letsencrypt/live/nayaxcaital.com /etc/letsencrypt/archive/nayaxcaital.com /etc/letsencrypt/renewal/nayaxcaital.com.conf
+ echo 'Generating certification for domain nayaxcaital.com'
+ mkdir -p /appsmith-stacks/data/certificate/certbot
+ certbot certonly --webroot --webroot-path=/appsmith-stacks/data/certificate/certbot --register-unsafely-without-email --domains nayaxcaital.com --rsa-key-size 4096 --agree-tos --force-renewal
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
An unexpected error occurred:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
socket.timeout: timed out
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 164, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd5efb19b20>, 'Connection to acme-v02.api.letsencrypt.org timed out. (connect timeout=45)')
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd5efb19b20>, 'Connection to acme-v02.api.letsencrypt.org timed out. (connect timeout=45)'))
 
During handling of the above exception, another exception occurred:
 
Error logs:
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd5efb19b20>, 'Connection to acme-v02.api.letsencrypt.org timed out. (connect timeout=45)'))
Please see the logfiles in /var/log/letsencrypt for more details.
+ (( 1 != 0 ))
+ echo 'Stop Nginx due to provisioning fail'
+ nginx -s stop
+ return 1
+ echo 'Status code from init_ssl_cert is 0'
+ APP_TEMPLATE=/opt/appsmith/templates/nginx-app-http.conf.template.sh
+ bash /opt/appsmith/templates/nginx-app-http.conf.template.sh nayaxcaital.com
+ index_html_served=/opt/appsmith/editor/index.html
+ index_html_original=/opt/appsmith/index.html.original
+ [[ ! -f /opt/appsmith/index.html.original ]]
+ node -e '
const fs = require("fs")
const content = fs.readFileSync("/opt/appsmith/index.html.original", "utf8").replace(
  /\b__(APPSMITH_[A-Z0-9_]+)__\b/g,
  (placeholder, name) => (process.env[name] || "")
)
fs.writeFileSync("/opt/appsmith/editor/index.html", content)
'
+ exec nginx -g 'daemon off;error_log stderr info;'
2023/10/25 08:45:30 [notice] 1645#1645: using the "epoll" event method
2023/10/25 08:45:30 [notice] 1645#1645: nginx/1.18.0 (Ubuntu)
2023/10/25 08:45:30 [notice] 1645#1645: OS: Linux 4.15.0-30-generic
2023/10/25 08:45:30 [notice] 1645#1645: getrlimit(RLIMIT_NOFILE): 1048576:[1048576](tel:1048576)
2023/10/25 08:45:30 [notice] 1645#1645: start worker processes
2023/10/25 08:45:30 [notice] 1645#1645: start worker process 1892
2023/10/25 08:45:30 [notice] 1645#1645: start worker process 1893
2023/10/25 08:45:30 [notice] 1645#1645: start worker process 1894
2023/10/25 08:45:30 [notice] 1645#1645: start worker process 1895
 
 
Machine specs are met.

**Comment by azaslavsky** [comment]
> Self-Hosted Version
> 1.9.15

That's not a self-hosted version number we've ever released. Please check the releases of this repository, and let us know which self-hosted version you are currently running.
