### ISSUE TITLE
Cannot switch organisations 

### ISSUE THREAD

**Issue by davidjmemmett** [getsentry/self-hosted#2521]
### Self-Hosted Version

23.10.1

### CPU Architecture

x86_64

### Docker Version

24.0.6 build ed223bc

### Docker Compose Version

v2.21.0

### Steps to Reproduce

1. At top-left, click Organisation name, then "Switch Organisation"
2. Note that "Create a new organisation" is the only option.

### Expected Result

When clicking "Switch Organisation" I expect a list of organisations that I'm a member of

### Actual Result

"Create a new organisation" is the only option.

**Comment by azaslavsky** [comment]
If you create a new org in this manner, does it show up in the list?

**Comment by joelpoxtonzoo** [comment]
Hi @azaslavsky 

No, it doesn't appear like any newly created organisations are available for selection either.

![image (7)](https://github.com/getsentry/self-hosted/assets/71333022/9bbdd0d7-d519-4370-ae69-fef295e0f106)

![image (8)](https://github.com/getsentry/self-hosted/assets/71333022/801d5608-421a-48aa-8c78-e5a638a8cd94)

**Comment by hubertdeng123** [comment]
Looks like you're trying to use a multi-org setup here, which is not the default that self-hosted Sentry comes with. Have you set the `SENTRY_SINGLE_ORGANIZATION` flag in your config file? How are you trying to enable the multi-org setup?

**Comment by davidjmemmett** [comment]
Hi @hubertdeng123, we've been successfully using multiple organisations in Sentry On-Premises for quite a few years now, the switcher appears to have broken somewhere between 23.9.1 (the previous, working version) and 23.10.1. The `SENTRY_SINGLE_ORGANIZATION` flag was toggled when we first started using Sentry On-Premises.

**Comment by hubertdeng123** [comment]
Got it, thanks for the context. I think hybrid cloud had some work with the control silo and region silo deployments so wondering if that affected anything here.

**Comment by markstory** [comment]
There were some recent changes to how the organization list is fetched as part of the work we're doing to make sentry multi-region. If you open the network panel in your browser, there should be requests going to the path `/api/0/organizations/?member=1` those requests power the org switcher menu.

The change I made was to make those requests use a host name instead of inheriting the host from the document. Could you check if the request to that endpoint is failing, and perhaps what if the host is correct?

**Comment by davidjmemmett** [comment]
Hi @markstory, we're seeing similar requests prefixed with an additional path delimiter: `//api/0/organizations/?member=1` - when navigating to that page, Sentry responds with a HTTP status code of 200 with a "Page Not Found" body.

Removing the extraneous path delimiter does return a JSON document containing the expected organisations. I have diffed our settings `sentry/sentry.conf.py` against the example settings, and there don't appear to be any settings missing/unset. Where is the host name set?

**Comment by davidjmemmett** [comment]
Upon further investigation, it turns out that we had a trailing path delimiter for the `system.url-prefix` settings in `sentry/config.yml`:

```
$ grep system.url-prefix sentry/config.example.yml 
# system.url-prefix: https://example.sentry.com
$ grep system.url-prefix sentry/config.yml 
system.url-prefix: https://redactedhostname/
```

After updating the `system.url-prefix` setting and restarting the containers, the issue appears to be resolved.

It may be worth [updating the documentation](https://develop.sentry.dev/config/#general:~:text=admin%40example.com%22-,system.url%2Dprefix,-Declared%20in%20config) to state that the `system.url-prefix` setting should not end with a trailing path delimiter.

Cheers,
David

**Comment by markstory** [comment]
> After updating the system.url-prefix setting and restarting the containers, the issue appears to be resolved.

Great to hear, I'm glad it was a simple fix.

> It may be worth [updating the documentation](https://develop.sentry.dev/config/#general:~:text=admin%40example.com%22-,system.url%2Dprefix,-Declared%20in%20config) to state that the system.url-prefix setting should not end with a trailing path delimiter.

I can do that :+1:
