### ISSUE TITLE
"upstream sent too big header while reading response header from upstream" when load many events from proxy

### ISSUE THREAD

**Issue by sistemasITI** [getsentry/self-hosted#2535]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

From our local network, i can see the events because I fixed it adding this to the Nginx on the local instance:

`        proxy_buffers    16 16k;
        proxy_buffer_size   32k;`

But if add this on our nginx reverse proxy (another instance) to access sentry from internet, the events are not loading.
We use sentry self-hosted 23.8.0
¿why this happens? 
Thank you.

### Expected Result

Show events on issues tab when access sentry from internet thought our proxy.

### Actual Result

events are not loading from sentry when access from internet

### Product Area

Issues

### Version

23.8.0

**Comment by hubertdeng123** [comment]
Is there by chance another nginx proxy on your machine that you haven't accounted for?

**Comment by sistemasITI** [comment]
this is part of my nginx config for websockets (I have to add that in other server with debian 11 and nginx 1.18.0
it works fine, but in debian 12 with nginx  1.22.1 it does not work)

`  location ~ /api/kernels/ {
    proxy_pass            http://url-to-website;
    proxy_set_header      Host $host;
    # websocket support
    proxy_http_version    1.1;
    proxy_set_header      Upgrade "websocket";
    proxy_set_header      Connection "Upgrade";
    proxy_read_timeout    86400;
  }

    location ~ /terminals/ {
    proxy_pass            http://url-to-website;
    proxy_set_header      Host $host;
    # websocket support
    proxy_http_version 1.1;
    proxy_set_header Upgrade "websocket";
    proxy_set_header Connection 'Upgrade';
    proxy_read_timeout    86400;
  }`

**Comment by sistemasITI** [comment]
sorry, its solved now. Thank you.
