### ISSUE TITLE
怎么查看已经超过保存期限的数据？

### ISSUE THREAD

**Issue by wujuwu** [getsentry/self-hosted#2538]
### Problem Statement

你好，我这边使用的sentry版本是23.2.0，我设置的数据保存期限是30天：
SENTRY_EVENT_RETENTION_DAYS=90
我也对数据进行过清理：
//登录postgres容器
docker exec -it sentry_onpremise_postgres_1 /bin/bash
//运行清理
vacuumdb -U postgres -d postgres -v -f --analyze
我们现在的需求是想查看一个月之前，具体来说是服务器停止1个月之前的历史数据，请问怎么操作？

**Comment by hubertdeng123** [comment]
Just to clarify, you are trying to find which data is older then 30 days? What kind of data are you looking for? The retention days seems to be for 90 days that you set there. The `SENTRY_EVENT_RETENTION_DAYS` is mostly applicable to snuba, which stores your event and other data in Clickhouse. If you'd like to view that data, you should look through clickhouse instead of postgres.

**Comment by wujuwu** [comment]
> Just to clarify, you are trying to find which data is older then 30 days? What kind of data are you looking for? The retention days seems to be for 90 days that you set there. The `SENTRY_EVENT_RETENTION_DAYS` is mostly applicable to snuba, which stores your event and other data in Clickhouse. If you'd like to view that data, you should look through clickhouse instead of postgres.

不好意思我发错了，应该是SENTRY_EVENT_RETENTION_DAYS=30，我们想查看已经被定时清理的数据，我看到postgres数据库里面有4.2G的大小，是不是只是应用清理了，但是数据库里面还有，怎么查看这些数据呢？

**Comment by hubertdeng123** [comment]
The retention days only applies to Clickhouse, as that is where we store event data. If you'd like to clean up I believe `sentry-cleanup` should do some of the work in cleaning up models, but that may not actually clear up disk space. You may need to clean that up manually yourself

**Comment by wujuwu** [comment]
Sorry, I may not have understood. What I mean is how to re read historical data from the database. I have already set SENTRY_ EVENT_ RETENTION_ DAYS=30, how can I view the data that Clickhouse has already cleaned? How can Clickhouse re read the data from the database?

**Comment by hubertdeng123** [comment]
Once Clickhouse cleans up the data, it no longer stores it and it is unaccessible. I'm a bit confused by your ask 😕

**Comment by wujuwu** [comment]
Sorry, this is a requirement for our product. There was some data that was not saved during the previous connection and I want to see it now, but it has been cleaned up. So I would like to ask if there is still any way to see it? If so, please let me know. If not, it's okay.




无拘物
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "getsentry/self-hosted"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月18日(星期六) 上午7:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [getsentry/self-hosted] 怎么查看已经超过保存期限的数据？ (Issue #2538)





 
Once Clickhouse cleans up the data, it no longer stores it and it is unaccessible. I'm a bit confused by your ask 😕

**Comment by hubertdeng123** [comment]
Unfortunately, there's no way for you to see it after it is cleaned up.

**Comment by wujuwu** [comment]
Okay, then there's no way. Thank you very much。




无拘物
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "getsentry/self-hosted"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月22日(星期三) 上午6:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [getsentry/self-hosted] 怎么查看已经超过保存期限的数据？ (Issue #2538)





 
Unfortunately, there's no way for you to see it after it is cleaned up.
