### ISSUE TITLE
Upgrading to 23.6.2 takes way too much time and there is no real progress display

### ISSUE THREAD

**Issue by afaianswq** [getsentry/self-hosted#2541]
### Self-Hosted Version

23.6.2

### CPU Architecture

x86_64

### Docker Version

24.0.7

### Docker Compose Version

2.21.0

### Steps to Reproduce

1. Start upgrading Sentry from 23.5.2 to 23.6.2

### Expected Result

Upgrade process runs smoothly, and even if it takes a long time to complete, there should be some in-between status updates.

### Actual Result

Nothing happens for almost 2 hours at all, I see this on my screen:

```
Running migrations for default
/usr/local/lib/python3.8/site-packages/memcache.py:1303: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key is '':
/usr/local/lib/python3.8/site-packages/memcache.py:1304: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key_extra_len is 0:
Audit Log Entrys: 100% |#######################################| Time:  0:00:03
Grouped Messages:  73% |############################           | ETA:   0:01:43
```

This is very disturbing because I don't know if upgrade has already failed or I need to wait few more (minutes, hours, weeks, years?) for it to complete.

It's also very strange that some migrations can take so much time on a e2-highcpu-32 class GCP machine.

**Comment by afaianswq** [comment]
I am constantly checking logs of `sentry-self-hosted-web-run-xxxx` container and it seems like app is trying to run migrations, get to 75-82% and crashes, and then starts over. And it keeps happening over and over and over again. Seems like a total failure to me.

**Comment by heraldurstromae** [comment]
This behaviour is also seen when running the backup.sh script from the scripts folder using a self-hosted Sentry version with docker:

```
Running hooks in /etc/ca-certificates/update.d...
done.
/usr/local/lib/python3.8/site-packages/memcache.py:1303: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key is '':
/usr/local/lib/python3.8/site-packages/memcache.py:1304: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key_extra_len is 0:
```
 
the script is hanging after this output for ~ 2 min and then exits without anymore output.
  
 I run similar version of docker/sentry as OP.

**Comment by azaslavsky** [comment]
The SyntaxWarning thing is a known issue in one of our dependencies - it is safe to ignore.

Regarding the slow upgrade - that is quite concerning. Maybe your instance is running out of memory during the upgrade?

**Comment by afaianswq** [comment]
Is 32GB RAM really low for Sentry? Anyway, I didn't notice RAM or any other resource shortage. And like I said, the migration was running and failing over and over again. I had to stop this process after 3 hours and restore from a backup.

**Comment by hubertdeng123** [comment]
How much RAM usage is really dependent on your usage of your Sentry instance. However, this should not be a problem during the upgrade process.
