### ISSUE TITLE
Does not accept events from another docker via host.docker.internal:9000

### ISSUE THREAD

**Issue by ilnytskyi** [getsentry/self-hosted#2542]
### Self-Hosted Version

23.11.0.dev0 c2e0590

### CPU Architecture

x86_64

### Docker Version

24.0.7

### Docker Compose Version

2.14.0

### Steps to Reproduce

1. Run self hosted sentry via `docker compose up -d`
2. Send logs from another docker container via `host.docker.internal:9000`
The container uses this config
```
    extra_hosts:
      host.docker.internal: host-gateway
```
its etc/hosts
```
www@e69d1ec4d29e:~$ cat /etc/hosts
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.17.0.1      host.docker.internal
192.168.240.7   e69d1ec4d29e
```
3. Use magento 2 with config and package https://github.com/justbetter/magento2-sentry
```
    'sentry' => [
        #Does not work locally
        'dsn' => 'http://2c057162f1722da0f915ccd3bfd3e57d@host.docker.internal:9000/2',
        #Works Ok with cloud
//        'dsn' => 'https://XXXX@XXXXX.ingest.sentry.io/11122333',
        'logrocket_key' => 'example/example',
        'environment' => 'development',
        'log_level' => \Monolog\Logger::INFO,
        'errorexception_reporting' => E_ALL,
        'ignore_exceptions' => [],
        'mage_mode_development' => true,
        'js_sdk_version' => \JustBetter\Sentry\Block\SentryScript::CURRENT_VERSION,
        'tracing_enabled' => true,
        'tracing_sample_rate' => 0.5,
        'ignore_js_errors' => []
    ],
```
4. I attach my binary request intercepred via ngrok (also does not work, even tried to send that manually via postman directly from host machine)
[request.txt](https://github.com/getsentry/self-hosted/files/13257359/request.txt)

### Expected Result

1. Sentry accepts events and logs are visible in the panel
2. Just like with cloud version. Used same config but different DSN
![Selection_909](https://github.com/getsentry/self-hosted/assets/3192770/dd40a4de-b8bd-4202-84ad-949c34633508)

### Actual Result

1. Sentry is empty 
![Selection_910](https://github.com/getsentry/self-hosted/assets/3192770/1d83c9f9-14bb-45a8-a1bd-c53a81a85356)
2. Senty nginx container logs shows 502 errors
```
2023/11/04 15:42:54 [error] 23#23: *1580 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.0.1, server: , request: "POST /api/2/store/ HTTP/1.1", upstream: "http://172.30.0.16:3000/api/2/store/", host: "host.docker.internal:9000"
2023-11-04T15:42:54.087162845Z 172.30.0.1 - - [04/Nov/2023:15:42:54 +0000] "POST /api/2/store/ HTTP/1.1" 502 150 "-" "sentry.php/3.22.0" "-"
```
Also cannot be proxied via ngrok to `9000`, same error in logs.
3. When trying to intercept via ngrok and resend request manually via postman it shows this error
```
CSRF Verification Failed
A required security token was not found or was invalid.

If you're continually seeing this issue, try the following:

Clear cookies (at least for Sentry's domain).
Reload the page you're trying to submit (don't re-submit data).
Re-enter the information, and submit the form again.
Ensure the URL does not contain an extra "/" anywhere (eg: https://foo//saml -> https://foo/saml).
```
![Selection_911](https://github.com/getsentry/self-hosted/assets/3192770/3453aa10-91b5-47ff-8136-31e0df43e37f)
4. When removing trailing slash it shows login page
![Selection_912](https://github.com/getsentry/self-hosted/assets/3192770/fff0ee6a-ef5d-464a-bbf4-749d21ab1340)

**ngrok** and **postman** are used to confirm no problem with network between two dockers.
Since I assume that there is problem with sentry built-in nginx or something else.
Interestingly when I do wget to `host.docker.internal:9000` it downloads login page, so my docker image can see Sentry image. But when sending events there is `502` .
The output from sentry docker compose
[sentry.log](https://github.com/getsentry/self-hosted/files/13257407/sentry.log)
shows this service on port 3000
```
sentry-self-hosted-relay-1                                          "/bin/bash /docker-e…"   relay                                          running             3000/tcp
```
5. There are also many 502 for these requests every few seconds (not sure from where they are coming, probably, some internal checker service)
```
172.30.0.1 - - [04/Nov/2023:18:15:52 +0000] "502\x00<?xml version=\x221.0\x22 encoding=\x22iso-8859-1\x22?>" 400 150 "-" "-" "-"
```

**Comment by azaslavsky** [comment]
Have you tried setting up proxy buffering for nginx? Similar issue that experienced 502s:

https://github.com/getsentry/self-hosted/issues/2256
