### ISSUE TITLE
Failed to install on centos 7 

### ISSUE THREAD

**Issue by swenker** [getsentry/self-hosted#2544]
### Self-Hosted Version

23.10.1

### CPU Architecture

x86_64

### Docker Version

20.10.22

### Docker Compose Version

2.20.3

### Steps to Reproduce

just execute ./install.sh

### Expected Result

the process finished successfully.

### Actual Result

`
#8 [symbolicator-cleanup 4/5] RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
#8 0.777 Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
#8 1.507 Get:2 http://deb.debian.org/debian bookworm-updates InRelease [52.1 kB]
#8 1.898 Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
#8 2.366 Get:4 http://deb.debian.org/debian bookworm/main amd64 Packages [8780 kB]
#8 316.7 Get:5 http://deb.debian.org/debian bookworm-updates/main amd64 Packages [6408 B]
#8 316.9 Get:6 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [96.0 kB]
#8 320.5 Fetched 9134 kB in 5min 20s (28.5 kB/s)
#8 320.5 Reading package lists...
#8 321.0 E: Problem executing scripts APT::Update::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'
#8 321.0 E: Sub-process returned an error code
#8 ERROR: executor failed running [/bin/sh -c apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*]: exit code: 100
------
 > [symbolicator-cleanup 4/5] RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*:
0.777 Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
1.507 Get:2 http://deb.debian.org/debian bookworm-updates InRelease [52.1 kB]
1.898 Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
2.366 Get:4 http://deb.debian.org/debian bookworm/main amd64 Packages [8780 kB]
316.7 Get:5 http://deb.debian.org/debian bookworm-updates/main amd64 Packages [6408 B]
316.9 Get:6 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [96.0 kB]

321.0 E: Problem executing scripts APT::Update::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'
321.0 E: Sub-process returned an error code
------
failed to solve: executor failed running [/bin/sh -c apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*]: exit code: 100
Error in install/build-docker-images.sh:9.
'$dcb --force-rm "$service"' exited with status 17
-> ./install.sh:main:29
--> install/build-docker-images.sh:source:9

Cleaning up...
`
Here is the full install log:
[sentry_install_log-2023-11-06_11-49-40.txt](https://github.com/getsentry/self-hosted/files/13262885/sentry_install_log-2023-11-06_11-49-40.txt)

**Comment by 396266318** [comment]
机器的配置
CentOS Linux release 7.9.2009 (Core)
4C8G
self-hosted version 23.10.1
执行 docker compose up -d，现在机器上执行任何命令都会报此提示
[sentry_install_log-2023-11-07_09-31-36.txt](https://github.com/getsentry/self-hosted/files/13274761/sentry_install_log-2023-11-07_09-31-36.txt)

Error: either "dev" is duplicate, or "veth83407f2@if206" is a garbage.

**Comment by swenker** [comment]
Hi there, what I wanna say is that I've got succeeded with self-hosted-23.7.2 just now. 
Hope you guys can take a look at the log uploaded with 23.10.1.

Thanks.

**Comment by azaslavsky** [comment]
Just to clarify: get exit code 100 on 23.10.1, but it succeeds no problem on 23.7.2? That's very odd, since that exit code usually means that apt-get failed to pull something down. This is true even if you retry on 23.10.1?

**Comment by jibenziliao** [comment]
same error

Self-Hosted Version
23.10.1

CPU Architecture
x86_64

Docker Version
24.0.7

Docker Compose Version
2.23.0

Steps to Reproduce
just execute ./install.sh

Expected Result
the process finished successfully.

Actual Result

```
▶ Parsing command line ...

▶ Detecting Docker platform
Detected Docker platform is linux/amd64

▶ Initializing Docker Compose ...

▶ Setting up error handling ...
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 292B done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 transferring context: 2B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/debian:bullseye-slim
#3 DONE 16.9s

#4 [1/2] FROM docker.io/library/debian:bullseye-slim@sha256:b0d53c872fd640c2af2608ba1e693cfc7dedea30abcd8f584b23d583ec6dadc7
#4 CACHED

#5 [2/2] RUN set -x   && apt-get update   && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends jq   && apt-get clean   && rm -rf /var/lib/apt/lists/*
#5 0.275 + apt-get update
#5 1.029 Get:1 http://security.debian.org/debian-security bullseye-security InRelease [48.4 kB]
#5 1.584 Get:2 http://security.debian.org/debian-security bullseye-security/main amd64 Packages [258 kB]
#5 2.259 Get:3 http://deb.debian.org/debian bullseye InRelease [116 kB]
#5 2.745 Get:4 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
#5 3.408 Get:5 http://deb.debian.org/debian bullseye/main amd64 Packages [8062 kB]
#5 357.7 Ign:5 http://deb.debian.org/debian bullseye/main amd64 Packages
#5 388.2 Ign:6 http://deb.debian.org/debian bullseye-updates/main amd64 Packages
#5 389.1 Ign:5 http://deb.debian.org/debian bullseye/main amd64 Packages
#5 389.1 Ign:6 http://deb.debian.org/debian bullseye-updates/main amd64 Packages
#5 389.1 Ign:5 http://deb.debian.org/debian bullseye/main amd64 Packages
#5 389.1 Ign:6 http://deb.debian.org/debian bullseye-updates/main amd64 Packages
#5 389.1 Ign:5 http://deb.debian.org/debian bullseye/main amd64 Packages
#5 389.1 Err:6 http://deb.debian.org/debian bullseye-updates/main amd64 Packages
#5 389.1   Could not connect to deb.debian.org:80 (151.101.110.132), connection timed out [IP: 151.101.110.132 80]
#5 389.1 Ign:5 http://deb.debian.org/debian bullseye/main amd64 Packages
#5 389.1 Err:5 http://deb.debian.org/debian bullseye/main amd64 Packages
#5 389.1   Connection timed out [IP: 151.101.110.132 80]
#5 389.1 Fetched 466 kB in 6min 29s (1199 B/s)
#5 389.1 Reading package lists...
#5 389.1 W: Failed to fetch http://deb.debian.org/debian/dists/bullseye/main/binary-amd64/Packages  Connection timed out [IP: 151.101.110.132 80]
#5 389.1 W: Failed to fetch http://deb.debian.org/debian/dists/bullseye-updates/main/binary-amd64/Packages  Could not connect to deb.debian.org:80 (151.101.110.132), connection timed out [IP: 151.101.110.132 80]
#5 389.1 W: Some index files failed to download. They have been ignored, or old ones used instead.
#5 389.1 + DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends jq
#5 389.1 Reading package lists...
#5 389.2 Building dependency tree...
#5 389.2 Reading state information...
#5 389.2 E: Unable to locate package jq
#5 ERROR: executor failed running [/bin/sh -c set -x   && apt-get update   && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends jq   && apt-get clean   && rm -rf /var/lib/apt/lists/*]: exit code: 100
------
 > [2/2] RUN set -x   && apt-get update   && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends jq   && apt-get clean   && rm -rf /var/lib/apt/lists/*:
389.1 Fetched 466 kB in 6min 29s (1199 B/s)
389.1 Reading package lists...
389.1 W: Failed to fetch http://deb.debian.org/debian/dists/bullseye/main/binary-amd64/Packages  Connection timed out [IP: 151.101.110.132 80]
389.1 W: Failed to fetch http://deb.debian.org/debian/dists/bullseye-updates/main/binary-amd64/Packages  Could not connect to deb.debian.org:80 (151.101.110.132), connection timed out [IP: 151.101.110.132 80]
389.1 W: Some index files failed to download. They have been ignored, or old ones used instead.
389.1 + DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends jq
389.1 Reading package lists...
389.2 Building dependency tree...
389.2 Reading state information...
389.2 E: Unable to locate package jq
------
ERROR: failed to solve: executor failed running [/bin/sh -c set -x   && apt-get update   && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends jq   && apt-get clean   && rm -rf /var/lib/apt/lists/*]: exit code: 100
```

**Comment by swenker** [comment]
> Just to clarify: get exit code 100 on 23.10.1, but it succeeds no problem on 23.7.2? That's very odd, since that exit code usually means that apt-get failed to pull something down. This is true even if you retry on 23.10.1?

Yes. I'm also confused.  Anyway, I am happy with 23.7.2 at the moment  even if I don't know why 23.10.1 doesn't work . 

By the way, is it possible to release an version without so many online update requests ?  What I have tried is to export all the images to an server without internet connection. But it failed.

**Comment by hubertdeng123** [comment]
Have you tried running the install script multiple times? This doesn't appear to be an issue with our script but some network issue. Wonder if there is some sort of firewall rule on your side preventing the package from being downloaded.

**Comment by innocentjulie** [comment]
阿里云 ，centos7.9安装[23.11.1](https://github.com/getsentry/self-hosted/releases/tag/23.11.1) 或者23.7.2都会报一样的错，都是
#2 [sentry-cleanup internal] load .dockerignore
#2 transferring context: 2B done
#2 DONE 0.0s

#3 [sentry-cleanup internal] load metadata for docker.io/library/sentry-self-hosted-local:latest
#3 DONE 0.0s

#4 [sentry-cleanup internal] load build context
#4 transferring context: 35B done
#4 DONE 0.0s

#5 [sentry-cleanup 1/5] FROM docker.io/library/sentry-self-hosted-local
#5 DONE 0.0s

#6 [sentry-cleanup 2/5] RUN if [ -z "${http_proxy}" ]; then echo "Acquire::http::proxy "${http_proxy}";" >> /etc/apt/apt.conf; fi
#6 DONE 0.3s

#7 [sentry-cleanup 3/5] RUN if [ -z "${https_proxy}" ]; then echo "Acquire::https::proxy "${https_proxy}";" >> /etc/apt/apt.conf; fi
#7 DONE 0.4s

#8 [sentry-cleanup 4/5] RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
#8 31.02 Err:1 http://deb.debian.org/debian bullseye InRelease
#8 31.02   Could not connect to debian.map.fastlydns.net:80 (151.101.110.132), connection timed out Unable to connect to deb.debian.org:http:
#8 31.02 Err:2 http://deb.debian.org/debian-security bullseye-security InRelease
#8 31.02   Unable to connect to deb.debian.org:http:
#8 31.02 Err:3 http://deb.debian.org/debian bullseye-updates InRelease
#8 31.02   Unable to connect to deb.debian.org:http:
#8 31.03 Reading package lists...
#8 31.04 W: Failed to fetch http://deb.debian.org/debian/dists/bullseye/InRelease  Could not connect to debian.map.fastlydns.net:80 (151.101.110.132), connection timed out Unable to connect to deb.debian.org:http:
#8 31.04 W: Failed to fetch http://deb.debian.org/debian-security/dists/bullseye-security/InRelease  Unable to connect to deb.debian.org:http:
#8 31.04 W: Failed to fetch http://deb.debian.org/debian/dists/bullseye-updates/InRelease  Unable to connect to deb.debian.org:http:
#8 31.04 W: Some index files failed to download. They have been ignored, or old ones used instead.
#8 31.04 Reading package lists...
#8 31.05 Building dependency tree...
#8 31.05 Reading state information...
#8 31.06 E: Unable to locate package cron
#8 ERROR: process "/bin/sh -c apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*" did not complete successfully: exit code: 100
------
 > [sentry-cleanup 4/5] RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*:
31.02   Unable to connect to deb.debian.org:http:
31.03 Reading package lists...
31.04 W: Failed to fetch http://deb.debian.org/debian/dists/bullseye/InRelease  Could not connect to debian.map.fastlydns.net:80 (151.101.110.132), connection timed out Unable to connect to deb.debian.org:http:
31.04 W: Failed to fetch http://deb.debian.org/debian-security/dists/bullseye-security/InRelease  Unable to connect to deb.debian.org:http:
31.04 W: Failed to fetch http://deb.debian.org/debian/dists/bullseye-updates/InRelease  Unable to connect to deb.debian.org:http:
31.04 W: Some index files failed to download. They have been ignored, or old ones used instead.
31.04 Reading package lists...
31.05 Building dependency tree...
31.05 Reading state information...
31.06 E: Unable to locate package cron
------
failed to solve: process "/bin/sh -c apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*" did not complete successfully: exit code: 100
Error in install/build-docker-images.sh:9.
'$dcb --force-rm "$service"' exited with status 17
-> ./install.sh:main:29
--> install/build-docker-images.sh:source:9

**Comment by azaslavsky** [comment]
Does [this](https://stackoverflow.com/a/38004106) suggestion help?
