### ISSUE TITLE
Can't fetch issues via API

### ISSUE THREAD

**Issue by darrelajonas** [getsentry/self-hosted#2554]
### Self-Hosted Version

23.11.0.dev0

### CPU Architecture

x86_64

### Docker Version

24.0.5, build ced0996

### Docker Compose Version

2.23.0

### Steps to Reproduce

1. Import Sentry postman collection
2. Generate an internal integration auth token (with read access to issues and events)
3. Configure postman to use the auth token
4. Try running the 'List Project Issues' API endpoint

### Expected Result

A JSON formatted list of issues to be returned

### Actual Result

![image](https://github.com/getsentry/self-hosted/assets/149162517/56387cec-dd70-4787-8032-b38d85033629)

**Comment by azaslavsky** [comment]
Is the user for which you created the Auth Token a member of the org in question? Are they marked as a superuser?

**Comment by darrelajonas** [comment]
The instructions I found online said to create an Internal Integration 

Ref: https://www.postman.com/sentryio/workspace/sentry-api-collection/collection/314074-08877b7b-7cdf-49db-b558-3c1553367cfa

**Comment by darrelajonas** [comment]
^ bump

**Comment by hubertdeng123** [comment]
I would make sure to check the permissions of the API auth token to ensure it has permissions to access the org issues

**Comment by darrelajonas** [comment]
OK I started again. Created an Auth Token for my own user account with full Admin permissions.

![image](https://github.com/getsentry/self-hosted/assets/149162517/bfc37a3f-2985-4dc1-88bb-7cf8d16368cd)


Then added the token as a Bearer token in Postman. 

Tried fetching issues for a project. Got this:

![image](https://github.com/getsentry/self-hosted/assets/149162517/c2cddfff-14cd-4adb-896e-fdc9905922b6)

**Comment by hubertdeng123** [comment]
At least we have some progress there. I'm not quite sure what your library does, since I'm not familiar with that, but can you try using curl as specified here?
https://docs.sentry.io/api/events/list-a-projects-issues/
