### ISSUE TITLE
Unable to pull `sentry-self-hosted-local` Docker image "pull access denied"

### ISSUE THREAD

**Issue by nguyenbry** [getsentry/self-hosted#2557]
### Self-Hosted Version

23.10.1

### CPU Architecture

arm64

### Docker Version

20.10.23

### Docker Compose Version

2.15.1

### Steps to Reproduce

1. Install zip from `https://github.com/getsentry/self-hosted/releases/tag/23.10.1`
2. Extract
3. cd into folder and `./install.sh`

### Expected Result

Install scrip should complete without error and the docker image should be able to be pulled.

### Actual Result

```

#2 [internal] load metadata for docker.io/library/sentry-self-hosted-local:latest
#2 ...

#3 [auth] library/sentry-self-hosted-local:pull token for registry-1.docker.io
#3 DONE 0.0s

#2 [internal] load metadata for docker.io/library/sentry-self-hosted-local:latest
#2 ERROR: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
------
 > [internal] load metadata for docker.io/library/sentry-self-hosted-local:latest:
------
failed to solve: sentry-self-hosted-local: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
Error in install/build-docker-images.sh:8.
'$dcb --force-rm "$service"' exited with status 17
-> ./install.sh:main:29
--> install/build-docker-images.sh:source:8

Cleaning up...

```

**Comment by azaslavsky** [comment]
This is almost certainly an issue with either your local docker settings, or a firewall/VPN you are behind. I just ran the install script with no issues, so I don't think its down remotely.

**Comment by barthez** [comment]
I had the same issue. I managed to build Sentry self-hosted by disabling the docker buildkit:
```
export DOCKER_BUILDKIT=0
```
However, I don't think it is the permanent solution since I can now see a deprecation warning:
```
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            BuildKit is currently disabled; enable it by removing the DOCKER_BUILDKIT=0
            environment-variable.
```
