### ISSUE TITLE
run ./install.sh error

### ISSUE THREAD

**Issue by shezhangzhang** [getsentry/self-hosted#2558]
### Self-Hosted Version

23.10.1

### CPU Architecture

aarch64 （apple m1 pro chip）

### Docker Version

24.0.6

### Docker Compose Version

v2.22.0-desktop.2

### Steps to Reproduce

./install.sh

### Expected Result

localhost:8000

### Actual Result

▶ Bootstrapping and migrating Snuba ...
 Network sentry-self-hosted_default  Creating
 Network sentry-self-hosted_default  Created
 Container sentry-self-hosted-zookeeper-1  Creating
 Container sentry-self-hosted-clickhouse-1  Creating
 Container sentry-self-hosted-redis-1  Creating
 zookeeper The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 
 Container sentry-self-hosted-clickhouse-1  Created
 Container sentry-self-hosted-redis-1  Created
 Container sentry-self-hosted-zookeeper-1  Created
 Container sentry-self-hosted-kafka-1  Creating
 kafka The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 
 Container sentry-self-hosted-kafka-1  Created
 Container sentry-self-hosted-zookeeper-1  Starting
 Container sentry-self-hosted-redis-1  Starting
 Container sentry-self-hosted-clickhouse-1  Starting
 Container sentry-self-hosted-clickhouse-1  Started
 Container sentry-self-hosted-zookeeper-1  Started
 Container sentry-self-hosted-zookeeper-1  Waiting
 Container sentry-self-hosted-redis-1  Started
 Container sentry-self-hosted-zookeeper-1  Healthy
 Container sentry-self-hosted-kafka-1  Starting
 Container sentry-self-hosted-kafka-1  Started
dependency failed to start: container sentry-self-hosted-kafka-1 is unhealthy
Error in install/bootstrap-snuba.sh:3.
'$dcr snuba-api bootstrap --no-migrate --force' exited with status 1
-> ./install.sh:main:31
--> install/bootstrap-snuba.sh:source:3

Cleaning up...

**Comment by shezhangzhang** [comment]
everything is 'latest', just run ./install.sh, failed.

**Comment by azaslavsky** [comment]
This is a new installation?

**Comment by shezhangzhang** [comment]
Yes, first time. I cloned the repo, and simply run './install.sh', and got that error.

**Comment by shezhangzhang** [comment]
OMG, can't believe that when I upgraded MacOS from v14 to the latest version, v14.1.1, it works...

**Comment by shezhangzhang** [comment]
When I add this: `platform: linux/amd64` to `kafka` and `smtp` section in docker-compose.yml, it works!

**Comment by CarloMara** [comment]
I'm seeing the same on a standard x86 linux box, any hopes this gets fixed soon?

**Comment by kavyuwu** [comment]
I am getting this too on my M1 Mac, new install for the first time

**Comment by hubertdeng123** [comment]
This is an ongoing issue here:
https://github.com/getsentry/self-hosted/issues/1585

Closing as a duplicate, please add your concerns in that ticket
