### ISSUE TITLE
Can not copy invite link from invite page 23.10.0 29f407b

### ISSUE THREAD

**Issue by d4mk0** [getsentry/self-hosted#2559]
### Problem Statement

I can not copy and share invite link from invite page

### Solution Brainstorm

Hello

We have 2 self hosted installations.
First - Sentry **22.11.0 60999b0**
Second - Sentry **23.10.0 29f407b**

In first installation I can invite member, and enter to this invite and copy invite link (version 22)
In second - I can`t see invite link (version 23)

What happened? Security issues? Can be enabled by config? Maybe it is installtion problems?

Thanks.

It was very useful. I think it is required feature for non-email servers.

**Comment by azaslavsky** [comment]
Do you mind posting comparative photos of what's happening on your two installations? And perhaps steps to reproduce as well? I'm having a bit of trouble zeroing in on exactly what you mean.

**Comment by d4mk0** [comment]
All screenshots was taken in organization -> members -> show page.

Without invitation link (23.10.0)
![image](https://github.com/getsentry/self-hosted/assets/4139198/6c0fbd0d-deec-4d9c-b833-40f2a02e8024)


With invitation link (22.11.0)
![image](https://github.com/getsentry/self-hosted/assets/4139198/0a30ef96-577e-43e9-b3e1-5d824cfc0523)

**Comment by hubertdeng123** [comment]
Looks like it was removed here:
https://github.com/getsentry/sentry/pull/53978
