### ISSUE TITLE
[On-Premise 23.8.0] Email invitation links become invalid immediately after sending 

### ISSUE THREAD

**Issue by kurousa** [getsentry/self-hosted#2561]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

1. send an invitation email from `/settings/sentry/members/` with "Resend Invitation".

2. click `Join your team` button in the received mail

### Expected Result

The invitation link must function properly.

### Actual Result

A message will appear on the web page that opens.
"This organization invite link is no longer valid.

### Product Area

Settings - Members

### Version

23.8.0

**Comment by SsuperL** [comment]
I'm facing this problem too.

**Comment by hubertdeng123** [comment]
@SsuperL are you also on 23.8.0? Wondering when this regression happened and if it may have been fixed in later versions.

**Comment by milandufek** [comment]
We are facing the same issue on `23.10.1`.

**Comment by hubertdeng123** [comment]
I'm able to reproduce this. Looks like the response is `{"details":"Invalid invite code"}`

**Comment by markstory** [comment]
When you go to accept the invitation link is in a browser window that already has a session?  I was able to reproduce the 'invalid invite code' state when I was logged in as a member that already existed in the organization. However, the links did work for me locally when I used the invite link in a private browsing window.

Are you able to check that the token & member id in the generated email link are also present in the `sentry_organizationmember` table?

**Comment by doccorso** [comment]
Hi, my version is also 23.8.0 and we are facing the same issue. There is any recent version without this regression?

Thanks
Davide

**Comment by hubertdeng123** [comment]
Have you ensured that your browser window does not already have a session?

**Comment by kurousa** [comment]
For this issue, we have confirmed that the workaround suggested by @markstory, 
i.e., if the invitee clicks on the invite URL in the email while in Private Browsing, this works fine.

FYI.

**Comment by doccorso** [comment]
@hubertdeng123 workaround work fine.

Thanks a lot

**Comment by maparent** [comment]
@kurousa  as described, the workaround did not work for me.

**Comment by hubertdeng123** [comment]
@maparent Did you happen to hit the hard stop at 23.6.2 while upgrading? This error looks pretty different if that's what you're seeing on login
`No Organization Access: You do not have access to any organizations within Sentry.`

**Comment by maparent** [comment]
I did miss the hard stop. The upgraded proceeded, though. Should I restore from backup and start over?

**Comment by azaslavsky** [comment]
Restoring from a backup, if you have one, seems reasonable. I would try on a separate box just to be sure, as backups across many versions can be unpredictable.
