### ISSUE TITLE
dependency failed to start: container sentry-self-hosted-clickhouse-1 is unhealthy

### ISSUE THREAD

**Issue by kkflie** [getsentry/self-hosted#2563]
### Self-Hosted Version

23.10.1

### CPU Architecture

x86_64

### Docker Version

24.0.2

### Docker Compose Version

2.21.0

### Steps to Reproduce

1.git clone repo by tag 23.10.1
2. ./install.sh

### Expected Result

everything works fine

### Actual Result

▶ Bootstrapping and migrating Snuba ...
 Network sentry-self-hosted_default  Creating
 Network sentry-self-hosted_default  Created
 Container sentry-self-hosted-clickhouse-1  Creating
 Container sentry-self-hosted-redis-1  Creating
 Container sentry-self-hosted-zookeeper-1  Creating
 Container sentry-self-hosted-zookeeper-1  Created
 Container sentry-self-hosted-kafka-1  Creating
 Container sentry-self-hosted-redis-1  Created
 Container sentry-self-hosted-clickhouse-1  Created
 Container sentry-self-hosted-kafka-1  Created
 Container sentry-self-hosted-redis-1  Starting
 Container sentry-self-hosted-clickhouse-1  Starting
 Container sentry-self-hosted-zookeeper-1  Starting
 Container sentry-self-hosted-redis-1  Started
 Container sentry-self-hosted-clickhouse-1  Started
 Container sentry-self-hosted-zookeeper-1  Started
 Container sentry-self-hosted-zookeeper-1  Waiting
 Container sentry-self-hosted-zookeeper-1  Healthy
 Container sentry-self-hosted-kafka-1  Starting
 Container sentry-self-hosted-kafka-1  Started
dependency failed to start: container sentry-self-hosted-clickhouse-1 is unhealthy
Error in install/bootstrap-snuba.sh:3.
'$dcr snuba-api bootstrap --no-migrate --force' exited with status 1
-> ./install.sh:main:31
--> install/bootstrap-snuba.sh:source:3

Cleaning up...

-  logs of  sentry-self-hosted-clickhouse-1 are here:
 [sentry-self-hosted-clickhouse-1.txt](https://github.com/getsentry/self-hosted/files/13325707/sentry-self-hosted-clickhouse-1.txt)
- docker compose logs are here:
 [docker-compose-logs.txt](https://github.com/getsentry/self-hosted/files/13325782/docker-compose-logs.txt)

**Comment by hubertdeng123** [comment]
I haven't seen this before:
`Unknown setting allow_nullable_key for storage AggregatingMergeTree`

Could you try deleting your clickhouse volume and recreating?
