### ISSUE TITLE
Github integration setup is breaking (oops page)

### ISSUE THREAD

**Issue by pweissbrod-eh** [getsentry/self-hosted#2569]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

I am trying to set up github with self-hosted sentry. I encountered the problem reported in issue getsentry/sentry#30865 
I am attempting [THE INSTRUCTIONS HERE](https://github.com/getsentry/sentry/issues/30865#issuecomment-1004196446)
I have created a github app using [THE INSTRUCTIONS HERE](https://develop.sentry.dev/integrations/github/)
I attempt to "install" the app in github. This is where the problems begin.

### Expected Result

I expect redirection to the sentry github integration page inside my hosted sentry instance.

### Actual Result

I get redirected to https://MYSENTRY/extensions/github-enterprise/setup/?installation_id=43771069&setup_action=install
This displays an internal server error.
![image](https://github.com/getsentry/sentry/assets/143639778/01b19ba3-c2d8-4250-8afc-1d8ad71453b1)

OTHER NOTES:
 - github attempts an oauth auth-code flow integration with my sentry instance using `https://MYSENTRY/extensions/github/setup/?installation_id=43771157&setup_action=install`
 - the sentry instance redirects to github `https://github.com/login/oauth/authorize?client_id=Iv1.18a364b69870d4de&response_type=code&scope=&state=7362092d16b74599b2fce82f83090f67&redirect_uri=https%3A%2F%2FMYSENTRY%2Fextensions%2Fgithub-enterprise%2Fsetup%2F`
 - NOTE ABOVE the `redirect_uri` is `github-enterprise` and not `github`!!!
 - NOTE2 for this to work the `redirect_uri` specified must be added to the github app callback urls otherwise we get an invalid redirect uri error from github
 - github redirects to https://FMYSENTRY/extensions/github-enterprise/setup/ with one of the codes in the url
 - this is where the server-side 500 error appears

### Product Area

Settings - Integrations

### Version

23.1.0.dev0

**Comment by hubertdeng123** [comment]
What happens when you manually try and hit the endpoint for `github` instead of `github-enterprise`? This doesn't appear to be normal. Are you using the docker compose version of self-hosted Sentry?

**Comment by ingria** [comment]
I have the same error.

I've tried using [this form](https://develop.sentry.dev/integrations/github/). I have a multi-tenant Sentry and I enter `https://mysentry.test` as `url-prefix`. This form autogenerates the following setup URL for the app:

```
https://mysentry.test/extensions/github/setup/
```

When I press on the "install app" button on github, it tries to open the following URL:

```
https://mysentry.test/extensions/github/setup/?installation_id=123456789&setup_action=install
```

And this happens:

![image](https://github.com/getsentry/self-hosted/assets/2178368/381d5a38-9cc3-441e-af94-1cb738236fa9)

If I use this URL as `url-prefix`:

```
https://mysentry.test/settings/my-sentry-organization/integrations
```

It still doesn't work: after I press installatiion button, the page shows spinner for some time (about 10 seconds) and then fails:

![image](https://github.com/getsentry/self-hosted/assets/2178368/19da8595-6b42-48a1-9fd4-ff063c6b71a0)

![image](https://github.com/getsentry/self-hosted/assets/2178368/8b842582-6eaa-4d0a-a3de-8391faff32c1)

**Comment by azaslavsky** [comment]
Before you get that error after seeing the spinner for 10 seconds, can you open chrom devtools and see what comes up. Do any network calls fail? Do errors get logged to the console?

**Comment by ingria** [comment]
There are two GET requests to `/api/0/organizations/org-slug/integrations/setup/` without any params. Both end up with 500 error:

```json
{"detail":"Internal Error","errorId":"some-id"}
```

Also, if I try to open this URL:

`/extensions/external-install/github/{app-id}/`

I can see the "Finish installation" page, but it shows an error:

![image](https://github.com/getsentry/self-hosted/assets/2178368/beda1847-797d-4c67-8040-1d2984528b89)

If I click on the "install github button", the following URL opens in new window:

`/organizations/org-slug/integrations/github/setup/?installation_id={app-id}`

![image](https://github.com/getsentry/self-hosted/assets/2178368/311c3ff8-a5bc-4e60-abad-4a6004d3aafa)

**Comment by azaslavsky** [comment]
Ok, when you get the `500` errors, do you see anything in your server logs (particularly `web`, but any others are of interest too)?
