### ISSUE TITLE
get error when execution ./install.sh

### ISSUE THREAD

**Issue by degary** [getsentry/self-hosted#2572]
### Self-Hosted Version

23.10.1

### CPU Architecture

x86_64

### Docker Version

24.0.7

### Docker Compose Version

2.21.0

### Steps to Reproduce

1. ./install.sh

### Expected Result

install success

### Actual Result

./docker_entrypoint.sh: line 15: exec: bootstrap: not found
Error in install/bootstrap-snuba.sh:3.
'$der snuba-api bootstrap --no-migrate --force' exited with status 127
-> ./install.sh:main: 31
--> install/bootstrap-snuba. sh: source: 3
error: The subcommand 'send-envelope' wasn't recognized
Did you mean 'send-event'?
|If you believe you received this message in error, try re-running with 'sentry-cli -- send-envelope

**Comment by hubertdeng123** [comment]
Where is the `./docker_entrypoint` coming from? Did you upgrade from an earlier version of self-hosted Sentry?

**Comment by taoqiyang** [comment]
@degary same error...
