### ISSUE TITLE
Sentry issues Showing only records within 7 days

### ISSUE THREAD

**Issue by NikoLXQ** [getsentry/self-hosted#2578]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### What are you trying to accomplish?

I want to see more issues, not only within 7 days.

### How are you getting stuck?

![ETLvb8ZN3ouhJExZiYgc2NOin2z](https://github.com/getsentry/sentry/assets/16128430/77de2221-7aba-477b-ba1b-0ad164804b5e)
As shown above, even if you choose to show data for 14 days. But the result still shows only within 7 days.
Is this related to the backend configuration SENTRY_EVENT_RETENTION_DAYS ?

### Where in the product are you?

Issues

**Comment by hubertdeng123** [comment]
It could be related to `SENTRY_EVENT_RETENTION_DAYS`. What do you have that value set to?

**Comment by NikoLXQ** [comment]
I set the 30, but it still only show the records within 7 days. Actually if use the event link to access , it's accessable

**Comment by hubertdeng123** [comment]
Are you sure your Sentry instance has events that are older than 7 days then? What version of self-hosted Sentry are you using? This doesn't seem normal and otherwise I'm not sure why this might be happening.
