### ISSUE TITLE
Can not connect to my Ruby app hosting on LightSail Ubuntu 22.04

### ISSUE THREAD

**Issue by ghun131** [getsentry/self-hosted#2583]
### Self-Hosted Version

23.10.1

### CPU Architecture

x86_64

### Docker Version

24.0.7

### Docker Compose Version

2.21.0

### Steps to Reproduce

1. Install sentry self hosted successfully
2. Run with `docker compose up -d`
3. Access the web on my domain http://xyz.uhgn.net
4. Follow installation instruction
<img width="924" alt="image" src="https://github.com/getsentry/self-hosted/assets/33661599/baa198df-4f9d-44e3-b090-df1bbed6f947">

### Expected Result

Sentry self hosted does not track data. The web looks like this 

<img width="1157" alt="image" src="https://github.com/getsentry/self-hosted/assets/33661599/6d473e19-e903-4d78-8e5c-80f52e3b932b">

### Actual Result

Sentry self hosted track data like Sentry cloud. It should look like this 

<img width="1164" alt="image" src="https://github.com/getsentry/self-hosted/assets/33661599/1c8eb41a-d17a-4cfb-ad9e-a8d1a4536892">

**Comment by hubertdeng123** [comment]
Could you check your nginx logs? I'm wondering if your Sentry instance is properly picking up the envelopes that are being sent from the SDK

**Comment by ghun131** [comment]
Thank you for your reply. I fixed it by killing my LightSail instance, then set everything up again. But this time instead of editing `sentry/config.yml` value `sentry.url-prefix: https://example.sentry.com`, I correctly fill up this form

<img width="616" alt="image" src="https://github.com/getsentry/self-hosted/assets/33661599/400c7cc4-f7ba-4a3b-a6a2-7f2a8677beb8">

with the Root Url as my domain name. Now everything works well and I still don't know why it didn't the first time
