### ISSUE TITLE
how to alter SENTRY_URL_PREFIX

### ISSUE THREAD

**Issue by codeLief** [getsentry/self-hosted#2587]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### What are you trying to accomplish?

how to alter  SENTRY_URL_PREFIX after sentry runing.

<img width="408" alt="image" src="https://github.com/getsentry/sentry/assets/10461291/42c79b93-6141-4dd7-b01c-d47487e17b69">

### How are you getting stuck?

When I modify SENTRY_URL_PREFIX

### Where in the product are you?

Settings

**Comment by hubertdeng123** [comment]
You should try to avoid setting the `SENTRY_URL_PREFIX` and use `system.url-prefix` instead. You can set that in your `sentry.conf.py`

**Comment by codeLief** [comment]
Ok, thanks. Where should I configure system.url-prefix in sentry.conf.py? sorry, I may not understand how to configure，please teach me more detail step。

**Comment by kkflie** [comment]
@codeLief sentry.conf.py is in self-hosted/sentry folder. It is automatically generated after executing ./install.sh.After you modified sentry.conf.py, you should execute ```docker compose down && docker compose up -d``` to make the configuration take effect

**Comment by codeLief** [comment]
Ok, thanks,  I know folder of sentry.conf.py, but I not understand how to configure then take effect. like this？
<img width="492" alt="image" src="https://github.com/getsentry/self-hosted/assets/10461291/7963b734-c041-4b70-81f3-f670ad46d672">

**Comment by kkflie** [comment]
@codeLief My bad, if you want to modify url-prefix, you should check self-hosted/sentry/config.yml, if you want to enable ssl, you should check hosted/sentry/sentry.conf.py

url-prefix in config.yml:

<img width="486" alt="image" src="https://github.com/getsentry/self-hosted/assets/40592678/3d331569-1f74-4cfa-8f88-ec112f06b916">

ssl option in setnry.conf.py:

<img width="647" alt="image" src="https://github.com/getsentry/self-hosted/assets/40592678/24f9f2b7-0751-4ccf-9851-71c8104a36ab">

**Comment by codeLief** [comment]
Many thanks, my problem is solve.
