### ISSUE TITLE
sentry queues list doesn't work when Redis has SSL enabled

### ISSUE THREAD

**Issue by lluczaj** [getsentry/self-hosted#2589]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

1. Run self-hosted Sentry on Kubernetes 
2. Enable SSL on redis
3. All Sentry features work properly 
4. Run sentry queues list from sentry-worker pod - this will fail

### Expected Result

Get queues list

### Actual Result

`Error: unknown broker type`

Does Sentry CLI expect to get `rediss` backend ? It seems that queues code hasn't been updated for a long time even though Redis TLS is now officially supported.

https://github.com/getsentry/sentry/blame/master/src/sentry/monitoring/queues.py#L91

### Product Area

Issues

### Version

23.6.2

**Comment by hubertdeng123** [comment]
Hmmm, you're heading into uncharted territory here. The Sentry CLI does not expect the rediss backend, so that's something you'd have to try yourself.

**Comment by lluczaj** [comment]
Since TLS in Redis is officially supported in Sentry don't you have any plans to fix the CLI ? 
I must say I tried to workaround it but apparently I am missing knowledge about Sentry/Celery and struggle with it a lot 🤔

**Comment by azaslavsky** [comment]
We don't support kubernetes-based setups - this repository is built around docker-compose only, and tooling (to some degree) works on that assumption. While there are other unaffiliated open-source projects floating around which provide some sample k8s setups, these are not officially supported by this project. Good luck!

**Comment by lluczaj** [comment]
@azaslavsky I may not know other Sentry setups good enough but to me this problem is not related to Kubernetes itself. 2 questions to you:
- is Redis SSL supported on other Sentry setups that you support
- If so - are you saying that you would be able to list queues with current Sentry CLI version on SSL-enabled Redis?
