### ISSUE TITLE
Can't set Performance Issue Creation Rate

### ISSUE THREAD

**Issue by kanadaj** [getsentry/self-hosted#2590]
### Self-Hosted Version

23.12.0.dev0

### CPU Architecture

x86_64

### Docker Version

20.10.5

### Docker Compose Version

N/A (using K8s)

### Steps to Reproduce

1. Install Sentry
2. Make a project
3. Go to Settings -> Project -> Performance
4. Try setting Performance Issue Creation Rate

### Expected Result

Setting and saving the value

### Actual Result

See error on screenshot:

![image](https://github.com/getsentry/self-hosted/assets/3247357/7e6ae641-1d07-42b3-b479-37e9770701ff)

On that note, isn't dynamic sampling also meant to be there?

**Comment by hubertdeng123** [comment]
Hmmm, that's not the same page I see. What feature flags do you have set?
<img width="1167" alt="Screenshot 2023-11-21 at 2 24 31 PM" src="https://github.com/getsentry/self-hosted/assets/25517925/b834e33b-230e-48c3-9a79-d49f282035c8">
