### ISSUE TITLE
[Backup/Restore] Dsn changed after restore

### ISSUE THREAD

**Issue by cddqssc** [getsentry/self-hosted#2591]
### Self-Hosted Version

23.10.1

### CPU Architecture

x86_64

### Docker Version

Docker version 24.0.7, build afdd53b

### Docker Compose Version

2.6.0

### Steps to Reproduce

1.  ./scripts/backup.sh  -> backup.json
2.  Copy backup.json to a new device and run: ./scripts/restore.sh

The restoration is successful, but the dsn changed from: 
![image](https://github.com/getsentry/self-hosted/assets/31430047/07dd2972-05f4-4ee8-abe9-c937eff8e7b2)
to:
![image](https://github.com/getsentry/self-hosted/assets/31430047/42802c49-490e-4fee-81f9-202f171d64fe)

Yes, only the last number has changed from **_2 to 3_**, but this requires modifying the client code.

### Expected Result

Dsn shoud be the same

### Actual Result

Dsn changed

**Comment by cddqssc** [comment]
Project ID in backup.json is 2:
![image](https://github.com/getsentry/self-hosted/assets/31430047/c91d752f-3346-4e7d-b855-53c5e2684788)

**Comment by hubertdeng123** [comment]
I've successfully replicated this, going to look into it

**Comment by hubertdeng123** [comment]
During my replication, it appears that I did not restore into an empty database. Did you make sure that your database was empty before restoring?

**Comment by hubertdeng123** [comment]
Ah, looks like it is offsetted by 1 due to the internal project

**Comment by cddqssc** [comment]
> During my replication, it appears that I did not restore into an empty database. Did you make sure that your database was empty before restoring?

Thank you for such a prompt response.  Yes, I'm sure that the database is empty before restoring, here are my steps:
1. Stop all containters: **docker compose down -v**
2. Delete all sentry related volumes: **docker volume rm sentry-clickhouse sentry-data sentry-kafka sentry-postgres sentry-redis sentry-symbolicator sentry-zookeeper**
3. Re-install sentry: **./install.sh(do not creating accounts during installation)**
4. Run: ./script/restore.sh

**Comment by azaslavsky** [comment]
Quick update here: @hubertdeng123 is working on a PR to fix this (linked above). Once we land that, this should be resolved, probably in time for the 23.12.0 release in mid-December.
