### ISSUE TITLE
 exit code: 100

### ISSUE THREAD

**Issue by Awxm** [getsentry/self-hosted#2597]
### Problem Statement

 > [sentry-cleanup 5/6] RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*:
1095.1 Unpacking libgcc-s1:amd64 (13.2.0-6) ...
1095.1 Replacing files in old package libgcc1:amd64 (1:8.3.0-6) ...
1095.2 Setting up libgcc-s1:amd64 (13.2.0-6) ...
1095.2 Setting up libc6:amd64 (2.37-12) ...
1095.2 /usr/bin/perl: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory
1095.2 dpkg: error processing package libc6:amd64 (--configure):
1095.2  installed libc6:amd64 package post-installation script subprocess returned error exit status 127
1095.2 Errors were encountered while processing:
1095.2  libc6:amd64
1095.3 E: Sub-process /usr/bin/dpkg returned an error code (1)
------
failed to solve: process "/bin/sh -c apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*" did not complete successfully: exit code: 100
Error in install/build-docker-images.sh:9.
'$dcb --force-rm "$service"' exited with status 17
-> ./install.sh:main:29
--> install/build-docker-images.sh:source:9

error: The subcommand 'send-envelope' wasn't recognized
	Did you mean 'send-event'?

If you believe you received this message in error, try re-running with 'sentry-cli -- send-envelope'

### Solution Brainstorm

How do I fix this

**Comment by Awxm** [comment]
my Docker version 24.0.7, build afdd53b  22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  9 15:34:04 UTC 2

**Comment by hubertdeng123** [comment]
What version of self-hosted are you on? Seems like sentry-cli is not picking up the `send-envelope` command

**Comment by Awxm** [comment]
> What version of self-hosted are you on? Seems like sentry-cli is not picking up the `send-envelope` command

I am using the latest version of docker sentry using the current warehouse install.sh direct installation

**Comment by Awxm** [comment]
I don't know if it's because of network fluctuations.  I use Alibaba's mirror source.

**Comment by azaslavsky** [comment]
Does [this](https://stackoverflow.com/a/38004106) suggestion help?

**Comment by baxibaba** [comment]
failed to solve: process "/bin/sh -c apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*" did not complete successfully: exit code: 100
Error in install/build-docker-images.sh:8.
'$dcb --force-rm "$service"' exited with status 17
-> ./install.sh:main:29
--> install/build-docker-images.sh:source:8

Cleaning up...

**Comment by hubertdeng123** [comment]
@baxibaba that is a different error regarding docker unable to remove a certain service. You'll need to fix that separately. Is there any additional error message there on why the line is exiting?

**Comment by baxibaba** [comment]
> @baxibaba that is a different error regarding docker unable to remove a certain service. You'll need to fix that separately. Is there any additional error message there on why the line is exiting?

Instead, release-23.11.2 will do
