### ISSUE TITLE
"http: invalid Host header" error during installation process.

### ISSUE THREAD

**Issue by robheffo79** [getsentry/self-hosted#2600]
### Self-Hosted Version

23.11.1

### CPU Architecture

x86_64

### Docker Version

20.10.24

### Docker Compose Version

2.17.2

### Steps to Reproduce

1. Download with command "wget https://github.com/getsentry/self-hosted/archive/refs/tags/23.11.2.tar.gz"
2. Untar file with command "tar -zxf ./23.11.1.tar.gz"
3. CD into directory with command "cd self-hosted.23.11.1"
4. Start installation with command "./install.sh"
5. Choose "y" when prompted to share diagnostics data
6. Wait for installation to run
7. At the "Ensuring Relay Credentials" stage, after the message "Network sentry-self-hosted_default Created" message it will fail with the following output.

http: invalid Host header
Error in install/ensure-relay-credentials.sh:29.
'$creds generate --stdout > "$RELAY_CREDENTIALS_JSON".tmp' exited with status 1
-> ./install.sh:main:26
--> install/ensure-relay-credentials.sh:source:29

### Expected Result

The installation to have completed successfully

### Actual Result

![image](https://github.com/getsentry/self-hosted/assets/37826034/221d0c7c-75ad-443d-bcba-74d9ae3b9c1e)

**Comment by azaslavsky** [comment]
Does running the install script a second time produce the same result? This could be a race in the install script.

**Comment by robheffo79** [comment]
I have run it multiple times now, including after updating all my OS packages, and the issue still occurs.

**Comment by hubertdeng123** [comment]
Can you check the logs in relay? Wonder if there's more info there

**Comment by bryanjuho** [comment]
Not sure if you guys figured it out but in my case I found [this comment](https://stackoverflow.com/a/77636675)  in stackoverflow
```
sudo snap refresh docker --channel=latest/edge
```
and it did the job, which I believe updates your docker with latest version from edge channel.

**Comment by hubertdeng123** [comment]
@bryanjuho Thanks for chiming in here. Hopefully this works for someone else
