### ISSUE TITLE
Sentry in k8s using helm chart

### ISSUE THREAD

**Issue by Nithya2505** [getsentry/self-hosted#2607]
### Self-Hosted Version

helm chart version  : sentry-20.11.0 app version: 23.11.0

### CPU Architecture

k8s containers

### Docker Version

running in eks cluster

### Docker Compose Version

no docker compose

### Steps to Reproduce

helm repo add sentry https://sentry-kubernetes.github.io/charts
helm install sentry sentry/sentry
helm install sentry sentry/sentry -f values.yaml
Once the installation is completed . I'm trying to integrate with slack and github and added the client ID and secret for both gihutb and slack . 
So I have added the client id and secrets in configmap . but its not picking the slack client ID and secret.

### Expected Result

integration should be installed

### Actual Result

<img width="817" alt="err-image" src="https://github.com/getsentry/self-hosted/assets/115529019/0f75c9fa-5a4c-44fc-b981-3a11990b46e5">

**Comment by azaslavsky** [comment]
We only offer support for docker-compose-based setups. There are other, unaffiliated projects with demo k8s setups - it may be worthwhile to ask there instead.
