### ISSUE TITLE
New Project, DSN Empty

### ISSUE THREAD

**Issue by zystudios** [getsentry/self-hosted#2621]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

![image](https://github.com/getsentry/sentry/assets/29728228/a8f8b299-7ab2-4953-b815-4e017d2ad1ef)

![image](https://github.com/getsentry/sentry/assets/29728228/01cfed8d-0703-48a8-92a9-4c1ba5231f05)

I deployed sentry on my own intranet, I create a new project and the dsn is empty no matter what type of project it is, I don't know how to fix it, thanks!

version Sentry 23.8.0.dev0 f866963

### Expected Result

DSN not empty

### Actual Result

DSN empty

### Product Area

Settings - Projects

**Comment by aldy505** [comment]
You'd need to uncomment this and fill it with your base URL.

https://github.com/getsentry/self-hosted/blob/76ab9a596e7dc32c468f387dd45ba637e8cfad53/sentry/config.example.yml#L82

**Comment by hubertdeng123** [comment]
Technically, `system.url-prefix` should be set on the initialization of a Sentry instance on the setup page, but if not you'll need to do what @aldy505 has mentioned. Does this error happen for every project you create?

**Comment by zystudios** [comment]
Thanks for the replies, it's true that   `system.url-prefix` is empty

Here's how I solved it

1 Go to <sentry_url>/manage/settings/

2 Change the Root Url, I have set it before, change it to a different one and change it back.

**Comment by zystudios** [comment]
I have a suggestion, if the system detects that the  `system.url-prefix`  is empty, it should give a hint instead of letting the DSN display empty

This is very important, and many people will not know what's going on
