### ISSUE TITLE
Need help figuring out what a large table prefixed `log_` is for

### ISSUE THREAD

**Issue by hariprasadiit** [getsentry/self-hosted#2623]
### Self-Hosted Version

23.10.1

### CPU Architecture

x86_64

### Docker Version

20.10.23

### Docker Compose Version

2.15.1

### Steps to Reproduce

Not sure how I can re-produce this

### Expected Result

no log table in database?

### Actual Result

I see one table with `log_` prefix which is bigger than nodestore.

```
                   table_name                   | Total Size | Index Size | Actual Size
------------------------------------------------+------------+------------+-------------
 log_20247                                      | 137 GB     | 589 MB     | 1925 MB
 nodestore_node                                 | 82 GB      | 1190 MB    | 790 MB
 sentry_eventattachment                         | 159 MB     | 125 MB     | 34 MB
```

Any help is appreciated in understanding what this is and is it safe to delete it?

**Comment by hubertdeng123** [comment]
We don't seem to have this table in our db, so I'm not exactly sure what that is for.

**Comment by hariprasadiit** [comment]
@hubertdeng123 thanks for the confirmation. After fiddling around with it I found that it was a table created `pg_repack` and the table was not cleaned up due to an interruption. After dropping the repack schema the table got deleted.
