### ISSUE TITLE
I don't want to config SMTP server, how can I create more member account?

### ISSUE THREAD

**Issue by 1s1y** [getsentry/self-hosted#2624]
### Self-Hosted Version

23.12.0.dev0

### CPU Architecture

x86_64

### Docker Version

24.0.7

### Docker Compose Version

v2.21.0

### Steps to Reproduce

1. I don't config SMTP server in my self-hosted sentry env.
2. User register is disabled.
3. I can't add more member account by invitation cause invalid SMTP.

### Expected Result

Can I create user account directly?

### Actual Result

...

**Comment by hubertdeng123** [comment]
You can create a user directly, and it's done through `sentry createuser` CLI command
