### ISSUE TITLE
Fresh Install Error - '$dcr web upgrade' exited with status 1

### ISSUE THREAD

**Issue by jeanlst** [getsentry/self-hosted#2642]
### Self-Hosted Version

23.11.2

### CPU Architecture

x84_64

### Docker Version

24.0.7

### Docker Compose Version

2.21.0

### Steps to Reproduce

  Get a fresh server with Ubuntu 22.04
  execute docker system prune -a to make sure there are no old containers and volumes
  clone this repo
  execute ./install.sh

### Expected Result

everything works fine

### Actual Result

 Container sentry-self-hosted-snuba-consumer-1  Started
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/opt/sentry/postgres-entrypoint.sh": permission denied: unknown
Error in install/set-up-and-migrate-database.sh:12.
'$dcr web upgrade' exited with status 1
-> ./install.sh:main:34
--> install/set-up-and-migrate-database.sh:source:12

Cleaning up...

**Comment by Chetan-Goyal** [comment]
I am also facing this issue in Mac M1 arm64 arch.

**Comment by azaslavsky** [comment]
Two previous issues, both of which were related to permissions and unexpected machine state:
https://github.com/getsentry/self-hosted/issues/1658
https://github.com/getsentry/self-hosted/issues/1794

Can you try the approaches recommended here and report back?
