### ISSUE TITLE
Migration time on 23.6.2

### ISSUE THREAD

**Issue by hiering** [getsentry/self-hosted#2645]
### Self-Hosted Version

23.2.0

### CPU Architecture

x86_64

### Docker Version

24.0.5

### Docker Compose Version

v2.20.2

### Steps to Reproduce

`sentry upgrade`

### Expected Result

Migration time is less than 1 hour.

### Actual Result

We upgraded Sentry from 23.2.0 to 23.6.2 and `sentry upgrade` took over 6 hours with a database size of 200GB. We would like to know if it is possible to reduce the downtime during the migration. Maybe there are options to increase the number of threads or something else?

**Comment by azaslavsky** [comment]
That is a very large database. Generally migrations like this are single threaded, and kind of have to lock up the whole database in the worst case. The downtime isn't great, but I'm not sure what exactly we could do to improve this.
