### ISSUE TITLE
Support new Beta User Feedback feature in self-hosted

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/self-hosted#2646]
New User Feedback workflow and JS widget to capture feedback outside of runtime errors (event_id link).

This will allow us have the feature on the Sandbox. And single tenant.

Feature flags:

```
"organizations:user-feedback-ui",
"organizations:user-feedback-ingest",
"organizations:issue-platform",
"organizations:feedback-ingest",
"organizations:feedback-post-process-group",
"organizations:feedback-visible",
```

## Documentation

Product: https://docs.sentry.io/product/user-feedback/
SDK: https://docs.sentry.io/platforms/javascript/user-feedback/

**Comment by aldy505** [comment]
Mandatory question: Do we need additional Sentry worker or Snuba consumer containers?

**Comment by hubertdeng123** [comment]
@bruno-garcia do you know the answer to this? I peeked into `sentry` and it doesn't look like any additional infra should be required but not entirely sure

**Comment by SebastiaanKloos** [comment]
I found nothing more than a feature flag that should be enabled. Weird thing is that it did not ingest any feedbacks.

**Comment by holtgrewe** [comment]
I can confirm, that after adding the feature flags, I can see the UI but nothing is ingested.

**Comment by JoshFerge** [comment]
Hello, please also add these features:

```
"organizations:issue-platform",
"organizations:feedback-ingest",
"organizations:feedback-post-process-group",
"organizations:feedback-visible",
```

let me know if this does not work!

**Comment by SebastiaanKloos** [comment]
> Hello, please also add these features:
> 
> ```
> "organizations:issue-platform",
> "organizations:feedback-ingest",
> "organizations:feedback-post-process-group",
> "organizations:feedback-visible",
> ```
> 
> let me know if this does not work!

Thank you so much. This fixed it. Woohoo!

![CleanShot 2024-01-02 at 23 14 38](https://github.com/getsentry/self-hosted/assets/6506510/e24bf201-cc6b-4886-b42d-89523c777ae6)

**Comment by schettn** [comment]
Anyone getting this after adding the features flags?

![image](https://github.com/getsentry/self-hosted/assets/52858351/c3de7b37-cd36-4f11-b29f-ea50ff0af56c)

**Comment by mlch911** [comment]
With the addition of these 6 flags, I can now see the user feedback tab, but it can't receive any data. The user feedback tab on the details page of a single issue also has no data.
I'm using sentry 24.1.0 right now.

**Comment by aldy505** [comment]
@mlch911 Hi, have you re-run `./install.sh` script yet?

**Comment by mlch911** [comment]
> @mlch911 Hi, have you re-run `./install.sh` script yet?
> 
> Also please make sure that every of the feature flag defined here already exists on your config, you might do a diff check for this:
> 
> https://github.com/getsentry/self-hosted/blob/5199bb07f927ca0a4f9330fedec857d1ac0fe811/sentry/sentry.conf.example.py#L265-L292

Are all these flags required?
![](https://s2.loli.net/2024/04/12/cqwl2KdVB1xIkir.png)

**Comment by mlch911** [comment]
> @mlch911 Hi, have you re-run `./install.sh` script yet?
> 
> Also please make sure that every of the feature flag defined here already exists on your config, you might do a diff check for this:
> 
> https://github.com/getsentry/self-hosted/blob/5199bb07f927ca0a4f9330fedec857d1ac0fe811/sentry/sentry.conf.example.py#L265-L292

Do we need to re run `./install.sh` after changing the config file?

**Comment by aldy505** [comment]
> > @mlch911 Hi, have you re-run `./install.sh` script yet?
> 
> > 
> 
> > Also please make sure that every of the feature flag defined here already exists on your config, you might do a diff check for this:
> 
> > 
> 
> > https://github.com/getsentry/self-hosted/blob/5199bb07f927ca0a4f9330fedec857d1ac0fe811/sentry/sentry.conf.example.py#L265-L292
> 
> 
> 
> Do we need to re run `./install.sh` after changing the config file?

Sometimes, when new flags are added, there are database migrations (both Postgres and Clickhouse) that has to be run that depends on a certain feature flags. 

Also it's recommended to have up-to-date feature flags as shown on the repository.

**Comment by aldy505** [comment]
From @drguthals

> User Feedback is officially here.  
> 
> Get direct feedback from users when they encounter a bug on your site. We’ll attach their comment with all the debugging context you could dream of, like replay events, error details, URL tags, and more.  
> 
> User Feedback makes debugging easier and faster, AND helps you identify trends across your entire user base so that you can prioritize the issues causing the most friction.
> 
> To get all the details on User Feedback, check out our latest blog post:
> https://bit.ly/sentry-user-feedback

https://discord.com/channels/621778831602221064/621786584110596119/1238164781311987763

So... it's GA already now?

**Comment by bruno-garcia** [comment]
It is GA, so it should be available on Self Hosted too

**Comment by michaelmairegger** [comment]
@bruno-garcia What are the features that have to be enabled in order to make it work?
I have this as baseline: https://github.com/getsentry/self-hosted/blob/24.6.0/sentry/sentry.conf.example.py

**Comment by aldy505** [comment]
Current known issue about user feedback feature (I just encountered this a few moments ago) https://github.com/getsentry/sentry/issues/67412
