### ISSUE TITLE
Using a mounted folder as a filestore

### ISSUE THREAD

**Issue by Aulig** [getsentry/self-hosted#2647]
### Self-Hosted Version

23.11.2

### CPU Architecture

x86_64

### Docker Version

24.0.5

### Docker Compose Version

1.29.2

### Steps to Reproduce

Since my sentry instance keeps getting bigger and bigger, I'm trying to make it store most data on an external disk, where I can more easily increase the storage space. I found the filestore documentation, which seems to be what I need to use here: https://develop.sentry.dev/services/filestore/

I have mounted my new disk at /mnt/sentry-filestore and then configured the filestore like this in config.yml:
```
filestore.backend: 'filesystem'
filestore.options:
  location: '/mnt/sentry-filestore/files'
dsym.cache-path: '/mnt/sentry-filestore/dsym-cache'
releasefile.cache-path: '/mnt/sentry-filestore/releasefile-cache'
```

To test, I'm uploading an avatar in the sentry settings, since I read that that gets stored on filestore. When doing that, I get this error in the logs:
```
web_1 | Traceback (most recent call last):
web_1 |   File "/usr/local/lib/python3.8/site-packages/sentry/api/base.py", line 231, in handle_exception
web_1 |     response = super().handle_exception(exc)
web_1 |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
web_1 |     self.raise_uncaught_exception(exc)
web_1 |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
web_1 |     raise exc
web_1 |   File "/usr/local/lib/python3.8/site-packages/sentry/api/base.py", line 355, in dispatch
web_1 |     response = handler(request, *args, **kwargs)
web_1 |   File "/usr/local/lib/python3.8/site-packages/sentry/api/bases/avatar.py", line 81, in put
web_1 |     self.save_avatar(obj, serializer)
web_1 |   File "/usr/local/lib/python3.8/site-packages/sentry/api/bases/avatar.py", line 69, in save_avatar
web_1 |     return self.model.save_avatar(
web_1 |   File "/usr/local/lib/python3.8/site-packages/sentry/models/avatars/base.py", line 168, in save_avatar
web_1 |     photo.putfile(avatar)
web_1 |   File "/usr/local/lib/python3.8/site-packages/sentry/../sentry_sdk/tracing_utils_py3.py", line 70, in func_with_tracing
web_1 |     return func(*args, **kwargs)
web_1 |   File "/usr/local/lib/python3.8/site-packages/sentry/models/files/abstractfile.py", line 295, in putfile
web_1 |     blob = self.FILE_BLOB_MODEL.from_file(blob_fileobj, logger=logger)
web_1 |   File "/usr/local/lib/python3.8/site-packages/sentry/models/files/abstractfileblob.py", line 204, in from_file
web_1 |     storage.save(blob.path, fileobj)
web_1 |   File "/usr/local/lib/python3.8/site-packages/django/core/files/storage.py", line 54, in save
web_1 |     name = self._save(name, content)
web_1 |   File "/usr/local/lib/python3.8/site-packages/django/core/files/storage.py", line 260, in _save
web_1 |     os.makedirs(directory, exist_ok=True)
web_1 |   File "/usr/local/lib/python3.8/os.py", line 213, in makedirs
web_1 |     makedirs(head, exist_ok=exist_ok)
web_1 |   File "/usr/local/lib/python3.8/os.py", line 213, in makedirs
web_1 |     makedirs(head, exist_ok=exist_ok)
web_1 |   File "/usr/local/lib/python3.8/os.py", line 213, in makedirs
web_1 |     makedirs(head, exist_ok=exist_ok)
web_1 |   File "/usr/local/lib/python3.8/os.py", line 223, in makedirs
web_1 |     mkdir(name, mode)
web_1 | PermissionError: [Errno 13] Permission denied: '/mnt/sentry-filestore'
web_1 | 09:56:21 [INFO] sentry.access.api: api.access (method='PUT' view='sentry.api.endpoints.avatar.organization.OrganizationAvatarEndpoint' response=500 user_id='1' is_app='False' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/organizations/sentry/avatar/' caller_ip='91.66.144.18' user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.16799449920654297 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
```

To avoid permission issues, I've set them to 777:
`ls -ld /mnt/sentry-filestore/`

`drwxrwxrwx 4 aulig aulig 4096 Dec 13 09:28 /mnt/sentry-filestore/`

But that didn't resolve the error unfortunately. I then read that I might need to bind the mounted folder, so I edited the docker-compose file like this:

```
  web:
    <<: *sentry_defaults
    [...]
    volumes:
      - type: bind
        source: /mnt/sentry-filestore
        target: /mnt/sentry-filestore
```

But then I get a different error, where I don't quite understand how it is related:
```
ERROR: for web  Cannot start service web: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/etc/sentry/entrypoint.sh": stat /etc/sentry/entrypoint.sh: no such file or directory: unknown
ERROR: Encountered errors while bringing up the project.
```
Most likely I'm misunderstanding how the bind works.

Apart from not being able to get it to work, I'm also wondering which containers all use the filestore and I would therefore have to add the bind to.

Or is there a different approach altogether that I should use?

### Expected Result

I'm hoping to get no error and the files get saved on my mounted external disk.

### Actual Result

I get various errors as described in the steps to reproduce.

Thank you in advance for your help!

**Comment by azaslavsky** [comment]
Would it be possible to symlink your external filestore where the default web volume lives (sentry-data)? This is pretty off the beaten path, but my general recommendation would be to avoid changing the internal config, and instead to do this at the docker and OS level, finding a way to point your docker container at the correct directory using the filesystem.

**Comment by Aulig** [comment]
> Would it be possible to symlink your external filestore where the default web volume lives (sentry-data)? This is pretty off the beaten path, but my general recommendation would be to avoid changing the internal config, and instead to do this at the docker and OS level, finding a way to point your docker container at the correct directory using the filesystem.

That's genius, thank you so much for that suggestion! I'll keep an eye on it, but it seems to be working fine :)
