### ISSUE TITLE
In which tables are issues information stored, i cant seem to find any data

### ISSUE THREAD

**Issue by NotJordi** [getsentry/self-hosted#2655]
### Self-Hosted Version

23.11.2

### CPU Architecture

x86_64

### Docker Version

24.0.7

### Docker Compose Version

2.23.3

### Steps to Reproduce

Basically as the title say, i cant seem to find any table that contains information about issues, i have check almost every table but no result. I was able to find information about saved and registered users but thats all. Ofc when i run sentry locally and open it, there are issues saved and showed in the dashboard. 

Im asking here since sentry sentry forum seems to be in read mode only.

### Expected Result

...

### Actual Result

...

### Event ID

.

**Comment by azaslavsky** [comment]
While this concept is referred to as "Issues" in our frontend copy, it is (confusingly) called "Groups" in most of our backend codebase. So the relevant model/table can be found [here](https://github.com/getsentry/sentry/blob/6d135c1c9440bf6f16fde8963b614a47d023b08a/src/sentry/models/group.py#L550).
