### ISSUE TITLE
Reduce container count in self-hosted

### ISSUE THREAD

**Issue by OldBucFan** [getsentry/self-hosted#2658]
### Problem Statement

Our upgrade from 22.8.0 to 23.11.1 effectively doubled the number of containers running, requiring an increased memory allocation and thus higher cost of ownership.

### Solution Brainstorm

Could Snuba and Sentry jobs be consolidated to run on a few containers vs. dedicated per job.

**Comment by rhuddleston** [comment]
Possibly an option so the snuba consumer or sentry consumer jobs can be optionally combined and consume multiple events in a single container?

**Comment by azaslavsky** [comment]
We have some long term plans to do this, but it's not on the docket until at least February of next year. I'll keep this issue open for now.

**Comment by aldy505** [comment]
This is a duplicate of https://github.com/getsentry/self-hosted/issues/2539 and https://github.com/getsentry/self-hosted/issues/1763

**Comment by azaslavsky** [comment]
Good point - will roll this issue into those and mark as a dupe.

**Comment by rhuddleston** [comment]
snuba issue: https://github.com/getsentry/snuba/issues/1670
