### ISSUE TITLE
 topic: ingest-sessions LAG increase permanently.

### ISSUE THREAD

**Issue by piellick** [getsentry/self-hosted#2659]
### Self-Hosted Version

23.11.2

### CPU Architecture

x86_64

### Docker Version

24.0.4

### Docker Compose Version

2.20.2

### Steps to Reproduce

Hello everyone, since we update to version `23.11.2` we have this kafka topic that grow. For now we can not make the link with a possible root cause all features seem to work.

check kafka metrics **snuba-consumers group** topic: **ingest-sessions**

![image](https://github.com/getsentry/self-hosted/assets/18485789/76f44d8e-6b45-48ef-823c-ee904974f82c)

### Expected Result

ingest-session lag sould decrease and event should be consumes.

### Actual Result

 topic: **ingest-sessions** continue to increase.
 ```

 docker compose run --rm kafka kafka-consumer-groups --bootstrap-server kafka:9092 --group snuba-consumers --describe
[+] Creating 1/0
 ✔ Container sentry-self-hosted-zookeeper-1  Running                                                                                                                                                                                     0.0s 

GROUP           TOPIC                PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                  HOST            CLIENT-ID
snuba-consumers ingest-replay-events 0          249592          249592          0               rdkafka-e52f61a0-d155-410d-88b6-5c05b1bb769a /100.64.2.34    rdkafka
snuba-consumers profiles-call-tree   0          -               0               -               rdkafka-9b050aa5-1782-4665-8308-503dbd574d1b /100.64.2.30    rdkafka
snuba-consumers processed-profiles   0          -               0               -               rdkafka-170f1ccf-7268-4374-a4c2-74afcd2247db /100.64.2.29    rdkafka
snuba-consumers outcomes             0          20706235        20706237        2               rdkafka-aeb36c21-934d-4474-b001-3a3fb11815d0 /100.64.2.17    rdkafka
snuba-consumers events               0          11867802        11867803        1               rdkafka-490d213d-c04b-4bd7-a0a3-f44cc4b49094 /100.64.2.14    rdkafka
snuba-consumers ingest-sessions      0          9922868         10083926        161058          -                                            -               -

```

**Comment by piellick** [comment]
hello again,
could be related to this deprecated feature ? 
https://github.com/getsentry/self-hosted/issues/2200

thanks a lot.

**Comment by hubertdeng123** [comment]
We removed all sessions infrastructure from self-hosted. Are you still running any of it? Otherwise, you should be fine to delete that topic.

**Comment by piellick** [comment]
hey @hubertdeng123 thanks for your help :pray: 

How check if sessions are still active ? 
what is the cleanest way to remove all references to sessions?

Thanks and good holidays :partying_face:

**Comment by hubertdeng123** [comment]
@piellick Happy holidays to you too!

You can do this by removing the kafka topic `ingest-sessions`. You should also remove any reference to `sessions` in your docker compose yaml file. If you're on 23.11.2, sessions should be removed completely already.

**Comment by azaslavsky** [comment]
I think `snuba-commit-log` should stick around, but @hubertdeng123 do you know more?

**Comment by hubertdeng123** [comment]
Yep, I think `snuba-commit-log` should stay.

**Comment by piellick** [comment]
thanks team .. but but isn’t it strange that it’s full?
![image](https://github.com/getsentry/self-hosted/assets/18485789/80674962-a7b9-45df-a3eb-dfdfa7c5c994)

**Comment by piellick** [comment]
Hi @azaslavsky , logs on `entry-self-hosted-subscription-consumer-events-1` are rather empty. Nothing since 3days (and more).

docker logs sentry-self-hosted-subscription-consumer-events-1 --since 4320m. We will perform a CT stop/start soon and i'll keep you inform.

**Comment by piellick** [comment]
Hi @azaslavsky, we did a restart of` subscription-consumer-events` ct and topic is still full.

**Comment by hubertdeng123** [comment]
What is your load on your Sentry instance. Unless something is abnormal about your setup, I'm not sure if the topic having a lot of events is a problem.

**Comment by piellick** [comment]
hi @hubertdeng123 , load is qiute low. 
![image](https://github.com/getsentry/self-hosted/assets/18485789/2696c723-daa9-4121-a713-bab231361d2f)

After a second restart, topic is emptied completely :shamrock: and we don't know why. Thanks

**Comment by hubertdeng123** [comment]
Glad the topic was able to be emptied. Is your problem solved? @piellick
