### ISSUE TITLE
Sentry binarie permissions list return empty info

### ISSUE THREAD

**Issue by piellick** [getsentry/self-hosted#2663]
### Self-Hosted Version

23.11.2

### CPU Architecture

x86_64

### Docker Version

24.0.4

### Docker Compose Version

2.20.2

### Steps to Reproduce

```
sentry permissions list --user user1@xxxxxxx.com
/usr/local/lib/python3.8/site-packages/memcache.py:1303: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key is '':
/usr/local/lib/python3.8/site-packages/memcache.py:1304: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key_extra_len is 0:
Permissions for `user1@xxxxxxx.com`:
```

### Expected Result

list all permissions for this user

### Actual Result

empty, we tried with many existing accounts.

**Comment by hubertdeng123** [comment]
Interesting, it looks like `sentry_userpermission` is no longer in use. Do you get the expected information when looking at the `auth_user` table in your db?

**Comment by piellick** [comment]
hello @hubertdeng123 i check and i come back to you.
