### ISSUE TITLE
Setup with AWS SES not working

### ISSUE THREAD

**Issue by duyleduc** [getsentry/self-hosted#2668]
### Self-Hosted Version

24.10

### CPU Architecture

x86_64

### Docker Version

24.0.2

### Docker Compose Version

1.28.6

### Steps to Reproduce

my sentry/config.yml contains these aws connection info:
mail.backend: 'smtp'  # Use dummy if you want to disable email entirely

mail.host: 'email-smtp.aws...'  

mail.port: 587 

mail.username: 'AKIA' 

mail.password: 'L0dS_super_secret_aws_key' 

mail.use-tls: false 

mail.use-ssl: false 
 

### Expected Result

Email sent

### Actual Result

sentry-self-hosted-worker-1                                        | 09:28:27 [ERROR] celery.app.trace: Task sentry.tasks.email.send_email[27586b08-1bf7-4037-b357-ddc4ac2d924d] raised unexpected: TimeoutError('timed out') (data={'hostname': 'celery@13e858dcddb6', 'id': '27586b08-1bf7-4037-b357-ddc4ac2d924d', 'name': 'sentry.tasks.email.send_email', 'exc': "TimeoutError('timed out')", 'traceback': 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task\n    R = retval = fun(*args, **kwargs)\n  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/celery.py", line 306, in _inner\n    reraise(*exc_info)\n  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/_compat.py", line 115, in reraise\n    raise value\n  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/celery.py", line 301, in _inner\n    return f(*args, **kwargs)\n  File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 760, in __protected_call__\n    return self.run(*args, **kwargs)\n  File "/usr/local/lib/python3.10/site-packages/sentry/silo/base.py", line 156, in override\n    return original_method(*args, **kwargs)\n  File "/usr/local/lib/python3.10/site-packages/sentry/tasks/base.py", line 117, in _wrapped\n    result = func(*args, **kwargs)\n  File "/usr/local/lib/python3.10/site-packages/sentry/tasks/email.py", line 64, in send_email\n    send_messages([message])\n  File "/usr/local/lib/python3.10/site-packages/sentry/utils/email/send.py", line 17, in send_messages\n    sent = connection.send_messages(messages)\n  File "/usr/local/lib/python3.10/site-packages/django/core/mail/backends/smtp.py", line 102, in send_messages\n    new_conn_created = self.open()\n  File "/usr/local/lib/python3.10/site-packages/django/core/mail/backends/smtp.py", line 62, in open\n    self.connection = self.connection_class(self.host, self.port, **connection_params)\n  File "/usr/local/lib/python3.10/smtplib.py", line 255, in __init__\n    (code, msg) = self.connect(host, port)\n  File "/usr/local/lib/python3.10/smtplib.py", line 341, in connect\n    self.sock = self._get_socket(host, port, self.timeout)\n  File "/usr/local/lib/python3.10/smtplib.py", line 312, in _get_socket\n    return socket.create_connection((host, port), timeout,\n  File "/usr/local/lib/python3.10/socket.py", line 845, in create_connection\n    raise err\n  File "/usr/local/lib/python3.10/socket.py", line 833, in create_connection\n    sock.connect(sa)\nTimeoutError: timed out\n', 'args': '()', 'kwargs': "{'message': <django.core.mail.message.EmailMultiAlternatives object at 0x7f1f71156f50>, '__start_time': 1703237227.004494}", 'description': 'raised unexpected', 'internal': False})

**Comment by aldy505** [comment]
You got a timeout error from `...name': 'sentry.tasks.email.send_email', 'exc': "TimeoutError('timed out')", 'traceback': 'Trace...`.

A few questions that might be the issue because AWS is so complicated:
1. Have you configured your SES instance to accept SMTP emails? See https://docs.aws.amazon.com/ses/latest/dg/send-using-smtp-programmatically.html
2. Do you use some kind of specific firewall routing in which the SES is only accessible from a certain EC2 or similar? Have you opened that firewall rule?
3. If everything seems right, I can only offer you to install Postfix on the same host as your Sentry instance, send the email from sentry configuration to the Postfix, then let the Postfix relay the SMTP request to AWS (I've done this on my company). See https://bobcares.com/blog/configure-postfix-as-a-relay-server/

**Comment by duyleduc** [comment]
Hi,

Thank you @aldy505  for your response, finally I made it working by modifying the file sentry/sentry.conf.py and adding the aws ses information.
