### ISSUE TITLE
Restoring backup on fresh install creates extra "sentry" org, increments existing DSN IDs

### ISSUE THREAD

**Issue by csvan** [getsentry/self-hosted#2669]
### Self-Hosted Version

23.12.0

### CPU Architecture

x86_64

### Docker Version

24.0.5

### Docker Compose Version

2.23.3

### Steps to Reproduce

1. Install Sentry self-hosted as per documentation on one host
2. Create a project in GUI
3. Run `scripts/backup.sh` to create backup file
4. Install exact same version of Sentry on another (identical) host
5. Copy `backup.json` file to `sentry` folder on new host
6. Run `scripts/restore.sh`
7. Start new Sentry instance

### Expected Result

The new Sentry instance should be identical to the one which the backup was created from (same organisations, users, projects, DSNs)

### Actual Result

While the new Sentry instance works fine, we observe that:
1. A new organisation called "sentry" has been added, in addition to the existing one. It usually has a slug called "sentry-7v" or the like. Seems like Sentry is creating a copy of the default organisation even though it already exists in the backup.
2. All project DSNs have been incremented by one - so e.g. 

```
https://xxxxx@sentry.domain.com/8
```
has become
```
https://xxxxx@sentry.domain.com/9
```

which breaks processing of events. Guessing this is related to the extra organisation above parking the first project id, causing all additional ones to be incremented.

**Comment by hubertdeng123** [comment]
Interesting, I was unable to reproduce this on the nightly build. Thought this would've been resolved by https://github.com/getsentry/sentry/pull/60484, but perhaps not.

Few things that will be helpful to debug this:
1. Does your `backup.json` file have an internal project?
2. Say your `backup.json` has  `n` projects. Are they numbered 1-n? Reason I ask, is that even if a project is deleted, we end up saving the project to the file in a state where a Sentry instance understands that the project has been deleted.

**Comment by hubertdeng123** [comment]
And just to confirm, you are sure you are using 23.12.0? What is in your `.env` file for `SENTRY_IMAGE`?

**Comment by csvan** [comment]
Hi @hubertdeng123, happy new year!

I do have an internal org as well, relevant part of the `backup.json`:

```
  {
    "model": "sentry.organization",
    "pk": 1,
    "fields": {
      "name": "Sentry",
      "slug": "sentry",
      "status": 0,
      "date_added": "2023-12-21T13:19:09.738Z",
      "default_role": "member",
      "is_test": false,
      "flags": "1"
    }
  },
  {
    "model": "sentry.organization",
    "pk": 2,
    "fields": {
      "name": "vgcs",
      "slug": "vgcs",
      "status": 0,
      "date_added": "2023-12-15T12:34:27.854Z",
      "default_role": "member",
      "is_test": false,
      "flags": "1"
    }
  },
  ```
  
  Turns out I was on 23.11.2, my bad. I will upgrade, but isn't the patch you linked included in this version?

**Comment by csvan** [comment]
Incidentally, I noticed while posting this that the `date_added` timestamps for the custom and default orgs are different (default should come before custom I suppose).

I believe this is because we at some point simply _renamed_ the default org to `vgcs` and used it as a custom one. After restoring that backup, Sentry then creates a new one - but it keeps on adding a new one on top of that if we restore a backup including that one etc.

**Comment by hubertdeng123** [comment]
> Turns out I was on 23.11.2, my bad. I will upgrade, but isn't the patch you linked included in this version?

Looks like 23.11.2 was released on Nov 27. The fix above was merged in on Nov 29, so it wouldn't have been picked up. Let me know if the problem is still occurring on a new version.

**Comment by csvan** [comment]
updating to latest Sentry indeed solves the issue, thanks and sorry for the miss
