### ISSUE TITLE
Running migrations manually

### ISSUE THREAD

**Issue by aminvakil** [getsentry/self-hosted#2674]
### Self-Hosted Version

23.8.0

### CPU Architecture

x86_84

### Docker Version

24.0.7

### Docker Compose Version

2.21.0

### Steps to Reproduce

I've accidentally dropped a table (nodestore_node), how can I run migrations manually, I've tried `docker compose down -v --remove-orphans && ./install.sh && docker compose up -d` and `docker compose run web upgrade`, but neither worked.

Is there a way to run migrations manually, so the table gets created?

### Expected Result

Run migrations manually

### Actual Result

Do not know how to run migrations manually

**Comment by hubertdeng123** [comment]
Can you try `sentry django migrate` with the nodestore migration to recreate the table?

**Comment by aminvakil** [comment]
I had created a clean sentry then, copied the schema and created table manually in our server.

But I will test this command on a clean self-hosted after dropping `nodestore_node` table and report back.

**Comment by aminvakil** [comment]
`docker compose run --rm web django migrate` resulted in:
```
Operations to perform:
  Apply all migrations: auth, contenttypes, nodestore, replays, sentry, sessions, sites, social_auth
Running migrations:
  No migrations to apply.
```

I guess as django migrations create a table in postgres itself marking whether a migration has been done or not, and it sees that all migrations have been done as that row is present there, it would not migrate again.

It crossed my mind to remove that row manually, and run `./install.sh` (I was not aware of `sentry django migrate` command that time) again, but it would maybe cause more problems, if there were other migrations which depend on the removed migration and so on.

Therefore I created a clean self-hosted from that exact version, get table schema and indexes, and created it again manually on our original self-hosted.

That being said, I think this issue can be closed and `docker compose run --rm web django migrate` is the answer to running migrations manually.
