### ISSUE TITLE
Cant deploy AWS Lambda Intergration. 

### ISSUE THREAD

**Issue by oscalmonarc** [getsentry/self-hosted#2675]
### Self-Hosted Version

24.1.0.dev0

### CPU Architecture

x86_64

### Docker Version

Docker version 24.0.7, build afdd53b

### Docker Compose Version

docker-compose version 1.18.0, build 8dd22a9

### Steps to Reproduce

When I click go to AWS for adding the aws intergration, I get an error. 
![sentry-1](https://github.com/getsentry/self-hosted/assets/7134252/03554539-e32b-4b7e-ac1f-da3911d82c32)

I get an error saying: URL query parameter templateURL is required.
![sentry2](https://github.com/getsentry/self-hosted/assets/7134252/f6c6e132-afab-41b0-959a-c291a1af5f2a)

### Expected Result

it should load the template and allow me to deploy it but it doesnt. 

### Actual Result

URL query parameter templateURL is required.

**Comment by azaslavsky** [comment]
Have you tried the instructions [here](https://github.com/getsentry/self-hosted/issues/1389#issuecomment-1072671738)? It seems like some manual work is required to get this integration to work on self-hosted.
