### ISSUE TITLE
Issues when restoring Sentry

### ISSUE THREAD

**Issue by brunococinoJC** [getsentry/self-hosted#2683]
### Self-Hosted Version

9.1.2

### CPU Architecture

x86_64

### Docker Version

20.10.25

### Docker Compose Version

1.25.0

### Steps to Reproduce

I'm unclear about the procedure to restore the Sentry installation

We want to upgrade to latest sentry version, so I was testing the restore.
I understand we need to backup and restore the main docker volumes,
let's say I want to create a new 9.1.2 install to test the migration, what should the steps look like?

first do a ./install.sh, then migrate data to the volumes? 
create the volumes manually beforehand and populate them?
Should I go to a new version?

The commands below are the ones I used to try and do this
```
docker run --rm --volumes-from sentry_postgres_1 -v $(pwd):/backup ubuntu tar cvf /backup/postgre-backup.tar /var/lib/postgresql/data
docker run --rm --volumes-from self-hosted_postgres_1 -v $(pwd):/backup ubuntu bash -c "cd /var/lib/postgresql/data && tar xvf /backup/postgre-backup.tar --strip 1"
```

This didn't work, causing my deploy to break, and if I try to ./install.sh after doing this, it has issues recongnizing redis/postgre hostname

### Expected Result

new install with previous data

### Actual Result

can put logs when I get the steps clear

**Comment by hubertdeng123** [comment]
You're using a pretty old version of self-hosted Sentry at this point. I'm not super familiar with what the restore process was back then, but it has since been improved drastically in the most recent versions. If you plan on migrating instances, I'd recommend you restore the docker volumes before running `./install.sh`.

See here for more details: https://develop.sentry.dev/self-hosted/backup/

**Comment by brunococinoJC** [comment]
Hey!
Our main goal is to upgrade the sentry version, was just scared to lose the data using the same volumes as the current install

I checked out that page, that's where I got the commands for restoring the volumes (making a tar of the data then decompressing that inside a new volume) but that caused issues when trying to do `./install.sh` on the same version afterwards

**Comment by hubertdeng123** [comment]
I'm not super familiar with 9.1.2 since it's super old at this point and we don't have much documentation around an upgrade process there, so I may be of limited help. What errors are you getting after trying to run `./install.sh`?

If docker volume backups are giving you trouble, it may be helpful to use `pg_dump` instead.

**Comment by brunococinoJC** [comment]
Just figured it would be easier to do a partial restore using the backup.json file, I don't mind historical data.

I did `docker-compose run -v $(pwd)/sentry:/sentry-data/backup  --rm -T -e SENTRY_LOG_LEVEL=CRITICAL sentry export /sentry-data/backup/backup.json`

Which worked, then I did a fresh install of 9.1.2 and tried to import the backup.json file and I got:
```
django.db.utils.IntegrityError: IntegrityError('duplicate key value violates unique constraint "sentry_useremail_user_id_469ffbb142507df2_uniq"\nDETAIL:  Key (user_id, email)=(26, {user_email@mycompany.com}) already exists.\n',)
SQL: UPDATE "sentry_useremail" SET "user_id" = %s, "email" = %s, "validation_hash" = %s, "date_hash_added" = %s, "is_verified" = %s WHERE "sentry_useremail"."id" = %s
```
(I replaced the actual email with the {} placeholder) Which I think its weird because this fresh install is using new volumes?

**Comment by azaslavsky** [comment]
It's probably trying to restore the admin data which is loaded up by default, violating uniqueness constraints. This is a major reason why we put so much work into updating the backup/restore scripts in recent versions - the old ones just blindly copy data in/out of the db, causing collision issues like this one.

Try creating a new instance, clearing the postgres DB (particularly, the tables where you are getting collision errors), then running the restore command you ran.

**Comment by brunococinoJC** [comment]
I see
I'm using the docker compose and I created all new volumes for this one that I tried to restore, so isn't using a new volume for the DB already clearing it?

Or do you mean clearing the table from the volume which I just tried to restore the data on, and then run the command again?

**Comment by azaslavsky** [comment]
Here is what I think is happening: when you do a "fresh" install of sentry, it populates the database with some very low-level basics: an admin account for `localhost`, a default organization called `sentry`, etc. What I think happened is that your export included some of those default instances, so when a fresh install makes them anew, there are collisions. However, if, after install, you clear all of these tables, those collisions should not occur.

But this is all a bit of speculation - the version you are on is >4 years old, so it's very hard to give concrete advice.
