### ISSUE TITLE
My Sentry Dashboard Side Menu is Red and I don't Know Why

### ISSUE THREAD

**Issue by Aulig** [getsentry/self-hosted#2684]
### Problem Statement

Occasionally (for a few days it's normal, then this problem is back for a few days), my sentry dashboard turns red and I can't figure out why. I assume this indicates some kind of error? I con't see any alert anywhere, nor did I find this explained in the docs.

![grafik](https://github.com/getsentry/self-hosted/assets/32148066/914caf2a-192a-427f-890c-4af159172db8)

### Solution Brainstorm

Show an alert explaining the issue that is causing the dashboard to turn red.

**Comment by hubertdeng123** [comment]
This was something new that was added, to indicate that you are now accessing your instance in super admin mode. It is intentional, so I'm going to close this.

**Comment by hubertdeng123** [comment]
@cathteng I believe you implemented this. Is this described in our docs somewhere?

**Comment by Aulig** [comment]
I see, thanks! So no error in my instance, that's good :)

**Comment by cathteng** [comment]
@hubertdeng123 yes, although it is not documented yet and we are currently making adjustments to self-hosted and demo orgs
