### ISSUE TITLE
sentry.sentry_metrics.consumers.indexer.processing.process_messages

### ISSUE THREAD

**Issue by fengxing1234** [getsentry/self-hosted#2686]
### Self-Hosted Version

23.9.1

### CPU Architecture

rancher

### Docker Version

0

### Docker Compose Version

0

### Steps to Reproduce

Level: Warning
Monitor failure: refresh-artifact-bundles-in-use
 
missed_checkin

No check-in reported on Jan 04, 06:25 AM.

INTERNAL-1P
2分 之前
 | 
2mo 之后
1.3k
0

Level: Warning
Monitor failure: deliver-from-outbox-control
 
missed_checkin

No check-in reported on Jan 04, 06:25 AM.

INTERNAL-1H
2分 之前
 | 
3mo 之后
1.3k
0

Level: Warning
Monitor failure: backfill-artifact-bundle-index
 
missed_checkin

No check-in reported on Jan 04, 06:25 AM.

INTERNAL-1G
2分 之前
 | 
3mo 之后
1.3k
0

Level: Warning
Monitor failure: schedule_auto_transition_to_ongoing
 
missed_checkin

No check-in reported on Jan 04, 06:25 AM.

INTERNAL-Y
2分 之前
 | 
3mo 之后
1.3k
0

Level: Warning
Monitor failure: clear-expired-snoozes
 
missed_checkin

No check-in reported on Jan 04, 06:25 AM.

INTERNAL-N
2分 之前
 | 
3mo 之后
542
0

Level: Warning
Monitor failure: fetch-release-registry-data
 
missed_checkin

No check-in reported on Jan 04, 06:25 AM.

INTERNAL-M
2分 之前
 | 
3mo 之后
542
0

Level: Warning
Monitor failure: clear-expired-rulesnoozes
 
missed_checkin

No check-in reported on Jan 04, 06:25 AM.

INTERNAL-B
2分 之前
 | 
3mo 之后
542
0

Level: Warning
Monitor failure: poll_recap_servers
 
missed_checkin

No check-in reported on Jan 04, 06:25 AM.

INTERNAL-9
2分 之前
 | 
3mo 之后
1.3k
0

Level: Warning
Monitor failure: send-ping
 
missed_checkin

No check-in reported on Jan 04, 06:25 AM.

INTERNAL-8
2分 之前
 | 
3mo 之后
1.3k
0

Level: Warning
Monitor failure: monitors-clock-pulse
 
missed_checkin

No check-in reported on Jan 04, 06:25 AM.

INTERNAL-7
2分 之前
 | 
3mo 之后
1.3k
0

Level: Warning
Monitor failure: check-auth
 
missed_checkin

No check-in reported on Jan 04, 06:25 AM.

INTERNAL-6
2分 之前
 | 
3mo 之后
1.3k
0

Level: Warning
Monitor failure: deliver-from-outbox
 
missed_checkin

No check-in reported on Jan 04, 06:25 AM.

INTERNAL-5
2分 之前
 | 
3mo 之后
1.3k
0

Level: Warning
Monitor failure: dynamic-sampling-collect-orgs
 
missed_checkin

No check-in reported on Jan 04, 06:20 AM.

INTERNAL-1S
7分 之前
 | 
2mo 之后
137
0

Level: Warning
Monitor failure: dynamic-sampling-boost-low-volume-projects
 
missed_checkin

No check-in reported on Jan 04, 06:20 AM.

INTERNAL-1R
7分 之前
 | 
2mo 之后
272
0

Level: Warning
Monitor failure: dynamic-sampling-boost-low-volume-transactions
 
missed_checkin

No check-in reported on Jan 04, 06:20 AM.

INTERNAL-X
7分 之前
 | 
3mo 之后
272
0

Level: Warning
Monitor failure: schedule-auto-resolution
 
missed_checkin

No check-in reported on Jan 04, 06:20 AM.

INTERNAL-W
7分 之前
 | 
3mo 之后
272
0

Level: Warning
Monitor failure: dynamic-sampling-sliding-window-org
 
missed_checkin

No check-in reported on Jan 04, 06:20 AM.

INTERNAL-F
7分 之前
 | 
3mo 之后
272
0

Level: Warning
Monitor failure: dynamic-sampling-recalibrate-orgs
 
missed_checkin

No check-in reported on Jan 04, 06:20 AM.

INTERNAL-E
7分 之前
 | 
3mo 之后
272
0

Level: Warning
Monitor failure: snuba-subscription-checker
 
missed_checkin

No check-in reported on Jan 04, 06:20 AM.

INTERNAL-D
7分 之前
 | 
3mo 之后
137
0

Level: Warning
Monitor failure: transaction-name-clusterer
 
missed_checkin

No check-in reported on Jan 04, 06:17 AM.

INTERNAL-P
10分 之前
 | 
3mo 之后
46
0

Level: Warning
Monitor failure: schedule-deletions
 
missed_checkin

No check-in reported on Jan 04, 06:15 AM.

INTERNAL-20
12分 之前
 | 
2mo 之后
181
0

Level: Warning
Monitor failure: schedule-deletions-control
 
missed_checkin

No check-in reported on Jan 04, 06:15 AM.

INTERNAL-1Y
12分 之前
 | 
2mo 之后
181
0

Level: Warning
Monitor failure: schedule-hybrid-cloud-foreign-key-jobs-control
 
missed_checkin

No check-in reported on Jan 04, 06:15 AM.

INTERNAL-1X
12分 之前
 | 
2mo 之后
181
0

Level: Warning
Monitor failure: auto-remove-inbox
 
missed_checkin

No check-in reported on Jan 04, 06:15 AM.

INTERNAL-1W
12分 之前
 | 
2mo 之后
181
0

Level: Warning
Monitor failure: update-user-reports
 
missed_checkin

No check-in reported on Jan 04, 06:15 AM.

INTERNAL-1Z
12分 之前
 | 
2mo 之后

![image](https://github.com/getsentry/self-hosted/assets/25051258/3b547a1a-a59d-42c2-bba9-01e4e0163076)

### Expected Result

I hope Sentry works properly

### Actual Result

![image](https://github.com/getsentry/self-hosted/assets/25051258/78a90194-6c2a-4624-b85e-8640b84fcd48)

**Comment by aldy505** [comment]
Hello! I don't quite get what the issue is and why have you came across this kind of internal errors so far.

Can you please make a detailed description of your current setup? Do you enable the Cron monitoring feature as described [in here](https://github.com/getsentry/self-hosted/issues/1993#issuecomment-1675633779)?
