### ISSUE TITLE
How to modify Members > Owner?

### ISSUE THREAD

**Issue by yysfwls** [getsentry/self-hosted#2687]
### Problem Statement

Owner's account cannot be logged in after accessing sso, how to change to other members? The configuration is not found in the config.yml and sentry.conf.py and docker-compose.yml...

**Comment by yysfwls** [comment]
<img width="1429" alt="65fb16f3bd4344eaf6a193fb1768e0b7" src="https://github.com/getsentry/self-hosted/assets/29426633/f15d41a1-f45b-4f6b-a090-7d8afc4ad5a5">

**Comment by yysfwls** [comment]
<img width="1069" alt="719eeb1dc279f18f09a3b26e7a057e6e" src="https://github.com/getsentry/self-hosted/assets/29426633/600de8c2-e85c-48f5-83bb-310114a18071">

I can't modify these

**Comment by hubertdeng123** [comment]
What you can do is change the permissions of your current user in postgres manually. You should be able to do this by modifying the `auth_user` table.

**Comment by yysfwls** [comment]
> What you can do is change the permissions of your current user in postgres manually. You should be able to do this by modifying the `auth_user` table.

sorry🥹，Do you have any more guidance?
![20240109-163403](https://github.com/getsentry/self-hosted/assets/29426633/d32c9590-415d-42a4-b45e-d87ed11e663f)

**Comment by azaslavsky** [comment]
```
docker compose exec postgres bash
psql -U postgres
select * from auth_user where email = <EMAIL_YOUI_CARE_ABOUT>;
```

You can then use standard SQL to update the `is_staff` and `is_superuser` booleans to `TRUE`.
