### ISSUE TITLE
Projects Dashboard error

### ISSUE THREAD

**Issue by 13267153287** [getsentry/self-hosted#2694]
### Platform

iOS

### Environment

Production

### Installed

CocoaPods

### Version

8.17.2

### Steps to Reproduce

<img width="299" alt="截屏2024-01-04 16 34 50" src="https://github.com/getsentry/sentry-cocoa/assets/51962401/5e836434-0b2f-4acc-9e9f-5cbb9de63750">

### Expected Result

When I refresh the dashboard, it will prompt me with errors in the image

### Actual Result

![Uploading 截屏2024-01-04 16.34.50.png…]()

**Comment by azaslavsky** [comment]
What version of self-hosted are you on?
