### ISSUE TITLE
Superusers unable to do multiple kinds of operations in the admin interface

### ISSUE THREAD

**Issue by jklaiho** [getsentry/self-hosted#2695]
### Self-Hosted Version

23.11.2

### CPU Architecture

x86_64

### Docker Version

24.0.7

### Docker Compose Version

2.21.0

### Steps to Reproduce

1. Log in as a superuser.
2. Attempt to perform any of the following actions in the UI:
  - in Admin -> Manage -> Users, attempt to hard delete a user account.
  - in Admin -> System Status -> Settings, attempt to adjust any of the rate limits or the Support and Security e-mails

### Expected Result

All attempted operations succeed.

### Actual Result

The attempted operations (possibly others that I haven't tested) fail.

Some background first: this is an old Sentry installation, dating back to at least the 8.x or 9.x era, if not earlier. I think initially it wasn't even container-based yet, but we've successfully upgraded it all the way to modern versions, and in the Compose era we've always done it with the official documented process, following all mandatory version steps.

It originally got installed with a single user called `sentry@localhost`, which still exists and has superuser privileges. It's the only user attached to the built-in `sentry` organization. We've since added two other superuser accounts that are actually connected to our main company organization, but not the `sentry` org, which we don't use for anything ourselves (but Sentry itself seems to log some things there). All of these account additions were done in the "old" era, prior to v10.

When logged in as any of the superusers, all the views can be opened (this requires separate superuser password re-entry in Safari, but not in Chrome for some reason). But performing the listed operations fails. Here's how:

**Hard deletion of a user**: this calls `DELETE /api/0/users/<id>/` and returns with an HTTP 403 and this message:
```
{
    "detail": "Missing required permission to hard delete account."
}
```

The deletion failure seems to not be affected by any org or team memberships that the user has or doesn't have. However, deactivating a user with a PUT to the same URL works just fine.

**The Settings page changes**: these do `PUT /api/0/internal/options/`, with a payload like `{system.rate-limit: "0"}` and they all fail with a 403 with an empty response, just displaying a "Failed to save" message in the form field.

Weirdly, I **am** able to edit the Admin Email field (with the payload `{system.admin-email: "somedude@someorg.com"}`), but not the Support Email and Security Email fields.

-----

Superusers, particularly in Django apps that rely on the `is_superuser` attribute, should be able to do any of these things, of course. Something's either off in our installation, or there's a Sentry bug. On our main company org, everything is working exactly as expected, it's just the site-wide admin that is flaking out.

**Comment by azaslavsky** [comment]
Sometimes very long-lived superuser sessions require the cookies to be manually deleted, and for you to re-log in, then go to the `Admin` menu in your profile dropdown. Unlikely, but worth a shot.

Do you have any logs on the `web` container, showing why these calls were rejected?

Can you also look at the following for the 3 superusers in question? Possible postgres to do this:

```
docker compose exec postgres bash
psql -U postgres
select username from auth_user where is_superuser = True;
```

**Comment by jklaiho** [comment]
Not an issue of session length; I'd not logged into the `sentry@localhost` user for literal years. Just to be safe I now logged in with a browser I've never used for Sentry, and the issue persisted.

All three superusers (and only them) were returned by the superuser query.

In the web logs (accessed with `docker compose logs -f --since 1m web`), nothing I could see for a failed request apart from this:

```
sentry-self-hosted-web-1  | 06:34:10 [INFO] sentry.superuser: superuser.request (url='http://sentry.ourdomain.com/api/0/internal/options/' method='PUT' ip_address='xxx.xxx.xxx.xxx' user_id=6)
sentry-self-hosted-web-1  | 06:34:10 [INFO] sentry.access.api: api.access (method='PUT' view='sentry.api.endpoints.system_options.SystemOptionsEndpoint' response=403 user_id='6' is_app='False' token_type='None' is_frontend_request='True' organization_id='None' auth_id='None' path='/api/0/internal/options/' caller_ip='xxx.xxx.xxx.xxx' user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.04027962684631348 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
sentry-self-hosted-web-1  | 06:34:10 [WARNING] django.request: Forbidden: /api/0/internal/options/ (status_code=403 request=<WSGIRequest: PUT '/api/0/internal/options/'>)
```

**Comment by hubertdeng123** [comment]
Looks like I'm able to reproduce this. Think it might be due to 
https://github.com/getsentry/sentry/pull/38389
