### ISSUE TITLE
[Self-Hosted] No Organization Access after upgrade as organization owner

### ISSUE THREAD

**Issue by debnet** [getsentry/self-hosted#2696]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

The issue happened after upgrading from 23.6.0 to 23.6.2 then 23.12.1.

I'm owner of the organization but I have the following message when logged onto Sentry:

> **No Organization Access**
> 
> You do not have access to any organizations within Sentry.
> 
> If you were expecting otherwise, this may be due to a configuration change in the organization. Please check your email inbox for an invite link to rejoin the organization.
> 
> Alternatively, reach out to an admin in your organization to re-invite you using [this guide](https://help.sentry.io/account/account-settings/how-do-i-add-members-to-my-organization/)
> 
> If you need to make changes to your user account, [please click here.](https://sentry.uchange.co/settings/account/)

When clicking on "please click here" I can still access Sentry organization and administration.

### Expected Result

Not having the "no organization access" when logged in.

### Actual Result

![image](https://github.com/getsentry/sentry/assets/634832/a37db325-ac29-4cd0-a3f6-731269024f55)

### Product Area

Sign In

### Version

23.12.1

**Comment by joeangry** [comment]
I just did a restore from a 23.1.1 backup to 23.1.1 then upgraded to 23.12.1 today, and I'm seeing the same thing as well.

**Comment by aldy505** [comment]
Hello @debnet and @joeangry, one user on Discord said they remedied the issue by changing their organization slug to something else. Give it a try and see if it resolved the issue. [See here](https://discord.com/channels/621778831602221064/796028405833007104/1186820368585994323) for the chat reference.

**Comment by joeangry** [comment]
> Hello @debnet and @joeangry, one user on Discord said they remedied the issue by changing their organization slug to something else. Give it a try and see if it resolved the issue. [See here](https://discord.com/channels/621778831602221064/796028405833007104/1186820368585994323) for the chat reference.

That seems to have fixed it for me. Thanks!

**Comment by debnet** [comment]
> Hello @debnet and @joeangry, one user on Discord said they remedied the issue by changing their organization slug to something else. Give it a try and see if it resolved the issue. [See here](https://discord.com/channels/621778831602221064/796028405833007104/1186820368585994323) for the chat reference.

It worked! Weird but thanks!

**Comment by aldy505** [comment]
I'm gonna close the issue. Feel free to create a new one and reference this issue if you encounter another one.
