### ISSUE TITLE
SSO (ADFS) with 2FA broken

### ISSUE THREAD

**Issue by 13werwolf13** [getsentry/self-hosted#2697]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

1. install self-hosted sentry
2. add ADFS SSO
3. add 2FA to user accounts

### Expected Result

after login write totp key & work

### Actual Result

2FA works for some users, for others it doesn’t (it asks for a key, but regardless of its correctness, it simply doesn’t login into sentry)

### Product Area

Sign In

### Version

23.6.1

**Comment by azaslavsky** [comment]
Do you have any server logs (from the `web` container) when these log ins fail? Generally, you'll be looking for a 400 or 403 error.

**Comment by azaslavsky** [comment]
Do you see anything suspicious in the `web` logs at all? It's odd that it would fail to log users in without leaving any breadcrumbs.

**Comment by 13werwolf13** [comment]
> Do you see anything suspicious in the `web` logs at all? It's odd that it would fail to log users in without leaving any breadcrumbs.

We will try to repeat the problem on a test bench so as not to experiment on a production instance. I'll come back later with an example log.
