### ISSUE TITLE
AWS EC2 Fails while starting the containers

### ISSUE THREAD

**Issue by Pixel-Minions** [getsentry/self-hosted#2703]
### Self-Hosted Version

23.13.1

### CPU Architecture

x86_64

### Docker Version

24 latest - Ubuntu and Debian

### Docker Compose Version

2.23.3

### Steps to Reproduce

When running 

`sudo docker compose up -d`

### Expected Result

Start all the containers

### Actual Result

Hangs here:

Started0.3s
 ✔ Container sentry-self-hosted-snuba-subscription-consumer-events-1            Started0.0s
 ✔ Container sentry-self-hosted-subscription-consumer-transactions-1            Started0.3s
 ✔ Container sentry-self-hosted-ingest-occurrences-1                            Started0.2s
 ✔ Container sentry-self-hosted-post-process-forwarder-issue-platform-1         Started0.3s
 ✔ Container sentry-self-hosted-worker-1                                        Started0.3s
 ✔ Container sentry-self-hosted-cron-1                                          Started0.3s
 ✔ Container sentry-self-hosted-attachments-consumer-1                          Started0.3s
 ✔ Container sentry-self-hosted-subscription-consumer-generic-metrics-1         Started0.3s
 ✔ Container sentry-self-hosted-metrics-consumer-1                              Started0.3s
 ✔ Container sentry-self-hosted-subscription-consumer-metrics-1                 Started0.3s
 ✔ Container sentry-self-hosted-post-process-forwarder-errors-1                 Started0.3s

**Comment by aldy505** [comment]
Hi. Can you give more detailed information of your current setup and commands you did before running `sudo docker compose up -d`?

**Comment by Pixel-Minions** [comment]
Hi, literally I follow these steps:
https://develop.sentry.dev/self-hosted/

Run in a AWS EC2 Ubuntu and Debian, in both happens the same. I make sure to use machines that matches at least the minimum requirements:
Then run:
`./install.sh`
and finally `sudo docker compose up -d`

**Comment by aldy505** [comment]
Have you tried to increase your machine specification? Perhaps somewhere around 4 vCPU + 16 GB RAM (t3.xlarge / t4g.xlarge / t2.xlarge instances). I really doubt Sentry would run against the minimum machine specification (2 vCPU + 4 GB RAM)

**Comment by Pixel-Minions** [comment]
Yes, I tried with t3 medium and large with the same results.

**Comment by Pixel-Minions** [comment]
Actually, I haven't tried with t4g.xlarge, I can give it a try, but the error is when just initializing the docker not during server execution.
