### ISSUE TITLE
No user feedback entry

### ISSUE THREAD

**Issue by zpfhyj** [getsentry/self-hosted#2705]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

I have updated self hosted sentry from 23.7.2 to 23.12.1. But after the update was completed, I found that there was no User Feedback entry left。 
As shown in the figure below, I logged in as an admin administrator account without a user feedback entry point
![sentry](https://github.com/getsentry/sentry/assets/24708763/cc3fd66b-8a37-4b8a-a23b-116e00ced5ce)

### Expected Result

Entrance with user feedback

### Actual Result

There is no entrance for user feedback

### Product Area

User Feedback

### Version

23.12.1

**Comment by aldy505** [comment]
Yeah the User Feedback feature is still in beta. You can enable it by customizing some things as you can see here https://github.com/getsentry/self-hosted/issues/2646

**Comment by zpfhyj** [comment]
> Yeah the User Feedback feature is still in beta. You can enable it by customizing some things as you can see here #2646

Ok, thank you very much. Follow the corresponding steps to modify it. The userfeedback entry is now functioning properly
