### ISSUE TITLE
How to create alert

### ISSUE THREAD

**Issue by Machock** [getsentry/self-hosted#2706]
### Self-Hosted Version

22.10.0

### CPU Architecture

x86_64

### Docker Version

20.10.10

### Docker Compose Version

2.6.0

### Steps to Reproduce

WHEN an event is captured by Sentry and all of the following happens
1.Number of events in an issue is more than 50 in 5minutes

IF all of these filters match
1.The event's tags match country equals US
2.The issue has happened at least 30 times

### Expected Result

if match country tag equals US &&  at least 30 times, will trigger webhooks

### Actual Result

how to understand my rule?

**Comment by hubertdeng123** [comment]
Are you asking if this is the right way to configure an alert for `if match country tag equals US && at least 30 times, will trigger webhooks`?

**Comment by Machock** [comment]
> Are you asking if this is the right way to configure an alert for `if match country tag equals US && at least 30 times, will trigger webhooks`?

yes, I want to know if these two conditions are the correct configuration.

**Comment by hubertdeng123** [comment]
That sounds correct, but you can probably get rid of the `The issue has happened at least 30 times` filter, since that is redundant

**Comment by Machock** [comment]
> That sounds correct, but you can probably get rid of the `The issue has happened at least 30 times` filter, since that is redundant

okay, I want to know sth about custom alert, can i use webhooks for step4 ?

<img width="896" alt="MicrosoftTeams-image (52)" src="https://github.com/getsentry/self-hosted/assets/27527278/7db404ac-ff88-412b-95a3-f92cdba45cb6">

**Comment by azaslavsky** [comment]
If you want to trigger a webhook call via an alertrule, you'll need to [build your own integration](https://docs.sentry.io/product/alerts/create-alerts/routing-alerts/#build-your-own-integration).

**Comment by Machock** [comment]
> build your own integration

I was installed webhooks plugin, I create issue alert, I can choice webhooks notification(as below image), but I create Custom Metric alert, there are no choice to select webhooks, what happened ? 
<img width="730" alt="image" src="https://github.com/getsentry/self-hosted/assets/27527278/3fcd594a-3b9d-4592-8c35-8892d13bd49b">

**Comment by azaslavsky** [comment]
No, you need to make a custom webhook integration. That is different from installing the webhook plugin. In this case, you are doing something more akin to making your own plugin which is triggered on alert rule actions.

**Comment by Machock** [comment]
> No, you need to make a custom webhook integration. That is different from installing the webhook plugin. In this case, you are doing something more akin to making your own plugin which is triggered on alert rule actions.

now, I get the webhook timeout, but test webhook is success, that happend ? where network need to connect ?

<img width="691" alt="image" src="https://github.com/getsentry/self-hosted/assets/27527278/8dc6ced4-8fa5-4f51-992f-4042fb587b72">

**Comment by Machock** [comment]
> No, you need to make a custom webhook integration. That is different from installing the webhook plugin. In this case, you are doing something more akin to making your own plugin which is triggered on alert rule actions.

now, I get the webhook timeout, but test webhook is success, that happend ? where network need to connect ? I test in my laptop also success.

<img width="691" alt="image" src="https://github.com/getsentry/self-hosted/assets/27527278/8dc6ced4-8fa5-4f51-992f-4042fb587b72">
