### ISSUE TITLE
No Issues incoming (on premise)

### ISSUE THREAD

**Issue by wm-ek** [getsentry/self-hosted#2707]
### Self-Hosted Version

23.12.1

### CPU Architecture

x86_64

### Docker Version

 24.0.7, build afdd53b

### Docker Compose Version

1.29.2, build 5becea4c

### Steps to Reproduce

1. Last week we had a project which sent a lot of requests to our sentry on premise instance. This caused also a high cpu load. We then removed the project and the queue of issues got cleared. The cpu load is now regular.
2. Now there are still no issues showing up under "Issues", from no project.
![6d6890f3ea816608a384e80f33699fd4](https://github.com/getsentry/self-hosted/assets/119679524/6dd49d18-cdb1-429d-9498-95d39426cefb)
3. Replays and performance data is showing correctly.
4. We attached some logs.
[logs_kafka.txt](https://github.com/getsentry/self-hosted/files/13941511/logs_kafka.txt)
[logs_redis.txt](https://github.com/getsentry/self-hosted/files/13941512/logs_redis.txt)

### Expected Result

Issues should show up.

### Actual Result

No new issues are incoming

**Comment by aldy505** [comment]
By "removed the project", did you delete the project from your Sentry organization dashboard? If you did, it's to be expected that the issues would be deleted too.

**Comment by wm-ek** [comment]
We removed the project from the application itself but not yet from sentry. however, this morning there were some new events incoming. now i also deleted the whole project and associated data on sentry itself. we will monitor the behaviour.

**Comment by jansorg** [comment]
fyi, I observed a similar problem. Restarting the container helped to process entries again.

**Comment by wm-ek** [comment]
@aldy505 
> Can your Sentry instance be accessible from public internet? If that's the case, you can do some security enhancement on your outermost reverse proxy

yes, the instance is publicly accessible. we are using it for ourself and client projects. we are using cloudflare as reverse proxy in front of the server; all traffic must come from cloudflare.

i already thought about limiting access but haven't had success yet finding up to date information:
- One thing would be limiting access to endpoints; make only those endpoints available publicly which need to be.
- Allow only traffic including referer from our projects - but i am not sure if that works.

Do you have any additional information or recommendations? That would be very valuable.

Thanks

**Comment by aldy505** [comment]
> @aldy505
> 
> > Can your Sentry instance be accessible from public internet? If that's the case, you can do some security enhancement on your outermost reverse proxy
> 
> yes, the instance is publicly accessible. we are using it for ourself and client projects. we are using cloudflare as reverse proxy in front of the server; all traffic must come from cloudflare.
> 
> i already thought about limiting access but haven't had success yet finding up to date information:
> 
> * One thing would be limiting access to endpoints; make only those endpoints available publicly which need to be.
> * Allow only traffic including referer from our projects - but i am not sure if that works.
> 
> Do you have any additional information or recommendations? That would be very valuable.
> 
> Thanks

See here: https://develop-8nsmrr5v5.sentry.dev/self-hosted/productionalizing

It's not merged to the main branch yet, but at least that contains a few things I'd suggest:
- Limit your internal/external access.
- Apply rate limiting, for normal instance, 100 rps might be a good start.
