### ISSUE TITLE
Partial JSON restore doesn't replace default organization

### ISSUE THREAD

**Issue by MoogyG** [getsentry/self-hosted#2709]
### Self-Hosted Version

23.11.2

### CPU Architecture

x86_64

### Docker Version

24.0.7

### Docker Compose Version

2.21.0

### Steps to Reproduce

1. make a partial JSON in production using "./backup.sh"
2. In staging, use "./install.sh --skip-user-creation --no-report-self-hosted-issues" 
3. then "docker compose --env-file .env.custom up -d" 
4. And finally "./restore.sh"

### Expected Result

I hope the default organization created during installation process to be replaced during the import.

### Actual Result

Here is the content of "sentry_organization" in production : 
```docker compose exec postgres psql -qAt -U postgres -d postgres -c "SELECT * FROM sentry_organization;"```
```1|Aleo|sentry|0|2022-03-07 15:55:47.06+00|member|0|f```

And the result in staging :

```docker compose exec postgres psql -qAt -U postgres -d postgres -c "SELECT * FROM sentry_organization;"```
```1|Sentry|sentry|0|2024-01-15 21:05:38.269531+00|member|1|f```
```2|Aleo|sentry-20|0|2022-03-07 15:55:47.06+00|member|0|f```

**Comment by hubertdeng123** [comment]
This should now be fixed in 23.12.0+. You'll need to upgrade if you would like this to work as you want it to

**Comment by MoogyG** [comment]
You are right, problem solved with 23.12.1.

Thanks!
