### ISSUE TITLE
Permissions on settings update inside container

### ISSUE THREAD

**Issue by darkfortressAU** [getsentry/self-hosted#2715]
### Self-Hosted Version

23.12.1

### CPU Architecture

x86_64

### Docker Version

24.0.7

### Docker Compose Version

2.21.0

### Steps to Reproduce

Install self hosted as per doco
attempt to set a feature in the early features tab such as the new UI

### Expected Result

Feature is activated

### Actual Result

`
sentry-self-hosted-web-1                                           | 23:35:22 [INFO] sentry.superuser: superuser.request (url='http://sentry-test.domain.com/api/0/internal/feature-flags/' method='PUT' ip_address='xxx.xxx.xxx.xxx' user_id=11)
sentry-self-hosted-web-1                                           | Traceback (most recent call last):
sentry-self-hosted-web-1                                           |   File "/usr/local/lib/python3.10/site-packages/sentry/api/base.py", line 231, in handle_exception
sentry-self-hosted-web-1                                           |     response = super().handle_exception(exc)
sentry-self-hosted-web-1                                           |   File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
sentry-self-hosted-web-1                                           |     self.raise_uncaught_exception(exc)
sentry-self-hosted-web-1                                           |   File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
sentry-self-hosted-web-1                                           |     raise exc
sentry-self-hosted-web-1                                           |   File "/usr/local/lib/python3.10/site-packages/sentry/api/base.py", line 355, in dispatch
sentry-self-hosted-web-1                                           |     response = handler(request, *args, **kwargs)
sentry-self-hosted-web-1                                           |   File "/usr/local/lib/python3.10/site-packages/sentry/api/endpoints/internal/feature_flags.py", line 43, in put
sentry-self-hosted-web-1                                           |     with open(py, "r+") as file:
sentry-self-hosted-web-1                                           | PermissionError: [Errno 13] Permission denied: '/etc/sentry/sentry.conf.py'

`

**Comment by aldy505** [comment]
Yeah this is a known problem.

See https://github.com/getsentry/self-hosted/issues/2533 and https://github.com/getsentry/sentry/pull/59956#issuecomment-1830804286

**Comment by darkfortressAU** [comment]
![Screenshot 2024-01-29 at 07-34-23 Create User Auth Token — Sentry](https://github.com/getsentry/self-hosted/assets/22900318/fb1b8d3a-cb8f-45e5-b939-abe8d0187fb8)
![Screenshot 2024-01-29 at 07-34-11 Create User Auth Token — Sentry](https://github.com/getsentry/self-hosted/assets/22900318/fd4db4e6-2c96-4fee-ab80-487b7e02c379)
![Screenshot 2024-01-29 at 07-34-06 Create User Auth Token — Sentry](https://github.com/getsentry/self-hosted/assets/22900318/ccf782a2-19cc-487e-88be-e9a5905bdb1e)
[sentry.nt.gov.au_Archive [24-01-29 07-34-48].har.txt](https://github.com/getsentry/self-hosted/files/14077908/sentry.nt.gov.au_Archive.24-01-29.07-34-48.har.txt)

**Comment by darkfortressAU** [comment]
sentry-self-hosted-web-1                                           | 22:31:53 [INFO] sentry.security: user.api-token-generated (ip_address='155.205.31.7' user_id=1 actor_id=1)
sentry-self-hosted-web-1                                           | 22:31:56 [INFO] sentry.access.api: api.access (method='POST' view='sentry.api.endpoints.relay.project_configs.RelayProjectConfigsEndpoint' response=200 user_id='None' is_app='None' token_type='None' is_frontend_request='False' organization_id='None' auth_id='None' path='/api/0/relays/projectconfigs/' caller_ip='172.18.0.50' user_agent='None' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.015787124633789062 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
sentry-self-hosted-nginx-1                                         | 10.2.39.246 - - [28/Jan/2024:22:31:57 +0000] "GET /_health/ HTTP/1.1" 200 12 "-" "-" "-"
sentry-self-hosted-nginx-1                                         | 10.2.39.245 - - [28/Jan/2024:22:31:59 +0000] "GET /_health/ HTTP/1.1" 200 12 "-" "-" "-"
sentry-self-hosted-ingest-monitors-1                               | 22:32:00 [INFO] sentry: monitors.consumer.clock_tick (reference_datetime='2024-01-28 22:32:00+00:00')
sentry-self-hosted-web-1                                           | 22:32:06 [INFO] sentry.access.api: api.access (method='POST' view='sentry.api.endpoints.relay.project_configs.RelayProjectConfigsEndpoint' response=200 user_id='None' is_app='None' token_type='None' is_frontend_request='False' organization_id='None' auth_id='None' path='/api/0/relays/projectconfigs/' caller_ip='172.18.0.50' user_agent='None' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.015635967254638672 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
sentry-self-hosted-web-1                                           | 22:32:16 [INFO] sentry.access.api: api.access (method='POST' view='sentry.api.endpoints.relay.project_configs.RelayProjectConfigsEndpoint' response=200 user_id='None' is_app='None' token_type='None' is_frontend_request='False' organization_id='None' auth_id='None' path='/api/0/relays/projectconfigs/' caller_ip='172.18.0.50' user_agent='None' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.01578664779663086 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
sentry-self-hosted-nginx-1                                         | 10.2.39.246 - - [28/Jan/2024:22:32:17 +0000] "GET /_health/ HTTP/1.1" 200 12 "-" "-" "-"
sentry-self-hosted-nginx-1                                         | 10.2.39.245 - - [28/Jan/2024:22:32:19 +0000] "GET /_health/ HTTP/1.1" 200 12 "-" "-" "-"
sentry-self-hosted-nginx-1                                         | 2024/01/28 22:32:23 [error] 22#22: *92739 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 10.2.39.247, server: , request: "POST /api/0/api-tokens/ HTTP/1.1", upstream: "http://172.18.0.36:9000/api/0/api-tokens/", host: "sentry.domain", referrer: "https://sentry.domain/settings/account/api/auth-tokens/new-token/"
sentry-self-hosted-nginx-1                                         | 10.2.39.247 - - [28/Jan/2024:22:32:23 +0000] "POST /api/0/api-tokens/ HTTP/1.1" 504 160 "https://sentry.domain/settings/account/api/auth-tokens/new-token/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0" "155.205.31.7"
sentry-self-hosted-web-1                                           | 22:32:24 [INFO] sentry.mail: mail.queued (message_type='api-token-generated' simplelazyobject_id=1 message_id='<xxxx@nt.gov.au>' message_to=(xxxx@xxx',))
sentry-self-hosted-worker-1                                        | 22:32:24 [INFO] sentry.mail: mail.sent (message_id='<xxxx@nt.gov.au>' size=5608)
sentry-self-hosted-web-1                                           | 22:32:24 [INFO] sentry.access.api: api.access (method='POST' view='sentry.api.endpoints.api_tokens.ApiTokensEndpoint' response=201 user_id='1' is_app='False' token_type='None' is_frontend_request='True' organization_id='None' auth_id='None' path='/api/0/api-tokens/' caller_ip='155.205.31.7' user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0' rate_limited='False' rate_limit_category='None' request_duration_seconds=30.615819692611694 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
sentry-self-hosted-web-1                                           | 22:32:26 [INFO] sentry.access.api: api.access (method='POST' view='sentry.api.endpoints.relay.project_configs.RelayProjectConfigsEndpoint' response=200 user_id='None' is_app='None' token_type='None' is_frontend_request='False' organization_id='None' auth_id='None' path='/api/0/relays/projectconfigs/' caller_ip='172.18.0.50' user_agent='None' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.014843940734863281 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')

**Comment by aldy505** [comment]
Hi, can you provide some context regarding those screenshots and logs? Is it the same problem as this issue, or is it a whole separate one? Also, what's your objective/things you'd expect to work?

**Comment by darkfortressAU** [comment]
Wrong bug apologies

**Comment by darkfortressAU** [comment]
This issue appears resolved in 24.1
