### ISSUE TITLE
Issue With Showing Auth Tokens In UI

### ISSUE THREAD

**Issue by rojinebrahimi** [getsentry/self-hosted#2716]
### Self-Hosted Version

23.12.1

### CPU Architecture

x86_64

### Docker Version

24.0.6

### Docker Compose Version

2.23.0

### Steps to Reproduce

Hi. When I try to create the Auth Token via UI, it does not show me the created token. However, the token is created successfully.

### Expected Result

UI should show me the token when I create it.

### Actual Result

It gives me either a 502 or 504 status code in Nginx logs.

**Comment by hubertdeng123** [comment]
Are there any logs that are displayed in your web container? You're saying that in the Settings->Auth Tokens you are not seeing any tokens displayed after being created?

**Comment by rojinebrahimi** [comment]
Hi, 
In fact, I see the settings and when I click Create New Token button, I only see 502 in Nginx log and UI after a while. The problem is that the token in fact gets created but the frontend does not show the generated token and instead gives us a 502/504 status code.

**Comment by azaslavsky** [comment]
Can you paste the log message (with the token sanitized, of course)?
