### ISSUE TITLE
Sentry 23.6.1 Integration with Jira Server(JIRA-9.12.1) Failed 400 Bad Request

### ISSUE THREAD

**Issue by yildizozgur** [getsentry/self-hosted#2718]
### Environment

self-hosted 23.6.1 

### Steps to Reproduce

1.Create an integration between Jira and Sentry according to this documentation: https://docs.sentry.io/product/integrations/issue-tracking/jira/
2.Navigate to organization( or default Sentry)
3.Click on "Issues" and open a specific issue
4.Click on "Link Jira Server Issue"

### Expected Result

When clicking on "Link Jira Server Issue", Jira issue create screen should appear without any errors and allow to create a Jira issue

### Actual Result

![Screenshot 2024-01-17 at 12 37 34](https://github.com/getsentry/sentry/assets/30257807/af8941f9-b4d4-42fa-9cf2-5971992586f1)

11:43:38 [ERROR] sentry_sdk.errors: Internal error in sentry_sdk
11:43:43 [INFO] sentry.integrations.client: integration.http_response (status_string='200' integration='jira_server')
11:43:44 [INFO] sentry.integrations.client: integration.http_response (status_string='400' error='400 Client Error:  for url: https://abc-jira.mysite.com/rest/api/2/issue/createmeta/554412/issuetypes' integration='jira_server')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sentry/shared_integrations/client/base.py", line 176, in _request
    resp.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/sentry/../requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error:  for url: https://abc-jira.mysite.com/rest/api/2/issue/createmeta/11602/issuetypes

When I checked Jira side, There was an update removing "createmeta" api calls. But sentry 23.6.1 which too newer version after Jira update still tries to use createmeta. Is there any workaround to skip this error?

https://confluence.atlassian.com/jiracore/createmeta-rest-endpoint-to-be-removed-975040986.html

### Product Area

Settings - Integrations

**Comment by hubertdeng123** [comment]
Looks like this is the same issue as https://github.com/getsentry/self-hosted/issues/2153, is that correct?

**Comment by yildizozgur** [comment]
Yes , it seems similar. Is there any solution to pass this error?

**Comment by azaslavsky** [comment]
No, we haven't gotten to the bottom of that one yet, and have had trouble replicating on our end. Any contributions on that front would be welcome!

**Comment by yildizozgur** [comment]
Hi, still waiting solution. I could not get appropriate solution .

**Comment by hubertdeng123** [comment]
Unfortunately, we have not made progress here. I'm going to close this and let's try and keep the bulk of the activity here, which has more engagement:
https://github.com/getsentry/self-hosted/issues/2153
