### ISSUE TITLE
Question about installation with http_proxy

### ISSUE THREAD

**Issue by lemrouch** [getsentry/self-hosted#2725]
### Problem Statement

I'm trying to install Sentry behind firewall.
Code in https://github.com/getsentry/self-hosted/pull/1543/files is
```
RUN if [ -z "${http_proxy}" ]; then echo "Acquire::http::proxy \"${http_proxy}\";" >> /etc/apt/apt.conf; fi
RUN if [ -z "${https_proxy}" ]; then echo "Acquire::https::proxy \"${https_proxy}\";" >> /etc/apt/apt.conf; fi
```
In my experience and documentation `-z` in test means _if the string is empty_ therefore the config won't be set if there are actual values in http_proxy and/or https_proxy variables.

### Solution Brainstorm

I guess the code was meant to be
```
RUN if [ ! -z "${http_proxy}" ]; then echo "Acquire::http::proxy \"${http_proxy}\";" >> /etc/apt/apt.conf; fi
RUN if [ ! -z "${https_proxy}" ]; then echo "Acquire::https::proxy \"${https_proxy}\";" >> /etc/apt/apt.conf; fi
```
or
```
RUN if [ -n "${http_proxy}" ]; then echo "Acquire::http::proxy \"${http_proxy}\";" >> /etc/apt/apt.conf; fi
RUN if [ -n "${https_proxy}" ]; then echo "Acquire::https::proxy \"${https_proxy}\";" >> /etc/apt/apt.conf; fi
```
Am I right or too tired?

**Comment by azaslavsky** [comment]
I think that's correct. Any interest in submitting a PR with the fix?
