### ISSUE TITLE
Replay retrieval suddenly stops working when using s3 storage (root: Storage GET error)

### ISSUE THREAD

**Issue by csvan** [getsentry/self-hosted#2729]
### Self-Hosted Version

21.13.1

### CPU Architecture

x86_64

### Docker Version

24.0.5

### Docker Compose Version

2.24.1

### Steps to Reproduce

Setup Sentry server with s3 backing

### Expected Result

Replays should work and be accessible in GUI

### Actual Result

Everything worked fine up until a random point in time, after which Replays can no longer be accessed. The GUI shows a generic error:

<img width="731" alt="Screenshot 2024-01-23 at 11 42 06" src="https://github.com/getsentry/self-hosted/assets/1127729/389e0f72-cb1f-42d2-afff-e811b33c8e79">

Inspecting the logs, we see `web` consistently throw this when Replays are being accessed:

```
web-1  | 10:36:01 [WARNING] root: Storage GET error.
```

This may seem plain enough, but exactly _what_ is going wrong? For other errors, we got detailed traces with S3 errors related to e.g. bucket access, but this really tells us nothing. There_ are no other logs showing exactly what went wrong either. 

Nothing has changed in the config of the server, Sentry or the associated s3 bucket. 

We have also verified that the server can still read/write the bucket - we can also see that Sentry is writing objects to it just fine.

So it appears something suddenly broke with Sentry accessing stuff on the bucket, but how can we even debug this? The logs do not give us anything to go on.

**Comment by csvan** [comment]
UPDATE: Starting a new Sentry server using the exact same settings as the previous one (`backup.sh` on the old instance and `restore.sh` on the new one), using the same s3 bucket, solves the issue. 

We also noticed that we could access _older_ Replays in the previous instance, suggesting that this is not a general issue with s3 access .

Guessing here, but it seems like Sentry at some point experienced an issue that caused it to (maybe?) mess up the names of s3 file references, meaning it could write them just fine, but then failed to retrieve them since the identifiers were incorrect.

**Comment by csvan** [comment]
UPDATE: Nvm, it stopped working again. Now we are seeing this in the logs if it's any help:

```
web-1  |   File "/usr/local/lib/python3.10/site-packages/sentry/snuba/referrer.py", line 754, in validate_referrer
web-1  |     raise Exception(error_message)
web-1  | Exception: referrer replays.query.details_query is not part of Referrer Enum
web-1  | 11:56:28 [WARNING] sentry.snuba.referrer: referrer replays.query.details_query is not part of Referrer Enum
```

**Comment by aldy505** [comment]
@hubertdeng123 @azaslavsky Can we transfer this to [github.com/getsentry/sentry](https://github.com/getsentry/sentry) to check if the team found any bugs on the S3 storage implementation?

**Comment by azaslavsky** [comment]
@aldy505 we don't use s3 internally as far as I'm aware, the integration only exists for self-hosted users, so this seems like the best home for it.

I think the best approach here is to go into https://github.com/getsentry/sentry/blob/b490e02482ee0c56f56194b11aa470c4462208e6/src/sentry/filestore/s3.py#L4 and add a ton of logging, especially of the errors reported back by S3, then restart the server. Hopefully this shines some more light on what is going on.
