### ISSUE TITLE
Alerts are not triggered

### ISSUE THREAD

**Issue by pawfra** [getsentry/self-hosted#2730]
### Self-Hosted Version

23.11.2

### CPU Architecture

x86_64

### Docker Version

N/A deployed in Kubernetes with cri-o (no docker installed)

### Docker Compose Version

N/A deployed in Kubernetes with cri-o (no docker installed)

### Steps to Reproduce

Alert set up to be triggered on any new events, no filters applied

### Expected Result

alerts triggered when the new new issue/events are coming in to sentry

### Actual Result

No alerts triggered, (in alert section of UI: "Alert not triggered yet",)

**Comment by aldy505** [comment]
When the alerts have met the required conditions, is there any logs emitted from the `web` and `worker` container?

**Comment by pawfra** [comment]
Thank you for quick reply,
Unfortunately I don't see anything related to alerts in web or worker container.
I'm new to sentry and it is a black box to me, I have spent a lot of time trying to figure it out without any success.
The alerts used to work but suddenly they stopped.

**Comment by azaslavsky** [comment]
If you are not seeing any logs at all in those containers, it is very likely that the alerts are not reaching your server. Are you sure that the SDK sending the alerts is configured correctly and sending them to the right URL?

**Comment by pawfra** [comment]
Sorry  I'm new to Sentry so maybe I'm getting it wrong,  my understanding is that the alerts are not sent to Sentry but generated from events that are sent to Sentry, and in my case events are sent to sentry and when I create an alert in Sentry UI I can see in Alert Preview messages that would trigger the alert, but unfortunately no alerts are ever generated, this used to work and now it stopped for unknown reason to me.

**Comment by hubertdeng123** [comment]
This should be a major part of the Sentry product, and it should work. It looks like you're not using the official docker compose version of self-hosted, so we can't offer much support here for you.
