### ISSUE TITLE
CSRF token validation error

### ISSUE THREAD

**Issue by trmjoa** [getsentry/self-hosted#2735]
### Self-Hosted Version

latest

### CPU Architecture

x86_64

### Docker Version

24.0.7

### Docker Compose Version

2.21.0

### Steps to Reproduce

I have installed the self hosted version as described.
In addition I have a nginx proxy installed on the host routing traffic to the nginx container mapped on 0.0.0.0:9000.

Host nginx config:

```
    server {
        listen       443 ssl;
        server_name  sentry.mycompany.com;

        ssl_certificate      /etc/pki/nginx/server.crt;
        ssl_certificate_key  /etc/pki/nginx/server.key;

    #    ssl_session_cache    shared:SSL:1m;
    #    ssl_session_timeout  5m;

    #    ssl_ciphers  HIGH:!aNULL:!MD5;
    #    ssl_prefer_server_ciphers  on;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        location / {
                proxy_pass http://0.0.0.0:9000;
        }
    }
```

sentry/config.yml is changed to:
```
# The URL prefix in which Sentry is accessible
system.url-prefix: 'https://sentry.mycompany.com'
#system.internal-url-prefix: 'http://web:9000'
```
sentry.config.py is changed to:
```
# If you're using a reverse SSL proxy, you should enable the X-Forwarded-Proto
# header and enable the settings below

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
#SOCIAL_AUTH_REDIRECT_IS_HTTPS = True
```

Go to the login page and try to log in.

### Expected Result

I would expect to be able to log in

### Actual Result

When trying to log in for the first time I get the following error message:

`sentry-self-hosted-web-1  | 00:13:15 [WARNING] django.security.csrf: Forbidden (Origin checking failed - https://sentry.mycompany.com does not match any trusted origins.): /auth/login/sentry/ (status_code=403 request=<WSGIRequest: POST '/auth/login/sentry/'>)`

I assume that its some sort of configuration error which causes this.

Are there some way of increasing the logging and get the system to display the trusted origins. This will give me a good indication of where to start the debugging.

**Comment by Herz3h** [comment]
Same issue here. Only I used traefik as a reverse proxy (and so added traefik labels to the nginx service, used to work well before).

I tried a fresh install and changing setting the config.yml similar to yours but problem remains.

**Comment by trmjoa** [comment]
To solve it temporarily (we are in a phase where we are testing out sentry). I applied the following patches:

```
[self-hosted]$ git diff nginx/nginx.conf
diff --git a/nginx/nginx.conf b/nginx/nginx.conf
index 8c29740..e2fab87 100644
--- a/nginx/nginx.conf
+++ b/nginx/nginx.conf
@@ -65,7 +65,10 @@ http {
        }

        server {
-               listen 80;
+               #listen 80;
+               listen 443 ssl;
+               ssl_certificate      server.crt;
+               ssl_certificate_key  server.key;

                location /api/store/ {
                        proxy_pass http://relay;
```

```
[self-hosted]$ git diff docker-compose.yml
diff --git a/docker-compose.yml b/docker-compose.yml
index d026fb8..896365f 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -404,7 +404,7 @@ services:
   nginx:
     <<: *restart_policy
     ports:
-      - "$SENTRY_BIND:80/tcp"
+      - "$SENTRY_BIND:443/tcp"
     image: "nginx:1.25.2-alpine"
     volumes:
       - type: bind
```

```
[self-hosted]$ git diff .env
diff --git a/.env b/.env
index 55fa433..1deb0e7 100644
--- a/.env
+++ b/.env
@@ -2,7 +2,7 @@ COMPOSE_PROJECT_NAME=sentry-self-hosted
 SENTRY_EVENT_RETENTION_DAYS=90
 # You can either use a port number or an IP:PORT combo for SENTRY_BIND
 # See https://docs.docker.com/compose/compose-file/#ports for more
-SENTRY_BIND=9000
+SENTRY_BIND="172.27.14.109:443"
 # Set SENTRY_MAIL_HOST to a valid FQDN (host/domain name) to be able to send emails!
 # SENTRY_MAIL_HOST=example.com
 SENTRY_IMAGE=getsentry/sentry:nightly
 ```
 
 It will bind the provided nginx container to port 443 on the host and use it to terminate ssl. It is explicitly advised **against** this in the docs, so I would not recommend it for production, but for me, right now it solves my problem. Remember to also change the ssl settings in the configuration files as described in the docs

**Comment by Herz3h** [comment]
Thank you for the provided steps. However I personally had to revert to latest 23.12.3 (v24 had the csrf token issue)

**Comment by fchienvuhoang** [comment]
same issue.

**Comment by nikooo777** [comment]
same here on a brand new install with caddy as reverse proxy. (ubuntu 22.04)

**Comment by hubertdeng123** [comment]
We have seen the same issue. What happens if you try setting `CSRF_TRUSTED_ORIGINS = ["https://your-site.com"]?

**Comment by hubertdeng123** [comment]
I believe this is now fixed on the latest version of sentry. I'll look to cut a release for this.
