### ISSUE TITLE
Upgrade clickhouse image to latest

### ISSUE THREAD

**Issue by franco-gondi** [getsentry/self-hosted#2741]
Latest clickhouse image has built in arm support. Using it would render useless the script that checks the platform.

**Comment by hubertdeng123** [comment]
We need to ensure that all of our services can run properly using later versions of clickhouse first. We have an internal team dedicated towards upgrading our clickhouse clusters right now so we're simply following along with what is run in SaaS. cc @MeredithAnya

**Comment by chadwhitacre** [comment]
@hubertdeng123 Should we fold this issue into #1385?

**Comment by hubertdeng123** [comment]
Yes, let's do that.
