### ISSUE TITLE
Upgrade from Sentry 21.4.1 to 21.5.0 fails

### ISSUE THREAD

**Issue by stumbaumr** [getsentry/self-hosted#2742]
### Self-Hosted Version

21.4.1

### CPU Architecture

x86_64

### Docker Version

24.0.1

### Docker Compose Version

v2.24.3

### Steps to Reproduce

Starting with on-premise Sentry 21.4.1, git clone self-hosted, git fetch && git checkout "21.5.0" (like described in "Hard Stops" in https://develop.sentry.dev/self-hosted/releases/ ).
Then ./install.sh

Then remove that docker-compose version check...

Then ./install.sh

Then see
Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/main/binary-amd64/Packages  404

and realize stretch has no directory under http://security.debian.org/debian-security/dists anymore...

### Expected Result

Upgrade from a almost 3 year old installation still should work.
Containers should not be build on-premises.....

### Actual Result

root@sentry01(dc1.prd):~/getsentry/self-hosted (git:(21.5.0))# ./install.sh
▶ Parsing command line ...

▶ Setting up error handling ...

▶ Checking minimum requirements ...

▶ Creating volumes for persistent storage ...
Created sentry-clickhouse.
Created sentry-data.
Created sentry-kafka.
Created sentry-postgres.
Created sentry-redis.
Created sentry-symbolicator.
Created sentry-zookeeper.

▶ Ensuring files from examples ...
../sentry/sentry.conf.py already exists, skipped creation.
../sentry/config.yml already exists, skipped creation.
../symbolicator/config.yml already exists, skipped creation.
../sentry/requirements.txt already exists, skipped creation.

▶ Generating secret key ...

▶ Replacing TSDB ...

▶ Fetching and updating Docker images ...
option '--no-ansi' is DEPRECATED ! Please use '--ansi' instead.
21.5.0: Pulling from getsentry/sentry
Digest: sha256:dd042ef4a56476a4c3a1964335dce281130f5bdf2d4fcc1f8dcfaab731e5d702
Status: Image is up to date for getsentry/sentry:21.5.0
docker.io/getsentry/sentry:21.5.0

▶ Building and tagging Docker images ...

option '--no-ansi' is DEPRECATED ! Please use '--ansi' instead.
#0 building with "default" instance using docker driver

#1 [snuba-cleanup internal] load build definition from Dockerfile
#1 transferring dockerfile: 243B done
#1 ...

#2 [symbolicator-cleanup internal] load .dockerignore
#2 transferring context: 2B done
#2 DONE 0.5s

#3 [sentry-cleanup internal] load build definition from Dockerfile
#3 transferring dockerfile: 243B done
#3 DONE 0.5s

#4 [sentry-cleanup internal] load .dockerignore
#4 transferring context: 2B done
#4 DONE 0.5s

#5 [symbolicator-cleanup internal] load build definition from Dockerfile
#5 transferring dockerfile: 243B done
#5 DONE 0.5s

#1 [snuba-cleanup internal] load build definition from Dockerfile
#1 DONE 0.5s

#6 [snuba-transactions-cleanup internal] load build definition from Dockerfile
#6 transferring dockerfile: 243B done
#6 DONE 0.6s

#7 [snuba-transactions-cleanup internal] load .dockerignore
#7 transferring context: 2B done
#7 DONE 0.6s

#8 [snuba-cleanup internal] load .dockerignore
#8 transferring context: 2B done
#8 DONE 0.6s

#9 [symbolicator-cleanup internal] load metadata for docker.io/getsentry/symbolicator:0.3.3
#9 DONE 0.0s

#10 [sentry-cleanup internal] load metadata for docker.io/getsentry/sentry:21.5.0
#10 DONE 0.0s

#11 [sentry-cleanup 1/3] FROM docker.io/getsentry/sentry:21.5.0
#11 CACHED

#12 [symbolicator-cleanup 1/3] FROM docker.io/getsentry/symbolicator:0.3.3
#12 CACHED

#13 [snuba-cleanup internal] load metadata for docker.io/getsentry/snuba:21.5.0
#13 DONE 0.0s

#14 [snuba-cleanup 1/3] FROM docker.io/getsentry/snuba:21.5.0
#14 CACHED

#15 [snuba-transactions-cleanup internal] load build context
#15 transferring context: 35B done
#15 ...

#16 [sentry-cleanup internal] load build context
#16 transferring context: 35B done
#16 DONE 0.2s

#15 [snuba-transactions-cleanup internal] load build context
#15 DONE 0.3s

#17 [symbolicator-cleanup internal] load build context
#17 transferring context: 35B done
#17 DONE 0.3s

#18 [snuba-cleanup internal] load build context
#18 transferring context: 35B done
#18 DONE 0.3s

#19 [snuba-cleanup 2/3] RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
#19 0.943 Get:1 http://deb.debian.org/debian buster InRelease [122 kB]
#19 0.943 Get:2 http://security.debian.org/debian-security buster/updates InRelease [34.8 kB]
#19 0.954 Get:3 http://deb.debian.org/debian buster-updates InRelease [56.6 kB]
#19 1.056 Get:4 http://security.debian.org/debian-security buster/updates/main amd64 Packages [582 kB]
#19 1.169 Get:5 http://deb.debian.org/debian buster/main amd64 Packages [7909 kB]
#19 1.312 Get:6 http://deb.debian.org/debian buster-updates/main amd64 Packages [8788 B]
#19 ...

#20 [symbolicator-cleanup 2/3] RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
#20 0.948 Ign:1 http://security.debian.org/debian-security stretch/updates InRelease
#20 0.950 Ign:2 http://security.debian.org/debian-security stretch/updates Release
#20 0.950 Ign:3 http://deb.debian.org/debian stretch InRelease
#20 0.951 Ign:4 http://deb.debian.org/debian stretch-updates InRelease
#20 0.952 Ign:5 http://security.debian.org/debian-security stretch/updates/main all Packages
#20 0.953 Ign:6 http://deb.debian.org/debian stretch Release
#20 0.955 Ign:7 http://deb.debian.org/debian stretch-updates Release
#20 0.955 Ign:8 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
#20 0.957 Ign:9 http://deb.debian.org/debian stretch/main amd64 Packages
#20 0.957 Ign:5 http://security.debian.org/debian-security stretch/updates/main all Packages
#20 0.958 Ign:10 http://deb.debian.org/debian stretch/main all Packages
#20 0.959 Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
#20 0.959 Ign:8 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
#20 0.961 Ign:5 http://security.debian.org/debian-security stretch/updates/main all Packages
#20 0.963 Ign:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
#20 0.965 Ign:9 http://deb.debian.org/debian stretch/main amd64 Packages
#20 0.967 Ign:10 http://deb.debian.org/debian stretch/main all Packages
#20 0.971 Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
#20 0.973 Ign:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
#20 0.973 Ign:8 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
#20 0.975 Ign:9 http://deb.debian.org/debian stretch/main amd64 Packages
#20 0.976 Ign:5 http://security.debian.org/debian-security stretch/updates/main all Packages
#20 0.976 Ign:10 http://deb.debian.org/debian stretch/main all Packages
#20 0.977 Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
#20 0.979 Ign:8 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
#20 0.980 Ign:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
#20 0.981 Ign:5 http://security.debian.org/debian-security stretch/updates/main all Packages
#20 0.982 Ign:9 http://deb.debian.org/debian stretch/main amd64 Packages
#20 0.983 Ign:8 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
#20 0.983 Ign:10 http://deb.debian.org/debian stretch/main all Packages
#20 0.984 Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
#20 0.985 Ign:5 http://security.debian.org/debian-security stretch/updates/main all Packages
#20 0.986 Ign:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
#20 0.987 Ign:9 http://deb.debian.org/debian stretch/main amd64 Packages
#20 0.988 Err:8 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
#20 0.988   404  Not Found [IP: 151.101.130.132 80]
#20 0.989 Ign:10 http://deb.debian.org/debian stretch/main all Packages
#20 0.990 Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
#20 0.992 Ign:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
#20 0.994 Err:9 http://deb.debian.org/debian stretch/main amd64 Packages
#20 0.994   404  Not Found
#20 0.996 Ign:10 http://deb.debian.org/debian stretch/main all Packages
#20 0.997 Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
#20 0.998 Err:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
#20 0.998   404  Not Found
#20 1.002 Reading package lists...
#20 1.010 W: The repository 'http://security.debian.org/debian-security stretch/updates Release' does not have a Release file.
#20 1.010 W: The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file.
#20 1.010 W: The repository 'http://deb.debian.org/debian stretch-updates Release' does not have a Release file.
#20 1.010 E: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/main/binary-amd64/Packages  404  Not Found [IP: 151.101.130.132 80]
#20 1.010 E: Failed to fetch http://deb.debian.org/debian/dists/stretch/main/binary-amd64/Packages  404  Not Found
#20 1.010 E: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/main/binary-amd64/Packages  404  Not Found
#20 1.010 E: Some index files failed to download. They have been ignored, or old ones used instead.
#20 ERROR: process "/bin/sh -c apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*" did not complete successfully: exit code: 100

#19 [snuba-transactions-cleanup 2/3] RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
#19 CANCELED

#21 [sentry-cleanup 2/3] RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
#21 0.850 Get:1 http://deb.debian.org/debian buster InRelease [122 kB]
#21 0.850 Get:2 http://security.debian.org/debian-security buster/updates InRelease [34.8 kB]
#21 0.859 Get:3 http://deb.debian.org/debian buster-updates InRelease [56.6 kB]
#21 0.964 Get:4 http://security.debian.org/debian-security buster/updates/main amd64 Packages [582 kB]
#21 1.109 Get:5 http://deb.debian.org/debian buster/main amd64 Packages [7909 kB]
#21 1.210 Get:6 http://deb.debian.org/debian buster-updates/main amd64 Packages [8788 B]
#21 CANCELED
------
 > [symbolicator-cleanup 2/3] RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*:
0.998 Err:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
0.998   404  Not Found
1.002 Reading package lists...
1.010 W: The repository 'http://security.debian.org/debian-security stretch/updates Release' does not have a Release file.
1.010 W: The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file.
1.010 W: The repository 'http://deb.debian.org/debian stretch-updates Release' does not have a Release file.
1.010 E: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/main/binary-amd64/Packages  404  Not Found [IP: 151.101.130.132 80]
1.010 E: Failed to fetch http://deb.debian.org/debian/dists/stretch/main/binary-amd64/Packages  404  Not Found
1.010 E: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/main/binary-amd64/Packages  404  Not Found
1.010 E: Some index files failed to download. They have been ignored, or old ones used instead.
------
failed to solve: process "/bin/sh -c apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*" did not complete successfully: exit code: 100
An error occurred, caught SIGERR on line 4
Cleaning up...

**Comment by stumbaumr** [comment]
Thanks @aldy505!
So yes, removing those cleanup containers got the installation from 21.4.1 via 21.5.0 to 21.6.3.

Next step is 23.6.2:
git checkout version and without removing the docker-compose version check directly started install.sh.

Now the PostGre Upgrade from version 9.6 to 14 fails.
```
Upgrade Complete
----------------
Optimizer statistics are not transferred by pg_upgrade.
Once you start the new server, consider running:
    /usr/lib/postgresql/14/bin/vacuumdb --all --analyze-in-stages

Running this script will delete the old cluster's data files:
    ./delete_old_cluster.sh
Error response from daemon: remove sentry-postgres: volume is in use - [b3cac55103c7ad23c0a90309efb046e5fe7d8e53f8420860e29978609d99915c]
Error in install/upgrade-postgres.sh:12.
'docker volume rm sentry-postgres' exited with status 1
-> ./install.sh:main:33
--> install/upgrade-postgres.sh:source:12

Looks like you've already sent this error to us, we're on it :)
```

But I do like that last sentence...

**Comment by stumbaumr** [comment]
Had to manually remove that old "sentry_onpremise-postgres-1" container...

**Comment by stumbaumr** [comment]
So the further upgrade to 24.1.0 went the standard way. But now SAML2 login does not work...

**Comment by aldy505** [comment]
Okay, since this is pretty much resolved and the new issue is on SAML2 integration, I'm going to close this one.
