### ISSUE TITLE
Release 24.1.1 - container names changed

### ISSUE THREAD

**Issue by fliespl** [getsentry/self-hosted#2752]
### Body

I have noticed that after upgrade from 24.1.0 that all container names were changed, causing disruption in monitoring using zabbix (down containers + duplicates).

I.e.
`/sentry-self-hosted-kafka_1`
became
`/sentry-self-hosted_kafka_1`

Is this a planned change or something went off?

**Comment by aldy505** [comment]
The container names didn't change. In fact, the container name for that is just "kafka", there are no prefix or separator such as dash or underlines. 

Perhaps it's a problem from your Docker configuration?

**Comment by fliespl** [comment]
Thank you. You were right. Sentry update was done with system update and some long standing docker compose update caused this change.
