### ISSUE TITLE
User Auth Token not showing

### ISSUE THREAD

**Issue by darkfortressAU** [getsentry/self-hosted#2760]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

1. Open UI screen to generate User Auth token
2. Set any permission option
3. Generate token

### Expected Result

Token is created and shown in the UI for the user to copy

### Actual Result

UI times out waiting on the fetch request, and simply does nothing apart from drop the loader spinner.
Token is created in the backend and visible in the list however it can not be seen or copied.

### Product Area

Settings - Auth

### Version

24.1.0

**Comment by hubertdeng123** [comment]
Sure, those nginx settings should go in your `nginx.conf` file. Please let me know if that helps at all here.

**Comment by dannyxu2015** [comment]
> Sure, those nginx settings should go in your `nginx.conf` file. Please let me know if that helps at all here.

I found same issue and after change the nginx config, same issue.
Got following log: 
`11:26:31 [INFO] sentry.security: user.api-token-generated (ip_address='192.168.2.16' user_id=1 actor_id=1)`

**Comment by Set3007** [comment]
Hello,
Got this issue on orga level Auth token creation. Because of lot of email was needed to be send, then the Relay http.timeout parameter was too low per default. Increase it did fix the issue.
