### ISSUE TITLE
GitLab Integration Problem

### ISSUE THREAD

**Issue by alexandraveres7** [getsentry/self-hosted#2768]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

1. Deploy Sentry in our Kubernetes cluster (all good, all pods running)
2. Sign in to sentry via browser
3. Go to Settings -> Integration and do the GitLab Integration
4. Activate Error Tracking from GitLab project
5. Commit & push on the respective GitLab project

### Expected Result

Event appears on Sentry issues dashboard

### Actual Result

No issues or events are shown in issues Sentry

### Product Area

Issues

### Version

23.11.2

**Comment by azaslavsky** [comment]
Hi! This repository only offers support for setups using docker-compose - Kubernetes is explicitly out of scope. It is possible that something in your k8s config is swallowing these messages. Sorry about that!

**Comment by alexandraveres7** [comment]
Oh I see :( thank you for the quick response!

**Comment by alexandraveres7** [comment]
Got it working by exposing sentry-relay port to our istio and then sending events to https://{key}@sentry-relay.syneto.eu/.
