### ISSUE TITLE
django.request: Not Found: /api/0/organizations/sentry/issues/3/events/recommended/ (status_code=404 request=<WSGIRequest: GET '/api/0/organizations/sentry/issues/3/events/recommended/?collapse=fullRelease'>)

### ISSUE THREAD

**Issue by ggbondoh** [getsentry/self-hosted#2770]
### Self-Hosted Version

24.1.0

### CPU Architecture

x86_64

### Docker Version

23.0.0

### Docker Compose Version

2.23.0

### Steps to Reproduce

1.issues list 
2.
![image](https://github.com/getsentry/self-hosted/assets/152591053/15267bbd-4e0b-4524-89e5-13bbfffb04d8)

### Expected Result

1

### Actual Result

1

**Comment by azaslavsky** [comment]
Do you have any error logs in your `web` container when you try to make this request?
