### ISSUE TITLE
Drastic drop in high frequency alerts

### ISSUE THREAD

**Issue by boxinegmbh** [getsentry/self-hosted#2771]
### Self-Hosted Version

24.1.1

### CPU Architecture

x86_64

### Docker Version

25.0.0

### Docker Compose Version

1.29.2

### Steps to Reproduce

Upgrade from 23.3.1 to 24.1.1
Full docker volume backup was done
Restore was successful

### Expected Result

Uninterrupted functionality of the configured alerts.

### Actual Result

After upgrade, steep decline in triggered alerts.
Tried setting up the alerting behaviour again but no change observed
![Screenshot from 2024-02-06 16-35-42](https://github.com/getsentry/self-hosted/assets/57713631/90d9ad34-2104-4ea9-bf63-1f594ab93694)

Alert settings
![Screenshot from 2024-02-06 17-17-25](https://github.com/getsentry/self-hosted/assets/57713631/dec5c7b6-b12a-456e-983a-c625f934b8ec)

**Comment by azaslavsky** [comment]
Did you do the hard stop at 23.6.2 when upgrading?

**Comment by boxinegmbh** [comment]
We upgraded from v23.3.1 to v23.4.0 to manage the postgres database upgrade
Then v23.4.0 to v23.9.1 and did the full docker volume backup
Then v23.9.1 to v23.11.1 used hardware with recommended requirements
Finally v23.11.1 to v24.1.1 when we saw this issue
Performed the Recovery steps suggested in the docs https://develop.sentry.dev/self-hosted/troubleshooting/#recovery
We did not perform the nuclear option since we wanted to recover all issues with no/minimal data loss
What exactly is the Hard stop?

**Comment by hubertdeng123** [comment]
A hard stop is a version of self-hosted Sentry that must be upgraded to before continuing. Are there any logs in your web container that might be able to tell us what might be going on? Looks like alerts are not being triggered.

**Comment by boxinegmbh** [comment]
After investigation, seems like sentry was amplifying the impact of errors (impacting 50% of sessions), after the upgrade the drastic drop is observed. 
The number of errors did not drastically change before and after upgrade.
Current assumption is the alerts based on the rate of sessions was wrong before upgrade to v24.1.1
