### ISSUE TITLE
SSO users getting multiple/erroneous email addresses after export/import

### ISSUE THREAD

**Issue by structurefall** [getsentry/self-hosted#2772]
### Self-Hosted Version

24.1.0

### CPU Architecture

x86_64

### Docker Version

25.0.2

### Docker Compose Version

2.24.5

### Steps to Reproduce

1. Run `sentry export` from old screwed up instance
2. Run `sentry import` on new instance
3. Duplicate Okta `config` column from old instance's `sentry_authprovider` table

### Expected Result

User emails should match

### Actual Result

You may recall that I previously reported [this](https://github.com/getsentry/self-hosted/issues/2392) issue, which was never fully resolved. I completely abandoned that installation because the database was apparently unsalvageable and built a new one from scratch, however I used the `sentry export` and `import` functions to retain some key data like DSNs. That worked perfectly and the new installation is great, but some users are reporting seeing their accounts associated with two email addresses, one of which belongs to another user.

We are using Okta for authentication. We don't have direct access to our Okta configuration, so (and this is almost certainly the source of the issue) we duplicated the config column from sentry_authprovider from our old installation.

I poked around a bit with the complaining users in the DB and found this:

```
postgres=# select * from sentry_useremail where email = 'user1@domain.com';
 id  |          email           |         validation_hash          |        date_hash_added        | is_verified | user_id
-----+--------------------------+----------------------------------+-------------------------------+-------------+---------
 107 | user1@domain.com | X5I5evnv0CrvIJWLW3zyZdB0Rh0l4YZW | 2024-02-01 23:12:55.189279+00 | f           |     107
 123 | user1@domain.com |                                  | 2023-04-25 19:26:55.989+00    | t           |       7
(2 rows)

postgres=# select * from sentry_useremail where user_id = 7;
 id  |          email           |         validation_hash          |        date_hash_added        | is_verified | user_id
-----+--------------------------+----------------------------------+-------------------------------+-------------+---------
   7 | user2@domain.com  | dkCGtPgrXYhtZOeSohUN02dkBASaL9Ra | 2024-02-01 23:12:54.182181+00 | f           |       7
 123 | user1@domain.com |                                  | 2023-04-25 19:26:55.989+00    | t           |       7
(2 rows)
```

Fortunately, we don't have much in the way of detailed permissions or groups, our users are basically in one big bucket, so dropping all existing user data wouldn't be a big problem.

If the answer is "drop all data from sentry_useremail" that's totally fine, but I want to make sure that doesn't disrupt access otherwise. Can you confirm?

**Comment by azaslavsky** [comment]
For a given user that has duplicate email address, what does their `sentry.user` and `sentry.useremail` model look like in the backup you imported from? Given you example, for `user_id == 7`, what is that user's `username`? Given that `username`, can you look back into the `export.json` file you imported, find the `sentry.user` model associated with that `username` (note that the `id` might be different!), and all `sentry.useremail` entries associated with that `sentry.user`? In particular, does the `email` field on the `sentry.user` model you find match the `email` on the `sentry.useremail` pointing to that model's id?

What I suspect happened is that the `sentry.useremail` wires got crossed somehow (probably a bug somewhere). So when users were reloaded, new emails were generated for all of them.

Also: is this causing any issues for you (ie, Okta doesn't work)? Or is this just a bit annoying, and users can just delete the emails if they'd like?

**Comment by structurefall** [comment]
So, first of all I just tried out the steps to set a new primary email (using my personal email on a totally different domain) so I could ask my affected users to try it, and that resulted in an additional email showing up in _my_ account- I now have the Okta one, which is "FirstLast@domain.com" and a new one that's "firstlast@domain.com" (no capitals) that is unverified, and the "resend verification" button wouldn't work. Additionally, the new non-capital one is now set as my primary, and trying to promote the other one to primary didn't work. 

I deleted the now non-primary "FirstLast" one, logged out, and logged back in, and the resend verification button now works and everything is fine with my account.

That doesn't really solve anything, but it does make me suspect that there's some garbling of upper/lower case in emails either on Okta's side or Sentry's.

All that follows is for one specific user. Here's the `sentry.user` model from export.json:
```{
  "model": "sentry.user",
  "pk": 209,
  "fields": {
    "password": "",
    "last_login": "2023-06-21T18:55:37.012Z",
    "username": "8587fb4a0ba44819a124d60f64447089",
    "name": "First Last",
    "email": "First.Last@domain.com",
    "is_staff": false,
    "is_active": true,
    "is_superuser": false,
    "is_managed": false,
    "is_sentry_app": null,
    "is_password_expired": false,
    "last_password_change": null,
    "flags": "0",
    "session_nonce": null,
    "date_joined": "2023-04-25T19:26:55.975Z",
    "last_active": "2023-06-21T18:55:37.128Z",
    "avatar_type": 0,
    "avatar_url": null
  }
}
```
They have one `sentry.email` entry and one `sentry.useremail` entry:
```
{
  "model": "sentry.email",
  "pk": 226,
  "fields": {
    "email": "First.Last@domain.com",
    "date_added": "2023-04-25T19:26:55.992Z"
  }
},
```
```
{
  "model": "sentry.useremail",
  "pk": 228,
  "fields": {
    "user": [
      "8587fb4a0ba44819a124d60f64447089"
    ],
    "email": "First.Last@domain.com",
    "validation_hash": "",
    "date_hash_added": "2023-04-25T19:26:55.989Z",
    "is_verified": true
  }
},
```
They have one `sentry.organizationmember` entry:
```
{
  "model": "sentry.organizationmember",
  "pk": 206,
  "fields": {
    "organization": 1,
    "user_id": 209,
    "email": null,
    "role": "member",
    "flags": "1",
    "token": null,
    "date_added": "2023-04-25T19:26:57.270Z",
    "token_expires_at": null,
    "has_global_access": true,
    "inviter_id": null,
    "invite_status": 0,
    "type": 50,
    "user_is_active": true,
    "user_email": "First.Last@domain.com"
  }
},
```
Their "username" hash also appears in this `sentry.authidentity`:
```
{
  "model": "sentry.authidentity",
  "pk": 107,
  "fields": {
    "user": [
      "8587fb4a0ba44819a124d60f64447089"
    ],
    "auth_provider": 1,
    "ident": "00u1g5pucjbCsF2ZM1d8",
    "data": {},
    "last_verified": "2024-01-31T22:43:00.784Z",
    "last_synced": "2024-01-31T22:43:00.784Z",
    "date_added": "2023-04-25T19:26:55.999Z"
  }
},
```

The user whose email they're also seeing has exactly one sentry.user entry and nothing else at all:
```
{
  "model": "sentry.user",
  "pk": 107,
  "fields": {
    "password": "",
    "last_login": "2021-10-13T23:45:34.026Z",
    "username": "79ce9b4f7e18438292016b408e5fcd35",
    "name": "Different Guy",
    "email": "Different.Guy@domain.com",
    "is_staff": false,
    "is_active": true,
    "is_superuser": false,
    "is_managed": false,
    "is_sentry_app": null,
    "is_password_expired": false,
    "last_password_change": null,
    "flags": "0",
    "session_nonce": null,
    "date_joined": "2021-07-12T16:58:10.359Z",
    "last_active": "2021-10-22T17:45:22.483Z",
    "avatar_type": 0,
    "avatar_url": null
  }
},
```
That user has exactly one `sentry.useremail` entry and no `sentry.email`:
```
{
  "model": "sentry.useremail",
  "pk": 126,
  "fields": {
    "user": [
      "79ce9b4f7e18438292016b408e5fcd35"
    ],
    "email": "Different.Guy@domain.com",
    "validation_hash": "",
    "date_hash_added": "2021-07-12T16:58:10.374Z",
    "is_verified": true
  }
},
```
...and that user has this `sentry.authidentity` entry:
```
{
  "model": "sentry.authidentity",
  "pk": 5,
  "fields": {
    "user": [
      "79ce9b4f7e18438292016b408e5fcd35"
    ],
    "auth_provider": 1,
    "ident": "00u1iy5h44cyPBzWp1d8",
    "data": {},
    "last_verified": "2024-01-31T22:43:00.135Z",
    "last_synced": "2024-01-31T22:43:00.135Z",
    "date_added": "2021-07-12T16:58:10.383Z"
  }
},
```

...so that's everything there. The emails do appear to match, and I don't see anything in particular that would associate these two users with each other, but I suspect that we shouldn't have both `sentry.email` AND `sentry.useremail`, so that could be an issue.

The user who is currently experiencing the issue, "First Last" in the above, can't fix their own account because "Different.Guy@domain.com" is currently their primary email, and when they try to make the other one primary they get denied because that email is already associated with another account. Further complicating things, "Different Guy" is no longer with our organization so we can't, for example, have them login to Okta to modify it from that side.

**Comment by azaslavsky** [comment]
One thing I'm noticing is that your backup is formatted in a way that indicates it was done pre-upgrade - as mentioned in the [release notes](https://github.com/getsentry/self-hosted/releases/tag/23.9.1), backups from before 23.9.1 are not compatible with releases after 23.9.1. This is a bit hidden though - I'll update the Breaking Changes doc to include this information.

In terms of fixing your problem: all we need to do is get the correct useremails matched to the right users, right? We could probably do this with direct SQL, by clearing the `useremail` table and repopulating it from the emails in `sentry_authuser`. Your users would need to re-validate their emails though - is this okay?

**Comment by structurefall** [comment]
That is okay, and we can try it, but it looks like I'll need to generate something for the validation hash column. What can I do for that?

**Comment by hubertdeng123** [comment]
@structurefall I think you can generate a random string for that. I believe we're using this funciton here to generate that:
https://github.com/getsentry/sentry/blob/9e90557e6fc0c255bd3fb353fdb5ea17a6f5b507/src/sentry/utils/security/hash.py#L6

**Comment by structurefall** [comment]
Sorry for the delay- we got it!

There was one additional step- I also had to clear `sentry_authidentity`, which left some users tied to the old, incorrect account.

Thanks for your help!
