### ISSUE TITLE
Prototype errors-only Sentry

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/self-hosted#2773]
Sentry has gotten really complex over the years, and we have a hypothesis that a lot of users would be interested in a package of Sentry that was just for errors and therefore much simpler to operate. This ticket is about prototyping what such a package might look like.

**Comment by aldy505** [comment]
Would love to see this. Might benefit from that layered (or generated) sentry.conf.py file -- don't remember where the convo at. But please do not make this more complicated by creating a CLI that generates the docker-compose.yml file. I think it'll be better for people to add required containers on their own.

**Comment by aldy505** [comment]
Closing this since it's implemented already https://github.com/getsentry/self-hosted/pull/3190
