### ISSUE TITLE
Problem with install.sh - upgrade from 23.6.2 to 23.12.1

### ISSUE THREAD

**Issue by francescom-monade** [getsentry/self-hosted#2781]
### Self-Hosted Version

23.6.2

### CPU Architecture

x86_64

### Docker Version

25.0.3, build 4debf41

### Docker Compose Version

2.24.5

### Steps to Reproduce

1. git clone https://github.com/getsentry/self-hosted
2. git checkout tags/23.12.1
3. copy all files to the folder where I want to install sentry
4. add sentry.conf.py, .env and config.yml with my custom configuration
5. sudo ./install.sh

### Expected Result

This should complete the installation without problems, as it did when I migrated it from 23.5.1 to 23.6.2.

### Actual Result

```
> [vroom-cleanup 2/5] RUN if [ -z "${http_proxy}" ]; then echo "Acquire::http::proxy "${http_proxy}";" >> /etc/apt/a>
can't create /etc/apt/apt.conf: nonexistent directory
------
failed to solve: process "/bin/sh -c if [ -z \"${http_proxy}\" ]; then echo \"Acquire::http::proxy \\\"${http_proxy}\>
Error in install/build-docker-images.sh:9.
'$dcb --force-rm "$service"' exited with status 17
-> ./install.sh:main:29
--> install/build-docker-images.sh:source:9
```

**Comment by hubertdeng123** [comment]
Interesting, nothing has been recently changed to update vroom-cleanup. I'm not too sure what might be going on here but perhaps there is a directory permissioning issue?

**Comment by vadim-vin** [comment]
Just for those who forget how to cherry-pick:

`git cherry-pick c3da53d2e76fa1773c2b5135b75344e3a57f6f19`
