### ISSUE TITLE
How to backup Sentry without the event data

### ISSUE THREAD

**Issue by RyuzakiKK** [getsentry/self-hosted#2785]
### Problem Statement

In our setup we want to keep event data for a maximum of 30 days. Using the option `SENTRY_EVENT_RETENTION_DAYS=30` seems to be working as expected.

However we'd also like to create periodical backup snapshots of Sentry to have a disaster recovery plan. The problem is that we'd like exclude event data from those snapshots, to prevent keeping user data in those backups "forever".

As far as I can see the containers that Sentry creates are the following:
- sentry-clickhouse
- sentry-data
- sentry-kafka
- sentry-postgres
- sentry-redis
- sentry-symbolicator
- sentry-zookeeper

From the info I was able to gather, the two containers that store non-event data are sentry-postgres and sentry-data.

With that assumption, I tried to create a snapshot of those two containers, "deleted" the others and re-started Sentry. However, that failed because Sentry complained about zookeeper.

Then I re-tried by including a snapshot of sentry-zookeeper as well and that time it worked.

Are there event data stored in sentry-postgres, sentry-data or sentry-zookeeper? Is it a supported usecase to backup only those three containers and let Sentry re-create the others from scratch?

Alternatively, is there a better way to achieve that? I know about the existence of `/scripts/backup.sh`, but that script expects you to manually stop Sentry before executing it, so unfortunately it's not really something that can be easily/safely automated.

**Comment by hubertdeng123** [comment]
What you can do without taking down your sentry instance is execute a backup command manually. This would involve docker exec'ing into your web container and performing the backup command through the cli.

So, something like this
```
docker compose run -v sentry:/sentry-data/backup --rm -T -e SENTRY_LOG_LEVEL=CRITICAL web export global /sentry-data/backup/backup.json
```

**Comment by hubertdeng123** [comment]
That shouldn't introduce any downtime to your instance.

**Comment by RyuzakiKK** [comment]
Thanks, in theory that should be exactly what we were looking for.

I'll be able to test it next week. For now we can close this issue.
