### ISSUE TITLE
facing issue in git checkout while upgrading to 24.1.1 to 24.1.2

### ISSUE THREAD

**Issue by balaG4046** [getsentry/self-hosted#2802]
### Self-Hosted Version

24.1.1

### CPU Architecture

x86_64

### Docker Version

20.10.25

### Docker Compose Version

2.16.0

### Steps to Reproduce

while upgrading to 24.1.1 to 24.1.2 we are facing issue 

**error: Your local changes to the following files would be overwritten by checkout:
        cron/Dockerfile**

even for 24.2.0 also same issue - kindly help us to resolve the issue. @hubertdeng123 @chad

### Expected Result

it should upgrade to 24.1.2 

### Actual Result

<img width="557" alt="Screenshot 2024-02-19 123712" src="https://github.com/getsentry/self-hosted/assets/148226908/5badf102-da97-4cff-b065-1c69a067cdb4">

**Comment by balaG4046** [comment]
@chadwhitacre @hubertdeng123 - Kindly help me with your suggestion here

**Comment by DarkByteZero** [comment]
This is a normal Git error that you are experiencing. You made custom changes to this file, and git asks if you want to overwrite these. If the changes you have made to the Dockerfile are not relevant, you can do the following.
`git reset --hard`

**Comment by balaG4046** [comment]
Hi 
issue is fixed now for the commit issue,  and we are facing new issue while updating from 24.1.1 to 24.1.2 - please refer the error screenshot,

whether the fix will we release in upcoming versions, however 24.2.0 also we are facing the same issue, Kindly need your suggestion to proceed 

<img width="605" alt="image" src="https://github.com/getsentry/self-hosted/assets/148226908/c0189dd1-9eab-4edf-97fd-14f9721e5112">

Thanks!

**Comment by aldy505** [comment]
Hi @balaG4046 I can't really deduct what your issue is from that clipped log. Can you show us the complete log? There should be a `sentry_install_log...` file on your directory. It's best to put it on a Pastebin or similar.

**Comment by balaG4046** [comment]
Hi @aldy505 
i have attached the logs - kindly check and help us to fix the issue
[sentry_install_log-2024-02-19_14-08-34.txt](https://github.com/getsentry/self-hosted/files/14356973/sentry_install_log-2024-02-19_14-08-34.txt)
[sentry_install_log-2024-02-20_06-58-48.txt](https://github.com/getsentry/self-hosted/files/14356974/sentry_install_log-2024-02-20_06-58-48.txt)

Thanks!

**Comment by aldy505** [comment]
Oh, it's just the Sentry container got a connection lost issue during connecting to the Postgres container. It's probably because a bad hardware on your end. Since the second log file looks like everything is okay, I suppose you are running a normal working Sentry right now?

If you don't have normal working Sentry running, try to check your server disk speed.

**Comment by balaG4046** [comment]
Hi @aldy505 

Thanks for looking in to our issue,

We are using RDS Postgres 13.10, in our Sentry. We have replaced the below variables which was provided in sentry.conf.py

**SENTRY_DB_NAME
SENTRY_DB_USER
SENTRY_DB_PASSWORD
SENTRY_POSTGRES_PORT
SENTRY_POSTGRES_HOST**

Looks like in our log,  it is trying to access default postgress container,

Below Hardware specification for our Sentry Dev Environment, 

Instance type - m6a.4xlarge,  
OS version - amazon Linux 2, 
EBS Volume type - gp2, 
IOPS - 300, 
EBS volume size - 100GB.

Kindly suggest us, what need to be done, if we are using external postgress like RDS in our case.

Thanks!

**Comment by praseeb** [comment]
@aldy505 @BYK 

Will there be any upcoming fix for this issue? the same issue facing while upgrading to 24.2.0 as well from 24.1.1
We are stuck in 24.1.1 version now. Any suggestions.

@balaG4046

**Comment by praseeb** [comment]
@hubertdeng123  @aldy505 @BYK @azaslavsky 

Any new release for this fix coming soon?

**Comment by aldy505** [comment]
> Any new release for this fix coming soon?

@praseeb I'm kind of loss here, what kind of issue are you experiencing right now?

**Comment by praseeb** [comment]
@aldy505  Looking for this ticket solution https://github.com/getsentry/self-hosted/issues/2804

Looks like its closed now. Basically, with non-default Postgresql set-up-and-migrate-database.sh is getting failed.
we were looking for that solution.
Could you please suggest what need to be done.

**Comment by hubertdeng123** [comment]
The fix to support non-default postgres db setups should be released soon. Thanks for your patience

https://github.com/getsentry/self-hosted/pull/2827

**Comment by chadwhitacre** [comment]
#2827 is merged. Are we good here?

**Comment by hubertdeng123** [comment]
Should be, and we've cut a release with the changes.
