### ISSUE TITLE
Setting up notifications in Sentry on-premise for MS teams

### ISSUE THREAD

**Issue by Evgeniy-Izotov** [getsentry/self-hosted#2803]
### Problem Statement

Is it possible to set up notifications in Sentry on-premis for MS Teams and what is the best way to do this? Is integration like Sentry Saas possible?
Thank you!

**Comment by azaslavsky** [comment]
This is currently not supported, but is in the backlog, see: https://github.com/getsentry/self-hosted/issues/2488
