### ISSUE TITLE
Version in footer not updated

### ISSUE THREAD

**Issue by ahbruinsma** [getsentry/self-hosted#2807]
### Self-Hosted Version

24.2.0

### CPU Architecture

x86_64

### Docker Version

25.0.3

### Docker Compose Version

2.24.5

### Steps to Reproduce

Running the selfhosted upgrade steps located here: 

https://develop.sentry.dev/self-hosted/releases/

### Expected Result

Footer should display newest version

### Actual Result

Footer still keeps displaying first installed version (23.12.1) and under Admin - Environment, it's says a upgrade is available

**Comment by azaslavsky** [comment]
If you `cd` into your `self-hosted` repository on the install machine (ie, the repository you run the code from) and run `git rev-parse HEAD`. What is the resulting value? Can you post it here?

**Comment by ahbruinsma** [comment]
Hello,

I did not use a git clone to checkout the sentry project, I downloaded the zip from: https://github.com/getsentry/self-hosted/releases/tag/24.2.0 and did an install from there.

Cheers

**Comment by azaslavsky** [comment]
And you restarted the server?

**Comment by hubertdeng123** [comment]
I am unable to reproduce this on my side. Can you check your .env file to ensure that you are using the 24.2.0 sentry images?

**Comment by ahbruinsma** [comment]
@hubertdeng123 I guess that was the problem. I did a full copy of the new zip but for some reason the .env file was not copied, so it was never really getting upgraded and that's why the version kept being the old one.
