### ISSUE TITLE
webhook cant't work

### ISSUE THREAD

**Issue by Sweet-KK** [getsentry/self-hosted#2809]
### Self-Hosted Version

23.12.1

### CPU Architecture

x86_64

### Docker Version

25.0.2

### Docker Compose Version

2.24.5

### Steps to Reproduce

https://github.com/kaokei/nextjs-webhook

I was using the forwarding service of the above code to receive alerts when testing the plug-in, but I could not receive notifications when there was a problem with the project, only the email was normal, and I tried to close the email

### Expected Result

can receive webhook alerts

### Actual Result

can‘t receive webhook alerts

![image](https://github.com/getsentry/self-hosted/assets/29600932/6886a7b1-b575-42d6-8b44-08de9942ba92)

**Comment by azaslavsky** [comment]
I believe the advice from [this](https://github.com/getsentry/self-hosted/issues/2706#issuecomment-1911242703) comment might apply here as well.

**Comment by Sweet-KK** [comment]
> I believe the advice from [this](https://github.com/getsentry/self-hosted/issues/2706#issuecomment-1911242703) comment might apply here as well.

Yes, Thank you for your help!
