### ISSUE TITLE
Sentry  23.1.0+ support PostgreSQL (14.10+) and Redis ( 6.2+ and 7.x )  

### ISSUE THREAD

**Issue by amitesh2181763** [getsentry/self-hosted#2810]
### Problem Statement

We want to know if we can upgrade our PostgreSQL database and Redis to the below-mentioned version of the sentry application compatible with this version and not face any issues.

**PostgreSQL Version** 14.10 and above
  **Redis Version** 6.2+ and 7.x
**Sentry Application current version:** 23.1.0

**Comment by azaslavsky** [comment]
You are of course welcome to try, but we only guarantee functionality for, and offer support with, Postgres 14.9 and Redis 5.0.14. In particular, Redis' major version bump suggests to me that there will probably be some breaking if you try to go that route.

**Comment by amitesh2181763** [comment]
Thank you for updating and is there any official document where we can see all the compatible version with Sentry application versions.

**Comment by azaslavsky** [comment]
No, we don't maintain a compatibility table. The best way is to run the install script for a given version and run the various `--version` commands on the running containers (sentry-postgres, sentry-redis, etc).
