### ISSUE TITLE
SAML 2.0 Google - app_not_configured_for_user

### ISSUE THREAD

**Issue by NerijusIPR** [getsentry/self-hosted#2812]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### What are you trying to accomplish?

I am trying to setup SAML authentification for my Sentry instance

Docker
23.11.1

### How are you getting stuck?

I get app_not_configured error while setting up SAML (last step)

In Google I've added mapping Primary email -> EmailAddress
ACS: https://sentry.example.com/saml/acs/sentry/
SLS: https://sentry.example.com/saml/sls/sentry/

In Sentry I enter:

Unique ID: EmailAddress
email: EmailAddress

### Where in the product are you?

Settings - Auth

### Version

23.11.1

**Comment by NerijusIPR** [comment]
Hi @azaslavsky ,

The error comes from Google, however I think the problem is with Unique ID parameter. I set it as email address, but seems that Sentry is passing something else.

As about web logs - nothing informative.

**Comment by hubertdeng123** [comment]
Have you modified your `config.yml` file to contain the client id and client secret?
https://develop.sentry.dev/self-hosted/sso/
