### ISSUE TITLE
Release adoption data is not available on self-hosted 

### ISSUE THREAD

**Issue by jayden-liner** [getsentry/self-hosted#2814]
**OS:**
- [ ]  Windows
- [ ]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- []  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.19.0, 5.17.0

**`react-native` version:** 0.70.6

**Are you using Expo?**
- [ ]  Yes
- [x]  No

I am seeing a weird issue, it looks like release adoption data is not available since the 20/12.
We are using React Native, did and did not release in december at all.

Our Sentry instance is self-hosted, and running the latest version. I am seeing both issues and performance metrics for the mobile app.

<img width="2226" alt="Screenshot 2024-02-19 at 2 55 42 PM" src="https://github.com/getsentry/sentry-react-native/assets/102014146/5813154c-c74b-4c6c-8737-4500126774d5">

**Comment by dieter-hofmann-c24** [comment]
Have the same issue, maybe related to 
https://github.com/getsentry/self-hosted/issues/2200

**Comment by dieter-hofmann-c24** [comment]
We use Sentry 23.11.1. As I understood, session where migrated to metrics and my assumption is that the release health feature should work with metrics now.

**Comment by hubertdeng123** [comment]
Are there any logs in your web container that may be helpful? Release health *should* work on metrics platform now, but something may be going wrong.

**Comment by hubertdeng123** [comment]
@jayden-liner @dieter-hofmann-c24 In your sentry.conf.py, are you specifying the metrics backend for `SENTRY_RELEASE_HEALTH` and `SENTRY_RELEASE_MONITOR`?

https://github.com/getsentry/self-hosted/blob/b3d3ce06da1661eca62a5d1fd5112810d6bbd117/sentry/sentry.conf.example.py#L195

**Comment by caseyduquettesc** [comment]
Same issue in 24.3.0. I have set `SENTRY_RELEASE_HEALTH` and `SENTRY_RELEASE_MONITOR`

**Comment by caseyduquettesc** [comment]
We fixed the issue in our setup. The root cause was https://github.com/getsentry/snuba/issues/4897. Setting the sharding key on `metrics_raw_v2_dist` fixed the snuba-metrics-consumer

**Comment by piellick** [comment]
hi,
we are facing a same situation.

Migration to sentry 23.11.2 we lost every statistics related to "release health".

We had missing entries `SENTRY_RELEASE_*` [as above](https://github.com/getsentry/self-hosted/issues/2814#issuecomment-2010491858) .

No `clickhouse storage distributed / sharding key errors` as here https://github.com/getsentry/snuba/issues/4897 on `snuba-metrics-consumer.`

How works metrics health ? Does we need to waits new releases to have statistics and messages on `snuba-metrics-consumer.` ?

thanks eveyones.

**Comment by azaslavsky** [comment]
We've changed the backend metrics consumer, though that was a while ago. How recent was your latest release?
