### ISSUE TITLE
the web page is not working

### ISSUE THREAD

**Issue by lihong22-tal** [getsentry/self-hosted#2819]
### Self-Hosted Version

24.2.0

### CPU Architecture

x86_64

### Docker Version

20.10.12

### Docker Compose Version

2.22.0

### Steps to Reproduce

1.login
2.to the /issues

### Expected Result

the /issues/ page is always loading, but don't show the content

### Actual Result

<img width="1342" alt="QQ20240222-145809@2x" src="https://github.com/getsentry/self-hosted/assets/132347247/edac1d64-ee70-4561-937a-ac0558b429ac">

**Comment by lihong22-tal** [comment]
> Well.. have you disable your adblockers yet?
> 
> Check your browser's network tab, is there any request made to the self-hosted sentry?
> 
> What's your instance's network configuration? How's the resource usage on your server (CPU, RAM, disk I/O), is it full or are there some empty spaces?

I also have the same problem using traceless browsers. Even when changing machines and browsers, I still can't load them. The resources on the server are relatively idle, and the network is also good.

**Comment by hubertdeng123** [comment]
Echoing what @aldy505 suggested, what is displayed in your browser's network tab? Are there any errors that are popping up in logs?

**Comment by r1v0n** [comment]
Facing the same trouble. The console (chrome dev tools) shows an error with loading some chunks
Happens on 24.2.0
The sentry service is behind CloudFlare (proxy enabled)

**Comment by aldy505** [comment]
> Facing the same trouble. The console (chrome dev tools) shows an error with loading some chunks
> 
> Happens on 24.2.0
> 
> The sentry service is behind CloudFlare (proxy enabled)

@r1v0n Hey, can you show me the error logs? Any screenshot of network tab?

**Comment by r1v0n** [comment]
@aldy505 Hey, sure
<img width="1715" alt="image" src="https://github.com/getsentry/self-hosted/assets/35006046/db1152e6-93c5-4a58-be0e-48748bf313eb">

**Comment by r1v0n** [comment]
I have just checked. The issue happens only when CloudFlare is used with DNS proxy mode.

**Comment by r1v0n** [comment]
If I flush the cache on CloudFlare it works until the next page reload

**Comment by hubertdeng123** [comment]
I think this may be an issue from your proxy settings then. I'm not very familiar with your setup but I would look into that

**Comment by r1v0n** [comment]
@hubertdeng123 Thank you!
I have just added a rule on CF to bypass the cache as it's not needed for my deployment.
Can be as a workaround

**Comment by lihong22-tal** [comment]
> Echoing what @aldy505 suggested, what is displayed in your browser's network tab? Are there any errors that are popping up in logs?

<img width="1356" alt="image" src="https://github.com/getsentry/self-hosted/assets/132347247/8e5a1834-e7b1-4ce5-bf53-9539acfb5b2a">
<img width="1430" alt="image" src="https://github.com/getsentry/self-hosted/assets/132347247/65cf8ad2-93d8-4e20-a439-a4965d2b3775">

**Comment by lihong22-tal** [comment]
> @hubertdeng123 Thank you! I have just added a rule on CF to bypass the cache as it's not needed for my deployment. Can be as a workaround My proxy server has no configuration besides basics (TLS, content types, logging...) @lihong22-tal Do you use CF or do you have any caching config?

No，I have not used CF and catching config. The website was fine a few months ago, but later I suddenly couldn't access the issues page after logging in. I reinstalled Sentry and it still didn't work.
