### ISSUE TITLE
Sentry does not accept any issues from application

### ISSUE THREAD

**Issue by ultramaks** [getsentry/self-hosted#2820]
### Self-Hosted Version

24.2.0

### CPU Architecture

x86_64

### Docker Version

Docker version 24.0.7, build afdd53

### Docker Compose Version

Docker Compose version v2.21.0

### Steps to Reproduce

Sentry is installed using install.sh (no any arguments passed during setup)
After installation I have found that I have to change port 9000 to 9100, since 9000 is already takes buy other application
I've tried to replace all 9000 occurrences in settings to 9100. Sentry has started, I have set up node.js project (we use Strapi CMS) but no any events come to Sentry
If we change DSN entry for sentry.io all events go fine there. But if I change it to self-hosted - no any events, though I can see the same output in browser console either I sent errors to cloud or self-hosted
The only thing I see in composer logs is
`entry-self-hosted-relay-1                                         | 2024-02-22T14:56:24.841620Z ERROR relay_server::services::upstream: authentication encountered error error=upstream request returned error 502 Bad Gateway error.sources=[no error details]`
I suspect that there is something wrong in configuration but can't find what exactly. I even tried to stop other app (with 9000 port) and start Sentry with 9000 port but I got the same situation
If I create issues in Sentry (not send from application) it's shown correctly

So my questions

1. what do I need to check and fix to remove the error above?
2. Where (except docker instances) Sentry stores it's configuration? Even after I delete all containers, images and volumes and restart install.sh it does not ask me for Admin creation. After docker compose up I can enter username that I have created on the first install. Can I reinstall it from scratch (setting up an initial admin user) 

### Expected Result

Sentry should accept all issues/errors from application

### Actual Result

No any results in Sentry from the application

**Comment by aldy505** [comment]
I'm suggesting you to reinstall Sentry from scratch. But I'd advise to install it on a dedicated VM (or machine, server, whatever). If port 9000 is used by other application, you should modify two things:

1. Change this one to anything other than 9000:
    https://github.com/getsentry/self-hosted/blob/8d2da229a2264e31790f736f31d2f6c3a31d0c50/.env#L5
2. Uncomment this, and change it to your `hostname:port` combination. If your IP is `192.168.1.2` and your port is `9100`, then it'd be `http://192.168.1.2:9100`.
    https://github.com/getsentry/self-hosted/blob/8d2da229a2264e31790f736f31d2f6c3a31d0c50/sentry/config.example.yml#L82

If there are any other configuration that defines the port `9000`, don't change it.

**Comment by ultramaks** [comment]
> I'm suggesting you to reinstall Sentry from scratch. But I'd advise to install it on a dedicated VM (or machine, server, whatever). If port 9000 is used by other application, you should modify two things:
> 
> 1. Change this one to anything other than 9000:
>    https://github.com/getsentry/self-hosted/blob/8d2da229a2264e31790f736f31d2f6c3a31d0c50/.env#L5
> 2. Uncomment this, and change it to your `hostname:port` combination. If your IP is `192.168.1.2` and your port is `9100`, then it'd be `http://192.168.1.2:9100`.
>    https://github.com/getsentry/self-hosted/blob/8d2da229a2264e31790f736f31d2f6c3a31d0c50/sentry/config.example.yml#L82
> 
> If there are any other configuration that defines the port `9000`, don't change it.

Thanks. I'll try
The question is how to reinstall it from scratch? Is it enough to just remove all containers, images and volumes from docker engine that are part of the sentry? As I said I tried but I was not able to reset the initially created admin account. After reinstall I always had already created user

**Comment by hubertdeng123** [comment]
Are there any logs in your nginx container indicating that the envelope containing the error has been received? What about logs in your web container?
