### ISSUE TITLE
Restoring problems

### ISSUE THREAD

**Issue by stingy64** [getsentry/self-hosted#2828]
### Self-Hosted Version

23.8.0

### CPU Architecture

x86_64

### Docker Version

25.0.3

### Docker Compose Version

2.0.1

### Steps to Reproduce

1. Fresh installation
2. Restoring backup.json using restore.sh

### Expected Result

Restoration should work as it has to.

### Actual Result
Hi there. Hope you doing well.
After restoring the backup file I get the following error.
Note that I restore the backup on the same version that I get it from.

![image](https://github.com/getsentry/self-hosted/assets/138775365/802c5046-0a35-4bb2-ba84-c23770848806)

If I click on the "please click here" link, I will be redirected to the gui.

If I create a new user, It shows me the below error instead:

![image](https://github.com/getsentry/self-hosted/assets/138775365/ced4feed-0201-42dc-b98e-a8c43eb7077a)

Worker logs shows a lot of this kind of error:

`sentry-self-hosted-worker-1                                    | 18:16:57 [WARNING] sentry.errors.events: symbolicate.slow (project_id=4 event_id='80e904f7c30643a388865cedf45e1f35')`

Any help is appreciated.

**Comment by hubertdeng123** [comment]
Could you try upgrading to 23.11.1+? We've greatly improved our backup/restore process since 23.8.0 and wondering if that might resolve your issue.
https://develop.sentry.dev/self-hosted/backup/

**Comment by stingy64** [comment]
> Could you try upgrading to 23.11.1+? We've greatly improved our backup/restore process since 23.8.0 and wondering if that might resolve your issue. https://develop.sentry.dev/self-hosted/backup/

Thank you very much.
I did the upgrading. I managed to fix the errors after the upgrade and now they are gone. but the problem is that the Sentry is not logging any issues any more.
docker compose logs contains some errors like these:

`sentry-self-hosted-relay-1  | 2024-02-28T10:19:29.157931Z ERROR relay_server::services::upstream: authentication encountered error error=upstream request returned error 503 Service Unavailable error.sources=[no error details]`
```
sentry-self-hosted-relay-1                                         | 2024-03-02T06:18:25.079888Z ERROR relay_server::utils::managed_envelope: dropped envelope: internal error tags.project_key="d5996d714b844ec6b9d456cf208aacac" tags.has_attachments=false tags.has_sessions=true tags.has_profiles=false tags.has_transactions=false tags.has_replays=false tags.has_checkins=false tags.event_category=None cached_summary=EnvelopeSummary { event_category: None, attachment_quantity: 0, session_quantity: 1, profile_quantity: 0, replay_quantity: 0, checkin_quantity: 0, secondary_transaction_quantity: 0, has_plain_attachments: false, event_metrics_extracted: false, payload_size: 273 } recomputed_summary=EnvelopeSummary { event_category: None, attachment_quantity: 0, session_quantity: 1, profile_quantity: 0, replay_quantity: 0, checkin_quantity: 0, secondary_transaction_quantity: 0, has_plain_attachments: false, event_metrics_extracted: false, payload_size: 273 }
sentry-self-hosted-relay-1                                         | 2024-03-02T06:18:25.079943Z ERROR relay_server::utils::managed_envelope: dropped envelope: internal error tags.project_key="d5996d714b844ec6b9d456cf208aacac" tags.has_attachments=false tags.has_sessions=true tags.has_profiles=false tags.has_transactions=false tags.has_replays=false tags.has_checkins=false tags.event_category=None cached_summary=EnvelopeSummary { event_category: None, attachment_quantity: 0, session_quantity: 1, profile_quantity: 0, replay_quantity: 0, checkin_quantity: 0, secondary_transaction_quantity: 0, has_plain_attachments: false, event_metrics_extracted: false, payload_size: 303 } recomputed_summary=EnvelopeSummary { event_category: None, attachment_quantity: 0, session_quantity: 1, profile_quantity: 0, replay_quantity: 0, checkin_quantity: 0, secondary_transaction_quantity: 0, has_plain_attachments: false, event_metrics_extracted: false, payload_size: 303 }

```

**Comment by azaslavsky** [comment]
Hmm this is odd. Just to be clear, did you try to reinstall the backup.json from version 23.8.0 on 23.11.1+? Or did you upgrade, then backup, then restore?
