### ISSUE TITLE
After 24.1.1 upgrade: envelope buffer capacity exceeded

### ISSUE THREAD

**Issue by TimofeyMakoveychuk** [getsentry/self-hosted#2836]
### Self-Hosted Version

24.1.1

### CPU Architecture

x86_64

### Docker Version

24.0.2

### Docker Compose Version

2.17.3

### Steps to Reproduce

1. Upgrade Sentry from 24.1.0 to 24.1.1

### Expected Result

Sentry should not drop any incoming errors

### Actual Result

All incoming error events are dropped. Go to /organizations/YOUR_ORGANISATION/stats/ and you will see that all error events are dropped.

We have about 100K events/hour and all are dropped in version 24.1.1. In version 24.1.0 all are either filtered or accepted by Sentry.

The log /docker/relay.log has bursts of the following errors: `The error log ERROR relay_server::endpoints::common: error handling request error=failed to queue envelope error.sources=[envelope buffer capacity exceeded]` and `ERROR relay_server::utils::managed_envelope: dropped envelope: internal error`

We can also observe the following errors in our frontend: `POST /api/* 503 (Service Unavailable)`

**Comment by csvan** [comment]
We have hit the same issue as of 24.1.1, it's also on 24.2.0. Solution on our end is a cron job to restart Sentry every 24h but this is of course not sustainable.

Issue does not seem to be that the system actually overflows the buffer, rather it _just stops processing events altogether, quickly causing it to build up_.

**Comment by csvan** [comment]
It _may_ be related to this, especially if you have high traffic: https://github.com/getsentry/self-hosted/issues/2825

**Comment by hubertdeng123** [comment]
Thanks for filing this. For both your instances, are all errors being dropped? That definitely does not appear to be normal. What does CPU/RAM usage look like?

**Comment by TimofeyMakoveychuk** [comment]
> Thanks for filing this. For both your instances, are all errors being dropped? That definitely does not appear to be normal. What does CPU/RAM usage look like?
Yes, all errors are being dropped.

**Comment by csvan** [comment]
@hubertdeng123 in our case memory goes up by around 20%, and peaks once it starts dropping envelopes from the buffer.

CPU usage goes down to very low levels (around 10% usage), most likely because everything is being dropped and no processing happens.

**Comment by TimofeyMakoveychuk** [comment]
@RexTim Thank you! Removing `proxy_buffering off;` in nginx.conf solved the issue for us :)

**Comment by maxpain** [comment]
The same problem on 24.2.0
`proxy_buffering off;` didn't help

**Comment by maxpain** [comment]
@hubertdeng123 could you please reopen this issue?

**Comment by csvan** [comment]
@maxpain did you _remove_ `proxy_buffering off;` ?

**Comment by maxpain** [comment]
> @maxpain did you _remove_ `proxy_buffering off;` ?

Yes. After 3-4 `docker compose stop && docker compose up -d`, I managed to make Sentry accept events, which is strange. We have a lot of traffic; that may be the reason.

**Comment by csvan** [comment]
Strange, we have not been able to reproduce the issue after removing `proxy_buffering off;`, but will keep a look out

**Comment by RexTim** [comment]
@maxpain if you have any other (nginx) reverse proxies between the public network and your sentry instance, make sure they also have proxy_buffering active and a decent proxy_buffer_size.

**Comment by maxpain** [comment]
> @maxpain if you have any other (nginx) reverse proxies between the public network and your sentry instance, make sure they also have proxy_buffering active and a decent proxy_buffer_size.

I use CloudFlare
