### ISSUE TITLE
Cannot install release version 24.2.0

### ISSUE THREAD

**Issue by axelgenus** [getsentry/self-hosted#2837]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

1. Execute ./install.sh

### Expected Result

Sentry should build and install successfully.

### Actual Result

```
#0 building with "default" instance using docker driver

getsentry/sentry#1 [symbolicator-cleanup internal] load build definition from Dockerfile
getsentry/sentry#1 transferring dockerfile: 469B done
getsentry/sentry#1 DONE 0.0s

getsentry/sentry#2 [symbolicator-cleanup internal] load metadata for docker.io/getsentry/symbolicator:24.2.0
getsentry/sentry#2 ERROR: docker.io/getsentry/symbolicator:24.2.0: not found
------
 > [symbolicator-cleanup internal] load metadata for docker.io/getsentry/symbolicator:24.2.0:
------
failed to solve: getsentry/symbolicator:24.2.0: docker.io/getsentry/symbolicator:24.2.0: not found
Error in install/build-docker-images.sh:9.
'$dcb --force-rm "$service"' exited with status 17
-> ./install.sh:main:30
--> install/build-docker-images.sh:source:9
```

### Product Area

Releases

### Version

24.2.0

**Comment by csvan** [comment]
You may have installed too close to the release, before the image was actually available. We spun up a 24.2.0 instance just now and it works without issue. Can you try again?

**Comment by hubertdeng123** [comment]
This image should now be available. Please try installing again. How did you attempt to install version 24.2.0? Did you manually edit the image versions in your .env file?

**Comment by axelgenus** [comment]
It was an issue with the branch `release/2024.02.00` which now has been deleted and replaced by the usual release tag. The upgrade now works.
