### ISSUE TITLE
AttributeError   sentry.tasks.digests.deliver_digest

### ISSUE THREAD

**Issue by kfkawalec** [getsentry/self-hosted#2838]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

Version 24.1.2 upgraded from 23.12.

### Expected Result

No errors.

### Actual Result

Error:
```
AttributeError: Can't get attribute '__model_unpickle_compat' on <module 'sentry.runner.initializer' from '/usr/local/lib/python3.11/site-packages/sentry/runner/initializer.py'>
```
Job:
```
{
args: [
mail:p:1:IssueOwners::ActiveMembers, 
1708018232.6266365
], 
kwargs: {
__start_time: 1708020298.317617
}, 
task_name: sentry.tasks.digests.deliver_digest
}
```

### Product Area

Unknown

### Version

24.1.2

**Comment by hubertdeng123** [comment]
Hi there, are you using the docker compose version of sentry? How are you upgrading your self-hosted instance?

**Comment by kfkawalec** [comment]
I am using Helm version on bare metal Kubernetes.

**Comment by aldy505** [comment]
You should consult to the Helm chart repository you're using, we can't support you for k8s from here.
