### ISSUE TITLE
Errors correctly link associated Replay, but the Replay shows no errors

### ISSUE THREAD

**Issue by csvan** [getsentry/self-hosted#2839]
### Self-Hosted Version

24.2.0

### CPU Architecture

x86_64

### Docker Version

24.0.7

### Docker Compose Version

2.24.1

### Steps to Reproduce

1. Install vanilla Sentry 24.2.0, with restored soft data from previous instance.
2. Install latest React SDK on client.
3. Start collecting data

### Expected Result

When clicking an error and then the linked Replay, the Replay should show the error in question.

### Actual Result

Not only does the Replay not show any errors, but _no_ Replays have any errors associated with them. 

It should be noted that the system otherwise works fine and errors are correctly processed. The only thing missing is their visibility in the Replay.

<img width="634" alt="Screenshot 2024-02-27 at 21 11 14" src="https://github.com/getsentry/self-hosted/assets/1127729/d2937807-595c-4142-9e0c-c43f842a61f2">

<img width="749" alt="Screenshot 2024-02-27 at 21 11 56" src="https://github.com/getsentry/self-hosted/assets/1127729/9475adc9-e1b2-4d5d-9543-f9e6f6999484">

**Comment by csvan** [comment]
Not sure if related but the logs are absolutely flooded with this:

```
worker-1                                        | 20:28:33 [INFO] sentry.tasks.post_process: handle_owner_assignment.issue_owners_exist (group=13 project=2 organization=1 reason='issue_owners_exist')
worker-1                                        | 20:28:33 [INFO] sentry.tasks.post_process: handle_owner_assignment.issue_owners_exist (group=2 project=2 organization=1 reason='issue_owners_exist')
worker-1                                        | 20:28:33 [INFO] sentry.tasks.post_process: handle_owner_assignment.issue_owners_exist (group=12 project=2 organization=1 reason='issue_owners_exist')
worker-1                                        | 20:28:33 [INFO] sentry.tasks.post_process: handle_owner_assignment.issue_owners_exist (group=25 project=2 organization=1 reason='issue_owners_exist')
worker-1                                        | 20:28:33 [INFO] sentry.tasks.post_process: handle_owner_assignment.issue_owners_exist (group=13 project=2 organization=1 reason='issue_owners_exist')
worker-1                                        | 20:28:33 [INFO] sentry.tasks.post_process: handle_owner_assignment.issue_owners_exist (group=17 project=2 organization=1 reason='issue_owners_exist')
worker-1                                        | 20:28:33 [INFO] sentry.tasks.post_process: handle_owner_assignment.issue_owners_exist (group=2 project=2 organization=1 reason='issue_owners_exist')
worker-1                                        | 20:28:33 [INFO] sentry.tasks.post_process: handle_owner_assignment.issue_owners_exist (group=2 project=2 organization=1 reason='issue_owners_exist')
worker-1                                        | 20:28:33 [INFO] sentry.tasks.post_process: handle_owner_assignment.issue_owners_exist (group=2 project=2 organization=1 reason='issue_owners_exist')
worker-1                                        | 20:28:33 [INFO] sentry.tasks.post_process: handle_owner_assignment.issue_owners_exist (group=3 project=2 organization=1 reason='issue_owners_exist')
```

**Comment by hubertdeng123** [comment]
Hmmm, was this working on the previous version of Sentry? If so, this very well may be a regression, but I'm also wondering if this may have to do with your soft restore that you performed. What was your process for performing the restore?

**Comment by hubertdeng123** [comment]
If that's the case, I don't think this is a problem with your backup/restore process. I wonder if there is some feature flag that might be missing here. Maybe the `organizations:session-replay-event-linking`?

@getsentry/replay Would that be the issue here?
