### ISSUE TITLE
Decompression of Replays frequently fails

### ISSUE THREAD

**Issue by csvan** [getsentry/self-hosted#2840]
### Self-Hosted Version

24.2.0

### CPU Architecture

x86_64

### Docker Version

24.0.7

### Docker Compose Version

2.24.0

### Steps to Reproduce

1. Install vanilla 24.2.0 setup
2. Install latest React SDK on client
3. Collect data

### Expected Result

All Replays should be correctly processed in their entirety

### Actual Result

While replays generally work, this happens often in the logs:

```
ingest-replay-recordings-1                      | Traceback (most recent call last):
ingest-replay-recordings-1                      |   File "/usr/local/lib/python3.11/site-packages/sentry/replays/usecases/ingest/__init__.py", line 197, in recording_post_processor
ingest-replay-recordings-1                      |     decompressed_segment = decompress(segment_bytes)
ingest-replay-recordings-1                      |                            ^^^^^^^^^^^^^^^^^^^^^^^^^
ingest-replay-recordings-1                      |   File "/usr/local/lib/python3.11/site-packages/sentry/replays/usecases/ingest/__init__.py", line 173, in decompress
ingest-replay-recordings-1                      |     return zlib.decompress(data, zlib.MAX_WBITS | 32)
ingest-replay-recordings-1                      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ingest-replay-recordings-1                      | zlib.error: Error -3 while decompressing data: incorrect data check
ingest-replay-recordings-1                      | 20:14:43 [ERROR] root: Failed to parse recording org=1, project=2, replay=33649c06e1ab499f9c5715e48c131a79, segment=0
```

The result is that some replays end up missing altogether, or otherwise contain incomplete data.

**Comment by hubertdeng123** [comment]
Looping in @getsentry/replay. Perhaps you all know more about what might be happening here based on the error message?

**Comment by JoshFerge** [comment]
@csvan could you provide an example payload with the problem?

**Comment by csvan** [comment]
@JoshFerge are you referring to a payload sent by the client itself, or one loaded for viewing in the Sentry GUI?

**Comment by csvan** [comment]
Sorry for the late reply, I will see if I can intercept and extract some of the failing calls
