### ISSUE TITLE
Suddenly our sentry instance came down due to high cpu load 

### ISSUE THREAD

**Issue by balaG4046** [getsentry/self-hosted#2848]
### Self-Hosted Version

24.1.0

### CPU Architecture

x86_64

### Docker Version

20.10.25

### Docker Compose Version

2.16.0

### Steps to Reproduce

Hi team,

We could see that there are some projects are creating a thousands of error events in our sentry due to that sentry application came down.

In order to avoid that we are checking the rate limit options  - Kindly let us know what is the default rate limit that we can set rate limit per project, so that it would not let our CPU usage increase.

And we  also could see that in our server Redis, snuba and Kafka container has consuming high CPU load at that time - to reduce that we came across this below setting  in Redis 

**emory Configuration: set maxmemory-policy to restrict Redis to use that much max memory.
                      docker compose exec redis redis-cli CONFIG SET maxmemory-policy volatile-ttl
                     docker compose exec redis redis-cli CONFIG SET maxmemory 4G**

will the above setting is recommended to proceed on the production sentry  or is there any other cleanup activities is recommeded for kafka and redis part, please help me with the steps , It would really help us. 

@hubertdeng123  @azaslavsky need your valuable suggestion in this case.

Thanks!

### Expected Result

sentry should handle the load 

### Actual Result

Suddenly our sentry instance came down due to high cpu load

**Comment by hubertdeng123** [comment]
What is your total RAM available? There's not much we can do right now, but note that in the 24.3.0 release rust consumers are used for snuba which may decrease this CPU/RAM usage significantly.

**Comment by balaG4046** [comment]
Hi @hubertdeng123 
we have 64.0 GiB of memory in our sentry, kindly let me know is there any default rate limit that we need to set for a project to restrict the users call?  

any process or any configuration setting that we need to apply in kafka or redis  - It would help us to improve the performance need your suggestions 

Note: upgrading 24.3.0 will take some time to test in our preprod since we are having a issues in 24.1.2  & 24.2.0 

Thanks!

**Comment by aldy505** [comment]
> Hi @hubertdeng123 we have 64.0 GiB of memory in our sentry, kindly let me know is there any default rate limit that we need to set for a project to restrict the users call?

Sadly there are no default rate limit. You'll need to set it on your reverse proxy. See https://develop.sentry.dev/self-hosted/reverse-proxy#rate-limiting and scroll down a bit for a few examples.
