### ISSUE TITLE
Sentry throws errors while it should receive errors

### ISSUE THREAD

**Issue by illmaren** [getsentry/self-hosted#2857]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

Install Docker sentry https://hub.docker.com/_/sentry/
Following instructions to connect DSN: https://docs.sentry.io/platforms/php/guides/laravel/

Getting this Report in Sentry Project: user_script:11: Attempt to modify a readonly table script: 094f8735408af273da283389ad983f63977831e8, on @user_script:11.

Clean Docker install following the instructions from the above link.
Server has way more than the minimum Ram needed to run Sentry (64gb available (around 40gb free as of writing this text.) 
Docker commands change as that I added a port and two Enviroment Variables first to access the sentry installation and the variables to use the whole thing with a nginx proxy 

### Expected Result

A Test Report should appear in the Laravel Project.

### Actual Result

A Error in the Sentry Project appears.

### Product Area

Issues

### Version

9.1.2

**Comment by azaslavsky** [comment]
Which version of self-hosted sentry are you using?

I'm also not sure what this means: "A Test Report should appear in the Laravel Project." Did you make a separate project for Laravel, and use that DSN? Or are you pointing the Laravel SDK at your original, default Sentry project?

**Comment by illmaren** [comment]
I use 9.1.2 

I used the following command:
php artisan sentry:publish --dsn=https://examplePublicKey@o0.ingest.sentry.io/0

To add the DSN into the config and .env of Laravel.

BUT even without the Laravel connection I get quite a bit of errors within the sentry project.

**Comment by azaslavsky** [comment]
9.1.2 is very old - I think it's getting close to 5 years at this point. I would not be surprised is something in the SDK changed in some way that works with newer versions but not something that old. What is the oldest version of the Sentry Laravel SDK yo'd be comfortable using? I know various releases added support for newer versions of Laravel - which one are you on?

Just speaking generally, it will be quite difficult for us to debug connection issues on an install this old. Have you considered upgrading?

**Comment by illmaren** [comment]
Oh didn't saw that it was that old, had seen that the repo was deprecated but not that old. Should read since then it was deprecated. As its a fresh install meaned for a new Project environment a newer version is no problem I'll figure out how to do that with docker. 

My Setup is not allowing me a full setup directly on the machine. 
I'll come back to you if I installed a more current version
