### ISSUE TITLE
Deploy sentry with a non independent domain

### ISSUE THREAD

**Issue by theremoon-j** [getsentry/self-hosted#2862]
### Problem Statement

Now I deploy sentry in Intranet with http. My app access Sentry by url like "http://10.252.10.129:9000/organizations/boss-sentry/issues".
My problem is how to access the web with an non independent domain.
Such as my domain is "www.bensen", normally the web should be "http://bensen/organizations/boss-sentry/issues". But "http://bensen" has been used for an other server in different department, so the url actually I want is "http://bensen/sentry".

I have try to set system.url-prefix in sentry/config.yml :
```
system.url-prefix: http://10.252.10.129:9000/sentry
system.internal-url-prefix: 'http://web:9000/sentry'
```

It doesnt work. 

How can I do this?

**Comment by csvan** [comment]
You can't, Sentry needs its own domain and cannot live on a path.

**Comment by hubertdeng123** [comment]
Echoing what was said above, you will need your own domain for this. Sentry cannot live on a path.
