### ISSUE TITLE
cannot visit http://localhost:9000 after docker compose up -d

### ISSUE THREAD

**Issue by Repeg** [getsentry/self-hosted#2863]
### Self-Hosted Version

24.2.0

### CPU Architecture

x86_64

### Docker Version

24.0.5

### Docker Compose Version

2.24.6

### Steps to Reproduce

[+] Running 48/51
 ✔ Container sentry-self-hosted-post-process-forwarder-errors-1                 Start...                                                               48.7s

 ✔ Container sentry-self-hosted-worker-1                                        Started                                                                50.9s

dockerntainer sentry-self-hosted-events-consumer-1                               Started                                                                50.9s

 ✔ Container sentry-self-hosted-subscription-consumer-metrics-1                 Start...                                                               50.7s

 ✔ Container sentry-self-hosted-subscription-consumer-events-1                  Starte...                                                              50.3s

 ✔ Container sentry-self-hosted-billing-metrics-consumer-1                      Started                                                                51.5s
 ⠏ Container sentry-self-hosted-web-1                                           Waiting                                                              1636.0s
 ✔ Container sentry-self-hosted-subscription-consumer-generic-metrics-1         Started                                                                51.1s
 ✔ Container sentry-self-hosted-post-process-forwarder-transactions-1           Started                                                                51.7s
 ✔ Container sentry-self-hosted-ingest-profiles-1                               Started                                                                50.6s
 ✔ Container sentry-self-hosted-ingest-replay-recordings-1                      Started                                                                50.8s
 ✔ Container sentry-self-hosted-attachments-consumer-1                          Started                                                                51.2s
 ✔ Container sentry-self-hosted-generic-metrics-consumer-1                      Started                                                                51.5s
 ✔ Container sentry-self-hosted-ingest-occurrences-1                            Started                                                                51.6s
 ✔ Container sentry-self-hosted-metrics-consumer-1                              Started                                                                51.6s
 ✔ Container sentry-self-hosted-sentry-cleanup-1                                Started                                                                50.0s
 ✔ Container sentry-self-hosted-transactions-consumer-1                         Started                                                                51.2s
 ✔ Container sentry-self-hosted-post-process-forwarder-issue-platform-1         Started                                                                49.4s
 ✔ Container sentry-self-hosted-subscription-consumer-transactions-1            Started                                                                51.5s
 ⠧ Container sentry-self-hosted-relay-1                                         Created                                                              1635.8s
 ⠦ Container sentry-self-hosted-nginx-1                                         Created                                                              1635.7s

### Expected Result

service up

### Actual Result

cannot visit page

**Comment by Repeg** [comment]
im using ubuntu 22.04

**Comment by Repeg** [comment]
and i got this result:

 ✘ Container sentry-self-hosted-web-1                                           Error                                                                2623.3s
 ✔ Container sentry-self-hosted-subscription-consumer-generic-metrics-1         Started                                                                51.1s
 ✔ Container sentry-self-hosted-post-process-forwarder-transactions-1           Started                                                                51.7s
 ✔ Container sentry-self-hosted-ingest-profiles-1                               Started                                                                50.6s
 ✔ Container sentry-self-hosted-ingest-replay-recordings-1                      Started                                                                50.8s
 ✔ Container sentry-self-hosted-attachments-consumer-1                          Started                                                                51.2s
 ✔ Container sentry-self-hosted-generic-metrics-consumer-1                      Started                                                                51.5s
 ✔ Container sentry-self-hosted-ingest-occurrences-1                            Started                                                                51.6s
 ✔ Container sentry-self-hosted-metrics-consumer-1                              Started                                                                51.6s
 ✔ Container sentry-self-hosted-sentry-cleanup-1                                Started                                                                50.0s
 ✔ Container sentry-self-hosted-transactions-consumer-1                         Started                                                                51.2s
 ✔ Container sentry-self-hosted-post-process-forwarder-issue-platform-1         Started                                                                49.4s
 ✔ Container sentry-self-hosted-subscription-consumer-transactions-1            Started                                                                51.5s
 ⠹ Container sentry-self-hosted-relay-1                                         Created                                                              2623.1s
 ⠙ Container sentry-self-hosted-nginx-1                                         Created                                                              2623.1s
dependency failed to start: container sentry-self-hosted-web-1 is unhealthy

**Comment by hubertdeng123** [comment]
What are the logs in your web container? Does it indicate any errors that are happening? If there are no error logs, you may want to increase your timeouts in .env file. Specifically `HEALTHCHECK_INTERVAL` or `HEALTHCHECK_TIMEOUT`

**Comment by Repeg** [comment]
**origin value：**
HEALTHCHECK_INTERVAL=30s   
HEALTHCHECK_TIMEOUT=1m30s

**change to：**
COMPOSE_PROJECT_NAME=sentry-self-hosted
SENTRY_EVENT_RETENTION_DAYS=90
# You can either use a port number or an IP:PORT combo for SENTRY_BIND
# See https://docs.docker.com/compose/compose-file/#ports for more
SENTRY_BIND=9000
# Set SENTRY_MAIL_HOST to a valid FQDN (host/domain name) to be able to send emails!
# SENTRY_MAIL_HOST=example.com
SENTRY_IMAGE=getsentry/sentry:nightly
SNUBA_IMAGE=getsentry/snuba:nightly
RELAY_IMAGE=getsentry/relay:nightly
SYMBOLICATOR_IMAGE=getsentry/symbolicator:nightly
VROOM_IMAGE=getsentry/vroom:nightly
WAL2JSON_VERSION=latest
HEALTHCHECK_INTERVAL=300s   
HEALTHCHECK_TIMEOUT=3m30s
HEALTHCHECK_RETRIES=10

but still got error: 
✔ Container sentry-self-hosted-generic-metrics-consumer-1                      Started                            3.0s
 ✔ Container sentry-self-hosted-ingest-monitors-1                               Started                            3.3s
 ✘ **Container sentry-self-hosted-web-1                                           Error                           1241.5s**
 ✔ Container sentry-self-hosted-worker-1                                        Started                            3.0s
 ✔ Container sentry-self-hosted-ingest-replay-recordings-1                      Started                            3.1s
 ✔ Container sentry-self-hosted-post-process-forwarder-issue-platform-1         Started                            2.3s
 ✔ Container sentry-self-hosted-billing-metrics-consumer-1                      Started                            2.6s
 ✔ Container sentry-self-hosted-ingest-occurrences-1                            Started                            2.9s
 ✔ Container sentry-self-hosted-subscription-consumer-transactions-1            Started                            2.1s
 ✔ Container sentry-self-hosted-attachments-consumer-1                          Started                            2.3s
 ✔ Container sentry-self-hosted-ingest-profiles-1                               Started                            1.7s
 ✔ Container sentry-self-hosted-subscription-consumer-metrics-1                 Started                            2.4s
 ✔ Container sentry-self-hosted-post-process-forwarder-errors-1                 Started                            1.7s
 ✔ Container sentry-self-hosted-sentry-cleanup-1                                Started                            1.2s
dependency failed to start: container sentry-self-hosted-web-1 is unhealthy

**Comment by Repeg** [comment]
my device info:
ThinkPad T14 Gen 2i
processor	 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz   2.80 GHz
RAM	         32.0 GB (31.7 GB available)
system	         64-bit operating system, based on x64 processor
Version:            Windows 10 Professional

did my hardware need upgraded?

**Comment by Repeg** [comment]
when got sentry-self-hosted-kafka-1 error, the logs are following:
===> Configuring ...
===> Running preflight checks ...
===> Check if /var/lib/kafka/data is writable ...
===> Check if Zookeeper is healthy ...
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:zookeeper.version=3.5.8-f439ca583e70862c3068a1f2a7d4d068eec33315, built on 05/04/2020 15:53 GMT
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:host.name=27f5aa73010c
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.version=1.8.0_222
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.vendor=Azul Systems, Inc.
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.home=/usr/lib/jvm/zulu-8-amd64/jre
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.class.path=/etc/confluent/docker/docker-utils.jar
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.io.tmpdir=/tmp
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.compiler=<NA>
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:os.name=Linux
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:os.arch=amd64
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:os.version=5.15.133.1-microsoft-standard-WSL2
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:user.name=root
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:user.home=/root
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:user.dir=/
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:os.memory.free=56MB
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:os.memory.max=873MB
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:os.memory.total=59MB
[main] INFO org.apache.zookeeper.ZooKeeper - Initiating client connection, connectString=zookeeper:2181 sessionTimeout=40000 watcher=io.confluent.admin.utils.ZookeeperConnectionWatcher@65b3120a
[main] INFO org.apache.zookeeper.common.X509Util - Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation
[main] INFO org.apache.zookeeper.ClientCnxnSocket - jute.maxbuffer value is 4194304 Bytes
[main] INFO org.apache.zookeeper.ClientCnxn - zookeeper.request.timeout value is 0. feature enabled=
[main-SendThread(zookeeper:2181)] INFO org.apache.zookeeper.ClientCnxn - Opening socket connection to server zookeeper/172.18.0.4:2181. Will not attempt to authenticate using SASL (unknown error)
[main-SendThread(zookeeper:2181)] INFO org.apache.zookeeper.ClientCnxn - Socket connection established, initiating session, client: /172.18.0.5:51460, server: zookeeper/172.18.0.4:2181
[main-SendThread(zookeeper:2181)] INFO org.apache.zookeeper.ClientCnxn - Session establishment complete on server zookeeper/172.18.0.4:2181, sessionid = 0x100000f9a380000, negotiated timeout = 40000
[main] INFO org.apache.zookeeper.ZooKeeper - Session: 0x100000f9a380000 closed
[main-EventThread] INFO org.apache.zookeeper.ClientCnxn - EventThread shut down for session: 0x100000f9a380000
===> Launching ...
===> Launching kafka ...
[2024-03-12 02:07:13,028] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
[2024-03-12 02:07:13,527] WARN The package io.confluent.support.metrics.collectors.FullCollector for collecting the full set of support metrics could not be loaded, so we are reverting to anonymous, basic metric collection. If you are a Confluent customer, please refer to the Confluent Platform documentation, section Proactive Support, on how to activate full metrics collection. (io.confluent.support.metrics.KafkaSupportConfig)
[2024-03-12 02:07:13,527] WARN The support metrics collection feature ("Metrics") of Proactive Support is disabled. (io.confluent.support.metrics.SupportedServerStartable)
[2024-03-12 02:07:14,491] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2024-03-12 02:07:14,533] INFO [kafka-log-cleaner-thread-0]: Starting (kafka.log.LogCleaner)
[2024-03-12 02:07:14,736] INFO Awaiting socket connections on 0.0.0.0:9092. (kafka.network.Acceptor)
[2024-03-12 02:07:14,759] INFO [SocketServer brokerId=1001] Created data-plane acceptor and processors for endpoint : EndPoint(0.0.0.0,9092,ListenerName(PLAINTEXT),PLAINTEXT) (kafka.network.SocketServer)
[2024-03-12 02:07:14,759] INFO [SocketServer brokerId=1001] Started 1 acceptor threads for data-plane (kafka.network.SocketServer)
[2024-03-12 02:07:14,858] INFO Creating /brokers/ids/1001 (is it secure? false) (kafka.zk.KafkaZkClient)
[2024-03-12 02:07:14,874] INFO Stat of the created znode at /brokers/ids/1001 is: 466,466,1710209234868,1710209234868,1,0,0,72057661049798657,180,0,466
 (kafka.zk.KafkaZkClient)
[2024-03-12 02:07:14,874] INFO Registered broker 1001 at path /brokers/ids/1001 with addresses: ArrayBuffer(EndPoint(kafka,9092,ListenerName(PLAINTEXT),PLAINTEXT)), czxid (broker epoch): 466 (kafka.zk.KafkaZkClient)
[2024-03-12 02:07:15,243] INFO [/config/changes-event-process-thread]: Starting (kafka.common.ZkNodeChangeNotificationListener$ChangeEventProcessThread)
[2024-03-12 02:07:15,322] INFO [SocketServer brokerId=1001] Started data-plane processors for 1 acceptors (kafka.network.SocketServer)
[2024-03-12 02:08:18,990] WARN Client session timed out, have not heard from server in 12209ms for sessionid 0x100000f9a380001 (org.apache.zookeeper.ClientCnxn)
===> User
uid=0(root) gid=0(root) groups=0(root)
===> Configuring ...
===> User
uid=0(root) gid=0(root) groups=0(root)
===> Configuring ...

**Comment by hubertdeng123** [comment]
Currently we do not provide support for windows. You mentioned previously you are using ubuntu 22.04 so I am a bit confused here. From the logs it seems like your containers are not able to communicate with each other. Are there any specific firewalls that is preventing this from happening?

**Comment by Repeg** [comment]
yes im using Ubuntu 22.04.3 LTS (GNU/Linux 5.15.133.1-microsoft-standard-WSL2 x86_64) on windows wsl2, since i have tried many times so I'm not sure if my device meets the hardware requirements.
and i have checked my ufw find it inactive:
   sudo ufw status
   [sudo] password for ***:
   Status: inactive

**Comment by Repeg** [comment]
thanks god i solved this by config my .wslconfig file to:
[wsl2]
memory=16GB
processors=4
swap=4GB

former value is: 
[wsl2]
memory=8GB
processors=2


so i think this is a hardware issue.
