### ISSUE TITLE
CSRF Verification Failed A required security token was not found or was invalid.

### ISSUE THREAD

**Issue by shivamkaushal-byte** [getsentry/self-hosted#2864]
This issue has gone three weeks without activity. In another week, I will close it.

But! If you comment or otherwise update it, I will reset the clock, and if you remove the label `Waiting for: Community`, I will leave it alone ... forever!

----

"A weed is but an unloved flower." ― _Ella Wheeler Wilcox_ 🥀

_Originally posted by @getsantry[bot] in https://github.com/getsentry/self-hosted/issues/2265#issuecomment-1669019505_

**Comment by shivamkaushal-byte** [comment]
CSRF Verification Failed
A required security token was not found or was invalid.

If you're continually seeing this issue, try the following:

Clear cookies (at least for Sentry's domain).
Reload the page you're trying to submit (don't re-submit data).
Re-enter the information, and submit the form again.
Ensure the URL does not contain an extra "/" anywhere (eg: https://foo//saml -> https://foo/saml)

still getting same issue when trying to login on self-hosted sentry. I am using ALB as reverse proxy.
need help

**Comment by hubertdeng123** [comment]
Please do not create these duplicate issues. You've already created https://github.com/getsentry/self-hosted/issues/2865. Thanks!
