### ISSUE TITLE
CSRF Verification Failed A required security token was not found or was invalid.

### ISSUE THREAD

**Issue by shivamkaushal-byte** [getsentry/self-hosted#2865]
### Self-Hosted Version

latest

### CPU Architecture

x86_64

### Docker Version

25.0.3

### Docker Compose Version

2.24.6

### Steps to Reproduce

Set up self hosted sentry:
git clone 
run ./install.sh
docker-compose up -d
attach ALB to ec2 instance, open in browser.
getting this issue

### Expected Result

should be logged in

### Actual Result

CSRF Verification Failed
A required security token was not found or was invalid.

If you're continually seeing this issue, try the following:

Clear cookies (at least for Sentry's domain).
Reload the page you're trying to submit (don't re-submit data).
Re-enter the information, and submit the form again.
Ensure the URL does not contain an extra "/" anywhere (eg: https://foo//saml -> https://foo/saml).

**Comment by josetetevi95** [comment]
**Hi, I wanted to create an issue and I found that you have already created it, I have the same error:**

---

### Self-Hosted Version
latest

### CPU Architecture
x86_64 (VPS)

### Docker Version
24.0.7

### Docker Compose Version
1.25.0

### Steps to Reproduce
Set up self hosted sentry:

- `git clone https://github.com/getsentry/self-hosted.git`
- run `./install.sh`
- run `docker-compose up -d`

- set the password, I also had an error that I had this error

<img width="880" alt="Screenshot 2024-03-07 at 13 37 43" src="https://github.com/getsentry/self-hosted/assets/110821426/1d1cfc55-73be-4eb3-832d-fc52fc6283b4">

- But I managed to create the password

### Actual Result
- All containers start either for geoIP

<img width="1361" alt="Screenshot 2024-03-07 at 14 39 03" src="https://github.com/getsentry/self-hosted/assets/110821426/b5f2a4e4-f859-41e0-bbf0-71ad21441cfe">

**When I want to connect to this error:**

<img width="1680" alt="Screenshot 2024-03-07 at 14 47 36" src="https://github.com/getsentry/self-hosted/assets/110821426/1aac9685-c36e-4f91-b0b0-eb183f08c041">

```
Échec de vérification CSRF
Le jeton de sécurité requis n'a pas été trouvé ou était invalide.

Si vous rencontrez toujours ce problème, essayez ceci :

Effacez les cookies (au moins pour le domaine de Sentry).
Rechargez la page que vous essayez d'envoyer (n'envoyez pas les données une deuxième fois).
Saisissez à nouveau les informations, et envoyez à nouveau le formulaire.
Ensure the URL does not contain an extra "/" anywhere (eg: https://foo//saml -> https://foo/saml).
Read more about [CSRF on Wikipedia](http://en.wikipedia.org/wiki/Cross-site_request_forgery).
```

**Please do you have a solution for me?**

**Comment by AnthonyGWeb** [comment]
👍 Same error here

**Comment by lisn0** [comment]
i have the same issue

**Comment by fzznk** [comment]
I had the same problem. In my case the error was due to the initial settings in sentry/sentry.conf.py
at the end of the file:

#################
# CSRF Settings #
#################

# Since version 24.1.0, Sentry migrated to Django 4 which contains stricter CSR>
# If you are accessing Sentry from multiple domains behind a reverse proxy, you>
# this to match your IPs/domains. Ports should be included if you are using cus>
# https://docs.djangoproject.com/en/4.2/ref/settings/#std-setting-CSRF_TRUSTED_>

CSRF_TRUSTED_ORIGINS = ["http://web:9000"]

It worked after adding "http://127.0.0.1:9000" to the list and re-running install.sh

**Comment by alispecifique** [comment]
In sentry/sentry.conf.py
`CSRF_TRUSTED_ORIGINS = ["sentry.mydomain.com", "127.0.0.1:9000"]`

My nginx config
```
server {
  server_name sentry.mydomain.com;

  location / {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;

    proxy_pass http://127.0.0.1:9000;

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'Upgrade';
  }

    listen 443 ssl;
    ssl_certificate /etc/nginx/tls/chained.crt;
    ssl_certificate_key /etc/nginx/tls/private.key;
}

server {
    if ($host = sentry.mydomain.com) {
        return 301 https://$host$request_uri;
    } 

  server_name sentry.mydomain.com;
    listen 80;
    return 404;
}
```

But it is still not working

**Comment by AnthonyGWeb** [comment]
Hi everyone,

It's worked after uncomment `CSRF_TRUSTED_ORIGINS = ["http://myip:9000"]`. Be careful in my case ` http://` is mandatory.

Bye,

**Comment by josetetevi95** [comment]
Hi everyone, tanks for solution, It's work for me `CSRF_TRUSTED_ORIGINS = ["http://myip:9000"]`

**Comment by hubertdeng123** [comment]
Thanks for chiming in folks. @shivamkaushal-byte does the solution above work for you?

**Comment by zhoulhb** [comment]
> Hi everyone, tanks for solution, It's work for me `CSRF_TRUSTED_ORIGINS = ["http://myip:9000"]`

thanks! By the way,this config file path is located in ${sentry_home}/sentry/sentry.conf.py

**Comment by shivamkaushal-byte** [comment]
Hi,
I found a solution, 
In sentry/sentry.conf.py
CSRF_TRUSTED_ORIGINS = ["sentry.mydomain.com", "127.0.0.1:9000"]
here replace "sentry.mydomain.com" with your DNS like sentry.com. it will work.

Thanks.
