### ISSUE TITLE
All events load indifinitely, organization chart stopped to receive events

### ISSUE THREAD

**Issue by kopax-polyconseil** [getsentry/self-hosted#2867]
### Self-Hosted Version

23.6.1

### CPU Architecture

x86_64

### Docker Version

gcp-managed

### Docker Compose Version

helmfile

### Steps to Reproduce

Not really sure how to reproduce

### Expected Result

We expect to collect error events and metrics without interruption

### Actual Result

Infinite loading spiner on `/organizations/sentry/issues/1318760/events/?project=2`

<img width="1101" alt="image" src="https://github.com/getsentry/self-hosted/assets/77674046/eaf5faf0-ebea-4bbf-aa58-4fe8a94553eb">

Chart stop to receive organization events, while events still arrived `organizations/sentry/stats/?pageStatsPeriod=7d&statsPeriod=7d`

<img width="1126" alt="image" src="https://github.com/getsentry/self-hosted/assets/77674046/4eacd96f-dff8-4972-a041-d6dbd176d759">

**Comment by hubertdeng123** [comment]
Are there any logs in your web container that indicates any sort of errors/failures?
