### ISSUE TITLE
What images are required ?

### ISSUE THREAD

**Issue by mhdimsy** [getsentry/self-hosted#2877]
### Self-Hosted Version

latest

### CPU Architecture

x86

### Docker Version

25

### Docker Compose Version

2.24

### Steps to Reproduce

Hi
I am new to Docker
What images are required for Sentry self−hosted?
How can I download and transfer the required images to a server without internet access?

This images are enogh?

getsentry/sentry-cli latest
symbolicator-cleanup-self-hosted-local latest
sentry-cleanup-self-hosted-local latest
vroom-cleanup-self-hosted-local latest
sentry-self-hosted-local latest
sentry-self-hosted-jq-local latest
getsentry/symbolicator 24.1.0
getsentry/snuba 24.1.0
getsentry/relay 24.1.0
getsentry/sentry 24.1.0
getsentry/vroom 24.1.0
nginx 1.25.2-alpine
ghcr.io/maxmind/geoipupdate v6.0.0
redis 6.2.13-alpine
memcached 1.6.21-alpine
busybox latest
postgres 14.5
tianon/exim4 latest
clickhouse-self-hosted-local latest
confluentinc/cp-kafka 5.5.7
confluentinc/cp-zookeeper 5.5.7

### Expected Result

Can build and run this service

### Actual Result

nothing

### Event ID

no event

**Comment by aldy505** [comment]
I would suggest you to have a network proxy that you can connect to. See https://develop.sentry.dev/self-hosted/#installing-behind-a-proxy for guides from Sentry's side.
