### ISSUE TITLE
CSRF 验证失败

### ISSUE THREAD

**Issue by dalxy** [getsentry/self-hosted#2878]
### Self-Hosted Version

24.2.0

### CPU Architecture

x86_64

### Docker Version

Docker version 20.10.23, build 876964a

### Docker Compose Version

Docker Compose version v2.9.0-6413-g38f6acd

### Steps to Reproduce

1.下载压缩包并解压
2.cd根目录
3../install.sh
4.安装完后docker-compose up -d
5.打开http://xxx:9000进入登陆页
6.填写密码，点击登录。
报错：CSRF 验证失败
安全令牌不存在或无效

如果您不断看到此问题，可尝试以下步骤：

清除 cookies（至少是 Sentry 域名下的 cookies）。
重新载入您试图提交的页面（不要重新提交数据）。
重新输入信息，然后再次提交表格。
Ensure the URL does not contain an extra "/" anywhere (eg: https://foo//saml -> https://foo/saml).

### Expected Result

可以正常登录

### Actual Result

CSRF 验证失败
安全令牌不存在或无效

如果您不断看到此问题，可尝试以下步骤：

清除 cookies（至少是 Sentry 域名下的 cookies）。
重新载入您试图提交的页面（不要重新提交数据）。
重新输入信息，然后再次提交表格。
Ensure the URL does not contain an extra "/" anywhere (eg: https://foo//saml -> https://foo/saml).

**Comment by hubertdeng123** [comment]
Have you attempted to update the `CSRF_TRUSTED_ORIGINS` variable in your `sentry.conf.py` file?

**Comment by dalxy** [comment]
I only did the above operation without modifying any files，do I need to modify the sentry.conf.py file?

**Comment by aldy505** [comment]
Yes you have to modify the sentry.conf.py file. See the documentation here https://develop.sentry.dev/self-hosted/troubleshooting/#csrf-verification-failed

**Comment by dalxy** [comment]
Do you need to reinstall it after the change?And, can I change "https://sentry.example.com" to my LAN website, because I don't have a public network ip

**Comment by aldy505** [comment]
It's safe to re-run `./install.sh` after changing the sentry.conf.py file. Yes you can change that to your LAN website.

**Comment by linydquantil** [comment]
Hello, I've encountered the exact same issue, using docker-compose to deploy on a machine that has access to the external network. How can I solve this?

**Comment by linydquantil** [comment]
@hubertdeng123  thanks ！！！
