### ISSUE TITLE
Github Integration Issue - No button to install on pop up, just regular app page

### ISSUE THREAD

**Issue by bruno-canada** [getsentry/self-hosted#2879]
### Self-Hosted Version

24.2.0

### CPU Architecture

x86_64

### Docker Version

25.0.1

### Docker Compose Version

2.11.1

### Steps to Reproduce

1. Created an app as outlined in the documentation: https://develop.sentry.dev/integrations/github/
2. Updated the `config.yml` as per the documentation
3. Rebuilt and restarted Sentry containers
4. Go to Sentry > Settings > Integration > GitHub > Add Instalation
5. The app main page opens with no CTA to install it. It just opens a regular app page in Github e.g. https://github.com/apps/app-name

### Expected Result

Have a button to click to install. No button. 

### Actual Result

Just loads the app main page inside the pop up, no button to click to install.

**Comment by hubertdeng123** [comment]
Did you restart your docker containers after updating your config file?

**Comment by bruno-canada** [comment]
> Did you restart your docker containers after updating your config file?

@hubertdeng123 - Yes. Rebuilt containers and restarted.

**Comment by hubertdeng123** [comment]
Then I'm not sure exactly what may be the case. Can you double check your setup url for your github app? It needs to point to your self hosted instance

**Comment by aldy505** [comment]
I know this is closed, but if anyone's found this issue and don't know what to do or how to resolve it, you'll just need to inspect the network tab and find out that GitHub actually provides an error on the URL query string, then we'll be redirected to our own self-hosted instance.

For my case, it was invalid `redirect_url` in which the docs is actually missing something about it. See https://github.com/getsentry/develop/issues/1254
