### ISSUE TITLE
ClickHouse db is unexpectedly growing

### ISSUE THREAD

**Issue by brogger71** [getsentry/self-hosted#2882]
### Self-Hosted Version

23.11.2

### CPU Architecture

x86_64

### Docker Version

4.2.0

### Docker Compose Version

instead of docker compose we use helm

### Steps to Reproduce

we're assuming, that issues are going to be saved indefinitely in the ClickHouse db. We're just pushing messages to sentry.io "on prem" on a daily base. The amount of daily messages are approx 6000.

### Expected Result

we've set the ZOO_AUTOPURGE_INTERVAL on zookeeper to value 1. According to the documentation, zookeeper should clean the data store in a hourly manner. The clean process is starting but we do not see any changes in the ClickHouse db.
Could It be, that there's another cleanup process for the ClickHouse db? What else can be done in order to reduce the data stored in the ClickHouse db?

### Actual Result

Removing file: Mar 7, 2024, 5:27:01 AM	/bitnami/zookeeper/data/version-2/log.cab0009ffb7
Removing file: Mar 7, 2024, 5:27:01 AM	/bitnami/zookeeper/data/version-2/snapshot.cab000affae
Removing file: Mar 7, 2024, 12:08:42 PM	/bitnami/zookeeper/data/version-2/log.cab000affb0
Removing file: Mar 7, 2024, 12:08:42 PM	/bitnami/zookeeper/data/version-2/snapshot.cab000c3332
Removing file: Mar 7, 2024, 8:03:12 PM	/bitnami/zookeeper/data/version-2/log.cab000c3334
Removing file: Mar 7, 2024, 10:31:49 PM	/bitnami/zookeeper/data/version-2/log.cab000d7755
Removing file: Mar 7, 2024, 8:03:12 PM	/bitnami/zookeeper/data/version-2/snapshot.cab000d7753

**Comment by aldy505** [comment]
The default setup for ClickHouse on self-hosted does not require you to use Zookeeper. Also make sure you're not missing any Snuba containers, IIRC there are some clean up job on one of those containers. 

If the problem persist, you should consult with the helm chart GitHub repository instead of this one.
