### ISSUE TITLE
How to change password hash in postgres ?

### ISSUE THREAD

**Issue by mostfurious** [getsentry/self-hosted#2884]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### What are you trying to accomplish?

We have no super users in the system. Client forgot his password and now asks as to change it. 

### How are you getting stuck?

We have root access to vm where sentry is running. I can access postgres database and i can see user password hashes that start with: pbkdf2_sha256$150000$
Question is how do i generate one like that ? And if i do replace it in auth_user table. Will the user be able to log in again ?

### Where in the product are you?

Sign In

### Version

22.8.0

**Comment by hubertdeng123** [comment]
I would not advise you to change the password hash inside the postgres table manually and I'm unsure if that will solve your issue. Could your client request a lost password to reset their password through email?

**Comment by mostfurious** [comment]
Thats the thing, email does not work already tried it. Might have to try and change smtp details if there is no other way of changing the password

**Comment by hubertdeng123** [comment]
Does email not work at all? Or just for the password reset page? Could you try sending an email from another user's account?
