### ISSUE TITLE
Sentry Application set rate_limit

### ISSUE THREAD

**Issue by amitesh2181763** [getsentry/self-hosted#2886]
Hi Team,

In our sentry application, we observed that a few projects are utilizing our application heavily and sending lots of log messages to our application, and we want to limit those log messages sent from the project to our sentry application.
As per the sentry official document, there is one option below suggested.

1) Set a rate_limit project level, like how many log messages are sent by the project every minute, but that option only affects the project level. If you want to know what the default limit is, we can set the project level.
2) Is there any option to set rate_limit org level in Senry?

**Our Sentry Application Version:** 24.1.0

 **URL:** https://docs.sentry.io/product/accounts/quotas/

Can you please suggest the best optimization method to limit these log messages as well as any other optimization parameters that need to be set?

**Comment by aldy505** [comment]
Quotas only exists for SaaS which has a billing feature. 

For self hosted, please refer to https://develop.sentry.dev/self-hosted/reverse-proxy#rate-limiting

**Comment by amitesh2181763** [comment]
Hi @aldy505 Thanks for the update, and can you please provide details about the below rate_limit option mentioned in the screen shot? This option will help us to limit the project error messages acceptance criteria, and this option is visible to us in the community edition. What is the default limit we can set for this option? and this error messages storing in which table into database.

<img width="737" alt="image" src="https://github.com/getsentry/self-hosted/assets/136332716/979caf61-8bb8-4c33-bdc3-3c8cbe299b64">

**Comment by hubertdeng123** [comment]
@amitesh2181763 The error messages are stored in clickhouse, should be in `errors_local`. The limit you should set for this option is based on your own use case, but by default we do not rate limit projects.

**Comment by amitesh2181763** [comment]
Hi @hubertdeng123 Thank you for the update, and this error message is stored in Clickhouse, so we need to do any housekeeping for that sentry and provide any way to do cleanup for the same. If we set a project-level error message send limit, there is no harm?, and after setting this project limit, some error messages go into dropped errors, so those messages are also stored in Clickhouse?

**Comment by hubertdeng123** [comment]
If you set a project-level rate limit, those dropped errors should not be stored in Clickhouse.
