### ISSUE TITLE
OperationalError: sentry.tasks.deletion.process_hybrid_cloud_foreign_key_cascade_batch

### ISSUE THREAD

**Issue by RedShiba** [getsentry/self-hosted#2896]
### Self-Hosted Version

24.2.0

### CPU Architecture

x86_64

### Docker Version

25.0.0

### Docker Compose Version

1.28.5

### Steps to Reproduce

upgrade Sentry 23.3.1 to 24.2.0
Sometimes(2-4 times per day) I catch internal task error
```
OperationalError 
sentry.tasks.deletion.process_hybrid_cloud_foreign_key_cascade_batch

port 5432 failed: Connection timed out
	Is the server running on that host and accepting TCP/IP connections?
```
<img width="1110" alt="paveikslas" src="https://github.com/getsentry/self-hosted/assets/96052052/b8eaaf05-aacf-43b4-91ea-a8a956935d1c">

seems it can't connect to postgres. But it happens only with this task, everything works good except this task. I enabled debug logs, maybe I will get some additional info, waiting reprodusing.

I don't see any influence on smth, so I don't think it's crucial. 
If you can confirm that I can ignore this error or even better how fix it, would be nice.

### Expected Result

no errors from task process_hybrid_cloud_foreign_key_cascade_batch

### Actual Result

I'm getting error from sentry task process_hybrid_cloud_foreign_key_cascade_batch

**Comment by hubertdeng123** [comment]
This does not look like a crucial task, as it is cleaning up data in postgres. It would be helpful to get some more info on why this is erroring out though.
