### ISSUE TITLE
Sentry - The string did not match the expected pattern. - No Trace Available

### ISSUE THREAD

**Issue by gokulan-knackforge** [getsentry/self-hosted#2898]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### What are you trying to accomplish?

Try to figure out the issue and fix it

### How are you getting stuck?

i have this error with no trace. The error is, "The string did not match the expected pattern."

### Where in the product are you?

Issues

### Link

https://iclasspro.sentry.io/issues/5028617459/events/88c242829d1f4d178c5a55b7d69cd1fd/

### Version

4.1.1

**Comment by aldy505** [comment]
Hello! Can you provide more details about the problem that you're facing?

**Comment by gokulan-knackforge** [comment]
@aldy505 Thanks for your response. Unfortunately, i do not have much details on the error page other than error message. No stack trace, no breadcrumbs. So that i raised this ticket. 

Error: "The string did not match the expected pattern."

**Comment by aldy505** [comment]
Can you put a screenshot on what's on that error page? I can't get any idea on why or how that error occured.

Whay did you do before the error occured? Or did you do nothing?

**Comment by gokulan-knackforge** [comment]
@aldy505 Here with i have attached screenshot of the sentry issue. And we haven;t done anything form our end at that time. But our clients might be. 

![sentry-error](https://github.com/getsentry/self-hosted/assets/51940535/318b1cd9-9591-465c-a128-dd5b4a4ea5b3)

**Comment by aldy505** [comment]
I don't think this is self-hosted, and the issue does not have any relation with Sentry at all. Therefore I'm going to close this issue. 

Since this is an issue on your application, you should read the docs about enriching your error events: https://docs.sentry.io/platforms/javascript/guides/angular/enriching-events/
