### ISSUE TITLE
I have set up self hosted sentry, it is working fine, now i have to integrate this with spring boot application. Do i need to set up DSN or default will work ??

### ISSUE THREAD

**Issue by shivamkaushal-byte** [getsentry/self-hosted#2905]
### Self-Hosted Version

latest

### CPU Architecture

x86_64

### Docker Version

25.0.3

### Docker Compose Version

2.24.6

### Steps to Reproduce

Set up self hosted sentry from official document

### Expected Result

Will have to integrate it with spring boot application and error will start coming up on sentry dashboard. 

### Actual Result

Developer has already integrated with default DSN but errors or logs are not coming on dashboard

**Comment by shivamkaushal-byte** [comment]
@csvan I am using self hosted sentry, already tried to integrate using DSN but its now showing anything.

**Comment by shivamkaushal-byte** [comment]
I am using self-hosted sentry and it giving DSN in http://332233344569087654@nginx/2 in this format. so is this fine ??

**Comment by hubertdeng123** [comment]
If no events are showing up, I'd check nginx logs to ensure that the envelopes are actually being picked up.

**Comment by shivamkaushal-byte** [comment]
I am using self-hosted sentry and it giving DSN in http://332233344569087654@nginx/2 in this format. so is this fine ??

**Comment by shivamkaushal-byte** [comment]
Developers are trying to connect with sentry via SDK but unable to send application errors on sentry dashboard. why ??

**Comment by csvan** [comment]
@shivamkaushal-byte you should investigate if the requests are even reaching the sentry instance. You can for example enable access logging for the Sentry nginx instance and inspect the logs as you are running your Spring Boot app.

**Comment by shivamkaushal-byte** [comment]
when we are using sentry API then we are getting error logs in sentry dashboard related to application but when are using SDK then nothing is showing .
Also DSN value is "http://0762297880b10d20b747c4d93d9c44c7@nginx/3"  in self hosted sentry. is it correct or valid ??

**Comment by azaslavsky** [comment]
No, something is quite wrong there. The bit following the `@` portion should be the URL of your Sentry instance, not `nginx`.

**Comment by shivamkaushal-byte** [comment]
After setting up self-hosted sentry what configuration i need to change to get proper DSN

**Comment by csvan** [comment]
@shivamkaushal-byte the `@nginx/3` part of your DSN needs to be a proper domain, e.g.  `mycompany.com/3` or `localhost:1337/3`. This of course depends on which URL your sentry instance is reachable on.

**Comment by shivamkaushal-byte** [comment]
My domain name is sentry.onemuthoot.com and i have set system.prefix_url = sentry.onemuthoot.com  in /sentry/config.yml but still i am getting this DSN. What is an issue??

**Comment by csvan** [comment]
Try changing it in the GUI under Admin -> Settings -> General -> Root URL

<img width="602" alt="Screenshot 2024-04-06 at 15 33 32" src="https://github.com/getsentry/self-hosted/assets/1127729/d5c98698-ba16-45fa-9968-5d09acc457ab">
