### ISSUE TITLE
Getting Internal Error After Restarting the sentry 

### ISSUE THREAD

**Issue by varma-shipsy** [getsentry/self-hosted#2910]
### Self-Hosted Version

23.9.1

### CPU Architecture

x86_64

### Docker Version

Docker version 24.0.6, build ed223bc

### Docker Compose Version

docker-compose version 1.29.2, build 5becea4c

### Steps to Reproduce

1. ./install.sh 
2. docker compose up -d
3. got the error : https://www.dragonflydb.io/error-solutions/redis-exceptions-busyloadingerror-redis-is-loading-the-dataset-in-memory (web-api-container unhealhty )
4. tried after a while it worked, sentry is up and running 
5, got internal errors now in dashboard on issues page and projects page 

![image](https://github.com/getsentry/self-hosted/assets/92160261/3b1a7e3f-6de5-43e7-b822-a3d1e87e5c1b)

### Expected Result

Page Should show up the issues list 

### Actual Result

Internal error 
![image](https://github.com/getsentry/self-hosted/assets/92160261/de3e5093-b486-443a-ab59-156885ee69d1)

**Comment by hubertdeng123** [comment]
What error logs are you getting in your redis/web containers? Could this be a redis issue on your side rather than a self-hosted Sentry specific issue?

**Comment by varma-shipsy** [comment]
@hubertdeng123 Seems we lost the redis volume data, when restarted it created a new redis-volume this seems issue how we can restore the redis to in sync with database again

**Comment by azaslavsky** [comment]
What happens if you re-run the install script (not a fresh install, just run `./install.sh` locally). Seems like a migration may have gone awry.
