### ISSUE TITLE
User Feedback: Client side issue

### ISSUE THREAD

**Issue by schettn** [getsentry/self-hosted#2920]
Anyone getting this after adding the features flags?

![image](https://github.com/getsentry/self-hosted/assets/52858351/c3de7b37-cd36-4f11-b29f-ea50ff0af56c)

_Originally posted by @schettn in https://github.com/getsentry/self-hosted/issues/2646#issuecomment-2011355646_

**Comment by hubertdeng123** [comment]
I'm going to close this, as you've already posted in https://github.com/getsentry/self-hosted/issues/2646, where we'll use as the primary issue for discussing beta user feedback issues.
