### ISSUE TITLE
change password error (api status code 500) in 21.5.1 using admin pannel

### ISSUE THREAD

**Issue by kaneruan** [getsentry/self-hosted#2933]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

same issue : https://github.com/getsentry/sentry/issues/38436

### Expected Result

no error

### Actual Result

<img width="1258" alt="image" src="https://github.com/getsentry/sentry/assets/13065289/91f23a8e-979f-4c7c-8916-0f8e82e9d251">
<img width="1056" alt="image" src="https://github.com/getsentry/sentry/assets/13065289/368e1d10-dd51-452f-998f-9c9261427e5b">

### Product Area

Other

### DSN

https://sentry.xxxx.xxxxx/admin/sentry/user/35/password/

### Version

21.5.1

**Comment by azaslavsky** [comment]
This is an old version, and this code is no longer in our codebase. For example, this file was removed entirely about 9 months ago, and the commit implies that it had already been unused for some time before that: https://github.com/getsentry/sentry/commit/9cd94f18cb4599e6a7d3d264f9bcc6ef4e526846

This was probably actually broken at the version you're on and has been fixed at a later version. Try updating your Sentry to a more recent version (remember that there is a hard stop at 23.6.2!).
