### ISSUE TITLE
settings account security no longer works

### ISSUE THREAD

**Issue by chris-laack** [getsentry/self-hosted#2935]
### Self-Hosted Version

24.2.0 and 24.3.0 

### CPU Architecture

x86_64

### Docker Version

26.0.0

### Docker Compose Version

v2.25.0

### Steps to Reproduce

Select User Settings Account Security

### Expected Result

Security settings must work

### Actual Result

Hi,

We have a new Sentry user as of today. When trying to set up MFA, we noticed that the Account Settings Security page no longer works. 
This affects Sentry versions 24.2.0 and 24.3.0.
Error see screen. 
Unfortunately, I cannot find a suitable entry in the logs that indicates the error. Here I would need help for troubleshooting. 

<img width="943" alt="Bildschirmfoto 2024-04-03 um 15 35 41" src="https://github.com/getsentry/self-hosted/assets/152288991/9e7fdc40-877a-4afa-886a-0dbe6e58cdce">

**Comment by azaslavsky** [comment]
So when that message pops up, you should (almost) always see an error (probably 500) in your browser's devtools. If you do, you should try to search for the error in your `web` container's logs. Does anything pop up on either of these channels?

**Comment by chris-laack** [comment]
Sorry for the delay. 
I'll have to set the log level to debug next week. I don't get any errors in the web container under Infos. In the browser debug mode I only see a http 304 error when loading the page. 
I will let you know when I have debugged the problem.
