### ISSUE TITLE
CSRF Token issue in aws ec2 server

### ISSUE THREAD

**Issue by Abhis9929** [getsentry/self-hosted#2938]
### Self-Hosted Version

24.4.0.dev0

### CPU Architecture

4 core

### Docker Version

25.0.3

### Docker Compose Version

1.25.0

### Steps to Reproduce

1. Clone the code
2. Go  inside the self-hosted folder
3. create .env.custom file from .env
4. run ./install.sh 

### Expected Result

I tried to run this self-hosted server on aws ec2 server and follow the steps mentioned but getting an error while login in the dashboard like CSRF Token something, do I need to change something in the sentry code as per ec2 server details, and if yes then in which file its need to change?

### Actual Result

I tried to run this self-hosted server on aws ec2 server and follow the steps mentioned but getting an error while login in the dashboard like CSRF Token something, do I need to change something in the sentry code as per ec2 server details, and if yes then in which file its need to change?

**Comment by thuvh** [comment]
is there any log from docker logs?

**Comment by chris-laack** [comment]
do you use an elb in the aws?
I had to set the following value in our sentry.conf. 
CSRF_TRUSTED_ORIGINS = ['https://sentry-url']

**Comment by Abhis9929** [comment]
No, I did not use any ELB.

Getting below error and logs in nginx conatiner.
![sentry-csrf](https://github.com/getsentry/self-hosted/assets/146874814/2f4cc677-8a4f-4935-a0fb-e28704d73254)
![sentry-nginx=logs](https://github.com/getsentry/self-hosted/assets/146874814/b3fab13e-9533-4234-96f5-c79fcd0e9cf2)

**Comment by chris-laack** [comment]
you must set the value CSRF_TRUSTED_ORIGINS with the host name with which you call the sentry system. 
In our case, this is the DNS alias which is called via our loadbalancer. 
The CSRF_TRUSTED_ORIGINS must be set in sentry.conf.py. 
See also here https://github.com/getsentry/self-hosted/issues/2865
I hope it helps you.

**Comment by aldy505** [comment]
There's also the docs here https://develop.sentry.dev/self-hosted/troubleshooting/#csrf-verification-failed

**Comment by Abhis9929** [comment]
Thanks for the Support, CSRF issue has been fixed. but now the issue is I am not getting errors in my sentry dashboard.
I created one node project and shared the DSN with my developer and he sent the errors but did not get errors in the dashboard.

Could you please help me with this, why errors are not reflected in the dashboard, which service logs need to be checked, and what else needs to be updated?

I checked kafka logs and zookeeper logs but there is nothing, only some INFO and WARNING are there.
![kafka-logs](https://github.com/getsentry/self-hosted/assets/146874814/95110611-9d8d-4d32-84c6-7cb2238ea84a)
![zookeeper-logs](https://github.com/getsentry/self-hosted/assets/146874814/0da01b74-1f6a-4034-8e33-51255aca615d)

Please help me with this issue.

Thanks

**Comment by Abhis9929** [comment]
Hey All, It's working now, getting errors from the code.

Thanks for the support.
