### ISSUE TITLE
Infinite loop while restoring backup

### ISSUE THREAD

**Issue by ingria** [getsentry/self-hosted#2944]
### Self-Hosted Version

dev-master

### CPU Architecture

x86_x64

### Docker Version

24.0.4

### Docker Compose Version

24.0.4

### Steps to Reproduce

run ./scripts/restore.sh

### Expected Result

everything works fine

### Actual Result

Importing: XX seconds elapsed line repeats indefinitely while nothing seems to happen

![image](https://github.com/getsentry/self-hosted/assets/2178368/0096c011-7eaf-462b-980e-06c23e6b5072)

**Comment by azaslavsky** [comment]
This is some new logging we added, though this is too frequent. I will tone this down to report once every 10 seconds instead.

How big is the JSON (or encrypted tarball you're importing). For reference, we generally expect somewhere roughly on the order of 1min/2Mb of data to import, though that can change depending on how beefy your machine is as well.

**Comment by ingria** [comment]
Turned out that the script asks "would you like to continue? y/n" in the very beginning and then starts flooding console with timer info, without waiting for my answer

So the solution is to blindly type y and press enter

**Comment by azaslavsky** [comment]
Fix for this is in-flight, will probably be on the next nightly release: https://github.com/getsentry/sentry/pull/68566

**Comment by ingria** [comment]
Also there's an extra space in log name:

```
sentry_restore _log-2024-04-10_13-48-52.txt
```

It causes another error in restore script:

```
cat: sentry_restore: No such file or directory
cat: _log-2024-04-10_13-55-47.txt: No such file or directory
```
