### ISSUE TITLE
Issue importing sentry exported data

### ISSUE THREAD

**Issue by MichelBitar99** [getsentry/self-hosted#2949]
### Self-Hosted Version

21.8.0

### CPU Architecture

x86_64

### Docker Version

20.10.18

### Docker Compose Version

1.29.2

### Steps to Reproduce

I am trying to migrate data (without event data) from sentry k8s to sentry self-hosted.

The export.json contains records similar to the following for all users:
``` json
[
{
    "model": "sentry.email",
    "pk": 3,
    "fields": {
      "email": "<user_example>",
      "date_added": "2021-02-25T13:30:14.337Z"
    }
  },
 {
    "model": "sentry.user",
    "pk": 3,
    "fields": {
      "password": "pbkdf2_sha256$120000$YUak................",
      "last_login": "2024-02-19T11:47:41.798Z",
      "username": "<user_example>",
      "name": "<user_name>",
      "email": "<user_example>",
      "is_staff": false,
      "is_active": true,
      "is_superuser": false,
      "is_managed": false,
      "is_sentry_app": null,
      "is_password_expired": false,
      "last_password_change": "2021-02-25T13:30:14.328Z",
      "flags": "0",
      "session_nonce": "Uxx....",
      "actor": 1,
      "date_joined": "2021-02-25T13:30:14.304Z",
      "last_active": "2024-03-04T08:26:57.695Z"
    }
  },
{
    "model": "sentry.useremail",
    "pk": 3,
    "fields": {
      "user": [
        "<user_example>"
      ],
      "email": "<user_example>",
      "validation_hash": "MXw1...............",
      "date_hash_added": "2021-02-25T13:30:14.334Z",
      "is_verified": false
    }
  }
]
```

I am running inside the web container the following command:
`
sentry import export.json
`

### Expected Result

I am expecting the data to be migrated successfully

### Actual Result

The import is failing with the following error:
```
django.db.utils.IntegrityError: IntegrityError('duplicate key value violates unique constraint "sentry_useremail_user_id_email_ade975f1_uniq"\nDETAIL:  Key (user_id, email)=(3, <user_example>) already exists.\n',)
SQL: UPDATE "sentry_useremail" SET "user_id" = %s, "email" = %s, "validation_hash" = %s, "date_hash_added" = %s, "is_verified" = %s WHERE "sentry_useremail"."id" = %s
```

The only way I can fix this is by deleting all the useremail models as such:
`
jq 'del(.[] | select(.model == "sentry.useremail"))'
`
And then importing the data.

However, if I do that, I will have the following error under the Members tab:
![image](https://github.com/getsentry/self-hosted/assets/43973789/8f676d9f-fbc9-4df7-8990-0d5e9985cff2)

Going a step further, even if we decide to lose all users and create them again, we would face issues restoring the data because of "sentry.userip", and then dashboards' created_by field etc...

**Comment by azaslavsky** [comment]
This script was basically nonfunctional on old versions, prior to 23.11.1. I'd recommend using the approach specified [here](https://develop.sentry.dev/self-hosted/backup/#full-backup) for your version instead. Conversely, you can upgrade to >=23.11.1 (don't forget the hard stop at 23.6.2 though!), at which point new backups generated post-upgrade will be able to be restored properly (however, this backup, which was made using an old version, will still fail). Sorry, this wasn't a great experience before we revamped it in 23.11.1, so the options for old versions aren't great!

**Comment by azaslavsky** [comment]
It's very hard to say. The reason this operation was so buggy was because it just exported/imported raw tables. But a new instance has entries of its own - these often collided, causing pks that point to nowhere (since the auto_increment is off), which produces all sorts of state dependent bugs. It's very hard to remotely debug this issue, especially on an old version like this.

Have you considered doing a full volume backup instead?

**Comment by MichelBitar99** [comment]
I see, I tried fixing the issue manually but got nowhere.

I believe that backing up the volumes is going to be much more complicated as there are a lot of discrepancies between the k8s and self-hosted version. I would bump into much more issues.
One simple example is that k8s uses bitnami/postgresql , and is on a whole different version of postgres.

Will try upgrading to 23.11.1 then performing a backup/restore.
