### ISSUE TITLE
register tab is not showing on sentry login page

### ISSUE THREAD

**Issue by shivamkaushal-byte** [getsentry/self-hosted#2954]
### Self-Hosted Version

latest

### CPU Architecture

x86_64

### Docker Version

25.0.3

### Docker Compose Version

2.24.6

### Steps to Reproduce

when invite any user then user will get an email with register link.
when user click to link then it redirects to login page and unable to see register tab.

### Expected Result

user can able to see register tab through which he can able to create account.

### Actual Result

register tab is not showing on login page

**Comment by aldy505** [comment]
Have you:

1. Uncomment this line and set your correct URL that you're using to access sentry?
    https://github.com/getsentry/self-hosted/blob/7c992697af16365a800b9c64c76d17ffceead8fa/sentry/config.example.yml#L82
2. Have registration enabled on your Sentry -> Admin Settings -> Enable Registration
