### ISSUE TITLE
Stats only shows dropped and filtered transactions/issues, not accepted ones. 

### ISSUE THREAD

**Issue by csvan** [getsentry/self-hosted#2956]
### Self-Hosted Version

24.3.0

### CPU Architecture

x86_64

### Docker Version

24.0.5

### Docker Compose Version

2.24.6

### Steps to Reproduce

Open the "Stats" page in the Sentry GUI.

### Expected Result

It should should correct data for number of issues and transactions.

### Actual Result

It only shows dropped and filtered transactions:

<img width="1447" alt="Screenshot 2024-04-13 at 09 31 27" src="https://github.com/getsentry/self-hosted/assets/1127729/3e251b0b-ffb4-430c-a1b4-8eb003a11ffe">

However, the system is working fine, and looking at individual projects shows that issues/transactions are indeed being accepted and processed properly:

<img width="463" alt="Screenshot 2024-04-13 at 09 32 23" src="https://github.com/getsentry/self-hosted/assets/1127729/d8695a36-056d-4b06-a039-0818e862f586">

This is thus not a major problem, but would be nice to know if it can be fixed. Problems started sometime after we upgraded to 24.3.0, it is unclear when.

**Comment by aldy505** [comment]
Have you apply the patch from this PR yet? https://github.com/getsentry/self-hosted/pull/2909/files

**Comment by csvan** [comment]
@aldy505 I was not aware of it, will give it a try

**Comment by hubertdeng123** [comment]
This patch will also be included in 24.4.0, which will be released later today

**Comment by csvan** [comment]
Confirming that upgrading to 24.4.0 resolves this, thanks <3
