### ISSUE TITLE
Cron warnings in log

### ISSUE THREAD

**Issue by bobvandevijver** [getsentry/self-hosted#2957]
### Self-Hosted Version

24.3.0

### CPU Architecture

x86_64

### Docker Version

26.0.0 / 24.0.7

### Docker Compose Version

2.25.0 / 2.21.1

### Steps to Reproduce

The cron service is spamming the log every 10 seconds with a warning about a schedule that is not supported (although it seems to be working fine as it is logging the same line every 10 seconds).

### Expected Result

No warnings.

### Actual Result

```
cron-1                                          | 08:23:30 [WARNING] sentry_sdk.errors: Intervals shorter than one minute are not supported by Sentry Crons. Monitor 'deliver-webhooks-control' has an interval of 10 seconds. Use the `exclude_beat_tasks` option in the celery integration to exclude it.
```

**Comment by hubertdeng123** [comment]
I think this may already be fixed actually here:
https://github.com/getsentry/sentry/pull/67627

Our new release is going out today that should include this 🤞

**Comment by bobvandevijver** [comment]
These lines are indeed gone with 24.4.0 👍🏻
