### ISSUE TITLE
first time install sudo ./install.sh fails

### ISSUE THREAD

**Issue by mikalauskas** [getsentry/self-hosted#2982]
### Self-Hosted Version

24.4.1

### CPU Architecture

x86_64

### Docker Version

25.0.2

### Docker Compose Version

2.24.5

### Steps to Reproduce

1. docker container prune
2. docker image prune -a
3. docker volume prune -a
4. git clone https://github.com/getsentry/self-hosted.git sentry
5. cd sentry
6. sudo ./install.sh

### Expected Result

getting 'You're all done! Run the following command to get Sentry running'

### Actual Result
```
...
▶ Bootstrapping and migrating Snuba ...
 Network sentry-self-hosted_default  Creating
 Network sentry-self-hosted_default  Created
 Volume "sentry-self-hosted_sentry-nginx-cache"  Creating
 Volume "sentry-self-hosted_sentry-nginx-cache"  Created
 Volume "sentry-self-hosted_sentry-vroom"  Creating
 Volume "sentry-self-hosted_sentry-vroom"  Created
 Volume "sentry-self-hosted_sentry-secrets"  Creating
 Volume "sentry-self-hosted_sentry-secrets"  Created
 Volume "sentry-self-hosted_sentry-smtp"  Creating
 Volume "sentry-self-hosted_sentry-smtp"  Created
 Volume "sentry-self-hosted_sentry-kafka-log"  Creating
 Volume "sentry-self-hosted_sentry-kafka-log"  Created
 Volume "sentry-self-hosted_sentry-zookeeper-log"  Creating
 Volume "sentry-self-hosted_sentry-zookeeper-log"  Created
 Volume "sentry-self-hosted_sentry-clickhouse-log"  Creating
 Volume "sentry-self-hosted_sentry-clickhouse-log"  Created
 Volume "sentry-self-hosted_sentry-smtp-log"  Creating
 Volume "sentry-self-hosted_sentry-smtp-log"  Created
 Container sentry-self-hosted-clickhouse-1  Creating
 Container sentry-self-hosted-zookeeper-1  Creating
 Container sentry-self-hosted-redis-1  Creating
 Container sentry-self-hosted-clickhouse-1  Created
 Container sentry-self-hosted-zookeeper-1  Created
 Container sentry-self-hosted-kafka-1  Creating
 Container sentry-self-hosted-redis-1  Created
 Container sentry-self-hosted-kafka-1  Created
 Container sentry-self-hosted-redis-1  Starting
 Container sentry-self-hosted-zookeeper-1  Starting
 Container sentry-self-hosted-clickhouse-1  Starting
 Container sentry-self-hosted-zookeeper-1  Started
 Container sentry-self-hosted-zookeeper-1  Waiting
 Container sentry-self-hosted-clickhouse-1  Started
 Container sentry-self-hosted-redis-1  Started
 Container sentry-self-hosted-zookeeper-1  Healthy
 Container sentry-self-hosted-kafka-1  Starting
 Container sentry-self-hosted-kafka-1  Started
dependency failed to start: container sentry-self-hosted-clickhouse-1 is unhealthy
Error in install/bootstrap-snuba.sh:3.
'$dcr snuba-api bootstrap --no-migrate --force' exited with status 1
-> ./install.sh:main:32
--> install/bootstrap-snuba.sh:source:3

Envelope from file sentry-envelope-913d5a3294be64de1584af3df85a1b41 dispatched
Cleaning up...
```
[sentry_install_log-2024-04-20_11-37-14.txt](https://github.com/getsentry/self-hosted/files/15047204/sentry_install_log-2024-04-20_11-37-14.txt)
[docker_compose_logs.txt](https://github.com/getsentry/self-hosted/files/15047205/docker_compose_logs.txt)

**Comment by aldy505** [comment]
This is most likely caused by a small machine specification (or a machine with not good enough performance -- as Zookeeper, Kafka and ClickHouse are costly to run). Can you share your machine specification?

**Comment by mikalauskas** [comment]
> This is most likely caused by a small machine specification (or a machine with not good enough performance -- as Zookeeper, Kafka and ClickHouse are costly to run). Can you share your machine specification?

It runs in vm on Xeon E-2278GE with 128 RAM but on HDD, io performance could be the case?

**Comment by aldy505** [comment]
> > This is most likely caused by a small machine specification (or a machine with not good enough performance -- as Zookeeper, Kafka and ClickHouse are costly to run). Can you share your machine specification?
> 
> It runs in vm on Xeon E-2278GE with 128 RAM but on HDD, io performance could be the case?

Ah yes, that might be the case. Can you upgrade to at least an SSD drive? Your CPU and RAM shouldn't be an issue here.
