### ISSUE TITLE
Always fails when executing “./install.sh” , please help me~thanks！

### ISSUE THREAD

**Issue by yuhuo** [getsentry/self-hosted#2984]
### Self-Hosted Version

24.4.1

### CPU Architecture

x86_64

### Docker Version

26.0.0

### Docker Compose Version

2.25.0

### Steps to Reproduce

1. git clone https://github.com/getsentry/self-hosted.git
2. cd self-hosted
3. ./install.sh

### Expected Result

install success

### Actual Result

#8 [symbolicator-cleanup 4/5] RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
#8 0.611 Ign:1 http://deb.debian.org/debian stretch InRelease
#8 0.612 Ign:2 http://security.debian.org/debian-security stretch/updates InRelease
#8 0.796 Ign:3 http://deb.debian.org/debian stretch-updates InRelease
#8 0.801 Ign:4 http://security.debian.org/debian-security stretch/updates Release
#8 0.983 Ign:5 http://deb.debian.org/debian stretch Release
#8 0.996 Ign:6 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
#8 1.171 Ign:7 http://deb.debian.org/debian stretch-updates Release
#8 1.196 Ign:8 http://security.debian.org/debian-security stretch/updates/main all Packages
#8 1.357 Ign:9 http://deb.debian.org/debian stretch/main amd64 Packages
#8 1.385 Ign:6 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
#8 1.543 Ign:10 http://deb.debian.org/debian stretch/main all Packages
#8 1.574 Ign:8 http://security.debian.org/debian-security stretch/updates/main all Packages
#8 1.729 Ign:11 http://deb.debian.org/debian stretch-updates/main amd64 Packages
#8 1.764 Ign:6 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
#8 1.914 Ign:12 http://deb.debian.org/debian stretch-updates/main all Packages
#8 1.956 Ign:8 http://security.debian.org/debian-security stretch/updates/main all Packages
#8 2.117 Ign:9 http://deb.debian.org/debian stretch/main amd64 Packages
#8 2.145 Ign:6 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
#8 2.302 Ign:10 http://deb.debian.org/debian stretch/main all Packages
#8 2.336 Ign:8 http://security.debian.org/debian-security stretch/updates/main all Packages
#8 2.488 Ign:11 http://deb.debian.org/debian stretch-updates/main amd64 Packages
#8 2.525 Ign:6 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
#8 2.674 Ign:12 http://deb.debian.org/debian stretch-updates/main all Packages
#8 2.715 Ign:8 http://security.debian.org/debian-security stretch/updates/main all Packages
#8 2.860 Ign:9 http://deb.debian.org/debian stretch/main amd64 Packages
#8 2.906 Err:6 http://security.debian.org/debian-security stretch/updates/main amd64 Packages
#8 2.906   404  Not Found [IP: 151.101.66.132 80]
#8 3.045 Ign:10 http://deb.debian.org/debian stretch/main all Packages
#8 3.097 Ign:8 http://security.debian.org/debian-security stretch/updates/main all Packages
#8 3.230 Ign:11 http://deb.debian.org/debian stretch-updates/main amd64 Packages
#8 3.417 Ign:12 http://deb.debian.org/debian stretch-updates/main all Packages
#8 3.603 Ign:9 http://deb.debian.org/debian stretch/main amd64 Packages
#8 3.804 Ign:10 http://deb.debian.org/debian stretch/main all Packages
#8 3.991 Ign:11 http://deb.debian.org/debian stretch-updates/main amd64 Packages
#8 4.177 Ign:12 http://deb.debian.org/debian stretch-updates/main all Packages
#8 4.363 Ign:9 http://deb.debian.org/debian stretch/main amd64 Packages
#8 4.548 Ign:10 http://deb.debian.org/debian stretch/main all Packages
#8 4.733 Ign:11 http://deb.debian.org/debian stretch-updates/main amd64 Packages
#8 4.919 Ign:12 http://deb.debian.org/debian stretch-updates/main all Packages
#8 5.104 Err:9 http://deb.debian.org/debian stretch/main amd64 Packages
#8 5.104   404  Not Found [IP: 151.101.90.132 80]
#8 5.475 Ign:10 http://deb.debian.org/debian stretch/main all Packages
#8 5.662 Err:11 http://deb.debian.org/debian stretch-updates/main amd64 Packages
#8 5.662   404  Not Found [IP: 151.101.90.132 80]
#8 5.849 Ign:12 http://deb.debian.org/debian stretch-updates/main all Packages
#8 5.852 Reading package lists...
#8 5.859 W: The repository 'http://security.debian.org/debian-security stretch/updates Release' does not have a Release file.
#8 5.859 W: The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file.
#8 5.859 W: The repository 'http://deb.debian.org/debian stretch-updates Release' does not have a Release file.
#8 5.859 E: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/main/binary-amd64/Packages  404  Not Found [IP: 151.101.66.132 80]
#8 5.859 E: Failed to fetch http://deb.debian.org/debian/dists/stretch/main/binary-amd64/Packages  404  Not Found [IP: 151.101.90.132 80]
#8 5.859 E: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/main/binary-amd64/Packages  404  Not Found [IP: 151.101.90.132 80]
#8 5.859 E: Some index files failed to download. They have been ignored, or old ones used instead.
#8 ERROR: process "/bin/sh -c apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*" did not complete successfully: exit code: 100
------
 > [symbolicator-cleanup 4/5] RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*:
5.662   404  Not Found [IP: 151.101.90.132 80]
5.849 Ign:12 http://deb.debian.org/debian stretch-updates/main all Packages
5.852 Reading package lists...
5.859 W: The repository 'http://security.debian.org/debian-security stretch/updates Release' does not have a Release file.
5.859 W: The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file.
5.859 W: The repository 'http://deb.debian.org/debian stretch-updates Release' does not have a Release file.
5.859 E: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/main/binary-amd64/Packages  404  Not Found [IP: 151.101.66.132 80]
5.859 E: Failed to fetch http://deb.debian.org/debian/dists/stretch/main/binary-amd64/Packages  404  Not Found [IP: 151.101.90.132 80]
5.859 E: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/main/binary-amd64/Packages  404  Not Found [IP: 151.101.90.132 80]
5.859 E: Some index files failed to download. They have been ignored, or old ones used instead.
------
failed to solve: process "/bin/sh -c apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*" did not complete successfully: exit code: 100
Error in install/build-docker-images.sh:9.
'$dcb --force-rm "$service"' exited with status 17
-> ./install.sh:main:30
--> install/build-docker-images.sh:source:9

Looks like you've already sent this error to us, we're on it :)
Cleaning up...

**Comment by aldy505** [comment]
Can you check your `.env` file or `.env.custom` file, does it have the Docker image tag as specified like so?
https://github.com/getsentry/self-hosted/blob/2fe5499fd108f052057a1c9636b9028462fa1a9a/.env#L8-L12

For 24.4.1, you should see Debian version of `bullseye` or `bookworm` rather than `stretch`. Debian stretch is not available anymore on Debian repository, see https://www.debian.org/releases/stretch/
