### ISSUE TITLE
Upgrade from 23.12.1 to 24.4.1 failed

### ISSUE THREAD

**Issue by enricolucakindle** [getsentry/self-hosted#2991]
### Self-Hosted Version

23.12.1

### CPU Architecture

x86/64

### Docker Version

25.0.3

### Docker Compose Version

2.24.5

### Steps to Reproduce

1. Shut down all services using docker compose down
2. git fetch
3. git checkout 24.3.0
4. sudo ./install.sh
5. docker compose up -d

### Expected Result

Updated sentry instance running

### Actual Result

![image](https://github.com/getsentry/self-hosted/assets/119679524/32461163-ca7d-4a06-bd64-8f64cda91f31)

**Comment by aldy505** [comment]
By any chance are you running the `sudo ./install.sh` and `docker compose up -d` on a separate shell/terminal session? That's the usual case.

If you're not running a rootless Docker, meaning you originally needed `sudo` to run docker, you should do `sudo docker compose up -d` instead.

The `$BASE_IMAGE` environment variable should be acquired from previous `./install.sh` script, that is the usual suspect for this problem.

**Comment by enricolucakindle** [comment]
i just double checked and tried again from snapshot. i am logged in as root and running both on the same shell. 

i used sudo ./install.sh and sudo docker compose up -d

![image](https://github.com/getsentry/self-hosted/assets/119679524/17f7c774-eb31-4c10-b4c6-c1c5439a24ea)

Many thanks

**Comment by inoa-jboliveira** [comment]
Hi, we are having exactly the same issue, running from the same terminal both commands.
We are upgrading from 23.11 to 24.4.1

**Comment by azaslavsky** [comment]
Have you tried `sudo` as well with no luck?

**Comment by inoa-jboliveira** [comment]
@azaslavsky Yes, I ran everything as root (sudo su)

**Comment by azaslavsky** [comment]
Are you willing to try [docker system prune -a](https://github.com/getsentry/self-hosted/issues/1155#issuecomment-972992335) on this device, to clear any residual docker state? Note that this shouldn't cause loss of data in the volumes themselves, but state in the running containers will get dropped.

How long have you had this install for?

**Comment by inoa-jboliveira** [comment]
Hi @azaslavsky, I will give it a try after hours since this is a production server. This install we had for a couple years now. I believe we upgraded sentry 3 or 4 times on it.

Since the install removes all containers, wouldn't it somewhat reset or prune things same as this command you suggest?

**Comment by hubertdeng123** [comment]
Did the install script completely succeed? Maybe values in your .env file are not being picked up properly to your docker compose file? Specifically for VROOM?

**Comment by inoa-jboliveira** [comment]
@hubertdeng123 No, it did not work for me. FYI I'm running ubuntu 20.4 LTS with everything up to date.

I believe the ./install.sh script is simply dying too soon. In other versions it would show the docker compose command at the end, but now it doesn't show anything after this warning about memcache. Below is the end of the command output on my system

```sh

▶ Checking for latest commit ...
skipped

▶ Checking minimum requirements ...
Found Docker version 26.1.1
Found Docker Compose version 2.27.0

▶ Turning things off ...

▶ Creating volumes for persistent storage ...
Created sentry-clickhouse.
Created sentry-data.
Created sentry-kafka.
Created sentry-postgres.
Created sentry-redis.
Created sentry-symbolicator.
Created sentry-zookeeper.

▶ Ensuring files from examples ...
sentry/sentry.conf.py already exists, skipped creation.
sentry/config.yml already exists, skipped creation.
symbolicator/config.yml already exists, skipped creation.

▶ Checking memcached backend ...
MemcachedCache found in sentry/sentry.conf.py, you should switch to PyMemcacheCache.
See:
  https://develop.sentry.dev/self-hosted/releases/#breaking-changes
```

**Comment by inoa-jboliveira** [comment]
Hey, it sounds like this is not a warning but an actual error. You guys need a better way to convey this information...
"you should" -> "you must" and something like "install.sh finished with errors!" :(

When I changed memcached, the upgrade did work.

I also realized that my sentry.conf.py is never being updated with latest sentry.conf.example.py. Any ideas on how to have these in sync? or how should it be installed differently? I wasnt the one configuring this server for the 1st time, so I don't know if having this conf file different from the example is something that just happens or if someone actively did it.

**Comment by azaslavsky** [comment]
The reason this was a warning was because we don't know how folks have modified their setups post-install. Saying "must" implies we know it's definitely true for your setup, when that is not necessarily the case.

> I also realized that my sentry.conf.py is never being updated with latest sentry.conf.example.py. Any ideas on how to have these in sync? or how should it be installed differently? I wasnt the one configuring this server for the 1st time, so I don't know if having this conf file different from the example is something that just happens or if someone actively did it.

We avoid overwriting this for the same reason - people modify these files for various install-specific reasons all the time, and cogently syncing them in all such cases is a very hard problem. We've talked about moving to an "inheritance" setup where there is a sentry.default.conf.py that your file could overwrite, but we don't have that sort of thing on the road map or anything.

For now, we check for things that may need updating in the install script and surface messages to users at that time, making the assumption that they know their setups best.

**Comment by jerome2710** [comment]
I agree with @inoa-jboliveira, neither did I see this notice. The installation is cumbersome with dozens of Docker containers. It is always a hassle to bring Sentry back up once it fails or after an update.

My setup is thankfully working again. I updated the `sentry.conf.py` and executed the exports from `detect-platform.sh` myself: https://github.com/getsentry/self-hosted/blob/24.4.1/install/detect-platform.sh#L22. After running docker-compose fetch/pull/build/force-recreate everything, the application is now up.

**Comment by enricolucakindle** [comment]
I tried today these steps:

1. docker system prune -a
2. docker compose down 
3. git status
4. git fetch
5. git checkout 
6. sudo ./install.sh

There was no error anymore running the install script, but when i started the containers (docker compose up -d), there was another problem: 

![image](https://github.com/getsentry/self-hosted/assets/119679524/c5e343bd-1571-466a-a918-da0d4e9c5f66)

**Comment by hubertdeng123** [comment]
Those errors should not be happening when you're trying to bring your docker containers up. It indicates to me that your docker containers have not been properly built before running `docker compose up -d`. Could you try running the install script without sudo?

**Comment by hubertdeng123** [comment]
Just to be sure, is your sentry.conf.py specifying PyMemcacheCache as the backend?

**Comment by enricolucakindle** [comment]
i still didn't have time to solve this, will post an update asap

**Comment by enricolucakindle** [comment]
finally i could get into this.  i changed the cache config with pymemcache and now it works

thanks!
