### ISSUE TITLE
Fresh OS with fresh sentry installation ends in starting loop

### ISSUE THREAD

**Issue by RosskoDCA** [getsentry/self-hosted#3004]
### Self-Hosted Version

24.4.1

### CPU Architecture

x86_64

### Docker Version

26.0.1

### Docker Compose Version

2.26.1

### Steps to Reproduce

1. sudo install.sh
2. docker compose up -d

### Expected Result

running containers

### Actual Result

see attaching docker log file
[dockerlog.txt](https://github.com/getsentry/self-hosted/files/15158279/dockerlog.txt)

after installation cpu on server goes to 500% and server is barely useable 
![image](https://github.com/getsentry/self-hosted/assets/6154492/9f366236-907e-46f7-8d62-0a359f3a9445)

when i stop and discard containers with docker compose down, cpu goes to 0%
![image](https://github.com/getsentry/self-hosted/assets/6154492/762873bd-77fc-4e9a-a626-b99c9554710e)

i believe, there's some strange problem with spinning containers

Also I want to mention that I was trying same procedure like 2 weeks ago on previous version with same result. Also I tried much older version, but it was not installable, there was error in missing dependency in repository or something.

**Comment by RosskoDCA** [comment]
i am attaching installation log and response from `lshw` 
[sentry_install_log-2024-04-30_04-08-24.txt](https://github.com/getsentry/self-hosted/files/15164042/sentry_install_log-2024-04-30_04-08-24.txt)

[hw.zip](https://github.com/getsentry/self-hosted/files/15164048/hw.zip)

**Comment by hubertdeng123** [comment]
How much CPU/RAM do you have on your machine?

**Comment by RosskoDCA** [comment]
8gb

**Comment by hubertdeng123** [comment]
We recommend 16 GB of RAM as a part of our minimum requirements in our readme. You should try and bump the amount of RAM accordingly

**Comment by RosskoDCA** [comment]
I rescale server to 16GB ram, made fresh install ubuntu 24.04, docker , Docker Compose version v2.27.0, Docker version 26.1.1 but same result, can not start all containers successfully.
Installation log is attached
[sentry_install_log-2024-05-06_05-06-38.txt](https://github.com/getsentry/self-hosted/files/15216888/sentry_install_log-2024-05-06_05-06-38.txt)

**Comment by RosskoDCA** [comment]
There are some python errors in installation log
```
2024-05-06 05:11:33,612 Attempting to connect to Kafka (attempt 0)...
2024-05-06 05:11:33,668 Connected to Kafka on attempt 0
2024-05-06 05:11:33,729 Creating Kafka topics...
2024-05-06 05:11:34,732 Failed to create topic events

Traceback (most recent call last):
  File "/usr/src/snuba/snuba/utils/manage_topics.py", line 31, in create_topics
    future.result()

etc.
```

**Comment by azaslavsky** [comment]
How much CPU (or vCPU) are you allocating for this? Are you running it on a cloud service (GCP, AWS, etc)?

**Comment by RosskoDCA** [comment]
I don't know how, but after stopping and starting containers again it somehow starts after feww minutes. It's strange behaviour, but I believe the main problem was the amout of ram. (By the way, in documentation here https://develop.sentry.dev/self-hosted/ is mentioned 4gb ram)
