### ISSUE TITLE
Service 'clickhouse' failed to build : base name (${BASE_IMAGE}) should not be blank

### ISSUE THREAD

**Issue by jerome2710** [getsentry/self-hosted#3010]
### Self-Hosted Version

24.4.2

### CPU Architecture

x86_64

### Docker Version

25.0.2

### Docker Compose Version

2.24.5

### Steps to Reproduce

I created a fresh install of Sentry with the current latest version of 24.4.2

### Expected Result

After successfully running `./install.sh` and running `docker-compose up -d`, I would expect the services to start.

### Actual Result

Some service called 'clickhouse' failed to build:

```bash
$ docker-compose up -d --force-recreate
Building clickhouse
Step 1/2 : ARG BASE_IMAGE
Step 2/2 : FROM ${BASE_IMAGE}
ERROR: Service 'clickhouse' failed to build : base name (${BASE_IMAGE}) should not be blank
```

**Comment by hubertdeng123** [comment]
Did you manage to complete the install script successfully? That's telling me that your clickhouse service hasn't been built properly

**Comment by jerome2710** [comment]
I agree with @inoa-jboliveira in https://github.com/getsentry/self-hosted/issues/2991#issuecomment-2092023065, neither did I see this notice. The installation is cumbersome with dozens of Docker containers. It is always a hassle to bring Sentry back up once it fails or after an update.

My setup is thankfully working again. I updated the `sentry.conf.py` and executed the exports from `detect-platform.sh` myself: https://github.com/getsentry/self-hosted/blob/24.4.1/install/detect-platform.sh#L22. After running docker-compose fetch/pull/build/force-recreate everything, the application is now up.

I would greatly encourage and appreciate if the setup was not so complex.

**Comment by hubertdeng123** [comment]
Thanks for the feedback. I am going to close this issue since it looks to be resolved.
