### ISSUE TITLE
no health check inbound filter

### ISSUE THREAD

**Issue by vanyakosmos** [getsentry/self-hosted#3011]
### Self-Hosted Version

23.6.1

### CPU Architecture

x86_64

### Docker Version

24.0.5

### Docker Compose Version

1.29.2

### Steps to Reproduce

open any project setting and go to inbound filters

### Expected Result

there is health check filter

### Actual Result

not health check filter

**Comment by hubertdeng123** [comment]
You may need to upgrade in order to see the setting. We are seeing the health check filter checkbox on our own instance.
