### ISSUE TITLE
sentry web: slow page loading time

### ISSUE THREAD

**Issue by vanyakosmos** [getsentry/self-hosted#3013]
### Self-Hosted Version

23.6.1

### CPU Architecture

x86_64

### Docker Version

24.0.5

### Docker Compose Version

1.29.2

### Steps to Reproduce

Open any sentry page

### Expected Result

Fast page load

### Actual Result

Slow page load, and sometimes it can just stuck indefinitely. Everything that goes to `web` service is suffering: emails loading, static files loading, initial page html loading.

My server has 6 cpus and 32gb RAM. I configured sentry web to use 9 uwsgi workers. Traffic is pretty moderate, only 8gb of memory is used and cpus are not overloaded.

At the time of "testing" I was probably the only person in the company who accessed sentry web. Problems occur at somewhat random time, one moment everything is fine, and the next one everything is slow as hell. If I open 5 tabs at the same time then everything will open veeery slowly (if ever).

How to debug something like this? At first glance everything should be fine... 
Postgres works fine and some endpoints that do not use it are also lagging (eg static files).

**Comment by hubertdeng123** [comment]
Hi there, thanks for writing in. Unfortunately it is hard to debug this problem without additional information. Is there any logs that may be of use in your web service?

**Comment by vanyakosmos** [comment]
mainly access logs and some pydantic warnings, no error:

![Screenshot 2024-05-06 at 09 25 33](https://github.com/getsentry/self-hosted/assets/16745500/76ecc7cc-ea75-4f6f-abac-81bc0e19c2b9)

in general page loading looks like this (requests are sorted by response time):

![Screenshot 2024-05-06 at 09 28 43](https://github.com/getsentry/self-hosted/assets/16745500/3fddd0fc-94f2-4544-b7cc-16bd61ae9522)

**Comment by azaslavsky** [comment]
Can you check CPU, memory, and network usage during these episodes? I would imagine some resource is being saturated.

**Comment by vanyakosmos** [comment]
this is what I see after opening 5 tabs at the same time:
![Screenshot 2024-05-08 at 10 43 30](https://github.com/getsentry/self-hosted/assets/16745500/af40007b-d96f-4113-95e7-238f1e5e6103)

- single uwgi worker is doing all the job without parallelization
- redis ate 20gb of memory
- relay workers are also underutilized (it is strange but unrelated to the current issue)

right now I have an even bigger machine (with enough memory, which might have been a problem in a previous case), but the lags are still the same:

![Screenshot 2024-05-08 at 19 12 57](https://github.com/getsentry/self-hosted/assets/16745500/22e7d7a6-a13b-4732-bfb7-9ab6bdcf586b)

**Comment by azaslavsky** [comment]
Have you tried setting a memory limit for redis, a la https://github.com/getsentry/self-hosted/issues/2262?
