### ISSUE TITLE
Postgres issue while upgrading

### ISSUE THREAD

**Issue by hubertdeng123** [getsentry/self-hosted#3014]
### Self-Hosted Version

24.4.2

### CPU Architecture

x86_64

### Docker Version

n/a

### Docker Compose Version

n/a

### Steps to Reproduce

Upgrading to 24.4.2+ is giving some users issues. This is taken from discord

1. ./install.sh
2. See error below
```
Running migrations for default
Operations to perform:
  Apply all migrations: auth, contenttypes, feedback, hybridcloud, nodestore, replays, sentry, sessions, sites, social_auth
Running migrations:
Alert Rules: 100% |#                                           | ETA:  --:--:--
 OK
  Applying sentry.0702_alert_rule_project_backfill_migration_2... OK
  Applying sentry.0703_add_team_user_to_rule... OK
Rules: 100% |##################################################| Time:  0:00:00
 OK
  Applying sentry.0705_grouphistory_add_userteam... OK
Group Historys: 100% |#########################################| Time:  0:00:00
 OK
  Applying sentry.0707_alert_rule_activations_incidents_fk... OK
  Applying sentry.0708_rule_remove_owner_state... OK
Creating missing DSNs
Correcting Group.num_comments counter
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sentry/db/postgres/decorators.py", line 91, in inner
    return func(self, sql, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry/db/postgres/base.py", line 84, in execute
    return self.cursor.execute(sql, clean_bad_params(params))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.IndexCorrupted: table tid from new index tuple (20,3) overlaps with invalid duplicate tuple at offset 7 of block 8 in index "sentry_groupedmessage_logger_993cb6d5"
```

### Expected Result

no error

### Actual Result

error

**Comment by hubertdeng123** [comment]
Possible solution from @Friberg on discord:

1. ./install.sh
Once install.sh runs into the issue, start postgres by issuing docker compose up -d postgres then run docker compose exec -it postgres bash
2. Inside postgres container, run su - postgres
3. Then psql
4. Inside psql-terminal run REINDEX (VERBOSE) TABLE CONCURRENTLY sentry_groupedmessage; and then exit container
5. Shutdown postgres by docker compose down
6. Rerun ./install.sh
7. If it finishes without issues, run docker compose up -d to start Sentry

Ok, so the solution worked! The full flow for me was:
1. docker compose down
2. git stash (I've got a few local changes to docker-compose.yml, nginx/nginx.conf and .env)
3. git fetch
4. git checkout 24.4.2
5. ./install.sh
6. Once install.sh runs into the issue, start postgres by issuing `docker compose up -d postgres` then run `docker compose exec -it postgres bash`
  a. Inside postgres container, run `su - postgres`
  b. Then `psql`
  c. Inside psql-terminal run `REINDEX (VERBOSE) TABLE CONCURRENTLY sentry_groupedmessage;` and then exit container
7. Shutdown postgres by `docker compose down`
8. Rerun `./install.sh`
9. If it finishes without issues, run `docker compose up -d` to start Sentry

https://discord.com/channels/621778831602221064/796028405833007104/1235624852564611106

**Comment by aldy505** [comment]
Didn't encountered the migration error when not using the alpine image (meaning continue using the debian image)

```diff
diff --git a/docker-compose.yml b/docker-compose.yml
index 9cc58dd..cb800ad 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -132,7 +132,7 @@ services:
   postgres:
     <<: *restart_policy
     # Using the same postgres version as Sentry dev for consistency purposes
-    image: "postgres:14.11-alpine"
+    image: "postgres:14.11"
     healthcheck:
       <<: *healthcheck_defaults
       # Using default user "postgres" from sentry/sentry.conf.example.py or value of POSTGRES_USER if provided
```

**Comment by tm1000** [comment]
What @aldy505 posted worked for me as well

note you can create a `docker.override.yml` file instead of editing docker-compose.yml directly (which is tracked)

docker.override.yml
```
services:
    postgres:
      # https://github.com/getsentry/self-hosted/issues/3014
      image: "postgres:14.11"
```

Ref: #3027

**Comment by hubertdeng123** [comment]
Going to close this due to https://github.com/getsentry/self-hosted/pull/3116
