### ISSUE TITLE
How to configure kafka client config

### ISSUE THREAD

**Issue by kimxogus** [getsentry/self-hosted#3018]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### What are you trying to accomplish?

I want to configure rdkafka's `clinet.id` and `partition.assignment.strategy` in sentry's `conf.py`.

### How are you getting stuck?

I tried to set sentry config.py file in 3 ways as below, but they didn't work.
```python
KAFKA_CLUSTERS["default"]["common"]["client.id"] = "my-client-id"
or
KAFKA_CLUSTERS["default"]["consumers"]["client.id"] = "my-client-id"
or
KAFKA_CLUSTERS["default"]["client.id"] = "my-client-id"
```

I referred [here](https://github.com/getsentry/sentry/blob/5bff6b7d5a87801b86adffd48acf9a817d793352/src/sentry/conf/server.py#L3412)

### Where in the product are you?

Other

### Version

24.2.0

**Comment by hubertdeng123** [comment]
That seems like it would be the right way to go about things. Did you try rerunning the install script after making these changes?

**Comment by kimxogus** [comment]
@hubertdeng123 What is the install script? I installed sentry with [k8s helm chart](https://github.com/sentry-kubernetes/charts/tree/develop/sentry).

**Comment by azaslavsky** [comment]
We don't offer support for the k8s setup specified in that repository - this repository only supports the docker-compose.yml setup we have here. `sentry-kubernetes` seems like a better place to go for further guidance.
