### ISSUE TITLE
Doesn't detect docker even though its installed and in PATH

### ISSUE THREAD

**Issue by coolaj86** [getsentry/self-hosted#3025]
## Update: Possible Solutions

Rather than instructing the user to use `sudo` prematurely, the install script could detect whether or not the current user has permissions to the `docker` group, or ask the user if they really want to `sudo`:

```sh
if ! groups | grep -q docker; then
    echo "$(id -u -n) is not a member of the group 'docker'"
    echo "Possible solutions:"
    echo "    sudo useradd '$(id -u -n)' 'docker' ; bash ./install.sh"
    echo "Or"
    echo "    sudo bash ./install.sh"
fi
```

Or

```sh
g_sudo=''
if ! groups | grep -q docker; then
    echo "$(id -u -n) is not a member of the group 'docker'"
    printf "Run using 'sudo'? [y/N] "
    read g_use_sudo
    if test "$g_use_sudo" = "y" || test "$g_use_sudo" = "yes"; then
        g_sudo='sudo'
    fi
fi
$g_sudo docker ...
```

In either case, if `sudo` is selectively used only for things that need `sudo`, it is less likely to cause permission or environment-related issues.

### Self-Hosted Version

24.4.2

### CPU Architecture

x86_64

### Docker Version

25.0.5

### Docker Compose Version

2.26.1

### Steps to Reproduce

```sh
command -v docker
```

```text
/home/app/.local/opt/docker/bin/docker
```

```sh
VERSION="24.4.2"
git clone https://github.com/getsentry/self-hosted.git
cd ./self-hosted/
git checkout ${VERSION}
sudo ./install.sh
```

```text
HEAD is now at 935a683 release: 24.4.2
� Parsing command line ...

� Detecting Docker platform
FAIL: Could not find a `docker` binary on this system. Are you sure it's installed?
```

### Expected Result

Should detect docker from the current `PATH`.

### Actual Result

Used something other than `PATH`.

**Comment by coolaj86** [comment]
What I actually had done was this:

`sentry-install.sh`:
```sh
# Assuming current latest version is 24.1.0
# Current actual version can be acquired from the Releases page on GitHub
VERSION="24.4.2"
git clone https://github.com/getsentry/self-hosted.git
(
        cd self-hosted || exit 1
        git checkout "${VERSION}"
        sudo ./install.sh
)
```

```sh
sh ./sentry-install.sh
```

By happenstance while debugging I manually went into `./self-hosted/` and ran `bash ./install.sh` (not `sudo`) and now it's gotten much further:

```text
Relay credentials written to relay/credentials.json.

� Generating secret key ...
Secret key written to sentry/config.yml

� Fetching and updating Docker images ...
```

and still going

So this issue is probably related to trying to using `sudo` where it isn't needed.

## Possible Solution

This should probably instead checking that the current user has permissions to docker rather than trying to elevate permissions prematurely:

```sh
if ! groups | grep -q docker; then
    echo "$(id -u -n) is not a member of the group 'docker'"
    echo "Possible solutions:"
    echo "    sudo useradd '$(id -u -n)' 'docker' ; bash ./install.sh"
    echo "Or"
    echo "    sudo bash ./install.sh"
fi
```

**Comment by azaslavsky** [comment]
Good solution.

I think we'd welcome a PR to this effect if you'd be so inclined!
