### ISSUE TITLE
Can Sentry currently support using MySQL instead of PostgreSQL? If so, how should it be configured?

### ISSUE THREAD

**Issue by CoderX-Aaron** [getsentry/self-hosted#3031]
### Self-Hosted Version

latest

### CPU Architecture

x86_64

### Docker Version

24.0.2

### Docker Compose Version

1.17.1

### Steps to Reproduce

1. I commented out the PostgreSQL-related configurations and added MySQL connection configurations in the [sentry.conf.example.py](http://sentry.conf.example.py/) file under the Sentry directory.
```python
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'sentry',
        'USER': 'root',
        'PASSWORD': 'sentry_admin',
        'HOST': '10.11.20.238',
        'PORT': '3306',
    }
}
```
2. And added the following instructions in the Dockerfile file under the Sentry directory.

```dockerfile
RUN apt-get update && apt-get install -y  build-essential pkg-config libmariadb-dev-compat libmariadb-dev
RUN pip install mysqlclient
```

### Expected Result

I hope that Sentry can be installed and run normally, and create table structures and data in MySQL.

### Actual Result

I hope that Sentry can be installed and run normally, and create table structures and data in MySQL.
However, during the installation process, I found that after connecting to the database, it still executes PostgreSQL statements and reports the following error.
```bash
MySQLdb.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF EXISTS sentry_groupedmessage DROP CONSTRAINT IF EXISTS sentry_groupedmessage_' at line 1")
```
So I want to know a definite answer, does Sentry currently support using MySQL? If it does, what additional configurations are needed?

**Comment by ktosiek** [comment]
Sentry doesn't work on MySQL, see: https://github.com/getsentry/sentry/issues/31753

Sentry dropped support for MySQL around 2015 (in version 8.0.0), when it was still supporting a more monolithic setup. With the current "self-hosted is a miniature sentry.io" approach I don't think support for different database backends is coming back.

**Comment by CoderX-Aaron** [comment]
> Sentry doesn't work on MySQL, see: [getsentry/sentry#31753](https://github.com/getsentry/sentry/issues/31753)
> 
> Sentry dropped support for MySQL around 2015 (in version 8.0.0), when it was still supporting a more monolithic setup. With the current "self-hosted is a miniature sentry.io" approach I don't think support for different database backends is coming back.

Okay, thank you for your response.
