### ISSUE TITLE
Service migration issue

### ISSUE THREAD

**Issue by swenker** [getsentry/self-hosted#3032]
### Self-Hosted Version

23.7.2

### CPU Architecture

x86_64

### Docker Version

24.0.9

### Docker Compose Version

2.27.0

### Steps to Reproduce

1.install sentry on **Server1**  and make sure it works well;
2.stop docker service on **Server1**
3. copy the full docker data folder(/var/lib/docker) from **Server1** to **Server2**.
4. start docker service on **Server2**
5. on **Server2** docker-compose up -d

### Expected Result

the service on Server2 works well .

### Actual Result

I can login and view the projects and issues under projects. but the request http://**server2**:9000/organizations/myorg-sentry/issues/ doesn't work.
I check browser console, there's request like this http://**server1**:9000/api/1/envelope/?sentry_key=e86296ce46df9af06d9e99d56ff941c7&sentry_version=7&sentry_client=sentry.javascript.react%2F7.60.1' 

and this leads to" Content Security Policy" issue in browser.

Now it seems all the others features works well except this one.

Do you guys know how I can fix this issue?

**Comment by azaslavsky** [comment]
Did you run `./install.sh` on server 2? It configures your server in ways that I don't think are entirely captured by docker exports (ex: the config file lives in the `self-hosted` repo, not inside docker).

**Comment by swenker** [comment]
> Did you run `./install.sh` on server 2? It configures your server in ways that I don't think are entirely captured by docker exports (ex: the config file lives in the `self-hosted` repo, not inside docker).

mm, I didn't run install.sh because Server2 couldn't connect to internet.  That's why I copied all the docker data folder from Server1 to Server2.   
As to the result , it seems the Server1 address  is saved ?  I searched both docker data folder and sentry folder(containing install.sh )  nothing found. Maybe it's saved in some database table of sentry?

**Comment by hubertdeng123** [comment]
We would highly recommend you to run install.sh on Server2 to make sure the config changes are picked up. I would suspect the address is saved somewhere in postgres but unsure exactly where.

**Comment by swenker** [comment]
I tried execute install.sh on Server2  , it shows internet connection is needed. So it failed .

I also tried to clean the issues by the following steps :
1. login to sentry worker container and execute :  sentry cleanup --days 3000
2. login to postgres container and do VACUUM FULL;
what I expected is that all the issues should be removed. But there are still some items left.

do you have a more detailed guide on how to clean the data in sentry  except the admin user?

**Comment by azaslavsky** [comment]
An instance can't really be created without running install.sh. More generally, we didn't really design the install and setup process to work offline, because a self-hosted server requires an internet connection anyway.

**Comment by swenker** [comment]
> An instance can't really be created without running install.sh. More generally, we didn't really design the install and setup process to work offline, because a self-hosted server requires an internet connection anyway.

Ok, got that. 
BTW,  I encountered the following errors sometimes. Is it due to network issues? 

`▶ Detecting Docker platform
Detected Docker platform is linux/amd64

▶ Initializing Docker Compose ...

▶ Setting up error handling ...
Sending build context to Docker daemon  2.048kB
Step 1/4 : FROM debian:bookworm-slim
 ---> 6abae0db1e5b
Step 2/4 : LABEL MAINTAINER="oss@sentry.io"
 ---> Using cache
 ---> ebee580cd28c
Step 3/4 : RUN set -x   && apt-get update   && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends jq   && apt-get clean   && rm -rf /var/lib/apt/lists/*
 ---> Running in 4f207fe087a4
+ apt-get update
Get:1 http://security.debian.org/debian-security bookworm-security InRelease [2281 B]
Get:2 http://deb.debian.org/debian bookworm InRelease [2281 B]
Err:1 http://security.debian.org/debian-security bookworm-security InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Err:2 http://deb.debian.org/debian bookworm InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Get:3 http://deb.debian.org/debian bookworm-updates InRelease [2281 B]
Err:3 http://deb.debian.org/debian bookworm-updates InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Reading package lists...
E: The repository 'http://security.debian.org/debian-security bookworm-security InRelease' is not signed.
E: Failed to fetch http://security.debian.org/debian-security/dists/bookworm-security/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: Failed to fetch http://deb.debian.org/debian/dists/bookworm/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'http://deb.debian.org/debian bookworm InRelease' is not signed.
E: Failed to fetch http://deb.debian.org/debian/dists/bookworm-updates/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'http://deb.debian.org/debian bookworm-updates InRelease' is not signed.
`

**Comment by swenker** [comment]
finally I found the config item in /manage/status/environment/ ,  
```
SENTRY_URL_PREFIX
'http://ServerA:9000'
```
It can be changed within  "Settings" -> "Root URL"

Thanks for your support.

**Comment by swenker** [comment]
finally I found the config item in /manage/status/environment/ ,  
```
SENTRY_URL_PREFIX
'http://ServerA:9000'
```
It can be changed within  "Settings" -> "Root URL"

Thanks for your support.

**Comment by swenker** [comment]
finally I found the config item in /manage/status/environment/ ,  
```
SENTRY_URL_PREFIX
'http://ServerA:9000'
```
It can be changed within  "Settings" -> "Root URL"

Thanks for your support.

**Comment by hubertdeng123** [comment]
Thanks for the writeup, and I'm glad you were able to get your instance working. Is there anything else we can help you with?

**Comment by swenker** [comment]
Really appreciated for all your help.  
All the issues I ever met have been resolved. 
By the way ,the env SENTRY_URL_PREFIX  can also be modified by changing  sentry/config.yml . I think it should be the more elegant way to achieve this. Other items such mail can also be config like this.

**Comment by hubertdeng123** [comment]
That's good to hear. I'm going to go ahead and close this issue then.
