### ISSUE TITLE
What is default Sentry application local user password encryption method ?

### ISSUE THREAD

**Issue by phamp008** [getsentry/self-hosted#3038]
### Self-Hosted Version

22.8

### CPU Architecture

x86_64

### Docker Version

23.0.5

### Docker Compose Version

1.18.0

### Steps to Reproduce

What is default Sentry application local user password encryption method ?

### Expected Result

n/a

### Actual Result

n/a

**Comment by aldy505** [comment]
To be honest, I don't know but let's do a dive to the source code.

It uses Django's auth mechanism, see https://docs.djangoproject.com/en/5.0/topics/auth/default/#how-to-log-a-user-in

Here's the code for login endpoint https://github.com/getsentry/sentry/blob/bedf1ff007b9dd164f41e6162d97f534ecb42ee9/src/sentry/api/endpoints/auth_login.py#L30-L82

That function calls to this `login` method https://github.com/getsentry/sentry/blob/bedf1ff007b9dd164f41e6162d97f534ecb42ee9/src/sentry/utils/auth.py#L287-L358

Here are the defined `AUTHENTICATION_BACKENDS` https://github.com/getsentry/sentry/blob/bedf1ff007b9dd164f41e6162d97f534ecb42ee9/src/sentry/conf/server.py#L551-L559

Here's the `EmailAuthBackend` class https://github.com/getsentry/sentry/blob/bedf1ff007b9dd164f41e6162d97f534ecb42ee9/src/sentry/utils/auth.py#L407-L440

The `user.check_password()` method refer to this Django method https://docs.djangoproject.com/en/5.0/topics/auth/passwords/

And.. according to the Django's documentation, it's PBDKF2.

Hopefully that answers your question, and hopefully the way I trace the source code also helps you to find out some other things if you're still curious :smiley:
