### ISSUE TITLE
Excessive resource consumption (Sentry release 24.4.1)

### ISSUE THREAD

**Issue by brunis** [getsentry/self-hosted#3047]
### Self-Hosted Version

24.4.1

### CPU Architecture

x86_64

### Docker Version

24.0.5

### Docker Compose Version

2.20.2

### Steps to Reproduce

1. start up sentry with 'docker compose up -d'

### Expected Result

Sentry shouldn't be using excessive resources constantly.

### Actual Result

**Example 1:**
%Cpu(s): 44.9 us, 10.0 sy,  0.0 ni, 32.0 id, 11.2 wa,  0.0 hi,  1.9 si,  0.0 st
MiB Mem :  15989.5 total,   1330.9 free,  11444.8 used,   3213.8 buff/cache
MiB Swap:  20480.0 total,  17310.8 free,   3169.2 used.   4195.1 avail Mem

**It needs an additional 3+ GB of swap besides the "recommended specs"** 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
  60456 omi       20   0  536140  94076   2876 R  87.4   0.6  18:31.03 sentry
 193511 omi       20   0  218344 141528  33144 R  61.8   0.9   0:01.86 sentry
  51277 omi       20   0 5821860   3.9g   1776 S  11.0  25.1   2:33.35 redis-server
  53045 root      20   0 5937388 371200  11048 S   5.6   2.3   1:08.33 java

**Sometimes it's just one sentry process.. but then there is a python process instead:**
  60456 omi       20   0  536140  94092   2876 S  80.8   0.6  29:02.38 sentry
 259285 omi       20   0  218364 141428  32904 R  61.9   0.9   0:01.87 python
 259232 omi       20   0 1217332 220652  47412 S  36.1   1.3   0:03.58 sentry
  51277 omi       20   0 5821860   3.3g   1776 R  10.9  21.4   3:54.12 redis-server
  52117 systemd+  20   0 2761956  92540  54408 S   5.6   0.6   1:55.64 clickhouse-serv

**Comment by aldy505** [comment]
Hello!

Yeah, sadly this is a known problem and everyone's not happy about it. There's an issue already about it though https://github.com/getsentry/self-hosted/issues/1763. You can also see this issue if you're interested: https://github.com/getsentry/self-hosted/issues/2539.

I'm going to close this issue as duplicate. Feel free to add more comments (or rants) on the issue I linked above!
