### ISSUE TITLE
 Issue Encountered: Invitation and 2FA Configuration

### ISSUE THREAD

**Issue by adminstudio** [getsentry/self-hosted#3048]
### Self-Hosted Version

24.3.0.dev0

### CPU Architecture

x86_64

### Docker Version

24.0.2

### Docker Compose Version

2.18.1

### Steps to Reproduce

I am using On-Premise docker sentry. 
Upon receiving the invitation email and clicking on the invite link, I encountered an error message stating, "No Organization Access." Despite following the instructions provided, I am unable to gain access to any organizations within Sentry.

Additionally, I experienced difficulties when attempting to configure two-factor authentication (2FA) after enabling it. The process seemed to get stuck in a loop, preventing me from completing the configuration successfully.

### Expected Result

![Uploading Screenshot from 2024-05-13 12-51-59.png…]()

### Actual Result

sentry-self-hosted-web-1                                           | 08:13:16 [INFO] sentry.access.api: api.access (method='GET' view='sentry.web.frontend.twofactor.TwoFactorAuthView' response=200 user_id='None' is_app='None' token_type='None' is_frontend_request='True' organization_id='None' auth_id='None' path='/auth/2fa/' caller_ip='....' user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.029494762420654297 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
sentry-self-hosted-web-1

**Comment by adminstudio** [comment]
![Screenshot from 2024-05-13 12-51-59](https://github.com/getsentry/self-hosted/assets/41367758/0f5c29c4-2295-4b1d-a25d-efcc010a1307)

**Comment by hubertdeng123** [comment]
Have you ensured that you are logged out of any other Sentry accounts before clicking on the link?

**Comment by adminstudio** [comment]
Thanks for your response. Yes, I logged out of the other Sentry accounts before clicking on the link. Yesterday, I updated to the latest version (Sentry 24.5.0.dev0), and so far, I haven't had any problems.
