### ISSUE TITLE
No Sentry DSN link - link invisible / non present

### ISSUE THREAD

**Issue by lcsvcn** [getsentry/self-hosted#3050]
### Self-Hosted Version

Sentry 24.4.2

### CPU Architecture

x86_64

### Docker Version

Docker version 26.1.2, build 211e74b

### Docker Compose Version

Docker Compose version v2.27.0

### Steps to Reproduce

1. Install application
2. Create project

### Expected Result

DSN would appear.

### Actual Result

NO DSN, see image below:
<img width="912" alt="Screenshot 2024-05-13 at 17 30 03" src="https://github.com/getsentry/self-hosted/assets/6011385/389e3ddb-e512-495b-83d6-e83eb338452b">

Delete and recreate key doesnt work

**Comment by lcsvcn** [comment]
Security Header Endpoint and other below appear like:

/api/5/security/?sentry_key=SECRET_KEY

**Comment by lcsvcn** [comment]
creating any new project looks like this:
<img width="1108" alt="Screenshot 2024-05-13 at 17 37 33" src="https://github.com/getsentry/self-hosted/assets/6011385/02131b4b-fc79-458e-a14a-31f21b1f90e7">

**Comment by aldy505** [comment]
Hello, this is a common issue that probably we should address this more clearly.

You should set the `system.url-prefix` to the domain that your Sentry instance is most accessible from:

https://github.com/getsentry/self-hosted/blob/9de4b70ece8b28d83d4b2e4a4b642ff14af52ae0/sentry/config.example.yml#L81-L82

**Comment by lcsvcn** [comment]
ok, thanks that worked!
