### ISSUE TITLE
How to change the default value of  Filter Time Range Select to 24H 

### ISSUE THREAD

**Issue by snowair** [getsentry/self-hosted#3054]
### Environment

Self-hosted

### What are you trying to accomplish?

Change the default selected one to Last 24 Hours

![image](https://github.com/getsentry/sentry/assets/1695133/97c3f793-6160-4b53-a11e-3314aaac6b0f)

### How are you getting stuck?

no

### Where in the product are you?

Issues

### Version

24.4.2

**Comment by aldy505** [comment]
There's no configuration for this anywhere. So basically if you want to set it to 24 hours to the entire organization/team, it's not possible.
