### ISSUE TITLE
Make CSRF optional

### ISSUE THREAD

**Issue by maverick-ai** [getsentry/self-hosted#3067]
### Problem Statement

I have successfully installed Sentry with self hosted method and no CSRF verification issue. But when I tunnel using zrok (open source alternative to ngrok) it shows CSRF Verification Failed. I know the reason is that the domain has changed. But what I wanted is that Can I disable CSRF altogether. I do not need that security feature. CSRF should be optional not compulsory

### Solution Brainstorm

Make CSRF optional and not compulsory

**Comment by aldy505** [comment]
I believe you're the one [asking on Discord earlier](https://discord.com/channels/621778831602221064/621778831602221072/1242175819816767560).

Sadly, no.. CSRF verification is something that's enforced not only by Sentry, but by Django itself. See this link for further documentation about it on Django side: https://docs.djangoproject.com/en/4.2/ref/settings/#std-setting-CSRF_TRUSTED_ORIGINS

**Comment by maverick-ai** [comment]
Yeah
