### ISSUE TITLE
Container is running, but application isnt accessible

### ISSUE THREAD

**Issue by lcsvcn** [getsentry/self-hosted#3068]
### Self-Hosted Version

Sentry 24.4.2

### CPU Architecture

x86_64

### Docker Version

Docker version 26.1.2, build 211e74b

### Docker Compose Version

Docker Compose version v2.27.0

### Steps to Reproduce

application is running ok on all containers but I can't access it on web:
<img width="1352" alt="Screenshot 2024-05-20 at 15 29 15" src="https://github.com/getsentry/self-hosted/assets/6011385/ff3439e4-861c-4ed9-bfdb-b162784efc54">

### Expected Result

application run sucessfully

### Actual Result

 Socket is not connected, Stack trace (when copying this message, always include the lines below):
clickhouse-1                                    | 2024-05-20T18:30:47.941977622Z 
clickhouse-1                                    | 2024-05-20T18:30:47.941982291Z 0. Poco::Net::SocketImpl::error(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x13c4ee8e in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:47.941986925Z 1. Poco::Net::SocketImpl::peerAddress() @ 0x13c510d6 in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:47.941991224Z 2. DB::ReadBufferFromPocoSocket::ReadBufferFromPocoSocket(Poco::Net::Socket&, unsigned long) @ 0x101540cd in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:47.942007271Z 3. DB::HTTPServerRequest::HTTPServerRequest(std::__1::shared_ptr<DB::Context const>, DB::HTTPServerResponse&, Poco::Net::HTTPServerSession&) @ 0x110e6fd5 in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:47.942011669Z 4. DB::HTTPServerConnection::run() @ 0x110e5d6e in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:47.942015242Z 5. Poco::Net::TCPServerConnection::start() @ 0x13c5614f in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:47.942018706Z 6. Poco::Net::TCPServerDispatcher::run() @ 0x13c57bda in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:47.942022190Z 7. Poco::PooledThread::run() @ 0x13d89e59 in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:47.942026682Z 8. Poco::ThreadImpl::runnableEntry(void*) @ 0x13d860ea in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:47.942029430Z 9. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
clickhouse-1                                    | 2024-05-20T18:30:47.942033417Z 10. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
clickhouse-1                                    | 2024-05-20T18:30:47.942037177Z  (version 21.8.13.1.altinitystable (altinity build))
clickhouse-1                                    | 2024-05-20T18:30:48.138853424Z 2024.05.20 18:30:48.138686 [ 297 ] {} <Error> ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 107, e.displayText() = Net Exception: Socket is not connected, Stack trace (when copying this message, always include the lines below):
clickhouse-1                                    | 2024-05-20T18:30:48.138872468Z 
clickhouse-1                                    | 2024-05-20T18:30:48.138876874Z 0. Poco::Net::SocketImpl::error(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x13c4ee8e in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:48.138881355Z 1. Poco::Net::SocketImpl::peerAddress() @ 0x13c510d6 in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:48.138885106Z 2. DB::HTTPServerRequest::HTTPServerRequest(std::__1::shared_ptr<DB::Context const>, DB::HTTPServerResponse&, Poco::Net::HTTPServerSession&) @ 0x110e6f0b in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:48.138889419Z 3. DB::HTTPServerConnection::run() @ 0x110e5d6e in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:48.138893249Z 4. Poco::Net::TCPServerConnection::start() @ 0x13c5614f in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:48.138896884Z 5. Poco::Net::TCPServerDispatcher::run() @ 0x13c57bda in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:48.138900373Z 6. Poco::PooledThread::run() @ 0x13d89e59 in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:48.138903899Z 7. Poco::ThreadImpl::runnableEntry(void*) @ 0x13d860ea in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:48.138907453Z 8. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
clickhouse-1                                    | 2024-05-20T18:30:48.138910939Z 9. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
clickhouse-1                                    | 2024-05-20T18:30:48.138914425Z  (version 21.8.13.1.altinitystable (altinity build))
clickhouse-1                                    | 2024-05-20T18:30:48.185461102Z 2024.05.20 18:30:48.185304 [ 280 ] {} <Error> ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 107, e.displayText() = Net Exception: Socket is not connected, Stack trace (when copying this message, always include the lines below):
clickhouse-1                                    | 2024-05-20T18:30:48.185476222Z 
clickhouse-1                                    | 2024-05-20T18:30:48.185478207Z 0. Poco::Net::SocketImpl::error(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x13c4ee8e in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:48.185497639Z 1. Poco::Net::SocketImpl::peerAddress() @ 0x13c510d6 in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:48.185501702Z 2. DB::HTTPServerRequest::HTTPServerRequest(std::__1::shared_ptr<DB::Context const>, DB::HTTPServerResponse&, Poco::Net::HTTPServerSession&) @ 0x110e6f0b in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:48.185505726Z 3. DB::HTTPServerConnection::run() @ 0x110e5d6e in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:48.185509246Z 4. Poco::Net::TCPServerConnection::start() @ 0x13c5614f in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:48.185514507Z 5. Poco::Net::TCPServerDispatcher::run() @ 0x13c57bda in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:48.185516948Z 6. Poco::PooledThread::run() @ 0x13d89e59 in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:48.185521833Z 7. Poco::ThreadImpl::runnableEntry(void*) @ 0x13d860ea in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:48.185525084Z 8. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
clickhouse-1                                    | 2024-05-20T18:30:48.185529147Z 9. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
clickhouse-1                                    | 2024-05-20T18:30:48.185531046Z  (version 21.8.13.1.altinitystable (altinity build))
clickhouse-1                                    | 2024-05-20T18:30:48.320784239Z 2024.05.20 18:30:48.320630 [ 275 ] {} <Error> ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 107, e.displayText() = Net Exception: Socket is not connected, Stack trace (when copying this message, always include the lines below):
clickhouse-1                                    | 2024-05-20T18:30:48.320799503Z 
clickhouse-1                                    | 2024-05-20T18:30:48.320803832Z 0. Poco::Net::SocketImpl::error(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x13c4ee8e in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:48.320809083Z 1. Poco::Net::SocketImpl::peerAddress() @ 0x13c510d6 in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:48.320814196Z 2. DB::HTTPServerRequest::HTTPServerRequest(std::__1::shared_ptr<DB::Context const>, DB::HTTPServerResponse&, Poco::Net::HTTPServerSession&) @ 0x110e6f0b in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:48.320817024Z 3. DB::HTTPServerConnection::run() @ 0x110e5d6e in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:48.320821164Z 4. Poco::Net::TCPServerConnection::start() @ 0x13c5614f in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:48.320824513Z 5. Poco::Net::TCPServerDispatcher::run() @ 0x13c57bda in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:48.320828171Z 6. Poco::PooledThread::run() @ 0x13d89e59 in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:48.320831891Z 7. Poco::ThreadImpl::runnableEntry(void*) @ 0x13d860ea in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:48.320835537Z 8. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
clickhouse-1                                    | 2024-05-20T18:30:48.320839089Z 9. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
clickhouse-1                                    | 2024-05-20T18:30:48.320844061Z  (version 21.8.13.1.altinitystable (altinity build))
clickhouse-1                                    | 2024-05-20T18:30:48.350512787Z 2024.05.20 18:30:48.350377 [ 260 ] {} <Error> ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 107, e.displayText() = Net Exception: Socket is not connected, Stack trace (when copying this message, always include the lines below):
clickhouse-1                                    | 2024-05-20T18:30:48.350542587Z 
clickhouse-1                                    | 2024-05-20T18:30:48.350547241Z 0. Poco::Net::SocketImpl::error(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x13c4ee8e in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:48.350551679Z 1. Poco::Net::SocketImpl::peerAddress() @ 0x13c510d6 in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:48.350555361Z 2. DB::HTTPServerRequest::HTTPServerRequest(std::__1::shared_ptr<DB::Context const>, DB::HTTPServerResponse&, Poco::Net::HTTPServerSession&) @ 0x110e6f0b in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:48.350559381Z 3. DB::HTTPServerConnection::run() @ 0x110e5d6e in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:48.350562976Z 4. Poco::Net::TCPServerConnection::start() @ 0x13c5614f in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:48.350566496Z 5. Poco::Net::TCPServerDispatcher::run() @ 0x13c57bda in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:48.350570022Z 6. Poco::PooledThread::run() @ 0x13d89e59 in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:48.350573520Z 7. Poco::ThreadImpl::runnableEntry(void*) @ 0x13d860ea in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:48.350577203Z 8. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
clickhouse-1                                    | 2024-05-20T18:30:48.350580778Z 9. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
clickhouse-1                                    | 2024-05-20T18:30:48.350584453Z  (version 21.8.13.1.altinitystable (altinity build))
clickhouse-1                                    | 2024-05-20T18:30:48.567043441Z 2024.05.20 18:30:48.566887 [ 281 ] {} <Error> ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 107, e.displayText() = Net Exception: Socket is not connected, Stack trace (when copying this message, always include the lines below):
clickhouse-1                                    | 2024-05-20T18:30:48.567059195Z 
clickhouse-1                                    | 2024-05-20T18:30:48.567064160Z 0. Poco::Net::SocketImpl::error(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x13c4ee8e in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:48.567068083Z 1. Poco::Net::SocketImpl::peerAddress() @ 0x13c510d6 in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:48.567071864Z 2. DB::HTTPServerRequest::HTTPServerRequest(std::__1::shared_ptr<DB::Context const>, DB::HTTPServerResponse&, Poco::Net::HTTPServerSession&) @ 0x110e6f0b in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:48.567076371Z 3. DB::HTTPServerConnection::run() @ 0x110e5d6e in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:48.567080175Z 4. Poco::Net::TCPServerConnection::start() @ 0x13c5614f in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:48.567083864Z 5. Poco::Net::TCPServerDispatcher::run() @ 0x13c57bda in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:48.567087485Z 6. Poco::PooledThread::run() @ 0x13d89e59 in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:48.567091003Z 7. Poco::ThreadImpl::runnableEntry(void*) @ 0x13d860ea in /usr/bin/clickhouse
clickhouse-1                                    | 2024-05-20T18:30:48.567094605Z 8. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
clickhouse-1                                    | 2024-05-20T18:30:48.567098142Z 9. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so

**Comment by azaslavsky** [comment]
The specific stack trace you link to implies that this is a known issue with snuba. Try the solution presented [here](https://github.com/getsentry/snuba/issues/5707#issuecomment-2027710056).
