### ISSUE TITLE
Can't find SOC2 Report

### ISSUE THREAD

**Issue by zrev2220** [getsentry/self-hosted#3072]
### Self-Hosted Version

24.4.2

### CPU Architecture

x86_64

### Docker Version

26.1.1

### Docker Compose Version

2.27.0

### Steps to Reproduce

1. Per [these docs](https://docs.sentry.io/security-legal-pii/security/soc2/), I tried locating our SOC2 Report from our self-hosted instance (our organization is undergoing its own SOC2 audit and we may need these documents to complete it).
2. I went to our organization settings (`{ourDomain}/settings/{ourOrganization}/`).

### Expected Result

The **Legal & Compliance** item in the sidebar should exist, and clicking it should give me access to Sentry's SOC2 Report.

### Actual Result

The **Legal & Compliance** sidebar item doesn't exist. :disappointed:

![image](https://github.com/getsentry/self-hosted/assets/22283396/74706bd4-34eb-42d3-85df-ad7c165fe04b)

Forgive me if I'm ignorant and this page is not relevant to self-hosted instances. This info was not clear in the docs, so I'd like to find out if either we're missing this page for some reason or if it's expected that the page isn't there.

**Comment by stayallive** [comment]
These documents (both SOC2 and ISO27001) do not apply to self-hosted at all.

Sentry has no control over your server and thus those reports and certificates have no effect on your self-hosted instance 👍 

You would need those when using the Sentry SaaS (@ sentry.io) which would prove things about data management and how your data is hosted / protected etc. but that doesn't apply of course when you self-host an instance of Sentry where Sentry has no control over your data at all 😄

**Comment by zrev2220** [comment]
Makes sense, thank you!
