### ISSUE TITLE
Referrer Enum missing referrers

### ISSUE THREAD

**Issue by NikolaiIuzhaninYS** [getsentry/self-hosted#3079]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

1. Upgrade self-hosted to 24.5.0
2. Look at the log of the "web" container

### Expected Result

Absense of warnings of this kind

### Actual Result

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sentry/snuba/referrer.py", line 875, in validate_referrer
    raise Exception(error_message)
Exception: referrer api.metrics.series is not part of Referrer Enum
11:04:57 [WARNING] sentry.snuba.referrer: referrer api.metrics.series is not part of Referrer Enum

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sentry/snuba/referrer.py", line 875, in validate_referrer
    raise Exception(error_message)
Exception: referrer Group.get_helpful is not part of Referrer Enum
10:59:10 [WARNING] sentry.snuba.referrer: referrer Group.get_helpful is not part of Referrer Enum

### Product Area

Other

### Version

24.5.0

**Comment by hubertdeng123** [comment]
Are you observing errors in your self-hosted install? AFAIK these should just be warnings

**Comment by NikolaiIuzhaninYS** [comment]
Ah, right, those are warnings. Anyway might be good to fix. If you could point me where the changes should be done, I could make a PR

**Comment by hubertdeng123** [comment]
I believe those can be added to https://github.com/getsentry/sentry/blob/0d270ad1c8532bb133772a03e166dca23a3a08ad/src/sentry/snuba/referrer.py
