### ISSUE TITLE
Testing Beta Sentry Metrics on self-hosted

### ISSUE THREAD

**Issue by JeremiaAu** [getsentry/self-hosted#3080]
### Problem Statement

Is it possible to use the new sentry metrics feature using a self-hosted instance?

https://github.com/getsentry/sentry/discussions/64195

### Solution Brainstorm

Maybe there is a feature flag that can be set in the config file like in this other issue:

https://github.com/getsentry/sentry/issues/69456#issuecomment-2073169610

**Comment by hubertdeng123** [comment]
Please read this issue for more details: https://github.com/getsentry/self-hosted/issues/2698

Closing this as a duplicate.
