### ISSUE TITLE
change sentry-self-hosted-nginx-1 to listen on 20.10.0.1

### ISSUE THREAD

**Issue by suren11111** [getsentry/self-hosted#3089]
### Body

i want to change the sentry-self-hosted-nginx-1  container listen from port to 20.10.0.1port. how do i solve this. guide me to change the listen port

**Comment by aldy505** [comment]
Assuming you want to have it listening to `20.10.0.1:80`, the regular http port, you just need to change this one line:

https://github.com/getsentry/self-hosted/blob/6917e398bb603e1673b2e2dc7ca2ccbb466305c7/.env#L5

For your scenario, should be
```ini
 SENTRY_BIND=20.10.0.1:80
```

**Comment by suren11111** [comment]
thanks, I change this by cd self-hosted/nginx/nginx.conf and in nginx.conf file i change listen 80 to listen20.10.0.1:80 after this i restart the container. i try to hit url it give me error bad gateway . this steps i follow  for  to change sentry-self-hosted-nginx-1 to listen on 20.10.0. I will try your step SENTRY_BIND=20.10.0.1:80 afterb this i will tell you this works for me or not ?

**Comment by aldy505** [comment]
No, please don't modify anything on the `nginx.conf` file. Instead, just modify the line that I specify earlier.

**Comment by suren11111** [comment]
I run docker compose up -d after change SENTRY_BIND=20.10.0.1:80 then error is
Error response from daemon: driver failed programming external connectivity on endpoint sentry-self-hosted-nginx-1 (f114508f8c37fbcaea87dee7e6649f17f101582ccb8599db09b5f2e643fdcd81): Error starting userland proxy: listen tcp4 20.10.8.0:80: bind: cannot assign requested address

**Comment by suren11111** [comment]
By default, sentry listen on localhost (127.0.0.1), which means it can only accept connections from the same machine where it's running.
I want to Changing it to listen on a specific IP address like "20.10.0.8" would allow it to accept connections from other machines on the network that can reach this IP address.. I want to do this in sentry-self-hosted-nginx-1 to listen on 20.10.0.8. please guide me the steps about his

**Comment by aldy505** [comment]
> I run docker compose up -d after change SENTRY_BIND=20.10.0.1:80 then error is Error response from daemon: driver failed programming external connectivity on endpoint sentry-self-hosted-nginx-1 (f114508f8c37fbcaea87dee7e6649f17f101582ccb8599db09b5f2e643fdcd81): Error starting userland proxy: listen tcp4 20.10.8.0:80: bind: cannot assign requested address

Are you sure that you **only** made changes to the `SENTRY_BIND` on the `.env` file? Have you reverted your `nginx.conf` file?


> By default, sentry listen on localhost (127.0.0.1), which means it can only accept connections from the same machine where it's running. I want to Changing it to listen on a specific IP address like "20.10.0.8" would allow it to accept connections from other machines on the network that can reach this IP address.. I want to do this in sentry-self-hosted-nginx-1 to listen on 20.10.0.8. please guide me the steps about his

By default Sentry should listen to all interface (`0.0.0.0`). The IP of `20.10.0.8` is not a private IP, it's a public IP. If you want to set it up properly to be access it from the internet, please read about reverse proxy section on the documentation (https://develop.sentry.dev/self-hosted/reverse-proxy).

Also assuming you don't want to set up your own reverse proxy, set your `SENTRY_BIND` to `0.0.0.0:80`, then do `sudo docker compose up -d nginx`. Then try to access `http://20.10.0.8`

**Comment by suren11111** [comment]
I am sure i  made onylt changes to the SENTRY_BIND on the .env file by SENTRY_BIND=20.10.0.1:80 this. i reverted by nginx.conf and this file listen to listen 80.

**Comment by suren11111** [comment]
Also assuming you don't want to set up your own reverse proxy, set your SENTRY_BIND to 0.0.0.0:80, then do sudo docker compose up -d nginx. Then try to access http://20.10.0.8

I try to do the same same step but this not works

**Comment by azaslavsky** [comment]
You're not providing us with very much information here. What version of Sentry are you on? What version of docker? What operating system and version?

Did Sentry ever work, or is this a new install?

**Comment by suren11111** [comment]
sentry version 24.0.5. ubuntu os, Docker version 24.0.5,

**Comment by azaslavsky** [comment]
Did Sentry ever work, or is this a new install? Like has this ever worked, or is this a new install that is failing?

**Comment by suren11111** [comment]
Yes, Sentry has been successfully operational. I have a query regarding its backup and restore process. Upon executing the backup and restore script, I received log files named 'sentry_backup_log.txt' and 'sentry_restore_log.txt'. I'd like to confirm if this method is correct, as well as verify the accuracy of the output displayed in the last two lines of the attached image.
![Screenshot from 2024-06-03 17-32-12](https://github.com/getsentry/self-hosted/assets/171140017/b9d8e285-3cc7-4ebc-9d30-30df4993c817)

**Comment by azaslavsky** [comment]
Backup/restore does work, but that sentence is correct: you'll be overwriting the existing database with the backed up one. You should do a [full backup](https://develop.sentry.dev/self-hosted/backup/#full-backup) just to be extra safe.

**Comment by suren11111** [comment]
so after this my next task is  to create a full backup of the sentry for the extra safe.

**Comment by hubertdeng123** [comment]
I'm a bit confused. Why are you now attempting to backup? Isn't your main goal to expose your sentry instance as a public ip and have it accessible by the internet? How are you obtaining 20.10.0.8? Is that the ip address of your machine?

**Comment by suren11111** [comment]
My first task is to make the Sentry instance accessible to the IP address 20.10.0.8 on my machine. My second task is to perform a backup and restore of the Sentry instance. please dont confused in this.

**Comment by hubertdeng123** [comment]
>  Error starting userland proxy: listen tcp4 20.10.8.0:80: bind: cannot assign requested address

Is this ip address being used by anything else? Running out of ideas here if you’ve tried everything else mentioned above
