### ISSUE TITLE
Take a lot of RAM & CPU resources, and lead to unable to connect to server via SSH

### ISSUE THREAD

**Issue by codingtalk** [getsentry/self-hosted#3090]
### Self-Hosted Version

24.5.0

### CPU Architecture

Intel(R) Xeon(R) Platinum 8269CY CPU @ 2.50GHz

### Docker Version

26.1.3

### Docker Compose Version

v2.27.0

### Steps to Reproduce

1. git clone https://github.com/getsentry/self-hosted.git
2. mv ./self-hosted ./sentry
3. git checkout 24.5.0
4. ./install.sh

### Expected Result

work correctly with 4core + 16RAM and take reasonable CPU and RAM  resources

### Actual Result

wait about half of a day, the consumption of RAM and CPU raised to extremely hight (4 core + 16 RAM) and no longer able to connect to server via SSH, have to reboot server, but the issue will appear again
![1716993971929](https://github.com/getsentry/self-hosted/assets/49552680/ab0d27c7-dd80-4a9b-9d8f-a1e95c75be46)

**Comment by hubertdeng123** [comment]
Unfortunately, there's not something we can do for you in the immediate term. We are working on an errors-only version of self-hosted Sentry, which should drastically reduce the amount of RAM and CPU resources that are being used though.

**Comment by codingtalk** [comment]
> Unfortunately, there's not something we can do for you in the immediate term. We are working on an errors-only version of self-hosted Sentry, which should drastically reduce the amount of RAM and CPU resources that are being used though.

that sounds awesome and thank you again, at last can we know what specific version you are now working on, so that i can apply this version to fix issues from my side

**Comment by henri9813** [comment]
Hello,

Sorry, but the documentation mentioned:

```
[Recommended system resource](https://develop.sentry.dev/self-hosted/#recommended-system-resource)

Depending on your usage, required system resource to run Sentry may varies. Minimum system specification for running Sentry looks like this:

2 CPU cores
4 GB RAM
```

Why sentry consume 16GB of ram ? 

How to make it consume 4GB of RAM ?

Best regards,

**Comment by hubertdeng123** [comment]
Sentry consumes that amount of RAM due to its services required to run. We're not looking to decrease this for the default Sentry install. However, if you'd like to use errors only self-hosted, you can do so. https://develop.sentry.dev/self-hosted/#errors-only-self-hosted-sentry
