### ISSUE TITLE
A proper way to disable GeoIP in self-hosted Sentry

### ISSUE THREAD

**Issue by many-juice** [getsentry/self-hosted#3096]
### Self-Hosted Version

24.2.0

### CPU Architecture

x64

### Docker Version

26.1.3

### Docker Compose Version

26.1.3

### Steps to Reproduce

When starting Sentry out-of-the-box, GeoIP containers fails with exit code 1 due to the missing GeoIP config [unless Maxmind account is added to /sentry/GeoIP.conf](https://develop.sentry.dev/self-hosted/geolocation/). It's expected, but it hurts.

### Expected Result

We don't need GeoIP at all and want to disable it completely to avoid confusing related errors.

### Actual Result

Is it enough and safe to completely remove this sections from Sentry's docker-compose.yml?
```
  #geoipupdate:
    #image: "ghcr.io/maxmind/geoipupdate:v6.0.0"
    # Override the entrypoint in order to avoid using envvars for config.
    # Futz with settings so we can keep mmdb and conf in same dir on host
    # (image looks for them in separate dirs by default).
    #entrypoint: ["/usr/bin/geoipupdate", "-d", "/sentry", "-f", "/sentry/GeoIP.conf"]
    #volumes:
     # - "./geoip:/sentry"
```
Also won't it somehow affect other Sentry services if I remove geoipupdate volume from Docker compose?
```
  volumes:
    - "./geoip:/geoip:ro"
```
And is it ok to remove the corresponding mount from the Relay container?
```
  relay:
    volumes:
      - type: bind
        read_only: true
        source: ./geoip
```

**Comment by hubertdeng123** [comment]
Yep, you should be able to remove it entirely from the docker compose file if you don't want to use it.
