### ISSUE TITLE
Sentry filestore - What is this used for?

### ISSUE THREAD

**Issue by piellick** [getsentry/self-hosted#3097]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### What are you trying to accomplish?

We try to plan a migration from local file storage to S3 block. Documentation indicate that filestore is use for release artifacts but here is another data on it ?

https://develop.sentry.dev/services/filestore/

### How are you getting stuck?

We are not able to know witch data are store on filestore , during the switch to object storage witch data will be unavailable ?

### Where in the product are you?

Settings

### Version

24.5.0

**Comment by hubertdeng123** [comment]
Filestore is primarily used for larger files, such as release artifacts and debug files. I would take a look at your `sentry-data` volume to see what files are in there.

**Comment by piellick** [comment]
Hi @hubertdeng123 thanks,
the docker volume structure for "data" volume is not necessarily human readable. Could we dump everything to a S3 bucket and switch to S3 file storage ?

**Comment by piellick** [comment]
To give more context, after changing filestorage config to an empty S3 bucket, we redeploy sentry through official docker-compose.

Release are still available on UI despite an empty bucket. Informations are stored elsewhere ?

**Comment by azaslavsky** [comment]
No, that will not work. We don't have support for changing filestores dynamically - each store uses it's own ex: folder structures and the like, and I would be very surprised if this sort of changeover succeeded.

**Comment by piellick** [comment]
hello @azaslavsky,
Thanks for validating my hypotesis. We did some test and i confirm ...swtiching form local FS to S3 didn't work.
