### ISSUE TITLE
All events tab still causing 502 errror

### ISSUE THREAD

**Issue by farfromrefug** [getsentry/self-hosted#3101]
### Self-Hosted Version

24.5.0

### CPU Architecture

x86_64

### Docker Version

20.10.23

### Docker Compose Version

2.9.0

### Steps to Reproduce

open an issue with lot's of multiple (hundreds to thousands) events
click on "All Events"
not further Events are shown, loading indicator stays forever, lot's of 502 Errors are shown in Firefox Console

### Expected Result

All Events should be shown

### Actual Result

Still facing the issue as presented [here](https://github.com/getsentry/self-hosted/issues/2329).
I am using latest so i should have all the fixes needed, though it is still happening.
One thing i am wondering is that my dockers are exposed through a nginx too. Should this one have settings change too? (i dont have easy access to those settings).

My main point for this issue is wouldnt be better to have a setting to change the number of issues shown per page? wouldnt that reduce the nginx buffer load? 
I tried to see if i could change it without going into sentry source code, but i dont think i can.
I would be really nice to have such a setting to ensure every server can handle the All Events page

**Comment by azaslavsky** [comment]
Yes, if you increase the proxy buffer in nginx, as mentioned in the issue, you'll be able to send more events per page. We don't have an in-app toggle for setting this at this time.

**Comment by azaslavsky** [comment]
Yes, this is what we did for our own dogfood setup.

**Comment by farfromrefug** [comment]
@azaslavsky ok found the way to do it and it worked. Thanks a lot! (still think that per page option would be a great addition)
