### ISSUE TITLE
Crons: check-ins did not time out.

### ISSUE THREAD

**Issue by JeremiaAu** [getsentry/self-hosted#3104]
### Self-Hosted Version

24.5.0

### CPU Architecture

x86_64

### Docker Version

26.1.3

### Docker Compose Version

2.27.0

### Steps to Reproduce

1. Upgrade from version [24.4.1](https://github.com/getsentry/self-hosted/releases/tag/24.4.1) to [24.5.0](https://github.com/getsentry/self-hosted/releases/tag/24.5.0)
2. Wait for new check-ins, that do not complete
3. Open Crons

### Expected Result

Check-ins time out after the configured amount of time.

### Actual Result

- Check-ins did not time out
- No Issue was created
- No E-Mail was sent

![image](https://github.com/getsentry/self-hosted/assets/96953097/679d6137-5646-4ef3-983c-cd6c04993c60)

(There are two identical timelines because of another issue: https://github.com/getsentry/sentry/issues/71722, they might be related)

**Comment by wedamija** [comment]
Hi @JeremiaAu 

Thanks for the report. We recently changed how we check for failures, and we forgot to have the consumers run in self hosted. Really sorry for the inconvenience here. JFYI, this is unrelated to your other report where the environments are duplicated.

Here's the fix https://github.com/getsentry/self-hosted/pull/3106

You could apply this locally to fix your problem, and I will also discuss getting a hot fix out with our self-hosted team.

**Comment by JeremiaAu** [comment]
I just applied the fix and can confirm that it solves the issue.
