### ISSUE TITLE
How to enable multiple social login, including email?

### ISSUE THREAD

**Issue by cristiano-linvix** [getsentry/self-hosted#3105]
### Problem Statement

How to activate multiple social logins and keep login with email too (like sentry.io)?

![image](https://github.com/getsentry/self-hosted/assets/54996308/ee742759-7178-4ae1-be33-f118328fbb46)

**Comment by aldy505** [comment]
Hi. You just need to enable and configure everything that's described here: https://develop.sentry.dev/integrations/, and then that's should be it.

**Comment by cristiano-linvix** [comment]
Hi, I hope you are well.

To be able to activate social login, I had to insert a record in the database so that I could activate it, after I activated Google's social login, I can no longer activate any social login, and the authentication method becomes just login Social.

I managed to configure the login via github through the web interface, but the same thing happens, when I activate it, only github works and the login via email disappears.

**Comment by azaslavsky** [comment]
I think these instructions are probably outdated by this point, being 3 years old. Have you tried setting up any other auth providers via the integration, like Azure or GitHub?

**Comment by cristiano-linvix** [comment]
Yes. I tried GitHub, the same problem happens, when I activate the provider, the email login is disabled and I only log in with the GitHub auth.

Any suggestions?

**Comment by azaslavsky** [comment]
So I'm not 100% clear on this (I don't own the feature), but I believe using SSO requires disabling email login? At least that is my reading of [this](https://docs.sentry.io/organization/authentication/sso/#getting-started) documentation. @markstory do you know the specific rules on this?

**Comment by markstory** [comment]
If you're looking to get the same login experience in self-hosted that is found on sentry.io, you won't be able to do that. The login page is augmented by the closed source extensions we include for sentry.io.

Depending on how you're configuring SSO, it can either be required or optional. When SSO is required by an organization, there isn't a way to preserve the email login form.

**Comment by cristiano-linvix** [comment]
> If you're looking to get the same login experience in self-hosted that is found on sentry.io, you won't be able to do that. The login page is augmented by the closed source extensions we include for sentry.io.
> 
> Depending on how you're configuring SSO, it can either be required or optional. When SSO is required by an organization, there isn't a way to preserve the email login form.

I got it!

The login experience I wanted for my system was actually sentry.io, it works very well, it's a shame it doesn't work on self-hosted.

Is there the possibility of leaving more than one provider enabled?
Google and GitHub for example.

**Comment by markstory** [comment]
At this point in time Organizations can only have a single SSO provider configured.

**Comment by cristiano-linvix** [comment]
I got it, thank you @markstory!
