### ISSUE TITLE
Upgrading to 24.5.0 breaks PostgreSQL indexes and causes upgrade to fail sometimes

### ISSUE THREAD

**Issue by afaianswq** [getsentry/self-hosted#3107]
### Self-Hosted Version

24.5.0

### CPU Architecture

x86_64

### Docker Version

26.1.3

### Docker Compose Version

2.27.0

### Steps to Reproduce

1, Upgrade Sentry from version 24.4.1 or below to 24.4.2 or above

### Expected Result

Sentry successfully upgraded

### Actual Result

Upgrade either fails (see https://github.com/getsentry/self-hosted/issues/3027) or you'll get PostgreSQL indexes broken which will cause other issues after the upgrade.

The reason for this is because in version 24.4.2 image for postgres was changed from "postgres:14.5" (debian based, classic glibc) to "postgres:14.11-alpine" (alpine, musl libc). PostgreSQL is known to have issues with indexes when libc version or implementation changes. Please refer to this documentation article: https://wiki.postgresql.org/wiki/Locale_data_changes#What_to_do

**Comment by azaslavsky** [comment]
Postgres was bumped to 14.11 for security reasons. You'll need to re-index as described in #3027

**Comment by azaslavsky** [comment]
The other options is to change `postgres:14.11-alpine` to `postgres:14.11`. If this works, we may just change the image going forward.

**Comment by afaianswq** [comment]
Both options are workarounds, not a real solution. This is a BUG and you need to fix it. For example, a proper solution would be to change postgres image back to default (debian-based, i.e. `postgres:14.11`). Because otherwise people will have to change it every time they upgrade their installation. Alternatively, if you want to keep alpine version, you have to figure out ALL affected indexes and add a migration step that will reindex all of them before any other database-related tasks are executed.

**Comment by afaianswq** [comment]
> Postgres was bumped to 14.11 for security reasons.

Also, I just want to make it clear one more time, the problem is not postgres version. Problem is that you have changed from debian-based image to alpine-based image.

**Comment by azaslavsky** [comment]
Does using `postgres:14.11` work for you? I want to get reports from the field before changing the version. Using this workaround will help us decide how to proceed.

**Comment by afaianswq** [comment]
> Does using `postgres:14.11` work for you?

Yes, it does.

**Comment by hubertdeng123** [comment]
I have opened a PR to change this. Thanks for following up here @afaianswq
