### ISSUE TITLE
souremap has been unable to display

### ISSUE THREAD

**Issue by maxming2333** [getsentry/self-hosted#3114]
### Self-Hosted Version

23.8.0

### CPU Architecture

x86_64

### Docker Version

Docker version 26.0.0, build 2ae903e

### Docker Compose Version

docker-compose version 1.29.2, build 5becea4c

### Steps to Reproduce

https://github.com/getsentry/sentry-javascript/issues/12382

### Expected Result

I've tried various methods now, but it still doesn't work

### Actual Result

I've tried various methods now, but it still doesn't work

**Comment by maxming2333** [comment]
I would like to ask which problem is this: `sentry`, `docker`, `docer-compose`, `self-hosted`, `sentry-vue` or `sentry-js` ?

**Comment by maxming2333** [comment]
I fix to this https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/480

---------------

#### This fixes "Permission denied" issues for `sentry-web` and `sentry-worker`，https://github.com/getsentry/self-hosted/issues/302
```bash
# /var/lib/docker/volumes/sentry-data/_data -> /data
docker exec sentry-self-hosted_web_1 chown -R sentry:sentry /data/files
```


#### This fixes "Permission denied" issues for `sentry-symbolicator`，https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/480
```bash
# /var/lib/docker/volumes/sentry-symbolicator/_data -> /data
docker exec sentry-self-hosted_symbolicator_1 chown -R symbolicator:symbolicator /data
```

**Comment by azaslavsky** [comment]
So are you still seeing the issue? Or does the last comment imply that it is fixed?

**Comment by maxming2333** [comment]
I'm very happy that the problem has been solved through the above method.
I will close the issue.
