### ISSUE TITLE
Can't upload Source maps

### ISSUE THREAD

**Issue by nnhiep** [getsentry/self-hosted#3129]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce
- We deploy Sentry on k8s cluster & Upload source maps use sentry-cli as below command.
`node_modules/@sentry/cli/bin/sentry-cli releases \
    files 'vn.com.dt.android@4.1.0' \
    upload-sourcemaps \
    --dist '4010011' \
    --strip-prefix /Users/maxinminax/Desktop/working/dt-rn \
    index.android.bundle index.android.bundle.map`
    
- After upload (status)
  Source Map Upload Report
  Scripts
    ~/index.android.bundle (sourcemap at index.android.bundle.map)
  Source Maps
    ~/index.android.bundle.map (debug id 32d7fc6c-fb8f-48fc-bab5-f69af123e950)

### Expected Result
Upload successfully 

### Actual Result
We only found information about Release Bundles; there were no Artifact Bundles (No artifact bundles found for this project).
We checked the related PVC and found that only 3.7Gi out of the allocated 10Gi has been used.

### Product Area

Issues - Source Maps

### Version

23.12.1

**Comment by hubertdeng123** [comment]
You're using a version of self-hosted Sentry that is unfortunately unsupported here. Since sentry has a lot of moving parts it is difficult to identify what may be going wrong here. You'll have more luck filing an issue in the repo of the k8s cluster you're using. Good luck!
