### ISSUE TITLE
Worker can't connect to postgres

### ISSUE THREAD

**Issue by jerbob92** [getsentry/self-hosted#3132]
### Self-Hosted Version

24.5.1

### CPU Architecture

x86_64

### Docker Version

26.1.3

### Docker Compose Version

2.27.0

### Steps to Reproduce

I'm not completely sure, I upgraded to 24.5.1.

### Expected Result

The worker being able to connect to postgres.

### Actual Result

I keep getting the following error:

```
django.db.utils.OperationalError: connection to server at "postgres" (10.201.17.4), port 5432 failed: Cannot assign requested address
Is the server running on that host and accepting TCP/IP connections?
```

In the workers process. I think when it's trying to store events. The odd thing is that it is processing events, so it seems like it's not completely broken. I really have no idea what's going on here. The frontend works fine and I can also connect to postgres just fine.

**Comment by azaslavsky** [comment]
Any chance your client could be [reassigning](https://github.com/getsentry/self-hosted/issues/97#issuecomment-398404324) hostnames?

**Comment by jerbob92** [comment]
Thanks for your reply!

I don't think so, wouldn't that make it completely fail in all processes?  The UI works fine and the events do show up in the UI.

The error is also different `Cannot assign requested address` vs `could not translate host name` and `Connection refused`. 

And since some events do appear in Sentry, wouldn't that mean that some connections do succeed? All events need to be processed by the worker container before they appear in the UI right?

**Comment by azaslavsky** [comment]
And just to be clear: as far as you can tell, this is only logspam, and no events are being dropped?
