### ISSUE TITLE
Release 24.5.1 has a critical bug!

### ISSUE THREAD

**Issue by danuk** [getsentry/self-hosted#3139]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

1. Install a Sentry 24.5.1
2. Go to the web login page: https://DOMAIN. (it redirect to page: "Welcome to Sentry
" (https://DOMAIN/organizations/sentry/issues/))
3. Try to press button "Continue", it doesn't works....

I see in browser console some information:
- HTTP STATUS: 400
- Response: 
{
    "error": "immutable_option",
    "errorDetail": {
        "option": "mail.use-tls",
        "message": "'mail.use-tls' cannot be changed at runtime because it is configured on disk"
    }
}

### Expected Result

It should work...

### Actual Result

- URL: https://DOMAIN/api/0/internal/options/?query=is:required
- Method: PUT
- HTTP STATUS: 400
- Response: 
{
    "error": "immutable_option",
    "errorDetail": {
        "option": "mail.use-tls",
        "message": "'mail.use-tls' cannot be changed at runtime because it is configured on disk"
    }
}

### Product Area

Unknown

### Version

24.5.1

**Comment by azaslavsky** [comment]
Have you attempted to install 24.5.0 (or 24.6.0, which just landed)? I am curious if this is specific to this version only.

**Comment by simonoff** [comment]
> Have you attempted to install 24.5.0 (or 24.6.0, which just landed)? I am curious if this is specific to this version only.

Same behaviour. 2.6.0 not fixed this issue.

**Comment by hubertdeng123** [comment]
Just to confirm, is this a clean install of self-hosted Sentry?

**Comment by simonoff** [comment]
> Just to confirm, is this a clean install of self-hosted Sentry?

Yes, completely free. Inside kubernetes, where we set all mail settings.

**Comment by hubertdeng123** [comment]
We don't officially support kubernetes deployments of self-hosted, only the docker compose version. This is not an issue there, so I'm going to go ahead and close this.

**Comment by Josefnm** [comment]
I have the same issue on a clean install of sentry docker compose version

**Comment by Josefnm** [comment]
Bypassed by setting my email settings to dummy instead of
mail.backend: 'smtp'  # Use dummy if you want to disable email entirely
mail.host: 'smtp.gmail.com'
mail.port: 465
mail.username: '***@gmail.com'
mail.password: '***'
mail.use-tls: false
mail.use-ssl: true
mail.from: '***@gmail.com'

**Comment by simonoff** [comment]
> We don't officially support kubernetes deployments of self-hosted, only the docker compose version. This is not an issue there, so I'm going to go ahead and close this.

what the difference? you have a bug, and its not related to kubernetes or docker. Its related to your code.

We have fixed it just by removing email settings, finish install and after move them back.
