### ISSUE TITLE
All links under point performance are broken

### ISSUE THREAD

**Issue by michaelmairegger** [getsentry/self-hosted#3145]
### Self-Hosted Version

24.6.0

### CPU Architecture

x86_64

### Docker Version

24.0.7

### Docker Compose Version

2.27.1

### Steps to Reproduce

Click on Queries and the new page shows:
> The organization you were looking for was not found.

### Expected Result

For e.g. `queries` the folowing URL should open:
https://.../organizations/sentry/insights/database/ 

### Actual Result

For e.g. `queries` the following URL opens:

https://.../insights/database/

**Comment by cavanierc** [comment]
Hello,
I have the same issue after upgrade to 24.6.0

**Comment by SmoshySmosh** [comment]
I am currently experiencing the same after upgrading.

**Comment by aldy505** [comment]
@KevinL10 @gggritso Hey, do you guys know anything related to this? I saw [this PR](https://github.com/getsentry/sentry/pull/71288) that probably made the change, but since it's included in 24.5.1, I'm not too sure.

**Comment by pavel-boev** [comment]
Enabling of feature "organizations:performance-insights" fixed this for me, but I still have useless "Caches", "Queues" and "LLM Monitoring" in navigation

**Comment by aldy505** [comment]
> Enabling of feature "organizations:performance-insights" fixed this for me, but I still have useless "Caches", "Queues" and "LLM Monitoring" in navigation

@pavel-boev Would you like to add these features and then re-run `install.sh` script?
```py
    # Show links and upsells to Insights modules
    "organizations:insights-entry-points",
    # Enable access to initial Insights modules (Queries, Requests, Vitals, App Starts, Page Loads, Resources)
    "organizations:insights-initial-modules",
    # Enable access to newer Insights modules (Caches, Queues, LLMs, Mobile UI)
    "organizations:insights-addon-modules",
```

(from https://github.com/getsentry/sentry/blob/0b1bc857461516585b36b9ef89e478b698493977/src/sentry/features/temporary.py#L401-L406)

**Comment by pavel-boev** [comment]
I prefer to keep "organizations:insights-addon-modules" disabled, because we don't use sentry for backend. But I still see these modules in the navigation with the disabled feature.

**Comment by LordSimal** [comment]
Adding the 3 feature flags mentioned above to the `sentry/sentry.conf.py` and doing a `./install.sh` does not fix this issue.

**Comment by zKoz210** [comment]
@LordSimal work for me

```
    "organizations:performance-insights",
    # Show links and upsells to Insights modules
    "organizations:insights-entry-points",
    # Enable access to initial Insights modules (Queries, Requests, Vitals, App Starts, Page Loads, Resources)
    "organizations:insights-initial-modules",
    # Enable access to newer Insights modules (Caches, Queues, LLMs, Mobile UI)
    "organizations:insights-addon-modules",
```
<img width="239" alt="image" src="https://github.com/getsentry/self-hosted/assets/28255085/dd6afd9b-5f10-4703-afb4-fed5bf51d711">

**Comment by LordSimal** [comment]
Indeed, I was missing `organizations:performance-insights` as well, so the following 2 features should be added to the `sentry.config.example.py` in this repo 😉 

```
"organizations:insights-addon-modules",
"organizations:performance-insights",
```

with that all the menu items work again

**Comment by gggritso** [comment]
👋🏻 hi everyone, sorry about the linking confusion!

- `"organizations:performance-insights"` was removed in https://github.com/getsentry/sentry/pull/72962 a few days ago, so the next release of self-hosted doesn't need it
- `"organizations:insights-entry-points"`, `"organizations:insights-initial-modules"` and `"organizations:insights-addon-modules"` should be enabled

@aldy505 do you mind making that change and/or pointing me to where I should make it?

**Comment by stumbaumr** [comment]
This was the first issue I found regarding the error message: https://github.com/getsentry/sentry/issues/53431
Linking it here to make this issue appear over there...

**Comment by aldy505** [comment]
> This was the first issue I found regarding the error message: https://github.com/getsentry/sentry/issues/53431
> 
> Linking it here to make this issue appear over there...

@stumbaumr This issue is not related to session replay. Are you referring to other issue? Or can you specify more of what you're experiencing?
