### ISSUE TITLE
Issue Real Time Update unfiltered

### ISSUE THREAD

**Issue by LucianoHanna** [getsentry/self-hosted#3156]
### Self-Hosted Version

24.5.0

### CPU Architecture

x86_64

### Docker Version

24.0.7

### Docker Compose Version

2.21.0

### Steps to Reproduce

1. Open Issues list (/organizations/sentry/issues)
2. Add some filter (for example: is:unresolved !level:info)
3. Enable real-time updates

### Expected Result

Receive real time update that matches the filter

### Actual Result

Receive real time update of all new issues received (including issues with info level)

**Comment by hubertdeng123** [comment]
This is something that appears to be working for me. Is your self-hosted Sentry instance ingesting issues properly? Upon a refresh of the page, are you getting the new issues?

**Comment by hubertdeng123** [comment]
Note: I am also testing on 24.6.dev
