### ISSUE TITLE
Provide ssl based docker-compose.yaml file

### ISSUE THREAD

**Issue by Sunderasen** [getsentry/self-hosted#3158]
### Problem Statement

Hi, I have own ssl certificate unable to use https .kindly provide ssl based docker-compose.yaml file

**Comment by aldy505** [comment]
Hello! If you wish to install the TLS certificate for accessing your Sentry instance, it's recommended to apply it on your outmost reverse proxy instead. See the documentation here: https://develop.sentry.dev/self-hosted/reverse-proxy#enabling-https

That way, it's easier during upgrades and will play nicer with any of people's custom setups. Considering complying with everyone's needs is a bit of a maintenance burden.
