### ISSUE TITLE
Insights dont work

### ISSUE THREAD

**Issue by DarkByteZero** [getsentry/self-hosted#3160]
### Self-Hosted Version

24.6.0

### CPU Architecture

x86_64

### Docker Version

25.0.1, build 29cf629

### Docker Compose Version

v2.24.2

### Steps to Reproduce

1. Install Sentry Version 24.6.0 
2. Custom Instrument of caches with go SDK, following description in [docs](https://develop.sentry.dev/sdk/performance/modules/caches/)  
![image](https://github.com/getsentry/self-hosted/assets/22873369/f1894ae2-2d16-44b8-af33-26c47ae14fa7)
![image](https://github.com/getsentry/self-hosted/assets/22873369/183f60d4-e4e4-462f-bbf7-c4770e6b82c0)

3. No Caches Insights

### Expected Result

See Insights of Caches

### Actual Result

API Requets on Caches Insights Page fail with 400

Data Returned by API:

"Column cache.hit was not found in metrics indexer"

**Comment by aldy505** [comment]
Have you enabled these? https://github.com/getsentry/self-hosted/pull/3152/files

**Comment by DarkByteZero** [comment]
yes, i should have all the required Flags

**Comment by aldy505** [comment]
We're debugging this on Discord https://discord.com/channels/621778831602221064/1255073501895852062. One assumption is that the instrumentation isn't correct.

**Comment by aldy505** [comment]
The solution was to add an additional feature flag: `"projects:span-metrics-extraction-addons"`.

@DarkByteZero please close this issue if that's fixed it for you.

**Comment by DarkByteZero** [comment]
It works now. Thanks for the Help
