### ISSUE TITLE
Performance doesn't show any data on dashboard 

### ISSUE THREAD

**Issue by b4ndar** [getsentry/self-hosted#3163]
### Self-Hosted Version

24.7.0.dev0

### CPU Architecture

arm64

### Docker Version

26.0.0

### Docker Compose Version

v2.26.1-desktop.1

### Steps to Reproduce

I seup my SentryFlutter.init within my dns and enabled the following : 

options.enableUserInteractionTracing = true;
options.enableMetrics = true;
options.enableTracing = true;
options.captureFailedRequests = true;
options.tracesSampleRate = 1.0;
options.captureFailedRequests = true;

also i add this to dio client : 

    client.addSentry(captureFailedRequests: true, failedRequestStatusCodes: [
      SentryStatusCode(400),
      SentryStatusCode(404),
      SentryStatusCode(500)
    ]);

the sentry listen and capture and display the issues on dashboard but the performance doesn't show any data . Why ?     

### Expected Result

Performance dashboard show the data of my app performance . 

### Actual Result

The performance on dashboard doesn't show any data .

**Comment by hubertdeng123** [comment]
Looks like you are on arm64 here. We do not support self-hosted Sentry for ARM, and have limited support for Mac OS silicon for the purposes of offering support for our devs.
