### ISSUE TITLE
Build always shows as unknown in self-hosted

### ISSUE THREAD

**Issue by andrea-berling** [getsentry/self-hosted#3165]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

1. Go to https://hub.docker.com/layers/getsentry/sentry/24.5.1/images/sha256-4c6e8885468559da05839b9f4034dcd80eaed6c67a7787f02b0e0fde08a422b4?context=explore
2. Check out the value of `SENTRY_BUILD` at line 46

### Expected Result

`SENTRY_BUILD` should point to the commit sha that was checked out when the Docker image was built

### Actual Result

`SENTRY_BUILD` is set to `unknown`, indicating that the proper build argument (`SOURCE_COMMIT`) was not provided when the image was built. Compare with Dockerfile, `ARG SOURCE_COMMIT`. As a result, this is what is shown in the footer:
<img width="1292" alt="image" src="https://github.com/getsentry/sentry/assets/25068541/7955c218-d363-46ee-927f-cda9e768acb7">

### Product Area

Footer

### Version

24.5.1

**Comment by aldy505** [comment]
It's a known issue, but it doesn't impact anything though. The commit sha should be there. https://github.com/getsentry/sentry/blob/5f49d2a6ef0e41c57c0229d7125d8ab42571db29/static/app/components/footer.tsx#L39-L48

**Comment by joshuarli** [comment]
https://github.com/getsentry/sentry/pull/76139
