### ISSUE TITLE
Error 502 Bad Gateway when downloading an attachment (minidump)

### ISSUE THREAD

**Issue by maxp1256** [getsentry/self-hosted#3178]
### Self-Hosted Version

24.2.0

### CPU Architecture

x86_64

### Docker Version

24.0.7-0ubuntu2~22.04.1

### Docker Compose Version

2.28.1

### Steps to Reproduce

When clicking "Download" attachment on specific events I'm getting an error 502 Bad Gateway from the internal nginx.

### Expected Result

Attachment being download correctly.

### Actual Result

web-1                                           | 06:13:04 [INFO] sentry.superuser: superuser.request (url='http://my.sentry.tld/api/0/projects/sentry/myproj/events/96d8f0da0b37457d93e33fd8e56bb327/attachments/224093/?download=1' method='GET' ip_address='195.x.x.x' user_id=1)
web-1                                           | 06:13:04 [INFO] sentry.access.api: api.access (method='POST' view='sentry.api.endpoints.relay.project_configs.RelayProjectConfigsEndpoint' response=200 user_id='None' is_app='None' token_type='None' is_frontend_request='False' organization_id='None' auth_id='None' path='/api/0/relays/projectconfigs/' caller_ip='172.20.0.50' user_agent='None' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.0137481689453125 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
web-1                                           | 06:13:04 [INFO] sentry.superuser: superuser.superuser_access (superuser_token_id='donotusemytoken' user_id=1 user_email='me@my.sentry.tld' su_org_accessed='sentry')
web-1                                           | 06:13:04 [INFO] sentry.access.api: api.access (method='GET' view='sentry.api.endpoints.event_attachment_details.EventAttachmentDetailsEndpoint' response=200 user_id='1' is_app='False' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/projects/sentry/myproj/events/96d8f0da0b37457d93e33fd8e56bb327/attachments/224093/' caller_ip='195.x.x.x' user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 OPR/110.0.0.0' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.23047924041748047 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
web-1                                           | 06:13:04 [WARNING] sentry_sdk.errors: Can not create a child span for sentry.models.files.abstractfile.AbstractFile.getfile. Please start a Sentry transaction before calling this function.
web-1                                           | [uwsgi-http key: my.sentry.tld client_addr: 172.20.0.51 client_port: 14030] hr_write(): Connection reset by peer [plugins/http/http.c line 565]

nginx-1                                         | 2024/07/03 06:13:04 [error] 27#27: *415 upstream sent invalid "Content-Length" header: "Content-Length: None" while reading response header from upstream, client: 172.20.0.1, server: , request: "GET /api/0/projects/sentry/myproj/events/96d8f0da0b37457d93e33fd8e56bb327/attachments/224093/?download=1 HTTP/1.0", upstream: "http://172.20.0.36:9000/api/0/projects/sentry/myproj/events/96d8f0da0b37457d93e33fd8e56bb327/attachments/224093/?download=1", host: "my.sentry.tld", referrer: "https://my.sentry.tld/organizations/sentry/discover/myproj:96d8f0da0b37457d93e33fd8e56bb327/?field=title&field=event.type&field=project&field=user.display&field=timestamp&field=replayId&homepage=true&name=All+Events&project=5&query=myproj.tag%3A12345+myproj.process%3Amy.exe&sort=-timestamp&statsPeriod=14d&yAxis=count%28%29"
nginx-1                                         | 172.20.0.1 - - [03/Jul/2024:06:13:04 +0000] "GET /api/0/projects/sentry/myproj/events/96d8f0da0b37457d93e33fd8e56bb327/attachments/224093/?download=1 HTTP/1.0" 502 552 "https://my.sentry.tld/organizations/sentry/discover/myproj:96d8f0da0b37457d93e33fd8e56bb327/?field=title&field=event.type&field=project&field=user.display&field=timestamp&field=replayId&homepage=true&name=All+Events&project=5&query=myproj.tag%3A12345+myproj.process%3Amy.exe&sort=-timestamp&statsPeriod=14d&yAxis=count%28%29" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 OPR/110.0.0.0" "195.x.x.x"
nginx-1                                         | 172.20.0.1 - - [03/Jul/2024:06:13:04 +0000] "POST /api/1/envelope/?sentry_key=26068dceff924512951e9184e133751d&sentry_version=7&sentry_client=sentry.javascript.react%2F7.99.0 HTTP/1.0" 200 2 "https://my.sentry.tld/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 OPR/110.0.0.0" "195.x.x.x"

Is there any possibliity to do auth / pass token to a wget call to test this locally without nginx? I've tried 
wget http://172.20.0.36:9000/api/0/projects/sentry/myproj/events/96d8f0da0b37457d93e33fd8e56bb327/attachments/224093/?download=1
 but getting only "401 Unauthorized" as result...

**Comment by hubertdeng123** [comment]
Looks like I am able to download attachments, so I cannot reproduce this issue. Maybe this is a proxy buffering issue?
https://github.com/getsentry/self-hosted/issues/2256

**Comment by maxp1256** [comment]
@hubertdeng123 I'm also able to download "some" attachments/minidumps, but on specific ones I'm getting the 502. We've a second nginx before the docker one and I've already configured the mentioned settings but this error message is from the first nginx (docker-container) so I think the problem may be from the nginx configuration, but not from "our" top one.

**Comment by hubertdeng123** [comment]
Gotcha, are these "some" attachments/minidumps ones of larger sizes?
