### ISSUE TITLE
Stats Not Showing Any Transactions

### ISSUE THREAD

**Issue by rojinebrahimi** [getsentry/self-hosted#3181]
### Self-Hosted Version

24.5.1

### CPU Architecture

x86_64

### Docker Version

24.0.6

### Docker Compose Version

2.23.0

### Steps to Reproduce

![Screenshot 2024-07-03 at 12 54 26](https://github.com/getsentry/self-hosted/assets/44529498/1f204d3c-3412-4d71-a6ff-0128e9a2c98b)

### Expected Result

I have both **snuba transaction subscription consumer** and **snuba transaction consumer** up and running. But I see no transactions coming. Seems like they are being dropped:
![Screenshot 2024-07-03 at 12 56 16](https://github.com/getsentry/self-hosted/assets/44529498/0e58a8fa-0464-417b-9dec-5b3ffb63c577)

### Actual Result

What are possible reasons for this? I did not have the issue before upgrading to version 24.5.1 (I was using 24.2.0).
Could you please guide me through this? Thanks.

**Comment by ingria** [comment]
Possibly related to #2876

**Comment by rojinebrahimi** [comment]
> Possibly related to #2876

Thank you. Are there any temporary solutions for this version? Shall I upgrade the service?

**Comment by aldy505** [comment]
Have you try applying this? https://github.com/getsentry/self-hosted/pull/2908

Also do you have `snuba-outcomes-billing-consumer` on your compose project? See https://github.com/getsentry/self-hosted/pull/2909

**Comment by rojinebrahimi** [comment]
Yes, I have included the `snuba-outcomes-billing-consumer`. Still see no results for accepted transactions.

**Comment by hubertdeng123** [comment]
This should be resolved by adding the `snuba-outcomes-billing-consumer`. I'd suggest upgrading your self-hosted instance and checking if it works.

**Comment by zKoz210** [comment]
Still playable on 24.8.0. If I use rust consumer, everything works fine with Python.

**Comment by hubertdeng123** [comment]
@zKoz210 Are you saying on 24.8.0 switching to python consumer worked for you? We are able to see these stats properly on rust consumer

**Comment by karatekaneen** [comment]
@hubertdeng123 We also need to do the same change as @zKoz210 to be able to see anything other than regular issues. 
Running a much smaller instance though with 6 cores and 24gb RAM.
