### ISSUE TITLE
MaxRetryError   /api/0/organizations/{organization_id_or_slug}/events-trends-statsv2/

### ISSUE THREAD

**Issue by xuweixi10** [getsentry/self-hosted#3182]
### Self-Hosted Version

24.6.0

### CPU Architecture

x86_64

### Docker Version

24.0.7

### Docker Compose Version

2.23.3

### Steps to Reproduce

I found that the monitoring inside sentry keeps reporting errors. why?

### Expected Result

no error

### Actual Result

HTTPConnectionPool(host='127.0.0.1', port=9091): Max retries exceeded with url: /trends/breakpoint-detector (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff7a6d1d4d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
<img width="1049" alt="截屏2024-07-03 17 53 52" src="https://github.com/getsentry/self-hosted/assets/40662756/11330376-6bf8-45db-a1b6-1ee56e0ce0d0">

**Comment by aldy505** [comment]
This shouldn't happen. `seer` is a service that does not available on self-hosted, and probably won't be happening in the near future. Did you use any custom flags, if so can you specify those here?

**Comment by mzglinski** [comment]
Hi, I have a similar error

![image](https://github.com/getsentry/self-hosted/assets/23341314/ca757a70-fa27-4693-9640-b427a3da1506)

These are my feature flags for profiling 

```
              "organizations:profiling",
              "organizations:profiling-ui-frames",
              "organizations:profiling-using-transactions",
              "organizations:profiling-beta",
              "organizations:profiling-stacktrace-links",
              "organizations:profiling-global-suspect-functions",
              "organizations:profiling-cpu-chart",
              "organizations:profiling-memory-chart",
              "organizations:profiling-view",
 ```

**Comment by xuweixi10** [comment]
`        "organizations:discover",
        "organizations:events",
        "organizations:profiling-view",
        "organizations:global-views",
        "organizations:incidents",
        "organizations:integrations-issue-basic",
        "organizations:integrations-issue-sync",
        "organizations:invite-members",
        "organizations:metric-alert-builder-aggregate",
        "organizations:sso-basic",
        "organizations:sso-rippling",
        "organizations:sso-saml2",
        "organizations:performance-view",
        "organizations:advanced-search",
        "organizations:session-replay",
        "organizations:issue-platform",
        "organizations:profiling",
        "organizations:monitors",
        "organizations:dashboards-mep",
        "organizations:mep-rollout-flag",
        "organizations:dashboards-rh-widget",
        "organizations:metrics-extraction",
        "organizations:transaction-metrics-extraction",
        "projects:custom-inbound-filters",
        "projects:data-forwarding",
        "projects:discard-groups",
        "projects:sample-events",
        "projects:plugins",
        "projects:rate-limits",
        "organizations:performance-chart-interpolation",
        "organizations:performance-use-metrics",
        "organizations:dashboards-mep",
        "organizations:mep-rollout-flag",
        "organizations:use-metrics-layer",
        "organizations:starfish-view",
        "organizations:on-demand-metrics-extraction",
        "organizations:on-demand-metrics-extraction-widgets",
        "projects:servicehooks",
        "organizations:issue-details-tag-improvements",
        "organizations:anr-analyze-frames",
        "organizations:anr-improvements",
        "organizations:device-classification",
        "organizations:gitlab-disable-on-broken",
        "organizations:grouping-stacktrace-ui",
        "organizations:grouping-title-ui",
        "organizations:mobile-cpu-memory-in-transactions",
        "organizations:performance-metrics-backed-transaction-summary",
        "organizations:performance-new-trends",
        "organizations:performance-new-widget-designs",
        "organizations:performance-span-histogram-view",
        "organizations:performance-trace-details",
        "organizations:performance-trace-explorer",
        "organizations:performance-trace",
        "organizations:performance-trace-explorer-with-metrics",
        "organizations:performance-transaction-name-only-search-indexed",
        "organizations:profiling-global-suspect-functions",
        "organizations:user-feedback-ui",
        "organizations:custom-metrics",
        "organizations:custom-metrics-extraction-rule",
        "organizations:custom-metrics-experimental"` 
here is all my flags

**Comment by aldy505** [comment]
For @xuweixi10, this is your culprit: `"organizations:performance-new-trends"`. See https://github.com/getsentry/sentry/blob/f3af800c5809f1c60386813986914bbf85915811/src/sentry/api/endpoints/organization_events_trends_v2.py#L49-L73

For @mzglinski, this is your culprit: `"organizations:profiling-global-suspect-functions"`. See https://github.com/getsentry/sentry/blob/f3af800c5809f1c60386813986914bbf85915811/src/sentry/api/endpoints/organization_profiling_functions.py#L69-L79

Please confirm if removing the feature flag and re-running `./install.sh` does fix this for you. Then, we'll close the issue.
