### ISSUE TITLE
ChunkLoadError while loading sentry Sentry UI

### ISSUE THREAD

**Issue by farzadsoltani** [getsentry/self-hosted#3189]
### Self-Hosted Version

24.6.0

### CPU Architecture

x86_64

### Docker Version

26.1.3

### Docker Compose Version

2.27.0

### Steps to Reproduce

I'm on a fresh installation and when we try to log in, it gives the following error:

![image](https://github.com/getsentry/self-hosted/assets/148318636/8d661377-9dee-4132-b01e-2667dfcc90a6)

It works for me, but my teammates can't log in.

```
vendors-node_modules_emotion_react_jsx-runtime_dist_emotion-react-jsx-runtime_browser_esm_js--a96064.6143c0b99a3cf95e4c25.js:12 Uncaught SyntaxError: Invalid or unexpected token (at vendors-node_modules_emotion_react_jsx-runtime_dist_emotion-react-jsx-runtime_browser_esm_js--a96064.6143c0b99a3cf95e4c25.js:12:102334)
sentry/:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://sentry.supademo.com/_static/dist/sentry/assets/sentry-simple.560778129eda82ce960f.woff
app.js:1 Uncaught (in promise) ChunkLoadError
    at _.f.j (app.js:1:87020)
    at app.js:1:856
    at Array.reduce (<anonymous>)
    at _.e (app.js:1:835)
    at e (app.js:2:512)
    at app.js:2:924
    at app.js:2:929
    at app.js:2:933
```

### Expected Result

It should load fine without the errors.

### Actual Result

Install logs; https://paste.ubuntu.com/p/hcRVQvXN26/

Container logs: https://paste.ubuntu.com/p/kqdcPYhDFC/

**Comment by farzadsoltani** [comment]
I've already gone through everything here: https://github.com/getsentry/self-hosted/issues/1174

It doesn't seem to have anything to do with my issue.

**Comment by hubertdeng123** [comment]
I do not think this is an issue specifically with Sentry, and perhaps a network issue on your side. Are you also accessing your Sentry instance from the same machine?

**Comment by farzadsoltani** [comment]
> I do not think this is an issue specifically with Sentry, and perhaps a network issue on your side. Are you also accessing your Sentry instance from the same machine?

Thanks for the reply. I didn't fully understand your question. Do you mean am I SSHing into the sentry server from my machine? If so, then yes.

It just randomly doesn't load for some of my teammates and we're 100% sure it's not a network issue.

**Comment by aldy505** [comment]
> > I do not think this is an issue specifically with Sentry, and perhaps a network issue on your side. Are you also accessing your Sentry instance from the same machine?
> 
> Thanks for the reply. I didn't fully understand your question. Do you mean am I SSHing into the sentry server from my machine? If so, then yes.

Accessing Sentry instance from the same machine means you're accessing it via "localhost", which from your Sentry URL, I believe you're accessing it via public internet.
 
> It just randomly doesn't load for some of my teammates and we're 100% sure it's not a network issue.

If it's not a network issue, do you happen to know of which web browser that your teammates used? If they're using some kind of ad-blocking mechanism or some privacy-strict browsers like Brave or Librewolf, I'd suggest to disable the protections (so disable ad-blocker, allow fingerprinting, allow cookies, etc).

**Comment by farzadsoltani** [comment]
@aldy505 Yes, it's being accessed via public internet.

We've tested on almost every browser and it's the same result (Safari, Chrome, Arc, Firefox). They don't have adblockers enabled and we're all devs.

**Comment by IanWoodard** [comment]
Could you provide more information about the setup you are using to host Sentry?

> It just randomly doesn't load for some of my teammates and we're 100% sure it's not a network issue.

Does this mean it intermittently works for your teammates but sometimes fails to load or does it never load for them?

You mentioned that you were able to access it. Are your teammates trying to access it the same way you are or are they doing it differently?

**Comment by farzadsoltani** [comment]
> Could you provide more information about the setup you are using to host Sentry?

It's just a basic installation with no extra setup. The only configuration I changed was for setting up my own URL. Is there anything specific you're looking for?


> Does this mean it intermittently works for your teammates but sometimes fails to load or does it never load for them?

It just never loads for them. One thing to consider is that since we haven't setup any mail provider, we're all using the same username and password to access it.

> You mentioned that you were able to access it. Are your teammates trying to access it the same way you are or are they doing it differently?

Yup, we all open it in the same browsers with the same version.

**Comment by hubertdeng123** [comment]
For setting up your own URL, did you appropriately set your `system.url-prefix`? Otherwise, I'm out of ideas on what may be happening.

**Comment by farzadsoltani** [comment]
> For setting up your own URL, did you appropriately set your `system.url-prefix`? Otherwise, I'm out of ideas on what may be happening.

Yup, I did. I don't think it would be working if I hadn't done this.

**Comment by nodir-malikov** [comment]
I recently encountered this issue. This solution helped me resolve it:

1. Run `docker-compose down` on your sentry self-hosted folder
2. Then, run `sudo ./install.sh`
3. Clear your browser's cache

I hope this will also solve your problem.

**Comment by farzadsoltani** [comment]
> I recently encountered this issue. This solution helped me resolve it:
> 
> 1. Run `docker-compose down` on your sentry self-hosted folder
> 2. Then, run `sudo ./install.sh`
> 3. Start it with `docker-compose up -d`
> 4. Clear your browser's cache and try to open your Sentry website
> 
> I hope this will also solve your problem.

This actually worked a while ago, but then it started happening again :| 
How long ago did you do this?

**Comment by nodir-malikov** [comment]
> This actually worked a while ago, but then it started happening again :| How long ago did you do this?

Yes, you're right. It happened again. I did this two days ago.

**Comment by nodir-malikov** [comment]
Wow, I think I found what caused the problem. After disabling the Cloudflare proxy in the DNS settings for my domain, everything seems to be working again. Do you also use Cloudflare Proxy for your domain?

**Comment by farzadsoltani** [comment]
> Wow, I think I found what caused the problem. After disabling the Cloudflare proxy in the DNS settings for my domain, everything seems to be working again. Do you also use Cloudflare Proxy for your domain?

It seems like this actually fixed it. I disabled the proxy, and it's loading for everyone. Let's keep this thread open for a few more days and I will report back if it's fully fixed.

**Comment by farzadsoltani** [comment]
The Cloudflare change fixed this. Thanks @nodir-malikov 

Although I'm closing this issue, I think it needs to be investigated more as this is more of a hack than a fix.
