### ISSUE TITLE
How to change Admin's email

### ISSUE THREAD

**Issue by linxiaowang** [getsentry/self-hosted#3196]
### Problem Statement

When first install set the admin's email, now I want to change it, but find no way, 
tryed
`docker-compose run --rm web createuser --email  ** --password  ** --superuser`
and delete the origin admin from member settings,  but the email still record the origin Admin's email

**Comment by hubertdeng123** [comment]
You should be able to change the user email in the admin settings. Are you not able to do that?

https://sentry.zendesk.com/hc/en-us/articles/23849998289435-How-do-I-update-my-email-password#:~:text=To%20change%20your%20email%20address,primary%22%20for%20the%20new%20address.

**Comment by linxiaowang** [comment]
> You should be able to change the user email in the admin settings. Are you not able to do that?
> 
> https://sentry.zendesk.com/hc/en-us/articles/23849998289435-How-do-I-update-my-email-password#:~:text=To%20change%20your%20email%20address,primary%22%20for%20the%20new%20address.



> You should be able to change the user email in the admin settings. Are you not able to do that?
> 
> https://sentry.zendesk.com/hc/en-us/articles/23849998289435-How-do-I-update-my-email-password#:~:text=To%20change%20your%20email%20address,primary%22%20for%20the%20new%20address.

Thank you for your response. I really wish I could see your reply earlier. I thought 'additional email' meant adding an extra email without realizing that it's possible to remove the original email after adding a new one. As a result, I had to reinstall Sentry and set it up again. Thanks again for your great job!
