### ISSUE TITLE
Release 24.8.0

### ISSUE THREAD

**Issue by IanWoodard** [getsentry/self-hosted#3203]
### Body

[24.7.0](https://github.com/getsentry/self-hosted/issues/3140) | ***24.8.0*** | [24.9.0](https://github.com/getsentry/self-hosted/issues/3271)

- [x] Release all components (_replace items with [publish repo issue links](https://github.com/getsentry/publish/issues)_).
  - https://github.com/getsentry/publish/issues/4218
  - https://github.com/getsentry/publish/issues/4219
  - https://github.com/getsentry/publish/issues/4220
  - https://github.com/getsentry/publish/issues/4221
  - https://github.com/getsentry/publish/issues/4217
- [x] Release self-hosted.
  - [x] https://github.com/getsentry/publish/issues/4222
  - [x] Check to make sure the new release branch in self-hosted includes the appropriate CalVer images.
  - [x] Accept (publish) the release.
  - [x] Edit [release notes](https://github.com/getsentry/self-hosted/releases).
- [x] Follow up.
  - [x] [Create the next release issue](https://github.com/getsentry/self-hosted/issues/new?assignees=&labels=&projects=&template=release.yml) and link it from this one.
    - _replace with link_
  - [x] Create a PR to update relocation release tests to add the new version.
    - https://github.com/getsentry/sentry/pull/76291

**Comment by aldy505** [comment]
@joshuarli @hubertdeng123 just curious, why are we not publishing sentry-docs again? Isn't publishing a versioned docs a good idea? Or do you guys have any other approach for that?

**Comment by joshuarli** [comment]
Versioned docs were never a thing, it's not like we ever had something like https://develop.sentry.dev/24.8.0/self-hosted/.
