### ISSUE TITLE
Question: Why profiling might not work on self hosted 23.10.1

### ISSUE THREAD

**Issue by antonsacred** [getsentry/self-hosted#3207]
### Self-Hosted Version

23.10.1

### CPU Architecture

x86_64

### Docker Version

-

### Docker Compose Version

-

### Steps to Reproduce

Not a direct bug, but on our instance profiling is not available:

* We have profiling widget inside performance summary
<img width="1140" alt="Screenshot 2024-07-17 at 11 58 43 PM" src="https://github.com/user-attachments/assets/88bb0cba-c235-4c9e-90ef-38908e1ea73c">
* But when I click to any of profiles I get error "You don't have access to this feature"

### Question

Why feature might not work on that version of self hosted version? Is there any feature toggle?

### Actual Result

<img width="371" alt="Screenshot 2024-07-18 at 12 04 36 AM" src="https://github.com/user-attachments/assets/0a6a6263-d1e5-4bac-95e9-7a9f33890705">

**Comment by joshuarli** [comment]
In sentry, it's off by default, and doesn't look like we enable it in the default self-hosted config. Try setting `SENTRY_USE_PROFILING = True` in your `sentry.conf.py`.

@hubertdeng123 I think should we enable? Otherwise what's the point of installing `vroom`?

**Comment by hubertdeng123** [comment]
Profiling should be enabled, it was added [here](https://github.com/getsentry/self-hosted/pull/2154). Can you check your sentry.conf.py file? Maybe you just don't have the right feature flags enabled.

Specifically `organizations:profiling`.
