### ISSUE TITLE
I cannot see the Traces and Metrics on the UI

### ISSUE THREAD

**Issue by trixobird** [getsentry/self-hosted#3214]
### Self-Hosted Version

24.7.0

### CPU Architecture

x86_64

### Docker Version

25.0.3

### Docker Compose Version

v2.29.0

### Steps to Reproduce

1. Open the UI

### Expected Result

On the left menu I expected to see Traces and Metrics

### Actual Result

I was not able to see these two options

**Comment by aldy505** [comment]
Yeah those two are behind a feature flags.

For Metrics, please refer to https://github.com/getsentry/self-hosted/issues/2698#issuecomment-1884061830

For Traces, please add `"organizations:performance-trace-explorer",` onto the list of feature flags on the `sentry/sentry.conf.py` file.
