### ISSUE TITLE
GitHub Integration Setup Screen leads to 404

### ISSUE THREAD

**Issue by fabio-thoma** [getsentry/self-hosted#3215]
### Self-Hosted Version

24.7.0

### CPU Architecture

x86_64

### Docker Version

27.0.3

### Docker Compose Version

2.28.1

### Steps to Reproduce

1. Open "Integrations" in Organization Settings (https://<sentry_base_url>/settings/sentry/integrations/github/)
2. Click on "Add Installation"
3. Log into GitHub

Now the setup fails. GitHub leads to 404 Page
https://github.com/login/oauth/authorize?client_id=&state=<clientid>&redirect_uri=https://<sentry_base_url>/extensions/github/setup/

### Expected Result

It should redirect to GitHub Authorization Screen.

### Actual Result

![Image](https://github.com/user-attachments/assets/b537ee79-192a-47ea-9713-4e652128c6b9)

**Comment by aldy505** [comment]
`client_id` should not be empty. Make sure you have everything that's defined here: https://github.com/getsentry/self-hosted/blob/485d3ffd2f6e6bc5b64afb0721ac2e75ed5ee33a/sentry/config.example.yml#L96-L109

For additional missing callback url, see https://github.com/getsentry/develop/issues/1254
