### ISSUE TITLE
Symbolicator  slow error

### ISSUE THREAD

**Issue by CodegeassBala** [getsentry/self-hosted#3216]
### Self-Hosted Version

24.3.0

### CPU Architecture

x86_64

### Docker Version

27.3

### Docker Compose Version

2.6

### Steps to Reproduce

set relay upstream to local url,

using a custom network in docker compose 

### Expected Result

The errors should get processed.

### Actual Result

[WARNING] sentry.errors.events: symbolicate.slow (project_id=2 event_id='9cf67db263764d7fb90b347177c47dd3')

![Image](https://github.com/user-attachments/assets/613adf4e-6940-4422-8a40-fb3ce1e094ae)

**Comment by CodegeassBala** [comment]
Can anyone please help on this, been stuck on this for quite a while now.

**Comment by IanWoodard** [comment]
Could you provide more context? Are the errors still being ingested properly? This just looks like a warning and isn't indicative of an error.

**Comment by CodegeassBala** [comment]
The errors are being injected but take too long like 30-40 mins. The errors show up only after the infinite retry is hit and the logs for that event stop. Temporarily disabled symbolicator, but would like to know how to fix this.

**Comment by soupdumplings** [comment]
Is this the only event where there's an error? I've encountered similar issues, and the cause was the slow network speed when downloading symbol files.

**Comment by IanWoodard** [comment]
Does disabling symbolicator speed things up? Could you also share the logs from the symbolicator container?

**Comment by CodegeassBala** [comment]
Disabling symbolicator does work, but then the stack trace would not map to the source code, right?

**Comment by hubertdeng123** [comment]
Yep, that is correct. What does your CPU/RAM usage look like?
