### ISSUE TITLE
Web Vitals still broken because of feature flags

### ISSUE THREAD

**Issue by hheexx** [getsentry/self-hosted#3225]
### Self-Hosted Version

24.6.1

### CPU Architecture

x86_64

### Docker Version

0.0.0

### Docker Compose Version

0.0.0

### Steps to Reproduce

Missing feature flag on master:  organizations:performance-insights

### Expected Result

/

### Actual Result

/

**Comment by aldy505** [comment]
I'm going to close this issue as a duplicate of https://github.com/getsentry/self-hosted/issues/3145

It's recommended to upgrade to 24.7.1 tho, there's a security fix for https://github.com/getsentry/sentry/security/advisories/GHSA-fm88-hc3v-3www. Also everything under "Insights" works there!

**Comment by hheexx** [comment]
@aldy505 sorry I entered an wrong version. I am already on 24.7.1 and insights were not working until I added  organizations:performance-insights feature flag.
As I said that feature flag is not currently on master.

**Comment by aldy505** [comment]
Are you sure you put the correct version on the .env file? Or did you use the .env.custom file? The feature flag was removed from the main sentry repository a while back before the 24.7.0 release though.
