### ISSUE TITLE
./sentey/config.yml change SMTP port not working

### ISSUE THREAD

**Issue by houzp** [getsentry/self-hosted#3229]
### Self-Hosted Version

24.7

### CPU Architecture

x86_64

### Docker Version

24.0.6

### Docker Compose Version

v2.21.0-desktop.1

### Steps to Reproduce

1. changed ./self-hosted-24.7.0/sentry/config.yml mail.port:25 to mail.port:465
2. docker compose down
3. ./install.sh
4. docker compose up
5. open webui ,F5 page,input password ,click th button ' send a test email ' then fail.

### Expected Result

get a email

### Actual Result

page return send mail fail.
and,
by smtp image author  (https://hub.docker.com/r/tianon/exim4),
the image no longer updated
please change the image to fix unknow bugs in futhure

**Comment by asottile-sentry** [comment]
changing the port in the configuration will break any connections to the container (which binds to port 25) -- you'd have to change it in both places though I'm not sure why you would do that
