### ISSUE TITLE
Redis memory is frequently being filled up

### ISSUE THREAD

**Issue by lunuan** [getsentry/self-hosted#3230]
### Problem Statement

Hi,

I'm experiencing an issue where my Redis memory is frequently being filled up. I've noticed that there are many string-type keys with formats like "e:38f7d1b4b32743a982be9738672f0064:43". The values associated with these keys are transaction events.

I would like to know:

Which service is writing these data into Redis?
Under what circumstances are these data being written to Redis?
Thank you for your assistance.

**Comment by xuweixi10** [comment]
maybe you need run more sentry worker to consumer the events.
