### ISSUE TITLE
Cron Job show Progress Or Failed

### ISSUE THREAD

**Issue by xuweixi11** [getsentry/self-hosted#3231]
### Self-Hosted Version

24.7.0

### CPU Architecture

x86_64

### Docker Version

27.0.3

### Docker Compose Version

2.28.1

### Steps to Reproduce

1. select cron tab
2. select the internal project

### Expected Result

maybe it should show success?

### Actual Result

![Image](https://github.com/user-attachments/assets/49e53e10-96f1-4653-9c73-ebdd0e71075b)
![Image](https://github.com/user-attachments/assets/324c4519-1136-4ed6-a42e-c60c299604e9)
![Image](https://github.com/user-attachments/assets/9847e20b-3941-4aed-9c63-ff7b7cb7169a)

**Comment by IanWoodard** [comment]
Could you provide more context? How are you configuring your cron monitors?

**Comment by xuweixi10** [comment]
Fine i the docker timezone i change to UTC every thing is ok

**Comment by xuweixi10** [comment]
i upgrade from 24.6.0 maybe some cron is deprecated? like clear-expired-raw-events

![Image](https://github.com/user-attachments/assets/9e82072c-a4d8-4848-a0d2-354b53845fa9)
