### ISSUE TITLE
Error in install 23.6.2

### ISSUE THREAD

**Issue by AlexFisher94** [getsentry/self-hosted#3233]
### Self-Hosted Version

23.6.2

### CPU Architecture

x86_64

### Docker Version

26.1.2

### Docker Compose Version

2.27.0

### Steps to Reproduce

1. git clone https://github.com/getsentry/self-hosted.git
2. git fetch
3. git checkout 23.6.2
4. nano docker-compose.yml (correcting paths to ssl certificates in `environment` and add volume with ssl certs to `nginx`)
5. sudo ./install.sh

### Expected Result

Successful installation

### Actual Result

Hello

I'm trying to install sentry 23.6.2. I know that is old version sentry, but it's need for checking update procedure

When i use `./install.sh` i have an error:

`[root@sa-vm-sentry-test self-hosted]# ./install.sh
▶ Parsing command line ...

▶ Detecting Docker platform
Detected Docker platform is linux/amd64

▶ Initializing Docker Compose ...

▶ Setting up error handling ...
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 351B done
#1 DONE 0.0s

#2 [internal] load metadata for docker.io/library/debian:bullseye-slim
#2 DONE 0.4s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [1/2] FROM docker.io/library/debian:bullseye-slim@sha256:b257e5e831aa9949737638f6d323cd563347b2a5571d98b9b15eef0c7cd80b68
#4 DONE 0.0s

#5 [2/2] RUN set -x   && apt-get update   && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends jq   && apt-get clean   && rm -rf /var/lib/apt/lists/*
#5 CACHED

#6 exporting to image
#6 exporting layers done
#6 writing image sha256:a0d838622ea3f70c79c03b5dda401bdb9dff59f87aee2004f139e35cd3c3b27b done
#6 naming to docker.io/library/sentry-self-hosted-jq-local done
#6 DONE 0.0s

Hey, so ... we would love to automatically find out about issues with your
Sentry instance so that we can improve the product. Turns out there is an app
for that, called Sentry. Would you be willing to let us automatically send data
about your instance upstream to Sentry for development and debugging purposes?

  y / yes / 1
  n / no / 0

(Btw, we send this to our own self-hosted Sentry instance, not to Sentry SaaS,
so that we can be in this together.)

Here's the info we may collect:

  - OS username
  - IP address
  - install log
  - runtime errors
  - performance data

Thirty (30) day retention. No marketing. Privacy policy at sentry.io/privacy.

y or n? n

Understood. To avoid this prompt in the future, use one of these flags:

  --report-self-hosted-issues
  --no-report-self-hosted-issues

or set the REPORT_SELF_HOSTED_ISSUES environment variable:

  REPORT_SELF_HOSTED_ISSUES=1 to send data
  REPORT_SELF_HOSTED_ISSUES=0 to not send data

▶ Checking for latest commit ...
skipped

▶ Checking minimum requirements ...
Found Docker version 26.1.2
Found Docker Compose version 2.27.0

▶ Turning things off ...
 Network sentry-self-hosted_default  Removing
 Network sentry-self-hosted_default  Removed

▶ Creating volumes for persistent storage ...
Created sentry-clickhouse.
Created sentry-data.
Created sentry-kafka.
Created sentry-postgres.
Created sentry-redis.
Created sentry-symbolicator.
Created sentry-zookeeper.

▶ Ensuring files from examples ...
sentry/sentry.conf.py already exists, skipped creation.
sentry/config.yml already exists, skipped creation.
symbolicator/config.yml already exists, skipped creation.

▶ Ensuring Relay credentials ...
relay/config.yml already exists, skipped creation.
relay/credentials.json already exists, skipped creation.

▶ Generating secret key ...
Secret key written to sentry/config.yml

▶ Fetching and updating Docker images ...
23.6.2: Pulling from getsentry/sentry
Digest: sha256:2668569bbb37a883818786581342f1d67529fc573a2e98c321479516271f063a
Status: Image is up to date for getsentry/sentry:23.6.2
docker.io/getsentry/sentry:23.6.2

▶ Building and tagging Docker images ...

#0 building with "default" instance using docker driver

#1 [web internal] load build definition from Dockerfile
#1 transferring dockerfile: 522B done
#1 DONE 0.0s

#2 [web internal] load metadata for docker.io/getsentry/sentry:23.6.2
#2 DONE 0.0s

#3 [web internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [web internal] load build context
#4 transferring context: 28.79kB done
#4 DONE 0.0s

#5 [web 1/4] FROM docker.io/getsentry/sentry:23.6.2
#5 CACHED

#6 [web 2/4] COPY . /usr/src/sentry
#6 DONE 0.0s

#7 [web 3/4] RUN if [ -s /usr/src/sentry/enhance-image.sh ]; then     /usr/src/sentry/enhance-image.sh; fi
#7 DONE 0.2s

#8 [web 4/4] RUN if [ -s /usr/src/sentry/requirements.txt ]; then     echo "sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image";     pip install -r /usr/src/sentry/requirements.txt; fi
#8 DONE 0.3s

#9 [web] exporting to image
#9 exporting layers 0.0s done
#9 writing image sha256:46f24dc5696dbae1a49d44be6f626e958a34fb18c92701ea8a9f85cb294dca9d done
#9 naming to docker.io/library/sentry-self-hosted-local done
#9 DONE 0.0s
#0 building with "default" instance using docker driver

#1 [clickhouse internal] load build definition from Dockerfile
#1 transferring dockerfile: 130B done
#1 DONE 0.0s

#2 [clickhouse internal] load metadata for docker.io/yandex/clickhouse-server:20.3.9.70
#2 DONE 0.0s

#3 [clickhouse internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [clickhouse 1/1] FROM docker.io/yandex/clickhouse-server:20.3.9.70
#4 CACHED

#5 [clickhouse] exporting to image
#5 exporting layers done
#5 writing image sha256:0943fe45e0a729f7696680cc96b654042937d3be487b3e24e0512e715a0f102b done
#5 naming to docker.io/library/clickhouse-self-hosted-local done
#5 DONE 0.0s
#0 building with "default" instance using docker driver

#1 [subscription-consumer-transactions internal] load build definition from Dockerfile
#1 transferring dockerfile: 522B done
#1 DONE 0.0s

#2 [subscription-consumer-transactions internal] load metadata for docker.io/getsentry/sentry:23.6.2
#2 DONE 0.0s

#3 [subscription-consumer-transactions internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [subscription-consumer-transactions 1/4] FROM docker.io/getsentry/sentry:23.6.2
#4 DONE 0.0s

#5 [subscription-consumer-transactions internal] load build context
#5 transferring context: 769B done
#5 DONE 0.0s

#6 [subscription-consumer-transactions 3/4] RUN if [ -s /usr/src/sentry/enhance-image.sh ]; then     /usr/src/sentry/enhance-image.sh; fi
#6 CACHED

#7 [subscription-consumer-transactions 2/4] COPY . /usr/src/sentry
#7 CACHED

#8 [subscription-consumer-transactions 4/4] RUN if [ -s /usr/src/sentry/requirements.txt ]; then     echo "sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image";     pip install -r /usr/src/sentry/requirements.txt; fi
#8 CACHED

#9 [subscription-consumer-transactions] exporting to image
#9 exporting layers done
#9 writing image sha256:9bb9239813ff769a602bab4911545f831931caba392f1570f00482991d1fb5cb done
#9 naming to docker.io/library/sentry-self-hosted-local done
#9 DONE 0.0s
#0 building with "default" instance using docker driver

#1 [ingest-profiles internal] load build definition from Dockerfile
#1 transferring dockerfile: 522B done
#1 DONE 0.0s

#2 [ingest-profiles internal] load metadata for docker.io/getsentry/sentry:23.6.2
#2 DONE 0.0s

#3 [ingest-profiles internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [ingest-profiles 1/4] FROM docker.io/getsentry/sentry:23.6.2
#4 DONE 0.0s

#5 [ingest-profiles internal] load build context
#5 transferring context: 769B done
#5 DONE 0.0s

#6 [ingest-profiles 2/4] COPY . /usr/src/sentry
#6 CACHED

#7 [ingest-profiles 3/4] RUN if [ -s /usr/src/sentry/enhance-image.sh ]; then     /usr/src/sentry/enhance-image.sh; fi
#7 CACHED

#8 [ingest-profiles 4/4] RUN if [ -s /usr/src/sentry/requirements.txt ]; then     echo "sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image";     pip install -r /usr/src/sentry/requirements.txt; fi
#8 CACHED

#9 [ingest-profiles] exporting to image
#9 exporting layers done
#9 writing image sha256:b2476bbffbab151e698ca7e3124edb1156d4f30e06d1139270c594e5dbed4596 done
#9 naming to docker.io/library/sentry-self-hosted-local done
#9 DONE 0.0s
#0 building with "default" instance using docker driver

#1 [symbolicator-cleanup internal] load build definition from Dockerfile
#1 transferring dockerfile: 528B done
#1 DONE 0.0s

#2 [symbolicator-cleanup internal] load metadata for docker.io/getsentry/symbolicator:23.6.2
#2 DONE 0.0s

#3 [symbolicator-cleanup internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [symbolicator-cleanup 1/5] FROM docker.io/getsentry/symbolicator:23.6.2
#4 DONE 0.0s

#5 [symbolicator-cleanup internal] load build context
#5 transferring context: 717B done
#5 DONE 0.0s

#6 [symbolicator-cleanup 4/5] RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
#6 CACHED

#7 [symbolicator-cleanup 3/5] RUN if [ -z "${https_proxy}" ]; then echo "Acquire::https::proxy "${https_proxy}";" >> /etc/apt/apt.conf; fi
#7 CACHED

#8 [symbolicator-cleanup 2/5] RUN if [ -z "${http_proxy}" ]; then echo "Acquire::http::proxy "${http_proxy}";" >> /etc/apt/apt.conf; fi
#8 CACHED

#9 [symbolicator-cleanup 5/5] COPY entrypoint.sh /entrypoint.sh
#9 CACHED

#10 [symbolicator-cleanup] exporting to image
#10 exporting layers done
#10 writing image sha256:b8b06334df13691a425d08c3e952386b9cf7c8709ebc73d59bd0e86eecb4aa08 done
#10 naming to docker.io/library/symbolicator-cleanup-self-hosted-local done
#10 DONE 0.0s
#0 building with "default" instance using docker driver

#1 [transactions-consumer internal] load build definition from Dockerfile
#1 transferring dockerfile: 522B done
#1 DONE 0.0s

#2 [transactions-consumer internal] load metadata for docker.io/getsentry/sentry:23.6.2
#2 DONE 0.0s

#3 [transactions-consumer internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [transactions-consumer 1/4] FROM docker.io/getsentry/sentry:23.6.2
#4 DONE 0.0s

#5 [transactions-consumer internal] load build context
#5 transferring context: 28.79kB done
#5 DONE 0.0s

#6 [transactions-consumer 2/4] COPY . /usr/src/sentry
#6 CACHED

#7 [transactions-consumer 3/4] RUN if [ -s /usr/src/sentry/enhance-image.sh ]; then     /usr/src/sentry/enhance-image.sh; fi
#7 CACHED

#8 [transactions-consumer 4/4] RUN if [ -s /usr/src/sentry/requirements.txt ]; then     echo "sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image";     pip install -r /usr/src/sentry/requirements.txt; fi
#8 CACHED

#9 [transactions-consumer] exporting to image
#9 exporting layers done
#9 writing image sha256:23a43aac02eef364b01000e2621df427adcb37a587bf5a45ab59344f34217488 done
#9 naming to docker.io/library/sentry-self-hosted-local done
#9 DONE 0.0s
#0 building with "default" instance using docker driver

#1 [attachments-consumer internal] load build definition from Dockerfile
#1 transferring dockerfile: 522B done
#1 DONE 0.0s

#2 [attachments-consumer internal] load metadata for docker.io/getsentry/sentry:23.6.2
#2 DONE 0.0s

#3 [attachments-consumer internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [attachments-consumer 1/4] FROM docker.io/getsentry/sentry:23.6.2
#4 DONE 0.0s

#5 [attachments-consumer internal] load build context
#5 transferring context: 769B done
#5 DONE 0.0s

#6 [attachments-consumer 3/4] RUN if [ -s /usr/src/sentry/enhance-image.sh ]; then     /usr/src/sentry/enhance-image.sh; fi
#6 CACHED

#7 [attachments-consumer 2/4] COPY . /usr/src/sentry
#7 CACHED

#8 [attachments-consumer 4/4] RUN if [ -s /usr/src/sentry/requirements.txt ]; then     echo "sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image";     pip install -r /usr/src/sentry/requirements.txt; fi
#8 CACHED

#9 [attachments-consumer] exporting to image
#9 exporting layers done
#9 writing image sha256:0c7d0cc6cd7936bb4b1326cb1d497977a17579714c24bd2916b4911dd318bd47 done
#9 naming to docker.io/library/sentry-self-hosted-local done
#9 DONE 0.0s
#0 building with "default" instance using docker driver

#1 [ingest-replay-recordings internal] load build definition from Dockerfile
#1 transferring dockerfile: 522B done
#1 DONE 0.0s

#2 [ingest-replay-recordings internal] load metadata for docker.io/getsentry/sentry:23.6.2
#2 DONE 0.0s

#3 [ingest-replay-recordings internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [ingest-replay-recordings 1/4] FROM docker.io/getsentry/sentry:23.6.2
#4 DONE 0.0s

#5 [ingest-replay-recordings internal] load build context
#5 transferring context: 769B done
#5 DONE 0.0s

#6 [ingest-replay-recordings 3/4] RUN if [ -s /usr/src/sentry/enhance-image.sh ]; then     /usr/src/sentry/enhance-image.sh; fi
#6 CACHED

#7 [ingest-replay-recordings 2/4] COPY . /usr/src/sentry
#7 CACHED

#8 [ingest-replay-recordings 4/4] RUN if [ -s /usr/src/sentry/requirements.txt ]; then     echo "sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image";     pip install -r /usr/src/sentry/requirements.txt; fi
#8 CACHED

#9 [ingest-replay-recordings] exporting to image
#9 exporting layers done
#9 writing image sha256:4fbd34cf044cfa0cae442ea48f9bd8b10aef52e252ebbf1029b0c11abd5aeb2b done
#9 naming to docker.io/library/sentry-self-hosted-local done
#9 DONE 0.0s
#0 building with "default" instance using docker driver

#1 [post-process-forwarder-transactions internal] load build definition from Dockerfile
#1 transferring dockerfile: 522B done
#1 DONE 0.0s

#2 [post-process-forwarder-transactions internal] load metadata for docker.io/getsentry/sentry:23.6.2
#2 DONE 0.0s

#3 [post-process-forwarder-transactions internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [post-process-forwarder-transactions 1/4] FROM docker.io/getsentry/sentry:23.6.2
#4 DONE 0.0s

#5 [post-process-forwarder-transactions internal] load build context
#5 transferring context: 769B done
#5 DONE 0.0s

#6 [post-process-forwarder-transactions 3/4] RUN if [ -s /usr/src/sentry/enhance-image.sh ]; then     /usr/src/sentry/enhance-image.sh; fi
#6 CACHED

#7 [post-process-forwarder-transactions 2/4] COPY . /usr/src/sentry
#7 CACHED

#8 [post-process-forwarder-transactions 4/4] RUN if [ -s /usr/src/sentry/requirements.txt ]; then     echo "sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image";     pip install -r /usr/src/sentry/requirements.txt; fi
#8 CACHED

#9 [post-process-forwarder-transactions] exporting to image
#9 exporting layers done
#9 writing image sha256:1265205a3e2c11426b8dcaebd91d37d8b6b6a422019d6bfde4e3d04fda8e80fd done
#9 naming to docker.io/library/sentry-self-hosted-local done
#9 DONE 0.0s
#0 building with "default" instance using docker driver

#1 [web internal] load build definition from Dockerfile
#1 transferring dockerfile: 522B done
#1 DONE 0.0s

#2 [web internal] load metadata for docker.io/getsentry/sentry:23.6.2
#2 DONE 0.0s

#3 [web internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [web 1/4] FROM docker.io/getsentry/sentry:23.6.2
#4 DONE 0.0s

#5 [web internal] load build context
#5 transferring context: 769B done
#5 DONE 0.0s

#6 [web 3/4] RUN if [ -s /usr/src/sentry/enhance-image.sh ]; then     /usr/src/sentry/enhance-image.sh; fi
#6 CACHED

#7 [web 2/4] COPY . /usr/src/sentry
#7 CACHED

#8 [web 4/4] RUN if [ -s /usr/src/sentry/requirements.txt ]; then     echo "sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image";     pip install -r /usr/src/sentry/requirements.txt; fi
#8 CACHED

#9 [web] exporting to image
#9 exporting layers done
#9 writing image sha256:46f24dc5696dbae1a49d44be6f626e958a34fb18c92701ea8a9f85cb294dca9d done
#9 naming to docker.io/library/sentry-self-hosted-local done
#9 DONE 0.0s
#0 building with "default" instance using docker driver

#1 [events-consumer internal] load build definition from Dockerfile
#1 transferring dockerfile: 522B done
#1 DONE 0.0s

#2 [events-consumer internal] load metadata for docker.io/getsentry/sentry:23.6.2
#2 DONE 0.0s

#3 [events-consumer internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [events-consumer 1/4] FROM docker.io/getsentry/sentry:23.6.2
#4 DONE 0.0s

#5 [events-consumer internal] load build context
#5 transferring context: 769B done
#5 DONE 0.0s

#6 [events-consumer 3/4] RUN if [ -s /usr/src/sentry/enhance-image.sh ]; then     /usr/src/sentry/enhance-image.sh; fi
#6 CACHED

#7 [events-consumer 2/4] COPY . /usr/src/sentry
#7 CACHED

#8 [events-consumer 4/4] RUN if [ -s /usr/src/sentry/requirements.txt ]; then     echo "sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image";     pip install -r /usr/src/sentry/requirements.txt; fi
#8 CACHED

#9 [events-consumer] exporting to image
#9 exporting layers done
#9 writing image sha256:f5727fd9438ac57c51f13afdbee8c174c97b2f9f7fd28aa2d8514612b483145c done
#9 naming to docker.io/library/sentry-self-hosted-local done
#9 DONE 0.0s
#0 building with "default" instance using docker driver

#1 [post-process-forwarder-errors internal] load build definition from Dockerfile
#1 transferring dockerfile: 522B done
#1 DONE 0.0s

#2 [post-process-forwarder-errors internal] load metadata for docker.io/getsentry/sentry:23.6.2
#2 DONE 0.0s

#3 [post-process-forwarder-errors internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [post-process-forwarder-errors 1/4] FROM docker.io/getsentry/sentry:23.6.2
#4 DONE 0.0s

#5 [post-process-forwarder-errors internal] load build context
#5 transferring context: 769B done
#5 DONE 0.0s

#6 [post-process-forwarder-errors 2/4] COPY . /usr/src/sentry
#6 CACHED

#7 [post-process-forwarder-errors 3/4] RUN if [ -s /usr/src/sentry/enhance-image.sh ]; then     /usr/src/sentry/enhance-image.sh; fi
#7 CACHED

#8 [post-process-forwarder-errors 4/4] RUN if [ -s /usr/src/sentry/requirements.txt ]; then     echo "sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image";     pip install -r /usr/src/sentry/requirements.txt; fi
#8 CACHED

#9 [post-process-forwarder-errors] exporting to image
#9 exporting layers done
#9 writing image sha256:7e4cfa13672aa633129c6ab5d2e56c5b4d06a29f60dd3ab10595e318878cbeef done
#9 naming to docker.io/library/sentry-self-hosted-local done
#9 DONE 0.0s
#0 building with "default" instance using docker driver

#1 [worker internal] load build definition from Dockerfile
#1 transferring dockerfile: 522B done
#1 DONE 0.0s

#2 [worker internal] load metadata for docker.io/getsentry/sentry:23.6.2
#2 DONE 0.0s

#3 [worker internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [worker 1/4] FROM docker.io/getsentry/sentry:23.6.2
#4 DONE 0.0s

#5 [worker internal] load build context
#5 transferring context: 769B done
#5 DONE 0.0s

#6 [worker 3/4] RUN if [ -s /usr/src/sentry/enhance-image.sh ]; then     /usr/src/sentry/enhance-image.sh; fi
#6 CACHED

#7 [worker 2/4] COPY . /usr/src/sentry
#7 CACHED

#8 [worker 4/4] RUN if [ -s /usr/src/sentry/requirements.txt ]; then     echo "sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image";     pip install -r /usr/src/sentry/requirements.txt; fi
#8 CACHED

#9 [worker] exporting to image
#9 exporting layers done
#9 writing image sha256:c5dd0daf5162938eca82faddbc336b20aa667984862303cebfe0c22c4bfbf3d5 done
#9 naming to docker.io/library/sentry-self-hosted-local done
#9 DONE 0.0s
#0 building with "default" instance using docker driver

#1 [subscription-consumer-events internal] load build definition from Dockerfile
#1 transferring dockerfile: 522B done
#1 DONE 0.0s

#2 [subscription-consumer-events internal] load metadata for docker.io/getsentry/sentry:23.6.2
#2 DONE 0.0s

#3 [subscription-consumer-events internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [subscription-consumer-events 1/4] FROM docker.io/getsentry/sentry:23.6.2
#4 DONE 0.0s

#5 [subscription-consumer-events internal] load build context
#5 transferring context: 769B done
#5 DONE 0.0s

#6 [subscription-consumer-events 3/4] RUN if [ -s /usr/src/sentry/enhance-image.sh ]; then     /usr/src/sentry/enhance-image.sh; fi
#6 CACHED

#7 [subscription-consumer-events 2/4] COPY . /usr/src/sentry
#7 CACHED

#8 [subscription-consumer-events 4/4] RUN if [ -s /usr/src/sentry/requirements.txt ]; then     echo "sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image";     pip install -r /usr/src/sentry/requirements.txt; fi
#8 CACHED

#9 [subscription-consumer-events] exporting to image
#9 exporting layers done
#9 writing image sha256:cbd5238b731c4499e8008bea6dbdd473272f06252339d4caf5b9790d7687b254 done
#9 naming to docker.io/library/sentry-self-hosted-local done
#9 DONE 0.0s
#0 building with "default" instance using docker driver

#1 [cron internal] load build definition from Dockerfile
#1 transferring dockerfile: 522B done
#1 DONE 0.0s

#2 [cron internal] load metadata for docker.io/getsentry/sentry:23.6.2
#2 DONE 0.0s

#3 [cron internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [cron 1/4] FROM docker.io/getsentry/sentry:23.6.2
#4 DONE 0.0s

#5 [cron internal] load build context
#5 transferring context: 769B done
#5 DONE 0.0s

#6 [cron 2/4] COPY . /usr/src/sentry
#6 CACHED

#7 [cron 3/4] RUN if [ -s /usr/src/sentry/enhance-image.sh ]; then     /usr/src/sentry/enhance-image.sh; fi
#7 CACHED

#8 [cron 4/4] RUN if [ -s /usr/src/sentry/requirements.txt ]; then     echo "sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://github.com/getsentry/self-hosted#enhance-sentry-image";     pip install -r /usr/src/sentry/requirements.txt; fi
#8 CACHED

#9 [cron] exporting to image
#9 exporting layers done
#9 writing image sha256:cbe0111d9f608fff61524efb9d1c0c6042160b039188adfd9934481450c48c8b done
#9 naming to docker.io/library/sentry-self-hosted-local done
#9 DONE 0.0s
#0 building with "default" instance using docker driver

#1 [sentry-cleanup internal] load build definition from Dockerfile
#1 transferring dockerfile: 528B done
#1 DONE 0.0s

#2 [sentry-cleanup internal] load metadata for docker.io/library/sentry-self-hosted-local:latest
#2 DONE 0.0s

#3 [sentry-cleanup internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [sentry-cleanup internal] load build context
#4 transferring context: 717B done
#4 DONE 0.0s

#5 [sentry-cleanup 1/5] FROM docker.io/library/sentry-self-hosted-local:latest
#5 DONE 0.0s

#6 [sentry-cleanup 2/5] RUN if [ -z "${http_proxy}" ]; then echo "Acquire::http::proxy "${http_proxy}";" >> /etc/apt/apt.conf; fi
#6 DONE 0.2s

#7 [sentry-cleanup 3/5] RUN if [ -z "${https_proxy}" ]; then echo "Acquire::https::proxy "${https_proxy}";" >> /etc/apt/apt.conf; fi
#7 DONE 0.3s

#8 [sentry-cleanup 4/5] RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
#8 0.347 Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
#8 0.463 Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
#8 0.506 Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
#8 0.551 Get:4 http://deb.debian.org/debian bullseye/main amd64 Packages [8067 kB]
#8 0.841 Get:5 http://deb.debian.org/debian-security bullseye-security/main amd64 Packages [280 kB]
#8 0.843 Get:6 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [18.8 kB]
#8 1.716 Fetched 8574 kB in 1s (5787 kB/s)
#8 1.716 Reading package lists...
#8 2.136 Reading package lists...
#8 2.553 Building dependency tree...
#8 2.659 Reading state information...
#8 2.758 The following additional packages will be installed:
#8 2.758   sensible-utils
#8 2.758 Suggested packages:
#8 2.758   anacron logrotate checksecurity
#8 2.758 Recommended packages:
#8 2.758   default-mta | mail-transport-agent
#8 2.789 The following NEW packages will be installed:
#8 2.789   cron sensible-utils
#8 2.881 0 upgraded, 2 newly installed, 0 to remove and 28 not upgraded.
#8 2.881 Need to get 114 kB of archives.
#8 2.881 After this operation, 314 kB of additional disk space will be used.
#8 2.881 Get:1 http://deb.debian.org/debian bullseye/main amd64 sensible-utils all 0.0.14 [14.8 kB]
#8 2.924 Get:2 http://deb.debian.org/debian bullseye/main amd64 cron amd64 3.0pl1-137 [99.6 kB]
#8 3.060 debconf: delaying package configuration, since apt-utils is not installed
#8 3.082 Fetched 114 kB in 0s (613 kB/s)
#8 3.098 Selecting previously unselected package sensible-utils.
(Reading database ... 7034 files and directories currently installed.)
#8 3.098 Preparing to unpack .../sensible-utils_0.0.14_all.deb ...
#8 3.099 Unpacking sensible-utils (0.0.14) ...
#8 3.129 Selecting previously unselected package cron.
#8 3.129 Preparing to unpack .../cron_3.0pl1-137_amd64.deb ...
#8 3.130 Unpacking cron (3.0pl1-137) ...
#8 3.154 Setting up sensible-utils (0.0.14) ...
#8 3.158 Setting up cron (3.0pl1-137) ...
#8 3.196 Adding group `crontab' (GID 101) ...
#8 3.207 Done.
#8 3.222 invoke-rc.d: could not determine current runlevel
#8 3.225 invoke-rc.d: policy-rc.d denied execution of start.
#8 DONE 3.4s

#9 [sentry-cleanup 5/5] COPY entrypoint.sh /entrypoint.sh
#9 DONE 0.0s

#10 [sentry-cleanup] exporting to image
#10 exporting layers 0.0s done
#10 writing image sha256:01bc8c6df468716fd6229add8f771ced7afc6fae631c64e24f9f04c45478ed36 done
#10 naming to docker.io/library/sentry-cleanup-self-hosted-local done
#10 DONE 0.0s

Docker images built.

▶ Downloading and installing wal2json ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  101k  100  101k    0     0   116k      0 --:--:-- --:--:-- --:--:--  193k

▶ Bootstrapping and migrating Snuba ...
 Network sentry-self-hosted_default  Creating
 Network sentry-self-hosted_default  Created
 Container sentry-self-hosted-zookeeper-1  Creating
 Container sentry-self-hosted-clickhouse-1  Creating
 Container sentry-self-hosted-redis-1  Creating
Error response from daemon: failed to populate volume: error evaluating symlinks from mount source "/var/lib/docker/volumes/sentry-self-hosted_sentry-secrets/_data": lstat /var/lib/docker/volumes/sentry-self-hosted_sentry-secrets: no such file or directory
Error in install/bootstrap-snuba.sh:3.
'$dcr snuba-api bootstrap --no-migrate --force' exited with status 1
-> ./install.sh:main:31
--> install/bootstrap-snuba.sh:source:3
`

Thanking for help!

**Comment by asottile-sentry** [comment]
sounds like you edited the volumes and broke at least the `sentry-secrets` one: https://github.com/getsentry/self-hosted/blob/0b11564e3652607baab6ec614f777517057ddfee/docker-compose.yml#L162

**Comment by AlexFisher94** [comment]
Thanks for help, i really mistaken with volumes.
