### ISSUE TITLE
Unexpected behaviour of retention policy of Debug files (ProGuard Mappings)

### ISSUE THREAD

**Issue by saksforever** [getsentry/self-hosted#3237]
### Self-Hosted Version

24.5.1

### CPU Architecture

x86_64

### Docker Version

23.0.4

### Docker Compose Version

2.27.0

### Steps to Reproduce

1. Upload ProGuard map via Gradle 
2. Events are correctly using this map every day
3. Wait for SENTRY_EVENT_RETENTION_DAYS to pass
4. Cleanup will delete Debug files 
docker logs sentry-self-hosted-sentry-cleanup-1
```shell
...
Removing ProjectDebugFile for days=21 project=xxx
...
``` 

4. Now events can not load this mapping

### Expected Result

I found this article - https://docs.sentry.io/platforms/android/data-management/debug-files/#retention-policy
Is it working only on cloud version?
Is there a way to get it on self-hosted version? Like removing it only if there are no new events with this ProGuard map for SENTRY_EVENT_RETENTION_DAYS? 
Or maybe extend/disable the retention period for debug files only?

### Actual Result

Before 24.5.1 we used old 22.11.0 - Debug mappings were not automatically removed there

Our releases live more than our SENTRY_EVENT_RETENTION_DAYS, so now we have to manually upload removed maps for broken releases via sentry-cli

![Image](https://github.com/user-attachments/assets/6f87aba3-19b8-4e6e-bce8-4b5641e81913)

**Comment by asottile-sentry** [comment]
this code paths described in this article apply equally to self-hosted: https://docs.sentry.io/platforms/android/data-management/debug-files/#retention-policy

the retention date is refreshed when the debug files are accessed -- if they're not accessed within the retention period they are deleted
