### ISSUE TITLE
Error   /settings/projects/internal/metrics/c%3Acustom%2Fddm.add_custom_metric%40none

### ISSUE THREAD

**Issue by xuweixi10** [getsentry/self-hosted#3243]
### Self-Hosted Version

24.7.1

### CPU Architecture

x86_64

### Docker Version

27.0.3

### Docker Compose Version

2.28.1

### Steps to Reproduce

1. go to project setting
2. click mertrics
3. click mertic name

### Expected Result

maybe should see mertics details?

### Actual Result

show error page

![Image](https://github.com/user-attachments/assets/8872ba8a-830e-48a7-8acb-78629d084c0c)

### Event ID

ac9ad2ec00a04379b61aef681e0883b2

**Comment by hubertdeng123** [comment]
Metrics is not yet enabled for self-hosted Sentry. This issue tracks that effort:
https://github.com/getsentry/self-hosted/issues/3167
