### ISSUE TITLE
Sentry and GitLab installed and running together will cause the CPU to occupy 100%

### ISSUE THREAD

**Issue by youxia-mrhan** [getsentry/self-hosted#3244]
### Body

Sentry conflicts with GitLab. Although they can be installed together and started and run normally, Sentry will occupy 100% CPU in about 10 minutes.

The version currently used is self-hosted-24.7.0, and Gitlab is the latest version.

System CentOS Stream 8, x86_64.

**Comment by hubertdeng123** [comment]
This doesn't appear to be a specific issue to Sentry. How much CPU are you using?

**Comment by youxia-mrhan** [comment]
CPU 8 cores, memory 16 GB. If you only install GitLab or Sentry, the CPU will only occupy about 10%. If the two applications are on the same machine, the top command will show that Sentry will occupy 100% of the CPU, causing the server to crash.

**Comment by youxia-mrhan** [comment]
I tried other applications and Sentry coexisting on the same server, and everything worked fine. However, until I met GitLab

**Comment by hubertdeng123** [comment]
Are you installing the gitlab integration or self hosted version of gitlab? You may need to allocate more resources if it is the latter.

**Comment by youxia-mrhan** [comment]
I tried both GitLab source code installation and Docker installation.

**Comment by hubertdeng123** [comment]
If you're experiencing resource issues you may want to consider errors only self-hosted https://develop.sentry.dev/self-hosted/#errors-only-self-hosted-sentry
