### ISSUE TITLE
Github integration not working

### ISSUE THREAD

**Issue by Xdemon202** [getsentry/self-hosted#3247]
### Self-Hosted Version

24.7.1 

### CPU Architecture

x86_64

### Docker Version

27.1.1

### Docker Compose Version

2.29.1

### Steps to Reproduce

Follow the instructions to add GitHub integration from [here](https://develop.sentry.dev/integrations/github/)

I created a GitHub app for testing integration

This is the configuration part : 
```
github-app.id: xxxxxx
github-app.name: '0menD'
github-app.webhook-secret: 'Lxxxxxoxoxoxoo'
github-app.client-id: 'ohohohoh'
github-app.client-secret: 'steal_my_pas))'
github-app.private-key: |
  -----BEGIN RSA PRIVATE KEY-----
```

### Expected Result

After following the instructions, I expect the integration to be displayed on the integrations page and I will finally start using the functionality.

### Actual Result

Integration does not appear

https://github.com/user-attachments/assets/d922a4b4-b9a6-47a1-a367-146c23de5980

**Comment by hubertdeng123** [comment]
Looks like potentially an issue with the callback url. It should be redirecting you back to your self-hosted Sentry instance. Could you double check that?

**Comment by hubertdeng123** [comment]
Looks like a duplicaet of https://github.com/getsentry/self-hosted/issues/3117. Going to close this

**Comment by Xdemon202** [comment]
@hubertdeng123  could you say please what  is wrong  : 

![Image](https://github.com/user-attachments/assets/6dbca5e7-2423-4467-b965-d35b5bac1a8f)
