### ISSUE TITLE
does sentry self-hosted have autofix feature

### ISSUE THREAD

**Issue by shan-ds** [getsentry/self-hosted#3249]
### Problem Statement

i recently got to know about sentry and i have few qutestion to know about it 
is sentry self-hosted is free or does it need a license 
does it have ai autofix feature 
thank you

**Comment by DarkByteZero** [comment]
Self Hosted Sentry is free to use, you do not need a license. 

Currently, the [Main Service](https://github.com/getsentry/seer) powering AI Autofix and other Advanced AI Features is not ready for Self Hosted Sentry.  So these features won't work, but everything else like replays, Issue Tracking and the new Performance Insights work.

**Comment by hubertdeng123** [comment]
Self hosted Sentry is free to use, and the AI autofix feature is not available.

**Comment by shan-ds** [comment]
thank you
