### ISSUE TITLE
Cron API after update 24.5.0 to 24.7.1 check-in event using CURL API returns: failed to queue envelope

### ISSUE THREAD

**Issue by alesak** [getsentry/self-hosted#3250]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

I am experiencing same issue after update 24.5.0 to 24.7.1 now when I send check-in event using CURL API returns

`{"detail":"failed to queue envelope"}`

All Cron monitors are failing!

Check-in events using PHP lib are failing too.

### Expected Result

check-in event goes through and is recorder in cron monitor

### Actual Result

All Cron monitors are now failing!

### Product Area

Crons

### Version

24.7.1

**Comment by hubertdeng123** [comment]
Are there details in your web container or nginx containers that may indicate a better error message?

**Comment by alesak** [comment]
Unfortunately cannot say, no longer on 24.7.1 and need the working system so cannot provide more information.

**Comment by yaneony** [comment]
Same was on 24.7.0
https://github.com/getsentry/self-hosted/issues/3217

**Comment by hubertdeng123** [comment]
I think that error specifically is not related to crons, but relay. Are there any other logs that you're seeing that could be useful here?
