### ISSUE TITLE
relay_server::services::project_upstream

### ISSUE THREAD

**Issue by BenJChen** [getsentry/self-hosted#3251]
### Self-Hosted Version

24.7.1

### CPU Architecture

x86_64

### Docker Version

24.0.6

### Docker Compose Version

2.20.3

### Steps to Reproduce

After a large number of errors entered the sentry service, sentry crashed

### Expected Result

The relay service returns to normal, and you can see error and performance statistics.

### Actual Result

![Image](https://github.com/user-attachments/assets/e72e8df6-24c4-4aec-ac30-57becb9a872d)

Yesterday, due to a large number of errors reported by the project, sentry failed. We tried removing all Kafka-related volumes and recreating them, restarting sentry and other methods. The project can run normally, but the data cannot be written. 12 hours have passed and we still cannot see new data in sentry. The data, nginx view request is normal, but a large number of errors appear in the relay, how to solve this

**Comment by joshuarli** [comment]
Related: https://github.com/getsentry/relay/issues/3828

What do you mean by "sentry crashed"? Is the web container failing?

**Comment by BenJChen** [comment]
> Related: [getsentry/relay#3828](https://github.com/getsentry/relay/issues/3828)
> 
> What do you mean by "sentry crashed"? Is the web container failing?


The error and performance data cannot be updated for more than ten hours. The nginx view request is normal and the relay prompts relay_server::services::project_upstream.

**Comment by joshuarli** [comment]
Have you tried restarting Relay? Is it just total failure to ingest any more events?

**Comment by BenJChen** [comment]
> 您是否尝试过重新启动 Relay？是否完全无法接收更多事件？



> Have you tried restarting Relay? Is it just total failure to ingest any more events?

Restarting relay and even restarting sentry failed to solve the problem. It was not until I tried to clear all redis caches and restart sentry that relay returned to normal.

**Comment by iambriccardo** [comment]
Hi, did you experience any overload of Redis when the errors started happening?
