### ISSUE TITLE
How to upgrade to 24.7.1

### ISSUE THREAD

**Issue by mostfurious** [getsentry/self-hosted#3253]
Hello,
It looks like starting from 24.7.0, file structure has completely changed. Where are install scripts ? Where is documentation ? Where are configuration files ? In self-hosted/config.yml ?  Why is it so poorly done ? The last release that had install script, configuration files .env file was 24.6.0.

**Comment by hubertdeng123** [comment]
I also do not think you are doing something correctly. Nothing has changed in relation to the file structure.

**Comment by mostfurious** [comment]
I've always downloaded zip from github. Now i downloaded this: https://github.com/getsentry/sentry/archive/refs/tags/24.7.1.zip

Tell me how is this normal ? How is this not changed ?


![Image](https://github.com/user-attachments/assets/9c50a1f5-aa99-4383-aab9-404646d18ea4)

**Comment by mostfurious** [comment]
Version 24.6.0 this file: https://github.com/getsentry/self-hosted/archive/refs/tags/24.6.0.zip

Looks totally different:


![Image](https://github.com/user-attachments/assets/4e94cb52-e6ed-4cc8-9e4b-0e738a52e6ee)


Why is there such a mix up ?

**Comment by LordSimal** [comment]
bro, those are 2 different repositories.
one is sentry itself, the other is the self-hosted repository containng the docker config for everything else.

You are mixing up https://github.com/getsentry/self-hosted and https://github.com/getsentry/sentry

**Comment by mostfurious** [comment]
Both of them were taken from here: https://github.com/getsentry/sentry/releases
Im not mixing anything.

**Comment by LordSimal** [comment]
just download the zip from https://github.com/getsentry/self-hosted and you are fine

**Comment by mostfurious** [comment]
Thanks. But it still weird that they are being mixed up like that
