### ISSUE TITLE
Kafka ingest-replay-events makes disk full, retention variables didn't work

### ISSUE THREAD

**Issue by mertcb** [getsentry/self-hosted#3258]
### Self-Hosted Version

23.12.1

### CPU Architecture

x86_64di

### Docker Version

26.1.3

### Docker Compose Version

2.27.0

### Steps to Reproduce

1. Add following values to .env file

KAFKA_LOG_RETENTION_HOURS=168
KAFKA_LOG_RETENTION_BYTES=26843545600
KAFKA_LOG_SEGMENT_BYTES=1073741824
KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS=300000
KAFKA_LOG_SEGMENT_DELETE_DELAY_MS=60000

2. Make a full install with ./install.sh
3. Let users use Sentry

Followed that sentry QA, https://forum.sentry.io/t/sentry-disk-cleanup-kafka/11337/2?u=byk

### Expected Result

Every logs in 'ingest-replay-events-0' topic should be deleted after 25GB disk usage.

### Actual Result

Logs are not deleted and disk is getting full.

**Comment by joshuarli** [comment]
KAFKA_LOG_RETENTION_BYTES=26843545600 isn't doing what you expect. See [here](https://stackoverflow.com/questions/52970153/kafka-how-to-avoid-running-out-of-disk-storage). You're misconfiguring kafka for what you want. 

Not a Sentry issue; closing.
