### ISSUE TITLE
Container sentry-self-hosted-web-1 is unhealthy

### ISSUE THREAD

**Issue by HarshHingu** [getsentry/self-hosted#3259]
### Self-Hosted Version

24.7.1

### CPU Architecture

x64-based processor

### Docker Version

24.0.7

### Docker Compose Version

2.19.0

### Steps to Reproduce

I am using windows Laptop and within that I have wsl 2 and in wsl I run sudo docker-compose up -d after sudo ./install.sh. Then I get error of Container sentry-self-hosted-web-1 is unhealthy. Sometimes it's kafka which is unhealthy. I tried sudo docker-compose down and again sudo docker-compose up -d still got same error.

![Image](https://github.com/user-attachments/assets/186f5399-e892-4f1f-9df4-38d91b750614)

![Image](https://github.com/user-attachments/assets/88935bdd-15c0-4795-b883-5c1a38375bcb)

![Image](https://github.com/user-attachments/assets/ad6b8873-45b5-47df-9072-6d0eef2bcee6)

### Expected Result

Where the sentry self-hosted starts working and no container is unhealthy

### Actual Result

Below is log of command sudo docker-compose logs web
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
*** Starting uWSGI 2.0.23 (64bit) on [Mon Aug 12 07:54:26 2024] ***

--- Python VM already initialized ---
Python main interpreter initialized at 0x7f5fffecf218
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
setting request body buffering size to 65536 bytes
mapped 1924224 bytes (1879 KB) for 12 cores
*** Operational MODE: preforking+threaded ***
spawned uWSGI master process (pid: 739)
spawned uWSGI worker 1 (pid: 759, cores: 4)
spawned uWSGI worker 2 (pid: 760, cores: 4)
spawned uWSGI worker 3 (pid: 761, cores: 4)
spawned uWSGI http 1 (pid: 762)
WSGI app 0 (mountpoint='') ready in 460 seconds on interpreter 0x7f5fffecf218 pid: 759 (default app)
WSGI app 0 (mountpoint='') ready in 475 seconds on interpreter 0x7f5fffecf218 pid: 760 (default app)
WSGI app 0 (mountpoint='') ready in 475 seconds on interpreter 0x7f5fffecf218 pid: 761 (default app)
DAMN ! worker 2 (pid: 760) died, killed by signal 9 :( trying respawn ...
Respawned uWSGI worker 2 (new pid: 819)

**Comment by joshuarli** [comment]
> Sometimes it's kafka which is unhealthy. 

I also see snuba restarting. Can you post more logs? This is pretty limited info, maybe you're running low on memory?

**Comment by HarshHingu** [comment]
docker logs of web-1 container, 


![Image](https://github.com/user-attachments/assets/77ad4033-df24-4519-9f81-5d53f533fbcb)

You can see the docker stats of web-1 container, What more logs you want to see?

![Image](https://github.com/user-attachments/assets/38721e93-40dc-4f0d-a920-4d109dc222eb)
![Image](https://github.com/user-attachments/assets/6c38c9ed-10cd-493c-9ed9-7c8fcecd7294)

docker Inspect web-1


[
    {
        "Id": "205a2d924b3938a3e1624729a9ae6e5f4375974e6decec50ccf433542095acb4",
        "Created": "2024-08-16T10:28:40.108791645Z",
        "Path": "/etc/sentry/entrypoint.sh",
        "Args": [
            "run",
            "web"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 40301,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2024-08-16T10:29:38.191470466Z",
            "FinishedAt": "0001-01-01T00:00:00Z",
            "Health": {
                "Status": "unhealthy",
                "FailingStreak": 19,
                "Log": [
                    {
                        "Start": "2024-08-16T16:21:20.331564067+05:30",
                        "End": "2024-08-16T16:21:59.519937373+05:30",
                        "ExitCode": 1,
                        "Output": ""
                    },
                    {
                        "Start": "2024-08-16T16:22:31.873279152+05:30",
                        "End": "2024-08-16T16:23:45.927186865+05:30",
                        "ExitCode": 1,
                        "Output": ""
                    },
                    {
                        "Start": "2024-08-16T16:24:20.191421142+05:30",
                        "End": "2024-08-16T16:25:15.360519873+05:30",
                        "ExitCode": 1,
                        "Output": ""
                    },
                    {
                        "Start": "2024-08-16T16:25:45.544173695+05:30",
                        "End": "2024-08-16T16:26:57.497885281+05:30",
                        "ExitCode": 1,
                        "Output": ""
                    },
                    {
                        "Start": "2024-08-16T16:27:27.576731016+05:30",
                        "End": "2024-08-16T16:28:22.745403095+05:30",
                        "ExitCode": -1,
                        "Output": "timed out starting health check for container 205a2d924b3938a3e1624729a9ae6e5f4375974e6decec50ccf433542095acb4"
                    }
                ]
            }
        },
        "Image": "sha256:15d3e48802738b4c59e8b612bbe9d7afe489a0a6c0d619cf04f6ab026617d85b",
        "ResolvConfPath": "/var/lib/docker/containers/205a2d924b3938a3e1624729a9ae6e5f4375974e6decec50ccf433542095acb4/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/205a2d924b3938a3e1624729a9ae6e5f4375974e6decec50ccf433542095acb4/hostname",
        "HostsPath": "/var/lib/docker/containers/205a2d924b3938a3e1624729a9ae6e5f4375974e6decec50ccf433542095acb4/hosts",
        "LogPath": "/var/lib/docker/containers/205a2d924b3938a3e1624729a9ae6e5f4375974e6decec50ccf433542095acb4/205a2d924b3938a3e1624729a9ae6e5f4375974e6decec50ccf433542095acb4-json.log",
        "Name": "/sentry-self-hosted-web-1",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/mnt/c/Users/Harsh Hingu/Documents/my sentry/self-hosted/sentry:/etc/sentry:rw",
                "/mnt/c/Users/Harsh Hingu/Documents/my sentry/self-hosted/geoip:/geoip:ro",
                "/mnt/c/Users/Harsh Hingu/Documents/my sentry/self-hosted/certificates:/usr/local/share/ca-certificates:ro"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "sentry-self-hosted_default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "ConsoleSize": [
                0,
                0
            ],
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "host",
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": [],
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": [
                {
                    "Name": "nofile",
                    "Hard": 4096,
                    "Soft": 4096
                }
            ],
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "Mounts": [
                {
                    "Type": "volume",
                    "Source": "sentry-data",
                    "Target": "/data",
                    "VolumeOptions": {}
                }
            ],
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware",
                "/sys/devices/virtual/powercap"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/201a0e980c9340d1fb37cd7140adb84692924082de7d16aa4c2778f2f5b40cb4-init/diff:/var/lib/docker/overlay2/vnbnqnxcjxlp02efo75sy28ad/diff:/var/lib/docker/overlay2/msvvjf9379e53n7nnor95fb4o/diff:/var/lib/docker/overlay2/st3hxit2x6p3hy8vmf7y71qoo/diff:/var/lib/docker/overlay2/8b1dc52b307366b527abc2b06d5aa43a80285df86fd63ef6fda92b121ba89bb0/diff:/var/lib/docker/overlay2/8b4d0769e4813c5ca71dfaac1fddae24cd9ad3edf94c40c11108a3120d54315b/diff:/var/lib/docker/overlay2/91dcb5b45175662216e381e5832443a3a2c80b515b58a360051e261bd5606884/diff:/var/lib/docker/overlay2/68626b834f657803c49cf5bf353528bb7b98c41590b747dad8443985ca615fd3/diff:/var/lib/docker/overlay2/51c6341b91ae8864f39030de548c49beb8543e5959d8b7425dd99c04c97f8925/diff:/var/lib/docker/overlay2/ba319e9e86f38ef130f2d700effb10b558cff9b7539ca70e505e521850809ff8/diff:/var/lib/docker/overlay2/17519babcdc98241863791b46c8090dd248cc648225525884a9f7f3b94c2de59/diff:/var/lib/docker/overlay2/a52ae2a7efa65f1f91b5fca70130a2719278079e5482c9bac6bd8fa8e54d72a0/diff:/var/lib/docker/overlay2/cd63fe78d52f149222cde56594d47bdef12042d885d4fd2f93db3c122d2d15b6/diff:/var/lib/docker/overlay2/ee1c03ec82eb682576799b0153ea792992b9e57b0c0a2ee66fd142c1182a9b46/diff:/var/lib/docker/overlay2/50f2e36bfa8bbfb4b3bf3964a6a022ae203b8805703fdd2618eddfb612c195bb/diff:/var/lib/docker/overlay2/1f7ebe4a6c6b5c47131f0d9079b850de80b26a1dcbe7b772b97d54b415a23e6f/diff:/var/lib/docker/overlay2/32ea4bcba80a6a34d888f282110e596e31062bfe6b768f719a09d84aab2eff79/diff:/var/lib/docker/overlay2/18388cf144ba4b0d4fc1c06bbad87cbdf558da3e20742b268602f050fcbea92a/diff:/var/lib/docker/overlay2/0b372c4c4f306e496320ba4c25067638697bc9f2c2d9472428afb87fc80e71f8/diff:/var/lib/docker/overlay2/67ffc8e1acc68b92883459164caccfcd00d907da1334cfd9dfad52dfe4721bd6/diff:/var/lib/docker/overlay2/9fdbbb56bb1aaf0ce6ac676be154f4bea0ab56caba7180e0f6f9011bcf11e915/diff",
                "MergedDir": "/var/lib/docker/overlay2/201a0e980c9340d1fb37cd7140adb84692924082de7d16aa4c2778f2f5b40cb4/merged",
                "UpperDir": "/var/lib/docker/overlay2/201a0e980c9340d1fb37cd7140adb84692924082de7d16aa4c2778f2f5b40cb4/diff",
                "WorkDir": "/var/lib/docker/overlay2/201a0e980c9340d1fb37cd7140adb84692924082de7d16aa4c2778f2f5b40cb4/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/mnt/c/Users/Harsh Hingu/Documents/my sentry/self-hosted/sentry",
                "Destination": "/etc/sentry",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/mnt/c/Users/Harsh Hingu/Documents/my sentry/self-hosted/geoip",
                "Destination": "/geoip",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/mnt/c/Users/Harsh Hingu/Documents/my sentry/self-hosted/certificates",
                "Destination": "/usr/local/share/ca-certificates",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "volume",
                "Name": "sentry-data",
                "Source": "/var/lib/docker/volumes/sentry-data/_data",
                "Destination": "/data",
                "Driver": "local",
                "Mode": "z",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "205a2d924b39",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "9000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "SENTRY_MAIL_HOST",
                "REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt",
                "SENTRY_EVENT_RETENTION_DAYS=90",
                "OPENAI_API_KEY",
                "DEFAULT_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt",
                "SENTRY_CONF=/etc/sentry",
                "VROOM=http://vroom:8085",
                "SENTRY_MAX_EXTERNAL_SOURCEMAP_SIZE",
                "GRPC_DEFAULT_SSL_ROOTS_FILE_PATH_ENV_VAR=/etc/ssl/certs/ca-certificates.crt",
                "COMPOSE_PROFILES=feature-complete",
                "PYTHONUSERBASE=/data/custom-packages",
                "SNUBA=http://snuba-api:1218",
                "PATH=/.venv/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "GPG_KEY=A035C8C19219BA821ECEA86B64E628F8D684696D",
                "PYTHON_VERSION=3.11.8",
                "PYTHON_PIP_VERSION=24.0",
                "PYTHON_SETUPTOOLS_VERSION=65.5.1",
                "PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/dbf0c85f76fb6e1ab42aa672ffca6f0a675d9ee4/public/get-pip.py",
                "PYTHON_GET_PIP_SHA256=dfe9fd5c28dc98b5ac17979a953ea550cec37ae1b47a5116007395bfacff2ab9",
                "PIP_NO_CACHE_DIR=1",
                "PIP_DISABLE_PIP_VERSION_CHECK=1",
                "UWSGI_NEED_PLUGIN=/var/lib/uwsgi/dogstatsd",
                "GRPC_POLL_STRATEGY=epoll1",
                "SENTRY_BUILD=a85dd406e127a3a11625e5b335ca58c46799dee7"
            ],
            "Cmd": [
                "run",
                "web"
            ],
            "Healthcheck": {
                "Test": [
                    "CMD",
                    "/bin/bash",
                    "-c",
                    "exec 3<>/dev/tcp/127.0.0.1/9000 && echo -e \"GET /_health/ HTTP/1.1\\r\\nhost: 127.0.0.1\\r\\n\\r\\n\" >&3 && grep ok -s -m 1 <&3"
                ],
                "Interval": 30000000000,
                "Timeout": 90000000000,
                "StartPeriod": 10000000000,
                "Retries": 10
            },
            "Image": "sentry-self-hosted-local",
            "Volumes": {
                "/data": {}
            },
            "WorkingDir": "/usr/src/sentry",
            "Entrypoint": [
                "/etc/sentry/entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "045c8d3945b654d5bdc9c9e63e03252212ba9908f7b55806cae624b4a54bac22",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.depends_on": "postgres:service_healthy:false,memcached:service_started:false,smtp:service_started:false,snuba-api:service_started:false,symbolicator:service_started:false,redis:service_healthy:false,kafka:service_healthy:false",
                "com.docker.compose.image": "sha256:15d3e48802738b4c59e8b612bbe9d7afe489a0a6c0d619cf04f6ab026617d85b",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "sentry-self-hosted",
                "com.docker.compose.project.config_files": "/mnt/c/Users/Harsh Hingu/Documents/my sentry/self-hosted/docker-compose.yml",
                "com.docker.compose.project.working_dir": "/mnt/c/Users/Harsh Hingu/Documents/my sentry/self-hosted",
                "com.docker.compose.service": "web",
                "com.docker.compose.version": "2.19.0",
                "maintainer": "oss@sentry.io",
                "org.opencontainers.image.authors": "oss@sentry.io",
                "org.opencontainers.image.description": "Sentry runtime image",
                "org.opencontainers.image.documentation": "https://develop.sentry.dev/self-hosted/",
                "org.opencontainers.image.licenses": "https://github.com/getsentry/sentry/blob/a85dd406e127a3a11625e5b335ca58c46799dee7/LICENSE",
                "org.opencontainers.image.revision": "a85dd406e127a3a11625e5b335ca58c46799dee7",
                "org.opencontainers.image.source": "https://github.com/getsentry/sentry/tree/a85dd406e127a3a11625e5b335ca58c46799dee7/",
                "org.opencontainers.image.title": "Sentry",
                "org.opencontainers.image.url": "https://sentry.io/",
                "org.opencontainers.image.vendor": "Functional Software, Inc."
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "1c5111e3f8b8acf870d077fe06534515abc48927ef2bd393a8f7b897d034f822",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "9000/tcp": null
            },
            "SandboxKey": "/var/run/docker/netns/1c5111e3f8b8",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "sentry-self-hosted_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "sentry-self-hosted-web-1",
                        "web",
                        "205a2d924b39"
                    ],
                    "NetworkID": "6e50929fe1be6e9b4f6daa34bf05395c4acf52ef132a1be1e57062c25013c2d9",
                    "EndpointID": "27434d64a39436585428531d29de1ff8b21bd242a4ad5abf1041b3d2fc6347ec",
                    "Gateway": "172.18.0.1",
                    "IPAddress": "172.18.0.38",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:12:00:26",
                    "DriverOpts": null
                }
            }
        }
    }
]

**Comment by joshuarli** [comment]
Can you please post logs of other containers (snuba, kafka as you said) that are crashing, and also total memory usage (just open task manager and show me the graph).

We need to see if it's an application error or out of memory error. It's most likely out of memory. You only showed me what sentry web is doing. That 300 mib / 6.68 gib memory usage means very little because I can't see what else is using memory.

**Comment by HarshHingu** [comment]
Will check by tomorrow again and share screenshot of other logs like Kafka,etc.

Currently this is screenshot of my task manager

![Image](https://github.com/user-attachments/assets/4270f9f5-0f22-452b-8fff-812611032154)

**Comment by Barsoomx** [comment]
check connection params to memcached/redis. i had the same problem where memcached was unreachable(wrong ipaddr) but every request silently timed out waiting for cache (because i moved infrastructure to a separate machine)

**Comment by barisyild** [comment]
Sentry was running incredibly slow and then I turned sentry off and on and started getting this error.
There was no such problem before the update.
