### ISSUE TITLE
build.version is unknown

### ISSUE THREAD

**Issue by souredoutlook** [getsentry/self-hosted#3261]
### Self-Hosted Version

24.7.1 unknwon

### CPU Architecture

unknown

### Docker Version

unknown

### Docker Compose Version

unknown

### Steps to Reproduce

Reported on Twitter here: https://x.com/anny_goerl/status/1822911040281362748

### Expected Result

Build identifier is not unknown

### Actual Result

Build identifier is unknown

**Comment by aldy505** [comment]
Not an actual issue that's messing up with anything. Also duplicate of https://github.com/getsentry/self-hosted/issues/3165, https://github.com/getsentry/self-hosted/issues/2925

**Comment by joshuarli** [comment]
https://github.com/getsentry/sentry/pull/76139  This should reduce the confusion!
