### ISSUE TITLE
How to handle session replays (lenght, sum storage)

### ISSUE THREAD

**Issue by klemen-df** [getsentry/self-hosted#3265]
### Self-Hosted Version

23.12.0

### CPU Architecture

x86_64

### Docker Version

23.12.0

### Docker Compose Version

2.29.1

### Steps to Reproduce

1. Use session replay
2. Very long (for various reasons - not a Sentry issue) are recorded
3. disk is full

### Expected Result

I don't know. Can I somehow:
- limit recording length
- limit max size (individual or all together) one replay size?

### Actual Result

1. Use session replay
2. Very long (for various reasons - not a Sentry issue) are recorded
3. disk is full

**Comment by joshuarli** [comment]
This isn't a self-hosted issue. I encourage you to post here: https://github.com/getsentry/sentry/discussions/categories/problem-understanding

That said you can try out the following:
- https://docs.sentry.io/product/explore/session-replay/web/replay-details/#retention
- And depending on your SDK, you can call something like replay.stop after your desired max recording length.
