### ISSUE TITLE
Self Hosted Replay: Loading replay detail results in 404

### ISSUE THREAD

**Issue by singhdimple** [getsentry/self-hosted#3274]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### What are you trying to accomplish?

Hi Team,

I am running selfhosted sentry(24.2.0) and want to use session replay feature

### How are you getting stuck?

Hi Team,

All the other features are working fine in my setup but session replay feature is not working and showing the below mentioned error 
I am able to see session replay data in kafka topics as well in clickhouse database but still on UI I'm getting this error.

Please help me out I have been troubleshooting it for a very long time but didn't find any solution.

![Image](https://github.com/user-attachments/assets/f86989c8-88f5-40d2-9705-c154c0dca782)

### Where in the product are you?

Replays

### Version

24.2.0

**Comment by bruno-garcia** [comment]
Also note some related closed tickets that might help her:
* https://github.com/getsentry/self-hosted/issues/3098
* https://github.com/getsentry/self-hosted/issues/2817
* https://github.com/getsentry/self-hosted/issues/2839

**Comment by joshuarli** [comment]
dupe: https://github.com/getsentry/self-hosted/issues/2846

Someone in that thread was able to get it working on 24.5.0, try upgrading to at least that version first. If you still encounter issues please post again on that issue and we can look into it further.

**Comment by singhdimple** [comment]
session replay was not visible on UI because in my web container /data/files was empty and I can see ingest-replay-recording container was having some data in /data/files 

it is due to not having shared volume among the containers.
