### ISSUE TITLE
Problem with using MS teams webhook

### ISSUE THREAD

**Issue by hostinqer** [getsentry/self-hosted#3277]
### Self-Hosted Version

24.2.0

### CPU Architecture

x86_64

### Docker Version

24.0.7

### Docker Compose Version

v2.18.1

### Steps to Reproduce

1. Login then go to **Settings** > **Integrations** > **WebHooks**  > **Add to Project** > _Select project from project list_  
2. Add Callback URLs: https://eample.webhook.office.com/webhookb2/@/IncomingWebhook/ (**_ADD FULL LINK_** )
3. Enable Plugin and Save Changes
4. use button  **Test plugin**  
5. And get error :

```
Test Results
"There was an internal error with the Plugin, Summary or Text is required."
```

### Expected Result

I would to Get ok :)

### Actual Result

**_`I REMOVE REAL WEBHOOK LINK FROM LOGS`_**

Test Results
`"There was an internal error with the Plugin, Summary or Text is required."`

![Image](https://github.com/user-attachments/assets/38ae04e5-7943-4a47-abe3-fff15f693231)

docker logs -f sentry-self-hosted-web-1
19:30:57 [INFO] sentry.plugins.client: plugin.http_response (url='https://example.webhook.office.com/webhookb2//IncomingWebhook/' plugin='webhook' status_string='400' error='400 Client Error: Bad Request for url: https://.webhook.office.com/webhookb2/@/IncomingWebhook//')
19:30:57 [INFO] sentry.plugins.webhooks: notification-plugin.notify-failed (error='Summary or Text is required.' plugin='webhooks' project_id=17 organization_id=1)
19:30:57 [INFO] sentry.access.api: api.access (method='POST' view='sentry.api.endpoints.project_plugin_details.ProjectPluginDetailsEndpoint' response=200 user_id='1' is_app='False' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/projects/sentry/email-service/plugins/webhooks/' caller_ip='172.19.0.1' user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.8808977603912354 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
[deadlock-detector] a process holding a robust mutex died. recovering...
19:30:57 [INFO] sentry.plugins.client: plugin.http_response (url='https://.webhook.office.com/webhookb2//IncomingWebhook/' plugin='webhook' status_string='400' error='400 Client Error: Bad Request for url: https://.webhook.office.com/webhookb2/-bfdf-/IncomingWebhook/')
19:30:57 [INFO] sentry.plugins.webhooks: notification-plugin.notify-failed (error='Summary or Text is required.' plugin='webhooks' project_id=17 organization_id=1)
19:30:57 [INFO] sentry.access.api: api.access (method='POST' view='sentry.api.endpoints.project_plugin_details.ProjectPluginDetailsEndpoint' response=200 user_id='1' is_app='False' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/projects/sentry/email-service/plugins/webhooks/' caller_ip='172.19.0.1' user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.3326714038848877 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
...The work of process 48382 is done. Seeya!
worker 1 killed successfully (pid: 48382)
Respawned uWSGI worker 1 (new pid: 48441)
19:30:57 [INFO] sentry.access.api: api.access (method='POST' view='sentry.api.endpoints.relay.project_configs.RelayProjectConfigsEndpoint' response=200 user_id='None' is_app='None' token_type='None' is_frontend_request='False' organization_id='None' auth_id='None' path='/api/0/relays/projectconfigs/' caller_ip='172.19.0.43' user_agent='None' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.012159347534179688 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
/usr/local/lib/python3.11/site-packages/sentry/../urllib3/connectionpool.py:1100: InsecureRequestWarning: Unverified HTTPS request is being made to host .webhook.office.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings

**Comment by joshuarli** [comment]
This isn't a self-hosted issue.

That said, i'm not sure what you're trying to do. I would avoid using any legacy integrations. Make sure you've set up Microsoft Teams correctly: https://docs.sentry.io/organization/integrations/notification-incidents/msteams/#install

**Comment by hostinqer** [comment]
@joshuarli  There’s nothing to configure in Microsoft Teams, I just created a webhook link there. Then I tried to use it in Sentry. I didn’t quite understand what you meant and why you consider this to be a legacy integration?
