### ISSUE TITLE
24.8.0 does not start successfuly on fresh installation

### ISSUE THREAD

**Issue by evolvoltd** [getsentry/self-hosted#3282]
### Self-Hosted Version

24.8.0

### CPU Architecture

x86_64

### Docker Version

27.1.2

### Docker Compose Version

2.29.1

### Steps to Reproduce

Sentry self hosted is installed on fresh Ubuntu 20.04.6 LTS using user 'sentry' who has sudo rights
1. sudo ./install.sh
2. sudo docker compose up -d

### Expected Result

All containers starts successfully.

### Actual Result

Geoipupdate keeps refusing to start.

 ⠋ Container sentry-self-hosted-geoipupdate-1                                   Starting                                                                                                                                                                                  2.0s
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "shm" to rootfs at "/dev/shm": mount shm:/dev/shm (via /proc/self/fd/6), flags: 0xe, data: mode=1777,size=67108864: cannot allocate memory: unknown

These is enough memory on server:
free -h
              total        used        free      shared  buff/cache   available
Mem:           24Gi        10Gi        10Gi        26Mi       3.0Gi        13Gi
Swap:            0B          0B          0B

**Comment by hubertdeng123** [comment]
Is this coming from the `sentry-self-hosted-geoipupdate-1` container? That container is optional and perhaps you have configured it wrong. Did you set that up based on https://develop.sentry.dev/self-hosted/geolocation/?
