### ISSUE TITLE
Enable Caches on Self Hosted

### ISSUE THREAD

**Issue by c5racing** [getsentry/self-hosted#3284]
### Self-Hosted Version

24.8.0

### CPU Architecture

x64

### Docker Version

20.10.16

### Docker Compose Version

1.6.0

### Steps to Reproduce

Is / Will Caches be available on self hosted?  If so, what is the feature flag that needs to be enabled?

### Expected Result

Caches is available in Self Hosted

### Actual Result

When clicking Caches, it displays "You don't have access to this feature"

**Comment by Szymen** [comment]
Is showed on my setup ...
![Image](https://github.com/user-attachments/assets/f911ec06-0e80-459b-8d83-1b897035e98b)

Have you compared enabled features in sentry.conf.py in your setup vs one from repo?

**Comment by c5racing** [comment]
I thought I had them all but after your comment, I had missed an entry.  Thank you
