### ISSUE TITLE
Release 24.8.1

### ISSUE THREAD

**Issue by mhshakouri** [getsentry/self-hosted#3291]
### Body
Issue on install script, checking for minimum requirements:
```
▶ Checking minimum requirements ...
Found Docker version 27.1.2
FAIL: Expected minimum docker compose version to be 2.19.0 but found 2.3.3
```

affected by:
`~/install/check-minimum-requirements.sh:L6`

[previous 24.8.0](https://github.com/getsentry/self-hosted/issues) | ***24.8.1*** | [next 24.8.1](https://github.com/getsentry/self-hosted/issues)

- [ ] Release all components (_replace items with [publish repo issue links](https://github.com/getsentry/publish/issues)_).
  - [ ] [`relay`](https://github.com/getsentry/relay/actions/workflows/release_binary.yml)
  - [ ] [`sentry`](https://github.com/getsentry/sentry/actions/workflows/release.yml)
  - [ ] [`snuba`](https://github.com/getsentry/snuba/actions/workflows/release.yml)
  - [ ] [`symbolicator`](https://github.com/getsentry/symbolicator/actions/workflows/release.yml)
  - [ ] [`vroom`](https://github.com/getsentry/vroom/actions/workflows/release.yaml)
- [x] Release self-hosted.
  - [x] [Prepare the `self-hosted` release](https://github.com/getsentry/self-hosted/actions/workflows/release.yml) (_replace with publish issue repo link_).
  - [x] Check to make sure the new release branch in self-hosted includes the appropriate CalVer images.
  - [ ] Accept (publish) the release.
  - [ ] Edit [release notes](https://github.com/getsentry/self-hosted/releases).
- [x] Follow up.
  - [ ] [Create the next release issue](https://github.com/getsentry/self-hosted/issues/new?assignees=&labels=&projects=&template=release.yml) and link it from this one.
    - _replace with link_
  - [ ] Update the [release issue template](https://github.com/getsentry/self-hosted/blob/master/.github/ISSUE_TEMPLATE/release.yml).
  - [x] Create a PR to update relocation release tests to add the new version.
    - _replace with link_

**Comment by hubertdeng123** [comment]
What are the reasons for creating this ticket? This is something we use internally
