### ISSUE TITLE
EOL of self hosted sentry

### ISSUE THREAD

**Issue by sree-warrier** [getsentry/self-hosted#3296]
### Body

Hi Team,

Need to know if the self hosted sentry is planned to do an EOL.

**Comment by aldy505** [comment]
I don't think there are any valid End Of Life for self-hosted Sentry since we're using CalVer, and there is never a patch version released for any old version. Users are always advised to upgrade regularly to the latest release. 

Please see https://develop.sentry.dev/self-hosted/releases/
