### ISSUE TITLE
Document sourcemaps debugging modal

### ISSUE THREAD

**Issue by derN3rd** [getsentry/self-hosted#3309]
Hey there,

since `sentry-cli sourcemaps explain` is now deprecated, I wanted to ask for some help on how to debug sourcemaps issues without this command now.

Any help would be appreciated, so we can add better docs for debugging.

Thanks in advance

**Comment by hubertdeng123** [comment]
It looks like the in app modal for sourcemaps was added september of last year. That would mean that this is available for self-hosted users 23.9.0+. What version are you on?
