### ISSUE TITLE
Unable to create sample events, and unable to report events by calling SDK

### ISSUE THREAD

**Issue by RmondJone** [getsentry/self-hosted#3311]
### Self-Hosted Version

24.7.0

### CPU Architecture

x86_64

### Docker Version

26.1.4

### Docker Compose Version

2.27.1

### Steps to Reproduce

1. Create a project
2. Create a test case

### Expected Result

Events can be created and reported normally

### Actual Result

Unable to create sample events, and unable to report events by calling SDK

![Image](https://github.com/user-attachments/assets/b231269d-f69e-4f6a-bfa0-383688018e2f)

**Comment by aldy505** [comment]
We'll need more information. Can you go to the server logs by running `sudo docker compose logs --tail 1 --follow nginx`, then at the same time, send the event again?

**Comment by RmondJone** [comment]
I rolled back the sentry version to 23.11.0 with the same configuration and there is no such problem. It seems that all versions 24 have this problem.

**Comment by aldy505** [comment]
Okay, a wild guess: go upgrade to 24.8.0 directly, replace every occurrence of "rust-consumer" to "consumer" on your `docker-compose.yml` file, and run the `./install.sh` script again. Did it fix it?
