### ISSUE TITLE
Add exclude flag to sentry cleanup in order to exclude some project

### ISSUE THREAD

**Issue by jamshidi799** [getsentry/self-hosted#3313]
we want to set different retention for some of our projects. but currently `sentry cleanup` only supports `--project` flag to include some projects.

Imagine that we want higher retention(for example one year) for only one project and lower retention(one month) for the rest of the projects. how we can achieve this now?

In this situation an `--exlcude` flag would be a nice option.

**Comment by hubertdeng123** [comment]
I don't think this is something that we want to officially introduce as it doesn't seem useful. You are welcome to develop your own solution for this though.
