### ISSUE TITLE
Document differences between SaaS and self-hosted

### ISSUE THREAD

**Issue by aldy505** [getsentry/self-hosted#3314]
### Problem Statement

This get asked quite a lot and the docs don't cover this question. We should put this on the documentation.

Right now this is the closest we get, but it's not clear yet and we should bring this on the top of the page.

![Image](https://github.com/user-attachments/assets/5e191882-ba59-42b5-bb65-d7600f47867e)

**Comment by aldy505** [comment]
Since I don't have time to write the docs yet, for those asking, the answer is:

The difference only resides on a few things that are impossible to be hosted by most people and billing/payment-related stuff. So to sum things up (these are list of things that are not available on self-hosted for the reason I just mentioned):
- Pricing & billing, because why would you ever want to pay for yourself (https://docs.sentry.io/pricing/)
- Spike Protection, it tightly coupled with quota, therefore it's on the [private getsentry repo](https://develop.sentry.dev/application/sentry-vs-getsentry/) (https://docs.sentry.io/pricing/quotas/spike-protection/)
- Spend Allocation (https://docs.sentry.io/pricing/quotas/spend-allocation/)
- AI autofix and LLM stuff (https://sentry.io/lp/ai-ml-beta/), though the repository is open at https://github.com/getsentry/seer
- And other obvious stuff like Data Storage Location (https://docs.sentry.io/organization/data-storage-location/)

And.. that's just it. Everything else should be available for self-hosted, even for subdomain-based organization (the kind of URL you'll see on the SaaS like `https://your-org.sentry.example.com`)

**Comment by DarkByteZero** [comment]
@aldy505 Hey,

Do you know anything about the availability of https://docs.sentry.io/product/performance/retention-priorities/ in self-hosted? The way I understand this feature is, that you can send every event to sentry and sentry creates statistics etc. but will not track every event.

**Comment by aldy505** [comment]
> @aldy505 Hey,
> 
> Do you know anything about the availability of https://docs.sentry.io/product/performance/retention-priorities/ in self-hosted? The way I understand this feature is, that you can send every event to sentry and sentry creates statistics etc. but will not store every event.

@DarkByteZero no clue at all, at the moment.
