### ISSUE TITLE
Filestore objects retention explained

### ISSUE THREAD

**Issue by VLZZZ** [getsentry/self-hosted#3315]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### What are you trying to accomplish?

Hi team!

I need you help in clarifying the proper approach for managing filesystem size for filestore blob objects. 

### How are you getting stuck?

We're using AWS S3 as a `filestore.backend`.

Despite we're using CronJob to run `sentry cleanup --concurrency 1 --days 90` daily, S3 objects in filestore bucket are never affected (IDK if it's expected)

Did I understand it correctly that the recommended approach for cleanup self-hosted filestore is:
**Programmatically remove all objects with creation date greater or equal to the configured `SENTRY_EVENT_RETENTION_DAYS`**?

Please correct me if I'm wrong but I couldn't find any related info in Sentry docs.
The closest answer I found on `sentry cleanup` is - https://github.com/getsentry/sentry/issues/20119#issuecomment-667857857
> It does delete old files if they are unreferenced anywhere. The issue is that files like this are attached to Release objects in the database. So they maintain a reference forever since a release exists forever. If you delete releases, the attached files will also be deleted.

~~So it might be also a case I believe, but~~   
We have only ~100 releases not older than `1d` (based on the 
 `sentry-cli --url https://<sentty_url>/ releases list --org  <org>` output) as we're removing old releases. But our S3 bucket filestore is several TB already and keep growing slowly, no any sings of cleanup drops. etc.

I need to hear some advice on this.

### Where in the product are you?

Other

### Version

25.1.0

**Comment by aldy505** [comment]
> Did I understand it correctly that the recommended approach for cleanup self-hosted filestore is:
> Programmatically remove all objects with creation date greater or equal to the configured SENTRY_EVENT_RETENTION_DAYS?

Yes. The `sentry cleanup` command only works for data residing on the filesystem.

There is a documentation (waiting to be merged) regarding data on external storage: https://github.com/getsentry/sentry-docs/blob/790cba94b49ae96d737a514644798706cc8b0f80/develop-docs/self-hosted/external-storage.mdx

**Comment by VLZZZ** [comment]
@aldy505 Thanks for the feedback, we're going to enable native AWS S3 Lifecycle policies and align it with the `sentry cleanup` `--days`.  

I believe it might be beneficial to clearly reflect (or cross-link the corresponding doc if any) in [the external storage documentation](https://github.com/getsentry/sentry-docs/blob/790cba94b49ae96d737a514644798706cc8b0f80/develop-docs/self-hosted/external-storage.mdx) on how to deal with the objects retention, and the cleanup solution for a filestore need to be implemented by the user.

Because when I read the new (to be merged edition) it still impossible to understand if I should take care of the objects TTL and what's the best practice here.

But of course it's up to you.

Thanks for your support!
