### ISSUE TITLE
Sorry, the events for this issue could not be found

### ISSUE THREAD

**Issue by brunis** [getsentry/self-hosted#3316]
### Self-Hosted Version

24.7.1

### CPU Architecture

x86_64

### Docker Version

24.0.7

### Docker Compose Version

2.24.6

### Steps to Reproduce

I'm getting events that have no details. I just get a page that displays:
```
Sorry, the events for this issue could not be found.

This could be due to a handful of reasons:

    The events are still processing and are on their way
    The events have been deleted
    There is an internal systems error or active issue
```

### Expected Result

I should receive events with details

### Actual Result
Event "details":
![Image](https://github.com/user-attachments/assets/5bfe9817-1376-4ece-a59a-89168cdc9694)
![Image](https://github.com/user-attachments/assets/a2ff6eba-7572-4c1b-a309-7504f85d78a9)

Browser console output:
![Image](https://github.com/user-attachments/assets/af498536-4899-4b2a-957c-bc2f73227069)

Also, the Bad Gateway Errors that Sentry throws when trying to see those event details end up in one of our projects:
![Image](https://github.com/user-attachments/assets/a5cbfe04-2871-4095-a790-524b20cf969d)

**Comment by brunis** [comment]
I started sentry from the cmdline to find the failing output. I've attached the error logs that appear when visiting the faulty event details.[_sentry_cmdline_output.txt](https://github.com/user-attachments/files/16959272/_sentry_cmdline_output.txt)

**Comment by hubertdeng123** [comment]
Hmmm, those error logs are useful. Looks like you may have duplicate releases? By any chance, did you happen to be on 24.5.0 or 24.5.1?

**Comment by brunis** [comment]
> Hmmm, those error logs are useful. Looks like you may have duplicate releases? By any chance, did you happen to be on 24.5.0 or 24.5.1?

Yes, both it looks like.. my console history reveals:
VERSION="24.1.1"
VERSION="24.1.2"
VERSION="24.4.0"
VERSION="24.4.1"
VERSION="24.5.0"
VERSION="24.5.1"
VERSION="24.7.1"

**Comment by bijancot** [comment]
Agree with @hubertdeng123 it seems your version kinda not match. Did you try upgrade it or something?. Same issue happen  to me when try to import from 23.5.1 to 24.8.0 

Try check branch or tags that used in your sentry code 

Cheers !
Baskoro

**Comment by brunis** [comment]
> Agree with [@hubertdeng123](https://github.com/hubertdeng123) it seems your version kinda not match. Did you try upgrade it or something?. Same issue happen to me when try to import from 23.5.1 to 24.8.0
> 
> Try check branch or tags that used in your sentry code
> 
> Cheers ! Baskoro

Are you telling me that sentry failed to upgraded certain components and they're now running mixed versions? ..

I'm on 24.7.1 now ..  see my previous comment to see my upgrade path..

**Comment by bijancot** [comment]
>Well, you forgot two hard stops then, you were supposed to do 23.5.1 -> 23.6 -> 23.11 first, before going to 24.8 ..

Actually no, i know that step but just curious what happen if do it directly from old version lol 😆

**Comment by hubertdeng123** [comment]
@brunis , you may want to take a look at this issue here:
https://github.com/getsentry/self-hosted/issues/3167

This may be what you are seeing and hopefully gives you more context on how to move forwards.
