### ISSUE TITLE
My performance page data is experiencing delays. What's going on

### ISSUE THREAD

**Issue by Yanglmunix** [getsentry/self-hosted#3319]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

![Image](https://github.com/user-attachments/assets/fe650da2-1fd3-4601-a6ad-ebac99b4da25)

I want to see real-time data. If I can't see real-time data, at least reduce the delay time

### How are you getting stuck?

My performance page data is experiencing delays, and the data displayed on the page is delayed. I cannot view real-time data charts. How can I optimize it

### Where in the product are you?

Unknown

### Version

24.7.1

**Comment by hubertdeng123** [comment]
Are you sure that your Sentry instance is ingesting data properly? What does your CPU/RAM usage look like?

**Comment by Yanglmunix** [comment]
> Are you sure that your Sentry instance is ingesting data properly? What does your CPU/RAM usage look like?

Oh, I found my problem. It was my Kafka messages piling up, and I have resolved the issue. Thank you
