### ISSUE TITLE
dependency failed to start: container sentry-self-hosted-web-1 is unhealthy

### ISSUE THREAD

**Issue by barisyild** [getsentry/self-hosted#3325]
### Self-Hosted Version

24.8.0

### CPU Architecture

x86_64

### Docker Version

27.2.1

### Docker Compose Version

2.29.2

### Steps to Reproduce

idk

### Expected Result

Sentry had to work.

### Actual Result

[logs.txt](https://github.com/user-attachments/files/16982082/logs.txt)

**Comment by hubertdeng123** [comment]
Looks like your services are not connecting to kafka properly. You may want to check to make sure that is available and healthy.

**Comment by barisyild** [comment]
> Looks like your services are not connecting to kafka properly. You may want to check to make sure that is available and healthy.

I think it was because the system was running slow, when I disabled swap ram the problem was solved.
