### ISSUE TITLE
Sentry stops accepting errors

### ISSUE THREAD

**Issue by barisyild** [getsentry/self-hosted#3327]
### Self-Hosted Version

24.8.0

### CPU Architecture

x86_64

### Docker Version

27.2.1

### Docker Compose Version

2.29.2

### Steps to Reproduce

-

### Expected Result

Sentry should have accepting errors.

### Actual Result

About every 24 hours the sentry stops accepting errors.
The problem is not solved without restarting Sentry.

```
relay-1 | 2024-09-14T10:22:17.355619Z DEBUG request{method=POST uri=/api/10/envelope/ version=HTTP/1.1}: tower_http::trace::on_request: started processing request
relay-1 | 2024-09-14T10:22:17.356611Z ERROR request{method=POST uri=/api/10/envelope/ version=HTTP/1.1}: relay_server::endpoints::common: error handling request error=failed to queue envelope
relay-1 | 2024-09-14T10:22:17.356735Z DEBUG request{method=POST uri=/api/10/envelope/ version=HTTP/1.1}: tower_http::trace::on_response: finished processing request latency=1 ms status=503
relay-1 | 2024-09-14T10:22:17.356755Z DEBUG request{method=POST uri=/api/10/envelope/ version=HTTP/1.1}: tower_http::trace::on_failure: response failed classification=Status code: 503 Service Unavailable latency=1 ms
relay-1 | 2024-09-14T10:22:17.357352Z ERROR relay_server::services::health_check: Not enough memory, 16071245824 / 16372436992 (98.16% >= 95.00%)
relay-1 | 2024-09-14T10:22:17.358510Z ERROR relay_server::services::health_check: Health check probe 'system memory' failed
```

System has 16 GB ram, swap memory disabled.
I can send full logs from pm.

![Image](https://github.com/user-attachments/assets/a901fb62-b5c2-4879-9d01-d5a58c3bd9da)

**Comment by bijancot** [comment]
Hi, just take a peek at this issue, what abaout the web container? is the logs look strange?

In my case this issue happened once and never happen again, but the web seems  not having enough sockets to open end up custom some config in web container and the redis it self

**Comment by hubertdeng123** [comment]
How often is this error happening? What does your event volume look like?

**Comment by bijancot** [comment]
I'll try to get it here soon. Unfortunately we don't have uptime monitoring
for our sentry because it counts as internal tools. But it's likely happen
almost every day back then, I'll try to undo our changes we made and get
the logs

Chers !

Pada Rab, 18 Sep 2024 pukul 06.15 Hubert Deng ***@***.***>
menulis:

**Comment by aldy505** [comment]
For this specific warn on your logs:
```
relay-1 | 2024-09-14T10:22:17.357352Z ERROR relay_server::services::health_check: Not enough memory, 16071245824 / 16372436992 (98.16% >= 95.00%)
relay-1 | 2024-09-14T10:22:17.358510Z ERROR relay_server::services::health_check: Health check probe 'system memory' failed
```

Please refer to this https://github.com/getsentry/self-hosted/issues/3330#issuecomment-2364791946
