### ISSUE TITLE
Sentry stopped processing queries

### ISSUE THREAD

**Issue by barisyild** [getsentry/self-hosted#3333]
### Self-Hosted Version

24.9.0

### CPU Architecture

x86_64

### Docker Version

27.2.1

### Docker Compose Version

2.29.2

### Steps to Reproduce

idk

### Expected Result

Sentry should have continued processing queries.

### Actual Result

Issue reporting, Profiles working but queries not working.

**Comment by hubertdeng123** [comment]
You will need to give more information if you'd like our support.

**Comment by barisyild** [comment]
> You will need to give more information if you'd like our support. 

After restarting the server several times it stopped processing queries.

I don't know exactly what kind of log I should send.

**Comment by aldy505** [comment]
Try to provide us the instrumentation code you're sending to your self-hosted instance. After the program sent the event (check this by enabling the debug option on your SDK), try to observe the `relay` container, see if it's rejecting the event. If no logs are shown, try to check `post-process-forwarder-transactions`, `subscription-consumer-transactions`, and `snuba-spans-consumer` containers. Is there any error logs there?

**Comment by barisyild** [comment]
```
DEBUG: Capturing transaction: 1f13e6456e2142f783e94fe39cd6e4c1
DEBUG: Attaching client report to envelope.
DEBUG: Serializing object: [censored]
DEBUG: Serializing object: [censored]
ERROR: Request failed, API returned 403
ERROR: {"detail":"event submission rejected with_reason: ProjectId"}
ERROR: The transport failed to send the envelope with response code 403
ERROR: Envelope submission failed
 java.lang.IllegalStateException: The transport failed to send the envelope with response code 403
java.lang.IllegalStateException: The transport failed to send the envelope with response code 403
        at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.flush(AsyncHttpTransport.java:320)
        at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.run(AsyncHttpTransport.java:243)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by hubertdeng123** [comment]
Can you make sure that your DSN matches what the project should be?

**Comment by barisyild** [comment]
> Can you make sure that your DSN matches what the project should be?

Yeah matches because reports issues.

**Comment by barisyild** [comment]
[Nuclear Option](https://develop.sentry.dev/self-hosted/troubleshooting/#nuclear-option) fixed my issue.

**Comment by wilkis3** [comment]
> [Nuclear Option](https://develop.sentry.dev/self-hosted/troubleshooting/#nuclear-option) fixed my issue.

Quickie: The nuclear option deletes only the queries, events etc. and not the settings and DSNs?

**Comment by barisyild** [comment]
> > [Nuclear Option](https://develop.sentry.dev/self-hosted/troubleshooting/#nuclear-option) fixed my issue.
> 
> Quickie: The nuclear option deletes only the queries, events etc. and not the settings and DSNs?

The queue must have been broken for some reason.

I had problems with kafka offset.
