### ISSUE TITLE
Install from git not installing all data previously contained in wheels

### ISSUE THREAD

**Issue by MRigal** [getsentry/self-hosted#3337]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

After stopping and yanking the sentry releases on Gihub, see https://github.com/getsentry/self-hosted/issues/1654 the way to go has been described as installing directly from git. However the content installed is not the same, in particular, when doing:
`pip install git+https://github.com/getsentry/sentry.git@24.9.0`
you will have no `locale` dir
wherea when installing the yanked version from pypi ignoring the warning through
`pip install sentry==23.7.1`
you will have a `locale` dir.

Context:
We want to add the legay integration for googlechat on our on-premise sentry from here: https://github.com/jweslley/sentry-googlechat
In the `sentry/enhance-image.sh` we used to have `pip install sentry-googlechat` but this fails it requires `sentry` to be installed and can't install it from PyPI.
We now try to install it from git but this fails as it installs a "weak" version of Sentry, not containing all package data like locale.
Also installing it locally from `/usr/src/sentry` (as it is COPY'd over in the previous step of the Docker image build definition) fails, for the same reason...

### Expected Result

If installing from git via `pip install git+https://github.com/getsentry/sentry.git@24.9.0` is the replacement of installing from PyPI, then it should have the same outcome. The pyproject.toml should be extended to include locale and possibly other discarded files from the build.

### Actual Result

`locale` dir is missing

### Product Area

Other

### Version

24.9.0

**Comment by MRigal** [comment]
@aldy505 thanks for your message! I'm not an author of the plugin, but I made [a MR](https://github.com/jweslley/sentry-googlechat/pull/6) with the fix, because indeed, it is not required!

Still, I think that if there is an announcement that installing from git is the go-to method to replace installing from PyPI wheels, it should then behave the same. Or at least, there should be a way with extras to get the same result. And IMHO, it makes sense that locale are present when installing from git.

**Comment by aldy505** [comment]
I'm going to close this issue as it's resolved.
