### ISSUE TITLE
Does Sentry Self-Hosted support distributed tracing (ex: tracing an issue across backend API and Angular front end)? A few questions.

### ISSUE THREAD

**Issue by edgariscoding** [getsentry/self-hosted#3338]
### Problem Statement

I keep reading about this cool feature and I want to implement it in our project but I can't seem to make much progress. 

I have my projects configured and reporting errors to Sentry but they use different DSNs since they're in different Sentry projects. Do I need to combine the UI and API into a single Sentry project? 

The API Issues contain a Trace ID and when i click it this is what i see:

![Image](https://github.com/user-attachments/assets/dfd35a1b-6419-4682-866b-c5a22f5799ed)

The UI issues do not contain a Trace ID, and there's a transaction field but it just shows `--`. 

I've tried to follow along with instruction in the documentation, but nothing seems to work, which made me question whether this is even supported in Self Hosted.

**Comment by aldy505** [comment]
Yes this is totally supported in self-hosted. I made a simple demo for this thing a while back here https://github.com/aldy505/mtls-tracing-demo, though it's not using dotnet. Make sure to crosscheck with the SDK (Angular or .NET in this case) to enable distributed tracing (on Angular and other frontend stuff it's closely related to the `tracePropagationTargets` config, see here https://docs.sentry.io/platforms/javascript/guides/angular/tracing/instrumentation/automatic-instrumentation/#tracepropagationtargets). For .NET if you;re ruynning ASP.NET Core, you don't need to do anything if you've enabled tracing.
