### ISSUE TITLE
upgrading from 9.0 to the latest, stuck on upgrade from 21.5.0 to 21.6.3. Could not find a version that satisfies the requirement sentry-relay==0.8.7 (from sentry)

### ISSUE THREAD

**Issue by IgalSc** [getsentry/self-hosted#3340]
### Self-Hosted Version

21.5.0

### CPU Architecture

x86_64

### Docker Version

no docker

### Docker Compose Version

no docker

### Steps to Reproduce

pip install sentry==21.6.3 sentry-relay==0.8.7 --no-cache-dir

### Expected Result

installation succeeds

### Actual Result

pip install sentry==21.6.3 sentry-relay==0.8.7 --no-cache-dir
Collecting pip
  Downloading https://files.pythonhosted.org/packages/a4/6d/6463d49a933f547439d6b5b98b46af8742cc03ae83543e4d7688c2420f8b/pip-21.3.1-py3-none-any.whl (1.7MB)
    100% |████████████████████████████████| 1.7MB 11.1MB/s
Installing collected packages: pip
  Found existing installation: pip 18.1
    Uninstalling pip-18.1:
      Successfully uninstalled pip-18.1
Successfully installed pip-21.3.1
Collecting sentry==21.6.3
  Downloading sentry-21.6.3-0-py36-none-any.whl (44.8 MB)
     |████████████████████████████████| 44.8 MB 3.5 MB/s
ERROR: Could not find a version that satisfies the requirement sentry-relay==0.8.7 (from versions: 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.5.6, 0.5.7, 0.5.8, 0.5.9, 0.5.10, 0.5.11, 0.5.12, 0.5.13, 0.8.24, 0.8.25, 0.8.26, 0.8.27, 0.15.13, 1.1.4)
ERROR: No matching distribution found for sentry-relay==0.8.7
(sentry_env_py36) (base) root@ip-10-199-2-94:~# pip install sentry==21.6.3 sentry-relay==0.8.24 --no-cache-dir
Collecting sentry==21.6.3
  Downloading sentry-21.6.3-0-py36-none-any.whl (44.8 MB)
     |████████████████████████████████| 44.8 MB 8.2 MB/s
Collecting sentry-relay==0.8.24
  Downloading sentry_relay-0.8.24-py2.py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (37.4 MB)
     |████████████████████████████████| 37.4 MB 2.5 MB/s
Collecting Pillow==8.2.0
  Downloading Pillow-8.2.0-cp36-cp36m-manylinux1_x86_64.whl (3.0 MB)
     |████████████████████████████████| 3.0 MB 51.5 MB/s
Collecting selenium==3.141.0
  Downloading selenium-3.141.0-py2.py3-none-any.whl (904 kB)
     |████████████████████████████████| 904 kB 58.3 MB/s
Collecting kombu==4.6.11
  Downloading kombu-4.6.11-py2.py3-none-any.whl (184 kB)
     |████████████████████████████████| 184 kB 63.6 MB/s
Collecting dataclasses==0.8
  Downloading dataclasses-0.8-py3-none-any.whl (19 kB)
Collecting mmh3==3.0.0
  Downloading mmh3-3.0.0-cp36-cp36m-manylinux2010_x86_64.whl (49 kB)
     |████████████████████████████████| 49 kB 52.3 MB/s
Collecting statsd==3.3
  Downloading statsd-3.3.0-py2.py3-none-any.whl (11 kB)
Collecting django-crispy-forms==1.7.2
  Downloading django_crispy_forms-1.7.2-py2.py3-none-any.whl (105 kB)
     |████████████████████████████████| 105 kB 63.2 MB/s
Collecting Django==1.11.29
  Downloading Django-1.11.29-py2.py3-none-any.whl (6.9 MB)
     |████████████████████████████████| 6.9 MB 59.6 MB/s
Collecting cssselect==1.0.3
  Downloading cssselect-1.0.3-py2.py3-none-any.whl (16 kB)
Collecting symbolic==8.1.0
  Downloading symbolic-8.1.0-py2.py3-none-manylinux2010_x86_64.whl (15.6 MB)
     |████████████████████████████████| 15.6 MB 60.4 MB/s
Collecting hiredis==0.3.1
  Downloading hiredis-0.3.1-cp36-cp36m-manylinux1_x86_64.whl (50 kB)
     |████████████████████████████████| 50 kB 55.5 MB/s
Collecting datadog==0.29.3
  Downloading datadog-0.29.3-py2.py3-none-any.whl (72 kB)
     |████████████████████████████████| 72 kB 36.4 MB/s
Collecting toronado==0.1.0
  Downloading toronado-0.1.0-py2.py3-none-any.whl (8.5 kB)
Collecting cffi==1.14.5
  Downloading cffi-1.14.5-cp36-cp36m-manylinux1_x86_64.whl (401 kB)
     |████████████████████████████████| 401 kB 62.1 MB/s
Collecting grpcio==1.35.0
  Downloading grpcio-1.35.0-cp36-cp36m-manylinux2014_x86_64.whl (4.1 MB)
     |████████████████████████████████| 4.1 MB 57.3 MB/s
Collecting PyJWT==2.1.0
  Downloading PyJWT-2.1.0-py3-none-any.whl (16 kB)
Collecting uWSGI==2.0.19.1
  Downloading uWSGI-2.0.19.1.tar.gz (803 kB)
     |████████████████████████████████| 803 kB 62.4 MB/s
  Preparing metadata (setup.py) ... done
Collecting botocore==1.13.50
  Downloading botocore-1.13.50-py2.py3-none-any.whl (5.9 MB)
     |████████████████████████████████| 5.9 MB 55.2 MB/s
Collecting PyYAML==5.4
  Downloading PyYAML-5.4-cp36-cp36m-manylinux1_x86_64.whl (640 kB)
     |████████████████████████████████| 640 kB 60.4 MB/s
Collecting requests-oauthlib==1.2.0
  Downloading requests_oauthlib-1.2.0-py2.py3-none-any.whl (22 kB)
Collecting django-picklefield==1.0.0
  Downloading django_picklefield-1.0.0-py2.py3-none-any.whl (14 kB)
Collecting googleapis-common-protos==1.52.0
  Downloading googleapis_common_protos-1.52.0-py2.py3-none-any.whl (100 kB)
     |████████████████████████████████| 100 kB 60.6 MB/s
Collecting python3-saml==1.10.1
  Downloading python3_saml-1.10.1-py3-none-any.whl (75 kB)
     |████████████████████████████████| 75 kB 55.0 MB/s
Collecting python-memcached==1.59
  Downloading python_memcached-1.59-py2.py3-none-any.whl (16 kB)
Collecting progressbar2==3.32.0
  Downloading progressbar2-3.32.0-py2.py3-none-any.whl (23 kB)
Collecting redis==3.4.1
  Downloading redis-3.4.1-py2.py3-none-any.whl (71 kB)
     |████████████████████████████████| 71 kB 58.9 MB/s
Collecting google-cloud-core==1.5.0
  Downloading google_cloud_core-1.5.0-py2.py3-none-any.whl (27 kB)
Collecting simplejson==3.17.2
  Downloading simplejson-3.17.2-cp36-cp36m-manylinux2010_x86_64.whl (127 kB)
     |████████████████████████████████| 127 kB 63.9 MB/s
Collecting confluent-kafka==1.5.0
  Downloading confluent_kafka-1.5.0-cp36-cp36m-manylinux1_x86_64.whl (8.1 MB)
     |████████████████████████████████| 8.1 MB 61.0 MB/s
Collecting email-reply-parser==0.5.12
  Downloading email_reply_parser-0.5.12-py3-none-any.whl (4.1 kB)
Collecting celery==4.4.7
  Downloading celery-4.4.7-py2.py3-none-any.whl (427 kB)
     |████████████████████████████████| 427 kB 62.0 MB/s
Collecting mistune==0.8.4
  Downloading mistune-0.8.4-py2.py3-none-any.whl (16 kB)
Collecting google-cloud-storage==1.35.0
  Downloading google_cloud_storage-1.35.0-py2.py3-none-any.whl (96 kB)
     |████████████████████████████████| 96 kB 55.8 MB/s
Collecting lxml==4.6.3
  Downloading lxml-4.6.3-cp36-cp36m-manylinux2014_x86_64.whl (6.3 MB)
     |████████████████████████████████| 6.3 MB 58.9 MB/s
Collecting beautifulsoup4==4.7.1
  Downloading beautifulsoup4-4.7.1-py3-none-any.whl (94 kB)
     |████████████████████████████████| 94 kB 49.1 MB/s
Collecting sentry-sdk<1.2.0,>=1.0.0
  Downloading sentry_sdk-1.1.0-py2.py3-none-any.whl (131 kB)
     |████████████████████████████████| 131 kB 62.8 MB/s
Collecting unidiff==0.6.0
  Downloading unidiff-0.6.0-py2.py3-none-any.whl (13 kB)
Collecting rfc3339-validator==0.1.2
  Downloading rfc3339_validator-0.1.2-py2.py3-none-any.whl (3.5 kB)
ERROR: Cannot install sentry-relay==0.8.24 and sentry==21.6.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested sentry-relay==0.8.24
    sentry 21.6.3 depends on sentry-relay==0.8.7

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
(sentry_env_py36) (base) root@ip-10-199-2-94:~# pip install sentry==21.6.3 --no-cache-dir
Collecting sentry==21.6.3
  Downloading sentry-21.6.3-0-py36-none-any.whl (44.8 MB)
     |████████████████████████████████| 44.8 MB 3.7 MB/s
Collecting Django==1.11.29
  Downloading Django-1.11.29-py2.py3-none-any.whl (6.9 MB)
     |████████████████████████████████| 6.9 MB 62.8 MB/s
Collecting kombu==4.6.11
  Downloading kombu-4.6.11-py2.py3-none-any.whl (184 kB)
     |████████████████████████████████| 184 kB 62.5 MB/s
Collecting google-api-core==1.25.1
  Downloading google_api_core-1.25.1-py2.py3-none-any.whl (92 kB)
     |████████████████████████████████| 92 kB 13.0 MB/s
Collecting python-u2flib-server==5.0.0
  Downloading python-u2flib-server-5.0.0.tar.gz (31 kB)
  Preparing metadata (setup.py) ... done
Collecting djangorestframework==3.11.2
  Downloading djangorestframework-3.11.2-py3-none-any.whl (911 kB)
     |████████████████████████████████| 911 kB 62.8 MB/s
Collecting requests==2.25.1
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 57.9 MB/s
Collecting croniter==0.3.37
  Downloading croniter-0.3.37-py2.py3-none-any.whl (13 kB)
Collecting googleapis-common-protos==1.52.0
  Downloading googleapis_common_protos-1.52.0-py2.py3-none-any.whl (100 kB)
     |████████████████████████████████| 100 kB 62.9 MB/s
Collecting google-cloud-pubsub==2.2.0
  Downloading google_cloud_pubsub-2.2.0-py2.py3-none-any.whl (179 kB)
     |████████████████████████████████| 179 kB 63.5 MB/s
Collecting requests-oauthlib==1.2.0
  Downloading requests_oauthlib-1.2.0-py2.py3-none-any.whl (22 kB)
Collecting dataclasses==0.8
  Downloading dataclasses-0.8-py3-none-any.whl (19 kB)
Collecting google-cloud-bigtable==1.6.1
  Downloading google_cloud_bigtable-1.6.1-py2.py3-none-any.whl (267 kB)
     |████████████████████████████████| 267 kB 59.6 MB/s
Collecting progressbar2==3.32.0
  Downloading progressbar2-3.32.0-py2.py3-none-any.whl (23 kB)
Collecting parsimonious==0.8.0
  Downloading parsimonious-0.8.0.tar.gz (38 kB)
  Preparing metadata (setup.py) ... done
Collecting PyJWT==2.1.0
  Downloading PyJWT-2.1.0-py3-none-any.whl (16 kB)
ERROR: Could not find a version that satisfies the requirement sentry-relay==0.8.7 (from sentry) (from versions: 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.5.6, 0.5.7, 0.5.8, 0.5.9, 0.5.10, 0.5.11, 0.5.12, 0.5.13, 0.8.24, 0.8.25, 0.8.26, 0.8.27, 0.15.13, 1.1.4)
ERROR: No matching distribution found for sentry-relay==0.8.7

**Comment by bijancot** [comment]
interesting it's from long time ago right? and it's look like the requirements.txt have been deprecated. Did you try to manually update the version inside requirements.txt to nearest version? like https://pypi.org/project/sentry-relay/#history or that mentioned in error messages ?

**Comment by IgalSc** [comment]
This is from 2 days ago.
I was given to administrate a system that has Sentry 9.0, and decided to upgrade it to the latest version. 
I went with the upgrade process outlined here https://develop.sentry.dev/self-hosted/releases/
i upgraded from 9.0 to 9.1.2 and to 21.5.0 with no issue,  but then it fails on the next step, because the sentry-relay==0.8.7 is a hardcoded requirement and looks like Sentry removed it from their repo.

**Comment by bijancot** [comment]
I see, there is some heads up that i missed when first time executing upgrade on sentry 

> We may have some updated configuration, especially for new features, so always check the example config files under the [sentry directory](https://github.com/getsentry/self-hosted/blob/master/sentry/) and see if you need to update your existing configuration. We do our best to automate critical configuration updates, but you should always check your configs during upgrades.

So you should try to compare it manually first like these https://github.com/getsentry/self-hosted/compare/21.5.0..21.6.3 or something else

**Comment by IgalSc** [comment]
`python3 -m venv sentry_env`


`pip install sentry==21.6.3
Collecting sentry==21.6.3
  Downloading sentry-21.6.3-0-py36-none-any.whl.metadata (6.0 kB)
Collecting beautifulsoup4==4.7.1 (from sentry==21.6.3)
  Using cached beautifulsoup4-4.7.1-py3-none-any.whl.metadata (3.0 kB)
Collecting boto3==1.10.49 (from sentry==21.6.3)
  Using cached boto3-1.10.49-py2.py3-none-any.whl.metadata (4.8 kB)
Collecting botocore==1.13.50 (from sentry==21.6.3)
  Using cached botocore-1.13.50-py2.py3-none-any.whl.metadata (3.4 kB)
Collecting celery==4.4.7 (from sentry==21.6.3)
  Using cached celery-4.4.7-py2.py3-none-any.whl.metadata (19 kB)
Collecting click==7.1.2 (from sentry==21.6.3)
  Using cached click-7.1.2-py2.py3-none-any.whl.metadata (2.9 kB)
Collecting croniter==0.3.37 (from sentry==21.6.3)
  Using cached croniter-0.3.37-py2.py3-none-any.whl.metadata (15 kB)
Collecting datadog==0.29.3 (from sentry==21.6.3)
  Using cached datadog-0.29.3-py2.py3-none-any.whl.metadata (4.5 kB)
Collecting django-crispy-forms==1.7.2 (from sentry==21.6.3)
  Using cached django_crispy_forms-1.7.2-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting django-picklefield==1.0.0 (from sentry==21.6.3)
  Using cached django_picklefield-1.0.0-py2.py3-none-any.whl.metadata (8.7 kB)
Collecting Django==1.11.29 (from sentry==21.6.3)
  Using cached Django-1.11.29-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting djangorestframework==3.11.2 (from sentry==21.6.3)
  Using cached djangorestframework-3.11.2-py3-none-any.whl.metadata (10 kB)
Collecting email-reply-parser==0.5.12 (from sentry==21.6.3)
  Using cached email_reply_parser-0.5.12-py3-none-any.whl.metadata (828 bytes)
Collecting google-api-core==1.25.1 (from sentry==21.6.3)
  Using cached google_api_core-1.25.1-py2.py3-none-any.whl.metadata (2.4 kB)
Collecting google-auth==1.24.0 (from sentry==21.6.3)
  Using cached google_auth-1.24.0-py2.py3-none-any.whl.metadata (3.3 kB)
Collecting google-cloud-bigtable==1.6.1 (from sentry==21.6.3)
  Using cached google_cloud_bigtable-1.6.1-py2.py3-none-any.whl.metadata (4.5 kB)
Collecting google-cloud-core==1.5.0 (from sentry==21.6.3)
  Using cached google_cloud_core-1.5.0-py2.py3-none-any.whl.metadata (2.4 kB)
Collecting googleapis-common-protos==1.52.0 (from sentry==21.6.3)
  Using cached googleapis_common_protos-1.52.0-py2.py3-none-any.whl.metadata (1.3 kB)
Collecting google-cloud-pubsub==2.2.0 (from sentry==21.6.3)
  Using cached google_cloud_pubsub-2.2.0-py2.py3-none-any.whl.metadata (8.7 kB)
Collecting google-cloud-storage==1.35.0 (from sentry==21.6.3)
  Using cached google_cloud_storage-1.35.0-py2.py3-none-any.whl.metadata (4.7 kB)
Collecting jsonschema==3.2.0 (from sentry==21.6.3)
  Using cached jsonschema-3.2.0-py2.py3-none-any.whl.metadata (7.8 kB)
Collecting lxml==4.6.3 (from sentry==21.6.3)
  Using cached lxml-4.6.3.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting maxminddb==2.0.3 (from sentry==21.6.3)
  Using cached maxminddb-2.0.3.tar.gz (286 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting mistune==0.8.4 (from sentry==21.6.3)
  Using cached mistune-0.8.4-py2.py3-none-any.whl.metadata (8.5 kB)
Collecting mmh3==3.0.0 (from sentry==21.6.3)
  Using cached mmh3-3.0.0.tar.gz (10 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting parsimonious==0.8.0 (from sentry==21.6.3)
  Using cached parsimonious-0.8.0.tar.gz (38 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting petname==2.6 (from sentry==21.6.3)
  Using cached petname-2.6.tar.gz (8.4 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting phonenumberslite==8.12.0 (from sentry==21.6.3)
  Using cached phonenumberslite-8.12.0-py2.py3-none-any.whl.metadata (10 kB)
Collecting Pillow==8.2.0 (from sentry==21.6.3)
  Downloading Pillow-8.2.0.tar.gz (47.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.9/47.9 MB 12.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting progressbar2==3.32.0 (from sentry==21.6.3)
  Using cached progressbar2-3.32.0-py2.py3-none-any.whl.metadata (7.6 kB)
Collecting PyJWT==2.1.0 (from sentry==21.6.3)
  Downloading PyJWT-2.1.0-py3-none-any.whl.metadata (4.0 kB)
Collecting python-dateutil==2.8.1 (from sentry==21.6.3)
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl.metadata (8.0 kB)
Collecting python-memcached==1.59 (from sentry==21.6.3)
  Using cached python_memcached-1.59-py2.py3-none-any.whl.metadata (2.1 kB)
Collecting python-u2flib-server==5.0.0 (from sentry==21.6.3)
  Using cached python-u2flib-server-5.0.0.tar.gz (31 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting python3-saml==1.10.1 (from sentry==21.6.3)
  Using cached python3_saml-1.10.1-py3-none-any.whl.metadata (1.3 kB)
Collecting PyYAML==5.4 (from sentry==21.6.3)
  Using cached PyYAML-5.4.tar.gz (174 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/root/sentry_env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/root/sentry_env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/root/sentry_env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-huzux3cr/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-huzux3cr/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-huzux3cr/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "/tmp/pip-build-env-huzux3cr/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-huzux3cr/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-huzux3cr/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-huzux3cr/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-huzux3cr/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-huzux3cr/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-huzux3cr/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 311, in run
          self.find_sources()
        File "/tmp/pip-build-env-huzux3cr/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 319, in find_sources
          mm.run()
        File "/tmp/pip-build-env-huzux3cr/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 540, in run
          self.add_defaults()
        File "/tmp/pip-build-env-huzux3cr/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 578, in add_defaults
          sdist.add_defaults(self)
        File "/tmp/pip-build-env-huzux3cr/overlay/lib/python3.12/site-packages/setuptools/command/sdist.py", line 108, in add_defaults
          super().add_defaults()
        File "/tmp/pip-build-env-huzux3cr/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 238, in add_defaults
          self._add_defaults_ext()
        File "/tmp/pip-build-env-huzux3cr/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 323, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 201, in get_source_files
        File "/tmp/pip-build-env-huzux3cr/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

**Comment by bijancot** [comment]
I'm kinda running out of idea, is moving your sentry to docker version could be added to your options ? the steps would be :
- prepare sentry 21.5.0 running with docker compose
- backup from existing (i'm kinda not sure is backup command could be executed there https://develop.sentry.dev/self-hosted/backup/)
- try restore from backup file to the docker version
- continue upgrade process

**Comment by IgalSc** [comment]
I do have an external DB for Sentry
Theoretically, I would need to run Docker version of 21.6.3, execute the upgrade, then launch 23.6.2, 23.11.0 and 24.8.0 as Docker, running upgrade every time?
I think I will give it a try

**Comment by bijancot** [comment]
ow that's great yes after moving to docker compose you don't need dealing with dependency hell at least as long as keepin your eye on version stops.

Would like to hear more if you already give it a try!

**Comment by IgalSc** [comment]
After running FAKE upgrades for half a day, i upgraded to 21.6.3, now I'm stuck half the way to upgrade to 23.6.2 
i had to add snuba, kafka, clickhouse and zookeper deployments)
now i have an issue with the startup of the 23.6.2

my environment variables are 
    spec:
      containers:
      - name: sentry
        image: getsentry/sentry:23.6.2
        ports:
        - containerPort: 9000
        env:
        - name: SENTRY_SECRET_KEY
          value: "secret_key_here"
        - name: SENTRY_DB_ENGINE
          value: "sentry.db.postgres"
        - name: SENTRY_POSTGRES_HOST
          value: "sentry-db-new.domain_name"
        - name: SENTRY_POSTGRES_PORT
          value: "5432"
        - name: SENTRY_DB_NAME
          value: "sentry_logging"
        - name: SENTRY_DB_USER
          value: "sentry"
        - name: SENTRY_DB_PASSWORD
          value: "passsword_here"
        - name: SENTRY_REDIS_HOST
          value: "redis-staging.domain_name"
        - name: SENTRY_REDIS_PORT
          value: "6379"
        - name: SENTRY_TSDB
          value: "sentry.tsdb.redis.RedisSnubaTSDB"
        - name: SENTRY_TSDB_OPTIONS
          value: '{"hosts": [["snuba-api.namepsace", 1218]]}'

The error i get is 
!! Configuration error: ConfigurationError("sentry.tsdb service failed to call validate()\nmodule 'sentry.tsdb.redis' has no attribute 'RedisSnubaTSDB'")

**Comment by jreagan000** [comment]
@IgalSc I am having issues upgrading from 10.1 to 21.5.0. What OS are you using? I am getting the following and not sure how to get passed it

#6 1.049 Ign:12 http://deb.debian.org/debian stretch-updates/main all Packages
#6 1.060 Ign:9 http://deb.debian.org/debian stretch/main all Packages
#6 1.083 Err:10 http://deb.debian.org/debian stretch/main amd64 Packages
#6 1.083   404  Not Found
#6 1.188 Err:11 http://deb.debian.org/debian stretch-updates/main amd64 Packages
#6 1.188   404  Not Found
#6 1.200 Ign:12 http://deb.debian.org/debian stretch-updates/main all Packages
#6 1.206 Reading package lists...
#6 1.218 W: The repository 'http://security.debian.org/debian-security stretch/updates Release' does not have a Release file.
#6 1.218 W: The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file.
#6 1.218 W: The repository 'http://deb.debian.org/debian stretch-updates Release' does not have a Release file.
#6 1.218 E: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/main/binary-amd64/Packages  404  Not Found [IP: 151.101.2.132 80]
#6 1.218 E: Failed to fetch http://deb.debian.org/debian/dists/stretch/main/binary-amd64/Packages  404  Not Found
#6 1.218 E: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/main/binary-amd64/Packages  404  Not Found
#6 1.218 E: Some index files failed to download. They have been ignored, or old ones used instead.
#6 ERROR: process "/bin/sh -c apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*" did not complete successfully: exit code: 100

**Comment by IgalSc** [comment]
@jreagan000  this looks like an issue updating the OS ?
I upgraded the Sentry from 9.1.2 to 21.5.0
Check the release notes - there's smth wrong with the 10.x versions

**Comment by aldy505** [comment]
Reading the discussion, I don't have any other suggestion rather than start anew. But I know that it's not desirable at all.

If you can do a backup clone of your VM, and if you're brave enough, you might want to go ahead and try to upgrade directly to 23.6.2.
