### ISSUE TITLE
Sometimes fail to symbolicate

### ISSUE THREAD

**Issue by youngdie** [getsentry/self-hosted#3343]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

If I run sentry for a long period of time, I will occasionally run into the problem of failing to symbolicate.

Sometimes it works by restarting docker, sometimes not.

Is it possible to check with the contents of “download failed”?

![Image](https://github.com/user-attachments/assets/18085dcd-5f88-4c7e-b0a3-77f50917db91)

### Expected Result

![Image](https://github.com/user-attachments/assets/d55dbe3f-7fcb-4712-8961-c849748c77cc)

The symbolicate must be successful

### Actual Result

The symbolicate fails

### Product Area

Processing

### Version

24.6.0

**Comment by bijancot** [comment]
Hi!

did you find something strange with the logs?

**Comment by youngdie** [comment]
I found some logs

![Image](https://github.com/user-attachments/assets/f3cb241e-51aa-425e-8a01-acae808968f1)

![Image](https://github.com/user-attachments/assets/aa0a9628-69b7-43fe-9760-79372c0681b7)

sentry-self-hosted-worker-1                                        | socket.gaierror: [Errno -2] Name or service not known
sentry-self-hosted-worker-1                                        | socket.gaierror: [Errno -2] Name or service not known
sentry-self-hosted-worker-1                                        | 10:27:56 [ERROR] sentry.errors.events: tasks.store.symbolicate_event.symbolication
sentry-self-hosted-worker-1                                        | socket.gaierror: [Errno -2] Name or service not known
sentry-self-hosted-worker-1                                        | socket.gaierror: [Errno -2] Name or service not known
sentry-self-hosted-worker-1                                        | 10:27:59 [ERROR] sentry.errors.events: tasks.store.symbolicate_event.symbolication
sentry-self-hosted-worker-1                                        | socket.gaierror: [Errno -2] Name or service not known
sentry-self-hosted-worker-1                                        | socket.gaierror: [Errno -2] Name or service not known

![Image](https://github.com/user-attachments/assets/6659a0e9-ba98-4962-9f9f-f7a98c74a5aa)

**Comment by bijancot** [comment]
Hi, it's look like either somehow your docker container can't resolve some service within docker compose, or the service have been changing name or something. Is there any changes in service name inside your docker compose ?

**Comment by youngdie** [comment]
No, I changed nothing, just did upgrade once. What should I do to find out?

**Comment by youngdie** [comment]
I found these messages. Is it ok?

![Image](https://github.com/user-attachments/assets/77b68da7-b351-4716-bcaf-f6d4738b1079)

**Comment by hubertdeng123** [comment]
Are there any logs in symbolicator? Looks like there is some trouble communicating to that container
