### ISSUE TITLE
Error in set-up-and-migrate-database.sh: '--create-kafka-topics' is no longer a valid option for 'sentry upgrade'

### ISSUE THREAD

**Issue by Jedve** [getsentry/self-hosted#3344]
### Self-Hosted Version

21.9.0

### CPU Architecture

x86_64

### Docker Version

24.0.5

### Docker Compose Version

2.20.2

### Steps to Reproduce

Execute script install.sh

### Expected Result

The installation should complete successfully without any errors, and the command sentry upgrade should execute without referencing the --create-kafka-topics option, allowing for proper setup of Sentry Self-Hosted.

### Actual Result

Running hooks in /etc/ca-certificates/update.d...
done.
Usage: sentry upgrade [OPTIONS]
Try 'sentry upgrade --help' for help.

Error: No such option: --create-kafka-topics
Error in install/set-up-and-migrate-database.sh:36.
'$dcr web upgrade --create-kafka-topics' exited with status 2
-> ./install.sh:main:37
--> install/set-up-and-migrate-database.sh:source:36

**Comment by bijancot** [comment]
Hi!

Did you follow this documentation https://develop.sentry.dev/self-hosted/releases/ ?

**Comment by Jedve** [comment]
H @bijancot !

Thank you for your answer.

Yes I did. 
I'm currently at the version 24.5.1 and if I understood correctly, there is no breaking changes from this version to run the update.
Even if I try to run the install.sh script at the 24.6.0 version, I get this error.

**Comment by bijancot** [comment]
i got similar issues when try from version 23.5.1 to 24.8.0. I guess this is my last suggestion for now, try replace all config including the template inside `/sentry` with the new one from target version. Or simply remove `config.yml` and `sentry.conf.py` then run install again. 

**Remember to backup both file before execute**

**Comment by Jedve** [comment]
@bijancot 

I tried your solution but still having the issue.

Can the issue come from the parameter "--create-kafka-topics" that has been removed from the sentry cli ?

**Comment by bijancot** [comment]
i remember something, what is the content of `set-up-and-migrate-database.sh` inside your `install` folder? could you please share it?

**Comment by Jedve** [comment]
Content of my install/set-up-and-migrate-database.sh:

`echo "${_group}Setting up / migrating database ..."

# Fixes https://github.com/getsentry/self-hosted/issues/2758, where a migration fails due to indexing issue
$dc up -d postgres
# Wait for postgres
RETRIES=5
until $dc exec postgres psql -U postgres -c "select 1" >/dev/null 2>&1 || [ $RETRIES -eq 0 ]; do
  echo "Waiting for postgres server, $((RETRIES--)) remaining attempts..."
  sleep 1
done

# Using django ORM to provide broader support for users with external databases
$dcr web shell -c "
from django.db import connection

with connection.cursor() as cursor:
  cursor.execute('ALTER TABLE IF EXISTS sentry_groupedmessage DROP CONSTRAINT IF EXISTS sentry_groupedmessage_project_id_id_515aaa7e_uniq;')
  cursor.execute('DROP INDEX IF EXISTS sentry_groupedmessage_project_id_id_515aaa7e_uniq;')
"

if [[ -n "${CI:-}" || "${SKIP_USER_CREATION:-0}" == 1 ]]; then
  $dcr web upgrade --noinput
  echo ""
  echo "Did not prompt for user creation. Run the following command to create one"
  echo "yourself (recommended):"
  echo ""
  echo "  $dc_base run --rm web createuser"
  echo ""
else
  $dcr web upgrade
fi

echo "${_endgroup}"`

**Comment by bijancot** [comment]
are u sure using 24.5.1 i can't found it in tag list (but i might be wrong) and the flag is still passed here https://github.com/getsentry/self-hosted/blob/24.6.0/install/set-up-and-migrate-database.sh and also check your .env file

**Comment by hubertdeng123** [comment]
You may need to ensure your .env file is pointing to the right sentry image

**Comment by Jedve** [comment]
@hubertdeng123 You're right !

I'm really confused that I didn't think about my custom .env file.

Thank you very much for your help.
