### ISSUE TITLE
js stacktraces don't get deobfuscated

### ISSUE THREAD

**Issue by 729993031** [getsentry/self-hosted#3349]
### Self-Hosted Version

24.8.0

### CPU Architecture

x86_64

### Docker Version

25.0.5

### Docker Compose Version

2.29.1

### Steps to Reproduce

1. When I restart the compouter system,
`cd self-hosted,
sudo ./install.sh
`
2. the js stacktraces don't get deobfuscated

## Use In Saas
![Image](https://github.com/user-attachments/assets/cf5f18be-6dec-4f2b-999b-dadc2f356593)

### Actual Result

![Image](https://github.com/user-attachments/assets/0ce52933-dc34-4609-b057-b951ee31f4a4)

## Hint
And I discovery the Profiling has Error  Now
![Image](https://github.com/user-attachments/assets/ec62d085-e5da-4b85-bd14-7e6a43f3c6de)

### Before
![Image](https://github.com/user-attachments/assets/8f27587e-db6f-4b34-b021-1aaf73e6bd74)

**Comment by aldy505** [comment]
Did you upload your JS sourcemap into Sentry yet? Please see https://docs.sentry.io/platforms/javascript/sourcemaps/

**Comment by 729993031** [comment]
# I think  I upload the  JS sourcemap into Sentry.

![Image](https://github.com/user-attachments/assets/3f0de61d-a971-414a-942f-49d7daf75d49)

![Image](https://github.com/user-attachments/assets/8e7d50f0-541b-483f-a7db-e3b7ee9b60d5)

**Comment by 729993031** [comment]
When I update to 24.9 . They can run now.
