### ISSUE TITLE
Update SSL cert

### ISSUE THREAD

**Issue by sbellver** [getsentry/self-hosted#3350]
### Self-Hosted Version

24.10.0

### CPU Architecture

x86_64

### Docker Version

27.0.3

### Docker Compose Version

1.25.0

### Steps to Reproduce

Add new ssl certs into certificates folder
- certificate.ca.crt
- certificate.crt
- certificate.key

![Image](https://github.com/user-attachments/assets/99f31ba3-0db6-4841-8da9-c116a990de93)

Run update-ca-certificates

Open url -> The SSL is the same as before (not updated)

Run install.sh
Run docker-compose ...

Open url -> The SSL is the same as before (not updated)

### Expected Result

Upgrade the custom SSL after reload/reinstall sentry 

### Actual Result

The certificate is the old one, which is already expired, and there is no way to update it.

**Comment by bc-sentry** [comment]
We are unable to reproduce this issue.
