### ISSUE TITLE
Why can't the go SDK capture error data be written to the externally configured ClickHouse?

### ISSUE THREAD

**Issue by ZLBillShaw** [getsentry/self-hosted#3351]
### Self-Hosted Version

24.9.0

### CPU Architecture

x86_64

### Docker Version

26.0.0

### Docker Compose Version

1.29.2

### Steps to Reproduce

1. I tried modifying the docker-compose.yml file to configure the external ClickHouse address as follows:
environment:
    SNUBA_SETTINGS: self_hosted
    CLICKHOUSE_HOST:  
    CLICKHOUSE_PORT:             
    CLICKHOUSE_USER: 
    CLICKHOUSE_PASSWORD: 
    CLICKHOUSE_DATABASE: 
    CLICKHOUSE_HTTP_PORT: 
    DEFAULT_BROKERS: "kafka:9092"
2. I filled in the corresponding configuration in the .env file as follows:
CLICKHOUSE_HOST=xxxxx
CLICKHOUSE_PORT=9000
CLICKHOUSE_USER=xxx
CLICKHOUSE_PASSWORD=xxx
CLICKHOUSE_DATABASE=sentry
CLICKHOUSE_HTTP_PORT=8123
3. I can currently create projects and capture errors using the API token, but I noticed that data is not being written to ClickHouse. Is there something I missed in the configuration? Because after I remove the external ClickHouse configurations from docker-compose.yml and .env, the data writes normally.

### Expected Result

I hope to be able to write the information correctly to the external ClickHouse server😭

### Actual Result

I suspect there might be some configuration options that I haven't modified, which are preventing the data from being written to the external ClickHouse.

**Comment by aldy505** [comment]
When you're using the external Clickhouse, do you see any error logs from the snuba containers? Meaning these containers https://github.com/getsentry/self-hosted/blob/8887a82a86153d0c9696463c0525976cf8e3f136/docker-compose.yml#L215-L307

**Comment by ZLBillShaw** [comment]
Thank you, I'll give it a try. My main question is that the only changes related to the ClickHouse configuration are the ones I've mentioned above, right?

**Comment by aldy505** [comment]
> Thank you, I'll give it a try. My main question is that the only changes related to the ClickHouse configuration are the ones I've mentioned above, right?

Yes, that should be it.

**Comment by ZLBillShaw** [comment]
I entered the container sentry-self-hosted-clickhouse-1 and found the following error logs. Could it be related to the configuration?
```shell
2024.10.08 04:16:07.189367 [ 1 ] {} <Warning> Application: Listen [0.0.0.0]:9009 failed: Poco::Exception. Code: 1000, e.code() = 98, Net Exception: Address already in use: 0.0.0.0:9009 (version 23.8.11.29.altinitystable (altinity build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
2024.10.08 04:16:07.194009 [ 1 ] {} <Warning> Access(local_directory): File /var/lib/clickhouse/access/users.list doesn't exist
2024.10.08 04:16:07.194049 [ 1 ] {} <Warning> Access(local_directory): Recovering lists in directory /var/lib/clickhouse/access/
2024.10.08 04:16:07.261683 [ 1 ] {} <Warning> Application: Listen [0.0.0.0]:8123 failed: Poco::Exception. Code: 1000, e.code() = 98, Net Exception: Address already in use: 0.0.0.0:8123 (version 23.8.11.29.altinitystable (altinity build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
2024.10.08 04:16:07.261802 [ 1 ] {} <Warning> Application: Listen [0.0.0.0]:9000 failed: Poco::Exception. Code: 1000, e.code() = 98, Net Exception: Address already in use: 0.0.0.0:9000 (version 23.8.11.29.altinitystable (altinity build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
2024.10.08 04:16:07.261896 [ 1 ] {} <Warning> Application: Listen [0.0.0.0]:9004 failed: Poco::Exception. Code: 1000, e.code() = 98, Net Exception: Address already in use: 0.0.0.0:9004 (version 23.8.11.29.altinitystable (altinity build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
2024.10.08 04:16:07.261994 [ 1 ] {} <Warning> Application: Listen [0.0.0.0]:9005 failed: Poco::Exception. Code: 1000, e.code() = 98, Net Exception: Address already in use: 0.0.0.0:9005 (version 23.8.11.29.altinitystable (altinity build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
```

**Comment by hubertdeng123** [comment]
If you're using an externally configured Clickhouse, then you won't need to start up the sentry-self-hosted-clickhouse-1 container and it is expected to error there.

**Comment by ZLBillShaw** [comment]
thanks

**Comment by aldy505** [comment]
Following up @ZLBillShaw, did you manage to get this resolved?

**Comment by ZLBillShaw** [comment]
The issue has been resolved, thank you.
