### ISSUE TITLE
Mandatory ram for self-hosted doesn't take errors-only into account

### ISSUE THREAD

**Issue by azimuthdeveloper** [getsentry/self-hosted#3355]
### Self-Hosted Version

24.9.0

### CPU Architecture

x86_64

### Docker Version

not related

### Docker Compose Version

not related

### Steps to Reproduce

1. Attempt to start errors-only sentry on a machine with <14GB of ram
2. Get an error about not enough RAM

### Expected Result

Sentry errors-only starts up

### Actual Result

Doesn't start.

Because errors-only is lighter than full-fat sentry, shouldn't it require less RAM, and shouldn't these requirements be relaxed accordingly? Errors-only was running well before the changes landed in 24.9.0.

Completely happy to be wrong though :)

**Comment by bijancot** [comment]
I'm not sure if these help or no. Because i'am not using my upgraded version of sentry in production. Could you check your redis? in my case back then, the redis is too full so i flush my redis and it start again.

**Comment by aldy505** [comment]
> Because errors-only is lighter than full-fat sentry, shouldn't it require less RAM, and shouldn't these requirements be relaxed accordingly? Errors-only was running well before the changes landed in 24.9.0.

Yeah you're not wrong, the system requirements script doesn't take the errors-only into account at all. See the script here: https://github.com/getsentry/self-hosted/blob/master/install/check-minimum-requirements.sh

But I don't think the devinfra team (the one who manages this repo) has decided on the proper minimum amount for installing the errors-only version. Feel free to submit a PR that change the `check-minimum-requirements.sh` file.

Side note, this should also be documented somewhere on the docs, sigh...

**Comment by azimuthdeveloper** [comment]
@aldy505  I probably can't take a punt on what amount of ram is appropriate, I'd just be guessing. It'd be good if someone with insight could pull a figure out of the air :)

**Comment by hubertdeng123** [comment]
This is a good point. We could consider decreasing the system requirements for errors only self-hosted here. Will update here

**Comment by romanstingler** [comment]
good luck with that, after over 20 min uptime with 32gb ram the python3 stuff is still just congesting everything. 
![Image](https://github.com/user-attachments/assets/39fe9e84-2abe-4d22-9fc0-8d42a7839d85)

**Comment by aldy505** [comment]
I'm currently trying to put this on the self-hosted docs, and can't think any other idea: I suppose the RAM requirements can't be lowered even for errors-only, since Kafka and ClickHouse would use all the RAM available. The only solution would be removing either Kafka or ClickHouse, or.. suggesting the users to use external services.

**Comment by bc-sentry** [comment]
The RAM requirements are best-effort recommendation.  Trimming the configuration is doable, but I don't think we should try and document requirements for this type of change.

**Comment by azimuthdeveloper** [comment]
They're not a best effort recommendation though are they, because you can't start the containers unless you have the amount of ram required?

**Comment by bc-sentry** [comment]
I'm just saying that we wouldn't specify requirements for the different configurations mentioned at https://develop.sentry.dev/self-hosted/#configuration-topics.
