### ISSUE TITLE
Duplicated release

### ISSUE THREAD

**Issue by moroine** [getsentry/self-hosted#3359]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

I have a repository https://github.com/mission-apprentissage/api-apprentissage/actions/runs/11122789320/job/30904805111 which is failing when I try to create a release via sentry. 

![Image](https://github.com/user-attachments/assets/faa1325d-1b76-43d4-8df0-4598e1a63def)

I cannot find out the eventId in my sentry to have better info about the issue.

Looks like the release is duplicated. ![Image](https://github.com/user-attachments/assets/a505a1cd-712b-4e6d-ab5b-6a5864b821d1)

And here is what I have when I try to click on view in one of them ![Image](https://github.com/user-attachments/assets/908db21b-85ec-4f23-88af-a3b42a366ba9)

### Expected Result

Being able to prevent duplicated release, or at least being able to remove duplicated release.

### Actual Result

Releases are duplicated and cannot be used

### Product Area

Releases

### Version

24.7.1

**Comment by bc-sentry** [comment]
Could you please provide the server-side logs for the request that returned the HTTP 500?  Thank you.

**Comment by moroine** [comment]
Sorry I don't have the logs anymore. I tried to reproduce by executing the sentry create-release again but it seems to work. Also accessing the Release page on the UI doesn't throw an error anymore.

That's strange as I'm still on 24.7.1

**Comment by bc-sentry** [comment]
If it reoccurs, please resubmit an issue.  Thank you.
