### ISSUE TITLE
Proguards not downloading

### ISSUE THREAD

**Issue by Meraj** [getsentry/self-hosted#3362]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

- upload a proguard file using sentry-cli or event android studio
- try to download the proguard from sentry dashboard

### Expected Result

- download proguard files successfully

### Actual Result

proguard file not downloading, it seems that there is some issue with EOF

when sending curl:

curl: (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)

### Product Area

APIs

### Version

24.9.0

**Comment by bc-sentry** [comment]
Could you please retry this with 24.11?  If it still occurs, could you please provide the detailed error log?  Thank you.

**Comment by Meraj** [comment]
Hi, I did some debugging and found that each file contains multiple FileBlob instances, which exceed the actual file size and prevent reaching the end-of-file (EOF) condition. It turns out the issue was related to my database sequence, not a bug from Sentry.
