### ISSUE TITLE
Self-hosted CSRF verification failed and troubleshooting method not work

### ISSUE THREAD

**Issue by hawkiiii** [getsentry/self-hosted#3367]
### Self-Hosted Version

24.8.0

### CPU Architecture

x86_64

### Docker Version

24.0.7

### Docker Compose Version

2.23.3

### Steps to Reproduce

Follow the self-hosted setup docs, login in and return the csrf failed page.
Try the following section and it doesnt work.
[CSRF verification failed](https://develop.sentry.dev/self-hosted/troubleshooting/#csrf-verification-failed)

### Expected Result

successful login.

### Actual Result

![Image](https://github.com/user-attachments/assets/eed240c7-2833-4448-83e6-8c8cdbb446d9)![Image](https://github.com/user-attachments/assets/e4284b67-91a9-470f-9883-89686d1d881b)

**Comment by aldy505** [comment]
What's being defined on your `CSRF_TRUSTED_ORIGINS` array?

Also, after changing the value, have you re-run `./install.sh`?
