### ISSUE TITLE
Sentry/react: Cannot push Error to Sentry from React Project

### ISSUE THREAD

**Issue by Sotatek-AnhNguyen32** [getsentry/self-hosted#3371]
### Is there an existing issue for this?

- [x] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [x] I have reviewed the documentation https://docs.sentry.io/
- [x] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Self-hosted/on-premise

### Which SDK are you using?

@sentry/react

### SDK Version

8.33.1

### Framework Version

"react": "^18.3.1"

### Reproduction Example/SDK Setup

```js
Sentry.init({
dsn: "https://key@host:port/projectId>, // Copy from Client DSN
integrations: [
Sentry.browserTracingIntegration(),
],
enabled: true,

debug: true,
// Performance Monitoring
tracesSampleRate: 1.0, // Capture 100% of the transactions
// Set 'tracePropagationTargets' to control for which URLs distributed tracing should be enabled
tracePropagationTargets: ["localhost", /^https:\/\/yourserver.io\/api/],
});
```

### Steps to Reproduce

1. Creating a project sentry from my self hosted domain like: `sentry.<host>.com:<port>`
2. Init Sentry & throw some Error in project
3. Check Issue tab on Error

### Expected Result

![Image](https://github.com/user-attachments/assets/947e3245-4a8e-431f-bec0-17f352cac9a9)
- There is no error on Issue tab, but still have transactions on Dashboard

### Actual Result

![Image](https://github.com/user-attachments/assets/6c38cb1c-b5cb-4219-b45c-6e4cc77f6b10)
- I also test the same step with my own SaaS sentry, it worked. What difference between SaaS and Self hosted?

**Comment by Lms24** [comment]
Hey, I transferred your issue to the Sentry self-hosted repo and asked internally if someone can help you debug this further. Unfortunately, I don't have much context around self-hosted.

**Comment by Lms24** [comment]
Actually, one more question: Which self-hosted version are you using?

**Comment by Sotatek-AnhNguyen32** [comment]
`Actually, one more question: Which self-hosted version are you using?` 
-> I have to ask the Admin. I'd like to ask if the filter below is the cause of this issue?
![Image](https://github.com/user-attachments/assets/b44d34c1-b4e0-484f-8c8a-62b8673bd773)

**Comment by mydea** [comment]
On this "Inbound Filters" page, above the section you screen-shotted, you should be able to see the number of events that are ingested, and with it how many are dropped. If you see in that chart that events are dropped server-side, then some kind of inbound filter or similar is probably responsible for this, yes.
