### ISSUE TITLE
set_tag allows any type of tag to be set

### ISSUE THREAD

**Issue by vanschelven** [getsentry/self-hosted#3374]
### How do you use Sentry?

Self-hosted/on-premise

### Version

2.15.0

### Steps to Reproduce

I set a non-string tag using `set_tag`

### Expected Result

I expected this to be converted to a string, or raise an error

### Actual Result

The actual non-string (an int in this case) was sent to the server, where it cannot be dealt with.

**Comment by vanschelven** [comment]
Given the Robustness principle ("be conservative in what you do, be liberal in what you accept from others"), the linked code from the relay would implement the "liberal" part. This issue is about the other half of that saying though (and for that reason should IMHO be part of the sentry-python repo)

**Comment by aldy505** [comment]
> I believe what happens in self-hosted is that there is no relay and this int is sent straight to the backend. I will transfer this to getsentry/self-hosted and see what they have to say.

We do have relay on self-hosted and it's doing every conversion from that code.

@vanschelven What's your self-hosted version? Do you see any logs from relay rejecting your event?

**Comment by vanschelven** [comment]
My self-hosted version is [a drop-in replacement for Sentry](https://www.bugsink.com/); it accepts the event just fine, but does warn me about the event being not-up-to-spec

**Comment by aldy505** [comment]
Going to close this issue since this is not related to self-hosted and it's been here for a bit long.

**Comment by vanschelven** [comment]
it's not related to self-hosted sentry indeed, but it should have been transferred back to sentry-python... oh well
