### ISSUE TITLE
" Oops! Something went wrong" sentry access issue

### ISSUE THREAD

**Issue by abdul-devops01** [getsentry/self-hosted#3381]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### What are you trying to accomplish?

Trying to log into sentry

### How are you getting stuck?

We have been using sentry selfhosted for a while now, I tried integrating slack to sentry and I needed to make modifications to the config.yml file according to sentry documentation, after making required documentation, I tried running the `./insall.sh` to rebuild and make changes but I got stuck with the issue of docker could not pull images because of authorization issues and I needed to run docker login, so I saw a solution online to delete sentry self hosted directory and install from scratch which I did, but all previous volumes were still existing, so I reinstalled and everything was file but on trying to accesses sentry I got the error;
```
Oops! Something went wrong
It looks like you've hit an issue in our server API. Don't worry though! We use Sentry to monitor Sentry and it's likely we're already looking into this!

If you're daring, you may want to try the following:

Give it a few seconds and reload the page.
If all else fails, [contact us](https://github.com/getsentry/sentry/issues/new/choose) with more details.

```

and the only error I am getting is from the nginx sentry, all other containers are running perfectly fine

`172.24.0.1 - - [12/Oct/2024:07:23:06 +0000] "GET /saml/metadata/sentry/ HTTP/1.1" 500 7700 "https://sentry.makerble.org/saml/metadata/sentry/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" "20.235.244.24"`

### Where in the product are you?

Sign In

### Link

https://sentry.makerble.org

**Comment by bijancot** [comment]
Hi, Can you share here what version that you used? and it would be great if possible share your tables `sentry_team` columns ?
