### ISSUE TITLE
symbolicator stops working after installation

### ISSUE THREAD

**Issue by maxpain** [getsentry/self-hosted#3386]
### Self-Hosted Version

24.10.0

### CPU Architecture

x84_64

### Docker Version

27.3.1

### Docker Compose Version

2.29.7

### Steps to Reproduce

The `sentry-self-hosted-symbolicator-1` container stops sometime after installation. I have to spin it up again. After this manual action, everything works fine.

![Image](https://github.com/user-attachments/assets/d5b13b37-a77b-4490-b3fc-83a783130770)

### Expected Result

`sentry-self-hosted-symbolicator-1` container should not stop

### Actual Result

`sentry-self-hosted-symbolicator-1` stops after some time after installation.

**Comment by bijancot** [comment]
Hi Maxpain, what's the log said ? please share `sentry-self-hosted-symbolicator-1`  logs 

Cheers!

**Comment by maxpain** [comment]
@bijancot Hello!

Nothing:
![Image](https://github.com/user-attachments/assets/cd7ea1fc-aeeb-4102-87e4-9b09b7c322af)

**Comment by maxpain** [comment]
I have to start it manually every time after maintenance/sentry upgrade/etc.

**Comment by BYK** [comment]
@maxpain that doesn't make much sense, can you try this for logs please: https://develop.sentry.dev/self-hosted/troubleshooting/#general

**Comment by BYK** [comment]
Also, if you search for exit code `137` you'd see the following:

>Exit code 137 is an error that indicates a process was terminated due to a lack of memory or a failed health check

So I'd make sure your system has enough memory.

**Comment by maxpain** [comment]
> So I'd make sure your system has enough memory.

I have 128GB of memory, so no problems here.

**Comment by BYK** [comment]
@maxpain we'd still appreciate logs.

Also, is that memory available to your Docker? (sometimes they run in VMs etc, hence me asking)
