### ISSUE TITLE
Auto-cleaning does not work

### ISSUE THREAD

**Issue by sasha-sup** [getsentry/self-hosted#3388]
### Self-Hosted Version

24.9.0

### CPU Architecture

x86_64

### Docker Version

24.0.2

### Docker Compose Version

2.29.7

### Steps to Reproduce

1.  Check how much space is taken up by sentry-data docker volume:
```
du -h --max-depth=1 /var/lib/docker/volumes/ | grep sentry-data 
135G	/var/lib/docker/volumes/sentry-data
```
2. Manualy run cleanup job:
```
docker exec -ti sentry-worker-1 sentry cleanup --days 90
Removing expired values for LostPasswordHash
Removing expired values for OrganizationMember
Removing expired values for ApiGrant
Removing expired values for ApiToken
Removing expired files associated with ExportedData
Removing old NodeStore values
Running bulk query deletes in BULK_QUERY_DELETES
Removing UserReport for days=90 project=*
Removing GroupEmailThread for days=90 project=*
Running bulk deletes in DELETES
Removing EventAttachment for days=90 project=*
Removing ReplayRecordingSegment for days=90 project=*
Removing ArtifactBundle for days=90 project=*
Removing MonitorCheckIn for days=90 project=*
Removing GroupRuleStatus for days=90 project=*
Removing RuleFireHistory for days=90 project=*
Preparing DELETES_BY_PROJECT context
Running bulk deletes in DELETES_BY_PROJECT
Removing Group for days=90 project=1
Removing ProjectDebugFile for days=90 project=1
Removing Group for days=90 project=2
Removing ProjectDebugFile for days=90 project=2
Removing Group for days=90 project=3
Removing ProjectDebugFile for days=90 project=3
Cleaning up unused FileBlob references
File Blobs: 100% |#                                                                    | ETA:  --:--:--
```
3. Check disk usage again
```
du -h --max-depth=1 /var/lib/docker/volumes/ | grep sentry-data 
135G	/var/lib/docker/volumes/sentry-data
```

### Expected Result

I expect the sentry-data size to decrease, but it does not. How to sort this out? 

### Actual Result

```
du -h --max-depth=1 /var/lib/docker/volumes/ | grep sentry-data 
135G	/var/lib/docker/volumes/sentry-data
```

**Comment by bijancot** [comment]
hi, did you already try to run cleanup process manually? and could you check retention period ad .env file?

Cheers!

**Comment by sasha-sup** [comment]
> hi, did you already try to run cleanup process manually? and could you check retention period ad .env file?
> 
> Cheers!
Hello.
Yes, I ran the cleanup manually. 
retention 14 days

**Comment by aldy505** [comment]
If you don't encounter any exception when running the cleanup command, then the auto-cleaning _does_ work. The remaining 135GB on your `sentry-data` contains just attachments, sourcemaps, and session replays. You might want to consider moving that to a blob storage (S3 or GCS), see the docs here https://develop.sentry.dev/self-hosted/experimental/external-storage/#sentry

**Comment by sasha-sup** [comment]
Hi. I reinstalled centri.
Now the disk space has gone back to 0. 
I checked the autoclean logs, yes. it works. except the space is not freeing up....

> If you don't encounter any exception when running the cleanup command, then the auto-cleaning _does_ work. The remaining 135GB on your `sentry-data` contains just attachments, sourcemaps, and session replays. You might want to consider moving that to a blob storage (S3 or GCS), see the docs here https://develop.sentry.dev/self-hosted/experimental/external-storage/#sentry

**Comment by csvan** [comment]
@sasha-sup autoclean does not remove replays and the like, you need to do so manually. You could for example add the following cronjob (change 30 to something else depending your retention period:

```
find /var/lib/docker/volumes/sentry-data/ -type f -mtime +30 -delete
```

**Comment by sasha-sup** [comment]
It's a barbaric method :) 

> [@sasha-sup](https://github.com/sasha-sup) autoclean does not remove replays and the like, you need to do so manually. You could for example add the following cronjob (change 30 to something else depending your retention period:
> 
> ```
> find /var/lib/docker/volumes/sentry-data/ -type f -mtime +30 -delete
> ```

**Comment by csvan** [comment]
Barbaric but efficient ;)
