### ISSUE TITLE
missing new breadcrumbs layout

### ISSUE THREAD

**Issue by farfromrefug** [getsentry/self-hosted#3392]
### Self-Hosted Version

24.10.0

### CPU Architecture

x86_64

### Docker Version

20.10.3

### Docker Compose Version

20.19.0

### Steps to Reproduce

install and open an issue

I was expecting with 24.10.0 to get the new breadcrumbs layout released in august https://sentry.io/changelog/improved-breadcrumbs-on-issues.

But i still get the old layout. Is there any setting to enable?

### Expected Result

new layout

### Actual Result

old layout

**Comment by farfromrefug** [comment]
@aldy505 thanks for your fast answer. I tried to add:
```
SENTRY_FEATURES["organizations:issue-details-streamline"]=True
SENTRY_FEATURES["organizations:new-timeline-ui"]=True
```
to my `sentry/sentry.conf.py` and install  again but it did not work. I also looked in early features but it was not there.

**Comment by aldy505** [comment]
Looping in @roggenkemper and @leeandher, perhaps we're missing a feature flag to make this return `true`? https://github.com/getsentry/sentry/blob/89fd57e27725a68956b3514f136fd9511724402a/static/app/components/timeline/utils.tsx#L4-L15

The `new-timeline-ui` doesn't exists on the temporary feature flag manager as well, so I know I'm definitely missing something. https://github.com/getsentry/sentry/blob/master/src/sentry/features/temporary.py

**Comment by leeandher** [comment]
Apologies for letting this fall through the cracks, but as of https://github.com/getsentry/sentry/pull/80025 this should be addressed. If not please reopen/reply!
