### ISSUE TITLE
uWSGI listen queue of socket "127.0.0.1:39995" (fd: 3) full !!! (501/500) ***

### ISSUE THREAD

**Issue by golimer** [getsentry/self-hosted#3404]
### Self-Hosted Version

23.8.0

### CPU Architecture

x64

### Docker Version

27.1.1

### Docker Compose Version

1.29.2

### Steps to Reproduce

not sure how to replicate happening randomaly 

### Expected Result

any idea how to solve this problem and what cause is ?

### Actual Result

web container unhealthy  

Mon Oct 28 15:51:16 2024 - *** uWSGI listen queue of socket "127.0.0.1:39995" (fd: 3) full !!! (501/500) ***
Mon Oct 28 15:51:17 2024 - *** uWSGI listen queue of socket "127.0.0.1:39995" (fd: 3) full !!! (501/500) ***
Mon Oct 28 15:51:18 2024 - *** uWSGI listen queue of socket "127.0.0.1:39995" (fd: 3) full !!! (501/500) ***
Mon Oct 28 15:51:19 2024 - *** uWSGI listen queue of socket "127.0.0.1:39995" (fd: 3) full !!! (501/500) ***
Mon Oct 28 15:51:20 2024 - *** uWSGI listen queue of socket "127.0.0.1:39995" (fd: 3) full !!! (501/500) ***
Mon Oct 28 15:51:21 2024 - *** uWSGI listen queue of socket "127.0.0.1:39995" (fd: 3) full !!! (501/500) ***
Mon Oct 28 15:51:22 2024 - *** uWSGI listen queue of socket "127.0.0.1:39995" (fd: 3) full !!! (501/500) ***
Mon Oct 28 15:51:23 2024 - *** uWSGI listen queue of socket "127.0.0.1:39995" (fd: 3) full !!! (501/500) ***
Mon Oct 28 15:51:24 2024 - *** uWSGI listen queue of socket "127.0.0.1:39995" (fd: 3) full !!! (501/500) ***
Mon Oct 28 15:51:25 2024 - *** uWSGI listen queue of socket "127.0.0.1:39995" (fd: 3) full !!! (501/500) ***
Mon Oct 28 15:51:26 2024 - *** uWSGI listen queue of socket "127.0.0.1:39995" (fd: 3) full !!! (501/500) ***
Mon Oct 28 15:51:27 2024 - *** uWSGI listen queue of socket "127.0.0.1:39995" (fd: 3) full !!! (501/500) ***
Mon Oct 28 15:51:28 2024 - *** uWSGI listen queue of socket "127.0.0.1:39995" (fd: 3) full !!! (501/500) ***
Mon Oct 28 15:51:29 2024 - *** uWSGI listen queue of socket "127.0.0.1:39995" (fd: 3) full !!! (501/500) ***
Mon Oct 28 15:51:31 2024 - *** uWSGI listen queue of socket "127.0.0.1:39995" (fd: 3) full !!! (501/500) ***
Mon Oct 28 15:51:32 2024 - *** uWSGI listen queue of socket "127.0.0.1:39995" (fd: 3) full !!! (501/500) ***
Mon Oct 28 15:51:33 2024 - *** uWSGI listen queue of socket "127.0.0.1:39995" (fd: 3) full !!! (501/500) ***

**Comment by aldy505** [comment]
See this stackoverflow answer https://stackoverflow.com/a/56861049/3153224

You can learn more about `somaxconn` here: https://serverfault.com/questions/518862/will-increasing-net-core-somaxconn-make-a-difference

**Comment by BYK** [comment]
I'd also try upgrading your instance as we had multiple uWSGI upgrades which may help.

**Comment by golimer** [comment]
well i did all mentioned before posting here .....

**Comment by BYK** [comment]
@golimer you reported using Sentry version 23.8 and the latest one out is 24.10 so I did not expect you to tried upgrading your instance. Is that the case?

**Comment by golimer** [comment]
OMG just now saw my version 24.8.0 🤦
