### ISSUE TITLE
can not integration github

### ISSUE THREAD

**Issue by wangjdecode** [getsentry/self-hosted#3405]
### Problem Statement

I'm trying to install github integration
![Image](https://github.com/user-attachments/assets/830e3056-6bc9-4be3-a1b6-0d0f040c20cf)

but when i click the install button, opening a window and shows a 404 page of github.
![Image](https://github.com/user-attachments/assets/db52a8a6-bcd5-447a-bcc9-5d3e617fc10a)

please help

**Comment by wangjdecode** [comment]
then i find a solution there https://github.com/getsentry/sentry/issues/30865. but after i made my own github app, it still shows the 404 page.
![Image](https://github.com/user-attachments/assets/59d0988b-036a-4e3f-830e-a99b00ccb06c)

**Comment by aldy505** [comment]
I believe this has been [asked and resolved on Discord](https://discord.com/channels/621778831602221064/796028405833007104/1301017158091935744) since there are no more response.
