### ISSUE TITLE
I cannot install with v24.10.0

### ISSUE THREAD

**Issue by Damon99999** [getsentry/self-hosted#3407]
### Self-Hosted Version

v24.10.0

### CPU Architecture

x86-64

### Docker Version

v27.3.1

### Docker Compose Version

v2.29.7

### Steps to Reproduce
just run sudo ./install.sh
 
### Expected Result

It can install completely, the report seems that i have network problems,but it's not, I'm in HK and also i even tried to use the proxy of America but it was also failed as the same
I also tried to access this url "https://registry-1.docker.io/v2/library/debian/manifests/bookworm-slim" through Chrome
it showed that: {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"library/debian","Action":"pull"}]}]}

### Actual Result

<pre>[sudo] password for lcm: 
▶ Parsing command line ...

▶ Detecting Docker platform
Detected Docker platform is linux/amd64

▶ Initializing Docker Compose ...

▶ Setting up error handling ...
#0 building with &quot;default&quot; instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 292B done
#1 DONE 0.0s

#2 [internal] load metadata for docker.io/library/debian:bookworm-slim
#2 ERROR: failed to do request: Head &quot;https://registry-1.docker.io/v2/library/debian/manifests/bookworm-slim&quot;: dial tcp 162.125.17.131:443: i/o timeout
------
 &gt; [internal] load metadata for docker.io/library/debian:bookworm-slim:
------
Dockerfile:1
--------------------
   1 | &gt;&gt;&gt; FROM debian:bookworm-slim
   2 |     
   3 |     LABEL MAINTAINER=&quot;oss@sentry.io&quot;
--------------------
ERROR: failed to solve: debian:bookworm-slim: failed to resolve source metadata for docker.io/library/debian:bookworm-slim: failed to do request: Head &quot;https://registry-1.docker.io/v2/library/debian/manifests/bookworm-slim&quot;: dial tcp 162.125.17.131:443: i/o timeout</pre>

**Comment by csvan** [comment]
Looks like a network error on your end, check firewall settings and eventual company proxy settings

**Comment by BYK** [comment]
Closing as this is not something we can fix on our end. You need to check your network and Docker Hub access.

**Comment by Damon99999** [comment]
thanks all
