### ISSUE TITLE
failed to solve: process "/bin/sh -c apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*" did not complete successfully: exit code: 100

### ISSUE THREAD

**Issue by hezhilong5211** [getsentry/self-hosted#3409]
### Problem Statement

![Image](https://github.com/user-attachments/assets/7f263ec3-b915-4c45-9ce2-78f76650a116)

### Solution Brainstorm

docker 运行 failed to solve: process "/bin/sh -c apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*“ 会出现GPG error 和 404的情况  已经换了阿里云镜像

**Comment by aldy505** [comment]
The only possible reason was there is something that intercept your request from the Linux machine to `http://dev.debian.org` as seen on your screenshot. Make sure that you have properly configured your network proxy settings.

**Comment by Sheepeer** [comment]
Met the same issue, have u solved it?

**Comment by Sheepeer** [comment]
My error log:
![Image](https://github.com/user-attachments/assets/a3eb2768-5b3a-4312-9e44-9e9997d0c2dd)

**Comment by aldy505** [comment]
> Met the same issue, have u solved it?

@Sheepeer make sure your network proxy is properly set up. It's a networking issue, not specific to Sentry self-hosted.

**Comment by Sheepeer** [comment]
> > Met the same issue, have u solved it?
> 
> [@Sheepeer](https://github.com/Sheepeer) make sure your network proxy is properly set up. It's a networking issue, not specific to Sentry self-hosted.

Thanks for your reply. But I feel confused, the error log shows `Connection timed out [IP: 151.101.66.132 80]`, however I ran `telnet 151.101.66.132 80` and it return connected. Is there any ideas?
![Image](https://github.com/user-attachments/assets/2b27d838-7641-4ed9-86b1-b1bdcdc68e34)

**Comment by BYK** [comment]
@Sheepeer very likely that your connection is getting intercepted. Being able to telnet to port 80 does not prove that it works as this system is trying to connect to port `443` with HTTPS (TLS).
