### ISSUE TITLE
Widget Filter not working with issue.priority

### ISSUE THREAD

**Issue by Dominic-BW** [getsentry/self-hosted#3412]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

1. Create a Dashboard
2. Create a Widget
3. Go to "Filter your results"
4. Type in "issue.priority:medium" as a filter

### Expected Result

Only Issues with priority medium are shown

### Actual Result

No issues are displayed, and also the auto completion does not recognize issue.priority

### Product Area

Dashboards

### Version

24.10.0

**Comment by bc-sentry** [comment]
On the dashboard edit widget page, in "Choose your dataset", have you chosen Issues?

**Comment by Dominic-BW** [comment]
No I have chosen “Errors and Transactions”, when I choose "issues" I can filter for  issues.priority values, but then I cannot display the properties of errors :)
But then it seems to me this is as designed and it would be more of a feature request to be able to also filter Errors with the priority value as well.

@bc-sentry Thanks for you help.

**Comment by bc-sentry** [comment]
Correct.  Glad to help.
