### ISSUE TITLE
Members unable to join teams via sentry UI after upgrade

### ISSUE THREAD

**Issue by sree-warrier** [getsentry/self-hosted#3423]
### Self-Hosted Version

24.2.0

### CPU Architecture

x86_64

### Docker Version

na

### Docker Compose Version

na

### Steps to Reproduce

Hi Team,

We did and upgrade with our self-hosted sentry from `23.11.2` to `24.2.0`. We haven't seen any anomalies except this issue. Please were unable to join another teams. We have enable this setting at sentry level, which means members should be able to join any team, which they were able to do in version `23.11.2`
![Image](https://github.com/user-attachments/assets/5738da5a-958e-4e7b-9ab0-7dde02f9d5a6)

But after upgrade members were not able to join any new teams, they were seeing this while going to teams list.

![Image](https://github.com/user-attachments/assets/da7e5294-3cfc-4ff0-bc29-435c7b68c82f)

Is this a bug in `24.2.0` version or any other setting we need to enable it ?

Note:  Same issue seen for leaving the team also.

### Expected Result

Members should be able to join and leave any team

### Actual Result

Members should be able to join and leave any team

**Comment by bc-sentry** [comment]
Please check the logs and see if you see an error while loading the teams page.
