### ISSUE TITLE
support SENTRY_ADMIN_ONLY_PROJECT_CREATION  env ?

### ISSUE THREAD

**Issue by vaynevayne** [getsentry/self-hosted#3425]
### Problem Statement

i  want add SENTRY_ADMIN_ONLY_PROJECT_CREATION to .env.custom
dose it support?

**Comment by hubertdeng123** [comment]
You can add any env variable you would like. Although, if you'd like to only allow sentry admins to create projects that I believe should be a setting in your sentry installation

**Comment by vaynevayne** [comment]
Do you know which setting item this is in the installation? @hubertdeng123

**Comment by aldy505** [comment]
It is not available from the command line. You should configure it from the UI. See the documentation about roles and permission here: https://docs.sentry.io/organization/membership/#organization-level-roles

**Comment by vaynevayne** [comment]
I read the documentation, still do not know where to configure, can you tell me which page in the ui which button can be configured? Simple plea. Let's not go around. Is that OK? Thank you.
@aldy505

**Comment by aldy505** [comment]
The page you're referring to is in the link I showed you. Got to Settings -> Members.  https://docs.sentry.io/organization/membership/#organization-level-roles

**Comment by vaynevayne** [comment]
![Image](https://github.com/user-attachments/assets/23e38044-1550-44f8-811a-66dc06e7ec08)

hi @aldy505   Didn't find any place to modify the configuration  This page is read-only

**Comment by hubertdeng123** [comment]
Hi @vaynevayne. This feature you're requesting is not really something we would want. However, you can disable members of your Sentry instance from creating projects in Organization Settings -> Membership section. Going to close this as I hope this will solve the issue you're facing.
