### ISSUE TITLE
How to set `HttpOnly` flag to true on cookie `sc`

### ISSUE THREAD

**Issue by madilekci-avena** [getsentry/self-hosted#3426]
### Problem Statement

I am having issues with one of the cookies sentry uses called `sc`. I need to set `httpOnly` flag for the cooke to `true` but couldn't find a way to control it. 
`Name: sc, Domain: sentry.retracedev.com, HttpOnly: , Secure: ✓, SameSite: Lax`

All I could found was this suggestion but these were already set as suggested in my app. Any suggestions on how to resolve this ? 

> Are you using a reverse SSL proxy? You will need to enable a few flags in `sentry.conf.py`
> 
> 
> 
> ```
> 
> SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
> 
> SESSION_COOKIE_SECURE = True
> 
> CSRF_COOKIE_SECURE = True
> 
> SOCIAL_AUTH_REDIRECT_IS_HTTPS = True
> 
> ``` 

 _Originally posted by @hubertdeng123 in [#2017](https://github.com/getsentry/self-hosted/issues/2017#issuecomment-1461106675)_

**Comment by hubertdeng123** [comment]
Can you provide more information? It is difficult to follow along with what you'd like to do
