### ISSUE TITLE
Release 24.12.0

### ISSUE THREAD

**Issue by bc-sentry** [getsentry/self-hosted#3431]
### Body

[previous 24.11.1](https://github.com/getsentry/self-hosted/issues/3445) | ***24.12.0*** | [next 24.13.0](https://github.com/getsentry/self-hosted/issues)

- [x] Release all components (_replace items with [publish repo issue links](https://github.com/getsentry/publish/issues)_).
  - [x] https://github.com/getsentry/publish/issues/4749
  - [x] https://github.com/getsentry/publish/issues/4750
  - [x] https://github.com/getsentry/publish/issues/4751
  - [x] https://github.com/getsentry/publish/issues/4752
  - [x] https://github.com/getsentry/publish/issues/4753
- [x] Release self-hosted.
  - [x] https://github.com/getsentry/publish/issues/4754
  - [x] Check to make sure the new release branch in self-hosted includes the appropriate CalVer images.
  - [x] Accept (publish) the release.
  - [x] Edit [release notes](https://github.com/getsentry/self-hosted/releases).
- [x] Follow up.
  - [x] [Create the next release issue](https://github.com/getsentry/self-hosted/issues/new?assignees=&labels=&projects=&template=release.yml) and link it from this one.
    - _replace with link_
  - [x] Update the [release issue template](https://github.com/getsentry/self-hosted/blob/master/.github/ISSUE_TEMPLATE/release.yml).
  - [x] Create a PR to update relocation release tests to add the new version.
    - _replace with link_

**Comment by hubertdeng123** [comment]
Looks like this was not completed yet, so reopening

**Comment by aldy505** [comment]
@hubertdeng123 you might want to fill in the changelog.

**Comment by hubertdeng123** [comment]
@aldy505 For self-hosted, there haven't been any changes since 24.11.2
