### ISSUE TITLE
The centos install.sh execution fails

### ISSUE THREAD

**Issue by m13886695261** [getsentry/self-hosted#3435]
### Self-Hosted Version

24.11.0

### CPU Architecture

x86_64

### Docker Version

25.0.5

### Docker Compose Version

2.30.3

### Steps to Reproduce

./install.sh

### Expected Result

succeed

### Actual Result

![Image](https://github.com/user-attachments/assets/b3015624-3af7-4c19-b1a3-d0b4f62bd18f)
This is my error log，My linux version is CentOS Linux release 7.3.1611 (Core)
It's been bothering me for two days. Can you help me look at this bug

**Comment by aldy505** [comment]
This is most likely a Docker issue instead of Sentry's. What I'd suggest is to use newer Linux variant that's best compatible with Docker.
