### ISSUE TITLE
Multiple 301 redirects of JS files because of NOSNIFF header and lack of MIME-TYPE

### ISSUE THREAD

**Issue by rafal-ksiazek-rmtcfm-com** [getsentry/self-hosted#3470]
### Self-Hosted Version

24.11.2

### CPU Architecture

x84_65

### Docker Version

24.0.5

### Docker Compose Version

2.3.3

### Machine Specification

- [x] My system meets the minimum system requirements of Sentry

### Steps to Reproduce

1. git clone
2. ./install.sh
3. update sentry/config.yml (mail configuration and system.url-prefix)
6. docker-compose up -d

### Expected Result

Member should be able to re register by invite link. 

### Actual Result

A lot of errors in console:

Refused to execute script from 'https://sentry.prpl.global/auth/login/sentry/' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

GET
https://sentry.prpl.global/_assets/chunks/vendors-node_modules_emotion_react_jsx-runtime_dist_emotion-react-jsx-runtime_browser_esm_js--1f88a8.38411c95843da6149a36.js
=> 301

GET
https://sentry.prpl.global/_assets/chunks/vendors-node_modules_moment-timezone_index_js-node_modules_query-string_index_js-node_modules-e4450d.3cc078efe71b1002e2ca.js
=> 301

GET 
https://sentry.prpl.global/_assets/chunks/app_bootstrap_initializeMain_tsx.79a2dbecf76d5c1bed86.js 
=> 301
https://sentry.prpl.global/_assets/chunks/app_bootstrap_initializeMain_tsx.79a2dbecf76d5c1bed86.js/ 
=> 302 FOUND - but there is no data

Even sending curl on the server:
curl -vvv  -H "Content-Type:text/javascript" 127.0.0.1:9000/_assets/chunks/app_bootstrap_index_tsx.225408d90295f81f55c23a.js
=> 301

You can login, and then all files are loaded. But member cannot register from invite link because of these errors.

**Comment by rafal-ksiazek-rmtcfm-com** [comment]
And because of these errors I cannot invite any member because they cannot register. 
Normally after login the site is working correctly...

**Comment by mohamedsamirspot** [comment]
i had similar issues 
i can't even to login
it continuously redirects me to to the login page again

**Comment by fabricebertheuil** [comment]
Bonjour, problème identique ici.

**Comment by anthony-launay** [comment]
Hi, same problem on our side

**Comment by rafal-ksiazek-rmtcfm-com** [comment]
I have moved to 24.10.0 - working without problems.

**Comment by mohamedsamirspot** [comment]
@rafal-ksiazek-rmtcfm-com  great
can you please provide us with the steps to go to version 24.10.0

**Comment by rafal-ksiazek-rmtcfm-com** [comment]
> [@rafal-ksiazek-rmtcfm-com](https://github.com/rafal-ksiazek-rmtcfm-com) great can you please provide us with the steps to go to version 24.10.0

I know solution but only with clearing the database:
```
docker-compose down --volumes
git checkout 24.10.0
./install.sh
docker-compose up -d
```

**Comment by mohamedsamirspot** [comment]
@rafal-ksiazek-rmtcfm-com This is a devastating solution, man. 😅😅 i hope they can give us a temp rollback way untill they fix the issue

**Comment by omarnoubair** [comment]
I'm facing the same issue, I tried to perform a downgrade, but I encountered a corrupted data error. Is this really the solution?

**Comment by netraagal** [comment]
Hello, I’m struggling with the same problem, and clearing the database is hardly a solution I wanna envisage

**Comment by aldy505** [comment]
Let's see, do you have 2FA enabled on the accounts?

If you do, does this solution solved the problem (although temporarily)? https://github.com/getsentry/self-hosted/issues/3473#issuecomment-2545899087

**Comment by GurvanVgx** [comment]
Hi, I'm facing the same issue, had to rollback and deactivate 2FA

**Comment by benoitPourtalet** [comment]
Hello, I have exactly the same problem.

**Comment by dgabrielson** [comment]
Same problem here - no 2FA whatsoever.

**Comment by BringerOD** [comment]
same issue

**Comment by BYK** [comment]
Confirmed that this is resolved with the latest Nginx patch in this repo so closing.

Will cut a patch release soon.
