### ISSUE TITLE
Cannot get past "Welcome to Sentry" page

### ISSUE THREAD

**Issue by drmrbrewer** [getsentry/self-hosted#3477]
### Self-Hosted Version

24.11.0

### CPU Architecture

aarch64

### Docker Version

27.4.0

### Docker Compose Version

2.31.0

### Machine Specification

- [x] My system meets the minimum system requirements of Sentry

### Steps to Reproduce

1. Follow [the docs](https://develop.sentry.dev/self-hosted/) to install Sentry
2. Open self-hosted Sentry page

### Expected Result

In the past, when I first open the self-hosted Sentry page I am directed to a setup page to enter some details, which in my case is already pre-filled because of the way I've scripted the install.

Now, I get to the "Welcome to Sentry" page:

![Image](https://github.com/user-attachments/assets/177e0030-210c-45ab-aa73-bc1365fdd83d)

And as expected all details are prefilled.  But when I click Continue, I see "Saving changes..." pop briefly then disappear... but I am not redirected to the dashboard.  All information is filled in, but it doesn't get off the Welcome page.

### Actual Result

From the `docker compose logs` when I press "Continue" button, I see the following:

	web-1                                           | 20:04:43 [INFO] sentry.superuser: superuser.request (url='http://sentry.mydomain.com/api/0/internal/options/?query=is:required' method='PUT' ip_address='121.123.88.142' user_id=1)
	web-1                                           | 20:04:43 [INFO] sentry: options.update (ip_address='121.123.88.142' user_id=1 option_key='system.url-prefix' option_value='https://sentry.mydomain.com')
	web-1                                           | 20:04:43 [INFO] sentry: options.update (ip_address='121.123.88.142' user_id=1 option_key='system.admin-email' option_value='sentry@mydomain.com')
	web-1                                           | 20:04:43 [WARNING] django.request: Bad Request: /api/0/internal/options/ (status_code=400 request=<WSGIRequest: PUT '/api/0/internal/options/?query=is:required'>)
	nginx-1                                         | 121.123.88.142 - - [18/Dec/2024:20:04:43 +0000] "PUT /api/0/internal/options/?query=is:required HTTP/1.1" 400 157 "https://sentry.mydomain.com/organizations/sentry/issues/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" "86.25.85.67, 121.123.88.142, 10.0.1.5"

**Comment by aldy505** [comment]
Are you experiencing something very similar to this? https://github.com/getsentry/self-hosted/issues/3186

**Comment by drmrbrewer** [comment]
@aldy505 I haven't looked into this in detail, but it does look similar, and the suggested workaround there (which is to comment out the `mail.use-ssl: false` line from `config.yml`) does seem to solve the problem.

**Comment by aldy505** [comment]
Great. I'm going to close this issue, feel free to open a new one when another problem arises.
