### ISSUE TITLE
How can I determine the proper value for TracesSampleRate? Roughly how many transactions should try to accept with based on the TracesSampleRate to avoid performance issues?

### ISSUE THREAD

**Issue by edgariscoding** [getsentry/self-hosted#3478]
### Problem Statement

Now I know this is a completely subjective question and the correct answer is "IT DEPENDS".

My issue is that I have no reference as to what I should try to shoot for. I have a fairly low powered Sentry server running on an Azure VM with the following specs:

```
16 core Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
32gig RAM
```

I enabled TracesSampleRate for our Sandbox environment and set it to 1.0 for 100% tracing. About 5-10 users use the Sandbox environment and somehow there was a huge spike on one day from 9-10am. This resulted in this:
<img width="1045" alt="Image" src="https://github.com/user-attachments/assets/7ea2ec08-b33d-43fe-97d5-88f54a2e7f45" />
<img width="461" alt="Image" src="https://github.com/user-attachments/assets/d1c610cc-4f49-4d62-b2b4-7a7547aa0bdc" />

I've prepared the TracesSampleRate to be 0.1 (10%) for our production environment. But we have thousands of users, if 100% of transactions generated by 5-10 users in a span of like 3 days are so many, I can imagine that even at 10%, thousands of users will flood our Sentry server.

Will Sentry automatically limit how many transactions it ingests or do I need to lower the rate to 0.01 as a precautionary measure based on my system specs?

Thanks!

**Comment by aldy505** [comment]
> Will Sentry automatically limit how many transactions it ingests or do I need to lower the rate to 0.01 as a precautionary measure based on my system specs?

No. I usually recommend people to set up their own rate limiter on their outmost reverse proxy. Some reverse proxy has a rate limiter middleware built in (like [Traefik does](https://doc.traefik.io/traefik/middlewares/http/ratelimit/)), Considering your CPU and RAM specification, things should be working well during high load. You will need to make sure that you have enough disk space to cater that high throughput events.

For comparison, this is my stats (I'm running 8 core Intel Xeon CPU + 16 GB of RAM on a on-premise VMware platform -- with event retention days of 14 days):
![Image](https://github.com/user-attachments/assets/d3131aec-0f57-4a13-aead-a0287de796cb)
![Image](https://github.com/user-attachments/assets/ea75149e-0752-40ed-9a40-3639cb5afe1b)


But with all that, yes, for production usecases, you might want to lower your traces sample rate. Setting it to `0.1` might be fine, but if you're experiencing bad things on your Sentry instance, you might want to go lower than that, setting it to `0.005` might not hurt. But you're just getting (probably) 0.005% of your observability data.

**Comment by edgariscoding** [comment]
Thanks, @aldy505, that gives me some reassurance. I'll keep a close eye on it tomorrow when we push to prod and change the values as needed if things go south.

**Comment by aldy505** [comment]
Good luck with your production release. Feel free to reply to this issue or create a new one when something comes up!

**Comment by edgariscoding** [comment]
@aldy505 So with TracesSampleRate set to 10%, I've gotten about 500K accepted transactions in the span of three hours after deployment to prod at 7am... and it'll only keep increasing throughout the day since our heaviest load is around 10-4pm.
<img width="1116" alt="Image" src="https://github.com/user-attachments/assets/d3f5f22c-773f-4b62-bbae-07ced89b1f9d" />

Server seems to be handling it fine for now
<img width="943" alt="Image" src="https://github.com/user-attachments/assets/c2ba5f1e-4521-45cd-9db1-b044cc4735dd" />


Guess I'll lower it to 0.5% (0.005) as you suggested and re-asses the value after a few days. I'll need to add a lot more storage, the storage allocated to Sentry's containers is currently 126gb and it jumped from 40% usage to 60% usage this morning.

**Comment by edgariscoding** [comment]
I should have known... there was an issue with our web.config transformation and it was being set to 1.0 on production. 

If anyone runs into a similar issue in the future... make sure your tracesSampleRate is properly reflected in production.
