### ISSUE TITLE
After privatization deployment, page error occurs

### ISSUE THREAD

**Issue by jiadaoyun** [getsentry/self-hosted#3485]
![Image](https://github.com/user-attachments/assets/27cc80b4-0cb1-415d-abe3-dece22cc761f)

Please help me find out why

**Comment by aldy505** [comment]
We cannot help you since you don't provide much information. Please recreate the issue by following the [Problem Report issue template](https://github.com/getsentry/self-hosted/issues/new?template=problem-report.yml).
