### ISSUE TITLE
Add Sentry error reporting to install.sh

### ISSUE THREAD

**Issue by BYK** [getsentry/self-hosted#740]
## Summary

`sentry-cli` has a Docker image and Bash signal trap support: https://docs.sentry.io/product/cli/send-event/#bash-hook

The two didn't play well together but now this can be overcome: https://github.com/getsentry/sentry-cli/pull/852

Hence, we should try this out and see if it is useful to catch unknown issues in the wild.

## Motivation

We rely on people to report issues with the install script and provide relevant logs along with that. This has worked okay so far but the process is very manual, cumbersome, and relies on the users reporting issues. Sentry was created to solve these issues to why not dog food?

**Comment by chadwhitacre** [comment]
@armenzg has a blog post coming out about how the Developer Productivity team did something very similar with our environment bootstrapping script. Inspo!

**Comment by chadwhitacre** [comment]
I'm going to reopen this because there are many more details we need to pay attention to in order to not piss off users with this change.

**Comment by chadwhitacre** [comment]
Sorry ... we've got https://github.com/getsentry/team-ospo/issues/36 as our meta ticket.
