### ISSUE TITLE
How to config SMTP Settings in `Sentry`?

### ISSUE THREAD

**Issue by agn-7** [getsentry/self-hosted#86]
How to config SMTP Settings in `Sentry`?

I set a configure own SMTP server mail in `onpremise/config.yml`, then I did:  

`sudo docker-compose up -d` (before that, I remove previous consider containers)   

but in sentry mail setting panel not appear my SMTP configs:
 [![sentry SMTP setting ][1]][1]

**Note**: I use [onpremise][2] sentry docker package.

What should I do?  

Thanks in advance.

  [1]: https://i.stack.imgur.com/kYNY2.jpg
  [2]: https://github.com/getsentry/onpremise

**Comment by agn-7** [comment]
what do I do with this link?!

**Comment by dcramer** [comment]
@agn-7 this isnt a support forum so please use an appropriate mechanism for question rather than the bug tracker

**Comment by baby5** [comment]
@agn-7 `docker-compose up --build -d cron web worker` just rebuild service

**Comment by agn-7** [comment]
[Here is the solution.](https://stackoverflow.com/a/51346278/3702377)

**Comment by Nemermel** [comment]
> [Here is the solution.](https://stackoverflow.com/a/51346278/3702377)

thx m8.

**Comment by BYK** [comment]
We also have this now: https://develop.sentry.dev/self-hosted/mail/
